dojo.provide("concord.chart.lib.themes.Desert");
dojo.require("concord.chart.lib.Theme");

(function(){
	//	notes: colors generated by moving in 30 degree increments around the hue circle,
	//		at 90% saturation, using a B value of 75 (HSB model).
	var dxc=concord.chart.lib;
	dxc.themes.Desert=new dxc.Theme({
		colors: [
			"#ffebd5",
			"#806544",
			"#fdc888",
			"#80766b",
			"#cda26e"
		]
	});
})();
