dojo.provide("concord.chart.lib.themes.Grasslands");
dojo.require("concord.chart.lib.Theme");

(function(){
	//	notes: colors generated by moving in 30 degree increments around the hue circle,
	//		at 90% saturation, using a B value of 75 (HSB model).
	var dxc=concord.chart.lib;
	dxc.themes.Grasslands=new dxc.Theme({
		colors: [
			"#70803a",
			"#dde574",
			"#788062",
			"#b1cc5d",
			"#eff2c2"
		]
	});
})();
