({	
	viewExpandedBtn: "Visualizar menos respostas",
	viewCollapsedBtn: "Visualizar ${0} mais respostas",
	placeholderMsg: "Digite sua mensagem aqui",
	sure: "Tem certeza de que deseja excluir este comentário?",
	exceed: "O comentário é muito longo.\n O comentário inserido excede o comprimento máximo permitido.\n Reduza-o para não mais do que ${0} caracteres e clique em Incluir.",
	remainLabelHint:"Seu comentário atingiu o limite de 500 caracteres.",
	tipsCommentField: "Digite um comentário para todos os editores ou para um editor",
	tipsRespondField: "Digite uma resposta para todos os editores ou para um",	
	resolveBtn: "Resolver",	
	replyBtn: "Responder",
	saveBtn: "Postar",
	deleteBtn: "Excluir",
	cancelBtn: "Cancelar",
	reopenBtn: "Abrir novamente",
	todayAt: "Hoje às ${time}",
	yesterdayAt: "Ontem às ${time}",
	dateAt: "${date} às ${time}",
	mentions: "Selecione um usuário para referência",
	noMentions: "Digitar espaço em branco para concluir a entrada",
	nocomments: "Não há nenhum comentário no documento '${0}'.",
	
	newComments:"Novos Comentários",
	mentiontomesomebody:"Alguém",
	mentiontome:"${0} mencionou você em um comentário",
	
	newcommentsnumber:"O número de comentário não lidos",
	jawsnewcommentsnumber: "O número de comentários não lidos é ",
	jawsnactivecommentsnumber: "O número de comentários ativos és ",
	
	activenum:"O número de comentários ativos",
	filterDesc:"Filtrar Comentários",
	menuallcomments:"Todos os Comentários",
	menutome: "@me",
	menubyme: "Por Mim",
	menuactive: "Ativo",
	menuresolved: "Resolvido",
	searchDesc: "Procurar Comentários",
	search: "Pesquisar",
	closeDesc: "Fechar Procura",
	clear: "Limpar",
	warnEnterKeywords: "Insira os termos de procura",
	nocommentstome: "Atualmente, não há nenhum comentário ou resposta com menção sobre mim no documento '${0}'.",
	nocommentsbyme: "Atualmente, não há nenhum comentário ou resposta escrito(a) por mim no documento '${0}'.",
	nocommentsar: "Atualmente, não há nenhum comentário na categoria '${0}' no documento '${1}'.",
	nosearchedcomments: "Atualmente, não há comentários ou respostas que contenham '${0}' na categoria '${1}' no documento '${2}'.",
	
	prevBtn: "Anterior",
	nextBtn: "Avançar",
	mentionHint:"Mostrando de ${0} a ${1} correspondências do total de ${2}",
		
	resolveFlag: "Comentários resolvidos",
	jawsCommentHint: "${authorname} postou o comentário ${timestamp}",
	jawsReplyHint: "${authorname} postou a resposta ${timestamp}",
	jawsContentHint: "O conteúdo é ${content}",
	jawsCommentStatusHint: "O status é ${status}",
	jawsCommentKeyHint: "É possível pressionar Enter ou a Barra de Espaço para acessar o documento para visualizar as linhas de comentários completas e resolver, responder ou excluir os comentários.",
	jawsMentionHint: "Widget de referência de docs. É possível pressionar a Seta para Cima ou a Seta para baixo para selecionar um usuário para referência",
	jawsMentionSelected: "Pressione Enter ou a Barra de Espaço para referência",
	commentDeletedMsg: "O comentário atual foi excluído por outro editor.",
	commentResolvedMsg: "O comentário atual foi resolvido.",
	warningCommentMsg: "Comentários feitos dentro de Arquvos para arquivos ${0} são suportados apenas on-line. A ligação de comentários será removida se uma nova versão for transferida por upload para edição.",
	orphanCommentTip: "A ligação do comentário foi removida nessa versão transferida por upload.",
	warningCommentName: "Aviso"
})

