({
	COLUMN: "Stĺpec",
	CLUSTERED_COLUMN: "Klastrovaný stĺpec",
	STACKED_COLUMN: "Navrstvený stĺpec",
	BAR:"Stĺpec",
	CLUSTERED_BAR:"Klastrovaný stĺpec",
	STACKED_BAR: "Navrstvený stĺpec",
	PIE:"Koláč",
	SLICE: "Výrez",
	AREA: "Plocha",
	STACKED_AREA: "Navrstvená plocha",
	LINE: "Čiara",
	STACKED_LINE: "Navrstvená čiara",
	MAKER_LINE: "Čiara so značkami",
	STACKED_MARKER_LINE: "Navrstvená čiara so značkami",
	SCATTER: "Rozptyl",
	SCATTER_MARKER_ONLY: "Rozptyl iba so značkami",
	SCATTER_MARKER_LINE_S: "Rozptyl s vyhladenými čiarami a značkami",
	SCATTER_LINE_S: "Rozptyl s vyhladenými čiarami", 
	SCATTER_MARKER_LINE_X: "Rozptyl s priamymi čiarami a značkami",
	SCATTER_LINE_X: "Rozptyl s priamymi čiarami",
	ERROR_INVALID_RANGE:"Neplatný rozsah údajov",
	TOO_MANY_POINTS: "Nemožno vytvoriť graf, ktorý má viac ako ${0} dátových bodov.",
	CHART_TYPES:"Typy grafu",
	DATA:"Údaje",
	DATA_RANGE:"Rozsah údajov",
	IN_ROWS:"Séria dát v riadkoch",
	IN_COLUMNS:"Séria dát v stĺpcoch",
	AUTO:"Automaticky"
})
