({
	alt			: "Alternatívny text",
	width		: "Šírka:",
	height		: "Výška:",
	cmUnit   : "cm",
	ptUnit 	 : "pt",
	inchUnit : "inch",
	inUnit   : "in",
	mmUnit 	 : "mm",
	
	inputWarning: "Zadajte kladné celé číslo s predvolenou jednotkou.",
	
	properties: "Vlastnosti",
	data: "Údaje",
	chart: "Graf",
	axis: "Os",
	series: "Séria",
	font: "Písmo",
	title: "Nadpis",
	legend: "Legenda",
	placement: "Umiestnenie",
	background: "Pozadie",
	plotarea: "Zobrazovaná oblasť",
	line : "Čiara",
	fill: "Výplň",
	border : "Okraj",
	labelfont: "Označenie",
	scale: "Mierka",
	minimum: "Minimum",
	maximum: "Maximum",
	majorunit: "Hlavná jednotka",
	minorunit: "Vedľajšia jednotka",
	smooth: "Hladký",
	marker: "Značky",
	markerfill: "Značka",
	enterTitle: "Tu zadajte nadpis",
	inputNumberWarning: "Zadajte číslo.",
	inputPosNumberWarning: "Zadajte kladné číslo.",
	maxMinWarning: "Maximálna hodnota musí byť väčšia ako minimálna hodnota",
	selectFontName: "Vybrať názov písma",
	selectFontSize: "Vybrať veľkosť písma",
	setBold: "Tučné písmo",
	setItalic: "Kurzíva",
	setFontColor: "Nastaviť farbu písma",
	setLegendPos: "Nastaviť umiestnenie legendy",
	setBackColor: "Nastaviť farbu pozadia grafu",
	setBorderWidth: "Nastaviť šírku okraja",
	setBorderColor: "Nastaviť farbu okraja",
	setPlotAreaColor: "Nastaviť farbu zobrazovanej oblasti",
	selectAxis: "Vybrať os",
	setLineWidth: "Nastaviť šírku čiary",
	setLineColor: "Nastaviť farbu čiary",
	selectSeries: "Vybrať série",
	setFillColor: "Nastaviť farbu výplne",
	setMarker: "Nastaviť značky",
	setSmooth: "Nastaviť hladkú čiaru",
	chartTitle: "Nadpis grafu",
	axisTitle: "Nadpis osi",
	
	ERR1: "Pole musí byť uzatvorené množinovými zátvorkami.",
	ERR3: "Reťazcové položky musia byť uzatvorené úvodzovkami.",
	ERR4: "Zadajte iba jeden rozsah.",
	ERR5: "Rozsah musí existovať.",
	ERR6: "Všetky rozsahy musia byť v rovnakom hárku.",
	ERR7: "Všetky rozsahy musia byť pre jeden riadok alebo stĺpec.",
	ERR9: "Vyžaduje sa hodnota série.",
	
	n	: "Žiadne",
	l	: "Vľavo",
	r	: "Vpravo",
	t	: "Hore",
	b   : "Dole",
	
	dataSeries:"Séria dát",
	label:"Názov série",
	xVal:"Hodnoty X série",
	yVal:"Hodnoty Y série",
	val:"Hodnoty série",
	cat:"Kategória",
		
	ltr: "Zľava doprava",
	rtl: "Sprava doľava",
	auto: "Kontextové",
	bidi_dir: "Smer",
	bidi_text_dir: "Smer textu"
})
