﻿/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        fileMenu: "ファイル",
        fileMenu_New: "新規",
        fileMenu_NewDocument: "文書",
        fileMenu_NewFromTemplate: "テンプレートから",
        fileMenu_NewDocumentfromTemplate: "テンプレートからの文書",
        fileMenu_NewPresentation: "プレゼンテーション",
        fileMenu_NewPresentationfromTemplate: "テンプレートからのプレゼンテーション",
        fileMenu_NewSpreadsheet: "スプレッドシート",
        fileMenu_NewSpreadsheetFromTemplate: "テンプレートからのスプレッドシート",
        fileMenu_Open: "開く",
        fileMenu_Import: "インポート...",
        //	fileMenu_Close: "Close",
        fileMenu_Discard: "直前のバージョンに戻す",
        fileMenu_ClearTrackChange: "変更マークの削除",
        fileMenu_SpreadsheetSettings: "文書ロケールの設定...",
        filemenu_revisionhistory: "改訂",
        fileMenu_Save: "保存",
        fileMenu_SaveAs: "コピー...",
        fileMenu_AutoPublish: "自動的に公開",
        fileMenu_AutoCheckIn: "自動的にチェックイン",
        fileMenu_PublishVersion: "今すぐ公開",
        fileMenu_AutoPublish2: "リポジトリーに自動保存",
        //	fileMenu_AutoPublish_Tips: "Makes your changes available to readers at the end of each editing session.",
        fileMenu_PublishVersion2: "今すぐリポジトリーに保存",
        fileMenu_AutoPublish3: "${0} に自動保存",
        fileMenu_PublishVersion3: "今すぐ ${0} に保存",      
        fileMenu_SubmitForReview: "レビュー用に送信...",
        fileMenu_CheckinVersion: "チェックイン...",
        fileMenu_Unlock: "ロックの解除",
        //	fileMenu_SaveAsDraft: "as Draft",
        //	fileMenu_SaveInMyDocs: "in My Documents",
        //	fileMenu_SaveToSymphony: "to Lotus Symphany",
        fileMenu_DownloadAs: "名前を指定してダウンロード",
        fileMenu_PDF: "PDF",
        fileMenu_ODF: "ODF",
        fileMenu_DOC: "Microsoft Word 97- 2007 (*.doc)",
        fileMenu_ODS: "ODS",
        fileMenu_XLS: "Microsoft Excel 97-2007 (*.xls) ",
        fileMenu_ShareWith: "共有...",
        fileMenu_ExportAsPDF: "PDF",
        fileMenu_ExportAsODF: "ODF",
        fileMenu_ExportAsPPT: "Microsoft Powerpoint 97- 2007 (*.ppt)",
        //	fileMenu_WebPreview: "Web Preview",
        fileMenu_PrintToPDF: "PDF に印刷...",
        fileMenu_ViewFileDetails: "ファイルの詳細の表示...",
        fileMenu_RecentFile: "最近使ったファイル",
        fileMenu_Open: "開く",
        fileMenu_Download: "ダウンロード",
        fileMenu_Print: "印刷",
        fileMenu_Export: "エクスポート",
        fileMenu_ExportToCSV: "CSV",
        fileMenu_ExportToPDF: "PDF (.pdf)",
        fileMenu_ExportToMarkdown: "Markdown (.md)",
        fileMenu_ExportToMS: "Microsoft Office 形式 (.${FILEEXTENSION})",
        fileMenu_ExportToODF: "Open Document 形式 (.${FILEEXTENSION})",
        fileMenu_PgSetup: "ページ・レイアウトの設定...",

        editMenu: "編集",
        editMenu_Undo: "元に戻す",
        editMenu_Redo: "やり直し",
        editMenu_Cut: "切り取り",
        editMenu_Copy: "コピー",
        editMenu_Paste: "貼り付け",
        editMenu_DeleteSlide: "スライドの削除",
        editMenu_SelectAll: "すべて選択",
        editMenu_Find: "検索...",
        editMenu_Replace: "置換...",
        editMenu_FindReplace: "検索と置換...",
        editMenu_EditLink: "リンクの追加または編集",
        editMenu_DeleteSheet: "シートの削除...",
        editMenu_RenameSheet: "シート名の変更...",
        editMenu_HideSheet: "シートの非表示",
        editMenu_MoveSheet: "シートの移動...",
        editMenu_DeleteRow: "行の削除",
        editMenu_DeleteColumn: "列の削除",
        editMenu_DeleteCellLeft: "セルを削除して左にシフト",
        editMenu_DeleteCellUp: "セルを削除して上にシフト",
        editMenu_ClearCell: "内容の削除",

        viewMenu: "表示",
        viewMenu_Master: "マスター",
        viewMenu_Notifications: "通知",
        viewMenu_SlideSorter: "スライド一覧",
        viewMenu_SpeakerNotes: "スピーカー・ノート",
        viewMenu_Toolbar_Basic: "基本認証",
        viewMenu_Toolbar_Advanced: "拡張",
        viewMenu_Toolbar_None: "なし",
        viewMenu_Toolbar: "ツールバー",
        viewMenu_Statusbar: "ステータス・バー",
        viewMenu_Navigator: "ナビゲーター...",
        //viewMenu_Sidebar: "Sidebar",
        viewMenu_ShowHideIndicators: "共同編集インジケータの表示",
        viewMenu_Assignment: "割り当てインジケーター",
        viewMenu_Bookmark: "ブックマーク",
        viewMenu_Coediting: "共同編集の強調表示",
        viewMenu_Rulers: "ルーラー",
        viewMenu_WebLayout: "Web レイアウト",
        viewMenu_AutomaticSpellCheck: "入力時の自動スペルチェック",
        viewMenu_Formulabar: "式バー",
        viewMenu_moveRight: "Enter によりカーソルが右に移動",
        viewMenu_showFullString: "セル内の内容を拡張",
        viewMenu_Doc: "文書の表示",
        viewMenu_Templates: "テンプレート",
        viewMenu_GridLines: "グリッド線の非表示",
        viewMenu_UnsupportWarning: "サポートされない機能のメッセージを表示",
        viewMenu_HiddenSheets: "非表示のシート",
        viewMenu_FreezeRows: "行を固定",
        viewMenu_FreezeColumns: "列を固定",
        viewMenu_NoFrozenRows: "固定行なし",
        viewmenu_NoFrozenColumns: "固定列なし",
        viewMenu_FreezeXRows: "${0} 行を固定",
        viewMenu_FreezeOneRow: "${0} 行を固定",
        viewMenu_FreezeXColumns: "${0} 列を固定",
        viewMenu_FreezeOneColumn: "${0} 列を固定",
        viewMenu_CarriageReturn: "書式設定記号",
        viewMenu_Navigation: "ナビゲーション範囲",
        viewMenu_ACL: "編集可能領域",
        viewMenu_GridOnOff: "グリッド線",
        viewMenu_ObserverMode: 'オブザーバー・モード',

        createMenu: "挿入",
        createMenu_NewSlide: "新規スライド",
        createMenu_DuplicateSlide: "スライドのコピー",
        createMenu_ImageFromFile: "イメージ...",
        createMenu_TextBox: "テキスト・ボックス",
        createMenu_Shape: "シェイプ",
        createMenu_break: "区切り",
        createMenu_RowAbove: "上の行",
        createMenu_RowBelow: "下の行",
        createMenu_ColumnRight: "右の列",
        createMenu_ColumnLeft: "左の列",
        createMenu_Sheet: "シート...",
        createMenu_Image: "イメージ...",
        createMenu_Comments: "コメント...",
        createMenu_WebLink: "Web リンク...",
        createMenu_SpecialCharacter: "記号と特殊文字...",
        createMenu_Function: "関数...",
        createMenu_Fromtemplate: "テンプレートから作成",

        insertMenu: "挿入",
        insertMenu_break: "改ページ",
        insertMenu_sectionbreak: "セクション区切り",
        insertMenu_Bookmark: "ブックマーク...",
        insertMenu_WebLink: "リンク...",
        insertMenu_SpecialCharacter: "記号と特殊文字...",
        insertMenu_HorizontalLine: "水平線",
        insertMenu_Header: "ヘッダー",
        insertMenu_Footer: "フッター",
        insertMenu_TableOfContents: "目次",

        insertMenu_HeaderFooter: "ヘッダー/フッター",
        insertMenu_HF_Edit: "編集",
        insertMenu_HF_Hide: "非表示",
        insertMenu_Endnotes: "文末脚注",
        insertMenu_RowAbove: "上の行",
        insertMenu_PageNumber: "ページ番号",
        insertMenu_PageNumberTop: "ページの先頭",
        insertMenu_PageNumberBottom: "ページの最後",
        insertMenu_PageNumberCurr: "現在の位置",
        insertMenu_TotalPageNumber: "ページ 1 / N",
        insertMenu_Date: "日付...",
        insertMenu_Time: "時刻...",
        insertMenu_Fields: "フィールド",
        //    insertMenu_Comment: "Comment",
        insertMenu_CellRight: "セル、右にシフト",
        insertMenu_CellDown: "セル、下にシフト",
        insertMenu_RowBelow: "下の行",
        insertMenu_ColumnBefore: "左に 1 列",
        insertMenu_ColumnAfter: "右に 1 列",
        insertMenu_Sheet: "シート...",
        insertMenu_Image: "イメージ...",
        insertMenu_DuplicateSheet: "シートのコピー",
        insertMenu_Function: "関数",
        insertMenu_FunctionSum: "SUM",
        insertMenu_FunctionAverage: "AVERAGE",
        insertMenu_FunctionCount: "COUNT",
        insertMenu_FunctionMax: "MAX",
        insertMenu_FunctionMin: "MIN",
        insertMenu_FunctionMore: "その他の関数...",
        insertMenu_NameRange: "名前付き範囲",
        insertMenu_NameRangeNew: "新規の範囲...",
        insertMenu_NameRangeManage: "範囲の管理...",
        insertMenu_Chart: "グラフ...",

        contextMenu_insertCellRight: "セルを挿入して右にシフト",
        contextMenu_insertCellDown: "セルを挿入して下にシフト",
        contextMenu_InsertRowAbove: "行を上に挿入",
        contextMenu_InsertRowBelow: "行を下に挿入",
        contextMenu_InsertColumnBefore: "前に列を挿入",
        contextMenu_InsertColumnAfter: "後ろに列を挿入",
        contextMenu_DownloadImage: "イメージとしてダウンロード",

        formatMenu: "書式",
        formatMenu_Columns: "列",
        formatMenu_DefaultFormatting: "デフォルトの書式設定",
        formatMenu_Template: "スタイル...",
        contextMenu_Template: "表スタイル...",
        formatMenu_LineSpacing: "行間",
        formatMenu_LineSpacing1: "1",
        formatMenu_LineSpacing12: "1.2",
        formatMenu_LineSpacing15: "1.5",
        formatMenu_LineSpacing2: "2",
        formatMenu_LineSpacing25: "2.5",
        formatMenu_LineSpacing3: "3",
        formatMenu_TextProperties: "テキストのプロパティー",
        formatMenu_PageBreakBefore: "直前に改ページ",
        formatMenu_KeepLines: "すべての行を保持",
        formatMenu_WidowControl: "ウィドウ/オーファン制御",
        formatMenu_Pagination: "段落のプロパティー",
        formatMenu_Bold: "太字",
        formatMenu_Italic: "イタリック",
        formatMenu_Underline: "下線",
        formatMenu_Strikethrough: "取り消し線",
        formatMenu_IncreaseSize: "フォント・サイズの拡大",
        formatMenu_DecreaseSize: "フォント・サイズの縮小",
        formatMenu_ImageProperties: "イメージのプロパティー...",
        formatMenu_ChartProperties: "グラフのプロパティー...",
        formatMenu_EditChart: "グラフの編集",
        formatMenu_InsertChart: "グラフの挿入",
        formatMenu_Properties: "プロパティー...",
        formatMenu_Heading: "見出し",
        formatMenu_Normal: "標準",
        formatMenu_Title: "タイトル",
        formatMenu_Subtitle: "サブタイトル",
        formatMenu_Heading1: "見出し 1",
        formatMenu_Heading2: "見出し 2",
        formatMenu_Heading3: "見出し 3",
        formatMenu_Heading4: "見出し 4",
        formatMenu_Heading5: "見出し 5",
        formatMenu_Heading6: "見出し 6",
        formatMenu_Heading7: "見出し 7",
        formatMenu_Heading8: "見出し 8",
        formatMenu_Heading9: "見出し 9",
        formatMenu_BulletedList: "黒丸付きリスト",
        formatMenu_NumberedList: "番号付きリスト",
        formatMenu_OutLine: "マルチレベル・リスト",
        formatMenu_Superscript: "上付き文字",
        formatMenu_Subscript: "下付き文字",
        formatMenu_Align: "位置合わせ",
        formatMenu_Left: "左揃え",
        formatMenu_Right: "右揃え",
        formatMenu_Center: "中央揃え",
        formatMenu_Justify: "両端揃え",
        formatMenu_Text_Direction: "テキストの方向",
        formatMenu_Ltr: "左から右",
        formatMenu_Rtl: "右から左",
        formatMenu_LineSpacing: "行間",
        formatMenu_LineSpacing1: "1.0",
        formatMenu_LineSpacing115: "1.15",
        formatMenu_LineSpacing15: "1.5",
        formatMenu_LineSpacing2: "2.0",
        formatMenu_LineSpacing25: "2.5",
        formatMenu_LineSpacing3: "3.0",
        formatMenu_Top: "上揃え",
        formatMenu_Bottom: "下揃え",
        formatMenu_Middle: "中央揃え",
        formatMenu_Direction: "テキストの方向",
        formatMenu_Rtl: "右から左",
        formatMenu_Ltr: "左から右",
        formatMenu_Auto: "コンテキスト対応",
        formatMenu_SheetDirection: "シートの方向",
        formatMenu_SheetRtl: "右から左",
        formatMenu_SheetLtr: "左から右",
        formatMenu_Indent: "インデントの増加",
        formatMenu_DecreaseIndent: "インデントの減少",
        formatMenu_ClearFormat: "書式設定のクリア",
        formatMenu_RowHeight: "行の高さ",
        formatMenu_ColumnWidth: "列幅",
        formatMenu_ShowRow: "行の表示",
        formatMenu_HideRow: "行の非表示",
        formatMenu_ShowColumn: "列の表示",
        formatMenu_HideColumn: "列の非表示",
        formatMenu_WrapText: "テキストの折り返し",
        formatMenu_Number: "数値",
        formatMenu_FontArial: "Arial",
        formatMenu_FontComicSansMS: "Comic Sans MS",
        formatMenu_FontCourierNew: "Courier New",
        formatMenu_FontGeorgia: "Georgia",
        formatMenu_FontLucidaSansUnicode: "Lucida Sans Unicode",
        formatMenu_FontTahoma: "Tahoma",
        formatMenu_FontTimesNewRoman: "Times New Roman",
        formatMenu_FontTrebuchetMS: "Trebuchet MS",
        formatMenu_FontVerdana: "Verdana",
        formatMenu_FontName: "フォント",

        layoutMenu: "レイアウト",
        layoutMenu_SlideLayout: "スライド・レイアウト...",
        layoutMenu_SlideDesign: "マスター・スタイル...",
        layoutMenu_DefaultFormatting: "デフォルトの書式設定",
        layoutMenu_Textprop_Bold: "太字",
        layoutMenu_Textprop_Italic: "イタリック",
        layoutMenu_Textprop_Underline: "下線",
        layoutMenu_Textprop_Strikethrough: "取り消し線",
        layoutMenu_TextProp: "テキストのプロパティー",
        LayoutMenu_RowHeight: "行の高さ...",
        LayoutMenu_ColumnWidth: "列幅...",
        LayoutMenu_ShowRow: "行の表示",
        LayoutMenu_HideRow: "行の非表示",
        LayoutMenu_RenameSheet: "シート名の変更...",
        LayoutMenu_MoveSheet: "シートの移動",

        tableMenu: "表",
        tableMenu_Create: "作成...",
        tableMenu_CreateFromTemplate: "テンプレートから作成",
        tableMenu_Delete: "削除",
        tableMenu_SetTableColor: "セルに色を付ける",
        tableMenu_CreateTable: "表の作成",
        tableMenu_Cell: "セル",
        tableMenu_CellMergeCells: "セルの結合",
        tableMenu_CellAlignLeft: "左揃え",
        tableMenu_CellAlignCenter: "中央揃え",
        tableMenu_CellAlignRight: "右揃え",
        tableMenu_CellClearContents: "内容の消去",
        tableMenu_CellProperties: "セルのプロパティー...",
        tableMenu_Row: "行",
        tableMenu_InsertRowAbove: "行を上に挿入",
        tableMenu_InsertRowBelow: "行を下に挿入",
        tableMenu_MoveRowAbove: "行を上に移動",
        tableMenu_MoveRowBelow: "行を下に移動",
        tableMenu_RowInsertRow: "行の挿入...",
        tableMenu_RowInsertRowAbove: "行を上に挿入",
        tableMenu_RowInsertRowBelow: "行を下に挿入",
        tableMenu_RowMoveRowAbove: "行を上に移動",
        tableMenu_RowMoveRowBelow: "行を下に移動",
        tableMenu_RowDelete: "削除",
        tableMenu_RowRepeat: "ヘッダー行を繰り返す",
        tableMenu_InsertColumnBefore: "前に列を挿入",
        tableMenu_InsertColumnAfter: "後ろに列を挿入",
        tableMenu_MoveColumnBefore: "列を左に移動",
        tableMenu_MoveColumnAfter: "列を右に移動",
        tableMenu_ResizeColumn: "列のサイズ変更",
        tableMenu_ResizeColumns: "列のサイズ変更",
        tableMenu_MarkasCategory: "カテゴリーとしてマーク",
        tableMenu_ColumnInsertColumn: "列の挿入...",
        tableMenu_ColumnAddColumnBefore: "前に列を挿入",
        tableMenu_ColumnAddColumnAfter: "後ろに列を挿入",
        tableMenu_ColumnMoveColumnAfter: "列を後に移動",
        tableMenu_ColumnMoveColumnBefore: "列を前に移動",
        tableMenu_ColumnDelete: "削除",
        tableMenu_ColumnSortAscending: "昇順にソート",
        tableMenu_ColumnSortDescending: "降順にソート",
        tableMenu_Column: "列",
        tableMenu_Style: "スタイル",
        tableMenu_TableProperties: "表のプロパティー...",

        teamMenu: "チーム",
        teamMenu_AddComment: "コメントの追加",
        teamMenu_AssignCells: "セルの割り当て",
        teamMenu_AssignSection: "セクションの割り当て",
        teamMenu_EditAssignment: "割り当ての編集",
        teamMenu_MarkSectionComplete: "セクションを完了としてマーク",
        teamMenu_MarkAssignmentComplete: "割り当てを完了としてマーク",
        teamMenu_WorkPrivatelyOnSection: "非公開でセクションで作業",
        teamMenu_CancelPrivateWork: "非公開の作業のキャンセル",
        teamMenu_ApproveSection: "セクションの承認",
        teamMenu_ApproveAssignment: "割り当ての承認",
        teamMenu_ReturnSectionForRework: "セクションを再作業のために戻す",
        teamMenu_ReturnAssignmentForRework: "割り当てを再作業のために戻す",
        teamMenu_RemoveSectionAssignment: "セクション割り当ての削除",
        teamMenu_RemoveCellAssignment: "セル割り当ての削除",
        teamMenu_RemoveCompletedAssignments: "完了した割り当ての削除",
        teamMenu_AboutThisSection: "このセクションについて",
        teamMenu_AboutAssignment: "この割り当てについて",

        presentationMenu: "プレゼンテーション",
        presentationMenu_SlideShow: "スライド・ショーの再生",
        presentationMenu_SlideShowWithCoview: "共有スライド・ショーの再生",
        presentationMenu_SlideTransitions: "画面切り替えの適用...",
        presentationMenu_SlideShowFromCurrent: "現在のスライドから再生",
        presentationMenu_EmptyCoviewInvites: "アクティブな共有スライド・ショーがありません",
        presentationMenu_CoviewInvites: "アクティブな共有スライド・ショー",

        dataMenu: "データ",
        dataMenu_Sort: "ソート...",
        dataMenu_SortAsc: "昇順にソート",
        dataMenu_SortDesc: "降順にソート",
        dataMenu_ACL: "保護領域",
        dataMenu_ACL_DELETE: "すべての許可の削除",
        dataMenu_Validity: "入力規則",
        dataMenu_InstantFilter: "インスタント・フィルター",
        dataMenu_Validation: "検証...",

        toolsMenu: "ツール",
        toolsMenu_AutoComplete: "セル・エントリーのオートコンプリート",
        toolsMenu_SelectDictionary: "スペル・チェック辞書",
        toolsMenu_Dictionary_ca_CT: "カタロニア語",
        toolsMenu_Dictionary_cs_CZ: "チェコ語 (チェコ)",
        toolsMenu_Dictionary_da_DK: "デンマーク語 (デンマーク)",
        toolsMenu_Dictionary_nl_NL: "オランダ語 (オランダ)",
        toolsMenu_Dictionary_en_AU: "英語 (オーストラリア)",
        toolsMenu_Dictionary_en_GB: "英語 (英国)",
        toolsMenu_Dictionary_en_US: "英語 (米国)",
        toolsMenu_Dictionary_fi_FI: "フィンランド語 (フィンランド)",
        toolsMenu_Dictionary_fr_FR: "フランス語 (フランス)",
        toolsMenu_Dictionary_fr_CA: "フランス語 (カナダ)",
        toolsMenu_Dictionary_de_DE: "ドイツ語 (ドイツ)",
        toolsMenu_Dictionary_de_CH: "ドイツ語 (スイス)",
        toolsMenu_Dictionary_el_GR: "ギリシャ語 (ギリシャ)",
        toolsMenu_Dictionary_it_IT: "イタリア語 (イタリア)",
        toolsMenu_Dictionary_pl_PL: "ポーランド語 (ポーランド)",
        toolsMenu_Dictionary_pt_BR: "ポルトガル語 (ブラジル)",
        toolsMenu_Dictionary_pt_PT: "ポルトガル語 (ポルトガル)",
        toolsMenu_Dictionary_ru_RU: "ロシア語 (ロシア)",
        toolsMenu_Dictionary_es_ES: "スペイン語 (スペイン)",
        toolsMenu_Dictionary_sv_SE: "スウェーデン語 (スウェーデン)",
        toolsMenu_Dictionary_nb_NO: "ノルウェー語 (ブークモール)",
        toolsMenu_Dictionary_nn_NO: "ノルウェー語 (ニーノシュク)",
        toolsMenu_Dictionary_he_IL: "ヘブライ語 (イスラエル)",
        toolsMenu_SpellCheck: "手動スペル・チェックの実行...",
        toolsMenu_Preferences: "設定",
        toolsMenu_Task: "タスク",
        toolsMenu_Task_Assigntask: "タスクの割り当て",
        teamMenu_AssignSlide: "スライドの割り当て",
        teamMenu_AssignSlides: "スライドの割り当て",
        teamMenu_EditSlide: "スライドの割り当ての編集",
        teamMenu_ReopenSlideAssignment: "スライドの割り当ての再オープン",
        teamMenu_ReopenSlideAssignments: "スライドの割り当ての再オープン",
        teamMenu_ReassignSlide: "スライドの再割り当て",
        teamMenu_ReassignSlides: "スライドの再割り当て",
        teamMenu_MarkSlidesComplete: "スライドを完了としてマーク",
        teamMenu_MarkSlidesCompletes: "スライドを完了としてマーク",
        teamMenu_ApproveSlide: "スライドの承認",
        teamMenu_ApproveSlides: "スライドの承認",
        teamMenu_ReturnForRework: "スライドを再作業のために戻す",
        teamMenu_ReturnForReworks: "スライドを再作業のために戻す",
        teamMenu_RemoveAssignment: "スライドの割り当ての削除",
        teamMenu_AboutThisSlide: "このスライドについて",

        addOnsMenu: "アドオン",

        helpMenu: "ヘルプ",
        helpMenu_About: "詳細情報",
        helpMenu_Overview: "ヘルプ目次",
        helpMenu_NewFeatures: "新機能",
        helpMenu_Tour: "ガイド付きツアー",

        accel_fileMenu_Save: "Ctrl+S",
        accel_fileMenu_Save_Mac: "\u2318S",
        accel_fileMenu_Print: "Ctrl+P",
        accel_fileMenu_Print_Mac: "\u2318P",
        accel_editMenu_SelectAll: "Ctrl+A",
        accel_editMenu_SelectAll_Mac: "\u2318A",
        accel_editMenu_Undo: "Ctrl+Z",
        accel_editMenu_Undo_Mac: "\u2318Z",
        accel_editMenu_Redo: "Ctrl+Y",
        accel_editMenu_Redo_Mac: "\u2318Y",
        accel_editMenu_Cut: "Ctrl+X",
        accel_editMenu_Cut_Mac: "\u2318X",
        accel_editMenu_Copy: "Ctrl+C",
        accel_editMenu_Copy_Mac: "\u2318C",
        accel_editMenu_Paste: "Ctrl+V",
        accel_editMenu_Paste_Mac: "\u2318V",
        accel_editMenu_Find: "Ctrl+F",
        accel_editMenu_Find_Mac: "\u2318F",
        accel_insertMenu_Link: "Ctrl+K",
        accel_insertMenu_Link_Mac: "\u2318K",
        accel_insertMenu_Header: "Ctrl+Shift+H",
        accel_insertMenu_Header_Mac: "\u21e7\u2318H",
        accel_insertMenu_Footer: "Ctrl+Shift+F",
        accel_insertMenu_Footer_Mac: "\u21e7\u2318F",
        accel_formatMenu_Textprop_Bold: "Ctrl+B",
        accel_formatMenu_Textprop_Bold_Mac: "\u2318B",
        accel_formatMenu_Textprop_Italic: "Ctrl+I",
        accel_formatMenu_Textprop_Italic_Mac: "\u2318I",
        accel_formatMenu_Textprop_FormatPainter: "Ctrl+SHIFT+C、Ctrl+SHIFT+V",
        accel_formatMenu_Textprop_FormatPainter_Mac: "\u21e7\u2318C、\u21e7\u2318V",
        accel_formatMenu_Textprop_Underline: "Ctrl+U",
        accel_formatMenu_Textprop_Underline_Mac: "\u2318U",
        accel_formatMenu_Headingprop_P: "Ctrl+Shift+0",
        accel_formatMenu_Headingprop_H1: "Ctrl+Shift+1",
        accel_formatMenu_Headingprop_H2: "Ctrl+Shift+2",
        accel_formatMenu_Headingprop_H3: "Ctrl+Shift+3",
        accel_formatMenu_Headingprop_H4: "Ctrl+Shift+4",
        accel_formatMenu_Headingprop_H5: "Ctrl+Shift+5",
        accel_formatMenu_Headingprop_H6: "Ctrl+Shift+6",
        accel_formatMenu_Superscript: "Ctrl+.",
        accel_formatMenu_Superscript_Mac: "\u2318.",
        accel_formatMenu_Subscript: "Ctrl+,",
        accel_formatMenu_Subscript_Mac: "\u2318,",
        accel_formatMenu_Left: "CTRL+SHIFT+L",
        accel_formatMenu_Left_Mac: "\u21e7\u2318L",
        accel_formatMenu_Right: "CTRL+SHIFT+R",
        accel_formatMenu_Right_Mac: "\u21e7\u2318R",
        accel_formatMenu_Center: "CTRL+SHIFT+E",
        accel_formatMenu_Center_Mac: "\u21e7\u2318E",
        accel_formatMenu_Justify: "CTRL+SHIFT+J",
        accel_formatMenu_Justify_Mac: "\u21e7\u2318J",
        accel_formatMenu_Indent: "CTRL+M",
        accel_formatMenu_Indent_Mac: "\u2318M",
        accel_formatMenu_DecreaseIndent: "CTRL+SHIFT+M",
        accel_formatMenu_DecreaseIndent_Mac: "\u21e7\u2318M",
        accel_teamMenu_AddComment: "Shift+F2",

        ctxMenuSmartTable: '表',
        ctxMenuTableProperties: "表のプロパティー",
        ctxMenuDeleteST: '削除',
        ctxMenuDeleteSTTable: '表の削除',
        ctxMenuChgSTStyle: 'スタイルの変更',
        ctxMenuShowCaption: '表題の表示',
        ctxMenuHideCaption: '表題の非表示',
        ctxMenuResizeST: 'サイズ変更',
        ctxMenuResizeColumnsST: '列のサイズ変更',
        ctxMenuSTRow: '行',
        ctxMenuAddSTRowAbv: '行を上に挿入',
        ctxMenuAddSTRowBlw: '行を下に挿入',
        ctxMenuMoveSTRowUp: '行を上に移動',
        ctxMenuMoveSTRowDown: '行を下に移動',
        ctxMenuDelSTRow: '削除',
        ctxMenuRepeatRow: 'ヘッダー行を繰り返す',
        ctxMenuSTCol: '列',
        ctxMenuAddSTColBfr: '前に列を挿入',
        ctxMenuAddSTColAft: '後ろに列を挿入',
        ctxMenuMoveSTColBefore: '列を前に移動',
        ctxMenuMoveSTColAfter: '列を後に移動',
        ctxMenuDelSTCol: '削除',
        ctxMenuSortSTColAsc: '昇順にソート',
        ctxMenuSortSTColDesc: '降順にソート',
        ctxMenuShowAllFacets: 'カテゴリーの表示',
        ctxMenuHideAllFacets: 'カテゴリーの非表示',
        ctxMenuSTCell: 'セル',
        ctxMenuMergeCells: 'セルの結合',
        ctxMenuMergeDown: '下のセルと結合',
        ctxMenuVerSplit: '垂直に分割',
        ctxMenuHorSplit: '水平に分割',
        ctxMenuSplitCells: 'セルの分割...',
        splitCells: 'セルの分割',
        ctxMenuAlignTextLeft: '左揃え',
        ctxMenuAlignTextCenter: '中央揃え',
        ctxMenuAlignTextRight: '右揃え',
        ctxMenuClearSTCellContent: '内容の消去',
        ctxMenuMakeHeaderRow: '選択した行をヘッダーとして使用',
        ctxMenuMakeNonHeaderRow: '見出しスタイルを削除',
        ctxMenuMakeHeaderCol: '選択した列をヘッダーとして使用',
        ctxMenuMakeNonHeaderCol: '見出しスタイルを削除',
        SHEET_CONTEXT_Hide: "非表示", // hide row, column or sheet
        SHEET_CONTEXT_Show: "表示", // show row, column
        SHEET_CONTEXT_MoveSheet: "移動...", // move sheet
        SHEET_CONTEXT_InsertSheet: "挿入...", // insert sheet
        SHEET_CONTEXT_DeleteSheet: "削除...", // delete sheet	
        SHEET_CONTEXT_DuplicateSheet: "複製...", // duplicate sheet
        SHEET_CONTEXT_RenameSheet: "名前変更...", // rename sheet
	
        ctxMenu_Image_WrapText: "テキストの折り返し",
        ctxMenu_Image_WrapText_Inline: "行内",
        ctxMenu_Image_WrapText_Square: "四角",
        ctxMenu_Image_WrapText_TopBottom: "上下",
        ctxMenu_Image_WrapText_Behind: "背面",
        ctxMenu_Image_WrapText_InFront: "前面",
        ctxMenu_Image_WrapText_Other: "その他のテキストの折り返し",
        ctxMenu_Image_WrapText_BothSides: "両側",
        ctxMenu_Image_WrapText_LeftOnly: "左のみ",
        ctxMenu_Image_WrapText_RightOnly: "右のみ",
        ctxMenu_Image_WrapText_LargestOnly: "最大のみ",

        ctxMenu_Shape_AddText: "テキストの追加",

        ctxMenu_Range_ACL: "範囲の保護",
        ctxMenu_Sheet_ACL: "シートの保護",

        ctxMenu_HeaderFooter: "ヘッダー / フッター",
        ctxMenu_HeaderFooter_DiffFirst: "最初のページのみ",
        ctxMenu_HeaderFooter_DiffOddEven: "奇数/偶数ページ別指定",
        ctxMenu_HeaderFooter_LinkToPre: "前と同じ",

        ctxMenu_copy: "コピー",
        ctxMenu_paste: "貼り付け",
        ctxMenu_delete: "削除",
        ctxMenu_cut: "切り取り",
        ctxMenu_select: "選択",
        ctxMenu_properties: "プロパティー",
        ctxMenu_bringToFront: "最前面へ移動",
        ctxMenu_sendToBack: "最背面へ移動",
        ctxMenu_arrange: "整列",
        ctxMenu_sendBackward: "背面へ移動",
        ctxMenu_sendForward: "前面に移動",
        ctxMenu_fontStyle: "フォント・スタイル",
        ctxMenu_selectStyle: "スタイルの選択",
        ctxMenu_fontSize: "フォント・サイズ",
        ctxMenu_fontFamily: "フォント・ファミリー",
        ctxMenu_bold: "太字",
        ctxMenu_italic: "イタリック",
        ctxMenu_u: "下線",
        ctxMenu_strike: "取り消し線",
        ctxMenu_super: "上付き文字",
        ctxMenu_sub: "下付き文字",
        ctxMenu_color: "色",
        ctxMenu_bgcolor: "背景色",
        ctxMenu_highcolor: "ハイライト色",
        ctxMenu_restart: "再起動リスト",
        ctxMenu_continue: "続行リスト",
        ctxMenu_separate: "別のリスト",
        ctxMenu_join: "前のリストに結合",
        ctxMenu_setNumberVal: "番号付けの値を設定...",
        webClipboardInfoTitle: "クリップボード",
        webClipboardInfoOKBtn: "OK",
        webClipboardInfoCutMsg: "ブラウザーのセキュリティー設定により自動コピーが禁止されています。 代わりにキーボードで Ctrl+X を使用してください。",
        webClipboardInfoCopyMsg: "ブラウザーのセキュリティー設定により自動コピーが禁止されています。 代わりにキーボードで Ctrl+C を使用してください。",
        webClipboardInfoPasteMsg: "ブラウザーのセキュリティー設定により、このエディターはクリップボード・データにアクセスできません。 代わりにキーボードで Ctrl+V を使用してください。",

        clearTrackChangeConfirmMsg: "この文書内の変更にマークを付けるためのすべての色分けは完全に削除されます。 続行しますか?"
});

