/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
	fileMenu: "ファイル",
	fileMenu_New: "新規",
	fileMenu_NewDocument: "文書",
	fileMenu_NewDocumentfromTemplate: "テンプレートからの文書",
	fileMenu_NewPresentation: "プレゼンテーション",
	fileMenu_NewPresentationfromTemplate: "テンプレートからのプレゼンテーション",
	fileMenu_NewSpreadsheet: "スプレッドシート",
	fileMenu_Open: "オープン",
//	fileMenu_Close: "Close",
	fileMenu_Discard: "破棄",
	fileMenu_Save: "保存",
//	fileMenu_SaveAs: "Save As...",
//	fileMenu_SaveAsDraft: "as Draft",
//	fileMenu_SaveInMyDocs: "in My Documents",
//	fileMenu_SaveToSymphony: "to Lotus Symphany",
	fileMenu_ShareWith: "共有...	",
	fileMenu_ExportAsPDF: "PDF としてエクスポート",
	fileMenu_WebPreview: "Web プリビュー",
	fileMenu_PrintPreview: "印刷プリビュー",
	fileMenu_RecentFile: "最近使ったファイル",
	fileMenu_Print: "印刷...",
	editMenu: "編集",
	editMenu_Undo: "元に戻す",
	editMenu_Redo: "やり直し",
	editMenu_Cut: "切り取り",
	editMenu_Copy: "コピー",
	editMenu_Paste: "貼り付け",
	editMenu_DeleteSlide:"スライドの削除",
	editMenu_SelectAll: "すべて選択",
	editMenu_Find: "検索...",
	editMenu_Replace: "置換...",
	editMenu_DeleteSheet: "シートの削除",
	editMenu_DuplicateSheet: "シートのコピー",
	editMenu_DeleteRow: "行の削除",
	editMenu_DeleteColumn: "列の削除",
	editMenu_ClearCell: "セルのクリア",
	viewMenu: "表示",
	viewMenu_Master: "マスター",
	viewMenu_Notifications: "通知",
	viewMenu_ShowHideIndicators: "共同編集インジケータの表示/非表示",
	viewMenu_SlideSorter: "スライド一覧の表示",
	viewMenu_SpeakerNotes: "スピーカー・ノートの表示",
	viewMenu_NextSlide: "次のスライド",
	viewMenu_PrevSlide: "前のスライド",
	createMenu: "作成",
	createMenu_NewSlide: "新規スライド",
	createMenu_DuplicateSlide: "スライドのコピー",
	createMenu_ImageFromFile: "ファイルから画像を作成",
	createMenu_TextBox: "テキスト・ボックス",
	createMenu_Task: "タスク",
    formatMenu_Text_Direction: "テキストの方向",
    formatMenu_Ltr: "左から右",
    formatMenu_Rtl: "右から左",  	
    formatMenu_Horizontal_Align: "水平配置",
    formatMenu_Vertical_Align: "垂直配置",
    formatMenu_Align_Top: "先頭",
    formatMenu_Align_Middle: "中央",
    formatMenu_Align_Bottom: "下端",
	layoutMenu: "レイアウト",
	layoutMenu_SlideLayout: "スライド・レイアウト",
	layoutMenu_SlideDesign: "マスター・スタイル",
	tableMenu: "表",
	tableMenu_CreateTable: "表の作成",
	tableMenu_Cell: "セル",
	tableMenu_CellAlignLeft: "テキストを左揃えにする",
	tableMenu_CellAlignCenter: "テキストを中央揃えにする",
	tableMenu_CellAlignRight: "テキストを右揃えにする",
	tableMenu_CellClearContents: "内容の消去",
	tableMenu_Row: "行",
	tableMenu_RowAddRowAbove: "行を上に追加",
	tableMenu_RowAddRowBelow: "行を下に追加",
	tableMenu_RowMoveRowAbove: "行を上に移動",
	tableMenu_RowMoveRowBelow: "行を下に移動",
	tableMenu_RowDelete: "削除",
	tableMenu_ColumnAddColumnBefore: "前に列を追加",
	tableMenu_ColumnAddColumnAfter: "後ろに列を追加",
	tableMenu_ColumnMoveColumnAfter: "列を後に移動",
	tableMenu_ColumnMoveColumnBefore: "列を前に移動",
	tableMenu_ColumnDelete: "削除",
	tableMenu_ColumnSortAscending: "昇順にソート",
	tableMenu_ColumnSortDescending: "降順にソート",
	tableMenu_Column: "列",
	tableMenu_Delete: "削除",
	presentationMenu: "プレゼンテーション",
	presentationMenu_SlideShow: "スライド・ショーの再生",
	presentationMenu_SlideShowFromCurrent: "現在のスライドから再生",
	toolsMenu: "ツール",
	toolsMenu_Task: "タスク",
	helpMenu: "ヘルプ",
	helpMenu_Overview: "ヘルプ目次"
})

