/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */


define({
        saveTip: "保存",
        undoTip: "元に戻す",
        redoTip: "やり直し",
        formatPainterTip: "書式設定のコピー",
        showSorterTip: "スライド一覧の表示",
        hideSorterTip: "スライド一覧の非表示",
        webClipboardTip: "Web クリップボード",
        spellCheckTip: "手動スペル・チェックの実行",
        createSectionTip: "セクションの割り当て",
        createCellsTip: "セルの割り当て",
        createSlideTip: "スライドの割り当て",
        submitTip: "割り当ての送信",
        addCommentTip: "コメントの追加",
        removeFormatTip: "書式設定の削除",
        sortAscTip: "昇順にソート",
        sortDescTip: "降順にソート",
        instantFilterTip: "インスタント・フィルター",
        insertChartTip: "グラフの挿入",
        startAutofillTip: "自動入力",
        dataValidationTip: "データ検証",

        selectFontTip: "フォントの選択",
        selectFontSizeTip: "フォント・サイズの選択",
        selectFontNameTip: "フォント名の選択",
        FontName: "フォント名",
        FontSize: "フォント・サイズ",
        increaseFontSizeTip: "フォント・サイズの拡大",
        decreaseFontSizeTip: "フォント・サイズの縮小",
        boldTip: "太字",
        italicTip: "イタリック",
        underlineTip: "下線",
        strikeThroughTip: "取り消し線",
        setFontColorTip: "フォントの色を設定",
        setShadingColorTip: "シェーディング色の設定",
        setBackgroundFill: "背景の塗りつぶし設定",
        setBgColorTip: "背景色を設定",
        setBorderTip: "境界線のスタイルと色を設定",
        setBorderColorTip: "境界線の色を設定",
        setHighlightColor: "ハイライト色を設定",
        formatPainter: "書式設定のコピー",
        //	clearFormat:"Remove Formatting",
        zoom: "ズーム",
        selectStyleTip: "スタイルの選択",
        styles: "スタイル",
        formatAsCurrencyTip: "通貨として書式設定",
        formatAsPercentTip: "パーセントとして書式設定",
        decreaseDecimalTip: "小数点以下の桁数を減らす",
        increaseDecimalTip: "小数点以下の桁数を増やす",
        formatNumberTip: "数値の書式設定",

        numberedListTip: "番号付けの追加または番号付けスタイルの変更",
        bulletedListTip: "マーカーの追加またはマーカースタイルの変更",
        multilevelListTip: "マルチレベル・リストを追加または変更します",
        indentTip: "インデントの増加",
        decreaseIndentTip: "インデントの減少",
        alignTip: "位置合わせ",
        leftAlignTip: "左揃え",
        centerTip: "中央揃え",
        rightAlignTip: "右揃え",
        justifyTip: "両端揃え",
        bottomBorderTip: "下境界線",
        borderTypes: "境界線のタイプ",
        borderTip: "境界線のスタイルを設定",
        topAlignTip: "上揃え",
        middleAlignTip: "中央揃え",
        bottomAlignTip: "下揃え",
        lineSpacingTip: "行間",
        mergeSplitCellTip: "セルの結合または分割",
        wrapNoWrapTip: "折り返しのオンまたはオフ",
        ltrDirectionTip: "左から右のテキストに変更",
        rtlDirectionTip: "右から左のテキストに変更",
        autoDirectionTip: "テキストの方向を変更",
        toggleSheetDirectionTip: "シートの方向を変更",
        setSheetDirectionLTR: "左から右",
        setSheetDirectionRTL: "右から左",

        addTableTip: "表の追加",
        insertOrMoveRowTip: "行の挿入または移動",
        insertOrMoveColTip: "列の挿入または移動",
        insertOrDeleteRowTip: "行の挿入または削除",
        insertOrDeleteColTip: "列の挿入または削除",
        insertFunctionTip: "関数の挿入",
        insertImage: "イメージの挿入",
        resizeCol: "列のサイズ変更",
        resizeCols: "列のサイズ変更",
        addLink: "リンクの追加または編集",
        tableStyle: "表スタイル",

        selectBorder_BottomBorder: "下境界線",
        selectBorder_TopBorder: "上境界線",
        selectBorder_LeftBorder: "左境界線",
        selectBorder_RightBorder: "右境界線",
        selectBorder_NoBorder: "線なし",
        selectBorder_AllBorders: "すべての境界線",

        insertOrMoveRow_InsertAbove: "行を上に挿入",
        insertOrMoveRow_InsertBelow: "行を下に挿入",
        insertOrMoveRow_MoveUp: "行を上に移動",
        insertOrMoveRow_MoveDown: "行を下に移動",
        insertOrMoveCol_InsertLeft: "前に列を挿入",
        insertOrMoveCol_InsertRight: "後ろに列を挿入",
        insertOrMoveCol_InsertBefore: "前に列を挿入",
        insertOrMoveCol_InsertAfter: "後ろに列を挿入",
        insertOrMoveCol_MoveLeft: "列を左に移動",
        insertOrMoveCol_MoveRight: "列を右に移動",

        insertOrDelete_Delete: "削除",

        combineButtonReadTip: "下矢印キーを押してメニューをアクティブにしてから、各矢印キーを使用してナビゲートします",

        lineSpacing_1: "1",
        lineSpacing_12: "1.2",
        lineSpacing_15: "1.5",
        lineSpacing_2: "2",
        lineSpacing_25: "2.5",
        lineSpacing_3: "3",

        percent: "%",
        font_arial: "Arial",

        fontSize: "${0}pt",

        slides: "1 ページに 1 スライド",
        slidesWithNotes: "メモ付きのスライド",
        preparingSlides: "スライドの印刷を準備中...",
        printLayoutOptionLabel: "印刷レイアウトのオプション",

        targetRemovedWhenDialogOpen: "ターゲットが別の共同編集者によって削除されたため、このアクションを完了できません。",

        NUMBER: "数値",
        CURRENCY: "通貨",
        PERCENT: "パーセント",
        DATE: "日付",
        TIME: "時刻",
        DATETIME: "日付/時刻",
        MORECURRENCY: "その他の通貨 (貨幣単位別)",
        MORECURRENCYCODE: "その他の通貨 (通貨コード別)",
        MOREDATE: "その他の日時形式",
        TEXT: "テキスト",
	
        // currency, by currency code
        // NOTE: MUST keep it in order
        CURRENCY_CODE: {
            AED: "アラブ首長国連邦 (ディルハム)",
            ARS: "アルゼンチン (ペソ)",
            AUD: "オーストラリア (ドル)",
            BGN: "ブルガリア (レフ)",
            BOB: "ボリビア (ボリビアーノ)",
            BRL: "ブラジル (レアル)",
            CAD: "カナダ (ドル)",
            CHF: "スイス (フラン)",
            CLP: "チリ (ペソ)",
            CNY: "中国 (人民元)",
            COP: "コロンビア (ペソ)",
            CRC: "コスタリカ (コロン)",
            CZK: "チェコ共和国 (コルナ)",
            DKK: "デンマーク (クローネ)",
            DOP: "ドミニカ共和国 (ペソ)",
            EGP: "エジプト (ポンド)",
            EUR: "オーストリア、ベルギー、フィンランド、フランス、...、スロベニア、スペイン (ユーロ)",
            GBP: "イングランド、英国 (ポンド)",
            HKD: "香港 (ドル)",
            HRK: "クロアチア (クーナ)",
            HUF: "ハンガリー (フォリント)",
            IDR: "インドネシア (ルピア)",
            ILS: "イスラエル (新シェケル)",
            INR: "インド (ルピー)",
            JPY: "日本 (円)",
            KRW: "韓国 (ウォン)",
            KZT: "カザフスタン (テンゲ)",
            MAD: "モロッコ (ディルハム)",
            MXN: "メキシコ (ペソ)",
            MYR: "マレーシア (リンギット)",
            NOK: "ノルウェー (クローネ)",
            NZD: "ニュージーランド (ドル)",
            PAB: "パナマ (バルボア)",
            PEN: "ペルー (ヌエボ・ソル)",
            PHP: "フィリピン (ペソ)",
            PKR: "パキスタン (ルピー)",
            PLN: "ポーランド (ズロチ)",
            PYG: "パラグアイ (グワラニ)",
            RON: "ルーマニア (新レイ)",
            RSD: "セルビア語 (キリル文字), セルビア語 (ローマ字)",
            RUB: "ロシア (ルーブル)",
            SAR: "サウジアラビア (リヤル)",
            SEK: "スウェーデン (クローナ)",
            SGD: "シンガポール (ドル)",
            SVC: "エルサルバドル (コロン)",
            THB: "タイ (バーツ)",
            TRY: "トルコ (リラ)",
            TWD: "台湾 (新ドル)",
            USD: "エクアドル、プエルトリコ、アメリカ合衆国 (米ドル)",
            UYU: "ウルグアイ (ペソ)",
            VEF: "ベネズエラ (ボリバル・フエルテ)",
            VND: "ベトナム (ドン)",
            ZAR: "南アフリカ (ランド)"
        },
        // for border toolbar
        allBorders: "すべての境界線",
        innerBorders: "内部の境界線",
        horizontalBorders: "横境界線",
        verticalBorders: "縦境界線",
        outerBorders: "外部の境界線",
        borderColor: "境界線の色",
        leftBorder: "左境界線",
        topBorder: "上境界線",
        rightBorder: "右境界線",
        bottomBorder: "下境界線",
        clearBorders: "境界線なし",
        BorderStyle_ThinSolid: "細い実線",
        BorderStyle_ThinDotted: "細い点線",
        BorderStyle_ThinDashed: "細い破線",
        BorderStyle_ThickSolid: "太い実線",
        BorderStyle_ThickDotted: "太い点線",
        BorderStyle_ThickDashed: "太い破線"
})

