define({      
//begin v1.x content
	"clearFilterDialogTitle": "Ryd filter",
	"filterDefDialogTitle": "Filter",
	"defaultRuleTitle": "Regel",
	"ruleTitleTemplate": "Regel ${ruleNumber}",
	"noFilterApplied": "Intet filter er anvendt.",
	"defineFilter": "Definér filter",
	"conditionEqual": "lig med",
	"conditionNotEqual": "ikke lig med",
	"conditionLess": "er mindre end",
	"conditionLessEqual": "mindre end eller lig med",
	"conditionGreater": "er større end",
	"conditionGreaterEqual": "større end eller lig med",
	"conditionContain": "indeholder",
	"conditionIs": "er",
	"conditionStartWith": "begynder med",
	"conditionEndWith": "slutter med",
	"conditionNotContain": "indeholder ikke",
	"conditionIsNot": "er ikke",
	"conditionNotStartWith": "begynder ikke med",
	"conditionNotEndWith": "slutter ikke med",
	"conditionBefore": "før",
	"conditionAfter": "efter",
	"conditionRange": "interval",
	"conditionIsEmpty": "er tom",
	"all": "alle",
	"any": "enhver",
	"relationAll": "alle regler",
	"waiRelAll": "Match alle følgende regler:",
	"relationAny": "enhver regel",
	"waiRelAny": "Match enhver af følgende regler:",
	"relationMsgFront": "Match",
	"relationMsgTail": "",
	"and": "og",
	"or": "eller",
	"addRuleButton": "Tilføj regel",
	"waiAddRuleButton": "Tilføj en ny regel",
	"removeRuleButton": "Fjern regel",
	"waiRemoveRuleButtonTemplate": "Fjern regel ${0}",
	"addRuleButton": "Tilføj filterregel",
	"cancelButton": "Annullér",
	"waiCancelButton": "Annullér denne dialogboks",
	"clearButton": "Ryd",
	"waiClearButton": "Ryd filtret",
	"filterButton": "Filtrér",
	"waiFilterButton": "Send filtret",
	"columnSelectLabel": "Kolonne:",
	"waiColumnSelectTemplate": "Kolonne til regel ${0}",
	"conditionSelectLabel": "Betingelse:",
	"waiConditionSelectTemplate": "Betingelse for regel ${0}",
	"valueBoxLabel": "Værdi:",
	"waiValueBoxTemplate": "Angiv filterværdi for regel ${0}",
	"rangeTo": "til",
	"rangeTemplate": "fra ${0} til ${1}",
	"statusTipHeaderColumn": "Kolonne",
	"statusTipHeaderCondition": "Regler",
	"statusTipTitle": "Filtreringslinje",
	"statusTipMsg": "Klik på filtreringslinjen her for at filtrere værdier i ${0}.",
	"anycolumn": "enhver kolonne",
	"statusTipTitleNoFilter": "Filtreringslinje",
	"statusTipTitleHasFilter": "Filter",
	"statusTipRelPre": "Match",
	"statusTipRelPost": "regler.",
	"statusTipHeaderAll": "Match alle regler.",
	"statusTipHeaderAny": "Match enhver regel.",
	"defaultItemsName": "elementer",
	"filterBarMsgHasFilterTemplate": "${0} af ${1} ${2} vises.",
	"filterBarMsgNoFilterTemplate": "Intet filter er anvendt",
	"filterBarDefButton": "Definér filter",
	"waiFilterBarDefButton": "Filtrér tabellen",
	"a11yFilterBarDefButton": "Filtrér...",
	"filterBarClearButton": "Ryd filter",
	"waiFilterBarClearButton": "Ryd filtret",
	"closeFilterBarBtn": "Luk filtreringslinje",
	"clearFilterMsg": "Dette fjerner filtret og viser alle tilgængelige records.",
	"anyColumnOption": "Enhver kolonne",
	"trueLabel": "Sand",
	"falseLabel": "Falsk",
	"radioTrueLabel": "Værdi sand",
	"radioFalseLabel": "Værdi falsk",
	"beginTimeRangeLabel": "Startværdi for tidsinterval",
	"endTimeRangeLabel": "Slutværdi for tidsinterval",
	"beginDateRangeLabel": "Startværdi for datointerval",
	"endDateRangeLabel": "Slutværdi for datointerval",
	"startsWithExpr": "${0}*"
//end v1.x content
});

