({
	ORIENTATION_LABEL: "Retning",
	PORTRAIT: "Stående",
	LANDSCAPE: "Liggende",
	PAGE_LABEL: "Siderækkefølge",
	PAGE_TYPE1: "Oppefra og ned, derefter til højre",
	PAGE_TYPE2: "Venstre mod højre, derefter ned",
	DISPLAY_OPTION_LABEL: "Fremvisningsvalg",
	HEADER: "Overskrift",
	FOOTER: "Sidefod",
	GRIDLINE: "Gitterlinjer",
	MARGINS_LABEL: "Margener",
	TOP: "Top:",
	BOTTOM: "Bund:",
	LEFT: "Venstre:",
	RIGHT: "Højre:",
	PAPER_FORMAT_LABEL: "Papirformat",
	PAPER_SIZE_LABEL: "Papirstr.:",
	HEIGHT: "Højde:",
	WIDTH: "Bredde:",
	
	TOOLTIP1:"Udskriv så mange rækker som siden er lang, flyt derefter på tværs, indtil der ikke er flere kolonner i arket, og flyt derefter ned og til venstre for at udskrive næste gruppe af rækker.",
	TOOLTIP2:"Udskriv så mange kolonner som siden er bred, flyt derefter ned, indtil der ikke er flere rækker i arket, og flyt derefter op og til højre for at udskrive næste gruppe af kolonner.",
	CM_LABEL: "cm",
	LETTER: "Brev",
	LEGAL: "Legal",
	TABLOID: "Tabloid",
	USER: "Bruger",
	SIZE1: "Kuv. #6 3/4",
	SIZE2: "Kuv. Monarch",
	SIZE3: "Kuv. #9",
	SIZE4: "Kuv. #10",
	SIZE5: "Kuv. #11",
	SIZE6: "Kuv. #12",
	SIZE7: "16 kai",
	SIZE8: "32 kai",
	SIZE9: "32 kai stor"
})
	
