({
	stViewClient:"Открыть клиент Sametime",
	stChatList:"Щелкните, чтобы открыть веб-клиент Sametime в новом окне.",
	stWebClient:"HCL Sametime ",
	stStatusMeeting:"На собрании",
	stStatusAvailable:"Доступен",
	stViewBd:"Показать список друзей Sametime",
	stErrorSTServer:"Ошибка при подключении к Sametime",
	stStatusAway:"Нет на месте",
	stLConnLogIn:"Войдите в HCL Connections для просмотра состояния в Sametime",
	stActionBar:"Панель действий Sametime",
	stStatusBusy:"Занят",
	stLogin:"Вход в Sametime",
	stUserOffline:"Не в сети",
	stStartChat:"Щелкните здесь, чтобы начать разговор",
	stLogout:"Выход из Sametime",
	stDisconnect:"Отключиться от Sametime",
	stViewSTActions:"Щелкните для просмотра действий Sametime",
	stError:"Возникла ошибка. Служба Sametime недоступна.",
	stUnableToConnect:"Не удалось подключиться к Sametime. ",
	stConnect:"Подключиться к Sametime",
	stNoStatuAvailable:"Состояние в Sametime недоступно",
	stStatusdnt:"Не беспокоить",
	stLoadingSTStatus:"Загрузка состояния в Sametime...",
	stShareAs:"Совместный доступ к документу...",
	stShareDlgTitle:"Поделиться документом через Sametime...",
	stShareDlgMsgTemplate:"На каком уровне следует предоставить 'совместный доступ к ${file_name}' для ${contact_name}?",
	stShareEditor:"Редактор",
	stShareReader:"Читатель",
	stShareSuccessTemplate:"${contact_name}, мне бы хотелось поделиться с вами документом '${file_name}':\n<a href=\"${document_link}\">${document_link}</a>"
})
