/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
    Arrow01_Gray: "화살표 01 회색",
    Arrow02_Gray: "화살표 02 회색",
    Arrow03_Red: "화살표 03 빨간색",
    Arrow04_Blue: "화살표 04 파란색",
    Arrow05_Blue: "화살표 05 파란색",
    Arrow06_Yellow: "화살표 06 노란색",
    Arrow07_Red: "화살표 07 빨간색",
    Arrow08_Gray: "화살표 08 회색",
    Arrow09_Orange: "화살표 09 주황색",
    Arrow10_Blue: "화살표 10 파란색",
    Arrow11_Blue: "화살표 11 파란색",
    Arrow12_Green: "화살표 12 녹색",
    Arrow13_Blue: "화살표 13 파란색",
    Arrow14_Green: "화살표 14 녹색",
    Arrow15_Orange: "화살표 15 주황색",
    Arrow16_Gray: "화살표 16 회색",
    CircleArrow01_Green: "원 화살표 01 녹색",
    CircleArrow02_Multi: "원 화살표 02 다중",
    CircleArrow03_Multi: "원 화살표 03 다중",
    CircleArrow04_Multi: "원 화살표 04 다중",
    CircleArrow05_Multi: "원 화살표 05 다중",
    CircleArrow06_Multi: "원 화살표 06 다중",
    CircleArrow07_Blue: "원 화살표 07 파란색",
    CircleArrow08_Green: "원 화살표 08 녹색",
    CircleArrow09_Multi: "원 화살표 09 다중",
    CurvedArrow01_Gray: "곡선 화살표 01 회색",
    CurvedArrow02_Blue: "곡선 화살표 02 파란색",
    CurvedArrow03_Blue: "곡선 화살표 03 파란색",
    CurvedArrow04_Orange: "곡선 화살표 04 주황색",
    CurvedArrow05_Red: "곡선 화살표 05 빨간색",
    CurvedArrow06_Blue: "곡선 화살표 06 파란색",
    CurvedArrow07_Purple: "곡선 화살표 07 보라색",
    CurvedArrow08_Green: "곡선 화살표 08 녹색",
    CurvedArrow09_Gray: "곡선 화살표 09 회색",
    CurvedArrow10_Blue: "곡선 화살표 10 파란색",
    CurvedArrow11_Orange: "곡선 화살표 11 주황색",
    CurvedArrow12_Blue: "곡선 화살표 12 파란색",
    CurvedArrow13_Green: "곡선 화살표 13 녹색",
    CurvedArrow14_Brown: "곡선 화살표 14 갈색",
    CurvedArrow15_Blue: "곡선 화살표 15 파란색",
    CurvedArrow16_Gray: "곡선 화살표 16 회색",
    CurvedArrow17_Gray: "곡선 화살표 17 회색",
    CurvedArrow18_Gray: "곡선 화살표 18 회색",
    CurvedArrow19_Gray: "곡선 화살표 19 회색",
    CurvedArrow20_Gray: "곡선 화살표 20 회색",
    TrendArrow01_Red: "동향 화살표 01 빨간색",
    TrendArrow02_Green: "동향 화살표 02 녹색",
    TrendArrow03_Orange: "동향 화살표 03 주황색",
    TrendArrow04_Red: "동향 화살표 04 빨간색",
    TrendArrow05_Orange: "동향 화살표 05 주황색",
    TrendArrow06_Blue: "동향 화살표 06 파란색",
    TrendArrow07_Orange: "동향 화살표 07 주황색",
    TrendArrow08_Yellow: "동향 화살표 08 노란색",
    TrendArrow09_Blue: "동향 화살표 09 파란색",
    TrendArrow10_Blue: "동향 화살표 10 파란색",
    TrendArrow11_Blue: "동향 화살표 11 파란색",
    TrendArrow12_Blue: "동향 화살표 12 파란색",
    TrendArrow13_Red: "동향 화살표 13 빨간색",
    TrendArrow14_Multi: "동향 화살표 14 다중",
    TrendArrow15_Blue: "동향 화살표 15 파란색",
    Bullet01_Circle_DarkRed: "글머리 기호 01 원 진한 빨간색",
    Bullet02_Circle_Blue: "글머리 기호 02 원 파란색",
    Bullet03_Circle_Green: "글머리 기호 03 원 녹색",
    Bullet04_Square_Black: "글머리 기호 04 정사각형 검은색",
    Bullet05_Square_Orange: "글머리 기호 05 정사각형 주황색",
    Bullet06_Square_Purple: "글머리 기호 06 정사각형 보라색",
    Bullet07_Diamond_Blue: "글머리 기호 07 다이아몬드 파란색",
    Bullet08_Diamond_LightBlue: "글머리 기호 08 다이아몬드 밝은 파란색",
    Bullet09_Diamond_Red: "글머리 기호 09 다이아몬드 빨간색",
    Bullet10_Star_Yellow: "글머리 기호 10 별 노란색",
    Bullet11_Star_Blue: "글머리 기호 11 별 파란색",
    Bullet12_Triangle_Blue: "글머리 기호 12 삼각형 파란색",
    Bullet13_Triangle_DarkGreen: "글머리 기호 13 삼각형 진한 녹색",
    Bullet14_Arrow_Red: "글머리 기호 14 화살표 빨간색",
    Bullet15_Arrow_Blue: "글머리 기호 15 화살표 파란색",
    Bullet16_Box_Blue: "글머리 기호 16 상자 파란색",
    Bullet17_Box_Red: "글머리 기호 17 상자 빨간색",
    Bullet18_Asterisk_LightBlue: "글머리 기호 18 별표 밝은 파란색",
    Bullet19_Leaves_Red: "글머리 기호 19 잎 빨간색",
    Bullet20_Target_Blue: "글머리 기호 20 과녁 파란색",
    Bullet21_Arrow_Blue: "글머리 기호 21 화살표 파란색",
    Bullet22_Arrow_DarkBlue: "글머리 기호 22 화살표 진한 파란색",
    Bullet23_Arrow_Brown: "글머리 기호 23 화살표 갈색",
    Bullet24_Flag_Red: "글머리 기호 24 깃발 빨간색",
    Bullet25_Flag_Green: "글머리 기호 25 깃발 녹색",
    Bullet26_X_Red: "글머리 기호 26 X 빨간색",
    Bullet27_X_Black: "글머리 기호 27 X 검은색",
    Bullet28_Checkmark_Green: "글머리 기호 28 선택 표시 녹색",
    Bullet29_Checkmark_Blue: "글머리 기호 29 선택 표시 파란색",
    Bullet30_Square_DarkRed: "글머리 기호 30 정사각형 진한 빨간색",
    camera: "카메라",
    computer1: "컴퓨터 1",
    computer2: "컴퓨터 2",
    computer3: "컴퓨터 3",
    Computer_Cloud: "컴퓨터 클라우드",
    Computer_Desktop: "컴퓨터 데스크탑",
    Computer_Laptop_Black: "컴퓨터 랩탑 검은색",
    Computer_Laptop_Silver: "컴퓨터 랩탑 은색",
    Database: "데이터베이스",
    evelope: "봉투",
    newspapers: "신문",
    openevelope: "열려 있는 봉투",
    Server: "서버",
    speaker: "스피커",
    WirelessAccessPoint: "무선 액세스 지점",
    Cycle01_Transparent: "사이클 01 투명",
    Cycle02_Transparent_Blue: "사이클 02 투명 파란색",
    Cycle03_Blue: "사이클 03 파란색",
    Cycle04_Blue: "사이클 04 파란색",
    Cycle05: "사이클 05",
    Cycle06: "사이클 06",
    Cycle07: "사이클 07",
    Cycle08_Blue: "사이클 08 파란색",
    Cycle09_Orange: "사이클 09 주황색",
    Donut01_LightBlue: "도넛 01 밝은 파란색",
    Donut02_Blue: "도넛 02 파란색",
    Donut03_Blue: "도넛 03 파란색",
    Donut04_DarkBlue: "도넛 04 진한 파란색",
    Donut05_DarkBlue: "도넛 05 진한 파란색",
    Donut06_Blue: "도넛 06 파란색",
    Donut07_Blue: "도넛 07 파란색",
    Graph: "그래프",
    People01_Blue: "사람 01 파란색",
    People02: "사람 02",
    Pillars01_Orange: "3차원 세로 막대형 01 주황색",
    Pillars02_LightBlue: "3차원 세로 막대형 02 밝은 파란색",
    Process01_Blue: "프로세스 01 파란색",
    Process02_Blue: "프로세스 02 파란색",
    Process03_Blue: "프로세스 03 파란색",
    Process04_GoUp_Blue: "프로세스 04 위로 이동 파란색",
    Process05_GoUp_Red: "프로세스 05 위로 이동 빨간색",
    Process06_GoUp_Yellow: "프로세스 06 위로 이동 노란색",
    Process07_Blue: "프로세스 07 파란색",
    Pyramid01: "피라미드 01",
    Pyramid02_Blue: "피라미드 02 파란색",
    Pyramid03: "피라미드 03",
    Radial01_Green: "방사형 01 녹색",
    Radial02_Green: "방사형 02 녹색",
    Radial03_Sphere: "방사형 03 구",
    Radial04_Sphere_Red: "방사형 04 구 빨간색",
    Radial05_Sphere_Blue: "방사형 05 구 파란색",
    Radial06_Arrows_DarkBlue: "방사형 06 화살표 진한 파란색",
    Radial07_Arrows_DarkBlue: "방사형 07 화살표 진한 파란색",
    Section_Circle: "섹션 원",
    Section_Cubes01: "섹션 정육면체 01",
    Section_Cubes02_Blue: "섹션 정육면체 02 파란색",
    Section_Cubes03_Orange: "섹션 정육면체 03 주황색",
    Section_Cubes04: "섹션 정육면체 04",
    Section_Cubes05: "섹션 정육면체 05",
    Section_Cuboids01_Blue: "섹션 직육면체 01 파란색",
    Section_Cuboids02_Blue: "섹션 직육면체 02 파란색",
    Section_Cuboids03: "섹션 직육면체 03",
    Section_Gears01: "섹션 기어 01",
    Section_Gears02: "섹션 기어 02",
    Section_Gears03: "섹션 기어 03",
    Section_Hexagon04_Orange: "섹션 육각형 04 주황색",
    Section_Hexagons01: "섹션 육각형 01",
    Section_Hexagons02_Blue: "섹션 육각형 02 파란색",
    Section_Hexagons03_Blue: "섹션 육각형 03 파란색",
    Section_Leaves01_LightBlue: "섹션 잎 01 밝은 파란색",
    Section_Leaves02_Green: "섹션 잎 02 녹색",
    Section_Pasters01: "섹션 스티커 01",
    Section_Pasters02_Blue: "섹션 스티커 02 파란색",
    Section_Puzzle01: "섹션 퍼즐 01",
    Section_Puzzle02: "섹션 퍼즐 02",
    Section_Puzzle03: "섹션 퍼즐 03",
    Section_Rectangles: "섹션 직사각형",
    Section_Squares: "섹션 정사각형",
    Section_Triangle: "섹션 삼각형",
    Target: "과녁",
    Venn01: "벤 다이어그램 01",
    Venn02: "벤 다이어그램 02",
    Venn03: "벤 다이어그램 03",
    Venn04: "벤 다이어그램 04",
    Venn05: "벤 다이어그램 05",
    Venn06_Blue: "벤 다이어그램 06 파란색",
    Venn07_Blue: "벤 다이어그램 07 파란색",
    Venn08: "벤 다이어그램 08",
    Blackboard: "칠판",
    Books: "책",
    Books1: "책 1",
    books2: "책 2",
    Chalk: "분필",
    clipboard: "클립보드",
    clock: "시계",
    Globe: "지구본",
    Glue: "풀",
    GraduationCap: "학사모",
    magnifyingglass: "돋보기",
    Microscope: "현미경",
    Notebook: "노트",
    notepad1: "메모장 1",
    notepad2: "메모장 2",
    notepad3: "메모장 3",
    PaperClip_Blue: "종이 클립 파란색",
    PaperClip_Red: "종이 클립 빨간색",
    Pencil: "연필",
    Ruler: "자",
    TestTubes: "시험관",
    thumbtack: "압정",
    clouds: "구름",
    DrippingFaucet: "물 떨어지는 수도꼭지",
    Earth: "지구",
    EndangeredAnimals1: "멸종 위기 동물 1",
    EndangeredAnimals2: "멸종 위기 동물 2",
    GreenCar: "친환경 차",
    GreenFactory: "친환경 공장",
    GreenHouse: "친환경 집",
    Leaf1: "잎 1",
    Leaf2: "잎 2",
    lightbulb: "전구",
    LightBulb_Flourescent_Off: "형광 전구 꺼짐",
    LightBulb_Flourescent_On: "형광 전구 켜짐",
    LightBulb_Standard_Off1: "표준 전구 꺼짐 1",
    LightBulb_Standard_Off2: "표준 전구 꺼짐 2",
    LightBulb_Standard_On: "표준 전구 켜짐",
    lightningcloud: "번개 구름",
    Pollution_Car: "매연 자동차",
    Pollution_Factory: "매연이 나오는 공장",
    Raindrop: "빗방울",
    RecycleBin: "휴지통",
    RecycleSymbol: "재활용 기호",
    RenewableEnergySymbol: "재생 에너지 기호",
    RenewableEnergy_Solar: "재생 에너지 태양광",
    RenewableEnergy_Water: "재생 에너지 물",
    RenewableEnergy_Wind: "재생 에너지 바람",
    sun: "태양",
    Sun1: "태양 1",
    Sun2: "태양 2",
    sundandcloud: "태양과 구름",
    world: "세계",
    Agreement: "계약",
    ATM01: "ATM 01",
    ATM02: "ATM 02",
    Balance_Balanced1: "저울 좌우 대칭 1",
    Balance_Balanced2: "저울 좌우 대칭 2",
    Balance_Unbalanced1: "저울 좌우 비대칭 1",
    Balance_Unbalanced2: "저울 좌우 비대칭 2",
    Calculator: "계산기",
    Chart_Decrease1: "차트 감소 1",
    Chart_Decrease2: "차트 감소 2",
    Chart_Increase1: "차트 증가 1",
    Chart_Increase2: "차트 증가 2",
    Chart_Plateau: "플래토 차트",
    Check: "수표",
    Contract: "계약서",
    CreditCard_Black: "신용카드 검은색",
    CreditCard_Cut: "신용카드 잘림",
    CreditCard_Gold: "신용카드 금색",
    Currency_Dollar: "지폐 달러 한 장",
    Currency_Dollars: "지폐 달러 여러 장",
    Currency_Stack: "지폐 더미",
    Currency_StackCoins: "지폐 동전 더미",
    GoldBar: "금괴",
    GoldBar_Stack: "금괴 더미",
    MoneyBag01: "돈 주머니 01",
    MoneyBag02: "돈 주머니 02",
    PercentSign: "퍼센트 부호",
    PiggyBank01_Broken: "돼지 저금통 01 깨짐",
    PiggyBank02_Broken: "돼지 저금통 02 깨짐",
    PiggyBank_Coins: "돼지 저금통 동전",
    PiggyBank_Currency: "돼지 저금통 지폐",
    Portfolio: "포트폴리오",
    PriceTag: "가격표",
    Safe_Closed: "금고 닫힘",
    Safe_Empty: "금고 비어 있음",
    Safe_Full: "금고 가득 참",
    Seal_Gold: "도장 금색",
    Seal_Red: "도장 빨간색",
    Seal_Silver: "도장 은색",
    Wallet_Empty: "지갑 비어 있음",
    Wallet_Full1: "지갑 가득 참 1",
    Wallet_Full2: "지갑 가득 참 2",
    BusinessPerson_Female6: "회사원 여성 6",
    BusinessPerson_Male3: "회사원 남성 3",
    Computer_User_Female1: "컴퓨터 사용자 여성 1",
    ConstructionWorker2: "건축 노동자 2",
    Presenter_Female1: "발표자 여성 1",
    Component_Circle01_Transparent_DarkBlue: "구성요소 원 01 투명 진한 파란색",
    Component_Circle02_Transparent_Bule: "구성요소 원 02 투명 파란색",
    Component_Circle03_Transparent_Green: "구성요소 원 03 투명 녹색",
    Component_Circle04_Transparent_Orange: "구성요소 원 04 투명 주황색",
    Component_Circle05_Transparent_Red: "구성요소 원 05 투명 빨간색",
    Component_Cube01_DarkBlue: "구성요소 정육면체 01 진한 파란색",
    Component_Cube02_LightBlue: "구성요소 정육면체 02 밝은 파란색",
    Component_Cube03_Green: "구성요소 정육면체 03 녹색",
    Component_Cube04_Orange: "구성요소 정육면체 04 주황색",
    Component_Cube05_DarkRed: "구성요소 정육면체 05 진한 빨간색",
    Component_Cuboid01_DarkBlue: "구성요소 직육면체 01 진한 파란색",
    Component_Cuboid02_Blue: "구성요소 직육면체 02 파란색",
    Component_Cuboid03_Green: "구성요소 직육면체 03 녹색",
    Component_Cuboid04_Orange: "구성요소 직육면체 04 주황색",
    Component_Cuboid05_Red: "구성요소 직육면체 05 빨간색",
    Component_Gear01_DarkBlue: "구성요소 기어 01 진한 파란색",
    Component_Gear02_LightBlue: "구성요소 기어 02 밝은 파란색",
    Component_Gear03_Green: "구성요소 기어 03 녹색",
    Component_Gear04_DarkRed: "구성요소 기어 04 진한 빨간색",
    Component_Gear05_Orange: "구성요소 기어 05 주황색",
    Component_Person01_DarkBlue: "구성요소 사람 01 진한 파란색",
    Component_Person02_Blue: "구성요소 사람 02 파란색",
    Component_Person03_Green: "구성요소 사람 03 녹색",
    Component_Person04_DarkRed: "구성요소 사람 04 진한 빨간색",
    Component_Person05_Orange: "구성요소 사람 05 주황색",
    Component_PuzzlePiece01_DarkBlue: "구성요소 퍼즐 조각 01 진한 파란색",
    Component_PuzzlePiece02_Blue: "구성요소 퍼즐 조각 02 파란색",
    Component_PuzzlePiece03_Green: "구성요소 퍼즐 조각 03 녹색",
    Component_PuzzlePiece04_Red: "구성요소 퍼즐 조각 04 빨간색",
    Component_PuzzlePiece05_Orange: "구성요소 퍼즐 조각 05 주황색",
    Component_Sphere01_DarkBlue: "구성요소 구 01 진한 파란색",
    Component_Sphere02_LightBlue: "구성요소 구 02 밝은 파란색",
    Component_Sphere03_Green: "구성요소 구 03 녹색",
    Component_Sphere04_DarkRed: "구성요소 구 04 진한 빨간색",
    Component_Sphere05_Orange: "구성요소 구 05 주황색",
    Book: "책",
    Box01: "상자 01",
    Box02: "상자 02",
    Bulb01_Yellow: "전구 01 노란색",
    Bulb02_Yellow: "전구 02 노란색",
    Calendar: "달력",
    Chart: "차트",
    Clipboard: "클립보드",
    Clock: "시계",
    Compass: "나침반",
    Flag01_Red: "깃발 01 빨간색",
    Flag02_Green: "깃발 02 녹색",
    Flag03_Blue: "깃발 03 파란색",
    Gift: "선물",
    House: "집",
    Icon_Computer01_White: "아이콘 컴퓨터 01 흰색",
    Icon_Computer02_Black: "아이콘 컴퓨터 02 검은색",
    Icon_Disk01_Blue: "아이콘 디스크 01 파란색",
    Icon_Disk02_Green: "아이콘 디스크 02 녹색",
    Icon_Document01_Grey: "아이콘 문서 01 회색",
    Icon_Document02_Grey: "아이콘 문서 02 회색",
    Icon_Document03_Blue: "아이콘 문서 03 파란색",
    Icon_Document04_Blue: "아이콘 문서 04 파란색",
    Icon_Envelope01_Blue: "아이콘 봉투 01 파란색",
    Icon_Envelope02_Yellow: "아이콘 봉투 02 노란색",
    Icon_Envelope03_Open_Yellow: "아이콘 봉투 03 열림 노란색",
    Icon_Envelope04_Open_Yellow: "아이콘 봉투 04 열림 노란색",
    Icon_Folder01_Yellow: "아이콘 폴더 01 노란색",
    Icon_Folder02_Yellow: "아이콘 폴더 02 노란색",
    Icon_Folder03_Open_Yellow: "아이콘 폴더 03 열림 노란색",
    Icon_Folder04_Open_Yellow: "아이콘 폴더 04 열림 노란색",
    Icon_Gear01_Grey: "아이콘 기어 01 회색",
    Icon_Gear02_Blue: "아이콘 기어 02 파란색",
    Icon_Network01_Blue: "아이콘 네트워크 01 파란색",
    Icon_Network02: "아이콘 네트워크 02",
    Icon_Pencil01: "아이콘 연필 01",
    Icon_Pencil02: "아이콘 연필 02",
    Icon_Printer01_White: "아이콘 프린터 01 흰색",
    Icon_Printer02_Black: "아이콘 프린터 02 검은색",
    Key01: "열쇠 01",
    Key02: "열쇠 02",
    Lock01_Yellow: "자물쇠 01 노란색",
    Lock02_Yellow: "자물쇠 02 노란색",
    Lock03_Blue: "자물쇠 03 파란색",
    Lock04_Blue: "자물쇠 04 파란색",
    Magnet: "자석",
    MagnifyingGlass: "돋보기",
    Medal: "메달",
    Notebook: "노트",
    Phone: "전화",
    PieChart: "원형 차트",
    Pin: "핀",
    PuzzlePiece: "퍼즐 조각 한 개",
    PuzzlePieces: "퍼즐 조각 여러 개",
    Roadblock: "바리케이드",
    Scissors: "가위",
    Shield01: "방패 01",
    Shield02_Orange: "방패 02 주황색",
    Shield03_Blue: "방패 03 파란색",
    Sign_Ban01: "부호 금지 01",
    Sign_Ban02: "부호 금지 02",
    Sign_CheckBox01: "부호 선택란 01",
    Sign_CheckBox02_Unchecked: "부호 선택란 02 선택 안됨",
    Sign_Checkmark01_Green: "부호 선택 표시 01 녹색",
    Sign_Checkmark02_Green: "부호 선택 표시 02 녹색",
    Sign_DoNotEnter: "부호 입장 불가",
    Sign_Error01: "부호 오류 01",
    Sign_Error02: "부호 오류 02",
    Sign_ExclamationPoint01_Red: "부호 느낌표 01 빨간색",
    Sign_ExclamationPoint02_Orange: "부호 느낌표 02 주황색",
    Sign_Help01_Green: "부호 도움말 01 녹색",
    Sign_Help02_Blue: "부호 도움말 02 파란색",
    Sign_Information: "부호 정보",
    Sign_Null: "부호 널",
    Sign_QuestionMark01_Blue: "부호 물음표 01 파란색",
    Sign_QuestionMark02_Red: "부호 물음표 02 빨간색",
    Sign_RadioButton01: "부호 단일 선택 단추 01",
    Sign_RadioButton02_Unchecked: "부호 단일 선택 단추 02 선택 안됨",
    Sign_Warning01_Red: "부호 경고 01 빨간색",
    Sign_Warning02_Orange: "부호 경고 02 주황색",
    Sign_X01_Red: "부호 X 01 빨간색",
    Sign_X02_Red: "부호 X 02 빨간색",
    Star_Yellow: "별 노란색",
    Wrench: "렌치",
    Airplane_Blue: "비행기 파란색",
    Bicycle_Blue: "자전거 파란색",
    Bus: "버스",
    Canoe_Blue: "카누 파란색",
    Car_Red: "자동차 빨간색",
    Helicopter_Blue: "헬리콥터 파란색",
    Motorcycle_Red: "오토바이 빨간색",
    Pedestrian_Blue: "보행자 파란색",
    PersonalTransporter_Green: "개인 운송차 녹색",
    Sailboat_Red: "요트 빨간색",
    Scooter_Orange: "스쿠터 주황색",
    Train_Red: "기차 빨간색",
    Truck_Blue: "트럭 파란색",
    
    aria_category_selector: "이미지 카테고리 옵션",
    filterImageGallery: "이미지 갤러리 필터"

})
