﻿/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        fileMenu: "파일",
        fileMenu_New: "새로 작성",
        fileMenu_NewDocument: "문서",
        fileMenu_NewFromTemplate: "템플리트에서",
        fileMenu_NewDocumentfromTemplate: "템플리트에서 문서",
        fileMenu_NewPresentation: "프리젠테이션",
        fileMenu_NewPresentationfromTemplate: "템플리트에서 프리젠테이션",
        fileMenu_NewSpreadsheet: "스프레드시트",
        fileMenu_NewSpreadsheetFromTemplate: "템플리트에서 스프레드시트",
        fileMenu_Open: "열기",
        fileMenu_Import: "가져오기...",
        //	fileMenu_Close: "Close",
        fileMenu_Discard: "마지막 버전으로 되돌리기",
        fileMenu_ClearTrackChange: "변경 표시 제거",
        fileMenu_SpreadsheetSettings: "문서 로케일 설정...",
        filemenu_revisionhistory: "개정",
        fileMenu_Save: "저장",
        fileMenu_SaveAs: "복사...",
        fileMenu_AutoPublish: "자동으로 공개",
        fileMenu_AutoCheckIn: "자동으로 체크인",
        fileMenu_PublishVersion: "지금 공개",
        fileMenu_AutoPublish2: "저장소에 자동 저장",
        //	fileMenu_AutoPublish_Tips: "Makes your changes available to readers at the end of each editing session.",
        fileMenu_PublishVersion2: "저장소에 지금 저장",
        fileMenu_AutoPublish3: "${0}에 자동 저장",
        fileMenu_PublishVersion3: "${0}에 지금 저장",      
        fileMenu_SubmitForReview: "검토용으로 제출...",
        fileMenu_CheckinVersion: "체크인...",
        fileMenu_Unlock: "잠금 해제",
        //	fileMenu_SaveAsDraft: "as Draft",
        //	fileMenu_SaveInMyDocs: "in My Documents",
        //	fileMenu_SaveToSymphony: "to Lotus Symphany",
        fileMenu_DownloadAs: "다음 형식으로 다운로드",
        fileMenu_PDF: "PDF",
        fileMenu_ODF: "ODF",
        fileMenu_DOC: "Microsoft Word 97- 2007(*.doc)",
        fileMenu_ODS: "ODS",
        fileMenu_XLS: "Microsoft Excel 97-2007(*.xls) ",
        fileMenu_ShareWith: "공유...",
        fileMenu_ExportAsPDF: "PDF",
        fileMenu_ExportAsODF: "ODF",
        fileMenu_ExportAsPPT: "Microsoft Powerpoint 97- 2007(*.ppt)",
        //	fileMenu_WebPreview: "Web Preview",
        fileMenu_PrintToPDF: "PDF로 인쇄...",
        fileMenu_ViewFileDetails: "파일 세부사항 보기...",
        fileMenu_RecentFile: "최근 파일",
        fileMenu_Open: "열기",
        fileMenu_Download: "다운로드",
        fileMenu_Print: "인쇄",
        fileMenu_Export: "내보내기",
        fileMenu_ExportToCSV: "CSV",
        fileMenu_ExportToPDF: "PDF(.pdf)",
        fileMenu_ExportToMarkdown: "마크다운(.md)",
        fileMenu_ExportToMS: "Microsoft Office 형식(.${FILEEXTENSION})",
        fileMenu_ExportToODF: "Open Document 형식(.${FILEEXTENSION})",
        fileMenu_PgSetup: "페이지 설정...",

        editMenu: "편집",
        editMenu_Undo: "실행 취소",
        editMenu_Redo: "다시 실행",
        editMenu_Cut: "잘라내기",
        editMenu_Copy: "복사",
        editMenu_Paste: "붙여넣기",
        editMenu_DeleteSlide: "슬라이드 삭제",
        editMenu_SelectAll: "모두 선택",
        editMenu_Find: "찾기...",
        editMenu_Replace: "바꾸기...",
        editMenu_FindReplace: "찾기 및 바꾸기...",
        editMenu_EditLink: "링크 추가 또는 편집",
        editMenu_DeleteSheet: "시트 삭제...",
        editMenu_RenameSheet: "시트 이름 변경...",
        editMenu_HideSheet: "시트 숨기기",
        editMenu_MoveSheet: "시트 이동...",
        editMenu_DeleteRow: "행 삭제",
        editMenu_DeleteColumn: "열 삭제",
        editMenu_DeleteCellLeft: "셀 삭제 후 왼쪽으로 이동",
        editMenu_DeleteCellUp: "셀 삭제 후 위로 이동",
        editMenu_ClearCell: "컨텐츠 삭제",

        viewMenu: "보기",
        viewMenu_Master: "마스터",
        viewMenu_Notifications: "알림",
        viewMenu_SlideSorter: "슬라이드 정렬기",
        viewMenu_SpeakerNotes: "발표자 메모",
        viewMenu_Toolbar_Basic: "기본",
        viewMenu_Toolbar_Advanced: "고급",
        viewMenu_Toolbar_None: "없음",
        viewMenu_Toolbar: "도구 모음",
        viewMenu_Statusbar: "상태 표시줄",
        viewMenu_Navigator: "네비게이터...",
        //viewMenu_Sidebar: "Sidebar",
        viewMenu_ShowHideIndicators: "공동 편집 표시기 표시",
        viewMenu_Assignment: "지정 표시기",
        viewMenu_Bookmark: "책갈피",
        viewMenu_Coediting: "공동 편집 강조표시",
        viewMenu_Rulers: "눈금자",
        viewMenu_WebLayout: "웹 레이아웃",
        viewMenu_AutomaticSpellCheck: "입력 시 맞춤법 검사",
        viewMenu_Formulabar: "수식 표시줄",
        viewMenu_moveRight: "Enter키를 누르면 커서를 오른쪽으로 이동",
        viewMenu_showFullString: "셀에서 컨텐츠 확장",
        viewMenu_Doc: "문서 보기",
        viewMenu_Templates: "템플리트",
        viewMenu_GridLines: "격자선 숨기기",
        viewMenu_UnsupportWarning: "지원되지 않는 기능 메시지 표시",
        viewMenu_HiddenSheets: "숨겨진 시트",
        viewMenu_FreezeRows: "행 고정",
        viewMenu_FreezeColumns: "열 고정",
        viewMenu_NoFrozenRows: "고정된 행이 없음",
        viewmenu_NoFrozenColumns: "고정된 열이 없음",
        viewMenu_FreezeXRows: "${0}개 행 고정",
        viewMenu_FreezeOneRow: "${0}개 행 고정",
        viewMenu_FreezeXColumns: "${0}개 열 고정",
        viewMenu_FreezeOneColumn: "${0}개 열 고정",
        viewMenu_CarriageReturn: "형식화 표시",
        viewMenu_Navigation: "탐색 패널",
        viewMenu_ACL: "편집 가능한 영역",
        viewMenu_GridOnOff: "격자선",
        viewMenu_ObserverMode: '관찰자 모드',

        createMenu: "삽입",
        createMenu_NewSlide: "새 슬라이드",
        createMenu_DuplicateSlide: "중복 슬라이드",
        createMenu_ImageFromFile: "이미지...",
        createMenu_TextBox: "텍스트 상자",
        createMenu_Shape: "형태",
        createMenu_break: "분할",
        createMenu_RowAbove: "행 위",
        createMenu_RowBelow: "행 아래",
        createMenu_ColumnRight: "열 오른쪽",
        createMenu_ColumnLeft: "열 왼쪽",
        createMenu_Sheet: "시트...",
        createMenu_Image: "이미지...",
        createMenu_Comments: "댓글...",
        createMenu_WebLink: "웹 링크...",
        createMenu_SpecialCharacter: "특수 문자...",
        createMenu_Function: "함수...",
        createMenu_Fromtemplate: "템플리트에서 작성",

        insertMenu: "삽입",
        insertMenu_break: "페이지 구분",
        insertMenu_sectionbreak: "섹션 분할",
        insertMenu_Bookmark: "책갈피 지정...",
        insertMenu_WebLink: "링크...",
        insertMenu_SpecialCharacter: "특수 문자...",
        insertMenu_HorizontalLine: "가로선",
        insertMenu_Header: "머리글",
        insertMenu_Footer: "바닥글",
        insertMenu_TableOfContents: "목차",

        insertMenu_HeaderFooter: "머리글/바닥글",
        insertMenu_HF_Edit: "편집",
        insertMenu_HF_Hide: "숨기기",
        insertMenu_Endnotes: "미주",
        insertMenu_RowAbove: "행 위",
        insertMenu_PageNumber: "페이지 번호",
        insertMenu_PageNumberTop: "페이지의 시작",
        insertMenu_PageNumberBottom: "페이지의 끝",
        insertMenu_PageNumberCurr: "현재 위치",
        insertMenu_TotalPageNumber: "1/N 페이지",
        insertMenu_Date: "날짜...",
        insertMenu_Time: "시간...",
        insertMenu_Fields: "필드",
        //    insertMenu_Comment: "Comment",
        insertMenu_CellRight: "셀 및 오른쪽으로 이동",
        insertMenu_CellDown: "셀 및 아래로 이동",
        insertMenu_RowBelow: "행 아래",
        insertMenu_ColumnBefore: "열 앞",
        insertMenu_ColumnAfter: "열 뒤",
        insertMenu_Sheet: "시트...",
        insertMenu_Image: "이미지...",
        insertMenu_DuplicateSheet: "시트 복제",
        insertMenu_Function: "함수",
        insertMenu_FunctionSum: "SUM",
        insertMenu_FunctionAverage: "AVERAGE",
        insertMenu_FunctionCount: "COUNT",
        insertMenu_FunctionMax: "MAX",
        insertMenu_FunctionMin: "MIN",
        insertMenu_FunctionMore: "추가 함수...",
        insertMenu_NameRange: "이름 지정된 범위",
        insertMenu_NameRangeNew: "새 범위...",
        insertMenu_NameRangeManage: "범위 관리...",
        insertMenu_Chart: "차트...",

        contextMenu_insertCellRight: "셀 삽입 후 오른쪽으로 이동",
        contextMenu_insertCellDown: "셀 삽입 후 아래로 이동",
        contextMenu_InsertRowAbove: "위에 행 삽입",
        contextMenu_InsertRowBelow: "아래에 행 삽입",
        contextMenu_InsertColumnBefore: "앞에 열 삽입",
        contextMenu_InsertColumnAfter: "뒤에 열 삽입",
        contextMenu_DownloadImage: "이미지로 다운로드",

        formatMenu: "형식",
        formatMenu_Columns: "열",
        formatMenu_DefaultFormatting: "기본 형식화",
        formatMenu_Template: "스타일...",
        contextMenu_Template: "테이블 스타일...",
        formatMenu_LineSpacing: "줄 간격",
        formatMenu_LineSpacing1: "1",
        formatMenu_LineSpacing12: "1.2",
        formatMenu_LineSpacing15: "1.5",
        formatMenu_LineSpacing2: "2",
        formatMenu_LineSpacing25: "2.5",
        formatMenu_LineSpacing3: "3",
        formatMenu_TextProperties: "텍스트 특성",
        formatMenu_PageBreakBefore: "앞에 페이지 구분",
        formatMenu_KeepLines: "동일한 행 유지",
        formatMenu_WidowControl: "단락의 첫 줄/마지막 줄 분리 방지",
        formatMenu_Pagination: "단락 특성",
        formatMenu_Bold: "굵은체",
        formatMenu_Italic: "기울임꼴",
        formatMenu_Underline: "밑줄",
        formatMenu_Strikethrough: "취소선",
        formatMenu_IncreaseSize: "글꼴 크기 늘리기",
        formatMenu_DecreaseSize: "글꼴 크기 줄이기",
        formatMenu_ImageProperties: "이미지 특성...",
        formatMenu_ChartProperties: "차트 특성...",
        formatMenu_EditChart: "차트 편집",
        formatMenu_InsertChart: "차트 삽입",
        formatMenu_Properties: "특성...",
        formatMenu_Heading: "표제",
        formatMenu_Normal: "일반",
        formatMenu_Title: "제목",
        formatMenu_Subtitle: "부제",
        formatMenu_Heading1: "표제 1",
        formatMenu_Heading2: "표제 2",
        formatMenu_Heading3: "표제 3",
        formatMenu_Heading4: "표제 4",
        formatMenu_Heading5: "표제 5",
        formatMenu_Heading6: "표제 6",
        formatMenu_Heading7: "표제 7",
        formatMenu_Heading8: "표제 8",
        formatMenu_Heading9: "표제 9",
        formatMenu_BulletedList: "글머리 기호 목록",
        formatMenu_NumberedList: "번호 매기기 목록",
        formatMenu_OutLine: "다단계 목록",
        formatMenu_Superscript: "윗첨자",
        formatMenu_Subscript: "아래첨자",
        formatMenu_Align: "맞춤",
        formatMenu_Left: "왼쪽",
        formatMenu_Right: "오른쪽",
        formatMenu_Center: "가운데",
        formatMenu_Justify: "양쪽 맞춤",
        formatMenu_Text_Direction: "텍스트 방향",
        formatMenu_Ltr: "왼쪽에서 오른쪽",
        formatMenu_Rtl: "오른쪽에서 왼쪽",
        formatMenu_LineSpacing: "줄 간격",
        formatMenu_LineSpacing1: "1.0",
        formatMenu_LineSpacing115: "1.15",
        formatMenu_LineSpacing15: "1.5",
        formatMenu_LineSpacing2: "2.0",
        formatMenu_LineSpacing25: "2.5",
        formatMenu_LineSpacing3: "3.0",
        formatMenu_Top: "맨 위",
        formatMenu_Bottom: "아래",
        formatMenu_Middle: "중간",
        formatMenu_Direction: "텍스트 방향",
        formatMenu_Rtl: "오른쪽에서 왼쪽",
        formatMenu_Ltr: "왼쪽에서 오른쪽",
        formatMenu_Auto: "컨텍스트",
        formatMenu_SheetDirection: "용지 방향",
        formatMenu_SheetRtl: "오른쪽에서 왼쪽",
        formatMenu_SheetLtr: "왼쪽에서 오른쪽",
        formatMenu_Indent: "들여쓰기 늘리기",
        formatMenu_DecreaseIndent: "들여쓰기 줄이기",
        formatMenu_ClearFormat: "형식화 지우기",
        formatMenu_RowHeight: "행 높이",
        formatMenu_ColumnWidth: "열 너비",
        formatMenu_ShowRow: "행 표시",
        formatMenu_HideRow: "행 숨기기",
        formatMenu_ShowColumn: "열 표시",
        formatMenu_HideColumn: "열 숨기기",
        formatMenu_WrapText: "텍스트 줄 바꾸기",
        formatMenu_Number: "숫자",
        formatMenu_FontArial: "Arial",
        formatMenu_FontComicSansMS: "Comic Sans MS",
        formatMenu_FontCourierNew: "Courier New",
        formatMenu_FontGeorgia: "Georgia",
        formatMenu_FontLucidaSansUnicode: "Lucida Sans Unicode",
        formatMenu_FontTahoma: "Tahoma",
        formatMenu_FontTimesNewRoman: "Times New Roman",
        formatMenu_FontTrebuchetMS: "Trebuchet MS",
        formatMenu_FontVerdana: "Verdana",
        formatMenu_FontName: "글꼴",

        layoutMenu: "레이아웃",
        layoutMenu_SlideLayout: "슬라이드 레이아웃...",
        layoutMenu_SlideDesign: "마스터 스타일...",
        layoutMenu_DefaultFormatting: "기본 형식화",
        layoutMenu_Textprop_Bold: "굵은체",
        layoutMenu_Textprop_Italic: "기울임꼴",
        layoutMenu_Textprop_Underline: "밑줄",
        layoutMenu_Textprop_Strikethrough: "취소선",
        layoutMenu_TextProp: "텍스트 특성",
        LayoutMenu_RowHeight: "행 높이...",
        LayoutMenu_ColumnWidth: "열 너비...",
        LayoutMenu_ShowRow: "행 표시",
        LayoutMenu_HideRow: "행 숨기기",
        LayoutMenu_RenameSheet: "시트 이름 변경...",
        LayoutMenu_MoveSheet: "시트 이동",

        tableMenu: "테이블",
        tableMenu_Create: "작성...",
        tableMenu_CreateFromTemplate: "템플리트에서 작성",
        tableMenu_Delete: "삭제",
        tableMenu_SetTableColor: "색상 셀",
        tableMenu_CreateTable: "테이블 작성",
        tableMenu_Cell: "셀",
        tableMenu_CellMergeCells: "셀 병합",
        tableMenu_CellAlignLeft: "왼쪽 맞춤",
        tableMenu_CellAlignCenter: "가운데 맞춤",
        tableMenu_CellAlignRight: "오른쪽 맞춤",
        tableMenu_CellClearContents: "컨텐츠 지우기",
        tableMenu_CellProperties: "셀 특성...",
        tableMenu_Row: "행",
        tableMenu_InsertRowAbove: "위에 행 삽입",
        tableMenu_InsertRowBelow: "아래에 행 삽입",
        tableMenu_MoveRowAbove: "위로 행 이동",
        tableMenu_MoveRowBelow: "아래로 행 이동",
        tableMenu_RowInsertRow: "행 삽입...",
        tableMenu_RowInsertRowAbove: "위에 행 삽입",
        tableMenu_RowInsertRowBelow: "아래에 행 삽입",
        tableMenu_RowMoveRowAbove: "위로 행 이동",
        tableMenu_RowMoveRowBelow: "아래로 행 이동",
        tableMenu_RowDelete: "삭제",
        tableMenu_RowRepeat: "머리글 행 반복",
        tableMenu_InsertColumnBefore: "앞에 열 삽입",
        tableMenu_InsertColumnAfter: "뒤에 열 삽입",
        tableMenu_MoveColumnBefore: "왼쪽으로 열 이동",
        tableMenu_MoveColumnAfter: "오른쪽으로 열 이동",
        tableMenu_ResizeColumn: "열 크기 조정",
        tableMenu_ResizeColumns: "열 크기 조정",
        tableMenu_MarkasCategory: "카테고리로 표시",
        tableMenu_ColumnInsertColumn: "열 삽입...",
        tableMenu_ColumnAddColumnBefore: "앞에 열 삽입",
        tableMenu_ColumnAddColumnAfter: "뒤에 열 삽입",
        tableMenu_ColumnMoveColumnAfter: "뒤로 열 이동",
        tableMenu_ColumnMoveColumnBefore: "앞으로 열 이동",
        tableMenu_ColumnDelete: "삭제",
        tableMenu_ColumnSortAscending: "오름차순 정렬",
        tableMenu_ColumnSortDescending: "내림차순 정렬",
        tableMenu_Column: "열",
        tableMenu_Style: "스타일",
        tableMenu_TableProperties: "테이블 특성...",

        teamMenu: "팀",
        teamMenu_AddComment: "주석 추가",
        teamMenu_AssignCells: "셀 지정",
        teamMenu_AssignSection: "섹션 지정",
        teamMenu_EditAssignment: "지정 편집",
        teamMenu_MarkSectionComplete: "섹션을 완료로 표시",
        teamMenu_MarkAssignmentComplete: "지정 완료 표시",
        teamMenu_WorkPrivatelyOnSection: "섹션에서 개인 작업",
        teamMenu_CancelPrivateWork: "개인 작업 취소",
        teamMenu_ApproveSection: "섹션 승인",
        teamMenu_ApproveAssignment: "지정 승인",
        teamMenu_ReturnSectionForRework: "재작업을 위해 섹션 리턴",
        teamMenu_ReturnAssignmentForRework: "재작업을 위해 지정 리턴",
        teamMenu_RemoveSectionAssignment: "섹션 지정 제거",
        teamMenu_RemoveCellAssignment: "셀 지정 제거",
        teamMenu_RemoveCompletedAssignments: "완료된 지정 제거",
        teamMenu_AboutThisSection: "이 섹션 정보",
        teamMenu_AboutAssignment: "이 지정 정보",

        presentationMenu: "프리젠테이션",
        presentationMenu_SlideShow: "슬라이드 쇼 재생",
        presentationMenu_SlideShowWithCoview: "공유 슬라이드 쇼 재생",
        presentationMenu_SlideTransitions: "슬라이드 전환 적용...",
        presentationMenu_SlideShowFromCurrent: "현재 슬라이드부터 재생",
        presentationMenu_EmptyCoviewInvites: "활성 공유 슬라이드 쇼 없음",
        presentationMenu_CoviewInvites: "활성 공유 슬라이드 쇼",

        dataMenu: "데이터",
        dataMenu_Sort: "정렬...",
        dataMenu_SortAsc: "오름차순 정렬",
        dataMenu_SortDesc: "내림차순 정렬",
        dataMenu_ACL: "보호 영역",
        dataMenu_ACL_DELETE: "모든 권한 삭제",
        dataMenu_Validity: "유효성",
        dataMenu_InstantFilter: "인스턴트 필터",
        dataMenu_Validation: "유효성 검증...",

        toolsMenu: "도구",
        toolsMenu_AutoComplete: "셀 항목 자동 완성",
        toolsMenu_SelectDictionary: "맞춤법 검사 사전",
        toolsMenu_Dictionary_ca_CT: "카탈로니아어",
        toolsMenu_Dictionary_cs_CZ: "체코어(체코)",
        toolsMenu_Dictionary_da_DK: "덴마크어(덴마크)",
        toolsMenu_Dictionary_nl_NL: "네덜란드어(네덜란드)",
        toolsMenu_Dictionary_en_AU: "영어(오스트레일리아)",
        toolsMenu_Dictionary_en_GB: "영어(영국)",
        toolsMenu_Dictionary_en_US: "영어(미국)",
        toolsMenu_Dictionary_fi_FI: "핀란드어(핀란드)",
        toolsMenu_Dictionary_fr_FR: "프랑스어(프랑스)",
        toolsMenu_Dictionary_fr_CA: "프랑스어(캐나다)",
        toolsMenu_Dictionary_de_DE: "독일어(독일)",
        toolsMenu_Dictionary_de_CH: "독일어(스위스)",
        toolsMenu_Dictionary_el_GR: "그리스어(그리스)",
        toolsMenu_Dictionary_it_IT: "이탈리아어(이탈리아)",
        toolsMenu_Dictionary_pl_PL: "폴란드어(폴라드)",
        toolsMenu_Dictionary_pt_BR: "포르투갈어(브라질)",
        toolsMenu_Dictionary_pt_PT: "포르투갈어(포르투갈)",
        toolsMenu_Dictionary_ru_RU: "러시아어(러시아)",
        toolsMenu_Dictionary_es_ES: "스페인어(스페인)",
        toolsMenu_Dictionary_sv_SE: "스웨덴어(스웨덴)",
        toolsMenu_Dictionary_nb_NO: "노르웨이어(노르웨이)",
        toolsMenu_Dictionary_nn_NO: "노르웨이어(뉘노르스크)",
        toolsMenu_Dictionary_he_IL: "히브리어(이스라엘)",
        toolsMenu_SpellCheck: "수동 맞춤법 검사 실행...",
        toolsMenu_Preferences: "환경 설정",
        toolsMenu_Task: "태스크",
        toolsMenu_Task_Assigntask: "태스크 지정",
        teamMenu_AssignSlide: "슬라이드 지정",
        teamMenu_AssignSlides: "슬라이드 지정",
        teamMenu_EditSlide: "슬라이드 지정 편집",
        teamMenu_ReopenSlideAssignment: "슬라이드 지정 다시 열기",
        teamMenu_ReopenSlideAssignments: "슬라이드 지정 다시 열기",
        teamMenu_ReassignSlide: "슬라이드 재지정",
        teamMenu_ReassignSlides: "슬라이드 재지정",
        teamMenu_MarkSlidesComplete: "슬라이드를 완료로 표시",
        teamMenu_MarkSlidesCompletes: "슬라이드를 완료로 표시",
        teamMenu_ApproveSlide: "슬라이드 승인",
        teamMenu_ApproveSlides: "슬라이드 승인",
        teamMenu_ReturnForRework: "재작업을 위해 슬라이드 리턴",
        teamMenu_ReturnForReworks: "재작업을 위해 슬라이드 리턴",
        teamMenu_RemoveAssignment: "슬라이드 지정 제거",
        teamMenu_AboutThisSlide: "이 슬라이드 정보",

        addOnsMenu: "추가 기능",

        helpMenu: "도움말",
        helpMenu_About: "정보",
        helpMenu_Overview: "도움말 컨텐츠",
        helpMenu_NewFeatures: "새로운 기능",
        helpMenu_Tour: "둘러보기 안내서",

        accel_fileMenu_Save: "Ctrl+S",
        accel_fileMenu_Save_Mac: "\u2318S",
        accel_fileMenu_Print: "Ctrl+P",
        accel_fileMenu_Print_Mac: "\u2318P",
        accel_editMenu_SelectAll: "Ctrl+A",
        accel_editMenu_SelectAll_Mac: "\u2318A",
        accel_editMenu_Undo: "Ctrl+Z",
        accel_editMenu_Undo_Mac: "\u2318Z",
        accel_editMenu_Redo: "Ctrl+Y",
        accel_editMenu_Redo_Mac: "\u2318Y",
        accel_editMenu_Cut: "Ctrl+X",
        accel_editMenu_Cut_Mac: "\u2318X",
        accel_editMenu_Copy: "Ctrl+C",
        accel_editMenu_Copy_Mac: "\u2318C",
        accel_editMenu_Paste: "Ctrl+V",
        accel_editMenu_Paste_Mac: "\u2318V",
        accel_editMenu_Find: "Ctrl+F",
        accel_editMenu_Find_Mac: "\u2318F",
        accel_insertMenu_Link: "Ctrl+K",
        accel_insertMenu_Link_Mac: "\u2318K",
        accel_insertMenu_Header: "CTRL+SHIFT+H",
        accel_insertMenu_Header_Mac: "\u21e7\u2318H",
        accel_insertMenu_Footer: "CTRL+SHIFT+F",
        accel_insertMenu_Footer_Mac: "\u21e7\u2318F",
        accel_formatMenu_Textprop_Bold: "Ctrl+B",
        accel_formatMenu_Textprop_Bold_Mac: "\u2318B",
        accel_formatMenu_Textprop_Italic: "Ctrl+I",
        accel_formatMenu_Textprop_Italic_Mac: "\u2318I",
        accel_formatMenu_Textprop_FormatPainter: "Ctrl+SHIFT+C, Ctrl+SHIFT+V",
        accel_formatMenu_Textprop_FormatPainter_Mac: "\u21e7\u2318C, \u21e7\u2318V",
        accel_formatMenu_Textprop_Underline: "Ctrl+U",
        accel_formatMenu_Textprop_Underline_Mac: "\u2318U",
        accel_formatMenu_Headingprop_P: "CTRL+SHIFT+0",
        accel_formatMenu_Headingprop_H1: "CTRL+SHIFT+1",
        accel_formatMenu_Headingprop_H2: "CTRL+SHIFT+2",
        accel_formatMenu_Headingprop_H3: "CTRL+SHIFT+3",
        accel_formatMenu_Headingprop_H4: "CTRL+SHIFT+4",
        accel_formatMenu_Headingprop_H5: "CTRL+SHIFT+5",
        accel_formatMenu_Headingprop_H6: "CTRL+SHIFT+6",
        accel_formatMenu_Superscript: "Ctrl+.",
        accel_formatMenu_Superscript_Mac: "\u2318.",
        accel_formatMenu_Subscript: "Ctrl+,",
        accel_formatMenu_Subscript_Mac: "\u2318,",
        accel_formatMenu_Left: "CTRL+SHIFT+L",
        accel_formatMenu_Left_Mac: "\u21e7\u2318L",
        accel_formatMenu_Right: "CTRL+SHIFT+R",
        accel_formatMenu_Right_Mac: "\u21e7\u2318R",
        accel_formatMenu_Center: "CTRL+SHIFT+E",
        accel_formatMenu_Center_Mac: "\u21e7\u2318E",
        accel_formatMenu_Justify: "CTRL+SHIFT+J",
        accel_formatMenu_Justify_Mac: "\u21e7\u2318J",
        accel_formatMenu_Indent: "CTRL+M",
        accel_formatMenu_Indent_Mac: "\u2318M",
        accel_formatMenu_DecreaseIndent: "CTRL+SHIFT+M",
        accel_formatMenu_DecreaseIndent_Mac: "\u21e7\u2318M",
        accel_teamMenu_AddComment: "SHIFT+F2",

        ctxMenuSmartTable: '테이블',
        ctxMenuTableProperties: "테이블 특성",
        ctxMenuDeleteST: '삭제',
        ctxMenuDeleteSTTable: '테이블 삭제',
        ctxMenuChgSTStyle: '스타일 변경',
        ctxMenuShowCaption: '캡션 표시',
        ctxMenuHideCaption: '캡션 숨기기',
        ctxMenuResizeST: '크기 조정',
        ctxMenuResizeColumnsST: '열 크기 조정',
        ctxMenuSTRow: '행',
        ctxMenuAddSTRowAbv: '위에 행 삽입',
        ctxMenuAddSTRowBlw: '아래에 행 삽입',
        ctxMenuMoveSTRowUp: '위로 행 이동',
        ctxMenuMoveSTRowDown: '아래로 행 이동',
        ctxMenuDelSTRow: '삭제',
        ctxMenuRepeatRow: '머리글 행 반복',
        ctxMenuSTCol: '열',
        ctxMenuAddSTColBfr: '앞에 열 삽입',
        ctxMenuAddSTColAft: '뒤에 열 삽입',
        ctxMenuMoveSTColBefore: '앞으로 열 이동',
        ctxMenuMoveSTColAfter: '뒤로 열 이동',
        ctxMenuDelSTCol: '삭제',
        ctxMenuSortSTColAsc: '오름차순 정렬',
        ctxMenuSortSTColDesc: '내림차순 정렬',
        ctxMenuShowAllFacets: '카테고리 표시',
        ctxMenuHideAllFacets: '카테고리 숨기기',
        ctxMenuSTCell: '셀',
        ctxMenuMergeCells: '셀 병합',
        ctxMenuMergeDown: '아래 셀과 병합',
        ctxMenuVerSplit: '수직 분할',
        ctxMenuHorSplit: '수평 분할',
        ctxMenuSplitCells: '셀 분할...',
        splitCells: '셀 분할',
        ctxMenuAlignTextLeft: '왼쪽 맞춤',
        ctxMenuAlignTextCenter: '가운데 맞춤',
        ctxMenuAlignTextRight: '오른쪽 맞춤',
        ctxMenuClearSTCellContent: '컨텐츠 지우기',
        ctxMenuMakeHeaderRow: '선택한 행을 머리글로 사용',
        ctxMenuMakeNonHeaderRow: '표제 스타일 제거',
        ctxMenuMakeHeaderCol: '선택한 열을 머리글로 사용',
        ctxMenuMakeNonHeaderCol: '표제 스타일 제거',
        SHEET_CONTEXT_Hide: "숨기기", // hide row, column or sheet
        SHEET_CONTEXT_Show: "표시", // show row, column
        SHEET_CONTEXT_MoveSheet: "이동...", // move sheet
        SHEET_CONTEXT_InsertSheet: "삽입...", // insert sheet
        SHEET_CONTEXT_DeleteSheet: "삭제...", // delete sheet	
        SHEET_CONTEXT_DuplicateSheet: "복제...", // duplicate sheet
        SHEET_CONTEXT_RenameSheet: "이름 변경...", // rename sheet
	
        ctxMenu_Image_WrapText: "텍스트 줄 바꾸기",
        ctxMenu_Image_WrapText_Inline: "텍스트를 일렬로",
        ctxMenu_Image_WrapText_Square: "정사각형",
        ctxMenu_Image_WrapText_TopBottom: "맨 위 및 맨 아래",
        ctxMenu_Image_WrapText_Behind: "텍스트 뒤",
        ctxMenu_Image_WrapText_InFront: "텍스트 앞",
        ctxMenu_Image_WrapText_Other: "추가 텍스트 줄 바꾸기",
        ctxMenu_Image_WrapText_BothSides: "양면 모두",
        ctxMenu_Image_WrapText_LeftOnly: "왼쪽만",
        ctxMenu_Image_WrapText_RightOnly: "오른쪽만",
        ctxMenu_Image_WrapText_LargestOnly: "큰 쪽만",

        ctxMenu_Shape_AddText: "텍스트 추가",

        ctxMenu_Range_ACL: "범위 보호",
        ctxMenu_Sheet_ACL: "시트 보호",

        ctxMenu_HeaderFooter: "머리글/바닥글",
        ctxMenu_HeaderFooter_DiffFirst: "첫 페이지만",
        ctxMenu_HeaderFooter_DiffOddEven: "홀수 페이지 및 짝수 페이지 구분",
        ctxMenu_HeaderFooter_LinkToPre: "이전 머리글/바닥글에 링크",

        ctxMenu_copy: "복사",
        ctxMenu_paste: "붙여넣기",
        ctxMenu_delete: "삭제",
        ctxMenu_cut: "잘라내기",
        ctxMenu_select: "선택",
        ctxMenu_properties: "특성",
        ctxMenu_bringToFront: "맨 앞으로 가져오기",
        ctxMenu_sendToBack: "뒤로 보내기",
        ctxMenu_arrange: "배열",
        ctxMenu_sendBackward: "뒤로 보내기",
        ctxMenu_sendForward: "앞으로 보내기",
        ctxMenu_fontStyle: "글꼴 스타일",
        ctxMenu_selectStyle: "스타일 선택",
        ctxMenu_fontSize: "글꼴 크기",
        ctxMenu_fontFamily: "글꼴 그룹",
        ctxMenu_bold: "굵은체",
        ctxMenu_italic: "기울임꼴",
        ctxMenu_u: "밑줄",
        ctxMenu_strike: "취소선",
        ctxMenu_super: "윗첨자",
        ctxMenu_sub: "아래첨자",
        ctxMenu_color: "색상",
        ctxMenu_bgcolor: "배경색",
        ctxMenu_highcolor: "강조표시 색상",
        ctxMenu_restart: "목록 다시 시작",
        ctxMenu_continue: "목록 계속",
        ctxMenu_separate: "목록 나누기",
        ctxMenu_join: "이전 목록에 결합",
        ctxMenu_setNumberVal: "번호 매기기 값 설정...",
        webClipboardInfoTitle: "클립보드",
        webClipboardInfoOKBtn: "확인",
        webClipboardInfoCutMsg: "브라우저 보안 설정으로 인해 자동 복사가 허용되지 않습니다. 대신 키보드에서 Ctrl+X를 사용하십시오.",
        webClipboardInfoCopyMsg: "브라우저 보안 설정으로 인해 자동 복사가 허용되지 않습니다. 대신 키보드에서 Ctrl+C를 사용하십시오.",
        webClipboardInfoPasteMsg: "브라우저 보안 설정으로 인해 이 편집자가 클립보드 데이터에 액세스할 수 없습니다. 대신 키보드에서 Ctrl+V를 사용하십시오.",

        clearTrackChangeConfirmMsg: "이 문서에서 변경사항을 표시하는 모든 색상 코딩이 영구 제거됩니다. 계속하시겠습니까?"
});

