({
	ORIENTATION_LABEL: "Suunta",
	PORTRAIT: "Pystytaso",
	LANDSCAPE: "Vaakataso",
	PAGE_LABEL: "Sivujärjestys",
	PAGE_TYPE1: "Ylhäältä alas, sitten oikealle",
	PAGE_TYPE2: "Vasemmalta oikealle, sitten alas",
	DISPLAY_OPTION_LABEL: "Näyttöasetukset",
	HEADER: "Otsikko",
	FOOTER: "Alatunniste",
	GRIDLINE: "Ruudukon viivat",
	TAGGED_PDF: "Tunnisteella varustettu PDF-tiedosto",
	MARGINS_LABEL: "Reunukset",
	TOP: "Yläreuna:",
	TOP_DESC:"Yläreunus senttimetreinä",
	TOP_DESC2:"Yläreunus tuumina",
	BOTTOM: "Alareuna:",
	BOTTOM_DESC:"Alareunus senttimetreinä",
	BOTTOM_DESC2:"Alareunus tuumina",	
	LEFT: "Vasen:",
	LEFT_DESC:"Vasen reunus senttimetreinä",
	LEFT_DESC2:"Vasen reunus tuumina",	
	RIGHT: "Oikea:",
	RIGHT_DESC:"Oikea reunus senttimetreinä",
	RIGHT_DESC2:"Oikea reunus tuumina",	
	PAPER_FORMAT_LABEL: "Paperikoko",
	PAPER_SIZE_LABEL: "Paperikoko:",
	HEIGHT: "Korkeus:",
	HEIGHT_DESC:"Paperin korkeus senttimetreinä",
	HEIGHT_DESC2:"Paperin korkeus tuumina",		
	WIDTH: "Leveys:",
	WIDTH_DESC:"Paperin leveys senttimetreinä",
	WIDTH_DESC2:"Paperin leveys tuumina",
	
	INVALID_MSG: "Syöte on virheellinen, ja se on korjattu automaattisesti. Kokeile toista arvoa, jos haluat toisen tuloksen.",
	
	TOOLTIP1:"Tulostaa niin monta riviä kuin arkille mahtuu pituussuunnassa ja siirtyy taulukossa sivusuuntaisesti, kunnes sarakkeita ei enää ole. Tämän jälkeen toiminto siirtyy alas ja vasemmalle ja tulostaa seuraavan riviryhmän.",
	TOOLTIP2:"Tulostaa niin monta saraketta kuin arkille mahtuu leveyssuunnassa ja siirtyy taulukossa alaspäin, kunnes rivejä ei enää ole. Tämän jälkeen toiminto siirtyy ylös ja oikealle ja tulostaa seuraavan sarakeryhmän.",
	CM_LABEL: " cm",
	LETTER: "Letter",
	LEGAL: "Legal",
	TABLOID: "Tabloidi",
	USER: "Mukautettu",
	SIZE1: "Kirjek. nro 6 3/4",
	SIZE2: "Kirjek. Monarch",
	SIZE3: "Kirjek. nro 9",
	SIZE4: "Kirjek. nro 10",
	SIZE5: "Kirjek. nro 11",
	SIZE6: "Kirjek. nro 12",
	SIZE7: "16 kai",
	SIZE8: "32 kai",
	SIZE9: "32 kai suuri"
})
	
