/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2014. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
	service_unavailable_title: "Tjänsten är inte tillgänglig.",
	service_unavailable_content: "${productName}-tjänsten är inte tillgänglig. Det går inte att bearbeta din begäran för tillfället. Försök senare eller kontakta systemadministratören.",
	access_denied_title: "Åtkomst nekas.",
	viewaccess_denied_content: "Du har inte behörighet att öppna filen. Filen måste göras publik eller så måste den delas med dig.",
	editaccess_denied_content: "Du har inte behörighet att använda ${productName} eller så har du inte behörighet att redigera filen. Filen måste delas med dig och du måste ha redigeringsbehörighet. Filen kan även ha låsts av en annan användare.",
	doc_notfound_title: "Det går inte att hitta dokumentet.",
	doc_notfound_content: "Det dokument som du vill nå har tagits bort eller flyttats. Kontrollera att länken är korrekt.",
	repository_out_of_space_title: "Utrymmet räcker inte",
	repository_out_of_space_content: "Det går inte att publicera ${0} eftersom maximal filstorlek redan har uppnåtts. Flytta filer till papperskorgen och ta sedan bort dem.",
	fileconnect_denied_title: "Anslutning nekas.",
	fileconnect_denied_content: "${productName} kan inte ansluta till fillagret. Försök senare eller kontakta systemadministratören.",
	unscanned_document_title: "Viruskontrollen slutförs",
	unscanned_document_content: "Filer som laddas upp till Connections viruskontrolleras automatiskt. Du kan redigera filen så snart kontrollen är klar.",
	malicious_document_title: "Skadlig fil",
	malicious_document_content: "Det går inte att redigera den här filen eftersom Connections upptäckte ett virus i den.",	
	convservice_unavailable_title: "Konverteringstjänsten är inte tillgänglig.",
	convservice_unavailable_content: "${productName}-konverteringstjänsten är inte tillgänglig. Det går inte att bearbeta din begäran för tillfället. Försök senare eller kontakta systemadministratören.",
	doc_toolarge_title: "Filen är för stor.",
	doc_toolarge_content: "Dokumentet du vill öppna är för stort.",
	doc_toolarge_content2: "Det går inte att öppna filen. Möjliga orsaker:",
	doc_toolarge_content3: "Det går inte att visa filen eftersom den är större än ${0} kB. Du kan ladda ned filen och redigera den. Om filen innehåller högupplösta bilder kan du minska filstorleken genom att ersätta dem med lågupplösta bilder.",
	doc_toolarge_content4: "Filen är för stor för att visas här men du kan öppna den genom att klicka på hämtningsknappen i namnlisten.",
	doc_toolarge_content_mobile: "Det går inte att öppna filen. En fil får inte vara större än ${0} KB på en mobil enhet.",
	sheet_toolarge_content: "Kalkylarket är större än ${0} KB.",
	sheet_toolarge_content2: "Kalkylarket innehåller fler än ${0} rader på ett ark.",
	sheet_toolarge_content5: "Kalkylarket innehåller fler än ${0} kolumner på ett ark.",
	sheet_toolarge_content3: "Kalkylarket innehåller fler än ${0} celler.",
	sheet_toolarge_content4: "Kalkylarket innehåller fler än ${0} formler.",
	text_toolarge_content: "Dokumentet är större än ${0} KB.",
	text_toolarge_content2:"Dokumentet innehåller fler än ${0} sidor.",
	text_toolarge_content3:"Dokumenttexten är större än ${0} KB.",
	pres_toolarge_content: "Det går inte att öppna presentationen eftersom den är större än ${0} kB. Om presentationen innehåller högupplösta bilder kan du minska filstorleken genom att ersätta dem med lågupplösta bilder.",
	pres_toolarge_content2: "Det går inte att öppna presentationen eftersom den innehåller fler än ${0} sidor.",
	pres_toolarge_content3: "Det går inte att öppna presentationen eftersom den innehåller fler än ${0} objekt.",
	pres_toolarge_content2_mobile: "Det går inte att öppna presentationen eftersom den innehåller fler än ${0} sidor.",
	pres_toolarge_content3_mobile: "Det går inte att öppna presentationen eftersom den innehåller fler än ${0} objekt på en mobil enhet.",
	sheet_view_toolarge_content1_mobile: "Det går inte att öppna kalkylarket på en mobil enhet eftersom det innehåller fler än ${0} rader.",
	sheet_view_toolarge_content2_mobile: "Det går inte att öppna kalkylarket på en mobil enhet eftersom det innehåller fler än ${0} kolumner.",
	sheet_view_toolarge_content3_mobile: "Det går inte att öppna kalkylarket på en mobil enhet eftersom det innehåller mer än ${0} rader och ${1} kolumner.",
	conversion_timeout_title: "Dokumentkonverteringen avbröts på grund av en tidsgräns.",
	conversion_timeout_content: "Just nu tar dokumentet för långt tid att konvertera. Försök igen senare.",
	invalid_docformat_title: "Det går inte att öppna dokumentet.",
	invalid_docformat_content: "Dokumenttypen är giltig men det går inte att läsa innehållet eftersom det är krypterat eller har skadats.",
	template_extension_conent_mismatch: "Källfiltypen är inte en mall. Filen har formatet .${0}. Starta med en giltig mall eller spara filen med ett annat namn med filtillägget .${0}.",
	invalid_docformat_title2: "Det går inte att importera filen till ${productName}.",
	invalid_docformat_content2: "Det finns något i filen som ${productName} saknar funktioner för. Det går inte att importera filen.",
	invalid_doctype_title: "Dokumenttypen hanteras inte.",
	invalid_doctype_content: "Dokumenttypen hanteras inte av ${productName}.",
	unsupported_browser_title: "Webbläsaren har inte alla funktioner.",
	malformed_request_title: "Begäran har ogiltigt format.",
	malformed_request_content: "Kontrollera att URL-adressen och parametrarna stämmer.",
	storageserver_error_title: "Lagringsservern är inte tillgänglig.",
	storageserver_error_content: "Servern är inte tillgänglig just nu. Begäran kan inte bearbetas just nu. Försök senare eller kontakta systemadministratören.",
	document_already_opened_title: "Dokumentet är redan öppet",
	document_already_opened_content:"Dokumentet har redan öppnats i webbläsaren.",
	toomany_documents_opened_inone_browser_title: "Det går inte att öppna dokumentet.",
	toomany_documents_opened_inone_browser_content:"Det går bara att öppna fem ${productName}-filer åt gången. Stäng andra dokument och försök öppna dokumentet igen.",
	document_max_session_exceeded_title:"Tjänsten är inte tillgänglig.",
	document_max_session_exceeded_content:"Det finns alltför många användare som redigerar dokument på servern, din begäran kan inte bearbetas. Försök igen senare.",
	kickout_user_content: "Dokumentet är redan öppet i ett annat fönster. Gå till det fönstret om du vill fortsätta att arbeta med dokumentet.",
	return_to_files: "Tillbaka till Filer",
	return_to_library: "Tillbaka till Bibliotek",
	return_to_icn: "Tillbaka till Content Navigator",
	document_already_open: "Dokumentet är redan öppet",
	cannotedit_noentitled_title: "Det går inte att samredigera filen",
	cannotedit_noentitled_content1: "Följande användare redigerar filen nu:",
	cannotedit_noentitled_content2: "Du har inte behörighet att redigera den här filen medan andra redigerar den. Prova att redigera filen senare.",
	cannotedit_noentitled_content3: "Följande användare redigerar filen nu:",
	cannotedit_noentitled_content4: "Du kan inte delta i redigeringssessionen eftersom den användare som redigerar filen nu inte har behörighet för samredigering. Prova att redigera filen senare.",
	toomany_coeditors_title: "För många användare",
	toomany_coeditors_content: "För många användare redigerar dokumentet just nu. Endast {0} användare kan arbeta med dokumentet samtidigt.",
	encrypted_pptdoc_title:"Krypterad fil",
	encrypted_pptdoc_content:"Filen är lösenordsskyddad. Den kan inte ändras i ${productName} om den inte först krypteras. ",
	server_busy_title:"Servern är upptagen",
	server_busy_content:"Vänta lite och försök igen senare.",
	document_encrypt_title:"Det krypterade dokumentet hanteras inte.",
	document_encrypt_content:"Filen är krypterad i fillagret. Av säkerhetsskäl kan ${productName} inte redigera filen direkt.",
	edit_locked_file: "Det går inte att redigera filen eftersom den är låst.",
	publish_locked_file: "Du kan inte publicera filen som en ny version eftersom den är låst. Innehåller sparas dock automatiskt i utkastet.",
	join_locked_file_session: "Du kan inte delta i samredigeringssessionen eftersom filen är låst av andra.",
	no_need_to_convert_title:"Inget behöver konverteras",
	no_need_to_convert_content:"Filformatet du vill konvertera har redan rätt format. Hämta filen direkt.",
	warning_icon: "Varningsikon",
	//html viewer error message
	incorrect_web_address_title:"Felaktig webbadress.",
	incorrect_web_address_content:"Webbadressen är inte korrekt.  Ange webbadressen igen.",
	unexpecified_conversion_error_title:"Ej angett fel.",
	unexpecified_conversion_error_content:"Servern returnerade ett icke angett fel.",
	encrypted_conversion_error_title:"Det krypterade dokumentet hanteras inte.",
	encrypted_conversion_error_content:"Filen är lösenordsskyddad. Om du ska kunna öppna filen måste du först dekryptera den.",
	service_busy_title:"Det gick inte att öppna dokumentet",
	service_busy_content:"Det gick inte att öppna dokumentet. Servern kan vara upptagen eller så är den inte tillgänglig. Försök igen senare eller kontakta administratören.",
	empty_doc_title: "Dokumentet är tomt.",
	empty_doc_content: "Försäkra dig om att dokumentet är fullständigt och försök igen.",
	corrupted_doc_title: "Det går inte att öppna filen.",
	corrupted_doc_content: "Filen har innehåll som inte hanteras, t.ex. makron, vilket gör att det inte går att visa innehållet i det här programmet.",
	draft_storage_error_title: "Dokumentet kan inte öppnas. ",
	draft_storage_error_content: "Det går inte att läsa in innehållet eftersom det är skadat. Kontakta administratören. ",
	unexpected_code_title: "${productName}-servern returnerar oväntad kod.",
	unexpected_code_content: "${productName}-servern returnerar oväntad kod.",
	request_time_out_title: "Tidsgränsen för inläsning av dokument har uppnåtts.",
	request_time_out_content: "Det tar för lång tid att läsa in det här dokumentet. Försök igen senare.",
	problem_id_msg_title: "Rapportera det här problemet till administratören. ",
	problem_id_msg_show: "Klicka för att visa information",
	problem_id_msg_hide: "Klicka för att dölja"
})

