({
	delete_general: "Izbriši",
	order: "Poredak",
	align_text: "Poravnaj tekst",
	align_slide: "Poravnaj u slajdu",
	align_objects: "Poravnaj izabrane objekte",
	zoom: "Povećanje",
	zoom_fit: "Prilagodi prozoru",
	insert_link: "Umetni vezu",
	add_link: "Dodaj vezu",
	open_link: "Otvori vezu",
	edit_link: "Uredi vezu",
	remove_link: "Ukloni vezu",
	insert_link_menu: "Veza",
	invalid_url: "URL se ne može otvoriti. Molimo vas da provjerite ispravnost URL-a i postavke pretražitelja za blokiranje iskočnih prozora.",
	dnd_canceled_on_slide_event: "Slajd se ne može premjestiti jer je drugi editor nedavno promijenio prezentaciju. Pokušajte ponovno kasnije.",
	rotate: "Rotiraj",
	flipX: "Vodoravno zrcaljenje",
	flipY: "Okomito zrcaljenje",
	rotate_right: "Rotiraj u smjeru kazaljke na satu za 90&#x00B0",
	rotate_left: "Rotiraj suprotno od kazaljke na satu za 90&#x00B0",
	color_set_fill: "Postavite boju za ispunu",
	color_nofill: "Bez ispune",
	color_nobackground: "Bez pozadine",
	color_auto: "Automatski",
	color_default: "Default",
	color_transparent: "Prozirno",
	
	objects_distribute: "Razdijeli",
	objects_distribute_v: "Okomito",
	objects_distribute_h: "Vodoravno",
	
	link_subject: "Predmet:",
	link_text: "Tekst za prikaz :",
	link_mailto: "Otvori e-poštu",
	link_goto: "Otvori vezu",
	link_done: "Gotovo",
	link_remove: "Ukloni",
	link_website: "Web stranica",
	link_email: "E-pošta",
	link_slide: "Slajd",
	link_slide_placeholder: "Izaberite ili upišite broj",
	link_slide_placeholder_deleted: "Povezani slajd je obrisan",
	link_slide_next: "Sljedeći slajd",
	link_slide_prev: "Prethodni slajd",
	link_slide_first: "Prvi slajd",
	link_slide_last: "Zadnji slajd",
	link_slide_number: "Slajd ${0}",
	link_not_support: "Tip poveznice nije podržan",
	link_acc_input: "Adresa ulazne poveznice",
	link_acc_mail_input: "Adresa ulazne pošte",
	

	// Jaws Support
	acc_blank: "prazno mjesto",// when selection is nothing but space char and empty paragraph
	acc_selected: " izabrano",
	acc_showed: " prikazan",
	acc_inTable: " u redu tablice ${0}, stupcu ${1} ",
	acc_titleSelected: "izabran naslov",
	acc_subtitleSelected: "izabran podnaslov",
	acc_outlineSelected: "izabran obris",
	acc_notesSelected: "izabrane govorne napomene",
	acc_imageSelected: "izabrana slika",
	acc_shapeSelected: "izabrani oblik",
	acc_rotated: " rotirano ${0} stupnjeva",
	acc_tableSelected: "izabrana tablica",
	acc_textboxSelected: "izabrani tekst okvir",
	acc_enterEdit: " pritisnite enter za uređivanje",
	acc_locked_by: " kojeg je zaključao korisnik ${0}",
	acc_slide_used_by: " kojeg upotrebljava korisnik ${0}",
	ACC_TABLE_TABLESIZE: "Izabrali ste ${0} redova, ${1} stupaca",
	ACC_TABLE_MAXSIZE: " Podržana maksimalna veličina tablice je 8*8",
	ACC_EditorMode: "način uređivanja editora",
	ACC_EndEditorMode: "zaustaviti način uređivanja editora",
	ACC_Table_new_row: "Dodan je novi red",
	ACC_Table_new_column: "Dodana je nova kolona",
	Acc_column: "stupac ${0}",
	acc_slide: "slajd ${0}",
	acc_editor: "Uredio ${0}",
	Plain: "Jednostavan",
	BlueStyle: "Plavi stil",
	RedTint: "Crvena nijansa",
	BlueHeader: "Plavo zaglavlje",
	DarkGrayHF: "Tamno sivo zaglavlje/donje zaglavlje",
	LightGrayRows: "Svjetlo sivi redovi",
	DarkGrayRows: "Tamno sivi redovi",
	BlueTint: "Plava nijansa",
	RedHeader: "Crveno zaglavlje",
	GreenHF: "Zeleno zaglavlje/donje zaglavlje",
	PlainRows: "Jednostavni redovi",
	GrayTint: "Siva nijansa",
	GreenTint: "Zelena nijansa",
	GreenHeader: "Zeleno zaglavlje",
	RedHF: "Crveno zaglavlje/donje zaglavlje",
	GreenStyle: "Zeleni stil",
	PurpleTint: "Ljubičasta nijansa",
	BlackHeader: "Crno zaglavlje",
	PurpleHeader: "Ljubičasto zaglavlje",
	LightBlueHF: "Svjetlo plavo zaglavlje/donje zaglavlje",
	
    formatMenu_LineSpacing: "Prored",
	linespaceboxTitle:"Prilagođeni prored",
	linespacelineTitle:"Red:",
	linespacenoticeContent :"Prored",
    formatMenu_LineSpacing_Customize: "Prilagođeno...",
    formatMenu_LineSpacing_CustomValue:"Prilagođeno: ${0}",
    lineSpaceWarning:"Upišite broj od 0 do 10",
    
    set_transparency_menu: "Neprozirnost slike",
    opacity_percent_value: "${0}%",
    opacity_title: "Neprozirnost",
    
    increaseLineWidthTip: "Povećaj debljinu linije",
	decreaseLineWidthTip : "Smanji debljinu linije",
    setBorderStyleTip:"Postavi stil linije",
    line_width_title: "Debljina linije",
    line_end_title: "Krajnje točke linije",
    line_dash_title: "Uzorak linije",
    line_dash_type1: "Puna",
    line_dash_type2: "Četvrtaste točke",
    line_dash_type3: "Crtice",
    line_dash_type4: "Okrugle točke",
    line_dash_type5: "Crtice i točke",
    line_dash_type6: "Duge crte",
    line_endpoints_type1: "Ništa",
    line_endpoints_type2: "Jednostavna desna strelica",
	line_endpoints_type3: "Jednostavna lijeva strelica",
	line_endpoints_type4: "Jednostavna dvostruka strelica",
	line_endpoints_type5: "Ispunjena desna strelica",
	line_endpoints_type6: "Ispunjena lijeva strelica",
    line_endpoints_type7: "Ispunjena dvostruka strelica",
    line_endpoints_type8: "Ispunjeni krug i strelica",
	line_endpoints_type9: "Ispunjeni dijamant i strelica",
	line_endpoints_type10: "Ispunjeni dijamanti",
    line_endpoints_type11: "Ispunjeni krugovi"
})

