({
	service_unavailable_title: "Tjänsten finns inte.",
	service_unavailable_content: "${productName}-tjänsten är inte tillgänglig så det går inte att bearbeta begäran nu. Försök senare eller kontakta administratören som kan kontrollera att ${productName}-tjänsten är tillgänglig.",
	access_denied_title: "Åtkomst nekas.",
	viewaccess_denied_content: "Du har inte behörighet att öppna filen. Filen måste göras publik eller så måste den delas med dig.",
	editaccess_denied_content: "Du har inte behörighet att redigera filen. Filen måste vara delad med dig eller så måste du ha redigeringsbehörighet till filen.",
	doc_notfound_title: "${productName}-tjänsten kan inte hitta filen.",
	doc_notfound_content: "Kontakta administratören som kan kontrollera att ${productName}-tjänsten är konfigurerad på rätt sätt.",
	fullviewer_notsupport_title: "Dokumentet hittades inte",
	fullviewer_notsupport_content: "En ny filvisningsfunktion lagrar dokumentet på en annan URL. Gå till filen i programmet och klicka på knappen Förhandsgranska om du vill titta på dokumentet.",
	fileconnect_denied_title: "Anslutning nekas.",
	fileconnect_denied_content: "${productName} kan inte ansluta till fillagret. Försök senare eller kontakta systemadministratören.",
	convservice_unavailable_title: "Konverteringstjänsten är inte tillgänglig.",
	convservice_unavailable_content: "Det går inte att bearbeta din begäran för tillfället. Försök igen senare eller be systemadministratören kontrollera att konverteringstjänsten är tillgänglig.",
	doc_toolarge_title: "Filen är för stor.",
	doc_toolarge_content: "Dokumentet du vill öppna är för stort.",
	doc_toolarge_content2: "Det går inte att öppna filen eftersom:",
	doc_toolarge_content3: "Filen kan inte visas eftersom den är större än ${0} KB. Du kan Du kan ladda ned och visa filen. Om filen innehåller högupplösta bilder kan du ersätta dem med lågupplösta för att minska filstorleken.",
	doc_toolarge_content4: "Filen kan inte visas eftersom filen ${0} är större än ${1} KB.",
	doc_toolarge_content5: "Filen är för stor för att visas här men du kan öppna den genom att klicka på hämtningsknappen i namnlisten.",
	edit_locked_file: "Det går inte att redigera filen eftersom den är låst.",
	sheet_toolarge_content: "Kalkylarket är större än ${0} KB.",
	sheet_toolarge_content2: "En ark i kalkylarket innehåller fler än ${0} rader.",
	sheet_toolarge_content5: "Ett ark i kalkylarket innehåller fler än ${0} kolumner.",
	sheet_toolarge_content3: "Kalkylarket innehåller fler än ${0} celler.",
	sheet_toolarge_content4: "Kalkylarket innehåller fler än ${0} formler.",
	text_toolarge_content: "Dokumentet är större än ${0} KB.",
	text_toolarge_content2:"Dokumentet innehåller fler än ${0} sidor.",
	text_toolarge_content3:"Texten i dokumentet är större än ${0} KB.",
	pres_toolarge_content: "Presentationen är större än ${0} KB.",
	pres_toolarge_content2: "Presentationen innehåller fler än ${0} sidor.",
	pres_toolarge_content3: "Presentationen innehåller fler än ${0} bilder.",
	pdf_toolarge_content: "PDF-filen är större än ${0} kB.",
	conversion_timeout_title: "Dokumentkonverteringen avbröts på grund av en tidsgräns.",
	conversion_timeout_content: "Just nu tar dokumentet för långt tid att konvertera. Försök igen senare.",
	invalid_docformat_title: "Dokumentinnehållet är inte giltigt.",
	invalid_docformat_content: "Dokumentets filtillägg är giltigt, men det går inte att nå innehållet.  Kontrollera att filen inte är skadad. ",
	invalid_doctype_title: "Dokumenttypen hanteras inte.",
	invalid_doctype_content: "Dokumenttypen hanteras inte av ${productName}.",
	malformed_request_title: "Fel URL eller parametrar.",
	malformed_request_content: "Kontrollera att URL-adressen och parametrarna stämmer.",
	storageserver_error_title: "Lagringsservern är inte tillgänglig.",
	storageserver_error_content: "Servern är inte tillgänglig just nu. Det går inte att bearbeta din begäran för tillfället. Försök igen senare eller be systemadministratören kontrollera att lagringstjänsten är tillgänglig.",
	incorrect_web_address_title:"Felaktig webbadress.",
	incorrect_web_address_content:"Webbadressen är inte korrekt.  Ange webbadressen igen.",
	unexpecified_conversion_error_title:"Ej angett fel.",
	unexpecified_conversion_error_content:"Servern returnerade ett icke angett fel.",
	encrypted_conversion_error_title:"CryptoAPI RC4-krypterade dokument hanteras inte. ",
	encrypted_conversion_error_content:"Filen är lösenordsskyddad. Om du vill öppna filen i ${productName} måste du först dekryptera den.",
	document_encrypt_title:"Dokumentet är krypterat.",
	document_encrypt_content:"Det går inte att visa filen online eftersom den krypterades när den överfördes.",
	service_busy_title:"Det gick inte att öppna dokumentet",
	service_busy_content:"Det gick inte att öppna dokumentet. Servern kan vara upptagen eller så är den inte tillgänglig. Försök igen senare eller kontakta administratören.",
	empty_doc_title: "Dokumentet är tomt.",
	empty_doc_content: "Försäkra dig om att dokumentet är fullständigt och försök igen.",
	corrupted_doc_title: "Det går inte att öppna filen.",
	corrupted_doc_content: "Filen har innehåll som inte hanteras, t.ex. makron, vilket gör att det inte går att visa innehållet i det här programmet.",
	draft_storage_error_title: "Dokumentet kan inte öppnas. ",
	draft_storage_error_content: "Det går inte att läsa in innehållet eftersom det är skadat. Kontakta administratören. ",
	unexpected_code_title: "Det går inte att visa dokumentet. ",
	unexpected_code_content: "${docsProductName}-server kanske inte är tillgänglig. Försök igen senare.",
	unpublished_document_title: "Det går inte att visa filen",
	unpublished_document_content: "Det finns ingen publicerad version av filen som är tillgänglig för visning.  Filägaren måste publicera en version av filen innan den kan visas.",
	unscanned_document_title: "Viruskontrollen slutförs",
	unscanned_document_content: "Filer som laddas upp till Connections viruskontrolleras automatiskt. Du kan se filen när viruskontrollen är klar.",
	malicious_document_title: "Skadlig fil",
	malicious_document_content: "Det går inte att se filen eftersom Connections upptäckte ett virus i den.",		
	repository_out_of_space_title: "Utrymmet räcker inte",
	repository_out_of_space_content: "Det går inte att publicera ${0} eftersom maximal filstorlek redan har uppnåtts. Flytta filer till papperskorgen och ta sedan bort dem.",
	pdf_error_title:"Det går inte att öppna filen.",
	pdf_error_content:"PDF-filen kan vara skadad.",
	problem_id_msg_title: "Rapportera det här problemet till din administratör. ",
	problem_id_msg_show: "Klicka för att visa information",
	problem_id_msg_hide: "Klicka för att dölja"
})

