({
	service_unavailable_title: "Tjenesten er ikke tilgjengelig.",
	service_unavailable_content: "${productName}-tjenesten er ikke tilgjengelig, og forespørselen din kan ikke behandles nå. Prøv igjen senere eller kontakt systemadministratoren for å kontrollere at ${productName} er online.",
	access_denied_title: "Ingen tilgang.",
	viewaccess_denied_content: "Du har ikke tillatelse til å vise denne filen. Filen må gjøres felles eller må være delt med deg.",
	editaccess_denied_content: "Du har ikke tillatelse til å redigere denne filen. Filen må være delt med deg, eller du må ha Redigerer-tilgang til filen.",
	doc_notfound_title: "${productName}-tjenesten finner ikke filen.",
	doc_notfound_content: "Kontakt administratoren for å kontrollere at ${productName}-tjenesten er konfigurert riktig.",
	fullviewer_notsupport_title: "Dokumentet ble ikke funnet",
	fullviewer_notsupport_content: "En ny filviser lagrer dokumentet i en annen url. Hvis du vil se dokumentet, må du finne filen i applikasjonen din og klikke på knappen Forhåndsvis.",
	fileconnect_denied_title: "Tilkobling nektet.",
	fileconnect_denied_content: "${productName} kan ikke koble seg til fillageret. Prøv igjen senere eller kontakt systemadministratoren.",
	convservice_unavailable_title: "Konverteringstjenesten er ikke tilgjengelig.",
	convservice_unavailable_content: "Forespørselen din kan ikke behandles nå. Prøv igjen senere eller kontakt systemadministratoren for å kontrollere at konverteringstjenesten er online.",
	doc_toolarge_title: "Filen er for stor.",
	doc_toolarge_content: "Dokumentet du vil arbeide med, er for stort.",
	doc_toolarge_content2: "Ikke tilgang til filen, fordi:",
	doc_toolarge_content3: "Filen kan ikke vises, fordi størrelsen på filen er større enn ${0} kB. Du kan laste ned filen for å vise den. Hvis filen har bilder med høy oppløsning, kan du erstatte dem med bilder med lav oppløsning for å redusere filstørrelsen.",
	doc_toolarge_content4: "Filen kan ikke vises, fordi størrelsen på filen ${0} er større enn ${1} kB.",
	doc_toolarge_content5: "Filen er for stor til å bli vist her, men du kan fremdeles åpne den ved å klikke på nedlastingsknappen på tittellinjen.",
	edit_locked_file: "Du kan ikke redigere denne filen fordi den er låst av andre redigerere.",
	sheet_toolarge_content: "Størrelsen på regnearket er større enn ${0} kB.",
	sheet_toolarge_content2: "Regnearket inneholder mer enn ${0} rader på ett ark.",
	sheet_toolarge_content5: "Regnearket inneholder mer enn ${0} kolonner på ett ark.",
	sheet_toolarge_content3: "Regnearket inneholder mer enn ${0} celler.",
	sheet_toolarge_content4: "Regnearket inneholder mer enn ${0} formler.",
	text_toolarge_content: "Størrelsen på dokumentet er større enn ${0} kB.",
	text_toolarge_content2:"Dokumentet inneholder mer enn ${0} sider.",
	text_toolarge_content3:"Tekststørrelsen på dokumentet er større enn ${0} kB.",
	pres_toolarge_content: "Størrelsen på presentasjonen er større enn ${0} kB.",
	pres_toolarge_content2: "Presentasjonen inneholder mer enn ${0} sider.",
	pres_toolarge_content3: "Presentasjonen inneholder mer enn ${0} grafikkobjekter.",
	pdf_toolarge_content: "Størrelsen på PDF-filen er større enn ${0} kB.",
	conversion_timeout_title: "Dokumentkonverteringen ble tidsavbrutt.",
	conversion_timeout_content: "Det tok for lang tid å konvertere dokumentet nå. Prøv igjen senere.",
	invalid_docformat_title: "Dokumentinnholdet er ikke gyldig.",
	invalid_docformat_content: "Filtypen for dokumentet er et gyldig format, men det var ikke mulig å få tilgang til innholdet i filen. Kontroller at filen ikke er ødelagt. ",
	invalid_doctype_title: "Dokumenttypen støttes ikke.",
	invalid_doctype_content: "Dokumenttypen støttes ikke av ${productName} nå.",
	malformed_request_title: "URLen eller parameterne er feil.",
	malformed_request_content: "Kontroller at URLen og parameterne er riktige.",
	storageserver_error_title: "Lagerserveren er ikke tilgjengelig.",
	storageserver_error_content: "Serveren er i øyeblikket ikke tilgjengelig. Forespørselen din kan ikke behandles nå. Prøv igjen senere eller kontakt systemadministratoren for å kontrollere at lagringstjenesten er online.",
	incorrect_web_address_title:"Feil webadresse.",
	incorrect_web_address_content:"Webadressen er ikke riktig. Skriv inn webadressen og prøv igjen.",
	unexpecified_conversion_error_title:"Feilen er ikke oppgitt.",
	unexpecified_conversion_error_content:"Serveren returnerte en uspesifisert feil.",
	encrypted_conversion_error_title:"CryptoAPI RC4-krypterte dokumenter støttes ikke.",
	encrypted_conversion_error_content:"Filen er passordbeskyttet. Hvis du vil vise filen i ${productName}, må du først sørge for at filen er dekryptert.",
	document_encrypt_title:"Dokumentet er kryptert.",
	document_encrypt_content:"Du kan ikke vise filen online fordi den ble kryptert da den ble lastet opp til Filer.",
	service_busy_title:"Dokumentet kunne ikke åpnes",
	service_busy_content:"Filen du ville vise, kunne ikke åpnes. Serveren er kanskje opptatt eller ikke tilgjengelig. Prøv igjen senere eller kontakt administratoren.",
	empty_doc_title: "Dokumentet er tomt.",
	empty_doc_content: "Sørg for at dokumentet har innhold, og prøv deretter igjen.",
	corrupted_doc_title: "Filen kan ikke åpnes.",
	corrupted_doc_content: "Filen inneholder innhold som ikke støttes, for eksempel makroer, og kan derfor ikke vises i denne applikasjonen.",
	draft_storage_error_title: "Dokumentet kan ikke åpnes.",
	draft_storage_error_content: "Kan ikke laste inn innholdet fordi det er ødelagt. Kontakt administratoren for å få hjelp.",
	unexpected_code_title: "Kan ikke vise dokumentet.",
	unexpected_code_content: "${docsProductName}-serveren er kanskje nede. Prøv igjen senere.",
	unpublished_document_title: "Kan ikke vise filen",
	unpublished_document_content: "Det finnes ingen publisert versjon av denne filen tilgjengelig for visning. Fileieren må publisere en versjon av filen før den kan vises.",
	unscanned_document_title: "Virusskanning fullføres",
	unscanned_document_content: "Filer som blir opplastet til Connections, blir automatisk skannet. Du kan vise denne filen så snart skanningen er fullført.",
	malicious_document_title: "Ondsinnet fil",
	malicious_document_content: "Du kan ikke vise denne filen fordi Connections oppdaget et virus under skanningen.",		
	repository_out_of_space_title: "Ikke nok plass",
	repository_out_of_space_content: "Kan ikke publisere ${0} fordi du har nådd filstørrelseskvoten din. Frigjør kvoteplass ved å flytte andre filer til papirkurven og deretter slette dem.",
	pdf_error_title:"Filen kan ikke åpnes.",
	pdf_error_content:"PDF-filen er kanskje ødelagt.",
	problem_id_msg_title: "Rapporter dette problemet til administratoren. ",
	problem_id_msg_show: "Klikk for å vise detaljer",
	problem_id_msg_hide: "Klikk for å skjule"
})

