/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
    Arrow01_Gray: "Puščica 01, siva",
    Arrow02_Gray: "Puščica 02, siva",
    Arrow03_Red: "Puščica 03, rdeča",
    Arrow04_Blue: "Puščica 04, modra",
    Arrow05_Blue: "Puščica 05, modra",
    Arrow06_Yellow: "Puščica 06, rumena",
    Arrow07_Red: "Puščica 07, rdeča",
    Arrow08_Gray: "Puščica 08, siva",
    Arrow09_Orange: "Puščica 09, oranžna",
    Arrow10_Blue: "Puščica 10, modra",
    Arrow11_Blue: "Puščica 11, modra",
    Arrow12_Green: "Puščica 12, zelena",
    Arrow13_Blue: "Puščica 13, modra",
    Arrow14_Green: "Puščica 14, zelena",
    Arrow15_Orange: "Puščica 15, oranžna",
    Arrow16_Gray: "Puščica 16, siva",
    CircleArrow01_Green: "Krožna puščica 01, zelena",
    CircleArrow02_Multi: "Krožna puščica 02, večbarvna",
    CircleArrow03_Multi: "Krožna puščica 03, večbarvna",
    CircleArrow04_Multi: "Krožna puščica 04, večbarvna",
    CircleArrow05_Multi: "Krožna puščica 05, večbarvna",
    CircleArrow06_Multi: "Krožna puščica 06, večbarvna",
    CircleArrow07_Blue: "Krožna puščica 07, modra",
    CircleArrow08_Green: "Krožna puščica 08, zelena",
    CircleArrow09_Multi: "Krožna puščica 09, večbarvna",
    CurvedArrow01_Gray: "Ukrivljena puščica 01, siva",
    CurvedArrow02_Blue: "Ukrivljena puščica 02, modra",
    CurvedArrow03_Blue: "Ukrivljena puščica 03, modra",
    CurvedArrow04_Orange: "Ukrivljena puščica 04, oranžna",
    CurvedArrow05_Red: "Ukrivljena puščica 05, rdeča",
    CurvedArrow06_Blue: "Ukrivljena puščica 06, modra",
    CurvedArrow07_Purple: "Ukrivljena puščica 07, vijolična",
    CurvedArrow08_Green: "Ukrivljena puščica 08, zelena",
    CurvedArrow09_Gray: "Ukrivljena puščica 09, siva",
    CurvedArrow10_Blue: "Ukrivljena puščica 10, modra",
    CurvedArrow11_Orange: "Ukrivljena puščica 11, oranžna",
    CurvedArrow12_Blue: "Ukrivljena puščica 12, modra",
    CurvedArrow13_Green: "Ukrivljena puščica 13, zelena",
    CurvedArrow14_Brown: "Ukrivljena puščica 14, rjava",
    CurvedArrow15_Blue: "Ukrivljena puščica 15, modra",
    CurvedArrow16_Gray: "Ukrivljena puščica 16, siva",
    CurvedArrow17_Gray: "Ukrivljena puščica 17, siva",
    CurvedArrow18_Gray: "Ukrivljena puščica 18, siva",
    CurvedArrow19_Gray: "Ukrivljena puščica 19, siva",
    CurvedArrow20_Gray: "Ukrivljena puščica 20, siva",
    TrendArrow01_Red: "Puščica trenda 01, rdeča",
    TrendArrow02_Green: "Puščica trenda 02, zelena",
    TrendArrow03_Orange: "Puščica trenda 03, oranžna",
    TrendArrow04_Red: "Puščica trenda 04, rdeča",
    TrendArrow05_Orange: "Puščica trenda 05, oranžna",
    TrendArrow06_Blue: "Puščica trenda 06, modra",
    TrendArrow07_Orange: "Puščica trenda 07, oranžna",
    TrendArrow08_Yellow: "Puščica trenda 08, rumena",
    TrendArrow09_Blue: "Puščica trenda 09, modra",
    TrendArrow10_Blue: "Puščica trenda 10, modra",
    TrendArrow11_Blue: "Puščica trenda 11, modra",
    TrendArrow12_Blue: "Puščica trenda 12, modra",
    TrendArrow13_Red: "Puščica trenda 13, rdeča",
    TrendArrow14_Multi: "Puščica trenda 14, večbarvna",
    TrendArrow15_Blue: "Puščica trenda 15, modra",
    Bullet01_Circle_DarkRed: "Naštevna oznaka 01, krog, temno rdeč",
    Bullet02_Circle_Blue: "Naštevna oznaka 02, krog, moder",
    Bullet03_Circle_Green: "Naštevna oznaka 03, krog, zelen",
    Bullet04_Square_Black: "Naštevna oznaka 04, kvadrat, črn",
    Bullet05_Square_Orange: "Naštevna oznaka 05, kvadrat, oranžen",
    Bullet06_Square_Purple: "Naštevna oznaka 06, kvadrat, vijoličen",
    Bullet07_Diamond_Blue: "Naštevna oznaka 07, karo, moder",
    Bullet08_Diamond_LightBlue: "Naštevna oznaka 08, karo, svetlo moder",
    Bullet09_Diamond_Red: "Naštevna oznaka 09, karo, rdeč",
    Bullet10_Star_Yellow: "Naštevna oznaka 10, zvezda, rumena",
    Bullet11_Star_Blue: "Naštevna oznaka 11, zvezda, modra",
    Bullet12_Triangle_Blue: "Naštevna oznaka 12, trikotnik, moder",
    Bullet13_Triangle_DarkGreen: "Naštevna oznaka 13, trikotnik, temno zelen",
    Bullet14_Arrow_Red: "Naštevna oznaka 14, puščica, rdeča",
    Bullet15_Arrow_Blue: "Naštevna oznaka 15, puščica, modra",
    Bullet16_Box_Blue: "Naštevna oznaka 16, kocka, modra",
    Bullet17_Box_Red: "Naštevna oznaka 17, kocka, rdeča",
    Bullet18_Asterisk_LightBlue: "Naštevna oznaka 18, zvezdica, svetlo modra",
    Bullet19_Leaves_Red: "Naštevna oznaka 19, listi, rdeči",
    Bullet20_Target_Blue: "Naštevna oznaka 20, tarča, modra",
    Bullet21_Arrow_Blue: "Naštevna oznaka 21, puščica, modra",
    Bullet22_Arrow_DarkBlue: "Naštevna oznaka 22, puščica, temno modra",
    Bullet23_Arrow_Brown: "Naštevna oznaka 23, puščica, rjava",
    Bullet24_Flag_Red: "Naštevna oznaka 24, zastavica, rdeča",
    Bullet25_Flag_Green: "Naštevna oznaka 25, zastavica, zelena",
    Bullet26_X_Red: "Naštevna oznaka 26, križec, rdeč",
    Bullet27_X_Black: "Naštevna oznaka 27, križec, črn",
    Bullet28_Checkmark_Green: "Naštevna oznaka 28, kljukica, zelena",
    Bullet29_Checkmark_Blue: "Naštevna oznaka 29, kljukica, modra",
    Bullet30_Square_DarkRed: "Naštevna oznaka 30, kvadrat, temno rdeč",
    camera: "Fotoaparat",
    computer1: "Računalnik 1",
    computer2: "Računalnik 2",
    computer3: "Računalnik 3",
    Computer_Cloud: "Računalniški oblak",
    Computer_Desktop: "Računalniško namizje",
    Computer_Laptop_Black: "Prenosni računalnik, črn",
    Computer_Laptop_Silver: "Prenosni računalnik, srebrn",
    Database: "Baza podatkov",
    evelope: "Ovojnica",
    newspapers: "Časopisi",
    openevelope: "Odprta ovojnica",
    Server: "Strežnik",
    speaker: "Zvočnik",
    WirelessAccessPoint: "Brezžična dostopna točka",
    Cycle01_Transparent: "Cikel 01, prozoren",
    Cycle02_Transparent_Blue: "Cikel 02, prozoren, moder",
    Cycle03_Blue: "Cikel 03, moder",
    Cycle04_Blue: "Cikel 04, moder",
    Cycle05: "Cikel 05",
    Cycle06: "Cikel 06",
    Cycle07: "Cikel 07",
    Cycle08_Blue: "Cikel 08, moder",
    Cycle09_Orange: "Cikel 09, oranžen",
    Donut01_LightBlue: "Kolobar 01, svetlo moder",
    Donut02_Blue: "Kolobar 02, moder",
    Donut03_Blue: "Kolobar 03, moder",
    Donut04_DarkBlue: "Kolobar 04, temno moder",
    Donut05_DarkBlue: "Kolobar 05, temno moder",
    Donut06_Blue: "Kolobar 06, moder",
    Donut07_Blue: "Kolobar 07, moder",
    Graph: "Graf",
    People01_Blue: "Ljudje 01, modri",
    People02: "Ljudje 02",
    Pillars01_Orange: "Stebri 01, oranžni",
    Pillars02_LightBlue: "Stebri 02, svetlo modri",
    Process01_Blue: "Proces 01, moder",
    Process02_Blue: "Proces 02, moder",
    Process03_Blue: "Proces 03, moder",
    Process04_GoUp_Blue: "Proces 04, naraščajoč, moder",
    Process05_GoUp_Red: "Proces 05, naraščajoč, rdeč",
    Process06_GoUp_Yellow: "Proces 06, naraščajoč, rumen",
    Process07_Blue: "Proces 07, moder",
    Pyramid01: "Piramida 01",
    Pyramid02_Blue: "Piramida 02, modra",
    Pyramid03: "Piramida 03",
    Radial01_Green: "Radialno 01, zelena",
    Radial02_Green: "Radialno 02, zelena",
    Radial03_Sphere: "Radialno 03, krogla",
    Radial04_Sphere_Red: "Radialno 04, krogla, rdeča",
    Radial05_Sphere_Blue: "Radialno 05, krogla, modra",
    Radial06_Arrows_DarkBlue: "Radialno 06, puščice, temno modre",
    Radial07_Arrows_DarkBlue: "Radialno 07, puščice, temno modre",
    Section_Circle: "Odsek, krog",
    Section_Cubes01: "Odsek, kocke 01",
    Section_Cubes02_Blue: "Odsek, kocke 02, modre",
    Section_Cubes03_Orange: "Odsek, kocke 03, oranžne",
    Section_Cubes04: "Odsek, kocke 04",
    Section_Cubes05: "Odsek, kocke 05",
    Section_Cuboids01_Blue: "Odsek, kvadri 01, modri",
    Section_Cuboids02_Blue: "Odsek, kvadri 02, modri",
    Section_Cuboids03: "Odsek, kvadri 03",
    Section_Gears01: "Odsek, zobniki 01",
    Section_Gears02: "Odsek, zobniki 02",
    Section_Gears03: "Odsek, zobniki 03",
    Section_Hexagon04_Orange: "Odsek, šesterokotnik 04, oranžen",
    Section_Hexagons01: "Odsek, šesterokotniki 01",
    Section_Hexagons02_Blue: "Odsek, šesterokotniki 02, modri",
    Section_Hexagons03_Blue: "Odsek, šesterokotniki 03, modri",
    Section_Leaves01_LightBlue: "Odsek, listi 01, svetlo modri",
    Section_Leaves02_Green: "Odsek, listi 02, zeleni",
    Section_Pasters01: "Odsek, papirne nalepke 01",
    Section_Pasters02_Blue: "Odsek, papirne nalepke 02, modre",
    Section_Puzzle01: "Odsek, kos sestavljanke 01",
    Section_Puzzle02: "Odsek, kos sestavljanke 02",
    Section_Puzzle03: "Odsek, kos sestavljanke 03",
    Section_Rectangles: "Odsek, pravokotniki",
    Section_Squares: "Odsek, kvadrati",
    Section_Triangle: "Odsek, trikotniki",
    Target: "Tarča",
    Venn01: "Vennov diagram 01",
    Venn02: "Vennov diagram 02",
    Venn03: "Vennov diagram 03",
    Venn04: "Vennov diagram 04",
    Venn05: "Vennov diagram 05",
    Venn06_Blue: "Vennov diagram 06, moder",
    Venn07_Blue: "Vennov diagram 07, moder",
    Venn08: "Vennov diagram 08",
    Blackboard: "Tabla",
    Books: "Knjige",
    Books1: "Knjige 1",
    books2: "Knjige 2",
    Chalk: "Kreda",
    clipboard: "odložišče",
    clock: "Ura",
    Globe: "Globus",
    Glue: "Lepilo",
    GraduationCap: "Maturantska čepica",
    magnifyingglass: "Povečevalno steklo",
    Microscope: "Mikroskop",
    Notebook: "Zvezek",
    notepad1: "Blok 1",
    notepad2: "Blok 2",
    notepad3: "Blok 3",
    PaperClip_Blue: "Sponka za papir, modra",
    PaperClip_Red: "Sponka za papir, rdeča",
    Pencil: "Svinčnik",
    Ruler: "Ravnilo",
    TestTubes: "Epruvete",
    thumbtack: "Risalni žebljiček",
    clouds: "Oblaki",
    DrippingFaucet: "Puščajoča pipa",
    Earth: "Zemlja",
    EndangeredAnimals1: "Ogrožene živali 1",
    EndangeredAnimals2: "Ogrožene živali 2",
    GreenCar: "Zeleni avtomobil",
    GreenFactory: "Zelena tovarna",
    GreenHouse: "Zelena hiša",
    Leaf1: "List 1",
    Leaf2: "List 2",
    lightbulb: "Žarnica",
    LightBulb_Flourescent_Off: "Fluorescentna žarnica, ne sveti",
    LightBulb_Flourescent_On: "Fluorescentna žarnica, sveti",
    LightBulb_Standard_Off1: "Žarnica, standardna, ne sveti 1",
    LightBulb_Standard_Off2: "Žarnica, standardna, ne sveti 2",
    LightBulb_Standard_On: "Žarnica, standardna, sveti",
    lightningcloud: "Oblak s strelo",
    Pollution_Car: "Onesnaževanje, avtomobil",
    Pollution_Factory: "Onesnaževanje, tovarna",
    Raindrop: "Dežna kapljica",
    RecycleBin: "Koš za recikliranje",
    RecycleSymbol: "Simbol za recikliranje",
    RenewableEnergySymbol: "Simbol za obnovljivo energijo",
    RenewableEnergy_Solar: "Obnovljiva energija, sončna",
    RenewableEnergy_Water: "Obnovljiva energija, voda",
    RenewableEnergy_Wind: "Obnovljiva energija, veter",
    sun: "Sonce",
    Sun1: "Sonce 1",
    Sun2: "Sonce 2",
    sundandcloud: "Sonce in oblak",
    world: "Svet",
    Agreement: "Dogovor",
    ATM01: "Bankomat 01",
    ATM02: "Bankomat 02",
    Balance_Balanced1: "Tehtnica, uravnotežena 1",
    Balance_Balanced2: "Tehtnica, uravnotežena 2",
    Balance_Unbalanced1: "Tehtnica, neuravnotežena 1",
    Balance_Unbalanced2: "Tehtnica, neuravnotežena 2",
    Calculator: "Kalkulator",
    Chart_Decrease1: "Grafikon, padajoč 1",
    Chart_Decrease2: "Grafikon, padajoč 2",
    Chart_Increase1: "Grafikon, naraščajoč 1",
    Chart_Increase2: "Grafikon, naraščajoč 2",
    Chart_Plateau: "Grafikon, stabilizacija",
    Check: "Kljukica",
    Contract: "Pogodba",
    CreditCard_Black: "Kreditna kartica, črna",
    CreditCard_Cut: "Kreditna kartica, prerezana",
    CreditCard_Gold: "Kreditna kartica, zlata",
    Currency_Dollar: "Valuta, dolar",
    Currency_Dollars: "Valuta, dolarji",
    Currency_Stack: "Valuta, kup",
    Currency_StackCoins: "Valuta, kup, kovanci",
    GoldBar: "Zlata palica",
    GoldBar_Stack: "Zlata palica, kup",
    MoneyBag01: "Torba z denarjem 01",
    MoneyBag02: "Torba z denarjem 02",
    PercentSign: "Znak za odstotek",
    PiggyBank01_Broken: "Šparovček 01, razbit",
    PiggyBank02_Broken: "Šparovček 02, razbit",
    PiggyBank_Coins: "Šparovček, kovanci",
    PiggyBank_Currency: "Šparovček, valuta",
    Portfolio: "Portfelj",
    PriceTag: "Listek s ceno",
    Safe_Closed: "Sef, zaprt",
    Safe_Empty: "Sef, prazen",
    Safe_Full: "Sef, poln",
    Seal_Gold: "Pečat, zlat",
    Seal_Red: "Pečat, rdeč",
    Seal_Silver: "Pečat, srebrn",
    Wallet_Empty: "Denarnica, prazna",
    Wallet_Full1: "Denarnica, polna 1",
    Wallet_Full2: "Denarnica, polna 2",
    BusinessPerson_Female6: "Poslovna ženska 6",
    BusinessPerson_Male3: "Poslovnež 3",
    Computer_User_Female1: "Računalniška uporabnica 1",
    ConstructionWorker2: "Gradbeni delavec 2",
    Presenter_Female1: "Predstaviteljica 1",
    Component_Circle01_Transparent_DarkBlue: "Komponenta, krog 01, prozoren, temno moder",
    Component_Circle02_Transparent_Bule: "Komponenta, krog 02, prozoren, moder",
    Component_Circle03_Transparent_Green: "Komponenta, krog 03, prozoren, zelen",
    Component_Circle04_Transparent_Orange: "Komponenta, krog 04, prozoren, oranžen",
    Component_Circle05_Transparent_Red: "Komponenta, krog 05, prozoren, rdeč",
    Component_Cube01_DarkBlue: "Komponenta, kocka 01, temno modra",
    Component_Cube02_LightBlue: "Komponenta, kocka 02, svetlo modra",
    Component_Cube03_Green: "Komponenta, kocka 03, zelena",
    Component_Cube04_Orange: "Komponenta, kocka 04, oranžna",
    Component_Cube05_DarkRed: "Komponenta, kocka 05, temno rdeča",
    Component_Cuboid01_DarkBlue: "Komponenta, kvader 01, temno moder",
    Component_Cuboid02_Blue: "Komponenta, kvader 02, moder",
    Component_Cuboid03_Green: "Komponenta, kvader 03, zelen",
    Component_Cuboid04_Orange: "Komponenta, kvader 04, oranžen",
    Component_Cuboid05_Red: "Komponenta, kvader 05, rdeč",
    Component_Gear01_DarkBlue: "Komponenta, zobnik 01, temno moder",
    Component_Gear02_LightBlue: "Komponenta, zobnik 02, svetlo moder",
    Component_Gear03_Green: "Komponenta, zobnik 03, zelen",
    Component_Gear04_DarkRed: "Komponenta, zobnik 04, temno rdeč",
    Component_Gear05_Orange: "Komponenta, zobnik 05, oranžen",
    Component_Person01_DarkBlue: "Komponenta, oseba 01, temno modra",
    Component_Person02_Blue: "Komponenta, oseba 02, modra",
    Component_Person03_Green: "Komponenta, oseba 03, zelena",
    Component_Person04_DarkRed: "Komponenta, oseba 04, temno rdeča",
    Component_Person05_Orange: "Komponenta, oseba 05, oranžna",
    Component_PuzzlePiece01_DarkBlue: "Komponenta, kos sestavljanke 01, temno moder",
    Component_PuzzlePiece02_Blue: "Komponenta, kos sestavljanke 02, moder",
    Component_PuzzlePiece03_Green: "Komponenta, kos sestavljanke 03, zelen",
    Component_PuzzlePiece04_Red: "Komponenta, kos sestavljanke 04, rdeč",
    Component_PuzzlePiece05_Orange: "Komponenta, kos sestavljanke 05, oranžen",
    Component_Sphere01_DarkBlue: "Komponenta, krogla 01, temno modra",
    Component_Sphere02_LightBlue: "Komponenta, krogla 02, svetlo modra",
    Component_Sphere03_Green: "Komponenta, krogla 03, zelena",
    Component_Sphere04_DarkRed: "Komponenta, krogla 04, temno rdeča",
    Component_Sphere05_Orange: "Komponenta, krogla 05, oranžna",
    Book: "Knjiga",
    Box01: "Škatla 01",
    Box02: "Škatla 02",
    Bulb01_Yellow: "Žarnica 01, rumena",
    Bulb02_Yellow: "Žarnica 02, rumena",
    Calendar: "Koledar",
    Chart: "Grafikon",
    Clipboard: "Odložišče",
    Clock: "Ura",
    Compass: "Kompas",
    Flag01_Red: "Zastavica 01, rdeča",
    Flag02_Green: "Zastavica 02, zelena",
    Flag03_Blue: "Zastavica 03, modra",
    Gift: "Darilo",
    House: "Hiša",
    Icon_Computer01_White: "Ikona, računalnik 01, bel",
    Icon_Computer02_Black: "Ikona, računalnik 02, črn",
    Icon_Disk01_Blue: "Ikona, disk 01, moder",
    Icon_Disk02_Green: "Ikona, disk 02, zelen",
    Icon_Document01_Grey: "Ikona, dokument 01, siv",
    Icon_Document02_Grey: "Ikona, dokument 02, siv",
    Icon_Document03_Blue: "Ikona, dokument 03, moder",
    Icon_Document04_Blue: "Ikona, dokument 04, moder",
    Icon_Envelope01_Blue: "Ikona, ovojnica 01, modra",
    Icon_Envelope02_Yellow: "Ikona, ovojnica 02, rumena",
    Icon_Envelope03_Open_Yellow: "Ikona, ovojnica 03, odprta, rumena",
    Icon_Envelope04_Open_Yellow: "Ikona, ovojnica 04, odprta, rumena",
    Icon_Folder01_Yellow: "Ikona, mapa 01, rumena",
    Icon_Folder02_Yellow: "Ikona, mapa 02, rumena",
    Icon_Folder03_Open_Yellow: "Ikona, mapa 03, odprta, rumena",
    Icon_Folder04_Open_Yellow: "Ikona, mapa 04, odprta, rumena",
    Icon_Gear01_Grey: "Ikona, zobnik 01, siv",
    Icon_Gear02_Blue: "Ikona, zobnik 02, moder",
    Icon_Network01_Blue: "Ikona, omrežje 01, modro",
    Icon_Network02: "Ikona, omrežje 02",
    Icon_Pencil01: "Ikona, svinčnik 01",
    Icon_Pencil02: "Ikona, svinčnik 02",
    Icon_Printer01_White: "Ikona, tiskalnik 01, bel",
    Icon_Printer02_Black: "Ikona, tiskalnik 02, črn",
    Key01: "Ključ 01",
    Key02: "Ključ 02",
    Lock01_Yellow: "Ključavnica 01, rumena",
    Lock02_Yellow: "Ključavnica 02, rumena",
    Lock03_Blue: "Ključavnica 03, modra",
    Lock04_Blue: "Ključavnica 04, modra",
    Magnet: "Magnet",
    MagnifyingGlass: "Povečevalno steklo",
    Medal: "Medalja",
    Notebook: "Beležnica",
    Phone: "Telefon",
    PieChart: "Tortni grafikon",
    Pin: "Risalni žebljiček",
    PuzzlePiece: "Kos sestavljanke",
    PuzzlePieces: "Kosi sestavljanke",
    Roadblock: "Cestna zapora",
    Scissors: "Škarje",
    Shield01: "Ščit 01",
    Shield02_Orange: "Ščit 02, oranžen",
    Shield03_Blue: "Ščit 03, moder",
    Sign_Ban01: "Znak, prepovedano 01",
    Sign_Ban02: "Znak, prepovedano 02",
    Sign_CheckBox01: "Znak, potrditveno polje 01",
    Sign_CheckBox02_Unchecked: "Znak, potrditveno polje 02, nepotrjeno",
    Sign_Checkmark01_Green: "Znak, kljukica 01, zelena",
    Sign_Checkmark02_Green: "Znak, kljukica 02, zelena",
    Sign_DoNotEnter: "Znak, ne vstopaj",
    Sign_Error01: "Znak, napaka 01",
    Sign_Error02: "Znak, napaka 02",
    Sign_ExclamationPoint01_Red: "Znak, klicaj 01, rdeč",
    Sign_ExclamationPoint02_Orange: "Znak, klicaj 02, oranžen",
    Sign_Help01_Green: "Znak, pomoč 01, zelen",
    Sign_Help02_Blue: "Znak, pomoč 02, moder",
    Sign_Information: "Znak, informacije",
    Sign_Null: "Znak, ničelno",
    Sign_QuestionMark01_Blue: "Znak, vprašaj 01, moder",
    Sign_QuestionMark02_Red: "Znak, vprašaj 02, rdeč",
    Sign_RadioButton01: "Znak, izbirni gumb 01",
    Sign_RadioButton02_Unchecked: "Znak, izbirni gumb 02, nepotrjen",
    Sign_Warning01_Red: "Znak, opozorilo 01, rdeč",
    Sign_Warning02_Orange: "Znak, opozorilo 02, oranžen",
    Sign_X01_Red: "Znak, križec 01, rdeč",
    Sign_X02_Red: "Znak, križec 02, rdeč",
    Star_Yellow: "Zvezda, rumena",
    Wrench: "Izvijač",
    Airplane_Blue: "Letalo, modro",
    Bicycle_Blue: "Kolo, modro",
    Bus: "Avtobus",
    Canoe_Blue: "Kanu, moder",
    Car_Red: "Avtomobil, rdeč",
    Helicopter_Blue: "Helikopter, moder",
    Motorcycle_Red: "Motor, rdeč",
    Pedestrian_Blue: "Pešec, moder",
    PersonalTransporter_Green: "Osebno vozilo, zeleno",
    Sailboat_Red: "Jadrnica, rdeča",
    Scooter_Orange: "Skuter, oranžen",
    Train_Red: "Vlak, rdeč",
    Truck_Blue: "Tovornjak, moder",
    
    aria_category_selector: "Možnosti slikovnih kategorij",
    filterImageGallery: "Filtriraj galerijo slik"

})
