/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */


define({
        saveTip: "Shrani",
        undoTip: "Razveljavi",
        redoTip: "Ponovno uveljavi",
        formatPainterTip: "Kopiranje oblikovanja",
        showSorterTip: "Prikaži razvrstilnik prosojnic",
        hideSorterTip: "Skrij razvrstilnik prosojnic",
        webClipboardTip: "Spletno odložišče",
        spellCheckTip: "Zaženi ročno preverjanje črkovanja",
        createSectionTip: "Dodeli odsek",
        createCellsTip: "Dodeli celice",
        createSlideTip: "Dodeli prosojnice",
        submitTip: "Oddaj dodelitev",
        addCommentTip: "Dodaj komentar",
        removeFormatTip: "Odstrani oblikovanje",
        sortAscTip: "Razvrsti naraščajoče",
        sortDescTip: "Razvrsti padajoče",
        instantFilterTip: "Neposredni filter",
        insertChartTip: "Vstavi grafikon",
        startAutofillTip: "Samodejno zapolni",
        dataValidationTip: "Preverjanje veljavnosti podatkov",

        selectFontTip: "Izberi pisavo",
        selectFontSizeTip: "Izberi velikost pisave",
        selectFontNameTip: "Izberi ime pisave",
        FontName: "Ime pisave",
        FontSize: "Velikost pisave",
        increaseFontSizeTip: "Povečaj velikost pisave",
        decreaseFontSizeTip: "Zmanjšaj velikost pisave",
        boldTip: "Krepko",
        italicTip: "Ležeče",
        underlineTip: "Podčrtano",
        strikeThroughTip: "Prečrtano",
        setFontColorTip: "Nastavi barvo pisave",
        setShadingColorTip: "Nastavi barvo senčenja",
        setBackgroundFill: "Nastavi polnilo ozadja",
        setBgColorTip: "Nastavi barvo ozadja",
        setBorderTip: "Nastavi slog in barvo obrobe",
        setBorderColorTip: "Nastavi barvo obrobe",
        setHighlightColor: "Nastavi barvo označevanja",
        formatPainter: "Kopiranje oblikovanja",
        //	clearFormat:"Remove Formatting",
        zoom: "Povečava/pomanjšava",
        selectStyleTip: "Izberi slog",
        styles: "Slog",
        formatAsCurrencyTip: "Oblikuj kot valuto",
        formatAsPercentTip: "Oblikuj kot odstotek",
        decreaseDecimalTip: "Zmanjšaj število decimalnih mest",
        increaseDecimalTip: "Povečaj število decimalnih mest",
        formatNumberTip: "Oblikuj številko",

        numberedListTip: "Dodaj oštevilčevanje ali spremeni slog oštevilčevanja",
        bulletedListTip: "Dodaj naštevne oznake ali spremeni slog naštevnih oznak",
        multilevelListTip: "Dodaj ali spremeni večravenski seznam",
        indentTip: "Povečaj zamik",
        decreaseIndentTip: "Zmanjšaj zamik",
        alignTip: "Poravnaj",
        leftAlignTip: "Poravnaj levo",
        centerTip: "Poravnaj na sredino",
        rightAlignTip: "Poravnaj desno",
        justifyTip: "Poravnaj",
        bottomBorderTip: "Dno obrobe",
        borderTypes: "Vrste obrobe",
        borderTip: "Nastavi slog obrobe",
        topAlignTip: "Poravnaj na vrh",
        middleAlignTip: "Poravnaj na sredino",
        bottomAlignTip: "Poravnaj na dno",
        lineSpacingTip: "Razmik med vrsticami",
        mergeSplitCellTip: "Združi ali razdeli celice",
        wrapNoWrapTip: "Vklopi ali izklopi prelom besedila",
        ltrDirectionTip: "Spremeni usmerjenost besedila v Od leve proti desni",
        rtlDirectionTip: "Spremeni usmerjenost besedila v Od desne proti levi",
        autoDirectionTip: "Spremeni usmerjenost besedila",
        toggleSheetDirectionTip: "Spremeni usmerjenost lista",
        setSheetDirectionLTR: "Od leve proti desni",
        setSheetDirectionRTL: "Od desne proti levi",

        addTableTip: "Dodaj tabelo",
        insertOrMoveRowTip: "Vstavi ali premakni vrstico",
        insertOrMoveColTip: "Vstavi ali premakni stolpec",
        insertOrDeleteRowTip: "Vstavi ali izbriši vrstico",
        insertOrDeleteColTip: "Vstavi ali izbriši stolpec",
        insertFunctionTip: "Vstavi funkcijo",
        insertImage: "Vstavi sliko",
        resizeCol: "Spremeni velikost stolpca",
        resizeCols: "Spremeni velikost stolpcev",
        addLink: "Dodaj ali uredi povezavo",
        tableStyle: "Slogi tabele",

        selectBorder_BottomBorder: "Obroba na dnu",
        selectBorder_TopBorder: "Obroba na vrhu",
        selectBorder_LeftBorder: "Leva obroba",
        selectBorder_RightBorder: "Desna obroba",
        selectBorder_NoBorder: "Brez črt",
        selectBorder_AllBorders: "Vse obrobe",

        insertOrMoveRow_InsertAbove: "Vstavi vrstico zgoraj",
        insertOrMoveRow_InsertBelow: "Vstavi vrstico spodaj",
        insertOrMoveRow_MoveUp: "Premakni vrstico gor",
        insertOrMoveRow_MoveDown: "Premakni vrstico dol",
        insertOrMoveCol_InsertLeft: "Vstavi stolpec pred",
        insertOrMoveCol_InsertRight: "Vstavi stolpec za",
        insertOrMoveCol_InsertBefore: "Vstavi stolpec pred",
        insertOrMoveCol_InsertAfter: "Vstavi stolpec za",
        insertOrMoveCol_MoveLeft: "Premakni stolpec na levo",
        insertOrMoveCol_MoveRight: "Premakni stolpec na desno",

        insertOrDelete_Delete: "Izbriši",

        combineButtonReadTip: "Pritisnite puščico dol, da aktivirate meni, nato se pomikajte s smernimi tipkami.",

        lineSpacing_1: "1",
        lineSpacing_12: "1,2",
        lineSpacing_15: "1,5",
        lineSpacing_2: "2",
        lineSpacing_25: "2,5",
        lineSpacing_3: "3",

        percent: "%",
        font_arial: "Arial",

        fontSize: "${0} pt",

        slides: "Ena prosojnica na stran",
        slidesWithNotes: "Prosojnice z opombami",
        preparingSlides: "Priprava prosojnic za tiskanje ...",
        printLayoutOptionLabel: "Možnosti postavitve tiskanja",

        targetRemovedWhenDialogOpen: "Tega dejanja ni mogoče dokončati, ker je sourednik odstranil cilj.",

        NUMBER: "Številka",
        CURRENCY: "Valuta",
        PERCENT: "Odstotek",
        DATE: "Datum",
        TIME: "Čas",
        DATETIME: "Datum-čas",
        MORECURRENCY: "Več valut glede na denarno enoto",
        MORECURRENCYCODE: "Več valut glede na kodo valute",
        MOREDATE: "Več oblik zapisa časa in datuma",
        TEXT: "Besedilo",
	
        // currency, by currency code
        // NOTE: MUST keep it in order
        CURRENCY_CODE: {
            AED: "Združeni arabski emirati (dirham)",
            ARS: "Argentina (pesosi)",
            AUD: "Avstralija (dolarji)",
            BGN: "Bolgarija (lev)",
            BOB: "Bolivija (boliviani)",
            BRL: "Brazilija (reali)",
            CAD: "Kanada (dolarji)",
            CHF: "Švica (franki)",
            CLP: "Čile (pesosi)",
            CNY: "Kitajska (juan renminbi)",
            COP: "Kolumbija (pesosi)",
            CRC: "Kostarika (kolon)",
            CZK: "Češka republika (krona)",
            DKK: "Danska (krone)",
            DOP: "Dominikanska republika (pesosi)",
            EGP: "Egipt (funti)",
            EUR: "Avstrija, Belgija, Finska, Francija, ..., Slovenija, Španija (evro)",
            GBP: "Anglija, Velika Britanija (funti)",
            HKD: "Hongkong (dolarji)",
            HRK: "Hrvaška (kuna)",
            HUF: "Madžarska (forint)",
            IDR: "Indonezija (rupije)",
            ILS: "Izrael (novi šekli)",
            INR: "Indija (rupije)",
            JPY: "Japonska (jen)",
            KRW: "Koreja, Južna (won)",
            KZT: "Kazahstan (tenge)",
            MAD: "Maroko (dirham)",
            MXN: "Mehika (pesosi)",
            MYR: "Malezija (ringgiti)",
            NOK: "Norveška (krona)",
            NZD: "Nova Zelandija (dolarji)",
            PAB: "Panama (balboa)",
            PEN: "Peru (novi soli)",
            PHP: "Filipini (pesosi)",
            PKR: "Pakistan (rupije)",
            PLN: "Poljska (zlot)",
            PYG: "Paragvaj (gvarani)",
            RON: "Romunija (novi leu)",
            RSD: "Srbščina (cirilica), srbščina (latinica)",
            RUB: "Ruska federacija (rublji)",
            SAR: "Saudova Arabija (rial)",
            SEK: "Švedska (krone)",
            SGD: "Singapur (dolarji)",
            SVC: "Salvador (koloni)",
            THB: "Tajska (baht)",
            TRY: "Turčija (lira)",
            TWD: "Tajvan (novi dolarji)",
            USD: "Ekvador, Portoriko, Združene države Amerike (ameriški dolarji)",
            UYU: "Urugvaj (pesosi)",
            VEF: "Venezuela (bolivar fuerte)",
            VND: "Vietnam (dong)",
            ZAR: "Južna Afrika (rand)"
        },
        // for border toolbar
        allBorders: "Vse obrobe",
        innerBorders: "Notranje obrobe",
        horizontalBorders: "Vodoravne obrobe",
        verticalBorders: "Navpične obrobe",
        outerBorders: "Zunanje obrobe",
        borderColor: "Barva obrobe",
        leftBorder: "Leva obroba",
        topBorder: "Zgornja obroba",
        rightBorder: "Desna obroba",
        bottomBorder: "Spodnja obroba",
        clearBorders: "Brez obrob",
        BorderStyle_ThinSolid: "Tanka, polna",
        BorderStyle_ThinDotted: "Tanka, pikčasta",
        BorderStyle_ThinDashed: "Tanka, črtkana",
        BorderStyle_ThickSolid: "Debela, polna",
        BorderStyle_ThickDotted: "Debela, pikčasta",
        BorderStyle_ThickDashed: "Debela, črtkana"
})

