({	
	viewExpandedBtn: "Kevesebb válasz megtekintése",
	viewCollapsedBtn: "További ${0} válasz megtekintése",
	placeholderMsg: "Ide írja be az üzenetet",
	sure: "Biztosan törölni szeretné ezt a megjegyzést?",
	exceed: "A megjegyzés túl hosszú.\n A beírt megjegyzés meghaladja az engedélyezett hosszt.\n Rövidítse legföljebb ${0} karakter hosszúra, majd kattintson a Hozzáadás lehetőségre.",
	remainLabelHint:"A megjegyzés hossza elérte az 500 karakteres korlátot.",
	tipsCommentField: "Megjegyzés írása az összes vagy csak egy szerkesztőnek",
	tipsRespondField: "Válasz írása az összes vagy csak egy szerkesztőnek",	
	resolveBtn: "Lezárás",	
	replyBtn: "Válasz",
	saveBtn: "Hozzászólás",
	deleteBtn: "Törlés",
	cancelBtn: "Mégse",
	reopenBtn: "Megnyitás újra",
	todayAt: "Ma, ${time} időpontban",
	yesterdayAt: "Tegnap, ${time} időpontban",
	dateAt: "${date} napon ${time} időpontban",
	mentions: "Egy megemlíteni kívánt felhasználó kiválasztása",
	noMentions: "Üres cellára koppintás a bevitel befejezéséhez",
	nocomments: "A(z) '${0}' dokumentumban nincsenek megjegyzések.",
	
	newComments:"Új megjegyzések",
	mentiontomesomebody:"Valaki",
	mentiontome:"${0} felhasználó megemlítette egy megjegyzésben",
	
	newcommentsnumber:"Az olvasatlan megjegyzések száma",
	jawsnewcommentsnumber: "Az olvasatlan megjegyzések száma: ",
	jawsnactivecommentsnumber: "Az aktív megjegyzések száma: ",
	
	activenum:"Az aktív megjegyzések száma",
	filterDesc:"Megjegyzések szűrése",
	menuallcomments:"Minden megjegyzés",
	menutome: "@én",
	menubyme: "Saját",
	menuactive: "Aktív",
	menuresolved: "Lezárva",
	searchDesc: "Megjegyzések keresése",
	search: "Keresés",
	closeDesc: "Keresés bezárása",
	clear: "Kiürítés",
	warnEnterKeywords: "Keresőkifejezések beírása",
	nocommentstome: "Jelenleg nincsenek megjegyzések vagy válaszok a(z) '${0}' dokumentumban, amelyek említenek engem.",
	nocommentsbyme: "Jelenleg nincsenek általam írt megjegyzések vagy válaszok a(z) '${0}' dokumentumban.",
	nocommentsar: "Jelenleg nincsenek megjegyzések a(z) '${0}' kategóriában a(z) '${1}' dokumentumban.",
	nosearchedcomments: "Jelenleg nincsenek '${0}' elemet tartalmazó megjegyzések vagy válaszok a(z) '${1}' kategóriában, a(z) '${2}' dokumentumban.",
	
	prevBtn: "Előző",
	nextBtn: "Következő",
	mentionHint:"${0}–${1} egyezés megjelenítése (összesen: ${2})",
		
	resolveFlag: "Lezárt megjegyzések",
	jawsCommentHint: "${authorname} tette közzé a megjegyzést ${timestamp} időpontban",
	jawsReplyHint: "${authorname} tette közzé a választ ${timestamp} időpontban",
	jawsContentHint: "A tartalom a következő: ${content}",
	jawsCommentStatusHint: "Az állapot a következő: ${status}",
	jawsCommentKeyHint: "Az Enter vagy a Szóköz billentyű lenyomásával a dokumentumhoz ugorhat, ahol megtekintheti a teljes megjegyzésszálat, illetve lezárhatja, megválaszolhatja vagy törölheti a megjegyzéseket.",
	jawsMentionHint: "Docs említési eszközelem. A Fel vagy Le nyilak megnyomásával választhatja ki a megemlíteni kívánt felhasználót",
	jawsMentionSelected: "A megemlítéshez nyomja meg az Enter vagy a Szóköz billentyűt",
	commentDeletedMsg: "A jelenlegi megjegyzést törölte egy másik szerkesztő.",
	commentResolvedMsg: "A jelenlegi megjegyzést már lezárták.",
	warningCommentMsg: "A Docs alkalmazásban a(z) ${0} fájlokhoz hozzáfűzött megjegyzések csak online támogatottak. A rendszer eltávolítja a megjegyzések csatolását, ha egy új változatot töltenek fel szerkesztéshez.",
	orphanCommentTip: "A rendszer eltávolította a megjegyzések csatolását ebben a feltöltött változatban.",
	warningCommentName: "Figyelem!"
})

