({
	stViewClient:"Mostra client Sametime ",
	stChatList:"Fare clic per aprire il client Web Sametime in una nuova finestra ",
	stWebClient:"HCL Sametime ",
	stStatusMeeting:"In riunione",
	stStatusAvailable:"Disponibile",
	stViewBd:"Mostra elenco di amici Sametime ",
	stErrorSTServer:"Errore di connessione a Sametime",
	stStatusAway:"Sono assente",
	stLConnLogIn:"Iscriviti a IBM per visualizzare lo stato di Sametime ",
	stActionBar:"Barra delle azioni di Sametime ",
	stStatusBusy:"Sono occupato ",
	stLogin:"Accedi a Sametime ",
	stUserOffline:"Sono offline",
	stStartChat:"Fare clic qui per avviare una conversazione ",
	stLogout:"Esci da Sametime ",
	stDisconnect:"Disconnetti da Sametime",
	stViewSTActions:"Fare clic per visualizzare le azioni di Sametime ",
	stError:"Si è verificato un errore.  Il servizio Sametime non è disponibile. ",
	stUnableToConnect:"La connessione a Sametime non è disponibile. ",
	stConnect:"Connetti a Sametime",
	stNoStatuAvailable:"Nessuno stato Sametime disponibile",
	stStatusdnt:"Non disturbare",
	stLoadingSTStatus:"Caricamento stato Sametime in corso...",
	stShareAs:"Condividi documento...",
	stShareDlgTitle:"Condividi documento tramite Sametime...",
	stShareDlgMsgTemplate:"Vuoi 'condividere ${file_name}' con ${contact_name} come Editor o Lettore?",
	stShareEditor:"Editor",
	stShareReader:"Lettore",
	stShareSuccessTemplate:"${contact_name}, desidero condividere il documento '${file_name}' con te:\n<a href=\"${document_link}\">${document_link}</a>"
})
