/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
    Arrow01_Gray: "Šípka 01, sivá",
    Arrow02_Gray: "Šípka 02, sivá",
    Arrow03_Red: "Šípka 03, červená",
    Arrow04_Blue: "Šípka 04, modrá",
    Arrow05_Blue: "Šípka 05, modrá",
    Arrow06_Yellow: "Šípka 06, žltá",
    Arrow07_Red: "Šípka 07, červená",
    Arrow08_Gray: "Šípka 08, sivá",
    Arrow09_Orange: "Šípka 09, oranžová",
    Arrow10_Blue: "Šípka 10, modrá",
    Arrow11_Blue: "Šípka 11, modrá",
    Arrow12_Green: "Šípka 12, zelená",
    Arrow13_Blue: "Šípka 13, modrá",
    Arrow14_Green: "Šípka 14, zelená",
    Arrow15_Orange: "Šípka 15, oranžová",
    Arrow16_Gray: "Šípka 16, sivá",
    CircleArrow01_Green: "Kruhová šípka 01, zelená",
    CircleArrow02_Multi: "Kruhová šípka 02, viacfarebná",
    CircleArrow03_Multi: "Kruhová šípka 03, viacfarebná",
    CircleArrow04_Multi: "Kruhová šípka 04, viacfarebná",
    CircleArrow05_Multi: "Kruhová šípka 05, viacfarebná",
    CircleArrow06_Multi: "Kruhová šípka 06, viacfarebná",
    CircleArrow07_Blue: "Kruhová šípka 07, modrá",
    CircleArrow08_Green: "Kruhová šípka 08, zelená",
    CircleArrow09_Multi: "Kruhová šípka 09, viacfarebná",
    CurvedArrow01_Gray: "Zaoblená šípka 01, sivá",
    CurvedArrow02_Blue: "Zaoblená šípka 02, modrá",
    CurvedArrow03_Blue: "Zaoblená šípka 03, modrá",
    CurvedArrow04_Orange: "Zaoblená šípka 04, oranžová",
    CurvedArrow05_Red: "Zaoblená šípka 05, červená",
    CurvedArrow06_Blue: "Zaoblená šípka 06, modrá",
    CurvedArrow07_Purple: "Zaoblená šípka 07, purpurová",
    CurvedArrow08_Green: "Zaoblená šípka 08, zelená",
    CurvedArrow09_Gray: "Zaoblená šípka 09, sivá",
    CurvedArrow10_Blue: "Zaoblená šípka 10, modrá",
    CurvedArrow11_Orange: "Zaoblená šípka 11, oranžová",
    CurvedArrow12_Blue: "Zaoblená šípka 12, modrá",
    CurvedArrow13_Green: "Zaoblená šípka 13, zelená",
    CurvedArrow14_Brown: "Zaoblená šípka 14, hnedá",
    CurvedArrow15_Blue: "Zaoblená šípka 15, modrá",
    CurvedArrow16_Gray: "Zaoblená šípka 16, sivá",
    CurvedArrow17_Gray: "Zaoblená šípka 17, sivá",
    CurvedArrow18_Gray: "Zaoblená šípka 18, sivá",
    CurvedArrow19_Gray: "Zaoblená šípka 19, sivá",
    CurvedArrow20_Gray: "Zaoblená šípka 20, sivá",
    TrendArrow01_Red: "Trendová šípka 01, červená",
    TrendArrow02_Green: "Trendová šípka 02, zelená",
    TrendArrow03_Orange: "Trendová šípka 03, oranžová",
    TrendArrow04_Red: "Trendová šípka 04, červená",
    TrendArrow05_Orange: "Trendová šípka 05, oranžová",
    TrendArrow06_Blue: "Trendová šípka 06, modrá",
    TrendArrow07_Orange: "Trendová šípka 07, oranžová",
    TrendArrow08_Yellow: "Trendová šípka 08, žltá",
    TrendArrow09_Blue: "Trendová šípka 09, modrá",
    TrendArrow10_Blue: "Trendová šípka 10, modrá",
    TrendArrow11_Blue: "Trendová šípka 11, modrá",
    TrendArrow12_Blue: "Trendová šípka 12, modrá",
    TrendArrow13_Red: "Trendová šípka 13, červená",
    TrendArrow14_Multi: "Trendová šípka 14, viacfarebná",
    TrendArrow15_Blue: "Trendová šípka 15, modrá",
    Bullet01_Circle_DarkRed: "Odrážka 01, kruh, tmavá červená",
    Bullet02_Circle_Blue: "Odrážka 02, kruh, modrá",
    Bullet03_Circle_Green: "Odrážka 03, kruh, zelená",
    Bullet04_Square_Black: "Odrážka 04, štvorec, čierna",
    Bullet05_Square_Orange: "Odrážka 05, štvorec, oranžová",
    Bullet06_Square_Purple: "Odrážka 06, štvorec, purpurová",
    Bullet07_Diamond_Blue: "Odrážka 07, diamant, modrá",
    Bullet08_Diamond_LightBlue: "Odrážka 08, diamant, svetlá modrá",
    Bullet09_Diamond_Red: "Odrážka 09, diamant, červená",
    Bullet10_Star_Yellow: "Odrážka 10, hviezda, žltá",
    Bullet11_Star_Blue: "Odrážka 11, hviezda, modrá",
    Bullet12_Triangle_Blue: "Odrážka 12, trojuholník, modrá",
    Bullet13_Triangle_DarkGreen: "Odrážka 13, trojuholník, tmavá zelená",
    Bullet14_Arrow_Red: "Odrážka 14, šípka, červená",
    Bullet15_Arrow_Blue: "Odrážka 15, šípka, modrá",
    Bullet16_Box_Blue: "Odrážka 16, okienko, modrá",
    Bullet17_Box_Red: "Odrážka 17, okienko, červená",
    Bullet18_Asterisk_LightBlue: "Odrážka 18, hviezdička, svetlá modrá",
    Bullet19_Leaves_Red: "Odrážka 19, listy, červená",
    Bullet20_Target_Blue: "Odrážka 20, cieľ, modrá",
    Bullet21_Arrow_Blue: "Odrážka 21, šípka, modrá",
    Bullet22_Arrow_DarkBlue: "Odrážka 22, šípka, tmavá modrá",
    Bullet23_Arrow_Brown: "Odrážka 23, šípka, hnedá",
    Bullet24_Flag_Red: "Odrážka 24, zástava, červená",
    Bullet25_Flag_Green: "Odrážka 25, zástava, zelená",
    Bullet26_X_Red: "Odrážka 26, X, červená",
    Bullet27_X_Black: "Odrážka 27, X, čierna",
    Bullet28_Checkmark_Green: "Odrážka 28, znak začiarknutia, zelená",
    Bullet29_Checkmark_Blue: "Odrážka 29, znak začiarknutia, modrá",
    Bullet30_Square_DarkRed: "Odrážka 30, štvorec, tmavá červená",
    camera: "Fotoaparát",
    computer1: "Počítač 1",
    computer2: "Počítač 2",
    computer3: "Počítač 3",
    Computer_Cloud: "Oblak počítačov",
    Computer_Desktop: "Stolný počítač",
    Computer_Laptop_Black: "Prenosný počítač, čierny",
    Computer_Laptop_Silver: "Prenosný počítač, strieborný",
    Database: "Databáza",
    evelope: "Obálka",
    newspapers: "Novinky",
    openevelope: "Otvorená obálka",
    Server: "Server",
    speaker: "Reproduktor",
    WirelessAccessPoint: "Prístupový bod bezdrôtovej siete",
    Cycle01_Transparent: "Cyklus 01, transparentný",
    Cycle02_Transparent_Blue: "Cyklus 02, transparentný modrý",
    Cycle03_Blue: "Cyklus 03, modrý",
    Cycle04_Blue: "Cyklus 04, modrý",
    Cycle05: "Cyklus 05",
    Cycle06: "Cyklus 06",
    Cycle07: "Cyklus 07",
    Cycle08_Blue: "Cyklus 08, modrý",
    Cycle09_Orange: "Cyklus 09, oranžový",
    Donut01_LightBlue: "Dolka 01, svetlá modrá",
    Donut02_Blue: "Dolka 02, modrá",
    Donut03_Blue: "Dolka 03, modrá",
    Donut04_DarkBlue: "Dolka 04, tmavá modrá",
    Donut05_DarkBlue: "Dolka 05, tmavá modrá",
    Donut06_Blue: "Dolka 06, modrá",
    Donut07_Blue: "Dolka 07, modrá",
    Graph: "Graf",
    People01_Blue: "Ľudia 01, modrá",
    People02: "Ľudia 02",
    Pillars01_Orange: "Stĺporadie 01, zelená",
    Pillars02_LightBlue: "Stĺporadie 02, svetlá modrá",
    Process01_Blue: "Proces 01, modrá",
    Process02_Blue: "Proces 02, modrá",
    Process03_Blue: "Proces 03, modrá",
    Process04_GoUp_Blue: "Proces 04, stupňujúca sa modrá",
    Process05_GoUp_Red: "Proces 05, stupňujúca sa červená",
    Process06_GoUp_Yellow: "Proces 06, stupňujúca sa žltá",
    Process07_Blue: "Proces 07, modrá",
    Pyramid01: "Pyramída 01",
    Pyramid02_Blue: "Pyramída 02, modrá",
    Pyramid03: "Pyramída 03",
    Radial01_Green: "Lúčovitý 01, zelená",
    Radial02_Green: "Lúčovitý 02, zelená",
    Radial03_Sphere: "Lúčovitý 03, guľa",
    Radial04_Sphere_Red: "Lúčovitý 04, guľa, červená",
    Radial05_Sphere_Blue: "Lúčovitý 05, guľa, modrá",
    Radial06_Arrows_DarkBlue: "Lúčovitý 06, šípky, tmavá modrá",
    Radial07_Arrows_DarkBlue: "Lúčovitý 07, šípky, tmavá modrá",
    Section_Circle: "Sekcia, kruh",
    Section_Cubes01: "Sekcia, kocky 01",
    Section_Cubes02_Blue: "Sekcia, kocky 02, modrá",
    Section_Cubes03_Orange: "Sekcia, kocky 03, oranžová",
    Section_Cubes04: "Sekcia, kocky 04",
    Section_Cubes05: "Sekcia, kocky 05",
    Section_Cuboids01_Blue: "Sekcia, kvádre 01, modrá",
    Section_Cuboids02_Blue: "Sekcia, kvádre 02, modrá",
    Section_Cuboids03: "Sekcia, kvádre 03",
    Section_Gears01: "Sekcia, ozubené kolieska 01",
    Section_Gears02: "Sekcia, ozubené kolieska 02",
    Section_Gears03: "Sekcia, kvádre 03",
    Section_Hexagon04_Orange: "Sekcia, šesťhran 04, oranžová",
    Section_Hexagons01: "Sekcia, šesťhrany 01",
    Section_Hexagons02_Blue: "Sekcia, šesťhrany 02, modrá",
    Section_Hexagons03_Blue: "Sekcia, šesťhrany 03, modrá",
    Section_Leaves01_LightBlue: "Sekcia, listy 01, svetlá modrá",
    Section_Leaves02_Green: "Sekcia, listy 02, zelená",
    Section_Pasters01: "Sekcia, nálepky 01",
    Section_Pasters02_Blue: "Sekcia, nálepky 02, modrá",
    Section_Puzzle01: "Sekcia, puzzle 01",
    Section_Puzzle02: "Sekcia, puzzle 02",
    Section_Puzzle03: "Sekcia, puzzle 03",
    Section_Rectangles: "Sekcia, obdĺžniky",
    Section_Squares: "Sekcia, štvorce",
    Section_Triangle: "Sekcia, trojuholník",
    Target: "Cieľ",
    Venn01: "Venn 01",
    Venn02: "Venn 02",
    Venn03: "Venn 03",
    Venn04: "Venn 04",
    Venn05: "Venn 05",
    Venn06_Blue: "Venn 06, modrá",
    Venn07_Blue: "Venn 07, modrá",
    Venn08: "Venn 08",
    Blackboard: "Čierna tabuľa",
    Books: "Knihy",
    Books1: "Knihy 1",
    books2: "Knihy 2",
    Chalk: "Krieda",
    clipboard: "schránka",
    clock: "hodiny",
    Globe: "Zemeguľa",
    Glue: "Lepidlo",
    GraduationCap: "Čiapka na promócie",
    magnifyingglass: "zväčšovacia lupa",
    Microscope: "Mikroskop",
    Notebook: "Poznámkový blok",
    notepad1: "Zápisník 1",
    notepad2: "Zápisník 2",
    notepad3: "Zápisník 3",
    PaperClip_Blue: "Spinka na papiere, modrá",
    PaperClip_Red: "Spinka na papiere, červená",
    Pencil: "Ceruzka",
    Ruler: "Pravítko",
    TestTubes: "Skúmavky",
    thumbtack: "Pripináčik",
    clouds: "Oblaky",
    DrippingFaucet: "Kvapkajúci kohútik",
    Earth: "Zem",
    EndangeredAnimals1: "Ohrozené zvieratá 1",
    EndangeredAnimals2: "Ohrozené zvieratá 2",
    GreenCar: "Zelené auto",
    GreenFactory: "Zelená továreň",
    GreenHouse: "Skleník",
    Leaf1: "List 1",
    Leaf2: "List 2",
    lightbulb: "Žiarovka",
    LightBulb_Flourescent_Off: "Žiarovka, fluorescenčná, vypnutá",
    LightBulb_Flourescent_On: "Žiarovka, fluorescenčná, zapnutá",
    LightBulb_Standard_Off1: "Žiarovka, štandardná, vypnutá 1",
    LightBulb_Standard_Off2: "Žiarovka, štandardná, vypnutá 2",
    LightBulb_Standard_On: "Žiarovka, štandardná, zapnutá",
    lightningcloud: "Oblak s bleskom",
    Pollution_Car: "Znečistenie z áut",
    Pollution_Factory: "Znečistenie z továrne",
    Raindrop: "Dažďová kvapka",
    RecycleBin: "Kôš",
    RecycleSymbol: "Symbol recyklácie",
    RenewableEnergySymbol: "Symbol obnoviteľnej energie",
    RenewableEnergy_Solar: "Solárna obnoviteľná energia",
    RenewableEnergy_Water: "Vodná obnoviteľná energia",
    RenewableEnergy_Wind: "Veterná obnoviteľná energia",
    sun: "Slnko",
    Sun1: "Slnko 1",
    Sun2: "Slnko 2",
    sundandcloud: "Slnko a oblak",
    world: "Svet",
    Agreement: "Zmluva",
    ATM01: "Bankomat 01",
    ATM02: "Bankomat 02",
    Balance_Balanced1: "Vyvážená rovnováha 1",
    Balance_Balanced2: "Vyvážená rovnováha 2",
    Balance_Unbalanced1: "Nevyvážená rovnováha 1",
    Balance_Unbalanced2: "Nevyvážená rovnováha 2",
    Calculator: "Kalkulačka",
    Chart_Decrease1: "Graf, pokles 1",
    Chart_Decrease2: "Graf, pokles 2",
    Chart_Increase1: "Graf, nárast 1",
    Chart_Increase2: "Graf, nárast 2",
    Chart_Plateau: "Graf, platina",
    Check: "Začiarknutie",
    Contract: "Zmluva",
    CreditCard_Black: "Kreditná karta, čierna",
    CreditCard_Cut: "Kreditná karta, vystrihnúť",
    CreditCard_Gold: "Kreditná karta, zlatá",
    Currency_Dollar: "Mena, dolár",
    Currency_Dollars: "Mena, doláre",
    Currency_Stack: "Mena, balík",
    Currency_StackCoins: "Mena, mince",
    GoldBar: "Zlatá tabuľka",
    GoldBar_Stack: "Zlaté tabuľky, kopa",
    MoneyBag01: "Taška na peniaze 01",
    MoneyBag02: "Taška na peniaze 02",
    PercentSign: "Znak percenta",
    PiggyBank01_Broken: "Pokladnička 01, zlomená",
    PiggyBank02_Broken: "Pokladnička 02, zlomená",
    PiggyBank_Coins: "Pokladnička, mince",
    PiggyBank_Currency: "Pokladnička, mena",
    Portfolio: "Portfólio",
    PriceTag: "Cenovka",
    Safe_Closed: "Trezor, zatvorený",
    Safe_Empty: "Trezor, prázdny",
    Safe_Full: "Plný trezor",
    Seal_Gold: "Pečať, zlatá",
    Seal_Red: "Pečať, červená",
    Seal_Silver: "Pečať, strieborná",
    Wallet_Empty: "Peňaženka prázdna",
    Wallet_Full1: "Peňaženka plná 1",
    Wallet_Full2: "Peňaženka plná 2",
    BusinessPerson_Female6: "Obchodníčka 6",
    BusinessPerson_Male3: "Obchodník 3",
    Computer_User_Female1: "Užívateľka počítača 1",
    ConstructionWorker2: "Stavebný pracovník 2",
    Presenter_Female1: "Prezentujúca 1",
    Component_Circle01_Transparent_DarkBlue: "Komponent, kruh 01, transparentný, tmavá modrá",
    Component_Circle02_Transparent_Bule: "Komponent, kruh 02, transparentný, modrá",
    Component_Circle03_Transparent_Green: "Komponent, kruh 03, transparentný, zelená",
    Component_Circle04_Transparent_Orange: "Komponent, kruh 04, transparentný, oranžová",
    Component_Circle05_Transparent_Red: "Komponent, kruh 05, transparentný, červená",
    Component_Cube01_DarkBlue: "Komponent, kocka 01, tmavá modrá",
    Component_Cube02_LightBlue: "Komponent, kocka 02, svetlá modrá",
    Component_Cube03_Green: "Komponent, kocka 03, zelená",
    Component_Cube04_Orange: "Komponent, kocka 04, oranžová",
    Component_Cube05_DarkRed: "Komponent, kocka 05, tmavá červená",
    Component_Cuboid01_DarkBlue: "Komponent, kváder 01, tmavá modrá",
    Component_Cuboid02_Blue: "Komponent, kváder 02, modrá",
    Component_Cuboid03_Green: "Komponent, kváder 03, zelená",
    Component_Cuboid04_Orange: "Komponent, kváder 04, oranžová",
    Component_Cuboid05_Red: "Komponent, kváder 05, červená",
    Component_Gear01_DarkBlue: "Komponent, ozubené koliesko 01, tmavá modrá",
    Component_Gear02_LightBlue: "Komponent, ozubené koliesko 02, svetlá modrá",
    Component_Gear03_Green: "Komponent, ozubené koliesko 03, zelená",
    Component_Gear04_DarkRed: "Komponent, ozubené koliesko 04, tmavá červená",
    Component_Gear05_Orange: "Komponent, ozubené koliesko 05, oranžová",
    Component_Person01_DarkBlue: "Komponent, osoba 01, tmavá modrá",
    Component_Person02_Blue: "Komponent, osoba 02, modrá",
    Component_Person03_Green: "Komponent, osoba 03, zelená",
    Component_Person04_DarkRed: "Komponent, osoba 04, tmavá červená",
    Component_Person05_Orange: "Komponent, osoba 05, oranžová",
    Component_PuzzlePiece01_DarkBlue: "Komponent, dielik puzzle 01, tmavá modrá",
    Component_PuzzlePiece02_Blue: "Komponent, dielik puzzle 02, modrá",
    Component_PuzzlePiece03_Green: "Komponent, dielik puzzle 03, zelená",
    Component_PuzzlePiece04_Red: "Komponent, dielik puzzle 04, červená",
    Component_PuzzlePiece05_Orange: "Komponent, dielik puzzle 05, oranžová",
    Component_Sphere01_DarkBlue: "Komponent, guľa 01, tmavá modrá",
    Component_Sphere02_LightBlue: "Komponent, guľa 02, svetlá modrá",
    Component_Sphere03_Green: "Komponent, guľa 03, zelená",
    Component_Sphere04_DarkRed: "Komponent, guľa 04, tmavá červená",
    Component_Sphere05_Orange: "Komponent, guľa 05, oranžová",
    Book: "Kniha",
    Box01: "Škatuľa 01",
    Box02: "Škatuľa 02",
    Bulb01_Yellow: "Žiarovka 01, žltá",
    Bulb02_Yellow: "Žiarovka 02, žltá",
    Calendar: "Kalendár",
    Chart: "Graf",
    Clipboard: "Schránka",
    Clock: "Hodiny",
    Compass: "Kompas",
    Flag01_Red: "Zástava 01, červená",
    Flag02_Green: "Zástava 02, zelená",
    Flag03_Blue: "Zástava 03, modrá",
    Gift: "Darček",
    House: "Dom",
    Icon_Computer01_White: "Ikona počítača 01, biela",
    Icon_Computer02_Black: "Ikona počítača 02, čierna",
    Icon_Disk01_Blue: "Ikona disku 01, modrá",
    Icon_Disk02_Green: "Ikona disku 02, zelená",
    Icon_Document01_Grey: "Ikona dokumentu 01, sivá",
    Icon_Document02_Grey: "Ikona dokumentu 02, sivá",
    Icon_Document03_Blue: "Ikona dokumentu 03, sivá",
    Icon_Document04_Blue: "Ikona dokumentu 04, sivá",
    Icon_Envelope01_Blue: "Ikona obálky 01, modrá",
    Icon_Envelope02_Yellow: "Ikona obálky 02, žltá",
    Icon_Envelope03_Open_Yellow: "Ikona obálky 03, otvorená, žltá",
    Icon_Envelope04_Open_Yellow: "Ikona obálky 04, otvorená, žltá",
    Icon_Folder01_Yellow: "Ikona zložky 01, žltá",
    Icon_Folder02_Yellow: "Ikona zložky 02, žltá",
    Icon_Folder03_Open_Yellow: "Ikona zložky 03, otvorená, žltá",
    Icon_Folder04_Open_Yellow: "Ikona zložky 04, otvorená, žltá",
    Icon_Gear01_Grey: "Ikona ozubeného kolieska 01, sivá",
    Icon_Gear02_Blue: "Ikona ozubeného kolieska 02, modrá",
    Icon_Network01_Blue: "Ikona siete 01, modrá",
    Icon_Network02: "Ikona siete 02",
    Icon_Pencil01: "Ikona ceruzky 01",
    Icon_Pencil02: "Ikona ceruzky 02",
    Icon_Printer01_White: "Ikona tlačiarne 01, biela",
    Icon_Printer02_Black: "Ikona tlačiarne 02, čierna",
    Key01: "Kľúč 01",
    Key02: "Kľúč 02",
    Lock01_Yellow: "Zámok 01, žltá",
    Lock02_Yellow: "Zámok 02, žltá",
    Lock03_Blue: "Zámok 03, modrá",
    Lock04_Blue: "Zámok 04, modrá",
    Magnet: "Magnet",
    MagnifyingGlass: "Zväčšovacia lupa",
    Medal: "Medaila",
    Notebook: "Poznámkový blok",
    Phone: "Telefón",
    PieChart: "Koláčový graf",
    Pin: "Pripnúť",
    PuzzlePiece: "Dielik puzzle",
    PuzzlePieces: "Dieliky puzzle",
    Roadblock: "Zátarasa",
    Scissors: "Nožnice",
    Shield01: "Štít 01",
    Shield02_Orange: "Štít 02, oranžová",
    Shield03_Blue: "Štít 03, modrá",
    Sign_Ban01: "Značka Zákaz 01",
    Sign_Ban02: "Značka Zákaz 02",
    Sign_CheckBox01: "Značka Začiarkavacie políčko 01",
    Sign_CheckBox02_Unchecked: "Značka Začiarkavacie políčko 02, nezačiarknuté",
    Sign_Checkmark01_Green: "Značka Začiarkavacie políčko 01, zelená",
    Sign_Checkmark02_Green: "Značka Začiarkavacie políčko 02, zelená",
    Sign_DoNotEnter: "Značka Nevstupovať",
    Sign_Error01: "Značka Chyba 01",
    Sign_Error02: "Značka Chyba 02",
    Sign_ExclamationPoint01_Red: "Značka Výkričník 01, červená",
    Sign_ExclamationPoint02_Orange: "Značka Výkričník 02, oranžová",
    Sign_Help01_Green: "Značka Pomoc 01, zelená",
    Sign_Help02_Blue: "Značka Pomoc 02, modrá",
    Sign_Information: "Značka Informácie",
    Sign_Null: "Značka Nula",
    Sign_QuestionMark01_Blue: "Značka Otáznik 01, modrá",
    Sign_QuestionMark02_Red: "Značka Otáznik 02, červená",
    Sign_RadioButton01: "Značka Prepínač 01",
    Sign_RadioButton02_Unchecked: "Značka Prepínač 02, nevybratá",
    Sign_Warning01_Red: "Značka Varovanie 01, červená",
    Sign_Warning02_Orange: "Značka Varovanie 02, oranžová",
    Sign_X01_Red: "Značka X 01, červená",
    Sign_X02_Red: "Značka X 02, červená",
    Star_Yellow: "Hviezda, žltá",
    Wrench: "Kľúč na matice",
    Airplane_Blue: "Lietadlo, modrá",
    Bicycle_Blue: "Bicykel, modrá",
    Bus: "Autobus",
    Canoe_Blue: "Kanoe, modrá",
    Car_Red: "Auto, červená",
    Helicopter_Blue: "Helikoptéra, modrá",
    Motorcycle_Red: "Motocykel, červená",
    Pedestrian_Blue: "Chodec, modrá",
    PersonalTransporter_Green: "Osobný dopravný prostriedok, zelená",
    Sailboat_Red: "Plachetnica, červená",
    Scooter_Orange: "Skúter, oranžová",
    Train_Red: "Vlak, červená",
    Truck_Blue: "Kamión, modrá",
    
    aria_category_selector: "Možnosti kategórie obrázkov",
    filterImageGallery: "Filtrovať galériu obrázkov"

})
