({
	labelPrintConfig: "Pentru cele mai bune rezultate, setaţi-vă pagina dumneavoastră de browser să utilizeze următoarea configuraţie:",
	labelConfigPageSize: "Dimensiune pagină: ${0}",
	labelConfigOrientation: "Orientare: ${0}",
	labelConfigHeader: "Antet: blanc ",
	labelConfigFooter: "Subsol: blanc ",
	labelConfigMargins: "Margini: ",
	labelConfigMarginTop: "Sus: ${0}${1}",
	labelConfigMarginBottom: "Jos: ${0}${1}",
	labelConfigMarginLeft: "Stânga: ${0}${1}",
	labelConfigMarginRight: "Dreapta: ${0}${1}",
	labelPrintContinue: "După ce setaţi setările de browser, faceţi clic pe OK pentru a continua tipărirea fişierului dumneavoastră.",
	labelMm: "milimetri ",
	labelInch: "inch ",
	labelPortrait: "Portret",
	labelPageA4: "A4",
	labelLetter: "Literă ",
	labelLandscape: "Peisaj ",
	titlePrintConfig: "Tipărire setări ",
	titlePrepare: "Pregătire pentru tipărire ",
	msgPrepare: "Fişierul este pregătit pentru tipărire. Pregătirea poate lua mult timp.",
	errPrepare: "A apărut o eroare în timpul pregătirii datelor.\nDoriţi să încercaţi din nou?",
	titleErr: "Eroare",
	btnRetry: "Reîncercaţi "
})
