({	
	dlgTaskCreateTitle: "セクションの割り当て",  
	dlgTaskDeleteTitle: "セクションの削除", 
	dlgTaskEditTitle: "割り当ての編集",
	dlgTaskRewordTitle: "割り当ての再作業",
	dlgTaskHistoryTitle: "このセクションについて",
	dlgTaskReopenTitle: "割り当ての再オープン",
	dlgTaskReassignTitle: "セクションの再割り当て",
	dlgTaskDeleteBtn: "削除",
	creatingTaskAsTODO: "割り当てを、「アクティビティー」アプリケーションで To Do 項目として保存しています",
	creatingTaskAsTODO2: "割り当てを保存しています",
	creatingTaskAsTODO3: "割り当てを保存しています",
	updatingTask: "割り当てを、「アクティビティー」アプリケーションで更新しています",
	updatingTask2: "割り当てを更新しています",
	updatingTask3: "割り当てを更新しています",
	restoringTask: "アクティビティーで割り当てが復元されるまで待機してください。",
	creatingFragment: "この選択内容について非公開文書を作成しています",
	updatingMaster: "処理中です... このセクションをメイン文書内で更新しています",
	cannotAccessActivity: "エラー。割り当てを記録するために、アクティビティー・サーバーにアクセスすることができません。後でやり直してください。",
	cannotAccessActivity2: "エラー。割り当てを記録するために、サーバーにアクセスすることができません。 後でやり直してください。",
	cannotAccessActivityContent: "割り当てを記録するために、アクティビティー・サーバーにアクセスすることができません。後でやり直してください。",
	cannotRecordAssignment: "割り当てを記録するために、アクティビティー・サーバーにアクセスすることができません。後でやり直してください。",
	notMemberofActivity: "アクティビティーが割り当てを記録できません。自分がアクティビティーに追加されていることを確認し、やり直してください。",
	cannotLoadActivity: "割り当てをロードするために、アクティビティー・サーバーにアクセスすることができません。後でやり直してください。",
	cannotLoadActivity2: "割り当てをロードするために、サーバーにアクセスすることができません。後でやり直してください。",
	cannotLoadAssignment: "この割り当てをロードするために、アクティビティー・サーバーにアクセスすることができません。後でやり直してください。",
	cannotSupportSocialEdit: "セクションの共同編集または割り当てを行う権限がありません。",
	cannotDeleteDraft: "現時点ではドラフトを削除できません。後でファイルを手動で削除してください。",
	taskAlreadyRemoved: "この文書のタスクが削除されたか、タスクを編集する許可がありません。",
	taskAlreadyCompleted: "タスクは完了したか、キャンセルされました。",
	taskAlreadyReassigned: "タスクは再割り当てされています。",
	assignmentAlreadyExist: "選択された領域は以前に割り当てられています。",
	notAllowedEditMaster: "メイン文書を編集できません。これを実行する権限があるかどうかを確認してください。",
	notAllowedEditPaticipant: "担当者またはレビュー担当者が定義されていないか、編集権限を持っていません。担当者またはレビュー担当者が正しいアクセス権限を持つようにしてください。",
	notValidAssignment: "割り当ては無効です。アクティビティー・サーバー上の割り当てプロパティーの一部が破損している可能性があります。「アクション」>「割り当ての削除」をクリックして、これを削除できます。",
	disableBlockerMsg: "ポップアップ・ブロッカーを有効にしているために、ページが正しく表示されません。Web サイト *cn.ibm.com のポップアップの表示を許可してください。",
	writeDesc: "${0} の書き込み: ${1}",
	reviewDesc: "${0} のレビュー: ${1}",
	reworkDesc: "${0} の再作業: ${1}",
	writeCompleteDesc: "セクション ${0} は ${1} によって書き込まれました",
	reviewCompleteDesc: "セクション ${0} は ${1} によってレビューされました",
	workingPrivateDesc: "${0} に対して ${1} が非公開で作業しています",
	actions: "アクション",	
	onlyAssignerDeleteTask: "完了としてマークされていないこの割り当てを削除することはできません。割り当てを行ったユーザーだけが削除することができます。",
	actionBtnEdit: "割り当ての編集",
	actionBtnRemove: "割り当ての削除",
	actionBtnAbout: "このセクションについて",
	actionBtnMarkComplete: "完了としてマーク",
	actionBtnWorkPrivately: "非公開で作業",
	actionBtnApprove: "このセクションを承認",
	actionBtnGotoPrivate: "非公開文書へ移動",
	actionBtnCancelPrivate: "非公開の作業のキャンセル",
	actionBtnRework: "再作業が必要",
	actionBtnReopen: "割り当ての再オープン",
	actionBtnReassign: "セクションの再割り当て",
	creating: "作成しています...",
	deleting: "削除中...",
	updating: "更新中...",
	loading: "ロード中...",
	restoring: "復元中...",
	lockCoeditingTask:"別の編集者が同じ割り当てを処理しています。後でやり直してください。"
})
