﻿/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        fileMenu: "Tiedosto",
        fileMenu_New: "Uusi",
        fileMenu_NewDocument: "Asiakirja",
        fileMenu_NewFromTemplate: "Mallipohjasta",
        fileMenu_NewDocumentfromTemplate: "Asiakirja mallipohjasta",
        fileMenu_NewPresentation: "Esitys",
        fileMenu_NewPresentationfromTemplate: "Esitys mallipohjasta",
        fileMenu_NewSpreadsheet: "Laskentataulukko",
        fileMenu_NewSpreadsheetFromTemplate: "Laskentataulukko mallipohjasta",
        fileMenu_Open: "Avaa",
        fileMenu_Import: "Tuo...",
        //	fileMenu_Close: "Close",
        fileMenu_Discard: "Palauta viimeisin versio",
        fileMenu_ClearTrackChange: "Poista muutosmerkinnät",
        fileMenu_SpreadsheetSettings: "Määritä asiakirjan paikallistunnus...",
        filemenu_revisionhistory: "Muutosversiot",
        fileMenu_Save: "Tallenna",
        fileMenu_SaveAs: "Kopioi...",
        fileMenu_AutoPublish: "Julkaise automaattisesti",
        fileMenu_AutoCheckIn: "Kuittaa sisään automaattisesti",
        fileMenu_PublishVersion: "Julkaise nyt",
        fileMenu_AutoPublish2: "Tallenna automaattisesti tietovarastoon",
        //	fileMenu_AutoPublish_Tips: "Makes your changes available to readers at the end of each editing session.",
        fileMenu_PublishVersion2: "Tallenna nyt tietovarastoon",
        fileMenu_AutoPublish3: "Tallenna automaattisesti kohteeseen ${0}",
        fileMenu_PublishVersion3: "Tallenna nyt kohteeseen ${0}",      
        fileMenu_SubmitForReview: "Lähetä tarkastettavaksi...",
        fileMenu_CheckinVersion: "Kuittaa sisään...",
        fileMenu_Unlock: "Poista lukitus",
        //	fileMenu_SaveAsDraft: "as Draft",
        //	fileMenu_SaveInMyDocs: "in My Documents",
        //	fileMenu_SaveToSymphony: "to Lotus Symphany",
        fileMenu_DownloadAs: "Lataa muodossa",
        fileMenu_PDF: "PDF",
        fileMenu_ODF: "ODF",
        fileMenu_DOC: "Microsoft Word 97–2007 (*.doc)",
        fileMenu_ODS: "ODS",
        fileMenu_XLS: "Microsoft Excel 97–2007 (*.xls) ",
        fileMenu_ShareWith: "Määritä yhteiskäyttöön...",
        fileMenu_ExportAsPDF: "PDF",
        fileMenu_ExportAsODF: "ODF",
        fileMenu_ExportAsPPT: "Microsoft Powerpoint 97–2007 (*.ppt)",
        //	fileMenu_WebPreview: "Web Preview",
        fileMenu_PrintToPDF: "Tulosta PDF-muotoon...",
        fileMenu_ViewFileDetails: "Näytä tiedoston tiedot...",
        fileMenu_RecentFile: "Viimeisimmät tiedostot",
        fileMenu_Open: "Avaa",
        fileMenu_Download: "Lataa",
        fileMenu_Print: "Tulosta",
        fileMenu_Export: "Vie",
        fileMenu_ExportToCSV: "CSV",
        fileMenu_ExportToPDF: "PDF (.pdf)",
        fileMenu_ExportToMarkdown: "Markdown (.md)",
        fileMenu_ExportToMS: "Microsoft Office -muoto (.${FILEEXTENSION})",
        fileMenu_ExportToODF: "Open Document -muoto (.${FILEEXTENSION})",
        fileMenu_PgSetup: "Sivun asetukset...",

        editMenu: "Muokkaa",
        editMenu_Undo: "Kumoa",
        editMenu_Redo: "Tee uudelleen",
        editMenu_Cut: "Leikkaa",
        editMenu_Copy: "Kopioi",
        editMenu_Paste: "Liitä",
        editMenu_DeleteSlide: "Poista dia",
        editMenu_SelectAll: "Valitse kaikki",
        editMenu_Find: "Etsi...",
        editMenu_Replace: "Korvaa...",
        editMenu_FindReplace: "Etsi ja korvaa...",
        editMenu_EditLink: "Lisää linkki tai muokkaa linkkiä",
        editMenu_DeleteSheet: "Poista taulukko...",
        editMenu_RenameSheet: "Nimeä taulukko uudelleen...",
        editMenu_HideSheet: "Piilota taulukko",
        editMenu_MoveSheet: "Siirrä taulukko...",
        editMenu_DeleteRow: "Poista rivi",
        editMenu_DeleteColumn: "Poista sarake",
        editMenu_DeleteCellLeft: "Poista solut ja siirrä vasemmalle",
        editMenu_DeleteCellUp: "Poista solut ja siirrä ylös",
        editMenu_ClearCell: "Poista sisältöä",

        viewMenu: "Näytä",
        viewMenu_Master: "Päädia",
        viewMenu_Notifications: "Ilmoitukset",
        viewMenu_SlideSorter: "Diojen lajittelunäkymä",
        viewMenu_SpeakerNotes: "Puhujan muistiinpanot",
        viewMenu_Toolbar_Basic: "Perus",
        viewMenu_Toolbar_Advanced: "Lisäasetukset",
        viewMenu_Toolbar_None: "Ei mitään",
        viewMenu_Toolbar: "Työkalurivi",
        viewMenu_Statusbar: "Tilarivi",
        viewMenu_Navigator: "Navigaattori...",
        //viewMenu_Sidebar: "Sidebar",
        viewMenu_ShowHideIndicators: "Näytä yhteismuokkauksen ilmaisimet",
        viewMenu_Assignment: "Toimeksiantojen ilmaisimet",
        viewMenu_Bookmark: "Kirjanmerkit",
        viewMenu_Coediting: "Yhteismuokkauksen korostukset",
        viewMenu_Rulers: "Viivaimet",
        viewMenu_WebLayout: "Web-asettelu",
        viewMenu_AutomaticSpellCheck: "Tarkista oikeinkirjoitus kirjoitettaessa",
        viewMenu_Formulabar: "Kaavarivi",
        viewMenu_moveRight: "Kohdistin siirtyy oikealle Enter-näppäimellä",
        viewMenu_showFullString: "Laajenna sisältöä soluissa",
        viewMenu_Doc: "Näytä asiakirja",
        viewMenu_Templates: "Mallipohjat",
        viewMenu_GridLines: "Piilota ruudukkoviivat",
        viewMenu_UnsupportWarning: "Näytä sanomat, jotka ilmoittavat, että ominaisuus ei ole tuettu",
        viewMenu_HiddenSheets: "Piilotetut taulukot",
        viewMenu_FreezeRows: "Lukitse rivit",
        viewMenu_FreezeColumns: "Lukitse sarakkeet",
        viewMenu_NoFrozenRows: "Ei lukittuja rivejä",
        viewmenu_NoFrozenColumns: "Ei lukittuja sarakkeita",
        viewMenu_FreezeXRows: "Lukitse ${0} riviä",
        viewMenu_FreezeOneRow: "Lukitse ${0} rivi",
        viewMenu_FreezeXColumns: "Lukitse ${0} saraketta",
        viewMenu_FreezeOneColumn: "Lukitse ${0} sarake",
        viewMenu_CarriageReturn: "Muotoilumerkit",
        viewMenu_Navigation: "Navigointiruutu",
        viewMenu_ACL: "Muokattavat alueet",
        viewMenu_GridOnOff: "Ruudukon viivat",
        viewMenu_ObserverMode: 'Tarkkailutila',

        createMenu: "Lisää",
        createMenu_NewSlide: "Uusi dia",
        createMenu_DuplicateSlide: "Monista dia",
        createMenu_ImageFromFile: "Kuva...",
        createMenu_TextBox: "Tekstikenttä",
        createMenu_Shape: "Muoto",
        createMenu_break: "Katko",
        createMenu_RowAbove: "Rivi yläpuolelle",
        createMenu_RowBelow: "Rivi alapuolelle",
        createMenu_ColumnRight: "Sarake oikealle",
        createMenu_ColumnLeft: "Sarake vasemmalle",
        createMenu_Sheet: "Taulukko...",
        createMenu_Image: "Kuva...",
        createMenu_Comments: "Kommentti...",
        createMenu_WebLink: "Web-linkki...",
        createMenu_SpecialCharacter: "Erikoismerkki...",
        createMenu_Function: "Funktio...",
        createMenu_Fromtemplate: "Luo mallipohjasta",

        insertMenu: "Lisää",
        insertMenu_break: "Sivunvaihto",
        insertMenu_sectionbreak: "Osanvaihto",
        insertMenu_Bookmark: "Kirjanmerkki...",
        insertMenu_WebLink: "Linkki...",
        insertMenu_SpecialCharacter: "Erikoismerkki...",
        insertMenu_HorizontalLine: "Vaakaviiva",
        insertMenu_Header: "Ylätunniste",
        insertMenu_Footer: "Alatunniste",
        insertMenu_TableOfContents: "Sisällysluettelo",

        insertMenu_HeaderFooter: "Otsikko/Alaviite",
        insertMenu_HF_Edit: "Muokkaa",
        insertMenu_HF_Hide: "Piilota",
        insertMenu_Endnotes: "Loppuviitteet",
        insertMenu_RowAbove: "Rivi yläpuolelle",
        insertMenu_PageNumber: "Sivunumero",
        insertMenu_PageNumberTop: "Sivun yläreuna",
        insertMenu_PageNumberBottom: "Sivun alareuna",
        insertMenu_PageNumberCurr: "Nykyinen paikka",
        insertMenu_TotalPageNumber: "Sivu 1/N",
        insertMenu_Date: "Päivämäärä...",
        insertMenu_Time: "Aika...",
        insertMenu_Fields: "Kentät",
        //    insertMenu_Comment: "Comment",
        insertMenu_CellRight: "Solut ja siirrä oikealle",
        insertMenu_CellDown: "Solut ja siirrä alas",
        insertMenu_RowBelow: "Rivi alapuolelle",
        insertMenu_ColumnBefore: "Sarake ennen",
        insertMenu_ColumnAfter: "Sarake jälkeen",
        insertMenu_Sheet: "Taulukko...",
        insertMenu_Image: "Kuva...",
        insertMenu_DuplicateSheet: "Monista laskentataulukko",
        insertMenu_Function: "Funktio",
        insertMenu_FunctionSum: "SUM",
        insertMenu_FunctionAverage: "AVERAGE",
        insertMenu_FunctionCount: "COUNT",
        insertMenu_FunctionMax: "MAX",
        insertMenu_FunctionMin: "MIN",
        insertMenu_FunctionMore: "Lisää funktioita...",
        insertMenu_NameRange: "Nimetty alue",
        insertMenu_NameRangeNew: "Uusi alue...",
        insertMenu_NameRangeManage: "Alueiden hallinta...",
        insertMenu_Chart: "Kaavio...",

        contextMenu_insertCellRight: "Lisää solut ja siirrä oikealle",
        contextMenu_insertCellDown: "Lisää solut ja siirrä alas",
        contextMenu_InsertRowAbove: "Lisää rivi yläpuolelle",
        contextMenu_InsertRowBelow: "Lisää rivi alapuolelle",
        contextMenu_InsertColumnBefore: "Lisää sarake edelle",
        contextMenu_InsertColumnAfter: "Lisää sarake jälkeen",
        contextMenu_DownloadImage: "Lataa kuvana",

        formatMenu: "Muotoile",
        formatMenu_Columns: "Sarakkeet",
        formatMenu_DefaultFormatting: "Oletusmuotoilu",
        formatMenu_Template: "Tyylit...",
        contextMenu_Template: "Taulukon tyylit...",
        formatMenu_LineSpacing: "Riviväli",
        formatMenu_LineSpacing1: "1",
        formatMenu_LineSpacing12: "1,2",
        formatMenu_LineSpacing15: "1,5",
        formatMenu_LineSpacing2: "2",
        formatMenu_LineSpacing25: "2,5",
        formatMenu_LineSpacing3: "3",
        formatMenu_TextProperties: "Tekstin ominaisuudet",
        formatMenu_PageBreakBefore: "Sivunvaihto ennen",
        formatMenu_KeepLines: "Pidä rivit yhdessä",
        formatMenu_WidowControl: "Leski- ja orporivien esto",
        formatMenu_Pagination: "Kappaleen ominaisuudet",
        formatMenu_Bold: "Lihavointi",
        formatMenu_Italic: "Kursivointi",
        formatMenu_Underline: "Alleviivaus",
        formatMenu_Strikethrough: "Yliviivaus",
        formatMenu_IncreaseSize: "Kasvata fonttikokoa",
        formatMenu_DecreaseSize: "Pienennä fonttikokoa",
        formatMenu_ImageProperties: "Kuvan ominaisuudet...",
        formatMenu_ChartProperties: "Kaavion ominaisuudet...",
        formatMenu_EditChart: "Muokkaa kaaviota",
        formatMenu_InsertChart: "Lisää kaavio",
        formatMenu_Properties: "Ominaisuudet...",
        formatMenu_Heading: "Otsikko",
        formatMenu_Normal: "Normaali",
        formatMenu_Title: "Otsikko",
        formatMenu_Subtitle: "Alaotsikko",
        formatMenu_Heading1: "Otsikko 1",
        formatMenu_Heading2: "Otsikko 2",
        formatMenu_Heading3: "Otsikko 3",
        formatMenu_Heading4: "Otsikko 4",
        formatMenu_Heading5: "Otsikko 5",
        formatMenu_Heading6: "Otsikko 6",
        formatMenu_Heading7: "Otsikko 7",
        formatMenu_Heading8: "Otsikko 8",
        formatMenu_Heading9: "Otsikko 9",
        formatMenu_BulletedList: "Luettelomerkein merkitty luettelo",
        formatMenu_NumberedList: "Numeroitu luettelo",
        formatMenu_OutLine: "Monitasoinen luettelo",
        formatMenu_Superscript: "Yläindeksi",
        formatMenu_Subscript: "Alaindeksi",
        formatMenu_Align: "Tasaa",
        formatMenu_Left: "Vasemmalle",
        formatMenu_Right: "Oikealle",
        formatMenu_Center: "Keskitä",
        formatMenu_Justify: "Tasaa",
        formatMenu_Text_Direction: "Tekstin suunta",
        formatMenu_Ltr: "Vasemmalta oikealle",
        formatMenu_Rtl: "Oikealta vasemmalle",
        formatMenu_LineSpacing: "Riviväli",
        formatMenu_LineSpacing1: "1,0",
        formatMenu_LineSpacing115: "1,15",
        formatMenu_LineSpacing15: "1,5",
        formatMenu_LineSpacing2: "2,0",
        formatMenu_LineSpacing25: "2,5",
        formatMenu_LineSpacing3: "3,0",
        formatMenu_Top: "Yläreuna",
        formatMenu_Bottom: "Alareuna",
        formatMenu_Middle: "Keskikohta",
        formatMenu_Direction: "Tekstin suunta",
        formatMenu_Rtl: "Oikealta vasemmalle",
        formatMenu_Ltr: "Vasemmalta oikealle",
        formatMenu_Auto: "Kontekstin mukainen",
        formatMenu_SheetDirection: "Taulukon suunta",
        formatMenu_SheetRtl: "Oikealta vasemmalle",
        formatMenu_SheetLtr: "Vasemmalta oikealle",
        formatMenu_Indent: "Lisää sisennystä",
        formatMenu_DecreaseIndent: "Vähennä sisennystä",
        formatMenu_ClearFormat: "Tyhjennä muotoilu",
        formatMenu_RowHeight: "Rivin korkeus",
        formatMenu_ColumnWidth: "Sarakkeen leveys",
        formatMenu_ShowRow: "Näytä rivi",
        formatMenu_HideRow: "Piilota rivi",
        formatMenu_ShowColumn: "Näytä sarake",
        formatMenu_HideColumn: "Piilota sarake",
        formatMenu_WrapText: "Rivitä teksti",
        formatMenu_Number: "Luku",
        formatMenu_FontArial: "Arial",
        formatMenu_FontComicSansMS: "Comic Sans MS",
        formatMenu_FontCourierNew: "Courier New",
        formatMenu_FontGeorgia: "Georgia",
        formatMenu_FontLucidaSansUnicode: "Lucida Sans Unicode",
        formatMenu_FontTahoma: "Tahoma",
        formatMenu_FontTimesNewRoman: "Times New Roman",
        formatMenu_FontTrebuchetMS: "Trebuchet MS",
        formatMenu_FontVerdana: "Verdana",
        formatMenu_FontName: "Fontti",

        layoutMenu: "Asettelu",
        layoutMenu_SlideLayout: "Dian asettelu...",
        layoutMenu_SlideDesign: "Päätyyli...",
        layoutMenu_DefaultFormatting: "Oletusmuotoilu",
        layoutMenu_Textprop_Bold: "Lihavointi",
        layoutMenu_Textprop_Italic: "Kursivointi",
        layoutMenu_Textprop_Underline: "Alleviivaus",
        layoutMenu_Textprop_Strikethrough: "Yliviivaus",
        layoutMenu_TextProp: "Tekstin ominaisuudet",
        LayoutMenu_RowHeight: "Rivin korkeus...",
        LayoutMenu_ColumnWidth: "Sarakkeen leveys...",
        LayoutMenu_ShowRow: "Näytä rivi",
        LayoutMenu_HideRow: "Piilota rivi",
        LayoutMenu_RenameSheet: "Nimeä taulukko uudelleen...",
        LayoutMenu_MoveSheet: "Siirrä taulukko",

        tableMenu: "Taulukko",
        tableMenu_Create: "Luo...",
        tableMenu_CreateFromTemplate: "Luo mallipohjasta",
        tableMenu_Delete: "Poista",
        tableMenu_SetTableColor: "Värisolu",
        tableMenu_CreateTable: "Luo taulukko",
        tableMenu_Cell: "Solu",
        tableMenu_CellMergeCells: "Yhdistä solut",
        tableMenu_CellAlignLeft: "Tasaa vasemmalle",
        tableMenu_CellAlignCenter: "Tasaa keskelle",
        tableMenu_CellAlignRight: "Tasaa oikealle",
        tableMenu_CellClearContents: "Tyhjennä sisältö",
        tableMenu_CellProperties: "Solun ominaisuudet...",
        tableMenu_Row: "Rivi",
        tableMenu_InsertRowAbove: "Lisää rivi yläpuolelle",
        tableMenu_InsertRowBelow: "Lisää rivi alapuolelle",
        tableMenu_MoveRowAbove: "Siirrä rivi ylös",
        tableMenu_MoveRowBelow: "Siirrä rivi alas",
        tableMenu_RowInsertRow: "Lisää rivi...",
        tableMenu_RowInsertRowAbove: "Lisää rivi yläpuolelle",
        tableMenu_RowInsertRowBelow: "Lisää rivi alapuolelle",
        tableMenu_RowMoveRowAbove: "Siirrä rivi yläpuolelle",
        tableMenu_RowMoveRowBelow: "Siirrä rivi alapuolelle",
        tableMenu_RowDelete: "Poista",
        tableMenu_RowRepeat: "Toista otsikkorivi",
        tableMenu_InsertColumnBefore: "Lisää sarake edelle",
        tableMenu_InsertColumnAfter: "Lisää sarake jälkeen",
        tableMenu_MoveColumnBefore: "Siirrä sarake vasemmalle",
        tableMenu_MoveColumnAfter: "Siirrä sarake oikealle",
        tableMenu_ResizeColumn: "Muuta sarakkeen kokoa",
        tableMenu_ResizeColumns: "Muuta sarakkeiden kokoa",
        tableMenu_MarkasCategory: "Merkitse luokaksi",
        tableMenu_ColumnInsertColumn: "Lisää sarake...",
        tableMenu_ColumnAddColumnBefore: "Lisää sarake edelle",
        tableMenu_ColumnAddColumnAfter: "Lisää sarake jälkeen",
        tableMenu_ColumnMoveColumnAfter: "Siirrä sarake jälkeen",
        tableMenu_ColumnMoveColumnBefore: "Siirrä sarake edelle",
        tableMenu_ColumnDelete: "Poista",
        tableMenu_ColumnSortAscending: "Nouseva lajittelu",
        tableMenu_ColumnSortDescending: "Laskeva lajittelu",
        tableMenu_Column: "Sarake",
        tableMenu_Style: "Tyyli",
        tableMenu_TableProperties: "Taulukon ominaisuudet...",

        teamMenu: "Työryhmä",
        teamMenu_AddComment: "Lisää kommentti",
        teamMenu_AssignCells: "Tee soluista toimeksianto",
        teamMenu_AssignSection: "Tee osasta toimeksianto",
        teamMenu_EditAssignment: "Muokkaa toimeksiantoa",
        teamMenu_MarkSectionComplete: "Merkitse osa valmiiksi",
        teamMenu_MarkAssignmentComplete: "Merkitse toimeksianto valmiiksi",
        teamMenu_WorkPrivatelyOnSection: "Käsittele osaa yksityisesti",
        teamMenu_CancelPrivateWork: "Peruuta yksityinen työskentely",
        teamMenu_ApproveSection: "Hyväksy osa",
        teamMenu_ApproveAssignment: "Hyväksy toimeksianto",
        teamMenu_ReturnSectionForRework: "Palauta osa tehtäväksi uudelleen",
        teamMenu_ReturnAssignmentForRework: "Palauta toimeksianto tehtäväksi uudelleen",
        teamMenu_RemoveSectionAssignment: "Poista osatoimeksianto",
        teamMenu_RemoveCellAssignment: "Poista solutoimeksianto",
        teamMenu_RemoveCompletedAssignments: "Poista valmiit toimeksiannot",
        teamMenu_AboutThisSection: "Tietoja tästä osasta",
        teamMenu_AboutAssignment: "Tietoja tästä toimeksiannosta",

        presentationMenu: "Esitys",
        presentationMenu_SlideShow: "Toista diaesitys",
        presentationMenu_SlideShowWithCoview: "Toista yhteiskäyttöön määritetty diaesitys",
        presentationMenu_SlideTransitions: "Käytä dian vaihtoa...",
        presentationMenu_SlideShowFromCurrent: "Toista nykyisestä diasta",
        presentationMenu_EmptyCoviewInvites: "Aktiivista yhteiskäyttöön määritettyä diaesitystä ei ole",
        presentationMenu_CoviewInvites: "Aktiivinen yhteiskäyttöön määritetty diaesitys",

        dataMenu: "Tiedot",
        dataMenu_Sort: "Lajittele...",
        dataMenu_SortAsc: "Nouseva lajittelu",
        dataMenu_SortDesc: "Laskeva lajittelu",
        dataMenu_ACL: "Suojatut alueet",
        dataMenu_ACL_DELETE: "Poista kaikki käyttöoikeudet",
        dataMenu_Validity: "Kelpoisuus",
        dataMenu_InstantFilter: "Pikasuodatin",
        dataMenu_Validation: "Tarkistus...",

        toolsMenu: "Työkalut",
        toolsMenu_AutoComplete: "Täydennä solujen merkinnät automaattisesti",
        toolsMenu_SelectDictionary: "Oikeinkirjoitussanastot",
        toolsMenu_Dictionary_ca_CT: "katalaani",
        toolsMenu_Dictionary_cs_CZ: "tšekki (Tšekki)",
        toolsMenu_Dictionary_da_DK: "tanska (Tanska)",
        toolsMenu_Dictionary_nl_NL: "hollanti (Alankomaat)",
        toolsMenu_Dictionary_en_AU: "englanti (Australia)",
        toolsMenu_Dictionary_en_GB: "englanti (Iso-Britannia)",
        toolsMenu_Dictionary_en_US: "englanti (Yhdysvallat)",
        toolsMenu_Dictionary_fi_FI: "suomi (Suomi)",
        toolsMenu_Dictionary_fr_FR: "ranska (Ranska)",
        toolsMenu_Dictionary_fr_CA: "ranska (Kanada)",
        toolsMenu_Dictionary_de_DE: "saksa (Saksa)",
        toolsMenu_Dictionary_de_CH: "saksa (Sveitsi)",
        toolsMenu_Dictionary_el_GR: "kreikka (Kreikka)",
        toolsMenu_Dictionary_it_IT: "italia (Italia)",
        toolsMenu_Dictionary_pl_PL: "puola (Puola)",
        toolsMenu_Dictionary_pt_BR: "portugali (Brasilia)",
        toolsMenu_Dictionary_pt_PT: "portugali (Portugali)",
        toolsMenu_Dictionary_ru_RU: "venäjä (Venäjä)",
        toolsMenu_Dictionary_es_ES: "espanja (Espanja)",
        toolsMenu_Dictionary_sv_SE: "ruotsi (Ruotsi)",
        toolsMenu_Dictionary_nb_NO: "norja (bokmål)",
        toolsMenu_Dictionary_nn_NO: "norja (uusnorja)",
        toolsMenu_Dictionary_he_IL: "heprea (Israel)",
        toolsMenu_SpellCheck: "Aja manuaalinen oikeinkirjoituksen tarkistus...",
        toolsMenu_Preferences: "Asetukset",
        toolsMenu_Task: "Tehtävä",
        toolsMenu_Task_Assigntask: "Tee tehtävästä toimeksianto",
        teamMenu_AssignSlide: "Tee diasta toimeksianto",
        teamMenu_AssignSlides: "Tee dioista toimeksianto",
        teamMenu_EditSlide: "Diatoimeksiannon muokkaus",
        teamMenu_ReopenSlideAssignment: "Avaa diatoimeksianto uudelleen",
        teamMenu_ReopenSlideAssignments: "Avaa diatoimeksiannot uudelleen",
        teamMenu_ReassignSlide: "Tee diasta toimeksianto uudelleen",
        teamMenu_ReassignSlides: "Tee dioista toimeksianto uudelleen",
        teamMenu_MarkSlidesComplete: "Merkitse dia valmiiksi",
        teamMenu_MarkSlidesCompletes: "Merkitse diat valmiiksi",
        teamMenu_ApproveSlide: "Hyväksy dia",
        teamMenu_ApproveSlides: "Hyväksy diat",
        teamMenu_ReturnForRework: "Palauta dia tehtäväksi uudelleen",
        teamMenu_ReturnForReworks: "Palauta diat tehtäväksi uudelleen",
        teamMenu_RemoveAssignment: "Poista diatoimeksianto",
        teamMenu_AboutThisSlide: "Tietoja tästä diasta",

        addOnsMenu: "Lisäosat",

        helpMenu: "Ohje",
        helpMenu_About: "Tietoja",
        helpMenu_Overview: "Ohjeen sisältö",
        helpMenu_NewFeatures: "Uudet ominaisuudet",
        helpMenu_Tour: "Opastettu kierros",

        accel_fileMenu_Save: "Ctrl+S",
        accel_fileMenu_Save_Mac: "\u2318S",
        accel_fileMenu_Print: "Ctrl+P",
        accel_fileMenu_Print_Mac: "\u2318P",
        accel_editMenu_SelectAll: "Ctrl+A",
        accel_editMenu_SelectAll_Mac: "\u2318A",
        accel_editMenu_Undo: "Ctrl+Z",
        accel_editMenu_Undo_Mac: "\u2318Z",
        accel_editMenu_Redo: "Ctrl+Y",
        accel_editMenu_Redo_Mac: "\u2318Y",
        accel_editMenu_Cut: "Ctrl+X",
        accel_editMenu_Cut_Mac: "\u2318X",
        accel_editMenu_Copy: "Ctrl+C",
        accel_editMenu_Copy_Mac: "\u2318C",
        accel_editMenu_Paste: "Ctrl+V",
        accel_editMenu_Paste_Mac: "\u2318V",
        accel_editMenu_Find: "Ctrl+F",
        accel_editMenu_Find_Mac: "\u2318F",
        accel_insertMenu_Link: "Ctrl+K",
        accel_insertMenu_Link_Mac: "\u2318K",
        accel_insertMenu_Header: "CTRL+VAIHTO+H",
        accel_insertMenu_Header_Mac: "\u21e7\u2318H",
        accel_insertMenu_Footer: "CTRL+VAIHTO+F",
        accel_insertMenu_Footer_Mac: "\u21e7\u2318F",
        accel_formatMenu_Textprop_Bold: "Ctrl+B",
        accel_formatMenu_Textprop_Bold_Mac: "\u2318B",
        accel_formatMenu_Textprop_Italic: "Ctrl+I",
        accel_formatMenu_Textprop_Italic_Mac: "\u2318I",
        accel_formatMenu_Textprop_FormatPainter: "Ctrl+VAIHTO+C, Ctrl+VAIHTO+V",
        accel_formatMenu_Textprop_FormatPainter_Mac: "\u21e7\u2318C, \u21e7\u2318V",
        accel_formatMenu_Textprop_Underline: "Ctrl+U",
        accel_formatMenu_Textprop_Underline_Mac: "\u2318U",
        accel_formatMenu_Headingprop_P: "CTRL+VAIHTO+0",
        accel_formatMenu_Headingprop_H1: "CTRL+VAIHTO+1",
        accel_formatMenu_Headingprop_H2: "CTRL+VAIHTO+2",
        accel_formatMenu_Headingprop_H3: "CTRL+VAIHTO+3",
        accel_formatMenu_Headingprop_H4: "CTRL+VAIHTO+4",
        accel_formatMenu_Headingprop_H5: "CTRL+VAIHTO+5",
        accel_formatMenu_Headingprop_H6: "CTRL+VAIHTO+6",
        accel_formatMenu_Superscript: "Ctrl+.",
        accel_formatMenu_Superscript_Mac: "\u2318.",
        accel_formatMenu_Subscript: "Ctrl+,",
        accel_formatMenu_Subscript_Mac: "\u2318,",
        accel_formatMenu_Left: "CTRL+VAIHTO+L",
        accel_formatMenu_Left_Mac: "\u21e7\u2318L",
        accel_formatMenu_Right: "CTRL+VAIHTO+R",
        accel_formatMenu_Right_Mac: "\u21e7\u2318R",
        accel_formatMenu_Center: "CTRL+VAIHTO+E",
        accel_formatMenu_Center_Mac: "\u21e7\u2318E",
        accel_formatMenu_Justify: "CTRL+VAIHTO+J",
        accel_formatMenu_Justify_Mac: "\u21e7\u2318J",
        accel_formatMenu_Indent: "CTRL+M",
        accel_formatMenu_Indent_Mac: "\u2318M",
        accel_formatMenu_DecreaseIndent: "CTRL+VAIHTO+M",
        accel_formatMenu_DecreaseIndent_Mac: "\u21e7\u2318M",
        accel_teamMenu_AddComment: "VAIHTO+F2",

        ctxMenuSmartTable: 'Taulukko',
        ctxMenuTableProperties: "Taulukon ominaisuudet",
        ctxMenuDeleteST: 'Poista',
        ctxMenuDeleteSTTable: 'Poista taulukko',
        ctxMenuChgSTStyle: 'Muuta tyyliä',
        ctxMenuShowCaption: 'Näytä kuvateksti',
        ctxMenuHideCaption: 'Piilota kuvateksti',
        ctxMenuResizeST: 'Muuta kokoa',
        ctxMenuResizeColumnsST: 'Muuta sarakkeiden kokoa',
        ctxMenuSTRow: 'Rivi',
        ctxMenuAddSTRowAbv: 'Lisää rivi yläpuolelle',
        ctxMenuAddSTRowBlw: 'Lisää rivi alapuolelle',
        ctxMenuMoveSTRowUp: 'Siirrä rivi yläpuolelle',
        ctxMenuMoveSTRowDown: 'Siirrä rivi alapuolelle',
        ctxMenuDelSTRow: 'Poista',
        ctxMenuRepeatRow: 'Toista otsikkorivi',
        ctxMenuSTCol: 'Sarake',
        ctxMenuAddSTColBfr: 'Lisää sarake edelle',
        ctxMenuAddSTColAft: 'Lisää sarake jälkeen',
        ctxMenuMoveSTColBefore: 'Siirrä sarake edelle',
        ctxMenuMoveSTColAfter: 'Siirrä sarake jälkeen',
        ctxMenuDelSTCol: 'Poista',
        ctxMenuSortSTColAsc: 'Nouseva lajittelu',
        ctxMenuSortSTColDesc: 'Laskeva lajittelu',
        ctxMenuShowAllFacets: 'Näytä luokat',
        ctxMenuHideAllFacets: 'Piilota luokat',
        ctxMenuSTCell: 'Solu',
        ctxMenuMergeCells: 'Yhdistä solut',
        ctxMenuMergeDown: 'Yhdistä alla olevaan soluun',
        ctxMenuVerSplit: 'Jaa pystysuunnassa',
        ctxMenuHorSplit: 'Jaa vaakasuunnassa',
        ctxMenuSplitCells: 'Jaa solut...',
        splitCells: 'Jaa solu',
        ctxMenuAlignTextLeft: 'Tasaa vasemmalle',
        ctxMenuAlignTextCenter: 'Tasaa keskelle',
        ctxMenuAlignTextRight: 'Tasaa oikealle',
        ctxMenuClearSTCellContent: 'Tyhjennä sisältö',
        ctxMenuMakeHeaderRow: 'Käytä valittua riviä otsikkona',
        ctxMenuMakeNonHeaderRow: 'Poista otsikon tyyli',
        ctxMenuMakeHeaderCol: 'Käytä valittua saraketta otsikkona',
        ctxMenuMakeNonHeaderCol: 'Poista otsikon tyyli',
        SHEET_CONTEXT_Hide: "Piilota", // hide row, column or sheet
        SHEET_CONTEXT_Show: "Näytä", // show row, column
        SHEET_CONTEXT_MoveSheet: "Siirrä...", // move sheet
        SHEET_CONTEXT_InsertSheet: "Lisää...", // insert sheet
        SHEET_CONTEXT_DeleteSheet: "Poista...", // delete sheet	
        SHEET_CONTEXT_DuplicateSheet: "Monista...", // duplicate sheet
        SHEET_CONTEXT_RenameSheet: "Nimeä uudelleen...", // rename sheet
	
        ctxMenu_Image_WrapText: "Rivitä teksti",
        ctxMenu_Image_WrapText_Inline: "Linjassa tekstin kanssa",
        ctxMenu_Image_WrapText_Square: "Neliö",
        ctxMenu_Image_WrapText_TopBottom: "Ylä ja ala",
        ctxMenu_Image_WrapText_Behind: "Tekstin takana",
        ctxMenu_Image_WrapText_InFront: "Tekstin edessä",
        ctxMenu_Image_WrapText_Other: "Lisää rivitettyä tekstiä",
        ctxMenu_Image_WrapText_BothSides: "Molemmat puolet",
        ctxMenu_Image_WrapText_LeftOnly: "Vain vasen",
        ctxMenu_Image_WrapText_RightOnly: "Vain oikea",
        ctxMenu_Image_WrapText_LargestOnly: "Vain suurin",

        ctxMenu_Shape_AddText: "Lisää tekstiä",

        ctxMenu_Range_ACL: "Suojaa alue",
        ctxMenu_Sheet_ACL: "Suojaa taulukko",

        ctxMenu_HeaderFooter: "Ylätunniste / alatunniste",
        ctxMenu_HeaderFooter_DiffFirst: "Vain ensimmäinen sivu",
        ctxMenu_HeaderFooter_DiffOddEven: "Erilaiset parittomat ja parilliset sivut",
        ctxMenu_HeaderFooter_LinkToPre: "Linkitä edelliseen",

        ctxMenu_copy: "Kopioi",
        ctxMenu_paste: "Liitä",
        ctxMenu_delete: "Poista",
        ctxMenu_cut: "Leikkaa",
        ctxMenu_select: "Valitse",
        ctxMenu_properties: "Ominaisuudet",
        ctxMenu_bringToFront: "Tuo eteen",
        ctxMenu_sendToBack: "Vie taakse",
        ctxMenu_arrange: "Järjestä",
        ctxMenu_sendBackward: "Siirrä taaksepäin",
        ctxMenu_sendForward: "Siirrä eteenpäin",
        ctxMenu_fontStyle: "Fonttityyli",
        ctxMenu_selectStyle: "Valitse tyyli",
        ctxMenu_fontSize: "Fonttikoko",
        ctxMenu_fontFamily: "Fonttiperhe",
        ctxMenu_bold: "Lihavointi",
        ctxMenu_italic: "Kursivointi",
        ctxMenu_u: "Alleviivaus",
        ctxMenu_strike: "Yliviivaus",
        ctxMenu_super: "Yläindeksi",
        ctxMenu_sub: "Alaindeksi",
        ctxMenu_color: "Väri",
        ctxMenu_bgcolor: "Taustaväri",
        ctxMenu_highcolor: "Korostusväri",
        ctxMenu_restart: "Aloita luettelon tekeminen alusta",
        ctxMenu_continue: "Jatka luetteloa",
        ctxMenu_separate: "Erillinen luettelo",
        ctxMenu_join: "Liitä edelliseen luetteloon",
        ctxMenu_setNumberVal: "Määritä numeroinnin arvo...",
        webClipboardInfoTitle: "Leikepöytä",
        webClipboardInfoOKBtn: "OK",
        webClipboardInfoCutMsg: "Selaimen suojausasetukset estävät automaattisen kopioinnin. Käytä sen sijaan näppäinyhdistelmää Ctrl+X.",
        webClipboardInfoCopyMsg: "Selaimen suojausasetukset estävät automaattisen kopioinnin. Käytä sen sijaan näppäinyhdistelmää Ctrl+C.",
        webClipboardInfoPasteMsg: "Selaimen suojausasetukset estävät tätä muokkausohjelmaa käyttämästä leikepöydän tietoja. Käytä sen sijaan näppäinyhdistelmää Ctrl+V.",

        clearTrackChangeConfirmMsg: "Kaikki muutosten värimerkinnät tässä asiakirjassa poistetaan pysyvästi. Haluatko jatkaa?"
});

