({
	ORIENTATION_LABEL: "Orientación",
	PORTRAIT: "Orientación vertical",
	LANDSCAPE: "Orientación horizontal",
	HEADER: "Cabecera",
	FOOTER: "Pie de página",
	MARGINS_LABEL: "Márgenes",
	TOP: "Arriba:",
	BOTTOM: "Abajo:",
	LEFT: "Izquierda:",
	RIGHT: "Derecha:",
	PAPER_FORMAT_LABEL: "Formato de papel",
	PAPER_SIZE_LABEL: "Tamaño de papel:",
	HEIGHT: "Altura:",
	WIDTH: "Anchura:",
	HEIGHT_DESC:"Altura del papel, en centímetros",
	HEIGHT_DESC2:"Altura del papel, en pulgadas",
	WIDTH_DESC:"Anchura del papel, en centímetros",
	WIDTH_DESC2:"Anchura del papel, en pulgadas",
	BOTTOM_DESC:"Margen inferior, en centímetros",
	BOTTOM_DESC2:"Margen inferior, en pulgadas",
	TOP_DESC:"Margen superior, en centímetros",
	TOP_DESC2:"Margen superior, en pulgadas",
	LEFT_DESC:"Margen izquierdo, en centímetros",
	LEFT_DESC2:"Margen izquierdo, en pulgadas",
	RIGHT_DESC:"Margen derecho, en centímetros",
	RIGHT_DESC2:"Margen derecho, en pulgadas",
	CM_LABEL: "cm",
	LETTER: "Carta",
	LEGAL: "Legal",
	TABLOID: "Tabloide",
	USER: "Usuario",
	SIZE1: "Sobre núm. 6 3/4",
	SIZE2: "Sobre Monarch",
	SIZE3: "Sobre núm. 9",
	SIZE4: "Sobre núm. 10",
	SIZE5: "Sobre núm. 11",
	SIZE6: "Sobre núm. 12",
	SIZE7: "16 kai",
	SIZE8: "32 kai",
	SIZE9: "32 kai grande",
	INVALID_MSG: "La entrada no es válida y se ha rectificado automáticamente. Inténtelo con otro valor si desea obtener otro resultado."
})
	
