({
	COLUMN: "Coloană",
	CLUSTERED_COLUMN: "Coloane grupate",
	STACKED_COLUMN: "Coloane stivuite",
	BAR:"Bară",
	CLUSTERED_BAR:"Bare grupate",
	STACKED_BAR: "Bare stivuite",
	PIE:"Circulară",
	SLICE: "Felie",
	AREA: "Suprafaţă",
	STACKED_AREA: "Suprafeţe stivuite",
	LINE: "Linie",
	STACKED_LINE: "Linii stivuite",
	MAKER_LINE: "Linie cu marcaje",
	STACKED_MARKER_LINE: "Linii stivuite cu marcaje",
	SCATTER: "Puncte",
	SCATTER_MARKER_ONLY: "Puncte numai cu marcaje",
	SCATTER_MARKER_LINE_S: "Puncte cu linii curbe şi marcaje",
	SCATTER_LINE_S: "Puncte cu linii curbe", 
	SCATTER_MARKER_LINE_X: "Puncte cu linii frânte şi marcaje",
	SCATTER_LINE_X: "Puncte cu linii frânte",
	ERROR_INVALID_RANGE:"Interval de date invalid",
	TOO_MANY_POINTS: "Nu se poate crea o diagramă care are mai mult de ${0} puncte de date",
	CHART_TYPES:"Tipuri de diagrame",
	DATA:"Date",
	DATA_RANGE:"Interval de date",
	IN_ROWS:"Serii de date în rânduri",
	IN_COLUMNS:"Serii de date în coloane",
	AUTO:"Automat"
})
