/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
    Arrow01_Gray: "Көрсеткі 01 сұр",
    Arrow02_Gray: "Көрсеткі 02 сұр",
    Arrow03_Red: "Көрсеткі 03 қызыл",
    Arrow04_Blue: "Көрсеткі 04 көк",
    Arrow05_Blue: "Көрсеткі 05 көк",
    Arrow06_Yellow: "Көрсеткі 06 сары",
    Arrow07_Red: "Көрсеткі 07 қызыл",
    Arrow08_Gray: "Көрсеткі 08 сұр",
    Arrow09_Orange: "Көрсеткі 09 қызғылт сары",
    Arrow10_Blue: "Көрсеткі 10 көк",
    Arrow11_Blue: "Көрсеткі 11 көк",
    Arrow12_Green: "Көрсеткі 12 жасыл",
    Arrow13_Blue: "Көрсеткі 13 көк",
    Arrow14_Green: "Көрсеткі 14 жасыл",
    Arrow15_Orange: "Көрсеткі 15 қызғылт сары",
    Arrow16_Gray: "Көрсеткі 16 сұр",
    CircleArrow01_Green: "Шеңберлі көрсеткі 01 жасыл",
    CircleArrow02_Multi: "Шеңберлі көрсеткі 02 бірнеше түсті",
    CircleArrow03_Multi: "Шеңберлі көрсеткі 03 бірнеше түсті",
    CircleArrow04_Multi: "Шеңберлі көрсеткі 04 бірнеше түсті",
    CircleArrow05_Multi: "Шеңберлі көрсеткі 05 бірнеше түсті",
    CircleArrow06_Multi: "Шеңберлі көрсеткі 06 бірнеше түсті",
    CircleArrow07_Blue: "Шеңберлі көрсеткі 07 көк",
    CircleArrow08_Green: "Шеңберлі көрсеткі 08 жасыл",
    CircleArrow09_Multi: "Шеңберлі көрсеткі 09 бірнеше түсті",
    CurvedArrow01_Gray: "Қисық көрсеткі 01 сұр",
    CurvedArrow02_Blue: "Қисық көрсеткі 02 көк",
    CurvedArrow03_Blue: "Қисық көрсеткі 03 көк",
    CurvedArrow04_Orange: "Қисық көрсеткі 04 қызғылт сары",
    CurvedArrow05_Red: "Қисық көрсеткі 05 қызыл",
    CurvedArrow06_Blue: "Қисық көрсеткі 06 көк",
    CurvedArrow07_Purple: "Қисық көрсеткі 07 күлгін",
    CurvedArrow08_Green: "Қисық көрсеткі 08 жасыл",
    CurvedArrow09_Gray: "Қисық көрсеткі 09 сұр",
    CurvedArrow10_Blue: "Қисық көрсеткі 10 көк",
    CurvedArrow11_Orange: "Қисық көрсеткі 11 қызғылт сары",
    CurvedArrow12_Blue: "Қисық көрсеткі 12 көк",
    CurvedArrow13_Green: "Қисық көрсеткі 13 жасыл",
    CurvedArrow14_Brown: "Қисық көрсеткі 14 қоңыр",
    CurvedArrow15_Blue: "Қисық көрсеткі 15 көк",
    CurvedArrow16_Gray: "Қисық көрсеткі 16 сұр",
    CurvedArrow17_Gray: "Қисық көрсеткі 17 сұр",
    CurvedArrow18_Gray: "Қисық көрсеткі 18 сұр",
    CurvedArrow19_Gray: "Қисық көрсеткі 19 сұр",
    CurvedArrow20_Gray: "Қисық көрсеткі 20 сұр",
    TrendArrow01_Red: "Тренд көрсеткісі 01 қызыл",
    TrendArrow02_Green: "Тренд көрсеткісі 02 жасыл",
    TrendArrow03_Orange: "Тренд көрсеткісі 03 қызғылт сары",
    TrendArrow04_Red: "Тренд көрсеткісі 04 қызыл",
    TrendArrow05_Orange: "Тренд көрсеткісі 05 қызғылт сары",
    TrendArrow06_Blue: "Тренд көрсеткісі 06 көк",
    TrendArrow07_Orange: "Тренд көрсеткісі 07 қызғылт сары",
    TrendArrow08_Yellow: "Тренд көрсеткісі 08 сары",
    TrendArrow09_Blue: "Тренд көрсеткісі 09 көк",
    TrendArrow10_Blue: "Тренд көрсеткісі 10 көк",
    TrendArrow11_Blue: "Тренд көрсеткісі 11 көк",
    TrendArrow12_Blue: "Тренд көрсеткісі 12 көк",
    TrendArrow13_Red: "Тренд көрсеткісі 13 қызыл",
    TrendArrow14_Multi: "Тренд көрсеткісі 14 бірнеше түсті",
    TrendArrow15_Blue: "Тренд көрсеткісі 15 көк",
    Bullet01_Circle_DarkRed: "Таңбалауыш 01 шеңберлі қою қызыл",
    Bullet02_Circle_Blue: "Таңбалауыш 02 шеңберлі көк",
    Bullet03_Circle_Green: "Таңбалауыш 03 шеңберлі жасыл",
    Bullet04_Square_Black: "Таңбалауыш 04 шаршылы қара",
    Bullet05_Square_Orange: "Таңбалауыш 05 шаршылы қызғылт сары",
    Bullet06_Square_Purple: "Таңбалауыш 06 шаршылы күлгін",
    Bullet07_Diamond_Blue: "Таңбалауыш 07 гауһар түсті көк",
    Bullet08_Diamond_LightBlue: "Таңбалауыш 08 гауһар түсті көк",
    Bullet09_Diamond_Red: "Таңбалауыш 09 гауһар түсті қызыл",
    Bullet10_Star_Yellow: "Таңбалауыш 10 жұлдызшасы сары ",
    Bullet11_Star_Blue: "Таңбалауыш 11 жұлдызшасы көк",
    Bullet12_Triangle_Blue: "Таңбалауыш 12 үшбұрышы көк",
    Bullet13_Triangle_DarkGreen: "Таңбалауыш 13 үшбұрышы қою жасыл",
    Bullet14_Arrow_Red: "Таңбалауыш 14 көрсеткісі қызыл",
    Bullet15_Arrow_Blue: "Таңбалауыш 15 көрсеткісі қызыл",
    Bullet16_Box_Blue: "Таңбалауыш 16 жолағы көк",
    Bullet17_Box_Red: "Таңбалауыш 17 жолағы қызыл",
    Bullet18_Asterisk_LightBlue: "Таңбалауыш 18 жұлдызшасы ашық көк",
    Bullet19_Leaves_Red: "Таңбалауыш 19 түйіні қызыл",
    Bullet20_Target_Blue: "Таңбалауыш 20 мақсатты көк",
    Bullet21_Arrow_Blue: "Таңбалауыш 21 көрсеткісі көк",
    Bullet22_Arrow_DarkBlue: "Таңбалауыш 22 көрсеткісі қою көк",
    Bullet23_Arrow_Brown: "Таңбалауыш 23 көрсеткісі қоңыр",
    Bullet24_Flag_Red: "Таңбалауыш 24 жалаушасы қызыл",
    Bullet25_Flag_Green: "Таңбалауыш 25 жалаушасы жасыл",
    Bullet26_X_Red: "Таңбалауыш 26 X қызыл",
    Bullet27_X_Black: "Таңбалауыш 27 X қара",
    Bullet28_Checkmark_Green: "Таңбалауыш 28 құсбелгісі жасыл",
    Bullet29_Checkmark_Blue: "Таңбалауыш 29 құсбелгісі көк",
    Bullet30_Square_DarkRed: "Таңбалауыш 30 шаршысы қоб қызыл",
    camera: "Камера",
    computer1: "Компьютер 1",
    computer2: "Компьютер 2",
    computer3: "Компьютер 3",
    Computer_Cloud: "Компьютер бұлты",
    Computer_Desktop: "Компьютер жұмыс үстелі",
    Computer_Laptop_Black: "Қара ноутбук",
    Computer_Laptop_Silver: "Күміс түсті ноутбук",
    Database: "Дерекқор",
    evelope: "Хатқалта",
    newspapers: "Газеттер",
    openevelope: "Хатқалтаны ашу",
    Server: "Сервер",
    speaker: "Баяндамашы",
    WirelessAccessPoint: "Желісіз кіру нүктесі",
    Cycle01_Transparent: "Айналым 01 мөлдір",
    Cycle02_Transparent_Blue: "Айналым 02 мөлдір көк",
    Cycle03_Blue: "Айналым 03 көк",
    Cycle04_Blue: "Айналым 04 көк",
    Cycle05: "Айналым 05",
    Cycle06: "Айналым 06",
    Cycle07: "Айналым 07",
    Cycle08_Blue: "Айналым 08 көк",
    Cycle09_Orange: "Айналым 09 қызғылт сары",
    Donut01_LightBlue: "Сақина 01 ақшыл көк",
    Donut02_Blue: "Сақина 02 көк",
    Donut03_Blue: "Сақина 03 көк",
    Donut04_DarkBlue: "Сақина 04 қою көк",
    Donut05_DarkBlue: "Сақина 05 қою көк",
    Donut06_Blue: "Сақина 06 көк",
    Donut07_Blue: "Сақина 07 көк",
    Graph: "Сызба",
    People01_Blue: "Адамдар 01 көк",
    People02: "Адамдар 02",
    Pillars01_Orange: "Бағаналар 01 қызғылт сары",
    Pillars02_LightBlue: "Бағаналар 02 ақшыл көк",
    Process01_Blue: "Процесс 01 көк",
    Process02_Blue: "Процесс 02 көк",
    Process03_Blue: "Процесс 03 көк",
    Process04_GoUp_Blue: "Процесс 04 көкке боялады",
    Process05_GoUp_Red: "Процесс 05 қызылға боялады",
    Process06_GoUp_Yellow: "Процесс 06 сарыға боялады",
    Process07_Blue: "Процесс 07 көк",
    Pyramid01: "Үшкіл 01",
    Pyramid02_Blue: "Үшкіл 02 көк",
    Pyramid03: "Үшкіл 03",
    Radial01_Green: "Радиалдық 01 жасыл",
    Radial02_Green: "Радиалдық 02 жасыл",
    Radial03_Sphere: "Радиалдық 03 сфера",
    Radial04_Sphere_Red: "Радиалдық 04 сфера қызыл",
    Radial05_Sphere_Blue: "Радиалдық 05 сфера көк",
    Radial06_Arrows_DarkBlue: "Радиалдық 06 көрсеткі қою көк",
    Radial07_Arrows_DarkBlue: "Радиалдық 07 көрсеткі қою көк",
    Section_Circle: "Бөлім шеңбері",
    Section_Cubes01: "Бөлім текшесі 01",
    Section_Cubes02_Blue: "Бөлім текшесі 02 көк",
    Section_Cubes03_Orange: "Бөлім текшесі 03 қызғылт сары",
    Section_Cubes04: "Бөлім текшесі 04",
    Section_Cubes05: "Бөлім текшесі 05",
    Section_Cuboids01_Blue: "Бөлім текшелесі 01 көк",
    Section_Cuboids02_Blue: "Бөлім текшелесі 02 көк",
    Section_Cuboids03: "Бөлім текшелесі 03",
    Section_Gears01: "Бөлім құрылғысы 01",
    Section_Gears02: "Бөлім құрылғысы 02",
    Section_Gears03: "Бөлім құрылғысы 03",
    Section_Hexagon04_Orange: "Бөлім алтыбұрышы 04 қызғылт сары",
    Section_Hexagons01: "Бөлім алтыбұрышы 01",
    Section_Hexagons02_Blue: "Бөлім алтыбұрышы 02 көк",
    Section_Hexagons03_Blue: "Бөлім алтыбұрышы 03 көк",
    Section_Leaves01_LightBlue: "Бөлім түйіні 01 ашық көк",
    Section_Leaves02_Green: "Бөлім түйіні 02 жасыл",
    Section_Pasters01: "Бөлім жапсырмасы 01",
    Section_Pasters02_Blue: "Бөлім жапсырмасы 02 көк",
    Section_Puzzle01: "Бөлім жұмбағы 01",
    Section_Puzzle02: "Бөлім жұмбағы 02",
    Section_Puzzle03: "Бөлім жұмбағы 03",
    Section_Rectangles: "Бөлім тіктөртбұрышы",
    Section_Squares: "Бөлім щарщылары",
    Section_Triangle: "Бөлім үшбұрыштары",
    Target: "Мақсаты",
    Venn01: "Венн 01",
    Venn02: "Венн 02",
    Venn03: "Венн 03",
    Venn04: "Венн 04",
    Venn05: "Венн 05",
    Venn06_Blue: "Венн 06 көк",
    Venn07_Blue: "Венн 07 көк",
    Venn08: "Венн 08",
    Blackboard: "Тақта",
    Books: "Кітаптар",
    Books1: "Кітаптар 1",
    books2: "Кітаптар 2",
    Chalk: "Бор",
    clipboard: "аралық сақтағыш",
    clock: "Сағат",
    Globe: "Глобус",
    Glue: "Бекіту",
    GraduationCap: "Түлек қалпағы",
    magnifyingglass: "Ұлғайтқыш әйнек",
    Microscope: "Микроскоп",
    Notebook: "Жазу кітапшасы",
    notepad1: "Блокнот 1",
    notepad2: "Блокнот 2",
    notepad3: "Блокнот 3",
    PaperClip_Blue: "Қағаз қыстырғышы көк",
    PaperClip_Red: "Қағаз қыстырғышы қызыл",
    Pencil: "Қарындаш",
    Ruler: "Сызғыш",
    TestTubes: "Тексеру текшелері",
    thumbtack: "Бармақшеге",
    clouds: "Бұлттар",
    DrippingFaucet: "Су ағызатын шүмек",
    Earth: "Жер",
    EndangeredAnimals1: "Қауіпті жануарлар 1",
    EndangeredAnimals2: "Қауіпті жануарлар 2",
    GreenCar: "Табиғи таза машина",
    GreenFactory: "Табиғи таза зауыт",
    GreenHouse: "Жылыжай",
    Leaf1: "Түйін 1",
    Leaf2: "Түйін 2",
    lightbulb: "Жарық шамы",
    LightBulb_Flourescent_Off: "Жарық шамы жарқылын өшіру",
    LightBulb_Flourescent_On: "Жарық шамы жарқылын жағу",
    LightBulb_Standard_Off1: "Жарық шамы стандартын өшіру 1",
    LightBulb_Standard_Off2: "Жарық шамы стандартын жағу 2",
    LightBulb_Standard_On: "Жарық шамы стандартын жағу",
    lightningcloud: "Жағу бұлты",
    Pollution_Car: "Ластаушы машина",
    Pollution_Factory: "Ластау зауыты",
    Raindrop: "Жаңбыр тамшысы",
    RecycleBin: "Себет",
    RecycleSymbol: "Себет белгісі",
    RenewableEnergySymbol: "Қалпына келетін энергия белгісі",
    RenewableEnergy_Solar: "Қалпына келетін күн жүйесінің энергиясы",
    RenewableEnergy_Water: "Қалпына кедетін судың энергиясы",
    RenewableEnergy_Wind: "Қалпына келетін жел энергиясы",
    sun: "Күн",
    Sun1: "Күн 1",
    Sun2: "Күн 2",
    sundandcloud: "Күн және бұлт",
    world: "Әлем",
    Agreement: "Келісім-шарт",
    ATM01: "ATM 01",
    ATM02: "ATM 02",
    Balance_Balanced1: "Теңгерілген теңгерім 1",
    Balance_Balanced2: "Теңгерілген теңгерім 2",
    Balance_Unbalanced1: "Теңгерілмеген теңгерім 1",
    Balance_Unbalanced2: "Теңгерілмеген теңгерім 2",
    Calculator: "Есептегіш",
    Chart_Decrease1: "Диаграмма кемуі 1",
    Chart_Decrease2: "Диаграмма кемуі 2",
    Chart_Increase1: "Диаграмма артуы 1",
    Chart_Increase2: "Диаграмма артуы 2",
    Chart_Plateau: "Диаграмма платосы",
    Check: "Чек",
    Contract: "Келісімшарт",
    CreditCard_Black: "Несиелік карта қара",
    CreditCard_Cut: "Несиелік картаны кесу",
    CreditCard_Gold: "Несиелік карта алтын",
    Currency_Dollar: "Валюта доллар",
    Currency_Dollars: "Валюта долларлары",
    Currency_Stack: "Валюта тізбегі",
    Currency_StackCoins: "Валюта тізбегінің тиындары",
    GoldBar: "Алтын жолақ",
    GoldBar_Stack: "Алтын жолағы тізбегі",
    MoneyBag01: "Ақша қапшығы 01",
    MoneyBag02: "Ақша қапшығы 02",
    PercentSign: "Пайыз белгісі",
    PiggyBank01_Broken: "Жинақтауыш 01 бұзылған",
    PiggyBank02_Broken: "Жинақтауыш 02 бұзылған",
    PiggyBank_Coins: "Жинақтауыш тиындары",
    PiggyBank_Currency: "Жинақтауыш валютасы",
    Portfolio: "Портфель",
    PriceTag: "Баға көрсеткіші",
    Safe_Closed: "Сақтау жабық",
    Safe_Empty: "Сақтау бос",
    Safe_Full: "Сақтау толық",
    Seal_Gold: "Мөр алтын",
    Seal_Red: "Мөр қызыл",
    Seal_Silver: "Мөр күміс",
    Wallet_Empty: "Әмиян бос",
    Wallet_Full1: "Әмиян толы 1",
    Wallet_Full2: "Әмиян толы 2",
    BusinessPerson_Female6: "Әйел іскери адам 6",
    BusinessPerson_Male3: "Еркек іскери адам 3",
    Computer_User_Female1: "Әйел компьютер пайдаланушы 1",
    ConstructionWorker2: "Құрылыс жұмысшысы 2",
    Presenter_Female1: "Әйел баяндамашы 1",
    Component_Circle01_Transparent_DarkBlue: "Құрамдас шеңбері 01 мөлдір қою көк",
    Component_Circle02_Transparent_Bule: "Құрамдас шеңбері 02 мөлдір көк",
    Component_Circle03_Transparent_Green: "Құрамдас шеңбері 03 мөлдір жасыл",
    Component_Circle04_Transparent_Orange: "Құрамдас шеңбері 04 мөлдір қызғылт сары",
    Component_Circle05_Transparent_Red: "Құрамдас шеңбері 05 мөлдір қызыл",
    Component_Cube01_DarkBlue: "Құрамдас текшесі 01 қою көк",
    Component_Cube02_LightBlue: "Құрамдас текшесі 02 ашық көк",
    Component_Cube03_Green: "Құрамдас текшесі 03 жасыл",
    Component_Cube04_Orange: "Құрамдас текшесі 04 қызғылт сары",
    Component_Cube05_DarkRed: "Құрамдас текшесі 05 қою қызыл",
    Component_Cuboid01_DarkBlue: "Құрамдас текшелімі 01 қою көк",
    Component_Cuboid02_Blue: "Құрамдас текшелімі 02 көк",
    Component_Cuboid03_Green: "Құрамдас текшелімі 03 жасыл",
    Component_Cuboid04_Orange: "Құрамдас текшелімі 04 қызғылт сары",
    Component_Cuboid05_Red: "Құрамдас текшелімі 05 қызыл",
    Component_Gear01_DarkBlue: "Құрамдас құрылғысы 01 қою көк",
    Component_Gear02_LightBlue: "Құрамдас құрылғысы 02 ашық көк",
    Component_Gear03_Green: "Құрамдас құрылғысы 03 жасыл",
    Component_Gear04_DarkRed: "Құрамдас құрылғысы 04 қою қызыл",
    Component_Gear05_Orange: "Құрамдас құрылғысы 05 қызғылт сары",
    Component_Person01_DarkBlue: "Құрамдас адамы 01 қою көк",
    Component_Person02_Blue: "Құрамдас адамы 02 көк",
    Component_Person03_Green: "Құрамдас адамы 03 жасыл",
    Component_Person04_DarkRed: "Құрамдас адамы 04 қою қызыл",
    Component_Person05_Orange: "Құрамдас адамы 05 қызғылт сары",
    Component_PuzzlePiece01_DarkBlue: "Құрамдас жұмбақ бөлігі 01 қою көк",
    Component_PuzzlePiece02_Blue: "Құрамдас жұмбақ бөлігі 02 көк",
    Component_PuzzlePiece03_Green: "Құрамдас жұмбақ бөлігі 03 жасыл",
    Component_PuzzlePiece04_Red: "Құрамдас жұмбақ бөлігі 04 қызыл",
    Component_PuzzlePiece05_Orange: "Құрамдас жұмбақ бөлігі 05 қызғылт сары",
    Component_Sphere01_DarkBlue: "Құрамдас сфера 01 қою көк",
    Component_Sphere02_LightBlue: "Құрамдас сфера 02 ашық көк",
    Component_Sphere03_Green: "Құрамдас сфера 03 жасыл",
    Component_Sphere04_DarkRed: "Құрамдас сфера 04 қою қызыл",
    Component_Sphere05_Orange: "Құрамдас сфера 05 қызғылт сары",
    Book: "Кітап",
    Box01: "Терезе 01",
    Box02: "Терезе 02",
    Bulb01_Yellow: "Шам 01 сары",
    Bulb02_Yellow: "Шам 02 сары",
    Calendar: "Күнтізбе",
    Chart: "Диаграмма",
    Clipboard: "Аралық сақтағыш",
    Clock: "Сағат",
    Compass: "Компас",
    Flag01_Red: "Жалауша 01 қызыл",
    Flag02_Green: "Жалауша 02 жасыл",
    Flag03_Blue: "Жалауша 03 көк",
    Gift: "Сыйлық",
    House: "Үй",
    Icon_Computer01_White: "Компьютер белгішесі 01 ақ",
    Icon_Computer02_Black: "Компьютер белгішесі 02 қара",
    Icon_Disk01_Blue: "Диск белгішесі 01 көк",
    Icon_Disk02_Green: "Диск белгішесі 02 жасыл",
    Icon_Document01_Grey: "Құжат белгішесі 01 сұр",
    Icon_Document02_Grey: "Құжат белгішесі 02 сұр",
    Icon_Document03_Blue: "Құжат белгішесі 03 көк",
    Icon_Document04_Blue: "Құжат белгішесі 04 көк",
    Icon_Envelope01_Blue: "Хатқалта белгішесі 01 көк",
    Icon_Envelope02_Yellow: "Хатқалта белгішесі 02 сары",
    Icon_Envelope03_Open_Yellow: "Хатқалта белгішесі 03 ашық сары",
    Icon_Envelope04_Open_Yellow: "Хатқалта белгішесі 04 ашық сары",
    Icon_Folder01_Yellow: "Қалта белгішесі 01 сары",
    Icon_Folder02_Yellow: "Қалта белгішесі 02 сары",
    Icon_Folder03_Open_Yellow: "Қалта белгішесі 03 ашық сары",
    Icon_Folder04_Open_Yellow: "Қалта белгішесі 04 ашық сары",
    Icon_Gear01_Grey: "Құрылғы белгішесі 01 сұр",
    Icon_Gear02_Blue: "Құрылғы белгішесі 02 көк",
    Icon_Network01_Blue: "Желі белгішесі 01 көк",
    Icon_Network02: "Желі белгішесі 02",
    Icon_Pencil01: "Қарындаш белгішесі 01",
    Icon_Pencil02: "Қарындаш белгішесі 02",
    Icon_Printer01_White: "Принтер белгішесі 01 ақ",
    Icon_Printer02_Black: "Принтер белгішесі 02 қара",
    Key01: "Кілт 01",
    Key02: "Кілт 02",
    Lock01_Yellow: "Құлып 01 сары",
    Lock02_Yellow: "Құлып 02 сары",
    Lock03_Blue: "Құлып 03 көк",
    Lock04_Blue: "Құлып 04 көк",
    Magnet: "Магнит",
    MagnifyingGlass: "Лупа",
    Medal: "Медаль",
    Notebook: "Жазу кітапшасы",
    Phone: "Телефон",
    PieChart: "Дөңгелек диаграмма",
    Pin: "Қыстыру",
    PuzzlePiece: "Жұмбақ бөлігі",
    PuzzlePieces: "Жұмбақ бөліктері",
    Roadblock: "Жол бөлігі",
    Scissors: "Қайшы",
    Shield01: "Қорғаныс 01",
    Shield02_Orange: "Қорғаныс 02 қызғылт сары",
    Shield03_Blue: "Қорғаныс 03 көк",
    Sign_Ban01: "Болдырмау белгісі 01",
    Sign_Ban02: "Болдырмау белгісі 02",
    Sign_CheckBox01: "Құсбелгі белгісі 01",
    Sign_CheckBox02_Unchecked: "Құсбелгі белгісі 02 тексерілмеген",
    Sign_Checkmark01_Green: "Құсбелгі белгісі 01 жасыл",
    Sign_Checkmark02_Green: "Құсбелгі белгісі 02 жасыл",
    Sign_DoNotEnter: "Енгізбеу белгісі",
    Sign_Error01: "Қате белгісі 01",
    Sign_Error02: "Қате белгісі 02",
    Sign_ExclamationPoint01_Red: "Леп белгісі 01 қызыл",
    Sign_ExclamationPoint02_Orange: "Леп белгісі 02 қызғылт сары",
    Sign_Help01_Green: "Анықтама белгісі 01 жасыл",
    Sign_Help02_Blue: "Анықтама белгісі 02 көк",
    Sign_Information: "Ақпарат белгісі",
    Sign_Null: "Нөл белгісі",
    Sign_QuestionMark01_Blue: "Сұрақ белгісі 01 көк",
    Sign_QuestionMark02_Red: "Сұрақ белгісі 02 қызыл",
    Sign_RadioButton01: "Радио түймешігі белгісі 01",
    Sign_RadioButton02_Unchecked: "Радио түймешігі белгісі 02 тексерілмеген",
    Sign_Warning01_Red: "Ескерту белгісі 01 қызыл",
    Sign_Warning02_Orange: "Ескерту белгісі 02 қызғылт сары",
    Sign_X01_Red: "Белгі X 01 қызыл",
    Sign_X02_Red: "Белгі X 02 қызыл",
    Star_Yellow: "Жұлдызша сары",
    Wrench: "Бұрайтын кілт",
    Airplane_Blue: "Ұшақ көк",
    Bicycle_Blue: "Велосипед көк",
    Bus: "Автобус",
    Canoe_Blue: "Каноэ көк",
    Car_Red: "Машина қызыл",
    Helicopter_Blue: "Тікұшақ көк",
    Motorcycle_Red: "Мотоцикл қызыл",
    Pedestrian_Blue: "Жүргінші көк",
    PersonalTransporter_Green: "Жеке тасымалдаушы жасыл",
    Sailboat_Red: "Желкенді қайық қызыл",
    Scooter_Orange: "Самокат қызғылт сары",
    Train_Red: "Поезд қызыл",
    Truck_Blue: "Жүк көлігі көк",
    
    aria_category_selector: "Сурет санатының параметрлері",
    filterImageGallery: "Сурет жиынтығын сүзу"

})
