/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */


define({
        saveTip: "Сақтау",
        undoTip: "Болдырмау",
        redoTip: "Қайтару",
        formatPainterTip: "Пішімдеуді көшіру",
        showSorterTip: "Слайдты сұрыптау құралын көрсету",
        hideSorterTip: "Слайдтарды сұрыптаушыды жасыру",
        webClipboardTip: "Веб-аралық сақтағыш",
        spellCheckTip: "Қолмен емлені тексеруді іске қосу",
        createSectionTip: "Бөлім тағайындау",
        createCellsTip: "Ұяшықтарды белгілеу",
        createSlideTip: "Слайдтарды тағайындау",
        submitTip: "Тапсырманы жіберу",
        addCommentTip: "Пікір қосу",
        removeFormatTip: "Пішімдеуді алып тастау",
        sortAscTip: "Артуы бойынша сұрыптау",
        sortDescTip: "Кемуі бойынша сұрыптау",
        instantFilterTip: "Жедел сүзгі",
        insertChartTip: "Диаграмма кірістіру",
        startAutofillTip: "Автотолтыру",
        dataValidationTip: "Деректер тексерісі",

        selectFontTip: "Қаріпті таңдау",
        selectFontSizeTip: "Қаріп өлшемін таңдау",
        selectFontNameTip: "Қаріп атауын таңдау",
        FontName: "Қаріп аты",
        FontSize: "Қаріп өлшемі",
        increaseFontSizeTip: "Қаріп өлшемін үлкейту",
        decreaseFontSizeTip: "Қаріп өлшемін кішірейту",
        boldTip: "Қалың",
        italicTip: "Көлбеу",
        underlineTip: "Астын сызу",
        strikeThroughTip: "Сызылған",
        setFontColorTip: "Қаріп түсін орнату",
        setShadingColorTip: "Көлеңке түсті орнату",
        setBackgroundFill: "Өңдік бояуды орнату",
        setBgColorTip: "Өңдік түсті орнату",
        setBorderTip: "Жиек мәнерін және түсін орнату",
        setBorderColorTip: "Жиек түсін орнату",
        setHighlightColor: "Ерекше түсті орнату",
        formatPainter: "Пішімдеуді көшіру",
        //	clearFormat:"Remove Formatting",
        zoom: "Үлкейту",
        selectStyleTip: "Мәнерді таңдау",
        styles: "Мәнер",
        formatAsCurrencyTip: "Валюта ретінде пішімдеу",
        formatAsPercentTip: "Пайыз ретінде пішімдеу",
        decreaseDecimalTip: "Ондық орындарды азайту",
        increaseDecimalTip: "Ондық орындарды арттыру",
        formatNumberTip: "Сан пішімі",

        numberedListTip: "Нөмірлеуді қосу немесе нөмірлеу мәнерін өзгерту",
        bulletedListTip: "Таңбалаушыларды қосу немесе таңбалаушы мәнерін өзгерту",
        multilevelListTip: "Көп деңгейлі тізімді қосу немесе өзгерту",
        indentTip: "Жол шегінісін үлкейту",
        decreaseIndentTip: "Жол шегінісін кішірейту",
        alignTip: "Туралау",
        leftAlignTip: "Сол жақ бойынша туралау",
        centerTip: "Ортасы бойынша туралау",
        rightAlignTip: "Оң жақ бойынша туралау",
        justifyTip: "Туралау",
        bottomBorderTip: "Жиек асты",
        borderTypes: "Жиек түрлері",
        borderTip: "Жиек стилін орнату",
        topAlignTip: "Жоғарыға туралау",
        middleAlignTip: "Ортаға туралау",
        bottomAlignTip: "Төменге туралау",
        lineSpacingTip: "Жол аралығы",
        mergeSplitCellTip: "Ұяшықтарды біріктіру немесе бөлу",
        wrapNoWrapTip: "Келесіге немесе келесіден тасымалдау",
        ltrDirectionTip: "Солдан оңға қарай мәтінді өзгерту",
        rtlDirectionTip: "Оңнан солға қарай мәтінді өзгерту",
        autoDirectionTip: "Мәтін бағытын өзгерту",
        toggleSheetDirectionTip: "Парақ бағытын өзгерту",
        setSheetDirectionLTR: "Солдан оңға",
        setSheetDirectionRTL: "Оңнан солға",

        addTableTip: "Кесте қосу",
        insertOrMoveRowTip: "Жолды кірістіру немесе жылжыту",
        insertOrMoveColTip: "Бағанды кірістіру немесе жылжыту",
        insertOrDeleteRowTip: "Жолды кірістіру немесе жою",
        insertOrDeleteColTip: "Бағанды кірістіру немесе жою",
        insertFunctionTip: "Функцияны кірістіру",
        insertImage: "Сурет кірістіру",
        resizeCol: "Баған өлшемін өзгерту",
        resizeCols: "Бағандар өлшемін өзгерту",
        addLink: "Сілтемені қосу немесе өңдеу",
        tableStyle: "Кесте мәнерлері",

        selectBorder_BottomBorder: "Төменгі жиек",
        selectBorder_TopBorder: "Үстіңгі жиек",
        selectBorder_LeftBorder: "Сол жақтағы жиек",
        selectBorder_RightBorder: "Оң жақ жиек",
        selectBorder_NoBorder: "Жолдар жоқ",
        selectBorder_AllBorders: "Барлық жиек",

        insertOrMoveRow_InsertAbove: "Жолды жоғары кірістіру",
        insertOrMoveRow_InsertBelow: "Жолды төмен кірістіру",
        insertOrMoveRow_MoveUp: "Жолды жоғары жылжыту",
        insertOrMoveRow_MoveDown: "Жолды төмен жылжыту",
        insertOrMoveCol_InsertLeft: "Бағанды алдына кірістіру",
        insertOrMoveCol_InsertRight: "Бағанды артынан кірістіру",
        insertOrMoveCol_InsertBefore: "Бағанды алдына кірістіру",
        insertOrMoveCol_InsertAfter: "Бағанды артынан кірістіру",
        insertOrMoveCol_MoveLeft: "Бағанды солға жылжыту",
        insertOrMoveCol_MoveRight: "Бағанды оңға жылжыту",

        insertOrDelete_Delete: "Жою",

        combineButtonReadTip: "Down Arrow пернесін мәзірді белсендіру үшін басыңыз, сосын көрсеткілермен шарлаңыз",

        lineSpacing_1: "1",
        lineSpacing_12: "1.2",
        lineSpacing_15: "1.5",
        lineSpacing_2: "2",
        lineSpacing_25: "2.5",
        lineSpacing_3: "3",

        percent: "%",
        font_arial: "Arial",

        fontSize: "${0} нүкте",

        slides: "Әр бетке бір слайд",
        slidesWithNotes: "Ескерімдері бар слайдтар",
        preparingSlides: "Слайдтарды басып шығаруға дайындау...",
        printLayoutOptionLabel: "Басып шығару схемасының параметрлері",

        targetRemovedWhenDialogOpen: "Бұл әрекетті аяқтау мүмкін емес, себебі мақсатты басқа бірлескен өңдегіш жойды.",

        NUMBER: "Сан",
        CURRENCY: "Валюта",
        PERCENT: "Пайыз",
        DATE: "Күні",
        TIME: "Уақыт",
        DATETIME: "КүнУақыт",
        MORECURRENCY: "Валюталық бірлік бойынша көп валюталар",
        MORECURRENCYCODE: "Валюта коды бойынша көп валюталар",
        MOREDATE: "Көп уақыт және күн пішімдері",
        TEXT: "Мәтін",
	
        // currency, by currency code
        // NOTE: MUST keep it in order
        CURRENCY_CODE: {
            AED: "Біріккен Араб Әмірлігі (Дирхам)",
            ARS: "Аргентина (Песо)",
            AUD: "Австралия (Доллар)",
            BGN: "Болгария (Лева)",
            BOB: "Боливия (Боливиано)",
            BRL: "Бразилия (Реал)",
            CAD: "Канада (Доллар)",
            CHF: "Швейцария (Франк)",
            CLP: "Чили (Песо)",
            CNY: "Қытай (Юан ренминбиі)",
            COP: "Колумбия (Песо)",
            CRC: "Коста-Рика (Колон)",
            CZK: "Чех Республикасы (Крона)",
            DKK: "Дания (Крона)",
            DOP: "Доминикан Республикасы (Песо)",
            EGP: "Мысыр (Фунт)",
            EUR: "Австрия, Бельгия, Финляндия, Франция, ..., Словения, Испания(Еуро)",
            GBP: "Англия, Біріккен әмірлік (Фунт)",
            HKD: "Гонконг (Доллар)",
            HRK: "Хорватия (Куна)",
            HUF: "Венгрия (Форинт)",
            IDR: "Индонезия (Рупия)",
            ILS: "Израиль (Жаңа шекелей)",
            INR: "Индия (Рупи)",
            JPY: "Жапония (Иен)",
            KRW: "Кроея, Оңтүстік (Вона)",
            KZT: "Қазақстан (Теңге)",
            MAD: "Марокко (дирхам)",
            MXN: "Мексика (Песо)",
            MYR: "Малайзия (Ринггит)",
            NOK: "Норвегия (Крона)",
            NZD: "Жаңа Зенландия (Доллар)",
            PAB: "Панама (Бальбоа)",
            PEN: "Перу (Жаңа перу солі)",
            PHP: "Филиппин (Песо)",
            PKR: "Пәкістан (Рупи)",
            PLN: "Польша (Злотых)",
            PYG: "Парагвай (Гуарани)",
            RON: "Румыния (Жаңа Лей)",
            RSD: "Сербиялық (Кирилл жазуы), Сербиялық (Латын)",
            RUB: "Ресей (Рубль)",
            SAR: "Сауд Арабиясы (Риал)",
            SEK: "Швеция (Крона)",
            SGD: "Сингапур (Доллар)",
            SVC: "Эль-Сальвадор (Колон)",
            THB: "Тайланд (Бахт)",
            TRY: "Түркия (Лира)",
            TWD: "Тайвань (Жаңа доллар)",
            USD: "Эквадор, Пуэрто-Рико, Америка Құрама Штаттары (АҚШ Доллар)",
            UYU: "Уругвай (Песо)",
            VEF: "Венесуэла (Боливар)",
            VND: "Вьетнам (Донг)",
            ZAR: "Оңтүстік Африка (Рант)"
        },
        // for border toolbar
        allBorders: "Барлық жиектер",
        innerBorders: "Ішкі жиектер",
        horizontalBorders: "Көлденең жиектер",
        verticalBorders: "Тігінен жиектер",
        outerBorders: "Сыртқы жиектер",
        borderColor: "Жиек түсі",
        leftBorder: "Сол жақтағы жиек",
        topBorder: "Жоғарғы жиек",
        rightBorder: "Оң жақ жиек",
        bottomBorder: "Төменгі жиек",
        clearBorders: "Жиектер жоқ",
        BorderStyle_ThinSolid: "Жіңішке тұтас сызық",
        BorderStyle_ThinDotted: "Жіңішке үзік сызық",
        BorderStyle_ThinDashed: "Жіңішке нүктелі сызық",
        BorderStyle_ThickSolid: "Қалың тұтас сызық",
        BorderStyle_ThickDotted: "Қалың үзік сызық",
        BorderStyle_ThickDashed: "Қалың нүктелі сызық"
})

