({
	COLUMN: "Stolpčni grafikon",
	CLUSTERED_COLUMN: "Razvrstilni stolpčni grafikon",
	STACKED_COLUMN: "Naložen stolpčni grafikon",
	BAR:"Palični grafikon",
	CLUSTERED_BAR:"Razvrstilni palični grafikon",
	STACKED_BAR: "Naložen palični grafikon",
	PIE:"Tortni grafikon",
	SLICE: "Rezina",
	AREA: "Ploščinski grafikon",
	STACKED_AREA: "Naložen ploščinski grafikon",
	LINE: "Črtni grafikon",
	STACKED_LINE: "Naložen črtni grafikon",
	MAKER_LINE: "Črtni grafikon z označevalci",
	STACKED_MARKER_LINE: "Naložen črtni grafikon z označevalci",
	SCATTER: "Raztreseni grafikon",
	SCATTER_MARKER_ONLY: "Raztreseni grafikon samo z označevalci",
	SCATTER_MARKER_LINE_S: "Raztreseni grafikon z gladkimi črtami in označevalci",
	SCATTER_LINE_S: "Raztreseni grafikon z gladkimi črtami", 
	SCATTER_MARKER_LINE_X: "Raztreseni grafikon z ravnimi črtami in označevalci",
	SCATTER_LINE_X: "Raztreseni grafikon z ravnimi črtami",
	ERROR_INVALID_RANGE:"Neveljaven obseg podatkov",
	TOO_MANY_POINTS: "Grafikona z več kot ${0} podatkovnimi točkami ni mogoče ustvariti",
	CHART_TYPES:"Vrste grafikonov",
	DATA:"Podatki",
	DATA_RANGE:"Obseg podatkov",
	IN_ROWS:"Podatkovni nizi v vrsticah",
	IN_COLUMNS:"Podatkovni nizi v stolpcih",
	AUTO:"Samodejno"
})
