({
	ORIENTATION_LABEL: "Orientamento",
	PORTRAIT: "Verticale",
	LANDSCAPE: "Orizzontale",
	PAGE_LABEL: "Ordine pagine",
	PAGE_TYPE1: "Dall'alto in basso, quindi a destra",
	PAGE_TYPE2: "Da sinistra a destra, quindi in basso",
	DISPLAY_OPTION_LABEL: "Opzioni di visualizzazione",
	HEADER: "Intestazione",
	FOOTER: "Piè di pagina",
	GRIDLINE: "Linee griglia",
	TAGGED_PDF: "PDF con tag",
	MARGINS_LABEL: "Margini",
	TOP: "Superiore:",
	TOP_DESC:"Margine superiore, in centimetri",
	TOP_DESC2:"Margine superiore, in pollici",
	BOTTOM: "Inferiore:",
	BOTTOM_DESC:"Margine inferiore, in centimetri",
	BOTTOM_DESC2:"Margine inferiore, in pollici",	
	LEFT: "Sinistro:",
	LEFT_DESC:"Margine sinistro, in centimetri",
	LEFT_DESC2:"Margine sinistro, in pollici",	
	RIGHT: "Destro:",
	RIGHT_DESC:"Margine destro, in centimetri",
	RIGHT_DESC2:"Margine destro, in pollici",	
	PAPER_FORMAT_LABEL: "Formato carta",
	PAPER_SIZE_LABEL: "Dimensione carta:",
	HEIGHT: "Altezza:",
	HEIGHT_DESC:"Altezza carta, in centimetri",
	HEIGHT_DESC2:"Altezza carta, in pollici",		
	WIDTH: "Larghezza:",
	WIDTH_DESC:"Larghezza carta, in centimetri",
	WIDTH_DESC2:"Larghezza carta, in pollici",
	
	INVALID_MSG: "L'input non è valido ed è stato corretto automaticamente. Inserire un altro valore per ottenere un risultato differente.",
	
	TOOLTIP1:"Stampa tante righe quante ne consente il foglio, procedendo lateralmente fino a quando le colonne del foglio terminano, quindi riprende a stampare in basso a sinistra il nuovo gruppo di righe.",
	TOOLTIP2:"Stampa tante colonne quante ne consente il foglio, spostandosi verso il basso fino a quando le righe del foglio terminano, quindi riprende a stampare in alto a destra il nuovo gruppo di colonne.",
	CM_LABEL: "cm",
	LETTER: "Letter",
	LEGAL: "Legal",
	TABLOID: "Tabloid",
	USER: "Utente",
	SIZE1: "Env. n. 6 3/4",
	SIZE2: "Env. Monarch",
	SIZE3: "Env. n. 9",
	SIZE4: "Env. n. 10",
	SIZE5: "Env. n. 11",
	SIZE6: "Env. n. 12",
	SIZE7: "16 kai",
	SIZE8: "32 kai",
	SIZE9: "32 kai grande"
})
	
