({
		SAVE: "Сақтау",
		UNDO:"Болдырмау",
		REDO:"Қайтару",
		INSERTROW:"Жол енгізу",
		DELETEROW:"Жолды жою",
		INSERTCOLUMN:"Баған енгізу",
		DELETECOLUMN:"Бағанды жою",
		FONTSIZE:"Қаріп өлшемі",
		FONTCOLOR:"Қаріп түсі",
		BOLD:"Қалың",
		ITALIC:"Көлбеу",
		UNDERLINE:"Астын сызу",
		STRIKETHROUGH:"Сызылған",
		CURRENCYTIP:"Валюта ретінде пішімдеу",
		PERCENTLABEL:"%",
		PERCENTTIP:"Пайыз ретінде пішімдеу",
		NUMBERFORMAT:"Сан пішімі",
		ALIGNLEFT:"Сол жақ бойынша туралау",
		ALIGNCENTER:"Ортасы бойынша туралау",
		ALIGNRIGHT:"Оң жақ бойынша туралау",
		SETCELLBORDER:"Ұяшық жиегін орнату",
		BACKGROUNDCOLOR:"Өң түсі",
		TASK:"Бөлім тағайындау",
		COMMENTS:"Пікір қосу",
		SUBMIT:"Жіберу",
		MERGECELL: "Ұяшықтарды біріктіру немесе бөлу",
		QUICKFORMULA: "Жылдам формула",
		WRAPTEXT: "Тасымалдау мәтіні",
		EIGHT:"8 нүкте",
		NINE:"9 нүкте",
		TEN:"10 нүкте",
		ELEVEN:"11 нүкте",
		TWELVE:"12 нүкте",
		FOURTEEN:"14 нүкте",
		SIXTEEN:"16 нүкте",
		EIGHTEEN:"18 нүкте",
		TWENTY:"20 нүкте",
		TWENTYTWO:"22 нүкте",
		TWENTYFOUR:"24 нүкте",
		NUMBER:"Сан",
		CURRENCY:"Валюта",
		PERCENT:"Пайыз",
		DATE:"Күн",
		TIME:"Уақыт",
		DATETIME: "КүнУақыт",
		MORECURRENCY:"Көп валюта",
		MOREDATE:"Қосымша пішімдер",
		
		
		CAD: "канадалық доллар",
		USD: "доллар",
		EUR: "еуро",
		CHF: "швейцариялық франк",
		HKD: "гонконгтік доллар",
		DKK: "крона",
		LTL: "лита",
		PHP: "песо",
		BRL: "реал",
		RUR: "рубль",
		GBP: "фунт",
		NLG: "гульден", // Netherlands
		TWD: "жаңа тайваньдық доллар",
		THB: "бахт", // Thailand
		ITL: "лира", // Turkey
		BGL: "лев", // Uzbekistan
		VND: "донг", // Vietnam
		KRW: "вона",	// Korean 
		CNY: "юан", // RMB
		JPY: "иен" // Japan Yen
})
