/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2014. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        spreadsheetTemplates: "Laskentataulukkomallit",
        documentTemplates: "Asiakirjamallit",
        titleShareDocument: "Jaa asiakirja",
        offline: "Offline-tila",
        versionPublishing: "Version julkaisu on meneillään.",
        versionPublishFailed: "Versiota ei julkaistu. Tiedosto saattaa olla liian iso, tai palvelin on saattanut tehdä aikakatkaisun. Yritä uudelleen tai peruuta toiminto ja pyydä järjestelmänvalvojaa selvittämään ongelma tarkistamalla palvelimen loki.",
        versionCheckinFailed: "Versiota ei kuitattu sisään. Tiedosto saattaa olla liian iso, tai palvelin on saattanut tehdä aikakatkaisun. Yritä uudelleen tai peruuta toiminto ja pyydä järjestelmänvalvojaa selvittämään ongelma tarkistamalla palvelimen loki.",
        versionSavedFailed: "Tallennus ei valmistunut. Yritä tallentaa myöhemmin uudelleen.",
        publishFileSizeExceedMsg: "Tiedoston julkaisu ei onnistu, koska se ylittää tietovaraston pääkäyttäjän asettaman enimmäiskoon. Pienennä tiedoston kokoa poistamalla sisältöä tai pyydä pääkäyttäjää kasvattamaan kokorajoitusta.",
        checkinFileSizeExceedMsg: "Tiedoston sisäänkuittaus ei onnistu, koska se ylittää tietovaraston pääkäyttäjän asettaman enimmäiskoon. Pienennä tiedoston kokoa poistamalla sisältöä tai pyydä pääkäyttäjää kasvattamaan kokorajoitusta.",
        versionpublished: "${0} on julkaissut version kello ${1}.",
        versionPublishing2: "Version tallennus on meneillään.",
        versionPublishFailed2: "Versiota ei tallennettu. Tiedosto saattaa olla liian iso, tai palvelin on saattanut tehdä aikakatkaisun. Yritä uudelleen tai peruuta toiminto ja pyydä järjestelmänvalvojaa selvittämään ongelma tarkistamalla palvelimen loki.",      
        publishFileSizeExceedMsg2: "Tiedoston tallennus ei onnistu, koska se ylittää tietovaraston pääkäyttäjän asettaman enimmäiskoon. Pienennä tiedoston kokoa poistamalla sisältöä tai pyydä pääkäyttäjää kasvattamaan kokorajoitusta.",
        versionpublished2: "${0} on tallentanut version kello ${1}.",
        chekinCloseDocsMsg: "Voit sulkea ohjelman ${productName} nyt.",
        draftSavingAs: "Tiedoston kopiointi on meneillään...",
        draftSavedAs: "Uusi kopio tallennetaan nimellä ${0}.",
        synchronizing: "Odota, että synkronointi palvelimen kanssa valmistuu.",
        synchronizeError: "Synkronointi palvelimen kanssa ei onnistu.",
        joinwithoutentitle: "Käyttäjät: ${0} haluavat muokata asiakirjaa, mutta he eivät voi liittyä muokkausistuntoon, koska sinulla ei ole oikeuksia yhteismuokkaukseen.",
        joinwithoutentitle2: "Käyttäjät: ${0} haluavat muokata asiakirjaa, mutta he eivät voi liittyä muokkausistuntoon, koska heillä ei ole oikeuksia yhteismuokkaukseen.",
        backtoFiles: "Avaa omat tiedostot",
        backtoCommFiles: "Avaa yhteisön tiedostot",
        backtoLibrary: "Avaa kirjasto",
        backtoICN: "Avaa Content Navigator",
        backtoRepository: "Avaa tiedostoluettelo",
        createNewSpred: "Luo laskentataulukko",
        createNewDoc: "Luo asiakirja",
        createNewDocFromTemp: "Luo asiakirja mallipohjasta",
        shareDoc: "Määritä asiakirja yhteiskäyttöön",
        exportPdf: "Sivun asetukset",
        insertDate: "Päivämäärän valinta",
        insertTime: "Kellonajan valinta",
        connect: "Muodosta yhteys",
        theDoc: "asiakirja",
        save: "Tallenna muutokset",
        saveBeforeReviewMsg: "Sinulla on tallentamattomia muutoksia. Tallenna muutokset ja lähetä kohde sitten uudelleen tarkastettavaksi.",
        submitReviewWidgetsFaiure: "Sovelluksen alustus ei onnistunut. Lähetä kohde myöhemmin uudelleen tarkastettavaksi.",
        widgetsFaiure: "Sovelluksen alustus ei onnistunut.",
        slideSorter: "Diat",
        commentsBar: "Kommentit",
        draftBadge: "LUONNOS",
        share: "Määritä yhteiskäyttöön",
        comment: "Kommentti",
        showSidebar: "Näytä sivupalkki",
        publishVersion: "Julkaise",
        checkInVersion: "Kuittaa sisään",
        saveVersion: "Tallenna",
        saved: "Kaikki muutokset on tallennettu",
        saving: "Tallennus on meneillään",
        submitFragment: "Lähetä",
        aria_inMainMenu: "Olet nyt päävalikossa",
        aria_inSlideSorter: "Olet nyt diojen lajittelunäkymässä",
        aria_inSlideEditor: "Olet nyt diojen muokkausnäkymässä",
        createNewPres: "Luo esitys",
        createNewAppFromTemp: "Luo asiakirja mallipohjasta",
        textdoc: "teksti",
        sheetdoc: "laskentataulukko",
        presdoc: "esitys",
        saveAsTextErrMsg: "Seuraavaa asiakirjaa ei voi tallentaa.",
        saveAsPresErrMsg: "Uutta esitysasiakirjaa ei voi tallentaa.",
        saveAsSheetErrMsg: "Uutta laskentataulukkoasiakirjaa ei voi tallentaa.",
        saveAsTextErrMsg1: "Tila ei riitä asiakirjan tallennukseen.",
        saveAsPresErrMsg1: "Tila ei riitä esityksen tallennukseen.",
        saveAsSheetErrMsg1: "Tila ei riitä laskentataulukon tallennukseen.",
        newDocTextErrMsg: "Uutta tekstitiedostoa ei voi luoda.",
        newDocSheetErrMsg: "Uutta laskentataulukkoasiakirjaa ei voi luoda.",
        newDocPresErrMsg: "Uutta esitysasiakirjaa ei voi luoda.",
        newDocTextErrMsg2: "Uutta asiakirjaa ei voi luoda mallipohjasta.",
        newDocSheetErrMsg2: "Uutta laskentataulukkoasiakirjaa ei voi luoda mallipohjasta.",
        newDocPresErrMsg2: "Uutta esitysasiakirjaa ei voi luoda mallipohjasta.",
        newDocTextErrMsg3: "Tila ei riitä asiakirjan luontiin.",
        newDocSheetErrMsg3: "Tila ei riitä laskentataulukon luontiin.",
        newDocPresErrMsg3: "Tila ei riitä esityksen luontiin.",
        newDocTextErrMsg4: "Järjestelmässä on jo asiakirja, jolla on sama otsikko. Määritä uudelle asiakirjalle eri otsikko.",
        newDocSheetErrMsg4: "Järjestelmässä on jo laskentataulukko, jolla on sama otsikko. Määritä uudelle laskentataulukolle eri otsikko.",
        newDocPresErrMsg4: "Järjestelmässä on jo esitys, jolla on sama otsikko. Määritä uudelle esitykselle eri otsikko.",        
        aclWarningTitle: "Uuden version muokkaus ei onnistu",
        aclWarningMsg: "Tiedostoa on suositeltavaa muokata vain online-tilassa, koska tiedoston omistaja on määrittänyt tiedostoon suojattuja alueita. Ota yhteys tiedoston omistajaan (${0}), jos uuden version siirto palvelimeen on mielestäsi tärkeää.",
        aclWarningMsgForOwner: "Tässä tiedostossa on suojattuja alueita. Siksi palvelimeen siirrettyä uutta versiota ei voi muokata online-tilassa.  Kaikki suojatut alueet on poistettava tiedostosta, ja sen jälkeen uuden palvelimeen siirretyn version voi avata muokattavaksi.",
        st0: "Taulukko1",
        st1: "Taulukko2",
        st2: "Taulukko3",
        FootnoteMsg: "Sivu",
        conflictMsg: "Toisten muokkaajien tekemät muutokset ovat ristiriidassa tekemiesi muutosten kanssa.  Tekemäsi muutokset peruutetaan.",
        undoRedoConflictMsg: "Kumoa- ja tee uudelleen -toiminnot keskeytetään, koska tekemäsi muokkaukset ja kanssasi asiakirjaa yhdessä muokkaavan henkilön tekemät muutokset ovat ristiriidassa",
        bigFileErrMsg: "Asiakirja on liian suuri. Tarkista päivittämällä selain, onko koko sisältö vahingoittumaton.",
        noPermissionMsg: "Sinulla ei ole tämän tiedoston muokkausoikeuksia. Pyydä tiedoston muokkausoikeudet tiedoston omistajalta ja yritä sitten uudelleen.",
        networkIssueMsg: "On ilmennyt verkko-ongelma.",
        networkIssueTitle: "Verkko-ongelma",
        networkIssueContent: "On ilmennyt verkko-ongelma. Päivitä sivu ja yritä muodostaa yhteys uudelleen.",
        lockEditorMsg: "Asiakirjan muokkaus ei onnistu, ennen kuin yhteys palvelimeen on muodostettu.",
        offlineReasonMsg: "Istunto on aikakatkaistu.",
        offlineReasonForServerUnacceptedMsg: "Joidenkin tekemiesi toimien käsittely ei onnistu. Docs-palvelin hylkää toimet, jotka on tehty viimeisen minuutin aikana.",
        offlineReasonForServerDraftFormatChange: "Asiakirjan muoto on vanhentunut palvelinpäivityksen vuoksi.",
        reloadExplanationMsg: "Jatka kirjautumalla uudelleen.",
        reloadBtnLabel: "Lataa uudelleen",
        reconnectingMsg: "Odota, että yhteys palvelimeen on muodostettu.",
        loadMsg: "Odota, että asiakirja latautuu.",
        loadingDocumentMsg: "Odota, että asiakirja latautuu palvelimesta.",
        reLoadingDocumentMsg: "Odota, että asiakirja latautuu uudelleen palvelimesta.",
        unsupportMsg: "Järjestelmä on havainnut ominaisuuden, joka ei ole tuettu. Katso lisätiedot.",
        browserWorkingMsg: "Käsittely on meneillään...",
        fileDeepDetectTitle: "Tiedostomuoto ja tiedoston tunniste eivät täsmää.",
        fileDeepDetectMsg: "Tiedostomuoto ei ole se, jonka tiedoston tunniste ilmaisee. Muokkaa tiedostoa tässä muodossa valitsemalla Jatka-vaihtoehto.",
        fileDeepDetectOkLabel: "Jatka",
        tipInfo: "Vihje: ${0}",
        selectTextInfo: "Valitse teksti, johon tyyliä käytetään.",
        removeRecentFile: "Tiedosto, jonka haluat avata, on poistettu. Haluatko poistaa tiedoston nimen Viimeisimmät tiedostot -luettelosta?",
        altLotusIcon: "",
        altErrorMsgIcon: "Virhesanoma",
        altWarningMsgIcon: "Varoitussanoma",
        altSuccessMsgIcon: "Onnistumissanoma",
        sidebarLandmarkDesc: "sivupalkki",
        footerTitle: "alatunniste",
        mainDesc: "sisältöalue",
        editLockedDocumentWarning: "Lukitsit tiedoston, kun toiset käyttäjät muokkasivat sitä. Yhdistä muutokset yhteistyössä muiden käyttäjien kanssa tai pyydä heitä lopettamaan muokkaus, jotta saat täydet muokkausoikeudet.",
        observerMode: "Olet nyt tarkkailutilassa",
        editorMode: "Olet nyt muokkaustilassa",
        maxEditorLimitReached: "Asiakirjan muokkaajien enimmäismäärä (${0}) tässä istunnossa on saavutettu. Voit siirtyä muokkaustilaan, jos joku muokkaajista poistuu asiakirjasta tai siirtyy tarkkailutilaan.",
        maxEditorLimitReachedTitle: "Muokkaajien enimmäismäärä on saavutettu",
        uploadNewVersionOpenConfirm: "${0} latasi uuden version ${1} ${2}. Haluatko avata uuden version?", //${0} name, ${1} time, ${2} date
        uploadNewVersionPublishConfirm: "${0} latasi uuden version ${1} ${2}.", //${0} name, ${1} time, ${2} date
        you: "Itse",
        today: "tänään",
        yesterday: "eilen",
        slideShowInviteMsg: "Käyttäjä ${0} on aloittanut yhteiskäyttöön määritetyn diaesityksen. Haluatko liittyä esitykseen?",
        slideShowInviteTitle: "Kutsu yhteiskäyttöön määritettyyn diaesitykseen",
        slideShowInviteTitle1: "Kutsu yhteiseen diaesitykseen",
        slideShowCoviewSelectUsersTitle: "Yhteiskäyttöön määritetty diaesitys",
        slideShowCoviewSelectUsersTitle1: "Yhteinen diaesitys",
        slideShowCoviewStmt: "Määritä yhteiskäyttöön esityksen nykyinen tila yhteiskäyttöön määritetyssä diaesityksessä.",
        slideShowCoviewStmt1: "Määritä yhteiskäyttöön esityksen nykyinen tila yhteisessä diaesityksessä.",
        slideShowCoviewOptionOne: "Kutsu kaikki muokkaajat liittymään diaesitykseen.",
        slideShowCoviewOptionOne1: "Kutsu kaikki muokkaajat ja tarkkailijat liittymään diaesitykseen.",
        slideShowCoviewOptionTwo: "Kutsu vain seuraavat muokkaajat liittymään diaesitykseen.",
        slideShowCoviewOptionTwo1: "Kutsu vain seuraavat muokkaajat ja tarkkailijat liittymään diaesitykseen.",
        slideShowCoviewSlidesOf: "Dia ${0}/${1}",  //as in Slide 1 of 4
        slideShowCoviewViewers: "${0} katselijaa",
        slideShowCoviewDialogInput: "Suodata nimi kirjoittamalla tähän",
        slideShowCoviewAddTitle: "Lisää yhteiskäyttöön määritettyyn diaesitykseen",
        slideShowCoviewAddTitle1: "Lisää yhteiseen diaesitykseen",
        slideShowCoviewMessage: "Valitse lisää tähän yhteiskäyttöön määritettyyn diaesitykseen kutsuttavia käyttäjiä.",
        slideShowCoviewMessage1: "Valitse lisää tähän yhteiseen diaesitykseen kutsuttavia käyttäjiä.",
        slideShowCoviewEnded: "Yhteiskäyttöön määritetty diaesitys on päättynyt",
        slideShowCoviewEndMessage: "Yhteiskäyttöön määritetty diaesitys, johon yrität liittyä, ei ole enää käytettävissä.",
        slideShowCoviewEndMessage2: "Käyttäjä ${0} on lopettanut yhteiskäyttöön määritetyn diaesityksen.",
        slideShowWarning: "Nykyinen diaesitys on lopetettava, ennen kuin uusi diaesitys voidaan aloittaa.",
        slideShowHoverMsg: "Napsauttamalla näet, ketkä muut katselevat diaesitystä.",
        slideShowHoverMsgAdd: "Kutsu lisää katselijoita napsauttamalla tätä.",
        csvEmpty: "Vienti .csv-tiedostona ei onnistu, koska taulukossa ei ole tietoja.",
        edit: "Muokkaa",
        printToPDF: "Lataa PDF-tiedostona",
        print: "Tulosta",
        view: "Näytä",
        openLatestFile: "Avaa viimeisin tiedosto",
        updateDocument: "Asiakirja on päivitetty.${0}.",
        updateSpreadsheet: "Laskentataulukko on päivitetty. ${0}.",
        updatePresentation: "Esitys on päivitetty.${0}.",
        labelCancel: "Peruuta",
        msgConversionFail: "Muunto ei onnistunut",
        updateNow: "Avaa nyt",
        fileUpdated: "Asiakirja on päivitetty",
        fileUpdatedContent1: "Asiakirja on päivitetty. Avaa viimeisin tiedosto ennen tulostusta.",
        htmlviewerlimitation1: "Laskentataulukossa on pivot-taulukko, jonka näyttö ei onnistu",
        htmlviewerlimitation2: "Laskentataulukossa on ehdollisia muotoiluja, joiden näyttö ei onnistu",
        htmlviewerlimitation3: "Laskentataulukossa on pivot-taulukko ja ehdollisia muotoiluja, joiden näyttö ei onnistu",
        close: "Sulje",
        closeDocs: "Sulje ${productName}",
        endSessionDlgTitle: "Muokkausistunto on päättynyt",
        endSessionDlgNotice: "Muokkausistuntosi on päättynyt, koska ${0} on kuitannut tiedoston sisään.",
        labelStopReview: "Lopeta tarkastus",
        labelRejct: "Hylkää",
        labelApprove: "Hyväksy",
        errorMsg: "Virhe",
        labelItemNotFountTitle: "Toiminnon toteutus ei onnistu.",
        labelItemNotFountMsg: "Toinen yhteisön jäsen on jo käsitellyt tätä asiakirjaa. Saat lisätietoja sulkemalla asiakirjan ja siirtymällä kirjastossa Tiedoston tiedot -sivulle.",
        viewProtectedAreas: "Laskentataulukko sisältää suojattuja alueita. Sitä on tarkasteltava tai muokattava vain online-tilassa.",
        macroTitle: "Tiedosto sisältää makron", 
        macroDesc: "Tiedoston muokkaus saattaa rikkoa makron. Voit estää käyttäjiä muokkaamasta aluetta tai taulukkoa, joka sisältää makron, valitsemalla vaihtoehdot Tiedot > Suojatut alueet.",
        problem_id_msg_title: "Ilmoita ongelmasta pääkäyttäjälle. ",
        problem_id_msg_show: "Näytä lisätiedot napsauttamalla",
    	problem_id_msg_hide: "Piilota lisätiedot napsauttamalla",
    	uploadNewVersionWarningTitle: "Uuden version muokkaus ei onnistu",
        changeHistoryWarningMsg: "Tiedostoa on suositeltavaa muokata vain online-tilassa, koska tiedoston omistaja on ottanut käyttöön muutostenseurannan. Ota yhteys tiedoston omistajaan (${0}), jos uuden version siirto palvelimeen on mielestäsi tärkeää.",
        changeHistoryWarningMsgForOwner: "Tiedostossa on muutostapahtumia. Siksi palvelimeen siirrettyä uutta versiota ei voi muokata online-tilassa.  Tiedoston muutostapahtumat on tyhjennettävä ja muutostenseuranta poistettava käytöstä, ennen kuin uuden palvelimeen siirretyn version voi avata muokattavaksi.",
        viewChangeHistory: "Asiakirjassa on muutostapahtumia. Sitä on tarkasteltava tai muokattava vain online-tilassa.",
    	contentCorruptErrMsg: "Sisällön lataus ei onnistu vioittumisen vuoksi. Pyydä apua pääkäyttäjältä."
});

