({
	ORIENTATION_LABEL: "Orijentacija",
	PORTRAIT: "Portret",
	LANDSCAPE: "Pejsaž",
	PAGE_LABEL: "Redoslijed stranica",
	PAGE_TYPE1: "Od vrha do dna, zatim desno",
	PAGE_TYPE2: "Od lijeva na desno, zatim dolje",
	DISPLAY_OPTION_LABEL: "Opcije prikaza",
	HEADER: "Zaglavlje",
	FOOTER: "Donje zaglavlje",
	GRIDLINE: "Mrežne linije",
	TAGGED_PDF: "Označen PDF",
	MARGINS_LABEL: "Margine",
	TOP: "Vrh:",
	TOP_DESC:"Gornja margina, u centimetrima",
	TOP_DESC2:"Gornja margina, u inčima",
	BOTTOM: "Dno:",
	BOTTOM_DESC:"Donja margina, u centimetrima",
	BOTTOM_DESC2:"Donja margina, u inčima",	
	LEFT: "Lijevo:",
	LEFT_DESC:"Lijeva margina, u centimetrima",
	LEFT_DESC2:"Lijeva margina, u inčima",	
	RIGHT: "Desno:",
	RIGHT_DESC:"Desna margina, u centimetrima",
	RIGHT_DESC2:"Desna margina, u inčima",	
	PAPER_FORMAT_LABEL: "Format papira",
	PAPER_SIZE_LABEL: "Veličina papira:",
	HEIGHT: "Visina:",
	HEIGHT_DESC:"Visina papira, u centimetrima",
	HEIGHT_DESC2:"Visina papira, u inčima",		
	WIDTH: "Širina:",
	WIDTH_DESC:"Širina papira, u centimetrima",
	WIDTH_DESC2:"Širina papira, u inčima",
	
	INVALID_MSG: "Unos je pogrešan i automatski je ispravljen. Pokušajte drugu vrijednost ako želite različit rezultat.",
	
	TOOLTIP1:"Ispisuje onoliko redova koliko je dugačak papir, pomičući se poprijeko sve dok ima stupaca na papiru, zatim se pomakne dolje i lijevo za ispis sljedeće grupe redova.",
	TOOLTIP2:"Ispisuje onoliko stupaca koliko je širok papir, pomičući se dolje sve dok ima redova na papiru, zatim se pomakne gore i desno za ispis sljedeće grupe stupaca.",
	CM_LABEL: "cm",
	LETTER: "Letter",
	LEGAL: "Legal",
	TABLOID: "Tabloid",
	USER: "Korisnik",
	SIZE1: "Env. #6 3/4",
	SIZE2: "Env. Monarch",
	SIZE3: "Env. #9",
	SIZE4: "Env. #10",
	SIZE5: "Env. #11",
	SIZE6: "Env. #12",
	SIZE7: "16 kai",
	SIZE8: "32 kai",
	SIZE9: "32 kai veliko"
})
	
