({
		SAVE: "Uložit",
		UNDO:"Zpět",
		REDO:"Znovu",
		INSERTROW:"Vložit řádek",
		DELETEROW:"Odstranit řádek",
		INSERTCOLUMN:"Vložit sloupec",
		DELETECOLUMN:"Odstranit sloupec",
		FONTSIZE:"Velikost písma",
		FONTCOLOR:"Barva písma",
		BOLD:"Tučné",
		ITALIC:"Kurzíva",
		UNDERLINE:"Podtržené",
		STRIKETHROUGH:"Přeškrtnuté",
		CURRENCYTIP:"Formátovat jako měnu",
		PERCENTLABEL:"%",
		PERCENTTIP:"Formátovat jako procenta",
		NUMBERFORMAT:"Formát čísla",
		ALIGNLEFT:"Zarovnat vlevo",
		ALIGNCENTER:"Zarovnat na střed",
		ALIGNRIGHT:"Zarovnat vpravo",
		SETCELLBORDER:"Nastavit ohraničení buňky",
		BACKGROUNDCOLOR:"Barva pozadí",
		TASK:"Přiřadit sekci",
		COMMENTS:"Přidat komentář",
		SUBMIT:"Odeslat",
		MERGECELL: "Sloučit nebo rozdělit buňky",
		QUICKFORMULA: "Rychlý vzorec",
		WRAPTEXT: "Zalomit text",
		EIGHT:"8 bodů",
		NINE:"9 bodů",
		TEN:"10 bodů",
		ELEVEN:"11 bodů",
		TWELVE:"12 bodů",
		FOURTEEN:"14 bodů",
		SIXTEEN:"16 bodů",
		EIGHTEEN:"18 bodů",
		TWENTY:"20 bodů",
		TWENTYTWO:"22 bodů",
		TWENTYFOUR:"24 bodů",
		NUMBER:"Číslo",
		CURRENCY:"Měna",
		PERCENT:"Procenta",
		DATE:"Datum",
		TIME:"Čas",
		DATETIME: "Datum a čas",
		MORECURRENCY:"Další měny",
		MOREDATE:"Další formáty",
		
		
		CAD: "kanadský dolar",
		USD: "dolar",
		EUR: "euro",
		CHF: "švýcarský frank",
		HKD: "hongkongský dolar",
		DKK: "koruna",
		LTL: "litas",
		PHP: "peso",
		BRL: "real",
		RUR: "rubl",
		GBP: "libra",
		NLG: "gulden", // Netherlands
		TWD: "nový tchaj-wanský dolar",
		THB: "baht", // Thailand
		ITL: "lira", // Turkey
		BGL: "lev", // Uzbekistan
		VND: "dong", // Vietnam
		KRW: "won",	// Korean 
		CNY: "jüan", // RMB
		JPY: "jen" // Japan Yen
})
