/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_symphony_conversion_converter_win32_WinPlatformMetaConvertor */

#ifndef _Included_com_ibm_symphony_conversion_converter_win32_WinPlatformMetaConvertor
#define _Included_com_ibm_symphony_conversion_converter_win32_WinPlatformMetaConvertor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_symphony_conversion_converter_win32_WinPlatformMetaConvertor
 * Method:    convert
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ibm_symphony_conversion_converter_win32_WinPlatformMetaConvertor_convert__Ljava_lang_String_2Ljava_lang_String_2II
  (JNIEnv *, jobject, jstring, jstring, jint, jint);

/*
 * Class:     com_ibm_symphony_conversion_converter_win32_WinPlatformMetaConvertor
 * Method:    convert
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ibm_symphony_conversion_converter_win32_WinPlatformMetaConvertor_convert__Ljava_lang_String_2Ljava_lang_String_2D
  (JNIEnv *, jobject, jstring, jstring, jdouble);

#ifdef __cplusplus
}
#endif
#endif
