﻿/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        fileMenu: "檔案",
        fileMenu_New: "新建",
        fileMenu_NewDocument: "文件",
        fileMenu_NewFromTemplate: "從範本",
        fileMenu_NewDocumentfromTemplate: "來自範本的文件",
        fileMenu_NewPresentation: "簡報",
        fileMenu_NewPresentationfromTemplate: "來自範本的簡報",
        fileMenu_NewSpreadsheet: "試算表",
        fileMenu_NewSpreadsheetFromTemplate: "來自範本的試算表",
        fileMenu_Open: "開啟",
        fileMenu_Import: "匯入...",
        //	fileMenu_Close: "Close",
        fileMenu_Discard: "回復到上一版",
        fileMenu_ClearTrackChange: "移除變更標示",
        fileMenu_SpreadsheetSettings: "設定文件語言環境...",
        filemenu_revisionhistory: "修訂",
        fileMenu_Save: "儲存",
        fileMenu_SaveAs: "複製...",
        fileMenu_AutoPublish: "自動發佈",
        fileMenu_AutoCheckIn: "自動移入",
        fileMenu_PublishVersion: "立即發佈",
        fileMenu_AutoPublish2: "自動儲存至儲存庫",
        //	fileMenu_AutoPublish_Tips: "Makes your changes available to readers at the end of each editing session.",
        fileMenu_PublishVersion2: "立即儲存至儲存庫",
        fileMenu_AutoPublish3: "自動儲存至${0}",
        fileMenu_PublishVersion3: "立即儲存至${0}",      
        fileMenu_SubmitForReview: "提交審核...",
        fileMenu_CheckinVersion: "移入...",
        fileMenu_Unlock: "解除鎖定",
        //	fileMenu_SaveAsDraft: "as Draft",
        //	fileMenu_SaveInMyDocs: "in My Documents",
        //	fileMenu_SaveToSymphony: "to Lotus Symphany",
        fileMenu_DownloadAs: "下載為",
        fileMenu_PDF: "PDF",
        fileMenu_ODF: "ODF",
        fileMenu_DOC: "Microsoft Word 97- 2007 (*.doc)",
        fileMenu_ODS: "ODS",
        fileMenu_XLS: "Microsoft Excel 97-2007 (*.xls) ",
        fileMenu_ShareWith: "共用...",
        fileMenu_ExportAsPDF: "PDF",
        fileMenu_ExportAsODF: "ODF",
        fileMenu_ExportAsPPT: "Microsoft Powerpoint 97- 2007 (*.ppt)",
        //	fileMenu_WebPreview: "Web Preview",
        fileMenu_PrintToPDF: "列印成 PDF...",
        fileMenu_ViewFileDetails: "檢視檔案詳細資訊...",
        fileMenu_RecentFile: "最近的檔案",
        fileMenu_Open: "開啟",
        fileMenu_Download: "下載",
        fileMenu_Print: "列印",
        fileMenu_Export: "匯出",
        fileMenu_ExportToCSV: "CSV",
        fileMenu_ExportToPDF: "PDF (.pdf)",
        fileMenu_ExportToMarkdown: "Markdown (.md)",
        fileMenu_ExportToMS: "Microsoft Office 格式 (.${FILEEXTENSION})",
        fileMenu_ExportToODF: "開放式文件格式 (.${FILEEXTENSION})",
        fileMenu_PgSetup: "頁面設定...",

        editMenu: "編輯",
        editMenu_Undo: "復原",
        editMenu_Redo: "重做",
        editMenu_Cut: "剪下",
        editMenu_Copy: "複製",
        editMenu_Paste: "貼上",
        editMenu_DeleteSlide: "刪除投影片",
        editMenu_SelectAll: "全選",
        editMenu_Find: "尋找...",
        editMenu_Replace: "取代...",
        editMenu_FindReplace: "尋找/取代...",
        editMenu_EditLink: "新增或編輯鏈結",
        editMenu_DeleteSheet: "刪除工作表...",
        editMenu_RenameSheet: "重新命名工作表...",
        editMenu_HideSheet: "隱藏工作表",
        editMenu_MoveSheet: "移動工作表...",
        editMenu_DeleteRow: "刪除列",
        editMenu_DeleteColumn: "刪除欄",
        editMenu_DeleteCellLeft: "刪除資料格並左移",
        editMenu_DeleteCellUp: "刪除資料格並上移",
        editMenu_ClearCell: "刪除內容",

        viewMenu: "檢視",
        viewMenu_Master: "主要",
        viewMenu_Notifications: "通知",
        viewMenu_SlideSorter: "投影片排序器",
        viewMenu_SpeakerNotes: "演講者備忘稿",
        viewMenu_Toolbar_Basic: "基本",
        viewMenu_Toolbar_Advanced: "進階",
        viewMenu_Toolbar_None: "無",
        viewMenu_Toolbar: "工具列",
        viewMenu_Statusbar: "狀態列",
        viewMenu_Navigator: "導覽器...",
        //viewMenu_Sidebar: "Sidebar",
        viewMenu_ShowHideIndicators: "顯示共同編輯指示器",
        viewMenu_Assignment: "指派指示器",
        viewMenu_Bookmark: "書籤",
        viewMenu_Coediting: "共同編輯強調顯示",
        viewMenu_Rulers: "尺規",
        viewMenu_WebLayout: "Web 佈置",
        viewMenu_AutomaticSpellCheck: "鍵入時進行拼字檢查",
        viewMenu_Formulabar: "公式列",
        viewMenu_moveRight: "按 Enter 鍵將游標右移",
        viewMenu_showFullString: "展開資料格中的內容",
        viewMenu_Doc: "檢視文件",
        viewMenu_Templates: "範本",
        viewMenu_GridLines: "隱藏格線",
        viewMenu_UnsupportWarning: "顯示不支援的功能訊息",
        viewMenu_HiddenSheets: "隱藏的工作表",
        viewMenu_FreezeRows: "凍結列",
        viewMenu_FreezeColumns: "凍結欄",
        viewMenu_NoFrozenRows: "無凍結的列",
        viewmenu_NoFrozenColumns: "無凍結的欄",
        viewMenu_FreezeXRows: "凍結 ${0} 列",
        viewMenu_FreezeOneRow: "凍結 ${0} 列",
        viewMenu_FreezeXColumns: "凍結 ${0} 欄",
        viewMenu_FreezeOneColumn: "凍結 ${0} 欄",
        viewMenu_CarriageReturn: "格式化標示",
        viewMenu_Navigation: "導覽窗格",
        viewMenu_ACL: "可編輯區域",
        viewMenu_GridOnOff: "格線",
        viewMenu_ObserverMode: '觀測器模式',

        createMenu: "插入",
        createMenu_NewSlide: "新建投影片",
        createMenu_DuplicateSlide: "複製投影片",
        createMenu_ImageFromFile: "影像...",
        createMenu_TextBox: "文字框",
        createMenu_Shape: "形狀",
        createMenu_break: "分頁",
        createMenu_RowAbove: "在上方插入列",
        createMenu_RowBelow: "在下方插入列",
        createMenu_ColumnRight: "欄右",
        createMenu_ColumnLeft: "欄左",
        createMenu_Sheet: "工作表...",
        createMenu_Image: "影像...",
        createMenu_Comments: "評論...",
        createMenu_WebLink: "Web 鏈結...",
        createMenu_SpecialCharacter: "特殊字元...",
        createMenu_Function: "函數...",
        createMenu_Fromtemplate: "從範本建立",

        insertMenu: "插入",
        insertMenu_break: "分頁",
        insertMenu_sectionbreak: "分節符號",
        insertMenu_Bookmark: "書籤...",
        insertMenu_WebLink: "鏈結...",
        insertMenu_SpecialCharacter: "特殊字元...",
        insertMenu_HorizontalLine: "水平線",
        insertMenu_Header: "頁首",
        insertMenu_Footer: "頁尾",
        insertMenu_TableOfContents: "目錄",

        insertMenu_HeaderFooter: "頁首/頁尾",
        insertMenu_HF_Edit: "編輯",
        insertMenu_HF_Hide: "隱藏",
        insertMenu_Endnotes: "尾註",
        insertMenu_RowAbove: "在上方插入列",
        insertMenu_PageNumber: "頁碼",
        insertMenu_PageNumberTop: "頁首",
        insertMenu_PageNumberBottom: "頁尾",
        insertMenu_PageNumberCurr: "現行位置",
        insertMenu_TotalPageNumber: "第 N 之 1 頁",
        insertMenu_Date: "日期...",
        insertMenu_Time: "時間...",
        insertMenu_Fields: "欄位",
        //    insertMenu_Comment: "Comment",
        insertMenu_CellRight: "資料格及右移",
        insertMenu_CellDown: "資料格及下移",
        insertMenu_RowBelow: "在下方插入列",
        insertMenu_ColumnBefore: "在前方插入欄",
        insertMenu_ColumnAfter: "在後方插入欄",
        insertMenu_Sheet: "工作表...",
        insertMenu_Image: "影像...",
        insertMenu_DuplicateSheet: "複製工作表",
        insertMenu_Function: "函數",
        insertMenu_FunctionSum: "SUM",
        insertMenu_FunctionAverage: "AVERAGE",
        insertMenu_FunctionCount: "COUNT",
        insertMenu_FunctionMax: "MAX",
        insertMenu_FunctionMin: "MIN",
        insertMenu_FunctionMore: "其他函數...",
        insertMenu_NameRange: "具名範圍",
        insertMenu_NameRangeNew: "新建範圍...",
        insertMenu_NameRangeManage: "管理範圍...",
        insertMenu_Chart: "圖表...",

        contextMenu_insertCellRight: "插入資料格並右移",
        contextMenu_insertCellDown: "插入資料格並下移",
        contextMenu_InsertRowAbove: "在上方插入列",
        contextMenu_InsertRowBelow: "在下方插入列",
        contextMenu_InsertColumnBefore: "在前方插入欄",
        contextMenu_InsertColumnAfter: "在後方插入欄",
        contextMenu_DownloadImage: "下載為影像",

        formatMenu: "格式",
        formatMenu_Columns: "欄",
        formatMenu_DefaultFormatting: "預設格式",
        formatMenu_Template: "樣式...",
        contextMenu_Template: "表格樣式...",
        formatMenu_LineSpacing: "行距",
        formatMenu_LineSpacing1: "1",
        formatMenu_LineSpacing12: "1.2",
        formatMenu_LineSpacing15: "1.5",
        formatMenu_LineSpacing2: "2",
        formatMenu_LineSpacing25: "2.5",
        formatMenu_LineSpacing3: "3",
        formatMenu_TextProperties: "文字內容",
        formatMenu_PageBreakBefore: "段落前分頁",
        formatMenu_KeepLines: "段落中不分頁",
        formatMenu_WidowControl: "遺留行/段落遺留字串控制項",
        formatMenu_Pagination: "段落內容",
        formatMenu_Bold: "粗體",
        formatMenu_Italic: "斜體",
        formatMenu_Underline: "底線",
        formatMenu_Strikethrough: "刪除線",
        formatMenu_IncreaseSize: "放大字型大小",
        formatMenu_DecreaseSize: "縮小字型大小",
        formatMenu_ImageProperties: "影像內容...",
        formatMenu_ChartProperties: "圖表內容...",
        formatMenu_EditChart: "編輯圖表",
        formatMenu_InsertChart: "插入圖表",
        formatMenu_Properties: "內容...",
        formatMenu_Heading: "標題",
        formatMenu_Normal: "一般",
        formatMenu_Title: "標題",
        formatMenu_Subtitle: "副標題",
        formatMenu_Heading1: "標題 1",
        formatMenu_Heading2: "標題 2",
        formatMenu_Heading3: "標題 3",
        formatMenu_Heading4: "標題 4",
        formatMenu_Heading5: "標題 5",
        formatMenu_Heading6: "標題 6",
        formatMenu_Heading7: "標題 7",
        formatMenu_Heading8: "標題 8",
        formatMenu_Heading9: "標題 9",
        formatMenu_BulletedList: "項目符號清單",
        formatMenu_NumberedList: "編號清單",
        formatMenu_OutLine: "多層清單",
        formatMenu_Superscript: "上標",
        formatMenu_Subscript: "下標",
        formatMenu_Align: "對齊",
        formatMenu_Left: "靠左",
        formatMenu_Right: "靠右",
        formatMenu_Center: "平行置中",
        formatMenu_Justify: "左右對齊",
        formatMenu_Text_Direction: "文字方向",
        formatMenu_Ltr: "從左到右",
        formatMenu_Rtl: "從右到左",
        formatMenu_LineSpacing: "行距",
        formatMenu_LineSpacing1: "1.0",
        formatMenu_LineSpacing115: "1.15",
        formatMenu_LineSpacing15: "1.5",
        formatMenu_LineSpacing2: "2.0",
        formatMenu_LineSpacing25: "2.5",
        formatMenu_LineSpacing3: "3.0",
        formatMenu_Top: "靠上",
        formatMenu_Bottom: "靠下",
        formatMenu_Middle: "垂直置中",
        formatMenu_Direction: "文字方向",
        formatMenu_Rtl: "從右到左",
        formatMenu_Ltr: "從左到右",
        formatMenu_Auto: "根據上下文",
        formatMenu_SheetDirection: "工作表方向",
        formatMenu_SheetRtl: "從右到左",
        formatMenu_SheetLtr: "從左到右",
        formatMenu_Indent: "增加縮排",
        formatMenu_DecreaseIndent: "減少縮排",
        formatMenu_ClearFormat: "清除格式化",
        formatMenu_RowHeight: "列高",
        formatMenu_ColumnWidth: "欄寬",
        formatMenu_ShowRow: "顯示列",
        formatMenu_HideRow: "隱藏列",
        formatMenu_ShowColumn: "顯示欄",
        formatMenu_HideColumn: "隱藏欄",
        formatMenu_WrapText: "文字換行",
        formatMenu_Number: "數字",
        formatMenu_FontArial: "Arial",
        formatMenu_FontComicSansMS: "Comic Sans MS",
        formatMenu_FontCourierNew: "新細明體",
        formatMenu_FontGeorgia: "Georgia",
        formatMenu_FontLucidaSansUnicode: "Lucida Sans Unicode",
        formatMenu_FontTahoma: "Tahoma",
        formatMenu_FontTimesNewRoman: "Times New Roman",
        formatMenu_FontTrebuchetMS: "Trebuchet MS",
        formatMenu_FontVerdana: "Verdana",
        formatMenu_FontName: "字型",

        layoutMenu: "佈置",
        layoutMenu_SlideLayout: "投影片版面配置...",
        layoutMenu_SlideDesign: "母片樣式...",
        layoutMenu_DefaultFormatting: "預設格式",
        layoutMenu_Textprop_Bold: "粗體",
        layoutMenu_Textprop_Italic: "斜體",
        layoutMenu_Textprop_Underline: "底線",
        layoutMenu_Textprop_Strikethrough: "刪除線",
        layoutMenu_TextProp: "文字內容",
        LayoutMenu_RowHeight: "列高...",
        LayoutMenu_ColumnWidth: "欄寬...",
        LayoutMenu_ShowRow: "顯示列",
        LayoutMenu_HideRow: "隱藏列",
        LayoutMenu_RenameSheet: "重新命名工作表...",
        LayoutMenu_MoveSheet: "移動工作表",

        tableMenu: "表格",
        tableMenu_Create: "建立...",
        tableMenu_CreateFromTemplate: "從範本建立",
        tableMenu_Delete: "刪除",
        tableMenu_SetTableColor: "彩色資料格",
        tableMenu_CreateTable: "建立表格",
        tableMenu_Cell: "資料格",
        tableMenu_CellMergeCells: "合併資料格",
        tableMenu_CellAlignLeft: "靠左對齊",
        tableMenu_CellAlignCenter: "置中對齊",
        tableMenu_CellAlignRight: "靠右對齊",
        tableMenu_CellClearContents: "清除內容",
        tableMenu_CellProperties: "資料格內容...",
        tableMenu_Row: "列",
        tableMenu_InsertRowAbove: "在上方插入列",
        tableMenu_InsertRowBelow: "在下方插入列",
        tableMenu_MoveRowAbove: "將列上移",
        tableMenu_MoveRowBelow: "將列下移",
        tableMenu_RowInsertRow: "插入列...",
        tableMenu_RowInsertRowAbove: "在上方插入列",
        tableMenu_RowInsertRowBelow: "在下方插入列",
        tableMenu_RowMoveRowAbove: "將列移至上方",
        tableMenu_RowMoveRowBelow: "將列移至下方",
        tableMenu_RowDelete: "刪除",
        tableMenu_RowRepeat: "重複標題列",
        tableMenu_InsertColumnBefore: "在前方插入欄",
        tableMenu_InsertColumnAfter: "在後方插入欄",
        tableMenu_MoveColumnBefore: "左移欄",
        tableMenu_MoveColumnAfter: "右移欄",
        tableMenu_ResizeColumn: "調整欄大小",
        tableMenu_ResizeColumns: "調整欄大小",
        tableMenu_MarkasCategory: "標示為種類",
        tableMenu_ColumnInsertColumn: "插入欄...",
        tableMenu_ColumnAddColumnBefore: "在前方插入欄",
        tableMenu_ColumnAddColumnAfter: "在後方插入欄",
        tableMenu_ColumnMoveColumnAfter: "將欄移至後方",
        tableMenu_ColumnMoveColumnBefore: "將欄移至前方",
        tableMenu_ColumnDelete: "刪除",
        tableMenu_ColumnSortAscending: "遞增排序",
        tableMenu_ColumnSortDescending: "遞減排序",
        tableMenu_Column: "欄",
        tableMenu_Style: "樣式",
        tableMenu_TableProperties: "表格內容...",

        teamMenu: "團隊",
        teamMenu_AddComment: "新增評論",
        teamMenu_AssignCells: "指派資料格",
        teamMenu_AssignSection: "指派區段",
        teamMenu_EditAssignment: "編輯指派",
        teamMenu_MarkSectionComplete: "將區段標示為完成",
        teamMenu_MarkAssignmentComplete: "將指派標示為完成",
        teamMenu_WorkPrivatelyOnSection: "單獨使用區段",
        teamMenu_CancelPrivateWork: "取消單獨工作",
        teamMenu_ApproveSection: "核准區段",
        teamMenu_ApproveAssignment: "核准指派",
        teamMenu_ReturnSectionForRework: "退回區段重做",
        teamMenu_ReturnAssignmentForRework: "退回指派重做",
        teamMenu_RemoveSectionAssignment: "移除區段指派",
        teamMenu_RemoveCellAssignment: "移除資料格指派",
        teamMenu_RemoveCompletedAssignments: "移除已完成的指派",
        teamMenu_AboutThisSection: "關於此區段",
        teamMenu_AboutAssignment: "關於這項指派",

        presentationMenu: "簡報",
        presentationMenu_SlideShow: "播放投影片",
        presentationMenu_SlideShowWithCoview: "播放共用的投影片...",
        presentationMenu_SlideTransitions: "套用投影片切換...",
        presentationMenu_SlideShowFromCurrent: "從目前的投影片開始播放",
        presentationMenu_EmptyCoviewInvites: "無作用中共用的投影片放映",
        presentationMenu_CoviewInvites: "作用中共用的投影片放映",

        dataMenu: "資料",
        dataMenu_Sort: "排序...",
        dataMenu_SortAsc: "遞增排序",
        dataMenu_SortDesc: "遞減排序",
        dataMenu_ACL: "受保護區域",
        dataMenu_ACL_DELETE: "刪除所有許可權",
        dataMenu_Validity: "有效性",
        dataMenu_InstantFilter: "即時過濾器",
        dataMenu_Validation: "驗證...",

        toolsMenu: "工具",
        toolsMenu_AutoComplete: "自動完成資料格輸入",
        toolsMenu_SelectDictionary: "拼字檢查字典",
        toolsMenu_Dictionary_ca_CT: "加泰蘭文",
        toolsMenu_Dictionary_cs_CZ: "捷克文（捷克）",
        toolsMenu_Dictionary_da_DK: "丹麥文（丹麥）",
        toolsMenu_Dictionary_nl_NL: "荷蘭文（荷蘭）",
        toolsMenu_Dictionary_en_AU: "英文（澳洲）",
        toolsMenu_Dictionary_en_GB: "英文（英國）",
        toolsMenu_Dictionary_en_US: "英文（美國）",
        toolsMenu_Dictionary_fi_FI: "芬蘭文（芬蘭）",
        toolsMenu_Dictionary_fr_FR: "法文（法國）",
        toolsMenu_Dictionary_fr_CA: "法文（加拿大）",
        toolsMenu_Dictionary_de_DE: "德文（德國）",
        toolsMenu_Dictionary_de_CH: "德文（瑞士）",
        toolsMenu_Dictionary_el_GR: "希臘文（希臘）",
        toolsMenu_Dictionary_it_IT: "義大利文（義大利）",
        toolsMenu_Dictionary_pl_PL: "波蘭文（波蘭）",
        toolsMenu_Dictionary_pt_BR: "葡萄牙文（巴西）",
        toolsMenu_Dictionary_pt_PT: "葡萄牙文（葡萄牙）",
        toolsMenu_Dictionary_ru_RU: "俄文（俄羅斯）",
        toolsMenu_Dictionary_es_ES: "西班牙文（西班牙）",
        toolsMenu_Dictionary_sv_SE: "瑞典文（瑞典）",
        toolsMenu_Dictionary_nb_NO: "挪威文（巴克摩）",
        toolsMenu_Dictionary_nn_NO: "挪威文（新挪威文）",
        toolsMenu_Dictionary_he_IL: "希伯來文（以色列）",
        toolsMenu_SpellCheck: "執行手動拼字檢查...",
        toolsMenu_Preferences: "喜好設定",
        toolsMenu_Task: "作業",
        toolsMenu_Task_Assigntask: "指派作業",
        teamMenu_AssignSlide: "指派投影片",
        teamMenu_AssignSlides: "指派投影片",
        teamMenu_EditSlide: "編輯投影片指派",
        teamMenu_ReopenSlideAssignment: "重新開啟投影片指派",
        teamMenu_ReopenSlideAssignments: "重新開啟投影片指派",
        teamMenu_ReassignSlide: "重新指派投影片",
        teamMenu_ReassignSlides: "重新指派投影片",
        teamMenu_MarkSlidesComplete: "將投影片標示為完成",
        teamMenu_MarkSlidesCompletes: "將投影片標示為完成",
        teamMenu_ApproveSlide: "核准投影片",
        teamMenu_ApproveSlides: "核准投影片",
        teamMenu_ReturnForRework: "退回投影片重做",
        teamMenu_ReturnForReworks: "退回投影片重做",
        teamMenu_RemoveAssignment: "移除投影片指派",
        teamMenu_AboutThisSlide: "關於此投影片",

        addOnsMenu: "附加程式",

        helpMenu: "說明",
        helpMenu_About: "關於",
        helpMenu_Overview: "說明內容",
        helpMenu_NewFeatures: "新增功能",
        helpMenu_Tour: "引導導覽",

        accel_fileMenu_Save: "Ctrl+S",
        accel_fileMenu_Save_Mac: "\u2318S",
        accel_fileMenu_Print: "Ctrl+P",
        accel_fileMenu_Print_Mac: "\u2318P",
        accel_editMenu_SelectAll: "Ctrl+A",
        accel_editMenu_SelectAll_Mac: "\u2318A",
        accel_editMenu_Undo: "Ctrl+Z",
        accel_editMenu_Undo_Mac: "\u2318Z",
        accel_editMenu_Redo: "Ctrl+Y",
        accel_editMenu_Redo_Mac: "\u2318Y",
        accel_editMenu_Cut: "Ctrl+X",
        accel_editMenu_Cut_Mac: "\u2318X",
        accel_editMenu_Copy: "Ctrl+C",
        accel_editMenu_Copy_Mac: "\u2318C",
        accel_editMenu_Paste: "Ctrl+V",
        accel_editMenu_Paste_Mac: "\u2318V",
        accel_editMenu_Find: "Ctrl+F",
        accel_editMenu_Find_Mac: "\u2318F",
        accel_insertMenu_Link: "Ctrl+K",
        accel_insertMenu_Link_Mac: "\u2318K",
        accel_insertMenu_Header: "CTRL+SHIFT+H",
        accel_insertMenu_Header_Mac: "\u21e7\u2318H",
        accel_insertMenu_Footer: "CTRL+SHIFT+F",
        accel_insertMenu_Footer_Mac: "\u21e7\u2318F",
        accel_formatMenu_Textprop_Bold: "Ctrl+B",
        accel_formatMenu_Textprop_Bold_Mac: "\u2318B",
        accel_formatMenu_Textprop_Italic: "Ctrl+I",
        accel_formatMenu_Textprop_Italic_Mac: "\u2318I",
        accel_formatMenu_Textprop_FormatPainter: "Ctrl+SHIFT+C, Ctrl+SHIFT+V",
        accel_formatMenu_Textprop_FormatPainter_Mac: "\u21e7\u2318C, \u21e7\u2318V",
        accel_formatMenu_Textprop_Underline: "Ctrl+U",
        accel_formatMenu_Textprop_Underline_Mac: "\u2318U",
        accel_formatMenu_Headingprop_P: "CTRL+SHIFT+0",
        accel_formatMenu_Headingprop_H1: "CTRL+SHIFT+1",
        accel_formatMenu_Headingprop_H2: "CTRL+SHIFT+2",
        accel_formatMenu_Headingprop_H3: "CTRL+SHIFT+3",
        accel_formatMenu_Headingprop_H4: "CTRL+SHIFT+4",
        accel_formatMenu_Headingprop_H5: "CTRL+SHIFT+5",
        accel_formatMenu_Headingprop_H6: "CTRL+SHIFT+6",
        accel_formatMenu_Superscript: "Ctrl+.",
        accel_formatMenu_Superscript_Mac: "\u2318.",
        accel_formatMenu_Subscript: "Ctrl+,",
        accel_formatMenu_Subscript_Mac: "\u2318,",
        accel_formatMenu_Left: "CTRL+SHIFT+L",
        accel_formatMenu_Left_Mac: "\u21e7\u2318L",
        accel_formatMenu_Right: "CTRL+SHIFT+R",
        accel_formatMenu_Right_Mac: "\u21e7\u2318R",
        accel_formatMenu_Center: "CTRL+SHIFT+E",
        accel_formatMenu_Center_Mac: "\u21e7\u2318E",
        accel_formatMenu_Justify: "CTRL+SHIFT+J",
        accel_formatMenu_Justify_Mac: "\u21e7\u2318J",
        accel_formatMenu_Indent: "CTRL+M",
        accel_formatMenu_Indent_Mac: "\u2318M",
        accel_formatMenu_DecreaseIndent: "CTRL+SHIFT+M",
        accel_formatMenu_DecreaseIndent_Mac: "\u21e7\u2318M",
        accel_teamMenu_AddComment: "SHIFT+F2",

        ctxMenuSmartTable: '表格',
        ctxMenuTableProperties: "表格內容",
        ctxMenuDeleteST: '刪除',
        ctxMenuDeleteSTTable: '刪除表格',
        ctxMenuChgSTStyle: '變更樣式',
        ctxMenuShowCaption: '顯示標題',
        ctxMenuHideCaption: '隱藏標題',
        ctxMenuResizeST: '調整大小',
        ctxMenuResizeColumnsST: '調整欄大小',
        ctxMenuSTRow: '列',
        ctxMenuAddSTRowAbv: '在上方插入列',
        ctxMenuAddSTRowBlw: '在下方插入列',
        ctxMenuMoveSTRowUp: '將列移至上方',
        ctxMenuMoveSTRowDown: '將列移至下方',
        ctxMenuDelSTRow: '刪除',
        ctxMenuRepeatRow: '重複標題列',
        ctxMenuSTCol: '欄',
        ctxMenuAddSTColBfr: '在前方插入欄',
        ctxMenuAddSTColAft: '在後方插入欄',
        ctxMenuMoveSTColBefore: '將欄移至前方',
        ctxMenuMoveSTColAfter: '將欄移至後方',
        ctxMenuDelSTCol: '刪除',
        ctxMenuSortSTColAsc: '遞增排序',
        ctxMenuSortSTColDesc: '遞減排序',
        ctxMenuShowAllFacets: '顯示種類',
        ctxMenuHideAllFacets: '隱藏種類',
        ctxMenuSTCell: '資料格',
        ctxMenuMergeCells: '合併資料格',
        ctxMenuMergeDown: '與下方資料格合併',
        ctxMenuVerSplit: '垂直分割',
        ctxMenuHorSplit: '水平分割',
        ctxMenuSplitCells: '分割資料格...',
        splitCells: '分割資料格',
        ctxMenuAlignTextLeft: '靠左對齊',
        ctxMenuAlignTextCenter: '置中對齊',
        ctxMenuAlignTextRight: '靠右對齊',
        ctxMenuClearSTCellContent: '清除內容',
        ctxMenuMakeHeaderRow: '以選取的列為標題',
        ctxMenuMakeNonHeaderRow: '移除標題樣式',
        ctxMenuMakeHeaderCol: '以選取的欄為標題',
        ctxMenuMakeNonHeaderCol: '移除標題樣式',
        SHEET_CONTEXT_Hide: "隱藏", // hide row, column or sheet
        SHEET_CONTEXT_Show: "顯示", // show row, column
        SHEET_CONTEXT_MoveSheet: "移動...", // move sheet
        SHEET_CONTEXT_InsertSheet: "插入...", // insert sheet
        SHEET_CONTEXT_DeleteSheet: "刪除...", // delete sheet	
        SHEET_CONTEXT_DuplicateSheet: "複製...", // duplicate sheet
        SHEET_CONTEXT_RenameSheet: "重新命名...", // rename sheet
	
        ctxMenu_Image_WrapText: "文字換行",
        ctxMenu_Image_WrapText_Inline: "文字內置",
        ctxMenu_Image_WrapText_Square: "方形",
        ctxMenu_Image_WrapText_TopBottom: "由上至下",
        ctxMenu_Image_WrapText_Behind: "文字在前",
        ctxMenu_Image_WrapText_InFront: "文字在後",
        ctxMenu_Image_WrapText_Other: "自動換列",
        ctxMenu_Image_WrapText_BothSides: "兩側",
        ctxMenu_Image_WrapText_LeftOnly: "僅左側",
        ctxMenu_Image_WrapText_RightOnly: "僅右側",
        ctxMenu_Image_WrapText_LargestOnly: "僅最大者",

        ctxMenu_Shape_AddText: "新增文字",

        ctxMenu_Range_ACL: "保護範圍",
        ctxMenu_Sheet_ACL: "保護工作表",

        ctxMenu_HeaderFooter: "頁首/頁尾",
        ctxMenu_HeaderFooter_DiffFirst: "僅第一頁",
        ctxMenu_HeaderFooter_DiffOddEven: "奇數頁與偶數頁不同",
        ctxMenu_HeaderFooter_LinkToPre: "鏈結到前一個",

        ctxMenu_copy: "複製",
        ctxMenu_paste: "貼上",
        ctxMenu_delete: "刪除",
        ctxMenu_cut: "剪下",
        ctxMenu_select: "選取",
        ctxMenu_properties: "內容",
        ctxMenu_bringToFront: "帶至前面",
        ctxMenu_sendToBack: "移至後面",
        ctxMenu_arrange: "排列",
        ctxMenu_sendBackward: "後移",
        ctxMenu_sendForward: "前移",
        ctxMenu_fontStyle: "字型樣式",
        ctxMenu_selectStyle: "選取樣式",
        ctxMenu_fontSize: "字型大小",
        ctxMenu_fontFamily: "字型系列",
        ctxMenu_bold: "粗體",
        ctxMenu_italic: "斜體",
        ctxMenu_u: "底線",
        ctxMenu_strike: "刪除線",
        ctxMenu_super: "上標",
        ctxMenu_sub: "下標",
        ctxMenu_color: "顏色",
        ctxMenu_bgcolor: "背景顏色",
        ctxMenu_highcolor: "強調顯示顏色",
        ctxMenu_restart: "重新編號",
        ctxMenu_continue: "繼續編號",
        ctxMenu_separate: "分離清單",
        ctxMenu_join: "結合前一份清單",
        ctxMenu_setNumberVal: "設定編號值...",
        webClipboardInfoTitle: "剪貼簿",
        webClipboardInfoOKBtn: "確定",
        webClipboardInfoCutMsg: "您的瀏覽器安全性設定會阻止自動複製。 請改用鍵盤上的 Ctrl+X 鍵。",
        webClipboardInfoCopyMsg: "您的瀏覽器安全性設定會阻止自動複製。 請改用鍵盤上的 Ctrl+C 鍵。",
        webClipboardInfoPasteMsg: "您的瀏覽器安全性設定會阻止此編輯器存取您的剪貼簿資料。 請改用鍵盤上的 Ctrl+V 鍵。",

        clearTrackChangeConfirmMsg: "此文件中所有用於標示變更的顏色代碼將會永久移除。 要繼續嗎？"
});

