/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
	fileMenu: "檔案",
	fileMenu_New: "新建",
	fileMenu_NewDocument: "文件",
	fileMenu_NewDocumentfromTemplate: "來自範本的文件",
	fileMenu_NewPresentation: "簡報",
	fileMenu_NewPresentationfromTemplate: "來自範本的簡報",
	fileMenu_NewSpreadsheet: "試算表",
	fileMenu_Open: "開啟",
//	fileMenu_Close: "Close",
	fileMenu_Discard: "捨棄",
	fileMenu_Save: "儲存",
//	fileMenu_SaveAs: "Save As...",
//	fileMenu_SaveAsDraft: "as Draft",
//	fileMenu_SaveInMyDocs: "in My Documents",
//	fileMenu_SaveToSymphony: "to Lotus Symphany",
	fileMenu_ShareWith: "分享對象...",
	fileMenu_ExportAsPDF: "匯出為 PDF",
	fileMenu_WebPreview: "Web 預覽",
	fileMenu_PrintPreview: "預覽列印",
	fileMenu_RecentFile: "最近的檔案",
	fileMenu_Print: "列印...",
	editMenu: "編輯",
	editMenu_Undo: "復原",
	editMenu_Redo: "重做",
	editMenu_Cut: "剪下",
	editMenu_Copy: "複製",
	editMenu_Paste: "貼上",
	editMenu_DeleteSlide:"刪除投影片",
	editMenu_SelectAll: "全選",
	editMenu_Find: "尋找...",
	editMenu_Replace: "取代...",
	editMenu_DeleteSheet: "刪除工作表",
	editMenu_DuplicateSheet: "複製工作表",
	editMenu_DeleteRow: "刪除列",
	editMenu_DeleteColumn: "刪除欄",
	editMenu_ClearCell: "清除資料格",
	viewMenu: "檢視",
	viewMenu_Master: "主要",
	viewMenu_Notifications: "通知",
	viewMenu_ShowHideIndicators: "顯示/隱藏共同編輯指示器",
	viewMenu_SlideSorter: "顯示投影片排序器",
	viewMenu_SpeakerNotes: "顯示主講人備忘稿",
	viewMenu_NextSlide: "下一張投影片",
	viewMenu_PrevSlide: "上一張投影片",
	createMenu: "建立",
	createMenu_NewSlide: "新建投影片",
	createMenu_DuplicateSlide: "複製投影片",
	createMenu_ImageFromFile: "圖形來源檔案",
	createMenu_TextBox: "文字框",
	createMenu_Task: "作業",
    formatMenu_Text_Direction: "文字方向",
    formatMenu_Ltr: "從左到右",
    formatMenu_Rtl: "從右到左",  	
    formatMenu_Horizontal_Align: "水平對齊",
    formatMenu_Vertical_Align: "垂直對齊",
    formatMenu_Align_Top: "靠上",
    formatMenu_Align_Middle: "置中",
    formatMenu_Align_Bottom: "靠下",
	layoutMenu: "佈置",
	layoutMenu_SlideLayout: "投影片佈置",
	layoutMenu_SlideDesign: "母片樣式",
	tableMenu: "表格",
	tableMenu_CreateTable: "建立表格",
	tableMenu_Cell: "資料格",
	tableMenu_CellAlignLeft: "靠左對齊文字",
	tableMenu_CellAlignCenter: "置中對齊文字",
	tableMenu_CellAlignRight: "靠右對齊文字",
	tableMenu_CellClearContents: "清除內容",
	tableMenu_Row: "列",
	tableMenu_RowAddRowAbove: "在上方新增列",
	tableMenu_RowAddRowBelow: "在下方新增列",
	tableMenu_RowMoveRowAbove: "將列移至上方",
	tableMenu_RowMoveRowBelow: "將列移至下方",
	tableMenu_RowDelete: "刪除",
	tableMenu_ColumnAddColumnBefore: "在前新增一欄",
	tableMenu_ColumnAddColumnAfter: "在後新增一欄",
	tableMenu_ColumnMoveColumnAfter: "將欄移至後方",
	tableMenu_ColumnMoveColumnBefore: "將欄移至前方",
	tableMenu_ColumnDelete: "刪除",
	tableMenu_ColumnSortAscending: "遞增排序",
	tableMenu_ColumnSortDescending: "遞減排序",
	tableMenu_Column: "欄",
	tableMenu_Delete: "刪除",
	presentationMenu: "簡報",
	presentationMenu_SlideShow: "播放投影片",
	presentationMenu_SlideShowFromCurrent: "從目前的投影片開始播放",
	toolsMenu: "工具",
	toolsMenu_Task: "作業",
	helpMenu: "說明",
	helpMenu_Overview: "說明內容"
})

