({
	ORIENTATION_LABEL: "Orientation",
	PORTRAIT: "Portrait",
	LANDSCAPE: "Landscape",
	PAGE_LABEL: "Page order",
	PAGE_TYPE1: "Top to bottom, then right",
	PAGE_TYPE2: "Left to right, then down",
	DISPLAY_OPTION_LABEL: "Display options",
	HEADER: "Header",
	FOOTER: "Footer",
	GRIDLINE: "Grid lines",
	TAGGED_PDF: "Tagged PDF",
	MARGINS_LABEL: "Margins",
	TOP: "Top:",
	TOP_DESC:"Top margin, in centimeters",
	TOP_DESC2:"Top margin, in inches",
	BOTTOM: "Bottom:",
	BOTTOM_DESC:"Bottom margin, in centimeters",
	BOTTOM_DESC2:"Bottom margin, in inches",	
	LEFT: "Left:",
	LEFT_DESC:"Left margin, in centimeters",
	LEFT_DESC2:"Left margin, in inches",	
	RIGHT: "Right:",
	RIGHT_DESC:"Right margin, in centimeters",
	RIGHT_DESC2:"Right margin, in inches",	
	PAPER_FORMAT_LABEL: "Paper format",
	PAPER_SIZE_LABEL: "Paper size:",
	HEIGHT: "Height:",
	HEIGHT_DESC:"Paper height, in centimeters",
	HEIGHT_DESC2:"Paper height, in inches",		
	WIDTH: "Width:",
	WIDTH_DESC:"Paper width, in centimeters",
	WIDTH_DESC2:"Paper width, in inches",
	
	INVALID_MSG: "The input is invalid and has been rectified automatically. Try another value if you want a different result.",
	
	TOOLTIP1:"Prints as many rows as the paper is long, moving across until there are no more columns in the sheet, then moves down and left to print the next group of rows.",
	TOOLTIP2:"Prints as many columns as the paper is wide, moving down until there are no more rows in the sheet, then moves up and right to print the next group of columns.",
	CM_LABEL: "cm",
	LETTER: "Letter",
	LEGAL: "Legal",
	TABLOID: "Tabloid",
	USER: "User",
	SIZE1: "Env. #6 3/4",
	SIZE2: "Env. Monarch",
	SIZE3: "Env. #9",
	SIZE4: "Env. #10",
	SIZE5: "Env. #11",
	SIZE6: "Env. #12",
	SIZE7: "16 kai",
	SIZE8: "32 kai",
	SIZE9: "32 kai large"
})
	