({
	ORIENTATION_LABEL: "Orientare",
	PORTRAIT: "Portret",
	LANDSCAPE: "Peisaj",
	PAGE_LABEL: "Ordine pagină",
	PAGE_TYPE1: "De sus în jos, apoi la dreapta",
	PAGE_TYPE2: "De la stânga la dreapta, apoi în jos",
	DISPLAY_OPTION_LABEL: "Opţiuni de afişare",
	HEADER: "Antet",
	FOOTER: "Subsol",
	GRIDLINE: "Linii de grilă",
	TAGGED_PDF: "PDF cu taguri",
	MARGINS_LABEL: "Margini",
	TOP: "Sus:",
	TOP_DESC:"Margine sus, în centimetri",
	TOP_DESC2:"Margine sus, în inch",
	BOTTOM: "Jos:",
	BOTTOM_DESC:"Margine jos, în centimetri",
	BOTTOM_DESC2:"Margine jos, în inch",	
	LEFT: "Stânga:",
	LEFT_DESC:"Margine stânga, în centimetri",
	LEFT_DESC2:"Margine stânga, în inch",	
	RIGHT: "Dreapta:",
	RIGHT_DESC:"Margine dreapta, în centimetri",
	RIGHT_DESC2:"Margine dreapta, în inch",	
	PAPER_FORMAT_LABEL: "Format hârtie",
	PAPER_SIZE_LABEL: "Dimensiune hârtie:",
	HEIGHT: "Înălţime:",
	HEIGHT_DESC:"Înălţime hârtie, în centimetri",
	HEIGHT_DESC2:"Înălţime hârtie, în inch",		
	WIDTH: "Lăţime:",
	WIDTH_DESC:"Lăţime hârtie, în centimetri",
	WIDTH_DESC2:"Lăţime hârtie, în inch",
	
	INVALID_MSG: "Intrarea este invalidă şi a fost rectificată automat. Încercaţi altă valoare dacă vreţi un rezultat diferit.",
	
	TOOLTIP1:"Tipăreşte atâtea rânduri cât este hârtia de lungă, mutându-se până când nu mai există coloane în foaie, apoi se mută în jos şi la stânga pentru a tipări următorul grup de rânduri.",
	TOOLTIP2:"Tipăreşte atâtea coloane pe cât este hârtia de lată, mutându-se în jos până când nu mai există rânduri în foaie, apoi se mută în sus şi la dreapta pentru a tipări următorul grup de coloane.",
	CM_LABEL: "cm",
	LETTER: "Scrisoare",
	LEGAL: "Legal",
	TABLOID: "Tabloid",
	USER: "Utilizator",
	SIZE1: "Env. #6 3/4",
	SIZE2: "Env. Monarch",
	SIZE3: "Env. #9",
	SIZE4: "Env. #10",
	SIZE5: "Env. #11",
	SIZE6: "Env. #12",
	SIZE7: "16 kai",
	SIZE8: "32 kai",
	SIZE9: "32 kai large"
})
	
