({
	ORIENTATION_LABEL: "Orientasi",
	PORTRAIT: "Potret",
	LANDSCAPE: "Lanskap",
	PAGE_LABEL: "Urutan halaman",
	PAGE_TYPE1: "Atas ke bawah, kemudian kanan",
	PAGE_TYPE2: "Kiri ke kanan, kemudian ke bawah",
	DISPLAY_OPTION_LABEL: "Pilihan tampilan",
	HEADER: "Header",
	FOOTER: "Footer",
	GRIDLINE: "Garis kisi",
	TAGGED_PDF: "PDF Ditandai",
	MARGINS_LABEL: "Margin",
	TOP: "Atas:",
	TOP_DESC:"Margin atas, dalam centimeter",
	TOP_DESC2:"Margin atas, dalam inci",
	BOTTOM: "Bawah:",
	BOTTOM_DESC:"Margin bawah, dalam centimeter",
	BOTTOM_DESC2:"Margin bawah, dalam inci",	
	LEFT: "Kiri:",
	LEFT_DESC:"Margin kiri, dalam centimeter",
	LEFT_DESC2:"Margin kiri, dalam inci",	
	RIGHT: "Kanan:",
	RIGHT_DESC:"Margin kanan, dalam centimeter",
	RIGHT_DESC2:"Margin kanan, dalam inci",	
	PAPER_FORMAT_LABEL: "Format kertas",
	PAPER_SIZE_LABEL: "Ukuran kertas:",
	HEIGHT: "Tinggi:",
	HEIGHT_DESC:"Tinggi kertas, dalam centimeter",
	HEIGHT_DESC2:"Tinggi kertas, dalam inci",		
	WIDTH: "Lebar:",
	WIDTH_DESC:"Lebar kertas, dalam centimeter",
	WIDTH_DESC2:"Lebar kertas, dalam inci",
	
	INVALID_MSG: "Input tidak valid dan telah diperbaiki secara otomatis. Coba nilai lain jika Anda menginginkan hasil yang berbeda.",
	
	TOOLTIP1:"Cetak baris sebanyak mungkin sepanjang kertas, lanjutkan terus ke samping hingga tidak lagi tersisa kolom dalam lembar, kemudian pindah ke bawah dan kiri untuk mencetak kelompok baris yang lain.",
	TOOLTIP2:"Cetak kolom sebanyak mungkin selebar kertas, lanjutkan terus ke bawah hingga tidak lagi tersisa baris dalam lembar, kemudian pindah ke atas dan kanan untuk mencetak kelompok kolom yang lain.",
	CM_LABEL: "cm",
	LETTER: "Letter",
	LEGAL: "Legal",
	TABLOID: "Tabloid",
	USER: "Pengguna",
	SIZE1: "Env. #6 3/4",
	SIZE2: "Env. Monarch",
	SIZE3: "Env. #9",
	SIZE4: "Env. #10",
	SIZE5: "Env. #11",
	SIZE6: "Env. #12",
	SIZE7: "16 kai",
	SIZE8: "32 kai",
	SIZE9: "32 kai besar"
})
	
