({
	COLUMN: "Spalte",
	CLUSTERED_COLUMN: "Spaltengruppe",
	STACKED_COLUMN: "Gestapelte Spalte",
	BAR:"Balken",
	CLUSTERED_BAR:"Balkengruppe",
	STACKED_BAR: "Gestapelter Balken",
	PIE:"Kreis",
	SLICE: "Ausschnitt",
	AREA: "Bereich",
	STACKED_AREA: "Gestapelter Bereich",
	LINE: "Linie",
	STACKED_LINE: "Gestapelte Linie",
	MAKER_LINE: "Linie mit Markierungen",
	STACKED_MARKER_LINE: "Gestapelte Linie mit Markierungen",
	SCATTER: "Streuung",
	SCATTER_MARKER_ONLY: "Punkte nur mit Markierungen",
	SCATTER_MARKER_LINE_S: "Punkte mit glatten Linien und Markierungen",
	SCATTER_LINE_S: "Punkte mit glatten Linien", 
	SCATTER_MARKER_LINE_X: "Punkte mit geraden Linien und Markierungen",
	SCATTER_LINE_X: "Punkte mit geraden Linien",
	ERROR_INVALID_RANGE:"Ungültiger Datenbereich",
	TOO_MANY_POINTS: "Es kann kein Diagramm mit mehr als ${0} Datenpunkten erstellt werden",
	CHART_TYPES:"Diagrammtypen",
	DATA:"Daten",
	DATA_RANGE:"Datenbereich",
	IN_ROWS:"Datenserien in Zeilen",
	IN_COLUMNS:"Datenserien in Spalten",
	AUTO:"Automatisch"
})
