({
	alt			: "Alternativer Text:",
	width		: "Breite:",
	height		: "Höhe:",
	cmUnit   : "cm",
	ptUnit 	 : "pt",
	inchUnit : "Zoll",
	inUnit   : "in",
	mmUnit 	 : "mm",
	
	inputWarning: "Geben Sie eine positive Zahl mit der Standardeinheit ein. ",
	
	properties: "Eigenschaften",
	data: "Daten",
	chart: "Diagramm",
	axis: "Achse",
	series: "Serie",
	font: "Schriftart",
	title: "Titel",
	legend: "Legende",
	placement: "Position",
	background: "Hintergrund",
	plotarea: "Zeichenbereich",
	line : "Linie",
	fill: "Füllung",
	border : "Rahmen",
	labelfont: "Bezeichnung",
	scale: "Maßstab",
	minimum: "Minimum",
	maximum: "Maximum",
	majorunit: "Übergeordnete Einheit",
	minorunit: "Untergeordnete Einheit",
	smooth: "Reibungslos",
	marker: "Markierungen",
	markerfill: "Markierung",
	enterTitle: "Titel hier eingeben",
	inputNumberWarning: "Geben Sie eine Zahl ein.",
	inputPosNumberWarning: "Geben Sie eine positive Zahl ein.",
	maxMinWarning: "Der Maximalwert muss größer sein als der Mindestwert",
	selectFontName: "Schriftartnamen wählen",
	selectFontSize: "Schriftgrad wählen",
	setBold: "Fett",
	setItalic: "Kursiv",
	setFontColor: "Schriftfarbe festlegen",
	setLegendPos: "Legendenplatzierung festlegen",
	setBackColor: "Hintergrundfarbe des Diagramms festlegen",
	setBorderWidth: "Rahmenbreite festlegen",
	setBorderColor: "Rahmenfarbe festlegen",
	setPlotAreaColor: "Farbe des Zeichenbereichs festlegen",
	selectAxis: "Achse auswählen",
	setLineWidth: "Linienstärke festlegen",
	setLineColor: "Linienfarbe festlegen",
	selectSeries: "Serie auswählen",
	setFillColor: "Füllfarbe festlegen",
	setMarker: "Markierungen festlegen",
	setSmooth: "Glatte Linien festlegen",
	chartTitle: "Diagrammtitel",
	axisTitle: "Achsentitel",
	
	ERR1: "Ein Array muss von geschweiften Klammern eingeschlossen sein.",
	ERR3: "Die Zeichenfolgeelemente müssen von Anführungszeichen eingeschlossen sein.",
	ERR4: "Nur einen Bereich eingeben.",
	ERR5: "Der Bereich muss existieren.",
	ERR6: "Alle Bereiche müssen in demselben Arbeitsblatt liegen.",
	ERR7: "Alle Bereiche müssen für eine einzelne Zeile oder Spalte gelten.",
	ERR9: "Ein Serienwert ist erforderlich.",
	
	n	: "Keine Angabe",
	l	: "Links",
	r	: "Rechts",
	t	: "Oben",
	b   : "Unten",
	
	dataSeries:"Datenserie",
	label:"Serienname",
	xVal:"X-Wert von Serien",
	yVal:"Y-Wert von Serien",
	val:"Serienwerte",
	cat:"Kategorie",
		
	ltr: "Links nach Rechts",
	rtl: "Rechts nach Links",
	auto: "Kontextbezogen",
	bidi_dir: "Richtung",
	bidi_text_dir: "Textausrichtung"
})
