({
	ORIENTATION_LABEL: "Orientacja",
	PORTRAIT: "Pionowo",
	LANDSCAPE: "Poziomo",
	PAGE_LABEL: "Kolejność stron",
	PAGE_TYPE1: "Od góry do dołu, następnie w prawo",
	PAGE_TYPE2: "Od lewej do prawej, następnie w dół",
	DISPLAY_OPTION_LABEL: "Opcje wyświetlania",
	HEADER: "Nagłówek",
	FOOTER: "Stopka",
	GRIDLINE: "Linie siatki",
	MARGINS_LABEL: "Marginesy",
	TOP: "U góry:",
	BOTTOM: "U dołu:",
	LEFT: "Z lewej:",
	RIGHT: "Z prawej:",
	PAPER_FORMAT_LABEL: "Format papieru",
	PAPER_SIZE_LABEL: "Wielkość papieru:",
	HEIGHT: "Wysokość:",
	WIDTH: "Szerokość:",
	
	TOOLTIP1:"Drukuje maksymalną liczbę wierszy mieszczących się na papierze, przechodząc w poprzek aż do wyczerpania kolumn w arkuszu, a następnie w dół i w lewo w celu wydrukowania następnej grupy wierszy.",
	TOOLTIP2:"Drukuje maksymalną liczbę kolumn mieszczących się na papierze, przechodząc w dół aż do wyczerpania wierszy w arkuszu, a następnie w górę i w prawo w celu wydrukowania następnej grupy kolumn.",
	CM_LABEL: "cm",
	LETTER: "Letter",
	LEGAL: "Legal",
	TABLOID: "Tabloid",
	USER: "Użytkownik",
	SIZE1: "Koperta 6 3/4",
	SIZE2: "Koperta Monarch",
	SIZE3: "Koperta 9",
	SIZE4: "Koperta 10",
	SIZE5: "Koperta 11",
	SIZE6: "Koperta 12",
	SIZE7: "16 kai",
	SIZE8: "32 kai",
	SIZE9: "32 kai, duży"
})
	
