({	
	dlgTaskCreateTitle: "Esleitu sekzio bat",  
	dlgTaskDeleteTitle: "Kendu sekzio bat", 
	dlgTaskEditTitle: "Editatu esleipena",
	dlgTaskRewordTitle: "Egokitu esleipena",
	dlgTaskHistoryTitle: "Sekzio honi buruz",
	dlgTaskReopenTitle: "Ireki esleipena berriro",
	dlgTaskReassignTitle: "Esleitu sekzioa berriro",
	dlgTaskDeleteBtn: "Ezabatu",
	creatingTaskAsTODO: "Esleipena gordetzen ari gara egiteko elementu gisa Jarduerak aplikazioan",
	creatingTaskAsTODO2: "Esleipena gordetzen ari gara",
	creatingTaskAsTODO3: "Esleipenak gordetzen ari gara",
	updatingTask: "Esleipena eguneratzen ari gara Jarduerak aplikazioan",
	updatingTask2: "Esleipena eguneratzen ari gara",
	updatingTask3: "Esleipenak eguneratzen ari gara",
	restoringTask: "Itxaron esleipena leheneratuta egon arte jardueran.",
	creatingFragment: "Dokumentu pribatu bat sortzen sekzio honetarako",
	updatingMaster: "Prozesatzen... Sekzioa eguneratzen ari gara dokumentu nagusian",
	cannotAccessActivity: "Errorea! Ezin da jarduera-zerbitzaria atzitu eta ezin da esleipenak erregistratu. Saiatu berriro geroago.",
	cannotAccessActivity2: "Errorea! Ezin da zerbitzaria atzitu eta ezin da esleipenak erregistratu. Saiatu berriro geroago.",
	cannotAccessActivityContent: "Ezin da jarduera-zerbitzaria atzitu eta ezin da esleipenak erregistratu. Saiatu berriro geroago.",
	cannotRecordAssignment: "Ezin da jarduera-zerbitzaria atzitu eta ezin da esleipenak erregistratu. Saiatu berriro geroago.",
	notMemberofActivity: "Jarduerak ezin du esleipena erregistratu. Egiaztatu jarduerara gehitu zaituztela eta saiatu berriro.",
	cannotLoadActivity: "Ezin da jarduera-zerbitzaria atzitu eta esleipenak ezin dira kargatu. Saiatu berriro geroago.",
	cannotLoadActivity2: "Ezin da zerbitzaria atzitu eta esleipenak ezin dira kargatu. Saiatu berriro geroago.",
	cannotLoadAssignment: "Ezin da jarduera-zerbitzaria atzitu eta ezin da esleipen hau kargatu. Saiatu berriro geroago.",
	cannotSupportSocialEdit: "Ez duzu elkarlanean editatzeko edo sekziorik esleitzeko baimenik.",
	cannotDeleteDraft: "Une honetan ezin da zirriborroa ezabatu. Ezabatu fitxategia geroago eskuz.",
	taskAlreadyRemoved: "Dokumentu honen ataza kendu dute edo ez duzu ataza editatzeko baimenik.",
	taskAlreadyCompleted: "Ataza amaitu edo bertan behera utzi dute.",
	taskAlreadyReassigned: "Ataza berriro esleitu da.",
	assignmentAlreadyExist: "Hautatutako area aurrez esleitu da.",
	notAllowedEditMaster: "Ezin duzu dokumentu nagusia editatu. Egiaztatu horretarako baimenik duzun.",
	notAllowedEditPaticipant: "Esleipenduna edo berrikuslea ez da definitu edo ez dute editatzeko baimenik. Ziurtatu esleipendunak edo berrikusleak behar den baimena duela.",
	notValidAssignment: "Baliteke esleipenaren propietate batzuk hondatuta egotea, eta esleipena baliogabea da. Kentzeko, sakatu Jarduerak > Kendu esleipena",
	disableBlockerMsg: "Laster-leihoen blokeatzaile bat duzu aktibatuta eta orria ezin da ondo bistaratu. Eman *cn.ibm.com webguneko laster-leihoei bistaratzeko baimena.",
	writeDesc: "Idatzi ${0}: ${1}",
	reviewDesc: "Berrikusi ${0}: ${1}",
	reworkDesc: "Egokitu ${0}: ${1}",
	writeCompleteDesc: "${0} sekzioa, ${1}(e)k idatzita",
	reviewCompleteDesc: "${0} sekzioa, ${1}(e)k berrikusia",
	workingPrivateDesc: "Lanean pribatuan hemen: ${1} (${0}(e)k sortua)",
	actions: "Ekintzak",	
	onlyAssignerDeleteTask: "Ez dute esleipen hau osatuta gisa markatu eta ezin duzu ezabatu. Esleitu zuenak bakarrik ezabatu dezake.",
	actionBtnEdit: "Editatu esleipena",
	actionBtnRemove: "Kendu esleipena",
	actionBtnAbout: "Sekzio honi buruz",
	actionBtnMarkComplete: "Markatu osatuta gisa",
	actionBtnWorkPrivately: "Jardun pribatuan",
	actionBtnApprove: "Onartu sekzio hau",
	actionBtnGotoPrivate: "Joan dokumentu pribatura",
	actionBtnCancelPrivate: "Utzi lan pribatua bertan behera",
	actionBtnRework: "Egokitzea beharrezkoa da",
	actionBtnReopen: "Ireki esleipena berriro",
	actionBtnReassign: "Esleitu sekzioa berriro",
	creating: "Sortzen...",
	deleting: "Ezabatzen...",
	updating: "Eguneratzen...",
	loading: "Kargatzen...",
	restoring: "Leheneratzen...",
	lockCoeditingTask:"Beste editore bat esleipen berberean dabil lanean. Saiatu berriro geroago."
})

