({
	stViewClient:"แสดง Sametime Client",
	stChatList:"คลิกเพื่อเปิดไคลเอ็นต์ Sametime Web ในหน้าต่างใหม่",
	stWebClient:"HCL Sametime ",
	stStatusMeeting:"กำลังประชุม",
	stStatusAvailable:"ฉันว่าง",
	stViewBd:"แสดงรายการ Sametime Buddy",
	stErrorSTServer:"เกิดข้อผิดพลาดในการเชื่อมต่อกับ Sametime",
	stStatusAway:"ฉันไม่อยู่",
	stLConnLogIn:"ลงชื่อเข้าใช้ HCL Connections เพื่อดูสถานะ Sametime",
	stActionBar:"แถบการดำเนินการ Sametime",
	stStatusBusy:"ฉันไม่ว่าง",
	stLogin:"ล็อกอินเข้าสู่ Sametime",
	stUserOffline:"ฉันออฟไลน์",
	stStartChat:"คลิกที่นี่เพื่อเริ่มต้นการสนทนา",
	stLogout:"ออกจากระบบ Sametime",
	stDisconnect:"ตัดการเชื่อมต่อจาก Sametime",
	stViewSTActions:"คลิกเพื่อดูการดำเนินการของ Sametime",
	stError:"เกิดข้อผิดพลาดขึ้น เซอร์วิส Sametime ไม่พร้อมใช้งาน",
	stUnableToConnect:"ไม่สามารถเชื่อมต่อกับ Sametime ",
	stConnect:"เชื่อมต่อกับ Sametime",
	stNoStatuAvailable:"ไม่มีสถานะ Sametime",
	stStatusdnt:"ห้ามรบกวน",
	stLoadingSTStatus:"กำลังโหลดสถานะ Sametime...",
	stShareAs:"กำลังแบ่งใช้เอกสาร...",
	stShareDlgTitle:"แบ่งใช้เอกสารผ่านทาง Sametime...",
	stShareDlgMsgTemplate:"คุณต้องการ 'แบ่งใช้ ${file_name}' กับ ${contact_name} เป็นผู้แก้ไข หรือผู้อ่านหรือไม่",
	stShareEditor:"ผู้แก้ไข",
	stShareReader:"ผู้อ่าน",
	stShareSuccessTemplate:"${contact_name}, ฉันต้องการแบ่งใช้เอกสาร '${file_name}' กับคุณ:\n<a href=\"${document_link}\">${document_link}</a>"
})
