/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2014. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
	service_unavailable_title: "Storitev ni na voljo.",
	service_unavailable_content: "Storitev ${productName} ni na voljo. Vaše zahteve trenutno ni mogoče obdelati. Poskusite znova pozneje ali se obrnite na skrbnika sistema.",
	access_denied_title: "Dostop je zavrnjen.",
	viewaccess_denied_content: "Nimate dovoljenja za ogled te datoteke. Datoteko je treba nastaviti kot javno ali pa jo dati v skupno rabo z vami.",
	editaccess_denied_content: "Niste upravičeni do uporabe storitve ${productName} ali nimate dovoljenja za urejanje te datoteke. Datoteka mora biti dodana v skupno rabo z vami, vaša raven dostopa pa nastavljena na urednika. Datoteko je morda tudi zaklenil drug urednik",
	doc_notfound_title: "Dokumenta ni mogoče najti.",
	doc_notfound_content: "Dokument, do katerega želite dostopati, je bil izbrisan ali premaknjen. Preverite, ali je povezava pravilna.",
	repository_out_of_space_title: "Ni dovolj prostora",
	repository_out_of_space_content: "Dokumenta ${0} ni mogoče objaviti, ker ste dosegli kvoto velikosti datotek. Zmanjšajte delež porabljene kvote, tako da premaknete druge datoteke v koš in jih nato izbrišete.",
	fileconnect_denied_title: "Vzpostavitev povezave je zavrnjena.",
	fileconnect_denied_content: "Storitev ${productName} se ne more povezati z datotečnim repozitorijem. Poskusite znova pozneje ali se obrnite na skrbnika sistema.",
	unscanned_document_title: "Iskanje virusov se dokončuje",
	unscanned_document_content: "Datoteke, naložene v Connections, so samodejno pregledane. To datoteko lahko urejate takoj po dokončanem pregledu.",
	malicious_document_title: "Zlonamerna datoteka",
	malicious_document_content: "Te datoteke ne morete urejati, ker je programska oprema Connections med pregledom zaznala virus.",	
	convservice_unavailable_title: "Storitev pretvorbe ni na voljo.",
	convservice_unavailable_content: "Storitev pretvorbe za storitev ${productName} ni na voljo. Vaše zahteve trenutno ni mogoče obdelati. Poskusite znova pozneje ali se obrnite na skrbnika sistema.",
	doc_toolarge_title: "Datoteka je prevelika.",
	doc_toolarge_content: "Dokument, do katerega želite dostopati, je prevelik.",
	doc_toolarge_content2: "Do datoteke ni mogoče dostopati. Možni razlogi:",
	doc_toolarge_content3: "Datoteke ni mogoče prikazati, ker velikost datoteke presega ${0} KB. Če želite urejati datoteko, jo lahko prenesete. Če so v datoteki slike visoke ločljivosti, jih lahko zamenjate s slikami nizke ločljivosti, da zmanjšate velikost datoteke.",
	doc_toolarge_content4: "Datoteka je prevelika, da bi si jo lahko ogledali tukaj, še vedno pa jo lahko odprete tako, da na naslovni vrstici kliknete gumb za prenos.",
	doc_toolarge_content_mobile: "Datoteke ni mogoče odpreti. Velikost datoteke v mobilni napravi ne sme presegati ${0} KB.",
	sheet_toolarge_content: "Velikost preglednice presega ${0} KB.",
	sheet_toolarge_content2: "Število vrstic na enem listu preglednice je večje kot ${0}.",
	sheet_toolarge_content5: "Število stolpcev na enem listu preglednice je večje kot ${0}.",
	sheet_toolarge_content3: "Število celic v preglednici je večje kot ${0}.",
	sheet_toolarge_content4: "Število formul v preglednici je večje kot ${0}.",
	text_toolarge_content: "Velikost dokumenta presega ${0} KB.",
	text_toolarge_content2:"Število strani v dokumentu je večje kot ${0}.",
	text_toolarge_content3:"Velikost besedila dokumenta presega ${0} KB.",
	pres_toolarge_content: "Do predstavitve ni mogoče dostopati, ker velikost predstavitve presega ${0} KB. Če ima predstavitev slike visoke ločljivosti, jih lahko zamenjate s tistimi z nizko ločljivostjo, da se zmanjša velikost predstavitve.",
	pres_toolarge_content2: "Do predstavitve ni mogoče dostopati, ker vsebuje več kot ${0} strani.",
	pres_toolarge_content3: "Do predstavitve ni mogoče dostopati, ker vsebuje več kot ${0} objektov.",
	pres_toolarge_content2_mobile: "Predstavitve ni mogoče odpreti v mobilni napravi, ker vsebuje več kot ${0} strani.",
	pres_toolarge_content3_mobile: "Predstavitve ni mogoče odpreti v mobilni napravi, ker vsebuje več kot ${0} objektov.",
	sheet_view_toolarge_content1_mobile: "Preglednice si ni mogoče ogledati v mobilni napravi, ker vsebuje več kot ${0} vrstic.",
	sheet_view_toolarge_content2_mobile: "Preglednice si ni mogoče ogledati v mobilni napravi, ker vsebuje več kot ${0} stolpcev.",
	sheet_view_toolarge_content3_mobile: "Preglednice si ni mogoče ogledati v mobilni napravi, ker vsebuje več kot ${0} vrstic in ${1} stolpcev.",
	conversion_timeout_title: "Časovna omejitev za pretvorbo dokumenta je potekla.",
	conversion_timeout_content: "Trenutno pretvorba dokumenta traja predolgo. Poskusite znova pozneje.",
	invalid_docformat_title: "Dokumenta ni mogoče odpreti",
	invalid_docformat_content: "Pripona dokumenta je veljavna, vendar vsebine ni mogoče brati, ker je poškodovana ali šifrirana.",
	template_extension_conent_mismatch: "Vir razširitve datoteke jo nepravilno opredeljuje kot predlogo. Datoteka je dejansko v formatu .${0}. Začnite z veljavno predlogo ali shranite to datoteko pod drugim imenom, tako da uporabite .${0} kot njeno razširitev.",
	invalid_docformat_title2: "Datoteke ni mogoče uvoziti v storitev ${productName}.",
	invalid_docformat_content2: "Obstaja nekaj v tej datoteki, česar storitev ${productName} v tem trenutku ne podpira. Te datoteke ni mogoče uvoziti.",
	invalid_doctype_title: "Vrsta dokumenta ni podprta.",
	invalid_doctype_content: "Storitev ${productName} trenutno ne podpira vrste dokumenta.",
	unsupported_browser_title: "Vaš brskalnik ne podpira vseh funkcij",
	malformed_request_title: "Zahteva je popačena.",
	malformed_request_content: "Poskrbite, da bodo URL in parametri pravilni.",
	storageserver_error_title: "Pomnilniški strežnik ni dosegljiv.",
	storageserver_error_content: "Strežnik trenutno ni dosegljiv. Vaše zahteve trenutno ni mogoče obdelati. Poskusite znova pozneje ali se obrnite na skrbnika sistema.",
	document_already_opened_title: "Dokument je že odprt",
	document_already_opened_content:"Ta dokument je že odprt v vašem brskalniku.",
	toomany_documents_opened_inone_browser_title: "Dokumenta ni mogoče odpreti",
	toomany_documents_opened_inone_browser_content:"Naenkrat lahko odprete le pet datotek storitve ${productName}. Zaprite druge dokumente in nato znova poskusite odpreti ta dokument.",
	document_max_session_exceeded_title:"Storitev ni na voljo.",
	document_max_session_exceeded_content:"Preveč uporabnikov ureja dokumente v strežniku, zato vaše zahteve ni mogoče nadaljevati. Poskusite znova pozneje.",
	kickout_user_content: "Ta dokument je že odprt v drugem oknu v vašem računalniku. Če želite nadaljevati urejanje dokumenta, se vrnite na drugo okno.",
	return_to_files: "Vrnite se na Datoteke",
	return_to_library: "Vrni se na Knjižnico",
	return_to_icn: "Vrni se na Content Navigator",
	document_already_open: "Dokument je že odprt",
	cannotedit_noentitled_title: "Te datoteke ni mogoče sočasno urejati",
	cannotedit_noentitled_content1: "Datoteko trenutno urejajo naslednji uporabniki:",
	cannotedit_noentitled_content2: "Niste pooblaščeni za urejanje te datoteke, medtem ko jo urejajo drugi. Poskusite jo urediti pozneje.",
	cannotedit_noentitled_content3: "Datoteko trenutno ureja naslednji uporabnik:",
	cannotedit_noentitled_content4: "Ne morete se pridružiti tej sočasni urejevalni seji, ker uporabnik, ki ureja datoteko, nima pravic za sočasno urejanje. Poskusite jo urediti pozneje.",
	toomany_coeditors_title: "Preveč uporabnikov",
	toomany_coeditors_content: "Ta dokument trenutno ureja preveč uporabnikov, hkrati lahko ta dokument ureja le naslednje število uporabnikov: {0}.",
	encrypted_pptdoc_title:"Šifrirana datoteka",
	encrypted_pptdoc_content:"Datoteka je zaščitena z geslom. V izdelku ${productName} je ni mogoče urejati, razen če jo najprej dešifrirate.",
	server_busy_title:"Strežnik je zaseden",
	server_busy_content:"Počakajte nekaj trenutkov in poskusite znova pozneje.",
	document_encrypt_title:"Šifrirani dokument ni podprt",
	document_encrypt_content:"Ta datoteka je šifrirana v datotečnem repozitoriju. Zaradi varnostnih vidikov je storitev ${productName} ne more urejati neposredno.",
	edit_locked_file: "Te datoteke ne morete urejati, ker so jo zaklenili drugi urejevalci.",
	publish_locked_file: "Te datoteke ne morete objaviti kot novo različico, ker je zaklenjena, vendar pa se vaša vsebina samodejno shranjuje v osnutek.",
	join_locked_file_session: "Ne morete se pridružiti seji sočasnega urejanja, ker so to datoteki zaklenili drugi uporabniki.",
	no_need_to_convert_title:"Ni potrebe po pretvorbi",
	no_need_to_convert_content:"Oblika zapisa datoteke, v katero želite izvesti pretvorbo, je že taka, kot želite. Izvedite neposredni prenos.",
	warning_icon: "Ikono opozorila",
	//html viewer error message
	incorrect_web_address_title:"Nepravilen spletni naslov.",
	incorrect_web_address_content:"Spletni naslov ni pravilen.  Vnesite spletni naslov in poskusite znova.",
	unexpecified_conversion_error_title:"Napaka ni določena.",
	unexpecified_conversion_error_content:"Strežnik je vrnil nedoločeno napako.",
	encrypted_conversion_error_title:"Šifrirani dokument ni podprt.",
	encrypted_conversion_error_content:"Datoteka je zaščitena z geslom. Če si želite datoteko ogledati v pregledovalniku, jo najprej dešifrirajte.",
	service_busy_title:"Dokumenta ni bilo mogoče odpreti",
	service_busy_content:"Datoteke, ki si jo želite ogledati, ni bilo mogoče odpreti. Strežnik je morda zaseden ali pa ni na voljo. Poskusite znova pozneje ali se obrnite na skrbnika.",
	empty_doc_title: "Dokument je prazen.",
	empty_doc_content: "Preverite, ali ima dokument vsebino, in poskusite znova.",
	corrupted_doc_title: "Datoteke ni mogoče odpreti.",
	corrupted_doc_content: "Datoteka vsebuje nepodprto vsebino, na primer makre, in si je zato ni mogoče ogledati v tej aplikaciji.",
	draft_storage_error_title: "Dokumenta ni mogoče odpreti.",
	draft_storage_error_content: "Vsebine ni mogoče naložiti, ker je pokvarjena. Za podporo se obrnite na skrbnika.",
	unexpected_code_title: "Strežnik ${productName} vrne nepričakovano kodo.",
	unexpected_code_content: "Strežnik ${productName} vrne nepričakovano kodo.",
	request_time_out_title: "Časovna omejitev nalaganja dokumenta.",
	request_time_out_content: "Nalaganje dokumenta traja predolgo. Poskusite znova pozneje.",
	problem_id_msg_title: "Sporočite težavo skrbniku. ",
	problem_id_msg_show: "Kliknite za prikaz podrobnosti",
	problem_id_msg_hide: "Kliknite, če želite skriti"
})

