({
	alt			: "Alternativní text:",
	width		: "Šířka:",
	height		: "Výška:",
	cmUnit   : "cm",
	ptUnit 	 : "b.",
	inchUnit : "in",
	inUnit   : "in",
	mmUnit 	 : "mm",
	
	inputWarning: "Zadejte kladné číslo ve výchozích jednotkách. ",
	
	properties: "Vlastnosti",
	data: "Data",
	chart: "Graf",
	axis: "Osa",
	series: "Posloupnost",
	font: "Písmo",
	title: "Titulek",
	legend: "Legenda",
	placement: "Umístění",
	background: "Pozadí",
	plotarea: "Plocha pro vykreslení",
	line : "Čára",
	fill: "Výplň",
	border : "Ohraničení",
	labelfont: "Popisek",
	scale: "Měřítko",
	minimum: "Minimum",
	maximum: "Maximum",
	majorunit: "Hlavní jednotka",
	minorunit: "Vedlejší jednotka",
	smooth: "Hladké",
	marker: "Značky",
	markerfill: "Značka",
	enterTitle: "Sem zadejte nadpis. ",
	inputNumberWarning: "Zadejte číslo.",
	inputPosNumberWarning: "Zadejte kladné číslo.",
	maxMinWarning: "Maximální hodnota musí být vyšší než minimální. ",
	selectFontName: "Vybrat název písma",
	selectFontSize: "Vybrat velikost písma",
	setBold: "Tučné",
	setItalic: "Kurzíva",
	setFontColor: "Nastavit barvu písma",
	setLegendPos: "Nastavit umístění legendy",
	setBackColor: "Nastavit barvu pozadí grafu",
	setBorderWidth: "Nastavit šířku ohraničení",
	setBorderColor: "Nastavit barvu ohraničení",
	setPlotAreaColor: "Nastavit barvu zákresové oblasti ",
	selectAxis: "Vybrat osu",
	setLineWidth: "Nastavit šířku čáry",
	setLineColor: "Nastavit barvu čáry",
	selectSeries: "Vybrat posloupnost",
	setFillColor: "Nastavit barvu výplně",
	setMarker: "Nastavit značky",
	setSmooth: "Nastavit hladkou čáru",
	chartTitle: "Titulek grafu",
	axisTitle: "Nadpis osy",
	
	ERR1: "Pole musí být uzavřeno ve složených závorkách. ",
	ERR3: "Řetězcové položky musí být uzavřeny v uvozovkách.",
	ERR4: "Zadejte pouze jednu oblast.",
	ERR5: "Oblast musí existovat.",
	ERR6: "Všechny oblasti se musí nacházet na stejném listu.",
	ERR7: "Všechny oblasti se musí vztahovat ke stejnému řádku nebo sloupci.",
	ERR9: "Hodnota posloupnosti je povinná.",
	
	n	: "Žádná položka",
	l	: "Vlevo",
	r	: "Vpravo",
	t	: "Nahoře",
	b   : "Dole",
	
	dataSeries:"Datová posloupnost",
	label:"Název posloupnosti",
	xVal:"Hodnoty posloupnosti X",
	yVal:"Hodnoty posloupnosti Y",
	val:"Hodnoty posloupnosti",
	cat:"Kategorie",
		
	ltr: "Zleva doprava",
	rtl: "Zprava doleva",
	auto: "Podle kontextu",
	bidi_dir: "Směr",
	bidi_text_dir: "Směr textu"
})
