({
		SAVE: "保存",
		UNDO:"元に戻す",
		REDO:"やり直し",
		INSERTROW:"行の挿入",
		DELETEROW:"行の削除",
		INSERTCOLUMN:"列の挿入",
		DELETECOLUMN:"列の削除",
		FONTSIZE:"フォント・サイズ",
		FONTCOLOR:"フォントの色",
		BOLD:"太字",
		ITALIC:"イタリック",
		UNDERLINE:"下線",
		STRIKETHROUGH:"取り消し線",
		CURRENCYTIP:"通貨としてフォーマット",
		PERCENTLABEL:"%",
		PERCENTTIP:"パーセントとしてフォーマット",
		NUMBERFORMAT:"数値の表示形式",
		ALIGNLEFT:"左揃え",
		ALIGNCENTER:"中央揃え",
		ALIGNRIGHT:"右揃え",
		SETCELLBORDER:"セルの枠線の設定",
		BACKGROUNDCOLOR:"マーカー",
		TASK:"セクションの割り当て",
		COMMENTS:"コメントの追加",
		SUBMIT:"送信",
		MERGECELL: "セルの結合または分割",
		QUICKFORMULA: "クイック式",
		WRAPTEXT: "テキストの折り返し",
		EIGHT:"8pt",
		NINE:"9pt",
		TEN:"10pt",
		ELEVEN:"11pt",
		TWELVE:"12pt",
		FOURTEEN:"14pt",
		SIXTEEN:"16pt",
		EIGHTEEN:"18pt",
		TWENTY:"20pt",
		TWENTYTWO:"22pt",
		TWENTYFOUR:"24pt",
		NUMBER:"数値",
		CURRENCY:"通貨",
		PERCENT:"パーセント",
		DATE:"日付",
		TIME:"時刻",
		DATETIME: "日付/時刻",
		MORECURRENCY:"その他の通貨",
		MOREDATE:"その他の書式",
		
		
		CAD: "カナダドル",
		USD: "ドル",
		EUR: "ユーロ",
		CHF: "スイスフラン",
		HKD: "香港ドル",
		DKK: "クローネ",
		LTL: "リタス",
		PHP: "ペソ",
		BRL: "レアル",
		RUR: "ルーブル",
		GBP: "ポンド",
		NLG: "ギルダー", // Netherlands
		TWD: "ニュー台湾ドル",
		THB: "バーツ", // Thailand
		ITL: "リラ", // Turkey
		BGL: "レフ", // Uzbekistan
		VND: "ドン", // Vietnam
		KRW: "ウオン",	// Korean 
		CNY: "元", // RMB
		JPY: "円" // Japan Yen
})
