({
	alt			: "Zamjenski tekst:",
	width		: "Širina:",
	height		: "Visina:",
	cmUnit   : "cm",
	ptUnit 	 : "pt",
	inchUnit : "inč",
	inUnit   : "in",
	mmUnit 	 : "mm",
	
	inputWarning: "Unesite pozitivan broj s default jedinicom. ",
	
	properties: "Svojstva",
	data: "Podaci",
	chart: "Grafikon",
	axis: "Os",
	series: "Serije",
	font: "Font",
	title: "Naslov",
	legend: "Legenda",
	placement: "Mjesto",
	background: "Pozadina",
	plotarea: "Područje za crtanje",
	line : "Linija",
	fill: "Ispuna",
	border : "Rub",
	labelfont: "Labela",
	scale: "Skala",
	minimum: "Minimum",
	maximum: "Maksimum",
	majorunit: "Glavna jedinica",
	minorunit: "Manja jedinica",
	smooth: "Gladak",
	marker: "Markeri",
	markerfill: "Marker",
	enterTitle: "Ovdje upišite naslov",
	inputNumberWarning: "Unesite broj.",
	inputPosNumberWarning: "Unesite pozitivan broj.",
	maxMinWarning: "Maksimalna vrijednost mora biti veća od minimalne vrijednosti.",
	selectFontName: "Izaberite ime fonta",
	selectFontSize: "Izaberite veličinu fonta",
	setBold: "Podebljajte",
	setItalic: "Kurziv",
	setFontColor: "Postavite boju fonta",
	setLegendPos: "Postavite mjesto za tumač znakova",
	setBackColor: "Postavite boju pozadine grafikona",
	setBorderWidth: "Postavite širinu ruba",
	setBorderColor: "Postavite boju ruba",
	setPlotAreaColor: "Postavite boju područja za crtanje",
	selectAxis: "Izaberite os",
	setLineWidth: "Postavite širinu linije",
	setLineColor: "Postavite boju linije",
	selectSeries: "Izaberite serije",
	setFillColor: "Postavite boju za ispunu",
	setMarker: "Postavite markere",
	setSmooth: "Postavite glatku liniju",
	chartTitle: "Naslov grafikona",
	axisTitle: "Naslov osi",
	
	ERR1: "Matrica mora biti u vitičastim zagradama.",
	ERR3: "Stavke niza znakova moraju biti u dvostrukim navodnicima.",
	ERR4: "Unesite samo jedan raspon.",
	ERR5: "Raspon mora postojati.",
	ERR6: "Svi rasponi moraju biti na istom listu.",
	ERR7: "Svi rasponi moraju biti za pojedinačni red ili stupac.",
	ERR9: "Potrebna je vrijednost serija.",
	
	n	: "Ništa",
	l	: "Lijevo",
	r	: "Desno",
	t	: "Vrh",
	b   : "Dno",
	
	dataSeries:"Serije podataka",
	label:"Ime serije",
	xVal:"X vrijednosti serije",
	yVal:"Y vrijednosti serije",
	val:"Vrijednosti serije",
	cat:"Kategorija",
		
	ltr: "Od lijeva na desno",
	rtl: "Od desna na lijevo",
	auto: "Kontekstualno",
	bidi_dir: "Smjer",
	bidi_text_dir: "Smjer teksta"
})
