({
	COLUMN: "Column",
	CLUSTERED_COLUMN: "Clustered Column",
	STACKED_COLUMN: "Stacked Column",
	BAR:"Bar",
	CLUSTERED_BAR:"Clustered Bar",
	STACKED_BAR: "Stacked Bar",
	PIE:"Pie",
	SLICE: "Slice",
	AREA: "Area",
	STACKED_AREA: "Stacked Area",
	LINE: "Line",
	STACKED_LINE: "Stacked Line",
	MAKER_LINE: "Line with Markers",
	STACKED_MARKER_LINE: "Stacked Line with Markers",
	SCATTER: "Scatter",
	SCATTER_MARKER_ONLY: "Scatter with only Markers",
	SCATTER_MARKER_LINE_S: "Scatter with Smooth Lines and Markers",
	SCATTER_LINE_S: "Scatter with Smooth Lines", 
	SCATTER_MARKER_LINE_X: "Scatter with Straight Lines and Markers",
	SCATTER_LINE_X: "Scatter with Straight Lines",
	ERROR_INVALID_RANGE:"Invalid data range",
	TOO_MANY_POINTS: "Cannot create a chart that has more than ${0} data points",
	CHART_TYPES:"Chart Types",
	DATA:"Data",
	DATA_RANGE:"Data Range",
	IN_ROWS:"Data series in rows",
	IN_COLUMNS:"Data series in columns",
	AUTO:"Automatic"
})
