/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
    Arrow01_Gray: "Βέλος 01, γκρι",
    Arrow02_Gray: "Βέλος 02, γκρι",
    Arrow03_Red: "Βέλος 03, κόκκινο",
    Arrow04_Blue: "Βέλος 04, μπλε",
    Arrow05_Blue: "Βέλος 05, μπλε",
    Arrow06_Yellow: "Βέλος 06, κίτρινο",
    Arrow07_Red: "Βέλος 07, κόκκινο",
    Arrow08_Gray: "Βέλος 08, γκρι",
    Arrow09_Orange: "Βέλος 09, πορτοκαλί",
    Arrow10_Blue: "Βέλος 10, μπλε",
    Arrow11_Blue: "Βέλος 11, μπλε",
    Arrow12_Green: "Βέλος 12, πράσινο",
    Arrow13_Blue: "Βέλος 13, μπλε",
    Arrow14_Green: "Βέλος 14, πράσινο",
    Arrow15_Orange: "Βέλος 15, πορτοκαλί",
    Arrow16_Gray: "Βέλος 16, γκρι",
    CircleArrow01_Green: "Κυκλικό βέλος 01, πράσινο",
    CircleArrow02_Multi: "Κυκλικό βέλος 02, πολύχρωμο",
    CircleArrow03_Multi: "Κυκλικό βέλος 03, πολύχρωμο",
    CircleArrow04_Multi: "Κυκλικό βέλος 04, πολύχρωμο",
    CircleArrow05_Multi: "Κυκλικό βέλος 05, πολύχρωμο",
    CircleArrow06_Multi: "Κυκλικό βέλος 06, πολύχρωμο",
    CircleArrow07_Blue: "Κυκλικό βέλος 07, μπλε",
    CircleArrow08_Green: "Κυκλικό βέλος 08, πράσινο",
    CircleArrow09_Multi: "Κυκλικό βέλος 09, πολύχρωμο",
    CurvedArrow01_Gray: "Κυρτό βέλος 01, γκρι",
    CurvedArrow02_Blue: "Κυρτό βέλος 02, μπλε",
    CurvedArrow03_Blue: "Κυρτό βέλος 03, μπλε",
    CurvedArrow04_Orange: "Κυρτό βέλος 04, πορτοκαλί",
    CurvedArrow05_Red: "Κυρτό βέλος 05, κόκκινο",
    CurvedArrow06_Blue: "Κυρτό βέλος 06, μπλε",
    CurvedArrow07_Purple: "Κυρτό βέλος 07, μωβ",
    CurvedArrow08_Green: "Κυρτό βέλος 08, πράσινο",
    CurvedArrow09_Gray: "Κυρτό βέλος 09, γκρι",
    CurvedArrow10_Blue: "Κυρτό βέλος 10, μπλε",
    CurvedArrow11_Orange: "Κυρτό βέλος 11, πορτοκαλί",
    CurvedArrow12_Blue: "Κυρτό βέλος 12, μπλε",
    CurvedArrow13_Green: "Κυρτό βέλος 13, πράσινο",
    CurvedArrow14_Brown: "Κυρτό βέλος 14, καφέ",
    CurvedArrow15_Blue: "Κυρτό βέλος 15, μπλε",
    CurvedArrow16_Gray: "Κυρτό βέλος 16, γκρι",
    CurvedArrow17_Gray: "Κυρτό βέλος 17, γκρι",
    CurvedArrow18_Gray: "Κυρτό βέλος 18, γκρι",
    CurvedArrow19_Gray: "Κυρτό βέλος 19, γκρι",
    CurvedArrow20_Gray: "Κυρτό βέλος 20, γκρι",
    TrendArrow01_Red: "Βέλος τάσης 01, κόκκινο",
    TrendArrow02_Green: "Βέλος τάσης 02, πράσινο",
    TrendArrow03_Orange: "Βέλος τάσης 03, πορτοκαλί",
    TrendArrow04_Red: "Βέλος τάσης 04, κόκκινο",
    TrendArrow05_Orange: "Βέλος τάσης 05, πορτοκαλί",
    TrendArrow06_Blue: "Βέλος τάσης 06, μπλε",
    TrendArrow07_Orange: "Βέλος τάσης 07, πορτοκαλί",
    TrendArrow08_Yellow: "Βέλος τάσης 08, κίτρινο",
    TrendArrow09_Blue: "Βέλος τάσης 09, μπλε",
    TrendArrow10_Blue: "Βέλος τάσης 10, μπλε",
    TrendArrow11_Blue: "Βέλος τάσης 11, μπλε",
    TrendArrow12_Blue: "Βέλος τάσης 12, μπλε",
    TrendArrow13_Red: "Βέλος τάσης 13, κόκκινο",
    TrendArrow14_Multi: "Βέλος τάσης 14, πολύχρωμο",
    TrendArrow15_Blue: "Βέλος τάσης 15, μπλε",
    Bullet01_Circle_DarkRed: "Κουκίδα 01, σκούρος κόκκινος κύκλος",
    Bullet02_Circle_Blue: "Κουκίδα 02, μπλε κύκλος",
    Bullet03_Circle_Green: "Κουκίδα 03, πράσινος κύκλος",
    Bullet04_Square_Black: "Κουκίδα 04, μαύρο τετράγωνο",
    Bullet05_Square_Orange: "Κουκίδα 05, πορτοκαλί τετράγωνο",
    Bullet06_Square_Purple: "Κουκίδα 06, μωβ τετράγωνο",
    Bullet07_Diamond_Blue: "Κουκίδα 07, μπλε ρόμβος",
    Bullet08_Diamond_LightBlue: "Κουκίδα 08, ανοιχτός μπλε ρόμβος",
    Bullet09_Diamond_Red: "Κουκίδα 09, κόκκινος ρόμβος",
    Bullet10_Star_Yellow: "Κουκίδα 10, κίτρινο αστέρι",
    Bullet11_Star_Blue: "Κουκίδα 11, μπλε αστέρι",
    Bullet12_Triangle_Blue: "Κουκίδα 12, μπλε τρίγωνο",
    Bullet13_Triangle_DarkGreen: "Κουκίδα 13, σκούρο πράσινο τρίγωνο",
    Bullet14_Arrow_Red: "Κουκίδα 14, κόκκινο βέλος",
    Bullet15_Arrow_Blue: "Κουκίδα 15, μπλε βέλος",
    Bullet16_Box_Blue: "Κουκίδα 16, μπλε κύβος",
    Bullet17_Box_Red: "Κουκίδα 17, κόκκινος κύβος",
    Bullet18_Asterisk_LightBlue: "Κουκίδα 18, ανοιχτός μπλε αστερίσκος",
    Bullet19_Leaves_Red: "Κουκίδα 19, κόκκινα φύλλα",
    Bullet20_Target_Blue: "Κουκίδα 20, μπλε στόχος",
    Bullet21_Arrow_Blue: "Κουκίδα 21, μπλε βέλος",
    Bullet22_Arrow_DarkBlue: "Κουκίδα 22, σκούρο μπλε βέλος",
    Bullet23_Arrow_Brown: "Κουκίδα 23, καφέ βέλος",
    Bullet24_Flag_Red: "Κουκίδα 24, κόκκινη σημαία",
    Bullet25_Flag_Green: "Κουκίδα 25, πράσινη σημαία",
    Bullet26_X_Red: "Κουκίδα 26, κόκκινο X",
    Bullet27_X_Black: "Κουκίδα 27, μαύρο X",
    Bullet28_Checkmark_Green: "Κουκίδα 28, πράσινο σημάδι επιλογής",
    Bullet29_Checkmark_Blue: "Κουκίδα 29, μπλε σημάδι επιλογής",
    Bullet30_Square_DarkRed: "Κουκίδα 30, σκούρο κόκκινο τετράγωνο",
    camera: "Κάμερα",
    computer1: "Υπολογιστής 1",
    computer2: "Υπολογιστής 2",
    computer3: "Υπολογιστής 3",
    Computer_Cloud: "Νέφος υπολογιστών",
    Computer_Desktop: "Υπολογιστής γραφείου",
    Computer_Laptop_Black: "Φορητός υπολογιστής σε μαύρο χρώμα",
    Computer_Laptop_Silver: "Φορητός υπολογιστής σε ασημί χρώμα",
    Database: "Βάση δεδομένων",
    evelope: "Φάκελος",
    newspapers: "Εφημερίδες",
    openevelope: "Ανοιχτός φάκελος",
    Server: "Εξυπηρετητής",
    speaker: "Ηχείο",
    WirelessAccessPoint: "Σημείο ασύρματης πρόσβασης (WAP)",
    Cycle01_Transparent: "Κύκλος 01, διαφανής",
    Cycle02_Transparent_Blue: "Κύκλος 02, διαφανής μπλε",
    Cycle03_Blue: "Κύκλος 03, μπλε",
    Cycle04_Blue: "Κύκλος 04, μπλε",
    Cycle05: "Κύκλος 05",
    Cycle06: "Κύκλος 06",
    Cycle07: "Κύκλος 07",
    Cycle08_Blue: "Κύκλος 08, μπλε",
    Cycle09_Orange: "Κύκλος 09, πορτοκαλί",
    Donut01_LightBlue: "Δακτύλιος 01, ανοιχτό μπλε",
    Donut02_Blue: "Δακτύλιος 02, μπλε",
    Donut03_Blue: "Δακτύλιος 03, μπλε",
    Donut04_DarkBlue: "Δακτύλιος 04, σκούρο μπλε",
    Donut05_DarkBlue: "Δακτύλιος 05, σκούρο μπλε",
    Donut06_Blue: "Δακτύλιος 06, μπλε",
    Donut07_Blue: "Δακτύλιος 07, μπλε",
    Graph: "Γράφημα",
    People01_Blue: "Άνθρωποι 01, μπλε",
    People02: "Άνθρωποι 02",
    Pillars01_Orange: "Στήλες 01, πορτοκαλί",
    Pillars02_LightBlue: "Στήλες 02, ανοιχτό μπλε",
    Process01_Blue: "Διεργασία 01, μπλε",
    Process02_Blue: "Διεργασία 02, μπλε",
    Process03_Blue: "Διεργασία 03, μπλε",
    Process04_GoUp_Blue: "Διεργασία 04, ανοδική φορά, μπλε",
    Process05_GoUp_Red: "Διεργασία 05, ανοδική φορά, κόκκινο",
    Process06_GoUp_Yellow: "Διεργασία 06, ανοδική φορά, κίτρινο",
    Process07_Blue: "Διεργασία 07, μπλε",
    Pyramid01: "Πυραμίδα 01",
    Pyramid02_Blue: "Πυραμίδα 02, μπλε",
    Pyramid03: "Πυραμίδα 03",
    Radial01_Green: "Ακτινική διάταξη 01, πράσινο",
    Radial02_Green: "Ακτινική διάταξη 02, πράσινο",
    Radial03_Sphere: "Ακτινική διάταξη 03, σφαίρες",
    Radial04_Sphere_Red: "Ακτινική διάταξη 04, σφαίρες, κόκκινο",
    Radial05_Sphere_Blue: "Ακτινική διάταξη 05, σφαίρες, μπλε",
    Radial06_Arrows_DarkBlue: "Ακτινική διάταξη 06, βέλη, σκούρο μπλε",
    Radial07_Arrows_DarkBlue: "Ακτινική διάταξη 07, βέλη, σκούρο μπλε",
    Section_Circle: "Ενότητες, κύκλος",
    Section_Cubes01: "Ενότητες, κύβοι 01",
    Section_Cubes02_Blue: "Ενότητες, κύβοι 02, μπλε",
    Section_Cubes03_Orange: "Ενότητες, κύβοι 03, πορτοκαλί",
    Section_Cubes04: "Ενότητες, κύβοι 04",
    Section_Cubes05: "Ενότητες, κύβοι 05",
    Section_Cuboids01_Blue: "Ενότητες, κυβοειδή 01, μπλε",
    Section_Cuboids02_Blue: "Ενότητες, κυβοειδή 02, μπλε",
    Section_Cuboids03: "Ενότητες, κυβοειδή 03",
    Section_Gears01: "Ενότητες, γρανάζια 01",
    Section_Gears02: "Ενότητες, γρανάζια 02",
    Section_Gears03: "Ενότητες, γρανάζια 03",
    Section_Hexagon04_Orange: "Ενότητες, εξάγωνα 04, πορτοκαλί",
    Section_Hexagons01: "Ενότητες, εξάγωνα 01",
    Section_Hexagons02_Blue: "Ενότητες, εξάγωνα 02, μπλε",
    Section_Hexagons03_Blue: "Ενότητες, εξάγωνα 03, μπλε",
    Section_Leaves01_LightBlue: "Ενότητες, φύλλα 01, μπλε",
    Section_Leaves02_Green: "Ενότητες, φύλλα 02, πράσινο",
    Section_Pasters01: "Ενότητες, αυτοκόλλητα σημειώματα 01",
    Section_Pasters02_Blue: "Ενότητες, αυτοκόλλητα σημειώματα 02, μπλε",
    Section_Puzzle01: "Παζλ 01",
    Section_Puzzle02: "Παζλ 02",
    Section_Puzzle03: "Παζλ 03",
    Section_Rectangles: "Παραλληλόγραμμα τμήματα",
    Section_Squares: "Τετράγωνα τμήματα",
    Section_Triangle: "Τμήματα τριγώνου",
    Target: "Στόχος",
    Venn01: "Venn 01",
    Venn02: "Venn 02",
    Venn03: "Venn 03",
    Venn04: "Venn 04",
    Venn05: "Venn 05",
    Venn06_Blue: "Venn 06, μπλε",
    Venn07_Blue: "Venn 07, μπλε",
    Venn08: "Venn 08",
    Blackboard: "Πίνακας",
    Books: "Βιβλία",
    Books1: "Βιβλία 1",
    books2: "Βιβλία 2",
    Chalk: "Κιμωλία",
    clipboard: "Πρόχειρο",
    clock: "Ρολόι",
    Globe: "Υδρόγειος",
    Glue: "Κόλλα",
    GraduationCap: "Καπέλο αποφοίτησης",
    magnifyingglass: "Μεγεθυντικός φακός",
    Microscope: "Μικροσκόπιο",
    Notebook: "Τετράδιο σημειώσεων",
    notepad1: "Σημειωματάριο 1",
    notepad2: "Σημειωματάριο 2",
    notepad3: "Σημειωματάριο 3",
    PaperClip_Blue: "Συνδετήρας (μπλε)",
    PaperClip_Red: "Συνδετήρας (κόκκινος)",
    Pencil: "Μολύβι",
    Ruler: "Χάρακας",
    TestTubes: "Δοκιμαστικοί σωλήνες",
    thumbtack: "Πινέζα",
    clouds: "Σύννεφα",
    DrippingFaucet: "Βρύση που στάζει",
    Earth: "Γη",
    EndangeredAnimals1: "Απειλούμενα ζώα 1",
    EndangeredAnimals2: "Απειλούμενα ζώα 2",
    GreenCar: "Οικολογικό αυτοκίνητο",
    GreenFactory: "Οικολογικό εργοστάσιο",
    GreenHouse: "Οικολογικό σπίτι",
    Leaf1: "Φύλλο 1",
    Leaf2: "Φύλλο 2",
    lightbulb: "Λαμπτήρας",
    LightBulb_Flourescent_Off: "Λαμπτήρας φθορισμού, σβηστός",
    LightBulb_Flourescent_On: "Λαμπτήρας φθορισμού, αναμμένος",
    LightBulb_Standard_Off1: "Απλός λαμπτήρας, σβηστός 1",
    LightBulb_Standard_Off2: "Απλός λαμπτήρας, σβηστός 2",
    LightBulb_Standard_On: "Απλός λαμπτήρας, αναμμένος",
    lightningcloud: "Σύννεφο με αστραπή",
    Pollution_Car: "Μη οικολογικό αυτοκίνητο",
    Pollution_Factory: "Μη οικολογικό εργοστάσιο",
    Raindrop: "Σταγόνα βροχής",
    RecycleBin: "Κάδος ανακύκλωσης",
    RecycleSymbol: "Σύμβολο ανακύκλωσης",
    RenewableEnergySymbol: "Σύμβολο ανανεώσιμης ενέργειας",
    RenewableEnergy_Solar: "Ανανεώσιμη ενέργεια - Ήλιος",
    RenewableEnergy_Water: "Ανανεώσιμη ενέργεια - Νερό",
    RenewableEnergy_Wind: "Ανανεώσιμη ενέργεια - Άνεμος",
    sun: "Ήλιος",
    Sun1: "Ήλιος 1",
    Sun2: "Ήλιος 2",
    sundandcloud: "Ήλιος και σύννεφο",
    world: "Κόσμος",
    Agreement: "Συμφωνία",
    ATM01: "ATM 01",
    ATM02: "ATM 02",
    Balance_Balanced1: "Ζυγός σε θέση ισορροπίας 1",
    Balance_Balanced2: "Ζυγός σε θέση ισορροπίας 2",
    Balance_Unbalanced1: "Ζυγός με βάρος 1",
    Balance_Unbalanced2: "Ζυγός με βάρος 2",
    Calculator: "Αριθμομηχανή",
    Chart_Decrease1: "Γράφημα, πτωτική τάση 1",
    Chart_Decrease2: "Γράφημα, πτωτική τάση 2",
    Chart_Increase1: "Γράφημα, ανοδική τάση 1",
    Chart_Increase2: "Γράφημα, ανοδική τάση 2",
    Chart_Plateau: "Γράφημα, σταθεροποίηση",
    Check: "Επιταγή",
    Contract: "Σύμβαση",
    CreditCard_Black: "Πιστωτική κάρτα (μαύρη)",
    CreditCard_Cut: "Πιστωτική κάρτα (κομμένη)",
    CreditCard_Gold: "Πιστωτική κάρτα (χρυσή)",
    Currency_Dollar: "Δολάριο",
    Currency_Dollars: "Δολάρια",
    Currency_Stack: "Χαρτονομίσματα",
    Currency_StackCoins: "Χαρτονομίσματα και κέρματα",
    GoldBar: "Ράβδος χρυσού",
    GoldBar_Stack: "Στοίβα ράβδων χρυσού",
    MoneyBag01: "Σάκος χρηματαποστολής 01",
    MoneyBag02: "Σάκος χρηματαποστολής 02",
    PercentSign: "Σύμβολο ποσοστού επί τοις εκατό",
    PiggyBank01_Broken: "Κουμπαράς 01, σπασμένος",
    PiggyBank02_Broken: "Κουμπαράς 02, σπασμένος",
    PiggyBank_Coins: "Κουμπαράς (κέρματα)",
    PiggyBank_Currency: "Κουμπαράς (χαρτονομίσματα)",
    Portfolio: "Χαρτοφύλακας",
    PriceTag: "Ετικέτα τιμής",
    Safe_Closed: "Κλειστό χρηματοκιβώτιο",
    Safe_Empty: "Άδειο χρηματοκιβώτιο",
    Safe_Full: "Γεμάτο χρηματοκιβώτιο",
    Seal_Gold: "Χρυσή σφραγίδα",
    Seal_Red: "Κόκκινή σφραγίδα",
    Seal_Silver: "Ασημένια σφραγίδα",
    Wallet_Empty: "Άδειο πορτοφόλι",
    Wallet_Full1: "Γεμάτο πορτοφόλι 1",
    Wallet_Full2: "Γεμάτο πορτοφόλι 2",
    BusinessPerson_Female6: "Γυναίκα επιχειρηματίας 6",
    BusinessPerson_Male3: "Άντρας επιχειρηματίας 3",
    Computer_User_Female1: "Γυναίκα χρήστης υπολογιστή 1",
    ConstructionWorker2: "Εργάτης 2",
    Presenter_Female1: "Παρουσιάστρια 1",
    Component_Circle01_Transparent_DarkBlue: "Κύκλος 01, διαφανής, σκούρο μπλε",
    Component_Circle02_Transparent_Bule: "Κύκλος 02, διαφανής, μπλε",
    Component_Circle03_Transparent_Green: "Κύκλος 03, διαφανής, πράσινο",
    Component_Circle04_Transparent_Orange: "Κύκλος 04, διαφανής, πορτοκαλί",
    Component_Circle05_Transparent_Red: "Κύκλος 05, διαφανής, κόκκινο",
    Component_Cube01_DarkBlue: "Κύβος 01, σκούρο μπλε",
    Component_Cube02_LightBlue: "Κύβος 02, ανοιχτό μπλε",
    Component_Cube03_Green: "Κύβος 03, πράσινο",
    Component_Cube04_Orange: "Κύβος 04, πορτοκαλί",
    Component_Cube05_DarkRed: "Κύβος 05, σκούρο κόκκινο",
    Component_Cuboid01_DarkBlue: "Κυβοειδές 01, σκούρο μπλε",
    Component_Cuboid02_Blue: "Κυβοειδές 02, μπλε",
    Component_Cuboid03_Green: "Κυβοειδές 03, πράσινο",
    Component_Cuboid04_Orange: "Κυβοειδές 04, πορτοκαλί",
    Component_Cuboid05_Red: "Κυβοειδές 05, κόκκινο",
    Component_Gear01_DarkBlue: "Γρανάζι 01, σκούρο μπλε",
    Component_Gear02_LightBlue: "Γρανάζι 02, ανοιχτό μπλε",
    Component_Gear03_Green: "Γρανάζι 03, πράσινο",
    Component_Gear04_DarkRed: "Γρανάζι 04, σκούρο κόκκινο",
    Component_Gear05_Orange: "Γρανάζι 05, πορτοκαλί",
    Component_Person01_DarkBlue: "Πρόσωπο 01, σκούρο μπλε",
    Component_Person02_Blue: "Πρόσωπο 02, μπλε",
    Component_Person03_Green: "Πρόσωπο 03, πράσινο",
    Component_Person04_DarkRed: "Πρόσωπο 04, σκούρο κόκκινο",
    Component_Person05_Orange: "Πρόσωπο 05, πορτοκαλί",
    Component_PuzzlePiece01_DarkBlue: "Κομμάτι παζλ 01, σκούρο μπλε",
    Component_PuzzlePiece02_Blue: "Κομμάτι παζλ 02, μπλε",
    Component_PuzzlePiece03_Green: "Κομμάτι παζλ 03, πράσινο",
    Component_PuzzlePiece04_Red: "Κομμάτι παζλ 04, κόκκινο",
    Component_PuzzlePiece05_Orange: "Κομμάτι παζλ 05, πορτοκαλί",
    Component_Sphere01_DarkBlue: "Σφαίρα 01, σκούρο μπλε",
    Component_Sphere02_LightBlue: "Σφαίρα 02, ανοιχτό μπλε",
    Component_Sphere03_Green: "Σφαίρα 03, Πράσινο",
    Component_Sphere04_DarkRed: "Σφαίρα 04, σκούρο κόκκινο",
    Component_Sphere05_Orange: "Σφαίρα 05, πορτοκαλί",
    Book: "Βιβλίο",
    Box01: "Κουτί 01",
    Box02: "Κουτί 02",
    Bulb01_Yellow: "Κίτρινη λάμπα 01",
    Bulb02_Yellow: "Κίτρινη λάμπα 02",
    Calendar: "Ημερολόγιο",
    Chart: "Γράφημα",
    Clipboard: "Πρόχειρο",
    Clock: "Ρολόι",
    Compass: "Πυξίδα",
    Flag01_Red: "Σημαία 01, κόκκινη",
    Flag02_Green: "Σημαία 02, πράσινη",
    Flag03_Blue: "Σημαία 03, μπλε",
    Gift: "Δώρο",
    House: "Σπίτι",
    Icon_Computer01_White: "Εικονίδιο υπολογιστή 01, λευκό",
    Icon_Computer02_Black: "Εικονίδιο υπολογιστή 02, μαύρο",
    Icon_Disk01_Blue: "Εικονίδιο δισκέτας 01, μπλε",
    Icon_Disk02_Green: "Εικονίδιο δισκέτας 02, πράσινο",
    Icon_Document01_Grey: "Εικονίδιο εγγράφου 01, γκρι",
    Icon_Document02_Grey: "Εικονίδιο εγγράφου 02, γκρι",
    Icon_Document03_Blue: "Εικονίδιο εγγράφου 03, μπλε",
    Icon_Document04_Blue: "Εικονίδιο εγγράφου 04, μπλε",
    Icon_Envelope01_Blue: "Εικονίδιο ταχυδρομικού φακέλου 01, μπλε",
    Icon_Envelope02_Yellow: "Εικονίδιο ταχυδρομικού φακέλου 02, κίτρινο",
    Icon_Envelope03_Open_Yellow: "Εικονίδιο ανοιχτού ταχυδρομικού φακέλου 03, κίτρινο",
    Icon_Envelope04_Open_Yellow: "Εικονίδιο ανοιχτού ταχυδρομικού φακέλου 04, κίτρινο",
    Icon_Folder01_Yellow: "Εικονίδιο φακέλου 01, κίτρινο",
    Icon_Folder02_Yellow: "Εικονίδιο φακέλου 02, κίτρινο",
    Icon_Folder03_Open_Yellow: "Εικονίδιο ανοιχτού φακέλου 03, κίτρινο",
    Icon_Folder04_Open_Yellow: "Εικονίδιο ανοιχτού φακέλου 04, κίτρινο",
    Icon_Gear01_Grey: "Εικονίδιο γραναζιού 01, γκρι",
    Icon_Gear02_Blue: "Εικονίδιο γραναζιού 02, μπλε",
    Icon_Network01_Blue: "Εικονίδιο δικτύου 01, μπλε",
    Icon_Network02: "Εικονίδιο δικτύου 02",
    Icon_Pencil01: "Εικονίδιο μολυβιού 01",
    Icon_Pencil02: "Εικονίδιο μολυβιού 02",
    Icon_Printer01_White: "Εικονίδιο εκτυπωτή 01, λευκό",
    Icon_Printer02_Black: "Εικονίδιο εκτυπωτή 02, μαύρο",
    Key01: "Κλειδί 01",
    Key02: "Κλειδί 02",
    Lock01_Yellow: "Λουκέτο 01, κίτρινο",
    Lock02_Yellow: "Λουκέτο 02, κίτρινο",
    Lock03_Blue: "Λουκέτο 03, μπλε",
    Lock04_Blue: "Λουκέτο 04, μπλε",
    Magnet: "Μαγνήτης",
    MagnifyingGlass: "Μεγεθυντικός φακός",
    Medal: "Παράσημο",
    Notebook: "Τετράδιο σημειώσεων",
    Phone: "Τηλέφωνο",
    PieChart: "Γράφημα πίτας",
    Pin: "Πινέζα",
    PuzzlePiece: "Κομμάτι παζλ",
    PuzzlePieces: "Κομμάτια παζλ",
    Roadblock: "Κώνος απαγόρευσης κυκλοφορίας",
    Scissors: "Ψαλίδι",
    Shield01: "Ασπίδα 01",
    Shield02_Orange: "Ασπίδα 02, πορτοκαλί",
    Shield03_Blue: "Ασπίδα 03, μπλε",
    Sign_Ban01: "Σήμα απαγόρευσης 01",
    Sign_Ban02: "Σήμα απαγόρευσης 02",
    Sign_CheckBox01: "Τετραγωνίδιο επιλογής 01",
    Sign_CheckBox02_Unchecked: "Τετραγωνίδιο επιλογής 02, μη επιλεγμένο",
    Sign_Checkmark01_Green: "Σημάδι επιλογής 01, πράσινο",
    Sign_Checkmark02_Green: "Σημάδι επιλογής 02, πράσινο",
    Sign_DoNotEnter: "Απαγορευτικό σήμα",
    Sign_Error01: "Σήμα σφάλματος 01",
    Sign_Error02: "Σήμα σφάλματος 02",
    Sign_ExclamationPoint01_Red: "Θαυμαστικό 01, κόκκινο",
    Sign_ExclamationPoint02_Orange: "Θαυμαστικό 02, πορτοκαλί",
    Sign_Help01_Green: "Σήμα βοήθειας (εικονίδιο λατινικού ερωτηματικού) 01, πράσινο",
    Sign_Help02_Blue: "Σήμα βοήθειας (εικονίδιο λατινικού ερωτηματικού) 02, μπλε",
    Sign_Information: "Σήμα πληροφοριών",
    Sign_Null: "Σύμβολο κενού",
    Sign_QuestionMark01_Blue: "Λατινικό ερωτηματικό 01, μπλε",
    Sign_QuestionMark02_Red: "Λατινικό ερωτηματικό 02, κόκκινο",
    Sign_RadioButton01: "Κουμπί επιλογής 01",
    Sign_RadioButton02_Unchecked: "Κουμπί επιλογής 02, μη επιλεγμένο",
    Sign_Warning01_Red: "Σήμα προειδοποίησης 01, κόκκινο",
    Sign_Warning02_Orange: "Σήμα προειδοποίησης 02, πορτοκαλί",
    Sign_X01_Red: "Σύμβολο X 01, κόκκινο",
    Sign_X02_Red: "Σύμβολο X 02, κόκκινο",
    Star_Yellow: "Κίτρινο αστέρι",
    Wrench: "Εργαλεία",
    Airplane_Blue: "Μπλε αεροπλάνο",
    Bicycle_Blue: "Μπλε ποδήλατο",
    Bus: "Λεωφορείο",
    Canoe_Blue: "Μπλε βάρκα",
    Car_Red: "Κόκκινο αυτοκίνητο",
    Helicopter_Blue: "Μπλε ελικόπτερο",
    Motorcycle_Red: "Κόκκινη μηχανή",
    Pedestrian_Blue: "Σήμα πεζών (μπλε χρώμα)",
    PersonalTransporter_Green: "Δίτροχος προσωπικός μεταφορέας (πράσινο χρώμα)",
    Sailboat_Red: "Ιστιοπλοϊκό με κόκκινη ρίγα",
    Scooter_Orange: "Πορτοκαλί μηχανή μικρού κυβισμού (σκούτερ)",
    Train_Red: "Κόκκινο τρένο",
    Truck_Blue: "Μπλε φορτηγό",
    
    aria_category_selector: "Επιλογή κατηγορίας εικόνων",
    filterImageGallery: "Φιλτράρισμα έκθεσης εικόνων"

})
