﻿/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        fileMenu: "Αρχείο",
        fileMenu_New: "Δημιουργία",
        fileMenu_NewDocument: "Έγγραφο",
        fileMenu_NewFromTemplate: "Από πρότυπο",
        fileMenu_NewDocumentfromTemplate: "Έγγραφο από πρότυπο",
        fileMenu_NewPresentation: "Παρουσίαση",
        fileMenu_NewPresentationfromTemplate: "Παρουσίαση από πρότυπο",
        fileMenu_NewSpreadsheet: "Υπολογιστικό φύλλο",
        fileMenu_NewSpreadsheetFromTemplate: "Υπολογιστικό φύλλο από πρότυπο",
        fileMenu_Open: "Άνοιγμα",
        fileMenu_Import: "Εισαγωγή...",
        //	fileMenu_Close: "Close",
        fileMenu_Discard: "Επαναφορά στην τελευταία εκδοχή",
        fileMenu_ClearTrackChange: "Αφαίρεση επισημάνσεων αλλαγών",
        fileMenu_SpreadsheetSettings: "Ορισμός ρύθμισης γλώσσας/περιοχής εγγράφου...",
        filemenu_revisionhistory: "Αναθεωρήσεις",
        fileMenu_Save: "Αποθήκευση",
        fileMenu_SaveAs: "Αντιγραφή...",
        fileMenu_AutoPublish: "Αυτόματη δημοσίευση",
        fileMenu_AutoCheckIn: "Αυτόματη επιστροφή ελέγχου",
        fileMenu_PublishVersion: "Άμεση δημοσίευση",
        fileMenu_AutoPublish2: "Αυτόματη αποθήκευση στο χώρο αποθήκευσης",
        //	fileMenu_AutoPublish_Tips: "Makes your changes available to readers at the end of each editing session.",
        fileMenu_PublishVersion2: "Άμεση αποθήκευση στο χώρο αποθήκευσης",
        fileMenu_AutoPublish3: "Αυτόματη αποθήκευση σε ${0}",
        fileMenu_PublishVersion3: "Άμεση αποθήκευση σε ${0}",      
        fileMenu_SubmitForReview: "Υποβολή για εξέταση...",
        fileMenu_CheckinVersion: "Επιστροφή ελέγχου...",
        fileMenu_Unlock: "Ξεκλείδωμα",
        //	fileMenu_SaveAsDraft: "as Draft",
        //	fileMenu_SaveInMyDocs: "in My Documents",
        //	fileMenu_SaveToSymphony: "to Lotus Symphany",
        fileMenu_DownloadAs: "Μεταφόρτωση ως",
        fileMenu_PDF: "PDF",
        fileMenu_ODF: "ODF",
        fileMenu_DOC: "Microsoft Word 97 - 2007 (*.doc)",
        fileMenu_ODS: "ODS",
        fileMenu_XLS: "Microsoft Excel 97 -2007 (*.xls) ",
        fileMenu_ShareWith: "Κοινή χρήση...",
        fileMenu_ExportAsPDF: "PDF",
        fileMenu_ExportAsODF: "ODF",
        fileMenu_ExportAsPPT: "Microsoft Powerpoint 97 - 2007 (*.ppt)",
        //	fileMenu_WebPreview: "Web Preview",
        fileMenu_PrintToPDF: "Εκτύπωση ως PDF...",
        fileMenu_ViewFileDetails: "Προβολή λεπτομερειών αρχείου...",
        fileMenu_RecentFile: "Πρόσφατα αρχεία",
        fileMenu_Open: "Άνοιγμα",
        fileMenu_Download: "Μεταφόρτωση",
        fileMenu_Print: "Εκτύπωση",
        fileMenu_Export: "Εξαγωγή",
        fileMenu_ExportToCSV: "CSV",
        fileMenu_ExportToPDF: "PDF (.pdf)",
        fileMenu_ExportToMarkdown: "Markdown (.md)",
        fileMenu_ExportToMS: "Μορφή Microsoft Office (.${FILEEXTENSION})",
        fileMenu_ExportToODF: "Μορφή Open Document (.${FILEEXTENSION})",
        fileMenu_PgSetup: "Ρύθμιση σελίδας...",

        editMenu: "Τροποποίηση",
        editMenu_Undo: "Αναίρεση",
        editMenu_Redo: "Ακύρωση αναίρεσης",
        editMenu_Cut: "Αποκοπή",
        editMenu_Copy: "Αντιγραφή",
        editMenu_Paste: "Επικόλληση",
        editMenu_DeleteSlide: "Διαγραφή διαφάνειας",
        editMenu_SelectAll: "Επιλογή όλων",
        editMenu_Find: "Εύρεση...",
        editMenu_Replace: "Αντικατάσταση...",
        editMenu_FindReplace: "Εύρεση και αντικατάσταση...",
        editMenu_EditLink: "Προσθήκη ή τροποποίηση διασύνδεσης",
        editMenu_DeleteSheet: "Διαγραφή φύλλου...",
        editMenu_RenameSheet: "Μετονομασία φύλλου...",
        editMenu_HideSheet: "Απόκρυψη φύλλου",
        editMenu_MoveSheet: "Μετακίνηση φύλλου...",
        editMenu_DeleteRow: "Διαγραφή γραμμής",
        editMenu_DeleteColumn: "Διαγραφή στήλης",
        editMenu_DeleteCellLeft: "Διαγραφή κελιών και μετακίνηση προς τα αριστερά",
        editMenu_DeleteCellUp: "Διαγραφή κελιών και μετακίνηση προς τα πάνω",
        editMenu_ClearCell: "Διαγραφή περιεχομένου",

        viewMenu: "Προβολή",
        viewMenu_Master: "Υπόδειγμα",
        viewMenu_Notifications: "Ειδοποιήσεις",
        viewMenu_SlideSorter: "Ταξινόμηση διαφανειών",
        viewMenu_SpeakerNotes: "Σημειώσεις ομιλητή",
        viewMenu_Toolbar_Basic: "Βασική",
        viewMenu_Toolbar_Advanced: "Σύνθετη",
        viewMenu_Toolbar_None: "Καμία",
        viewMenu_Toolbar: "Γραμμή εργαλείων",
        viewMenu_Statusbar: "Γραμμή κατάστασης",
        viewMenu_Navigator: "Πλοηγός...",
        //viewMenu_Sidebar: "Sidebar",
        viewMenu_ShowHideIndicators: "Εμφάνιση ενδείξεων συνεργατικής επεξεργασίας",
        viewMenu_Assignment: "Ενδείξεις ανάθεσης",
        viewMenu_Bookmark: "Σελιδοδείκτες",
        viewMenu_Coediting: "Επισημάνσεις συνεργατικής επεξεργασίας",
        viewMenu_Rulers: "Χάρακες",
        viewMenu_WebLayout: "Διαδικτυακή διάταξη",
        viewMenu_AutomaticSpellCheck: "Ορθογραφικός έλεγχος κατά την πληκτρολόγηση",
        viewMenu_Formulabar: "Γραμμή τύπων",
        viewMenu_moveRight: "Μετακίνηση δείκτη προς τα δεξιά με το πλήκτρο Enter",
        viewMenu_showFullString: "Ανάπτυξη περιεχομένου στα κελιά",
        viewMenu_Doc: "Προβολή εγγράφου",
        viewMenu_Templates: "Πρότυπα",
        viewMenu_GridLines: "Απόκρυψη γραμμών πλέγματος",
        viewMenu_UnsupportWarning: "Εμφάνιση μηνυμάτων μη υποστηριζόμενων λειτουργιών",
        viewMenu_HiddenSheets: "Κρυφά φύλλα",
        viewMenu_FreezeRows: "Σταθεροποίηση γραμμών",
        viewMenu_FreezeColumns: "Σταθεροποίηση στηλών",
        viewMenu_NoFrozenRows: "Δεν υπάρχουν σταθεροποιημένες γραμμές.",
        viewmenu_NoFrozenColumns: "Δεν υπάρχουν σταθεροποιημένες στήλες.",
        viewMenu_FreezeXRows: "Σταθεροποίηση ${0} γραμμών",
        viewMenu_FreezeOneRow: "Σταθεροποίηση ${0} γραμμής",
        viewMenu_FreezeXColumns: "Σταθεροποίηση ${0} στηλών",
        viewMenu_FreezeOneColumn: "Σταθεροποίηση ${0} στήλης",
        viewMenu_CarriageReturn: "Σημάδια μορφοποίησης",
        viewMenu_Navigation: "Πλαίσιο πλοήγησης",
        viewMenu_ACL: "Τροποποιήσιμες περιοχές",
        viewMenu_GridOnOff: "Γραμμές πλέγματος",
        viewMenu_ObserverMode: 'Κατάσταση παρατηρητή',

        createMenu: "Εισαγωγή",
        createMenu_NewSlide: "Νέα διαφάνεια",
        createMenu_DuplicateSlide: "Αντίγραφο διαφάνειας",
        createMenu_ImageFromFile: "Εικόνα...",
        createMenu_TextBox: "Πλαίσιο κειμένου",
        createMenu_Shape: "Σχήμα",
        createMenu_break: "Αλλαγή",
        createMenu_RowAbove: "Γραμμή πάνω",
        createMenu_RowBelow: "Γραμμή κάτω",
        createMenu_ColumnRight: "Στήλη δεξιά",
        createMenu_ColumnLeft: "Στήλη αριστερά",
        createMenu_Sheet: "Φύλλο...",
        createMenu_Image: "Εικόνα...",
        createMenu_Comments: "Σχόλιο...",
        createMenu_WebLink: "Διαδικτυακή διασύνδεση...",
        createMenu_SpecialCharacter: "Ειδικός χαρακτήρας...",
        createMenu_Function: "Συνάρτηση...",
        createMenu_Fromtemplate: "Δημιουργία από πρότυπο",

        insertMenu: "Εισαγωγή",
        insertMenu_break: "Αλλαγή σελίδας",
        insertMenu_sectionbreak: "Αλλαγή ενότητας",
        insertMenu_Bookmark: "Σελιδοδείκτης...",
        insertMenu_WebLink: "Διασύνδεση...",
        insertMenu_SpecialCharacter: "Ειδικός χαρακτήρας...",
        insertMenu_HorizontalLine: "Οριζόντια γραμμή",
        insertMenu_Header: "Κεφαλίδα",
        insertMenu_Footer: "Υποσέλιδο",
        insertMenu_TableOfContents: "Πίνακας περιεχομένων",

        insertMenu_HeaderFooter: "Κεφαλίδα/Υποσέλιδο",
        insertMenu_HF_Edit: "Τροποποίηση",
        insertMenu_HF_Hide: "Απόκρυψη",
        insertMenu_Endnotes: "Σημειώσεις τέλους",
        insertMenu_RowAbove: "Γραμμή πάνω",
        insertMenu_PageNumber: "Αριθμός σελίδας",
        insertMenu_PageNumberTop: "Αρχή σελίδας",
        insertMenu_PageNumberBottom: "Τέλος σελίδας",
        insertMenu_PageNumberCurr: "Τρέχουσα θέση",
        insertMenu_TotalPageNumber: "Σελίδα 1 από Ν",
        insertMenu_Date: "Ημερομηνία...",
        insertMenu_Time: "Ώρα...",
        insertMenu_Fields: "Πεδία",
        //    insertMenu_Comment: "Comment",
        insertMenu_CellRight: "Κελιά και μετακίνηση προς τα δεξιά",
        insertMenu_CellDown: "Κελιά και μετακίνηση προς τα κάτω",
        insertMenu_RowBelow: "Γραμμή κάτω",
        insertMenu_ColumnBefore: "Στήλη πριν",
        insertMenu_ColumnAfter: "Στήλη μετά",
        insertMenu_Sheet: "Φύλλο...",
        insertMenu_Image: "Εικόνα...",
        insertMenu_DuplicateSheet: "Δημιουργία διπλότυπου φύλλου",
        insertMenu_Function: "Συνάρτηση",
        insertMenu_FunctionSum: "SUM",
        insertMenu_FunctionAverage: "AVERAGE",
        insertMenu_FunctionCount: "COUNT",
        insertMenu_FunctionMax: "MAX",
        insertMenu_FunctionMin: "MIN",
        insertMenu_FunctionMore: "Περισσότερες συναρτήσεις...",
        insertMenu_NameRange: "Επώνυμη περιοχή",
        insertMenu_NameRangeNew: "Δημιουργία περιοχής...",
        insertMenu_NameRangeManage: "Διαχείριση περιοχών...",
        insertMenu_Chart: "Γράφημα...",

        contextMenu_insertCellRight: "Εισαγωγή κελιών και μετακίνηση προς τα δεξιά",
        contextMenu_insertCellDown: "Εισαγωγή κελιών και μετακίνηση προς τα κάτω",
        contextMenu_InsertRowAbove: "Εισαγωγή γραμμής πάνω",
        contextMenu_InsertRowBelow: "Εισαγωγή γραμμής κάτω",
        contextMenu_InsertColumnBefore: "Εισαγωγή στήλης πριν",
        contextMenu_InsertColumnAfter: "Εισαγωγή στήλης μετά",
        contextMenu_DownloadImage: "Μεταφόρτωση ως εικόνας",

        formatMenu: "Μορφή",
        formatMenu_Columns: "Στήλες",
        formatMenu_DefaultFormatting: "Προεπιλεγμένη μορφοποίηση",
        formatMenu_Template: "Στυλ...",
        contextMenu_Template: "Στυλ πίνακα...",
        formatMenu_LineSpacing: "Διάστιχο",
        formatMenu_LineSpacing1: "1",
        formatMenu_LineSpacing12: "1,2",
        formatMenu_LineSpacing15: "1,5",
        formatMenu_LineSpacing2: "2",
        formatMenu_LineSpacing25: "2,5",
        formatMenu_LineSpacing3: "3",
        formatMenu_TextProperties: "Ιδιότητες κειμένου",
        formatMenu_PageBreakBefore: "Αλλαγή σελίδας πριν από",
        formatMenu_KeepLines: "Διατήρηση γραμμών μαζί",
        formatMenu_WidowControl: "Έλεγχος χήρων/ορφανών",
        formatMenu_Pagination: "Ιδιότητες παραγράφου",
        formatMenu_Bold: "Έντονη γραφή",
        formatMenu_Italic: "Πλάγια γραφή",
        formatMenu_Underline: "Υπογράμμιση",
        formatMenu_Strikethrough: "Διαγράμμιση",
        formatMenu_IncreaseSize: "Αύξηση μεγέθους γραμματοσειράς",
        formatMenu_DecreaseSize: "Μείωση μεγέθους γραμματοσειράς",
        formatMenu_ImageProperties: "Ιδιότητες εικόνας...",
        formatMenu_ChartProperties: "Ιδιότητες γραφήματος...",
        formatMenu_EditChart: "Τροποποίηση γραφήματος",
        formatMenu_InsertChart: "Εισαγωγή γραφήματος",
        formatMenu_Properties: "Ιδιότητες...",
        formatMenu_Heading: "Επικεφαλίδα",
        formatMenu_Normal: "Κανονική",
        formatMenu_Title: "Τίτλος",
        formatMenu_Subtitle: "Υπότιτλος",
        formatMenu_Heading1: "Επικεφαλίδα 1",
        formatMenu_Heading2: "Επικεφαλίδα 2",
        formatMenu_Heading3: "Επικεφαλίδα 3",
        formatMenu_Heading4: "Επικεφαλίδα 4",
        formatMenu_Heading5: "Επικεφαλίδα 5",
        formatMenu_Heading6: "Επικεφαλίδα 6",
        formatMenu_Heading7: "Επικεφαλίδα 7",
        formatMenu_Heading8: "Επικεφαλίδα 8",
        formatMenu_Heading9: "Επικεφαλίδα 9",
        formatMenu_BulletedList: "Λίστα με κουκίδες",
        formatMenu_NumberedList: "Αριθμημένη λίστα",
        formatMenu_OutLine: "Λίστα πολλαπλών επιπέδων",
        formatMenu_Superscript: "Εκθέτης",
        formatMenu_Subscript: "Δείκτης",
        formatMenu_Align: "Στοίχιση",
        formatMenu_Left: "Αριστερά",
        formatMenu_Right: "Δεξιά",
        formatMenu_Center: "Στο κέντρο",
        formatMenu_Justify: "Πλήρης στοίχιση",
        formatMenu_Text_Direction: "Κατεύθυνση κειμένου",
        formatMenu_Ltr: "Αριστερά προς δεξιά",
        formatMenu_Rtl: "Δεξιά προς αριστερά",
        formatMenu_LineSpacing: "Διάστιχο",
        formatMenu_LineSpacing1: "1,0",
        formatMenu_LineSpacing115: "1,15",
        formatMenu_LineSpacing15: "1,5",
        formatMenu_LineSpacing2: "2,0",
        formatMenu_LineSpacing25: "2,5",
        formatMenu_LineSpacing3: "3,0",
        formatMenu_Top: "Πάνω",
        formatMenu_Bottom: "Κάτω",
        formatMenu_Middle: "Στη μέση",
        formatMenu_Direction: "Κατεύθυνση κειμένου",
        formatMenu_Rtl: "Δεξιά προς αριστερά",
        formatMenu_Ltr: "Αριστερά προς δεξιά",
        formatMenu_Auto: "Συμφραστικά",
        formatMenu_SheetDirection: "Κατεύθυνση φύλλου",
        formatMenu_SheetRtl: "Δεξιά προς αριστερά",
        formatMenu_SheetLtr: "Αριστερά προς δεξιά",
        formatMenu_Indent: "Αύξηση εσοχής",
        formatMenu_DecreaseIndent: "Μείωση εσοχής",
        formatMenu_ClearFormat: "Εκκαθάριση μορφοποίησης",
        formatMenu_RowHeight: "Ύψος γραμμής",
        formatMenu_ColumnWidth: "Πλάτος στήλης",
        formatMenu_ShowRow: "Εμφάνιση γραμμής",
        formatMenu_HideRow: "Απόκρυψη γραμμής",
        formatMenu_ShowColumn: "Εμφάνιση στήλης",
        formatMenu_HideColumn: "Απόκρυψη στήλης",
        formatMenu_WrapText: "Αναδίπλωση κειμένου",
        formatMenu_Number: "Αριθμός",
        formatMenu_FontArial: "Arial",
        formatMenu_FontComicSansMS: "Comic Sans MS",
        formatMenu_FontCourierNew: "Courier New",
        formatMenu_FontGeorgia: "Georgia",
        formatMenu_FontLucidaSansUnicode: "Lucida Sans Unicode",
        formatMenu_FontTahoma: "Tahoma",
        formatMenu_FontTimesNewRoman: "Times New Roman",
        formatMenu_FontTrebuchetMS: "Trebuchet MS",
        formatMenu_FontVerdana: "Verdana",
        formatMenu_FontName: "Γραμματοσειρά",

        layoutMenu: "Διάταξη",
        layoutMenu_SlideLayout: "Διάταξη διαφανειών...",
        layoutMenu_SlideDesign: "Στυλ υποδείγματος...",
        layoutMenu_DefaultFormatting: "Προεπιλεγμένη μορφοποίηση",
        layoutMenu_Textprop_Bold: "Έντονη γραφή",
        layoutMenu_Textprop_Italic: "Πλάγια γραφή",
        layoutMenu_Textprop_Underline: "Υπογράμμιση",
        layoutMenu_Textprop_Strikethrough: "Διαγράμμιση",
        layoutMenu_TextProp: "Ιδιότητες κειμένου",
        LayoutMenu_RowHeight: "Ύψος γραμμής...",
        LayoutMenu_ColumnWidth: "Πλάτος στήλης...",
        LayoutMenu_ShowRow: "Εμφάνιση γραμμής",
        LayoutMenu_HideRow: "Απόκρυψη γραμμής",
        LayoutMenu_RenameSheet: "Μετονομασία φύλλου...",
        LayoutMenu_MoveSheet: "Μετακίνηση φύλλου",

        tableMenu: "Πίνακας",
        tableMenu_Create: "Δημιουργία...",
        tableMenu_CreateFromTemplate: "Δημιουργία από πρότυπο",
        tableMenu_Delete: "Διαγραφή",
        tableMenu_SetTableColor: "Χρώμα κελιών",
        tableMenu_CreateTable: "Δημιουργία πίνακα",
        tableMenu_Cell: "Κελί",
        tableMenu_CellMergeCells: "Συγχώνευση κελιών",
        tableMenu_CellAlignLeft: "Στοίχιση αριστερά",
        tableMenu_CellAlignCenter: "Στοίχιση στο κέντρο",
        tableMenu_CellAlignRight: "Στοίχιση δεξιά",
        tableMenu_CellClearContents: "Εκκαθάριση περιεχομένου",
        tableMenu_CellProperties: "Ιδιότητες κελιού...",
        tableMenu_Row: "Γραμμή",
        tableMenu_InsertRowAbove: "Εισαγωγή γραμμής πάνω",
        tableMenu_InsertRowBelow: "Εισαγωγή γραμμής κάτω",
        tableMenu_MoveRowAbove: "Μετακίνηση γραμμής προς τα πάνω",
        tableMenu_MoveRowBelow: "Μετακίνηση γραμμής προς τα κάτω",
        tableMenu_RowInsertRow: "Εισαγωγή γραμμής...",
        tableMenu_RowInsertRowAbove: "Εισαγωγή γραμμής πάνω",
        tableMenu_RowInsertRowBelow: "Εισαγωγή γραμμής κάτω",
        tableMenu_RowMoveRowAbove: "Μετακίνηση γραμμής πάνω",
        tableMenu_RowMoveRowBelow: "Μετακίνηση γραμμής κάτω",
        tableMenu_RowDelete: "Διαγραφή",
        tableMenu_RowRepeat: "Επανάληψη γραμμής κεφαλίδας",
        tableMenu_InsertColumnBefore: "Εισαγωγή στήλης πριν",
        tableMenu_InsertColumnAfter: "Εισαγωγή στήλης μετά",
        tableMenu_MoveColumnBefore: "Μετακίνηση στήλης αριστερά",
        tableMenu_MoveColumnAfter: "Μετακίνηση στήλης δεξιά",
        tableMenu_ResizeColumn: "Αλλαγή μεγέθους στήλης",
        tableMenu_ResizeColumns: "Αλλαγή μεγέθους στηλών",
        tableMenu_MarkasCategory: "Επισήμανση ως κατηγορίας",
        tableMenu_ColumnInsertColumn: "Εισαγωγή στήλης...",
        tableMenu_ColumnAddColumnBefore: "Εισαγωγή στήλης πριν",
        tableMenu_ColumnAddColumnAfter: "Εισαγωγή στήλης μετά",
        tableMenu_ColumnMoveColumnAfter: "Μετακίνηση στήλης μετά",
        tableMenu_ColumnMoveColumnBefore: "Μετακίνηση στήλης πριν",
        tableMenu_ColumnDelete: "Διαγραφή",
        tableMenu_ColumnSortAscending: "Ταξινόμηση σε αύξουσα σειρά",
        tableMenu_ColumnSortDescending: "Ταξινόμηση σε φθίνουσα σειρά",
        tableMenu_Column: "Στήλη",
        tableMenu_Style: "Στυλ",
        tableMenu_TableProperties: "Ιδιότητες πίνακα...",

        teamMenu: "Ομάδα",
        teamMenu_AddComment: "Προσθήκη σχολίου",
        teamMenu_AssignCells: "Ανάθεση κελιών",
        teamMenu_AssignSection: "Ανάθεση ενότητας",
        teamMenu_EditAssignment: "Τροποποίηση ανάθεσης",
        teamMenu_MarkSectionComplete: "Επισήμανση ενότητας ως ολοκληρωμένης",
        teamMenu_MarkAssignmentComplete: "Επισήμανση ανατεθειμένης εργασίας ως ολοκληρωμένης",
        teamMenu_WorkPrivatelyOnSection: "Ιδιωτική εργασία στην ενότητα",
        teamMenu_CancelPrivateWork: "Ακύρωση ιδιωτικής εργασίας",
        teamMenu_ApproveSection: "Έγκριση ενότητας",
        teamMenu_ApproveAssignment: "Έγκριση ανάθεσης",
        teamMenu_ReturnSectionForRework: "Επιστροφή ενότητας για επανεκτέλεση εργασιών",
        teamMenu_ReturnAssignmentForRework: "Επιστροφή ανάθεσης για επανεκτέλεση εργασιών",
        teamMenu_RemoveSectionAssignment: "Κατάργηση ανάθεσης ενότητας",
        teamMenu_RemoveCellAssignment: "Κατάργηση ανάθεσης κελιών",
        teamMenu_RemoveCompletedAssignments: "Αφαίρεση ολοκληρωμένων αναθέσεων",
        teamMenu_AboutThisSection: "Πληροφορίες για αυτή την ενότητα",
        teamMenu_AboutAssignment: "Πληροφορίες για αυτή την ανάθεση",

        presentationMenu: "Παρουσίαση",
        presentationMenu_SlideShow: "Αναπαραγωγή προβολής διαφανειών",
        presentationMenu_SlideShowWithCoview: "Αναπαραγωγή κοινόχρηστης προβολής διαφανειών",
        presentationMenu_SlideTransitions: "Εφαρμογή εφέ εναλλαγής διαφανειών...",
        presentationMenu_SlideShowFromCurrent: "Αναπαραγωγή από την τρέχουσα διαφάνεια",
        presentationMenu_EmptyCoviewInvites: "Καμία ενεργή κοινόχρηστη προβολή διαφανειών",
        presentationMenu_CoviewInvites: "Ενεργή κοινόχρηστη προβολή διαφανειών",

        dataMenu: "Δεδομένα",
        dataMenu_Sort: "Ταξινόμηση...",
        dataMenu_SortAsc: "Ταξινόμηση σε αύξουσα σειρά",
        dataMenu_SortDesc: "Ταξινόμηση σε φθίνουσα σειρά",
        dataMenu_ACL: "Προστατευμένες περιοχές",
        dataMenu_ACL_DELETE: "Διαγραφή όλων των δικαιωμάτων",
        dataMenu_Validity: "Εγκυρότητα",
        dataMenu_InstantFilter: "Αυτόματο φίλτρο",
        dataMenu_Validation: "Επικύρωση...",

        toolsMenu: "Εργαλεία",
        toolsMenu_AutoComplete: "Αυτόματη συμπλήρωση καταχωρήσεων κελιών",
        toolsMenu_SelectDictionary: "Λεξικά ορθογραφικού ελέγχου",
        toolsMenu_Dictionary_ca_CT: "Καταλανικά",
        toolsMenu_Dictionary_cs_CZ: "Τσεχικά (Τσεχία)",
        toolsMenu_Dictionary_da_DK: "Δανικά (Δανία)",
        toolsMenu_Dictionary_nl_NL: "Ολλανδικά (Ολλανδία)",
        toolsMenu_Dictionary_en_AU: "Αγγλικά (Αυστραλία)",
        toolsMenu_Dictionary_en_GB: "Αγγλικά (Μεγάλη Βρετανία)",
        toolsMenu_Dictionary_en_US: "Αγγλικά (Ηνωμένες Πολιτείες)",
        toolsMenu_Dictionary_fi_FI: "Φινλανδικά (Φινλανδία)",
        toolsMenu_Dictionary_fr_FR: "Γαλλικά (Γαλλία)",
        toolsMenu_Dictionary_fr_CA: "Γαλλικά (Καναδάς)",
        toolsMenu_Dictionary_de_DE: "Γερμανικά (Γερμανία)",
        toolsMenu_Dictionary_de_CH: "Γερμανικά (Ελβετία)",
        toolsMenu_Dictionary_el_GR: "Ελληνικά (Ελλάδα)",
        toolsMenu_Dictionary_it_IT: "Ιταλικά (Ιταλία)",
        toolsMenu_Dictionary_pl_PL: "Πολωνικά (Πολωνία)",
        toolsMenu_Dictionary_pt_BR: "Πορτογαλικά (Βραζιλία)",
        toolsMenu_Dictionary_pt_PT: "Πορτογαλικά (Πορτογαλία)",
        toolsMenu_Dictionary_ru_RU: "Ρωσικά (Ρωσία)",
        toolsMenu_Dictionary_es_ES: "Ισπανικά (Ισπανία)",
        toolsMenu_Dictionary_sv_SE: "Σουηδικά (Σουηδία)",
        toolsMenu_Dictionary_nb_NO: "Νορβηγικά (Bokml)",
        toolsMenu_Dictionary_nn_NO: "Νορβηγικά (Nynorsk)",
        toolsMenu_Dictionary_he_IL: "Εβραϊκά (Ισραήλ)",
        toolsMenu_SpellCheck: "Μη αυτόματη εκτέλεση ορθογραφικού ελέγχου...",
        toolsMenu_Preferences: "Προτιμήσεις",
        toolsMenu_Task: "Εργασία",
        toolsMenu_Task_Assigntask: "Ανάθεση εργασίας",
        teamMenu_AssignSlide: "Ανάθεση διαφάνειας",
        teamMenu_AssignSlides: "Ανάθεση διαφανειών",
        teamMenu_EditSlide: "Τροποποίηση ανάθεσης",
        teamMenu_ReopenSlideAssignment: "Νέο άνοιγμα ανάθεσης διαφάνειας",
        teamMenu_ReopenSlideAssignments: "Νέο άνοιγμα ανάθεσης διαφανειών",
        teamMenu_ReassignSlide: "Νέα ανάθεση διαφάνειας",
        teamMenu_ReassignSlides: "Νέα ανάθεση διαφανειών",
        teamMenu_MarkSlidesComplete: "Επισήμανση διαφάνειας ως ολοκληρωμένης",
        teamMenu_MarkSlidesCompletes: "Επισήμανση διαφανειών ως ολοκληρωμένων",
        teamMenu_ApproveSlide: "Έγκριση διαφάνειας",
        teamMenu_ApproveSlides: "Έγκριση διαφανειών",
        teamMenu_ReturnForRework: "Επιστροφή διαφάνειας για επανεκτέλεση εργασιών",
        teamMenu_ReturnForReworks: "Επιστροφή διαφανειών για επανεκτέλεση εργασιών",
        teamMenu_RemoveAssignment: "Κατάργηση ανάθεσης",
        teamMenu_AboutThisSlide: "Πληροφορίες για αυτή τη διαφάνεια",

        addOnsMenu: "Πρόσθετα προγράμματα",

        helpMenu: "Βοήθεια",
        helpMenu_About: "Πληροφορίες",
        helpMenu_Overview: "Περιεχόμενα βοήθειας",
        helpMenu_NewFeatures: "Τι νέο υπάρχει;",
        helpMenu_Tour: "Ξενάγηση",

        accel_fileMenu_Save: "Ctrl+S",
        accel_fileMenu_Save_Mac: "\u2318S",
        accel_fileMenu_Print: "Ctrl+P",
        accel_fileMenu_Print_Mac: "\u2318P",
        accel_editMenu_SelectAll: "Ctrl+A",
        accel_editMenu_SelectAll_Mac: "\u2318A",
        accel_editMenu_Undo: "Ctrl+Z",
        accel_editMenu_Undo_Mac: "\u2318Z",
        accel_editMenu_Redo: "Ctrl+Y",
        accel_editMenu_Redo_Mac: "\u2318Y",
        accel_editMenu_Cut: "Ctrl+X",
        accel_editMenu_Cut_Mac: "\u2318X",
        accel_editMenu_Copy: "Ctrl+C",
        accel_editMenu_Copy_Mac: "\u2318C",
        accel_editMenu_Paste: "Ctrl+V",
        accel_editMenu_Paste_Mac: "\u2318V",
        accel_editMenu_Find: "Ctrl+F",
        accel_editMenu_Find_Mac: "\u2318F",
        accel_insertMenu_Link: "Ctrl+K",
        accel_insertMenu_Link_Mac: "\u2318K",
        accel_insertMenu_Header: "CTRL+SHIFT+H",
        accel_insertMenu_Header_Mac: "\u21e7\u2318H",
        accel_insertMenu_Footer: "CTRL+SHIFT+F",
        accel_insertMenu_Footer_Mac: "\u21e7\u2318F",
        accel_formatMenu_Textprop_Bold: "Ctrl+B",
        accel_formatMenu_Textprop_Bold_Mac: "\u2318B",
        accel_formatMenu_Textprop_Italic: "Ctrl+I",
        accel_formatMenu_Textprop_Italic_Mac: "\u2318I",
        accel_formatMenu_Textprop_FormatPainter: "Ctrl+SHIFT+C, Ctrl+SHIFT+V",
        accel_formatMenu_Textprop_FormatPainter_Mac: "\u21e7\u2318C, \u21e7\u2318V",
        accel_formatMenu_Textprop_Underline: "Ctrl+U",
        accel_formatMenu_Textprop_Underline_Mac: "\u2318U",
        accel_formatMenu_Headingprop_P: "CTRL+SHIFT+0",
        accel_formatMenu_Headingprop_H1: "CTRL+SHIFT+1",
        accel_formatMenu_Headingprop_H2: "CTRL+SHIFT+2",
        accel_formatMenu_Headingprop_H3: "CTRL+SHIFT+3",
        accel_formatMenu_Headingprop_H4: "CTRL+SHIFT+4",
        accel_formatMenu_Headingprop_H5: "CTRL+SHIFT+5",
        accel_formatMenu_Headingprop_H6: "CTRL+SHIFT+6",
        accel_formatMenu_Superscript: "Ctrl+.",
        accel_formatMenu_Superscript_Mac: "\u2318.",
        accel_formatMenu_Subscript: "Ctrl+,",
        accel_formatMenu_Subscript_Mac: "\u2318,",
        accel_formatMenu_Left: "CTRL+SHIFT+L",
        accel_formatMenu_Left_Mac: "\u21e7\u2318L",
        accel_formatMenu_Right: "CTRL+SHIFT+R",
        accel_formatMenu_Right_Mac: "\u21e7\u2318R",
        accel_formatMenu_Center: "CTRL+SHIFT+E",
        accel_formatMenu_Center_Mac: "\u21e7\u2318E",
        accel_formatMenu_Justify: "CTRL+SHIFT+J",
        accel_formatMenu_Justify_Mac: "\u21e7\u2318J",
        accel_formatMenu_Indent: "CTRL+M",
        accel_formatMenu_Indent_Mac: "\u2318M",
        accel_formatMenu_DecreaseIndent: "CTRL+SHIFT+M",
        accel_formatMenu_DecreaseIndent_Mac: "\u21e7\u2318M",
        accel_teamMenu_AddComment: "SHIFT+F2",

        ctxMenuSmartTable: 'Πίνακας',
        ctxMenuTableProperties: "Ιδιότητες πίνακα",
        ctxMenuDeleteST: 'Διαγραφή',
        ctxMenuDeleteSTTable: 'Διαγραφή πίνακα',
        ctxMenuChgSTStyle: 'Αλλαγή στυλ',
        ctxMenuShowCaption: 'Εμφάνιση λεζάντας',
        ctxMenuHideCaption: 'Απόκρυψη λεζάντας',
        ctxMenuResizeST: 'Αλλαγή μεγέθους',
        ctxMenuResizeColumnsST: 'Αλλαγή μεγέθους στηλών',
        ctxMenuSTRow: 'Γραμμή',
        ctxMenuAddSTRowAbv: 'Εισαγωγή γραμμής πάνω',
        ctxMenuAddSTRowBlw: 'Εισαγωγή γραμμής κάτω',
        ctxMenuMoveSTRowUp: 'Μετακίνηση γραμμής πάνω',
        ctxMenuMoveSTRowDown: 'Μετακίνηση γραμμής κάτω',
        ctxMenuDelSTRow: 'Διαγραφή',
        ctxMenuRepeatRow: 'Επανάληψη γραμμής κεφαλίδας',
        ctxMenuSTCol: 'Στήλη',
        ctxMenuAddSTColBfr: 'Εισαγωγή στήλης πριν',
        ctxMenuAddSTColAft: 'Εισαγωγή στήλης μετά',
        ctxMenuMoveSTColBefore: 'Μετακίνηση στήλης πριν',
        ctxMenuMoveSTColAfter: 'Μετακίνηση στήλης μετά',
        ctxMenuDelSTCol: 'Διαγραφή',
        ctxMenuSortSTColAsc: 'Ταξινόμηση σε αύξουσα σειρά',
        ctxMenuSortSTColDesc: 'Ταξινόμηση σε φθίνουσα σειρά',
        ctxMenuShowAllFacets: 'Εμφάνιση κατηγοριών',
        ctxMenuHideAllFacets: 'Απόκρυψη κατηγοριών',
        ctxMenuSTCell: 'Κελί',
        ctxMenuMergeCells: 'Συγχώνευση κελιών',
        ctxMenuMergeDown: 'Συγχώνευση με το κάτω κελί',
        ctxMenuVerSplit: 'Διαχωρισμός κατακόρυφα',
        ctxMenuHorSplit: 'Διαχωρισμός οριζόντια',
        ctxMenuSplitCells: 'Διαχωρισμός κελιών...',
        splitCells: 'Διαχωρισμός κελιού',
        ctxMenuAlignTextLeft: 'Στοίχιση αριστερά',
        ctxMenuAlignTextCenter: 'Στοίχιση στο κέντρο',
        ctxMenuAlignTextRight: 'Στοίχιση δεξιά',
        ctxMenuClearSTCellContent: 'Εκκαθάριση περιεχομένου',
        ctxMenuMakeHeaderRow: 'Χρήση επιλεγμένης γραμμής ως κεφαλίδας',
        ctxMenuMakeNonHeaderRow: 'Αφαίρεση στυλ κεφαλίδας',
        ctxMenuMakeHeaderCol: 'Χρήση επιλεγμένης στήλης ως κεφαλίδας',
        ctxMenuMakeNonHeaderCol: 'Αφαίρεση στυλ κεφαλίδας',
        SHEET_CONTEXT_Hide: "Απόκρυψη", // hide row, column or sheet
        SHEET_CONTEXT_Show: "Εμφάνιση", // show row, column
        SHEET_CONTEXT_MoveSheet: "Μετακίνηση...", // move sheet
        SHEET_CONTEXT_InsertSheet: "Εισαγωγή...", // insert sheet
        SHEET_CONTEXT_DeleteSheet: "Διαγραφή...", // delete sheet	
        SHEET_CONTEXT_DuplicateSheet: "Αντιγραφή...", // duplicate sheet
        SHEET_CONTEXT_RenameSheet: "Μετονομασία...", // rename sheet
	
        ctxMenu_Image_WrapText: "Αναδίπλωση κειμένου",
        ctxMenu_Image_WrapText_Inline: "Ευθυγράμμιση με το κείμενο",
        ctxMenu_Image_WrapText_Square: "Τετράγωνο",
        ctxMenu_Image_WrapText_TopBottom: "Πάνω και κάτω",
        ctxMenu_Image_WrapText_Behind: "Πίσω από το κείμενο",
        ctxMenu_Image_WrapText_InFront: "Μπροστά από το κείμενο",
        ctxMenu_Image_WrapText_Other: "Περισσότερες επιλογές αναδίπλωσης κειμένου",
        ctxMenu_Image_WrapText_BothSides: "Και στις δύο πλευρές",
        ctxMenu_Image_WrapText_LeftOnly: "Μόνο αριστερά",
        ctxMenu_Image_WrapText_RightOnly: "Μόνο δεξιά",
        ctxMenu_Image_WrapText_LargestOnly: "Μεγαλύτερη",

        ctxMenu_Shape_AddText: "Προσθήκη κειμένου",

        ctxMenu_Range_ACL: "Προστασία περιοχής",
        ctxMenu_Sheet_ACL: "Προστασία φύλλου",

        ctxMenu_HeaderFooter: "Κεφαλίδα/Υποσέλιδο",
        ctxMenu_HeaderFooter_DiffFirst: "Μόνο στην πρώτη σελίδα",
        ctxMenu_HeaderFooter_DiffOddEven: "Διαφοροποίηση μονών και ζυγών σελίδων",
        ctxMenu_HeaderFooter_LinkToPre: "Σύνδεση με προηγούμενα",

        ctxMenu_copy: "Αντιγραφή",
        ctxMenu_paste: "Επικόλληση",
        ctxMenu_delete: "Διαγραφή",
        ctxMenu_cut: "Αποκοπή",
        ctxMenu_select: "Επιλογή",
        ctxMenu_properties: "Ιδιότητες",
        ctxMenu_bringToFront: "Μεταφορά σε πρώτο πλάνο",
        ctxMenu_sendToBack: "Μεταφορά στο τέλος",
        ctxMenu_arrange: "Διευθέτηση",
        ctxMenu_sendBackward: "Μεταφορά προς τα πίσω",
        ctxMenu_sendForward: "Μεταφορά προς τα μπρος",
        ctxMenu_fontStyle: "Στυλ γραμματοσειράς",
        ctxMenu_selectStyle: "Επιλογή στυλ",
        ctxMenu_fontSize: "Μέγεθος γραμματοσειράς",
        ctxMenu_fontFamily: "Οικογένεια γραμματοσειρών",
        ctxMenu_bold: "Έντονη γραφή",
        ctxMenu_italic: "Πλάγια γραφή",
        ctxMenu_u: "Υπογράμμιση",
        ctxMenu_strike: "Διαγράμμιση",
        ctxMenu_super: "Εκθέτης",
        ctxMenu_sub: "Δείκτης",
        ctxMenu_color: "Χρώμα",
        ctxMenu_bgcolor: "Χρώμα φόντου",
        ctxMenu_highcolor: "Χρώμα επισήμανσης",
        ctxMenu_restart: "Επανέναρξη λίστας",
        ctxMenu_continue: "Συνέχιση λίστας",
        ctxMenu_separate: "Διαχωρισμός λίστας",
        ctxMenu_join: "Σύνδεση με προηγούμενη λίστα",
        ctxMenu_setNumberVal: "Ορισμός τιμής αρίθμησης...",
        webClipboardInfoTitle: "Πρόχειρο",
        webClipboardInfoOKBtn: "OK",
        webClipboardInfoCutMsg: "Οι ρυθμίσεις ασφάλειας του προγράμματος πλοήγησης δεν επιτρέπουν την αυτόματη αποκοπή. Εκτελέστε αυτή την ενέργεια χρησιμοποιώντας το συνδυασμό πλήκτρων Ctrl+X.",
        webClipboardInfoCopyMsg: "Οι ρυθμίσεις ασφάλειας του προγράμματος πλοήγησης δεν επιτρέπουν την αυτόματη αντιγραφή. Εκτελέστε αυτή την ενέργεια χρησιμοποιώντας το συνδυασμό πλήκτρων Ctrl+C.",
        webClipboardInfoPasteMsg: "Οι ρυθμίσεις ασφάλειας του προγράμματος πλοήγησης δεν επιτρέπουν στο πρόγραμμα σύνταξης την πρόσβαση στα δεδομένα που υπάρχουν στο πρόχειρο. Χρησιμοποιήστε το συνδυασμό πλήκτρων Ctrl+V.",

        clearTrackChangeConfirmMsg: "Θα αφαιρεθούν οριστικά όλες οι χρωματικές επισημάνσεις των αλλαγών από αυτό το έγγραφο. Θέλετε να συνεχίσετε;"
});

