/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2014. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        spreadsheetTemplates: "Templat Spreadsheet",
        documentTemplates: "Templat Dokumen",
        titleShareDocument: "Berbagi Dokumen",
        offline: "Offline",
        versionPublishing: "Menerbitkan versi.",
        versionPublishFailed: "Versi tidak dipublikasikan. Ukuran file mungkin terlalu besar, atau waktu untuk server telah habis. Coba lagi, atau batalkan dan minta administrator Anda untuk memeriksa log server untuk mengidentifikasi masalah.",
        versionCheckinFailed: "Versi tidak di-check in. Ukuran file mungkin terlalu besar, atau waktu untuk server telah habis. Coba lagi, atau batalkan dan minta administrator Anda untuk memeriksa log server untuk mengidentifikasi masalah.",
        versionSavedFailed: "Belum selesai menyimpan. Coba Simpan kembali nanti.",
        publishFileSizeExceedMsg: "Tidak dapat menerbitkan file karena file melebihi ukuran maksimum yang ditetapkan oleh administrator repositori Anda. Hapus beberapa konten untuk membuat ukuran file menjadi lebih kecil, atau hubungi administrator Anda untuk menaikkan batasan ukuran.",
        checkinFileSizeExceedMsg: "Tidak dapat check in file karena file melebihi ukuran maksimum yang ditetapkan oleh administrator repositori Anda. Hapus beberapa konten untuk membuat ukuran file menjadi lebih kecil, atau hubungi administrator Anda untuk menaikkan batasan ukuran.",
        versionpublished: "Versi dipublikasikan oleh ${0} pada pukul ${1}.",
        versionPublishing2: "Menyimpan versi.",
        versionPublishFailed2: "Versi tidak disimpan. Ukuran file mungkin terlalu besar, atau waktu untuk server telah habis. Coba lagi, atau batalkan dan minta administrator Anda untuk memeriksa log server untuk mengidentifikasi masalah.",      
        publishFileSizeExceedMsg2: "Tidak dapat menyimpan file karena file melebihi ukuran maksimum yang ditetapkan oleh administrator repositori Anda. Hapus beberapa konten untuk membuat ukuran file menjadi lebih kecil, atau hubungi administrator Anda untuk menaikkan batasan ukuran.",
        versionpublished2: "Versi disimpan oleh ${0} pada pukul ${1}.",
        chekinCloseDocsMsg: "Sekarang Anda dapat menutup ${productName}.",
        draftSavingAs: "Menyalin file...",
        draftSavedAs: "Salinan yang baru disimpan sebagai ${0}.",
        synchronizing: "Tunggu sembari operasi sinkronisasi dengan server selesai.",
        synchronizeError: "Operasi sinkronisasi tidak dapat diselesaikan.",
        joinwithoutentitle: "Pengguna: ${0} ingin mengedit dokumen, tetapi tidak dapat bergabung dengan sesi pengeditan karena Anda tidak diperkenankan untuk melakukan pengeditan bersama.",
        joinwithoutentitle2: "Pengguna: ${0} ingin mengedit dokumen tetapi tidak dapat bergabung dengan sesi pengeditan karena mereka tidak diperkenankan untuk melakukan pengeditan bersama.",
        backtoFiles: "Buka File Saya",
        backtoCommFiles: "Buka File Komunitas",
        backtoLibrary: "Buka Pustaka",
        backtoICN: "Buka Navigator Konten",
        backtoRepository: "Buka Daftar File",
        createNewSpred: "Buat Spreadsheet",
        createNewDoc: "Buat Dokumen",
        createNewDocFromTemp: "Buat Dokumen dari Templat",
        shareDoc: "Berbagi dokumen",
        exportPdf: "Pengaturan Halaman'",
        insertDate: "Pemilihan Tanggal",
        insertTime: "Pemilihan Waktu",
        connect: "Hubungkan",
        theDoc: "dokumen",
        save: "Simpan Perubahan",
        saveBeforeReviewMsg: "Anda memiliki perubahan yang belum disimpan. Simpan perubahan Anda lalu Kirim untuk Peninjauan kembali.",
        submitReviewWidgetsFaiure: "Aplikasi tidak dimulai dengan benar. Kirim untuk Peninjauan kembali nanti.",
        widgetsFaiure: "Aplikasi tidak dimulai dengan benar.",
        slideSorter: "Slide",
        commentsBar: "Komentar",
        draftBadge: "DRAF",
        share: "Bagikan",
        comment: "Komentar",
        showSidebar: "Tampilkan Bilah Sisi",
        publishVersion: "Terbitkan",
        checkInVersion: "Check In",
        saveVersion: "Simpan",
        saved: "Semua perubahan disimpan",
        saving: "Menyimpan",
        submitFragment: "Kirim",
        aria_inMainMenu: "Anda sekarang sedang berada pada menu utama",
        aria_inSlideSorter: "Anda sekarang sedang berada dalam tampilan pengurut slide",
        aria_inSlideEditor: "Anda sekarang sedang berada dalam tampilan editor slide",
        createNewPres: "Buat Presentasi",
        createNewAppFromTemp: "Buat dokumen dari templat",
        textdoc: "teks",
        sheetdoc: "spreadsheet",
        presdoc: "presentasi",
        saveAsTextErrMsg: "Dokumen teks baru tidak dapat disimpan.",
        saveAsPresErrMsg: "Dokumen presentasi baru tidak dapat disimpan.",
        saveAsSheetErrMsg: "Dokumen spreadsheet baru tidak dapat disimpan.",
        saveAsTextErrMsg1: "Tidak tersedia cukup ruang untuk menyimpan dokumen.",
        saveAsPresErrMsg1: "Tidak tersedia cukup ruang untuk menyimpan presentasi.",
        saveAsSheetErrMsg1: "Tidak tersedia cukup ruang untuk menyimpan spreadsheet.",
        newDocTextErrMsg: "Dokumen teks baru tidak dapat dibuat.",
        newDocSheetErrMsg: "Dokumen spreadsheet baru tidak dapat dibuat.",
        newDocPresErrMsg: "Dokumen presentasi baru tidak dapat dibuat.",
        newDocTextErrMsg2: "Dokumen teks baru tidak dapat dibuat dari templat.",
        newDocSheetErrMsg2: "Dokumen spreadsheet baru tidak dapat dibuat dari templat.",
        newDocPresErrMsg2: "Dokumen presentasi baru tidak dapat dibuat dari templat.",
        newDocTextErrMsg3: "Tidak tersedia cukup ruang untuk membuat dokumen.",
        newDocSheetErrMsg3: "Tidak tersedia cukup ruang untuk membuat spreadsheet.",
        newDocPresErrMsg3: "Tidak tersedia cukup ruang untuk membuat presentasi.",
        newDocTextErrMsg4: "Dokumen dengan judul tersebut sudah ada. Beri judul yang berbeda untuk dokumen baru.",
        newDocSheetErrMsg4: "Spreadsheet dengan judul tersebut sudah ada. Beri judul yang berbeda untuk spreadsheet baru.",
        newDocPresErrMsg4: "Presentasi dengan judul tersebut sudah ada. Beri judul yang berbeda untuk presentasi baru.",        
        aclWarningTitle: "Tidak dapat mengedit versi baru",
        aclWarningMsg: "Karena pemilik file mengatur area yang dilindungi pada file ini, lebih baik mengedit secara online. Hubungi pemilik file (${0}) jika Anda harus mengunggah versi baru.",
        aclWarningMsgForOwner: "Terdapat area yang dilindungi di dalam file ini. Sehingga Anda tidak dapat mengedit versi baru yang diunggah secara online.  Anda harus menghapus semua area yang dilindungi di dalam file dan setelah itu Anda dapat membuka dan mengedit versi baru yang diunggah.",
        st0: "Sheet1",
        st1: "Sheet2",
        st2: "Sheet3",
        FootnoteMsg: "Halaman",
        conflictMsg: "Terdapat konflik dengan apa yang sedang diubah oleh editor lain.  Perubahan Anda dibatalkan.",
        undoRedoConflictMsg: "Operasi batalkan dan ulangi telah ditangguhkan dikarenakan sebuah konflik yang terjadi di antara file yang Anda edit dengan file orang lain yang sedang dikerjakan dalam pengeditan bersama",
        bigFileErrMsg: "Ukuran dokumen terlalu besar. Segarkan browser untuk melihat jika semua konten masih utuh",
        noPermissionMsg: "Anda tidak memiliki izin untuk mengedit file ini. Hubungi pemilik untuk memperoleh izin mengedit dan coba lagi.",
        networkIssueMsg: "Terdapat masalah pada jaringan.",
        networkIssueTitle: "Masalah Jaringan",
        networkIssueContent: "Terdapat masalah dengan jaringan. Segarkan halaman dan coba untuk terhubung kembali.",
        lockEditorMsg: "Dokumen tidak dapat diedit hingga tersedia koneksi dengan server.",
        offlineReasonMsg: "Waktu sesi Anda telah habis.",
        offlineReasonForServerUnacceptedMsg: "Tidak dapat memproses beberapa tindakan Anda. Tindakan dalam 1 menit akan dibatalkan oleh server Docs.",
        offlineReasonForServerDraftFormatChange: "Format dokumen Anda sudah tidak berlaku dikarenakan upgrade server.",
        reloadExplanationMsg: "Login kembali untuk melanjutkan mengedit.",
        reloadBtnLabel: "Muat Ulang",
        reconnectingMsg: "Tunggu saat koneksi disambungkan dengan server.",
        loadMsg: "Tunggu saat sedang memuat dokumen.",
        loadingDocumentMsg: "Tunggu saat sedang memuat dokumen dari server.",
        reLoadingDocumentMsg: "Tunggu saat sedang memuat kembali dokumen dari server.",
        unsupportMsg: "Fitur yang tidak terdukung terdeteksi. Lihat rincian lebih lanjut",
        browserWorkingMsg: "Sedang mengerjakan...",
        fileDeepDetectTitle: "Format file dan ekstensi file tidak sesuai",
        fileDeepDetectMsg: "Format file tidak sama dengan format yang ditandai oleh ekstensi file. Klik Lanjutkan untuk mengedit file dalam format ini.",
        fileDeepDetectOkLabel: "Lanjutkan",
        tipInfo: "Tip: ${0}",
        selectTextInfo: "Pilih teks untuk menerapkan gaya.",
        removeRecentFile: "File yang ingin Anda buka telah dihapus. Apakah Anda ingin menghapus nama file dari daftar File Terkini?",
        altLotusIcon: "",
        altErrorMsgIcon: "Pesan Kesalahan",
        altWarningMsgIcon: "Pesan Peringatan",
        altSuccessMsgIcon: "Pesan Berhasil",
        sidebarLandmarkDesc: "bilah sisir",
        footerTitle: "footer",
        mainDesc: "area konten",
        editLockedDocumentWarning: "Anda mengunci file ketika pengguna lain sedang mengedit file. Silakan bekerja dengan mereka untuk mengoordinasikan perubahan-perubahan atau meminta mereka untuk menyelesaikan pengeditan sehingga Anda dapat memiliki akses pengeditan yang eksklusif.",
        observerMode: "Anda sekarang sedang berada dalam mode Pengamat",
        editorMode: "Anda sekarang sedang berada dalam mode editor",
        maxEditorLimitReached: "Dokumen telah mencapai jumlah maksimum editor dari ${0} untuk sesi ini. Anda dapat beralih ke mode editor pada saat editor meninggalkan dokumen atau beralih ke mode pengamat",
        maxEditorLimitReachedTitle: "Jumlah Maksimum Editor yang Dicapai",
        uploadNewVersionOpenConfirm: "${0} mengunggah versi baru pada pukul ${1} ${2}. Apakah Anda ingin membuka versi baru?", //${0} name, ${1} time, ${2} date
        uploadNewVersionPublishConfirm: "${0} mengunggah versi baru pada pukul ${1} ${2}.", //${0} name, ${1} time, ${2} date
        you: "Anda",
        today: "hari ini",
        yesterday: "kemarin",
        slideShowInviteMsg: "Pengguna ${0} telah memulai slide show yang dibagikan. Apakah Anda ingin bergabung?",
        slideShowInviteTitle: "Undangan Slide Show yang Dibagikan",
        slideShowInviteTitle1: "Undangan Slide Show Kolektif",
        slideShowCoviewSelectUsersTitle: "Slide Show yang Dibagikan",
        slideShowCoviewSelectUsersTitle1: "Slide Show Kolektif",
        slideShowCoviewStmt: "Berbagi keadaan presentasi saat ini dalam slide show yang dibagikan.",
        slideShowCoviewStmt1: "Berbagi keadaan presentasi saat ini dalam slide show kolektif.",
        slideShowCoviewOptionOne: "Undang semua editor untuk bergabung dalam slide show.",
        slideShowCoviewOptionOne1: "Undang semua editor dan pengamat untuk bergabung dalam slide show.",
        slideShowCoviewOptionTwo: "Mengundang hanya para editor berikut untuk bergabung dalam slide show.",
        slideShowCoviewOptionTwo1: "Mengundang hanya para editor dan pengamat berikut untuk bergabung dalam slide show.",
        slideShowCoviewSlidesOf: "Slide ${0} dari ${1}",  //as in Slide 1 of 4
        slideShowCoviewViewers: "${0} Pemantau",
        slideShowCoviewDialogInput: "Ketik untuk menyaring nama",
        slideShowCoviewAddTitle: "Tambah pada Slide Show yang Dibagikan",
        slideShowCoviewAddTitle1: "Tambah pada Slide Show Kolektif",
        slideShowCoviewMessage: "Pilih pengguna tambahan untuk diundang dalam slide show yang dibagikan.",
        slideShowCoviewMessage1: "Pilih pengguna tambahan untuk diundang dalam slide show kolektif.",
        slideShowCoviewEnded: "Slide Show yang Dibagikan Berakhir",
        slideShowCoviewEndMessage: "Anda tidak dapat bergabung dengan slide show yang dibagikan.",
        slideShowCoviewEndMessage2: "Pengguna ${0} telah mengakhiri slide show yang dibagikan.",
        slideShowWarning: "Anda harus menutup slide show saat ini sebelum memulai slide show yang baru.",
        slideShowHoverMsg: "Klik untuk melihat siapa lagi yang sedang melihat slide show.",
        slideShowHoverMsgAdd: "Klik untuk mengundang lebih banyak pemantau.",
        csvEmpty: "Tidak dapat mengekspor sebagai file .csv karena lembar tidak berisi data.",
        edit: "Edit",
        printToPDF: "Unduh sebagai PDF",
        print: "Cetak",
        view: "Tampilan",
        openLatestFile: "Buka file terbaru",
        updateDocument: "Dokumen telah diperbarui.${0}.",
        updateSpreadsheet: "Spreadsheet diperbarui.${0}",
        updatePresentation: "Presentasi diperbarui.${0}.",
        labelCancel: "Batal",
        msgConversionFail: "Konversi Gagal",
        updateNow: "Buka Sekarang",
        fileUpdated: "Dokumen telah diperbarui",
        fileUpdatedContent1: "Dokumen telah diperbarui. Buka file terbaru sebelum Anda cetak.",
        htmlviewerlimitation1: "Spreadsheet ini memuat tabel pivot yang tidak dapat ditampilkan",
        htmlviewerlimitation2: "Spreadsheet ini memuat format bersyarat yang tidak dapat ditampilkan",
        htmlviewerlimitation3: "Spreadsheet memuat tabel pivot dan format bersyarat yang tidak dapat ditampilkan",
        close: "Tutup",
        closeDocs: "Tutup ${productName}",
        endSessionDlgTitle: "Sesi pengeditan telah berakhir",
        endSessionDlgNotice: "Sesi pengeditan Anda telah berakhir karena ${0} sudah check in di berkas.",
        labelStopReview: "Hentikan Peninjauan",
        labelRejct: "Tolak",
        labelApprove: "Terima",
        errorMsg: "Kesalahan",
        labelItemNotFountTitle: "Tidak dapat menyelesaikan tindakan.",
        labelItemNotFountMsg: "Anggota komunitas lainnya telah melakukan tindakan pada dokumen ini. Untuk informasi lebih lanjut, tutup dokumen dan kunjungi halaman Rincian File dalam pustaka Anda.",
        viewProtectedAreas: "Spreadsheet ini berisi area-area yang dilindungi. Anda hanya dapat melihat atau mengedit secara online.",
        macroTitle: "File berisi makro", 
        macroDesc: "Mengedit file ini dapat merusak makro. Untuk mencegah orang lain mengedit rentang atau lembar yang berisi makro, gunakan Data > Area yang Dilindungi.",
        problem_id_msg_title: "Laporkan masalah ini ke Administrator Anda. ",
        problem_id_msg_show: "Klik untuk menampilkan rincian",
    	problem_id_msg_hide: "Klik untuk menyembunyikan",
    	uploadNewVersionWarningTitle: "Tidak dapat mengedit versi baru",
        changeHistoryWarningMsg: "Karena pemilik file telah mengaktifkan Lacak Perubahan pada file ini, lebih baik lakukan pengeditan secara online. Hubungi pemilik file (${0}) jika Anda harus mengunggah versi baru.",
        changeHistoryWarningMsgForOwner: "Terdapat Riwayat Perubahan pada file ini. Sehingga Anda tidak dapat mengedit versi baru yang diunggah secara online.  Anda harus menghapus Riwayat Perubahan dan menonaktifkan Lacak Perubahan pada file ini, kemudian Anda dapat membuka dan mengedit versi baru yang diunggah.",
        viewChangeHistory: "Dokumen ini berisi riwayat perubahan. Anda hanya dapat melihat atau mengedit secara online.",
    	contentCorruptErrMsg: "Tidak dapat memuat konten karena konten rusak. Hubungi administrator untuk dukungan."
});

