/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
    Arrow01_Gray: "ลูกศร 01  เทา",
    Arrow02_Gray: "ลูกศร 02 สีเทา",
    Arrow03_Red: "ลูกศร 03 สีแดง",
    Arrow04_Blue: "ลูกศร 04 สีน้ำเงิน",
    Arrow05_Blue: "ลูกศร 05 สีน้ำเงิน",
    Arrow06_Yellow: "ลูกศร 06 สีเหลือง",
    Arrow07_Red: "ลูกศร 07 สีแดง",
    Arrow08_Gray: "ลูกศร 08 สีเทา",
    Arrow09_Orange: "ลูกศร 09 สีส้ม",
    Arrow10_Blue: "ลูกศร 10 สีน้ำเงิน",
    Arrow11_Blue: "ลูกศร 11 สีน้ำเงิน",
    Arrow12_Green: "ลูกศร 12 สีเขียว",
    Arrow13_Blue: "ลูกศร 13 สีน้ำเงิน",
    Arrow14_Green: "ลูกศร 14 สีเขียว",
    Arrow15_Orange: "ลูกศร 15 สีส้ม",
    Arrow16_Gray: "ลูกศร 16 สีเทา",
    CircleArrow01_Green: "ลูกศรวงกลม 01 สีเขียว",
    CircleArrow02_Multi: "ลูกศรวงกลม 02 หลายสี",
    CircleArrow03_Multi: "ลูกศรวงกลม 03 หลายสี",
    CircleArrow04_Multi: "ลูกศรวงกลม 04 หลายสี",
    CircleArrow05_Multi: "ลูกศรวงกลม 05 หลายสี",
    CircleArrow06_Multi: "ลูกศรวงกลม 06 หลายสี",
    CircleArrow07_Blue: "ลูกศรวงกลม 07 สีน้ำเงิน",
    CircleArrow08_Green: "ลูกศรวงกลม 08 สีเขียว",
    CircleArrow09_Multi: "ลูกศรวงกลม 09 หลายสี",
    CurvedArrow01_Gray: "ลูกศรโค้ง 01 สีเทา",
    CurvedArrow02_Blue: "ลูกศรโค้ง 02 สีน้ำเงิน",
    CurvedArrow03_Blue: "ลูกศรโค้ง 03 สีน้ำเงิน",
    CurvedArrow04_Orange: "ลูกศรโค้ง 04 สีส้ม",
    CurvedArrow05_Red: "ลูกศรโค้ง 05 สีแดง",
    CurvedArrow06_Blue: "ลูกศรโค้ง 06 สีน้ำเงิน",
    CurvedArrow07_Purple: "ลูกศรโค้ง 07 สีม่วง",
    CurvedArrow08_Green: "ลูกศรโค้ง 08 สีเขียว",
    CurvedArrow09_Gray: "ลูกศรโค้ง 09 สีเทา",
    CurvedArrow10_Blue: "ลูกศรโค้ง 10 สีน้ำเงิน",
    CurvedArrow11_Orange: "ลูกศรโค้ง 11 สีส้ม",
    CurvedArrow12_Blue: "ลูกศรโค้ง 12 สีน้ำเงิน",
    CurvedArrow13_Green: "ลูกศรโค้ง 13 สีเขียว",
    CurvedArrow14_Brown: "ลูกศรโค้ง 14 สีน้ำตาล",
    CurvedArrow15_Blue: "ลูกศรโค้ง 15 สีน้ำเงิน",
    CurvedArrow16_Gray: "ลูกศรโค้ง 16 สีเทา",
    CurvedArrow17_Gray: "ลูกศรโค้ง 17 สีเทา",
    CurvedArrow18_Gray: "ลูกศรโค้ง 18 สีเทา",
    CurvedArrow19_Gray: "ลูกศรโค้ง 19 สีเทา",
    CurvedArrow20_Gray: "ลูกศรโค้ง 20 สีเทา",
    TrendArrow01_Red: "ลูกศรแนวโน้ม 01 สีแดง",
    TrendArrow02_Green: "ลูกศรแนวโน้ม 02 สีเขียว",
    TrendArrow03_Orange: "ลูกศรแนวโน้ม 03 สีส้ม",
    TrendArrow04_Red: "ลูกศรแนวโน้ม 04 สีแดง",
    TrendArrow05_Orange: "ลูกศรแนวโน้ม 05 สีส้ม",
    TrendArrow06_Blue: "ลูกศรแนวโน้ม 06 สีน้ำเงิน",
    TrendArrow07_Orange: "ลูกศรแนวโน้ม 07 สีส้ม",
    TrendArrow08_Yellow: "ลูกศรแนวโน้ม 08 สีเหลือง",
    TrendArrow09_Blue: "ลูกศรแนวโน้ม 09 สีน้ำเงิน",
    TrendArrow10_Blue: "ลูกศรแนวโน้ม 10 สีน้ำเงิน",
    TrendArrow11_Blue: "ลูกศรแนวโน้ม 11 สีน้ำเงิน",
    TrendArrow12_Blue: "ลูกศรแนวโน้ม 12 สีน้ำเงิน",
    TrendArrow13_Red: "ลูกศรแนวโน้ม 13 สีแดง",
    TrendArrow14_Multi: "ลูกศรแนวโน้ม 14 หลายสี",
    TrendArrow15_Blue: "ลูกศรแนวโน้ม 15 สีน้ำเงิน",
    Bullet01_Circle_DarkRed: "จุดนำ 01 รูปวงกลมสีแดงเข้ม",
    Bullet02_Circle_Blue: "จุดนำ 02 รูปวงกลมสีน้ำเงิน",
    Bullet03_Circle_Green: "จุดนำ 03 รูปวงกลมสีเขียว",
    Bullet04_Square_Black: "จุดนำ 04 รูปสี่เหลี่ยมจัตุรัสสีดำ",
    Bullet05_Square_Orange: "จุดนำ 05 รูปสี่เหลี่ยมจัตุรัสสีส้ม",
    Bullet06_Square_Purple: "จุดนำ 06 รูปสี่เหลี่ยมจัตุรัสสีม่วง",
    Bullet07_Diamond_Blue: "จุดนำ 07 รูปข้าวหลามตัดสีน้ำเงิน",
    Bullet08_Diamond_LightBlue: "จุดนำ 08 รูปข้าวหลามตัดสีฟ้า",
    Bullet09_Diamond_Red: "จุดนำ 09 รูปข้าวหลามตัดสีแดง",
    Bullet10_Star_Yellow: "จุดนำ 10 รูปดาวสีเหลือง",
    Bullet11_Star_Blue: "จุดนำ 11 รูปดาวสีน้ำเงิน",
    Bullet12_Triangle_Blue: "จุดนำ 12 รูปสามเหลี่ยมสีน้ำเงิน",
    Bullet13_Triangle_DarkGreen: "จุดนำ 13 รูปสามเหลี่ยมสีเขียวเข้ม",
    Bullet14_Arrow_Red: "จุดนำ 14 ลูกศรสีแดง",
    Bullet15_Arrow_Blue: "จุดนำ 15 ลูกศรสีน้ำเงิน",
    Bullet16_Box_Blue: "จุดนำ 16 กล่องสีน้ำเงิน",
    Bullet17_Box_Red: "จุดนำ 17 กล่องสีแดง",
    Bullet18_Asterisk_LightBlue: "จุดนำ 18 ดอกจันสีฟ้า",
    Bullet19_Leaves_Red: "จุดนำ 19 ใบไม้สีแดง",
    Bullet20_Target_Blue: "จุดนำ 20 เป้าหมายสีน้ำเงิน",
    Bullet21_Arrow_Blue: "จุดนำ 21 ลูกศรสีน้ำเงิน",
    Bullet22_Arrow_DarkBlue: "จุดนำ 22 ลูกศรสีน้ำเงินเข้ม",
    Bullet23_Arrow_Brown: "จุดนำ 23 ลูกศรสีน้ำตาล",
    Bullet24_Flag_Red: "จุดนำ 24 แฟล็กสีแดง",
    Bullet25_Flag_Green: "จุดนำ 25 แฟล็กสีเขียว",
    Bullet26_X_Red: "จุดนำ 26 X สีแดง",
    Bullet27_X_Black: "จุดนำ 27 X สีดำ",
    Bullet28_Checkmark_Green: "จุดนำ 28 เครื่องหมายถูกสีเขียว",
    Bullet29_Checkmark_Blue: "จุดนำ 29 เครื่องหมายถูกสีน้ำเงิน",
    Bullet30_Square_DarkRed: "จุดนำ 30 รูปสี่เหลี่ยมจัตุรัสสีแดงเข้ม",
    camera: "กล้อง",
    computer1: "คอมพิวเตอร์ 1",
    computer2: "คอมพิวเตอร์ 2",
    computer3: "คอมพิวเตอร์ 3",
    Computer_Cloud: "คอมพิวเตอร์ Cloud",
    Computer_Desktop: "คอมพิวเตอร์เดสก์ท็อป",
    Computer_Laptop_Black: "คอมพิวเตอร์แลปท็อปสีดำ",
    Computer_Laptop_Silver: "คอมพิวเตอร์แลปท็อปสีเงิน",
    Database: "ฐานข้อมูล",
    evelope: "จดหมาย",
    newspapers: "หนังสือพิมพ์",
    openevelope: "จดหมายเปิด",
    Server: "เซิร์ฟเวอร์",
    speaker: "ลำโพง",
    WirelessAccessPoint: "Wireless Access Point",
    Cycle01_Transparent: "วงกลม 01 โปร่งใส",
    Cycle02_Transparent_Blue: "วงกลม 02 โปร่งใสสีน้ำเงิน",
    Cycle03_Blue: "วงกลม 03 สีน้ำเงิน",
    Cycle04_Blue: "วงกลม 04 สีน้ำเงิน",
    Cycle05: "วงกลม 05",
    Cycle06: "วงกลม 06",
    Cycle07: "วงกลม 07",
    Cycle08_Blue: "วงกลม 08 สีน้ำเงิน",
    Cycle09_Orange: "วงกลม 09 สีส้ม",
    Donut01_LightBlue: "โดนัท 01 สีฟ้า",
    Donut02_Blue: "โดนัท 02 สีน้ำเงิน",
    Donut03_Blue: "โดนัท 03 สีน้ำเงิน",
    Donut04_DarkBlue: "โดนัท 04 สีน้ำเงินเข้ม",
    Donut05_DarkBlue: "โดนัท 05 สีน้ำเงินเข้ม",
    Donut06_Blue: "โดนัท 06 สีน้ำเงิน",
    Donut07_Blue: "โดนัท 07 สีน้ำเงิน",
    Graph: "กราฟ",
    People01_Blue: "บุคคล 01 สีน้ำเงิน",
    People02: "บุคคล 02",
    Pillars01_Orange: "เสา 01 สีส้ม",
    Pillars02_LightBlue: "เสา 02 สีฟ้า",
    Process01_Blue: "กระบวนการ 01 สีน้ำเงิน",
    Process02_Blue: "กระบวนการ 02 สีน้ำเงิน",
    Process03_Blue: "กระบวนการ 03 สีน้ำเงิน",
    Process04_GoUp_Blue: "กระบวนการ 04 สีน้ำเงินเข้มขึ้น",
    Process05_GoUp_Red: "กระบวนการ 05 สีแดงเข้มขึ้น",
    Process06_GoUp_Yellow: "กระบวนการ 06 สีเหลืองเข้มขึ้น",
    Process07_Blue: "กระบวนการ 07 สีน้ำเงิน",
    Pyramid01: "ปิรามิด 01",
    Pyramid02_Blue: "ปิรามิด 02 สีน้ำเงิน",
    Pyramid03: "ปิรามิด 03",
    Radial01_Green: "รัศมี 01 สีเขียว",
    Radial02_Green: "รัศมี 02 สีเขียว",
    Radial03_Sphere: "รัศมี 03 โลก",
    Radial04_Sphere_Red: "รัศมี 04 โลกสีแดง",
    Radial05_Sphere_Blue: "รัศมี 05 โลกสีน้ำเงิน",
    Radial06_Arrows_DarkBlue: "รัศมี 06 ลูกศรสีน้ำเงินเข้ม",
    Radial07_Arrows_DarkBlue: "รัศมี 07 ลูกศรสีน้ำเงินเข้ม",
    Section_Circle: "ส่วนรูปวงกลม",
    Section_Cubes01: "ส่วนรูปลูกบาศก์ 01",
    Section_Cubes02_Blue: "ส่วนรูปลูกบาศก์ 02 สีน้ำเงิน",
    Section_Cubes03_Orange: "ส่วนรูปลูกบาศก์ 03 สีส้ม",
    Section_Cubes04: "ส่วนรูปลูกบาศก์ 04",
    Section_Cubes05: "ส่วนรูปลูกบาศก์ 05",
    Section_Cuboids01_Blue: "ส่วนรูปสี่เหลี่ยมมุมฉาก 01 สีน้ำเงิน",
    Section_Cuboids02_Blue: "ส่วนรูปสี่เหลี่ยมมุมฉาก 02 สีน้ำเงิน",
    Section_Cuboids03: "ส่วนรูปสี่เหลี่ยมมุมฉาก 03",
    Section_Gears01: "ส่วนรูปเกียร์ 01",
    Section_Gears02: "ส่วนรูปเกียร์ 02",
    Section_Gears03: "ส่วนรูปเกียร์ 03",
    Section_Hexagon04_Orange: "ส่วนรูปหกเหลี่ยม 04 สีส้ม",
    Section_Hexagons01: "ส่วนรูปหกเหลี่ยม 01",
    Section_Hexagons02_Blue: "ส่วนรูปหกเหลี่ยม 02 สีน้ำเงิน",
    Section_Hexagons03_Blue: "ส่วนรูปหกเหลี่ยม 03 สีน้ำเงิน",
    Section_Leaves01_LightBlue: "ส่วนรูปใบไม้ 01 สีฟ้า",
    Section_Leaves02_Green: "ส่วนรูปใบไม้ 02 สีเขียว",
    Section_Pasters01: "ส่วนรูปแผ่นกระดาษ 01",
    Section_Pasters02_Blue: "ส่วนรูปแผ่นกระดาษ 02 สีน้ำเงิน",
    Section_Puzzle01: "ส่วนรูปปริศนา 01",
    Section_Puzzle02: "ส่วนรูปปริศนา 02",
    Section_Puzzle03: "ส่วนรูปปริศนา 03",
    Section_Rectangles: "ส่วนรูปสี่เหลี่ยมผืนผ้า",
    Section_Squares: "ส่วนรูปสี่เหลี่ยมจัตุรัส",
    Section_Triangle: "ส่วนรูปสามเหลี่ยม",
    Target: "เป้าหมาย",
    Venn01: "Venn 01",
    Venn02: "Venn 02",
    Venn03: "Venn 03",
    Venn04: "Venn 04",
    Venn05: "Venn 05",
    Venn06_Blue: "Venn 06 สีน้ำเงิน",
    Venn07_Blue: "Venn 07 สีน้ำเงิน",
    Venn08: "Venn 08",
    Blackboard: "กระดานดำ",
    Books: "หนังสือ",
    Books1: "หนังสือ 1",
    books2: "หนังสือ 2",
    Chalk: "ชอล์ก",
    clipboard: "คลิปบอร์ด",
    clock: "นาฬิกา",
    Globe: "โลก",
    Glue: "กาว",
    GraduationCap: "หมวกรับปริญญา",
    magnifyingglass: "แว่นขยาย",
    Microscope: "กล้องจุลทรรศน์",
    Notebook: "โน๊ตบุ๊ก",
    notepad1: "โน๊ตแพด 1",
    notepad2: "โน๊ตแพด 2",
    notepad3: "โน๊ตแพด 3",
    PaperClip_Blue: "คลิปหนีบกระดาษสีน้ำเงิน",
    PaperClip_Red: "คลิปหนีบกระดาษสีแดง",
    Pencil: "ดินสอ",
    Ruler: "ไม้บรรทัด",
    TestTubes: "หลอดทดลอง",
    thumbtack: "เข็มหมุดติดกระดาษ",
    clouds: "เมฆ",
    DrippingFaucet: "ก๊อกน้ำที่มีน้ำหยด",
    Earth: "โลก",
    EndangeredAnimals1: "สัตว์อันตราย 1",
    EndangeredAnimals2: "สัตว์อันตราย 2",
    GreenCar: "รถยนต์สีเขียว",
    GreenFactory: "โรงงานสีเขียว",
    GreenHouse: "บ้านสีเขียว",
    Leaf1: "ใบไม้ 1",
    Leaf2: "ใบไม้ 2",
    lightbulb: "หลอดไฟ",
    LightBulb_Flourescent_Off: "หลอดไฟฟลูออเรสเซนต์ปิด",
    LightBulb_Flourescent_On: "หลอดไฟฟลูออเรสเซนต์เปิด",
    LightBulb_Standard_Off1: "หลอดไฟมาตรฐานปิด 1",
    LightBulb_Standard_Off2: "หลอดไฟมาตรฐานปิด 2",
    LightBulb_Standard_On: "หลอดไฟมาตรฐานเปิด",
    lightningcloud: "เมฆฟ้าแลบ",
    Pollution_Car: "รถยนต์ที่เป็นมลพิษ",
    Pollution_Factory: "โรงงานที่เป็นมลพิษ",
    Raindrop: "หยดฝน",
    RecycleBin: "ถังขยะรีไซเคิล",
    RecycleSymbol: "สัญลักษณ์รีไซเคิล",
    RenewableEnergySymbol: "สัญลักษณ์พลังงานที่ไม่มีวันหมด",
    RenewableEnergy_Solar: "พลังงานแสงอาทิตย์ที่ไม่มีวันหมด",
    RenewableEnergy_Water: "พลังงานน้ำที่ไม่มีวันหมด",
    RenewableEnergy_Wind: "พลังงานลมที่ไม่มีวันหมด",
    sun: "ดวงอาทิตย์",
    Sun1: "ดวงอาทิตย์ 1",
    Sun2: "ดวงอาทิตย์ 2",
    sundandcloud: "ดวงอาทิตย์และเมฆ",
    world: "โลก",
    Agreement: "ข้อตกลง",
    ATM01: "ATM 01",
    ATM02: "ATM 02",
    Balance_Balanced1: "งบที่สมดุล 1",
    Balance_Balanced2: "งบที่สมดุล 2",
    Balance_Unbalanced1: "งบที่ไม่สมดุล 1",
    Balance_Unbalanced2: "งบที่ไม่สมดุล 2",
    Calculator: "เครื่องคิดเลข",
    Chart_Decrease1: "แผนภูมิลดลง 1",
    Chart_Decrease2: "แผนภูมิลดลง 2",
    Chart_Increase1: "แผนภูมิเพิ่มขึ้น 1",
    Chart_Increase2: "แผนภูมิเพิ่มขึ้น 2",
    Chart_Plateau: "แผนภูมิ Plateau",
    Check: "ตรวจสอบ",
    Contract: "สัญญา",
    CreditCard_Black: "บัตรเครดิตสีดำ",
    CreditCard_Cut: "บัตรเครดิต Cut",
    CreditCard_Gold: "บัตรเครดิตสีทอง",
    Currency_Dollar: "สกุลเงินดอลลาร์",
    Currency_Dollars: "สกุลเงินดอลลาร์",
    Currency_Stack: "สแต็กสกุลเงิน",
    Currency_StackCoins: "เหรียญสแต็กสกุลเงิน",
    GoldBar: "แถบสีทอง",
    GoldBar_Stack: "สแต็กแถบสีทอง",
    MoneyBag01: "ถุงเงิน 01",
    MoneyBag02: "ถุงเงิน 02",
    PercentSign: "เครื่องหมายเปอร์เซ็นต์",
    PiggyBank01_Broken: "กระปุกออมสิน 01 แตก",
    PiggyBank02_Broken: "กระปุกออมสิน 02 แตก",
    PiggyBank_Coins: "เหรียญในกระปุกออมสิน",
    PiggyBank_Currency: "สกุลเงินในกระปุกออมสิน",
    Portfolio: "กระเป๋าใส่เอกสาร",
    PriceTag: "ป้ายราคา",
    Safe_Closed: "ตู้เซฟที่ปิด",
    Safe_Empty: "ตู้เซฟที่ว่างเปล่า",
    Safe_Full: "ตู้เซฟเต็ม",
    Seal_Gold: "ตราประทับสีทอง",
    Seal_Red: "ตราประทับสีแดง",
    Seal_Silver: "ตราประทับสีเงิน",
    Wallet_Empty: "กระเป๋าสตางค์ว่าง",
    Wallet_Full1: "กระเป๋าสตางค์เต็ม 1",
    Wallet_Full2: "กระเป๋าสตางค์เต็ม 2",
    BusinessPerson_Female6: "บุคคลทางธุรกิจเพศหญิง 6",
    BusinessPerson_Male3: "บุคคลทางธุรกิจเพศชาย 3",
    Computer_User_Female1: "ผู้ใช้คอมพิวเตอร์เพศหญิง 1",
    ConstructionWorker2: "คนงานก่อสร้าง 2",
    Presenter_Female1: "ผู้นำเสนอเพศหญิง 1",
    Component_Circle01_Transparent_DarkBlue: "คอมโพเนนต์รูปวงกลม 01 โปร่งใสสีน้ำเงินเข้ม",
    Component_Circle02_Transparent_Bule: "คอมโพเนนต์รูปวงกลม 02 โปร่งใสสีน้ำเงิน",
    Component_Circle03_Transparent_Green: "คอมโพเนนต์รูปวงกลม 03 โปร่งใสสีเขียว",
    Component_Circle04_Transparent_Orange: "คอมโพเนนต์รูปวงกลม 04 โปร่งใสสีส้ม",
    Component_Circle05_Transparent_Red: "คอมโพเนนต์รูปวงกลม 05 โปร่งใสสีแดง",
    Component_Cube01_DarkBlue: "คอมโพเนนต์รูปลูกบาศก์ 01 สีน้ำเงินเข้ม",
    Component_Cube02_LightBlue: "คอมโพเนนต์รูปลูกบาศก์ 02 สีฟ้า",
    Component_Cube03_Green: "คอมโพเนนต์รูปลูกบาศก์ 03 สีเขียว",
    Component_Cube04_Orange: "คอมโพเนนต์รูปลูกบาศก์ 04 สีส้ม",
    Component_Cube05_DarkRed: "คอมโพเนนต์รูปลูกบาศก์ 05 สีแดงเข้ม",
    Component_Cuboid01_DarkBlue: "คอมโพเนนต์รูปสี่เหลี่ยมมุมฉาก 01 สีน้ำเงินเข้ม",
    Component_Cuboid02_Blue: "คอมโพเนนต์รูปสี่เหลี่ยมมุมฉาก 02 สีน้ำเงิน",
    Component_Cuboid03_Green: "คอมโพเนนต์รูปสี่เหลี่ยมมุมฉาก 03 สีเขียว",
    Component_Cuboid04_Orange: "คอมโพเนนต์รูปสี่เหลี่ยมมุมฉาก 04 สีส้ม",
    Component_Cuboid05_Red: "คอมโพเนนต์รูปสี่เหลี่ยมมุมฉาก 05 สีแดง",
    Component_Gear01_DarkBlue: "คอมโพเนนต์รูปเกียร์ 01 สีน้ำเงินเข้ม",
    Component_Gear02_LightBlue: "คอมโพเนนต์รูปเกียร์ 02 สีฟ้า",
    Component_Gear03_Green: "คอมโพเนนต์รูปเกียร์ 03 สีเขียว",
    Component_Gear04_DarkRed: "คอมโพเนนต์รูปเกียร์ 04 สีแดงเข้ม",
    Component_Gear05_Orange: "คอมโพเนนต์รูปเกียร์ 05 สีส้ม",
    Component_Person01_DarkBlue: "คอมโพเนนต์รูปบุคคล 01 สีน้ำเงินเข้ม",
    Component_Person02_Blue: "คอมโพเนนต์รูปบุคคล 02 สีน้ำเงิน",
    Component_Person03_Green: "คอมโพเนนต์รูปบุคคล 03 สีเขียว",
    Component_Person04_DarkRed: "คอมโพเนนต์รูปบุคคล 04 สีแดงเข้ม",
    Component_Person05_Orange: "คอมโพเนนต์รูปบุคคล 05 สีส้ม",
    Component_PuzzlePiece01_DarkBlue: "คอมโพเนนต์รูปชิ้นปริศนา 01 สีน้ำเงินเข้ม",
    Component_PuzzlePiece02_Blue: "คอมโพเนนต์รูปชิ้นปริศนา 02 สีน้ำเงิน",
    Component_PuzzlePiece03_Green: "คอมโพเนนต์รูปชิ้นปริศนา 03 สีเขียว",
    Component_PuzzlePiece04_Red: "คอมโพเนนต์รูปชิ้นปริศนา 04 สีแดง",
    Component_PuzzlePiece05_Orange: "คอมโพเนนต์รูปชิ้นปริศนา 05 สีส้ม",
    Component_Sphere01_DarkBlue: "คอมโพเนนต์รูปโลก 01 สีน้ำเงินเข้ม",
    Component_Sphere02_LightBlue: "คอมโพเนนต์รูปโลก 02 สีฟ้า",
    Component_Sphere03_Green: "คอมโพเนนต์รูปโลก 03 สีเขียว",
    Component_Sphere04_DarkRed: "คอมโพเนนต์รูปโลก 04 สีแดงเข้ม",
    Component_Sphere05_Orange: "คอมโพเนนต์รูปโลก 05 สีส้ม",
    Book: "หนังสือ",
    Box01: "กล่อง 01",
    Box02: "กล่อง 02",
    Bulb01_Yellow: "หลอดไฟฟ้า 01 สีเหลือง",
    Bulb02_Yellow: "หลอดไฟฟ้า 02 สีเหลือง",
    Calendar: "ปฏิทิน",
    Chart: "แผนภูมิ",
    Clipboard: "คลิปบอร์ด",
    Clock: "นาฬิกา",
    Compass: "เข็มทิศ",
    Flag01_Red: "แฟล็ก 01 สีแดง",
    Flag02_Green: "แฟล็ก 02 สีเขียว",
    Flag03_Blue: "แฟล็ก 03 สีน้ำเงิน",
    Gift: "ของขวัญ",
    House: "บ้าน",
    Icon_Computer01_White: "ไอคอนคอมพิวเตอร์ 01 สีขาว",
    Icon_Computer02_Black: "ไอคอนคอมพิวเตอร์ 02 สีดำ",
    Icon_Disk01_Blue: "ไอคอนดิสก์ 01 สีน้ำเงิน",
    Icon_Disk02_Green: "ไอคอนดิสก์ 02 สีเขียว",
    Icon_Document01_Grey: "ไอคอนเอกสาร 01 สีเทา",
    Icon_Document02_Grey: "ไอคอนเอกสาร 02 สีเทา",
    Icon_Document03_Blue: "ไอคอนเอกสาร 03 สีน้ำเงิน",
    Icon_Document04_Blue: "ไอคอนเอกสาร 04 สีน้ำเงิน",
    Icon_Envelope01_Blue: "ไอคอนซองจดหมาย 01 สีน้ำเงิน",
    Icon_Envelope02_Yellow: "ไอคอนซองจดหมาย 02 สีเหลือง",
    Icon_Envelope03_Open_Yellow: "ไอคอนซองจดหมาย 03 เปิดสีเหลือง",
    Icon_Envelope04_Open_Yellow: "ไอคอนซองจดหมาย 04 เปิดสีเหลือง",
    Icon_Folder01_Yellow: "ไอคอนโฟลเดอร์ 01 สีเหลือง",
    Icon_Folder02_Yellow: "ไอคอนโฟลเดอร์ 02 สีเหลือง",
    Icon_Folder03_Open_Yellow: "ไอคอนโฟลเดอร์ 03 เปิดสีเหลือง",
    Icon_Folder04_Open_Yellow: "ไอคอนโฟลเดอร์ 04 เปิดสีเหลือง",
    Icon_Gear01_Grey: "ไอคอนเกียร์ 01 สีเทา",
    Icon_Gear02_Blue: "ไอคอนเกียร์ 02 สีน้ำเงิน",
    Icon_Network01_Blue: "ไอคอนเครือข่าย 01 สีน้ำเงิน",
    Icon_Network02: "ไอคอนเครือข่าย 02",
    Icon_Pencil01: "ไอคอนดินสอ 01",
    Icon_Pencil02: "ไอคอนดินสอ 02",
    Icon_Printer01_White: "ไอคอนเครื่องพิมพ์ 01 สีขาว",
    Icon_Printer02_Black: "ไอคอนเครื่องพิมพ์ 02 สีดำ",
    Key01: "กุญแจ 01",
    Key02: "กุญแจ 02",
    Lock01_Yellow: "ล็อค 01 สีเหลือง",
    Lock02_Yellow: "ล็อค 02 สีเหลือง",
    Lock03_Blue: "ล็อค 03 สีน้ำเงิน",
    Lock04_Blue: "ล็อค 04 สีน้ำเงิน",
    Magnet: "แม่เหล็ก",
    MagnifyingGlass: "แว่นขยาย",
    Medal: "เหรียญรางวัล",
    Notebook: "โน๊ตบุ๊ก",
    Phone: "โทรศัพท์",
    PieChart: "แผนภูมิวงกลม",
    Pin: "ปักหมุด",
    PuzzlePiece: "ชิ้นปริศนา",
    PuzzlePieces: "ชิ้นปริศนา",
    Roadblock: "สิ่งกีดขวางบนถนน",
    Scissors: "กรรไกร",
    Shield01: "โล่ 01",
    Shield02_Orange: "โล่ 02 สีส้ม",
    Shield03_Blue: "โล่ 03 สีน้ำเงิน",
    Sign_Ban01: "เครื่องหมายแถบ 01",
    Sign_Ban02: "เครื่องหมายแถบ 02",
    Sign_CheckBox01: "เครื่องหมายเช็กบ็อกซ์ 01",
    Sign_CheckBox02_Unchecked: "เครื่องหมายเช็กบ็อกซ์ 02 ที่ไม่ได้เลือก",
    Sign_Checkmark01_Green: "เครื่องหมายถูก 01 สีเขียว",
    Sign_Checkmark02_Green: "เครื่องหมายถูก 02 สีเขียว",
    Sign_DoNotEnter: "เครื่องหมายไม่ได้ป้อน",
    Sign_Error01: "เครื่องหมายข้อผิดพลาด 01",
    Sign_Error02: "เครื่องหมายข้อผิดพลาด 02",
    Sign_ExclamationPoint01_Red: "เครื่องหมายตกใจ 01 สีแดง",
    Sign_ExclamationPoint02_Orange: "เครื่องหมายตกใจ 02 สีส้ม",
    Sign_Help01_Green: "เครื่องหมายวิธีใช้ 01 สีเขียว",
    Sign_Help02_Blue: "เครื่องหมายวิธีใช้ 02 สีน้ำเงิน",
    Sign_Information: "เครื่องหมายข้อมูล",
    Sign_Null: "เครื่องหมาย Null",
    Sign_QuestionMark01_Blue: "เครื่องหมายคำถาม 01 สีน้ำเงิน",
    Sign_QuestionMark02_Red: "เครื่องหมายคำถาม 02 สีแดง",
    Sign_RadioButton01: "เครื่องหมายปุ่มเรดิโอ 01",
    Sign_RadioButton02_Unchecked: "เครื่องหมายปุ่มเรดิโอ 02 ที่ไม่ได้เลือก",
    Sign_Warning01_Red: "เครื่องหมายคำเตือน 01 สีแดง",
    Sign_Warning02_Orange: "เครื่องหมายคำเตือน 02 สีส้ม",
    Sign_X01_Red: "เครื่องหมาย X 01 สีแดง",
    Sign_X02_Red: "เครื่องหมาย X 02 สีแดง",
    Star_Yellow: "ดาวสีเหลือง",
    Wrench: "ประแจ",
    Airplane_Blue: "เครื่องบินสีน้ำเงิน",
    Bicycle_Blue: "จักรยานสีน้ำเงิน",
    Bus: "รถบัส",
    Canoe_Blue: "เรือแคนนูสีน้ำเงิน",
    Car_Red: "รถยนต์สีแดง",
    Helicopter_Blue: "เฮลิคอปเตอร์สีน้ำเงิน",
    Motorcycle_Red: "มอเตอร์ไซต์สีแดง",
    Pedestrian_Blue: "คนเดินถนนสีน้ำเงิน",
    PersonalTransporter_Green: "ผู้ขนส่งส่วนบุคคลสีเขียว",
    Sailboat_Red: "เรือใบสีแดง",
    Scooter_Orange: "รถสคูเตอร์สีส้ม",
    Train_Red: "รถไฟสีแดง",
    Truck_Blue: "รถบรรทุกสีน้ำเงิน",
    
    aria_category_selector: "อ็อพชันหมวดหมู่อิมเมจ",
    filterImageGallery: "กรองแกลเลอรีภาพ"

})
