﻿/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        fileMenu: "ไฟล์",
        fileMenu_New: "สร้าง",
        fileMenu_NewDocument: "เอกสาร",
        fileMenu_NewFromTemplate: "จากเท็มเพลต",
        fileMenu_NewDocumentfromTemplate: "เอกสารจากเท็มเพลต",
        fileMenu_NewPresentation: "การนำเสนอ",
        fileMenu_NewPresentationfromTemplate: "การนำเสนอจากเท็มเพลต",
        fileMenu_NewSpreadsheet: "สเปร็ดชีต",
        fileMenu_NewSpreadsheetFromTemplate: "สเปร็ดชีตจากเท็มเพลต",
        fileMenu_Open: "เปิด",
        fileMenu_Import: "อิมพอร์ต...",
        //	fileMenu_Close: "Close",
        fileMenu_Discard: "แปลงกลับเป็นเวอร์ชันล่าสุด",
        fileMenu_ClearTrackChange: "ลบเครื่องหมายการเปลี่ยน",
        fileMenu_SpreadsheetSettings: "ตั้งค่าโลแคลเอกสาร...",
        filemenu_revisionhistory: "การแก้ไข",
        fileMenu_Save: "บันทึก",
        fileMenu_SaveAs: "คัดลอก...",
        fileMenu_AutoPublish: "เผยแพร่โดยอัตโนมัติ",
        fileMenu_AutoCheckIn: "เช็กอินโดยอัตโนมัติ",
        fileMenu_PublishVersion: "เผยแพร่ตอนนี้",
        fileMenu_AutoPublish2: "บันทึกอัตโนมัติลงในที่เก็บ",
        //	fileMenu_AutoPublish_Tips: "Makes your changes available to readers at the end of each editing session.",
        fileMenu_PublishVersion2: "บันทึกลงในที่เก็บตอนนี้",
        fileMenu_AutoPublish3: "บันทึกอัตโนมัติลงใน ${0}",
        fileMenu_PublishVersion3: "บันทึกลงใน ${0} ตอนนี้",      
        fileMenu_SubmitForReview: "กำลังส่งเพื่อตรวจทาน...",
        fileMenu_CheckinVersion: "เช็กอิน...",
        fileMenu_Unlock: "ปลดล็อค",
        //	fileMenu_SaveAsDraft: "as Draft",
        //	fileMenu_SaveInMyDocs: "in My Documents",
        //	fileMenu_SaveToSymphony: "to Lotus Symphany",
        fileMenu_DownloadAs: "ดาวน์โหลดเป็น",
        fileMenu_PDF: "PDF",
        fileMenu_ODF: "ODF",
        fileMenu_DOC: "Microsoft Word 97- 2007 (*.doc)",
        fileMenu_ODS: "ODS",
        fileMenu_XLS: "Microsoft Excel 97-2007 (*.xls) ",
        fileMenu_ShareWith: "แบ่งใช้...",
        fileMenu_ExportAsPDF: "PDF",
        fileMenu_ExportAsODF: "ODF",
        fileMenu_ExportAsPPT: "Microsoft Powerpoint 97- 2007 (*.ppt)",
        //	fileMenu_WebPreview: "Web Preview",
        fileMenu_PrintToPDF: "พิมพ์เป็น PDF...",
        fileMenu_ViewFileDetails: "ดูรายละเอียดไฟล์...",
        fileMenu_RecentFile: "ไฟล์เมื่อเร็วๆ นี้",
        fileMenu_Open: "เปิด",
        fileMenu_Download: "ดาวน์โหลด",
        fileMenu_Print: "พิมพ์",
        fileMenu_Export: "เอ็กซ์พอร์ต",
        fileMenu_ExportToCSV: "CSV",
        fileMenu_ExportToPDF: "PDF (.pdf)",
        fileMenu_ExportToMarkdown: "Markdown(.md)",
        fileMenu_ExportToMS: "รูปแบบ Microsoft Office (.${FILEEXTENSION})",
        fileMenu_ExportToODF: "รูปแบบ Open Document (.${FILEEXTENSION})",
        fileMenu_PgSetup: "ตั้งค่าหน้ากระดาษ...",

        editMenu: "แก้ไข",
        editMenu_Undo: "เลิกทำ",
        editMenu_Redo: "ทำซ้ำ",
        editMenu_Cut: "ตัด",
        editMenu_Copy: "คัดลอก",
        editMenu_Paste: "วาง",
        editMenu_DeleteSlide: "ลบสไลด์",
        editMenu_SelectAll: "เลือกทั้งหมด",
        editMenu_Find: "ค้นหา...",
        editMenu_Replace: "แทนที่...",
        editMenu_FindReplace: "ค้นหาและแทนที่...",
        editMenu_EditLink: "เพิ่มหรือแก้ไขลิงก์",
        editMenu_DeleteSheet: "ลบชีต...",
        editMenu_RenameSheet: "เปลี่ยนชื่อชีต...",
        editMenu_HideSheet: "ซ่อนชีต",
        editMenu_MoveSheet: "ย้ายชีต...",
        editMenu_DeleteRow: "ลบแถว",
        editMenu_DeleteColumn: "ลบคอลัมน์",
        editMenu_DeleteCellLeft: "ลบเซลล์และเลื่อนไปทางซ้าย",
        editMenu_DeleteCellUp: "ลบเซลล์และเลื่อนไปทางขวา",
        editMenu_ClearCell: "ลบเนื้อหา",

        viewMenu: "ดู",
        viewMenu_Master: "ต้นแบบ",
        viewMenu_Notifications: "การแจ้ง",
        viewMenu_SlideSorter: "ตัวเรียงลำดับสไลด์",
        viewMenu_SpeakerNotes: "หมายเหตุของผู้พูด",
        viewMenu_Toolbar_Basic: "พื้นฐาน",
        viewMenu_Toolbar_Advanced: "ขั้นสูง",
        viewMenu_Toolbar_None: "ไม่มี",
        viewMenu_Toolbar: "แถบเครื่องมือ",
        viewMenu_Statusbar: "แถบสถานะ",
        viewMenu_Navigator: "เนวิเกเตอร์...",
        //viewMenu_Sidebar: "Sidebar",
        viewMenu_ShowHideIndicators: "แสดงตัวบ่งชี้การแก้ไขร่วม",
        viewMenu_Assignment: "ตัวบ่งชี้การมอบหมาย",
        viewMenu_Bookmark: "บุ๊กมาร์ก",
        viewMenu_Coediting: "ไฮไลต์การแก้ไขร่วม",
        viewMenu_Rulers: "ไม้บรรทัด",
        viewMenu_WebLayout: "โครงร่างเว็บ",
        viewMenu_AutomaticSpellCheck: "ตรวจสอบการสะกดคำเมื่อคุณพิมพ์",
        viewMenu_Formulabar: "แถบสูตร",
        viewMenu_moveRight: "เริ่มย้ายเคอร์เซอร์ไปทางขวา",
        viewMenu_showFullString: "ขยายเนื้อหาในเซลล์",
        viewMenu_Doc: "ดูเอกสาร",
        viewMenu_Templates: "เท็มเพลต",
        viewMenu_GridLines: "ซ่อนเส้นกริด",
        viewMenu_UnsupportWarning: "แสดงข้อความคุณลักษณะที่ไม่สนับสนุน",
        viewMenu_HiddenSheets: "ชีตที่ซ่อนไว้",
        viewMenu_FreezeRows: "ตรึงแถว",
        viewMenu_FreezeColumns: "ตรึงคอลัมน์",
        viewMenu_NoFrozenRows: "ไม่มีแถวที่ตรึงไว้",
        viewmenu_NoFrozenColumns: "ไม่มีคอลัมน์ที่ตรึงไว้",
        viewMenu_FreezeXRows: "ตรึง ${0} แถว",
        viewMenu_FreezeOneRow: "ตรึง ${0} แถว",
        viewMenu_FreezeXColumns: "ตรึง ${0} คอลัมน์",
        viewMenu_FreezeOneColumn: "ตรึง ${0} คอลัมน์",
        viewMenu_CarriageReturn: "เครื่องหมายจัดรูปแบบ",
        viewMenu_Navigation: "บานหน้าต่างการนำทาง",
        viewMenu_ACL: "พื้นที่ที่สามารถแก้ไขได้",
        viewMenu_GridOnOff: "เส้นกริด",
        viewMenu_ObserverMode: 'โหมดผู้สังเกต',

        createMenu: "แทรก",
        createMenu_NewSlide: "สร้างสไลด์ใหม่",
        createMenu_DuplicateSlide: "ทำซ้ำสไลด์",
        createMenu_ImageFromFile: "อิมเมจ...",
        createMenu_TextBox: "กล่องข้อความ",
        createMenu_Shape: "รูปร่าง",
        createMenu_break: "พัก",
        createMenu_RowAbove: "แถวด้านบน",
        createMenu_RowBelow: "แถวด้านล่าง",
        createMenu_ColumnRight: "คอลัมน์ขวา",
        createMenu_ColumnLeft: "คอลัมน์ซ้าย",
        createMenu_Sheet: "ชีต...",
        createMenu_Image: "อิมเมจ...",
        createMenu_Comments: "ข้อคิดเห็น...",
        createMenu_WebLink: "เว็บลิงก์...",
        createMenu_SpecialCharacter: "อักขระพิเศษ...",
        createMenu_Function: "ฟังก์ชัน...",
        createMenu_Fromtemplate: "สร้างจากเท็มเพลต",

        insertMenu: "แทรก",
        insertMenu_break: "เส้นกั้นหน้า",
        insertMenu_sectionbreak: "เส้นกั้นส่วน",
        insertMenu_Bookmark: "บุ๊กมาร์ก...",
        insertMenu_WebLink: "ลิงก์...",
        insertMenu_SpecialCharacter: "อักขระพิเศษ...",
        insertMenu_HorizontalLine: "บรรทัดในแนวนอน",
        insertMenu_Header: "ส่วนหัว",
        insertMenu_Footer: "ส่วนท้าย",
        insertMenu_TableOfContents: "สารบัญ",

        insertMenu_HeaderFooter: "ส่วนหัว/ส่วนท้าย",
        insertMenu_HF_Edit: "แก้ไข",
        insertMenu_HF_Hide: "ซ่อน",
        insertMenu_Endnotes: "อ้างอิงท้ายเรื่อง",
        insertMenu_RowAbove: "แถวด้านบน",
        insertMenu_PageNumber: "หมายเลขหน้า",
        insertMenu_PageNumberTop: "ด้านบนของหน้า",
        insertMenu_PageNumberBottom: "ด้านล่างของหน้า",
        insertMenu_PageNumberCurr: "ตำแหน่งปัจจุบัน",
        insertMenu_TotalPageNumber: "หน้า 1 จาก N",
        insertMenu_Date: "วันที่...",
        insertMenu_Time: "เวลา...",
        insertMenu_Fields: "ฟิลด์",
        //    insertMenu_Comment: "Comment",
        insertMenu_CellRight: "เซลล์เลื่อนไปทางขวา",
        insertMenu_CellDown: "เซลล์และเลื่อนลง",
        insertMenu_RowBelow: "แถวด้านล่าง",
        insertMenu_ColumnBefore: "คอลัมน์ก่อนหน้า",
        insertMenu_ColumnAfter: "คอลัมน์ตามหลัง",
        insertMenu_Sheet: "ชีต...",
        insertMenu_Image: "อิมเมจ...",
        insertMenu_DuplicateSheet: "ทำซ้ำชีต",
        insertMenu_Function: "ฟังก์ชัน",
        insertMenu_FunctionSum: "สรุป",
        insertMenu_FunctionAverage: "เฉลี่ย",
        insertMenu_FunctionCount: "จำนวน",
        insertMenu_FunctionMax: "สูงสุด",
        insertMenu_FunctionMin: "ต่ำสุด",
        insertMenu_FunctionMore: "ฟังก์ชันเพิ่มเติม...",
        insertMenu_NameRange: "ช่วงที่ระบุชื่อ",
        insertMenu_NameRangeNew: "ช่วงใหม่...",
        insertMenu_NameRangeManage: "จัดการช่วง...",
        insertMenu_Chart: "แผนภูมิ...",

        contextMenu_insertCellRight: "แทรกเซลล์และเลื่อนไปทางขวา",
        contextMenu_insertCellDown: "แทรกเซลล์และเลื่อนลง",
        contextMenu_InsertRowAbove: "แทรกแถวด้านบน",
        contextMenu_InsertRowBelow: "แทรกแถวด้านล่าง",
        contextMenu_InsertColumnBefore: "แทรกคอลัมน์ก่อน",
        contextMenu_InsertColumnAfter: "แทรกคอลัมน์หลัง",
        contextMenu_DownloadImage: "ดาวน์โหลดเป็นไฟล์อิมเมจ",

        formatMenu: "รูปแบบ",
        formatMenu_Columns: "คอลัมน์",
        formatMenu_DefaultFormatting: "การจัดรูปแบบดีฟอลต์",
        formatMenu_Template: "สไตล์...",
        contextMenu_Template: "สไตล์ตาราง...",
        formatMenu_LineSpacing: "ระยะห่างระหว่างบรรทัด",
        formatMenu_LineSpacing1: "1",
        formatMenu_LineSpacing12: "1.2",
        formatMenu_LineSpacing15: "1.5",
        formatMenu_LineSpacing2: "2",
        formatMenu_LineSpacing25: "2.5",
        formatMenu_LineSpacing3: "3",
        formatMenu_TextProperties: "คุณสมบัติข้อความ",
        formatMenu_PageBreakBefore: "ตัวแยกหน้าก่อน",
        formatMenu_KeepLines: "เก็บบรรทัดเข้าด้วยกัน",
        formatMenu_WidowControl: "การควบคุม Widow/Orphan",
        formatMenu_Pagination: "คุณสมบัติย่อหน้า",
        formatMenu_Bold: "ตัวหนา",
        formatMenu_Italic: "ตัวเอียง",
        formatMenu_Underline: "ขีดเส้นใต้",
        formatMenu_Strikethrough: "ขีดฆ่า",
        formatMenu_IncreaseSize: "เพิ่มขนาดฟอนต์",
        formatMenu_DecreaseSize: "ลดขนาดฟอนต์",
        formatMenu_ImageProperties: "คุณสมบัติอิมเมจ...",
        formatMenu_ChartProperties: "คุณสมบัติแผนภูมิ...",
        formatMenu_EditChart: "แก้ไขแผนภูมิ",
        formatMenu_InsertChart: "แทรกแผนภูมิ",
        formatMenu_Properties: "คุณสมบัติ...",
        formatMenu_Heading: "ส่วนหัว",
        formatMenu_Normal: "ปกติ",
        formatMenu_Title: "หัวเรื่อง",
        formatMenu_Subtitle: "หัวเรื่องย่อย",
        formatMenu_Heading1: "ส่วนหัวที่ 1",
        formatMenu_Heading2: "ส่วนหัวที่ 2",
        formatMenu_Heading3: "ส่วนหัวที่ 3",
        formatMenu_Heading4: "ส่วนหัวที่ 4",
        formatMenu_Heading5: "ส่วนหัวที่ 5",
        formatMenu_Heading6: "ส่วนหัวที่ 6",
        formatMenu_Heading7: "ส่วนหัวที่ 7",
        formatMenu_Heading8: "ส่วนหัวที่ 8",
        formatMenu_Heading9: "ส่วนหัวที่ 9",
        formatMenu_BulletedList: "รายการสัญลักษณ์แสดงหัวข้อย่อย",
        formatMenu_NumberedList: "รายการกำหนดหมายเลข",
        formatMenu_OutLine: "รายการหลายระดับ",
        formatMenu_Superscript: "ตัวยก",
        formatMenu_Subscript: "ตัวห้อย",
        formatMenu_Align: "จัดตำแหน่ง",
        formatMenu_Left: "ซ้าย",
        formatMenu_Right: "ขวา",
        formatMenu_Center: "กึ่งกลาง",
        formatMenu_Justify: "จัดขอบ",
        formatMenu_Text_Direction: "ทิศทางข้อความ",
        formatMenu_Ltr: "ซ้ายไปขวา",
        formatMenu_Rtl: "ขวาไปซ้าย",
        formatMenu_LineSpacing: "ระยะห่างระหว่างบรรทัด",
        formatMenu_LineSpacing1: "1.0",
        formatMenu_LineSpacing115: "1.15",
        formatMenu_LineSpacing15: "1.5",
        formatMenu_LineSpacing2: "2.0",
        formatMenu_LineSpacing25: "2.5",
        formatMenu_LineSpacing3: "3.0",
        formatMenu_Top: "ด้านบน",
        formatMenu_Bottom: "ด้านล่าง",
        formatMenu_Middle: "กึ่งกลาง",
        formatMenu_Direction: "ทิศทางข้อความ",
        formatMenu_Rtl: "ขวาไปซ้าย",
        formatMenu_Ltr: "ซ้ายไปขวา",
        formatMenu_Auto: "ตามบริบท",
        formatMenu_SheetDirection: "ทิศทางชีต",
        formatMenu_SheetRtl: "ขวาไปซ้าย",
        formatMenu_SheetLtr: "ซ้ายไปขวา",
        formatMenu_Indent: "เพิ่มการเยื้อง",
        formatMenu_DecreaseIndent: "ลดการเยื้อง",
        formatMenu_ClearFormat: "ลบรูปแบบ",
        formatMenu_RowHeight: "ความสูงของแถว",
        formatMenu_ColumnWidth: "ความกว้างของคอลัมน์",
        formatMenu_ShowRow: "แสดงแถว",
        formatMenu_HideRow: "ซ่อนแถว",
        formatMenu_ShowColumn: "แสดงคอลัมน์",
        formatMenu_HideColumn: "ซ่อนคอลัมน์",
        formatMenu_WrapText: "ตัดข้อความ",
        formatMenu_Number: "ตัวเลข",
        formatMenu_FontArial: "Arial",
        formatMenu_FontComicSansMS: "Comic Sans MS",
        formatMenu_FontCourierNew: "Courier New",
        formatMenu_FontGeorgia: "Georgia",
        formatMenu_FontLucidaSansUnicode: "Lucida Sans Unicode",
        formatMenu_FontTahoma: "Tahoma",
        formatMenu_FontTimesNewRoman: "Times New Roman",
        formatMenu_FontTrebuchetMS: "Trebuchet MS",
        formatMenu_FontVerdana: "Verdana",
        formatMenu_FontName: "ฟอนต์",

        layoutMenu: "โครงร่าง",
        layoutMenu_SlideLayout: "โครงร่างสไลด์...",
        layoutMenu_SlideDesign: "สไตล์ต้นแบบ...",
        layoutMenu_DefaultFormatting: "การจัดรูปแบบดีฟอลต์",
        layoutMenu_Textprop_Bold: "ตัวหนา",
        layoutMenu_Textprop_Italic: "ตัวเอียง",
        layoutMenu_Textprop_Underline: "ขีดเส้นใต้",
        layoutMenu_Textprop_Strikethrough: "ขีดฆ่า",
        layoutMenu_TextProp: "คุณสมบัติข้อความ",
        LayoutMenu_RowHeight: "ความสูงของแถว...",
        LayoutMenu_ColumnWidth: "ความกว้างของคอลัมน์...",
        LayoutMenu_ShowRow: "แสดงแถว",
        LayoutMenu_HideRow: "ซ่อนแถว",
        LayoutMenu_RenameSheet: "เปลี่ยนชื่อชีต...",
        LayoutMenu_MoveSheet: "ย้ายชีต",

        tableMenu: "ตาราง",
        tableMenu_Create: "สร้าง...",
        tableMenu_CreateFromTemplate: "สร้างจากเท็มเพลต",
        tableMenu_Delete: "ลบ",
        tableMenu_SetTableColor: "สีเซลล์",
        tableMenu_CreateTable: "สร้างตาราง",
        tableMenu_Cell: "เซลล์",
        tableMenu_CellMergeCells: "ผสานเซลล์",
        tableMenu_CellAlignLeft: "จัดตำแหน่งชิดซ้าย",
        tableMenu_CellAlignCenter: "จัดตำแหน่งกึ่งกลาง",
        tableMenu_CellAlignRight: "จัดตำแหน่งชิดขวา",
        tableMenu_CellClearContents: "ล้างเนื้อหา",
        tableMenu_CellProperties: "คุณสมบัติเซลล์...",
        tableMenu_Row: "แถว",
        tableMenu_InsertRowAbove: "แทรกแถวด้านบน",
        tableMenu_InsertRowBelow: "แทรกแถวด้านล่าง",
        tableMenu_MoveRowAbove: "ย้ายแถวขึ้น",
        tableMenu_MoveRowBelow: "ย้ายแถวลง",
        tableMenu_RowInsertRow: "แทรกแถว...",
        tableMenu_RowInsertRowAbove: "แทรกแถวด้านบน",
        tableMenu_RowInsertRowBelow: "แทรกแถวด้านล่าง",
        tableMenu_RowMoveRowAbove: "ย้ายแถวด้านบน",
        tableMenu_RowMoveRowBelow: "ย้ายแถวด้านล่าง",
        tableMenu_RowDelete: "ลบ",
        tableMenu_RowRepeat: "ทำซ้ำแถวส่วนหัว",
        tableMenu_InsertColumnBefore: "แทรกคอลัมน์ก่อน",
        tableMenu_InsertColumnAfter: "แทรกคอลัมน์หลัง",
        tableMenu_MoveColumnBefore: "ย้ายคอลัมน์ซ้าย",
        tableMenu_MoveColumnAfter: "ย้ายคอลัมน์ขวา",
        tableMenu_ResizeColumn: "ปรับขนาดคอลัมน์",
        tableMenu_ResizeColumns: "ปรับขนาดคอลัมน์",
        tableMenu_MarkasCategory: "ทำเครื่องหมายเป็นหมวดหมู่",
        tableMenu_ColumnInsertColumn: "แทรกคอลัมน์...",
        tableMenu_ColumnAddColumnBefore: "แทรกคอลัมน์ก่อน",
        tableMenu_ColumnAddColumnAfter: "แทรกคอลัมน์หลัง",
        tableMenu_ColumnMoveColumnAfter: "ย้ายคอลัมน์หลัง",
        tableMenu_ColumnMoveColumnBefore: "ย้ายคอลัมน์ก่อน",
        tableMenu_ColumnDelete: "ลบ",
        tableMenu_ColumnSortAscending: "เรียงลำดับจากน้อยไปมาก",
        tableMenu_ColumnSortDescending: "เรียงลำดับจากมากไปน้อย",
        tableMenu_Column: "คอลัมน์",
        tableMenu_Style: "ลักษณะ",
        tableMenu_TableProperties: "คุณสมบัติตาราง...",

        teamMenu: "ทีมงาน",
        teamMenu_AddComment: "เพิ่มข้อคิดเห็น",
        teamMenu_AssignCells: "มอบหมายเซลล์",
        teamMenu_AssignSection: "มอบหมายส่วน",
        teamMenu_EditAssignment: "แก้ไขการมอบหมาย",
        teamMenu_MarkSectionComplete: "ทำเครื่องหมายส่วนที่เสร็จสมบูรณ์",
        teamMenu_MarkAssignmentComplete: "ทำเครื่องหมายว่าการมอบหมายเสร็จสมบูรณ์",
        teamMenu_WorkPrivatelyOnSection: "ทำงานแบบไพรเวตบนส่วน",
        teamMenu_CancelPrivateWork: "ยกเลิกงานไพรเวต",
        teamMenu_ApproveSection: "ส่วนที่อนุมัติ",
        teamMenu_ApproveAssignment: "อนุมัติการมอบหมาย",
        teamMenu_ReturnSectionForRework: "ส่งคืนส่วนสำหรับทำงานอีกครั้ง",
        teamMenu_ReturnAssignmentForRework: "ส่งคืนการมอบหมายเพื่อทำงานอีกครั้ง",
        teamMenu_RemoveSectionAssignment: "ลบการมอบหมายส่วน",
        teamMenu_RemoveCellAssignment: "ลบการมอบหมายเซลล์",
        teamMenu_RemoveCompletedAssignments: "ลบการกำหนดที่เสร็จสิ้นแล้ว",
        teamMenu_AboutThisSection: "เกี่ยวกับส่วนนี้",
        teamMenu_AboutAssignment: "เกี่ยวกับการกำหนดนี้",

        presentationMenu: "การนำเสนอ",
        presentationMenu_SlideShow: "เล่นการแสดงสไลด์",
        presentationMenu_SlideShowWithCoview: "เล่นการแสดงสไลด์ที่แบ่งใช้",
        presentationMenu_SlideTransitions: "ใช้การเปลี่ยนสไลด์...",
        presentationMenu_SlideShowFromCurrent: "เล่นจากสไลด์ปัจจุบัน",
        presentationMenu_EmptyCoviewInvites: "ไม่มีการแสดงสไลด์ที่แบ่งใช้ซึ่งแอ็คทีฟ",
        presentationMenu_CoviewInvites: "การแสดงสไลด์ที่แบ่งใช้ซึ่งแอ็คทีฟ",

        dataMenu: "ข้อมูล",
        dataMenu_Sort: "เรียงลำดับ...",
        dataMenu_SortAsc: "เรียงลำดับจากน้อยไปมาก",
        dataMenu_SortDesc: "เรียงลำดับจากมากไปน้อย",
        dataMenu_ACL: "พื้นที่ป้องกัน",
        dataMenu_ACL_DELETE: "ลบสิทธิทั้งหมด",
        dataMenu_Validity: "ความถูกต้อง",
        dataMenu_InstantFilter: "ตัวกรองทันที",
        dataMenu_Validation: "การตรวจสอบความถูกต้อง...",

        toolsMenu: "เครื่องมือ",
        toolsMenu_AutoComplete: "ทำรายการเซลล์สมบูรณ์โดยอัตโนมัติ",
        toolsMenu_SelectDictionary: "พจนานุกรมการตรวจสอบการสะกดคำ",
        toolsMenu_Dictionary_ca_CT: "ภาษาคาตาลัน",
        toolsMenu_Dictionary_cs_CZ: "ภาษาเช็ก (เช็ก)",
        toolsMenu_Dictionary_da_DK: "ภาษาเดนมาร์ก (เดนมาร์ก)",
        toolsMenu_Dictionary_nl_NL: "เนเธอร์แลนด์ (เนเธอร์แลนด์)",
        toolsMenu_Dictionary_en_AU: "ภาษาอังกฤษ (ออสเตรเลีย)",
        toolsMenu_Dictionary_en_GB: "ภาษาอังกฤษ (สหราชอาณาจักร)",
        toolsMenu_Dictionary_en_US: "ภาษาอังกฤษ (สหรัฐอเมริกา)",
        toolsMenu_Dictionary_fi_FI: "ภาษาฟินนิช (ฟินแลนด์)",
        toolsMenu_Dictionary_fr_FR: "ภาษาฝรั่งเศส (ฝรั่งเศส)",
        toolsMenu_Dictionary_fr_CA: "ภาษาฝรั่งเศส (แคนาดา)",
        toolsMenu_Dictionary_de_DE: "ภาษาเยอรมนี (เยอรมนี)",
        toolsMenu_Dictionary_de_CH: "ภาษาเยอรมนี (สวิตเซอร์แลนด์)",
        toolsMenu_Dictionary_el_GR: "ภาษากรีซ (กรีซ)",
        toolsMenu_Dictionary_it_IT: "ภาษาอิตาลี (อิตาลี)",
        toolsMenu_Dictionary_pl_PL: "ภาษาโปแลนด์ (โปแลนด์)",
        toolsMenu_Dictionary_pt_BR: "ภาษาโปรตุเกส (บราซิล)",
        toolsMenu_Dictionary_pt_PT: "ภาษาโปรตุเกส (โปรตุเกส)",
        toolsMenu_Dictionary_ru_RU: "ภาษารัสเซีย (รัสเซีย)",
        toolsMenu_Dictionary_es_ES: "ภาษาสเปน (สเปน)",
        toolsMenu_Dictionary_sv_SE: "ภาษาสวีเดน (สวีเดน)",
        toolsMenu_Dictionary_nb_NO: "ภาษานอร์เวีย (บุ๊กมอล)",
        toolsMenu_Dictionary_nn_NO: "ภาษานอร์เวีย (นีนอสก์)",
        toolsMenu_Dictionary_he_IL: "ภาษาฮีบรู (อิสราเอล)",
        toolsMenu_SpellCheck: "รันการตรวจสอบการสะกดคำด้วยตนเอง...",
        toolsMenu_Preferences: "การกำหนดค่าตามความชอบ",
        toolsMenu_Task: "ภารกิจ",
        toolsMenu_Task_Assigntask: "กำหนดภารกิจ",
        teamMenu_AssignSlide: "กำหนดสไลด์",
        teamMenu_AssignSlides: "มอบหมายสไลด์",
        teamMenu_EditSlide: "แก้ไขการกำหนดสไลด์",
        teamMenu_ReopenSlideAssignment: "เปิดการกำหนดสไลด์อีกครั้ง",
        teamMenu_ReopenSlideAssignments: "เปิดการกำหนดสไลด์อีกครั้ง",
        teamMenu_ReassignSlide: "กำหนดสไลด์อีกครั้ง",
        teamMenu_ReassignSlides: "กำหนดสไลด์อีกครั้ง",
        teamMenu_MarkSlidesComplete: "ทำเครื่องหมายสไลด์สมบูรณ์",
        teamMenu_MarkSlidesCompletes: "ทำเครื่องหมายว่าสไลด์เสร็จสมบูรณ์",
        teamMenu_ApproveSlide: "อนุมัติสไลด์",
        teamMenu_ApproveSlides: "อนุมัติสไลด์",
        teamMenu_ReturnForRework: "ส่งคืนสไลด์สำหรับทำใหม่",
        teamMenu_ReturnForReworks: "ส่งคืนสไลด์สำหรับทำงานอีกครั้ง",
        teamMenu_RemoveAssignment: "ลบการกำหนดสไลด์ออก",
        teamMenu_AboutThisSlide: "เกี่ยวกับสไลด์นี้",

        addOnsMenu: "โปรแกรมเสริม",

        helpMenu: "วิธีใช้",
        helpMenu_About: "เกี่ยวกับ",
        helpMenu_Overview: "เนื้อหาวิธีใช้",
        helpMenu_NewFeatures: "มีอะไรใหม่",
        helpMenu_Tour: "ไกด์ทัวร์",

        accel_fileMenu_Save: "Ctrl+S",
        accel_fileMenu_Save_Mac: "\u2318S",
        accel_fileMenu_Print: "Ctrl+P",
        accel_fileMenu_Print_Mac: "\u2318P",
        accel_editMenu_SelectAll: "Ctrl+A",
        accel_editMenu_SelectAll_Mac: "\u2318A",
        accel_editMenu_Undo: "Ctrl+Z",
        accel_editMenu_Undo_Mac: "\u2318Z",
        accel_editMenu_Redo: "Ctrl+Y",
        accel_editMenu_Redo_Mac: "\u2318Y",
        accel_editMenu_Cut: "Ctrl+X",
        accel_editMenu_Cut_Mac: "\u2318X",
        accel_editMenu_Copy: "Ctrl+C",
        accel_editMenu_Copy_Mac: "\u2318C",
        accel_editMenu_Paste: "Ctrl+V",
        accel_editMenu_Paste_Mac: "\u2318V",
        accel_editMenu_Find: "Ctrl+F",
        accel_editMenu_Find_Mac: "\u2318F",
        accel_insertMenu_Link: "Ctrl+K",
        accel_insertMenu_Link_Mac: "\u2318K",
        accel_insertMenu_Header: "CTRL+SHIFT+H",
        accel_insertMenu_Header_Mac: "\u21e7\u2318H",
        accel_insertMenu_Footer: "CTRL+SHIFT+F",
        accel_insertMenu_Footer_Mac: "\u21e7\u2318F",
        accel_formatMenu_Textprop_Bold: "Ctrl+B",
        accel_formatMenu_Textprop_Bold_Mac: "\u2318B",
        accel_formatMenu_Textprop_Italic: "Ctrl+I",
        accel_formatMenu_Textprop_Italic_Mac: "\u2318I",
        accel_formatMenu_Textprop_FormatPainter: "Ctrl+SHIFT+C, Ctrl+SHIFT+V",
        accel_formatMenu_Textprop_FormatPainter_Mac: "\u21e7\u2318C, \u21e7\u2318V",
        accel_formatMenu_Textprop_Underline: "Ctrl+U",
        accel_formatMenu_Textprop_Underline_Mac: "\u2318U",
        accel_formatMenu_Headingprop_P: "CTRL+SHIFT+0",
        accel_formatMenu_Headingprop_H1: "CTRL+SHIFT+1",
        accel_formatMenu_Headingprop_H2: "CTRL+SHIFT+2",
        accel_formatMenu_Headingprop_H3: "CTRL+SHIFT+3",
        accel_formatMenu_Headingprop_H4: "CTRL+SHIFT+4",
        accel_formatMenu_Headingprop_H5: "CTRL+SHIFT+5",
        accel_formatMenu_Headingprop_H6: "CTRL+SHIFT+6",
        accel_formatMenu_Superscript: "Ctrl+.",
        accel_formatMenu_Superscript_Mac: "\u2318.",
        accel_formatMenu_Subscript: "Ctrl+,",
        accel_formatMenu_Subscript_Mac: "\u2318,",
        accel_formatMenu_Left: "CTRL+SHIFT+L",
        accel_formatMenu_Left_Mac: "\u21e7\u2318L",
        accel_formatMenu_Right: "CTRL+SHIFT+R",
        accel_formatMenu_Right_Mac: "\u21e7\u2318R",
        accel_formatMenu_Center: "CTRL+SHIFT+E",
        accel_formatMenu_Center_Mac: "\u21e7\u2318E",
        accel_formatMenu_Justify: "CTRL+SHIFT+J",
        accel_formatMenu_Justify_Mac: "\u21e7\u2318J",
        accel_formatMenu_Indent: "CTRL+M",
        accel_formatMenu_Indent_Mac: "\u2318M",
        accel_formatMenu_DecreaseIndent: "CTRL+SHIFT+M",
        accel_formatMenu_DecreaseIndent_Mac: "\u21e7\u2318M",
        accel_teamMenu_AddComment: "SHIFT+F2",

        ctxMenuSmartTable: 'ตาราง',
        ctxMenuTableProperties: "คุณสมบัติตาราง",
        ctxMenuDeleteST: 'ลบ',
        ctxMenuDeleteSTTable: 'ลบตาราง',
        ctxMenuChgSTStyle: 'เปลี่ยนสไตล์',
        ctxMenuShowCaption: 'แสดงคำบรรยายภาพ',
        ctxMenuHideCaption: 'ซ่อนคำบรรยายภาพ',
        ctxMenuResizeST: 'ปรับขนาด',
        ctxMenuResizeColumnsST: 'ปรับขนาดคอลัมน์',
        ctxMenuSTRow: 'แถว',
        ctxMenuAddSTRowAbv: 'แทรกแถวด้านบน',
        ctxMenuAddSTRowBlw: 'แทรกแถวด้านล่าง',
        ctxMenuMoveSTRowUp: 'ย้ายแถวด้านบน',
        ctxMenuMoveSTRowDown: 'ย้ายแถวด้านล่าง',
        ctxMenuDelSTRow: 'ลบ',
        ctxMenuRepeatRow: 'ทำซ้ำแถวส่วนหัว',
        ctxMenuSTCol: 'คอลัมน์',
        ctxMenuAddSTColBfr: 'แทรกคอลัมน์ก่อน',
        ctxMenuAddSTColAft: 'แทรกคอลัมน์หลัง',
        ctxMenuMoveSTColBefore: 'ย้ายคอลัมน์ก่อน',
        ctxMenuMoveSTColAfter: 'ย้ายคอลัมน์หลัง',
        ctxMenuDelSTCol: 'ลบ',
        ctxMenuSortSTColAsc: 'เรียงลำดับจากน้อยไปมาก',
        ctxMenuSortSTColDesc: 'เรียงลำดับจากมากไปน้อย',
        ctxMenuShowAllFacets: 'แสดงหมวดหมู่',
        ctxMenuHideAllFacets: 'ซ่อนหมวดหมู่',
        ctxMenuSTCell: 'เซลล์',
        ctxMenuMergeCells: 'ผสานเซลล์',
        ctxMenuMergeDown: 'ผสานกับเซลล์ด้านล่าง',
        ctxMenuVerSplit: 'แยกแนวตั้ง',
        ctxMenuHorSplit: 'แยกแนวนอน',
        ctxMenuSplitCells: 'แยกเซลล์...',
        splitCells: 'เซลล์แยก',
        ctxMenuAlignTextLeft: 'จัดตำแหน่งชิดซ้าย',
        ctxMenuAlignTextCenter: 'จัดตำแหน่งกึ่งกลาง',
        ctxMenuAlignTextRight: 'จัดตำแหน่งชิดขวา',
        ctxMenuClearSTCellContent: 'ล้างเนื้อหา',
        ctxMenuMakeHeaderRow: 'ใช้แถวที่เลือกเป็นส่วนหัว',
        ctxMenuMakeNonHeaderRow: 'ลบสไตล์ส่วนหัว',
        ctxMenuMakeHeaderCol: 'ใช้คอลัมน์ที่เลือกเป็นส่วนหัว',
        ctxMenuMakeNonHeaderCol: 'ลบสไตล์ส่วนหัว',
        SHEET_CONTEXT_Hide: "ซ่อน", // hide row, column or sheet
        SHEET_CONTEXT_Show: "แสดง", // show row, column
        SHEET_CONTEXT_MoveSheet: "ย้าย...", // move sheet
        SHEET_CONTEXT_InsertSheet: "แทรก...", // insert sheet
        SHEET_CONTEXT_DeleteSheet: "ลบ...", // delete sheet	
        SHEET_CONTEXT_DuplicateSheet: "ซ้ำ...", // duplicate sheet
        SHEET_CONTEXT_RenameSheet: "เปลี่ยนชื่อ...", // rename sheet
	
        ctxMenu_Image_WrapText: "ตัดข้อความ",
        ctxMenu_Image_WrapText_Inline: "แนวเดียวกับข้อความ",
        ctxMenu_Image_WrapText_Square: "สี่เหลี่ยม",
        ctxMenu_Image_WrapText_TopBottom: "ด้านบน และด้านล่าง",
        ctxMenu_Image_WrapText_Behind: "ข้างหลังข้อความ",
        ctxMenu_Image_WrapText_InFront: "ด้านหน้าข้อความ",
        ctxMenu_Image_WrapText_Other: "ตัดข้อความเพิ่มเติม",
        ctxMenu_Image_WrapText_BothSides: "ทั้งสองด้าน",
        ctxMenu_Image_WrapText_LeftOnly: "เฉพาะด้านซ้าย",
        ctxMenu_Image_WrapText_RightOnly: "เฉพาะด้านขวา",
        ctxMenu_Image_WrapText_LargestOnly: "เฉพาะด้านที่ใหญ่ที่สุด",

        ctxMenu_Shape_AddText: "เพิ่มข้อความ",

        ctxMenu_Range_ACL: "ป้องกันช่วง",
        ctxMenu_Sheet_ACL: "ป้องกันชีต",

        ctxMenu_HeaderFooter: "ส่วนหัว / ส่วนท้าย",
        ctxMenu_HeaderFooter_DiffFirst: "เฉพาะหน้าแรกเท่านั้น",
        ctxMenu_HeaderFooter_DiffOddEven: "สร้างเลขหน้าคู่ และหน้าคี่ให้ชิดคนละมุม",
        ctxMenu_HeaderFooter_LinkToPre: "ลิงก์ไปยังก่อนหน้า",

        ctxMenu_copy: "คัดลอก",
        ctxMenu_paste: "วาง",
        ctxMenu_delete: "ลบ",
        ctxMenu_cut: "ตัด",
        ctxMenu_select: "เลือก",
        ctxMenu_properties: "คุณสมบัติ",
        ctxMenu_bringToFront: "นำไปข้างหน้า",
        ctxMenu_sendToBack: "ส่งย้อนกลับ",
        ctxMenu_arrange: "จัดเรียง",
        ctxMenu_sendBackward: "ส่งย้อนกลับ",
        ctxMenu_sendForward: "ส่งไปข้างหน้า",
        ctxMenu_fontStyle: "ลักษณะฟอนต์",
        ctxMenu_selectStyle: "เลือกลักษณะ",
        ctxMenu_fontSize: "ขนาดฟอนต์",
        ctxMenu_fontFamily: "ตระกูลฟอนต์",
        ctxMenu_bold: "ตัวหนา",
        ctxMenu_italic: "ตัวเอียง",
        ctxMenu_u: "ขีดเส้นใต้",
        ctxMenu_strike: "ขีดเส้นทับกลาง",
        ctxMenu_super: "ตัวยก",
        ctxMenu_sub: "ตัวห้อย",
        ctxMenu_color: "สี",
        ctxMenu_bgcolor: "สีพื้นหลัง",
        ctxMenu_highcolor: "สีไฮไลต์",
        ctxMenu_restart: "รีสตาร์ทรายการ",
        ctxMenu_continue: "ทำรายการต่อไป",
        ctxMenu_separate: "แยกรายการ",
        ctxMenu_join: "รวมเข้ากับรายการก่อนหน้า",
        ctxMenu_setNumberVal: "ตั้งค่าตัวเลข...",
        webClipboardInfoTitle: "คลิปบอร์ด",
        webClipboardInfoOKBtn: "ตกลง",
        webClipboardInfoCutMsg: "ค่าติดตั้งความปลอดภัยของเบราว์เซอร์ของคุณยับยั้งการคัดลอกแบบอัตโนมัติ ให้ใช้ Ctrl+X บนคีย์บอร์ดของคุณแทน",
        webClipboardInfoCopyMsg: "ค่าติดตั้งความปลอดภัยของเบราว์เซอร์ของคุณยับยั้งการคัดลอกแบบอัตโนมัติ ให้ใช้ Ctrl+C บนคีย์บอร์ดของคุณแทน",
        webClipboardInfoPasteMsg: "ค่าติดตั้งความปลอดภัยของเบราว์เซอร์ของคุณยับยั้งเอดิเตอร์นี้ไม่ให้เข้าถึงข้อมูลคลิปบอร์ดของคุณ ให้ใช้ Ctrl+V บนคีย์บอร์ดของคุณแทน",

        clearTrackChangeConfirmMsg: "รหัสสีทั้งหมดที่แสดงการเปลี่ยนแปลงในเอกสารนี้จะถูกลบอย่างถาวร คุณต้องการทำต่อไปหรือไม่?"
});

