/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */


define({
        saveTip: "บันทึก",
        undoTip: "เลิกทำ",
        redoTip: "ทำซ้ำ",
        formatPainterTip: "คัดลอกรูปแบบ",
        showSorterTip: "แสดงตัวเรียงสไลด์",
        hideSorterTip: "ซ่อนตัวเรียงสไลด์",
        webClipboardTip: "เว็บคลิปบอร์ด",
        spellCheckTip: "รันการตรวจสอบการสะกดคำด้วยตนเอง",
        createSectionTip: "กำหนดส่วน",
        createCellsTip: "มอบหมายเซลล์",
        createSlideTip: "มอบหมายสไลด์",
        submitTip: "ส่งการมอบหมาย",
        addCommentTip: "เพิ่มข้อคิดเห็น",
        removeFormatTip: "ลบการจัดรูปแบบ",
        sortAscTip: "เรียงลำดับจากน้อยไปมาก",
        sortDescTip: "เรียงลำดับจากมากไปน้อย",
        instantFilterTip: "ตัวกรองทันที",
        insertChartTip: "แทรกแผนภูมิ",
        startAutofillTip: "Autofill",
        dataValidationTip: "การตรวจสอบข้อมูล",

        selectFontTip: "เลือกฟอนต์",
        selectFontSizeTip: "เลือกขนาดฟอนต์",
        selectFontNameTip: "เลือกชื่อฟอนต์",
        FontName: "ชื่อฟอนต์",
        FontSize: "ขนาดฟอนต์",
        increaseFontSizeTip: "เพิ่มขนาดฟอนต์",
        decreaseFontSizeTip: "ลดขนาดฟอนต์",
        boldTip: "ตัวหนา",
        italicTip: "ตัวเอียง",
        underlineTip: "ขีดเส้นใต้",
        strikeThroughTip: "ขีดฆ่า",
        setFontColorTip: "ตั้งค่าสีฟอนต์",
        setShadingColorTip: "ตั้งค่าระดับสี",
        setBackgroundFill: "ตั้งค่าการเติมพื้นหลัง",
        setBgColorTip: "ตั้งค่าสีพื้นหลัง",
        setBorderTip: "ตั้งค่าลักษณะเส้นขอบและสี",
        setBorderColorTip: "ตั้งค่าสีเส้นขอบ",
        setHighlightColor: "ตั้งค่าสีไฮไลต์",
        formatPainter: "คัดลอกรูปแบบ",
        //	clearFormat:"Remove Formatting",
        zoom: "ขยาย",
        selectStyleTip: "เลือกลักษณะ",
        styles: "ลักษณะ",
        formatAsCurrencyTip: "จัดรูปแบบเป็นสกุลเงิน",
        formatAsPercentTip: "จัดรูปแบบเป็นเปอร์เซ็นต์",
        decreaseDecimalTip: "ลดตำแหน่งทศนิยม",
        increaseDecimalTip: "เพิ่มตำแหน่งทศนิยม",
        formatNumberTip: "จัดรูปแบบตัวเลข",

        numberedListTip: "เพิ่มลำดับเลขหรือเปลี่ยนลักษณะลำดับเลข",
        bulletedListTip: "เพิ่มหัวข้อ หรือเปลี่ยนลักษณะหัวข้อ",
        multilevelListTip: "เพิ่มหรือเปลี่ยนรายการหลายระดับ",
        indentTip: "เพิ่มการเยื้อง",
        decreaseIndentTip: "ลดการเยื้อง",
        alignTip: "จัดตำแหน่ง",
        leftAlignTip: "จัดตำแหน่งชิดซ้าย",
        centerTip: "จัดตำแหน่งกึ่งกลาง",
        rightAlignTip: "จัดตำแหน่งชิดขวา",
        justifyTip: "จัดขอบ",
        bottomBorderTip: "เส้นขอบด้านล่าง",
        borderTypes: "ชนิดของเส้นขอบ",
        borderTip: "ตั้งค่ารูปแบบเส้นขอบ",
        topAlignTip: "จัดตำแหน่งบนสุด",
        middleAlignTip: "จัดตำแหน่งตรงกลาง",
        bottomAlignTip: "จัดตำแหน่งล่างสุด",
        lineSpacingTip: "ระยะห่างระหว่างบรรทัด",
        mergeSplitCellTip: "ผสานหรือแบ่งเซลล์",
        wrapNoWrapTip: "เปิดหรือปิดการตัดคำ",
        ltrDirectionTip: "เปลี่ยนเป็นข้อความแบบซ้ายไปขวา",
        rtlDirectionTip: "เปลี่ยนเป็นข้อความแบบขวาไปซ้าย",
        autoDirectionTip: "เปลี่ยนทิศทางข้อความ",
        toggleSheetDirectionTip: "เปลี่ยนทิศทางชีต",
        setSheetDirectionLTR: "ซ้ายไปขวา",
        setSheetDirectionRTL: "ขวาไปซ้าย",

        addTableTip: "เพิ่มตาราง",
        insertOrMoveRowTip: "แทรกหรือย้ายแถว",
        insertOrMoveColTip: "แทรกหรือย้ายคอลัมน์",
        insertOrDeleteRowTip: "แทรกหรือลบแถว",
        insertOrDeleteColTip: "แทรกหรือลบคอลัมน์",
        insertFunctionTip: "แทรกฟังก์ชัน",
        insertImage: "แทรกอิมเมจ",
        resizeCol: "ปรับขนาดคอลัมน์",
        resizeCols: "ปรับขนาดคอลัมน์",
        addLink: "เพิ่มหรือแก้ไขลิงก์",
        tableStyle: "ลักษณะตาราง",

        selectBorder_BottomBorder: "เส้นขอบด้านล่าง",
        selectBorder_TopBorder: "เส้นขอบด้านบน",
        selectBorder_LeftBorder: "เส้นขอบด้านซ้าย",
        selectBorder_RightBorder: "เส้นขอบด้านขวา",
        selectBorder_NoBorder: "ไม่มีเส้น",
        selectBorder_AllBorders: "เส้นขอบทั้งหมด",

        insertOrMoveRow_InsertAbove: "แทรกแถวด้านบน",
        insertOrMoveRow_InsertBelow: "แทรกแถวด้านล่าง",
        insertOrMoveRow_MoveUp: "ย้ายแถวขึ้น",
        insertOrMoveRow_MoveDown: "ย้ายแถวลง",
        insertOrMoveCol_InsertLeft: "แทรกคอลัมน์ก่อน",
        insertOrMoveCol_InsertRight: "แทรกคอลัมน์หลัง",
        insertOrMoveCol_InsertBefore: "แทรกคอลัมน์ก่อน",
        insertOrMoveCol_InsertAfter: "แทรกคอลัมน์หลัง",
        insertOrMoveCol_MoveLeft: "ย้ายคอลัมน์ซ้าย",
        insertOrMoveCol_MoveRight: "ย้ายคอลัมน์ขวา",

        insertOrDelete_Delete: "ลบ",

        combineButtonReadTip: "กดคีย์ลูกศรลงเพื่อเปิดใช้งานเมนู  จากนั้นนำทางด้วยคีย์ลูกศร",

        lineSpacing_1: "1",
        lineSpacing_12: "1.2",
        lineSpacing_15: "1.5",
        lineSpacing_2: "2",
        lineSpacing_25: "2.5",
        lineSpacing_3: "3",

        percent: "%",
        font_arial: "Arial",

        fontSize: "${0}pt",

        slides: "หนึ่งสไลด์ต่อหน้า",
        slidesWithNotes: "สไลด์ที่มีหมายเหตุ",
        preparingSlides: "กำลังเตรียมสไลด์ของคุณเพื่อการพิมพ์...",
        printLayoutOptionLabel: "พิมพ์ตัวเลือกโครงร่าง",

        targetRemovedWhenDialogOpen: "ไม่สามารถทำแอ็คชันนี้ให้เสร็จสมบูรณ์ เนื่องจากเป้าหมายถูกลบออกแล้วโดยเอดิเตอร์ร่วมอื่น",

        NUMBER: "ตัวเลข",
        CURRENCY: "สกุลเงิน",
        PERCENT: "เปอร์เซนต์",
        DATE: "วันที่",
        TIME: "เวลา",
        DATETIME: "DateTime",
        MORECURRENCY: "สกุลเงินเพิ่มเติมโดยเรียงตามหน่วยเงินตรา",
        MORECURRENCYCODE: "สกุลเงินเพิ่มเติมโดยเรียงตามโค้ดสกุลเงิน",
        MOREDATE: "รูปแบบเวลาและวันที่เพิ่มเติม",
        TEXT: "ข้อความ",
	
        // currency, by currency code
        // NOTE: MUST keep it in order
        CURRENCY_CODE: {
            AED: "สหรัฐอาหรับเอมิเรตส์ (เดอร์แฮม)",
            ARS: "อาร์เจนตินา (เปโซ)",
            AUD: "ออสเตรเลีย (ดอลลาร์)",
            BGN: "บัลแกเรีย (เลฟ)",
            BOB: "โบลิเวีย (โบลีเบียโน)",
            BRL: "บราซิล (เรอัล)",
            CAD: "แคนาดา (ดอลลาร์)",
            CHF: "สวิตเซอร์แลนด์ (ฟรังก์)",
            CLP: "ชิลี (เปโซ)",
            CNY: "จีน (หยวนเหรินหมินปี้)",
            COP: "โคลอมเบีย (เปโซ)",
            CRC: "คอสตาริกา (โกลอน)",
            CZK: "สาธารณรัฐเช็ก (โครูนา)",
            DKK: "เดนมาร์ก (โครน)",
            DOP: "สาธารณรัฐโดมินิกัน (เปโซ)",
            EGP: "อียิปต์ (ปอนด์)",
            EUR: "ออสเตรีย เบลเยียม ฟินแลนด์ ฝรั่งเศส,  ..., สโลวีเนีย สเปน (ยูโร)",
            GBP: "อังกฤษ สหราชอาณาจักร (ปอนด์)",
            HKD: "ฮ่องกง (ดอลลาร์)",
            HRK: "โครเอเชีย (คูนา)",
            HUF: "ฮังการี (โฟรินต์)",
            IDR: "อินโดนีเซีย (รูปียะฮ์)",
            ILS: "อิสราเอล (นิวเชเกล)",
            INR: "อินเดีย (รูปี)",
            JPY: "ญี่ปุ่น (เยน)",
            KRW: "เกาหลีใต้ (วอน)",
            KZT: "คาซัคสถาน (เตงเก)",
            MAD: "โมร็อกโก (ดีร์แฮม)",
            MXN: "เม็กซิโก (เปโซ)",
            MYR: "มาเลเซีย (ริงกิต)",
            NOK: "นอร์เวย์ (โครน)",
            NZD: "นิวซีแลนด์ (ดอลลาร์)",
            PAB: "ปานามา (บัลโบอา)",
            PEN: "เปรู (นูโวซอล)",
            PHP: "ฟิลิปปินส์ (เปโซ)",
            PKR: "ปากีสถาน (รูปี)",
            PLN: "โปแลนด์ (ซวอตือ)",
            PYG: "ปารากวัย (กวารานี)",
            RON: "โรมาเนีย (นิวลิว)",
            RSD: "เซอร์เบีย (ซีริลลิก), เซอร์เบีย (ละติน)",
            RUB: "รัสเซีย (รูเบิล)",
            SAR: "ซาอุดีอาระเบีย (ริยาล)",
            SEK: "สวีเดน (โครนา)",
            SGD: "สิงคโปร์ (ดอลลาร์)",
            SVC: "เอลซัลวาดอร์ (โคลอน)",
            THB: "ไทย (บาท)",
            TRY: "ตุรกี (ลีรา)",
            TWD: "ไต้หวัน (ดอลลาร์ไต้หวันใหม่)",
            USD: "เอกวาดอร์ เปอร์โตริโก สหรัฐอเมริกา (ดอลลาร์สหรัฐฯ)",
            UYU: "อุรุกวัย (เปโซ)",
            VEF: "เวเนซุเอลา (โบลิวาร์)",
            VND: "เวียดนาม (ดอง)",
            ZAR: "แอฟริกาใต้ (แรนด์)"
        },
        // for border toolbar
        allBorders: "เส้นขอบทั้งหมด",
        innerBorders: "เส้นขอบภายใน",
        horizontalBorders: "เส้นขอบแนวนอน",
        verticalBorders: "เส้นขอบแนวตั้ง",
        outerBorders: "เส้นขอบภายนอก",
        borderColor: "สีเส้นขอบ",
        leftBorder: "เส้นขอบด้านซ้าย",
        topBorder: "เส้นขอบด้านบน",
        rightBorder: "เส้นขอบด้านขวา",
        bottomBorder: "เส้นขอบด้านล่าง",
        clearBorders: "ไม่มีเส้นขอบ",
        BorderStyle_ThinSolid: "เส้นทึบบาง",
        BorderStyle_ThinDotted: "เส้นประบาง",
        BorderStyle_ThinDashed: "เส้นขีดบาง",
        BorderStyle_ThickSolid: "เส้นทึบหนา",
        BorderStyle_ThickDotted: "เส้นประหนา",
        BorderStyle_ThickDashed: "เส้นขีดหนา"
})

