﻿/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        fileMenu: "Dosya",
        fileMenu_New: "Yeni",
        fileMenu_NewDocument: "Belge",
        fileMenu_NewFromTemplate: "Şablondan",
        fileMenu_NewDocumentfromTemplate: "Şablondan Belge",
        fileMenu_NewPresentation: "Sunum",
        fileMenu_NewPresentationfromTemplate: "Şablondan Sunum",
        fileMenu_NewSpreadsheet: "Elektronik Sayfa",
        fileMenu_NewSpreadsheetFromTemplate: "Şablondan Elektronik Sayfa",
        fileMenu_Open: "Aç",
        fileMenu_Import: "Al...",
        //	fileMenu_Close: "Close",
        fileMenu_Discard: "Son Sürüme Geri Dön",
        fileMenu_ClearTrackChange: "Değişiklik İşaretlerini Kaldır",
        fileMenu_SpreadsheetSettings: "Belge Yerel Ayarını Ayarla...",
        filemenu_revisionhistory: "Düzeltmeler",
        fileMenu_Save: "Kaydet",
        fileMenu_SaveAs: "Kopyala...",
        fileMenu_AutoPublish: "Otomatik Olarak Yayınla",
        fileMenu_AutoCheckIn: "Otomatik Olarak Geri Ver",
        fileMenu_PublishVersion: "Şimdi Yayınla",
        fileMenu_AutoPublish2: "Havuza Otomatik Olarak Kaydet",
        //	fileMenu_AutoPublish_Tips: "Makes your changes available to readers at the end of each editing session.",
        fileMenu_PublishVersion2: "Havuza Şimdi Kaydet",
        fileMenu_AutoPublish3: "${0} İçine Otomatik Kaydet",
        fileMenu_PublishVersion3: "${0} İçine Şimdi Kaydet",      
        fileMenu_SubmitForReview: "İnceleme İçin Gönder...",
        fileMenu_CheckinVersion: "Geri Ver...",
        fileMenu_Unlock: "Kilidi Aç",
        //	fileMenu_SaveAsDraft: "as Draft",
        //	fileMenu_SaveInMyDocs: "in My Documents",
        //	fileMenu_SaveToSymphony: "to Lotus Symphany",
        fileMenu_DownloadAs: "Şu biçimde yükle:",
        fileMenu_PDF: "PDF",
        fileMenu_ODF: "ODF",
        fileMenu_DOC: "Microsoft Word 97- 2007 (*.doc)",
        fileMenu_ODS: "ODS",
        fileMenu_XLS: "Microsoft Excel 97-2007 (*.xls) ",
        fileMenu_ShareWith: "Paylaş...",
        fileMenu_ExportAsPDF: "PDF",
        fileMenu_ExportAsODF: "ODF",
        fileMenu_ExportAsPPT: "Microsoft Powerpoint 97- 2007 (*.ppt)",
        //	fileMenu_WebPreview: "Web Preview",
        fileMenu_PrintToPDF: "PDF Olarak Yazdır...",
        fileMenu_ViewFileDetails: "Dosya Ayrıntılarını Görüntüle...",
        fileMenu_RecentFile: "En Son Dosyalar",
        fileMenu_Open: "Aç",
        fileMenu_Download: "Karşıdan Yükle",
        fileMenu_Print: "Yazdır",
        fileMenu_Export: "Ver",
        fileMenu_ExportToCSV: "CSV",
        fileMenu_ExportToPDF: "PDF (.pdf)",
        fileMenu_ExportToMarkdown: "Markdown(.md)",
        fileMenu_ExportToMS: "Microsoft Office biçimi (.${FILEEXTENSION})",
        fileMenu_ExportToODF: "Open Document biçimi (.${FILEEXTENSION})",
        fileMenu_PgSetup: "Sayfa Düzeni...",

        editMenu: "Düzenle",
        editMenu_Undo: "Geri Al",
        editMenu_Redo: "Yinele",
        editMenu_Cut: "Kes",
        editMenu_Copy: "Kopyala",
        editMenu_Paste: "Yapıştır",
        editMenu_DeleteSlide: "Slaydı Sil",
        editMenu_SelectAll: "Tümünü Seç",
        editMenu_Find: "Bul...",
        editMenu_Replace: "Değiştir...",
        editMenu_FindReplace: "Bul ve Değiştir...",
        editMenu_EditLink: "Bağlantı Ekle ya da Düzenle",
        editMenu_DeleteSheet: "Sayfayı Sil...",
        editMenu_RenameSheet: "Sayfayı Yeniden Adlandır...",
        editMenu_HideSheet: "Sayfayı Gizle",
        editMenu_MoveSheet: "Sayfayı Taşı...",
        editMenu_DeleteRow: "Satırı Sil",
        editMenu_DeleteColumn: "Sütunu Sil",
        editMenu_DeleteCellLeft: "Hücreleri Sil ve Sola Kaydır",
        editMenu_DeleteCellUp: "Hücreleri Sil ve Yukarı Kaydır",
        editMenu_ClearCell: "İçeriği Sil",

        viewMenu: "Görüntüle",
        viewMenu_Master: "Ana",
        viewMenu_Notifications: "Bildirimler",
        viewMenu_SlideSorter: "Slayt Düzenleyici",
        viewMenu_SpeakerNotes: "Konuşmacı Notları",
        viewMenu_Toolbar_Basic: "Temel",
        viewMenu_Toolbar_Advanced: "Gelişmiş",
        viewMenu_Toolbar_None: "Hiçbiri",
        viewMenu_Toolbar: "Araç Çubuğu",
        viewMenu_Statusbar: "Durum Çubuğu",
        viewMenu_Navigator: "Gezgin...",
        //viewMenu_Sidebar: "Sidebar",
        viewMenu_ShowHideIndicators: "Yardımcı Düzenleyici Göstergelerini Göster",
        viewMenu_Assignment: "Atama Göstergeleri",
        viewMenu_Bookmark: "Yer İşaretleri",
        viewMenu_Coediting: "Birlikte Düzenleme Vurgulamaları",
        viewMenu_Rulers: "Cetveller",
        viewMenu_WebLayout: "Web Düzeni",
        viewMenu_AutomaticSpellCheck: "Yazarken Yazım Denetimi Yap",
        viewMenu_Formulabar: "Formül Çubuğu",
        viewMenu_moveRight: "Enter, İmleci Sağa Taşır",
        viewMenu_showFullString: "İçeriği Hücrelerde Genişlet",
        viewMenu_Doc: "Belgeyi Görüntüle",
        viewMenu_Templates: "Şablonlar",
        viewMenu_GridLines: "Kılavuz Çizgileri Gizle",
        viewMenu_UnsupportWarning: "Desteklenmeyen Özellik İletilerini Göster",
        viewMenu_HiddenSheets: "Gizli Sayfalar",
        viewMenu_FreezeRows: "Satırları Dondur",
        viewMenu_FreezeColumns: "Sütunları Dondur",
        viewMenu_NoFrozenRows: "Dondurulmuş Satır Yok",
        viewmenu_NoFrozenColumns: "Dondurulmuş Sütun Yok",
        viewMenu_FreezeXRows: "${0} Satırı Dondur",
        viewMenu_FreezeOneRow: "${0} Satırı Dondur",
        viewMenu_FreezeXColumns: "${0} Sütunu Dondur",
        viewMenu_FreezeOneColumn: "${0} Sütunu Dondur",
        viewMenu_CarriageReturn: "Biçimlendirme İşaretleri",
        viewMenu_Navigation: "Gezinme Bölmesi",
        viewMenu_ACL: "Düzenlenebilir Alanlar",
        viewMenu_GridOnOff: "Kılavuz Çizgiler",
        viewMenu_ObserverMode: 'Gözlemci Modu',

        createMenu: "Ekle",
        createMenu_NewSlide: "Yeni Slayt",
        createMenu_DuplicateSlide: "Slaydı Yinele",
        createMenu_ImageFromFile: "Resim...",
        createMenu_TextBox: "Metin Kutusu",
        createMenu_Shape: "Şekil",
        createMenu_break: "Kesme",
        createMenu_RowAbove: "Üstüne Satır Ekle",
        createMenu_RowBelow: "Aşağıya Satır Ekle",
        createMenu_ColumnRight: "Sağdaki Sütun",
        createMenu_ColumnLeft: "Soldaki Sütun",
        createMenu_Sheet: "Sayfa...",
        createMenu_Image: "Resim...",
        createMenu_Comments: "Yorum...",
        createMenu_WebLink: "Web Bağlantısı...",
        createMenu_SpecialCharacter: "Özel Karakter...",
        createMenu_Function: "İşlev...",
        createMenu_Fromtemplate: "Şablondan Oluştur",

        insertMenu: "Ekle",
        insertMenu_break: "Sayfa Sonu",
        insertMenu_sectionbreak: "Bölüm Sonu",
        insertMenu_Bookmark: "Yer İşareti...",
        insertMenu_WebLink: "Bağlantı...",
        insertMenu_SpecialCharacter: "Özel Karakter...",
        insertMenu_HorizontalLine: "Yatay Çizgi",
        insertMenu_Header: "Üstbilgi",
        insertMenu_Footer: "Altbilgi",
        insertMenu_TableOfContents: "İçindekiler Tablosu",

        insertMenu_HeaderFooter: "Üstbilgi/Altbilgi",
        insertMenu_HF_Edit: "Düzenle",
        insertMenu_HF_Hide: "Gizle",
        insertMenu_Endnotes: "Sonnotlar",
        insertMenu_RowAbove: "Üstüne Satır Ekle",
        insertMenu_PageNumber: "Sayfa Numarası",
        insertMenu_PageNumberTop: "Sayfanın Üstü",
        insertMenu_PageNumberBottom: "Sayfanın Altı",
        insertMenu_PageNumberCurr: "Geçerli Konum",
        insertMenu_TotalPageNumber: "Sayfa 1 / N",
        insertMenu_Date: "Tarih...",
        insertMenu_Time: "Saat...",
        insertMenu_Fields: "Alanlar",
        //    insertMenu_Comment: "Comment",
        insertMenu_CellRight: "Hücreler ve Sağa Kaydır",
        insertMenu_CellDown: "Hücreler ve Aşağı Kaydır",
        insertMenu_RowBelow: "Aşağıya Satır Ekle",
        insertMenu_ColumnBefore: "Önüne Sütun Ekle",
        insertMenu_ColumnAfter: "Arkasına Sütun Ekle",
        insertMenu_Sheet: "Sayfa...",
        insertMenu_Image: "Resim...",
        insertMenu_DuplicateSheet: "Sayfayı Yinele",
        insertMenu_Function: "İşlev",
        insertMenu_FunctionSum: "SUM",
        insertMenu_FunctionAverage: "AVERAGE",
        insertMenu_FunctionCount: "COUNT",
        insertMenu_FunctionMax: "MAX",
        insertMenu_FunctionMin: "MIN",
        insertMenu_FunctionMore: "Diğer İşlevler...",
        insertMenu_NameRange: "Adlandırılmış Aralık",
        insertMenu_NameRangeNew: "Yeni Aralık...",
        insertMenu_NameRangeManage: "Aralıkları Yönet...",
        insertMenu_Chart: "Grafik...",

        contextMenu_insertCellRight: "Hücreleri Ekle ve Sağa Kaydır",
        contextMenu_insertCellDown: "Hücreleri Ekle ve Aşağı Kaydır",
        contextMenu_InsertRowAbove: "Satırı Yukarı Ekle",
        contextMenu_InsertRowBelow: "Satırı Aşağı Ekle",
        contextMenu_InsertColumnBefore: "Sütunu Önüne Ekle",
        contextMenu_InsertColumnAfter: "Sütunu Arkasına Ekle",
        contextMenu_DownloadImage: "Resim Olarak Karşıdan Yükle",

        formatMenu: "Biçim",
        formatMenu_Columns: "Sütunlar",
        formatMenu_DefaultFormatting: "Varsayılan Biçimlendirme",
        formatMenu_Template: "Stiller...",
        contextMenu_Template: "Tablo Stilleri...",
        formatMenu_LineSpacing: "Satır Aralığı",
        formatMenu_LineSpacing1: "1",
        formatMenu_LineSpacing12: "1,2",
        formatMenu_LineSpacing15: "1.5",
        formatMenu_LineSpacing2: "2",
        formatMenu_LineSpacing25: "2,5",
        formatMenu_LineSpacing3: "3",
        formatMenu_TextProperties: "Metin Özellikleri",
        formatMenu_PageBreakBefore: "Önüne Sayfa Sonu",
        formatMenu_KeepLines: "Satırları Bir Arada Tut",
        formatMenu_WidowControl: "Tek Kalan Satır Denetimi",
        formatMenu_Pagination: "Paragraf Özellikleri",
        formatMenu_Bold: "Kalın",
        formatMenu_Italic: "İtalik",
        formatMenu_Underline: "Altı Çizili",
        formatMenu_Strikethrough: "Üstü Çizili",
        formatMenu_IncreaseSize: "Yazı Tipi Boyutunu Artır",
        formatMenu_DecreaseSize: "Yazı Tipi Boyutunu Azalt",
        formatMenu_ImageProperties: "Resim Özellikleri...",
        formatMenu_ChartProperties: "Grafik Özellikleri...",
        formatMenu_EditChart: "Grafiği Düzenle",
        formatMenu_InsertChart: "Grafik Ekle",
        formatMenu_Properties: "Özellikler...",
        formatMenu_Heading: "Başlık",
        formatMenu_Normal: "Normal",
        formatMenu_Title: "Başlık",
        formatMenu_Subtitle: "Alt başlık",
        formatMenu_Heading1: "Başlık 1",
        formatMenu_Heading2: "Başlık 2",
        formatMenu_Heading3: "Başlık 3",
        formatMenu_Heading4: "Başlık 4",
        formatMenu_Heading5: "Başlık 5",
        formatMenu_Heading6: "Başlık 6",
        formatMenu_Heading7: "Başlık 7",
        formatMenu_Heading8: "Başlık 8",
        formatMenu_Heading9: "Başlık 9",
        formatMenu_BulletedList: "Madde İşaretli Liste",
        formatMenu_NumberedList: "Numaralı Liste",
        formatMenu_OutLine: "Çok Düzeyli Liste",
        formatMenu_Superscript: "Üst Simge",
        formatMenu_Subscript: "Alt Simge",
        formatMenu_Align: "Hizala",
        formatMenu_Left: "Sola",
        formatMenu_Right: "Sağa",
        formatMenu_Center: "Ortala",
        formatMenu_Justify: "Yasla",
        formatMenu_Text_Direction: "Metin Yönü",
        formatMenu_Ltr: "Soldan Sağa",
        formatMenu_Rtl: "Sağdan Sola",
        formatMenu_LineSpacing: "Satır Aralığı",
        formatMenu_LineSpacing1: "1.0",
        formatMenu_LineSpacing115: "1.15",
        formatMenu_LineSpacing15: "1.5",
        formatMenu_LineSpacing2: "2.0",
        formatMenu_LineSpacing25: "2,5",
        formatMenu_LineSpacing3: "3.0",
        formatMenu_Top: "Üste",
        formatMenu_Bottom: "Alta",
        formatMenu_Middle: "Ortaya",
        formatMenu_Direction: "Metin Yönü",
        formatMenu_Rtl: "Sağdan Sola",
        formatMenu_Ltr: "Soldan Sağa",
        formatMenu_Auto: "Bağlamsal",
        formatMenu_SheetDirection: "Sayfa Yönü",
        formatMenu_SheetRtl: "Sağdan Sola",
        formatMenu_SheetLtr: "Soldan Sağa",
        formatMenu_Indent: "Girintiyi Artır",
        formatMenu_DecreaseIndent: "Girintiyi Azalt",
        formatMenu_ClearFormat: "Biçimlendirmeyi Temizle",
        formatMenu_RowHeight: "Satır Yüksekliği",
        formatMenu_ColumnWidth: "Sütun Genişliği",
        formatMenu_ShowRow: "Satırı Göster",
        formatMenu_HideRow: "Satırı Gizle",
        formatMenu_ShowColumn: "Sütunu Göster",
        formatMenu_HideColumn: "Sütunu Gizle",
        formatMenu_WrapText: "Metni Kaydır",
        formatMenu_Number: "Sayı",
        formatMenu_FontArial: "Arial",
        formatMenu_FontComicSansMS: "Comic Sans MS",
        formatMenu_FontCourierNew: "Courier New",
        formatMenu_FontGeorgia: "Georgia",
        formatMenu_FontLucidaSansUnicode: "Lucida Sans Unicode",
        formatMenu_FontTahoma: "Tahoma",
        formatMenu_FontTimesNewRoman: "Times New Roman",
        formatMenu_FontTrebuchetMS: "Trebuchet MS",
        formatMenu_FontVerdana: "Verdana",
        formatMenu_FontName: "Yazı Tipi",

        layoutMenu: "Düzen",
        layoutMenu_SlideLayout: "Slayt Düzeni...",
        layoutMenu_SlideDesign: "Ana Stil...",
        layoutMenu_DefaultFormatting: "Varsayılan Biçimlendirme",
        layoutMenu_Textprop_Bold: "Kalın",
        layoutMenu_Textprop_Italic: "İtalik",
        layoutMenu_Textprop_Underline: "Altı Çizili",
        layoutMenu_Textprop_Strikethrough: "Üstü Çizili",
        layoutMenu_TextProp: "Metin Özellikleri",
        LayoutMenu_RowHeight: "Satır Yüksekliği...",
        LayoutMenu_ColumnWidth: "Sütun Genişliği...",
        LayoutMenu_ShowRow: "Satırı Göster",
        LayoutMenu_HideRow: "Satırı Gizle",
        LayoutMenu_RenameSheet: "Sayfayı Yeniden Adlandır...",
        LayoutMenu_MoveSheet: "Sayfayı Taşı",

        tableMenu: "Tablo",
        tableMenu_Create: "Oluştur...",
        tableMenu_CreateFromTemplate: "Şablondan Oluştur",
        tableMenu_Delete: "Sil",
        tableMenu_SetTableColor: "Hücre Rengi",
        tableMenu_CreateTable: "Tablo Oluştur",
        tableMenu_Cell: "Hücre",
        tableMenu_CellMergeCells: "Hücreleri Birleştir",
        tableMenu_CellAlignLeft: "Sola Hizala",
        tableMenu_CellAlignCenter: "Ortala",
        tableMenu_CellAlignRight: "Sağa Hizala",
        tableMenu_CellClearContents: "İçeriği Temizle",
        tableMenu_CellProperties: "Hücre Özellikleri...",
        tableMenu_Row: "Satır",
        tableMenu_InsertRowAbove: "Satırı Yukarı Ekle",
        tableMenu_InsertRowBelow: "Satırı Aşağı Ekle",
        tableMenu_MoveRowAbove: "Satırı Yukarı Taşı",
        tableMenu_MoveRowBelow: "Satırı Aşağı Taşı",
        tableMenu_RowInsertRow: "Satır Ekle...",
        tableMenu_RowInsertRowAbove: "Satırı Yukarı Ekle",
        tableMenu_RowInsertRowBelow: "Satırı Aşağı Ekle",
        tableMenu_RowMoveRowAbove: "Satırı Yukarı Taşı",
        tableMenu_RowMoveRowBelow: "Satırı Aşağı Taşı",
        tableMenu_RowDelete: "Sil",
        tableMenu_RowRepeat: "Üstbilgi Satırını Yinele",
        tableMenu_InsertColumnBefore: "Sütunu Önüne Ekle",
        tableMenu_InsertColumnAfter: "Sütunu Arkasına Ekle",
        tableMenu_MoveColumnBefore: "Sütunu Sola Taşı",
        tableMenu_MoveColumnAfter: "Sütunu Sağa Taşı",
        tableMenu_ResizeColumn: "Sütunu Yeniden Boyutlandır",
        tableMenu_ResizeColumns: "Sütunları Yeniden Boyutlandır",
        tableMenu_MarkasCategory: "Kategori Olarak İşaretle",
        tableMenu_ColumnInsertColumn: "Sütun Ekle...",
        tableMenu_ColumnAddColumnBefore: "Sütunu Önüne Ekle",
        tableMenu_ColumnAddColumnAfter: "Sütunu Arkasına Ekle",
        tableMenu_ColumnMoveColumnAfter: "Sütunu Arkasına Taşı",
        tableMenu_ColumnMoveColumnBefore: "Sütunu Önüne Taşı",
        tableMenu_ColumnDelete: "Sil",
        tableMenu_ColumnSortAscending: "Artan Düzende Sırala",
        tableMenu_ColumnSortDescending: "Azalan Düzende Sırala",
        tableMenu_Column: "Sütun",
        tableMenu_Style: "Stil",
        tableMenu_TableProperties: "Tablo Özellikleri...",

        teamMenu: "Ekip",
        teamMenu_AddComment: "Yorum Ekle",
        teamMenu_AssignCells: "Hücreleri Ata",
        teamMenu_AssignSection: "Bölüm Ata",
        teamMenu_EditAssignment: "Atamayı Düzenle",
        teamMenu_MarkSectionComplete: "Bölümü Tamamlandı Olarak İşaretle",
        teamMenu_MarkAssignmentComplete: "Atamayı Tamamlandı Olarak İşaretle",
        teamMenu_WorkPrivatelyOnSection: "Bu Bölümde Özel Olarak Çalış",
        teamMenu_CancelPrivateWork: "Özel Çalışmayı İptal Et",
        teamMenu_ApproveSection: "Bölümü Onayla",
        teamMenu_ApproveAssignment: "Atamayı Onayla",
        teamMenu_ReturnSectionForRework: "Yeniden Çalışma İçin Bölüme Dön",
        teamMenu_ReturnAssignmentForRework: "Yeniden Çalışma İçin Atamaya Dön",
        teamMenu_RemoveSectionAssignment: "Bölüm Atamasını Kaldır",
        teamMenu_RemoveCellAssignment: "Hücre Atamasını Kaldır",
        teamMenu_RemoveCompletedAssignments: "Tamamlanan Atamaları Kaldır",
        teamMenu_AboutThisSection: "Bu Bölüm Hakkında",
        teamMenu_AboutAssignment: "Bu Atama Hakkında",

        presentationMenu: "Sunum",
        presentationMenu_SlideShow: "Slayt Gösterisini Oynat",
        presentationMenu_SlideShowWithCoview: "Paylaşılan Slayt Gösterisini Oynat",
        presentationMenu_SlideTransitions: "Slayt Geçişini Uygula...",
        presentationMenu_SlideShowFromCurrent: "Geçerli Slayttan Oynat",
        presentationMenu_EmptyCoviewInvites: "Etkin Paylaşılan Slayt Gösterisi Yok",
        presentationMenu_CoviewInvites: "Etkin Paylaşılan Slayt Gösterisi",

        dataMenu: "Veri",
        dataMenu_Sort: "Sırala...",
        dataMenu_SortAsc: "Artan Düzende Sırala",
        dataMenu_SortDesc: "Azalan Düzende Sırala",
        dataMenu_ACL: "Korumalı Alanlar",
        dataMenu_ACL_DELETE: "Tüm İzinleri Sil",
        dataMenu_Validity: "Geçerlilik",
        dataMenu_InstantFilter: "Anında Süzgeç",
        dataMenu_Validation: "Doğrulama...",

        toolsMenu: "Araçlar",
        toolsMenu_AutoComplete: "Hücre Girdilerini Otomatik Doldur",
        toolsMenu_SelectDictionary: "Yazım Denetimi Sözlükleri",
        toolsMenu_Dictionary_ca_CT: "Katalanca",
        toolsMenu_Dictionary_cs_CZ: "Çekçe (Çek)",
        toolsMenu_Dictionary_da_DK: "Danca (Danimarka)",
        toolsMenu_Dictionary_nl_NL: "Felemenkçe (Hollanda)",
        toolsMenu_Dictionary_en_AU: "İngilizce (Avustralya)",
        toolsMenu_Dictionary_en_GB: "İngilizce (İngiltere)",
        toolsMenu_Dictionary_en_US: "İngilizce (ABD)",
        toolsMenu_Dictionary_fi_FI: "Fince (Finlandiya)",
        toolsMenu_Dictionary_fr_FR: "Fransızca (Fransa)",
        toolsMenu_Dictionary_fr_CA: "Fransızca (Kanada)",
        toolsMenu_Dictionary_de_DE: "Almanca (Almanya)",
        toolsMenu_Dictionary_de_CH: "Almanca (İsviçre)",
        toolsMenu_Dictionary_el_GR: "Yunanca (Yunanistan)",
        toolsMenu_Dictionary_it_IT: "İtalyanca (İtalya)",
        toolsMenu_Dictionary_pl_PL: "Lehçe (Polonya)",
        toolsMenu_Dictionary_pt_BR: "Portekizce (Brezilya)",
        toolsMenu_Dictionary_pt_PT: "Portekizce (Portekiz)",
        toolsMenu_Dictionary_ru_RU: "Rusça (Rusya)",
        toolsMenu_Dictionary_es_ES: "İspanyolca (İspanya)",
        toolsMenu_Dictionary_sv_SE: "İsveççe (İsveç)",
        toolsMenu_Dictionary_nb_NO: "Norveççe (Bokmål)",
        toolsMenu_Dictionary_nn_NO: "Norveççe (Nynorsk)",
        toolsMenu_Dictionary_he_IL: "İbranice (İsrail)",
        toolsMenu_SpellCheck: "El İle Yazım Denetimini Yürüt...",
        toolsMenu_Preferences: "Tercihler",
        toolsMenu_Task: "Görev",
        toolsMenu_Task_Assigntask: "Görev Ata",
        teamMenu_AssignSlide: "Slayt Ata",
        teamMenu_AssignSlides: "Slaytları Ata",
        teamMenu_EditSlide: "Slayt Atamasını Düzenle",
        teamMenu_ReopenSlideAssignment: "Slayt Atamasını Yeniden Aç",
        teamMenu_ReopenSlideAssignments: "Slayt Atamalarını Yeniden Aç",
        teamMenu_ReassignSlide: "Slaydı Yeniden Ata",
        teamMenu_ReassignSlides: "Slaytları Yeniden Ata",
        teamMenu_MarkSlidesComplete: "Slaydı Tamamlandı Olarak İşaretle",
        teamMenu_MarkSlidesCompletes: "Slaytları Tamamlandı Olarak İşaretle",
        teamMenu_ApproveSlide: "Slaydı Onayla",
        teamMenu_ApproveSlides: "Slaytları Onayla",
        teamMenu_ReturnForRework: "Yeniden Çalışma İçin Slayda Dön",
        teamMenu_ReturnForReworks: "Yeniden Çalışma İçin Slaytlara Dön",
        teamMenu_RemoveAssignment: "Slayt Atamasını Kaldır",
        teamMenu_AboutThisSlide: "Bu Slayt Hakkında",

        addOnsMenu: "Eklentiler",

        helpMenu: "Yardım",
        helpMenu_About: "Hakkında",
        helpMenu_Overview: "Yardım İçeriği",
        helpMenu_NewFeatures: "Yenilikler",
        helpMenu_Tour: "Rehberli Tur",

        accel_fileMenu_Save: "Ctrl+S",
        accel_fileMenu_Save_Mac: "\u2318S",
        accel_fileMenu_Print: "Ctrl+P",
        accel_fileMenu_Print_Mac: "\u2318P",
        accel_editMenu_SelectAll: "Ctrl+A",
        accel_editMenu_SelectAll_Mac: "\u2318A",
        accel_editMenu_Undo: "Ctrl+Z",
        accel_editMenu_Undo_Mac: "\u2318Z",
        accel_editMenu_Redo: "Ctrl+Y",
        accel_editMenu_Redo_Mac: "\u2318Y",
        accel_editMenu_Cut: "Ctrl+X",
        accel_editMenu_Cut_Mac: "\u2318X",
        accel_editMenu_Copy: "Ctrl+C",
        accel_editMenu_Copy_Mac: "\u2318C",
        accel_editMenu_Paste: "Ctrl+V",
        accel_editMenu_Paste_Mac: "\u2318V",
        accel_editMenu_Find: "Ctrl+F",
        accel_editMenu_Find_Mac: "\u2318F",
        accel_insertMenu_Link: "Ctrl+K",
        accel_insertMenu_Link_Mac: "\u2318K",
        accel_insertMenu_Header: "CTRL+ÜST KRKTR+H",
        accel_insertMenu_Header_Mac: "\u21e7\u2318H",
        accel_insertMenu_Footer: "CTRL+ÜST KRKTR+F",
        accel_insertMenu_Footer_Mac: "\u21e7\u2318F",
        accel_formatMenu_Textprop_Bold: "Ctrl+B",
        accel_formatMenu_Textprop_Bold_Mac: "\u2318B",
        accel_formatMenu_Textprop_Italic: "Ctrl+I",
        accel_formatMenu_Textprop_Italic_Mac: "\u2318I",
        accel_formatMenu_Textprop_FormatPainter: "Ctrl+ÜST KRKT+C, Ctrl+ÜST KRKT+V",
        accel_formatMenu_Textprop_FormatPainter_Mac: "\u21e7\u2318C, \u21e7\u2318V",
        accel_formatMenu_Textprop_Underline: "Ctrl+U",
        accel_formatMenu_Textprop_Underline_Mac: "\u2318U",
        accel_formatMenu_Headingprop_P: "CTRL+ÜST KRKTR+0",
        accel_formatMenu_Headingprop_H1: "CTRL+ÜST KRKTR+1",
        accel_formatMenu_Headingprop_H2: "CTRL+ÜST KRKTR+2",
        accel_formatMenu_Headingprop_H3: "CTRL+ÜST KRKTR+3",
        accel_formatMenu_Headingprop_H4: "CTRL+ÜST KRKTR+4",
        accel_formatMenu_Headingprop_H5: "CTRL+ÜST KRKTR+5",
        accel_formatMenu_Headingprop_H6: "CTRL+ÜST KRKTR+6",
        accel_formatMenu_Superscript: "Ctrl+.",
        accel_formatMenu_Superscript_Mac: "\u2318.",
        accel_formatMenu_Subscript: "Ctrl+,",
        accel_formatMenu_Subscript_Mac: "\u2318,",
        accel_formatMenu_Left: "CTRL+ÜST KRKTR+L",
        accel_formatMenu_Left_Mac: "\u21e7\u2318L",
        accel_formatMenu_Right: "CTRL+ÜST KRKTR+R",
        accel_formatMenu_Right_Mac: "\u21e7\u2318R",
        accel_formatMenu_Center: "CTRL+ÜST KRTR+E",
        accel_formatMenu_Center_Mac: "\u21e7\u2318E",
        accel_formatMenu_Justify: "CTRL+ÜST KRTR+J",
        accel_formatMenu_Justify_Mac: "\u21e7\u2318J",
        accel_formatMenu_Indent: "CTRL+M",
        accel_formatMenu_Indent_Mac: "\u2318M",
        accel_formatMenu_DecreaseIndent: "CTRL+ÜST KRTR+M",
        accel_formatMenu_DecreaseIndent_Mac: "\u21e7\u2318M",
        accel_teamMenu_AddComment: "ÜST KRKTR+F2",

        ctxMenuSmartTable: 'Tablo',
        ctxMenuTableProperties: "Tablo Özellikleri",
        ctxMenuDeleteST: 'Sil',
        ctxMenuDeleteSTTable: 'Tabloyu Sil',
        ctxMenuChgSTStyle: 'Stili Değiştir',
        ctxMenuShowCaption: 'Başlığı Göster',
        ctxMenuHideCaption: 'Başlığı Gizle',
        ctxMenuResizeST: 'Yeniden Boyutlandır',
        ctxMenuResizeColumnsST: 'Sütunları Yeniden Boyutlandır',
        ctxMenuSTRow: 'Satır',
        ctxMenuAddSTRowAbv: 'Satırı Yukarı Ekle',
        ctxMenuAddSTRowBlw: 'Satırı Aşağı Ekle',
        ctxMenuMoveSTRowUp: 'Satırı Yukarı Taşı',
        ctxMenuMoveSTRowDown: 'Satırı Aşağı Taşı',
        ctxMenuDelSTRow: 'Sil',
        ctxMenuRepeatRow: 'Üstbilgi Satırını Yinele',
        ctxMenuSTCol: 'Sütun',
        ctxMenuAddSTColBfr: 'Sütunu Önüne Ekle',
        ctxMenuAddSTColAft: 'Sütunu Arkasına Ekle',
        ctxMenuMoveSTColBefore: 'Sütunu Önüne Taşı',
        ctxMenuMoveSTColAfter: 'Sütunu Arkasına Taşı',
        ctxMenuDelSTCol: 'Sil',
        ctxMenuSortSTColAsc: 'Artan Düzende Sırala',
        ctxMenuSortSTColDesc: 'Azalan Düzende Sırala',
        ctxMenuShowAllFacets: 'Kategorileri Göster',
        ctxMenuHideAllFacets: 'Kategorileri Gizle',
        ctxMenuSTCell: 'Hücre',
        ctxMenuMergeCells: 'Hücreleri Birleştir',
        ctxMenuMergeDown: 'Aşağıdaki Hücreyle Birleştir',
        ctxMenuVerSplit: 'Dikey Olarak Böl',
        ctxMenuHorSplit: 'Yatay Olarak Böl',
        ctxMenuSplitCells: 'Hücreleri Böl...',
        splitCells: 'Hücreyi Böl',
        ctxMenuAlignTextLeft: 'Sola Hizala',
        ctxMenuAlignTextCenter: 'Ortala',
        ctxMenuAlignTextRight: 'Sağa Hizala',
        ctxMenuClearSTCellContent: 'İçeriği Temizle',
        ctxMenuMakeHeaderRow: 'Seçilen Satırı Üstbilgi Olarak Kullan',
        ctxMenuMakeNonHeaderRow: 'Başlık Stilini Kaldır',
        ctxMenuMakeHeaderCol: 'Seçilen Sütunu Üstbilgi Olarak Kullan',
        ctxMenuMakeNonHeaderCol: 'Başlık Stilini Kaldır',
        SHEET_CONTEXT_Hide: "Gizle", // hide row, column or sheet
        SHEET_CONTEXT_Show: "Göster", // show row, column
        SHEET_CONTEXT_MoveSheet: "Taşı...", // move sheet
        SHEET_CONTEXT_InsertSheet: "Ekle...", // insert sheet
        SHEET_CONTEXT_DeleteSheet: "Sil...", // delete sheet	
        SHEET_CONTEXT_DuplicateSheet: "Yinele...", // duplicate sheet
        SHEET_CONTEXT_RenameSheet: "Yeniden Adlandır...", // rename sheet
	
        ctxMenu_Image_WrapText: "Metni Kaydır",
        ctxMenu_Image_WrapText_Inline: "Metinle Hizala",
        ctxMenu_Image_WrapText_Square: "Kare",
        ctxMenu_Image_WrapText_TopBottom: "Üst ve Alt",
        ctxMenu_Image_WrapText_Behind: "Metnin Arkasına",
        ctxMenu_Image_WrapText_InFront: "Metnin Önüne",
        ctxMenu_Image_WrapText_Other: "Diğer Metin Kaydırma",
        ctxMenu_Image_WrapText_BothSides: "Her İki Tarafa",
        ctxMenu_Image_WrapText_LeftOnly: "Yalnızca Sola",
        ctxMenu_Image_WrapText_RightOnly: "Yalnızca Sağa",
        ctxMenu_Image_WrapText_LargestOnly: "Yalnızca En Büyük",

        ctxMenu_Shape_AddText: "Metin Ekle",

        ctxMenu_Range_ACL: "Aralığı Koru",
        ctxMenu_Sheet_ACL: "Sayfayı Koru",

        ctxMenu_HeaderFooter: "Altbilgi / Üstbilgi",
        ctxMenu_HeaderFooter_DiffFirst: "Yalnızca İlk Sayfa",
        ctxMenu_HeaderFooter_DiffOddEven: "Farklı Tek ve Çift Sayfalar",
        ctxMenu_HeaderFooter_LinkToPre: "Öncekine Bağla",

        ctxMenu_copy: "Kopyala",
        ctxMenu_paste: "Yapıştır",
        ctxMenu_delete: "Sil",
        ctxMenu_cut: "Kes",
        ctxMenu_select: "Seç",
        ctxMenu_properties: "Özellikler",
        ctxMenu_bringToFront: "Öne Getir",
        ctxMenu_sendToBack: "Arkaya Gönder",
        ctxMenu_arrange: "Düzenle",
        ctxMenu_sendBackward: "Geriye Gönder",
        ctxMenu_sendForward: "İleriye Gönder",
        ctxMenu_fontStyle: "Yazı Tipi Stili",
        ctxMenu_selectStyle: "Stil Seç",
        ctxMenu_fontSize: "Yazı Tipi Boyutu",
        ctxMenu_fontFamily: "Yazı Tipi Ailesi",
        ctxMenu_bold: "Kalın",
        ctxMenu_italic: "İtalik",
        ctxMenu_u: "Altı Çizili",
        ctxMenu_strike: "Üstü Çizili",
        ctxMenu_super: "Üst Simge",
        ctxMenu_sub: "Alt Simge",
        ctxMenu_color: "Renk",
        ctxMenu_bgcolor: "Arka Plan Rengi",
        ctxMenu_highcolor: "Vurgu Rengi",
        ctxMenu_restart: "Listeyi Yeniden Başlat",
        ctxMenu_continue: "Listeye Devam Et",
        ctxMenu_separate: "Ayrı Liste",
        ctxMenu_join: "Önceki Listeyle Birleştir",
        ctxMenu_setNumberVal: "Numaralandırma Değerini Ayarla...",
        webClipboardInfoTitle: "Pano",
        webClipboardInfoOKBtn: "Tamam",
        webClipboardInfoCutMsg: "Tarayıcı güvenlik ayarlarınız otomatik kopyalamaya izin vermiyor. Bunun yerine klavyenizde Ctrl+X tuşlarını kullanın.",
        webClipboardInfoCopyMsg: "Tarayıcı güvenlik ayarlarınız otomatik kopyalamaya izin vermiyor. Bunun yerine klavyenizde Ctrl+C tuşlarını kullanın.",
        webClipboardInfoPasteMsg: "Tarayıcı güvenlik ayarlarınız, bu düzenleyicinin verilerinize erişmesini engelliyor. Bunun yerine klavyenizde Ctrl+V tuşlarını kullanın.",

        clearTrackChangeConfirmMsg: "Bu belgede değişiklikleri işaretleyen tüm renk kodlaması kalıcı olarak kaldırılacak. Devam etmek istiyor musunuz?"
});

