/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */


define({
        saveTip: "Kaydet",
        undoTip: "Geri Al",
        redoTip: "Yinele",
        formatPainterTip: "Biçimlendirmeyi Kopyala",
        showSorterTip: "Slayt Düzenleyiciyi Göster",
        hideSorterTip: "Slayt Düzenleyiciyi Gizle",
        webClipboardTip: "Web Panosu",
        spellCheckTip: "El İle Yazım Denetimini Yürüt",
        createSectionTip: "Bölüm Ata",
        createCellsTip: "Hücreleri Ata",
        createSlideTip: "Slaytları Ata",
        submitTip: "Atamayı Gönder",
        addCommentTip: "Yorum Ekle",
        removeFormatTip: "Biçimlendirmeyi Kaldır",
        sortAscTip: "Artan Düzende Sırala",
        sortDescTip: "Azalan Düzende Sırala",
        instantFilterTip: "Anında Süzgeç",
        insertChartTip: "Grafik Ekle",
        startAutofillTip: "Otomatik Doldurma",
        dataValidationTip: "Veri Doğrulaması",

        selectFontTip: "Yazı Tipi Seç",
        selectFontSizeTip: "Yazı Tipi Boyutu Seç",
        selectFontNameTip: "Yazı Tipi Adını Seç",
        FontName: "Yazı Tipi Adı",
        FontSize: "Yazı Tipi Boyutu",
        increaseFontSizeTip: "Yazı Tipi Boyutunu Artır",
        decreaseFontSizeTip: "Yazı Tipi Boyutunu Azalt",
        boldTip: "Kalın",
        italicTip: "İtalik",
        underlineTip: "Altı Çizili",
        strikeThroughTip: "Üstü Çizili",
        setFontColorTip: "Yazı Tipi Rengini Ayarla",
        setShadingColorTip: "Gölge Rengini Ayarla",
        setBackgroundFill: "Arka Plan Dolgusunu Ayarla",
        setBgColorTip: "Arka Plan Rengini Ayarla",
        setBorderTip: "Kenarlık Stilini ve Rengini Ayarla",
        setBorderColorTip: "Kenarlık Rengini Ayarla",
        setHighlightColor: "Vurgu Rengini Ayarla",
        formatPainter: "Biçimlendirmeyi Kopyala",
        //	clearFormat:"Remove Formatting",
        zoom: "Yakınlaştır/Uzaklaştır",
        selectStyleTip: "Stil Seç",
        styles: "Stil",
        formatAsCurrencyTip: "Para Birimi Olarak Biçimlendir",
        formatAsPercentTip: "Yüzde Olarak Biçimlendir",
        decreaseDecimalTip: "Ondalık Konumlarını Azalt",
        increaseDecimalTip: "Ondalık Konumlarını Artır",
        formatNumberTip: "Sayıyı Biçimlendir",

        numberedListTip: "Numaralandırma Ekle ya da Numaralandırma Stilini Değiştir",
        bulletedListTip: "Madde İşareti Ekle ya da Madde İşareti Stilini Değiştir",
        multilevelListTip: "Çok Düzeyli Madde İşareti Listesini Ekle ya da Değiştir",
        indentTip: "Girintiyi Artır",
        decreaseIndentTip: "Girintiyi Azalt",
        alignTip: "Hizala",
        leftAlignTip: "Sola Hizala",
        centerTip: "Ortala",
        rightAlignTip: "Sağa Hizala",
        justifyTip: "Yasla",
        bottomBorderTip: "Alt Kenarlık",
        borderTypes: "Kenarlık Tipleri",
        borderTip: "Kenarlık Stilini Ayarla",
        topAlignTip: "Üste Hizala",
        middleAlignTip: "Ortaya Hizala",
        bottomAlignTip: "Alta Hizala",
        lineSpacingTip: "Satır Aralığı",
        mergeSplitCellTip: "Hücreleri Birleştir ya da Böl",
        wrapNoWrapTip: "Kaydırma açık veya kapalı",
        ltrDirectionTip: "Soldan Sağa Metnine Değiştir",
        rtlDirectionTip: "Sağdan Sola Metnine Değiştir",
        autoDirectionTip: "Metin Yönünü Değiştir",
        toggleSheetDirectionTip: "Sayfa Yönünü Değiştir",
        setSheetDirectionLTR: "Soldan Sağa",
        setSheetDirectionRTL: "Sağdan Sola",

        addTableTip: "Tablo Ekle",
        insertOrMoveRowTip: "Satır Ekle ya da Taşı",
        insertOrMoveColTip: "Sütun Ekle ya da Taşı",
        insertOrDeleteRowTip: "Satır Ekle ya da Sil",
        insertOrDeleteColTip: "Sütun Ekle ya da Sil",
        insertFunctionTip: "İşlev Ekle",
        insertImage: "Resim Ekle",
        resizeCol: "Sütunu Yeniden Boyutlandır",
        resizeCols: "Sütunları Yeniden Boyutlandır",
        addLink: "Bağlantı Ekle ya da Düzenle",
        tableStyle: "Tablo Stilleri",

        selectBorder_BottomBorder: "Alt Kenarlık",
        selectBorder_TopBorder: "Üst Kenarlık",
        selectBorder_LeftBorder: "Sol Kenarlık",
        selectBorder_RightBorder: "Sağ Kenarlık",
        selectBorder_NoBorder: "Çizgi Yok",
        selectBorder_AllBorders: "Tüm Kenarlıklar",

        insertOrMoveRow_InsertAbove: "Satırı Yukarı Ekle",
        insertOrMoveRow_InsertBelow: "Satırı Aşağı Ekle",
        insertOrMoveRow_MoveUp: "Satırı Yukarı Taşı",
        insertOrMoveRow_MoveDown: "Satırı Aşağı Taşı",
        insertOrMoveCol_InsertLeft: "Sütunu Önüne Ekle",
        insertOrMoveCol_InsertRight: "Sütunu Arkasına Ekle",
        insertOrMoveCol_InsertBefore: "Sütunu Önüne Ekle",
        insertOrMoveCol_InsertAfter: "Sütunu Arkasına Ekle",
        insertOrMoveCol_MoveLeft: "Sütunu Sola Taşı",
        insertOrMoveCol_MoveRight: "Sütunu Sağa Taşı",

        insertOrDelete_Delete: "Sil",

        combineButtonReadTip: "Menüyü etkinleştirmek için Aşağı Ok tuşuna basın daha sonra ok tuşlarıyla gezinin",

        lineSpacing_1: "1",
        lineSpacing_12: "1,2",
        lineSpacing_15: "1.5",
        lineSpacing_2: "2",
        lineSpacing_25: "2,5",
        lineSpacing_3: "3",

        percent: "%",
        font_arial: "Arial",

        fontSize: "${0}pt",

        slides: "Sayfa Başına Bir Slayt",
        slidesWithNotes: "Notlu Slaytlar",
        preparingSlides: "Slaytlarınız yazdırma için hazırlanıyor...",
        printLayoutOptionLabel: "Düzen seçeneklerini yazdır",

        targetRemovedWhenDialogOpen: "Hedef başka bir birlikte düzenleyen tarafından kaldırıldığından bu işlem tamamlanamıyor.",

        NUMBER: "Sayı",
        CURRENCY: "Para Birimi",
        PERCENT: "Yüzde",
        DATE: "Tarih",
        TIME: "Saat",
        DATETIME: "TarihSaat",
        MORECURRENCY: "Para birimine göre diğer para birimleri",
        MORECURRENCYCODE: "Para birimi koduna göre diğer para birimleri",
        MOREDATE: "Diğer saat ve tarih biçimleri",
        TEXT: "Metin",
	
        // currency, by currency code
        // NOTE: MUST keep it in order
        CURRENCY_CODE: {
            AED: "Birleşik Arap Emirlikleri (Dirhem)",
            ARS: "Arjantin (Peso)",
            AUD: "Avustralya (Dolar)",
            BGN: "Bulgaristan (Leva)",
            BOB: "Bolivya (Boliviano)",
            BRL: "Brezilya (Real)",
            CAD: "Kanada (Dolar)",
            CHF: "İsviçre (Frank)",
            CLP: "Şili (Peso)",
            CNY: "Çin (Yuan Renminbisi)",
            COP: "Kolombiya (Peso)",
            CRC: "Kosta Rika (Colon)",
            CZK: "Çek Cumhuriyeti (Koruna)",
            DKK: "Danimarka (Kron)",
            DOP: "Dominik Cumhuriyeti (Peso)",
            EGP: "Mısır (Pound)",
            EUR: "Avusturya, Belçika, Finlandiya, Fransa,  ..., Slovenya, İspanya (Euro)",
            GBP: "İngiltere, Birleşik Krallık (Pound)",
            HKD: "Hong Kong (Dolar)",
            HRK: "Hırvatistan (Kuna)",
            HUF: "Macaristan (Forint)",
            IDR: "Endonezya (Rupi)",
            ILS: "İsrail (Yeni Şekel)",
            INR: "Hindistan (Rupi)",
            JPY: "Japonya (Yen)",
            KRW: "Kore, Güney (Von)",
            KZT: "Kazakistan (Tenges)",
            MAD: "Fas (dirhem)",
            MXN: "Meksika (Peso)",
            MYR: "Malezya (Ringgiti)",
            NOK: "Norveç (Kron)",
            NZD: "Yeni Zelanda (Dolar)",
            PAB: "Panama (Balboa)",
            PEN: "Peru (Nuevos Soles)",
            PHP: "Filipinler (Peso)",
            PKR: "Pakistan (Rupi)",
            PLN: "Polonya (Zloti)",
            PYG: "Paraguay (Guarani)",
            RON: "Romanya (Yeni Ley)",
            RSD: "Sırbistan (Kiril), Sırbistan (Latin)",
            RUB: "Rusya (Ruble)",
            SAR: "Suudi Arabistan (Riyal)",
            SEK: "İsveç (Krona)",
            SGD: "Singapur (Dolar)",
            SVC: "El Salvador (Colon)",
            THB: "Tayland (Baht)",
            TRY: "Türkiye (Lira)",
            TWD: "Tayvan (Yeni Dolar)",
            USD: "Ekvator, Porto Riko, Amerika Birleşik Devletleri (ABD Doları)",
            UYU: "Uruguay (Peso)",
            VEF: "Venezuela (Bolivar Fuerte)",
            VND: "Vietnam (Dong)",
            ZAR: "Güney Afrika (Rand)"
        },
        // for border toolbar
        allBorders: "Tüm Kenarlıklar",
        innerBorders: "İç Kenarlıklar",
        horizontalBorders: "Yatay Kenarlıklar",
        verticalBorders: "Dikey Kenarlıklar",
        outerBorders: "Dış Kenarlıklar",
        borderColor: "Kenarlık Rengi",
        leftBorder: "Sol Kenarlık",
        topBorder: "Üst Kenarlık",
        rightBorder: "Sağ Kenarlık",
        bottomBorder: "Alt Kenarlık",
        clearBorders: "Kenarlık Yok",
        BorderStyle_ThinSolid: "İnce İçi Dolu",
        BorderStyle_ThinDotted: "İnce Noktalı",
        BorderStyle_ThinDashed: "İnce Çizgili",
        BorderStyle_ThickSolid: "Kalın İçi Dolu",
        BorderStyle_ThickDotted: "Kalın Noktalı",
        BorderStyle_ThickDashed: "Kalın Çizgili"
})

