/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
    Arrow01_Gray: "Flecha 01 gris",
    Arrow02_Gray: "Flecha 02 gris",
    Arrow03_Red: "Flecha 03 roja",
    Arrow04_Blue: "Flecha 04 azul",
    Arrow05_Blue: "Flecha 05 azul",
    Arrow06_Yellow: "Flecha 06 amarilla",
    Arrow07_Red: "Flecha 07 roja",
    Arrow08_Gray: "Flecha 08 gris",
    Arrow09_Orange: "Flecha 09 naranja",
    Arrow10_Blue: "Flecha 10 azul",
    Arrow11_Blue: "Flecha 11 azul",
    Arrow12_Green: "Flecha 12 verde",
    Arrow13_Blue: "Flecha 13 azul",
    Arrow14_Green: "Flecha 14 verde",
    Arrow15_Orange: "Flecha 15 naranja",
    Arrow16_Gray: "Flecha 16 gris",
    CircleArrow01_Green: "Flecha de círculo 01 verde",
    CircleArrow02_Multi: "Flecha de círculo 02 multi",
    CircleArrow03_Multi: "Flecha de círculo 03 multi",
    CircleArrow04_Multi: "Flecha de círculo 04 multi",
    CircleArrow05_Multi: "Flecha de círculo 05 multi",
    CircleArrow06_Multi: "Flecha de círculo 06 multi",
    CircleArrow07_Blue: "Flecha de círculo 07 azul",
    CircleArrow08_Green: "Flecha de círculo 08 verde",
    CircleArrow09_Multi: "Flecha de círculo 09 multi",
    CurvedArrow01_Gray: "Flecha curva 01 gris",
    CurvedArrow02_Blue: "Flecha curva 02 azul",
    CurvedArrow03_Blue: "Flecha curva 03 azul",
    CurvedArrow04_Orange: "Flecha curva 04 naranja",
    CurvedArrow05_Red: "Flecha curva 05 roja",
    CurvedArrow06_Blue: "Flecha curva 06 azul",
    CurvedArrow07_Purple: "Flecha curva 07 púrpura",
    CurvedArrow08_Green: "Flecha curva 08 verde",
    CurvedArrow09_Gray: "Flecha curva 09 gris",
    CurvedArrow10_Blue: "Flecha curva 10 azul",
    CurvedArrow11_Orange: "Flecha curva 11 naranja",
    CurvedArrow12_Blue: "Flecha curva 12 azul",
    CurvedArrow13_Green: "Flecha curva 13 verde",
    CurvedArrow14_Brown: "Flecha curva 14 marrón",
    CurvedArrow15_Blue: "Flecha curva 15 azul",
    CurvedArrow16_Gray: "Flecha curva 16 gris",
    CurvedArrow17_Gray: "Flecha curva 17 gris",
    CurvedArrow18_Gray: "Flecha curva 18 gris",
    CurvedArrow19_Gray: "Flecha curva 19 gris",
    CurvedArrow20_Gray: "Flecha curva 20 gris",
    TrendArrow01_Red: "Flecha de tendencia 01 roja",
    TrendArrow02_Green: "Flecha de tendencia 02 verde",
    TrendArrow03_Orange: "Flecha de tendencia 03 naranja",
    TrendArrow04_Red: "Flecha de tendencia 04 roja",
    TrendArrow05_Orange: "Flecha de tendencia 05 naranja",
    TrendArrow06_Blue: "Flecha de tendencia 06 azul",
    TrendArrow07_Orange: "Flecha de tendencia 07 naranja",
    TrendArrow08_Yellow: "Flecha de tendencia 08 amarilla",
    TrendArrow09_Blue: "Flecha de tendencia 09 azul",
    TrendArrow10_Blue: "Flecha de tendencia 10 azul",
    TrendArrow11_Blue: "Flecha de tendencia 11 azul",
    TrendArrow12_Blue: "Flecha de tendencia 12 azul",
    TrendArrow13_Red: "Flecha de tendencia 13 roja",
    TrendArrow14_Multi: "Flecha de tendencia 14 multi",
    TrendArrow15_Blue: "Flecha de tendencia 15 azul",
    Bullet01_Circle_DarkRed: "Viñeta 01 de círculo rojo oscuro",
    Bullet02_Circle_Blue: "Viñeta 02 de círculo azul",
    Bullet03_Circle_Green: "Viñeta 03 de círculo verde",
    Bullet04_Square_Black: "Viñeta 04 de cuadrado negro",
    Bullet05_Square_Orange: "Viñeta 05 de cuadrado naranja",
    Bullet06_Square_Purple: "Viñeta 06 de cuadrado púrpura",
    Bullet07_Diamond_Blue: "Viñeta 07 de rombo azul",
    Bullet08_Diamond_LightBlue: "Viñeta 08 de rombo azul claro",
    Bullet09_Diamond_Red: "Viñeta 09 de rombo rojo",
    Bullet10_Star_Yellow: "Viñeta 10 de estrella amarilla",
    Bullet11_Star_Blue: "Viñeta 11 de estrella azul",
    Bullet12_Triangle_Blue: "Viñeta 12 de triángulo azul",
    Bullet13_Triangle_DarkGreen: "Viñeta 13 de triángulo verde oscuro",
    Bullet14_Arrow_Red: "Viñeta 14 de flecha roja",
    Bullet15_Arrow_Blue: "Viñeta 15 de flecha azul",
    Bullet16_Box_Blue: "Viñeta 16 de recuadro azul",
    Bullet17_Box_Red: "Viñeta 17 de recuadro rojo",
    Bullet18_Asterisk_LightBlue: "Viñeta 18 de asterisco azul claro",
    Bullet19_Leaves_Red: "Viñeta 19 de hojas rojas",
    Bullet20_Target_Blue: "Viñeta 20 de destino azul",
    Bullet21_Arrow_Blue: "Viñeta 21 de flecha azul",
    Bullet22_Arrow_DarkBlue: "Viñeta 22 de flecha azul oscuro",
    Bullet23_Arrow_Brown: "Viñeta 23 de flecha marrón",
    Bullet24_Flag_Red: "Viñeta 24 de distintivo rojo",
    Bullet25_Flag_Green: "Viñeta 25 de distintivo verde",
    Bullet26_X_Red: "Viñeta 26 de X roja",
    Bullet27_X_Black: "Viñeta 27 de X negra",
    Bullet28_Checkmark_Green: "Viñeta 28 de marca de selección verde",
    Bullet29_Checkmark_Blue: "Viñeta 29 de marca de selección azul",
    Bullet30_Square_DarkRed: "Viñeta 30 de cuadrado rojo oscuro",
    camera: "Cámara",
    computer1: "Sistema 1",
    computer2: "Sistema 2",
    computer3: "Sistema 3",
    Computer_Cloud: "Nube de sistema",
    Computer_Desktop: "Escritorio de sistema",
    Computer_Laptop_Black: "Portátil negro",
    Computer_Laptop_Silver: "Portátil plateado",
    Database: "Base de datos",
    evelope: "Sobre",
    newspapers: "Periódicos",
    openevelope: "Abrir sobre",
    Server: "Servidor",
    speaker: "Altavoz",
    WirelessAccessPoint: "Punto de acceso wireless",
    Cycle01_Transparent: "Ciclo 01 transparente",
    Cycle02_Transparent_Blue: "Ciclo 02 transparente azul",
    Cycle03_Blue: "Ciclo 03 azul",
    Cycle04_Blue: "Ciclo 04 azul",
    Cycle05: "Ciclo 05",
    Cycle06: "Ciclo 06",
    Cycle07: "Ciclo 07",
    Cycle08_Blue: "Ciclo 08 azul",
    Cycle09_Orange: "Ciclo 09 naranja",
    Donut01_LightBlue: "Donut 01 azul claro",
    Donut02_Blue: "Donut 02 azul",
    Donut03_Blue: "Donut 03 azul",
    Donut04_DarkBlue: "Donut 04 azul oscuro",
    Donut05_DarkBlue: "Donut 05 azul oscuro",
    Donut06_Blue: "Donut 06 azul",
    Donut07_Blue: "Donut 07 azul",
    Graph: "Gráfico",
    People01_Blue: "Personas 01 azules",
    People02: "Personas 02",
    Pillars01_Orange: "Pilares 01 naranjas",
    Pillars02_LightBlue: "Pilares 02 azules claros",
    Process01_Blue: "Proceso 01 azul",
    Process02_Blue: "Proceso 02 azul",
    Process03_Blue: "Proceso 03 azul",
    Process04_GoUp_Blue: "Proceso 04 Subir azul",
    Process05_GoUp_Red: "Proceso 05 Subir rojo",
    Process06_GoUp_Yellow: "Proceso 06 Subir amarillo",
    Process07_Blue: "Proceso 07 azul",
    Pyramid01: "Pirámide 01",
    Pyramid02_Blue: "Pirámide 02 azul",
    Pyramid03: "Pirámide 03",
    Radial01_Green: "Radial 01 verde",
    Radial02_Green: "Radial 02 verde",
    Radial03_Sphere: "Radial 03 de esfera",
    Radial04_Sphere_Red: "Radial 04 de esfera rojo",
    Radial05_Sphere_Blue: "Radial 05 de esfera azul",
    Radial06_Arrows_DarkBlue: "Radial 06 de flechas azul oscuro",
    Radial07_Arrows_DarkBlue: "Radial 07 de flechas azul oscuro",
    Section_Circle: "Círculo de sección",
    Section_Cubes01: "Cubos de sección 01",
    Section_Cubes02_Blue: "Cubos de sección 02 azules",
    Section_Cubes03_Orange: "Cubos de sección 03 naranjas",
    Section_Cubes04: "Cubos de sección 04",
    Section_Cubes05: "Cubos de sección 05",
    Section_Cuboids01_Blue: "Cuboides de sección 01 azules",
    Section_Cuboids02_Blue: "Cuboides de sección 02 azules",
    Section_Cuboids03: "Cuboides de sección 03",
    Section_Gears01: "Herramientas de la sección 01",
    Section_Gears02: "Herramientas de la sección 02",
    Section_Gears03: "Herramientas de la sección 03",
    Section_Hexagon04_Orange: "Hexágono de la sección 04 naranja",
    Section_Hexagons01: "Hexágonos de la sección 01",
    Section_Hexagons02_Blue: "Hexágonos de la sección 02 azules",
    Section_Hexagons03_Blue: "Hexágonos de la sección 03 azules",
    Section_Leaves01_LightBlue: "Hojas de la sección 01 azul claro",
    Section_Leaves02_Green: "Hojas de la sección 02 verdes",
    Section_Pasters01: "Sección de pegado 01",
    Section_Pasters02_Blue: "Sección de pegado 02 azul",
    Section_Puzzle01: "Sección de puzzle 01",
    Section_Puzzle02: "Sección de puzzle 02",
    Section_Puzzle03: "Sección de puzzle 03",
    Section_Rectangles: "Sección de rectángulos",
    Section_Squares: "Sección de cuadrados",
    Section_Triangle: "Sección de triángulo",
    Target: "Destino",
    Venn01: "Venn 01",
    Venn02: "Venn 02",
    Venn03: "Venn 03",
    Venn04: "Venn 04",
    Venn05: "Venn 05",
    Venn06_Blue: "Venn 06 azul",
    Venn07_Blue: "Venn 07 azul",
    Venn08: "Venn 08",
    Blackboard: "Pizarra",
    Books: "Manuales",
    Books1: "Libros 1",
    books2: "Libros 2",
    Chalk: "Tiza",
    clipboard: "portapapeles",
    clock: "reloj",
    Globe: "Mundo",
    Glue: "Cola",
    GraduationCap: "Gorra de graduación",
    magnifyingglass: "lupa",
    Microscope: "Microscopio",
    Notebook: "Cuaderno",
    notepad1: "Bloc de notas 1",
    notepad2: "Bloc de notas 2",
    notepad3: "Bloc de notas 3",
    PaperClip_Blue: "Clip azul",
    PaperClip_Red: "Clip rojo",
    Pencil: "Lápiz",
    Ruler: "Regla",
    TestTubes: "Tubos de ensayo",
    thumbtack: "Chincheta",
    clouds: "Nubes",
    DrippingFaucet: "Grifo goteando",
    Earth: "Tierra",
    EndangeredAnimals1: "Animales en peligro de extinción 1",
    EndangeredAnimals2: "Animales en peligro de extinción 2",
    GreenCar: "Coche verde",
    GreenFactory: "Fábrica verde",
    GreenHouse: "Invernadero",
    Leaf1: "Hoja 1",
    Leaf2: "Hoja 2",
    lightbulb: "Bombilla",
    LightBulb_Flourescent_Off: "Fluorescente de la bombilla apagado",
    LightBulb_Flourescent_On: "Fluorescente de la bombilla encendido",
    LightBulb_Standard_Off1: "Bombilla estándar apagada 1",
    LightBulb_Standard_Off2: "Bombilla estándar apagada 2",
    LightBulb_Standard_On: "Bombilla estándar encendida",
    lightningcloud: "Nube de tormenta",
    Pollution_Car: "Coche contaminante",
    Pollution_Factory: "Fábrica contaminante",
    Raindrop: "Gota de lluvia",
    RecycleBin: "Papelera de reciclaje",
    RecycleSymbol: "Símbolo de reciclaje",
    RenewableEnergySymbol: "Símbolo de energía renovable",
    RenewableEnergy_Solar: "Energía solar renovable",
    RenewableEnergy_Water: "Energía hidráulica renovable",
    RenewableEnergy_Wind: "Energía eólica renovable",
    sun: "Sol",
    Sun1: "Sol 1",
    Sun2: "Sol 2",
    sundandcloud: "Sol y nube",
    world: "Mundo",
    Agreement: "Acuerdo",
    ATM01: "ATM 01",
    ATM02: "ATM 02",
    Balance_Balanced1: "Saldo equilibrado 1",
    Balance_Balanced2: "Saldo equilibrado 2",
    Balance_Unbalanced1: "Saldo no equilibrado 1",
    Balance_Unbalanced2: "Saldo no equilibrado 2",
    Calculator: "Calculadora",
    Chart_Decrease1: "Descenso de diagrama 1",
    Chart_Decrease2: "Descenso de diagrama 2",
    Chart_Increase1: "Aumento de diagrama 1",
    Chart_Increase2: "Aumento de diagrama 2",
    Chart_Plateau: "Punto plano del gráfico",
    Check: "Comprobación",
    Contract: "Contrato",
    CreditCard_Black: "Tarjeta de crédito negra",
    CreditCard_Cut: "Tarjeta de crédito cortada",
    CreditCard_Gold: "Tarjeta de crédito dorada",
    Currency_Dollar: "Dólar Moneda",
    Currency_Dollars: "Dólares moneda",
    Currency_Stack: "Pila Moneda",
    Currency_StackCoins: "Monedas de Pila moneda",
    GoldBar: "Barra de oro",
    GoldBar_Stack: "Pila de barra de oro",
    MoneyBag01: "Bolsa de dinero 01",
    MoneyBag02: "Bolsa de dinero 02",
    PercentSign: "Signo de porcentaje",
    PiggyBank01_Broken: "Hucha rota 01",
    PiggyBank02_Broken: "Hucha rota 02",
    PiggyBank_Coins: "Monedas de hucha",
    PiggyBank_Currency: "Moneda de hucha",
    Portfolio: "Menú de tareas",
    PriceTag: "Etiqueta de precio",
    Safe_Closed: "Caja fuerte cerrada",
    Safe_Empty: "Caja fuerte vacía",
    Safe_Full: "Caja fuerte llena",
    Seal_Gold: "Cierre dorado",
    Seal_Red: "Cierre rojo",
    Seal_Silver: "Cierre plateado",
    Wallet_Empty: "Cartera vacía",
    Wallet_Full1: "Cartera llena 1",
    Wallet_Full2: "Cartera llena 2",
    BusinessPerson_Female6: "Persona femenina de negocios 6",
    BusinessPerson_Male3: "Persona masculina de negocios 3",
    Computer_User_Female1: "Usuario femenino 1 del sistema",
    ConstructionWorker2: "Trabajador de la construcción 2",
    Presenter_Female1: "Presentador femenino 1",
    Component_Circle01_Transparent_DarkBlue: "Círculo de componente 01 transparente azul oscuro",
    Component_Circle02_Transparent_Bule: "Círculo de componente 02 transparente azul",
    Component_Circle03_Transparent_Green: "Círculo de componente 03 transparente verde",
    Component_Circle04_Transparent_Orange: "Círculo de componente 04 transparente naranja",
    Component_Circle05_Transparent_Red: "Círculo de componente 05 transparente rojo",
    Component_Cube01_DarkBlue: "Cubo de componente 01 azul oscuro",
    Component_Cube02_LightBlue: "Cubo de componente 02 azul claro",
    Component_Cube03_Green: "Cubo de componente 03 verde",
    Component_Cube04_Orange: "Cubo de componente 04 naranja",
    Component_Cube05_DarkRed: "Cubo de componente 05 rojo oscuro",
    Component_Cuboid01_DarkBlue: "Cuboide de componente 01 azul oscuro",
    Component_Cuboid02_Blue: "Azul de cuboide de componente 02",
    Component_Cuboid03_Green: "Verde de cuboide de componente 03",
    Component_Cuboid04_Orange: "Naranja de cuboide de componente 04",
    Component_Cuboid05_Red: "Rojo de cuboide de componente 05",
    Component_Gear01_DarkBlue: "Azul oscuro de herramienta de componente 01",
    Component_Gear02_LightBlue: "Azul claro de herramienta de componente 02",
    Component_Gear03_Green: "Verde de herramienta de componente 03",
    Component_Gear04_DarkRed: "Rojo oscuro de herramienta de componente 04",
    Component_Gear05_Orange: "Naranja de herramienta de componente 05",
    Component_Person01_DarkBlue: "Azul oscuro de persona de componente 01",
    Component_Person02_Blue: "Azul de persona de componente 02",
    Component_Person03_Green: "Verde de persona de componente 03",
    Component_Person04_DarkRed: "Rojo oscuro de persona de componente 04",
    Component_Person05_Orange: "Naranja de persona de componente 05",
    Component_PuzzlePiece01_DarkBlue: "Azul oscuro de pieza de puzzle de componente 01",
    Component_PuzzlePiece02_Blue: "Azul de pieza de puzzle de componente 02",
    Component_PuzzlePiece03_Green: "Verde de pieza de puzzle de componente 03",
    Component_PuzzlePiece04_Red: "Rojo de pieza de puzzle de componente 04",
    Component_PuzzlePiece05_Orange: "Naranja de pieza de puzzle de componente 05",
    Component_Sphere01_DarkBlue: "Azul oscuro de esfera de componente 01",
    Component_Sphere02_LightBlue: "Azul claro de esfera de componente 02",
    Component_Sphere03_Green: "Verde de esfera de componente 03",
    Component_Sphere04_DarkRed: "Rojo oscuro de esfera de componente 04",
    Component_Sphere05_Orange: "Naranja de esfera de componente 05",
    Book: "Libro",
    Box01: "Recuadro 01",
    Box02: "Recuadro 02",
    Bulb01_Yellow: "Amarillo de bombilla 01",
    Bulb02_Yellow: "Amarillo de bombilla 02",
    Calendar: "Agenda",
    Chart: "Gráfico",
    Clipboard: "Portapapeles",
    Clock: "Reloj",
    Compass: "Brújula",
    Flag01_Red: "Distintivo 01 rojo",
    Flag02_Green: "Distintivo 02 verde",
    Flag03_Blue: "Distintivo 03 azul",
    Gift: "Regalo",
    House: "Casa",
    Icon_Computer01_White: "Icono de sistema 01 blanco",
    Icon_Computer02_Black: "Icono de sistema 02 negro",
    Icon_Disk01_Blue: "Icono de disco 01 azul",
    Icon_Disk02_Green: "Icono de disco 02 verde",
    Icon_Document01_Grey: "Icono de documento 01 gris",
    Icon_Document02_Grey: "Icono de documento 02 gris",
    Icon_Document03_Blue: "Icono de documento 03 azul",
    Icon_Document04_Blue: "Icono de documento 04 azul",
    Icon_Envelope01_Blue: "Icono de sobre 01 azul",
    Icon_Envelope02_Yellow: "Icono de sobre 02 amarillo",
    Icon_Envelope03_Open_Yellow: "Icono de sobre 03 abrir amarillo",
    Icon_Envelope04_Open_Yellow: "Icono de sobre 04 abrir amarillo",
    Icon_Folder01_Yellow: "Icono de carpeta 01 amarillo",
    Icon_Folder02_Yellow: "Icono de carpeta 02 amarillo",
    Icon_Folder03_Open_Yellow: "Icono de carpeta 03 abrir amarillo",
    Icon_Folder04_Open_Yellow: "Icono de carpeta 04 abrir amarillo",
    Icon_Gear01_Grey: "Icono de herramientas 01 gris",
    Icon_Gear02_Blue: "Icono de herramientas 02 azul",
    Icon_Network01_Blue: "Icono de red 01 azul",
    Icon_Network02: "Icono de red 02",
    Icon_Pencil01: "Icono de lápiz 01",
    Icon_Pencil02: "Icono de lápiz 02",
    Icon_Printer01_White: "Icono de impresora 01 blanco",
    Icon_Printer02_Black: "Icono de impresora 02 negro",
    Key01: "Clave 01",
    Key02: "Clave 02",
    Lock01_Yellow: "Bloqueo 01 amarillo",
    Lock02_Yellow: "Bloqueo 02 amarillo",
    Lock03_Blue: "Bloqueo 03 azul",
    Lock04_Blue: "Bloqueo 04 azul",
    Magnet: "Imán",
    MagnifyingGlass: "Lupa",
    Medal: "Medalla",
    Notebook: "Cuaderno",
    Phone: "Teléfono",
    PieChart: "Gráfico circular",
    Pin: "Patilla",
    PuzzlePiece: "Pieza de puzzle",
    PuzzlePieces: "Piezas de puzzle",
    Roadblock: "Retén",
    Scissors: "Tijeras",
    Shield01: "Escudo 01",
    Shield02_Orange: "Escudo 02 naranja",
    Shield03_Blue: "Escudo 03 azul",
    Sign_Ban01: "Signo de prohibición 01",
    Sign_Ban02: "Signo de prohibición 02",
    Sign_CheckBox01: "Signo de casilla de verificación 01",
    Sign_CheckBox02_Unchecked: "Signo de casilla de verificación 02 desmarcado",
    Sign_Checkmark01_Green: "Signo de casilla de verificación 01 verde",
    Sign_Checkmark02_Green: "Signo de casilla de verificación 02 verde",
    Sign_DoNotEnter: "Signo No especificar",
    Sign_Error01: "Signo de error 01",
    Sign_Error02: "Signo de error 02",
    Sign_ExclamationPoint01_Red: "Signo de punto de exclamación 01 rojo",
    Sign_ExclamationPoint02_Orange: "Signo de punto de exclamación 02 naranja",
    Sign_Help01_Green: "Signo de ayuda 01 verde",
    Sign_Help02_Blue: "Signo de ayuda 02 azul",
    Sign_Information: "Signo de información",
    Sign_Null: "Signo nulo",
    Sign_QuestionMark01_Blue: "Signo de interrogación 01 azul",
    Sign_QuestionMark02_Red: "Signo de interrogación 02 rojo",
    Sign_RadioButton01: "Signo de botón de selección 01",
    Sign_RadioButton02_Unchecked: "Signo de botón de selección 02 desmarcado",
    Sign_Warning01_Red: "Signo de aviso 01 rojo",
    Sign_Warning02_Orange: "Signo de aviso 02 naranja",
    Sign_X01_Red: "Signo X 01 rojo",
    Sign_X02_Red: "Signo X 02 rojo",
    Star_Yellow: "Estrella amarilla",
    Wrench: "Llave para tuercas",
    Airplane_Blue: "Avión azul",
    Bicycle_Blue: "Bicicleta azul",
    Bus: "Bus",
    Canoe_Blue: "Canoa azul",
    Car_Red: "Automóvil rojo",
    Helicopter_Blue: "Helicóptero azul",
    Motorcycle_Red: "Motocicleta roja",
    Pedestrian_Blue: "Peatón azul",
    PersonalTransporter_Green: "Transportador personal verde",
    Sailboat_Red: "Barco rojo",
    Scooter_Orange: "Scooter naranja",
    Train_Red: "Tren rojo",
    Truck_Blue: "Camión azul",
    
    aria_category_selector: "Opciones de categoría de imagen",
    filterImageGallery: "Galería de imágenes de filtro"

})
