/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
	fileMenu: "Archivo",
	fileMenu_New: "Nuevo",
	fileMenu_NewDocument: "Documento",
	fileMenu_NewDocumentfromTemplate: "Documento a partir de plantilla",
	fileMenu_NewPresentation: "Presentación",
	fileMenu_NewPresentationfromTemplate: "Presentación a partir de plantilla",
	fileMenu_NewSpreadsheet: "Hoja de cálculo",
	fileMenu_Open: "Abrir",
//	fileMenu_Close: "Close",
	fileMenu_Discard: "Descartar",
	fileMenu_Save: "Guardar",
//	fileMenu_SaveAs: "Save As...",
//	fileMenu_SaveAsDraft: "as Draft",
//	fileMenu_SaveInMyDocs: "in My Documents",
//	fileMenu_SaveToSymphony: "to Lotus Symphany",
	fileMenu_ShareWith: "Compartir con...	",
	fileMenu_ExportAsPDF: "Exportar como PDF",
	fileMenu_WebPreview: "Previsualización web",
	fileMenu_PrintPreview: "Vista previa",
	fileMenu_RecentFile: "Archivos recientes",
	fileMenu_Print: "Imprimir...",
	editMenu: "Editar",
	editMenu_Undo: "Deshacer",
	editMenu_Redo: "Rehacer",
	editMenu_Cut: "Cortar",
	editMenu_Copy: "Copiar",
	editMenu_Paste: "Pegar",
	editMenu_DeleteSlide:"Suprimir diapositiva",
	editMenu_SelectAll: "Seleccionar todo",
	editMenu_Find: "Buscar...",
	editMenu_Replace: "Sustituir...",
	editMenu_DeleteSheet: "Suprimir hoja",
	editMenu_DuplicateSheet: "Duplicar hoja",
	editMenu_DeleteRow: "Suprimir fila",
	editMenu_DeleteColumn: "Suprimir columna",
	editMenu_ClearCell: "Borrar celda",
	viewMenu: "Ver",
	viewMenu_Master: "Fondo",
	viewMenu_Notifications: "Notificaciones",
	viewMenu_ShowHideIndicators: "Mostrar/ocultar indicadores de coedición",
	viewMenu_SlideSorter: "Mostrar clasificador de diapositivas",
	viewMenu_SpeakerNotes: "Mostrar notas del orador",
	viewMenu_NextSlide: "Siguiente diapositiva",
	viewMenu_PrevSlide: "Diapositiva anterior",
	createMenu: "Crear",
	createMenu_NewSlide: "Nueva diapositiva",
	createMenu_DuplicateSlide: "Duplicar diapositiva",
	createMenu_ImageFromFile: "Gráfico a partir de archivo",
	createMenu_TextBox: "Cuadro de texto",
	createMenu_Task: "Tarea",
    formatMenu_Text_Direction: "Dirección del texto",
    formatMenu_Ltr: "De izquierda a derecha",
    formatMenu_Rtl: "De derecha a izquierda",  	
    formatMenu_Horizontal_Align: "Alineación horizontal",
    formatMenu_Vertical_Align: "Alineación vertical",
    formatMenu_Align_Top: "Arriba",
    formatMenu_Align_Middle: "Medio",
    formatMenu_Align_Bottom: "Abajo",
	layoutMenu: "Diseño",
	layoutMenu_SlideLayout: "Diseño de diapositiva",
	layoutMenu_SlideDesign: "Estilos maestros",
	tableMenu: "Tabla",
	tableMenu_CreateTable: "Crear tabla",
	tableMenu_Cell: "Celda",
	tableMenu_CellAlignLeft: "Alinear texto a la izquierda",
	tableMenu_CellAlignCenter: "Alinear texto al centro",
	tableMenu_CellAlignRight: "Alinear texto a la derecha",
	tableMenu_CellClearContents: "Borrar contenidos",
	tableMenu_Row: "Fila",
	tableMenu_RowAddRowAbove: "Añadir fila arriba",
	tableMenu_RowAddRowBelow: "Añadir fila abajo",
	tableMenu_RowMoveRowAbove: "Mover fila arriba",
	tableMenu_RowMoveRowBelow: "Mover fila abajo",
	tableMenu_RowDelete: "Suprimir",
	tableMenu_ColumnAddColumnBefore: "Añadir columna antes",
	tableMenu_ColumnAddColumnAfter: "Añadir columna después",
	tableMenu_ColumnMoveColumnAfter: "Mover columna antes",
	tableMenu_ColumnMoveColumnBefore: "Mover columna después",
	tableMenu_ColumnDelete: "Suprimir",
	tableMenu_ColumnSortAscending: "Orden ascendente",
	tableMenu_ColumnSortDescending: "Orden descendente",
	tableMenu_Column: "Columna",
	tableMenu_Delete: "Suprimir",
	presentationMenu: "Presentación",
	presentationMenu_SlideShow: "Reproducir presentación de diapositivas",
	presentationMenu_SlideShowFromCurrent: "Reproducir desde la diapositiva actual",
	toolsMenu: "Herramientas",
	toolsMenu_Task: "Tarea",
	helpMenu: "Ayuda",
	helpMenu_Overview: "Contenido de Ayuda"
})

