/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */


define({
        saveTip: "Guardar",
        undoTip: "Deshacer",
        redoTip: "Rehacer",
        formatPainterTip: "Copiar formato",
        showSorterTip: "Mostrar clasificador de diapositivas",
        hideSorterTip: "Ocultar clasificador de diapositivas",
        webClipboardTip: "Portapapeles web",
        spellCheckTip: "Ejecutar el corrector ortográfico de forma manual",
        createSectionTip: "Asignar una sección",
        createCellsTip: "Asignar celdas",
        createSlideTip: "Asignar diapositivas",
        submitTip: "Enviar asignación",
        addCommentTip: "Añadir un comentario",
        removeFormatTip: "Eliminar formato",
        sortAscTip: "Orden ascendente",
        sortDescTip: "Orden descendente",
        instantFilterTip: "Filtro instantáneo",
        insertChartTip: "Insertar gráfico",
        startAutofillTip: "Rellenado automático",
        dataValidationTip: "Validación de datos",

        selectFontTip: "Seleccionar juego de caracteres internacional",
        selectFontSizeTip: "Seleccionar tamaño de font",
        selectFontNameTip: "Seleccionar nombre de font",
        FontName: "Nombre de font",
        FontSize: "Tamaño de font",
        increaseFontSizeTip: "Aumentar tamaño de fuente",
        decreaseFontSizeTip: "Reducir tamaño de fuente",
        boldTip: "Negrita",
        italicTip: "Cursiva",
        underlineTip: "Subrayado",
        strikeThroughTip: "Tachado",
        setFontColorTip: "Establecer color de fuente",
        setShadingColorTip: "Establecer color de sombreado",
        setBackgroundFill: "Establecer relleno de fondo",
        setBgColorTip: "Establecer color de fondo",
        setBorderTip: "Establecer estilo y color de borde",
        setBorderColorTip: "Establecer color de borde",
        setHighlightColor: "Establecer color de resalte",
        formatPainter: "Copiar formato",
        //	clearFormat:"Remove Formatting",
        zoom: "Zoom",
        selectStyleTip: "Seleccionar estilo",
        styles: "Estilo",
        formatAsCurrencyTip: "Dar formato como moneda",
        formatAsPercentTip: "Dar formato como porcentaje",
        decreaseDecimalTip: "Reducir posiciones decimales",
        increaseDecimalTip: "Aumentar posiciones decimales",
        formatNumberTip: "Número de formato",

        numberedListTip: "Agregar numeración o cambiar estilo de numeración",
        bulletedListTip: "Agregar viñetas o cambiar estilo de viñeta",
        multilevelListTip: "Agregar o cambiar lista multinivel",
        indentTip: "Aumentar sangría",
        decreaseIndentTip: "Reducir sangría",
        alignTip: "Alinear",
        leftAlignTip: "Alinear izquierda",
        centerTip: "Alinear centro",
        rightAlignTip: "Alinear derecha",
        justifyTip: "Justificar",
        bottomBorderTip: "Parte inferior del borde",
        borderTypes: "Tipos de borde",
        borderTip: "Establecer estilo de borde",
        topAlignTip: "Alineación superior",
        middleAlignTip: "Centrar",
        bottomAlignTip: "Alineación inferior",
        lineSpacingTip: "Interlineado",
        mergeSplitCellTip: "Combinar o dividir celdas",
        wrapNoWrapTip: "Ajuste on y off",
        ltrDirectionTip: "Cambiar la dirección del texto de izquierda a derecha",
        rtlDirectionTip: "Cambiar la dirección del texto de derecha a izquierda",
        autoDirectionTip: "Cambiar la dirección del texto",
        toggleSheetDirectionTip: "Cambiar la dirección de la hoja",
        setSheetDirectionLTR: "De izquierda a derecha",
        setSheetDirectionRTL: "De derecha a izquierda",

        addTableTip: "Añadir tabla",
        insertOrMoveRowTip: "Insertar o mover fila",
        insertOrMoveColTip: "Insertar o mover columna",
        insertOrDeleteRowTip: "Insertar o suprimir fila",
        insertOrDeleteColTip: "Insertar o suprimir columna",
        insertFunctionTip: "Función Insertar",
        insertImage: "Insertar imagen",
        resizeCol: "Redimensionar columna",
        resizeCols: "Redimensionar columnas",
        addLink: "Agregar o editar un enlace",
        tableStyle: "Estilos de tabla",

        selectBorder_BottomBorder: "Borde inferior",
        selectBorder_TopBorder: "Borde superior",
        selectBorder_LeftBorder: "Borde izquierdo",
        selectBorder_RightBorder: "Borde derecho",
        selectBorder_NoBorder: "Sin líneas",
        selectBorder_AllBorders: "Todo el borde",

        insertOrMoveRow_InsertAbove: "Insertar fila antes",
        insertOrMoveRow_InsertBelow: "Insertar fila después",
        insertOrMoveRow_MoveUp: "Subir fila",
        insertOrMoveRow_MoveDown: "Bajar fila",
        insertOrMoveCol_InsertLeft: "Insertar columna antes",
        insertOrMoveCol_InsertRight: "Insertar columna después",
        insertOrMoveCol_InsertBefore: "Insertar columna antes",
        insertOrMoveCol_InsertAfter: "Insertar columna después",
        insertOrMoveCol_MoveLeft: "Mover columna a la izquierda",
        insertOrMoveCol_MoveRight: "Mover columna a la derecha",

        insertOrDelete_Delete: "Suprimir",

        combineButtonReadTip: "Pulse la tecla Flecha abajo para activar el menú y, a continuación, desplácese con las teclas de flecha",

        lineSpacing_1: "1",
        lineSpacing_12: "1,2",
        lineSpacing_15: "1.5",
        lineSpacing_2: "2",
        lineSpacing_25: "2,5",
        lineSpacing_3: "3",

        percent: "%",
        font_arial: "Arial",

        fontSize: "${0}pt",

        slides: "Una diapositiva por página",
        slidesWithNotes: "Diapositivas con Notes",
        preparingSlides: "Preparando las diapositivas para imprimirlas...",
        printLayoutOptionLabel: "Opciones de diseño de impresión",

        targetRemovedWhenDialogOpen: "Esta acción no puede realizarse porque el destino lo ha eliminado otro coeditor.",

        NUMBER: "Número",
        CURRENCY: "Moneda",
        PERCENT: "Porcentaje",
        DATE: "Fecha",
        TIME: "Hora",
        DATETIME: "DateTime",
        MORECURRENCY: "Más monedas por unidad monetaria",
        MORECURRENCYCODE: "Más monedas por código de moneda",
        MOREDATE: "Más formatos de hora y de fecha",
        TEXT: "Texto",
	
        // currency, by currency code
        // NOTE: MUST keep it in order
        CURRENCY_CODE: {
            AED: "Emiratos Árabes Unidos (Dirham)",
            ARS: "Argentina (Pesos)",
            AUD: "Australia (Dólares)",
            BGN: "Bulgaria (Leva)",
            BOB: "Bolivia (Bolivianos)",
            BRL: "Brasil (Reales)",
            CAD: "Canadá (Dólares)",
            CHF: "Suiza (Francos)",
            CLP: "Chile (Pesos)",
            CNY: "China (Yuan Renminbi)",
            COP: "Colombia (Pesos)",
            CRC: "Costa Rica (Colón)",
            CZK: "República Checa (Koruny)",
            DKK: "Dinamarca (Kroner)",
            DOP: "República Dominicana (Pesos)",
            EGP: "Egipto (Libras)",
            EUR: "Austria, Bélgica, Finlandia, Francia,  ..., Eslovenia, España (Euro)",
            GBP: "Inglaterra, Reino Unido (Libras)",
            HKD: "Hong Kong (Dólares)",
            HRK: "Croacia (Kuna)",
            HUF: "Hungría (Florín)",
            IDR: "Indonesia (Rupiahs)",
            ILS: "Israel (Nueva Shekels)",
            INR: "India (Rupias)",
            JPY: "Japón (Yen)",
            KRW: "Corea, Sur (Won)",
            KZT: "Kazakhstán (Tenges)",
            MAD: "Marruecos (dirham)",
            MXN: "México (Pesos)",
            MYR: "Malasia (Ringgits)",
            NOK: "Noruega (Krone)",
            NZD: "Nueva Zelanda (Dólares)",
            PAB: "Panamá (Balboa)",
            PEN: "Perú (Nuevos Soles)",
            PHP: "Filipinas (Pesos)",
            PKR: "Pakistán (Rupias)",
            PLN: "Polonia (Zlotych)",
            PYG: "Paraguay (Guaraní)",
            RON: "Rumanía (Nueva Lei)",
            RSD: "Serbio (Cirílico), Serbio (Latino)",
            RUB: "Rusia (Rublos)",
            SAR: "Arabia Saudí (Riyals)",
            SEK: "Suecia (Kronor)",
            SGD: "Singapur (Dólares)",
            SVC: "El Salvador (Colones)",
            THB: "Tailandia (Baht)",
            TRY: "Turquía (Lira)",
            TWD: "Taiwán (Nuevos Dólares)",
            USD: "Ecuador, Puerto Rico, Estados Unidos de América (Dólares de EE.UU.)",
            UYU: "Uruguay (Pesos)",
            VEF: "Venezuela (Bolívares Fuertes)",
            VND: "Vietnam (Dong)",
            ZAR: "Sudáfrica (Rand)"
        },
        // for border toolbar
        allBorders: "Todos los bordes",
        innerBorders: "Bordes internos",
        horizontalBorders: "Bordes horizontales",
        verticalBorders: "Bordes verticales",
        outerBorders: "Bordes externos",
        borderColor: "Color del borde",
        leftBorder: "Borde izquierdo",
        topBorder: "Borde superior",
        rightBorder: "Borde derecho",
        bottomBorder: "Borde inferior",
        clearBorders: "Sin bordes",
        BorderStyle_ThinSolid: "Sólido fino",
        BorderStyle_ThinDotted: "De puntos fino",
        BorderStyle_ThinDashed: "De guiones fino",
        BorderStyle_ThickSolid: "Sólido grueso",
        BorderStyle_ThickDotted: "De puntos grueso",
        BorderStyle_ThickDashed: "De guiones grueso"
})

