({	
	viewExpandedBtn: "더 적은 답글 보기",
	viewCollapsedBtn: "${0}개의 추가 답글 보기",
	placeholderMsg: "여기에 메시지를 입력하십시오.",
	sure: "이 댓글을 삭제하시겠습니까?",
	exceed: "댓글이 너무 깁니다.\n 입력한 댓글이 허용되는 최대 길이를 초과합니다.\n ${0}자 이하로 줄이고 추가를 클릭하십시오.",
	remainLabelHint:"댓글이 한계인 500문자에 도달했습니다.",
	tipsCommentField: "모든 편집자 또는 한 편집자에게 댓글 입력",
	tipsRespondField: "모든 편집자 또는 한 편집자에게 응답 입력",	
	resolveBtn: "해결",	
	replyBtn: "답글",
	saveBtn: "게시",
	deleteBtn: "삭제",
	cancelBtn: "취소",
	reopenBtn: "다시 열기",
	todayAt: "오늘 ${time}",
	yesterdayAt: "어제 ${time}",
	dateAt: "${date} ${time}",
	mentions: "멘션할 사용자 선택",
	noMentions: "입력을 완료하려면 공백을 탭하십시오.",
	nocomments: "'${0}' 문서에 댓글이 없습니다.",
	
	newComments:"새로운 댓글",
	mentiontomesomebody:"특정 사용자",
	mentiontome:"${0}님이 댓글에서 사용자를 멘션했습니다.",
	
	newcommentsnumber:"읽지 않은 댓글 수",
	jawsnewcommentsnumber: "읽지 않은 댓글 수 ",
	jawsnactivecommentsnumber: "활성 댓글 수 ",
	
	activenum:"활성 댓글 수",
	filterDesc:"댓글 필터링",
	menuallcomments:"모든 댓글",
	menutome: "내가 멘션된 글",
	menubyme: "내가 작성한 글",
	menuactive: "활성",
	menuresolved: "해결됨",
	searchDesc: "댓글 검색",
	search: "검색",
	closeDesc: "검색 닫기",
	clear: "지우기",
	warnEnterKeywords: "검색 조건 입력",
	nocommentstome: "현재 '${0}' 문서에 내가 멘션된 댓글 또는 응답이 없습니다.",
	nocommentsbyme: "현재 '${0}' 문서에 내가 작성한 댓글 또는 응답이 없습니다.",
	nocommentsar: "현재 '${1}' 문서에 '${0}' 카테고리의 댓글이 없습니다.",
	nosearchedcomments: "현재 '${2}' 문서에 '${1}' 카테고리의 '${0}'을(를) 포함하는 댓글 또는 응답이 없습니다.",
	
	prevBtn: "이전",
	nextBtn: "다음",
	mentionHint:"${0} - ${1} / 총 ${2} 일치 표시",
		
	resolveFlag: "해결된 댓글",
	jawsCommentHint: "${authorname}이(가) ${timestamp} 댓글을 게시했습니다.",
	jawsReplyHint: "${authorname}이(가) ${timestamp} 응답을 게시했습니다.",
	jawsContentHint: "컨텐츠는 ${content}입니다.",
	jawsCommentStatusHint: "상태는 ${status}입니다.",
	jawsCommentKeyHint: "Enter 또는 스페이스바를 눌러 완료 댓글 스레드를 보고 댓글을 해결, 응답 또는 삭제할 수 있습니다.",
	jawsMentionHint: "Docs 멘션 위젯입니다. 멘션할 사용자를 추가하려면 위로 화살표 또는 아래로 화살표 누르십시오.",
	jawsMentionSelected: "멘션하려면 Enter 또는 스페이스바를 누르십시오.",
	commentDeletedMsg: "현재 댓글을 다른 편집자가 삭제했습니다.",
	commentResolvedMsg: "현재 댓글이 해결되었습니다.",
	warningCommentMsg: "${0} 파일에 대해 Docs 안에서 작성된 댓글은 온라인으로만 지원됩니다. 댓글의 연결은 편집을 위해 새 버전이 업로드되면 제거됩니다.",
	orphanCommentTip: "이 업로드된 버전에서 댓글의 연결이 제거되었습니다.",
	warningCommentName: "경고"
})

