({
	ORIENTATION_LABEL: "Orientácia",
	PORTRAIT: "Portrét",
	LANDSCAPE: "Krajinka",
	PAGE_LABEL: "Poradie strán",
	PAGE_TYPE1: "Zhora nadol, potom doprava",
	PAGE_TYPE2: "Zľava doprava, potom nadol",
	DISPLAY_OPTION_LABEL: "Voľby zobrazenia",
	HEADER: "Hlavička",
	FOOTER: "Päta",
	GRIDLINE: "Čiary mriežky",
	TAGGED_PDF: "Označené PDF",
	MARGINS_LABEL: "Okraje",
	TOP: "Vrch:",
	TOP_DESC:"Horný okraj, v centimetroch",
	TOP_DESC2:"Horný okraj, v palcoch",
	BOTTOM: "Spodok:",
	BOTTOM_DESC:"Spodný okraj, v centimetroch",
	BOTTOM_DESC2:"Spodný okraj, v palcoch",	
	LEFT: "Vľavo:",
	LEFT_DESC:"Ľavý okraj, v centimetroch",
	LEFT_DESC2:"Ľavý okraj, v palcoch",	
	RIGHT: "Vpravo:",
	RIGHT_DESC:"Pravý okraj, v centimetroch",
	RIGHT_DESC2:"Pravý okraj, v palcoch",	
	PAPER_FORMAT_LABEL: "Formát papiera",
	PAPER_SIZE_LABEL: "Veľkosť papiera:",
	HEIGHT: "Výška:",
	HEIGHT_DESC:"Výška papiera, v centimetroch",
	HEIGHT_DESC2:"Výška papiera, v palcoch",		
	WIDTH: "Šírka:",
	WIDTH_DESC:"Šírka papiera, v centimetroch",
	WIDTH_DESC2:"Šírka papiera, v palcoch",
	
	INVALID_MSG: "Vstup je neplatný a bol automaticky opravený. Ak chcete iný výsledok, skúste inú hodnotu.",
	
	TOOLTIP1:"Vytlačí maximum riadkov podľa dĺžky papiera, potom pokračuje, kým v hárku nebudú ďalšie stĺpce, a potom sa presunie nadol doľava a vytlačí ďalšiu skupinu riadkov.",
	TOOLTIP2:"Vytlačí maximum stĺpcov podľa šírky papiera, pričom sa posúva nadol, kým v hárku nebudú ďalšie riadky, a potom sa presunie nahor doprava a vytlačí ďalšiu skupinu stĺpcov.",
	CM_LABEL: "cm",
	LETTER: "List",
	LEGAL: "Legal",
	TABLOID: "Tabloid",
	USER: "Užívateľ",
	SIZE1: "Env. #6 3/4",
	SIZE2: "Env. Monarch",
	SIZE3: "Env. #9",
	SIZE4: "Env. #10",
	SIZE5: "Env. #11",
	SIZE6: "Env. #12",
	SIZE7: "16 kai",
	SIZE8: "32 kai",
	SIZE9: "32 kai large"
})
	
