({
	alt			: "Texto alternativo:",
	width		: "Largura:",
	height		: "Altura:",
	cmUnit   : "cm",
	ptUnit 	 : "pt",
	inchUnit : "polegada",
	inUnit   : "pol",
	mmUnit 	 : "mm",
	
	inputWarning: "Introduza um número positivo com a unidade predefinida. ",
	
	properties: "Propriedades",
	data: "Dados",
	chart: "Gráfico",
	axis: "Eixo",
	series: "Série",
	font: "Tipo de letra",
	title: "Título",
	legend: "Legenda",
	placement: "Colocação",
	background: "Fundo",
	plotarea: "Área de traçamento",
	line : "Linha",
	fill: "Preenchimento",
	border : "Contorno",
	labelfont: "Rótulo",
	scale: "Escala",
	minimum: "Mínima",
	maximum: "Máxima",
	majorunit: "Unidade maior",
	minorunit: "Unidade menor",
	smooth: "Suave",
	marker: "Marcadores",
	markerfill: "Marcador",
	enterTitle: "Introduza o título aqui",
	inputNumberWarning: "Introduza um número.",
	inputPosNumberWarning: "Introduza um número positivo.",
	maxMinWarning: "O valor máximo tem de ser superior ao valor mínimo",
	selectFontName: "Seleccionar nome do tipo de letra",
	selectFontSize: "Seleccionar tamanho do tipo de letra",
	setBold: "Negrito",
	setItalic: "Itálico",
	setFontColor: "Definir cor do tipo de letra",
	setLegendPos: "Definir colocação da legenda",
	setBackColor: "Definir cor de segundo plano do gráfico",
	setBorderWidth: "Definir largura do contorno",
	setBorderColor: "Definir cor do contorno",
	setPlotAreaColor: "Definir cor da área de traçamento",
	selectAxis: "Seleccionar um eixo",
	setLineWidth: "Definir largura da linha",
	setLineColor: "Definir cor da linha",
	selectSeries: "Seleccionar uma série",
	setFillColor: "Definir cor de preenchimento",
	setMarker: "Definir marcadores",
	setSmooth: "Definir linha suave",
	chartTitle: "Título do gráfico",
	axisTitle: "Título do eixo",
	
	ERR1: "Uma matriz tem de ser colocada entre chavetas.",
	ERR3: "Os itens da cadeia têm de ser colocados entre aspas duplas.",
	ERR4: "Introduza apenas um intervalo.",
	ERR5: "O intervalo tem de existir.",
	ERR6: "Todos os intervalos têm de estar na mesma folha.",
	ERR7: "Todos os intervalos têm de corresponder a uma única linha ou coluna.",
	ERR9: "É requerido um valor de série.",
	
	n	: "Nenhuma",
	l	: "Esquerda",
	r	: "Direita",
	t	: "Superior",
	b   : "Inferior",
	
	dataSeries:"Série de dados",
	label:"Nome da série",
	xVal:"Valores da série X",
	yVal:"Valores da série Y",
	val:"Valores da série",
	cat:"Categoria",
		
	ltr: "Esquerda para a direita",
	rtl: "Direita para a esquerda",
	auto: "Contextual",
	bidi_dir: "Direcção",
	bidi_text_dir: "Direcção do texto"
})
