({
	alt			: "Ordezko testua:",
	width		: "Zabalera:",
	height		: "Altuera:",
	cmUnit   : "cm",
	ptUnit 	 : "puntu",
	inchUnit : "hazbete",
	inUnit   : "in",
	mmUnit 	 : "mm",
	
	inputWarning: "Idatzi zenbaki positibo bat eta lehenetsitako unitatea. ",
	
	properties: "Propietateak",
	data: "Datuak",
	chart: "Diagrama",
	axis: "Ardatza",
	series: "Serieak",
	font: "Letra-tipoa",
	title: "Titulua",
	legend: "Legenda",
	placement: "Kokapena",
	background: "Atzeko planoa",
	plotarea: "Marrazte-area",
	line : "Lerroa",
	fill: "Betegarria",
	border : "Ertza",
	labelfont: "Etiketa",
	scale: "Eskala",
	minimum: "Minimoa",
	maximum: "Maximoa",
	majorunit: "Unitate nagusia",
	minorunit: "Unitate sekundarioa",
	smooth: "Leuna",
	marker: "Markatzaileak",
	markerfill: "Markatzailea",
	enterTitle: "Idatzi titulua hemen",
	inputNumberWarning: "Idatzi zenbaki bat.",
	inputPosNumberWarning: "Idatzi zenbaki positibo bat.",
	maxMinWarning: "Balio maximoa balio minimoa baino handiagoa izan behar da",
	selectFontName: "Hautatu letra-izena",
	selectFontSize: "Hautatu letra-tamaina",
	setBold: "Lodia",
	setItalic: "Etzana",
	setFontColor: "Ezarri letra-kolorea",
	setLegendPos: "Ezarri legendaren kokalekua",
	setBackColor: "Ezarri diagramaren atzeko planoaren kolorea",
	setBorderWidth: "Ezarri ertzaren zabalera",
	setBorderColor: "Ezarri ertzaren kolorea",
	setPlotAreaColor: "Ezarri marrazte-arearen kolorea",
	selectAxis: "Hautatu ardatz bat",
	setLineWidth: "Ezarri lerroaren zabalera",
	setLineColor: "Ezarri lerroaren kolorea",
	selectSeries: "Hautatu serie bat",
	setFillColor: "Ezarri betetze-kolorea",
	setMarker: "Ezarri markatzaileak",
	setSmooth: "Ezarri lerro leuna",
	chartTitle: "Diagramaren titulua",
	axisTitle: "Ardatzaren titulua",
	
	ERR1: "Matrize bat giltza artean ({}) egon behar da.",
	ERR3: "Katearen elementuak komatxo bikoitzen artean egon behar dira.",
	ERR4: "Idatzi barruti bat bakarrik.",
	ERR5: "Barrutia existitu behar da.",
	ERR6: "Barruti guztiak orri berberean egon behar dira.",
	ERR7: "Barruti guztiak errenkada edo zutabe bakar baterako izan behar dira.",
	ERR9: "Serie-balio bat behar da.",
	
	n	: "Bat ere ez",
	l	: "Ezkerrean",
	r	: "Eskuinean",
	t	: "Goian",
	b   : "Behean",
	
	dataSeries:"Datu-seriea",
	label:"Serie-izena",
	xVal:"X seriearen balioak",
	yVal:"Y seriearen balioak",
	val:"Serie-balioak",
	cat:"Kategoria",
		
	ltr: "Ezkerretik eskuinera",
	rtl: "Eskuinetik ezkerrera",
	auto: "Testuinguruaren araberakoak",
	bidi_dir: "Norabidea",
	bidi_text_dir: "Testuaren norabidea"
})

