({
	alt			: "Teks Alternatif:",
	width		: "Lebar:",
	height		: "Tinggi:",
	cmUnit   : "cm",
	ptUnit 	 : "pt",
	inchUnit : "inci",
	inUnit   : "dalam",
	mmUnit 	 : "mm",
	
	inputWarning: "Masukkan angka positif dengan unit default. ",
	
	properties: "Properti",
	data: "Data",
	chart: "Bagan",
	axis: "Sumbu",
	series: "Seri",
	font: "Font",
	title: "Judul",
	legend: "Legenda",
	placement: "Penempatan",
	background: "Latar belakang",
	plotarea: "Area Plot",
	line : "Garis",
	fill: "Isian",
	border : "Tepian",
	labelfont: "Label",
	scale: "Skala",
	minimum: "Minimum",
	maximum: "Maksimum",
	majorunit: "Satuan Mayor",
	minorunit: "Satuan Minor",
	smooth: "Halus",
	marker: "Penanda",
	markerfill: "Penanda",
	enterTitle: "Masukkan judul di sini",
	inputNumberWarning: "Masukkan angka.",
	inputPosNumberWarning: "Masukkan angka positif.",
	maxMinWarning: "Nilai maksimum harus lebih besar dari nilai minimum",
	selectFontName: "Pilih Nama Font",
	selectFontSize: "Pilih Ukuran Font",
	setBold: "Tebal",
	setItalic: "Miring",
	setFontColor: "Atur Warna Font",
	setLegendPos: "Atur Penempatan Legenda",
	setBackColor: "Atur Warna Latar Belakang Grafik",
	setBorderWidth: "Atur Lebar Tepian",
	setBorderColor: "Atur Warna Tepian",
	setPlotAreaColor: "Atur Warna Area Plot",
	selectAxis: "Pilih Sumbu",
	setLineWidth: "Atur Lebar Garis",
	setLineColor: "Atur Warna Garis",
	selectSeries: "Pilih Seri",
	setFillColor: "Atur Warna Isian",
	setMarker: "Atur Penanda",
	setSmooth: "Atur Garis Halus",
	chartTitle: "Judul Grafik",
	axisTitle: "Judul Sumbu",
	
	ERR1: "Susunan harus diapit oleh kurung kurawal.",
	ERR3: "Item string harus diapit dengan tanda petik ganda.",
	ERR4: "Masukkan hanya satu rentang.",
	ERR5: "Rentang harus ada.",
	ERR6: "Semua rentang harus berada pada lembar yang sama.",
	ERR7: "Semua rentang harus untuk satu baris atau kolom",
	ERR9: "Nilai seri wajib diisi.",
	
	n	: "Tidak Ada",
	l	: "Kiri",
	r	: "Kanan",
	t	: "Atas",
	b   : "Bawah",
	
	dataSeries:"Seri Data",
	label:"Nama Seri",
	xVal:"Nilai X Seri",
	yVal:"Nilai Y Seri",
	val:"Nilai Seri",
	cat:"Kategori",
		
	ltr: "Kiri ke Kanan",
	rtl: "Kanan ke Kiri",
	auto: "Kontekstual",
	bidi_dir: "Arah",
	bidi_text_dir: "Arah Teks"
})
