({
	labelPrintConfig: "최상의 인쇄 결과를 얻으려면 다음 구성을 사용하도록 브라우저의 페이지를 설정하십시오.",
	labelConfigPageSize: "페이지 크기: ${0}",
	labelConfigOrientation: "방향: ${0}",
	labelConfigHeader: "머리글: 공백",
	labelConfigFooter: "바닥글: 공백",
	labelConfigMargins: "여백: ",
	labelConfigMarginTop: "위: ${0}${1}",
	labelConfigMarginBottom: "아래: ${0}${1}",
	labelConfigMarginLeft: "왼쪽: ${0}${1}",
	labelConfigMarginRight: "오른쪽: ${0}${1}",
	labelPrintContinue: "브라우저 설정이 완료되면 확인을 클릭하여 파일 인쇄를 계속하십시오.",
	labelMm: "mm",
	labelInch: "인치",
	labelPortrait: "세로",
	labelPageA4: "A4",
	labelLetter: "Letter",
	labelLandscape: "가로",
	titlePrintConfig: "인쇄 설정",
	titlePrepare: "인쇄 준비",
	msgPrepare: "파일 인쇄를 준비하고 있습니다. 시간이 오래 걸릴 수 있습니다.",
	errPrepare: "데이터를 준비하는 중 오류가 발생했습니다.\n다시 시도하시겠습니까?",
	titleErr: "오류",
	btnRetry: "재시도"
})
