({
	ORIENTATION_LABEL: "Retning",
	PORTRAIT: "Stående",
	LANDSCAPE: "Liggende",
	PAGE_LABEL: "Siderekkefølge",
	PAGE_TYPE1: "Øverst til nederst, så til høyre",
	PAGE_TYPE2: "Venstre til høyre, så ned",
	DISPLAY_OPTION_LABEL: "Visningsalternativer",
	HEADER: "Topptekst",
	FOOTER: "Bunntekst",
	GRIDLINE: "Rutenettlinjer",
	MARGINS_LABEL: "Marger",
	TOP: "Topp:",
	BOTTOM: "Bunn:",
	LEFT: "Venstre:",
	RIGHT: "Høyre:",
	PAPER_FORMAT_LABEL: "Papirformat",
	PAPER_SIZE_LABEL: "Størrelse:",
	HEIGHT: "Høyde:",
	WIDTH: "Bredde:",
	
	TOOLTIP1:"Skriver ut så mange rader som sider er lang, og beveger seg bortover til det ikke er flere kolonner på arket, og flytter så ned for å skrive den neste gruppen med rader.",
	TOOLTIP2:"Skriver ut så mange kolonner som sider er bred, og beveger seg nedover til det ikke er flere rader på arket, og flytter så opp og til høyre for å skrive den neste gruppen med kolonner.",
	CM_LABEL: "cm",
	LETTER: "Letter",
	LEGAL: "Legal",
	TABLOID: "Tabloid",
	USER: "Bruker",
	SIZE1: "Env. #6 3/4",
	SIZE2: "Env. Monarch",
	SIZE3: "Env. #9",
	SIZE4: "Env. #10",
	SIZE5: "Env. #11",
	SIZE6: "Env. #12",
	SIZE7: "16 kai",
	SIZE8: "32 kai",
	SIZE9: "32 kai stor"
})
	
