/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
    Arrow01_Gray: "Arrow 01 Gray",
    Arrow02_Gray: "Arrow 02 Gray",
    Arrow03_Red: "Arrow 03 Red",
    Arrow04_Blue: "Arrow 04 Blue",
    Arrow05_Blue: "Arrow 05 Blue",
    Arrow06_Yellow: "Arrow 06 Yellow",
    Arrow07_Red: "Arrow 07 Red",
    Arrow08_Gray: "Arrow 08 Gray",
    Arrow09_Orange: "Arrow 09 Orange",
    Arrow10_Blue: "Arrow 10 Blue",
    Arrow11_Blue: "Arrow 11 Blue",
    Arrow12_Green: "Arrow 12 Green",
    Arrow13_Blue: "Arrow 13 Blue",
    Arrow14_Green: "Arrow 14 Green",
    Arrow15_Orange: "Arrow 15 Orange",
    Arrow16_Gray: "Arrow 16 Gray",
    CircleArrow01_Green: "Circle Arrow 01 Green",
    CircleArrow02_Multi: "Circle Arrow 02 Multi",
    CircleArrow03_Multi: "Circle Arrow 03 Multi",
    CircleArrow04_Multi: "Circle Arrow 04 Multi",
    CircleArrow05_Multi: "Circle Arrow 05 Multi",
    CircleArrow06_Multi: "Circle Arrow 06 Multi",
    CircleArrow07_Blue: "Circle Arrow 07 Blue",
    CircleArrow08_Green: "Circle Arrow 08 Green",
    CircleArrow09_Multi: "Circle Arrow 09 Multi",
    CurvedArrow01_Gray: "Curved Arrow 01 Gray",
    CurvedArrow02_Blue: "Curved Arrow 02 Blue",
    CurvedArrow03_Blue: "Curved Arrow 03 Blue",
    CurvedArrow04_Orange: "Curved Arrow 04 Orange",
    CurvedArrow05_Red: "Curved Arrow 05 Red",
    CurvedArrow06_Blue: "Curved Arrow 06 Blue",
    CurvedArrow07_Purple: "Curved Arrow 07 Purple",
    CurvedArrow08_Green: "Curved Arrow 08 Green",
    CurvedArrow09_Gray: "Curved Arrow 09 Gray",
    CurvedArrow10_Blue: "Curved Arrow 10 Blue",
    CurvedArrow11_Orange: "Curved Arrow 11 Orange",
    CurvedArrow12_Blue: "Curved Arrow 12 Blue",
    CurvedArrow13_Green: "Curved Arrow 13 Green",
    CurvedArrow14_Brown: "Curved Arrow 14 Brown",
    CurvedArrow15_Blue: "Curved Arrow 15 Blue",
    CurvedArrow16_Gray: "Curved Arrow 16 Gray",
    CurvedArrow17_Gray: "Curved Arrow 17 Gray",
    CurvedArrow18_Gray: "Curved Arrow 18 Gray",
    CurvedArrow19_Gray: "Curved Arrow 19 Gray",
    CurvedArrow20_Gray: "Curved Arrow 20 Gray",
    TrendArrow01_Red: "Trend Arrow 01 Red",
    TrendArrow02_Green: "Trend Arrow 02 Green",
    TrendArrow03_Orange: "Trend Arrow 03 Orange",
    TrendArrow04_Red: "Trend Arrow 04 Red",
    TrendArrow05_Orange: "Trend Arrow 05 Orange",
    TrendArrow06_Blue: "Trend Arrow 06 Blue",
    TrendArrow07_Orange: "Trend Arrow 07 Orange",
    TrendArrow08_Yellow: "Trend Arrow 08 Yellow",
    TrendArrow09_Blue: "Trend Arrow 09 Blue",
    TrendArrow10_Blue: "Trend Arrow 10 Blue",
    TrendArrow11_Blue: "Trend Arrow 11 Blue",
    TrendArrow12_Blue: "Trend Arrow 12 Blue",
    TrendArrow13_Red: "Trend Arrow 13 Red",
    TrendArrow14_Multi: "Trend Arrow 14 Multi",
    TrendArrow15_Blue: "Trend Arrow 15 Blue",
    Bullet01_Circle_DarkRed: "Bullet 01 Circle Dark Red",
    Bullet02_Circle_Blue: "Bullet 02 Circle Blue",
    Bullet03_Circle_Green: "Bullet 03 Circle Green",
    Bullet04_Square_Black: "Bullet 04 Square Black",
    Bullet05_Square_Orange: "Bullet 05 Square Orange",
    Bullet06_Square_Purple: "Bullet 06 Square Purple",
    Bullet07_Diamond_Blue: "Bullet 07 Diamond Blue",
    Bullet08_Diamond_LightBlue: "Bullet 08 Diamond Light Blue",
    Bullet09_Diamond_Red: "Bullet 09 Diamond Red",
    Bullet10_Star_Yellow: "Bullet 10 Star Yellow",
    Bullet11_Star_Blue: "Bullet 11 Star Blue",
    Bullet12_Triangle_Blue: "Bullet 12 Triangle Blue",
    Bullet13_Triangle_DarkGreen: "Bullet 13 Triangle Dark Green",
    Bullet14_Arrow_Red: "Bullet 14 Arrow Red",
    Bullet15_Arrow_Blue: "Bullet 15 Arrow Blue",
    Bullet16_Box_Blue: "Bullet 16 Box Blue",
    Bullet17_Box_Red: "Bullet 17 Box Red",
    Bullet18_Asterisk_LightBlue: "Bullet 18 Asterisk Light Blue",
    Bullet19_Leaves_Red: "Bullet 19 Leaves Red",
    Bullet20_Target_Blue: "Bullet 20 Target Blue",
    Bullet21_Arrow_Blue: "Bullet 21 Arrow Blue",
    Bullet22_Arrow_DarkBlue: "Bullet 22 Arrow Dark Blue",
    Bullet23_Arrow_Brown: "Bullet 23 Arrow Brown",
    Bullet24_Flag_Red: "Bullet 24 Flag Red",
    Bullet25_Flag_Green: "Bullet 25 Flag Green",
    Bullet26_X_Red: "Bullet 26 X Red",
    Bullet27_X_Black: "Bullet 27 X Black",
    Bullet28_Checkmark_Green: "Bullet 28 Checkmark Green",
    Bullet29_Checkmark_Blue: "Bullet 29 Checkmark Blue",
    Bullet30_Square_DarkRed: "Bullet 30 Square Dark Red",
    camera: "Camera",
    computer1: "Computer 1",
    computer2: "Computer 2",
    computer3: "Computer 3",
    Computer_Cloud: "Computer Cloud",
    Computer_Desktop: "Computer Desktop",
    Computer_Laptop_Black: "Computer Laptop Black",
    Computer_Laptop_Silver: "Computer Laptop Silver",
    Database: "Database",
    evelope: "Envelope",
    newspapers: "Newspapers",
    openevelope: "Open Envelope",
    Server: "Server",
    speaker: "Speaker",
    WirelessAccessPoint: "Wireless Access Point",
    Cycle01_Transparent: "Cycle 01 Transparent",
    Cycle02_Transparent_Blue: "Cycle 02 Transparent Blue",
    Cycle03_Blue: "Cycle 03 Blue",
    Cycle04_Blue: "Cycle 04 Blue",
    Cycle05: "Cycle 05",
    Cycle06: "Cycle 06",
    Cycle07: "Cycle 07",
    Cycle08_Blue: "Cycle 08 Blue",
    Cycle09_Orange: "Cycle 09 Orange",
    Donut01_LightBlue: "Donut 01 Light Blue",
    Donut02_Blue: "Donut 02 Blue",
    Donut03_Blue: "Donut 03 Blue",
    Donut04_DarkBlue: "Donut 04 Dark Blue",
    Donut05_DarkBlue: "Donut 05 Dark Blue",
    Donut06_Blue: "Donut 06 Blue",
    Donut07_Blue: "Donut 07 Blue",
    Graph: "Graph",
    People01_Blue: "People 01 Blue",
    People02: "People 02",
    Pillars01_Orange: "Pillars 01 Orange",
    Pillars02_LightBlue: "Pillars 02 Light Blue",
    Process01_Blue: "Process 01 Blue",
    Process02_Blue: "Process 02 Blue",
    Process03_Blue: "Process 03 Blue",
    Process04_GoUp_Blue: "Process 04 Go Up Blue",
    Process05_GoUp_Red: "Process 05 Go Up Red",
    Process06_GoUp_Yellow: "Process 06 Go Up Yellow",
    Process07_Blue: "Process 07 Blue",
    Pyramid01: "Pyramid 01",
    Pyramid02_Blue: "Pyramid 02 Blue",
    Pyramid03: "Pyramid 03",
    Radial01_Green: "Radial 01 Green",
    Radial02_Green: "Radial 02 Green",
    Radial03_Sphere: "Radial 03 Sphere",
    Radial04_Sphere_Red: "Radial 04 Sphere Red",
    Radial05_Sphere_Blue: "Radial 05 Sphere Blue",
    Radial06_Arrows_DarkBlue: "Radial 06 Arrows Dark Blue",
    Radial07_Arrows_DarkBlue: "Radial 07 Arrows Dark Blue",
    Section_Circle: "Section Circle",
    Section_Cubes01: "Section Cubes 01",
    Section_Cubes02_Blue: "Section Cubes 02 Blue",
    Section_Cubes03_Orange: "Section Cubes 03 Orange",
    Section_Cubes04: "Section Cubes 04",
    Section_Cubes05: "Section Cubes 05",
    Section_Cuboids01_Blue: "Section Cuboids 01 Blue",
    Section_Cuboids02_Blue: "Section Cuboids 02 Blue",
    Section_Cuboids03: "Section Cuboids 03",
    Section_Gears01: "Section Gears 01",
    Section_Gears02: "Section Gears 02",
    Section_Gears03: "Section Gears 03",
    Section_Hexagon04_Orange: "Section Hexagon 04 Orange",
    Section_Hexagons01: "Section Hexagons 01",
    Section_Hexagons02_Blue: "Section Hexagons 02 Blue",
    Section_Hexagons03_Blue: "Section Hexagons 03 Blue",
    Section_Leaves01_LightBlue: "Section Leaves 01 Light Blue",
    Section_Leaves02_Green: "Section Leaves 02 Green",
    Section_Pasters01: "Section Pasters 01",
    Section_Pasters02_Blue: "Section Pasters 02 Blue",
    Section_Puzzle01: "Section Puzzle 01",
    Section_Puzzle02: "Section Puzzle 02",
    Section_Puzzle03: "Section Puzzle 03",
    Section_Rectangles: "Section Rectangles",
    Section_Squares: "Section Squares",
    Section_Triangle: "Section Triangle",
    Target: "Target",
    Venn01: "Venn 01",
    Venn02: "Venn 02",
    Venn03: "Venn 03",
    Venn04: "Venn 04",
    Venn05: "Venn 05",
    Venn06_Blue: "Venn 06 Blue",
    Venn07_Blue: "Venn 07 Blue",
    Venn08: "Venn 08",
    Blackboard: "Blackboard",
    Books: "Books",
    Books1: "Books 1",
    books2: "Books 2",
    Chalk: "Chalk",
    clipboard: "clipboard",
    clock: "clock",
    Globe: "Globe",
    Glue: "Glue",
    GraduationCap: "Graduation Cap",
    magnifyingglass: "magnifyingglass",
    Microscope: "Microscope",
    Notebook: "Notebook",
    notepad1: "Notepad 1",
    notepad2: "Notepad 2",
    notepad3: "Notepad 3",
    PaperClip_Blue: "Paper Clip Blue",
    PaperClip_Red: "Paper Clip Red",
    Pencil: "Pencil",
    Ruler: "Ruler",
    TestTubes: "Test Tubes",
    thumbtack: "Thumbtack",
    clouds: "Clouds",
    DrippingFaucet: "Dripping Faucet",
    Earth: "Earth",
    EndangeredAnimals1: "Endangered Animals 1",
    EndangeredAnimals2: "Endangered Animals 2",
    GreenCar: "Green Car",
    GreenFactory: "Green Factory",
    GreenHouse: "Green House",
    Leaf1: "Leaf 1",
    Leaf2: "Leaf 2",
    lightbulb: "Lightbulb",
    LightBulb_Flourescent_Off: "Light Bulb Flourescent Off",
    LightBulb_Flourescent_On: "Light Bulb Flourescent On",
    LightBulb_Standard_Off1: "Light Bulb Standard Off 1",
    LightBulb_Standard_Off2: "Light Bulb Standard Off 2",
    LightBulb_Standard_On: "Light Bulb Standard On",
    lightningcloud: "Lightning Cloud",
    Pollution_Car: "Pollution Car",
    Pollution_Factory: "Pollution Factory",
    Raindrop: "Raindrop",
    RecycleBin: "Recycle Bin",
    RecycleSymbol: "Recycle Symbol",
    RenewableEnergySymbol: "Renewable Energy Symbol",
    RenewableEnergy_Solar: "Renewable Energy Solar",
    RenewableEnergy_Water: "Renewable Energy Water",
    RenewableEnergy_Wind: "Renewable Energy Wind",
    sun: "Sun",
    Sun1: "Sun 1",
    Sun2: "Sun 2",
    sundandcloud: "Sun and Cloud",
    world: "World",
    Agreement: "Agreement",
    ATM01: "ATM 01",
    ATM02: "ATM 02",
    Balance_Balanced1: "Balance Balanced 1",
    Balance_Balanced2: "Balance Balanced 2",
    Balance_Unbalanced1: "Balance Unbalanced 1",
    Balance_Unbalanced2: "Balance Unbalanced 2",
    Calculator: "Calculator",
    Chart_Decrease1: "Chart Decrease 1",
    Chart_Decrease2: "Chart Decrease 2",
    Chart_Increase1: "Chart Increase 1",
    Chart_Increase2: "Chart Increase 2",
    Chart_Plateau: "Chart Plateau",
    Check: "Check",
    Contract: "Contract",
    CreditCard_Black: "Credit Card Black",
    CreditCard_Cut: "Credit Card Cut",
    CreditCard_Gold: "Credit Card Gold",
    Currency_Dollar: "Currency Dollar",
    Currency_Dollars: "Currency Dollars",
    Currency_Stack: "Currency Stack",
    Currency_StackCoins: "Currency Stack Coins",
    GoldBar: "Gold Bar",
    GoldBar_Stack: "Gold Bar Stack",
    MoneyBag01: "Money Bag 01",
    MoneyBag02: "Money Bag 02",
    PercentSign: "Percent Sign",
    PiggyBank01_Broken: "Piggy Bank 01 Broken",
    PiggyBank02_Broken: "Piggy Bank 02 Broken",
    PiggyBank_Coins: "Piggy Bank Coins",
    PiggyBank_Currency: "Piggy Bank Currency",
    Portfolio: "Portfolio",
    PriceTag: "Price Tag",
    Safe_Closed: "Safe Closed",
    Safe_Empty: "Safe Empty",
    Safe_Full: "Safe Full",
    Seal_Gold: "Seal Gold",
    Seal_Red: "Seal Red",
    Seal_Silver: "Seal Silver",
    Wallet_Empty: "Wallet Empty",
    Wallet_Full1: "Wallet Full 1",
    Wallet_Full2: "Wallet Full 2",
    BusinessPerson_Female6: "Business Person Female 6",
    BusinessPerson_Male3: "Business Person Male 3",
    Computer_User_Female1: "Computer User Female1",
    ConstructionWorker2: "Construction Worker 2",
    Presenter_Female1: "Presenter Female 1",
    Component_Circle01_Transparent_DarkBlue: "Component Circle 01 Transparent Dark Blue",
    Component_Circle02_Transparent_Bule: "Component Circle 02 Transparent Bule",
    Component_Circle03_Transparent_Green: "Component Circle 03 Transparent Green",
    Component_Circle04_Transparent_Orange: "Component Circle 04 Transparent Orange",
    Component_Circle05_Transparent_Red: "Component Circle 05 Transparent Red",
    Component_Cube01_DarkBlue: "Component Cube 01 Dark Blue",
    Component_Cube02_LightBlue: "Component Cube 02 Light Blue",
    Component_Cube03_Green: "Component Cube 03 Green",
    Component_Cube04_Orange: "Component Cube 04 Orange",
    Component_Cube05_DarkRed: "Component Cube 05 Dark Red",
    Component_Cuboid01_DarkBlue: "Component Cuboid 01 Dark Blue",
    Component_Cuboid02_Blue: "Component Cuboid 02 Blue",
    Component_Cuboid03_Green: "Component Cuboid 03 Green",
    Component_Cuboid04_Orange: "Component Cuboid 04 Orange",
    Component_Cuboid05_Red: "Component Cuboid 05 Red",
    Component_Gear01_DarkBlue: "Component Gear 01 Dark Blue",
    Component_Gear02_LightBlue: "Component Gear 02 Light Blue",
    Component_Gear03_Green: "Component Gear 03 Green",
    Component_Gear04_DarkRed: "Component Gear 04 Dark Red",
    Component_Gear05_Orange: "Component Gear 05 Orange",
    Component_Person01_DarkBlue: "Component Person 01 Dark Blue",
    Component_Person02_Blue: "Component Person 02 Blue",
    Component_Person03_Green: "Component Person 03 Green",
    Component_Person04_DarkRed: "Component Person 04 Dark Red",
    Component_Person05_Orange: "Component Person 05 Orange",
    Component_PuzzlePiece01_DarkBlue: "Component Puzzle Piece 01 Dark Blue",
    Component_PuzzlePiece02_Blue: "Component Puzzle Piece 02 Blue",
    Component_PuzzlePiece03_Green: "Component Puzzle Piece 03 Green",
    Component_PuzzlePiece04_Red: "Component Puzzle Piece 04 Red",
    Component_PuzzlePiece05_Orange: "Component Puzzle Piece 05 Orange",
    Component_Sphere01_DarkBlue: "Component Sphere 01 Dark Blue",
    Component_Sphere02_LightBlue: "Component Sphere 02 Light Blue",
    Component_Sphere03_Green: "Component Sphere 03 Green",
    Component_Sphere04_DarkRed: "Component Sphere 04 Dark Red",
    Component_Sphere05_Orange: "Component Sphere 05 Orange",
    Book: "Book",
    Box01: "Box 01",
    Box02: "Box 02",
    Bulb01_Yellow: "Bulb 01 Yellow",
    Bulb02_Yellow: "Bulb 02 Yellow",
    Calendar: "Calendar",
    Chart: "Chart",
    Clipboard: "Clipboard",
    Clock: "Clock",
    Compass: "Compass",
    Flag01_Red: "Flag 01 Red",
    Flag02_Green: "Flag 02 Green",
    Flag03_Blue: "Flag 03 Blue",
    Gift: "Gift",
    House: "House",
    Icon_Computer01_White: "Icon Computer 01 White",
    Icon_Computer02_Black: "Icon Computer 02 Black",
    Icon_Disk01_Blue: "Icon Disk 01 Blue",
    Icon_Disk02_Green: "Icon Disk 02 Green",
    Icon_Document01_Grey: "Icon Document 01 Grey",
    Icon_Document02_Grey: "Icon Document 02 Grey",
    Icon_Document03_Blue: "Icon Document 03 Blue",
    Icon_Document04_Blue: "Icon Document 04 Blue",
    Icon_Envelope01_Blue: "Icon Envelope 01 Blue",
    Icon_Envelope02_Yellow: "Icon Envelope 02 Yellow",
    Icon_Envelope03_Open_Yellow: "Icon Envelope 03 Open Yellow",
    Icon_Envelope04_Open_Yellow: "Icon Envelope 04 Open Yellow",
    Icon_Folder01_Yellow: "Icon Folder 01 Yellow",
    Icon_Folder02_Yellow: "Icon Folder 02 Yellow",
    Icon_Folder03_Open_Yellow: "Icon Folder 03 Open Yellow",
    Icon_Folder04_Open_Yellow: "Icon Folder 04 Open Yellow",
    Icon_Gear01_Grey: "Icon Gear 01 Grey",
    Icon_Gear02_Blue: "Icon Gear 02 Blue",
    Icon_Network01_Blue: "Icon Network 01 Blue",
    Icon_Network02: "Icon Network 02",
    Icon_Pencil01: "Icon Pencil 01",
    Icon_Pencil02: "Icon Pencil 02",
    Icon_Printer01_White: "Icon Printer 01 White",
    Icon_Printer02_Black: "Icon Printer 02 Black",
    Key01: "Key 01",
    Key02: "Key 02",
    Lock01_Yellow: "Lock 01 Yellow",
    Lock02_Yellow: "Lock 02 Yellow",
    Lock03_Blue: "Lock 03 Blue",
    Lock04_Blue: "Lock 04 Blue",
    Magnet: "Magnet",
    MagnifyingGlass: "Magnifying Glass",
    Medal: "Medal",
    Notebook: "Notebook",
    Phone: "Phone",
    PieChart: "Pie Chart",
    Pin: "Pin",
    PuzzlePiece: "Puzzle Piece",
    PuzzlePieces: "Puzzle Pieces",
    Roadblock: "Roadblock",
    Scissors: "Scissors",
    Shield01: "Shield 01",
    Shield02_Orange: "Shield 02 Orange",
    Shield03_Blue: "Shield 03 Blue",
    Sign_Ban01: "Sign Ban 01",
    Sign_Ban02: "Sign Ban 02",
    Sign_CheckBox01: "Sign Check Box 01",
    Sign_CheckBox02_Unchecked: "Sign Check Box 02 Unchecked",
    Sign_Checkmark01_Green: "Sign Checkmark 01 Green",
    Sign_Checkmark02_Green: "Sign Checkmark 02 Green",
    Sign_DoNotEnter: "Sign Do Not Enter",
    Sign_Error01: "Sign Error 01",
    Sign_Error02: "Sign Error 02",
    Sign_ExclamationPoint01_Red: "Sign Exclamation Point 01 Red",
    Sign_ExclamationPoint02_Orange: "Sign Exclamation Point 02 Orange",
    Sign_Help01_Green: "Sign Help 01 Green",
    Sign_Help02_Blue: "Sign Help 02 Blue",
    Sign_Information: "Sign Information",
    Sign_Null: "Sign Null",
    Sign_QuestionMark01_Blue: "Sign Question Mark 01 Blue",
    Sign_QuestionMark02_Red: "Sign Question Mark 02 Red",
    Sign_RadioButton01: "Sign Radio Button 01",
    Sign_RadioButton02_Unchecked: "Sign Radio Button 02 Unchecked",
    Sign_Warning01_Red: "Sign Warning 01 Red",
    Sign_Warning02_Orange: "Sign Warning 02 Orange",
    Sign_X01_Red: "Sign X 01 Red",
    Sign_X02_Red: "Sign X 02 Red",
    Star_Yellow: "Star Yellow",
    Wrench: "Wrench",
    Airplane_Blue: "Airplane Blue",
    Bicycle_Blue: "Bicycle Blue",
    Bus: "Bus",
    Canoe_Blue: "Canoe Blue",
    Car_Red: "Car Red",
    Helicopter_Blue: "Helicopter Blue",
    Motorcycle_Red: "Motorcycle Red",
    Pedestrian_Blue: "Pedestrian Blue",
    PersonalTransporter_Green: "Personal Transporter Green",
    Sailboat_Red: "Sailboat Red",
    Scooter_Orange: "Scooter Orange",
    Train_Red: "Train Red",
    Truck_Blue: "Truck Blue",
    
    aria_category_selector: "Image Category Options",
    filterImageGallery: "Filter image gallery"

})