/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
	fileMenu: "File",
	fileMenu_New: "New",
	fileMenu_NewDocument: "Document",
	fileMenu_NewFromTemplate: "From Template",
	fileMenu_NewDocumentfromTemplate: "Document from Template",
	fileMenu_NewPresentation: "Presentation",
	fileMenu_NewPresentationfromTemplate: "Presentation from Template",
	fileMenu_NewSpreadsheet: "Spreadsheet",
	fileMenu_NewSpreadsheetFromTemplate: "Spreadsheet from Template",
	fileMenu_Open: "Open",
	fileMenu_Import: "Import...",
//	fileMenu_Close: "Close",
	fileMenu_Discard: "Revert to Last Version",
	fileMenu_ClearTrackChange: "Remove Change Marks",
	fileMenu_SpreadsheetSettings: "Set Document Locale...",
	filemenu_revisionhistory: "Revisions",
	fileMenu_Save: "Save",
	fileMenu_SaveAs: "Save As...",
	fileMenu_PublishVersion: "Publish Version...",
	fileMenu_SubmitForReview: "Submit For Review...",
	fileMenu_CheckinVersion: "Check In...",
	fileMenu_Unlock: "Unlock",
//	fileMenu_SaveAsDraft: "as Draft",
//	fileMenu_SaveInMyDocs: "in My Documents",
//	fileMenu_SaveToSymphony: "to Lotus Symphany",
	fileMenu_DownloadAs: "Download as",
	fileMenu_PDF: "PDF",
	fileMenu_ODF: "ODF",
	fileMenu_DOC: "Microsoft Word 97- 2007 (*.doc)",
	fileMenu_ODS: "ODS",
	fileMenu_XLS: "Microsoft Excel 97-2007 (*.xls) ",
	fileMenu_ShareWith: "Share...	",
	fileMenu_ExportAsPDF: "PDF",
	fileMenu_ExportAsODF: "ODF",
	fileMenu_ExportAsPPT: "Microsoft Powerpoint 97- 2007 (*.ppt)",
//	fileMenu_WebPreview: "Web Preview",
	fileMenu_PrintToPDF: "Print to PDF...",
	fileMenu_ViewFileDetails: "View File Details...",
	fileMenu_RecentFile: "Recent Files",
	fileMenu_Open: "Open",
	fileMenu_Download: "Download",
	fileMenu_Print: "Print",
	fileMenu_Export: "Export",
	fileMenu_ExportToCSV: "CSV",
	fileMenu_PgSetup: "Page Setup...",
	
	editMenu: "Edit",
	editMenu_Undo: "Undo",
	editMenu_Redo: "Redo",
	editMenu_Cut: "Cut",
	editMenu_Copy: "Copy",
	editMenu_Paste: "Paste",
	editMenu_DeleteSlide:"Delete Slide",
	editMenu_SelectAll: "Select All",
	editMenu_Find: "Find...",
	editMenu_Replace: "Replace...",
	editMenu_FindReplace: "Find and Replace...",
	editMenu_EditLink: "Add or Edit Link",
	editMenu_DeleteSheet: "Delete Sheet...",
	editMenu_RenameSheet: "Rename Sheet...",
	editMenu_HideSheet: "Hide Sheet",
	editMenu_MoveSheet: "Move Sheet...",
	editMenu_DeleteRow: "Delete Row",
	editMenu_DeleteColumn: "Delete Column",
	editMenu_ClearCell: "Delete Content",
	
	viewMenu: "View",
	viewMenu_Master: "Master",
	viewMenu_Notifications: "Notifications",
	viewMenu_SlideSorter: "Slide Sorter",
	viewMenu_SpeakerNotes: "Speaker Notes",
	viewMenu_Toolbar_Basic: "Basic",
	viewMenu_Toolbar_Advanced: "Advanced",
	viewMenu_Toolbar_None: "None",
	viewMenu_Toolbar: "Toolbar",
	viewMenu_Statusbar:	"Statusbar",
	viewMenu_Navigator: "Navigator...",
	//viewMenu_Sidebar: "Sidebar",
	viewMenu_ShowHideIndicators: "Show Co-Editing Indicators",
	viewMenu_Assignment: "Assignment Indicators",
	viewMenu_Coediting: "Co-editing Highlights",
	viewMenu_Rulers: "Rulers",
	viewMenu_WebLayout: "Web Layout",
	viewMenu_AutomaticSpellCheck: "Check Spelling as You Type",
	viewMenu_Formulabar: "Formula Bar",
	viewMenu_moveRight: "Enter Moves Cursor to Right",
	viewMenu_showFullString: "Extend Content in Cells",
	viewMenu_Doc: "View Document",
	viewMenu_Templates: "Templates",
	viewMenu_GridLines: "Hide Grid Lines",
	viewMenu_UnsupportWarning: "Show Unsupported Feature Messages",
	viewMenu_HiddenSheets:"Hidden Sheets",
	viewMenu_FreezeRows:"Freeze Rows",
	viewMenu_FreezeColumns:"Freeze Columns",
	viewMenu_NoFrozenRows:"No Frozen Rows",
	viewmenu_NoFrozenColumns:"No Frozen Columns",
	viewMenu_FreezeXRows:"Freeze ${0} Rows",
	viewMenu_FreezeOneRow:"Freeze ${0} Row",
	viewMenu_FreezeXColumns:"Freeze ${0} Columns",
	viewMenu_FreezeOneColumn:"Freeze ${0} Column",
	viewMenu_CarriageReturn:"Formatting Marks",
	
	viewMenu_ObserverMode: 'Observer Mode',
	createMenu: "Insert",
	createMenu_NewSlide: "New Slide",
	createMenu_DuplicateSlide: "Duplicate Slide",
	createMenu_ImageFromFile: "Image...",
	createMenu_TextBox: "Text Box",
	createMenu_Shape: "Shape",
	createMenu_break: "Break",
    createMenu_RowAbove: "Row Above",
    createMenu_RowBelow: "Row Below",
    createMenu_ColumnRight: "Column Right",
    createMenu_ColumnLeft: "Column Left",
    createMenu_Sheet: "Sheet...",
    createMenu_Image: "Image...",
    createMenu_Comments: "Comment...",
    createMenu_WebLink: "Web Link...",
    createMenu_SpecialCharacter: "Special Character...",
    createMenu_Function: "Function...",
    createMenu_Fromtemplate: "Create From Template",
    
    insertMenu: "Insert",
    insertMenu_break: "Page Break",
	insertMenu_sectionbreak: "Section Break",
    insertMenu_WebLink: "Link...",
    insertMenu_SpecialCharacter: "Special Character...",
    insertMenu_HorizontalLine: "Horizontal Line",
    insertMenu_Header: "Header",
    insertMenu_Footer: "Footer",
 	insertMenu_TableOfContents: "Table of Contents",
     
    insertMenu_HeaderFooter: "Header/Footer",
    insertMenu_HF_Edit: "Edit",
    insertMenu_HF_Hide: "Hide",
    insertMenu_Endnotes: "Endnotes",
    insertMenu_RowAbove: "Row Above",
    insertMenu_PageNumber: "Page Number",
    insertMenu_PageNumberTop: "Top of Page",
    insertMenu_PageNumberBottom: "Bottom of Page",
    insertMenu_PageNumberCurr: "Current Position",    
    insertMenu_TotalPageNumber: "Page 1 of N",
    insertMenu_Date: "Date...",
    insertMenu_Time: "Time...",
    insertMenu_Fields: "Fields",
//    insertMenu_Comment: "Comment",
    insertMenu_RowBelow: "Row Below",
    insertMenu_ColumnBefore: "Column Before",
    insertMenu_ColumnAfter: "Column After",
    insertMenu_Sheet: "Sheet...",
    insertMenu_Image: "Image...",
    insertMenu_DuplicateSheet: "Duplicate Sheet",
    insertMenu_Function: "Function",
    insertMenu_FunctionSum: "SUM",
    insertMenu_FunctionAverage: "AVERAGE",
    insertMenu_FunctionCount: "COUNT",
    insertMenu_FunctionMax: "MAX",
    insertMenu_FunctionMin: "MIN",
    insertMenu_FunctionMore: "More Functions...",    
    insertMenu_NameRange:"Named Range",  
    insertMenu_NameRangeNew:"New Range...",
    insertMenu_NameRangeManage:"Manage Ranges...",
    insertMenu_Chart: "Chart...",
    
    contextMenu_InsertRowAbove: "Insert Row Above",
    contextMenu_InsertRowBelow: "Insert Row Below",
    contextMenu_InsertColumnBefore: "Insert Column Before",
    contextMenu_InsertColumnAfter: "Insert Column After",
    contextMenu_DownloadImage: "Download as Image",
    
    formatMenu: "Format",
	formatMenu_DefaultFormatting: "Default Formatting",    
    formatMenu_Template: "Template...",
    formatMenu_LineSpacing: "Line Spacing",
    formatMenu_LineSpacing1: "1",
    formatMenu_LineSpacing12: "1.2",
    formatMenu_LineSpacing15: "1.5",
    formatMenu_LineSpacing2: "2",
    formatMenu_LineSpacing25: "2.5",
    formatMenu_LineSpacing3: "3",
    formatMenu_TextProperties: "Text Properties",
    formatMenu_Bold: "Bold",
    formatMenu_Italic: "Italic",
    formatMenu_Underline: "Underline",
    formatMenu_Strikethrough: "Strikethrough",
    formatMenu_IncreaseSize: "Increase Font Size",
    formatMenu_DecreaseSize: "Decrease Font Size",
    formatMenu_ImageProperties: "Image Properties...",
    formatMenu_ChartProperties: "Chart Properties...",
    formatMenu_EditChart: "Edit Chart",
    formatMenu_InsertChart: "Insert Chart",
    formatMenu_Properties: "Properties...",
    formatMenu_Heading: "Heading",
    formatMenu_Normal: "Normal",
    formatMenu_Title : "Title",
    formatMenu_Subtitle: "Subtitle",
    formatMenu_Heading1: "Heading 1",
    formatMenu_Heading2: "Heading 2",
    formatMenu_Heading3: "Heading 3",
    formatMenu_Heading4: "Heading 4",
    formatMenu_Heading5: "Heading 5",
    formatMenu_Heading6: "Heading 6",
    formatMenu_Heading7 : "Heading 7",
    formatMenu_Heading8 : "Heading 8",
    formatMenu_Heading9 : "Heading 9",
    formatMenu_BulletedList: "Bulleted List",
    formatMenu_NumberedList: "Numbered List",
    formatMenu_OutLine:"Multilevel List",
    formatMenu_Superscript: "Superscript",
    formatMenu_Subscript: "Subscript",
    formatMenu_Align: "Align",
    formatMenu_Left: "Left",
    formatMenu_Right: "Right",
    formatMenu_Center: "Center",
    formatMenu_Justify: "Justify",
    formatMenu_LineSpacing:"Line Spacing",
    formatMenu_LineSpacing1:"1.0",
    formatMenu_LineSpacing115:"1.15",
    formatMenu_LineSpacing15:"1.5",
    formatMenu_LineSpacing2:"2.0",
    formatMenu_LineSpacing25:"2.5",
    formatMenu_LineSpacing3:"3.0",
    formatMenu_Top: "Top",
    formatMenu_Bottom: "Bottom",
    formatMenu_Middle: "Middle",
    formatMenu_Direction: "Text Direction",
    formatMenu_Rtl: "Right to Left",
    formatMenu_Ltr: "Left to Right",
    formatMenu_Auto: "Contextual",
    formatMenu_SheetDirection: "Sheet Direction",
    formatMenu_SheetRtl: "Right to Left",
    formatMenu_SheetLtr: "Left to Right",
    formatMenu_Indent: "Increase Indent",
    formatMenu_DecreaseIndent: "Decrease Indent",
    formatMenu_RowHeight: "Row Height",
    formatMenu_ColumnWidth: "Column Width",
    formatMenu_ShowRow: "Show Row",
    formatMenu_HideRow: "Hide Row",
    formatMenu_ShowColumn: "Show Column",
    formatMenu_HideColumn: "Hide Column",
    formatMenu_WrapText: "Wrap Text",
    formatMenu_Number: "Number",
    formatMenu_FontArial: "Arial",
    formatMenu_FontComicSansMS: "Comic Sans MS",
    formatMenu_FontCourierNew: "Courier New",
    formatMenu_FontGeorgia: "Georgia",
    formatMenu_FontLucidaSansUnicode: "Lucida Sans Unicode",
    formatMenu_FontTahoma: "Tahoma",
    formatMenu_FontTimesNewRoman: "Times New Roman",
    formatMenu_FontTrebuchetMS: "Trebuchet MS",
    formatMenu_FontVerdana: "Verdana",
    formatMenu_FontName: "Font",
    
	layoutMenu: "Layout",
	layoutMenu_SlideLayout: "Slide Layout...",
	layoutMenu_SlideDesign: "Master Style...",
	layoutMenu_DefaultFormatting: "Default Formatting",
	layoutMenu_Textprop_Bold: "Bold",
	layoutMenu_Textprop_Italic: "Italic",
	layoutMenu_Textprop_Underline: "Underline",
	layoutMenu_Textprop_Strikethrough: "Strikethrough",
	layoutMenu_TextProp: "Text Properties",
    LayoutMenu_RowHeight: "Row Height...",
    LayoutMenu_ColumnWidth: "Column Width...",
    LayoutMenu_ShowRow: "Show Row",
    LayoutMenu_HideRow: "Hide Row",
    LayoutMenu_RenameSheet: "Rename Sheet...",
    LayoutMenu_MoveSheet: "Move Sheet",
    
	tableMenu: "Table",
	tableMenu_Create: "Create...",
	tableMenu_CreateFromTemplate: "Create From Template",
	tableMenu_Delete: "Delete",
	tableMenu_SetTableColor:"Color Cell",
	tableMenu_CreateTable: "Create Table",
	tableMenu_Cell: "Cell",
	tableMenu_CellMergeCells: "Merge Cells",
	tableMenu_CellAlignLeft: "Align Left",
	tableMenu_CellAlignCenter: "Align Center",
	tableMenu_CellAlignRight: "Align Right",
	tableMenu_CellClearContents: "Clear Content",
	tableMenu_CellProperties: "Cell Properties...",
	tableMenu_Row: "Row",
	tableMenu_InsertRowAbove: "Insert Row Above",
	tableMenu_InsertRowBelow: "Insert Row Below",
	tableMenu_MoveRowAbove: "Move Row Up",
	tableMenu_MoveRowBelow: "Move Row Down",
	tableMenu_RowInsertRow: "Insert Row...",
	tableMenu_RowInsertRowAbove: "Insert Row Above",
	tableMenu_RowInsertRowBelow: "Insert Row Below",
	tableMenu_RowMoveRowAbove: "Move Row Above",
	tableMenu_RowMoveRowBelow: "Move Row Below",
	tableMenu_RowDelete: "Delete",
	tableMenu_InsertColumnBefore: "Insert Column Before",
	tableMenu_InsertColumnAfter: "Insert Column After",
	tableMenu_MoveColumnBefore: "Move Column Left",
	tableMenu_MoveColumnAfter: "Move Column Right",
	tableMenu_ResizeColumn: "Resize Column",
	tableMenu_ResizeColumns: "Resize Columns",
	tableMenu_MarkasCategory: "Mark as Category",
	tableMenu_ColumnInsertColumn: "Insert Column...",
	tableMenu_ColumnAddColumnBefore: "Insert Column Before",
	tableMenu_ColumnAddColumnAfter: "Insert Column After",
	tableMenu_ColumnMoveColumnAfter: "Move Column After",
	tableMenu_ColumnMoveColumnBefore: "Move Column Before",
	tableMenu_ColumnDelete: "Delete",
	tableMenu_ColumnSortAscending: "Sort Ascending",
	tableMenu_ColumnSortDescending: "Sort Descending",
	tableMenu_Column: "Column",
	tableMenu_Style: "Style",
	tableMenu_TableProperties: "Table Properties...",
	
	teamMenu: "Team",
	teamMenu_AddComment: "Add Comment",
	teamMenu_AssignCells: "Assign Cells",
	teamMenu_AssignSection: "Assign a Section",
	teamMenu_EditAssignment: "Edit Assignment",
	teamMenu_MarkSectionComplete: "Mark Section Complete",
	teamMenu_MarkAssignmentComplete: "Mark Assignment Complete",
	teamMenu_WorkPrivatelyOnSection: "Work Privately on Section",
	teamMenu_CancelPrivateWork: "Cancel Private Work",
	teamMenu_ApproveSection: "Approve Section",
	teamMenu_ApproveAssignment: "Approve Assignment",
	teamMenu_ReturnSectionForRework: "Return Section for Rework",
	teamMenu_ReturnAssignmentForRework: "Return Assignment for Rework",
	teamMenu_RemoveSectionAssignment: "Remove Section Assignment",
	teamMenu_RemoveCellAssignment: "Remove Cell Assignment",
	teamMenu_RemoveCompletedAssignments: "Remove Completed Assignments",
	teamMenu_AboutThisSection: "About This Section",
	teamMenu_AboutAssignment: "About This Assignment",
	
	presentationMenu: "Presentation",
	presentationMenu_SlideShow: "Play Slide Show",
	presentationMenu_SlideShowWithCoview: "Play Shared Slide Show",
	presentationMenu_SlideTransitions: "Apply Slide Transition...",
	presentationMenu_SlideShowFromCurrent: "Play from Current Slide",
	presentationMenu_EmptyCoviewInvites: "No Active Shared Slide Show",
	presentationMenu_CoviewInvites: "Active Shared Slide Show",
	
	dataMenu: "Data",
	dataMenu_Sort: "Sort...",
	dataMenu_SortAsc: "Sort Ascending",
	dataMenu_SortDesc: "Sort Descending",	
	dataMenu_Validity: "Validity",
	dataMenu_InstantFilter: "Instant Filter",
	
	toolsMenu: "Tools",
	toolsMenu_AutoComplete: "Autocomplete Cell Entries",
	toolsMenu_SelectDictionary: "Spell Check Dictionaries",
	toolsMenu_Dictionary_ca_CT: "Catalan",
	toolsMenu_Dictionary_cs_CZ: "Czech (Czech)",
	toolsMenu_Dictionary_da_DK: "Danish (Denmark)",
	toolsMenu_Dictionary_nl_NL: "Dutch (Netherlands)",
	toolsMenu_Dictionary_en_AU: "English (Australia)",
	toolsMenu_Dictionary_en_BT: "English (Great Britain)",
	toolsMenu_Dictionary_en_US: "English (United States)",
	toolsMenu_Dictionary_fi_FI: "Finnish (Finland)",
	toolsMenu_Dictionary_fr_FR: "French (France)",
	toolsMenu_Dictionary_fr_CA: "French (Canada)",
	toolsMenu_Dictionary_de_DE: "German (Germany)",
	toolsMenu_Dictionary_de_CH: "German (Switzerland)",
	toolsMenu_Dictionary_el_GR: "Greek (Greece)",
	toolsMenu_Dictionary_it_IT: "Italian (Italy)",
	toolsMenu_Dictionary_pl_PL: "Polish (Poland)",
	toolsMenu_Dictionary_pt_BR: "Portuguese (Brazil)",
	toolsMenu_Dictionary_pt_PT: "Portuguese (Portugal)",
	toolsMenu_Dictionary_ru_RU: "Russian (Russia)",
	toolsMenu_Dictionary_es_ES: "Spanish (Spain)",
	toolsMenu_Dictionary_sv_SE: "Swedish (Sweden)",
	toolsMenu_Dictionary_nb_NO: "Norwegian (Bokml)",
	toolsMenu_Dictionary_nn_NO: "Norwegian (Nynorsk)",	
	toolsMenu_Dictionary_he_IL: "Hebrew (Israel)",	
	toolsMenu_SpellCheck: "Run Manual Spell Check...",
	toolsMenu_Preferences: "Preferences",
	toolsMenu_Task: "Task",
	toolsMenu_Task_Assigntask: "Assign a Task",
	teamMenu_AssignSlide: "Assign Slide",
	teamMenu_AssignSlides: "Assign Slides",
	teamMenu_EditSlide: "Edit Slide Assignment",
	teamMenu_ReopenSlideAssignment: "Reopen Slide Assignment",	
	teamMenu_ReopenSlideAssignments: "Reopen Slide Assignments",	
	teamMenu_ReassignSlide: "Reassign Slide",
	teamMenu_ReassignSlides: "Reassign Slides",	
	teamMenu_MarkSlidesComplete: "Mark Slide Complete",
	teamMenu_MarkSlidesCompletes: "Mark Slides Complete",
	teamMenu_ApproveSlide: "Approve Slide",
	teamMenu_ApproveSlides: "Approve Slides",
	teamMenu_ReturnForRework: "Return Slide for Rework",
	teamMenu_ReturnForReworks: "Return Slides for Rework",
	teamMenu_RemoveAssignment: "Remove Slide Assignment",
	teamMenu_AboutThisSlide: "About This Slide",
	
	helpMenu: "Help",
	helpMenu_About: "About",
	helpMenu_Overview: "Help Contents",
	
	accel_fileMenu_Save: "Ctrl+S",
	accel_fileMenu_Save_Mac:"\u2318S",
	accel_fileMenu_Print: "Ctrl+P",	
	accel_fileMenu_Print_Mac: "\u2318P",
	accel_editMenu_SelectAll: "Ctrl+A",
	accel_editMenu_SelectAll_Mac:"\u2318A",
	accel_editMenu_Undo: "Ctrl+Z",
	accel_editMenu_Undo_Mac: "\u2318Z",
	accel_editMenu_Redo: "Ctrl+Y",
	accel_editMenu_Redo_Mac: "\u2318Y",
	accel_editMenu_Cut: "Ctrl+X",
	accel_editMenu_Cut_Mac: "\u2318X",
	accel_editMenu_Copy: "Ctrl+C",
	accel_editMenu_Copy_Mac: "\u2318C",
	accel_editMenu_Paste: "Ctrl+V",
	accel_editMenu_Paste_Mac: "\u2318V",
	accel_editMenu_Find: "Ctrl+F",
	accel_editMenu_Find_Mac: "\u2318F",
	accel_insertMenu_Link: "Ctrl+K",
	accel_insertMenu_Link_Mac: "\u2318K",
	accel_insertMenu_Header: "CTRL+SHIFT+H",
	accel_insertMenu_Header_Mac: "\u21e7\u2318H",
	accel_insertMenu_Footer: "CTRL+SHIFT+F",
	accel_insertMenu_Footer_Mac: "\u21e7\u2318F",
	accel_formatMenu_Textprop_Bold: "Ctrl+B",
	accel_formatMenu_Textprop_Bold_Mac: "\u2318B",
	accel_formatMenu_Textprop_Italic: "Ctrl+I",
	accel_formatMenu_Textprop_Italic_Mac: "\u2318I",
	accel_formatMenu_Textprop_Underline: "Ctrl+U",
	accel_formatMenu_Textprop_Underline_Mac: "\u2318U",
	accel_formatMenu_Headingprop_P:  "CTRL+SHIFT+0",
	accel_formatMenu_Headingprop_H1: "CTRL+SHIFT+1",
	accel_formatMenu_Headingprop_H2: "CTRL+SHIFT+2",
	accel_formatMenu_Headingprop_H3: "CTRL+SHIFT+3",
	accel_formatMenu_Headingprop_H4: "CTRL+SHIFT+4",
	accel_formatMenu_Headingprop_H5: "CTRL+SHIFT+5",
	accel_formatMenu_Headingprop_H6: "CTRL+SHIFT+6",
	accel_formatMenu_Superscript: "Ctrl+.",
	accel_formatMenu_Superscript_Mac: "\u2318.",
	accel_formatMenu_Subscript: "Ctrl+,",
	accel_formatMenu_Subscript_Mac: "\u2318,",
	accel_formatMenu_Left: "CTRL+SHIFT+L",
	accel_formatMenu_Left_Mac: "\u21e7\u2318L",
	accel_formatMenu_Right: "CTRL+SHIFT+R",
	accel_formatMenu_Right_Mac: "\u21e7\u2318R",
	accel_formatMenu_Center: "CTRL+SHIFT+E",
	accel_formatMenu_Center_Mac: "\u21e7\u2318E",
	accel_formatMenu_Justify: "CTRL+SHIFT+J",
	accel_formatMenu_Justify_Mac: "\u21e7\u2318J",
	accel_formatMenu_Indent: "CTRL+M",
	accel_formatMenu_Indent_Mac: "\u2318M",
	accel_formatMenu_DecreaseIndent: "CTRL+SHIFT+M",
	accel_formatMenu_DecreaseIndent_Mac: "\u21e7\u2318M",
	accel_teamMenu_AddComment: "SHIFT+F2",
	
	ctxMenuSmartTable: 'Table',
	ctxMenuTableProperties: "Table Properties",
	ctxMenuDeleteST: 'Delete',
	ctxMenuDeleteSTTable: 'Delete Table',
	ctxMenuChgSTStyle: 'Change Style',
	ctxMenuShowCaption: 'Show Caption',
	ctxMenuHideCaption: 'Hide Caption',
	ctxMenuResizeST: 'Resize',
	ctxMenuResizeColumnsST: 'Resize Columns',
	ctxMenuSTRow: 'Row',
	ctxMenuAddSTRowAbv: 'Insert Row Above',
	ctxMenuAddSTRowBlw: 'Insert Row Below',
	ctxMenuMoveSTRowUp: 'Move Row Above',
	ctxMenuMoveSTRowDown: 'Move Row Below',
	ctxMenuDelSTRow: 'Delete',
	ctxMenuSTCol: 'Column',
	ctxMenuAddSTColBfr: 'Insert Column Before',
	ctxMenuAddSTColAft: 'Insert Column After',  
	ctxMenuMoveSTColBefore: 'Move Column Before',
	ctxMenuMoveSTColAfter: 'Move Column After',
	ctxMenuDelSTCol: 'Delete',
	ctxMenuSortSTColAsc: 'Sort Ascending',
	ctxMenuSortSTColDesc: 'Sort Descending',
	ctxMenuShowAllFacets: 'Show Categories',
	ctxMenuHideAllFacets: 'Hide Categories',
	ctxMenuSTCell: 'Cell',
	ctxMenuMergeCells: 'Merge Cells',
	ctxMenuMergeDown: 'Merge with Cell Below',
	ctxMenuVerSplit: 'Split Vertically',
	ctxMenuHorSplit: 'Split Horizontally',
	ctxMenuSplitCells: 'Split Cells...',
	splitCells: 'Split Cell',
	ctxMenuAlignTextLeft: 'Align Left',
	ctxMenuAlignTextCenter: 'Align Center',
	ctxMenuAlignTextRight: 'Align Right',
	ctxMenuClearSTCellContent: 'Clear Content',
	ctxMenuMakeHeaderRow: 'Use Selected Row as Header',
	ctxMenuMakeNonHeaderRow: 'Remove Heading Style',
	ctxMenuMakeHeaderCol: 'Use Selected Column as Header',
	ctxMenuMakeNonHeaderCol: 'Remove Heading Style',
	SHEET_CONTEXT_Hide: "Hide", // hide row, column or sheet
	SHEET_CONTEXT_Show: "Show", // show row, column
	SHEET_CONTEXT_MoveSheet: "Move...", // move sheet
	SHEET_CONTEXT_InsertSheet: "Insert...", // insert sheet
	SHEET_CONTEXT_DeleteSheet: "Delete...", // delete sheet	
	SHEET_CONTEXT_DuplicateSheet: "Duplicate...", // duplicate sheet
	SHEET_CONTEXT_RenameSheet: "Rename...", // rename sheet
	
	ctxMenu_Image_WrapText:	"Wrap Text",
	ctxMenu_Image_WrapText_Inline: "In Line with Text",
	ctxMenu_Image_WrapText_Square: "Square",
	ctxMenu_Image_WrapText_TopBottom: "Top and Bottom",
	ctxMenu_Image_WrapText_Behind: "Behind Text",
	ctxMenu_Image_WrapText_InFront: "In Front of Text",
	ctxMenu_Image_WrapText_Other: "More Wrap Text",
	ctxMenu_Image_WrapText_BothSides: "Both Sides",
	ctxMenu_Image_WrapText_LeftOnly: "Left Only",
	ctxMenu_Image_WrapText_RightOnly: "Right Only",
	ctxMenu_Image_WrapText_LargestOnly: "Largest Only",

	ctxMenu_Shape_AddText: "Add Text",
	
	ctxMenu_HeaderFooter: "Header / Footer",
	ctxMenu_HeaderFooter_DiffFirst: "First Page Only",
	ctxMenu_HeaderFooter_DiffOddEven: "Different Odd and Even Pages",
	ctxMenu_HeaderFooter_LinkToPre: "Link to Previous",
	
	ctxMenu_copy: 		"Copy",
	ctxMenu_paste: 		"Paste",
	ctxMenu_delete: 	"Delete",
	ctxMenu_cut:		"Cut",
	ctxMenu_properties:	"Properties",
	ctxMenu_bringToFront: "Bring to Front",
	ctxMenu_sendToBack: "Send to Back",
	ctxMenu_arrange: "Arrange",
	ctxMenu_sendBackward: "Send Backward",
	ctxMenu_sendForward: "Send Forward",
	ctxMenu_fontStyle:	"Font Style",
	ctxMenu_selectStyle:	"Select Style",
	ctxMenu_fontSize:	"Font Size",
	ctxMenu_fontFamily:	"Font Family",
	ctxMenu_bold:		"Bold",
	ctxMenu_italic:		"Italic",
	ctxMenu_u:			"Underline",
	ctxMenu_strike:		"Strikethough",
	ctxMenu_super:		"Superscript",
	ctxMenu_sub:		"Subscript",
	ctxMenu_color:		"Color",
	ctxMenu_bgcolor:	"Background Color",
	ctxMenu_highcolor:	"Highlight Color",
	ctxMenu_restart:	"Restart List",
	ctxMenu_continue:	"Continue List",
	ctxMenu_separate:	"Separate List",
	ctxMenu_join:		"Join to Previous List",
	webClipboardInfoTitle: "Clipboard",
	webClipboardInfoOKBtn: "OK",
	webClipboardInfoCutMsg: "Your browser security settings prevent automatic copying. Use Ctrl+X on your keyboard instead.",
	webClipboardInfoCopyMsg: "Your browser security settings prevent automatic copying. Use Ctrl+C on your keyboard instead.",
	webClipboardInfoPasteMsg: "Your browser security settings prevent this editor from accessing your clipboard data. Use Ctrl+V on your keyboard instead.",
	
	clearTrackChangeConfirmMsg: "All color coding that marks changes in this document will be permanently removed. Do you want to continue?"
})

