/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
	fileMenu: "File",
	fileMenu_New: "New",
	fileMenu_NewDocument: "Document",
	fileMenu_NewDocumentfromTemplate: "Document from Template",
	fileMenu_NewPresentation: "Presentation",
	fileMenu_NewPresentationfromTemplate: "Presentation from Template",
	fileMenu_NewSpreadsheet: "Spreadsheet",
	fileMenu_Open: "Open",
//	fileMenu_Close: "Close",
	fileMenu_Discard: "Discard",
	fileMenu_Save: "Save",
	fileMenu_SaveAs: "Save As...",
//	fileMenu_SaveAsDraft: "as Draft",
//	fileMenu_SaveInMyDocs: "in My Documents",
//	fileMenu_SaveToSymphony: "to Lotus Symphany",
	fileMenu_ShareWith: "Share With...	",
	fileMenu_ExportAsPDF: "Export As PDF",
	fileMenu_WebPreview: "Web Preview",
	fileMenu_PrintPreview: "Print Preview",
	fileMenu_RecentFile: "Recent Files",
	fileMenu_Print: "Print...",
	editMenu: "Edit",
	editMenu_Undo: "Undo",
	editMenu_Redo: "Redo",
	editMenu_Cut: "Cut",
	editMenu_Copy: "Copy",
	editMenu_Paste: "Paste",
	editMenu_DeleteSlide:"Delete Slide",
	editMenu_SelectAll: "Select All",
	editMenu_Find: "Find...",
	editMenu_Replace: "Replace...",
	editMenu_DeleteSheet: "Delete Sheet",
	editMenu_DuplicateSheet: "Duplicate Sheet",
	editMenu_DeleteRow: "Delete Row",
	editMenu_DeleteColumn: "Delete Column",
	editMenu_ClearCell: "Clear Cell",
	viewMenu: "View",
	viewMenu_Master: "Master",
	viewMenu_Notifications: "Notifications",
	viewMenu_ShowHideIndicators: "Show/Hide Co-Editing Indicators",
	viewMenu_SlideSorter: "Show Slide Sorter",
	viewMenu_SpeakerNotes: "Show Speaker Notes",
	viewMenu_NextSlide: "Next Slide",
	viewMenu_PrevSlide: "Previous Slide",
	createMenu: "Create",
	createMenu_NewSlide: "New Slide",
	createMenu_DuplicateSlide: "Duplicate Slide",
	createMenu_ImageFromFile: "Graphic From File",
	createMenu_TextBox: "Text Box",
	createMenu_Task: "Task",
    formatMenu_Text_Direction: "Text Direction",
    formatMenu_Ltr: "Left to Right",
    formatMenu_Rtl: "Right to Left",  	
    formatMenu_Horizontal_Align: "Horizontal Align",
    formatMenu_Vertical_Align: "Vertical Align",
    formatMenu_Align_Top: "Top",
    formatMenu_Align_Middle: "Middle",
    formatMenu_Align_Bottom: "Bottom",
	layoutMenu: "Layout",
	layoutMenu_SlideLayout: "Slide Layout",
	layoutMenu_SlideDesign: "Master Styles",
	tableMenu: "Table",
	tableMenu_CreateTable: "Create Table",
	tableMenu_Cell: "Cell",
	tableMenu_CellAlignLeft: "Align Text Left",
	tableMenu_CellAlignCenter: "Align Text Center",
	tableMenu_CellAlignRight: "Align Text Right",
	tableMenu_CellClearContents: "Clear Contents",
	tableMenu_Row: "Row",
	tableMenu_RowAddRowAbove: "Add Row Above",
	tableMenu_RowAddRowBelow: "Add Row Below",
	tableMenu_RowMoveRowAbove: "Move Row Above",
	tableMenu_RowMoveRowBelow: "Move Row Below",
	tableMenu_RowDelete: "Delete",
	tableMenu_ColumnAddColumnBefore: "Add Column Before",
	tableMenu_ColumnAddColumnAfter: "Add Column After",
	tableMenu_ColumnMoveColumnAfter: "Move Column After",
	tableMenu_ColumnMoveColumnBefore: "Move Column Before",
	tableMenu_ColumnDelete: "Delete",
	tableMenu_ColumnSortAscending: "Sort Ascending",
	tableMenu_ColumnSortDescending: "Sort Descending",
	tableMenu_Column: "Column",
	tableMenu_Delete: "Delete",
	presentationMenu: "Presentation",
	presentationMenu_SlideShow: "Play Slide Show",
	presentationMenu_SlideShowFromCurrent: "Play from Current Slide",
	toolsMenu: "Tools",
	toolsMenu_Task: "Task",
	helpMenu: "Help",
	helpMenu_Overview: "Help Contents"
})