({	
	viewExpandedBtn: "Wyświetl mniej odpowiedzi",
	viewCollapsedBtn: "Wyświetl więcej odpowiedzi (więcej o ${0})",
	placeholderMsg: "Tutaj wpisz wiadomość",
	sure: "Czy na pewno usunąć ten komentarz?",
	exceed: "Komentarz jest zbyt długi.\n Wprowadzony komentarz ma długość większą niż maksymalnie dopuszczalna.\n Zmniejsz długość do maksymalnie ${0} znaków i kliknij opcję Dodaj.",
	remainLabelHint:"Komentarz osiągnął limit wynoszący 500 znaków.",
	tipsCommentField: "Wpisz komentarz dla wszystkich edytorów lub jednego edytora",
	tipsRespondField: "Wpisz odpowiedź dla wszystkich edytorów lub jednego edytora",	
	resolveBtn: "Rozstrzygnij",	
	replyBtn: "Odpowiedz",
	saveBtn: "Publikuj",
	deleteBtn: "Usuń",
	cancelBtn: "Anuluj",
	reopenBtn: "Otwórz ponownie",
	todayAt: "dzisiaj o ${time}",
	yesterdayAt: "wczoraj o ${time}",
	dateAt: "${date} o ${time}",
	mentions: "Wybierz użytkownika, dla którego zostanie utworzona wzmianka",
	noMentions: "Dotknięcie pustego pola powoduje zakończenie wprowadzania danych",
	nocomments: "Brak komentarzy w dokumencie ${0}.",
	
	newComments:"Nowe komentarze",
	mentiontomesomebody:"Ktoś",
	mentiontome:"Użytkownik ${0} wspominał Cię w komentarzu",
	
	newcommentsnumber:"Liczba nieprzeczytanych komentarzy",
	jawsnewcommentsnumber: "Liczba nieprzeczytanych komentarzy: ",
	jawsnactivecommentsnumber: "Liczba aktywnych komentarzy: ",
	
	activenum:"Liczba aktywnych komentarzy",
	filterDesc:"Filtruj komentarze",
	menuallcomments:"Wszystkie komentarze",
	menutome: "Do mnie",
	menubyme: "Moje",
	menuactive: "Aktywne",
	menuresolved: "Rozstrzygnięte",
	searchDesc: "Szukaj w komentarzach",
	search: "Szukaj",
	closeDesc: "Zamknij wyszukiwanie",
	clear: "Wyczyść",
	warnEnterKeywords: "Wprowadź terminy do wyszukania",
	nocommentstome: "Aktualnie w dokumencie ${0} nie ma komentarzy ani odpowiedzi ze wzmianką o mnie.",
	nocommentsbyme: "Aktualnie w dokumencie ${0} nie ma moich komentarzy ani odpowiedzi.",
	nocommentsar: "Aktualnie w dokumencie ${1} nie ma komentarzy w kategorii ${0}.",
	nosearchedcomments: "Aktualnie w dokumencie ${2} nie ma komentarzy ani odpowiedzi w kategorii ${1} zawierających łańcuch ${0}.",
	
	prevBtn: "Wstecz",
	nextBtn: "Dalej",
	mentionHint:"Wyświetlane pasujące pozycje: ${0}–${1} z ${2}",
		
	resolveFlag: "Rozstrzygnięte komentarze",
	jawsCommentHint: "${authorname} opublikował komentarz ${timestamp}",
	jawsReplyHint: "${authorname} opublikował odpowiedź ${timestamp}",
	jawsContentHint: "Treść: ${content}",
	jawsCommentStatusHint: "Status: ${status}",
	jawsCommentKeyHint: "Naciskając klawisz Enter lub klawisz spacji można przejść do dokumentu w celu wyświetlenia pełnego wątku komentarzy i rozstrzygnąć, odpowiedzieć lub usunąć komentarze.",
	jawsMentionHint: "Widget wzmianek dotyczących dokumentu. Aby wybrać użytkownika, dla którego ma zostać utworzona wzmianka, należy nacisnąć klawisz strzałki w górę lub strzałki w dół.",
	jawsMentionSelected: "Naciśnij klawisz Enter lub klawisz spacji, aby utworzyć wzmiankę.",
	commentDeletedMsg: "Bieżący komentarz został usunięty przez innego edytora.",
	commentResolvedMsg: "Bieżący komentarz został rozstrzygnięty.",
	warningCommentMsg: "Komentarze wprowadzone w programie Docs dotyczące plików (${0}) są obsługiwane tylko w trybie z połączeniem. Powiązania komentarzy zostaną usunięte, jeśli nowa wersja zostanie przesłana do edycji.",
	orphanCommentTip: "Powiązanie komentarza zostało usunięte w tej przesłanej wersji.",
	warningCommentName: "Ostrzeżenia"
})

