({	
	dlgTaskCreateTitle: "Affecter une section",  
	dlgTaskDeleteTitle: "Supprimer une section", 
	dlgTaskEditTitle: "Editer l'affectation",
	dlgTaskRewordTitle: "Transformer l'affectation",
	dlgTaskHistoryTitle: "A propos de cette section",
	dlgTaskReopenTitle: "Réouvrir l'affectation",
	dlgTaskReassignTitle: "Réaffecter la section",
	dlgTaskDeleteBtn: "Supprimer",
	creatingTaskAsTODO: "L'enregistrement de votre affectation en tant que tâche est en cours dans l'application Activités",
	creatingTaskAsTODO2: "L'affectation est en cours d'enregistrement",
	creatingTaskAsTODO3: "Les affectations sont en cours d'enregistrement",
	updatingTask: "La mise à jour de votre affectation est en cours dans l'application Activités",
	updatingTask2: "L'affectation est en cours de mise à jour",
	updatingTask3: "Les affectations sont en cours de mise à jour",
	restoringTask: "Patientez pendant que votre affectation est restaurée dans l'activité.",
	creatingFragment: "Un document privé est en cours de création pour cette section",
	updatingMaster: "Traitement en cours... La mise à jour de la section est en cours dans le document principal",
	cannotAccessActivity: "Erreur ! L'accès actuel au serveur d'activités ne permet pas d'enregistrer des affectations. Réessayez plus tard.",
	cannotAccessActivity2: "Erreur ! L'accès actuel au serveur ne permet pas d'enregistrer des affectations. Réessayez plus tard.",
	cannotAccessActivityContent: "L'accès actuel au serveur d'activités ne permet pas d'enregistrer des affectations. Réessayez plus tard.",
	cannotRecordAssignment: "L'accès actuel au serveur d'activités ne permet pas d'enregistrer des affectations. Réessayez plus tard.",
	notMemberofActivity: "L'activité ne peut enregistrer votre affectation. Vérifiez que vous avez bien été ajouté à l'activité puis réessayez.",
	cannotLoadActivity: "L'accès actuel au serveur d'activités ne permet pas de charger des affectations. Réessayez plus tard.",
	cannotLoadActivity2: "L'accès actuel au serveur ne permet pas de charger des affectations. Réessayez plus tard.",
	cannotLoadAssignment: "L'accès actuel au serveur d'activités ne permet pas de charger cette affectation. Réessayez plus tard.",
	cannotSupportSocialEdit: "Vous n'avez pas le droit de co-éditer ou d'affecter des sections.",
	cannotDeleteDraft: "Le brouillon ne peut pas être supprimé maintenant. Supprimez plus tard le fichier manuellement.",
	taskAlreadyRemoved: "La tâche de ce document a été supprimée ou vous n'êtes pas autorisé à l'éditer.",
	taskAlreadyCompleted: "La tâche est terminée ou annulée.",
	taskAlreadyReassigned: "La tâche a été réaffectée.",
	assignmentAlreadyExist: "La zone sélectionnée a déjà été affectée.",
	notAllowedEditMaster: "Vous ne pouvez pas éditer le document principal. Vérifiez si vous disposez des droits nécessaires.",
	notAllowedEditPaticipant: "Le réviseur ou le destinataire de l'affectation ne sont pas définis ou ne disposent pas d'un accès en édition. Assurez-vous que l'accès correct est bien paramétré.",
	notValidAssignment: "L'affectation n'est pas valide, certaines des propriétés d'affectation du serveur d'activités sont peut-être corrompues. Vous pouvez supprimer cette affectation en cliquant sur Actions > Supprimer l'affectation",
	disableBlockerMsg: "Vous avez un logiciel de blocage d'incrustations qui empêche la page de s'afficher correctement. Autorisez l'affichage des fenêtres en incrustation en provenance du site Web *cn.ibm.com.",
	writeDesc: "Ecrire ${0} : ${1}",
	reviewDesc: "Réviser ${0} : ${1}",
	reworkDesc: "Réécrire ${0} : ${1}",
	writeCompleteDesc: "Section ${0} écrite par ${1}",
	reviewCompleteDesc: "Section ${0} révisée par ${1}",
	workingPrivateDesc: "Travail en privé sur ${0} par ${1}",
	actions: "Actions",	
	onlyAssignerDeleteTask: "Vous ne pouvez pas supprimer cette affectation car elle n'a pas été marquée comme terminée. Seule la personne qui l'a affectée peut la supprimer.",
	actionBtnEdit: "Editer l'affectation",
	actionBtnRemove: "Supprimer l'affectation",
	actionBtnAbout: "A propos de cette section",
	actionBtnMarkComplete: "Marquer comme terminé",
	actionBtnWorkPrivately: "Travailler en privé",
	actionBtnApprove: "Approuver cette section",
	actionBtnGotoPrivate: "Aller au document privé",
	actionBtnCancelPrivate: "Annuler les modifications privées",
	actionBtnRework: "Transformation requise",
	actionBtnReopen: "Réouvrir l'affectation",
	actionBtnReassign: "Réaffecter la section",
	creating: "Création en cours...",
	deleting: "Suppression en cours...",
	updating: "Mise à jour en cours...",
	loading: "Chargement en cours...",
	restoring: "Restauration en cours...",
	lockCoeditingTask:"Un autre éditeur travaille sur la même affectation. Réessayez plus tard."
})
