({	
	dlgTaskCreateTitle: "Zaduženje sekcije",  
	dlgTaskDeleteTitle: "Uklanjanje sekcije", 
	dlgTaskEditTitle: "Uređenje dodjele",
	dlgTaskRewordTitle: "Prerađivanje zaduženja",
	dlgTaskHistoryTitle: "O ovoj sekciji",
	dlgTaskReopenTitle: "Ponovo otvaranje zaduženja",
	dlgTaskReassignTitle: "Ponovna dodjela sekcije",
	dlgTaskDeleteBtn: "Izbriši",
	creatingTaskAsTODO: "Vaše zaduženje se sprema kao stavka liste zadataka u aplikaciji Aktivnosti",
	creatingTaskAsTODO2: "Zaduženje se sprema",
	creatingTaskAsTODO3: "Dodjele se spremaju",
	updatingTask: "Vaša dodjela se ažurira u aplikaciji Aktivnosti",
	updatingTask2: "Zaduženje se ažurira",
	updatingTask3: "Dodjele se ažuriraju",
	restoringTask: "Pričekajte dok se vaša dodjela vrati u aktivnost.",
	creatingFragment: "Privatni dokument se kreira za ovu sekciju",
	updatingMaster: "U obradi... Ova sekcija se ažurira u glavnom dokumentu",
	cannotAccessActivity: "Greška! Nije moguće pristupiti serveru aktivnosti i zapisati zaduženja. Pokušajte ponovo kasnije.",
	cannotAccessActivity2: "Greška! Nije moguće pristupiti servera i zapisati zaduženja. Pokušajte ponovo kasnije.",
	cannotAccessActivityContent: "Nije moguće pristupiti do servera aktivnosti i zapisati zaduženja. Pokušajte ponovo kasnije.",
	cannotRecordAssignment: "Nije moguće pristupiti do servera aktivnosti i zapisati zaduženja. Pokušajte ponovo kasnije.",
	notMemberofActivity: "Aktivnost ne može zapisati vaše zaduženje. Provjerite, da budete sigurni, da ste dodani u aktivnost i pokušajte ponovo.",
	cannotLoadActivity: "Nije moguće pristupiti do servera aktivnosti i učitati zaduženja. Pokušajte ponovo kasnije.",
	cannotLoadActivity2: "Nije moguće pristupiti do servera i učitti zaduženja. Pokušajte ponovo kasnije.",
	cannotLoadAssignment: "Nije moguće pristupiti do servera aktivnosti i učitati ova zaduženja. Pokušajte ponovo kasnije.",
	cannotSupportSocialEdit: "Niste ovlašteni za zajedničko uređivanje ili zaduženje sekcija.",
	cannotDeleteDraft: "Skica se trenutno ne može izbrisati. Izbrišite datoteku ručno kasnije.",
	taskAlreadyRemoved: "Zadatak ovog dokumenta je uklonjen ili vam nije dozvoljeno uređivanje zadatka.",
	taskAlreadyCompleted: "Zadatak je dovršen ili otkazan.",
	taskAlreadyReassigned: "Zadatak je ponovo dodijeljen.",
	assignmentAlreadyExist: "Izabrano područje je prethodno dodijeljeno.",
	notAllowedEditMaster: "Ne možete uređivati glavni dokument. Provjerite da li imate dozvolu da to učinite.",
	notAllowedEditPaticipant: "Zaduženik ili nadzornik nije definisan ili nema pristup za uređivanje. Osigurajte da zaduženik ili nadzornik imaju odgovarajući pristup.",
	notValidAssignment: "Zaduženje nije validno, neka od osobina dodjele na serveru aktivnosti je korumpirana. Možete je ukloniti klikom na Akcije > Ukloni zaduženje",
	disableBlockerMsg: "Uključen je pop-up bloker što sprečava ispravno prikazivanje stranice.  Dozvoli prikazivanje pop-upova za Web *cn.ibm.com.",
	writeDesc: "Pisanje ${0}: ${1}",
	reviewDesc: "Pregled ${0}: ${1}",
	reworkDesc: "Prerada ${0}: ${1}",
	writeCompleteDesc: "Sekciju ${0} napisao ${1}",
	reviewCompleteDesc: "Sekciju ${0} pregledao ${1}",
	workingPrivateDesc: "Na ${0} privatno radio ${1}",
	actions: "Akcije",	
	onlyAssignerDeleteTask: "Ne možete izbrisati ovo zaduženje koja nije bila označena kao dovršeno. Izbrisati ga može samo osoba koja je i zadužila.",
	actionBtnEdit: "Uredi zaduženje",
	actionBtnRemove: "Ukloni zaduženje",
	actionBtnAbout: "O ovom sekciji",
	actionBtnMarkComplete: "Označi kao dovršeno",
	actionBtnWorkPrivately: "Radi privatno",
	actionBtnApprove: "Odobri ovu sekciju",
	actionBtnGotoPrivate: "Idi na privatni dokument",
	actionBtnCancelPrivate: "Otkaži privatni rad",
	actionBtnRework: "Potrebno je preraditi",
	actionBtnReopen: "Ponovo otvori sekciju",
	actionBtnReassign: "Ponovo dodijeli sekciju",
	creating: "Kreiranje...",
	deleting: "Brisanje...",
	updating: "Ažuriranje...",
	loading: "Učitavanje...",
	restoring: "Vraćanje...",
	lockCoeditingTask:"Drugi editor radi na zaduženju. Pokušajte ponovo kasnije."
})

