({
	ORIENTATION_LABEL: "Orientering",
	PORTRAIT: "Stående",
	LANDSCAPE: "Liggande",
	PAGE_LABEL: "Sidordning",
	PAGE_TYPE1: "Uppifrån och ned, sedan åt höger",
	PAGE_TYPE2: "Från vänster till höger, sedan nedåt",
	DISPLAY_OPTION_LABEL: "Visningsalternativ",
	HEADER: "Sidhuvud",
	FOOTER: "Sidfot",
	GRIDLINE: "Rutnätslinjer",
	MARGINS_LABEL: "Marginaler",
	TOP: "Övre:",
	BOTTOM: "Nedre:",
	LEFT: "Vänster:",
	RIGHT: "Höger: ",
	PAPER_FORMAT_LABEL: "Pappersformat",
	PAPER_SIZE_LABEL: "Format:",
	HEIGHT: "Höjd:",
	WIDTH: "Bredd:",
	
	TOOLTIP1:"Skriver ut så många rader som ryms på sidans längd tills det inte finns några fler kolumner i arket, därefter fortsätter utskriften med nästa grupp av rader.",
	TOOLTIP2:"Skriver ut så många kolumner som ryms på sidans bredd tills det inte finns några fler rader i arket, därefter fortsätter utskriften med nästa grupp av kolumner.",
	CM_LABEL: " cm",
	LETTER: "Letter",
	LEGAL: "Legal",
	TABLOID: "Tabloid",
	USER: "Användare",
	SIZE1: "Env. #6 3/4",
	SIZE2: "Env. Monarch",
	SIZE3: "Env. #9",
	SIZE4: "Env. #10",
	SIZE5: "Env. #11",
	SIZE6: "Env. #12",
	SIZE7: "16 kai",
	SIZE8: "32 kai",
	SIZE9: "32 kai"
})
	
