({
	COLUMN: "Колона",
	CLUSTERED_COLUMN: "Групирани колони",
	STACKED_COLUMN: "Напластени колони",
	BAR:"Лента",
	CLUSTERED_BAR:"Групирана лента",
	STACKED_BAR: "Напластена лента",
	PIE:"Пита",
	SLICE: "Исечок",
	AREA: "Област",
	STACKED_AREA: "Напластена област",
	LINE: "Линија",
	STACKED_LINE: "Напластена линија",
	MAKER_LINE: "Линија со обележувачи",
	STACKED_MARKER_LINE: "Напластена линија со обележувачи",
	SCATTER: "Распрсни",
	SCATTER_MARKER_ONLY: "Распрснато само со обележувачи",
	SCATTER_MARKER_LINE_S: "Распрснато со заоблени линии и обележувачи",
	SCATTER_LINE_S: "Распрснато со заоблени линии", 
	SCATTER_MARKER_LINE_X: "Распрснато со прави линии и обележувачи",
	SCATTER_LINE_X: "Распрснато со прави линии",
	ERROR_INVALID_RANGE:"Неважечки опсег на податоци",
	TOO_MANY_POINTS: "Не може да се создаде графикон што има повеќе од ${0} податочни точки",
	CHART_TYPES:"Тип на графикон",
	DATA:"Податоци",
	DATA_RANGE:"Опсег на податоци",
	IN_ROWS:"Податочни серии во редови",
	IN_COLUMNS:"Податочни серии во колони",
	AUTO:"Автоматски"
})

