/* ***************************************************************** */
/*                                                                   */
/* HCL Confidential                                                  */
/*                                                                   */
/* OCO Source Materials                                              */
/*                                                                   */
/* Copyright HCL Technologies Limited 2020                           */
/*                                                                   */
/* The source code for this program is not published or otherwise    */
/* divested of its trade secrets, irrespective of what has been      */
/* deposited with the U.S. Copyright Office.                         */
/*                                                                   */
/* ***************************************************************** */

({
	service_unavailable_title: "サービスを使用できません。",
	service_unavailable_content: "${productName} サービスを使用できません。 現時点では要求を処理できません。 後でやり直すか、システム管理者にお問い合わせください。",
	access_denied_title: "アクセスが拒否されました。",
	viewaccess_denied_content: "このファイルを表示するための許可がありません。 ファイルが公開されているか、ファイルを共有している必要があります。",
	editaccess_denied_content: "${productName} を使用するライセンスがないか、このファイルを編集するための許可がありません。 ファイルが自分に共有されていて、アクセス・レベルが編集者に設定されている必要があります。 ファイルが他の編集者によってロックされている可能性があります。",
	doc_notfound_title: "文書が見つかりません。",
	doc_notfound_content: "アクセス対象の文書は削除または移動されました。 リンクが正しいことを確認してください。",
	repository_out_of_space_title: "スペースが不足しています",
	repository_out_of_space_content: "ファイル・サイズの割り当て量に到達したため、${0} を公開できません。 他のファイルをごみ箱に移動して削除することで、自分の割り当て量を減らしてください。",
	fileconnect_denied_title: "接続が拒否されました。",
	fileconnect_denied_content: "${productName} がファイル・リポジトリーに接続できません。 後でやり直すか、システム管理者にお問い合わせください。",
	unscanned_document_title: "ウィルス・スキャンを完了しています",
	unscanned_document_content: "HCL Connections にアップロードされるファイルは自動的にスキャンされます。 スキャンが完了し次第、このファイルを編集できるようになります。",
	malicious_document_title: "悪意のあるコンテンツを含むファイル",
	malicious_document_content: "HCL Connections でスキャン中にウィルスが検出されたため、このファイルを編集できません。",
	convservice_unavailable_title: "変換サービスを使用できません。",
	convservice_unavailable_content: "${productName} 変換サービスを使用できません。 現時点では要求を処理できません。 後でやり直すか、システム管理者にお問い合わせください。",
	doc_toolarge_title: "ファイルが大きすぎます。",
	doc_toolarge_content: "アクセスしようとしている文書が大きすぎます。",
	doc_toolarge_content2: "ファイルにアクセスできません。 以下の理由が考えられます:",
	doc_toolarge_content3: "ファイルのサイズが ${0} KB を超えているため、ファイルを表示できません。 ファイルをダウンロードして編集することはできます。 ファイルに高解像度のイメージが含まれている場合、より低い解像度のイメージに置き換えるとファイル・サイズを小さくすることができます。",
	doc_toolarge_content4: "ファイルが大きすぎてここでは表示できません。ただし、タイトル・バーの「ダウンロード」ボタンをクリックすることで開くことができます。",
	doc_toolarge_content_mobile: "ファイルを開くことができません。 モバイル・デバイスでは、${0} KB を超えるファイル・サイズを使用できません。",
	sheet_toolarge_content: "スプレッドシートのサイズが ${0} KB を超えています。",
	sheet_toolarge_content2: "スプレッドシートの 1 シートの行数が ${0} 行を超えています。",
	sheet_toolarge_content5: "スプレッドシートの 1 シートの列数が ${0} 列を超えています。",
	sheet_toolarge_content3: "スプレッドシートのセル数が ${0} 個を超えています。",
	sheet_toolarge_content4: "スプレッドシートの式数が ${0} 個を超えています。",
	text_toolarge_content: "文書のサイズが ${0} KB を超えています。",
	text_toolarge_content2:"文書のページ数が ${0} ページを超えています。",
	text_toolarge_content3:"文書のテキスト・サイズが ${0} KB を超えています。",
	pres_toolarge_content: "プレゼンテーションのサイズが ${0} KB を超えているため、プレゼンテーションにアクセスできません。 プレゼンテーションに高解像度のイメージが含まれている場合、より低い解像度のイメージに置き換えるとプレゼンテーションのサイズを小さくすることができます。",
	pres_toolarge_content2: "プレゼンテーションに ${0} を超えるページが含まれているため、プレゼンテーションにアクセスできません。",
	pres_toolarge_content3: "プレゼンテーションに ${0} を超えるオブジェクトが含まれているため、プレゼンテーションにアクセスできません。",
	pres_toolarge_content2_mobile: "プレゼンテーションを開くことができません。モバイル・デバイス上で、ページ数が ${0} ページを超えているためです。",
	pres_toolarge_content3_mobile: "プレゼンテーションを開くことができません。モバイル・デバイス上で、オブジェクト数が ${0} 個を超えているためです。",
	sheet_view_toolarge_content1_mobile: "スプレッドシートを表示できません。モバイル・デバイス上で、行数が ${0} 行を超えているためです。",
	sheet_view_toolarge_content2_mobile: "スプレッドシートを表示できません。モバイル・デバイス上で、列数が ${0} 列を超えているためです。",
	sheet_view_toolarge_content3_mobile: "スプレッドシートを表示できません。モバイル・デバイス上で、行数が ${0} 行を、列数が ${1} 列を超えているためです。",
	conversion_timeout_title: "文書変換がタイムアウトになりました。",
	conversion_timeout_content: "現時点では、文書の変換に時間がかかりすぎています。 後でやり直してください。",
	invalid_docformat_title: "文書を開くことができません",
	invalid_docformat_content: "文書の拡張子は有効ですが、内容を読み取ることができません。破損しているか、暗号化されているためです。",
	template_extension_conent_mismatch: "ソース・ファイルの拡張子により、誤ってテンプレートとして識別されています。 ファイルは実際には .${0} の形式です。 有効なテンプレートを使用して作成するか、このファイルを .${0} を拡張子とした異なる名前で保存してください。",
	invalid_docformat_title2: "このファイルを ${productName} にインポートすることはできません。",
	invalid_docformat_content2: "現在の ${productName} ではサポートされない内容がこのファイルに含まれています。 このファイルをインポートすることはできません。",
	invalid_doctype_title: "この文書タイプはサポートされていません。",
	invalid_doctype_content: "この文書タイプは、${productName} で現在サポートされていません。",
	unsupported_browser_title: "ご使用のブラウザーでは、一部の機能がサポートされていません",
	malformed_request_title: "要求の形式に誤りがあります。",
	malformed_request_content: "URL とパラメーターが正しいことを確認してください。",
	storageserver_error_title: "このストレージサーバーを使用できません。",
	storageserver_error_content: "このサーバーは現在使用できません。 現時点では要求を処理できません。 後でやり直すか、システム管理者にお問い合わせください。",
	document_already_opened_title: "文書は既に開いています",
	document_already_opened_content:"この文書は既にブラウザーによって開かれています。",
	toomany_documents_opened_inone_browser_title: "この文書を開くことはできません",
	toomany_documents_opened_inone_browser_content:"同時に開くことができる ${productName} のファイル数は 5 つのみです。 他の文書を閉じてから、この文書を再度開いてみてください。",
	document_max_session_exceeded_title:"サービスを使用できません。",
	document_max_session_exceeded_content:"サーバー上の文書を編集しているユーザーが多すぎます。要求を続行できません。 後でやり直してください。",
	kickout_user_content: "この文書は、自分のコンピューターの別のウィンドウで既に開いています。 文書の編集を続行する場合は、もう 1 つのウィンドウに戻ってください。",
	return_to_files: "ファイルに戻る",
	return_to_library: "ライブラリーに戻る",
	return_to_icn: "コンテンツ・ナビゲーターに戻る",
	document_already_open: "文書が既に開いています",
	cannotedit_noentitled_title: "このファイルを共同編集することはできません",
	cannotedit_noentitled_content1: "以下のユーザーが現在このファイルを編集しています:",
	cannotedit_noentitled_content2: "他のユーザーがこのファイルを編集している間は、このファイルの編集は許可されません。後でこのファイルを編集してみてください。",
	cannotedit_noentitled_content3: "以下のユーザーが現在このファイルを編集しています:",
	cannotedit_noentitled_content4: "編集しているユーザーが共同編集の権限を持たないため、あなたがこの編集セッションに参加することはできません。後でこのファイルを編集してみてください。",
	toomany_coeditors_title: "ユーザーが多すぎます",
	toomany_coeditors_content: "現在この文書を編集しているユーザーが多すぎます。{0} 人のユーザーのみが、同時にこの文書で作業できます。",
	encrypted_pptdoc_title:"暗号化されたファイル",
	encrypted_pptdoc_content:"ファイルはパスワード保護されています。暗号化解除しないかぎり、${productName} で編集できません。",
	server_busy_title:"サーバーがビジーです",
	server_busy_content:"しばらく待機し、後でやり直してください。",
	document_encrypt_title:"暗号化された文書はサポートされていません",
	document_encrypt_content:"このファイルはファイル・リポジトリーで暗号化されています。 セキュリティーが考慮されたため、${productName} で直接編集できませんでした。",
	edit_locked_file: "このファイルは他の編集者によってロックされているため、編集できません。",
	publish_locked_file: "このファイルはロックされているため、新規バージョンとして公開できません。ただし、作業中のコンテンツは自動的にドラフトに保存されます。",
	join_locked_file_session: "このファイルは、他のユーザーによってロックされているため、共同編集セッションに参加できません。",
	no_need_to_convert_title:"変換する必要はありません",
	no_need_to_convert_content:"変換しようとしているファイルは、既に目的のファイル形式になっています。 直接ダウンロードしてください。",
	warning_icon: "「警告」アイコン",
	//html viewer error message
	incorrect_web_address_title:"正しくない Web アドレスです。",
	incorrect_web_address_content:"Web アドレスが正しくありません。Web アドレスを入力し直してください。",
	unexpecified_conversion_error_title:"エラーが特定できません。",
	unexpecified_conversion_error_content:"サーバーが原因不明のエラーを返しました。",
	encrypted_conversion_error_title:"暗号化された文書はサポートされていません。",
	encrypted_conversion_error_content:"ファイルはパスワード保護されています。 このファイルをビューアーで表示するには、まずファイルの号化が解除されていることを確認してください。",
	service_busy_title:"文書を開くのに失敗しました",
	service_busy_content:"表示しようとしているファイルを開くことができませんでした。サーバーがビジーであるか、使用できなかった可能性が考えられます。 後でやり直すか、管理者にお問い合わせください。",
	empty_doc_title: "文書が空です。",
	empty_doc_content: "文書に内容が含まれていることを確認して、やり直してください。",
	corrupted_doc_title: "ファイルを開くことができません。",
	corrupted_doc_content: "ファイルに例えばマクロなどのサポートされない内容が含まれています。そのため、このアプリケーションで表示することができません。",
	draft_storage_error_title: "文書を開けません。",
	draft_storage_error_content: "コンテンツ壊れているため、ロードできません。管理者にサポートを依頼してください。",
	unexpected_code_title: "${productName} サーバーが予期しないコードを返しました。",
	unexpected_code_content: "${productName} サーバーが予期しないコードを返しました。",
	request_time_out_title: "文書のロードがタイムアウトになりました。",
	request_time_out_content: "この文書のロードに時間がかかりすぎています。 後でやり直してください。",
	problem_id_msg_title: "この問題を管理者に報告してください。 ",
	problem_id_msg_show: "クリックして詳細を表示",
	problem_id_msg_hide: "クリックして非表示"
})
