({
		SAVE: "Запазване",
		UNDO:"Отмяна",
		REDO:"Връщане",
		INSERTROW:"Вмъкване на ред",
		DELETEROW:"Изтриване на ред",
		INSERTCOLUMN:"Вмъкване на колона",
		DELETECOLUMN:"Изтриване на колона",
		FONTSIZE:"Размер на шрифт",
		FONTCOLOR:"Цвят на шрифт",
		BOLD:"Получер",
		ITALIC:"Курсив",
		UNDERLINE:"Подчертаване",
		STRIKETHROUGH:"Зачеркване",
		CURRENCYTIP:"Форматиране като валута",
		PERCENTLABEL:"%",
		PERCENTTIP:"Форматиране като процент",
		NUMBERFORMAT:"Форматиране на число",
		ALIGNLEFT:"Подравняване наляво",
		ALIGNCENTER:"Подравняване в център",
		ALIGNRIGHT:"Подравняване надясно",
		SETCELLBORDER:"Задаване на граница на клетка",
		BACKGROUNDCOLOR:"Цвят на фон",
		TASK:"Задаване на раздел",
		COMMENTS:"Добавяне на коментар",
		SUBMIT:"Подаване",
		MERGECELL: "Обединяване или разделяне на клетки",
		QUICKFORMULA: "Бърза формула",
		WRAPTEXT: "Пренасяне на текст",
		EIGHT:"8pt",
		NINE:"9pt",
		TEN:"10pt",
		ELEVEN:"11pt",
		TWELVE:"12pt",
		FOURTEEN:"14pt",
		SIXTEEN:"16pt",
		EIGHTEEN:"18pt",
		TWENTY:"20pt",
		TWENTYTWO:"22pt",
		TWENTYFOUR:"24pt",
		NUMBER:"Число",
		CURRENCY:"Валута",
		PERCENT:"Процент",
		DATE:"Дата",
		TIME:"Час",
		DATETIME: "ДатаЧас",
		MORECURRENCY:"Още валути",
		MOREDATE:"Още формули",
		
		
		CAD: "канадски долар",
		USD: "долар",
		EUR: "евро",
		CHF: "швейцарски франк",
		HKD: "хонгконгски долар",
		DKK: "крона",
		LTL: "литас",
		PHP: "песо",
		BRL: "реал",
		RUR: "рубла",
		GBP: "паунд",
		NLG: "гулден", // Netherlands
		TWD: "нова тайвански долар",
		THB: "бат", // Thailand
		ITL: "лира", // Turkey
		BGL: "лев", // Uzbekistan
		VND: "донг", // Vietnam
		KRW: "вон",	// Korean 
		CNY: "юан", // RMB
		JPY: "йена" // Japan Yen
})
