({
	ORIENTATION_LABEL: "Orientamento",
	PORTRAIT: "Verticale",
	LANDSCAPE: "Orizzontale",
	HEADER: "Intestazione",
	FOOTER: "Piè di pagina",
	MARGINS_LABEL: "Margini",
	TOP: "Superiore:",
	BOTTOM: "Inferiore:",
	LEFT: "Sinistro:",
	RIGHT: "Destro:",
	PAPER_FORMAT_LABEL: "Formato carta",
	PAPER_SIZE_LABEL: "Dimensione carta:",
	HEIGHT: "Altezza:",
	WIDTH: "Larghezza:",
	HEIGHT_DESC:"Altezza carta, in centimetri",
	HEIGHT_DESC2:"Altezza carta, in pollici",
	WIDTH_DESC:"Larghezza carta, in centimetri",
	WIDTH_DESC2:"Larghezza carta, in pollici",
	BOTTOM_DESC:"Margine inferiore, in centimetri",
	BOTTOM_DESC2:"Margine inferiore, in pollici",
	TOP_DESC:"Margine superiore, in centimetri",
	TOP_DESC2:"Margine superiore, in pollici",
	LEFT_DESC:"Margine sinistro, in centimetri",
	LEFT_DESC2:"Margine sinistro, in pollici",
	RIGHT_DESC:"Margine destro, in centimetri",
	RIGHT_DESC2:"Margine destro, in pollici",
	CM_LABEL: "cm",
	LETTER: "Letter",
	LEGAL: "Legal",
	TABLOID: "Tabloid",
	USER: "Utente",
	SIZE1: "Busta #6 3/4",
	SIZE2: "Busta Monarch",
	SIZE3: "Busta #9",
	SIZE4: "Busta #10",
	SIZE5: "Busta #11",
	SIZE6: "Busta #12",
	SIZE7: "16 kai",
	SIZE8: "32 kai",
	SIZE9: "32 kai grande",
	INVALID_MSG: "L'input non è valido ed è stato corretto automaticamente. Inserire un altro valore per ottenere un risultato differente."
})
	

