({
	delete_general: "Sil",
	order: "Sırala",
	align_text: "Metni Hizala",
	align_slide: "Slayt İçinde Hizala",
	align_objects: "Seçilen Nesneleri Hizala",
	zoom: "Yakınlaştır/Uzaklaştır",
	zoom_fit: "Pencereye Sığdır",
	insert_link: "Bağlantı Ekle",
	add_link: "Bağlantı Ekle",
	open_link: "Bağlantıyı Aç",
	edit_link: "Bağlantıyı Düzenle",
	remove_link: "Bağlantıyı Kaldır",
	insert_link_menu: "Bağlantı",
	invalid_url: "URL açılamıyor. Lütfen URL'nin doğru olup olmadığını kontrol edin ya da tarayıcı için açılır pencereleri engelleme ayarını kontrol edin. ",
	dnd_canceled_on_slide_event: "Başka bir düzenleyici yakın zamanda sunumu değiştirdiği için slayt taşınamıyor. Daha sonra yeniden deneyin.",
	rotate: "Döndür",
	flipX: "Yatay Olarak Çevir",
	flipY: "Dikey Olarak Çevir",
	rotate_right: "Saat Yönünde 90&#x00B0 Döndür",
	rotate_left: "Saatin Tersi Yönde 90&#x00B0 Döndür",
	color_set_fill: "Dolgu Rengini Ayarla",
	color_nofill: "Dolgu Yok",
	color_nobackground: "Arka Plan Yok",
	color_auto: "Otomatik",
	color_default: "Varsayılan",
	color_transparent: "Saydam",
	
	objects_distribute: "Dağıt",
	objects_distribute_v: "Dikey Olarak",
	objects_distribute_h: "Yatay Olarak",
	
	link_subject: "Konu:",
	link_text: "Görüntülenecek metin:",
	link_mailto: "E-postayı Aç",
	link_goto: "Bağlantıyı Aç",
	link_done: "Bitti",
	link_remove: "Kaldır",
	link_website: "Web sitesi",
	link_email: "E-posta",
	link_slide: "Slayt",
	link_slide_placeholder: "Sayı seçin ya da girin",
	link_slide_placeholder_deleted: "Bağlantılı Slayt Silindi",
	link_slide_next: "Sonraki Slayt",
	link_slide_prev: "Önceki Slayt",
	link_slide_first: "İlk Slayt",
	link_slide_last: "Son Slayt",
	link_slide_number: "Slayt ${0}",
	link_not_support: "Desteklenmeyen bağlantı tipi",
	link_acc_input: "Bağlantı adresini girin",
	link_acc_mail_input: "Posta adresini girin",
	

	// Jaws Support
	acc_blank: "boş",// when selection is nothing but space char and empty paragraph
	acc_selected: " seçildi",
	acc_showed: " gösterildi",
	acc_inTable: " tablo satırı ${0} sütunu ${1} ",
	acc_titleSelected: "başlık seçildi",
	acc_subtitleSelected: "altbaşlık seçildi",
	acc_outlineSelected: "anahat seçildi",
	acc_notesSelected: "konuşma notları seçildi",
	acc_imageSelected: "grafik seçildi",
	acc_shapeSelected: "şekil seçildi",
	acc_rotated: " ${0} derece döndürüldü",
	acc_tableSelected: "tablo seçildi",
	acc_textboxSelected: "metin kutusu seçildi",
	acc_enterEdit: " düzenleme için enter tuşuna basın",
	acc_locked_by: " ${0} adlı kullanıcı tarafından kilitlenen",
	acc_slide_used_by: " ${0} adlı kullanıcı tarafından kullanılan",
	ACC_TABLE_TABLESIZE: "${0} satır, ${1} sütun seçtiniz",
	ACC_TABLE_MAXSIZE: " Desteklenen en büyük tablo boyutu 8*8'dir.",
	ACC_EditorMode: "düzenleyici düzenleme modu",
	ACC_EndEditorMode: "düzenleyici düzenleme modunu sona erdir",
	ACC_Table_new_row: "Yeni bir satır eklendi",
	ACC_Table_new_column: "Yeni bir sütun eklendi",
	Acc_column: "sütun  ${0}",
	acc_slide: "slayt ${0}",
	acc_editor: "${0} ile düzenle",
	Plain: "Düz",
	BlueStyle: "Mavi stil",
	RedTint: "Kırmızı ton",
	BlueHeader: "Mavi üstbilgi",
	DarkGrayHF: "Koyu gri üstbilgi/altbilgi",
	LightGrayRows: "Açık gri satırlar",
	DarkGrayRows: "Koyu gri satırlar",
	BlueTint: "Mavi ton",
	RedHeader: "Kırmızı üstbilgi",
	GreenHF: "Yeşil üstbilgi/altbilgi",
	PlainRows: "Düz satırlar",
	GrayTint: "Gri ton",
	GreenTint: "Yeşil ton",
	GreenHeader: "Yeşil üstbilgi",
	RedHF: "Kırmızı üstbilgi/altbilgi",
	GreenStyle: "Yeşil stil",
	PurpleTint: "Mor ton",
	BlackHeader: "Siyah üstbilgi",
	PurpleHeader: "Mor üstbilgi",
	LightBlueHF: "Açık mavi üstbilgi/altbilgi",
	
    formatMenu_LineSpacing: "Satır Aralığı",
	linespaceboxTitle:"Özel Aralık",
	linespacelineTitle:"Satır:",
	linespacenoticeContent :"Satır Aralığı",
    formatMenu_LineSpacing_Customize: "Özel...",
    formatMenu_LineSpacing_CustomValue:"Özel: ${0}",
    lineSpaceWarning:"0 ile 10 arası bir sayı girin",
    
    set_transparency_menu: "Resim Opaklığı",
    opacity_percent_value: "${0}%",
    opacity_title: "Opaklık",
    
    increaseLineWidthTip: "Çizgi Kalınlığını Artır",
	decreaseLineWidthTip : "Çizgi Kalınlığını Azalt",
    setBorderStyleTip:"Çizgi Stilini Ayarla",
    line_width_title: "Çizgi kalınlığı",
    line_end_title: "Çizgi uç noktaları",
    line_dash_title: "Çizgi deseni",
    line_dash_type1: "İçi Dolu",
    line_dash_type2: "Kara noktalar",
    line_dash_type3: "Kısa çizgiler",
    line_dash_type4: "Yuvarlak noktalar",
    line_dash_type5: "Kısa çizgi ve noktalar",
    line_dash_type6: "Uzun çizgiler",
    line_endpoints_type1: "Hiçbiri",
    line_endpoints_type2: "Basit sağ ok",
	line_endpoints_type3: "Basit sol ok",
	line_endpoints_type4: "Basit çift uçlu ok",
	line_endpoints_type5: "Dolgulu sağ ok",
	line_endpoints_type6: "Dolgulu sol ok",
    line_endpoints_type7: "Dolgulu çift uçlu ok",
    line_endpoints_type8: "Dolgulu daire ve ok",
	line_endpoints_type9: "Dolgulu baklava ve ok",
	line_endpoints_type10: "Dolgulu baklavalar",
    line_endpoints_type11: "Dolgulu daireler"
})

