({
	labelPrintConfig: "A legjobb nyomtatási eredmények eléréséhez, adja meg a böngésző lapbeállításai közt az alábbi értékeket:",
	labelConfigPageSize: "Oldalméret: ${0}",
	labelConfigOrientation: "Tájolás: ${0}",
	labelConfigHeader: "üFejléc: üres",
	labelConfigFooter: "üLábléc: üres",
	labelConfigMargins: "Margók: ",
	labelConfigMarginTop: "Felső: ${0}${1}",
	labelConfigMarginBottom: "Alsó: ${0}${1}",
	labelConfigMarginLeft: "Bal: ${0}${1}",
	labelConfigMarginRight: "Jobb: ${0}${1}",
	labelPrintContinue: "A böngészőbeállítások megadása után kattintson az OK gombra a fájl nyomtatásának folytatásához.",
	labelMm: "milliméter",
	labelInch: "hüvelyk",
	labelPortrait: "álló",
	labelPageA4: "A4",
	labelLetter: "Letter",
	labelLandscape: "fekvő",
	titlePrintConfig: "Nyomtatási beállítások",
	titlePrepare: "Előkészítés nyomtatásra",
	msgPrepare: "A fájl nyomtatásra való előkészítése zajlik. Lehet, hogy ez az előkészítés hosszabb ideig tart.",
	errPrepare: "Hiba történt az adatok előkészítése közben.\nMegpróbálja újra?",
	titleErr: "Hiba",
	btnRetry: "Újrapróbálkozás"
})
