({
	delete_general: "מחיקה",
	order: "סדר",
	align_text: "יישור תמליל",
	align_slide: "יישור בשקופית",
	align_objects: "יישור האובייקטים שנבחרו",
	zoom: "זום",
	zoom_fit: "התאמה לחלון",
	insert_link: "הוספת קישור",
	add_link: "הוספת קישור",
	open_link: "פתיחת הקישור",
	edit_link: "עריכת קישור",
	remove_link: "סילוק קישור",
	insert_link_menu: "קישור",
	invalid_url: "לא ניתן לפתוח את ה- URL. אנא בדקו האם ה-URL נכון או בדקו את הגדרות חסימת החלונות הקופצים של הדפדפן שלכם. ",
	dnd_canceled_on_slide_event: "לא ניתן להעביר את השקופית מפני שעורך אחר שינה את המצב לאחרונה. נסו שוב מאוחר יותר.‏",
	rotate: "סיבוב",
	flipX: "היפוך אופקי",
	flipY: "היפוך אנכי",
	rotate_right: "סיבוב בכיוון השעון 90&#x00B0",
	rotate_left: "סיבוב נגד כיוון השעון 90&#x00B0",
	color_set_fill: "הגדרת צבע מילוי",
	color_nofill: "ללא מילוי",
	color_nobackground: "ללא רקע",
	color_auto: "אוטומטי",
	color_default: "ברירת מחדל",
	color_transparent: "שקוף",
	
	objects_distribute: "פיזור",
	objects_distribute_v: "אנכי",
	objects_distribute_h: "אופקי",
	
	link_subject: "נושא:",
	link_text: "תמליל להצגה:",
	link_mailto: "פתיחת דואל",
	link_goto: "פתיחת הקישור",
	link_done: "סיום",
	link_remove: "סילוק",
	link_website: "אתר רשת",
	link_email: "דואל",
	link_slide: "שקופית",
	link_slide_placeholder: "בחרו או הקלידו מספר",
	link_slide_placeholder_deleted: "השקופית המקושרת נמחקה",
	link_slide_next: "השקופית הבאה",
	link_slide_prev: "השקופית הקודמת",
	link_slide_first: "שקופית ראשונה",
	link_slide_last: "שקופית אחרונה",
	link_slide_number: "שקופית ${0}",
	link_not_support: "סוג קישור לא נתמך",
	link_acc_input: "ציון כתובת קישור",
	link_acc_mail_input: "ציון כתובת דואל",
	

	// Jaws Support
	acc_blank: "ריק",// when selection is nothing but space char and empty paragraph
	acc_selected: " נבחר",
	acc_showed: " הוצג",
	acc_inTable: " בטבלה שורה ${0} עמודה ${1} ",
	acc_titleSelected: "נבחרה כותרת",
	acc_subtitleSelected: "נבחרה תת-כותרת",
	acc_outlineSelected: "נבחר מתאר",
	acc_notesSelected: "נבחרו הערות דובר",
	acc_imageSelected: "נבחרה גרפיקה",
	acc_shapeSelected: "נבחרה צורה",
	acc_rotated: " סובב ב-${0} מעלות",
	acc_tableSelected: "נבחרה טבלה",
	acc_textboxSelected: "נבחרה תיבת תמליל",
	acc_enterEdit: " לחצו על Enter כדי לערוך",
	acc_locked_by: " שננעל על ידי המשתמש ${0}",
	acc_slide_used_by: " שנמצא בשימוש המשתמש ${0}",
	ACC_TABLE_TABLESIZE: "בחרתם ${0} שורות, ${1} עמודות",
	ACC_TABLE_MAXSIZE: " גודל הטבלה המרבי הנתמך הוא 8*8",
	ACC_EditorMode: "מצב עריכה של העורך",
	ACC_EndEditorMode: "סיום מצב עריכה של העורך",
	ACC_Table_new_row: "שורה חדשה נוספה",
	ACC_Table_new_column: "עמודה חדשה נוספה",
	Acc_column: "עמודה ${0}",
	acc_slide: "שקופית ${0}",
	acc_editor: "עריכה על ידי ${0}",
	Plain: "פשוט",
	BlueStyle: "סגנון כחול",
	RedTint: "גוון אדום",
	BlueHeader: "כותרת עליונה כחולה",
	DarkGrayHF: "כותרת עליונה/תחתונה באפור כהה",
	LightGrayRows: "שורות אפורות בהירות",
	DarkGrayRows: "שורות אפורות כהות",
	BlueTint: "גוון כחול",
	RedHeader: "כותרת עליונה אדומה",
	GreenHF: "כותרת עליונה/תחתונה ירוקה",
	PlainRows: "שורות פשוטות",
	GrayTint: "גוון אפור",
	GreenTint: "גוון ירוק",
	GreenHeader: "כותרת עליונה ירוקה",
	RedHF: "כותרת עליונה/תחתונה אדומה",
	GreenStyle: "סגנון ירוק",
	PurpleTint: "גוון סגול",
	BlackHeader: "כותרת עליונה שחורה",
	PurpleHeader: "כותרת עליונה סגולה",
	LightBlueHF: "כותרת עליונה/תחתונה בכחול בהיר",
	
    formatMenu_LineSpacing: "ריווח שורות",
	linespaceboxTitle:"ריווח מותאם",
	linespacelineTitle:"שורה:",
	linespacenoticeContent :"ריווח שורות",
    formatMenu_LineSpacing_Customize: "מותאם...‏",
    formatMenu_LineSpacing_CustomValue:"מותאם: ${0}",
    lineSpaceWarning:"ציינו מספר בטווח 0 עד 10",
    
    set_transparency_menu: "אטימות תמונה",
    opacity_percent_value: "${0}%",
    opacity_title: "אטימות",
    
    increaseLineWidthTip: "הגדלת משקל קו ",
	decreaseLineWidthTip : "הקטנת משקל קו",
    setBorderStyleTip:"הגדרת סגנון קו",
    line_width_title: "משקל קו ",
    line_end_title: "נקודות קצה של קו ",
    line_dash_title: "תבנית קו",
    line_dash_type1: "יציב",
    line_dash_type2: "נקודות מרובעות",
    line_dash_type3: "מקפים",
    line_dash_type4: "נקודות עגולות",
    line_dash_type5: "מקפים ונקודות",
    line_dash_type6: "מקפים ארוכים",
    line_endpoints_type1: "ללא",
    line_endpoints_type2: "חץ ימני פשוט",
	line_endpoints_type3: "חץ שמאלי פשוט",
	line_endpoints_type4: "חץ כפול פשוט",
	line_endpoints_type5: "חץ ימני ממולא",
	line_endpoints_type6: "חץ שמאלי ממולא",
    line_endpoints_type7: "חץ כפול ממולא",
    line_endpoints_type8: "חץ ועיגול ממולאים",
	line_endpoints_type9: "יהלום וחץ ממולאים",
	line_endpoints_type10: "יהלומים ממולאים",
    line_endpoints_type11: "עיגולים ממולאים"
})

