({	
	createTaskSummary: "${0} oprettede opgaven.",
	completeTaskSummary: "${0} har markeret opgaven som udført.",
	editTaskSummary5: "${0} redigerede opgavens ${1}, ${2}, ${3}, ${4} og ${5}.",
	editTaskSummary4: "${0} redigerede opgavens ${1}, ${2}, ${3} og ${4}.",
	editTaskSummary3: "${0} redigerede opgavens ${1}, ${2} og ${3}.",
	editTaskSummary2: "${0} redigerede opgavens ${1} og ${2}.",
	editTaskSummary1: "${0} redigerede opgavens ${1}.",
	editTaskSummary0: "${0} redigerede opgaven.",
	removeTaskSummary: "${0} fjernede opgaven.",
	reopenTaskSummary: "${0} genåbnede opgaven.",
	reassignTaskSummary: "${0} flyttede ${1} fra ${2} til ${3}.",
	reassignTaskSummary2: "${0} flyttede den tildelte fra ${1} til ${2} og korrekturlæseren fra ${3} til ${4}.",
	workPrivateSummary: "${0} begyndte at arbejde privat på denne opgave.",
	approveTaskSummary: "${0} godkendte denne opgave.",
	rejectTaskSummary: "${0} afviste denne opgave.",
	rejectTaskSummary2: "${0} returnerede denne opgave til ${1} til omarbejdning.",
	submitTaskSummary: "${0} sendte privat arbejde tilbage til dokumentet.",
	cancelPrivateSummary: "${0} annullerede det private arbejde.",
	updatedFieldsDesc: "${0}: ${1} -> ${2}",
	fieldAssignee: "tildelt",
	fieldDuedate: "tidsfrist",
	fieldDescription: "beskrivelse",
	fieldReviewer: "korrekturlæser",
	fieldTitle: "titel",
	emptyFieldValue: "[Ikke tildelt]",
	errorAddMember:"Der er ingen adgang til aktivitetsserveren, så der kan tilføjes tildelte eller korrekturlæsere. Prøv igen senere.",
	errorCreateActivity:"Der er ingen adgang til aktivitetsserveren, så aktiviteten kan oprettes. Prøv igen senere.",
	errorLoadActivity:"Der er ingen adgang til aktivitetsserveren, så tildelingerne kan indlæses. Prøv igen senere.",
	errorCreateAssignment: "Der er ingen adgang til aktivitetsserveren, så tildelingen kan oprettes. Prøv igen senere.",
	errorDeleteAssignment: "Der er ingen adgang til aktivitetsserveren, så tildelingerne kan slettes. Prøv igen senere.",
	errorupdateAssignment: "Der er ingen adgang til aktivitetsserveren, så tildelingerne kan opdateres. Prøv igen senere.",
	errorSubmitAssignment: "Du kan ikke udføre denne funktion. Kontrollér, om du har tilladelse til at gøre det.",	
	errorAddMember2:"Der er ingen adgang til serveren, så der kan tilføjes tildelte eller korrekturlæsere. Prøv igen senere.",
	errorCreateActivity2:"Der er ingen adgang til serveren, så aktiviteten kan oprettes. Prøv igen senere.",
	errorLoadActivity2:"Der er ingen adgang til serveren, så tildelingerne kan indlæses. Prøv igen senere.",
	errorCreateAssignment2: "Der er ingen adgang til serveren, så tildelingen kan oprettes. Prøv igen senere.",
	errorDeleteAssignment2: "Der er ingen adgang til serveren, så tildelingerne kan slettes. Prøv igen senere.",
	errorupdateAssignment2: "Der er ingen adgang til serveren, så tildelingerne kan opdateres. Prøv igen senere."	
})
