({
	delete_general: "削除",
	order: "順序",
	align_text: "テキストの位置合わせ",
	align_slide: "スライドに合わせる",
	align_objects: "選択したオブジェクトに合わせる",
	zoom: "ズーム",
	zoom_fit: "ウィンドウに合わせる",
	insert_link: "リンクの挿入",
	add_link: "リンクの追加",
	open_link: "リンクを開く",
	edit_link: "リンクの編集",
	remove_link: "リンクの削除",
	insert_link_menu: "リンク",
	invalid_url: "URL を開けません。URL が正しいことを確認するか、ブラウザーがポップアップをブロックする設定になっているかを確認します。",
	dnd_canceled_on_slide_event: "別の編集者が最近プレゼンテーションを変更したため、このスライドは移動できません。 後でやり直してください。",
	rotate: "回転",
	flipX: "横方向に反転",
	flipY: "縦方向に反転",
	rotate_right: "時計回りに 90&#x00B0 回転",
	rotate_left: "時計の反対回りに 90&#x00B0 回転",
	color_set_fill: "塗りつぶしの色を設定",
	color_nofill: "塗りつぶしなし",
	color_nobackground: "背景なし",
	color_auto: "自動再生",
	color_default: "デフォルト",
	color_transparent: "透明",
	
	objects_distribute: "配置",
	objects_distribute_v: "縦方向",
	objects_distribute_h: "横方向",
	
	link_subject: "件名 :",
	link_text: "表示テキスト :",
	link_mailto: "メールを開く",
	link_goto: "リンクを開く",
	link_done: "完了",
	link_remove: "削除",
	link_website: "Web サイト",
	link_email: "メール",
	link_slide: "スライド",
	link_slide_placeholder: "選択または数値を入力します",
	link_slide_placeholder_deleted: "リンクされたスライドは削除されました",
	link_slide_next: "次のスライド",
	link_slide_prev: "前のスライド",
	link_slide_first: "最初のスライド",
	link_slide_last: "最後のスライド",
	link_slide_number: "スライド ${0}",
	link_not_support: "サポートされないリンク・タイプ",
	link_acc_input: "リンク・アドレスの入力",
	link_acc_mail_input: "メール・アドレスの入力",
	

	// Jaws Support
	acc_blank: "空白",// when selection is nothing but space char and empty paragraph
	acc_selected: " 選択済み",
	acc_showed: " 表示済み",
	acc_inTable: " テーブル行 ${0} 列 ${1} ",
	acc_titleSelected: "選択済みタイトル",
	acc_subtitleSelected: "選択済みサブタイトル",
	acc_outlineSelected: "選択済み概略",
	acc_notesSelected: "選択済み発話メモ",
	acc_imageSelected: "選択済み画像",
	acc_shapeSelected: "選択済みシェイプ",
	acc_rotated: " ${0} 度回転済み",
	acc_tableSelected: "選択済み表",
	acc_textboxSelected: "選択済みテキスト・ボックス",
	acc_enterEdit: " 編集するには Enter を押してください",
	acc_locked_by: " ユーザー ${0} がロックしています",
	acc_slide_used_by: " ユーザー ${0} が使用しています",
	ACC_TABLE_TABLESIZE: "${0} 行、${1} 列を選択しました",
	ACC_TABLE_MAXSIZE: " サポートされる最大表サイズは 8*8 です",
	ACC_EditorMode: "エディター編集モード",
	ACC_EndEditorMode: "エディター編集モードの終了",
	ACC_Table_new_row: "新しい行が追加されました",
	ACC_Table_new_column: "新しい列が追加されました",
	Acc_column: "列  ${0}",
	acc_slide: "スライド ${0}",
	acc_editor: "${0} が編集",
	Plain: "シンプル",
	BlueStyle: "青のスタイル",
	RedTint: "薄い赤",
	BlueHeader: "青のヘッダー",
	DarkGrayHF: "濃いグレーのヘッダー/フッター",
	LightGrayRows: "明るいグレーの行",
	DarkGrayRows: "濃いグレーの行",
	BlueTint: "薄い青",
	RedHeader: "赤のヘッダー",
	GreenHF: "緑のヘッダー/フッター",
	PlainRows: "シンプルな行",
	GrayTint: "薄いグレー",
	GreenTint: "薄い緑",
	GreenHeader: "緑のヘッダー",
	RedHF: "赤のヘッダー/フッター",
	GreenStyle: "緑のスタイル",
	PurpleTint: "薄い紫",
	BlackHeader: "黒のヘッダー",
	PurpleHeader: "紫のヘッダー",
	LightBlueHF: "明るい青のヘッダー/フッター",
	
    formatMenu_LineSpacing: "行間",
	linespaceboxTitle:"カスタム・スペーシング",
	linespacelineTitle:"行",
	linespacenoticeContent :"行間",
    formatMenu_LineSpacing_Customize: "カスタム...",
    formatMenu_LineSpacing_CustomValue:"カスタム: ${0}",
    lineSpaceWarning:"0 から 10 の数値を入力してください",
    
    set_transparency_menu: "イメージの透明度",
    opacity_percent_value: "${0}%",
    opacity_title: "透明度",
    
    increaseLineWidthTip: "線の太さを増加",
	decreaseLineWidthTip : "線の太さを減少",
    setBorderStyleTip:"線のスタイルを設定",
    line_width_title: "線の太さ",
    line_end_title: "線の端点",
    line_dash_title: "線のパターン",
    line_dash_type1: "実線",
    line_dash_type2: "四角のドット",
    line_dash_type3: "ダッシュ",
    line_dash_type4: "丸のドット",
    line_dash_type5: "ダッシュとドット",
    line_dash_type6: "長いダッシュ",
    line_endpoints_type1: "なし",
    line_endpoints_type2: "単純右矢印",
	line_endpoints_type3: "単純な左矢印",
	line_endpoints_type4: "単純な二重矢印",
	line_endpoints_type5: "塗りつぶした右矢印",
	line_endpoints_type6: "塗りつぶした左矢印",
    line_endpoints_type7: "塗りつぶした二重矢印",
    line_endpoints_type8: "塗りつぶした円と矢印",
	line_endpoints_type9: "塗りつぶしたひし形と矢印",
	line_endpoints_type10: "塗りつぶしたひし形",
    line_endpoints_type11: "塗りつぶした丸"
})

