define({      
//begin v1.x content
	"clearFilterDialogTitle": "เคลียร์ตัวกรอง",
	"filterDefDialogTitle": "ตัวกรอง",
	"defaultRuleTitle": "กฎ",
	"ruleTitleTemplate": "กฎ ${ruleNumber}",
	"noFilterApplied": "ไม่มีการใช้ตัวกรอง",
	"defineFilter": "กำหนดตัวกรอง",
	"conditionEqual": "เท่ากับ",
	"conditionNotEqual": "ไม่เท่ากับ",
	"conditionLess": "น้อยกว่า",
	"conditionLessEqual": "น้อยกว่าหรือเท่ากับ",
	"conditionGreater": "มากกว่า",
	"conditionGreaterEqual": "มากกว่าหรือเท่ากับ",
	"conditionContain": "มี",
	"conditionIs": "เป็น",
	"conditionStartWith": "ขึ้นต้นด้วย",
	"conditionEndWith": "ลงท้ายด้วย",
	"conditionNotContain": "ไม่มี",
	"conditionIsNot": "ไม่เป็น",
	"conditionNotStartWith": "ไม่ขึ้นต้นด้วย",
	"conditionNotEndWith": "ไม่ลงท้ายด้วย",
	"conditionBefore": "ก่อน",
	"conditionAfter": "หลัง",
	"conditionRange": "ช่วง",
	"conditionIsEmpty": "ว่าง",
	"all": "ทั้งหมด",
	"any": "ใดๆ",
	"relationAll": "กฎทั้งหมด",
	"waiRelAll": "จับคู่กฎต่อไปนี้ทั้งหมด:",
	"relationAny": "กฏใดๆ",
	"waiRelAny": "จับคู่กฎใดๆ ต่อไปนี้:",
	"relationMsgFront": "จับคู่",
	"relationMsgTail": "",
	"and": "และ",
	"or": "หรือ",
	"addRuleButton": "เพิ่มกฎ",
	"waiAddRuleButton": "เพิ่มกฎใหม่",
	"removeRuleButton": "ลบกฎออก",
	"waiRemoveRuleButtonTemplate": "ลบกฎ ${0}",
	"addRuleButton": "เพิ่มกฎการกรอง",
	"cancelButton": "ยกเลิก",
	"waiCancelButton": "ยกเลิกไดอะล็อกนี้",
	"clearButton": "เคลียร์",
	"waiClearButton": "เคลียร์ตัวกรองนี้",
	"filterButton": "ตัวกรอง",
	"waiFilterButton": "ส่งตัวกรอง",
	"columnSelectLabel": "คอลัมน์:",
	"waiColumnSelectTemplate": "คอลัมน์สำหรับกฎ ${0}",
	"conditionSelectLabel": "เงื่อนไข:",
	"waiConditionSelectTemplate": "เงื่อนไขสำหรับกฎ ${0}",
	"valueBoxLabel": "ค่า:",
	"waiValueBoxTemplate": "ป้อนค่าที่จะกรองสำหรับกฎ ${0}",
	"rangeTo": "ถึง",
	"rangeTemplate": "ตั้งแต่ ${0} ถึง ${1}",
	"statusTipHeaderColumn": "คอลัมน์",
	"statusTipHeaderCondition": "กฎ",
	"statusTipTitle": "แถบตัวกรอง",
	"statusTipMsg": "คลิกแถบตัวกรองที่นี่เพื่อกรองค่าใน ${0}",
	"anycolumn": "คอลัมน์ใดๆ",
	"statusTipTitleNoFilter": "แถบตัวกรอง",
	"statusTipTitleHasFilter": "ตัวกรอง",
	"statusTipRelPre": "จับคู่",
	"statusTipRelPost": "กฎ",
	"statusTipHeaderAll": "จับคู่กฎทั้งหมด",
	"statusTipHeaderAny": "จับคู่กฎใดๆ",
	"defaultItemsName": "ไอเท็ม",
	"filterBarMsgHasFilterTemplate": "${0} จาก ${1} ${2} ถูกแสดงอยู่",
	"filterBarMsgNoFilterTemplate": "ไม่มีการใช้ตัวกรอง",
	"filterBarDefButton": "กำหนดตัวกรอง",
	"waiFilterBarDefButton": "กรองตาราง",
	"a11yFilterBarDefButton": "ตัวกรอง...",
	"filterBarClearButton": "เคลียร์ตัวกรอง",
	"waiFilterBarClearButton": "เคลียร์ตัวกรอง",
	"closeFilterBarBtn": "ปิดแถบตัวกรอง",
	"clearFilterMsg": "นี่จะลบตัวกรอง และแสดงเร็กคอร์ดที่มีอยู่ทั้งหมด",
	"anyColumnOption": "คอลัมน์ใดๆ",
	"trueLabel": "จริง",
	"falseLabel": "เท็จ",
	"radioTrueLabel": "ค่าจริง",
	"radioFalseLabel": "ค่าเท็จ",
	"beginTimeRangeLabel": "ค่าเริ่มต้นช่วงเวลา",
	"endTimeRangeLabel": "ค่าสิ้นสุดช่วงเวลา",
	"beginDateRangeLabel": "ค่าเริ่มต้นช่วงวันที่",
	"endDateRangeLabel": "ค่าเริ่มต้นช่วงวันที่",
	"startsWithExpr": "${0}*"
//end v1.x content
});

