({	
	viewExpandedBtn: "Visualitza menys respostes",
	viewCollapsedBtn: "Visualitza ${0} respostes més",
	placeholderMsg: "Escriviu aquí el vostre missatge",
	sure: "Esteu segur que voleu suprimir aquest comentari?",
	exceed: "El comentari és massa llarg.\n El comentari que heu introduït sobrepassa la longitud màxima permesa.\n Reduïu-lo en no més de ${0} caràcters i feu clic a Afegeix.",
	remainLabelHint:"El vostre comentari ha arribat al límit de 500 caràcters.",
	tipsCommentField: "Introduïu un comentari per a tots els editors o per a un editor",
	tipsRespondField: "Introduïu una resposta per a tots els editors o per a un editor",	
	resolveBtn: "Resol",	
	replyBtn: "Respon",
	saveBtn: "Publica",
	deleteBtn: "Suprimeix",
	cancelBtn: "Cancel·la",
	reopenBtn: "Reobre",
	todayAt: "Avui a les ${time}",
	yesterdayAt: "Ahir a les ${time}",
	dateAt: "${date} a les ${time}",
	mentions: "Seleccioneu un usuari a mencionar",
	noMentions: "Toqueu l'espai en blanc per completar l'entrada",
	nocomments: "No hi ha cap comentari al document '${0}'.",
	
	newComments:"Comentaris nous",
	mentiontomesomebody:"Algú",
	mentiontome:"${0} us ha mencionat en un comentari",
	
	newcommentsnumber:"Número de comentaris sense llegir",
	jawsnewcommentsnumber: "El número de comentaris sense llegir són ",
	jawsnactivecommentsnumber: "El número de comentaris actius són ",
	
	activenum:"El número de comentaris actius",
	filterDesc:"Filtra comentaris",
	menuallcomments:"Tots els comentaris",
	menutome: "@jo",
	menubyme: "Meus",
	menuactive: "Actius",
	menuresolved: "Resolts",
	searchDesc: "Cerca comentaris",
	search: "Cerca",
	closeDesc: "Tanca la cerca",
	clear: "Esborra",
	warnEnterKeywords: "Introduïu termes de cerca",
	nocommentstome: "Actualment, no hi ha cap comentari ni resposta que em mencioni al document '${0}'.",
	nocommentsbyme: "Actualment, no hi ha cap comentari ni resposta meu al document '${0}'.",
	nocommentsar: "Actualment, no hi ha cap comentari a la categoria '${0}' del document '${1}'.",
	nosearchedcomments: "Actualment, no hi ha cap comentari ni resposta que contingui '${0}' a la categoria '${1}' del document '${2}'.",
	
	prevBtn: "Anterior",
	nextBtn: "Següent",
	mentionHint:"S'estan mostrant de ${0} a ${1} coincidències d'un total de ${2}.",
		
	resolveFlag: "Comentaris resolts",
	jawsCommentHint: "${authorname} ha publicat el comentari ${timestamp}",
	jawsReplyHint: "${authorname} ha publicat la resposta ${timestamp}",
	jawsContentHint: "El contingut és ${content}",
	jawsCommentStatusHint: "L'estat és ${status}",
	jawsCommentKeyHint: "Premeu intro o la barra d'espai per anar al document i veure, resoldre, contestar o eliminar els comentaris.",
	jawsMentionHint: "Widget de menció Docs. Premeu la tecla de fletxa amunt o fletxa avall per seleccionar l'usuari que voleu mencionar",
	jawsMentionSelected: "Premeu Intro o la barra d'espai per mencionar",
	commentDeletedMsg: "Un altre editor ha eliminat el comentari actual.",
	commentResolvedMsg: "El comentari actual s'ha resolt.",
	warningCommentMsg: "Els comentaris fets dins de Docs per a fitxers ${0} només s'admeten en línia. Els enllaços de comentaris s'eliminaran si es carrega una versió nova per editar.",
	orphanCommentTip: "L'enllaç de comentari s'ha eliminat en aquesta versió carregada.",
	warningCommentName: "Advertiment"
})

