({
	service_unavailable_title: "Serviço não disponível",
	service_unavailable_content: "O serviço do ${productName} não está disponível e de momento não é possível processar o seu pedido. Tente novamente mais tarde ou contacte o administrador do sistema para se certificar de que o serviço do ${productName} está online.",
	access_denied_title: "Acesso recusado",
	viewaccess_denied_content: "Não tem permissão para visualizar este ficheiro. O ficheiro tem de ser público ou partilhado consigo.",
	editaccess_denied_content: "Não tem permissão para editar este ficheiro. O ficheiro tem de ser partilhado consigo ou tem de ter acesso de editor ao mesmo.",
	doc_notfound_title: "O serviço do ${productName} não conseguiu localizar o ficheiro.",
	doc_notfound_content: "Contacte o administrador para se certificar de que o serviço do ${productName} está configurado correctamente.",
	fullviewer_notsupport_title: "Documento não encontrado",
	fullviewer_notsupport_content: "Um novo visualizador de ficheiro armazena o documento num URL diferente. Para visualizar o documento, localize o ficheiro na aplicação e faça clique no botão Pré-visualizar.",
	fileconnect_denied_title: "Ligação recusada",
	fileconnect_denied_content: "Não é possível ao ${productName} estabelecer ligação ao repositório de ficheiros. Tente novamente mais tarde ou contacte o administrador do sistema.",
	convservice_unavailable_title: "Serviço de conversão não disponível",
	convservice_unavailable_content: "Neste momento, não é possível processar o seu pedido. Tente novamente mais tarde ou contacte o administrador do sistema, de forma a certificar-se de que o serviço de conversão está online.",
	doc_toolarge_title: "O ficheiro é demasiado grande.",
	doc_toolarge_content: "O documento ao qual pretende aceder é demasiado grande.",
	doc_toolarge_content2: "Não é possível aceder ao ficheiro, porque:",
	doc_toolarge_content3: "Não é possível apresentar o ficheiro, uma vez que o tamanho do ficheiro é superior a ${0} KB. Pode descarregar o ficheiro para o visualizar. Se o ficheiro contiver imagens em alta resolução, pode substitui-las por imagens de baixa resolução para reduzir o tamanho do ficheiro.",
	doc_toolarge_content4: "O ficheiro não pode ser apresentado, uma vez que o tamanho do ficheiro ${0} é superior a ${1} KB.",
	doc_toolarge_content5: "O ficheiro é demasiado grande para ser visualizado aqui, mas mesmo assim pode abri-lo se fizer clique no botão descarregar na barra de título.",
	edit_locked_file: "Não é possível editar este ficheiro, uma vez que o mesmo está bloqueado por outros editores.",
	sheet_toolarge_content: "O tamanho da folha de cálculo é superior a ${0} KB.",
	sheet_toolarge_content2: "A folha de cálculo contém mais do que ${0} linhas numa única folha.",
	sheet_toolarge_content5: "A folha de cálculo contém mais do que ${0} colunas numa única folha.",
	sheet_toolarge_content3: "A folha de cálculo contém mais do que ${0} células.",
	sheet_toolarge_content4: "A folha de cálculo contém mais do que ${0} fórmulas.",
	text_toolarge_content: "O tamanho do documento é superior a ${0} KB.",
	text_toolarge_content2:"O documento contém mais do que ${0} páginas.",
	text_toolarge_content3:"O tamanho do texto do documento é superior a ${0} KB.",
	pres_toolarge_content: "O tamanho da apresentação é superior a ${0} KB.",
	pres_toolarge_content2: "A apresentação contém mais do que ${0} páginas.",
	pres_toolarge_content3: "A apresentação contém mais do que ${0} imagens.",
	pdf_toolarge_content: "O tamanho do pdf é superior a ${0} KB.",
	conversion_timeout_title: "O tempo limite de conversão do documento foi excedido.",
	conversion_timeout_content: "Neste momento, a conversão do documento está a demorar demasiado tempo. Tente novamente mais tarde.",
	invalid_docformat_title: "Conteúdo do documento não válido",
	invalid_docformat_content: "A extensão de ficheiro do documento corresponde a um formato válido, mas não é possível aceder ao conteúdo do ficheiro. Certifique-se de que o ficheiro não está danificado. ",
	invalid_doctype_title: "O tipo de documento não é suportado.",
	invalid_doctype_content: "O tipo de documento não é actualmente suportado pelo ${productName}.",
	malformed_request_title: "URL ou parâmetros incorrectos",
	malformed_request_content: "Certifique-se de que o URL e os parâmetros estão correctos.",
	storageserver_error_title: "O servidor de armazenamento não está disponível.",
	storageserver_error_content: "O servidor encontra-se indisponível. Neste momento, não é possível processar o seu pedido. Tente novamente mais tarde ou contacte o administrador do sistema, de forma a certificar-se de que o serviço de armazenamento está online.",
	incorrect_web_address_title:"Endereço da Web incorrecto",
	incorrect_web_address_content:"O endereço da Web não está correcto.  Introduza o endereço da Web e tente novamente.",
	unexpecified_conversion_error_title:"Erro não especificado",
	unexpecified_conversion_error_content:"O servidor devolveu um erro não especificado.",
	encrypted_conversion_error_title:"Os documentos encriptados com CryptoAPI RC4 não são suportados.",
	encrypted_conversion_error_content:"O ficheiro está protegido por palavra-passe. Para visualizar o ficheiro no ${productName}, assegure-se de que o ficheiro está desencriptado.",
	document_encrypt_title:"Documento encriptado",
	document_encrypt_content:"Não é possível visualizar o ficheiro online, uma vez que o mesmo foi encriptado quando foi transferido para os Ficheiros.",
	service_busy_title:"Falha ao abrir o documento",
	service_busy_content:"Não foi possível abrir o ficheiro que pretende visualizar. O servidor poderá estar ocupado ou indisponível. Tente novamente mais tarde ou contacte o administrador.",
	empty_doc_title: "Documento vazio",
	empty_doc_content: "Certifique-se de que o documento inclui conteúdo e, em seguida, tente novamente.",
	corrupted_doc_title: "Não é possível abrir o ficheiro.",
	corrupted_doc_content: "O ficheiro contém conteúdo não suportado, por exemplo macros, e por esse motivo não pode ser visualizado nesta aplicação.",
	draft_storage_error_title: "Não é possível abrir o documento.",
	draft_storage_error_content: "Não é possível carregar o conteúdo porque está danificado. Contacte o administrador para obter suporte.",
	unexpected_code_title: "Não é possível visualizar o documento.",
	unexpected_code_content: "O servidor do ${docsProductName} poderá estar indisponível. Tente novamente mais tarde.",
	unpublished_document_title: "Não é possível visualizar o ficheiro",
	unpublished_document_content: "Não está disponível para visualização uma versão publicada deste ficheiro.  O proprietário do ficheiro tem de publicar uma versão do ficheiro para que seja possível visualizar o mesmo.",
	unscanned_document_title: "A concluir a verificação de vírus",
	unscanned_document_content: "Os ficheiros carregados para o Connections são verificados automaticamente. Pode visualizar este ficheiro logo que a verificação do mesmo seja concluída.",
	malicious_document_title: "Ficheiro malicioso",
	malicious_document_content: "Não pode visualizar este ficheiro, uma vez que o Connections detectou um vírus durante a verificação.",		
	repository_out_of_space_title: "Não existe espaço suficiente",
	repository_out_of_space_content: "Não é possível publicar o ${0} uma vez que atingiu o limite do tamanho de ficheiros. Reduza a quota movendo outros ficheiros para o lixo e, em seguida, eliminando-os.",
	pdf_error_title:"Não é possível abrir o ficheiro.",
	pdf_error_content:"O ficheiro PDF pode estar corrompido.",
	problem_id_msg_title: "Comunique este problema ao seu administrador. ",
	problem_id_msg_show: "Clique para mostrar os detalhes",
	problem_id_msg_hide: "Clique para ocultar"
})

