define({      
//begin v1.x content
	"clearFilterDialogTitle": "Počisti filter",
	"filterDefDialogTitle": "Filter",
	"defaultRuleTitle": "Pravilo",
	"ruleTitleTemplate": "Pravilo ${ruleNumber}",
	"noFilterApplied": "Uporabljen ni noben filter.",
	"defineFilter": "Določi filter",
	"conditionEqual": "enak",
	"conditionNotEqual": "ni enak",
	"conditionLess": "je manj kot",
	"conditionLessEqual": "manj kot ali enak",
	"conditionGreater": "je več kot",
	"conditionGreaterEqual": "več kot ali enak",
	"conditionContain": "vsebuje",
	"conditionIs": "je",
	"conditionStartWith": "se začne z",
	"conditionEndWith": "se konča z",
	"conditionNotContain": "ne vsebuje",
	"conditionIsNot": "ni",
	"conditionNotStartWith": "se ne začne z",
	"conditionNotEndWith": "se ne konča z",
	"conditionBefore": "pred",
	"conditionAfter": "po",
	"conditionRange": "obseg",
	"conditionIsEmpty": "je prazen",
	"all": "vsa",
	"any": "katera koli",
	"relationAll": "vsa pravila",
	"waiRelAll": "Nastavite ujemanje z vsemi od teh pravil:",
	"relationAny": "katero koli pravilo",
	"waiRelAny": "Nastavite ujemanje s katerimi koli od teh pravil:",
	"relationMsgFront": "Nastavi ujemanje",
	"relationMsgTail": "",
	"and": "in",
	"or": "ali",
	"addRuleButton": "Dodaj pravilo",
	"waiAddRuleButton": "Dodaj novo pravilo",
	"removeRuleButton": "Odstrani pravilo",
	"waiRemoveRuleButtonTemplate": "Odstrani pravilo ${0}",
	"addRuleButton": "Dodaj pravilo filtra",
	"cancelButton": "Prekliči",
	"waiCancelButton": "Zapri to pogovorno okno",
	"clearButton": "Počisti",
	"waiClearButton": "Počisti filter",
	"filterButton": "Filter",
	"waiFilterButton": "Pošlji filter",
	"columnSelectLabel": "Stolpec:",
	"waiColumnSelectTemplate": "Stolpec za pravilo ${0}",
	"conditionSelectLabel": "Pogoj:",
	"waiConditionSelectTemplate": "Pogoj za pravilo ${0}",
	"valueBoxLabel": "Vrednost:",
	"waiValueBoxTemplate": "Vnesite vrednost filtra za pravilo ${0}",
	"rangeTo": "do",
	"rangeTemplate": "od ${0} do ${1}",
	"statusTipHeaderColumn": "Stolpec",
	"statusTipHeaderCondition": "Pravila",
	"statusTipTitle": "Vrstica filtra",
	"statusTipMsg": "Kliknite vrstico filtra na tem mestu, da nastavite filter za vrednosti v ${0}.",
	"anycolumn": "kateri koli stolpec",
	"statusTipTitleNoFilter": "Vrstica filtra",
	"statusTipTitleHasFilter": "Filter",
	"statusTipRelPre": "Nastavi ujemanje",
	"statusTipRelPost": "s pravili.",
	"statusTipHeaderAll": "Nastavite ujemanje z vsemi pravili.",
	"statusTipHeaderAny": "Nastavite ujemanje s katerimi koli pravili.",
	"defaultItemsName": "postavke",
	"filterBarMsgHasFilterTemplate": "${0}/${1} ${2} (prikazanih).",
	"filterBarMsgNoFilterTemplate": "Uporabljen ni noben filter",
	"filterBarDefButton": "Določi filter",
	"waiFilterBarDefButton": "Nastavi filter za tabelo",
	"a11yFilterBarDefButton": "Nastavi filter ...",
	"filterBarClearButton": "Počisti filter",
	"waiFilterBarClearButton": "Počisti filter",
	"closeFilterBarBtn": "Zapri vrstico filtra",
	"clearFilterMsg": "Tako odstranite filter in omogočite prikaz vseh razpoložljivih zapisov.",
	"anyColumnOption": "Kateri koli stolpec",
	"trueLabel": "True",
	"falseLabel": "False",
	"radioTrueLabel": "Vrednost True",
	"radioFalseLabel": "Vrednost False",
	"beginTimeRangeLabel": "Vrednost časovnega obsega – začetek",
	"endTimeRangeLabel": "Vrednost časovnega obsega – konec",
	"beginDateRangeLabel": "Vrednost datumskega obsega – začetek",
	"endDateRangeLabel": "Vrednost datumskega obsega – konec",
	"startsWithExpr": "${0}*"
//end v1.x content
});

