({
	labelPrintConfig: "For å få best mulig resultat for utskriften, bør du definere nettleserens sideoppsett slik:",
	labelConfigPageSize: "Sidestørrelse: ${0}",
	labelConfigOrientation: "Retning: ${0}",
	labelConfigHeader: "Topptekst: blank",
	labelConfigFooter: "Bunntekst: blank",
	labelConfigMargins: "Marger: ",
	labelConfigMarginTop: "Topp: ${0}${1}",
	labelConfigMarginBottom: "Bunn: ${0}${1}",
	labelConfigMarginLeft: "Venstre: ${0}${1}",
	labelConfigMarginRight: "Høyre: ${0}${1}",
	labelPrintContinue: "Når du har definert nettleserinnstillingene, klikker du på OK for å fortsette utskriften av filen.",
	labelMm: "millimeter",
	labelInch: "tommer",
	labelPortrait: "Stående",
	labelPageA4: "A4",
	labelLetter: "Letter",
	labelLandscape: "Liggende",
	titlePrintConfig: "Utskriftsinnstillinger",
	titlePrepare: "Forbereder utskrift",
	msgPrepare: "Filen blir klargjort for utskrift. Klargjøringen kan ta lang tid.",
	errPrepare: "Det oppstod en feil ved klargjøring av dataene.\nVil du prøve igjen?",
	titleErr: "Feil",
	btnRetry: "Prøv igjen"
})
