({
	COLUMN: "Stubičasti",
	CLUSTERED_COLUMN: "Grupisani stubičasti",
	STACKED_COLUMN: "Naslagani stubičasti",
	BAR:"Traka",
	CLUSTERED_BAR:"Grupisani trakasti",
	STACKED_BAR: "Naslagani trakasti",
	PIE:"Kružni",
	SLICE: "Isečak",
	AREA: "Oblasni",
	STACKED_AREA: "Naslagani oblasni",
	LINE: "Linijski",
	STACKED_LINE: "Naslagani linijski",
	MAKER_LINE: "Linijski sa označivačima",
	STACKED_MARKER_LINE: "Naslagani linijski sa označivačima",
	SCATTER: "XY",
	SCATTER_MARKER_ONLY: "XY samo sa označivačima",
	SCATTER_MARKER_LINE_S: "XY sa umekšanim linijama i označivačima",
	SCATTER_LINE_S: "XY sa umekšanim linijama", 
	SCATTER_MARKER_LINE_X: "XY sa pravim linijama i označivačima",
	SCATTER_LINE_X: "XY sa pravim linijama",
	ERROR_INVALID_RANGE:"Nevažeći opseg podataka",
	TOO_MANY_POINTS: "Nije moguće kreirati grafikon koji ima više od ${0} vrednosti pokazatelja",
	CHART_TYPES:"Tipovi grafikona",
	DATA:"Podaci",
	DATA_RANGE:"Opseg podataka",
	IN_ROWS:"Serije podataka u redovima",
	IN_COLUMNS:"Serije podataka u kolonama",
	AUTO:"Automatski"
})

