﻿/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        fileMenu: "Arkiv",
        fileMenu_New: "Nytt",
        fileMenu_NewDocument: "Dokument",
        fileMenu_NewFromTemplate: "Från mall",
        fileMenu_NewDocumentfromTemplate: "Dokument från mall",
        fileMenu_NewPresentation: "Presentation",
        fileMenu_NewPresentationfromTemplate: "Presentation från mall",
        fileMenu_NewSpreadsheet: "Kalkylark",
        fileMenu_NewSpreadsheetFromTemplate: "Kalkylark från mall",
        fileMenu_Open: "Öppna",
        fileMenu_Import: "Importera...",
        //	fileMenu_Close: "Close",
        fileMenu_Discard: "Återgå till den senaste versionen",
        fileMenu_ClearTrackChange: "Ta bort ändringsmarkeringar",
        fileMenu_SpreadsheetSettings: "Ange språkmiljö för dokument...",
        filemenu_revisionhistory: "Revisioner",
        fileMenu_Save: "Spara",
        fileMenu_SaveAs: "Kopiera...",
        fileMenu_AutoPublish: "Publicera automatiskt",
        fileMenu_AutoCheckIn: "Checka in automatiskt",
        fileMenu_PublishVersion: "Publicera nu",
        fileMenu_AutoPublish2: "Spara automatiskt till datalager",
        //	fileMenu_AutoPublish_Tips: "Makes your changes available to readers at the end of each editing session.",
        fileMenu_PublishVersion2: "Spara till datalager nu",
        fileMenu_AutoPublish3: "Spara automatiskt till ${0}",
        fileMenu_PublishVersion3: "Spara till ${0} nu",      
        fileMenu_SubmitForReview: "Skicka för granskning...",
        fileMenu_CheckinVersion: "Checka in...",
        fileMenu_Unlock: "Lås upp",
        //	fileMenu_SaveAsDraft: "as Draft",
        //	fileMenu_SaveInMyDocs: "in My Documents",
        //	fileMenu_SaveToSymphony: "to Lotus Symphany",
        fileMenu_DownloadAs: "Hämta som",
        fileMenu_PDF: "PDF",
        fileMenu_ODF: "ODF",
        fileMenu_DOC: "Microsoft Word 97- 2007 (*.doc)",
        fileMenu_ODS: "ODS",
        fileMenu_XLS: "Microsoft Excel 97-2007 (*.xls) ",
        fileMenu_ShareWith: "Dela...",
        fileMenu_ExportAsPDF: "PDF",
        fileMenu_ExportAsODF: "ODF",
        fileMenu_ExportAsPPT: "Microsoft Powerpoint 97- 2007 (*.ppt)",
        //	fileMenu_WebPreview: "Web Preview",
        fileMenu_PrintToPDF: "Skriv till PDF...",
        fileMenu_ViewFileDetails: "Visa fildetaljer...",
        fileMenu_RecentFile: "Senaste filer",
        fileMenu_Open: "Öppna",
        fileMenu_Download: "Hämta",
        fileMenu_Print: "Skriv ut",
        fileMenu_Export: "Exportera",
        fileMenu_ExportToCSV: "CSV",
        fileMenu_ExportToPDF: "PDF (.pdf)",
        fileMenu_ExportToMarkdown: "Markdown (.md)",
        fileMenu_ExportToMS: "Microsoft Office-format (.${FILEEXTENSION})",
        fileMenu_ExportToODF: "Open Document-format (.${FILEEXTENSION})",
        fileMenu_PgSetup: "Utskriftsformat...",

        editMenu: "Redigera",
        editMenu_Undo: "Ångra",
        editMenu_Redo: "Gör om",
        editMenu_Cut: "Klipp ut",
        editMenu_Copy: "Kopiera",
        editMenu_Paste: "Klistra in",
        editMenu_DeleteSlide: "Ta bort presentationsbild",
        editMenu_SelectAll: "Markera allt",
        editMenu_Find: "Sök...",
        editMenu_Replace: "Ersätt...",
        editMenu_FindReplace: "Sök och ersätt...",
        editMenu_EditLink: "Lägg till eller redigera länk",
        editMenu_DeleteSheet: "Ta bort ark...",
        editMenu_RenameSheet: "Byt namn på ark...",
        editMenu_HideSheet: "Göm ark",
        editMenu_MoveSheet: "Flytta ark...",
        editMenu_DeleteRow: "Ta bort rad",
        editMenu_DeleteColumn: "Ta bort kolumn",
        editMenu_DeleteCellLeft: "Ta bort celler och skifta vänster",
        editMenu_DeleteCellUp: "Ta bort celler och skifta uppåt",
        editMenu_ClearCell: "Ta bort innehåll",

        viewMenu: "Visa",
        viewMenu_Master: "Bakgrund",
        viewMenu_Notifications: "Meddelanden",
        viewMenu_SlideSorter: "Bildsortering",
        viewMenu_SpeakerNotes: "Stödanteckningar",
        viewMenu_Toolbar_Basic: "Enkelt",
        viewMenu_Toolbar_Advanced: "Avancerat",
        viewMenu_Toolbar_None: "Ingen",
        viewMenu_Toolbar: "Verktygsfält",
        viewMenu_Statusbar: "Statusfält",
        viewMenu_Navigator: "Navigering...",
        //viewMenu_Sidebar: "Sidebar",
        viewMenu_ShowHideIndicators: "Visa samredigeringsindikatorer",
        viewMenu_Assignment: "Indikatorer för tilldelning",
        viewMenu_Bookmark: "Bokmärken",
        viewMenu_Coediting: "Samredigeringsmarkeringar",
        viewMenu_Rulers: "Linjaler",
        viewMenu_WebLayout: "Webblayout",
        viewMenu_AutomaticSpellCheck: "Stavningskontrollera medan du skriver",
        viewMenu_Formulabar: "Formelfält",
        viewMenu_moveRight: "Enter flyttar markören åt höger",
        viewMenu_showFullString: "Utvidga innehåll i celler",
        viewMenu_Doc: "Visa dokument",
        viewMenu_Templates: "Mallar",
        viewMenu_GridLines: "Göm rutnätslinjer",
        viewMenu_UnsupportWarning: "Visa meddelanden om funktioner som inte hanteras",
        viewMenu_HiddenSheets: "Gömda ark",
        viewMenu_FreezeRows: "Lås rader",
        viewMenu_FreezeColumns: "Lås kolumner",
        viewMenu_NoFrozenRows: "Inga låsta rader",
        viewmenu_NoFrozenColumns: "Inga låsta kolumner",
        viewMenu_FreezeXRows: "Lås ${0} rader",
        viewMenu_FreezeOneRow: "Lås ${0} rad",
        viewMenu_FreezeXColumns: "Lås ${0} kolumner",
        viewMenu_FreezeOneColumn: "Lås ${0} kolumn",
        viewMenu_CarriageReturn: "Formateringsmarkeringar",
        viewMenu_Navigation: "Navigeringsruta",
        viewMenu_ACL: "Redigerbara områden",
        viewMenu_GridOnOff: "Rutnätslinjer",
        viewMenu_ObserverMode: 'Bevakningsläge',

        createMenu: "Infoga",
        createMenu_NewSlide: "Ny presentationsbild",
        createMenu_DuplicateSlide: "Duplicera presentationsbild",
        createMenu_ImageFromFile: "Bild...",
        createMenu_TextBox: "Textruta",
        createMenu_Shape: "Form",
        createMenu_break: "Brytning",
        createMenu_RowAbove: "Rad ovanför",
        createMenu_RowBelow: "Rad nedanför",
        createMenu_ColumnRight: "Kolumn till höger",
        createMenu_ColumnLeft: "Kolumn till vänster",
        createMenu_Sheet: "Ark...",
        createMenu_Image: "Bild...",
        createMenu_Comments: "Kommentar...",
        createMenu_WebLink: "Webblänk...",
        createMenu_SpecialCharacter: "Specialtecken...",
        createMenu_Function: "Funktion...",
        createMenu_Fromtemplate: "Skapa från mall",

        insertMenu: "Infoga",
        insertMenu_break: "Sidbrytning",
        insertMenu_sectionbreak: "Avsnittsbrytning",
        insertMenu_Bookmark: "Bokmärken...",
        insertMenu_WebLink: "Länk...",
        insertMenu_SpecialCharacter: "Specialtecken...",
        insertMenu_HorizontalLine: "Horisontell linje",
        insertMenu_Header: "Sidhuvud",
        insertMenu_Footer: "Sidfot",
        insertMenu_TableOfContents: "Innehållsförteckning",

        insertMenu_HeaderFooter: "Sidhuvud/sidfot",
        insertMenu_HF_Edit: "Redigera",
        insertMenu_HF_Hide: "Dölj",
        insertMenu_Endnotes: "Slutnoter",
        insertMenu_RowAbove: "Rad ovanför",
        insertMenu_PageNumber: "Sidnummer",
        insertMenu_PageNumberTop: "Överst på sidan",
        insertMenu_PageNumberBottom: "Nederst på sidan",
        insertMenu_PageNumberCurr: "Aktuell position",
        insertMenu_TotalPageNumber: "Sida 1 av n",
        insertMenu_Date: "Datum...",
        insertMenu_Time: "Klockslag...",
        insertMenu_Fields: "Fält",
        //    insertMenu_Comment: "Comment",
        insertMenu_CellRight: "Celler och skifta höger",
        insertMenu_CellDown: "Celler och skifta nedåt",
        insertMenu_RowBelow: "Rad nedanför",
        insertMenu_ColumnBefore: "Kolumn före",
        insertMenu_ColumnAfter: "Kolumn efter",
        insertMenu_Sheet: "Ark...",
        insertMenu_Image: "Bild...",
        insertMenu_DuplicateSheet: "Duplicera ark",
        insertMenu_Function: "Funktion",
        insertMenu_FunctionSum: "SUM",
        insertMenu_FunctionAverage: "AVERAGE",
        insertMenu_FunctionCount: "COUNT",
        insertMenu_FunctionMax: "MAX",
        insertMenu_FunctionMin: "MIN",
        insertMenu_FunctionMore: "Fler funktioner...",
        insertMenu_NameRange: "Namngivet intervall",
        insertMenu_NameRangeNew: "Nytt intervall...",
        insertMenu_NameRangeManage: "Hantera intervaller...",
        insertMenu_Chart: "Diagram...",

        contextMenu_insertCellRight: "Inga celler och skifta höger",
        contextMenu_insertCellDown: "Inga celler och skifta nedåt",
        contextMenu_InsertRowAbove: "Infoga rad ovanför",
        contextMenu_InsertRowBelow: "Infoga rad nedanför",
        contextMenu_InsertColumnBefore: "Infoga kolumn före",
        contextMenu_InsertColumnAfter: "Infoga kolumn efter",
        contextMenu_DownloadImage: "Hämta som bild",

        formatMenu: "Format",
        formatMenu_Columns: "Kolumner",
        formatMenu_DefaultFormatting: "Standardformatering",
        formatMenu_Template: "Format ...",
        contextMenu_Template: "Tabellformat ...",
        formatMenu_LineSpacing: "Radavstånd",
        formatMenu_LineSpacing1: "1",
        formatMenu_LineSpacing12: "1.2",
        formatMenu_LineSpacing15: "1.5",
        formatMenu_LineSpacing2: "2",
        formatMenu_LineSpacing25: "2.5",
        formatMenu_LineSpacing3: "3",
        formatMenu_TextProperties: "Textegenskaper",
        formatMenu_PageBreakBefore: "Sidbrytning före",
        formatMenu_KeepLines: "Håll ihop rader",
        formatMenu_WidowControl: "Kontroll av enstaka rader",
        formatMenu_Pagination: "Styckeegenskaper",
        formatMenu_Bold: "Halvfet",
        formatMenu_Italic: "Kursiv",
        formatMenu_Underline: "Understrykning",
        formatMenu_Strikethrough: "Genomstrykning",
        formatMenu_IncreaseSize: "Öka teckenstorlek",
        formatMenu_DecreaseSize: "Minska teckenstorlek",
        formatMenu_ImageProperties: "Bildegenskaper...",
        formatMenu_ChartProperties: "Diagramegenskaper...",
        formatMenu_EditChart: "Ändra diagram",
        formatMenu_InsertChart: "Infoga diagram",
        formatMenu_Properties: "Egenskaper...",
        formatMenu_Heading: "Rubrik",
        formatMenu_Normal: "Normal",
        formatMenu_Title: "Rubrik",
        formatMenu_Subtitle: "Underrubrik",
        formatMenu_Heading1: "Rubrik 1",
        formatMenu_Heading2: "Rubrik 2",
        formatMenu_Heading3: "Rubrik 3",
        formatMenu_Heading4: "Rubrik 4",
        formatMenu_Heading5: "Rubrik 5",
        formatMenu_Heading6: "Rubrik 6",
        formatMenu_Heading7: "Rubrik 7",
        formatMenu_Heading8: "Rubrik 8",
        formatMenu_Heading9: "Rubrik 9",
        formatMenu_BulletedList: "Punktlista",
        formatMenu_NumberedList: "Numrerad lista",
        formatMenu_OutLine: "Flernivålista",
        formatMenu_Superscript: "Upphöjt",
        formatMenu_Subscript: "Nedsänkt",
        formatMenu_Align: "Justera",
        formatMenu_Left: "Vänster",
        formatMenu_Right: "Höger",
        formatMenu_Center: "Centrerat",
        formatMenu_Justify: "Marginaljustera",
        formatMenu_Text_Direction: "Textriktning",
        formatMenu_Ltr: "Vänster till höger",
        formatMenu_Rtl: "Höger till vänster",
        formatMenu_LineSpacing: "Radavstånd",
        formatMenu_LineSpacing1: "1.0",
        formatMenu_LineSpacing115: "1.15",
        formatMenu_LineSpacing15: "1.5",
        formatMenu_LineSpacing2: "2.0",
        formatMenu_LineSpacing25: "2.5",
        formatMenu_LineSpacing3: "3.0",
        formatMenu_Top: "Överkant",
        formatMenu_Bottom: "Underkant",
        formatMenu_Middle: "Centrera",
        formatMenu_Direction: "Textriktning",
        formatMenu_Rtl: "Höger till vänster",
        formatMenu_Ltr: "Vänster till höger",
        formatMenu_Auto: "Kontext",
        formatMenu_SheetDirection: "Arkriktning",
        formatMenu_SheetRtl: "Höger till vänster",
        formatMenu_SheetLtr: "Vänster till höger",
        formatMenu_Indent: "Öka indrag",
        formatMenu_DecreaseIndent: "Minska indrag",
        formatMenu_ClearFormat: "Ta bort formatering",
        formatMenu_RowHeight: "Radhöjd",
        formatMenu_ColumnWidth: "Kolumnbredd",
        formatMenu_ShowRow: "Visa rad",
        formatMenu_HideRow: "Göm rad",
        formatMenu_ShowColumn: "Visa kolumn",
        formatMenu_HideColumn: "Göm kolumn",
        formatMenu_WrapText: "Radbryt text",
        formatMenu_Number: "Tal",
        formatMenu_FontArial: "Arial",
        formatMenu_FontComicSansMS: "Comic Sans MS",
        formatMenu_FontCourierNew: "Courier New",
        formatMenu_FontGeorgia: "Georgia",
        formatMenu_FontLucidaSansUnicode: "Lucida Sans Unicode",
        formatMenu_FontTahoma: "Tahoma",
        formatMenu_FontTimesNewRoman: "Times New Roman",
        formatMenu_FontTrebuchetMS: "Trebuchet MS",
        formatMenu_FontVerdana: "Verdana",
        formatMenu_FontName: "Teckensnitt",

        layoutMenu: "Layout",
        layoutMenu_SlideLayout: "Bildlayout...",
        layoutMenu_SlideDesign: "Bakgrundsformat...",
        layoutMenu_DefaultFormatting: "Standardformatering",
        layoutMenu_Textprop_Bold: "Halvfet",
        layoutMenu_Textprop_Italic: "Kursiv",
        layoutMenu_Textprop_Underline: "Understrykning",
        layoutMenu_Textprop_Strikethrough: "Genomstrykning",
        layoutMenu_TextProp: "Textegenskaper",
        LayoutMenu_RowHeight: "Radhöjd...",
        LayoutMenu_ColumnWidth: "Kolumnbredd...",
        LayoutMenu_ShowRow: "Visa rad",
        LayoutMenu_HideRow: "Göm rad",
        LayoutMenu_RenameSheet: "Byt namn på ark...",
        LayoutMenu_MoveSheet: "Flytta ark",

        tableMenu: "Tabell",
        tableMenu_Create: "Skapa...",
        tableMenu_CreateFromTemplate: "Skapa från mall",
        tableMenu_Delete: "Ta bort",
        tableMenu_SetTableColor: "Cellfärg",
        tableMenu_CreateTable: "Infoga tabell",
        tableMenu_Cell: "Cell",
        tableMenu_CellMergeCells: "Sammanfoga celler",
        tableMenu_CellAlignLeft: "Vänsterjustera",
        tableMenu_CellAlignCenter: "Centrera",
        tableMenu_CellAlignRight: "Högerjustera",
        tableMenu_CellClearContents: "Rensa innehåll",
        tableMenu_CellProperties: "Cellegenskaper...",
        tableMenu_Row: "Rad",
        tableMenu_InsertRowAbove: "Infoga rad ovanför",
        tableMenu_InsertRowBelow: "Infoga rad nedanför",
        tableMenu_MoveRowAbove: "Flytta rad uppåt",
        tableMenu_MoveRowBelow: "Flytta rad nedåt",
        tableMenu_RowInsertRow: "Infoga rad...",
        tableMenu_RowInsertRowAbove: "Infoga rad ovanför",
        tableMenu_RowInsertRowBelow: "Infoga rad nedanför",
        tableMenu_RowMoveRowAbove: "Flytta rad ovanför",
        tableMenu_RowMoveRowBelow: "Flytta rad nedanför",
        tableMenu_RowDelete: "Ta bort",
        tableMenu_RowRepeat: "Upprepa rubrikrad",
        tableMenu_InsertColumnBefore: "Infoga kolumn före",
        tableMenu_InsertColumnAfter: "Infoga kolumn efter",
        tableMenu_MoveColumnBefore: "Flytta kolumn åt vänster",
        tableMenu_MoveColumnAfter: "Flytta kolumn åt höger",
        tableMenu_ResizeColumn: "Ändra storlek på kolumn",
        tableMenu_ResizeColumns: "Ändra storlek på kolumner",
        tableMenu_MarkasCategory: "Markera som kategori",
        tableMenu_ColumnInsertColumn: "Infoga kolumn...",
        tableMenu_ColumnAddColumnBefore: "Infoga kolumn före",
        tableMenu_ColumnAddColumnAfter: "Infoga kolumn efter",
        tableMenu_ColumnMoveColumnAfter: "Flytta kolumn åt höger",
        tableMenu_ColumnMoveColumnBefore: "Flytta kolumn åt vänster",
        tableMenu_ColumnDelete: "Ta bort",
        tableMenu_ColumnSortAscending: "Sortera stigande",
        tableMenu_ColumnSortDescending: "Sortera fallande",
        tableMenu_Column: "Kolumn",
        tableMenu_Style: "Format",
        tableMenu_TableProperties: "Tabellegenskaper...",

        teamMenu: "Team",
        teamMenu_AddComment: "Lägg till kommentar",
        teamMenu_AssignCells: "Tilldela celler",
        teamMenu_AssignSection: "Tilldela ett avsnitt",
        teamMenu_EditAssignment: "Ändra tilldelning",
        teamMenu_MarkSectionComplete: "Markera avsnitt som slutfört",
        teamMenu_MarkAssignmentComplete: "Markera tilldelning som slutförd",
        teamMenu_WorkPrivatelyOnSection: "Arbeta privat med avsnitt",
        teamMenu_CancelPrivateWork: "Avbryt privat arbete",
        teamMenu_ApproveSection: "Godkänn avsnitt",
        teamMenu_ApproveAssignment: "Godkänn tilldelning",
        teamMenu_ReturnSectionForRework: "Returnera avsnitt för omarbetning",
        teamMenu_ReturnAssignmentForRework: "Returnera tilldelning för omarbetning",
        teamMenu_RemoveSectionAssignment: "Ta bort avsnittstilldelning",
        teamMenu_RemoveCellAssignment: "Ta bort celltilldelning",
        teamMenu_RemoveCompletedAssignments: "Ta bort slutförda tilldelningar",
        teamMenu_AboutThisSection: "Om det här avsnittet",
        teamMenu_AboutAssignment: "Om denna tilldelning",

        presentationMenu: "Presentation",
        presentationMenu_SlideShow: "Spela upp bildspel",
        presentationMenu_SlideShowWithCoview: "Spela upp delat bildspel",
        presentationMenu_SlideTransitions: "Tillämpa bildövergång...",
        presentationMenu_SlideShowFromCurrent: "Spela upp från aktuell bild",
        presentationMenu_EmptyCoviewInvites: "Inget aktivt delat bildspel",
        presentationMenu_CoviewInvites: "Aktivt delat bildspel",

        dataMenu: "Data",
        dataMenu_Sort: "Sortera...",
        dataMenu_SortAsc: "Sortera stigande",
        dataMenu_SortDesc: "Sortera fallande",
        dataMenu_ACL: "Skyddade områden",
        dataMenu_ACL_DELETE: "Ta bort alla behörigheter",
        dataMenu_Validity: "Validera",
        dataMenu_InstantFilter: "Snabbfilter",
        dataMenu_Validation: "Validering ...",

        toolsMenu: "Verktyg",
        toolsMenu_AutoComplete: "Automatiska cellifyllnadsposter",
        toolsMenu_SelectDictionary: "Ordböcker för stavningskontroll",
        toolsMenu_Dictionary_ca_CT: "Katalanska",
        toolsMenu_Dictionary_cs_CZ: "Tjeckiska (Tjeckien)",
        toolsMenu_Dictionary_da_DK: "Danska (Danmark)",
        toolsMenu_Dictionary_nl_NL: "Nederländska (Nederländerna)",
        toolsMenu_Dictionary_en_AU: "Engelska (Australien)",
        toolsMenu_Dictionary_en_GB: "Engelska (Storbritannien)",
        toolsMenu_Dictionary_en_US: "Engelska (USA)",
        toolsMenu_Dictionary_fi_FI: "Finska (Finland)",
        toolsMenu_Dictionary_fr_FR: "Franska (Frankrike)",
        toolsMenu_Dictionary_fr_CA: "Franska (Kanada)",
        toolsMenu_Dictionary_de_DE: "Tyska (Tyskland)",
        toolsMenu_Dictionary_de_CH: "Tyska (Schweiz)",
        toolsMenu_Dictionary_el_GR: "Grekiska (Grekland)",
        toolsMenu_Dictionary_it_IT: "Italienska (Italien)",
        toolsMenu_Dictionary_pl_PL: "Polska (Polen)",
        toolsMenu_Dictionary_pt_BR: "Portugisiska (Brasilien)",
        toolsMenu_Dictionary_pt_PT: "Portugisiska (Portugal)",
        toolsMenu_Dictionary_ru_RU: "Ryska (Ryssland)",
        toolsMenu_Dictionary_es_ES: "Spanska (Spanien)",
        toolsMenu_Dictionary_sv_SE: "Svenska (Sverige)",
        toolsMenu_Dictionary_nb_NO: "Norska (Bokmål)",
        toolsMenu_Dictionary_nn_NO: "Norska (Nynorsk)",
        toolsMenu_Dictionary_he_IL: "Hebreiska (Israel)",
        toolsMenu_SpellCheck: "Kör manuell stavningskontroll...",
        toolsMenu_Preferences: "Inställningar",
        toolsMenu_Task: "Uppgift",
        toolsMenu_Task_Assigntask: "Tilldela en uppgift",
        teamMenu_AssignSlide: "Tilldela presentationsbild",
        teamMenu_AssignSlides: "Tilldela presentationsbilder",
        teamMenu_EditSlide: "Ändra bildtilldelning",
        teamMenu_ReopenSlideAssignment: "Öppna bildtilldelning igen",
        teamMenu_ReopenSlideAssignments: "Öppna bildtilldelningar igen",
        teamMenu_ReassignSlide: "Omtilldela bild",
        teamMenu_ReassignSlides: "Omtilldela bilder",
        teamMenu_MarkSlidesComplete: "Markera bild som slutförd",
        teamMenu_MarkSlidesCompletes: "Markera bilder som slutförda",
        teamMenu_ApproveSlide: "Godkänn bild",
        teamMenu_ApproveSlides: "Godkänn bilder",
        teamMenu_ReturnForRework: "Returnera bild för omarbetning",
        teamMenu_ReturnForReworks: "Returnera bilder för omarbetning",
        teamMenu_RemoveAssignment: "Ta bort bildtilldelning",
        teamMenu_AboutThisSlide: "Om denna bild",

        addOnsMenu: "Tillägg",

        helpMenu: "Hjälp",
        helpMenu_About: "Om",
        helpMenu_Overview: "Hjälpinnehåll",
        helpMenu_NewFeatures: "Nyheter",
        helpMenu_Tour: "Guidad rundtur",

        accel_fileMenu_Save: "Ctrl+S",
        accel_fileMenu_Save_Mac: "\u2318S",
        accel_fileMenu_Print: "Ctrl+P",
        accel_fileMenu_Print_Mac: "\u2318P",
        accel_editMenu_SelectAll: "Ctrl+A",
        accel_editMenu_SelectAll_Mac: "\u2318A",
        accel_editMenu_Undo: "Ctrl+Z",
        accel_editMenu_Undo_Mac: "\u2318Z",
        accel_editMenu_Redo: "Ctrl+Y",
        accel_editMenu_Redo_Mac: "\u2318Y",
        accel_editMenu_Cut: "Ctrl+X",
        accel_editMenu_Cut_Mac: "\u2318X",
        accel_editMenu_Copy: "Ctrl+C",
        accel_editMenu_Copy_Mac: "\u2318C",
        accel_editMenu_Paste: "Ctrl+V",
        accel_editMenu_Paste_Mac: "\u2318V",
        accel_editMenu_Find: "Ctrl+F",
        accel_editMenu_Find_Mac: "\u2318F",
        accel_insertMenu_Link: "Ctrl+K",
        accel_insertMenu_Link_Mac: "\u2318K",
        accel_insertMenu_Header: "Ctrl+Skift+H",
        accel_insertMenu_Header_Mac: "\u21e7\u2318H",
        accel_insertMenu_Footer: "Ctrl+Skift+F",
        accel_insertMenu_Footer_Mac: "\u21e7\u2318F",
        accel_formatMenu_Textprop_Bold: "Ctrl+B",
        accel_formatMenu_Textprop_Bold_Mac: "\u2318B",
        accel_formatMenu_Textprop_Italic: "Ctrl+I",
        accel_formatMenu_Textprop_Italic_Mac: "\u2318I",
        accel_formatMenu_Textprop_FormatPainter: "Ctrl+Skift+C, Ctrl+Skift+V",
        accel_formatMenu_Textprop_FormatPainter_Mac: "\u21e7\u2318C, \u21e7\u2318V",
        accel_formatMenu_Textprop_Underline: "Ctrl+U",
        accel_formatMenu_Textprop_Underline_Mac: "\u2318U",
        accel_formatMenu_Headingprop_P: "Ctrl+Skift+0",
        accel_formatMenu_Headingprop_H1: "Ctrl+Skift+1",
        accel_formatMenu_Headingprop_H2: "Ctrl+Skift+2",
        accel_formatMenu_Headingprop_H3: "Ctrl+Skift+3",
        accel_formatMenu_Headingprop_H4: "Ctrl+Skift+4",
        accel_formatMenu_Headingprop_H5: "Ctrl+Skift+5",
        accel_formatMenu_Headingprop_H6: "Ctrl+Skift+6",
        accel_formatMenu_Superscript: "Ctrl+.",
        accel_formatMenu_Superscript_Mac: "\u2318.",
        accel_formatMenu_Subscript: "Ctrl+,",
        accel_formatMenu_Subscript_Mac: "\u2318,",
        accel_formatMenu_Left: "Ctrl+Skift+L",
        accel_formatMenu_Left_Mac: "\u21e7\u2318L",
        accel_formatMenu_Right: "Ctrl+Skift+R",
        accel_formatMenu_Right_Mac: "\u21e7\u2318R",
        accel_formatMenu_Center: "Ctrl+Skift+E",
        accel_formatMenu_Center_Mac: "\u21e7\u2318E",
        accel_formatMenu_Justify: "Ctrl+Skift+J",
        accel_formatMenu_Justify_Mac: "\u21e7\u2318J",
        accel_formatMenu_Indent: "Ctrl+M",
        accel_formatMenu_Indent_Mac: "\u2318M",
        accel_formatMenu_DecreaseIndent: "Ctrl+Skift+M",
        accel_formatMenu_DecreaseIndent_Mac: "\u21e7\u2318M",
        accel_teamMenu_AddComment: "Skift+F2",

        ctxMenuSmartTable: 'Tabell',
        ctxMenuTableProperties: "Tabellegenskaper",
        ctxMenuDeleteST: 'Ta bort',
        ctxMenuDeleteSTTable: 'Ta bort tabell',
        ctxMenuChgSTStyle: 'Ändra format',
        ctxMenuShowCaption: 'Visa bildtext',
        ctxMenuHideCaption: 'Göm bildtext',
        ctxMenuResizeST: 'Ändra storlek',
        ctxMenuResizeColumnsST: 'Ändra storlek på kolumner',
        ctxMenuSTRow: 'Rad',
        ctxMenuAddSTRowAbv: 'Infoga rad ovanför',
        ctxMenuAddSTRowBlw: 'Infoga rad nedanför',
        ctxMenuMoveSTRowUp: 'Flytta rad ovanför',
        ctxMenuMoveSTRowDown: 'Flytta rad nedanför',
        ctxMenuDelSTRow: 'Ta bort',
        ctxMenuRepeatRow: 'Upprepa rubrikrad',
        ctxMenuSTCol: 'Kolumn',
        ctxMenuAddSTColBfr: 'Infoga kolumn före',
        ctxMenuAddSTColAft: 'Infoga kolumn efter',
        ctxMenuMoveSTColBefore: 'Flytta kolumn åt vänster',
        ctxMenuMoveSTColAfter: 'Flytta kolumn åt höger',
        ctxMenuDelSTCol: 'Ta bort',
        ctxMenuSortSTColAsc: 'Sortera stigande',
        ctxMenuSortSTColDesc: 'Sortera fallande',
        ctxMenuShowAllFacets: 'Visa kategorier',
        ctxMenuHideAllFacets: 'Göm kategorier',
        ctxMenuSTCell: 'Cell',
        ctxMenuMergeCells: 'Sammanfoga celler',
        ctxMenuMergeDown: 'Sammanfoga med cell nedanför',
        ctxMenuVerSplit: 'Dela vertikalt',
        ctxMenuHorSplit: 'Dela horisontellt',
        ctxMenuSplitCells: 'Dela celler...',
        splitCells: 'Dela cell',
        ctxMenuAlignTextLeft: 'Vänsterjustera',
        ctxMenuAlignTextCenter: 'Centrera',
        ctxMenuAlignTextRight: 'Högerjustera',
        ctxMenuClearSTCellContent: 'Rensa innehåll',
        ctxMenuMakeHeaderRow: 'Använd markerad rad som rubrik',
        ctxMenuMakeNonHeaderRow: 'Ta bort rubrikformat',
        ctxMenuMakeHeaderCol: 'Använd markerad kolumn som rubrik',
        ctxMenuMakeNonHeaderCol: 'Ta bort rubrikformat',
        SHEET_CONTEXT_Hide: "Dölj", // hide row, column or sheet
        SHEET_CONTEXT_Show: "Visa", // show row, column
        SHEET_CONTEXT_MoveSheet: "Flytta...", // move sheet
        SHEET_CONTEXT_InsertSheet: "Infoga...", // insert sheet
        SHEET_CONTEXT_DeleteSheet: "Ta bort...", // delete sheet	
        SHEET_CONTEXT_DuplicateSheet: "Duplicera...", // duplicate sheet
        SHEET_CONTEXT_RenameSheet: "Byt namn...", // rename sheet
	
        ctxMenu_Image_WrapText: "Radbryt text",
        ctxMenu_Image_WrapText_Inline: "Justera med text",
        ctxMenu_Image_WrapText_Square: "Kvadrat",
        ctxMenu_Image_WrapText_TopBottom: "Överst och nederst",
        ctxMenu_Image_WrapText_Behind: "Bakom text",
        ctxMenu_Image_WrapText_InFront: "Framför text",
        ctxMenu_Image_WrapText_Other: "Mer radbruten text",
        ctxMenu_Image_WrapText_BothSides: "Båda sidorna",
        ctxMenu_Image_WrapText_LeftOnly: "Endast vänster",
        ctxMenu_Image_WrapText_RightOnly: "Endast höger",
        ctxMenu_Image_WrapText_LargestOnly: "Endast största",

        ctxMenu_Shape_AddText: "Lägg till text",

        ctxMenu_Range_ACL: "Skydda intervall",
        ctxMenu_Sheet_ACL: "Skydda ark",

        ctxMenu_HeaderFooter: "Sidhuvud/sidfot",
        ctxMenu_HeaderFooter_DiffFirst: "Endast första sidan",
        ctxMenu_HeaderFooter_DiffOddEven: "Olika udda och jämna sidor",
        ctxMenu_HeaderFooter_LinkToPre: "Länka till föregående",

        ctxMenu_copy: "Kopiera",
        ctxMenu_paste: "Klistra in",
        ctxMenu_delete: "Ta bort",
        ctxMenu_cut: "Klipp ut",
        ctxMenu_select: "Välj",
        ctxMenu_properties: "Egenskaper",
        ctxMenu_bringToFront: "I förgrunden",
        ctxMenu_sendToBack: "I bakgrunden",
        ctxMenu_arrange: "Placera",
        ctxMenu_sendBackward: "Längre bak",
        ctxMenu_sendForward: "Längre fram",
        ctxMenu_fontStyle: "Teckenformat",
        ctxMenu_selectStyle: "Välj format",
        ctxMenu_fontSize: "Teckenstorlek",
        ctxMenu_fontFamily: "Teckenfamilj",
        ctxMenu_bold: "Halvfet",
        ctxMenu_italic: "Kursiv",
        ctxMenu_u: "Understrykning",
        ctxMenu_strike: "Genomstrykning",
        ctxMenu_super: "Upphöjt",
        ctxMenu_sub: "Nedsänkt",
        ctxMenu_color: "Färg",
        ctxMenu_bgcolor: "Bakgrundsfärg",
        ctxMenu_highcolor: "Framhävningsfärg",
        ctxMenu_restart: "Starta om listan",
        ctxMenu_continue: "Fortsätt med listan",
        ctxMenu_separate: "Separat lista",
        ctxMenu_join: "Koppla till föregående lista",
        ctxMenu_setNumberVal: "Välj numreringsvärde ...",
        webClipboardInfoTitle: "Urklipp",
        webClipboardInfoOKBtn: "OK",
        webClipboardInfoCutMsg: "Säkerhetsinställningarna för webbläsaren förhindrar automatiskt kopiering. Tryck på Ctrl+X i stället.",
        webClipboardInfoCopyMsg: "Säkerhetsinställningarna för webbläsaren förhindrar automatiskt kopiering. Tryck på Ctrl+C i stället.",
        webClipboardInfoPasteMsg: "Webbläsarens säkerhetsinställningar förhindrar att den här redigeraren öppnar Urklipp. Tryck på Ctrl+V i stället.",

        clearTrackChangeConfirmMsg: "Alla färger som markerar ändringar i dokumentet kommer att tas bort. Vill du fortsätta?"
});

