/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
	fileMenu: "Arkiv",
	fileMenu_New: "Nytt",
	fileMenu_NewDocument: "Dokument",
	fileMenu_NewDocumentfromTemplate: "Dokument från mall",
	fileMenu_NewPresentation: "Presentation",
	fileMenu_NewPresentationfromTemplate: "Presentation från mall",
	fileMenu_NewSpreadsheet: "Kalkylark",
	fileMenu_Open: "Öppna",
//	fileMenu_Close: "Close",
	fileMenu_Discard: "Ta bort",
	fileMenu_Save: "Spara",
//	fileMenu_SaveAs: "Save As...",
//	fileMenu_SaveAsDraft: "as Draft",
//	fileMenu_SaveInMyDocs: "in My Documents",
//	fileMenu_SaveToSymphony: "to Lotus Symphany",
	fileMenu_ShareWith: "Dela med...	",
	fileMenu_ExportAsPDF: "Exportera som PDF",
	fileMenu_WebPreview: "Webbförhandsgranskning",
	fileMenu_PrintPreview: "Förhandsgranska",
	fileMenu_RecentFile: "Senaste filer",
	fileMenu_Print: "Skriv ut...",
	editMenu: "Redigera",
	editMenu_Undo: "Ångra",
	editMenu_Redo: "Gör om",
	editMenu_Cut: "Klipp ut",
	editMenu_Copy: "Kopiera",
	editMenu_Paste: "Klistra in",
	editMenu_DeleteSlide:"Ta bort presentationsbild",
	editMenu_SelectAll: "Markera allt",
	editMenu_Find: "Sök...",
	editMenu_Replace: "Ersätt...",
	editMenu_DeleteSheet: "Ta bort ark",
	editMenu_DuplicateSheet: "Duplicera ark",
	editMenu_DeleteRow: "Ta bort rad",
	editMenu_DeleteColumn: "Ta bort kolumn",
	editMenu_ClearCell: "Rensa cell",
	viewMenu: "Visa",
	viewMenu_Master: "Bakgrund",
	viewMenu_Notifications: "Meddelanden",
	viewMenu_ShowHideIndicators: "Visa/göm samredigeringsindikatorer",
	viewMenu_SlideSorter: "Visa bildsortering",
	viewMenu_SpeakerNotes: "Visa stödanteckningar",
	viewMenu_NextSlide: "Nästa presentationsbild",
	viewMenu_PrevSlide: "Föregående presentationsbild",
	createMenu: "Skapa",
	createMenu_NewSlide: "Ny presentationsbild",
	createMenu_DuplicateSlide: "Duplicera presentationsbild",
	createMenu_ImageFromFile: "Grafik från fil",
	createMenu_TextBox: "Textruta",
	createMenu_Task: "Uppgift",
    formatMenu_Text_Direction: "Textriktning",
    formatMenu_Ltr: "Vänster till höger",
    formatMenu_Rtl: "Höger till vänster",  	
    formatMenu_Horizontal_Align: "Justera horisontellt",
    formatMenu_Vertical_Align: "Justera vertikalt",
    formatMenu_Align_Top: "Överkant",
    formatMenu_Align_Middle: "Centrera",
    formatMenu_Align_Bottom: "Underkant",
	layoutMenu: "Layout",
	layoutMenu_SlideLayout: "Bildlayout",
	layoutMenu_SlideDesign: "Bakgrundsformat",
	tableMenu: "Tabell",
	tableMenu_CreateTable: "Infoga tabell",
	tableMenu_Cell: "Cell",
	tableMenu_CellAlignLeft: "Vänsterjustera text",
	tableMenu_CellAlignCenter: "Centrera text",
	tableMenu_CellAlignRight: "Högerjustera text",
	tableMenu_CellClearContents: "Rensa innehåll",
	tableMenu_Row: "Rad",
	tableMenu_RowAddRowAbove: "Lägg till rad ovanför",
	tableMenu_RowAddRowBelow: "Lägg till rad nedanför",
	tableMenu_RowMoveRowAbove: "Flytta rad uppåt",
	tableMenu_RowMoveRowBelow: "Flytta rad nedåt",
	tableMenu_RowDelete: "Ta bort",
	tableMenu_ColumnAddColumnBefore: "Lägg till kolumn före",
	tableMenu_ColumnAddColumnAfter: "Lägg till kolumn efter",
	tableMenu_ColumnMoveColumnAfter: "Flytta kolumn åt höger",
	tableMenu_ColumnMoveColumnBefore: "Flytta kolumn åt vänster",
	tableMenu_ColumnDelete: "Ta bort",
	tableMenu_ColumnSortAscending: "Sortera stigande",
	tableMenu_ColumnSortDescending: "Sortera fallande",
	tableMenu_Column: "Kolumn",
	tableMenu_Delete: "Ta bort",
	presentationMenu: "Presentation",
	presentationMenu_SlideShow: "Spela upp bildspel",
	presentationMenu_SlideShowFromCurrent: "Spela upp från aktuell bild",
	toolsMenu: "Verktyg",
	toolsMenu_Task: "Uppgift",
	helpMenu: "Hjälp",
	helpMenu_Overview: "Hjälpinnehåll"
})

