({	
	createTaskSummary: "${0} created the task.",
	completeTaskSummary: "${0} marked the task complete.",
	editTaskSummary5: "${0} edited the task's ${1}, ${2}, ${3}, ${4} and ${5}.",
	editTaskSummary4: "${0} edited the task's ${1}, ${2}, ${3} and ${4}.",
	editTaskSummary3: "${0} edited the task's ${1}, ${2} and ${3}.",
	editTaskSummary2: "${0} edited the task's ${1} and ${2}.",
	editTaskSummary1: "${0} edited the task's ${1}.",
	editTaskSummary0: "${0} edited the task.",
	removeTaskSummary: "${0} removed the task.",
	reopenTaskSummary: "${0} reopened the task.",
	reassignTaskSummary: "${0} reassigned the ${1} from ${2} to ${3}.",
	reassignTaskSummary2: "${0} reassigned the assignee from ${1} to ${2}, and the reviewer from ${3} to ${4}.",
	workPrivateSummary: "${0} began working privately on this task.",
	approveTaskSummary: "${0} approved this task.",
	rejectTaskSummary: "${0} rejected this task.",
	rejectTaskSummary2: "${0} returned this task to ${1} for rework.",
	submitTaskSummary: "${0} submitted private work back to the document.",
	cancelPrivateSummary: "${0} cancelled the private work.",
	updatedFieldsDesc: "${0}: ${1} -> ${2}",
	fieldAssignee: "assignee",
	fieldDuedate: "due date",
	fieldDescription: "description",
	fieldReviewer: "reviewer",
	fieldTitle: "title",
	emptyFieldValue: "[Unassigned]",
	errorAddMember:"There is no access to the activity server to add assignees or reviewers. Try again later.",
	errorCreateActivity:"There is no access to the activity server to create the activity. Try again later.",
	errorLoadActivity:"There is no access to the activity server to load assignments. Try again later.",
	errorCreateAssignment: "There is no access to the activity server to create the assignment. Try again later.",
	errorDeleteAssignment: "There is no access to the activity server to delete assignments. Try again later.",
	errorupdateAssignment: "There is no access to the activity server to update assignments. Try again later.",
	errorSubmitAssignment: "You cannot perform this action. Check to see if you have permission to do it.",	
	errorAddMember2:"There is no access to the server to add assignees or reviewers. Try again later.",
	errorCreateActivity2:"There is no access to the server to create the activity. Try again later.",
	errorLoadActivity2:"There is no access to the server to load assignments. Try again later.",
	errorCreateAssignment2: "There is no access to the server to create the assignment. Try again later.",
	errorDeleteAssignment2: "There is no access to the server to delete assignments. Try again later.",
	errorupdateAssignment2: "There is no access to the server to update assignments. Try again later."	
})