({
	ORIENTATION_LABEL: "Orientation",
	PORTRAIT: "Portrait",
	LANDSCAPE: "Paysage",
	HEADER: "En-tête",
	FOOTER: "Pied de page",
	MARGINS_LABEL: "Marges",
	TOP: "Haut :",
	BOTTOM: "Bas :",
	LEFT: "Gauche :",
	RIGHT: "Droite :",
	PAPER_FORMAT_LABEL: "Format de papier",
	PAPER_SIZE_LABEL: "Taille de papier :",
	HEIGHT: "Hauteur :",
	WIDTH: "Largeur :",
	HEIGHT_DESC:"Hauteur du papier, en centimètres",
	HEIGHT_DESC2:"Hauteur du papier, en pouces",
	WIDTH_DESC:"Largeur du papier, en centimètres",
	WIDTH_DESC2:"Largeur du papier, en pouces",
	BOTTOM_DESC:"Marge inférieure, en centimètres",
	BOTTOM_DESC2:"Marge inférieure, en pouces",
	TOP_DESC:"Marge supérieure, en centimètres",
	TOP_DESC2:"Marge supérieure, en pouces",
	LEFT_DESC:"Marge de gauche, en centimètres",
	LEFT_DESC2:"Marge de gauche, en pouces",
	RIGHT_DESC:"Marge de droite, en centimètres",
	RIGHT_DESC2:"Marge de droite, en pouces",
	CM_LABEL: "cm",
	LETTER: "Letter",
	LEGAL: "Legal",
	TABLOID: "Tabloid",
	USER: "Utilisateur",
	SIZE1: "Env. #6 3/4",
	SIZE2: "Env. Monarch",
	SIZE3: "Env. #9",
	SIZE4: "Env. #10",
	SIZE5: "Env. #11",
	SIZE6: "Env. #12",
	SIZE7: "16 kai",
	SIZE8: "32 kai",
	SIZE9: "32 kai grand",
	INVALID_MSG: "La saisie n'est pas valide et a été automatiquement corrigée. Essayez une autre valeur si vous souhaitez obtenir un autre résultat."
})
	
