/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
    Arrow01_Gray: "灰色箭头 01",
    Arrow02_Gray: "灰色箭头 02",
    Arrow03_Red: "红色箭头 03",
    Arrow04_Blue: "蓝色箭头 04",
    Arrow05_Blue: "蓝色箭头 05",
    Arrow06_Yellow: "黄色箭头 06",
    Arrow07_Red: "红色箭头 07",
    Arrow08_Gray: "灰色箭头 08",
    Arrow09_Orange: "橙色箭头 09",
    Arrow10_Blue: "蓝色箭头 10",
    Arrow11_Blue: "蓝色箭头 11",
    Arrow12_Green: "绿色箭头 12",
    Arrow13_Blue: "蓝色箭头 13",
    Arrow14_Green: "绿色箭头 14",
    Arrow15_Orange: "橙色箭头 15",
    Arrow16_Gray: "灰色箭头 16",
    CircleArrow01_Green: "绿色圆形箭头 01",
    CircleArrow02_Multi: "多色圆形箭头 02",
    CircleArrow03_Multi: "多色圆形箭头 03",
    CircleArrow04_Multi: "多色圆形箭头 04",
    CircleArrow05_Multi: "多色圆形箭头 05",
    CircleArrow06_Multi: "多色圆形箭头 06",
    CircleArrow07_Blue: "蓝色圆形箭头 07",
    CircleArrow08_Green: "绿色圆形箭头 08",
    CircleArrow09_Multi: "多色圆形箭头 09",
    CurvedArrow01_Gray: "灰色曲线箭头 01",
    CurvedArrow02_Blue: "蓝色曲线箭头 02",
    CurvedArrow03_Blue: "蓝色曲线箭头 03",
    CurvedArrow04_Orange: "橙色曲线箭头 04",
    CurvedArrow05_Red: "红色曲线箭头 05",
    CurvedArrow06_Blue: "蓝色曲线箭头 06",
    CurvedArrow07_Purple: "紫色曲线箭头 07",
    CurvedArrow08_Green: "绿色曲线箭头 08",
    CurvedArrow09_Gray: "灰色曲线箭头 09",
    CurvedArrow10_Blue: "蓝色曲线箭头 10",
    CurvedArrow11_Orange: "橙色曲线箭头 11",
    CurvedArrow12_Blue: "蓝色曲线箭头 12",
    CurvedArrow13_Green: "绿色曲线箭头 13",
    CurvedArrow14_Brown: "棕色曲线箭头 14",
    CurvedArrow15_Blue: "蓝色曲线箭头 15",
    CurvedArrow16_Gray: "灰色曲线箭头 16",
    CurvedArrow17_Gray: "灰色曲线箭头 17",
    CurvedArrow18_Gray: "灰色曲线箭头 18",
    CurvedArrow19_Gray: "灰色曲线箭头 19",
    CurvedArrow20_Gray: "灰色曲线箭头 20",
    TrendArrow01_Red: "红色趋势箭头 01",
    TrendArrow02_Green: "绿色趋势箭头 02",
    TrendArrow03_Orange: "橙色趋势箭头 03",
    TrendArrow04_Red: "红色趋势箭头 04",
    TrendArrow05_Orange: "橙色趋势箭头 05",
    TrendArrow06_Blue: "蓝色趋势箭头 06",
    TrendArrow07_Orange: "橙色趋势箭头 07",
    TrendArrow08_Yellow: "黄色趋势箭头 08",
    TrendArrow09_Blue: "蓝色趋势箭头 09",
    TrendArrow10_Blue: "蓝色趋势箭头 10",
    TrendArrow11_Blue: "蓝色趋势箭头 11",
    TrendArrow12_Blue: "蓝色趋势箭头 12",
    TrendArrow13_Red: "红色趋势箭头 13",
    TrendArrow14_Multi: "多色趋势箭头 14",
    TrendArrow15_Blue: "蓝色趋势箭头 15",
    Bullet01_Circle_DarkRed: "深红色圆形项目符号 01",
    Bullet02_Circle_Blue: "蓝色圆形项目符号 02",
    Bullet03_Circle_Green: "绿色圆形项目符号 03",
    Bullet04_Square_Black: "黑色正方形项目符号 04",
    Bullet05_Square_Orange: "橙色正方形项目符号 05",
    Bullet06_Square_Purple: "紫色正方形项目符号 06",
    Bullet07_Diamond_Blue: "蓝色菱形项目符号 07",
    Bullet08_Diamond_LightBlue: "浅蓝色菱形项目符号 08",
    Bullet09_Diamond_Red: "红色菱形项目符号 09",
    Bullet10_Star_Yellow: "黄色星形项目符号 10",
    Bullet11_Star_Blue: "蓝色星形项目符号 11",
    Bullet12_Triangle_Blue: "蓝色三角形项目符号 12",
    Bullet13_Triangle_DarkGreen: "深绿色三角形项目符号 13",
    Bullet14_Arrow_Red: "红色箭头项目符号 14",
    Bullet15_Arrow_Blue: "蓝色箭头项目符号 15",
    Bullet16_Box_Blue: "蓝色箱子项目符号 16",
    Bullet17_Box_Red: "红色箱子项目符号 17",
    Bullet18_Asterisk_LightBlue: "浅蓝色星号项目符号 18",
    Bullet19_Leaves_Red: "红色叶子项目符号 19",
    Bullet20_Target_Blue: "蓝色靶子项目符号 20",
    Bullet21_Arrow_Blue: "蓝色箭头项目符号 21",
    Bullet22_Arrow_DarkBlue: "深蓝色箭头项目符号 22",
    Bullet23_Arrow_Brown: "棕色箭头项目符号 23",
    Bullet24_Flag_Red: "红色旗帜项目符号 24",
    Bullet25_Flag_Green: "绿色旗帜项目符号 25",
    Bullet26_X_Red: "红色 X 项目符号 26",
    Bullet27_X_Black: "黑色 X 项目符号 27",
    Bullet28_Checkmark_Green: "绿色勾选项目符号 28",
    Bullet29_Checkmark_Blue: "蓝色勾选项目符号 29",
    Bullet30_Square_DarkRed: "深红色正方形项目符号 30",
    camera: "摄像头",
    computer1: "计算机 1",
    computer2: "计算机 2",
    computer3: "计算机 3",
    Computer_Cloud: "计算机云",
    Computer_Desktop: "台式计算机",
    Computer_Laptop_Black: "黑色笔记本电脑",
    Computer_Laptop_Silver: "银色笔记本电脑",
    Database: "数据库",
    evelope: "信封",
    newspapers: "报纸",
    openevelope: "打开的信封",
    Server: "服务器",
    speaker: "扬声器",
    WirelessAccessPoint: "无线接入点",
    Cycle01_Transparent: "透明循环 01",
    Cycle02_Transparent_Blue: "蓝色透明循环 02",
    Cycle03_Blue: "蓝色循环 03",
    Cycle04_Blue: "蓝色循环 04",
    Cycle05: "循环 05",
    Cycle06: "循环 06",
    Cycle07: "循环 07",
    Cycle08_Blue: "蓝色循环 08",
    Cycle09_Orange: "橙色循环 09",
    Donut01_LightBlue: "浅蓝色圆环 01",
    Donut02_Blue: "蓝色圆环 02",
    Donut03_Blue: "蓝色圆环 03",
    Donut04_DarkBlue: "深蓝色圆环 04",
    Donut05_DarkBlue: "深蓝色圆环 05",
    Donut06_Blue: "蓝色圆环 06",
    Donut07_Blue: "蓝色圆环 07",
    Graph: "图形",
    People01_Blue: "蓝色人群 01",
    People02: "人群 02",
    Pillars01_Orange: "橙色柱子 01",
    Pillars02_LightBlue: "浅蓝色柱子 02",
    Process01_Blue: "蓝色流程 01",
    Process02_Blue: "蓝色流程 02",
    Process03_Blue: "蓝色流程 03",
    Process04_GoUp_Blue: "蓝色上行流程 04",
    Process05_GoUp_Red: "红色上行流程 05",
    Process06_GoUp_Yellow: "黄色上行流程 06",
    Process07_Blue: "蓝色流程 07",
    Pyramid01: "金字塔 01",
    Pyramid02_Blue: "蓝色金字塔 02",
    Pyramid03: "金字塔 03",
    Radial01_Green: "绿色辐射图 01",
    Radial02_Green: "绿色辐射图 02",
    Radial03_Sphere: "球形辐射图 03",
    Radial04_Sphere_Red: "红色球形辐射图 04",
    Radial05_Sphere_Blue: "蓝色球形辐射图 05",
    Radial06_Arrows_DarkBlue: "深蓝色箭头辐射图 06",
    Radial07_Arrows_DarkBlue: "深蓝色箭头辐射图 07",
    Section_Circle: "圆形分块",
    Section_Cubes01: "立方体分块 01",
    Section_Cubes02_Blue: "蓝色立方体分块 02",
    Section_Cubes03_Orange: "橙色立方体分块 03",
    Section_Cubes04: "立方体分块 04",
    Section_Cubes05: "立方体分块 05",
    Section_Cuboids01_Blue: "蓝色长方体分块 01",
    Section_Cuboids02_Blue: "蓝色长方体分块 02",
    Section_Cuboids03: "长方体分块 03",
    Section_Gears01: "齿轮分块 01",
    Section_Gears02: "齿轮分块 02",
    Section_Gears03: "齿轮分块 03",
    Section_Hexagon04_Orange: "橙色六边形分块 04",
    Section_Hexagons01: "六边形分块 01",
    Section_Hexagons02_Blue: "蓝色六边形分块 02",
    Section_Hexagons03_Blue: "蓝色六边形分块 03",
    Section_Leaves01_LightBlue: "浅蓝色叶子分块 01",
    Section_Leaves02_Green: "绿色叶子分块 02",
    Section_Pasters01: "贴纸分块 01",
    Section_Pasters02_Blue: "蓝色贴纸分块 02",
    Section_Puzzle01: "拼图分块 01",
    Section_Puzzle02: "拼图分块 02",
    Section_Puzzle03: "拼图分块 03",
    Section_Rectangles: "矩形分块",
    Section_Squares: "正方形分块",
    Section_Triangle: "三角形分块",
    Target: "目标",
    Venn01: "维恩图 01",
    Venn02: "维恩图 02",
    Venn03: "维恩图 03",
    Venn04: "维恩图 04",
    Venn05: "维恩图 05",
    Venn06_Blue: "蓝色维恩图 06",
    Venn07_Blue: "蓝色维恩图 07",
    Venn08: "维恩图 08",
    Blackboard: "黑板",
    Books: "书籍",
    Books1: "书籍 1",
    books2: "书籍 2",
    Chalk: "粉笔",
    clipboard: "剪贴板",
    clock: "时钟",
    Globe: "地球仪",
    Glue: "胶水",
    GraduationCap: "毕业帽",
    magnifyingglass: "放大镜",
    Microscope: "显微镜",
    Notebook: "笔记本",
    notepad1: "记事本 1",
    notepad2: "记事本 2",
    notepad3: "记事本 3",
    PaperClip_Blue: "蓝色回形针",
    PaperClip_Red: "红色回形针",
    Pencil: "铅笔",
    Ruler: "标尺",
    TestTubes: "试管",
    thumbtack: "图钉",
    clouds: "云朵",
    DrippingFaucet: "滴水的龙头",
    Earth: "地球",
    EndangeredAnimals1: "濒危动物 1",
    EndangeredAnimals2: "濒危动物 2",
    GreenCar: "绿色汽车",
    GreenFactory: "绿色工厂",
    GreenHouse: "绿色房屋",
    Leaf1: "叶子 1",
    Leaf2: "叶子 2",
    lightbulb: "灯泡",
    LightBulb_Flourescent_Off: "熄灭的荧光灯泡",
    LightBulb_Flourescent_On: "点亮的荧光灯泡",
    LightBulb_Standard_Off1: "熄灭的标准灯泡 1",
    LightBulb_Standard_Off2: "熄灭的标准灯泡 2",
    LightBulb_Standard_On: "点亮的标准灯泡",
    lightningcloud: "带闪电的云朵",
    Pollution_Car: "有污染的汽车",
    Pollution_Factory: "有污染的工厂",
    Raindrop: "雨滴",
    RecycleBin: "回收站",
    RecycleSymbol: "回收符号",
    RenewableEnergySymbol: "可再生能源符号",
    RenewableEnergy_Solar: "可再生太阳能",
    RenewableEnergy_Water: "可再生水能",
    RenewableEnergy_Wind: "可再生风能",
    sun: "太阳",
    Sun1: "太阳 1",
    Sun2: "太阳 2",
    sundandcloud: "太阳和云朵",
    world: "世界",
    Agreement: "协议",
    ATM01: "ATM 01",
    ATM02: "ATM 02",
    Balance_Balanced1: "平衡天平 1",
    Balance_Balanced2: "平衡天平 2",
    Balance_Unbalanced1: "不平衡天平 1",
    Balance_Unbalanced2: "不平衡天平 2",
    Calculator: "计算器",
    Chart_Decrease1: "下降图表 1",
    Chart_Decrease2: "下降图表 2",
    Chart_Increase1: "上升图表 1",
    Chart_Increase2: "上升图表 2",
    Chart_Plateau: "平稳图表",
    Check: "支票",
    Contract: "合同",
    CreditCard_Black: "黑色信用卡",
    CreditCard_Cut: "剪切的信用卡",
    CreditCard_Gold: "金色信用卡",
    Currency_Dollar: "美元货币",
    Currency_Dollars: "多张美元货币",
    Currency_Stack: "一叠货币",
    Currency_StackCoins: "一堆硬币和纸币",
    GoldBar: "金条",
    GoldBar_Stack: "金条堆",
    MoneyBag01: "钱袋 01",
    MoneyBag02: "钱袋 02",
    PercentSign: "百分号",
    PiggyBank01_Broken: "砸碎的储蓄罐 02",
    PiggyBank02_Broken: "砸碎的储蓄罐 02",
    PiggyBank_Coins: "硬币储蓄罐",
    PiggyBank_Currency: "纸币储蓄罐",
    Portfolio: "公文包",
    PriceTag: "价格标签",
    Safe_Closed: "关闭的保险箱",
    Safe_Empty: "空保险箱",
    Safe_Full: "装满的保险箱",
    Seal_Gold: "金色封条",
    Seal_Red: "红色封条",
    Seal_Silver: "银色封条",
    Wallet_Empty: "空钱包",
    Wallet_Full1: "装满的钱包 1",
    Wallet_Full2: "装满的钱包 2",
    BusinessPerson_Female6: "女性商业人士 6",
    BusinessPerson_Male3: "男性商业人士 3",
    Computer_User_Female1: "女性计算机用户 1",
    ConstructionWorker2: "建筑工人 2",
    Presenter_Female1: "女性演示者 1",
    Component_Circle01_Transparent_DarkBlue: "深蓝色透明圆形组件 01",
    Component_Circle02_Transparent_Bule: "蓝色透明圆形组件 02",
    Component_Circle03_Transparent_Green: "绿色透明圆形组件 03",
    Component_Circle04_Transparent_Orange: "橙色透明圆形组件 04",
    Component_Circle05_Transparent_Red: "红色透明圆形组件 05",
    Component_Cube01_DarkBlue: "深蓝色立方体组件 01",
    Component_Cube02_LightBlue: "浅蓝色立方体组件 02",
    Component_Cube03_Green: "绿色立方体组件 03",
    Component_Cube04_Orange: "橙色立方体组件 04",
    Component_Cube05_DarkRed: "深红色立方体组件 05",
    Component_Cuboid01_DarkBlue: "深蓝色长方体组件 01",
    Component_Cuboid02_Blue: "蓝色长方体组件 02",
    Component_Cuboid03_Green: "绿色长方体组件 03",
    Component_Cuboid04_Orange: "橙色长方体组件 04",
    Component_Cuboid05_Red: "红色长方体组件 05",
    Component_Gear01_DarkBlue: "深蓝色齿轮组件 01",
    Component_Gear02_LightBlue: "浅蓝色齿轮组件 02",
    Component_Gear03_Green: "绿色齿轮组件 03",
    Component_Gear04_DarkRed: "深红色齿轮组件 04",
    Component_Gear05_Orange: "橙色齿轮组件 05",
    Component_Person01_DarkBlue: "深蓝色人像组件 01",
    Component_Person02_Blue: "蓝色人像组件 02",
    Component_Person03_Green: "绿色人像组件 03",
    Component_Person04_DarkRed: "深红色人像组件 04",
    Component_Person05_Orange: "橙色人像组件 05",
    Component_PuzzlePiece01_DarkBlue: "深蓝色拼图块组件 01",
    Component_PuzzlePiece02_Blue: "蓝色拼图块组件 02",
    Component_PuzzlePiece03_Green: "绿色拼图块组件 03",
    Component_PuzzlePiece04_Red: "红色拼图块组件 04",
    Component_PuzzlePiece05_Orange: "橙色拼图块组件 05",
    Component_Sphere01_DarkBlue: "深蓝色球形组件 01",
    Component_Sphere02_LightBlue: "浅蓝色球形组件 02",
    Component_Sphere03_Green: "绿色球形组件 03",
    Component_Sphere04_DarkRed: "深红色球形组件 04",
    Component_Sphere05_Orange: "橙色球形组件 05",
    Book: "书籍",
    Box01: "箱子 01",
    Box02: "箱子 02",
    Bulb01_Yellow: "黄色灯泡 01",
    Bulb02_Yellow: "黄色灯泡 02",
    Calendar: "日历",
    Chart: "图表",
    Clipboard: "剪贴板",
    Clock: "时钟",
    Compass: "罗盘",
    Flag01_Red: "红色旗帜 01",
    Flag02_Green: "绿色旗帜 02",
    Flag03_Blue: "蓝色旗帜 03",
    Gift: "礼物",
    House: "房屋",
    Icon_Computer01_White: "白色计算机图标 01",
    Icon_Computer02_Black: "黑色计算机图标 02",
    Icon_Disk01_Blue: "蓝色磁盘图标 01",
    Icon_Disk02_Green: "绿色磁盘图标 02",
    Icon_Document01_Grey: "灰色文档图标 01",
    Icon_Document02_Grey: "灰色文档图标 02",
    Icon_Document03_Blue: "蓝色文档图标 03",
    Icon_Document04_Blue: "蓝色文档图标 04",
    Icon_Envelope01_Blue: "蓝色信封图标 01",
    Icon_Envelope02_Yellow: "黄色信封图标 02",
    Icon_Envelope03_Open_Yellow: "黄色打开信封图标 03",
    Icon_Envelope04_Open_Yellow: "黄色打开信封图标 04",
    Icon_Folder01_Yellow: "黄色文件夹图标 01",
    Icon_Folder02_Yellow: "黄色文件夹图标 02",
    Icon_Folder03_Open_Yellow: "黄色打开文件夹图标 03",
    Icon_Folder04_Open_Yellow: "黄色打开文件夹图标 04",
    Icon_Gear01_Grey: "灰色齿轮图标 01",
    Icon_Gear02_Blue: "蓝色齿轮图标 02",
    Icon_Network01_Blue: "蓝色网络图标 01",
    Icon_Network02: "网络图标 02",
    Icon_Pencil01: "铅笔图标 01",
    Icon_Pencil02: "铅笔图标 02",
    Icon_Printer01_White: "白色打印机图标 01",
    Icon_Printer02_Black: "黑色打印机图标 02",
    Key01: "钥匙 01",
    Key02: "钥匙 02",
    Lock01_Yellow: "黄色锁 01",
    Lock02_Yellow: "黄色锁 02",
    Lock03_Blue: "蓝色锁 03",
    Lock04_Blue: "蓝色锁 04",
    Magnet: "磁铁",
    MagnifyingGlass: "放大镜",
    Medal: "奖章",
    Notebook: "笔记本",
    Phone: "电话",
    PieChart: "饼图",
    Pin: "大头针",
    PuzzlePiece: "拼图块",
    PuzzlePieces: "多个拼图块",
    Roadblock: "路障",
    Scissors: "剪刀",
    Shield01: "盾牌 01",
    Shield02_Orange: "橙色盾牌 02",
    Shield03_Blue: "蓝色盾牌 03",
    Sign_Ban01: "禁止符号 01",
    Sign_Ban02: "禁止符号 02",
    Sign_CheckBox01: "复选框符号 01",
    Sign_CheckBox02_Unchecked: "未选中的复选框符号 02",
    Sign_Checkmark01_Green: "绿色勾选符号 01",
    Sign_Checkmark02_Green: "绿色勾选符号 02",
    Sign_DoNotEnter: "禁止输入符号",
    Sign_Error01: "错误符号 01",
    Sign_Error02: "错误符号 02",
    Sign_ExclamationPoint01_Red: "红色惊叹号 01",
    Sign_ExclamationPoint02_Orange: "橙色惊叹号 02",
    Sign_Help01_Green: "绿色帮助符号 01",
    Sign_Help02_Blue: "蓝色帮助符号 02",
    Sign_Information: "信息符号",
    Sign_Null: "空符号",
    Sign_QuestionMark01_Blue: "蓝色问号 01",
    Sign_QuestionMark02_Red: "红色问号 02",
    Sign_RadioButton01: "单选按钮符号 01",
    Sign_RadioButton02_Unchecked: "未选中的单选按钮符号 02",
    Sign_Warning01_Red: "红色警告符号 01",
    Sign_Warning02_Orange: "橙色警告符号 02",
    Sign_X01_Red: "红色 X 符号 01",
    Sign_X02_Red: "红色 X 符号 02",
    Star_Yellow: "黄色星形",
    Wrench: "扳手",
    Airplane_Blue: "蓝色飞机",
    Bicycle_Blue: "蓝色自行车",
    Bus: "公共汽车",
    Canoe_Blue: "蓝色独木舟",
    Car_Red: "红色汽车",
    Helicopter_Blue: "蓝色直升飞机",
    Motorcycle_Red: "红色摩托车",
    Pedestrian_Blue: "蓝色行人",
    PersonalTransporter_Green: "绿色个人运输车",
    Sailboat_Red: "红色帆船",
    Scooter_Orange: "橙色小摩托车",
    Train_Red: "红色火车",
    Truck_Blue: "蓝色卡车",
    
    aria_category_selector: "图像类别选项",
    filterImageGallery: "过滤图像库"

})
