﻿/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        fileMenu: "文件",
        fileMenu_New: "新建",
        fileMenu_NewDocument: "文档",
        fileMenu_NewFromTemplate: "来自模板",
        fileMenu_NewDocumentfromTemplate: "根据模板新建文档",
        fileMenu_NewPresentation: "演示文稿",
        fileMenu_NewPresentationfromTemplate: "根据模板新建演示文稿",
        fileMenu_NewSpreadsheet: "电子表格",
        fileMenu_NewSpreadsheetFromTemplate: "根据模板新建电子表格",
        fileMenu_Open: "打开",
        fileMenu_Import: "导入...",
        //	fileMenu_Close: "Close",
        fileMenu_Discard: "还原到上一版本",
        fileMenu_ClearTrackChange: "除去更改标记",
        fileMenu_SpreadsheetSettings: "设置文档语言环境...",
        filemenu_revisionhistory: "修订版",
        fileMenu_Save: "保存",
        fileMenu_SaveAs: "复制...",
        fileMenu_AutoPublish: "自动发布",
        fileMenu_AutoCheckIn: "自动检入",
        fileMenu_PublishVersion: "立即发布",
        fileMenu_AutoPublish2: "自动保存到存储库",
        //	fileMenu_AutoPublish_Tips: "Makes your changes available to readers at the end of each editing session.",
        fileMenu_PublishVersion2: "立即保存到存储库",
        fileMenu_AutoPublish3: "自动保存到 ${0}",
        fileMenu_PublishVersion3: "立即保存到 ${0}",      
        fileMenu_SubmitForReview: "提交以进行复审",
        fileMenu_CheckinVersion: "检入...",
        fileMenu_Unlock: "解锁",
        //	fileMenu_SaveAsDraft: "as Draft",
        //	fileMenu_SaveInMyDocs: "in My Documents",
        //	fileMenu_SaveToSymphony: "to Lotus Symphany",
        fileMenu_DownloadAs: "下载为",
        fileMenu_PDF: "PDF",
        fileMenu_ODF: "ODF",
        fileMenu_DOC: "Microsoft Word 97- 2007 (*.doc)",
        fileMenu_ODS: "ODS",
        fileMenu_XLS: "Microsoft Excel 97-2007 (*.xls) ",
        fileMenu_ShareWith: "共享...",
        fileMenu_ExportAsPDF: "PDF",
        fileMenu_ExportAsODF: "ODF",
        fileMenu_ExportAsPPT: "Microsoft Powerpoint 97- 2007 (*.ppt)",
        //	fileMenu_WebPreview: "Web Preview",
        fileMenu_PrintToPDF: "打印成 PDF...",
        fileMenu_ViewFileDetails: "查看文件详细信息...",
        fileMenu_RecentFile: "最近文件",
        fileMenu_Open: "打开",
        fileMenu_Download: "下载",
        fileMenu_Print: "打印",
        fileMenu_Export: "导出",
        fileMenu_ExportToCSV: "CSV",
        fileMenu_ExportToPDF: "PDF (.pdf)",
        fileMenu_ExportToMarkdown: "Markdown(.md)",
        fileMenu_ExportToMS: "Microsoft Office 格式 (.${FILEEXTENSION})",
        fileMenu_ExportToODF: "Open Document 格式 (.${FILEEXTENSION})",
        fileMenu_PgSetup: "页面设置...",

        editMenu: "编辑",
        editMenu_Undo: "撤销",
        editMenu_Redo: "重做",
        editMenu_Cut: "剪切",
        editMenu_Copy: "复制",
        editMenu_Paste: "粘贴",
        editMenu_DeleteSlide: "删除幻灯片",
        editMenu_SelectAll: "全选",
        editMenu_Find: "查找...",
        editMenu_Replace: "替换...",
        editMenu_FindReplace: "查找并替换...",
        editMenu_EditLink: "添加或编辑链接",
        editMenu_DeleteSheet: "删除工作表...",
        editMenu_RenameSheet: "重命名工作表...",
        editMenu_HideSheet: "隐藏工作表",
        editMenu_MoveSheet: "移动工作表...",
        editMenu_DeleteRow: "删除行",
        editMenu_DeleteColumn: "删除列",
        editMenu_DeleteCellLeft: "删除单元格并左移",
        editMenu_DeleteCellUp: "删除单元格并上移",
        editMenu_ClearCell: "删除内容",

        viewMenu: "查看",
        viewMenu_Master: "母版",
        viewMenu_Notifications: "通知",
        viewMenu_SlideSorter: "幻灯片排序器",
        viewMenu_SpeakerNotes: "演讲者备注",
        viewMenu_Toolbar_Basic: "基本",
        viewMenu_Toolbar_Advanced: "高级",
        viewMenu_Toolbar_None: "无",
        viewMenu_Toolbar: "工具栏",
        viewMenu_Statusbar: "状态栏",
        viewMenu_Navigator: "导航器...",
        //viewMenu_Sidebar: "Sidebar",
        viewMenu_ShowHideIndicators: "显示共同编辑的指示符",
        viewMenu_Assignment: "分配指示符",
        viewMenu_Bookmark: "书签",
        viewMenu_Coediting: "共同编辑突出显示项",
        viewMenu_Rulers: "标尺",
        viewMenu_WebLayout: "Web 布局",
        viewMenu_AutomaticSpellCheck: "输入时检查拼写",
        viewMenu_Formulabar: "公式栏",
        viewMenu_moveRight: "进入并将光标移动到右侧",
        viewMenu_showFullString: "扩展单元格中的内容",
        viewMenu_Doc: "查看文档",
        viewMenu_Templates: "模板",
        viewMenu_GridLines: "隐藏网格线",
        viewMenu_UnsupportWarning: "显示不受支持的功能消息",
        viewMenu_HiddenSheets: "隐藏工作表",
        viewMenu_FreezeRows: "冻结行",
        viewMenu_FreezeColumns: "冻结列",
        viewMenu_NoFrozenRows: "不冻结行",
        viewmenu_NoFrozenColumns: "不冻结列",
        viewMenu_FreezeXRows: "冻结 ${0} 行",
        viewMenu_FreezeOneRow: "冻结 ${0} 行",
        viewMenu_FreezeXColumns: "冻结 ${0} 列",
        viewMenu_FreezeOneColumn: "冻结 ${0} 列",
        viewMenu_CarriageReturn: "格式化标记",
        viewMenu_Navigation: "导航窗格",
        viewMenu_ACL: "可编辑区域",
        viewMenu_GridOnOff: "网格线",
        viewMenu_ObserverMode: '观察者模式',

        createMenu: "插入",
        createMenu_NewSlide: "新建幻灯片",
        createMenu_DuplicateSlide: "复制幻灯片",
        createMenu_ImageFromFile: "图像...",
        createMenu_TextBox: "文本框",
        createMenu_Shape: "形状",
        createMenu_break: "分隔",
        createMenu_RowAbove: "在上方插入行",
        createMenu_RowBelow: "在下方插入行",
        createMenu_ColumnRight: "在右侧插入列",
        createMenu_ColumnLeft: "在左侧插入列",
        createMenu_Sheet: "工作表...",
        createMenu_Image: "图像...",
        createMenu_Comments: "注释...",
        createMenu_WebLink: "Web 链接...",
        createMenu_SpecialCharacter: "特殊字符...",
        createMenu_Function: "函数...",
        createMenu_Fromtemplate: "从模板创建",

        insertMenu: "插入",
        insertMenu_break: "分页符",
        insertMenu_sectionbreak: "分节符",
        insertMenu_Bookmark: "书签...",
        insertMenu_WebLink: "链接...",
        insertMenu_SpecialCharacter: "特殊字符...",
        insertMenu_HorizontalLine: "水平线",
        insertMenu_Header: "页眉",
        insertMenu_Footer: "页脚",
        insertMenu_TableOfContents: "目录",

        insertMenu_HeaderFooter: "页眉/页脚",
        insertMenu_HF_Edit: "编辑",
        insertMenu_HF_Hide: "隐藏",
        insertMenu_Endnotes: "尾注",
        insertMenu_RowAbove: "在上方插入行",
        insertMenu_PageNumber: "页码",
        insertMenu_PageNumberTop: "页面顶部",
        insertMenu_PageNumberBottom: "页面底部",
        insertMenu_PageNumberCurr: "当前位置",
        insertMenu_TotalPageNumber: "第 1 页（共 N 页）",
        insertMenu_Date: "日期...",
        insertMenu_Time: "时间...",
        insertMenu_Fields: "字段",
        //    insertMenu_Comment: "Comment",
        insertMenu_CellRight: "单元格并右移",
        insertMenu_CellDown: "单元格并下移",
        insertMenu_RowBelow: "在下方插入行",
        insertMenu_ColumnBefore: "在之前插入列",
        insertMenu_ColumnAfter: "在之后插入列",
        insertMenu_Sheet: "工作表...",
        insertMenu_Image: "图像...",
        insertMenu_DuplicateSheet: "复制工作表",
        insertMenu_Function: "函数",
        insertMenu_FunctionSum: "总和",
        insertMenu_FunctionAverage: "平均值",
        insertMenu_FunctionCount: "计数",
        insertMenu_FunctionMax: "最大值",
        insertMenu_FunctionMin: "最小值",
        insertMenu_FunctionMore: "更多函数...",
        insertMenu_NameRange: "指定的范围",
        insertMenu_NameRangeNew: "新建范围...",
        insertMenu_NameRangeManage: "管理范围...",
        insertMenu_Chart: "图表...",

        contextMenu_insertCellRight: "插入单元格并右移",
        contextMenu_insertCellDown: "插入单元格并下移",
        contextMenu_InsertRowAbove: "在上方插入行",
        contextMenu_InsertRowBelow: "在下方插入行",
        contextMenu_InsertColumnBefore: "在之前插入列",
        contextMenu_InsertColumnAfter: "在之后插入列",
        contextMenu_DownloadImage: "下载为图像",

        formatMenu: "格式",
        formatMenu_Columns: "列",
        formatMenu_DefaultFormatting: "缺省格式",
        formatMenu_Template: "样式...",
        contextMenu_Template: "表格样式...",
        formatMenu_LineSpacing: "行间距",
        formatMenu_LineSpacing1: "1",
        formatMenu_LineSpacing12: "1.2",
        formatMenu_LineSpacing15: "1.5",
        formatMenu_LineSpacing2: "2",
        formatMenu_LineSpacing25: "2.5",
        formatMenu_LineSpacing3: "3",
        formatMenu_TextProperties: "文本属性",
        formatMenu_PageBreakBefore: "段前分页",
        formatMenu_KeepLines: "段中不分页",
        formatMenu_WidowControl: "孤行控制",
        formatMenu_Pagination: "段落属性",
        formatMenu_Bold: "粗体",
        formatMenu_Italic: "斜体",
        formatMenu_Underline: "下划线",
        formatMenu_Strikethrough: "删除线",
        formatMenu_IncreaseSize: "增大字体大小",
        formatMenu_DecreaseSize: "减小字体大小",
        formatMenu_ImageProperties: "图像属性...",
        formatMenu_ChartProperties: "图表属性...",
        formatMenu_EditChart: "编辑图表",
        formatMenu_InsertChart: "插入图表",
        formatMenu_Properties: "属性...",
        formatMenu_Heading: "标题",
        formatMenu_Normal: "普通",
        formatMenu_Title: "标题",
        formatMenu_Subtitle: "副标题",
        formatMenu_Heading1: "标题 1",
        formatMenu_Heading2: "标题 2",
        formatMenu_Heading3: "标题 3",
        formatMenu_Heading4: "标题 4",
        formatMenu_Heading5: "标题 5",
        formatMenu_Heading6: "标题 6",
        formatMenu_Heading7: "标题 7",
        formatMenu_Heading8: "标题 8",
        formatMenu_Heading9: "标题 9",
        formatMenu_BulletedList: "符号列表",
        formatMenu_NumberedList: "编号列表",
        formatMenu_OutLine: "多级列表",
        formatMenu_Superscript: "上标",
        formatMenu_Subscript: "下标",
        formatMenu_Align: "对齐",
        formatMenu_Left: "左",
        formatMenu_Right: "右",
        formatMenu_Center: "水平居中",
        formatMenu_Justify: "两端对齐",
        formatMenu_Text_Direction: "文本方向",
        formatMenu_Ltr: "从左至右",
        formatMenu_Rtl: "从右至左",
        formatMenu_LineSpacing: "行间距",
        formatMenu_LineSpacing1: "1.0",
        formatMenu_LineSpacing115: "1.15",
        formatMenu_LineSpacing15: "1.5",
        formatMenu_LineSpacing2: "2.0",
        formatMenu_LineSpacing25: "2.5",
        formatMenu_LineSpacing3: "3.0",
        formatMenu_Top: "顶部",
        formatMenu_Bottom: "底部",
        formatMenu_Middle: "垂直居中",
        formatMenu_Direction: "文本方向",
        formatMenu_Rtl: "从右至左",
        formatMenu_Ltr: "从左至右",
        formatMenu_Auto: "上下文",
        formatMenu_SheetDirection: "工作表方向",
        formatMenu_SheetRtl: "从右至左",
        formatMenu_SheetLtr: "从左至右",
        formatMenu_Indent: "增加缩进",
        formatMenu_DecreaseIndent: "减少缩进",
        formatMenu_ClearFormat: "清除格式",
        formatMenu_RowHeight: "行高",
        formatMenu_ColumnWidth: "列宽",
        formatMenu_ShowRow: "显示行",
        formatMenu_HideRow: "隐藏行",
        formatMenu_ShowColumn: "显示列",
        formatMenu_HideColumn: "隐藏列",
        formatMenu_WrapText: "文本自动换行",
        formatMenu_Number: "数值",
        formatMenu_FontArial: "Arial",
        formatMenu_FontComicSansMS: "Comic Sans MS",
        formatMenu_FontCourierNew: "Courier New",
        formatMenu_FontGeorgia: "Georgia",
        formatMenu_FontLucidaSansUnicode: "Lucida Sans Unicode",
        formatMenu_FontTahoma: "Tahoma",
        formatMenu_FontTimesNewRoman: "Times New Roman",
        formatMenu_FontTrebuchetMS: "Trebuchet MS",
        formatMenu_FontVerdana: "Verdana",
        formatMenu_FontName: "字体",

        layoutMenu: "布局",
        layoutMenu_SlideLayout: "幻灯片布局...",
        layoutMenu_SlideDesign: "母版样式...",
        layoutMenu_DefaultFormatting: "缺省格式",
        layoutMenu_Textprop_Bold: "粗体",
        layoutMenu_Textprop_Italic: "斜体",
        layoutMenu_Textprop_Underline: "下划线",
        layoutMenu_Textprop_Strikethrough: "删除线",
        layoutMenu_TextProp: "文本属性",
        LayoutMenu_RowHeight: "行高...",
        LayoutMenu_ColumnWidth: "列宽...",
        LayoutMenu_ShowRow: "显示行",
        LayoutMenu_HideRow: "隐藏行",
        LayoutMenu_RenameSheet: "重命名工作表...",
        LayoutMenu_MoveSheet: "移动工作表",

        tableMenu: "表格",
        tableMenu_Create: "创建...",
        tableMenu_CreateFromTemplate: "从模板创建",
        tableMenu_Delete: "删除",
        tableMenu_SetTableColor: "彩色单元格",
        tableMenu_CreateTable: "创建表格",
        tableMenu_Cell: "单元格",
        tableMenu_CellMergeCells: "合并单元格",
        tableMenu_CellAlignLeft: "左对齐",
        tableMenu_CellAlignCenter: "居中对齐",
        tableMenu_CellAlignRight: "右对齐",
        tableMenu_CellClearContents: "清除内容",
        tableMenu_CellProperties: "单元格属性...",
        tableMenu_Row: "行",
        tableMenu_InsertRowAbove: "在上方插入行",
        tableMenu_InsertRowBelow: "在下方插入行",
        tableMenu_MoveRowAbove: "将行上移",
        tableMenu_MoveRowBelow: "将行下移",
        tableMenu_RowInsertRow: "插入行...",
        tableMenu_RowInsertRowAbove: "在上方插入行",
        tableMenu_RowInsertRowBelow: "在下方插入行",
        tableMenu_RowMoveRowAbove: "将行上移",
        tableMenu_RowMoveRowBelow: "将行下移",
        tableMenu_RowDelete: "删除",
        tableMenu_RowRepeat: "重复标题行",
        tableMenu_InsertColumnBefore: "在之前插入列",
        tableMenu_InsertColumnAfter: "在之后插入列",
        tableMenu_MoveColumnBefore: "将列左移",
        tableMenu_MoveColumnAfter: "将列右移",
        tableMenu_ResizeColumn: "调整列大小",
        tableMenu_ResizeColumns: "调整列大小",
        tableMenu_MarkasCategory: "标记为类别",
        tableMenu_ColumnInsertColumn: "插入列...",
        tableMenu_ColumnAddColumnBefore: "在之前插入列",
        tableMenu_ColumnAddColumnAfter: "在之后插入列",
        tableMenu_ColumnMoveColumnAfter: "将列后移",
        tableMenu_ColumnMoveColumnBefore: "将列前移",
        tableMenu_ColumnDelete: "删除",
        tableMenu_ColumnSortAscending: "按升序排序",
        tableMenu_ColumnSortDescending: "按降序排序",
        tableMenu_Column: "列",
        tableMenu_Style: "样式",
        tableMenu_TableProperties: "表格属性...",

        teamMenu: "工作组",
        teamMenu_AddComment: "添加注释",
        teamMenu_AssignCells: "分配单元格",
        teamMenu_AssignSection: "分配一个区段",
        teamMenu_EditAssignment: "编辑分配",
        teamMenu_MarkSectionComplete: "将区段标记为“完成”",
        teamMenu_MarkAssignmentComplete: "将分配标记为“完成”",
        teamMenu_WorkPrivatelyOnSection: "在区段上进行独立工作",
        teamMenu_CancelPrivateWork: "取消独自工作",
        teamMenu_ApproveSection: "核准区段",
        teamMenu_ApproveAssignment: "核准分配",
        teamMenu_ReturnSectionForRework: "返回区段以修订",
        teamMenu_ReturnAssignmentForRework: "返回分配以修订",
        teamMenu_RemoveSectionAssignment: "除去区段分配",
        teamMenu_RemoveCellAssignment: "除去单元格分配",
        teamMenu_RemoveCompletedAssignments: "除去已完成的分配",
        teamMenu_AboutThisSection: "关于该区段",
        teamMenu_AboutAssignment: "关于本分配",

        presentationMenu: "演示文稿",
        presentationMenu_SlideShow: "放映幻灯片",
        presentationMenu_SlideShowWithCoview: "放映共享幻灯片",
        presentationMenu_SlideTransitions: "应用幻灯片切换...",
        presentationMenu_SlideShowFromCurrent: "从当前幻灯片开始放映",
        presentationMenu_EmptyCoviewInvites: "无活动的共享幻灯片放映",
        presentationMenu_CoviewInvites: "活动共享幻灯片放映",

        dataMenu: "数据",
        dataMenu_Sort: "排序...",
        dataMenu_SortAsc: "按升序排序",
        dataMenu_SortDesc: "按降序排序",
        dataMenu_ACL: "受保护区域",
        dataMenu_ACL_DELETE: "删除所有许可权",
        dataMenu_Validity: "有效性",
        dataMenu_InstantFilter: "即时筛选",
        dataMenu_Validation: "验证...",

        toolsMenu: "工具",
        toolsMenu_AutoComplete: "自动完成单元格输入",
        toolsMenu_SelectDictionary: "拼写检查字典",
        toolsMenu_Dictionary_ca_CT: "加泰罗尼亚语",
        toolsMenu_Dictionary_cs_CZ: "捷克语（捷克）",
        toolsMenu_Dictionary_da_DK: "丹麦语（丹麦）",
        toolsMenu_Dictionary_nl_NL: "荷兰语（荷兰）",
        toolsMenu_Dictionary_en_AU: "英语（澳大利亚）",
        toolsMenu_Dictionary_en_GB: "英语（英国）",
        toolsMenu_Dictionary_en_US: "英语（美国）",
        toolsMenu_Dictionary_fi_FI: "芬兰语（芬兰）",
        toolsMenu_Dictionary_fr_FR: "法语（法国）",
        toolsMenu_Dictionary_fr_CA: "法语（加拿大）",
        toolsMenu_Dictionary_de_DE: "德语（德国）",
        toolsMenu_Dictionary_de_CH: "德语（瑞士）",
        toolsMenu_Dictionary_el_GR: "希腊语（希腊）",
        toolsMenu_Dictionary_it_IT: "意大利语（意大利）",
        toolsMenu_Dictionary_pl_PL: "波兰语（波兰）",
        toolsMenu_Dictionary_pt_BR: "葡萄牙语（巴西）",
        toolsMenu_Dictionary_pt_PT: "葡萄牙语（葡萄牙）",
        toolsMenu_Dictionary_ru_RU: "俄语（俄罗斯）",
        toolsMenu_Dictionary_es_ES: "西班牙语（西班牙）",
        toolsMenu_Dictionary_sv_SE: "瑞典语（瑞典）",
        toolsMenu_Dictionary_nb_NO: "挪威语（博克马尔语）",
        toolsMenu_Dictionary_nn_NO: "挪威语（尼诺斯克语）",
        toolsMenu_Dictionary_he_IL: "希伯来语（以色列）",
        toolsMenu_SpellCheck: "运行手动拼写检查...",
        toolsMenu_Preferences: "首选项",
        toolsMenu_Task: "任务",
        toolsMenu_Task_Assigntask: "分配一个任务",
        teamMenu_AssignSlide: "分配幻灯片",
        teamMenu_AssignSlides: "分配幻灯片",
        teamMenu_EditSlide: "编辑幻灯片分配",
        teamMenu_ReopenSlideAssignment: "重新打开幻灯片分配",
        teamMenu_ReopenSlideAssignments: "重新打开幻灯片分配",
        teamMenu_ReassignSlide: "重新分配幻灯片",
        teamMenu_ReassignSlides: "重新分配幻灯片",
        teamMenu_MarkSlidesComplete: "将幻灯片标记为完成",
        teamMenu_MarkSlidesCompletes: "将幻灯片标记为完成",
        teamMenu_ApproveSlide: "核准幻灯片",
        teamMenu_ApproveSlides: "核准幻灯片",
        teamMenu_ReturnForRework: "返回幻灯片以修订",
        teamMenu_ReturnForReworks: "返回幻灯片以修订",
        teamMenu_RemoveAssignment: "除去幻灯片分配",
        teamMenu_AboutThisSlide: "关于本幻灯片",

        addOnsMenu: "附加组件",

        helpMenu: "帮助",
        helpMenu_About: "关于",
        helpMenu_Overview: "帮助内容",
        helpMenu_NewFeatures: "新功能",
        helpMenu_Tour: "指导教程",

        accel_fileMenu_Save: "Ctrl+S",
        accel_fileMenu_Save_Mac: "\u2318S",
        accel_fileMenu_Print: "Ctrl+P",
        accel_fileMenu_Print_Mac: "\u2318P",
        accel_editMenu_SelectAll: "Ctrl+A",
        accel_editMenu_SelectAll_Mac: "\u2318A",
        accel_editMenu_Undo: "Ctrl+Z",
        accel_editMenu_Undo_Mac: "\u2318Z",
        accel_editMenu_Redo: "Ctrl+Y",
        accel_editMenu_Redo_Mac: "\u2318Y",
        accel_editMenu_Cut: "Ctrl+X",
        accel_editMenu_Cut_Mac: "\u2318X",
        accel_editMenu_Copy: "Ctrl+C",
        accel_editMenu_Copy_Mac: "\u2318C",
        accel_editMenu_Paste: "Ctrl+V",
        accel_editMenu_Paste_Mac: "\u2318V",
        accel_editMenu_Find: "Ctrl+F",
        accel_editMenu_Find_Mac: "\u2318F",
        accel_insertMenu_Link: "Ctrl+K",
        accel_insertMenu_Link_Mac: "\u2318K",
        accel_insertMenu_Header: "CTRL+SHIFT+H",
        accel_insertMenu_Header_Mac: "\u21e7\u2318H",
        accel_insertMenu_Footer: "CTRL+SHIFT+F",
        accel_insertMenu_Footer_Mac: "\u21e7\u2318F",
        accel_formatMenu_Textprop_Bold: "Ctrl+B",
        accel_formatMenu_Textprop_Bold_Mac: "\u2318B",
        accel_formatMenu_Textprop_Italic: "Ctrl+I",
        accel_formatMenu_Textprop_Italic_Mac: "\u2318I",
        accel_formatMenu_Textprop_FormatPainter: "Ctrl+SHIFT+C, Ctrl+SHIFT+V",
        accel_formatMenu_Textprop_FormatPainter_Mac: "\u21e7\u2318C, \u21e7\u2318V",
        accel_formatMenu_Textprop_Underline: "Ctrl+U",
        accel_formatMenu_Textprop_Underline_Mac: "\u2318U",
        accel_formatMenu_Headingprop_P: "CTRL+SHIFT+0",
        accel_formatMenu_Headingprop_H1: "CTRL+SHIFT+1",
        accel_formatMenu_Headingprop_H2: "CTRL+SHIFT+2",
        accel_formatMenu_Headingprop_H3: "CTRL+SHIFT+3",
        accel_formatMenu_Headingprop_H4: "CTRL+SHIFT+4",
        accel_formatMenu_Headingprop_H5: "CTRL+SHIFT+5",
        accel_formatMenu_Headingprop_H6: "CTRL+SHIFT+6",
        accel_formatMenu_Superscript: "Ctrl+.",
        accel_formatMenu_Superscript_Mac: "\u2318.",
        accel_formatMenu_Subscript: "Ctrl+,",
        accel_formatMenu_Subscript_Mac: "\u2318,",
        accel_formatMenu_Left: "CTRL+SHIFT+L",
        accel_formatMenu_Left_Mac: "\u21e7\u2318L",
        accel_formatMenu_Right: "CTRL+SHIFT+R",
        accel_formatMenu_Right_Mac: "\u21e7\u2318R",
        accel_formatMenu_Center: "CTRL+SHIFT+E",
        accel_formatMenu_Center_Mac: "\u21e7\u2318E",
        accel_formatMenu_Justify: "CTRL+SHIFT+J",
        accel_formatMenu_Justify_Mac: "\u21e7\u2318J",
        accel_formatMenu_Indent: "CTRL+M",
        accel_formatMenu_Indent_Mac: "\u2318M",
        accel_formatMenu_DecreaseIndent: "CTRL+SHIFT+M",
        accel_formatMenu_DecreaseIndent_Mac: "\u21e7\u2318M",
        accel_teamMenu_AddComment: "SHIFT+F2",

        ctxMenuSmartTable: '表格',
        ctxMenuTableProperties: "表格属性",
        ctxMenuDeleteST: '删除',
        ctxMenuDeleteSTTable: '删除表格',
        ctxMenuChgSTStyle: '更改样式',
        ctxMenuShowCaption: '显示文字说明',
        ctxMenuHideCaption: '隐藏文字说明',
        ctxMenuResizeST: '调整大小',
        ctxMenuResizeColumnsST: '调整列大小',
        ctxMenuSTRow: '行',
        ctxMenuAddSTRowAbv: '在上方插入行',
        ctxMenuAddSTRowBlw: '在下方插入行',
        ctxMenuMoveSTRowUp: '将行上移',
        ctxMenuMoveSTRowDown: '将行下移',
        ctxMenuDelSTRow: '删除',
        ctxMenuRepeatRow: '重复标题行',
        ctxMenuSTCol: '列',
        ctxMenuAddSTColBfr: '在之前插入列',
        ctxMenuAddSTColAft: '在之后插入列',
        ctxMenuMoveSTColBefore: '将列前移',
        ctxMenuMoveSTColAfter: '将列后移',
        ctxMenuDelSTCol: '删除',
        ctxMenuSortSTColAsc: '按升序排序',
        ctxMenuSortSTColDesc: '按降序排序',
        ctxMenuShowAllFacets: '显示类别',
        ctxMenuHideAllFacets: '隐藏类别',
        ctxMenuSTCell: '单元格',
        ctxMenuMergeCells: '合并单元格',
        ctxMenuMergeDown: '与下方的单元格合并',
        ctxMenuVerSplit: '垂直拆分',
        ctxMenuHorSplit: '水平拆分',
        ctxMenuSplitCells: '拆分单元格...',
        splitCells: '拆分单元格',
        ctxMenuAlignTextLeft: '左对齐',
        ctxMenuAlignTextCenter: '居中对齐',
        ctxMenuAlignTextRight: '右对齐',
        ctxMenuClearSTCellContent: '清除内容',
        ctxMenuMakeHeaderRow: '将所选行用作标题',
        ctxMenuMakeNonHeaderRow: '除去标题样式',
        ctxMenuMakeHeaderCol: '将所选列用作标题',
        ctxMenuMakeNonHeaderCol: '除去标题样式',
        SHEET_CONTEXT_Hide: "隐藏", // hide row, column or sheet
        SHEET_CONTEXT_Show: "显示", // show row, column
        SHEET_CONTEXT_MoveSheet: "移动...", // move sheet
        SHEET_CONTEXT_InsertSheet: "插入...", // insert sheet
        SHEET_CONTEXT_DeleteSheet: "删除...", // delete sheet	
        SHEET_CONTEXT_DuplicateSheet: "复制...", // duplicate sheet
        SHEET_CONTEXT_RenameSheet: "重命名...", // rename sheet
	
        ctxMenu_Image_WrapText: "文本自动换行",
        ctxMenu_Image_WrapText_Inline: "与文本对齐",
        ctxMenu_Image_WrapText_Square: "正方形",
        ctxMenu_Image_WrapText_TopBottom: "顶部和底部",
        ctxMenu_Image_WrapText_Behind: "文本之后",
        ctxMenu_Image_WrapText_InFront: "文本之前",
        ctxMenu_Image_WrapText_Other: "更多文本自动换行",
        ctxMenu_Image_WrapText_BothSides: "双面",
        ctxMenu_Image_WrapText_LeftOnly: "仅限左侧",
        ctxMenu_Image_WrapText_RightOnly: "仅限右侧",
        ctxMenu_Image_WrapText_LargestOnly: "仅限最大",

        ctxMenu_Shape_AddText: "添加文本",

        ctxMenu_Range_ACL: "保护范围",
        ctxMenu_Sheet_ACL: "保护工作表",

        ctxMenu_HeaderFooter: "页眉/页脚",
        ctxMenu_HeaderFooter_DiffFirst: "仅第一页",
        ctxMenu_HeaderFooter_DiffOddEven: "奇数页与偶数页不同",
        ctxMenu_HeaderFooter_LinkToPre: "链接到上一个",

        ctxMenu_copy: "复制",
        ctxMenu_paste: "粘贴",
        ctxMenu_delete: "删除",
        ctxMenu_cut: "剪切",
        ctxMenu_select: "选择",
        ctxMenu_properties: "属性",
        ctxMenu_bringToFront: "移到前端",
        ctxMenu_sendToBack: "移到后端",
        ctxMenu_arrange: "排列",
        ctxMenu_sendBackward: "后移",
        ctxMenu_sendForward: "前移",
        ctxMenu_fontStyle: "字体样式",
        ctxMenu_selectStyle: "选择样式",
        ctxMenu_fontSize: "字体大小",
        ctxMenu_fontFamily: "字体系列",
        ctxMenu_bold: "粗体",
        ctxMenu_italic: "斜体",
        ctxMenu_u: "下划线",
        ctxMenu_strike: "删除线",
        ctxMenu_super: "上标",
        ctxMenu_sub: "下标",
        ctxMenu_color: "颜色",
        ctxMenu_bgcolor: "背景色",
        ctxMenu_highcolor: "突出显示颜色",
        ctxMenu_restart: "重新编号",
        ctxMenu_continue: "继续编号",
        ctxMenu_separate: "单独的列表",
        ctxMenu_join: "加入上一列表",
        ctxMenu_setNumberVal: "设置编号值...",
        webClipboardInfoTitle: "剪贴板",
        webClipboardInfoOKBtn: "确定",
        webClipboardInfoCutMsg: "您的浏览器安全设置阻止自动复制。 请改用键盘上的 Ctrl+X。",
        webClipboardInfoCopyMsg: "您的浏览器安全设置阻止自动复制。 请改用键盘上的 Ctrl+C。",
        webClipboardInfoPasteMsg: "您的浏览器安全设置阻止该编辑器访问剪贴板数据。 请改为使用键盘上的 Ctrl+V。",

        clearTrackChangeConfirmMsg: "将永久除去用于标记该文档中更改的所有彩色编码。 要继续吗？"
});

