({	
	viewExpandedBtn: "Visa färre svar",
	viewCollapsedBtn: "Visa ${0} fler svar",
	placeholderMsg: "Skriv ditt meddelande här",
	sure: "Vill du ta bort den här kommentaren?",
	exceed: "Kommentaren är för lång.\nKommentaren överskrider maximalt antal tecken.\nMinska antalet tecken till högst ${0} och klicka på Lägg till.",
	remainLabelHint:"Kommentaren har nått den maximala gränsen 500 tecken.",
	tipsCommentField: "Skriv en kommentar till en eller alla redigerare",
	tipsRespondField: "Skriv ett svar till en eller alla redigerare",	
	resolveBtn: "Lös",	
	replyBtn: "Svara",
	saveBtn: "Lämna in",
	deleteBtn: "Ta bort",
	cancelBtn: "Avbryt",
	reopenBtn: "Öppna igen",
	todayAt: "Idag ${time}",
	yesterdayAt: "Igår ${time}",
	dateAt: "${date} ${time}",
	mentions: "Välj en användare att nämna",
	noMentions: "Fyll i med resten med blanktecken",
	nocomments: "Det finns inga kommentarer i dokumentet ${0}.",
	
	newComments:"Nya kommentarer",
	mentiontomesomebody:"Någon",
	mentiontome:"${0} nämnde dig i en kommentar",
	
	newcommentsnumber:"Antal olästa kommentarer",
	jawsnewcommentsnumber: "Antalet olästa kommentarer är ",
	jawsnactivecommentsnumber: "Antalet aktiva kommentarer är ",
	
	activenum:"Antal aktiva kommentarer",
	filterDesc:"Filtrera kommentarer",
	menuallcomments:"Alla kommentarer",
	menutome: "@mig",
	menubyme: "Av mig",
	menuactive: "Aktiv",
	menuresolved: "Löst",
	searchDesc: "Sök efter kommentarer",
	search: "Sök",
	closeDesc: "Stäng sökning",
	clear: "Rensa",
	warnEnterKeywords: "Fyll i sökvillkor",
	nocommentstome: "Det finns för närvarande inga kommentarer eller svar som nämner mig i dokumentet ${0}.",
	nocommentsbyme: "Det finns för närvarande inga kommentarer eller svar av mig i dokumentet ${0}.",
	nocommentsar: "Det finns för närvarande inga kommentarer under kategorin ${0} i dokumentet ${1}.",
	nosearchedcomments: "Det finns för närvarande inga kommentarer eller svar som innehåller ${0} under kategorin ${1} i dokumentet ${2}.",
	
	prevBtn: "Föregående",
	nextBtn: "Nästa",
	mentionHint:"Visar ${0} - ${1} matchningar av totalt ${2}",
		
	resolveFlag: "Lösta kommentarer",
	jawsCommentHint: "${authorname} skickade in kommentaren ${timestamp}",
	jawsReplyHint: "${authorname} skickade in svaret ${timestamp}",
	jawsContentHint: "Innehållet är ${content}",
	jawsCommentStatusHint: "Status är ${status}",
	jawsCommentKeyHint: "Du kan trycka på Enter eller mellanslagstangenten om du vill gå till dokumentet och se hela kommentarstråden samt lösa, svara eller ta bort kommentarer.",
	jawsMentionHint: "Docs-omnämnanden. Välj en användare du vill nämna genom att trycka på uppåt- eller nedåtpil.",
	jawsMentionSelected: "Tryck på Enter eller mellanslagstangenten för att nämna",
	commentDeletedMsg: "Kommentaren har tagits bort av en annan redigerare.",
	commentResolvedMsg: "Kommentaren har lösts.",
	warningCommentMsg: "Kommentarer som har gjorts i Docs för ${0} filer hanteras endast online. Kommentarslänkarna tas bort om en ny version överförs för redigering.",
	orphanCommentTip: "Kommentarslänken har tagits bort i den här överförda versionen.",
	warningCommentName: "Varning"
})

