﻿/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        fileMenu: "File",
        fileMenu_New: "Nuovo",
        fileMenu_NewDocument: "Documento",
        fileMenu_NewFromTemplate: "Da modello",
        fileMenu_NewDocumentfromTemplate: "Documento da modello",
        fileMenu_NewPresentation: "Presentazione",
        fileMenu_NewPresentationfromTemplate: "Presentazione da modello",
        fileMenu_NewSpreadsheet: "Foglio di calcolo",
        fileMenu_NewSpreadsheetFromTemplate: "Foglio di calcolo dal modello",
        fileMenu_Open: "Apri",
        fileMenu_Import: "Importa...",
        //	fileMenu_Close: "Close",
        fileMenu_Discard: "Ritorna all'ultima versione",
        fileMenu_ClearTrackChange: "Rimuovi contrassegni di modifica",
        fileMenu_SpreadsheetSettings: "Imposta locale documenti...",
        filemenu_revisionhistory: "Revisioni",
        fileMenu_Save: "Salva",
        fileMenu_SaveAs: "Copia...",
        fileMenu_AutoPublish: "Pubblica automaticamente",
        fileMenu_AutoCheckIn: "Esegui check-in automaticamente",
        fileMenu_PublishVersion: "Pubblica ora",
        fileMenu_AutoPublish2: "Salva automaticamente nel repository",
        //	fileMenu_AutoPublish_Tips: "Makes your changes available to readers at the end of each editing session.",
        fileMenu_PublishVersion2: "Salva nel repository ora",
        fileMenu_AutoPublish3: "Salva automaticamente nel ${0}",
        fileMenu_PublishVersion3: "Salva nel ${0} ora",      
        fileMenu_SubmitForReview: "Invia per la revisione...",
        fileMenu_CheckinVersion: "Esegui check in...",
        fileMenu_Unlock: "Sblocca",
        //	fileMenu_SaveAsDraft: "as Draft",
        //	fileMenu_SaveInMyDocs: "in My Documents",
        //	fileMenu_SaveToSymphony: "to Lotus Symphany",
        fileMenu_DownloadAs: "Scarica come",
        fileMenu_PDF: "PDF",
        fileMenu_ODF: "ODF",
        fileMenu_DOC: "Microsoft Word 97- 2007 (*.doc)",
        fileMenu_ODS: "ODS",
        fileMenu_XLS: "Microsoft Excel 97-2007 (*.xls) ",
        fileMenu_ShareWith: "Condividi...",
        fileMenu_ExportAsPDF: "PDF",
        fileMenu_ExportAsODF: "ODF",
        fileMenu_ExportAsPPT: "Microsoft Powerpoint 97- 2007 (*.ppt)",
        //	fileMenu_WebPreview: "Web Preview",
        fileMenu_PrintToPDF: "Esporta come PDF...",
        fileMenu_ViewFileDetails: "Visualizza dettagli del file...",
        fileMenu_RecentFile: "File recenti",
        fileMenu_Open: "Apri",
        fileMenu_Download: "Scarica",
        fileMenu_Print: "Stampa",
        fileMenu_Export: "Esporta",
        fileMenu_ExportToCSV: "CSV",
        fileMenu_ExportToPDF: "PDF (.pdf)",
        fileMenu_ExportToMarkdown: "Markdown (.md)",
        fileMenu_ExportToMS: "Formato Microsoft Office (.${FILEEXTENSION})",
        fileMenu_ExportToODF: "Formato Open Document (.${FILEEXTENSION})",
        fileMenu_PgSetup: "Impostazione pagina...",

        editMenu: "Modifica",
        editMenu_Undo: "Annulla",
        editMenu_Redo: "Ripristina",
        editMenu_Cut: "Taglia",
        editMenu_Copy: "Copia",
        editMenu_Paste: "Incolla",
        editMenu_DeleteSlide: "Elimina diapositiva",
        editMenu_SelectAll: "Seleziona tutto",
        editMenu_Find: "Trova...",
        editMenu_Replace: "Sostituisci...",
        editMenu_FindReplace: "Trova e sostituisci...",
        editMenu_EditLink: "Aggiungi o modifica collegamento",
        editMenu_DeleteSheet: "Elimina foglio...",
        editMenu_RenameSheet: "Rinomina foglio...",
        editMenu_HideSheet: "Nascondi foglio",
        editMenu_MoveSheet: "Sposta foglio...",
        editMenu_DeleteRow: "Elimina riga",
        editMenu_DeleteColumn: "Elimina colonna",
        editMenu_DeleteCellLeft: "Elimina celle e sposta a sinistra",
        editMenu_DeleteCellUp: "Elimina celle e sposta su",
        editMenu_ClearCell: "Elimina contenuto",

        viewMenu: "Visualizza",
        viewMenu_Master: "Principale",
        viewMenu_Notifications: "Notifiche",
        viewMenu_SlideSorter: "Sequenza diapositive",
        viewMenu_SpeakerNotes: "Note del relatore",
        viewMenu_Toolbar_Basic: "Base",
        viewMenu_Toolbar_Advanced: "Avanzate",
        viewMenu_Toolbar_None: "Nessuno",
        viewMenu_Toolbar: "Barra degli strumenti",
        viewMenu_Statusbar: "Barra di stato",
        viewMenu_Navigator: "Navigatore...",
        //viewMenu_Sidebar: "Sidebar",
        viewMenu_ShowHideIndicators: "Mostra indicatori co-modifica",
        viewMenu_Assignment: "Indicatori di assegnazione",
        viewMenu_Bookmark: "Segnalibri",
        viewMenu_Coediting: "Evidenziatori co-modifica",
        viewMenu_Rulers: "Righelli",
        viewMenu_WebLayout: "Layout web",
        viewMenu_AutomaticSpellCheck: "Controllo ortografico durante la digitazione",
        viewMenu_Formulabar: "Barra della formula",
        viewMenu_moveRight: "Invio sposta il cursore verso destra",
        viewMenu_showFullString: "Estendi contenuto nelle celle",
        viewMenu_Doc: "Visualizza documento",
        viewMenu_Templates: "Modelli",
        viewMenu_GridLines: "Nascondi linee della griglia",
        viewMenu_UnsupportWarning: "Mostra messaggi della funzione non supportata",
        viewMenu_HiddenSheets: "Fogli nascosti",
        viewMenu_FreezeRows: "Blocca righe",
        viewMenu_FreezeColumns: "Blocca colonne",
        viewMenu_NoFrozenRows: "Nessuna linea bloccata",
        viewmenu_NoFrozenColumns: "Nessuna colonna bloccata",
        viewMenu_FreezeXRows: "Blocca ${0} righe",
        viewMenu_FreezeOneRow: "Blocca ${0} riga",
        viewMenu_FreezeXColumns: "Blocca ${0} colonne",
        viewMenu_FreezeOneColumn: "Blocca ${0} colonna",
        viewMenu_CarriageReturn: "Contrassegni di formattazione",
        viewMenu_Navigation: "Pannello di navigazione",
        viewMenu_ACL: "Aree modificabili",
        viewMenu_GridOnOff: "Linee della griglia",
        viewMenu_ObserverMode: 'Modalità spettatore',

        createMenu: "Inserisci",
        createMenu_NewSlide: "Nuova diapositiva",
        createMenu_DuplicateSlide: "Duplica diapositiva",
        createMenu_ImageFromFile: "Immagine...",
        createMenu_TextBox: "Casella di testo",
        createMenu_Shape: "Forma",
        createMenu_break: "Interruzione",
        createMenu_RowAbove: "Riga sopra",
        createMenu_RowBelow: "Riga sotto",
        createMenu_ColumnRight: "Colonna a destra",
        createMenu_ColumnLeft: "Colonna a sinistra",
        createMenu_Sheet: "Foglio...",
        createMenu_Image: "Immagine...",
        createMenu_Comments: "Commento...",
        createMenu_WebLink: "Collegamento Web...",
        createMenu_SpecialCharacter: "Carattere speciale...",
        createMenu_Function: "Funzione...",
        createMenu_Fromtemplate: "Crea da modello",

        insertMenu: "Inserisci",
        insertMenu_break: "Interruzione di pagina",
        insertMenu_sectionbreak: "Interruzione di sezione",
        insertMenu_Bookmark: "Segnalibro...",
        insertMenu_WebLink: "Collegamento...",
        insertMenu_SpecialCharacter: "Carattere speciale...",
        insertMenu_HorizontalLine: "Linea orizzontale",
        insertMenu_Header: "Intestazione",
        insertMenu_Footer: "Piè di pagina",
        insertMenu_TableOfContents: "Indice",

        insertMenu_HeaderFooter: "Intestazione/Piè di pagina",
        insertMenu_HF_Edit: "Modifica",
        insertMenu_HF_Hide: "Nascondi",
        insertMenu_Endnotes: "Note di chiusura",
        insertMenu_RowAbove: "Riga sopra",
        insertMenu_PageNumber: "Numerazione pagina",
        insertMenu_PageNumberTop: "Inizio pagina",
        insertMenu_PageNumberBottom: "Fine pagina",
        insertMenu_PageNumberCurr: "Posizione corrente",
        insertMenu_TotalPageNumber: "Pagina 1 di N",
        insertMenu_Date: "Data...",
        insertMenu_Time: "Ora...",
        insertMenu_Fields: "Campi",
        //    insertMenu_Comment: "Comment",
        insertMenu_CellRight: "Celle e sposta a destra",
        insertMenu_CellDown: "Celle e sposta giù",
        insertMenu_RowBelow: "Riga sotto",
        insertMenu_ColumnBefore: "Colonna prima",
        insertMenu_ColumnAfter: "Colonna dopo",
        insertMenu_Sheet: "Foglio...",
        insertMenu_Image: "Immagine...",
        insertMenu_DuplicateSheet: "Duplica foglio",
        insertMenu_Function: "Funzione",
        insertMenu_FunctionSum: "SOMMA",
        insertMenu_FunctionAverage: "MEDIA",
        insertMenu_FunctionCount: "CONTEGGIO",
        insertMenu_FunctionMax: "MAX",
        insertMenu_FunctionMin: "MIN",
        insertMenu_FunctionMore: "Altre funzioni...",
        insertMenu_NameRange: "Intervallo denominato",
        insertMenu_NameRangeNew: "Nuovo intervallo...",
        insertMenu_NameRangeManage: "Gestisci intervalli...",
        insertMenu_Chart: "Grafico...",

        contextMenu_insertCellRight: "Inserisci celle e sposta a destra",
        contextMenu_insertCellDown: "Inserisci celle e sposta giù",
        contextMenu_InsertRowAbove: "Inserisci riga sopra",
        contextMenu_InsertRowBelow: "Inserisci riga sotto",
        contextMenu_InsertColumnBefore: "Inserisci colonna prima",
        contextMenu_InsertColumnAfter: "Inserisci colonna dopo",
        contextMenu_DownloadImage: "Scarica come immagine",

        formatMenu: "Formato",
        formatMenu_Columns: "Colonne",
        formatMenu_DefaultFormatting: "Formattazione predefinita",
        formatMenu_Template: "Stili...",
        contextMenu_Template: "Stili tabella...",
        formatMenu_LineSpacing: "Interlinea",
        formatMenu_LineSpacing1: "1",
        formatMenu_LineSpacing12: "1,2",
        formatMenu_LineSpacing15: "1,5",
        formatMenu_LineSpacing2: "2",
        formatMenu_LineSpacing25: "2,5",
        formatMenu_LineSpacing3: "3",
        formatMenu_TextProperties: "Proprietà testo",
        formatMenu_PageBreakBefore: "Interruzione pagina prima",
        formatMenu_KeepLines: "Mantieni assieme le linee",
        formatMenu_WidowControl: "Controllo righe isolate",
        formatMenu_Pagination: "Proprietà paragrafo",
        formatMenu_Bold: "Grassetto",
        formatMenu_Italic: "Corsivo",
        formatMenu_Underline: "Sottolineato",
        formatMenu_Strikethrough: "Barrato",
        formatMenu_IncreaseSize: "Aumenta la dimensione del font",
        formatMenu_DecreaseSize: "Diminuisci la dimensione del font",
        formatMenu_ImageProperties: "Proprietà immagine...",
        formatMenu_ChartProperties: "Proprietà grafico...",
        formatMenu_EditChart: "Modifica grafico",
        formatMenu_InsertChart: "Inserisci grafico",
        formatMenu_Properties: "Proprietà...",
        formatMenu_Heading: "Intestazione",
        formatMenu_Normal: "Normale",
        formatMenu_Title: "Titolo",
        formatMenu_Subtitle: "Sottotitolo",
        formatMenu_Heading1: "Intestazione 1",
        formatMenu_Heading2: "Intestazione 2",
        formatMenu_Heading3: "Intestazione 3",
        formatMenu_Heading4: "Intestazione 4",
        formatMenu_Heading5: "Intestazione 5",
        formatMenu_Heading6: "Intestazione 6",
        formatMenu_Heading7: "Intestazione 7",
        formatMenu_Heading8: "Intestazione 8",
        formatMenu_Heading9: "Intestazione 9",
        formatMenu_BulletedList: "Elenco puntato",
        formatMenu_NumberedList: "Elenco numerato",
        formatMenu_OutLine: "Elenco multilivello",
        formatMenu_Superscript: "Apice",
        formatMenu_Subscript: "Pedice",
        formatMenu_Align: "Allinea",
        formatMenu_Left: "A sinistra",
        formatMenu_Right: "A destra",
        formatMenu_Center: "Centra",
        formatMenu_Justify: "Giustifica",
        formatMenu_Text_Direction: "Orientamento testo",
        formatMenu_Ltr: "Da sinistra a destra",
        formatMenu_Rtl: "Da destra a sinistra",
        formatMenu_LineSpacing: "Interlinea",
        formatMenu_LineSpacing1: "1,0",
        formatMenu_LineSpacing115: "1,15",
        formatMenu_LineSpacing15: "1,5",
        formatMenu_LineSpacing2: "2,0",
        formatMenu_LineSpacing25: "2,5",
        formatMenu_LineSpacing3: "3.0",
        formatMenu_Top: "In alto",
        formatMenu_Bottom: "In basso",
        formatMenu_Middle: "Al centro",
        formatMenu_Direction: "Orientamento testo",
        formatMenu_Rtl: "Da destra a sinistra",
        formatMenu_Ltr: "Da sinistra a destra",
        formatMenu_Auto: "Contestuale",
        formatMenu_SheetDirection: "Orientamento foglio",
        formatMenu_SheetRtl: "Da destra a sinistra",
        formatMenu_SheetLtr: "Da sinistra a destra",
        formatMenu_Indent: "Aumenta rientro",
        formatMenu_DecreaseIndent: "Diminuisci rientro",
        formatMenu_ClearFormat: "Cancella formattazione",
        formatMenu_RowHeight: "Altezza riga",
        formatMenu_ColumnWidth: "Larghezza colonna",
        formatMenu_ShowRow: "Mostra riga",
        formatMenu_HideRow: "Nascondi riga",
        formatMenu_ShowColumn: "Mostra colonna",
        formatMenu_HideColumn: "Nascondi colonna",
        formatMenu_WrapText: "Manda a capo testo",
        formatMenu_Number: "Numero",
        formatMenu_FontArial: "Arial",
        formatMenu_FontComicSansMS: "Comic Sans MS",
        formatMenu_FontCourierNew: "Courier New",
        formatMenu_FontGeorgia: "Georgia",
        formatMenu_FontLucidaSansUnicode: "Lucida Sans Unicode",
        formatMenu_FontTahoma: "Tahoma",
        formatMenu_FontTimesNewRoman: "Times New Roman",
        formatMenu_FontTrebuchetMS: "Trebuchet MS",
        formatMenu_FontVerdana: "Verdana",
        formatMenu_FontName: "Font",

        layoutMenu: "Layout",
        layoutMenu_SlideLayout: "Layout diapositiva...",
        layoutMenu_SlideDesign: "Stile principale...",
        layoutMenu_DefaultFormatting: "Formattazione predefinita",
        layoutMenu_Textprop_Bold: "Grassetto",
        layoutMenu_Textprop_Italic: "Corsivo",
        layoutMenu_Textprop_Underline: "Sottolineato",
        layoutMenu_Textprop_Strikethrough: "Barrato",
        layoutMenu_TextProp: "Proprietà testo",
        LayoutMenu_RowHeight: "Altezza riga...",
        LayoutMenu_ColumnWidth: "Larghezza colonna...",
        LayoutMenu_ShowRow: "Mostra riga",
        LayoutMenu_HideRow: "Nascondi riga",
        LayoutMenu_RenameSheet: "Rinomina foglio...",
        LayoutMenu_MoveSheet: "Sposta foglio",

        tableMenu: "Tabella",
        tableMenu_Create: "Crea...",
        tableMenu_CreateFromTemplate: "Crea da modello",
        tableMenu_Delete: "Elimina",
        tableMenu_SetTableColor: "Colora cella",
        tableMenu_CreateTable: "Crea tabella",
        tableMenu_Cell: "Cella",
        tableMenu_CellMergeCells: "Unisci celle",
        tableMenu_CellAlignLeft: "Allinea a sinistra",
        tableMenu_CellAlignCenter: "Centra",
        tableMenu_CellAlignRight: "Allinea a destra",
        tableMenu_CellClearContents: "Cancella contenuto",
        tableMenu_CellProperties: "Proprietà cella...",
        tableMenu_Row: "Riga",
        tableMenu_InsertRowAbove: "Inserisci riga sopra",
        tableMenu_InsertRowBelow: "Inserisci riga sotto",
        tableMenu_MoveRowAbove: "Sposta riga su",
        tableMenu_MoveRowBelow: "Sposta riga giù",
        tableMenu_RowInsertRow: "Inserisci riga...",
        tableMenu_RowInsertRowAbove: "Inserisci riga sopra",
        tableMenu_RowInsertRowBelow: "Inserisci riga sotto",
        tableMenu_RowMoveRowAbove: "Sposta riga sopra",
        tableMenu_RowMoveRowBelow: "Sposta riga sotto",
        tableMenu_RowDelete: "Elimina",
        tableMenu_RowRepeat: "Ripeti riga intestazione",
        tableMenu_InsertColumnBefore: "Inserisci colonna prima",
        tableMenu_InsertColumnAfter: "Inserisci colonna dopo",
        tableMenu_MoveColumnBefore: "Sposta colonna a sinistra",
        tableMenu_MoveColumnAfter: "Sposta colonna a destra",
        tableMenu_ResizeColumn: "Ridimensiona colonna",
        tableMenu_ResizeColumns: "Ridimensiona colonne",
        tableMenu_MarkasCategory: "Contrassegna come categoria",
        tableMenu_ColumnInsertColumn: "Inserisci colonna...",
        tableMenu_ColumnAddColumnBefore: "Inserisci colonna prima",
        tableMenu_ColumnAddColumnAfter: "Inserisci colonna dopo",
        tableMenu_ColumnMoveColumnAfter: "Sposta colonna dopo",
        tableMenu_ColumnMoveColumnBefore: "Sposta colonna prima",
        tableMenu_ColumnDelete: "Elimina",
        tableMenu_ColumnSortAscending: "Ordinamento crescente",
        tableMenu_ColumnSortDescending: "Ordinamento decrescente",
        tableMenu_Column: "Colonna",
        tableMenu_Style: "Stile",
        tableMenu_TableProperties: "Proprietà tabella...",

        teamMenu: "Gruppo",
        teamMenu_AddComment: "Aggiungi commento",
        teamMenu_AssignCells: "Assegna celle",
        teamMenu_AssignSection: "Assegna una sezione",
        teamMenu_EditAssignment: "Modifica assegnazione",
        teamMenu_MarkSectionComplete: "Contrassegna sezione come completa",
        teamMenu_MarkAssignmentComplete: "Contrassegna l'assegnazione come completa",
        teamMenu_WorkPrivatelyOnSection: "Lavora privatamente sulla sezione",
        teamMenu_CancelPrivateWork: "Annulla lavoro privato",
        teamMenu_ApproveSection: "Approva sezione",
        teamMenu_ApproveAssignment: "Approva assegnazione",
        teamMenu_ReturnSectionForRework: "Restituisci sezione per la rielaborazione",
        teamMenu_ReturnAssignmentForRework: "Restituisci assegnazione per la rielaborazione",
        teamMenu_RemoveSectionAssignment: "Rimuovi assegnazione sezione",
        teamMenu_RemoveCellAssignment: "Rimuovi assegnazione cella",
        teamMenu_RemoveCompletedAssignments: "Rimuovi assegnazioni completate",
        teamMenu_AboutThisSection: "Informazioni su questa sezione",
        teamMenu_AboutAssignment: "Informazioni su questa assegnazione",

        presentationMenu: "Presentazione",
        presentationMenu_SlideShow: "Riproduci presentazione",
        presentationMenu_SlideShowWithCoview: "Riproduci presentazione condivisa",
        presentationMenu_SlideTransitions: "Applica transizione diapositiva...",
        presentationMenu_SlideShowFromCurrent: "Riproduci dalla diapositiva corrente",
        presentationMenu_EmptyCoviewInvites: "Nessuna presentazione condivisa attiva",
        presentationMenu_CoviewInvites: "Presentazione condivisa attiva",

        dataMenu: "Dati",
        dataMenu_Sort: "Ordina...",
        dataMenu_SortAsc: "Ordinamento crescente",
        dataMenu_SortDesc: "Ordinamento decrescente",
        dataMenu_ACL: "Aree protette",
        dataMenu_ACL_DELETE: "Elimina tutte le autorizzazioni",
        dataMenu_Validity: "Validità",
        dataMenu_InstantFilter: "Filtro istantaneo",
        dataMenu_Validation: "Convalida...",

        toolsMenu: "Strumenti",
        toolsMenu_AutoComplete: "Completamento automatico voci cella",
        toolsMenu_SelectDictionary: "Dizionari di controllo ortografico",
        toolsMenu_Dictionary_ca_CT: "Catalano",
        toolsMenu_Dictionary_cs_CZ: "Ceco (Repubblica ceca)",
        toolsMenu_Dictionary_da_DK: "Danese (Danimarca)",
        toolsMenu_Dictionary_nl_NL: "Olandese (Paesi Bassi)",
        toolsMenu_Dictionary_en_AU: "Inglese (Australia)",
        toolsMenu_Dictionary_en_GB: "Inglese (Gran Bretagna)",
        toolsMenu_Dictionary_en_US: "Inglese (Stati Uniti)",
        toolsMenu_Dictionary_fi_FI: "Finlandese (Finlandia)",
        toolsMenu_Dictionary_fr_FR: "Francese (Francia)",
        toolsMenu_Dictionary_fr_CA: "Francese (Canada)",
        toolsMenu_Dictionary_de_DE: "Tedesco (Germania)",
        toolsMenu_Dictionary_de_CH: "Tedesco (Svizzera)",
        toolsMenu_Dictionary_el_GR: "Greco (Grecia)",
        toolsMenu_Dictionary_it_IT: "Italiano (Italia)",
        toolsMenu_Dictionary_pl_PL: "Polacco (Polonia)",
        toolsMenu_Dictionary_pt_BR: "Portoghese (Brasile)",
        toolsMenu_Dictionary_pt_PT: "Portoghese (Portogallo)",
        toolsMenu_Dictionary_ru_RU: "Russo (Russia)",
        toolsMenu_Dictionary_es_ES: "Spagnolo (Spagna)",
        toolsMenu_Dictionary_sv_SE: "Svedese (Svezia)",
        toolsMenu_Dictionary_nb_NO: "Norvegese (Bokml)",
        toolsMenu_Dictionary_nn_NO: "Norvegese (Nynorsk)",
        toolsMenu_Dictionary_he_IL: "Ebraico (Israele)",
        toolsMenu_SpellCheck: "Esegui controllo ortografico manuale...",
        toolsMenu_Preferences: "Preferenze",
        toolsMenu_Task: "Attività",
        toolsMenu_Task_Assigntask: "Assegna un\'attività",
        teamMenu_AssignSlide: "Assegna diapositiva",
        teamMenu_AssignSlides: "Assegna diapositive",
        teamMenu_EditSlide: "Modifica assegnazione diapositiva",
        teamMenu_ReopenSlideAssignment: "Riapri l'assegnazione della diapositiva",
        teamMenu_ReopenSlideAssignments: "le Riapri assegnazioni delle diapositive",
        teamMenu_ReassignSlide: "Riassegna diapositiva",
        teamMenu_ReassignSlides: "Riassegna diapositive",
        teamMenu_MarkSlidesComplete: "Contrassegna la diapositiva come completa",
        teamMenu_MarkSlidesCompletes: "Contrassegna le diapositive come complete",
        teamMenu_ApproveSlide: "Approva diapositiva",
        teamMenu_ApproveSlides: "Approva diapositive",
        teamMenu_ReturnForRework: "Restituisci diapositiva per la rielaborazione",
        teamMenu_ReturnForReworks: "Restituisci diapositive per la rielaborazione",
        teamMenu_RemoveAssignment: "Rimuovi assegnazione diapositiva",
        teamMenu_AboutThisSlide: "Informazioni su questa diapositiva",

        addOnsMenu: "Componenti aggiuntivi",

        helpMenu: "Guida",
        helpMenu_About: "Informazioni",
        helpMenu_Overview: "Contenuto della guida",
        helpMenu_NewFeatures: "Novità",
        helpMenu_Tour: "Presentazione guidata",

        accel_fileMenu_Save: "Ctrl+S",
        accel_fileMenu_Save_Mac: "\u2318S",
        accel_fileMenu_Print: "Ctrl+P",
        accel_fileMenu_Print_Mac: "\u2318P",
        accel_editMenu_SelectAll: "Ctrl+A",
        accel_editMenu_SelectAll_Mac: "\u2318A",
        accel_editMenu_Undo: "Ctrl+Z",
        accel_editMenu_Undo_Mac: "\u2318Z",
        accel_editMenu_Redo: "Ctrl+Y",
        accel_editMenu_Redo_Mac: "\u2318Y",
        accel_editMenu_Cut: "Ctrl+X",
        accel_editMenu_Cut_Mac: "\u2318X",
        accel_editMenu_Copy: "Ctrl+C",
        accel_editMenu_Copy_Mac: "\u2318C",
        accel_editMenu_Paste: "Ctrl+V",
        accel_editMenu_Paste_Mac: "\u2318V",
        accel_editMenu_Find: "Ctrl+F",
        accel_editMenu_Find_Mac: "\u2318F",
        accel_insertMenu_Link: "Ctrl+K",
        accel_insertMenu_Link_Mac: "\u2318K",
        accel_insertMenu_Header: "CTRL+MAIUSC+H",
        accel_insertMenu_Header_Mac: "\u21e7\u2318H",
        accel_insertMenu_Footer: "CTRL+MAIUSC+F",
        accel_insertMenu_Footer_Mac: "\u21e7\u2318F",
        accel_formatMenu_Textprop_Bold: "Ctrl+B",
        accel_formatMenu_Textprop_Bold_Mac: "\u2318B",
        accel_formatMenu_Textprop_Italic: "Ctrl+I",
        accel_formatMenu_Textprop_Italic_Mac: "\u2318I",
        accel_formatMenu_Textprop_FormatPainter: "Ctrl+SHIFT+C, Ctrl+SHIFT+V",
        accel_formatMenu_Textprop_FormatPainter_Mac: "\u21e7\u2318C, \u21e7\u2318V",
        accel_formatMenu_Textprop_Underline: "Ctrl+U",
        accel_formatMenu_Textprop_Underline_Mac: "\u2318U",
        accel_formatMenu_Headingprop_P: "CTRL+MAIUSC+0",
        accel_formatMenu_Headingprop_H1: "CTRL+MAIUSC+1",
        accel_formatMenu_Headingprop_H2: "CTRL+MAIUSC+2",
        accel_formatMenu_Headingprop_H3: "CTRL+MAIUSC+3",
        accel_formatMenu_Headingprop_H4: "CTRL+MAIUSC+4",
        accel_formatMenu_Headingprop_H5: "CTRL+MAIUSC+5",
        accel_formatMenu_Headingprop_H6: "CTRL+MAIUSC+6",
        accel_formatMenu_Superscript: "Ctrl+.",
        accel_formatMenu_Superscript_Mac: "\u2318.",
        accel_formatMenu_Subscript: "Ctrl+,",
        accel_formatMenu_Subscript_Mac: "\u2318,",
        accel_formatMenu_Left: "CTRL+MAIUSC+L",
        accel_formatMenu_Left_Mac: "\u21e7\u2318L",
        accel_formatMenu_Right: "CTRL+MAIUSC+R",
        accel_formatMenu_Right_Mac: "\u21e7\u2318R",
        accel_formatMenu_Center: "CTRL+MAIUSC+E",
        accel_formatMenu_Center_Mac: "\u21e7\u2318E",
        accel_formatMenu_Justify: "CTRL+MAIUSC+J",
        accel_formatMenu_Justify_Mac: "\u21e7\u2318J",
        accel_formatMenu_Indent: "CTRL+M",
        accel_formatMenu_Indent_Mac: "\u2318M",
        accel_formatMenu_DecreaseIndent: "CTRL+MAIUSC+M",
        accel_formatMenu_DecreaseIndent_Mac: "\u21e7\u2318M",
        accel_teamMenu_AddComment: "MAIUSC+F2",

        ctxMenuSmartTable: 'Tabella',
        ctxMenuTableProperties: "Proprietà tabella",
        ctxMenuDeleteST: 'Elimina',
        ctxMenuDeleteSTTable: 'Elimina tabella',
        ctxMenuChgSTStyle: 'Modifica stile',
        ctxMenuShowCaption: 'Mostra didascalia',
        ctxMenuHideCaption: 'Nascondi didascalia',
        ctxMenuResizeST: 'Ridimensiona',
        ctxMenuResizeColumnsST: 'Ridimensiona colonne',
        ctxMenuSTRow: 'Riga',
        ctxMenuAddSTRowAbv: 'Inserisci riga sopra',
        ctxMenuAddSTRowBlw: 'Inserisci riga sotto',
        ctxMenuMoveSTRowUp: 'Sposta riga sopra',
        ctxMenuMoveSTRowDown: 'Sposta riga sotto',
        ctxMenuDelSTRow: 'Elimina',
        ctxMenuRepeatRow: 'Ripeti riga intestazione',
        ctxMenuSTCol: 'Colonna',
        ctxMenuAddSTColBfr: 'Inserisci colonna prima',
        ctxMenuAddSTColAft: 'Inserisci colonna dopo',
        ctxMenuMoveSTColBefore: 'Sposta colonna prima',
        ctxMenuMoveSTColAfter: 'Sposta colonna dopo',
        ctxMenuDelSTCol: 'Elimina',
        ctxMenuSortSTColAsc: 'Ordinamento crescente',
        ctxMenuSortSTColDesc: 'Ordinamento decrescente',
        ctxMenuShowAllFacets: 'Mostra categorie',
        ctxMenuHideAllFacets: 'Nascondi categorie',
        ctxMenuSTCell: 'Cella',
        ctxMenuMergeCells: 'Unisci celle',
        ctxMenuMergeDown: 'Unisci con la cella in basso',
        ctxMenuVerSplit: 'Separa verticalmente',
        ctxMenuHorSplit: 'Suddividi orizzontalmente',
        ctxMenuSplitCells: 'Dividi celle...',
        splitCells: 'Dividi cella',
        ctxMenuAlignTextLeft: 'Allinea a sinistra',
        ctxMenuAlignTextCenter: 'Centra',
        ctxMenuAlignTextRight: 'Allinea a destra',
        ctxMenuClearSTCellContent: 'Cancella contenuto',
        ctxMenuMakeHeaderRow: 'Utilizza riga selezionata come intestazione',
        ctxMenuMakeNonHeaderRow: 'Rimuove stile intestazione',
        ctxMenuMakeHeaderCol: 'Utilizza colonna selezionata come intestazione',
        ctxMenuMakeNonHeaderCol: 'Rimuove stile intestazione',
        SHEET_CONTEXT_Hide: "Nascondi", // hide row, column or sheet
        SHEET_CONTEXT_Show: "Mostra", // show row, column
        SHEET_CONTEXT_MoveSheet: "Sposta...", // move sheet
        SHEET_CONTEXT_InsertSheet: "Inserisci...", // insert sheet
        SHEET_CONTEXT_DeleteSheet: "Elimina...", // delete sheet	
        SHEET_CONTEXT_DuplicateSheet: "Duplica...", // duplicate sheet
        SHEET_CONTEXT_RenameSheet: "Rinomina...", // rename sheet
	
        ctxMenu_Image_WrapText: "Manda a capo testo",
        ctxMenu_Image_WrapText_Inline: "In linea con il testo",
        ctxMenu_Image_WrapText_Square: "Quadrato",
        ctxMenu_Image_WrapText_TopBottom: "Sopra e sotto",
        ctxMenu_Image_WrapText_Behind: "Dietro il testo",
        ctxMenu_Image_WrapText_InFront: "Davanti al testo",
        ctxMenu_Image_WrapText_Other: "Più testo a capo",
        ctxMenu_Image_WrapText_BothSides: "Entrambi i lati",
        ctxMenu_Image_WrapText_LeftOnly: "Solo a sinistra",
        ctxMenu_Image_WrapText_RightOnly: "Solo a destra",
        ctxMenu_Image_WrapText_LargestOnly: "Solo più grande",

        ctxMenu_Shape_AddText: "Aggiungi testo",

        ctxMenu_Range_ACL: "Proteggi intervallo",
        ctxMenu_Sheet_ACL: "Proteggi foglio",

        ctxMenu_HeaderFooter: "Intestazione / Piè di pagina",
        ctxMenu_HeaderFooter_DiffFirst: "Solo prima pagina",
        ctxMenu_HeaderFooter_DiffOddEven: "Pagine dispari e pari diverse",
        ctxMenu_HeaderFooter_LinkToPre: "Collega al precedente",

        ctxMenu_copy: "Copia",
        ctxMenu_paste: "Incolla",
        ctxMenu_delete: "Elimina",
        ctxMenu_cut: "Taglia",
        ctxMenu_select: "Seleziona",
        ctxMenu_properties: "Proprietà",
        ctxMenu_bringToFront: "Porta in primo piano",
        ctxMenu_sendToBack: "Porta in secondo piano",
        ctxMenu_arrange: "Disponi",
        ctxMenu_sendBackward: "Porta indietro",
        ctxMenu_sendForward: "Porta avanti",
        ctxMenu_fontStyle: "Stile di font",
        ctxMenu_selectStyle: "Seleziona stile",
        ctxMenu_fontSize: "Dimensione font",
        ctxMenu_fontFamily: "Famiglia di font",
        ctxMenu_bold: "Grassetto",
        ctxMenu_italic: "Corsivo",
        ctxMenu_u: "Sottolineato",
        ctxMenu_strike: "Barrato",
        ctxMenu_super: "Apice",
        ctxMenu_sub: "Pedice",
        ctxMenu_color: "Colore",
        ctxMenu_bgcolor: "Colore sfondo",
        ctxMenu_highcolor: "Colore di evidenziazione",
        ctxMenu_restart: "Riavvia elenco",
        ctxMenu_continue: "Continua elenco",
        ctxMenu_separate: "Separa elenco",
        ctxMenu_join: "Unisci a elenco precedente",
        ctxMenu_setNumberVal: "Imposta valore di numerazione...",
        webClipboardInfoTitle: "Appunti",
        webClipboardInfoOKBtn: "OK",
        webClipboardInfoCutMsg: "Le impostazioni della sicurezza del browser impediscono la copia automatica. In alternativa, utilizzare Ctrl+X sulla tastiera.",
        webClipboardInfoCopyMsg: "Le impostazioni della sicurezza del browser impediscono la copia automatica. In alternativa, utilizzare Ctrl+C sulla tastiera.",
        webClipboardInfoPasteMsg: "Le impostazioni della sicurezza del browser impediscono a questo editor di accedere ai dati degli appunti. In alternativa, utilizzare Ctrl+V sulla tastiera.",

        clearTrackChangeConfirmMsg: "Tutte le codifiche a colori che contrassegnano le modifiche in questo documento verranno rimosse. Si desidera continuare?"
});

