/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
	fileMenu: "File",
	fileMenu_New: "Nuovo",
	fileMenu_NewDocument: "Documento",
	fileMenu_NewDocumentfromTemplate: "Documento da modello",
	fileMenu_NewPresentation: "Presentazione",
	fileMenu_NewPresentationfromTemplate: "Presentazione da modello",
	fileMenu_NewSpreadsheet: "Foglio di calcolo",
	fileMenu_Open: "Apri",
//	fileMenu_Close: "Close",
	fileMenu_Discard: "Elimina",
	fileMenu_Save: "Salva",
//	fileMenu_SaveAs: "Save As...",
//	fileMenu_SaveAsDraft: "as Draft",
//	fileMenu_SaveInMyDocs: "in My Documents",
//	fileMenu_SaveToSymphony: "to Lotus Symphany",
	fileMenu_ShareWith: "Condividi con...	",
	fileMenu_ExportAsPDF: "Esporta come PDF",
	fileMenu_WebPreview: "Anteprima Web",
	fileMenu_PrintPreview: "Anteprima di stampa",
	fileMenu_RecentFile: "File recenti",
	fileMenu_Print: "Stampa...",
	editMenu: "Modifica",
	editMenu_Undo: "Annulla",
	editMenu_Redo: "Ripristina",
	editMenu_Cut: "Taglia",
	editMenu_Copy: "Copia",
	editMenu_Paste: "Incolla",
	editMenu_DeleteSlide:"Elimina diapositiva",
	editMenu_SelectAll: "Seleziona tutto",
	editMenu_Find: "Trova...",
	editMenu_Replace: "Sostituisci...",
	editMenu_DeleteSheet: "Elimina foglio",
	editMenu_DuplicateSheet: "Duplica foglio",
	editMenu_DeleteRow: "Elimina riga",
	editMenu_DeleteColumn: "Elimina colonna",
	editMenu_ClearCell: "Cancella cella",
	viewMenu: "Visualizza",
	viewMenu_Master: "Principale",
	viewMenu_Notifications: "Notifiche",
	viewMenu_ShowHideIndicators: "Mostra/Nascondi indicatori co-editing",
	viewMenu_SlideSorter: "Mostra sequenza diapositive",
	viewMenu_SpeakerNotes: "Mostra note del relatore",
	viewMenu_NextSlide: "Diapositiva successiva",
	viewMenu_PrevSlide: "Diapositiva precedente",
	createMenu: "Crea",
	createMenu_NewSlide: "Nuova diapositiva",
	createMenu_DuplicateSlide: "Duplica diapositiva",
	createMenu_ImageFromFile: "Grafico da file",
	createMenu_TextBox: "Casella di testo",
	createMenu_Task: "Attività",
    formatMenu_Text_Direction: "Orientamento testo",
    formatMenu_Ltr: "Da sinistra a destra",
    formatMenu_Rtl: "Da destra a sinistra",  	
    formatMenu_Horizontal_Align: "Allineamento orizzontale",
    formatMenu_Vertical_Align: "Allineamento verticale",
    formatMenu_Align_Top: "In alto",
    formatMenu_Align_Middle: "Al centro",
    formatMenu_Align_Bottom: "In basso",
	layoutMenu: "Layout",
	layoutMenu_SlideLayout: "Layout diapositiva",
	layoutMenu_SlideDesign: "Stili principali",
	tableMenu: "Tabella",
	tableMenu_CreateTable: "Crea tabella",
	tableMenu_Cell: "Cella",
	tableMenu_CellAlignLeft: "Allinea il testo a sinistra",
	tableMenu_CellAlignCenter: "Centra il testo",
	tableMenu_CellAlignRight: "Allinea il testo a destra",
	tableMenu_CellClearContents: "Cancella contenuto",
	tableMenu_Row: "Riga",
	tableMenu_RowAddRowAbove: "Aggiungi riga sopra",
	tableMenu_RowAddRowBelow: "Aggiungi riga sotto",
	tableMenu_RowMoveRowAbove: "Sposta riga sopra",
	tableMenu_RowMoveRowBelow: "Sposta riga sotto",
	tableMenu_RowDelete: "Elimina",
	tableMenu_ColumnAddColumnBefore: "Aggiungi colonna prima",
	tableMenu_ColumnAddColumnAfter: "Aggiungi colonna dopo",
	tableMenu_ColumnMoveColumnAfter: "Sposta colonna dopo",
	tableMenu_ColumnMoveColumnBefore: "Sposta colonna prima",
	tableMenu_ColumnDelete: "Elimina",
	tableMenu_ColumnSortAscending: "Ordinamento crescente",
	tableMenu_ColumnSortDescending: "Ordinamento decrescente",
	tableMenu_Column: "Colonna",
	tableMenu_Delete: "Elimina",
	presentationMenu: "Presentazione",
	presentationMenu_SlideShow: "Riproduci presentazione",
	presentationMenu_SlideShowFromCurrent: "Riproduci dalla diapositiva corrente",
	toolsMenu: "Strumenti",
	toolsMenu_Task: "Attività",
	helpMenu: "Guida",
	helpMenu_Overview: "Contenuto della guida"
})

