({
		SAVE: "שמירה",
		UNDO:"ביטול פעולה",
		REDO:"שחזור פעולה",
		INSERTROW:"הוספת שורה",
		DELETEROW:"מחיקת שורה",
		INSERTCOLUMN:"הוספת עמודה",
		DELETECOLUMN:"מחיקת עמודה",
		FONTSIZE:"גודל גופן",
		FONTCOLOR:"צבע גופן",
		BOLD:"מודגש",
		ITALIC:"נטוי",
		UNDERLINE:"קו תחתי",
		STRIKETHROUGH:"קו חוצה",
		CURRENCYTIP:"עיצוב כמטבע",
		PERCENTLABEL:"%",
		PERCENTTIP:"עיצוב כאחוז",
		NUMBERFORMAT:"עיצוב מספר",
		ALIGNLEFT:"יישור לשמאל",
		ALIGNCENTER:"יישור למרכז",
		ALIGNRIGHT:"יישור לימין",
		SETCELLBORDER:"הגדרת גבול תא",
		BACKGROUNDCOLOR:"צבע רקע",
		TASK:"הקצאת חלק",
		COMMENTS:"הוספת הערה",
		SUBMIT:"הגשה",
		MERGECELL: "מיזוג או פיצול תאים",
		QUICKFORMULA: "נוסחה מהירה",
		WRAPTEXT: "גלישת תמליל",
		EIGHT:"8pt",
		NINE:"9pt",
		TEN:"10pt",
		ELEVEN:"11pt",
		TWELVE:"12pt",
		FOURTEEN:"14pt",
		SIXTEEN:"16pt",
		EIGHTEEN:"18pt",
		TWENTY:"20pt",
		TWENTYTWO:"22pt",
		TWENTYFOUR:"24pt",
		NUMBER:"מספר",
		CURRENCY:"מטבע",
		PERCENT:"אחוזים",
		DATE:"תאריך",
		TIME:"שעה",
		DATETIME: "תאריך-שעה",
		MORECURRENCY:"עוד מטבעות",
		MOREDATE:"עוד מבנים ",
		
		
		CAD: "דולר קנדי ",
		USD: "דולר",
		EUR: "אירו",
		CHF: "פרנק שוויצרי",
		HKD: "דולר הונג קונג",
		DKK: "קרונה",
		LTL: "לאטי ",
		PHP: "פזו",
		BRL: "ריאל",
		RUR: "רובל ",
		GBP: "לירה שטרלינג",
		NLG: "גילדר ", // Netherlands
		TWD: "דולר טעיוואני החדש",
		THB: "באט ", // Thailand
		ITL: "לירה ", // Turkey
		BGL: "לב ", // Uzbekistan
		VND: "דונג", // Vietnam
		KRW: "וון",	// Korean 
		CNY: "יואן ", // RMB
		JPY: "ין " // Japan Yen
})
