define({      
//begin v1.x content
	"clearFilterDialogTitle": "Tyhjennä suodatin",
	"filterDefDialogTitle": "Suodatin",
	"defaultRuleTitle": "Sääntö",
	"ruleTitleTemplate": "Sääntö ${ruleNumber}",
	"noFilterApplied": "Suodatinta ei ole käytössä.",
	"defineFilter": "Määritä suodatin",
	"conditionEqual": "yhtä suuri kuin",
	"conditionNotEqual": "eri suuri kuin",
	"conditionLess": "pienempi kuin",
	"conditionLessEqual": "pienempi tai yhtä suuri kuin",
	"conditionGreater": "suurempi kuin",
	"conditionGreaterEqual": "suurempi tai yhtä suuri kuin",
	"conditionContain": "sisältää",
	"conditionIs": "on",
	"conditionStartWith": "alkaa merkein",
	"conditionEndWith": "loppuu merkein",
	"conditionNotContain": "ei sisällä",
	"conditionIsNot": "ei ole",
	"conditionNotStartWith": "ei ala merkein",
	"conditionNotEndWith": "ei lopu merkein",
	"conditionBefore": "ennen",
	"conditionAfter": "jälkeen",
	"conditionRange": "alueella",
	"conditionIsEmpty": "on tyhjä",
	"all": "kaikki",
	"any": "mikä tahansa",
	"relationAll": "kaikki säännöt",
	"waiRelAll": "Vastaa kaikkia seuraavia sääntöjä:",
	"relationAny": "mikä tahansa sääntö",
	"waiRelAny": "Vastaa mitä tahansa seuraavista säännöistä:",
	"relationMsgFront": "Vastine",
	"relationMsgTail": "",
	"and": "ja",
	"or": "tai",
	"addRuleButton": "Lisää sääntö",
	"waiAddRuleButton": "Lisää uusi sääntö",
	"removeRuleButton": "Poista sääntö",
	"waiRemoveRuleButtonTemplate": "Poista sääntö ${0}",
	"addRuleButton": "Lisää suodatussääntö",
	"cancelButton": "Peruuta",
	"waiCancelButton": "Peruuta valintaikkuna",
	"clearButton": "Tyhjennä",
	"waiClearButton": "Tyhjennä suodatin",
	"filterButton": "Suodata",
	"waiFilterButton": "Lähetä suodatin",
	"columnSelectLabel": "Sarake:",
	"waiColumnSelectTemplate": "Säännön ${0} sarake",
	"conditionSelectLabel": "Ehto:",
	"waiConditionSelectTemplate": "Säännön ${0} ehto",
	"valueBoxLabel": "Arvo:",
	"waiValueBoxTemplate": "Anna säännön ${0} suodatettava arvo",
	"rangeTo": "–",
	"rangeTemplate": "${0}–${1}",
	"statusTipHeaderColumn": "Sarake",
	"statusTipHeaderCondition": "Säännöt",
	"statusTipTitle": "Suodatinpalkki",
	"statusTipMsg": "Suodata arvot (${0}) napsauttamalla suodatinpalkkia tästä.",
	"anycolumn": "mikä tahansa sarake",
	"statusTipTitleNoFilter": "Suodatinpalkki",
	"statusTipTitleHasFilter": "Suodatin",
	"statusTipRelPre": "Vastaa",
	"statusTipRelPost": "sääntöä.",
	"statusTipHeaderAll": "Vastaa kaikkia sääntöjä.",
	"statusTipHeaderAny": "Vastaa mitä tahansa sääntöjä.",
	"defaultItemsName": "kohdetta",
	"filterBarMsgHasFilterTemplate": "Näkyvissä ${0}/${1} ${2}.",
	"filterBarMsgNoFilterTemplate": "Suodatinta ei ole käytössä",
	"filterBarDefButton": "Määritä suodatin",
	"waiFilterBarDefButton": "Suodata taulukko",
	"a11yFilterBarDefButton": "Suodatin...",
	"filterBarClearButton": "Tyhjennä suodatin",
	"waiFilterBarClearButton": "Tyhjennä suodatin",
	"closeFilterBarBtn": "Sulje suodatinpalkki",
	"clearFilterMsg": "Tämä poistaa suodattimen ja näyttää kaikki käytettävissä olevat tietueet.",
	"anyColumnOption": "Mikä tahansa sarake",
	"trueLabel": "Tosi",
	"falseLabel": "Epätosi",
	"radioTrueLabel": "Tosi-arvo",
	"radioFalseLabel": "Epätosi-arvo",
	"beginTimeRangeLabel": "Aika-alueen alkuarvo",
	"endTimeRangeLabel": "Aika-alueen loppuarvo",
	"beginDateRangeLabel": "Päivämääräalueen alkuarvo",
	"endDateRangeLabel": "Päivämääräalueen loppuarvo",
	"startsWithExpr": "${0}*"
//end v1.x content
});

