({	
	viewExpandedBtn: "مشاهدة ردود أقل",
	viewCollapsedBtn: "مشاهدة ${0} ردود أخرى",
	placeholderMsg: "أكتب رسالتك هنا",
	sure: "هل أنت واثق أنك تريد حذف هذا التعقيب؟",
	exceed: "التعقيب طويل جدا.\n التعقيب الذي قمت بادخاله يتجاوز أقصى طول مسموح به.\n قم بانقاصه حتى لا يزيد على ${0} حرف (حروف) واضغط اضافة.",
	remainLabelHint:"وصل التعقيب الخاص بك الى حد 500 حرف.",
	tipsCommentField: "أكتب تعقيب لكل المحررين أو لمحرر واحد فقط",
	tipsRespondField: "أكتب استجابة لكل المحررين أو لمحرر واحد فقط",	
	resolveBtn: "حل",	
	replyBtn: "رد",
	saveBtn: "ارسال",
	deleteBtn: "حذف",
	cancelBtn: "الغاء",
	reopenBtn: "اعادة فتح",
	todayAt: "اليوم في الساعة ${time}",
	yesterdayAt: "أمس في الساعة ${time}",
	dateAt: "${date} في الساعة ${time}",
	mentions: "تحديد مستخدم للتذكير",
	noMentions: "النقر على الفراغ لاتمام الادخال",
	nocomments: "لا توجد تعقيبات في وثيقة '${0}'.",
	
	newComments:"تعقيبات جديدة",
	mentiontomesomebody:"شخص ما",
	mentiontome:"${0} ذكرك في تعقيب",
	
	newcommentsnumber:"عدد التعقيبات الغير مقروءة",
	jawsnewcommentsnumber: "عدد التعقيبات الغير مقروءة هو ",
	jawsnactivecommentsnumber: "عدد التعقيبات الفعالة هو ",
	
	activenum:"عدد التعقيبات الفعالة",
	filterDesc:"ترشيح التعقيبات",
	menuallcomments:"كل التعقيبات",
	menutome: "@me",
	menubyme: "بواسطتي",
	menuactive: "فعال",
	menuresolved: "تم الحل",
	searchDesc: "بحث التعقيبات",
	search: "بحث",
	closeDesc: "اغلاق عملية البحث",
	clear: "محو",
	warnEnterKeywords: "ادخال مصطلحات البحث",
	nocommentstome: "حاليا لا توجد تعقيبات أو استجابات ورد فيها ذكري في وثيقة '${0}'.",
	nocommentsbyme: "حاليا لا توجد تعقيبات أو استجابات بواسطتي في وثيقة '${0}'.",
	nocommentsar: "حاليا لا توجد تعقيبات أو ردود بالتصنيف '${0}' في وثيقة '${1}'.",
	nosearchedcomments: "حاليا لا توجد تعقيبات أو ردود تحتوى على '${0}' بالتصنيف '${1}' في الوثيقة '${2}'.",
	
	prevBtn: "‏سابق‏",
	nextBtn: "‏تالي‏",
	mentionHint:"يتم عرض ${0} الى ${1} مطابقة/مطابقات من اجمالي ${2}",
		
	resolveFlag: "التعقيبات التي تم حلها",
	jawsCommentHint: "${authorname} أرسل التعقيب ${timestamp}",
	jawsReplyHint: "${authorname} أرسل الرد ${timestamp}",
	jawsContentHint: "المحتويات هي ${content}",
	jawsCommentStatusHint: "الحالة هي ${status}",
	jawsCommentKeyHint: "يمكنك الضغط على ادخال أو مسطرة المسافات للذهاب الى الوثيقة لمشاهدة سلسلة التعقيبات الكاملة، وحل، والرد على أو حذف التعقيبات.",
	jawsMentionHint: "عنصر واجهة تعامل Docs mention. يمكنك الضغط على السهم لأعلى أو السهم لأسفل لتحديد مستخدم ليتم ذكره",
	jawsMentionSelected: "اضغط ادخال أو مسطرة المسافات ليتم الذكر",
	commentDeletedMsg: "التعقيب الحالي تم حذفه بواسطة محرر آخر.",
	commentResolvedMsg: "تم حل التعقيب الحالي.",
	warningCommentMsg: "التعقيبات التي تمت داخل Docs لملفات ${0} يتم دعمها على الانترنت فقط. سيتم ازالة ترابط التعقيبات اذا تم تحميل نسخة جديدة للتحرير.",
	orphanCommentTip: "تم ازالة ترابط التعقيبات في هذه النسخة التي تم تحميلها.",
	warningCommentName: "تحذير"
})

