/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
    Arrow01_Gray: "Strzałka 01 - szara",
    Arrow02_Gray: "Strzałka 02 - szara",
    Arrow03_Red: "Strzałka 03 - czerwona",
    Arrow04_Blue: "Strzałka 04 - niebieska",
    Arrow05_Blue: "Strzałka 05 - niebieska",
    Arrow06_Yellow: "Strzałka 06 - żółta",
    Arrow07_Red: "Strzałka 07 - czerwona",
    Arrow08_Gray: "Strzałka 08 - szara",
    Arrow09_Orange: "Strzałka 09 - pomarańczowa",
    Arrow10_Blue: "Strzałka 10 - niebieska",
    Arrow11_Blue: "Strzałka 11 - niebieska",
    Arrow12_Green: "Strzałka 12 - zielona",
    Arrow13_Blue: "Strzałka 13 - niebieska",
    Arrow14_Green: "Strzałka 14 - zielona",
    Arrow15_Orange: "Strzałka 15 - pomarańczowa",
    Arrow16_Gray: "Strzałka 16 - szara",
    CircleArrow01_Green: "Strzałka zapętlona 01 - zielona",
    CircleArrow02_Multi: "Strzałka zapętlona 02 - wielokolorowa",
    CircleArrow03_Multi: "Strzałka zapętlona 03 - wielokolorowa",
    CircleArrow04_Multi: "Strzałka zapętlona 04 - wielokolorowa",
    CircleArrow05_Multi: "Strzałka zapętlona 05 - wielokolorowa",
    CircleArrow06_Multi: "Strzałka zapętlona 06 - wielokolorowa",
    CircleArrow07_Blue: "Strzałka zapętlona 07 - niebieska",
    CircleArrow08_Green: "Strzałka zapętlona 08 - zielona",
    CircleArrow09_Multi: "Strzałka zapętlona 09 - wielokolorowa",
    CurvedArrow01_Gray: "Strzałka zakrzywiona 01 - szara",
    CurvedArrow02_Blue: "Strzałka zakrzywiona 02 - niebieska",
    CurvedArrow03_Blue: "Strzałka zakrzywiona 03 - niebieska",
    CurvedArrow04_Orange: "Strzałka zakrzywiona 04 - pomarańczowa",
    CurvedArrow05_Red: "Strzałka zakrzywiona 05 - czerwona",
    CurvedArrow06_Blue: "Strzałka zakrzywiona 06 - niebieska",
    CurvedArrow07_Purple: "Strzałka zakrzywiona 07 - fioletowa",
    CurvedArrow08_Green: "Strzałka zakrzywiona 08 - zielona",
    CurvedArrow09_Gray: "Strzałka zakrzywiona 09 - szara",
    CurvedArrow10_Blue: "Strzałka zakrzywiona 10 - niebieska",
    CurvedArrow11_Orange: "Strzałka zakrzywiona 11 - pomarańczowa",
    CurvedArrow12_Blue: "Strzałka zakrzywiona 12 - niebieska",
    CurvedArrow13_Green: "Strzałka zakrzywiona 13 - zielona",
    CurvedArrow14_Brown: "Strzałka zakrzywiona 14 - brązowa",
    CurvedArrow15_Blue: "Strzałka zakrzywiona 15 - niebieska",
    CurvedArrow16_Gray: "Strzałka zakrzywiona 16 - szara",
    CurvedArrow17_Gray: "Strzałka zakrzywiona 17 - szara",
    CurvedArrow18_Gray: "Strzałka zakrzywiona 18 - szara",
    CurvedArrow19_Gray: "Strzałka zakrzywiona 19 - szara",
    CurvedArrow20_Gray: "Strzałka zakrzywiona 20 - szara",
    TrendArrow01_Red: "Strzałka wskaźnika trendu 01 - czerwona",
    TrendArrow02_Green: "Strzałka wskaźnika trendu 02 - zielona",
    TrendArrow03_Orange: "Strzałka wskaźnika trendu 03 - pomarańczowa",
    TrendArrow04_Red: "Strzałka wskaźnika trendu 04 - czerwona",
    TrendArrow05_Orange: "Strzałka wskaźnika trendu 05 - pomarańczowa",
    TrendArrow06_Blue: "Strzałka wskaźnika trendu 06 - niebieska",
    TrendArrow07_Orange: "Strzałka wskaźnika trendu 07 - pomarańczowa",
    TrendArrow08_Yellow: "Strzałka wskaźnika trendu 08 - żółta",
    TrendArrow09_Blue: "Strzałka wskaźnika trendu 09 - niebieska",
    TrendArrow10_Blue: "Strzałka wskaźnika trendu 10 - niebieska",
    TrendArrow11_Blue: "Strzałka wskaźnika trendu 11 - niebieska",
    TrendArrow12_Blue: "Strzałka wskaźnika trendu 12 - niebieska",
    TrendArrow13_Red: "Strzałka wskaźnika trendu 13 - czerwona",
    TrendArrow14_Multi: "Strzałka wskaźnika trendu 14 - wielokolorowa",
    TrendArrow15_Blue: "Strzałka wskaźnika trendu 15 - niebieska",
    Bullet01_Circle_DarkRed: "Znacznik podpunktu 01 - okrąg, ciemnoczerwony",
    Bullet02_Circle_Blue: "Znacznik podpunktu 02 - okrąg, niebieski",
    Bullet03_Circle_Green: "Znacznik podpunktu 03 - okrąg, zielony",
    Bullet04_Square_Black: "Znacznik podpunktu 04 - kwadrat, czarny",
    Bullet05_Square_Orange: "Znacznik podpunktu 05 - kwadrat, pomarańczowy",
    Bullet06_Square_Purple: "Znacznik podpunktu 06 - kwadrat, fioletowy",
    Bullet07_Diamond_Blue: "Znacznik podpunktu 07 - romb, niebieski",
    Bullet08_Diamond_LightBlue: "Znacznik podpunktu 08 - romb, jasnoniebieski",
    Bullet09_Diamond_Red: "Znacznik podpunktu 09 - romb, czerwony",
    Bullet10_Star_Yellow: "Znacznik podpunktu 10 - gwiazda, żółta",
    Bullet11_Star_Blue: "Znacznik podpunktu 11 - gwiazda, niebieska",
    Bullet12_Triangle_Blue: "Znacznik podpunktu 12 - trójkąt, niebieski",
    Bullet13_Triangle_DarkGreen: "Znacznik podpunktu 13 - trójkąt, ciemnozielony",
    Bullet14_Arrow_Red: "Znacznik podpunktu 14 - strzałka, czerwona",
    Bullet15_Arrow_Blue: "Znacznik podpunktu 15 - strzałka, niebieska",
    Bullet16_Box_Blue: "Znacznik podpunktu 16 - prostokąt, niebieski",
    Bullet17_Box_Red: "Znacznik podpunktu 17 - prostokąt, czerwony",
    Bullet18_Asterisk_LightBlue: "Znacznik podpunktu 18 - gwiazdka, jasnoniebieska",
    Bullet19_Leaves_Red: "Znacznik podpunktu 19 - liść, czerwony",
    Bullet20_Target_Blue: "Znacznik podpunktu 20 - cel, niebieski",
    Bullet21_Arrow_Blue: "Znacznik podpunktu 21 - strzałka, niebieska",
    Bullet22_Arrow_DarkBlue: "Znacznik podpunktu 22 - strzałka, ciemnoniebieska",
    Bullet23_Arrow_Brown: "Znacznik podpunktu 23 - strzałka, brązowa",
    Bullet24_Flag_Red: "Znacznik podpunktu 24 - flaga, czerwona",
    Bullet25_Flag_Green: "Znacznik podpunktu 25 - flaga, zielona",
    Bullet26_X_Red: "Znacznik podpunktu 26 - znak X, czerwony",
    Bullet27_X_Black: "Znacznik podpunktu 27 - znak X, czarny",
    Bullet28_Checkmark_Green: "Znacznik podpunktu 28 - znacznik wyboru, zielony",
    Bullet29_Checkmark_Blue: "Znacznik podpunktu 29 - znacznik wyboru, niebieski",
    Bullet30_Square_DarkRed: "Znacznik podpunktu 30 - kwadrat, ciemnoczerwony",
    camera: "Kamera",
    computer1: "Komputer 1",
    computer2: "Komputer 2",
    computer3: "Komputer 3",
    Computer_Cloud: "Chmura komputerów",
    Computer_Desktop: "Komputer desktop",
    Computer_Laptop_Black: "Komputer laptop - czarny",
    Computer_Laptop_Silver: "Komputer laptop - srebrny",
    Database: "Baza danych",
    evelope: "Koperta",
    newspapers: "Gazety",
    openevelope: "Otwarta koperta",
    Server: "Serwer",
    speaker: "Głośnik",
    WirelessAccessPoint: "Bezprzewodowy punkt dostępu",
    Cycle01_Transparent: "Cykl 01 - przezroczysty",
    Cycle02_Transparent_Blue: "Cykl 02 - przezroczysty, niebieski",
    Cycle03_Blue: "Cykl 03 - niebieski",
    Cycle04_Blue: "Cykl 04 - niebieski",
    Cycle05: "Cykl 05",
    Cycle06: "Cykl 06",
    Cycle07: "Cykl 07",
    Cycle08_Blue: "Cykl 08 - niebieski",
    Cycle09_Orange: "Cykl 09 - pomarańczowy",
    Donut01_LightBlue: "Obwarzanek 01 - jasnoniebieski",
    Donut02_Blue: "Obwarzanek 02 - niebieski",
    Donut03_Blue: "Obwarzanek 03 - niebieski",
    Donut04_DarkBlue: "Obwarzanek 04 - ciemnoniebieski",
    Donut05_DarkBlue: "Obwarzanek 05 - ciemnoniebieski",
    Donut06_Blue: "Obwarzanek 06 - niebieski",
    Donut07_Blue: "Obwarzanek 07 - niebieski",
    Graph: "Wykres",
    People01_Blue: "Ludzie 01 - niebiescy",
    People02: "Ludzie 02",
    Pillars01_Orange: "Słupy 01 - pomarańczowe",
    Pillars02_LightBlue: "Słupy 02 - jasnoniebieskie",
    Process01_Blue: "Proces 01 - niebieski",
    Process02_Blue: "Proces 02 - niebieski",
    Process03_Blue: "Proces 03 - niebieski",
    Process04_GoUp_Blue: "Proces 04 - niebieski, w górę",
    Process05_GoUp_Red: "Proces 05 - czerwony, w górę",
    Process06_GoUp_Yellow: "Proces 06 - żółty, w górę",
    Process07_Blue: "Proces 07 - niebieski",
    Pyramid01: "Piramida 01",
    Pyramid02_Blue: "Piramida 02 - niebieska",
    Pyramid03: "Piramida 03",
    Radial01_Green: "Promienie 01 - zielone",
    Radial02_Green: "Promienie 02 - zielone",
    Radial03_Sphere: "Promienie 03 - sfera",
    Radial04_Sphere_Red: "Promienie 04 - sfera, czerwona",
    Radial05_Sphere_Blue: "Promienie 05 - sfera, niebieska",
    Radial06_Arrows_DarkBlue: "Promienie 06 - strzałki, ciemnoniebieskie",
    Radial07_Arrows_DarkBlue: "Promienie 07 - strzałki, ciemnoniebieskie",
    Section_Circle: "Sekcja - Okrąg",
    Section_Cubes01: "Sekcja - kostki 01",
    Section_Cubes02_Blue: "Sekcja - kostki 02 - niebieskie",
    Section_Cubes03_Orange: "Sekcja - kostki 03 - pomarańczowe",
    Section_Cubes04: "Sekcja - kostki 04",
    Section_Cubes05: "Sekcja - kostki 05",
    Section_Cuboids01_Blue: "Sekcja - prostopadłościany 01 - niebieskie",
    Section_Cuboids02_Blue: "Sekcja - prostopadłościany 02 - niebieskie",
    Section_Cuboids03: "Sekcja - prostopadłościany 03",
    Section_Gears01: "Sekcja - koła zębate 01",
    Section_Gears02: "Sekcja - koła zębate 02",
    Section_Gears03: "Sekcja - koła zębate 03",
    Section_Hexagon04_Orange: "Sekcja - sześciokąt 04 - pomarańczowy",
    Section_Hexagons01: "Sekcja - sześciokąty 01",
    Section_Hexagons02_Blue: "Sekcja - sześciokąty 02 - niebieskie",
    Section_Hexagons03_Blue: "Sekcja - sześciokąty 03 - niebieskie",
    Section_Leaves01_LightBlue: "Sekcja - liście 01 - jasnoniebieskie",
    Section_Leaves02_Green: "Sekcja - liście 02 - zielone",
    Section_Pasters01: "Sekcja - naklejki 01",
    Section_Pasters02_Blue: "Sekcja - naklejki 02 - niebieskie",
    Section_Puzzle01: "Sekcja - układanka 01",
    Section_Puzzle02: "Sekcja - układanka 02",
    Section_Puzzle03: "Sekcja - układanka 03",
    Section_Rectangles: "Sekcja - prostokąty",
    Section_Squares: "Sekcja - kwadraty",
    Section_Triangle: "Sekcja - trójkąt",
    Target: "Element docelowy",
    Venn01: "Diagram Venna 01",
    Venn02: "Diagram Venna 02",
    Venn03: "Diagram Venna 03",
    Venn04: "Diagram Venna 04",
    Venn05: "Diagram Venna 05",
    Venn06_Blue: "Diagram Venna 06 - niebieski",
    Venn07_Blue: "Diagram Venna 07 - niebieski",
    Venn08: "Diagram Venna 08",
    Blackboard: "Tablica",
    Books: "Książki",
    Books1: "Książki 1",
    books2: "Książki 2",
    Chalk: "Kreda",
    clipboard: "schowek",
    clock: "zegar",
    Globe: "Globus",
    Glue: "Klej",
    GraduationCap: "Czapka akademicka",
    magnifyingglass: "Lupa",
    Microscope: "Mikroskop",
    Notebook: "Notes",
    notepad1: "Notatnik 1",
    notepad2: "Notatnik 2",
    notepad3: "Notatnik 3",
    PaperClip_Blue: "Spinacz niebieski",
    PaperClip_Red: "Spinacz czerwony",
    Pencil: "Ołówek",
    Ruler: "Linijka",
    TestTubes: "Probówki",
    thumbtack: "Pineska",
    clouds: "Chmury",
    DrippingFaucet: "Cieknący kran",
    Earth: "Ziemia",
    EndangeredAnimals1: "Zagrożone zwierzęta 1",
    EndangeredAnimals2: "Zagrożone zwierzęta 2",
    GreenCar: "Zielony samochód",
    GreenFactory: "Zielona fabryka",
    GreenHouse: "Szklarnia",
    Leaf1: "Liść 1",
    Leaf2: "Liść 2",
    lightbulb: "Żarówka",
    LightBulb_Flourescent_Off: "Żarówka energooszczędna wyłączona",
    LightBulb_Flourescent_On: "Żarówka energooszczędna włączona",
    LightBulb_Standard_Off1: "Żarówka standardowa wyłączona 1",
    LightBulb_Standard_Off2: "Żarówka standardowa wyłączona 2",
    LightBulb_Standard_On: "Żarówka standardowa włączona",
    lightningcloud: "Chmura z błyskawicami",
    Pollution_Car: "Samochód - zanieczyszczenia",
    Pollution_Factory: "Fabryka - zanieczyszczenia",
    Raindrop: "Kropla deszczu",
    RecycleBin: "Kosz na śmieci",
    RecycleSymbol: "Symbol przetwarzania wtórnego",
    RenewableEnergySymbol: "Symbol energii odnawialnej",
    RenewableEnergy_Solar: "Energia odnawialna - słoneczna",
    RenewableEnergy_Water: "Energia odnawialna - wodna",
    RenewableEnergy_Wind: "Energia odnawialna - wiatrowa",
    sun: "Słońce",
    Sun1: "Słońce 1",
    Sun2: "Słońce 2",
    sundandcloud: "Słońce i chmura",
    world: "Świat",
    Agreement: "Umowa",
    ATM01: "Bankomat 01",
    ATM02: "Bankomat 02",
    Balance_Balanced1: "Bilans - zbilansowany 1",
    Balance_Balanced2: "Bilans - zbilansowany 2",
    Balance_Unbalanced1: "Bilans - niezbilansowany 1",
    Balance_Unbalanced2: "Bilans - niezbilansowany 2",
    Calculator: "Kalkulator",
    Chart_Decrease1: "Wykres w dół 1",
    Chart_Decrease2: "Wykres w dół 2",
    Chart_Increase1: "Wykres w górę 1",
    Chart_Increase2: "Wykres w górę 2",
    Chart_Plateau: "Wykres - wyrównany",
    Check: "Znacznik wyboru",
    Contract: "Kontrakt",
    CreditCard_Black: "Karta kredytowa - czarna",
    CreditCard_Cut: "Karta kredytowa - przecięta",
    CreditCard_Gold: "Karta kredytowa - złota",
    Currency_Dollar: "Waluta - dolar",
    Currency_Dollars: "Waluta - dolary",
    Currency_Stack: "Stos waluty",
    Currency_StackCoins: "Stos waluty - monety",
    GoldBar: "Sztabka złota",
    GoldBar_Stack: "Stos sztabek złota",
    MoneyBag01: "Worek z pieniędzmi 01",
    MoneyBag02: "Worek z pieniędzmi 02",
    PercentSign: "Znak procent",
    PiggyBank01_Broken: "Skarbonka 01 - rozbita",
    PiggyBank02_Broken: "Skarbonka 02 - rozbita",
    PiggyBank_Coins: "Skarbonka - monety",
    PiggyBank_Currency: "Skarbonka - waluta",
    Portfolio: "Teczka",
    PriceTag: "Metka z ceną",
    Safe_Closed: "Sejf - zamknięty",
    Safe_Empty: "Sejf - pusty",
    Safe_Full: "Sejf - pełny",
    Seal_Gold: "Pieczęć - złota",
    Seal_Red: "Pieczęć - czerwona",
    Seal_Silver: "Pieczęć - srebrna",
    Wallet_Empty: "Portfel - pusty",
    Wallet_Full1: "Portfel - pełny 1",
    Wallet_Full2: "Portfel - pełny 2",
    BusinessPerson_Female6: "Bizneswoman 6",
    BusinessPerson_Male3: "Biznesmen 3",
    Computer_User_Female1: "Użytkownik komputera - kobieta 1",
    ConstructionWorker2: "Pracownik budowy 2",
    Presenter_Female1: "Prezenter - kobieta 1",
    Component_Circle01_Transparent_DarkBlue: "Komponent - okrąg 01 - przezroczysty, ciemnoniebieski",
    Component_Circle02_Transparent_Bule: "Komponent - okrąg 02 - przezroczysty, niebieski",
    Component_Circle03_Transparent_Green: "Komponent - okrąg 03 - przezroczysty, zielony",
    Component_Circle04_Transparent_Orange: "Komponent - okrąg 04 - przezroczysty, pomarańczowy",
    Component_Circle05_Transparent_Red: "Komponent - okrąg 05 - przezroczysty, czerwony",
    Component_Cube01_DarkBlue: "Komponent - kostka 01 - ciemnoniebieska",
    Component_Cube02_LightBlue: "Komponent - kostka 02 - jasnoniebieska",
    Component_Cube03_Green: "Komponent - kostka 03 - zielona",
    Component_Cube04_Orange: "Komponent - kostka 04 - pomarańczowa",
    Component_Cube05_DarkRed: "Komponent - kostka 05 - ciemnoczerwona",
    Component_Cuboid01_DarkBlue: "Komponent - prostopadłościan 01 - ciemnoniebieski",
    Component_Cuboid02_Blue: "Komponent - prostopadłościan 02 - niebieski",
    Component_Cuboid03_Green: "Komponent - prostopadłościan 03 - zielony",
    Component_Cuboid04_Orange: "Komponent - prostopadłościan 04 - pomarańczowy",
    Component_Cuboid05_Red: "Komponent - prostopadłościan 05 - czerwony",
    Component_Gear01_DarkBlue: "Komponent - koło zębate 01 - ciemnoniebieskie",
    Component_Gear02_LightBlue: "Komponent - koło zębate 02 - jasnoniebieskie",
    Component_Gear03_Green: "Komponent - koło zębate 03 - zielone",
    Component_Gear04_DarkRed: "Komponent - koło zębate 04 - ciemnoczerwone",
    Component_Gear05_Orange: "Komponent - koło zębate 05 - pomarańczowe",
    Component_Person01_DarkBlue: "Komponent - osoba 01 - ciemnoniebieska",
    Component_Person02_Blue: "Komponent - osoba 02 - niebieska",
    Component_Person03_Green: "Komponent - osoba 03 - zielona",
    Component_Person04_DarkRed: "Komponent - osoba 04 - ciemnoczerwona",
    Component_Person05_Orange: "Komponent - osoba 05 - pomarańczowa",
    Component_PuzzlePiece01_DarkBlue: "Komponent - element układanki 01 - ciemnoniebieski",
    Component_PuzzlePiece02_Blue: "Komponent - element układanki 02 - niebieski",
    Component_PuzzlePiece03_Green: "Komponent - element układanki 03 - zielony",
    Component_PuzzlePiece04_Red: "Komponent - element układanki 04 - czerwony",
    Component_PuzzlePiece05_Orange: "Komponent - element układanki 05 - pomarańczowy",
    Component_Sphere01_DarkBlue: "Komponent - kula 01 - ciemnoniebieska",
    Component_Sphere02_LightBlue: "Komponent - kula 02 - jasnoniebieska",
    Component_Sphere03_Green: "Komponent - kula 03 - zielona",
    Component_Sphere04_DarkRed: "Komponent - kula 04 - ciemnoczerwona",
    Component_Sphere05_Orange: "Komponent - kula 05 - pomarańczowa",
    Book: "Książka",
    Box01: "Pudełko 01",
    Box02: "Pudełko 02",
    Bulb01_Yellow: "Żarówka 01 - żółta",
    Bulb02_Yellow: "Żarówka 02 - żółta",
    Calendar: "Kalendarz",
    Chart: "Wykres",
    Clipboard: "Schowek",
    Clock: "Zegar",
    Compass: "Kompas",
    Flag01_Red: "Flaga 01 - czerwona",
    Flag02_Green: "Flaga 02 - zielona",
    Flag03_Blue: "Flaga 03 - niebieska",
    Gift: "Podarunek",
    House: "Dom",
    Icon_Computer01_White: "Ikona - komputer 01 - biały",
    Icon_Computer02_Black: "Ikona - komputer 02 - czarny",
    Icon_Disk01_Blue: "Ikona - dysk 01 - niebieski",
    Icon_Disk02_Green: "Ikona - dysk 02 - zielony",
    Icon_Document01_Grey: "Ikona - dokument 01 - szary",
    Icon_Document02_Grey: "Ikona - dokument 02 - szary",
    Icon_Document03_Blue: "Ikona - dokument 03 - niebieski",
    Icon_Document04_Blue: "Ikona - dokument 04 - niebieski",
    Icon_Envelope01_Blue: "Ikona - koperta 01 - niebieska",
    Icon_Envelope02_Yellow: "Ikona - koperta 02 - żółta",
    Icon_Envelope03_Open_Yellow: "Ikona - koperta 03 - otwarta, żółta",
    Icon_Envelope04_Open_Yellow: "Ikona - koperta 04 - otwarta, żółta",
    Icon_Folder01_Yellow: "Ikona - folder 01 - żółty",
    Icon_Folder02_Yellow: "Ikona - folder 02 - żółty",
    Icon_Folder03_Open_Yellow: "Ikona - folder 03 - otwarty, żółty",
    Icon_Folder04_Open_Yellow: "Ikona - folder 04 - otwarty, żółty",
    Icon_Gear01_Grey: "Ikona - koło zębate 01 - szare",
    Icon_Gear02_Blue: "Ikona - koło zębate 02 - niebieskie",
    Icon_Network01_Blue: "Ikona - sieć 01 - niebieska",
    Icon_Network02: "Ikona - sieć 02",
    Icon_Pencil01: "Ikona - ołówek 01",
    Icon_Pencil02: "Ikona - ołówek 02",
    Icon_Printer01_White: "Ikona - drukarka 01 - biała",
    Icon_Printer02_Black: "Ikona - drukarka 02 - czarna",
    Key01: "Klucz 01",
    Key02: "Klucz 02",
    Lock01_Yellow: "Kłódka 01 - żółta",
    Lock02_Yellow: "Kłódka 02 - żółta",
    Lock03_Blue: "Kłódka 03 - niebieska",
    Lock04_Blue: "Kłódka 04 - niebieska",
    Magnet: "Magnes",
    MagnifyingGlass: "Lupa",
    Medal: "Medal",
    Notebook: "Notes",
    Phone: "Telefon",
    PieChart: "Wykres kołowy",
    Pin: "Pinezka",
    PuzzlePiece: "Element układanki",
    PuzzlePieces: "Elementy układanki",
    Roadblock: "Blokada drogowa",
    Scissors: "Nożyczki",
    Shield01: "Tarcza 01",
    Shield02_Orange: "Tarcza 02 - pomarańczowa",
    Shield03_Blue: "Tarcza 03 - niebieska",
    Sign_Ban01: "Znak - zabronione 01",
    Sign_Ban02: "Znak - zabronione 02",
    Sign_CheckBox01: "Znak - pole wyboru 01",
    Sign_CheckBox02_Unchecked: "Znak - pole wyboru 02 - niezaznaczone",
    Sign_Checkmark01_Green: "Znak - znacznik wyboru 01 - zielony",
    Sign_Checkmark02_Green: "Znak - znacznik wyboru 02 - zielony",
    Sign_DoNotEnter: "Znak - nie wchodzić",
    Sign_Error01: "Znak - błąd 01",
    Sign_Error02: "Znak - błąd 02",
    Sign_ExclamationPoint01_Red: "Znak - wykrzyknik 01 - czerwony",
    Sign_ExclamationPoint02_Orange: "Znak - wykrzyknik 02 - pomarańczowy",
    Sign_Help01_Green: "Znak - pomoc 01 - zielony",
    Sign_Help02_Blue: "Znak - pomoc 02 - niebieski",
    Sign_Information: "Znak - informacja",
    Sign_Null: "Znak - pusty",
    Sign_QuestionMark01_Blue: "Znak - znak zapytania 01 - niebieski",
    Sign_QuestionMark02_Red: "Znak - znak zapytania 02 - czerwony",
    Sign_RadioButton01: "Znak - przełącznik 01",
    Sign_RadioButton02_Unchecked: "Znak - przełącznik 02 - niezaznaczony",
    Sign_Warning01_Red: "Znak - ostrzeżenie 01 - czerwone",
    Sign_Warning02_Orange: "Znak - ostrzeżenie 02 - pomarańczowe",
    Sign_X01_Red: "Znak - znak X 01 - czerwony",
    Sign_X02_Red: "Znak - znak X 02 - czerwony",
    Star_Yellow: "Gwiazda - żółta",
    Wrench: "Klucz nasadowy",
    Airplane_Blue: "Samolot - niebieski",
    Bicycle_Blue: "Rower - niebieski",
    Bus: "Autobus",
    Canoe_Blue: "Kajak - niebieski",
    Car_Red: "Samochód - czerwony",
    Helicopter_Blue: "Śmigłowiec - niebieski",
    Motorcycle_Red: "Motocykl - czerwony",
    Pedestrian_Blue: "Pieszy - niebieski",
    PersonalTransporter_Green: "Transporter osobisty - zielony",
    Sailboat_Red: "Jacht - czerwony",
    Scooter_Orange: "Skuter - pomarańczowy",
    Train_Red: "Pociąg - czerwony",
    Truck_Blue: "Ciężarówka - niebieska",
    
    aria_category_selector: "Opcje kategorii obrazu",
    filterImageGallery: "Filtruj galerię obrazów"

})
