/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */


define({
        saveTip: "Zapisz",
        undoTip: "Cofnij",
        redoTip: "Ponów",
        formatPainterTip: "Kopiuj formatowanie",
        showSorterTip: "Pokaż moduł sortowania slajdów",
        hideSorterTip: "Ukryj moduł sortowania slajdów",
        webClipboardTip: "Schowek WWW",
        spellCheckTip: "Uruchom ręczne sprawdzanie pisowni",
        createSectionTip: "Przypisz sekcję",
        createCellsTip: "Przypisz komórki",
        createSlideTip: "Przypisz slajdy",
        submitTip: "Wprowadź przypisanie",
        addCommentTip: "Dodaj komentarz",
        removeFormatTip: "Usuń formatowanie",
        sortAscTip: "Sortuj rosnąco",
        sortDescTip: "Sortuj malejąco",
        instantFilterTip: "Szybki filtr",
        insertChartTip: "Wstaw wykres",
        startAutofillTip: "Automatyczne wypełnianie",
        dataValidationTip: "Sprawdzanie poprawności danych",

        selectFontTip: "Wybierz czcionkę",
        selectFontSizeTip: "Wybierz wielkość czcionki",
        selectFontNameTip: "Wybierz nazwę czcionki",
        FontName: "Nazwa czcionki",
        FontSize: "Wielkość czcionki",
        increaseFontSizeTip: "Zwiększ wielkość czcionki",
        decreaseFontSizeTip: "Zmniejsz wielkość czcionki",
        boldTip: "Pogrubienie",
        italicTip: "Kursywa",
        underlineTip: "Podkreślenie",
        strikeThroughTip: "Przekreślenie",
        setFontColorTip: "Ustaw kolor czcionki",
        setShadingColorTip: "Ustaw kolor cieniowania",
        setBackgroundFill: "Ustaw wypełnienie tła",
        setBgColorTip: "Ustaw kolor tła",
        setBorderTip: "Ustaw styl i kolor krawędzi",
        setBorderColorTip: "Ustaw kolor krawędzi",
        setHighlightColor: "Ustaw kolor wyróżnienia",
        formatPainter: "Kopiuj formatowanie",
        //	clearFormat:"Remove Formatting",
        zoom: "Powiększenie",
        selectStyleTip: "Wybierz styl",
        styles: "Styl",
        formatAsCurrencyTip: "Formatuj jako walutę",
        formatAsPercentTip: "Formatuj jako wartość procentową",
        decreaseDecimalTip: "Zmniejsz liczbę miejsc dziesiętnych",
        increaseDecimalTip: "Zwiększ liczbę miejsc dziesiętnych",
        formatNumberTip: "Formatuj jako liczbę",

        numberedListTip: "Dodaj numerację lub zmień styl numeracji",
        bulletedListTip: "Dodaj wypunktowanie lub zmień styl wypunktowania",
        multilevelListTip: "Dodaj lub zmień listę wielopoziomową",
        indentTip: "Zwiększ wcięcie",
        decreaseIndentTip: "Zmniejsz wcięcie",
        alignTip: "Wyrównaj",
        leftAlignTip: "Wyrównaj do lewej",
        centerTip: "Wyśrodkuj",
        rightAlignTip: "Wyrównaj do prawej",
        justifyTip: "Wyrównaj",
        bottomBorderTip: "Dolna krawędź",
        borderTypes: "Typy krawędzi",
        borderTip: "Ustaw styl krawędzi",
        topAlignTip: "Wyrównaj do góry",
        middleAlignTip: "Wyśrodkuj w pionie",
        bottomAlignTip: "Wyrównaj do dołu",
        lineSpacingTip: "Interlinia",
        mergeSplitCellTip: "Scal lub podziel komórki",
        wrapNoWrapTip: "Włącz lub wyłącz opływanie",
        ltrDirectionTip: "Przekształć w tekst czytany od lewej do prawej",
        rtlDirectionTip: "Przekształć w tekst czytany od prawej do lewej",
        autoDirectionTip: "Zmień kierunek tekstu",
        toggleSheetDirectionTip: "Zmień kierunek arkusza",
        setSheetDirectionLTR: "Od lewej do prawej",
        setSheetDirectionRTL: "Od prawej do lewej",

        addTableTip: "Dodaj tabelę",
        insertOrMoveRowTip: "Wstaw lub przenieś wiersz",
        insertOrMoveColTip: "Wstaw lub przenieś kolumnę",
        insertOrDeleteRowTip: "Wstaw lub usuń wiersz",
        insertOrDeleteColTip: "Wstaw lub usuń kolumnę",
        insertFunctionTip: "Wstaw funkcję",
        insertImage: "Wstaw obraz",
        resizeCol: "Zmień wielkość kolumny",
        resizeCols: "Zmień wielkość kolumn",
        addLink: "Dodaj lub edytuj odsyłacz",
        tableStyle: "Style tabel",

        selectBorder_BottomBorder: "Dolna krawędź",
        selectBorder_TopBorder: "Górna krawędź",
        selectBorder_LeftBorder: "Lewa krawędź",
        selectBorder_RightBorder: "Prawa krawędź",
        selectBorder_NoBorder: "Brak linii",
        selectBorder_AllBorders: "Wszystkie krawędzie",

        insertOrMoveRow_InsertAbove: "Wstaw wiersz powyżej",
        insertOrMoveRow_InsertBelow: "Wstaw wiersz poniżej",
        insertOrMoveRow_MoveUp: "Przenieś wiersz w górę",
        insertOrMoveRow_MoveDown: "Przenieś wiersz w dół",
        insertOrMoveCol_InsertLeft: "Wstaw kolumnę przed",
        insertOrMoveCol_InsertRight: "Wstaw kolumnę po",
        insertOrMoveCol_InsertBefore: "Wstaw kolumnę przed",
        insertOrMoveCol_InsertAfter: "Wstaw kolumnę po",
        insertOrMoveCol_MoveLeft: "Przenieś kolumnę w lewo",
        insertOrMoveCol_MoveRight: "Przenieś kolumnę w prawo",

        insertOrDelete_Delete: "Usuń",

        combineButtonReadTip: "Naciśnij klawisz strzałki w dół, aby aktywować menu. Do nawigacji w menu służą klawisze strzałek.",

        lineSpacing_1: "1",
        lineSpacing_12: "1,2",
        lineSpacing_15: "1,5",
        lineSpacing_2: "2",
        lineSpacing_25: "2,5",
        lineSpacing_3: "3",

        percent: "%",
        font_arial: "Arial",

        fontSize: "${0} pkt",

        slides: "Jeden slajd na stronę",
        slidesWithNotes: "Slajdy z uwagami",
        preparingSlides: "Przygotowywanie slajdów do drukowania...",
        printLayoutOptionLabel: "Opcje układu drukowania",

        targetRemovedWhenDialogOpen: "Tego działania nie można wykonać, ponieważ element docelowy został usunięty przez innego współedytującego.",

        NUMBER: "Liczba",
        CURRENCY: "Waluta",
        PERCENT: "Wartość procentowa",
        DATE: "Data",
        TIME: "Godzina",
        DATETIME: "Data i godzina",
        MORECURRENCY: "Więcej walut według jednostek walutowych",
        MORECURRENCYCODE: "Więcej walut według kodów walut",
        MOREDATE: "Więcej formatów czasu i daty",
        TEXT: "Tekst",
	
        // currency, by currency code
        // NOTE: MUST keep it in order
        CURRENCY_CODE: {
            AED: "Zjednoczone Emiraty Arabskie (dirhem)",
            ARS: "Argentyna (peso)",
            AUD: "Australia (dolar)",
            BGN: "Bułgaria (lew)",
            BOB: "Boliwia (boliviano)",
            BRL: "Brazylia (real)",
            CAD: "Kanada (dolar)",
            CHF: "Szwajcaria (frank)",
            CLP: "Chile (peso)",
            CNY: "China (yuan)",
            COP: "Kolumbia (peso)",
            CRC: "Kostaryka (colon)",
            CZK: "Czechy (korona)",
            DKK: "Dania (korona)",
            DOP: "Dominikana (peso)",
            EGP: "Egipt (funt)",
            EUR: "Austria, Belgia, Finlandia, Francja, ..., Słowenia, Hiszpania (euro)",
            GBP: "Anglia, Wielka Brytania (funt szterling)",
            HKD: "Hongkong (dolar)",
            HRK: "Chorwacja (kuna)",
            HUF: "Węgry (forint)",
            IDR: "Indonezja (rupia)",
            ILS: "Izrael (szekel)",
            INR: "Indie (rupia)",
            JPY: "Japonia (jen)",
            KRW: "Korea Południowa (won)",
            KZT: "Kazachstan (tenge)",
            MAD: "Maroko (dirham)",
            MXN: "Meksyk (peso)",
            MYR: "Malezja (ringgit)",
            NOK: "Norwegia (korona)",
            NZD: "Nowa Zelandia (dolar)",
            PAB: "Panama (balboa)",
            PEN: "Peru (nowy sol)",
            PHP: "Filipiny (peso)",
            PKR: "Pakistan (rupia)",
            PLN: "Polska (złoty)",
            PYG: "Paragwaj (guarani)",
            RON: "Rumunia (lej)",
            RSD: "Serbia (dinar)",
            RUB: "Rosja (rubel)",
            SAR: "Arabia Saudyjska (rial)",
            SEK: "Szwecja (korona)",
            SGD: "Singapur (dolar)",
            SVC: "Salwador (colon)",
            THB: "Tajlandia (baht)",
            TRY: "Turcja (lira)",
            TWD: "Tajwan (dolar)",
            USD: "Ekwador, Puerto Rico, Stany Zjednoczone (dolar amerykański)",
            UYU: "Urugwaj (peso)",
            VEF: "Wenezuela (bolivar)",
            VND: "Wietnam (đong)",
            ZAR: "Afryka Południowa (rand)"
        },
        // for border toolbar
        allBorders: "Wszystkie krawędzie",
        innerBorders: "Krawędzie wewnętrzne",
        horizontalBorders: "Krawędzie poziome",
        verticalBorders: "Krawędzie pionowe",
        outerBorders: "Krawędzie zewnętrzne",
        borderColor: "Kolor krawędzi",
        leftBorder: "Lewa krawędź",
        topBorder: "Górna krawędź",
        rightBorder: "Prawa krawędź",
        bottomBorder: "Dolna krawędź",
        clearBorders: "Bez krawędzi",
        BorderStyle_ThinSolid: "Cienka ciągła",
        BorderStyle_ThinDotted: "Cienka kropkowana",
        BorderStyle_ThinDashed: "Cienka przerywana",
        BorderStyle_ThickSolid: "Gruba ciągła",
        BorderStyle_ThickDotted: "Gruba kropkowana",
        BorderStyle_ThickDashed: "Gruba przerywana"
})

