/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2014. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        spreadsheetTemplates: "Plantillas de hojas de cálculo",
        documentTemplates: "Plantillas de documentos",
        titleShareDocument: "Compartir documento",
        offline: "Fuera de línea",
        versionPublishing: "Publicando la versión.",
        versionPublishFailed: "La versión no se ha publicado. Es posible que el archivo sea demasiado largo, o que el servidor haya agotar tiempo de espera. Vuelva a intentarlo, o cancele y pida al administrador que compruebe el registro del servidor para identificar el problema.",
        versionCheckinFailed: "La versión no se ha incorporado. Es posible que el archivo sea demasiado largo, o que el servidor haya agotar tiempo de espera. Vuelva a intentarlo, o cancele y pida al administrador que compruebe el registro del servidor para identificar el problema.",
        versionSavedFailed: "No se ha completado Guardar. Vuelva a intentar Guardar más tarde.",
        publishFileSizeExceedMsg: "No se puede publicar el archivo porque supera el tamaño máximo definido por el administrador del repositorio. Suprima parte del contenido para reducir el archivo, o póngase en contacto con el administrador para aumentar la limitación de tamaño.",
        checkinFileSizeExceedMsg: "No se puede incorporar el archivo porque supera el tamaño máximo definido por el administrador del repositorio. Suprima parte del contenido para reducir el archivo, o póngase en contacto con el administrador para aumentar la limitación de tamaño.",
        versionpublished: "${0} ha publicado la versión a las ${1}.",
        versionPublishing2: "Guardando la versión.",
        versionPublishFailed2: "La versión no se ha guardado. Es posible que el archivo sea demasiado largo, o que el servidor haya agotar tiempo de espera. Vuelva a intentarlo, o cancele y pida al administrador que compruebe el registro del servidor para identificar el problema.",      
        publishFileSizeExceedMsg2: "No se puede guardar el archivo porque supera el tamaño máximo definido por el administrador del repositorio. Suprima parte del contenido para reducir el archivo, o póngase en contacto con el administrador para aumentar la limitación de tamaño.",
        versionpublished2: "${0} ha guardado la versión a las ${1}.",
        chekinCloseDocsMsg: "Puede cerrar ${productName} ahora.",
        draftSavingAs: "Copiando archivo...",
        draftSavedAs: "La nueva copia se ha guardado como ${0}.",
        synchronizing: "Espere mientras la operación de sincronización con el servidor se haya completado.",
        synchronizeError: "La operación de sincronización con el servidor no se puede completar.",
        joinwithoutentitle: "Usuarios: ${0} desea editar el documento, pero no puede unirse a la sesión de edición porque no tiene derechos para coeditarlo.",
        joinwithoutentitle2: "Usuarios: ${0} desea editar el documento pero no puede unirse a la sesión de edición porque no tiene derechos para coeditarlo.",
        backtoFiles: "Abrir Mis archivos",
        backtoCommFiles: "Abrir Archivos de la comunidad",
        backtoLibrary: "Abrir Biblioteca",
        backtoICN: "Abrir Navegador de contenido",
        backtoRepository: "Abrir Lista de archivos",
        createNewSpred: "Crear una hoja de cálculo",
        createNewDoc: "Crear un documento",
        createNewDocFromTemp: "Crear un documento a partir de una plantilla",
        shareDoc: "Compartir un documento",
        exportPdf: "Configuración de la página",
        insertDate: "Selección de fecha",
        insertTime: "Selección de hora",
        connect: "Unir",
        theDoc: "el documento",
        save: "Cambios nuevos",
        saveBeforeReviewMsg: "No ha guardado los cambios. Guarde los cambios y Someta para revisión de nuevo.",
        submitReviewWidgetsFaiure: "No se ha inicializado la aplicación correctamente. Vuelva a Someter para revisión más tarde.",
        widgetsFaiure: "La aplicación no se ha inicializado correctamente.",
        slideSorter: "Diapositivas",
        commentsBar: "Comentarios",
        draftBadge: "BORRADOR",
        share: "Compartir",
        comment: "Comentario",
        showSidebar: "Mostrar barra lateral",
        publishVersion: "Publicar",
        checkInVersion: "Incorporar",
        saveVersion: "Guardar",
        saved: "Todos los cambios guardados",
        saving: "Guardando",
        submitFragment: "Enviar",
        aria_inMainMenu: "Ahora se encuentra en el menú principal",
        aria_inSlideSorter: "Ahora se encuentra en la vista del clasificador de diapositivas",
        aria_inSlideEditor: "Ahora se encuentra en la vista del editor de diapositivas",
        createNewPres: "Crear una presentación",
        createNewAppFromTemp: "Crear un documento a partir de una plantilla",
        textdoc: "texto",
        sheetdoc: "hoja de cálculo",
        presdoc: "presentación",
        saveAsTextErrMsg: "El nuevo documento de texto no se puede guardar.",
        saveAsPresErrMsg: "El nuevo documento de presentación no se puede guardar.",
        saveAsSheetErrMsg: "El nuevo documento de hoja de cálculo no se puede guardar.",
        saveAsTextErrMsg1: "No hay suficiente espacio para guardar el documento.",
        saveAsPresErrMsg1: "No hay suficiente espacio para guardar la presentación.",
        saveAsSheetErrMsg1: "No hay suficiente espacio para guardar la hoja de cálculo.",
        newDocTextErrMsg: "No se puede crear un nuevo documento de texto.",
        newDocSheetErrMsg: "No se puede crear un nuevo documento de hoja de cálculo.",
        newDocPresErrMsg: "No se puede crear un nuevo documento de presentación.",
        newDocTextErrMsg2: "No se puede crear un nuevo documento de texto desde la plantilla.",
        newDocSheetErrMsg2: "No se puede crear un nuevo documento de hoja de cálculo desde la plantilla.",
        newDocPresErrMsg2: "No se puede crear un nuevo documento de presentación desde la plantilla.",
        newDocTextErrMsg3: "No hay suficiente espacio para crear un documento.",
        newDocSheetErrMsg3: "No hay suficiente espacio para crear una hoja de cálculo.",
        newDocPresErrMsg3: "No hay suficiente espacio para crear una presentación.",
        newDocTextErrMsg4: "Ya hay un documento con este título. Proporcione un título distinto para el nuevo documento.",
        newDocSheetErrMsg4: "Ya hay una hoja de cálculo con este título. Proporcione un título distinto para la nueva hoja de cálculo.",
        newDocPresErrMsg4: "Ya hay una presentación con este título. Proporcione un título distinto para la nueva presentación.",        
        aclWarningTitle: "No se puede editar la nueva versión",
        aclWarningMsg: "Como el propietario de archivo ha establecido áreas protegidas en este archivo, es mejor editarlo en línea. Póngase en contacto con el propietario de archivo (${0}) si cree que realmente necesita cargar una nueva versión.",
        aclWarningMsgForOwner: "Hay áreas protegidas en este archivo. Por este motivo, no podrá editar la nueva versión subida en línea.  Debe eliminar todas las áreas protegidas en este archivo y después puede abrir y editar la nueva versión subida.",
        st0: "Hoja1",
        st1: "Hoja2",
        st2: "Hoja3",
        FootnoteMsg: "Página",
        conflictMsg: "Hay un conflicto con lo que están cambiando otros editores.  Su cambio se ha rescindido.",
        undoRedoConflictMsg: "Las operaciones de deshacer y rehacer se han suspendido debido a un conflicto entre lo que está editando y en lo que está trabajando otra persona que está coeditando",
        bigFileErrMsg: "El tamaño del documento es demasiado grande. Renueve el navegador para ver si todo el contenido está intacto",
        noPermissionMsg: "No tiene permiso para editar este archivo. Póngase en contacto con el propietario del archivo para obtener permiso de edición e inténtelo de nuevo.",
        networkIssueMsg: "Existe un problema de red.",
        networkIssueTitle: "Problema de red",
        networkIssueContent: "Existe un problema de red. Renueve la página e intente volver a conectarse.",
        lockEditorMsg: "El documento no se puede editar hasta que haya una conexión con el servidor.",
        offlineReasonMsg: "La sesión ha superado el tiempo de espera.",
        offlineReasonForServerUnacceptedMsg: "No se pueden procesar algunas de sus acciones. El servidor de Docs descartará las acciones que se realicen durante el próximo minuto.",
        offlineReasonForServerDraftFormatChange: "El formato de su documento está fuera de fecha debido a la actualización del servidor.",
        reloadExplanationMsg: "Vuelva a iniciar sesión para seguir trabajando.",
        reloadBtnLabel: "Recargar",
        reconnectingMsg: "Espere mientras se establece la conexión con el servidor.",
        loadMsg: "Espere mientras se carga el documento.",
        loadingDocumentMsg: "Espere mientras se carga el documento desde el servidor.",
        reLoadingDocumentMsg: "Espere mientras se recarga el documento desde el servidor.",
        unsupportMsg: "Se ha detectado una característica no soportada. Vea más detalles.",
        browserWorkingMsg: "Espere...",
        fileDeepDetectTitle: "El formato de archivo y la extensión de archivo no coinciden.",
        fileDeepDetectMsg: "El formato de archivo no es el mismo formato que el que se indica mediante la extensión de archivo. Pulse Continuar para editar el archivo en este formato.",
        fileDeepDetectOkLabel: "Continuar",
        tipInfo: "Consejo: ${0}",
        selectTextInfo: "Seleccione texto para aplicar estilo.",
        removeRecentFile: "El archivo que desea abrir se ha suprimido. ¿Desea eliminar el nombre del archivo de la lista de Archivos recientes?",
        altLotusIcon: "",
        altErrorMsgIcon: "Mensaje de error",
        altWarningMsgIcon: "Mensaje de aviso",
        altSuccessMsgIcon: "Mensaje satisfactorio",
        sidebarLandmarkDesc: "barra lateral",
        footerTitle: "pie de página",
        mainDesc: "área de contenidos",
        editLockedDocumentWarning: "Ha bloqueado este archivo cuando otros usuarios lo estaba editando. Le rogamos que trabajen conjuntamente para coordinar los cambios o les pida que finalicen la edición para que pueda tener acceso único de edición.",
        observerMode: "Ahora se encuentra en el modo observador",
        editorMode: "Ahora se encuentra en el modo editor",
        maxEditorLimitReached: "El documento ha alcanzado el número máximo de editores de ${0} de esta sesión. Puede pasar al modo editor cuando un editor abandone el documento o cambie al modo observador.",
        maxEditorLimitReachedTitle: "Número máximo de editores alcanzado",
        uploadNewVersionOpenConfirm: "${0} ha subido una nueva versión a las ${1} ${2}. ¿Desea abrir la nueva versión?", //${0} name, ${1} time, ${2} date
        uploadNewVersionPublishConfirm: "${0} ha subido una nueva versión a las ${1} ${2}.", //${0} name, ${1} time, ${2} date
        you: "Usted",
        today: "hoy",
        yesterday: "ayer",
        slideShowInviteMsg: "El usuario ${0} ha iniciado una presentación de diapositivas compartida. ¿Desea unirse?",
        slideShowInviteTitle: "Invitación a la presentación de diapositivas compartida",
        slideShowInviteTitle1: "Invitación a la presentación de diapositivas colectiva",
        slideShowCoviewSelectUsersTitle: "Presentación de diapositivas compartida",
        slideShowCoviewSelectUsersTitle1: "Presentación de diapositivas colectiva",
        slideShowCoviewStmt: "Compartir el estado actual de la presentación en una presentación de diapositivas compartida.",
        slideShowCoviewStmt1: "Compartir el estado actual de la presentación en una presentación de diapositivas colectiva.",
        slideShowCoviewOptionOne: "Invitar a todos los editores a unirse a la presentación de diapositivas.",
        slideShowCoviewOptionOne1: "Invitar a todos los editores y observadores a unirse a la presentación de diapositivas.",
        slideShowCoviewOptionTwo: "Invitar solo a los siguientes editores a unirse a la presentación de diapositivas.",
        slideShowCoviewOptionTwo1: "Invitar solo a los siguientes editores y observadores a unirse a la presentación de diapositivas.",
        slideShowCoviewSlidesOf: "Diapositiva ${0} de ${1}",  //as in Slide 1 of 4
        slideShowCoviewViewers: "Visores ${0}",
        slideShowCoviewDialogInput: "Escriba para filtrar nombre",
        slideShowCoviewAddTitle: "Añadir a presentación de diapositivas compartida",
        slideShowCoviewAddTitle1: "Añadir a presentación de diapositivas colectiva",
        slideShowCoviewMessage: "Seleccione usuarios adicionales a los que invitar a esta presentación de diapositivas compartida.",
        slideShowCoviewMessage1: "Seleccione usuarios adicionales a los que invitar a esta presentación de diapositivas colectiva.",
        slideShowCoviewEnded: "La presentación de diapositivas compartida ha finalizado",
        slideShowCoviewEndMessage: "La presentación de diapositivas compartida a la que se está intentando unir ya no está disponible.",
        slideShowCoviewEndMessage2: "El usuario ${0} ha finalizado la presentación de diapositivas compartida.",
        slideShowWarning: "Debe cerrar la presentación de diapositivas actual antes de iniciar una nueva.",
        slideShowHoverMsg: "Pulse para ver quién más está viendo la presentación de diapositivas.",
        slideShowHoverMsgAdd: "Pulse para invitar a más visores.",
        csvEmpty: "No se puede exportar como archivo .csv porque el archivo no contiene ningún dato.",
        edit: "Editar",
        printToPDF: "Descargar como PDF",
        print: "Imprimir",
        view: "Ver",
        openLatestFile: "Abrir el archivo más reciente",
        updateDocument: "El documento se ha actualizado. ${0}.",
        updateSpreadsheet: "La hoja de cálculo se ha actualizado. ${0}.",
        updatePresentation: "La presentación se ha actualizado. ${0}.",
        labelCancel: "Cancelar",
        msgConversionFail: "La conversión ha fallado.",
        updateNow: "Abrir ahora",
        fileUpdated: "El documento se ha actualizado.",
        fileUpdatedContent1: "El documento se ha actualizado. Abra el archivo más reciente antes de imprimir.",
        htmlviewerlimitation1: "Esta hoja de cálculo contiene una tabla dinámica que no se puede visualizar.",
        htmlviewerlimitation2: "Esta hoja de cálculo contiene formato condicional que no se puede visualizar.",
        htmlviewerlimitation3: "Esta hoja de cálculo contiene una tabla dinámica y formato condicional que no se puede visualizar.",
        close: "Cerrar",
        closeDocs: "Cerrar ${productName}",
        endSessionDlgTitle: "La sesión de edición ha finalizado",
        endSessionDlgNotice: "La sesión de edición ha finalizado porque ${0} ha incorporado el archivo.",
        labelStopReview: "Parar revisión",
        labelRejct: "Rechazar",
        labelApprove: "Aprobar",
        errorMsg: "Error",
        labelItemNotFountTitle: "No se puede completar la acción.",
        labelItemNotFountMsg: "Otro miembro de la comunidad ya ha realizado la acción en el documento. Para obtener más información, cierre el documento y vaya a la página Detalles de archivo en la biblioteca.",
        viewProtectedAreas: "Esta hoja de cálculo contiene áreas protegidas. Sólo debe editarlo o verlo en línea.",
        macroTitle: "El archivo contiene una macro.", 
        macroDesc: "Si se edita este archivo, se podría romper la macro. Para evitar que otras personas editen el rango o la hoja que contiene la macro, utilice Datos > Áreas protegidas.",
        problem_id_msg_title: "Informe de este problema al administrador. ",
        problem_id_msg_show: "Pulsar para ver detalles",
    	problem_id_msg_hide: "Pulsar para ocultar",
    	uploadNewVersionWarningTitle: "No se puede editar la nueva versión",
        changeHistoryWarningMsg: "Como el propietario de archivo ha habilitado el Seguimiento de cambios en este archivo, es mejor editarlo en línea. Póngase en contacto con el propietario de archivo (${0}) si cree que realmente necesita cargar una nueva versión.",
        changeHistoryWarningMsgForOwner: "Este archivo tiene Historial de cambios. Por este motivo, no podrá editar la nueva versión subida en línea.  Debe borrar el Historial de cambios e inhabilitar el Rastreo de cambios en este archivo y después podrá abrir y editar la nueva versión cargada.",
        viewChangeHistory: "Este documento contiene historial de cambios. Sólo debe editarlo o verlo en línea.",
    	contentCorruptErrMsg: "No se puede cargar el contenido porque está dañado. Póngase en contacto con su administrador para obtener ayuda. "
});

