/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */


define({
    root: ({
        saveTip: "Save",
        undoTip: "Undo",
        redoTip: "Redo",
        formatPainterTip: "Copy Formatting",
        showSorterTip: "Show Slide Sorter",
        hideSorterTip: "Hide Slide Sorter",
        webClipboardTip: "Web Clipboard",
        spellCheckTip: "Run Manual Spell Check",
        createSectionTip: "Assign a Section",
        createCellsTip: "Assign Cells",
        createSlideTip: "Assign Slides",
        submitTip: "Submit Assignment",
        addCommentTip: "Add Comment",
        removeFormatTip: "Remove Formatting",
        sortAscTip: "Sort Ascending",
        sortDescTip: "Sort Descending",
        instantFilterTip: "Instant Filter",
        insertChartTip: "Insert Chart",
        startAutofillTip: "Autofill",
        dataValidationTip: "Data Validation",

        selectFontTip: "Select Font",
        selectFontSizeTip: "Select Font Size",
        selectFontNameTip: "Select Font Name",
        FontName: "Font Name",
        FontSize: "Font Size",
        increaseFontSizeTip: "Increase Font Size",
        decreaseFontSizeTip: "Decrease Font Size",
        boldTip: "Bold",
        italicTip: "Italic",
        underlineTip: "Underline",
        strikeThroughTip: "Strikethrough",
        setFontColorTip: "Set Font Color",
        setShadingColorTip: "Set Shading Color",
        setBackgroundFill: "Set Background Fill",
        setBgColorTip: "Set Background Color",
        setBorderTip: "Set Border Style and Color",
        setBorderColorTip: "Set Border Color",
        setHighlightColor: "Set Highlight Color",
        formatPainter: "Copy Formatting",
        //	clearFormat:"Remove Formatting",
        zoom: "Zoom",
        selectStyleTip: "Select Style",
        styles: "Style",
        formatAsCurrencyTip: "Format As Currency",
        formatAsPercentTip: "Format As Percent",
        decreaseDecimalTip: "Decrease Decimal Places",
        increaseDecimalTip: "Increase Decimal Places",
        formatNumberTip: "Format Number",

        numberedListTip: "Add Numbering or Change Numbering Style",
        bulletedListTip: "Add Bullets or Change Bullet Style",
        multilevelListTip: "Add or Change Multilevel List",
        indentTip: "Increase Indent",
        decreaseIndentTip: "Decrease Indent",
        alignTip: "Align",
        leftAlignTip: "Align Left",
        centerTip: "Align Center",
        rightAlignTip: "Align Right",
        justifyTip: "Justify",
        bottomBorderTip: "Border Bottom",
        borderTypes: "Border Types",
        borderTip: "Set Border Style",
        topAlignTip: "Align Top",
        middleAlignTip: "Align Middle",
        bottomAlignTip: "Align Bottom",
        lineSpacingTip: "Line Spacing",
        mergeSplitCellTip: "Merge or Split Cells",
        wrapNoWrapTip: "Wrap on or off",
        ltrDirectionTip: "Change to Left-to-Right Text",
        rtlDirectionTip: "Change to Right-to-Left Text",
        autoDirectionTip: "Change Text Direction",
        toggleSheetDirectionTip: "Change Sheet Direction",
        setSheetDirectionLTR: "Left to Right",
        setSheetDirectionRTL: "Right to Left",

        addTableTip: "Add Table",
        insertOrMoveRowTip: "Insert or Move Row",
        insertOrMoveColTip: "Insert or Move Column",
        insertOrDeleteRowTip: "Insert or Delete Row",
        insertOrDeleteColTip: "Insert or Delete Column",
        insertFunctionTip: "Insert Function",
        insertImage: "Insert Image",
        resizeCol: "Resize Column",
        resizeCols: "Resize Columns",
        addLink: "Add or Edit Link",
        tableStyle: "Table Styles",

        selectBorder_BottomBorder: "Bottom Border",
        selectBorder_TopBorder: "Top Border",
        selectBorder_LeftBorder: "Left Border",
        selectBorder_RightBorder: "Right Border",
        selectBorder_NoBorder: "No Lines",
        selectBorder_AllBorders: "All Border",

        insertOrMoveRow_InsertAbove: "Insert Row Above",
        insertOrMoveRow_InsertBelow: "Insert Row Below",
        insertOrMoveRow_MoveUp: "Move Row Up",
        insertOrMoveRow_MoveDown: "Move Row Down",
        insertOrMoveCol_InsertLeft: "Insert Column Before",
        insertOrMoveCol_InsertRight: "Insert Column After",
        insertOrMoveCol_InsertBefore: "Insert Column Before",
        insertOrMoveCol_InsertAfter: "Insert Column After",
        insertOrMoveCol_MoveLeft: "Move Column Left",
        insertOrMoveCol_MoveRight: "Move Column Right",

        insertOrDelete_Delete: "Delete",

        combineButtonReadTip: "Press the Down Arrow key to activate the menu, and then navigate with the arrow keys",

        lineSpacing_1: "1",
        lineSpacing_12: "1.2",
        lineSpacing_15: "1.5",
        lineSpacing_2: "2",
        lineSpacing_25: "2.5",
        lineSpacing_3: "3",

        percent: "%",
        font_arial: "Arial",

        fontSize: "${0}pt",

        slides: "One Slide per Page",
        slidesWithNotes: "Slides with Notes",
        preparingSlides: "Preparing your slides for printing...",
        printLayoutOptionLabel: "Print layout options",

        targetRemovedWhenDialogOpen: "This action cannot be completed because the target has been removed by another co-editor.",

        NUMBER: "Number",
        CURRENCY: "Currency",
        PERCENT: "Percent",
        DATE: "Date",
        TIME: "Time",
        DATETIME: "DateTime",
        MORECURRENCY: "More currencies by monetary unit",
        MORECURRENCYCODE: "More currencies by currency code",
        MOREDATE: "More time and date formats",
        TEXT: "Text",
	
        // currency, by currency code
        // NOTE: MUST keep it in order
        CURRENCY_CODE: {
            AED: "United Arab Emirates (Dirham)",
            ARS: "Argentina (Pesos)",
            AUD: "Australia (Dollars)",
            BGN: "Bulgaria (Leva)",
            BOB: "Bolivia (Bolivianos)",
            BRL: "Brazil (Reals)",
            CAD: "Canada (Dollars)",
            CHF: "Switzerland (Francs)",
            CLP: "Chile (Pesos)",
            CNY: "China (Yuan Renminbi)",
            COP: "Colombia (Pesos)",
            CRC: "Costa Rica (Colon)",
            CZK: "Czech Republic (Koruny)",
            DKK: "Denmark (Kroner)",
            DOP: "Dominican Republic (Pesos)",
            EGP: "Egypt (Pounds)",
            EUR: "Austria, Belgium, Finland, France,  ..., Slovenia, Spain (Euro)",
            GBP: "England, United Kingdom (Pounds)",
            HKD: "Hong Kong (Dollars)",
            HRK: "Croatia (Kuna)",
            HUF: "Hungary (Forint)",
            IDR: "Indonesia (Rupiahs)",
            ILS: "Israel (New Shekels)",
            INR: "India (Rupees)",
            JPY: "Japan (Yen)",
            KRW: "Korea, South (Won)",
            KZT: "Kazakhstan (Tenges)",
            MAD: "Morocco (dirham)",
            MXN: "Mexico (Pesos)",
            MYR: "Malaysia (Ringgits)",
            NOK: "Norway (Krone)",
            NZD: "New Zealand (Dollars)",
            PAB: "Panama (Balboa)",
            PEN: "Peru (Nuevos Soles)",
            PHP: "Philippines (Pesos)",
            PKR: "Pakistan (Rupees)",
            PLN: "Poland (Zlotych)",
            PYG: "Paraguay (Guarani)",
            RON: "Romania (New Lei)",
            RSD: "Serbian (Cyrillic), Serbian (Latin)",
            RUB: "Russia (Rubles)",
            SAR: "Saudi Arabia (Riyals)",
            SEK: "Sweden (Kronor)",
            SGD: "Singapore (Dollars)",
            SVC: "El Salvador (Colones)",
            THB: "Thailand (Baht)",
            TRY: "Turkey (Lira)",
            TWD: "Taiwan (New Dollars)",
            USD: "Ecuador, Puerto Rico, United States of America (U.S. Dollars)",
            UYU: "Uruguay (Pesos)",
            VEF: "Venezuela (Bolivares Fuertes)",
            VND: "Vietnam (Dong)",
            ZAR: "South Africa (Rand)"
        },
        // for border toolbar
        allBorders: "All Borders",
        innerBorders: "Internal Borders",
        horizontalBorders: "Horizontal Borders",
        verticalBorders: "Vertical Borders",
        outerBorders: "External Borders",
        borderColor: "Border Color",
        leftBorder: "Left Border",
        topBorder: "Upper Border",
        rightBorder: "Right Border",
        bottomBorder: "Lower Border",
        clearBorders: "No Borders",
        BorderStyle_ThinSolid: "Thin Solid",
        BorderStyle_ThinDotted: "Thin Dotted",
        BorderStyle_ThinDashed: "Thin Dashed",
        BorderStyle_ThickSolid: "Thick Solid",
        BorderStyle_ThickDotted: "Thick Dotted",
        BorderStyle_ThickDashed: "Thick Dashed"
    })
})