/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2014. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        spreadsheetTemplates: "Arbeitsblattvorlagen",
        documentTemplates: "Dokumentvorlagen",
        titleShareDocument: "Dokument gemeinsam nutzen",
        offline: "Offline",
        versionPublishing: "Die Version wird veröffentlicht.",
        versionPublishFailed: "Die Version wurde nicht veröffentlicht. Möglicherweise ist die Datei zu groß oder der Server hat das zulässige Zeitlimit überschritten. Versuchen Sie es später noch einmal oder brechen Sie den Vorgang ab und wenden Sie sich an Ihren Administrator, um das Serverprotokoll zu überprüfen und das Problem zu ermitteln.",
        versionCheckinFailed: "Die Version wurde nicht eingecheckt. Möglicherweise ist die Datei zu groß oder der Server hat das zulässige Zeitlimit überschritten. Versuchen Sie es später noch einmal oder brechen Sie den Vorgang ab und wenden Sie sich an Ihren Administrator, um das Serverprotokoll zu überprüfen und das Problem zu ermitteln.",
        versionSavedFailed: "Der Speichervorgang wurde nicht abgeschlossen. Versuchen Sie später noch einmal zu speichern.",
        publishFileSizeExceedMsg: "Datei kann nicht veröffentlicht werden, da sie die maximal zulässige Dateigröße überschreitet, die vom Repository-Administrator festgelegt wurde. Löschen Sie Teile des Inhalts, um die Datei zu verkleinern, oder wenden Sie sich an Ihren Administrator, um die maximale Größe zu ändern.",
        checkinFileSizeExceedMsg: "Datei kann nicht eingecheckt werden, da sie die vom Repository-Administrator festgelegte maximal zulässige Dateigröße überschreitet. Löschen Sie Teile des Inhalts, um die Datei zu verkleinern, oder wenden Sie sich an Ihren Administrator, um die maximale Größe zu ändern.",
        versionpublished: "Version veröffentlicht von ${0} um ${1}.",
        versionPublishing2: "Die Version wird gespeichert.",
        versionPublishFailed2: "Die Version wurde nicht gespeichert. Möglicherweise ist die Datei zu groß oder der Server hat das zulässige Zeitlimit überschritten. Versuchen Sie es später noch einmal oder brechen Sie den Vorgang ab und wenden Sie sich an Ihren Administrator, um das Serverprotokoll zu überprüfen und das Problem zu ermitteln.",      
        publishFileSizeExceedMsg2: "Datei kann nicht gespeichert werden, da sie die maximal zulässige Dateigröße überschreitet, die vom Repository-Administrator festgelegt wurde. Löschen Sie Teile des Inhalts, um die Datei zu verkleinern, oder wenden Sie sich an Ihren Administrator, um die maximale Größe zu ändern.",
        versionpublished2: "Version gespeichert von ${0} um ${1}.",
        chekinCloseDocsMsg: "Sie können ${productName} jetzt schließen.",
        draftSavingAs: "Datei wird kopiert ...",
        draftSavedAs: "Die neue Kopie wird gespeichert unter ${0}.",
        synchronizing: "Warten, bis die Synchronisation mit dem Server abgeschlossen ist.",
        synchronizeError: "Die Synchronisation mit dem Server kann nicht abgeschlossen werden.",
        joinwithoutentitle: "Benutzer: ${0} beabsichtigen das Dokument zu bearbeiten, können jedoch nicht an der Bearbeitung teilnehmen, weil Sie nicht zur gemeinsamen Bearbeitung berechtigt sind.",
        joinwithoutentitle2: "Benutzer: ${0} beabsichtigen das Dokument zu bearbeiten, können jedoch nicht an der Bearbeitung teilnehmen, weil sie nicht zur gemeinsamen Bearbeitung berechtigt sind.",
        backtoFiles: "Öffnen Sie 'Meine Dateien'",
        backtoCommFiles: "Community-Dateien öffnen",
        backtoLibrary: "Bibliothek öffnen",
        backtoICN: "Content Navigator öffnen",
        backtoRepository: "Dateienliste öffnen",
        createNewSpred: "Arbeitsblatt erstellen",
        createNewDoc: "Dokument erstellen",
        createNewDocFromTemp: "Dokument aus Vorlage erstellen",
        shareDoc: "Dokument gemeinsam nutzen",
        exportPdf: "Seite einrichten",
        insertDate: "Datumsauswahl",
        insertTime: "Zeitauswahl",
        connect: "Verbinden",
        theDoc: "Dokument",
        save: "Änderungen speichern",
        saveBeforeReviewMsg: "Sie haben nicht gespeicherte Änderungen. Speichern Sie Ihre Änderungen und reichen Sie sie erneut zur Prüfung ein.",
        submitReviewWidgetsFaiure: "Die Anwendung wurde nicht ordnungsgemäß initialisiert. Später zur Prüfung einreichen.",
        widgetsFaiure: "Die Anwendung wurde nicht ordnungsgemäß initialisiert.",
        slideSorter: "Folien",
        commentsBar: "Kommentare",
        draftBadge: "ENTWURF",
        share: "Freigeben",
        comment: "Kommentar",
        showSidebar: "Seitenleiste anzeigen",
        publishVersion: "Veröffentlichen",
        checkInVersion: "Einchecken",
        saveVersion: "Speichern",
        saved: "Alle Änderungen wurden gespeichert",
        saving: "Wird gespeichert",
        submitFragment: "Absenden",
        aria_inMainMenu: "Sie befinden sich nun im Hauptmenü",
        aria_inSlideSorter: "Sie befinden sich in der Sortierkomponentenansicht für Folien",
        aria_inSlideEditor: "Sie befinden sich in der Editoransicht für Folien",
        createNewPres: "Präsentation erstellen",
        createNewAppFromTemp: "Dokument aus einer Vorlage erstellen",
        textdoc: "Text",
        sheetdoc: "Arbeitsblatt",
        presdoc: "Präsentation",
        saveAsTextErrMsg: "Das neue Textdokument kann nicht gespeichert werden.",
        saveAsPresErrMsg: "Das neue Präsentationsdokument kann nicht gespeichert werden.",
        saveAsSheetErrMsg: "Das neue Arbeitsblattdokument kann nicht gespeichert werden.",
        saveAsTextErrMsg1: "Es ist nicht genügend Speicherplatz zum Speichern des Dokuments vorhanden.",
        saveAsPresErrMsg1: "Es ist nicht genügend Speicherplatz zum Speichern der Präsentation vorhanden.",
        saveAsSheetErrMsg1: "Es ist nicht genügend Speicherplatz zum Speichern des Arbeitsblatts vorhanden.",
        newDocTextErrMsg: "Ein neues Textdokument kann nicht erstellt werden.",
        newDocSheetErrMsg: "Ein neues Arbeitsblattdokument kann nicht erstellt werden.",
        newDocPresErrMsg: "Ein neues Präsentationsdokument kann nicht erstellt werden.",
        newDocTextErrMsg2: "Ein neues Textdokument kann nicht aus der Vorlage erstellt werden.",
        newDocSheetErrMsg2: "Ein neues Arbeitsblattdokument kann nicht aus der Vorlage erstellt werden.",
        newDocPresErrMsg2: "Ein neues Präsentationsdokument kann nicht aus der Vorlage erstellt werden.",
        newDocTextErrMsg3: "Es ist nicht ausreichend Speicherplatz vorhanden, um ein Dokument zu erstellen.",
        newDocSheetErrMsg3: "Es ist nicht ausreichend Speicherplatz vorhanden, um ein Arbeitsblatt zu erstellen.",
        newDocPresErrMsg3: "Es ist nicht ausreichend Speicherplatz vorhanden, um eine Präsentation zu erstellen.",
        newDocTextErrMsg4: "Es ist bereits ein Dokument mit diesem Titel vorhanden. Geben Sie einen anderen Titel für das neue Dokument an.",
        newDocSheetErrMsg4: "Es ist bereits ein Arbeitsblatt mit diesem Titel vorhanden. Geben Sie einen anderen Titel für das neue Arbeitsblatt an.",
        newDocPresErrMsg4: "Es ist bereits eine Präsentation mit diesem Titel vorhanden. Geben Sie einen anderen Titel für die neue Präsentation an.",        
        aclWarningTitle: "Die neue Version kann nicht bearbeitet werden",
        aclWarningMsg: "Da der Dateieigner in dieser Datei geschützte Bereiche festgelegt hat, sollte sie online bearbeitet werden. Wenden Sie sich an den Dateieigner (${0}), wenn Sie der Ansicht sind, dass Sie eine neue Version hochladen müssen.",
        aclWarningMsgForOwner: "Diese Datei enthält geschützte Bereiche. Daher können Sie die hochgeladene neue Version nicht online bearbeiten. Sie müssen alle geschützten Bereiche in dieser Datei entfernen; dann können Sie sie öffnen und die hochgeladene neue Version bearbeiten. ",
        st0: "Blatt1",
        st1: "Blatt2",
        st2: "Blatt3",
        FootnoteMsg: "Seite",
        conflictMsg: "Es besteht ein Konflikt mit den Änderungen anderer Bearbeiter.  Ihre Änderung wird widerrufen.",
        undoRedoConflictMsg: "Die Funktionen 'Rückgängig' und 'Wiederholen' wurden wegen eines Konflikts zwischen Ihrer Bearbeitung und denen eines anderen Benutzers inaktiviert.",
        bigFileErrMsg: "Das Dokument ist zu groß. Aktualisieren Sie Ihren Browser, um zu überprüfen, ob der gesamte Inhalt unbeschädigt ist.",
        noPermissionMsg: "Sie sind nicht berechtigt, diese Datei zu bearbeiten. Wenden Sie sich an den Dateieigner, um eine Berechtigung zum Bearbeiten zu erhalten, und versuchen Sie es erneut.",
        networkIssueMsg: "Es besteht ein Netzproblem.",
        networkIssueTitle: "Netzwerkproblem",
        networkIssueContent: "Es besteht ein Netzproblem. Aktualisieren Sie die Seite und versuchen Sie erneut, eine Verbindung herzustellen.",
        lockEditorMsg: "Das Dokument kann nicht bearbeitet werden, bis eine Verbindung zum Server besteht",
        offlineReasonMsg: "Das zulässige Zeitlimit der Sitzung wurde überschritten.",
        offlineReasonForServerUnacceptedMsg: "Einige Ihrer Aktionen konnten nicht verarbeitet werden. Aktionen innerhalb einer Minute werden vom Docs-Server verworfen.",
        offlineReasonForServerDraftFormatChange: "Das Format Ihre Dokuments ist aufgrund eines Server-Upgrades nicht auf dem neuesten Stand. ",
        reloadExplanationMsg: "Melden Sie sich erneut an, um Ihre Arbeit fortzusetzen.",
        reloadBtnLabel: "Erneut laden",
        reconnectingMsg: "Warten, bis eine Verbindung mit dem Server hergestellt ist.",
        loadMsg: "Warten, während das Dokument lädt.",
        loadingDocumentMsg: "Warten, während das Dokument vom Server geladen wird.",
        reLoadingDocumentMsg: "Warten, während das Dokument erneut vom Server geladen wird.",
        unsupportMsg: "Es wurde eine nicht unterstützte Funktion gefunden. Nähere Informationen finden Sie hier. ",
        browserWorkingMsg: "Beschäftigt...",
        fileDeepDetectTitle: "Das Dateiformat und die Dateierweiterung stimmen nicht überein.",
        fileDeepDetectMsg: "Das Dateiformat entspricht nicht dem Format, das von der Dateierweiterung vorgegeben wird. Klicken Sie auf 'Fortfahren', um die Datei in diesem Format zu bearbeiten.",
        fileDeepDetectOkLabel: "Weiter",
        tipInfo: "Tipp: ${0}",
        selectTextInfo: "Wählen Sie Text aus, um einen Stil anzuwenden.",
        removeRecentFile: "Die Datei, die Sie öffnen möchten, wurde gelöscht. Möchten Sie den Dateinamen aus der Liste der zuletzt verwendeten Dateien entfernen?",
        altLotusIcon: "",
        altErrorMsgIcon: "Fehlermeldung",
        altWarningMsgIcon: "Warnung",
        altSuccessMsgIcon: "Nachricht über erfolgreiche Ausführung",
        sidebarLandmarkDesc: "Seitenleiste",
        footerTitle: "Fußzeile",
        mainDesc: "Inhaltsbereich",
        editLockedDocumentWarning: "Sie haben die Datei gesperrt, während andere Personen sie bearbeiteten. Bitte arbeiten Sie gemeinsam mit ihnen, um Änderungen zu koordinieren oder bitten Sie sie, die Bearbeitung zu beenden, damit Sie exklusiven Bearbeitungszugriff erhalten können.",
        observerMode: "Sie arbeiten zur Zeit im Modus 'Beobachter'",
        editorMode: "Sie arbeiten zur Zeit im Modus 'Bearbeiter'",
        maxEditorLimitReached: "Das Dokument hat bereits die maximal zulässige Anzahl von ${0} Bearbeiter für diese Sitzung erreicht. Sie können in den Bearbeitungsmodus wechseln, wenn  ein Bearbeiter das Dokument verlässt oder in den Beobachtermodus wechselt.",
        maxEditorLimitReachedTitle: "Maximale Bearbeiteranzahl erreicht",
        uploadNewVersionOpenConfirm: "Eine neue Version wurde von ${0} nach ${1} ${2} hochgeladen. Möchten Sie die neue Version öffnen?", //${0} name, ${1} time, ${2} date
        uploadNewVersionPublishConfirm: "Eine neue Version wurde von ${0} nach ${1} ${2} hochgeladen.", //${0} name, ${1} time, ${2} date
        you: "Benutzer",
        today: "heute",
        yesterday: "gestern",
        slideShowInviteMsg: "Benutzer ${0} hat eine gemeinsame Präsentation eingeleitet. Möchten Sie daran teilnehmen?",
        slideShowInviteTitle: "Einladung zu gemeinsamer Präsentation",
        slideShowInviteTitle1: "Einladung zur Sammelpräsentation",
        slideShowCoviewSelectUsersTitle: "Gemeinsame Präsentation",
        slideShowCoviewSelectUsersTitle1: "Sammelpräsentation",
        slideShowCoviewStmt: "Geben Sie die aktuelle Version der Darstellung in einer gemeinsamen Präsentation frei.",
        slideShowCoviewStmt1: "Geben Sie die aktuelle Version der Darstellung in einer Sammelpräsentation frei.",
        slideShowCoviewOptionOne: "Laden Sie alle Bearbeiter zur Präsentation ein.",
        slideShowCoviewOptionOne1: "Laden Sie alle Bearbeiter und Beobachter zur Präsentation ein.",
        slideShowCoviewOptionTwo: "Laden Sie nur die folgenden Bearbeiter zur Präsentation ein.",
        slideShowCoviewOptionTwo1: "Laden Sie nur die folgenden Bearbeiter und Beobachter zur Präsentation ein.",
        slideShowCoviewSlidesOf: "Folie ${0} von ${1}",  //as in Slide 1 of 4
        slideShowCoviewViewers: "${0} Betrachter",
        slideShowCoviewDialogInput: "Filternamen eingeben",
        slideShowCoviewAddTitle: "Zur gemeinsamen Präsentation hinzufügen",
        slideShowCoviewAddTitle1: "Zur Sammelpräsentation hinzufügen",
        slideShowCoviewMessage: "Wählen Sie zusätzliche Benutzer und laden Sie sie zu dieser gemeinsamen Präsentation ein.",
        slideShowCoviewMessage1: "Wählen Sie zusätzliche Benutzer und laden Sie sie zu dieser Sammelpräsentation ein.",
        slideShowCoviewEnded: "Gemeinsame Präsentation ist beendet",
        slideShowCoviewEndMessage: "Die gemeinsame Präsentation, an der Sie teilnehmen möchten, ist nicht mehr verfügbar.",
        slideShowCoviewEndMessage2: "Benutzer ${0} hat die gemeinsame Präsentation beendet.",
        slideShowWarning: "Sie müssen die aktuelle Präsentation schließen, um eine neue zu beginnen.",
        slideShowHoverMsg: "Klicken Sie, um zu sehen, wer die Präsentation betrachtet.",
        slideShowHoverMsgAdd: "Klicken Sie, um weitere Betrachter anzuzeigen.",
        csvEmpty: "Ein Export als CSV-Datei ist nicht möglich, da das Arbeitsblatt keine Daten enthält.",
        edit: "Bearbeiten",
        printToPDF: "Als PDF herunterladen",
        print: "Drucken",
        view: "Ansicht",
        openLatestFile: "Neueste Datei öffnen",
        updateDocument: "Das Dokument wurde aktualisiert. ${0}.",
        updateSpreadsheet: "Das Arbeitsblatt wurde aktualisiert.${0}",
        updatePresentation: "Die Präsentation wurde aktualisiert. ${0}.",
        labelCancel: "Abbrechen",
        msgConversionFail: "Konvertierung fehlgeschlagen",
        updateNow: "Jetzt öffnen",
        fileUpdated: "Das aktualisierte Dokument",
        fileUpdatedContent1: "Das Dokument wurde aktualisiert. Öffnen Sie vor dem Drucken die neueste Datei.",
        htmlviewerlimitation1: "Dieses Arbeitsblatt enthält eine Pivot-Tabelle, die nicht angezeigt werden kann",
        htmlviewerlimitation2: "Dieses Arbeitsblatt enthält bedingte Formatierungen, die nicht angezeigt werden können",
        htmlviewerlimitation3: "Dieses Arbeitsblatt enthält eine Pivot-Tabelle und bedingte Formatierungen, die nicht angezeigt werden können",
        close: "Schließen",
        closeDocs: "Schließen Sie ${productName}.",
        endSessionDlgTitle: "Die Bearbeitungssitzung wurde beendet",
        endSessionDlgNotice: "Ihre Bearbeitungssitzung wurde beendet, weil ${0} die Datei eingecheckt hat.",
        labelStopReview: "Prüfung anhalten",
        labelRejct: "Ablehnen",
        labelApprove: "Genehmigen",
        errorMsg: "Fehler",
        labelItemNotFountTitle: "Aktion kann nicht abgeschlossen werden.",
        labelItemNotFountMsg: "Ein anderes Community-Mitglied führt bereits eine Aktion an diesem Dokument durch. Um weitere Informationen zu erhalten, schließen Sie das Dokument und rufen Sie die Seite mit den Dateiinformationen in Ihrer Bibliothek auf.",
        viewProtectedAreas: "Dieses Arbeitsblatt enthält geschützte Bereiche. Sie sollten es nur online anzeigen oder bearbeiten.",
        macroTitle: "Die Datei enthält ein Makro", 
        macroDesc: "Durch die Bearbeitung dieser Datei kann das Makro beschädigt werden. Verwenden Sie 'Daten > Geschützte Bereiche', um zu verhindern, dass Benutzer den Bereich oder das Arbeitsblatt mit dem Makro bearbeiten.",
        problem_id_msg_title: "Melden Sie dieses Problem Ihrem Administrator. ",
        problem_id_msg_show: "Klicken, um Details anzuzeigen",
    	problem_id_msg_hide: "Klicken, um auszublenden",
    	uploadNewVersionWarningTitle: "Die neue Version kann nicht bearbeitet werden",
        changeHistoryWarningMsg: "Da der Dateieigner die Änderungsnachverfolgung in dieser Datei aktiviert hat, sollten Sie sie online bearbeiten. Wenden Sie sich an den Dateieigner (${0}), wenn Sie der Ansicht sind, dass Sie eine neue Version hochladen müssen.",
        changeHistoryWarningMsgForOwner: "Diese Datei verfügt über ein Änderungsprotokoll. Daher können Sie die hochgeladene neue Version nicht online bearbeiten. Sie müssen das Änderungsprotokoll löschen und die Änderungsnachverfolgung in dieser Datei inaktivieren; dann können Sie sie öffnen und die hochgeladene neue Version bearbeiten.",
        viewChangeHistory: "Dieses Dokument enthält ein Änderungsprotokoll. Sie sollten es nur online anzeigen oder bearbeiten.",
    	contentCorruptErrMsg: "Der Inhalt kann nicht geladen werden, da er beschädigt ist. Wenden Sie sich an Ihren Administrator, um Unterstützung zu erhalten."
});

