({
	ORIENTATION_LABEL: "Tájolás",
	PORTRAIT: "Álló",
	LANDSCAPE: "Fekvő",
	PAGE_LABEL: "Oldalsorrend",
	PAGE_TYPE1: "Fentről lefelé, majd jobbra",
	PAGE_TYPE2: "Balról jobbra, majd lefelé",
	DISPLAY_OPTION_LABEL: "Megjelenítési beállítások",
	HEADER: "Fejléc",
	FOOTER: "Lábléc",
	GRIDLINE: "Rácsvonalak",
	TAGGED_PDF: "Címkézett PDF",
	MARGINS_LABEL: "Margók",
	TOP: "Felső:",
	TOP_DESC:"Felső margó, centiméter",
	TOP_DESC2:"Felső margó, hüvelyk",
	BOTTOM: "Alsó",
	BOTTOM_DESC:"Alsó margó, centiméter",
	BOTTOM_DESC2:"Alsó margó, hüvelyk",	
	LEFT: "Bal:",
	LEFT_DESC:"Bal margó, centiméter",
	LEFT_DESC2:"Bal margó, hüvelyk",	
	RIGHT: "Jobb:",
	RIGHT_DESC:"Jobb margó, centiméter",
	RIGHT_DESC2:"Jobb margó, hüvelyk",	
	PAPER_FORMAT_LABEL: "Papírformátum",
	PAPER_SIZE_LABEL: "Papírméret:",
	HEIGHT: "Magasság:",
	HEIGHT_DESC:"A papír magassága, centiméter",
	HEIGHT_DESC2:"A papír magassága, hüvelyk",		
	WIDTH: "Szélesség:",
	WIDTH_DESC:"A papír szélessége, centiméter",
	WIDTH_DESC2:"A papír szélessége, hüvelyk",
	
	INVALID_MSG: "A bemenet érvénytelen, és rendszer automatikusan kijavította. Ha más eredményt szeretne, adjon meg másik értéket.",
	
	TOOLTIP1:"Annyi sort nyomtat, amennyit a papír hossza lehetővé tesz. Eközben addig mozog keresztbe, amíg már nincs több oszlop a munkalapon, majd lefelé és balra mozdul, hogy kinyomtassa a következő sorcsoportot.",
	TOOLTIP2:"Annyi oszlopot nyomtat, amennyit a papír szélessége lehetővé tesz. Eközben addig mozog lefelé, amíg már nincs több sor a munkalapon, majd felfelé és jobbra mozdul, hogy kinyomtassa a következő oszlopcsoportot.",
	CM_LABEL: "cm",
	LETTER: "Letter",
	LEGAL: "Legal",
	TABLOID: "Tabloid",
	USER: "Egyéni",
	SIZE1: "Boríték, 6 3/4",
	SIZE2: "Boríték, Monarch",
	SIZE3: "Boríték, 9",
	SIZE4: "Boríték, 10",
	SIZE5: "Boríték, 11",
	SIZE6: "Boríték, 12",
	SIZE7: "16 kai",
	SIZE8: "32 kai",
	SIZE9: "32 kai nagy"
})
	
