/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */


define({
        saveTip: "Gem",
        undoTip: "Fortryd",
        redoTip: "Annullér Fortryd",
        formatPainterTip: "Kopiér formatering",
        showSorterTip: "Vis diassortering",
        hideSorterTip: "Skjul diassortering",
        webClipboardTip: "Webudklipsholder",
        spellCheckTip: "Kør manuel stavekontrol",
        createSectionTip: "Tildel en sektion",
        createCellsTip: "Tildel celler",
        createSlideTip: "Tildel dias",
        submitTip: "Send tildeling",
        addCommentTip: "Tilføj kommentar",
        removeFormatTip: "Fjern formatering",
        sortAscTip: "Sortér stigende",
        sortDescTip: "Sortér faldende",
        instantFilterTip: "Filtrér omgående",
        insertChartTip: "Indsæt diagram",
        startAutofillTip: "Automatisk udfyldning",
        dataValidationTip: "Datavalidering",

        selectFontTip: "Vælg skrifttype",
        selectFontSizeTip: "Vælg skriftstørrelse",
        selectFontNameTip: "Vælg skriftnavn",
        FontName: "Skriftnavn",
        FontSize: "Skriftstørrelse",
        increaseFontSizeTip: "Forøg skriftstørrelse",
        decreaseFontSizeTip: "Formindsk skriftstørrelse",
        boldTip: "Fed",
        italicTip: "Kursiv",
        underlineTip: "Understreget",
        strikeThroughTip: "Gennemstreget",
        setFontColorTip: "Definér skrifttypefarve",
        setShadingColorTip: "Definér skyggefarve",
        setBackgroundFill: "Definér baggrundsudfyldning",
        setBgColorTip: "Definér baggrundsfarve",
        setBorderTip: "Definér kanttypografi og -farve",
        setBorderColorTip: "Definér kantfarve",
        setHighlightColor: "Definér fremhævningsfarve",
        formatPainter: "Kopiér formatering",
        //	clearFormat:"Remove Formatting",
        zoom: "Zoom",
        selectStyleTip: "Vælg typografi",
        styles: "Typografi",
        formatAsCurrencyTip: "Formatér som valuta",
        formatAsPercentTip: "Formatér som procent",
        decreaseDecimalTip: "Færre decimaler",
        increaseDecimalTip: "Flere decimaler",
        formatNumberTip: "Formatér tal",

        numberedListTip: "Tilføj nummerings- eller revidér nummeringstypografi",
        bulletedListTip: "Tilføj punkttegn eller Revidér punkttegnstypografi",
        multilevelListTip: "Tilføj eller Revidér lister på flere niveauer",
        indentTip: "Forøg indrykning",
        decreaseIndentTip: "Formindsk indrykning",
        alignTip: "Justér",
        leftAlignTip: "Venstrejusteret",
        centerTip: "Centreret",
        rightAlignTip: "Højrejusteret",
        justifyTip: "Lige margener",
        bottomBorderTip: "Nederste kant",
        borderTypes: "Kanttyper",
        borderTip: "Definér kanttypografi",
        topAlignTip: "Justér top",
        middleAlignTip: "Justér midt",
        bottomAlignTip: "Justér bund",
        lineSpacingTip: "Linjemellemrum",
        mergeSplitCellTip: "Flet eller opdel celler",
        wrapNoWrapTip: "Ombrydning aktiveret eller deaktiveret",
        ltrDirectionTip: "Skift til Venstre til højre-tekst",
        rtlDirectionTip: "Skift til Højre til venstre-tekst",
        autoDirectionTip: "Skift tekstretning",
        toggleSheetDirectionTip: "Skift arkretning",
        setSheetDirectionLTR: "Venstre til højre",
        setSheetDirectionRTL: "Højre til venstre",

        addTableTip: "Tilføj tabel",
        insertOrMoveRowTip: "Indsæt eller flyt række",
        insertOrMoveColTip: "Indsæt eller flyt kolonne",
        insertOrDeleteRowTip: "Indsæt eller slet række",
        insertOrDeleteColTip: "Indsæt eller slet kolonne",
        insertFunctionTip: "Indsættefunktion",
        insertImage: "Indsæt billede",
        resizeCol: "Tilpas størrelse på kolonne",
        resizeCols: "Tilpas størrelse på kolonner",
        addLink: "Tilføj eller redigér link",
        tableStyle: "Tabeltypografier",

        selectBorder_BottomBorder: "Nederste kant",
        selectBorder_TopBorder: "Øverste kant",
        selectBorder_LeftBorder: "Venstre kant",
        selectBorder_RightBorder: "Højre kant",
        selectBorder_NoBorder: "Ingen linjer",
        selectBorder_AllBorders: "Alle kanter",

        insertOrMoveRow_InsertAbove: "Indsæt række over",
        insertOrMoveRow_InsertBelow: "Indsæt række under",
        insertOrMoveRow_MoveUp: "Flyt række op",
        insertOrMoveRow_MoveDown: "Flyt række ned",
        insertOrMoveCol_InsertLeft: "Indsæt kolonne før",
        insertOrMoveCol_InsertRight: "Indsæt kolonne efter",
        insertOrMoveCol_InsertBefore: "Indsæt kolonne før",
        insertOrMoveCol_InsertAfter: "Indsæt kolonne efter",
        insertOrMoveCol_MoveLeft: "Flyt kolonne til venstre",
        insertOrMoveCol_MoveRight: "Flyt kolonne til højre",

        insertOrDelete_Delete: "Slet",

        combineButtonReadTip: "Tryk på Pil ned for at aktivere menuen, og navigér derefter med piletasterne",

        lineSpacing_1: "1",
        lineSpacing_12: "1,2",
        lineSpacing_15: "1,5",
        lineSpacing_2: "2",
        lineSpacing_25: "2,5",
        lineSpacing_3: "3",

        percent: "%",
        font_arial: "Arial",

        fontSize: "${0} pt",

        slides: "Ét dias pr. side",
        slidesWithNotes: "Dias med noter",
        preparingSlides: "Klargør dias til udskrivning...",
        printLayoutOptionLabel: "Indstillinger til udskrivning af layout",

        targetRemovedWhenDialogOpen: "Denne handling kan ikke gennemføres, fordi målet er slettet af en anden medforfatter.",

        NUMBER: "Tal",
        CURRENCY: "Valuta",
        PERCENT: "Procent",
        DATE: "Dato",
        TIME: "Klokkeslæt",
        DATETIME: "Dato/klokkeslæt",
        MORECURRENCY: "Flere valutaer opdelt efter monetær enhed",
        MORECURRENCYCODE: "Flere valutaer opdelt efter valutakode",
        MOREDATE: "Flere klokkeslæts- og datoformater",
        TEXT: "Tekst",
	
        // currency, by currency code
        // NOTE: MUST keep it in order
        CURRENCY_CODE: {
            AED: "Forenede Arabiske Emirater (Dirham)",
            ARS: "Argentina (peso)",
            AUD: "Australien (dollar)",
            BGN: "Bulgarien (leva)",
            BOB: "Bolivia (boliviano)",
            BRL: "Brasilien (real)",
            CAD: "Canada (dollar)",
            CHF: "Schweiz (franc)",
            CLP: "Chile (peso)",
            CNY: "Kina (yuan renminbi)",
            COP: "Colombia (peso)",
            CRC: "Costa Rica (colon)",
            CZK: "Tjekkiet (koruna)",
            DKK: "Danmark (kroner)",
            DOP: "Dominikanske republik (peso)",
            EGP: "Egypten (pund)",
            EUR: "Østrig, Belgien, Finland, Frankrig,..., Slovenien, Spanien (euro)",
            GBP: "England, Storbritannien (pund)",
            HKD: "Hongkong (dollar)",
            HRK: "Kroatien (kuna)",
            HUF: "Ungarn (forint)",
            IDR: "Indonesien (rupiah)",
            ILS: "Israel (shekel)",
            INR: "Indien (rupee)",
            JPY: "Japan (yen)",
            KRW: "Korea, Syd (won)",
            KZT: "Kazakhstan (tenges)",
            MAD: "Marokko (dirham)",
            MXN: "Mexico (peso)",
            MYR: "Malaysia (ringgit)",
            NOK: "Norge (krone)",
            NZD: "New Zealand (dollar)",
            PAB: "Panama (balboa)",
            PEN: "Peru (Nueve sol)",
            PHP: "Filippinerne (peso)",
            PKR: "Pakistan (rupee)",
            PLN: "Polen (zloty)",
            PYG: "Paraguay (guarani)",
            RON: "Rumænien (leu)",
            RSD: "Serbien (kyrillisk), Serbien (latin)",
            RUB: "Rusland (rubel)",
            SAR: "Saudi-Arabien (riyal)",
            SEK: "Sverige (krone)",
            SGD: "Singapore (dollar)",
            SVC: "El Salvador (colon)",
            THB: "Thailand (baht)",
            TRY: "Tyrkiet (lira)",
            TWD: "Taiwan (ny dollar)",
            USD: "Ecuador, Puerto Rico, USA (US dollar)",
            UYU: "Uruguay (peso)",
            VEF: "Venezuela (bolivar fuerte)",
            VND: "Vietnam (dong)",
            ZAR: "Sydafrika (rand)"
        },
        // for border toolbar
        allBorders: "Alle kanter",
        innerBorders: "Interne kanter",
        horizontalBorders: "Vandrette kanter",
        verticalBorders: "Lodrette kanter",
        outerBorders: "Eksterne kanter",
        borderColor: "Kantfarve",
        leftBorder: "Venstre kant",
        topBorder: "Øvre kant",
        rightBorder: "Højre kant",
        bottomBorder: "Nedre kant",
        clearBorders: "Ingen kanter",
        BorderStyle_ThinSolid: "Tynd, udfyldt",
        BorderStyle_ThinDotted: "Tynd, prikket",
        BorderStyle_ThinDashed: "Tynd, brudt linje",
        BorderStyle_ThickSolid: "Tyk, udfyldt",
        BorderStyle_ThickDotted: "Tyk, prikket",
        BorderStyle_ThickDashed: "Tyk, brudt linje"
})

