define({      
//begin v1.x content
	"clearFilterDialogTitle": "Vymazat filtr",
	"filterDefDialogTitle": "Filtr",
	"defaultRuleTitle": "Pravidlo",
	"ruleTitleTemplate": "Pravidlo ${ruleNumber}",
	"noFilterApplied": "Není použitý žádný filtr.",
	"defineFilter": "Definovat filtr",
	"conditionEqual": "rovná se",
	"conditionNotEqual": "nerovná se",
	"conditionLess": "je menší než",
	"conditionLessEqual": "je menší nebo rovno",
	"conditionGreater": "je větší než",
	"conditionGreaterEqual": "je větší nebo rovno",
	"conditionContain": "obsahuje",
	"conditionIs": "je",
	"conditionStartWith": "začíná znaky",
	"conditionEndWith": "končí znaky",
	"conditionNotContain": "neobsahuje",
	"conditionIsNot": "není",
	"conditionNotStartWith": "nezačíná znaky",
	"conditionNotEndWith": "nekončí znaky",
	"conditionBefore": "před",
	"conditionAfter": "po",
	"conditionRange": "rozsah",
	"conditionIsEmpty": "je prázdné",
	"all": "vše",
	"any": "cokoli",
	"relationAll": "všechna pravidla",
	"waiRelAll": "Vyhovovat všem následujícím pravidlům:",
	"relationAny": "libovolné pravidlo",
	"waiRelAny": "Vyhovovat kterémukoli z následujících pravidel:",
	"relationMsgFront": "Odpovídat",
	"relationMsgTail": "",
	"and": "a",
	"or": "nebo",
	"addRuleButton": "Přidat pravidlo",
	"waiAddRuleButton": "Přidat nové pravidlo",
	"removeRuleButton": "Odebrat pravidlo",
	"waiRemoveRuleButtonTemplate": "Odebrat pravidlo ${0}",
	"addRuleButton": "Přidat pravidlo filtrace",
	"cancelButton": "Storno",
	"waiCancelButton": "Zrušit toto dialogové okno",
	"clearButton": "Vymazat",
	"waiClearButton": "Vymazat filtr",
	"filterButton": "Filtr",
	"waiFilterButton": "Odeslat filtr",
	"columnSelectLabel": "Sloupec:",
	"waiColumnSelectTemplate": "Sloupec pro pravidlo ${0}",
	"conditionSelectLabel": "Podmínka:",
	"waiConditionSelectTemplate": "Podmínka pro pravidlo ${0}",
	"valueBoxLabel": "Hodnota:",
	"waiValueBoxTemplate": "Zadejte hodnotu filtrování pro pravidlo ${0}",
	"rangeTo": "do",
	"rangeTemplate": "od ${0} do ${1}",
	"statusTipHeaderColumn": "Sloupec",
	"statusTipHeaderCondition": "Pravidla",
	"statusTipTitle": "Panel filtru",
	"statusTipMsg": "Klepněte na panel filtru, chcete-li filtrovat hodnoty v umístění ${0}.",
	"anycolumn": "kterýkoli sloupec",
	"statusTipTitleNoFilter": "Panel filtru",
	"statusTipTitleHasFilter": "Filtr",
	"statusTipRelPre": "Shoda:",
	"statusTipRelPost": "pravidel.",
	"statusTipHeaderAll": "Shoda se všemi pravidly.",
	"statusTipHeaderAny": "Shoda se kterýmikoli pravidly.",
	"defaultItemsName": "položky",
	"filterBarMsgHasFilterTemplate": "Zobrazeno ${0} z ${1} ${2}.",
	"filterBarMsgNoFilterTemplate": "Není použit žádný filtr",
	"filterBarDefButton": "Definovat filtr",
	"waiFilterBarDefButton": "Filtrovat tabulku",
	"a11yFilterBarDefButton": "Filtrovat...",
	"filterBarClearButton": "Vymazat filtr",
	"waiFilterBarClearButton": "Vymazat filtr",
	"closeFilterBarBtn": "Zavřít panel filtru",
	"clearFilterMsg": "Tato akce odebere filtr a zobrazí se všechny záznamy k dispozici.",
	"anyColumnOption": "Kterýkoli sloupec",
	"trueLabel": "Ano",
	"falseLabel": "Ne",
	"radioTrueLabel": "Hodnota Ano",
	"radioFalseLabel": "Hodnota Ne",
	"beginTimeRangeLabel": "Počáteční hodnota rozsahu času",
	"endTimeRangeLabel": "Koncová hodnota rozsahu času",
	"beginDateRangeLabel": "Počáteční hodnota rozsahu data",
	"endDateRangeLabel": "Koncová hodnota rozsahu data",
	"startsWithExpr": "${0}*"
//end v1.x content
});

