({	
	viewExpandedBtn: "Ver menos respostas",
	viewCollapsedBtn: "Ver mais ${0} respostas",
	placeholderMsg: "Introduza a sua mensagem aqui",
	sure: "Tem a certeza de que pretende eliminar este comentário?",
	exceed: "O comentário é demasiado longo.\n O comentário que introduziu excede o tamanho máximo permitido.\n Reduza o mesmo para um máximo de ${0} caracteres e faça clique em Adicionar.",
	remainLabelHint:"O seu comentário atingiu o limite de 500 caracteres.",
	tipsCommentField: "Introduza um comentário para todos os editores ou apenas para um editor",
	tipsRespondField: "Introduza uma resposta para todos os editores ou apenas para um editor",	
	resolveBtn: "Processar",	
	replyBtn: "Responder",
	saveBtn: "Publicar",
	deleteBtn: "Eliminar",
	cancelBtn: "Cancelar",
	reopenBtn: "Reabrir",
	todayAt: "Hoje às ${time}",
	yesterdayAt: "Ontem às ${time}",
	dateAt: "${date} às ${time}",
	mentions: "Seleccione um utilizador para mencionar",
	noMentions: "Tocar num campo em branco para preencher com os dados",
	nocomments: "Não existem comentários no documento '${0}'.",
	
	newComments:"Novos comentários",
	mentiontomesomebody:"Alguém",
	mentiontome:"${0} mencionou-o num comentário",
	
	newcommentsnumber:"O número de comentários não lidos",
	jawsnewcommentsnumber: "O número de comentários não lidos é ",
	jawsnactivecommentsnumber: "O número de comentários activos é ",
	
	activenum:"O número de comentários activos",
	filterDesc:"Filtrar comentários",
	menuallcomments:"Todos os comentários",
	menutome: "@eu",
	menubyme: "Por mim",
	menuactive: "Activo",
	menuresolved: "Processado",
	searchDesc: "Procurar nos comentários",
	search: "Procurar",
	closeDesc: "Fechar a procura",
	clear: "Limpar",
	warnEnterKeywords: "Introduzir termos da procura",
	nocommentstome: "Actualmente não existem comentários ou respostas que me mencionem no documento '${0}'.",
	nocommentsbyme: "Actualmente não existem comentários ou respostas minhas no documento '${0}'.",
	nocommentsar: "Actualmente não existem comentários na categoria '${0}' no documento '${1}'.",
	nosearchedcomments: "Actualmente não existem comentários ou respostas que contêm '${0}' na categoria '${1}' no documento '${2}'.",
	
	prevBtn: "Anterior",
	nextBtn: "Seguinte",
	mentionHint:"A mostrar ${0} a ${1} correspondências de um total de ${2}",
		
	resolveFlag: "Comentários processados",
	jawsCommentHint: "${authorname} publicou o comentário ${timestamp}",
	jawsReplyHint: "${authorname} publicou a resposta ${timestamp}",
	jawsContentHint: "O conteúdo é ${content}",
	jawsCommentStatusHint: "O estado é ${status}",
	jawsCommentKeyHint: "Pode premir Enter ou a Barra de espaços para aceder ao documento e visualizar a sessão de comentários completa, bem como processar, responder ou eliminar os comentários.",
	jawsMentionHint: "Mecanismo de menções do Docs. Pode premir a seta para cima ou a seta para baixo para seleccionar um utilizador a mencionar.",
	jawsMentionSelected: "Prima Enter ou a Barra de espaços para mencionar",
	commentDeletedMsg: "O comentário actual foi eliminado por outro editor.",
	commentResolvedMsg: "O comentário actual foi processado.",
	warningCommentMsg: "Os comentários realizados no Docs para os ficheiros ${0} apenas são suportados online. Se carregar uma nova versão para edição, a ligação aos comentários será removida.",
	orphanCommentTip: "A ligação ao comentário foi removida na versão carregada.",
	warningCommentName: "Aviso"
})

