({
		SAVE: "Spremi",
		UNDO:"Poništi",
		REDO:"Ponovno napravi",
		INSERTROW:"Umetni red",
		DELETEROW:"Izbriši red",
		INSERTCOLUMN:"Umetni stupac",
		DELETECOLUMN:"Izbriši stupac",
		FONTSIZE:"Veličina fonta",
		FONTCOLOR:"Boja fonta",
		BOLD:"Podebljaj",
		ITALIC:"Kurziv",
		UNDERLINE:"Podcrtaj",
		STRIKETHROUGH:"Precrtaj",
		CURRENCYTIP:"Formatiraj kao valutu",
		PERCENTLABEL:"%",
		PERCENTTIP:"Formatiraj kao postotak",
		NUMBERFORMAT:"Format broja",
		ALIGNLEFT:"Poravnaj lijevo",
		ALIGNCENTER:"Poravnaj u centar",
		ALIGNRIGHT:"Poravnaj desno",
		SETCELLBORDER:"Postavi rub ćelije",
		BACKGROUNDCOLOR:"Boja pozadine",
		TASK:"Dodijeli odjeljak",
		COMMENTS:"Dodaj komentar",
		SUBMIT:"Submit",
		MERGECELL: "Spoji ili razdijeli ćelije",
		QUICKFORMULA: "Brza formula",
		WRAPTEXT: "Prelomi tekst",
		EIGHT:"8pt",
		NINE:"9pt",
		TEN:"10pt",
		ELEVEN:"11pt",
		TWELVE:"12pt",
		FOURTEEN:"14pt",
		SIXTEEN:"16pt",
		EIGHTEEN:"18pt",
		TWENTY:"20pt",
		TWENTYTWO:"22pt",
		TWENTYFOUR:"24pt",
		NUMBER:"Broj",
		CURRENCY:"Valuta",
		PERCENT:"Postotak",
		DATE:"Datum",
		TIME:"Vrijeme",
		DATETIME: "Datum i vrijeme",
		MORECURRENCY:"Još valuta",
		MOREDATE:"Još formata",
		
		
		CAD: "kanadski dolar",
		USD: "dolar",
		EUR: "euro",
		CHF: "švicarski franak",
		HKD: "honkonški dolar",
		DKK: "kruna",
		LTL: "litas",
		PHP: "pezo",
		BRL: "real",
		RUR: "rublja",
		GBP: "funta",
		NLG: "gulden", // Netherlands
		TWD: "novotajvanski dolar",
		THB: "baht", // Thailand
		ITL: "lira", // Turkey
		BGL: "lev", // Uzbekistan
		VND: "dong", // Vietnam
		KRW: "von",	// Korean 
		CNY: "juan", // RMB
		JPY: "jen" // Japan Yen
})
