({
	service_unavailable_title: "Usluga nije raspoloživa.",
	service_unavailable_content: "${productName} usluga nije dostupna i vaš zahtjev se trenutno ne može obraditi. Pokušajte ponovno kasnije ili zatražite od sistem administratora da provjeri je li ${productName} usluga online.",
	access_denied_title: "Pristup zabranjen.",
	viewaccess_denied_content: "Nemate dozvolu za gledanje ove datoteke. Datoteka mora biti javna ili mora da se dijeli s vama.",
	editaccess_denied_content: "Nemate dozvolu za uređivanje ove datoteke. Datoteka se mora dijeliti s vama ili morate imati pristup editora za datoteku.",
	doc_notfound_title: "${productName} usluga ne može pronaći datoteku.",
	doc_notfound_content: "Obratite se administratoru i provjerite je li ${productName} usluga pravilno postavljena.",
	fullviewer_notsupport_title: "Dokument nije pronađen",
	fullviewer_notsupport_content: "Novi preglednik datoteka pohranjuje dokument na drugom url-u. Da biste pregledali dokument, pronađite datoteku u aplikaciji i kliknite tipku Pregled.",
	fileconnect_denied_title: "Veza je uskraćena.",
	fileconnect_denied_content: "${productName} se ne može povezati sa spremištem datoteke. Pokušajte kasnije ili kontaktirajte vašeg sistem administratora.",
	convservice_unavailable_title: "Usluga konverzije nije raspoloživa.",
	convservice_unavailable_content: "Vaš zahtjev ne može trenutno da se obradi. Pokušajte kasnije ili zatražite od sistem administratora da provjeri je li usluga konverzije online.",
	doc_toolarge_title: "Datoteka je prevelika.",
	doc_toolarge_content: "Dokument kojem želite pristupiti je prevelik.",
	doc_toolarge_content2: "Ne može se pristupiti datoteci zbog:",
	doc_toolarge_content3: "Datoteci se ne može pristupiti jer je veličina datoteke veća od ${0} KB. Ako datoteka ima sliku visoke rezolucije, možete je zamijeniti s jednom niske rezolucije da smanjite veličinu datoteke.",
	edit_locked_file: "Ne možete uređivati ovu datoteku jer su je zaključali drugi editori.",
	sheet_toolarge_content: "Veličina proračunske tablice je veća od ${0} KB.",
	sheet_toolarge_content2: "Proračunska tablica sadrži više od ${0} redova na jednom listu.",
	sheet_toolarge_content5: "Proračunska tablica sadrži više od ${0} kolona na jednom listu.",
	sheet_toolarge_content3: "Proračunska tablica sadrži više od ${0} ćelija.",
	sheet_toolarge_content4: "Proračunska tablica sadrži više od ${0} formula.",
	text_toolarge_content: "Veličina dokumenta je veća od ${0} KB.",
	text_toolarge_content2:"Dokument sadrži više od ${0} stranica.",
	text_toolarge_content3:"Veličina teksta u dokumentu je veća od ${0} KB.",
	pres_toolarge_content: "Veličina prezentacije je veća od ${0} KB.",
	pres_toolarge_content2: "Prezentacija sadrži više od ${0} stranica.",
	pres_toolarge_content3: "Prezentacija sadrži više od ${0} grafika.",
	pdf_toolarge_content: "Veličina pdf-a je veća od ${0} KB.",
	conversion_timeout_title: "Konverzija dokumenta je prekoračila vrijeme.",
	conversion_timeout_content: "Dokumentu trenutno treba previše vremena za konverziju. Pokušajte ponovo kasnije.",
	invalid_docformat_title: "Sadržaj dokumenta nije važeći.",
	invalid_docformat_content: "Ekstenzija datoteke dokumenta predstavlja važeći format, ali se ne može pristupiti sadržaju datoteke.  Provjerite je li datoteka ispravna. ",
	invalid_doctype_title: "Tip dokumenta nije podržan.",
	invalid_doctype_content: "${productName} trenutno ne podržava ovaj tip dokumenta.",
	malformed_request_title: "Pogrešan URL ili parametri.",
	malformed_request_content: "Uvjeri se da su URL i parametri ispravni.",
	storageserver_error_title: "Server za spremanje podataka nije raspoloživ.",
	storageserver_error_content: "Server je trenutno nedostupan. Vaš zahtjev ne može trenutno da se obradi. Pokušajte kasnije ili zatražite od sistem administratora da provjeri je li usluga spremanja online.",
	incorrect_web_address_title:"Pogrešna web adresa.",
	incorrect_web_address_content:"Web adresa nije ispravna.  Unesite web adresu i pokušajte ponovo.",
	unexpecified_conversion_error_title:"Greška nije specificirana.",
	unexpecified_conversion_error_content:"Server je vratio nespecificiranu grešku.",
	encrypted_conversion_error_title:"Šifrirani dokument nije podržan.",
	encrypted_conversion_error_content:"Datoteka je zaštićena lozinkom. Da biste pregledali datoteku u ${productName}, prvo morate dešifrirati datoteku.",
	document_encrypt_title:"Dokument je šifriran.",
	document_encrypt_content:"Datoteku ne možete pregledavati online jer je šifrirana kod spremanja u Datoteke.",
	service_busy_title:"Neuspješno otvaranje dokumenta",
	service_busy_content:"Datoteka koju želite pregledati se ne može otvoriti. Server je možda zauzet ili nedostupan. Pokušajte kasnije ili kontaktirajte administratora.",
	empty_doc_title: "Dokument je prazan.",
	empty_doc_content: "Provjerite nalazi li se u dokumentu sadržaj i pokušajte ponovo.",
	corrupted_doc_title: "Datoteka se ne može otvoriti.",
	corrupted_doc_content: "Datoteka sadrži nepodržani sadržaj, na primjer makronaredbe pa se ne može pregledavati u ovoj aplikaciji.",
	unexpected_code_title: "Dokument se ne može pregledati.",
	unexpected_code_content: "${docsProductName} server je možda nedostupan. Pokušajte ponovo kasnije.",
	unpublished_document_title: "Nije moguće pregledati datoteku",
	unpublished_document_content: "Nema objavljene verzije ove datoteke dostupne za pregledavanje.  Vlasnik datoteke mora objaviti verziju datoteke da bi se mogla pregledavati.",
	repository_out_of_space_title: "Nema dovoljno prostora",
	repository_out_of_space_content: "Ne može se objaviti ${0} jer ste dostigli kvotu veličine vaše datoteke. 1Smanjite vašu kvotu prebacivanjem drugih datoteka u smeće i zatim ih obrišite.",
	pdf_error_title:"1Datoteka se ne može otvoriti.",
	pdf_error_content:"PDF datoteka možda nije ispravna."
})

