({
	ORIENTATION_LABEL: "Orientació",
	PORTRAIT: "Vertical",
	LANDSCAPE: "Horitzontal",
	PAGE_LABEL: "Ordre de les pàgines",
	PAGE_TYPE1: "De dalt a baix i a la dreta",
	PAGE_TYPE2: "D\'esquerra a dreta, i després avall",
	DISPLAY_OPTION_LABEL: "Opcions de visualització",
	HEADER: "Capçalera",
	FOOTER: "Peu de pàgina",
	GRIDLINE: "Línies de quadrícula",
	TAGGED_PDF: "PDF etiquetat",
	MARGINS_LABEL: "Marges",
	TOP: "Superior:",
	TOP_DESC:"Marge superior, en centímetres",
	TOP_DESC2:"Marge superior, en polzades",
	BOTTOM: "Inferior:",
	BOTTOM_DESC:"Marge inferior, en centímetres",
	BOTTOM_DESC2:"Marge inferior, en polzades",	
	LEFT: "Esquerra:",
	LEFT_DESC:"Marge esquerre, en centímetres",
	LEFT_DESC2:"Marge esquerre, en polzades",	
	RIGHT: "Dreta:",
	RIGHT_DESC:"Marge dret, en centímetres",
	RIGHT_DESC2:"Marge dret, en polzades",	
	PAPER_FORMAT_LABEL: "Format del paper",
	PAPER_SIZE_LABEL: "Mida del paper:",
	HEIGHT: "Alçada:",
	HEIGHT_DESC:"Alçada del paper, en centímetres",
	HEIGHT_DESC2:"Alçada del paper, en polzades",		
	WIDTH: "Amplada:",
	WIDTH_DESC:"Amplada del paper, en centímetres",
	WIDTH_DESC2:"Amplada del paper, en polzades",
	
	INVALID_MSG: "L\'entrada no és vàlida i s\'ha rectificat automàticament. Proveu-ho amb un altre valor si voleu un resultat diferent.",
	
	TOOLTIP1:"Imprimeix tantes files com càpiguen a la longitud de la pàgina, desplaçant-se de costat fins que no hi hagi més columnes al full i, tot seguit, es desplaça cap avall i cap a l\'esquerra per imprimir el següent grup de files. ",
	TOOLTIP2:"Imprimeix tantes columnes com càpiguen a l\'amplada del paper, desplaçant-se cap avall fins que no hi hagi més files al full i, tot seguit, es desplaça cap amunt i cap a la dreta per imprimir el següent grup de columnes.",
	CM_LABEL: "cm",
	LETTER: "Carta",
	LEGAL: "Legal",
	TABLOID: "Tabloide",
	USER: "Usuari",
	SIZE1: "Sobre n.6 3/4",
	SIZE2: "Sobre Monarch",
	SIZE3: "Sobre #9",
	SIZE4: "Sobre #10",
	SIZE5: "Sobre #11",
	SIZE6: "Sobre #12",
	SIZE7: "16 kai",
	SIZE8: "32 kai",
	SIZE9: "32 kai gran"
})
	
