({	
	createTaskSummary: "${0}(e)k ataza sortu du.",
	completeTaskSummary: "${0}(e)k ataza markatu du osatuta gisa.",
	editTaskSummary5: "${0}(e)k atazaren ${1}, ${2}, ${3}, ${4} eta ${5} editatu ditu.",
	editTaskSummary4: "${0}(e)k atazaren ${1}, ${2}, ${3} eta ${4} editatu ditu.",
	editTaskSummary3: "${0}(e)k atazaren ${1}, ${2} eta ${3} editatu ditu.",
	editTaskSummary2: "${0}(e)k atazaren ${1} eta ${2} editatu ditu.",
	editTaskSummary1: "${0}(e)k atazaren ${1} editatu du.",
	editTaskSummary0: "${0}(e)k ataza editatu du.",
	removeTaskSummary: "${0}(e)k ataza ezabatu du.",
	reopenTaskSummary: "${0}(e)k ataza ireki du berriro.",
	reassignTaskSummary: "${0}(e)k berriro esleitu du ${1} ${2}(e)tik ${3}(e)ra.",
	reassignTaskSummary2: "${0}(e)k ataza berriro esleitu du ${1}(e)tik to ${2}(e)ra, eta berrikuspena ${3}(e)tik ${4}(e)ra.",
	workPrivateSummary: "${0}(e)k ataza honi ekin dio pribatuan.",
	approveTaskSummary: "${0}(e) ataza hau onartu du.",
	rejectTaskSummary: "${0}(e)k ataza hau baztertu du.",
	rejectTaskSummary2: "${0}(e)k ataza hau itzuli dio ${1}(r)i egokitzeko.",
	submitTaskSummary: "${0}(e)k hainbat lan pribatu itzuli dio dokumentuari.",
	cancelPrivateSummary: "${0}(e)k bertan behera utzi du lan pribatua.",
	updatedFieldsDesc: "${0}: ${1} -> ${2}",
	fieldAssignee: "esleipenduna",
	fieldDuedate: "epemuga",
	fieldDescription: "deskribapena",
	fieldReviewer: "berrikuslea",
	fieldTitle: "titulua",
	emptyFieldValue: "[Esleitu gabea]",
	errorAddMember:"Ezin da jarduera-zerbitzaria atzitu eta ezin da berrikusle edo esleipendunik gehitu. Saiatu berriro geroago.",
	errorCreateActivity:"Ezin da jarduera-zerbitzaria atzitu eta jarduera ezin da sortu. Saiatu berriro geroago.",
	errorLoadActivity:"Ezin da jarduera-zerbitzaria atzitu eta esleipenak ezin dira kargatu. Saiatu berriro geroago.",
	errorCreateAssignment: "Ezin da jarduera-zerbitzaria atzitu eta esleipena ezin da sortu. Saiatu berriro geroago.",
	errorDeleteAssignment: "Ezin da jarduera-zerbitzaria atzitu eta esleipenak ezin dira ezabatu. Saiatu berriro geroago.",
	errorupdateAssignment: "Ezin da jarduera-zerbitzaria atzitu eta esleipenak ezin dira eguneratu. Saiatu berriro geroago.",
	errorSubmitAssignment: "Ezin duzu ekintza hau egin. Egiaztatu egiteko baimena duzun.",	
	errorAddMember2:"Ezin da zerbitzaria atzitu eta ezin da berrikusle edo esleipendunik gehitu. Saiatu berriro geroago.",
	errorCreateActivity2:"Ezin da zerbitzaria atzitu eta ekintza ezin da sortu. Saiatu berriro geroago.",
	errorLoadActivity2:"Ezin da zerbitzaria atzitu eta esleipenak ezin dira kargatu. Saiatu berriro geroago.",
	errorCreateAssignment2: "Ezin da zerbitzaria atzitu eta esleipena ezin da sortu. Saiatu berriro geroago.",
	errorDeleteAssignment2: "Ezin da zerbitzaria atzitu eta esleipenak ezin dira ezabatu. Saiatu berriro geroago.",
	errorupdateAssignment2: "Ezin da zerbitzaria atzitu eta esleipenak ezin dira eguneratu. Saiatu berriro geroago."	
})

