({
	alt			: "Tekst alternatywny:",
	width		: "Szerokość:",
	height		: "Wysokość:",
	cmUnit   : "cm",
	ptUnit 	 : "pkt",
	inchUnit : "cal",
	inUnit   : "cal",
	mmUnit 	 : "mm",
	
	inputWarning: "Wprowadź liczbę dodatnią o jednostce domyślnej. ",
	
	properties: "Właściwości",
	data: "Dane",
	chart: "Wykres",
	axis: "Oś",
	series: "Seria",
	font: "Czcionka",
	title: "Tytuł",
	legend: "Legenda",
	placement: "Rozmieszczenie",
	background: "Tło",
	plotarea: "Obszar kreślenia",
	line : "Linia",
	fill: "Wypełnienie",
	border : "Krawędzie",
	labelfont: "Etykieta",
	scale: "Skala",
	minimum: "Minimalna",
	maximum: "Maksymalna",
	majorunit: "Jednostka główna",
	minorunit: "Jednostka pomocnicza",
	smooth: "Wygładź",
	marker: "Znaczniki",
	markerfill: "Znacznik",
	enterTitle: "Wprowadź tytuł w tym miejscu",
	inputNumberWarning: "Wprowadź liczbę.",
	inputPosNumberWarning: "Wprowadź liczbę dodatnią.",
	maxMinWarning: "Wartość maksymalna musi być większa niż wartość minimalna.",
	selectFontName: "Wybierz nazwę czcionki",
	selectFontSize: "Wybierz wielkość czcionki",
	setBold: "Pogrubienie",
	setItalic: "Kursywa",
	setFontColor: "Ustaw kolor czcionki",
	setLegendPos: "Ustaw rozmieszczenie legendy",
	setBackColor: "Ustaw kolor tła wykresu",
	setBorderWidth: "Ustaw szerokość krawędzi",
	setBorderColor: "Ustaw kolor krawędzi",
	setPlotAreaColor: "Ustaw kolor obszaru kreślenia",
	selectAxis: "Wybierz oś",
	setLineWidth: "Ustaw szerokość linii",
	setLineColor: "Ustaw kolor linii",
	selectSeries: "Wybierz serię",
	setFillColor: "Ustaw kolor wypełnienia",
	setMarker: "Ustaw znaczniki",
	setSmooth: "Ustaw wygładzoną linię",
	chartTitle: "Tytuł wykresu",
	axisTitle: "Tytuł osi",
	
	ERR1: "Tablica musi być ujęta w nawias klamrowy.",
	ERR3: "Łańcuchy muszą być ujęte w podwójny cudzysłów.",
	ERR4: "Wprowadź tylko jeden zakres.",
	ERR5: "Zakres musi istnieć.",
	ERR6: "Wszystkie zakresy muszą znajdować się w tym samym arkuszu.",
	ERR7: "Każdy zakres musi znajdować się w jednym wierszu lub kolumnie.",
	ERR9: "Wymagana jest wartość serii.",
	
	n	: "Brak",
	l	: "Z lewej",
	r	: "Z prawej",
	t	: "U góry",
	b   : "U dołu",
	
	dataSeries:"Seria danych",
	label:"Nazwa serii",
	xVal:"Wartości X serii",
	yVal:"Wartości Y serii",
	val:"Wartości serii",
	cat:"Kategoria",
		
	ltr: "Od lewej do prawej",
	rtl: "Od prawej do lewej",
	auto: "Kontekstowo",
	bidi_dir: "Kierunek",
	bidi_text_dir: "Kierunek tekstu"
})
