#!/usr/bin/python

# ***************************************************************** 
#                                                                   
# Licensed Materials - Property of IBM.                                               
#                                                                   
# IBM Docs Source Materials                                              
#                                                                   
# (c) Copyright IBM Corporation 2012. All Rights Reserved.                                        
#                                                                   
# U.S. Government Users Restricted Rights: Use, duplication or 
# disclosure restricted by GSA ADP Schedule Contract with 
# IBM Corp.              
#                                                                   
# ***************************************************************** 

import re,sys,os,subprocess,socket,shutil,distutils,time
sys.path.append('/opt/ll/lib/registry')
sys.path.append('/opt/ll/lib/apache/zookeeper')
from registryLib import *
from zooKeeperLib import *

#---------------------------------------------------------------------------------------------
# Main
#---------------------------------------------------------------------------------------------

#Initialize objects
registryParser = RegistryParser()
zooKeeperClient = ZooKeeperClient()

baseTopologyName = registryParser.getBaseTopologyName()
topologyName = registryParser.getTopologyName()

isDocsMA = registryParser.getSetting('Docs','is_docs_multiactive')
print 'is Docs multiactive %s' % (isDocsMA)

routingPolicy = registryParser.getSetting('Docs', 'docsrp_routing_policy')
print 'Docs routing policy is %s' % (routingPolicy)

hostname = socket.gethostname().split('.')[0]

if (isDocsMA == "true" or routingPolicy == "dynamic"):
  zooKeeperClient.updateActivationStatus('Start to set server %s phase to flipped' % (hostname))
  print 'Start to set server %s phase to flipped' % (hostname)
  
  try:
    phasePath = '/' + baseTopologyName + '/data/docs/data/' + topologyName + '/members/' + hostname + "/phase"  
    zooKeeperClient.setData(phasePath, 'flipped')
    print 'Set server %s phase to flipped successfully' % (hostname) 
  except:
    zooKeeperClient.updateActivationStatus('Error while set phase to flipped')
    print('Error while set phase to flipped')
    sys.exit(-1)
    
  zooKeeperClient.updateActivationStatus('Set server %s phase to flipped successfully' % (hostname))
  
  



