#!/usr/bin/python

# ***************************************************************** 
#                                                                   
# Licensed Materials - Property of IBM.                                               
#                                                                   
# IBM Docs Source Materials                                              
#                                                                   
# (c) Copyright IBM Corporation 2013. All Rights Reserved.                                        
#                                                                   
# U.S. Government Users Restricted Rights: Use, duplication or 
# disclosure restricted by GSA ADP Schedule Contract with 
# IBM Corp.              
#                                                                   
# ***************************************************************** 

import re,sys,os,subprocess,shutil,distutils,time
sys.path.append('/opt/ll/lib/registry')
sys.path.append('/opt/ll/lib/apache/zookeeper')
sys.path.append('/opt/ll/lib/nfs')
from registryLib import *
from zooKeeperLib import *

def executeCommand(command, obfuscate=None):
  log = 'Executing: '
  if obfuscate:
    log += command.replace(obfuscate, '***')
  else:
    log +=  command
  print log
  p = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  output = p.communicate()[0]
  print output
  if p.returncode:
    raise Exception('Error executing command: ' + output)
  print 'Command successful.'
  
  return output

#---------------------------------------------------------------------------------------------
# Main
#---------------------------------------------------------------------------------------------

#Initialize objects
registryParser = RegistryParser()
zooKeeperClient = ZooKeeperClient()
was_username = registryParser.getSetting('MiddlewareWebSphere','admin_username')
was_password = registryParser.getSetting('MiddlewareWebSphere','admin_password')

zooKeeperClient.updateActivationStatus('Starting draft migration tool in Docs')
print('Starting draft migration tool in Docs')

try:
  #executeCommand('/opt/IBM/WebSphere/AppServer/profiles/AppSrv01/bin/wsadmin.sh -lang jython -username %s -password %s -f /opt/ll/apps/IBMDocs/rpm/DocsApp/installer/docs/tasks/start_migration_tool.py' % (was_username, was_password))
  #zooKeeperClient.updateActivationStatus('Draft migration tool is started')
  #print('Draft migration tool is started')
  print('Draft migration tool has been disabled')
except:
  zooKeeperClient.updateActivationStatus('Error while executing /opt/ll/apps/IBMDocs/rpm/DocsApp/installer/docs/tasks/start_migration_tool.py')
  print('Error while executing /opt/ll/apps/IBMDocs/rpm/DocsApp/installer/docs/tasks/start_migration_tool.py')
  sys.exit(-1)
  



