({
	labelNormal: "Visualizzazione normale",
	labelPlay: "Riproduci presentazione",
	labelZoomIn: "Zoom avanti",
	labelZoomOut: "Zoom indietro",
	labelFitWidth: "Adatta in larghezza",
	labelReset: "Reimpostare",
	lablePageUp: "Pagina precedente",
	lablePageDown: "Pagina successiva",
	labelPrint: "Stampa",
	labelBuild: "${productName} ${0}",
	labelVersion: "${productName} ${0} ${1}",
	msgLoading: "Caricamento del documento in corso. Attendere.",
	msgConversionFail: "Conversione non riuscita",
	labelReload: "Ricarica",
	labelHelpContent:"Contenuto della guida",
	labelAbout:"Informazioni",
	labelProject:"${productName}",
	labelEdit: "Modifica",
	labelHelp: "Guida",
	labelCancel: "Annulla",
	labelImageTypeIcon: "Documento",
	errPrintBeforeLoading: "Per stampare, non è possibile utilizzare il menu del browser. Fare clic sul pulsante Stampa sulla barra degli strumenti per stampare il documento. Non è possibile stampare adesso perché il contenuto non è caricato completamente.",
	errPrintFromBrowserMenu: "Per stampare il documento, premere il pulsante Stampa sulla barra degli strumenti anziché utilizzare il menu Stampa del browser.",
	errPrintConversionFail: "Non è possibile stampare perché la conversione del file non è stata eseguita correttamente.",
	successMsg:"Esito positivo",
	warningMsg:"Avviso",
	errorMsg:"Errore",
	backtofiles:"Torna a File",
	openLatestFile: "Apri il file più recente",
	updatePresentation:"La presentazione è stata aggiornata.${0} per visualizzate tutto il testo e le immagini",
	updateNow: "Apri ora",
	fileUpdated: "La presentazione è stata aggiornata",
	fileUpdatedContent1: "La presentazione è stata aggiornata. Aprire il file più recente prima di stampare.",
	fileUpdatedContent2: "La presentazione è stata aggiornata. Aprire il file più recente prima di riprodurre la presentazione.",
	htmlviewerlimitation: "Questa presentazione contiene un'animazione che non è possibile visualizzare",
	labelStopReview: "Arresta revisione",
	labelRejct: "Rifiuta",
	labelApprove: "Approva",
	labelItemNotFountTitle: "Impossibile completare l'azione.",
	labelItemNotFountMsg: "Un altro componente della comunità ha già eseguito un'azione su questo documento. Per ulteriori informazioni, chiudere il documento e andare alla pagina Dettagli file nella propria libreria."
})

