({
	service_unavailable_title: "服务不可用。",
	service_unavailable_content: "${productName} 服务不可用，目前无法处理您的请求。请稍后重试，或联系您的系统管理员，以确保 ${productName} 服务联机。",
	access_denied_title: "拒绝访问。",
	viewaccess_denied_content: "您无权查看该文件。必须公开或与您共享该文件。",
	editaccess_denied_content: "您无权编辑此文件。此文件必须与您共享，或者您必须具有该文件的编辑者访问权。",
	doc_notfound_title: "${productName} 服务找不到此文件。",
	doc_notfound_content: "请与您的管理员联系，以确保正确设置 ${productName} 服务。",
	fullviewer_notsupport_title: "找不到文档",
	fullviewer_notsupport_content: "一个新的文件查看者将文档存储在另外一个 URL 中。要查看该文档，请在您的应用程序中找到该文件，并单击“预览”按钮。",
	fileconnect_denied_title: "连接被拒绝。",
	fileconnect_denied_content: "${productName} 无法连接到文件存储库。请稍后重试，或联系您的系统管理员。",
	convservice_unavailable_title: "转换服务不可用。",
	convservice_unavailable_content: "目前无法处理您的请求。请稍后重试，或联系您的系统管理员，以确保转换服务联机。",
	doc_toolarge_title: "文件过大。",
	doc_toolarge_content: "您要访问的文档过大。",
	doc_toolarge_content2: "文件无法访问，原因是：",
	doc_toolarge_content3: "文件无法显示，因为文件大小大于 ${0} KB。您可以下载文件进行查看。如果文件包含高分辨率图像，那么可以将它们替换为低分辨率图像以减小文件大小。",
	doc_toolarge_content4: "文件无法显示，原因是 ${0} 文件的大小大于 ${1} KB。",
	doc_toolarge_content5: "文件太大无法在这里查看，但是您仍然可以通过单击标题栏上的下载按钮打开。",
	edit_locked_file: "您无法编辑此文件，因为它已由其他编辑者锁定。",
	sheet_toolarge_content: "电子表格大小大于 ${0} KB。",
	sheet_toolarge_content2: "电子表格在一张工作表中包含的行数超过 ${0}。",
	sheet_toolarge_content5: "电子表格在一张工作表中包含的列数超过 ${0}。",
	sheet_toolarge_content3: "电子表格包含 ${0} 个以上的单元格。",
	sheet_toolarge_content4: "电子表格包含 ${0} 个以上的公式。",
	text_toolarge_content: "文档大小大于 ${0} KB。",
	text_toolarge_content2:"文档包含的页数超过 ${0}。",
	text_toolarge_content3:"文档的文本大小大于 ${0} KB。",
	pres_toolarge_content: "演示文稿的大小大于 ${0} KB。",
	pres_toolarge_content2: "演示文稿包含的页数超过 ${0}。",
	pres_toolarge_content3: "演示文稿包含的图形数超过 ${0}。",
	pdf_toolarge_content: "PDF 的大小大于 ${0} KB。",
	conversion_timeout_title: "文档转换超时。",
	conversion_timeout_content: "目前，文档转换耗时过长以致无法完成。请稍后重试。",
	invalid_docformat_title: "文档内容无效。",
	invalid_docformat_content: "文档的文件扩展名的格式有效，但文件内容不可访问。请确保文件无损坏。",
	invalid_doctype_title: "文档类型不受支持。",
	invalid_doctype_content: "${productName} 当前不支持此文档类型。",
	malformed_request_title: "URL 或参数不正确。",
	malformed_request_content: "确保 URL 和参数正确。",
	storageserver_error_title: "存储服务器不可用。",
	storageserver_error_content: "服务器当前不可用。目前无法处理您的请求。请稍后重试，或联系您的系统管理员，以确保存储服务联机。",
	incorrect_web_address_title:"Web 地址不正确。",
	incorrect_web_address_content:"Web 地址不正确。请输入 Web 地址，然后重试。",
	unexpecified_conversion_error_title:"未指定错误。",
	unexpecified_conversion_error_content:"服务器返回未指定的错误。",
	encrypted_conversion_error_title:"不支持 CryptoAPI RC4 加密文档。",
	encrypted_conversion_error_content:"此文件受密码保护。要在 ${productName} 中查看此文件，请先确保对此文件进行解密。",
	document_encrypt_title:"该文档已加密。",
	document_encrypt_content:"由于文件在上传至“文件”时已加密，因此无法联机查看该文件。",
	service_busy_title:"无法打开文档",
	service_busy_content:"您要查看的文件无法打开。服务器可能忙碌或不可用。请稍后重试或联系管理员。",
	empty_doc_title: "该文档是空文档。",
	empty_doc_content: "请确保文档包含内容，然后重试。",
	corrupted_doc_title: "无法打开该文件。",
	corrupted_doc_content: "该文件包含不受支持的内容（例如宏），因此无法在该应用程序中进行查看。",
	draft_storage_error_title: "无法打开文档。",
	draft_storage_error_content: "无法装入内容，因为内容已损坏。请与管理员联系以获取支持。",
	unexpected_code_title: "无法查看文档。",
	unexpected_code_content: "${docsProductName} 服务器可能已宕机。请稍后重试。",
	unpublished_document_title: "无法查看文件",
	unpublished_document_content: "无法查看此文件的发布版本。文件所有者必须首先发布该文件的版本，然后才能查看。",
	unscanned_document_title: "病毒扫描即将完成",
	unscanned_document_content: "自动扫描上传到 Connections 的文件。您可以在扫描完成时查看该文件。",
	malicious_document_title: "恶意文件",
	malicious_document_content: "您无法编辑此文件，因为 Connections 在对其进行扫描时检测到病毒。",		
	repository_out_of_space_title: "无足够空间",
	repository_out_of_space_content: "由于已达到文件大小配额，因此无法发布 ${0}。请将其他文件移至废纸篓并删除，以减少配额。",
	pdf_error_title:"无法打开该文件。",
	pdf_error_content:"PDF 文件可能已损坏。",
	problem_id_msg_title: "请将此问题报告给您的管理员。",
	problem_id_msg_show: "单击以显示详细信息",
	problem_id_msg_hide: "单击以隐藏"
})

