({
	labelNormal: "标准视图",
	labelPlay: "放映幻灯片",
	labelZoomIn: "放大",
	labelZoomOut: "缩小",
	labelFitWidth: "适合页宽",
	labelReset: "重置",
	lablePageUp: "上一页",
	lablePageDown: "下一页",
	labelPrint: "打印",
	labelBuild: "${productName} ${0}",
	labelVersion: "${productName} ${0} ${1}",
	msgLoading: "正在加载您的文档，请稍等。",
	msgConversionFail: "转换失败",
	labelReload: "重新加载",
	labelHelpContent:"帮助内容",
	labelAbout:"关于",
	labelProject:"${productName}",
	labelEdit: "编辑",
	labelHelp: "帮助",
	labelCancel: "取消",
	labelImageTypeIcon: "文档",
	errPrintBeforeLoading: "要进行打印，您不能使用浏览器中的菜单。请单击“打印”工具栏按钮以打印文档。您现在不能打印，因为内容尚未全部加载。",
	errPrintFromBrowserMenu: "要打印文档，请单击工具栏上的“打印”按钮，而不是浏览器中的“打印”菜单。",
	errPrintConversionFail: "由于无法成功转换内容，因此您无法打印。",
	successMsg:"成功",
	warningMsg:"警告",
	errorMsg:"错误",
	backtofiles:"返回到“文件”",
	openLatestFile: "打开最新文件",
	updatePresentation:"演示文稿已更新。${0} 以查看所有文本和图像",
	updateNow: "立即打开",
	fileUpdated: "演示文稿已更新",
	fileUpdatedContent1: "演示文稿已更新。先打开最新的文件，然后进行打印。",
	fileUpdatedContent2: "演示文稿已更新。先打开最新的文件，然后播放幻灯片。",
	htmlviewerlimitation: "该演示文稿包含无法显示的动画。",
	labelStopReview: "停止审阅",
	labelRejct: "拒绝",
	labelApprove: "批准",
	labelItemNotFountTitle: "无法完成操作。",
	labelItemNotFountMsg: "另一个社区成员已对此文档进行了操作。有关更多信息，请关闭文档，转至库中的“文件详细信息”页面。"
})

