({
	COLUMN: "Sütun",
	CLUSTERED_COLUMN: "Kümelenmiş Sütun",
	STACKED_COLUMN: "Yığınlanmış Sütun",
	BAR:"Çubuk",
	CLUSTERED_BAR:"Kümelenmiş Çubuk",
	STACKED_BAR: "Yığınlanmış Çubuk",
	PIE:"Pasta",
	SLICE: "Dilim",
	AREA: "Alan",
	STACKED_AREA: "Yığınlanmış Alan",
	LINE: "Çizgi",
	STACKED_LINE: "Yığınlanmış Çizgi",
	MAKER_LINE: "İşaretçileri Olan Çizgi",
	STACKED_MARKER_LINE: "İşaretçileri Olan Yığılmış Çizgi",
	SCATTER: "Dağılım",
	SCATTER_MARKER_ONLY: "Yalnızca İşaretçiler İçeren Dağılım",
	SCATTER_MARKER_LINE_S: "Yumuşak Çizgiler ve İşaretçiler İçeren Dağılım",
	SCATTER_LINE_S: "Yumuşak Çizgiler İçeren Dağılım", 
	SCATTER_MARKER_LINE_X: "Düz Çizgiler ve İşaretçiler İçeren Dağılım",
	SCATTER_LINE_X: "Düz Çizgiler İçeren Dağılım",
	ERROR_INVALID_RANGE:"Geçersiz veri aralığı",
	TOO_MANY_POINTS: "${0} veri noktasından fazlasını içeren bir grafik oluşturulamaz",
	CHART_TYPES:"Grafik Tipleri",
	DATA:"Veri",
	DATA_RANGE:"Veri Aralığı",
	IN_ROWS:"Satılar halindeki veri dizisi",
	IN_COLUMNS:"Sütunlar halindeki veri dizisi",
	AUTO:"Otomatik"
})
