({
	alt			: "Diğer metin:",
	width		: "Genişlik:",
	height		: "Yükseklik:",
	cmUnit   : "cm",
	ptUnit 	 : "pt",
	inchUnit : "inç",
	inUnit   : "in",
	mmUnit 	 : "mm",
	
	inputWarning: "Varsayılan birimle pozitif bir sayı girin. ",
	
	properties: "Özellikler",
	data: "Veri",
	chart: "Grafik",
	axis: "Eksen",
	series: "Dizi",
	font: "Yazı Tipi",
	title: "Başlık",
	legend: "Gösterge",
	placement: "Yerleşim",
	background: "Arka Plan",
	plotarea: "Çizim Alanı",
	line : "Satır",
	fill: "Doldur",
	border : "Kenarlık",
	labelfont: "Etiket",
	scale: "Ölçek",
	minimum: "En az",
	maximum: "En çok",
	majorunit: "Ana Birim",
	minorunit: "Alt Birim",
	smooth: "Düzgün",
	marker: "İşaretleyiciler",
	markerfill: "İşaretleyici",
	enterTitle: "Başlığı buraya girin",
	inputNumberWarning: "Bir sayı girin.",
	inputPosNumberWarning: "Pozitif bir sayı girin.",
	maxMinWarning: "Değer üst sınırı, değer alt sınırından büyük olmalı.",
	selectFontName: "Yazı Tipi Adını Seç",
	selectFontSize: "Yazı Tipi Boyutu Seç",
	setBold: "Kalın",
	setItalic: "İtalik",
	setFontColor: "Yazı Tipi Rengini Ayarla",
	setLegendPos: "Gösterge Yerleşimini Ayarla",
	setBackColor: "Grafik Arka Plan Rengini Ayarla",
	setBorderWidth: "Kenarlık Genişliğini Ayarla",
	setBorderColor: "Kenarlık Rengini Ayarla",
	setPlotAreaColor: "Çizim Alanı Rengini Ayarla",
	selectAxis: "Eksen Seç",
	setLineWidth: "Çizgi Genişliğini Ayarla",
	setLineColor: "Çizgi Rengini Ayarla",
	selectSeries: "Dizi Seç",
	setFillColor: "Dolgu Rengini Ayarla",
	setMarker: "İşaretleyicileri Ayarla",
	setSmooth: "Yumuşak Çizgiyi Ayarla",
	chartTitle: "Grafik Başlığı",
	axisTitle: "Eksen Başlığı",
	
	ERR1: "Bir dizinin büyük ayraç içine alınması gerekir.",
	ERR3: "Dize öğelerinin çift tırnak işareti içine alınması gerekir.",
	ERR4: "Yalnızca tek bir aralık girin.",
	ERR5: "Aralık var olmalıdır.",
	ERR6: "Tüm aralıkların aynı sayfada olması gerekir.",
	ERR7: "Tüm aralıkların tek bir satır ya da sütunda olması gerekir.",
	ERR9: "Bir dizi değeri gerekli.",
	
	n	: "Yok",
	l	: "Sol",
	r	: "Sağ",
	t	: "Üst",
	b   : "Alt",
	
	dataSeries:"Veri Dizisi",
	label:"Dizi Adı",
	xVal:"X Dizisi Değerleri",
	yVal:"Y Dizisi Değerleri",
	val:"Dizi Değerleri",
	cat:"Kategori",
		
	ltr: "Soldan Sağa",
	rtl: "Sağdan Sola",
	auto: "Bağlamsal",
	bidi_dir: "Yön",
	bidi_text_dir: "Metin Yönü"
})
