({
	COLUMN: "คอลัมน์",
	CLUSTERED_COLUMN: "คอลัมน์ที่คลัสเตอร์",
	STACKED_COLUMN: "คอลัมน์ที่สแต็ก",
	BAR:"แถบ",
	CLUSTERED_BAR:"แถบที่คลัสเตอร์",
	STACKED_BAR: "แถบที่สแต็ก",
	PIE:"แผนภูมิวงกลม",
	SLICE: "แผ่นบาง",
	AREA: "พื้นที่",
	STACKED_AREA: "พื้นที่ที่สแต็ก",
	LINE: "เส้น",
	STACKED_LINE: "เส้นที่สแต็ก",
	MAKER_LINE: "เส้นที่มีมาร์กเกอร์",
	STACKED_MARKER_LINE: "เส้นที่สแต็กซึ่งมีมาร์กเกอร์",
	SCATTER: "จุดกระจาย",
	SCATTER_MARKER_ONLY: "จุดกระจายที่มีมาร์กเกอร์เท่านั้น",
	SCATTER_MARKER_LINE_S: "จุดกระจายที่มีเส้นตรงและมาร์กเกอร์",
	SCATTER_LINE_S: "จุดกระจายที่มีเส้นตรง", 
	SCATTER_MARKER_LINE_X: "จุดกระจายที่มีเส้นตรงและมาร์กเกอร์",
	SCATTER_LINE_X: "จุดกระจายที่มีเส้นตรง",
	ERROR_INVALID_RANGE:"ช่วงข้อมูลไม่ถูกต้อง",
	TOO_MANY_POINTS: "ไม่สามารถสร้างแผนภูมิที่มีจุดข้อมูลมากกว่า ${0}",
	CHART_TYPES:"ชนิดแผนภูมิ",
	DATA:"ข้อมูล",
	DATA_RANGE:"ช่วงข้อมูล",
	IN_ROWS:"ชุดข้อมูลในแถว",
	IN_COLUMNS:"ชุดข้อมูลในคอลัมน์",
	AUTO:"แบบอัตโนมัติ"
})
