({
	stViewClient:"Εμφάνιση πελάτη Sametime",
	stChatList:"Πατήστε εδώ για να ανοίξετε το διαδικτυακό πελάτη Sametime σε ένα νέο παράθυρο.",
	stWebClient:"HCL Sametime ",
	stStatusMeeting:"Σε σύσκεψη",
	stStatusAvailable:"Είμαι διαθέσιμος",
	stViewBd:"Εμφάνιση λίστας φίλων του Sametime",
	stErrorSTServer:"Σφάλμα κατά τη σύνδεση με το Sametime",
	stStatusAway:"Απουσιάζω",
	stLConnLogIn:"Συνδεθείτε στο HCL Connections για να δείτε την κατάσταση Sametime",
	stActionBar:"Γραμμή ενεργειών του Sametime",
	stStatusBusy:"Απασχολημένος",
	stLogin:"Σύνδεση με το Sametime",
	stUserOffline:"Αποσυνδεδεμένος",
	stStartChat:"Πατήστε εδώ για να ξεκινήσετε μια συνομιλία",
	stLogout:"Αποσύνδεση από το Sametime",
	stDisconnect:"Αποσύνδεση από το Sametime",
	stViewSTActions:"Πατήστε για να δείτε τις ενέργειες Sametime",
	stError:"Παρουσιάστηκε σφάλμα. Η υπηρεσία Sametime δεν είναι διαθέσιμη.",
	stUnableToConnect:"Η σύνδεση με το Sametime δεν είναι διαθέσιμη. ",
	stConnect:"Σύνδεση με το Sametime",
	stNoStatuAvailable:"Δεν υπάρχουν πληροφορίες για την κατάσταση Sametime",
	stStatusdnt:"Δεν είμαι διαθέσιμος",
	stLoadingSTStatus:"Φόρτωση κατάστασης Sametime...",
	stShareAs:"Κοινή χρήση εγγράφου...",
	stShareDlgTitle:"Κοινή χρήση εγγράφου μέσω Sametime...",
	stShareDlgMsgTemplate:"Θέλετε να διαθέσετε το αρχείο '${file_name}' για κοινή χρήση στο χρήστη ${contact_name} με δικαίωμα πρόσβασης επιμελητή ή αναγνώστη;",
	stShareEditor:"Επιμελητής",
	stShareReader:"Αναγνώστης",
	stShareSuccessTemplate:"Αγαπητέ/ή ${contact_name}, θα ήθελα να σου διαθέσω το έγγραφο '${file_name}' για κοινή χρήση:\n<a href=\"${document_link}\">${document_link}</a>"
})
