/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2014. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        spreadsheetTemplates: "試算表範本",
        documentTemplates: "文件範本",
        titleShareDocument: "共用文件",
        offline: "離線",
        versionPublishing: "正在發佈版本。",
        versionPublishFailed: "未發佈版本。檔案可能太大，或伺服器可能逾時。請重試，或取消並要求您的管理者檢查伺服器日誌以識別問題。",
        versionCheckinFailed: "未移入此版本。檔案可能太大，或伺服器可能逾時。請重試，或取消並要求您的管理者檢查伺服器日誌以識別問題。",
        versionSavedFailed: "未順利完成儲存。請稍後重試儲存。",
        publishFileSizeExceedMsg: "無法發佈此檔案，因為檔案超出儲存庫管理者設定的大小上限。請刪除部分內容，使檔案變小，或者聯絡您的管理者以提高上限。",
        checkinFileSizeExceedMsg: "無法移入此檔案，因為檔案超出儲存庫管理者設定的大小上限。請刪除部分內容，使檔案變小，或者聯絡您的管理者以提高上限。",
        versionpublished: "${0} 已於${1} 發佈版本。",
        versionPublishing2: "正在儲存版本。",
        versionPublishFailed2: "未儲存版本。檔案可能太大，或伺服器可能逾時。請重試，或取消並要求您的管理者檢查伺服器日誌以識別問題。",      
        publishFileSizeExceedMsg2: "無法儲存此檔案，因為檔案超出儲存庫管理者設定的大小上限。請刪除部分內容，使檔案變小，或者聯絡您的管理者以提高上限。",
        versionpublished2: "${0} 已於${1} 儲存版本。",
        chekinCloseDocsMsg: "您現在可以關閉 ${productName}。",
        draftSavingAs: "正在複製檔案...",
        draftSavedAs: "新副本另存為 ${0}。",
        synchronizing: "請等待與伺服器的同步化作業完成。",
        synchronizeError: "無法完成與伺服器的同步化作業。",
        joinwithoutentitle: "使用者：${0} 想要編輯文件，但無法加入編輯階段作業，因為您不具共同編輯的資格。",
        joinwithoutentitle2: "使用者：${0} 想要編輯文件但無法加入編輯階段作業，因為他們不具共同編輯的資格。",
        backtoFiles: "開啟我的檔案",
        backtoCommFiles: "開啟社群檔案",
        backtoLibrary: "開啟檔案庫",
        backtoICN: "開啟 Content Navigator",
        backtoRepository: "開啟檔案清單",
        createNewSpred: "建立試算表",
        createNewDoc: "建立文件",
        createNewDocFromTemp: "從範本建立文件",
        shareDoc: "共用文件",
        exportPdf: "頁面設定",
        insertDate: "日期選擇",
        insertTime: "時間選擇",
        connect: "連接",
        theDoc: "文件",
        save: "儲存變更",
        saveBeforeReviewMsg: "您有未儲存的變更。儲存變更，然後再次提交審核。",
        submitReviewWidgetsFaiure: "未正確起始設定應用程式。請稍後重試提交審核。",
        widgetsFaiure: "未正確起始設定應用程式。",
        slideSorter: "投影片",
        commentsBar: "評論",
        draftBadge: "草稿",
        share: "共用",
        comment: "評論",
        showSidebar: "顯示資訊看板",
        publishVersion: "發佈",
        checkInVersion: "移入",
        saveVersion: "儲存",
        saved: "所有變更皆已儲存",
        saving: "正在儲存",
        submitFragment: "提交",
        aria_inMainMenu: "您現在位於主功能表",
        aria_inSlideSorter: "您現在位於投影片排序器視圖",
        aria_inSlideEditor: "您現在位於投影片編輯器視圖",
        createNewPres: "建立簡報",
        createNewAppFromTemp: "從範本建立文件",
        textdoc: "文字",
        sheetdoc: "試算表",
        presdoc: "簡報",
        saveAsTextErrMsg: "無法儲存新的文字文件。",
        saveAsPresErrMsg: "無法儲存新的簡報文件。",
        saveAsSheetErrMsg: "無法儲存新的試算表文件。",
        saveAsTextErrMsg1: "沒有足夠的空間來儲存文件。",
        saveAsPresErrMsg1: "沒有足夠的空間來儲存簡報。",
        saveAsSheetErrMsg1: "沒有足夠的空間來儲存試算表。",
        newDocTextErrMsg: "無法建立新的文字文件。",
        newDocSheetErrMsg: "無法建立新的試算表文件。",
        newDocPresErrMsg: "無法建立新的簡報文件。",
        newDocTextErrMsg2: "無法從範本建立新的文字文件。",
        newDocSheetErrMsg2: "無法從範本建立新的試算表文件。",
        newDocPresErrMsg2: "無法從範本建立新的簡報文件。",
        newDocTextErrMsg3: "沒有足夠的空間來建立文件。",
        newDocSheetErrMsg3: "沒有足夠的空間來建立試算表。",
        newDocPresErrMsg3: "沒有足夠的空間來建立簡報。",
        newDocTextErrMsg4: "已有文件使用此標題。請為此新文件提供一個不同的標題。",
        newDocSheetErrMsg4: "已有試算表使用此標題。請為此新試算表提供一個不同的標題。",
        newDocPresErrMsg4: "已有簡報使用此標題。請為此新簡報提供一個不同的標題。",        
        aclWarningTitle: "無法編輯新版本",
        aclWarningMsg: "因為檔案擁有者已設定此檔案中的受保護區域，所以最好線上進行編輯。如果真的需要上傳新的版本，請聯絡檔案擁有者 (${0})。",
        aclWarningMsgForOwner: "此檔案中有受保護的區域。因此您無法線上編輯上傳的新版本。您必須移除此檔案中所有受保護的區域，才可以開啟並編輯上傳的新版本。",
        st0: "工作表 1",
        st1: "工作表 2",
        st2: "工作表 3",
        FootnoteMsg: "頁",
        conflictMsg: "與其他編輯者正在變更的內容發生衝突。您的變更已取消。",
        undoRedoConflictMsg: "復原和重做作業已暫停，因為您正在編輯的內容和共同編輯的另一個人員正在處理的內容之間有衝突",
        bigFileErrMsg: "文件的大小太大。請重新整理瀏覽器，查看是否所有內容都是完整的",
        noPermissionMsg: "您沒有編輯這個檔案的許可權。請聯絡檔案的擁有者或取得編輯許可權，然後再試一次。",
        networkIssueMsg: "網路發生問題。",
        networkIssueTitle: "網路問題",
        networkIssueContent: "網路發生問題。請重新整理頁面，並嘗試再次連線。",
        lockEditorMsg: "必須連線至伺服器才能編輯文件。",
        offlineReasonMsg: "您的階段作業逾時。",
        offlineReasonForServerUnacceptedMsg: "無法處理您的部分動作。Docs 伺服器將捨棄 1 分鐘內的動作。",
        offlineReasonForServerDraftFormatChange: "由於伺服器升級導致您的文件格式已過期。",
        reloadExplanationMsg: "重新登入以繼續工作。",
        reloadBtnLabel: "重新載入",
        reconnectingMsg: "正在建立伺服器的連線，請稍候。",
        loadMsg: "正在載入文件，請稍候。",
        loadingDocumentMsg: "正在從伺服器載入文件，請稍候。",
        reLoadingDocumentMsg: "正在從伺服器重新載入文件，請稍候。",
        unsupportMsg: "偵測到不支援的功能。請參閱其他詳細資料。",
        browserWorkingMsg: "工作中...",
        fileDeepDetectTitle: "檔案格式與副檔名不符",
        fileDeepDetectMsg: "檔案格式與副檔名所表示的格式不同。請按一下「繼續」來編輯這種格式的檔案。",
        fileDeepDetectOkLabel: "繼續",
        tipInfo: "提示：${0}",
        selectTextInfo: "選取要套用樣式的文字。",
        removeRecentFile: "您要開啟的檔案已遭刪除。要從「最近的檔案」清單中移除該檔名嗎？",
        altLotusIcon: "",
        altErrorMsgIcon: "錯誤訊息",
        altWarningMsgIcon: "警告訊息",
        altSuccessMsgIcon: "成功訊息",
        sidebarLandmarkDesc: "資訊看板",
        footerTitle: "頁尾",
        mainDesc: "內容區",
        editLockedDocumentWarning: "其他人在編輯此檔案時，您鎖定了檔案。請與他們一起處理檔案以協調變更，或要求他們完成編輯，讓您擁有專用的編輯存取權。",
        observerMode: "您現在位於觀測器模式",
        editorMode: "您現在位於編輯器模式",
        maxEditorLimitReached: "文件已達到此階段作業的 ${0} 次編輯器數目上限。您可以在編輯者離開文件或切換至觀測器模式時，切換至編輯器模式。",
        maxEditorLimitReachedTitle: "已達到編輯器數目上限",
        uploadNewVersionOpenConfirm: "${0} 已在 ${2} ${1} 上傳了新版本。要開啟新版本嗎？", //${0} name, ${1} time, ${2} date
        uploadNewVersionPublishConfirm: "${0} 已在 ${2} ${1} 上傳了新版本。", //${0} name, ${1} time, ${2} date
        you: "您",
        today: "今天",
        yesterday: "昨天",
        slideShowInviteMsg: "使用者 ${0} 已起始共用投影片放映。您要加入嗎？",
        slideShowInviteTitle: "共用的投影片放映邀請",
        slideShowInviteTitle1: "集體的投影片放映邀請",
        slideShowCoviewSelectUsersTitle: "共用的投影片放映",
        slideShowCoviewSelectUsersTitle1: "集體的投影片放映",
        slideShowCoviewStmt: "在共用的投影片放映中共用簡報的現行狀態。",
        slideShowCoviewStmt1: "在集體的投影片放映中共用簡報的現行狀態。",
        slideShowCoviewOptionOne: "邀請所有編輯者加入投影片放映。",
        slideShowCoviewOptionOne1: "邀請所有編輯器和觀測者加入投影片放映。",
        slideShowCoviewOptionTwo: "僅邀請下列編輯者加入投影片放映。",
        slideShowCoviewOptionTwo1: "僅邀請下列編輯者和觀測者加入投影片放映。",
        slideShowCoviewSlidesOf: "投影片 ${1} 之 ${0}",  //as in Slide 1 of 4
        slideShowCoviewViewers: "${0} 個檢視器",
        slideShowCoviewDialogInput: "輸入以過濾名稱",
        slideShowCoviewAddTitle: "新增至共用的投影片放映",
        slideShowCoviewAddTitle1: "新增至集體的投影片放映",
        slideShowCoviewMessage: "選取其他要邀請至此共用投影片放映的使用者。",
        slideShowCoviewMessage1: "選取其他要邀請至此集體投影片放映的使用者。",
        slideShowCoviewEnded: "已結束共用的投影片放映",
        slideShowCoviewEndMessage: "您嘗試要加入的共用投影片放映已不再提供。",
        slideShowCoviewEndMessage2: "使用者 ${0} 已結束共用投影片放映。",
        slideShowWarning: "您必須關閉現行的投影片放映後，才能開始新的投影片放映。",
        slideShowHoverMsg: "按一下可查看其他正在檢視投影片放映的人。",
        slideShowHoverMsgAdd: "按一下可邀請更多檢視器。",
        csvEmpty: "無法匯出為 .csv 檔案，因為工作表中未包含資料。",
        edit: "編輯",
        printToPDF: "下載為 PDF",
        print: "列印",
        view: "檢視",
        openLatestFile: "開啟最新檔案",
        updateDocument: "文件已更新。${0}。",
        updateSpreadsheet: "試算表已更新。${0}",
        updatePresentation: "簡報已更新。${0}。",
        labelCancel: "取消",
        msgConversionFail: "轉換失敗",
        updateNow: "立即開啟",
        fileUpdated: "文件已更新",
        fileUpdatedContent1: "文件已更新。列印之前請開啟最新檔案。",
        htmlviewerlimitation1: "此試算表包含無法顯示的樞紐表。",
        htmlviewerlimitation2: "此試算表包含無法顯示的條件格式。",
        htmlviewerlimitation3: "此試算表包含無法顯示的樞紐表和條件格式。",
        close: "關閉",
        closeDocs: "關閉 ${productName}",
        endSessionDlgTitle: "編輯階段作業已結束",
        endSessionDlgNotice: "編輯階段作業已結束，因為 ${0} 已移入檔案。",
        labelStopReview: "停止審核",
        labelRejct: "拒絕",
        labelApprove: "核准",
        errorMsg: "錯誤",
        labelItemNotFountTitle: "無法完成動作。",
        labelItemNotFountMsg: "另一個社群成員已對此文件採取動作。如需相關資訊，請關閉文件，並跳至您檔案庫中的「檔案詳細資料」頁面。",
        viewProtectedAreas: "此試算表包含受保護區域。您應該僅能在線上進行檢視或編輯。",
        macroTitle: "檔案包含巨集", 
        macroDesc: "編輯此檔案可能會破壞巨集。要防止對包含巨集的範圍或工作表進行編輯，請使用「資料 > 受保護區域」。",
        problem_id_msg_title: "請向管理者報告此問題。",
        problem_id_msg_show: "按一下即可顯示詳細資料",
    	problem_id_msg_hide: "按一下即可隱藏",
    	uploadNewVersionWarningTitle: "無法編輯新版本",
        changeHistoryWarningMsg: "因為檔案擁有者已啟用此檔案的「追蹤變更」，所以最好線上進行編輯。如果真的需要上傳新的版本，請聯絡檔案擁有者 (${0})。",
        changeHistoryWarningMsgForOwner: "此檔案中有「變更歷程」。因此您無法線上編輯上傳的新版本。您必須清除此檔案中的「變更歷程」並停用「追蹤變更」，才可以開啟並編輯上傳的新版本。",
        viewChangeHistory: "此文件包含變更歷程。您應該僅能在線上進行檢視或編輯。",
    	contentCorruptErrMsg: "無法載入內容，因為它已毀損。請聯絡您的管理者以取得支援。"
});

