({
	delete_general: "Supprimer",
	order: "Ordre",
	align_text: "Aligner le texte",
	align_slide: "Aligner dans la diapositive",
	align_objects: "Aligner les objets sélectionnés",
	zoom: "Zoom",
	zoom_fit: "Ajuster à la fenêtre",
	insert_link: "Insérer un lien",
	add_link: "Ajouter un lien",
	open_link: "Ouvrir le lien",
	edit_link: "Editer le lien",
	remove_link: "Retirer le lien",
	insert_link_menu: "Lien",
	invalid_url: "Impossible d'ouvir l'URL. Vérifiez que l'URL est correcte ou contrôlez le paramètre de blocage des fenêtres en incrustation du navigateur.",
	dnd_canceled_on_slide_event: "La diapositive ne peut pas être déplacée car un autre éditeur a récemment modifié la présentation. Réessayez plus tard.",
	rotate: "Faire pivoter",
	flipX: "Inverser horizontalement",
	flipY: "Inverser verticalement",
	rotate_right: "Faire pivoter de 90&#x00B0 dans le sens horaire",
	rotate_left: "Faire pivoter de 90&#x00B0 dans le sens anti-horaire",
	color_set_fill: "Définir la couleur de remplissage",
	color_nofill: "Aucun remplissage",
	color_nobackground: "Aucun arrière-plan",
	color_auto: "Auto",
	color_default: "Valeur par défaut",
	color_transparent: "Transparent",
	
	objects_distribute: "Distribuer",
	objects_distribute_v: "Verticalement",
	objects_distribute_h: "Horizontalement",
	
	link_subject: "Sujet :",
	link_text: "Texte à afficher :",
	link_mailto: "Ouvrir l'e-mail",
	link_goto: "Ouvrir le lien",
	link_done: "Terminé",
	link_remove: "Retirer",
	link_website: "Site Web",
	link_email: "E-mail",
	link_slide: "Diapositive",
	link_slide_placeholder: "Sélectionnez ou entrez un numéro",
	link_slide_placeholder_deleted: "Diapositive liée supprimée",
	link_slide_next: "Diapositive suivante",
	link_slide_prev: "Diapositive précédente",
	link_slide_first: "Première diapositive",
	link_slide_last: "Dernière diapositive",
	link_slide_number: "Diapositive ${0}",
	link_not_support: "Type de lien non pris en charge",
	link_acc_input: "Entrez l'adresse du lien",
	link_acc_mail_input: "Entrez l'adresse de l'e-mail",
	

	// Jaws Support
	acc_blank: "vide",// when selection is nothing but space char and empty paragraph
	acc_selected: " sélectionné(e)",
	acc_showed: " affiché",
	acc_inTable: " dans la ligne de tableau ${0} la colonne ${1} ",
	acc_titleSelected: "titre sélectionné",
	acc_subtitleSelected: "sous-titre sélectionné",
	acc_outlineSelected: "contour sélectionné",
	acc_notesSelected: "notes de présentation sélectionnées",
	acc_imageSelected: "image sélectionnée",
	acc_shapeSelected: "forme sélectionnée",
	acc_rotated: " rotation d ${0} degrés",
	acc_tableSelected: "table sélectionnée",
	acc_textboxSelected: "zone de texte sélectionnée",
	acc_enterEdit: " appuyez sur Entrée pour éditer",
	acc_locked_by: " qui est verrouillé par l'utilisateur ${0}",
	acc_slide_used_by: " qui est utilisé par l'utilisateur ${0}",
	ACC_TABLE_TABLESIZE: "Vous avez sélectionné ${0} lignes, ${1} colonnes",
	ACC_TABLE_MAXSIZE: " La taille maximale de tableau prise en charge est de 8*8",
	ACC_EditorMode: "Mode d'édition de l'éditeur",
	ACC_EndEditorMode: "arrêter le mode d'édition de l'éditeur",
	ACC_Table_new_row: "Une nouvelle ligne est ajoutée",
	ACC_Table_new_column: "Une nouvelle colonne est ajoutée",
	Acc_column: "colonne ${0}",
	acc_slide: "diapositive ${0}",
	acc_editor: "Edition par ${0}",
	Plain: "Uni",
	BlueStyle: "Style de bleu",
	RedTint: "Ton rouge",
	BlueHeader: "En-tête bleu",
	DarkGrayHF: "En-tête/Pied de page gris foncé",
	LightGrayRows: "Lignes gris clair",
	DarkGrayRows: "Lignes gris foncé",
	BlueTint: "Ton bleu",
	RedHeader: "En-tête rouge",
	GreenHF: "En-tête/Pied de page vert",
	PlainRows: "Lignes unies",
	GrayTint: "Ton gris",
	GreenTint: "Ton vert",
	GreenHeader: "En-tête vert",
	RedHF: "En-tête/Pied de page rouge",
	GreenStyle: "Style vert",
	PurpleTint: "Ton violet",
	BlackHeader: "En-tête noir",
	PurpleHeader: "En-tête violet",
	LightBlueHF: "En-tête/Pied de page bleu clair",
	
    formatMenu_LineSpacing: "Interligne",
	linespaceboxTitle:"Espacement personnalisé",
	linespacelineTitle:"Ligne :",
	linespacenoticeContent :"Interligne",
    formatMenu_LineSpacing_Customize: "Personnalisé...",
    formatMenu_LineSpacing_CustomValue:"Personnalisé : ${0}",
    lineSpaceWarning:"Entrez un nombre compris entre 0 et 10",
    
    set_transparency_menu: "Opacité de l'image",
    opacity_percent_value: "${0}%",
    opacity_title: "Opacité",
    
    increaseLineWidthTip: "Augmenter l'épaisseur du trait",
	decreaseLineWidthTip : "Diminuer l'épaisseur du trait",
    setBorderStyleTip:"Définir le style de ligne",
    line_width_title: "Epaisseur du trait",
    line_end_title: "Extrémités de la ligne",
    line_dash_title: "Motif de ligne",
    line_dash_type1: "Pleine",
    line_dash_type2: "Carrés",
    line_dash_type3: "Tirets",
    line_dash_type4: "Points",
    line_dash_type5: "Tirets et points",
    line_dash_type6: "Longs tirets",
    line_endpoints_type1: "Sans",
    line_endpoints_type2: "Flèche vers la droite simple",
	line_endpoints_type3: "Flèche vers la gauche simple",
	line_endpoints_type4: "Flèche double simple",
	line_endpoints_type5: "Flèche vers la droite pleine",
	line_endpoints_type6: "Flèche vers la gauche pleine",
    line_endpoints_type7: "Flèche double pleine",
    line_endpoints_type8: "Flèche et cercle pleins",
	line_endpoints_type9: "Flèche et losange pleins",
	line_endpoints_type10: "Losanges pleins",
    line_endpoints_type11: "Cercles pleins"
})

