({
	COLUMN: "Oszlop",
	CLUSTERED_COLUMN: "Fürtözött oszlop",
	STACKED_COLUMN: "Halmozott oszlop",
	BAR:"Sáv",
	CLUSTERED_BAR:"Fürtözött sáv",
	STACKED_BAR: "Halmozott sáv",
	PIE:"Torta",
	SLICE: "Szelet",
	AREA: "Terület",
	STACKED_AREA: "Halmozott terület",
	LINE: "Vonal",
	STACKED_LINE: "Halmozott vonal",
	MAKER_LINE: "Vonal jelölőkkel",
	STACKED_MARKER_LINE: "Halmozott vonal jelölőkkel",
	SCATTER: "Szórás",
	SCATTER_MARKER_ONLY: "Szórásdiagram kizárólag jelölőkkel",
	SCATTER_MARKER_LINE_S: "Szórásdiagram törésmentes vonalakkal és jelölőkkel",
	SCATTER_LINE_S: "Szórásdiagram törésmentes vonalakkal", 
	SCATTER_MARKER_LINE_X: "Szórásdiagram egyenes vonalakkal és jelölőkkel",
	SCATTER_LINE_X: "Szórásdiagram egyenes vonalakkal",
	ERROR_INVALID_RANGE:"Érvénytelen adattartomány",
	TOO_MANY_POINTS: "Nem lehet ${0} adatpontnál többet tartalmazó diagramot létrehozni.",
	CHART_TYPES:"Diagramtípusok",
	DATA:"Adatok",
	DATA_RANGE:"Adattartomány",
	IN_ROWS:"Adatsor sorokban",
	IN_COLUMNS:"Adatsor oszlopokban",
	AUTO:"Automatikus"
})
