({
	COLUMN: "直條圖",
	CLUSTERED_COLUMN: "群組直條圖",
	STACKED_COLUMN: "堆疊直條圖",
	BAR:"橫條圖",
	CLUSTERED_BAR:"群組橫條圖",
	STACKED_BAR: "堆疊橫條圖",
	PIE:"圓餅圖",
	SLICE: "區塊",
	AREA: "區域圖",
	STACKED_AREA: "堆疊區域圖",
	LINE: "折線圖",
	STACKED_LINE: "堆疊折線圖",
	MAKER_LINE: "帶有標記的折線圖",
	STACKED_MARKER_LINE: "帶有資料標記的堆疊折線圖",
	SCATTER: "散佈圖",
	SCATTER_MARKER_ONLY: "帶有資料標記的散佈圖",
	SCATTER_MARKER_LINE_S: "帶有平滑線及資料標記的散佈圖",
	SCATTER_LINE_S: "帶有平滑線的散佈圖", 
	SCATTER_MARKER_LINE_X: "帶有直線及資料標記的散佈圖",
	SCATTER_LINE_X: "帶有直線的散佈圖",
	ERROR_INVALID_RANGE:"無效的資料範圍",
	TOO_MANY_POINTS: "無法建立資料點數大於 ${0} 的圖表",
	CHART_TYPES:"圖表類型",
	DATA:"資料",
	DATA_RANGE:"資料範圍",
	IN_ROWS:"列中的資料數列",
	IN_COLUMNS:"直欄中的資料數列",
	AUTO:"自動"
})
