({
	alt			: "替代文字：",
	width		: "寬度：",
	height		: "高度：",
	cmUnit   : "公分",
	ptUnit 	 : "pt",
	inchUnit : "英吋",
	inUnit   : "英吋",
	mmUnit 	 : "公釐",
	
	inputWarning: "以預設單位輸入正數。",
	
	properties: "內容",
	data: "資料",
	chart: "圖表",
	axis: "軸",
	series: "數列",
	font: "字型",
	title: "標題",
	legend: "圖註",
	placement: "位置",
	background: "背景",
	plotarea: "繪圖區",
	line : "線條",
	fill: "填入",
	border : "邊框",
	labelfont: "標籤",
	scale: "範圍",
	minimum: "下限",
	maximum: "上限",
	majorunit: "主要單位",
	minorunit: "次要單位",
	smooth: "平滑",
	marker: "標記",
	markerfill: "標記",
	enterTitle: "在這裡輸入標題",
	inputNumberWarning: "請輸入數字。",
	inputPosNumberWarning: "請輸入正數。",
	maxMinWarning: "上限值必須大於下限值",
	selectFontName: "選取字型名稱",
	selectFontSize: "選取字型大小",
	setBold: "粗體",
	setItalic: "斜體",
	setFontColor: "設定字型顏色",
	setLegendPos: "設定圖註位置",
	setBackColor: "設定圖表背景顏色",
	setBorderWidth: "設定邊框寬度",
	setBorderColor: "設定邊框顏色",
	setPlotAreaColor: "設定繪圖區顏色",
	selectAxis: "選取軸",
	setLineWidth: "設定線寬",
	setLineColor: "設定線條顏色",
	selectSeries: "選取數列",
	setFillColor: "設定填入顏色",
	setMarker: "設定標記",
	setSmooth: "設定平滑線條",
	chartTitle: "圖表標題",
	axisTitle: "軸標題",
	
	ERR1: "陣列必須用大括弧括住。",
	ERR3: "字串項目必須用雙引號括住。",
	ERR4: "僅能輸入一個範圍。",
	ERR5: "範圍必須存在。",
	ERR6: "所有範圍必須在相同的工作表中。",
	ERR7: "所有範圍必須針對單列或直欄。",
	ERR9: "需要數列值。",
	
	n	: "無",
	l	: "靠左",
	r	: "靠右",
	t	: "靠上",
	b   : "靠下",
	
	dataSeries:"資料數列",
	label:"數列名稱",
	xVal:"數列 X 值",
	yVal:"數列 Y 值",
	val:"數列值",
	cat:"種類",
		
	ltr: "從左到右",
	rtl: "從右到左",
	auto: "環境定義",
	bidi_dir: "方向",
	bidi_text_dir: "文字方向"
})
