({
	ORIENTATION_LABEL: "Tájolás",
	PORTRAIT: "Álló",
	LANDSCAPE: "Fekvő",
	HEADER: "Fejléc",
	FOOTER: "Lábléc",
	MARGINS_LABEL: "Margók",
	TOP: "Felső:",
	BOTTOM: "Alsó",
	LEFT: "Bal:",
	RIGHT: "Jobb:",
	PAPER_FORMAT_LABEL: "Papírformátum",
	PAPER_SIZE_LABEL: "Papírméret:",
	HEIGHT: "Magasság:",
	WIDTH: "Szélesség:",
	HEIGHT_DESC:"A papír magassága, centiméter",
	HEIGHT_DESC2:"A papír magassága, hüvelyk",
	WIDTH_DESC:"A papír szélessége, centiméter",
	WIDTH_DESC2:"A papír szélessége, hüvelyk",
	BOTTOM_DESC:"Alsó margó, centiméter",
	BOTTOM_DESC2:"Alsó margó, hüvelyk",
	TOP_DESC:"Felső margó, centiméter",
	TOP_DESC2:"Felső margó, hüvelyk",
	LEFT_DESC:"Bal margó, centiméter",
	LEFT_DESC2:"Bal margó, hüvelyk",
	RIGHT_DESC:"Jobb margó, centiméter",
	RIGHT_DESC2:"Jobb margó, hüvelyk",
	CM_LABEL: "cm",
	LETTER: "Letter",
	LEGAL: "Legal",
	TABLOID: "Tabloid",
	USER: "Egyéni",
	SIZE1: "Boríték, 6 3/4",
	SIZE2: "Boríték, Monarch",
	SIZE3: "Boríték, 9",
	SIZE4: "Boríték, 10",
	SIZE5: "Boríték, 11",
	SIZE6: "Boríték, 12",
	SIZE7: "16 kai",
	SIZE8: "32 kai",
	SIZE9: "32 kai nagy",
	INVALID_MSG: "A bemenet érvénytelen, és rendszer automatikusan kijavította. Ha más eredményt szeretne, adjon meg másik értéket."
})
	

