﻿/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        fileMenu: "Fichier",
        fileMenu_New: "Nouveau",
        fileMenu_NewDocument: "Document",
        fileMenu_NewFromTemplate: "A partir d'un modèle",
        fileMenu_NewDocumentfromTemplate: "Document à partir d'un modèle",
        fileMenu_NewPresentation: "Présentation",
        fileMenu_NewPresentationfromTemplate: "Présentation à partir d'un modèle",
        fileMenu_NewSpreadsheet: "Feuille de calcul",
        fileMenu_NewSpreadsheetFromTemplate: "Feuille de calcul à partir d'un modèle",
        fileMenu_Open: "Ouvrir",
        fileMenu_Import: "Importer...",
        //	fileMenu_Close: "Close",
        fileMenu_Discard: "Rétablir la version précédente",
        fileMenu_ClearTrackChange: "Retirer les marques de modification",
        fileMenu_SpreadsheetSettings: "Définir l'environnement local du document...",
        filemenu_revisionhistory: "Révisions",
        fileMenu_Save: "Enregistrer",
        fileMenu_SaveAs: "Copier...",
        fileMenu_AutoPublish: "Publier automatiquement",
        fileMenu_AutoCheckIn: "Restituer automatiquement",
        fileMenu_PublishVersion: "Publier maintenant",
        fileMenu_AutoPublish2: "Enregistrement auto dans le référentiel",
        //	fileMenu_AutoPublish_Tips: "Makes your changes available to readers at the end of each editing session.",
        fileMenu_PublishVersion2: "Enregistrer dans le référentiel maintenant",
        fileMenu_AutoPublish3: "Enregistrement auto dans ${0}",
        fileMenu_PublishVersion3: "Enregistrer dans ${0} maintenant",      
        fileMenu_SubmitForReview: "Soumettre pour révision...",
        fileMenu_CheckinVersion: "Restituer...",
        fileMenu_Unlock: "Déverrouiller",
        //	fileMenu_SaveAsDraft: "as Draft",
        //	fileMenu_SaveInMyDocs: "in My Documents",
        //	fileMenu_SaveToSymphony: "to Lotus Symphany",
        fileMenu_DownloadAs: "Télécharger comme",
        fileMenu_PDF: "PDF",
        fileMenu_ODF: "ODF",
        fileMenu_DOC: "Microsoft Word 97- 2007 (*.doc)",
        fileMenu_ODS: "ODS",
        fileMenu_XLS: "Microsoft Excel 97-2007 (*.xls) ",
        fileMenu_ShareWith: "Partager...",
        fileMenu_ExportAsPDF: "PDF",
        fileMenu_ExportAsODF: "ODF",
        fileMenu_ExportAsPPT: "Microsoft Powerpoint 97- 2007 (*.ppt)",
        //	fileMenu_WebPreview: "Web Preview",
        fileMenu_PrintToPDF: "Imprimer dans un PDF...",
        fileMenu_ViewFileDetails: "Afficher les détails du fichier...",
        fileMenu_RecentFile: "Fichiers récents",
        fileMenu_Open: "Ouvrir",
        fileMenu_Download: "Télécharger",
        fileMenu_Print: "Imprimer",
        fileMenu_Export: "Exporter",
        fileMenu_ExportToCSV: "CSV",
        fileMenu_ExportToPDF: "PDF (.pdf)",
        fileMenu_ExportToMarkdown: "Markdown (.md)",
        fileMenu_ExportToMS: "Format Microsoft Office (.${FILEEXTENSION})",
        fileMenu_ExportToODF: "Format Open Document (.${FILEEXTENSION})",
        fileMenu_PgSetup: "Mise en page...",

        editMenu: "Editer",
        editMenu_Undo: "Annuler",
        editMenu_Redo: "Rétablir",
        editMenu_Cut: "Couper",
        editMenu_Copy: "Copier",
        editMenu_Paste: "Coller",
        editMenu_DeleteSlide: "Supprimer une diapositive",
        editMenu_SelectAll: "Tout sélectionner",
        editMenu_Find: "Rechercher...",
        editMenu_Replace: "Remplacer...",
        editMenu_FindReplace: "Rechercher et remplacer...",
        editMenu_EditLink: "Ajouter ou éditer un lien",
        editMenu_DeleteSheet: "Supprimer la feuille...",
        editMenu_RenameSheet: "Renommer la feuille...",
        editMenu_HideSheet: "Masquer la feuille",
        editMenu_MoveSheet: "Déplacer la feuille...",
        editMenu_DeleteRow: "Supprimer la ligne",
        editMenu_DeleteColumn: "Supprimer la colonne",
        editMenu_DeleteCellLeft: "Supprimer les cellules et décaler vers la gauche",
        editMenu_DeleteCellUp: "Supprimer les cellules et décaler vers le haut",
        editMenu_ClearCell: "Supprimer le contenu",

        viewMenu: "Vue",
        viewMenu_Master: "Maître",
        viewMenu_Notifications: "Notifications",
        viewMenu_SlideSorter: "Sélecteur de diapositive",
        viewMenu_SpeakerNotes: "Notes de l'intervenant",
        viewMenu_Toolbar_Basic: "Standard",
        viewMenu_Toolbar_Advanced: "Avancée",
        viewMenu_Toolbar_None: "Sans",
        viewMenu_Toolbar: "Barre d'outils",
        viewMenu_Statusbar: "Barre d'état",
        viewMenu_Navigator: "Navigateur...",
        //viewMenu_Sidebar: "Sidebar",
        viewMenu_ShowHideIndicators: "Afficher les indicateurs de co-édition",
        viewMenu_Assignment: "Indicateurs d'affectation",
        viewMenu_Bookmark: "Signets",
        viewMenu_Coediting: "Mises en évidence des co-éditions",
        viewMenu_Rulers: "Règles",
        viewMenu_WebLayout: "Disposition Web",
        viewMenu_AutomaticSpellCheck: "Vérifier l'orthographe en cours de frappe",
        viewMenu_Formulabar: "Barre de formule",
        viewMenu_moveRight: "Entrée déplace le curseur vers la droite",
        viewMenu_showFullString: "Etendre le contenu dans les cellules",
        viewMenu_Doc: "Afficher le document",
        viewMenu_Templates: "Modèles",
        viewMenu_GridLines: "Masquer le quadrillage",
        viewMenu_UnsupportWarning: "Afficher les messages relatifs aux fonctions non prises en charge",
        viewMenu_HiddenSheets: "Feuilles masquées",
        viewMenu_FreezeRows: "Figer les lignes",
        viewMenu_FreezeColumns: "Figer les colonnes",
        viewMenu_NoFrozenRows: "Aucune ligne figée",
        viewmenu_NoFrozenColumns: "Aucune colonne figée",
        viewMenu_FreezeXRows: "Figer ${0} lignes",
        viewMenu_FreezeOneRow: "Figer ${0} ligne",
        viewMenu_FreezeXColumns: "Figer ${0} colonnes",
        viewMenu_FreezeOneColumn: "Figer ${0} colonne",
        viewMenu_CarriageReturn: "Marques de mise en forme",
        viewMenu_Navigation: "Panneau de navigation",
        viewMenu_ACL: "Zones modifiables",
        viewMenu_GridOnOff: "Quadrillage",
        viewMenu_ObserverMode: 'Mode Observateur',

        createMenu: "Insérer",
        createMenu_NewSlide: "Nouvelle diapositive",
        createMenu_DuplicateSlide: "Dupliquer la diapositive",
        createMenu_ImageFromFile: "Image...",
        createMenu_TextBox: "Zone de texte",
        createMenu_Shape: "Forme",
        createMenu_break: "Saut",
        createMenu_RowAbove: "Ligne au-dessus",
        createMenu_RowBelow: "Ligne au-dessous",
        createMenu_ColumnRight: "Colonne à droite",
        createMenu_ColumnLeft: "Colonne à gauche",
        createMenu_Sheet: "Feuille...",
        createMenu_Image: "Image...",
        createMenu_Comments: "Commentaire...",
        createMenu_WebLink: "Lien Web...",
        createMenu_SpecialCharacter: "Caractères spéciaux...",
        createMenu_Function: "Fonction...",
        createMenu_Fromtemplate: "Créer à partir d'un modèle",

        insertMenu: "Insérer",
        insertMenu_break: "Saut de page",
        insertMenu_sectionbreak: "Saut de section",
        insertMenu_Bookmark: "Signet...",
        insertMenu_WebLink: "Lien...",
        insertMenu_SpecialCharacter: "Caractères spéciaux...",
        insertMenu_HorizontalLine: "Ligne horizontale",
        insertMenu_Header: "En-tête",
        insertMenu_Footer: "Pied de page",
        insertMenu_TableOfContents: "Table des matières",

        insertMenu_HeaderFooter: "En-tête/pied de page",
        insertMenu_HF_Edit: "Editer",
        insertMenu_HF_Hide: "Masquer",
        insertMenu_Endnotes: "Notes de fin",
        insertMenu_RowAbove: "Ligne au-dessus",
        insertMenu_PageNumber: "Numéro de page",
        insertMenu_PageNumberTop: "Début de page",
        insertMenu_PageNumberBottom: "Fin de page",
        insertMenu_PageNumberCurr: "Position actuelle",
        insertMenu_TotalPageNumber: "Page 1/N",
        insertMenu_Date: "Date...",
        insertMenu_Time: "Heure...",
        insertMenu_Fields: "Zones",
        //    insertMenu_Comment: "Comment",
        insertMenu_CellRight: "Cellules et décalage vers la droite",
        insertMenu_CellDown: "Cellules et décalage vers le bas",
        insertMenu_RowBelow: "Ligne au-dessous",
        insertMenu_ColumnBefore: "Colonne avant",
        insertMenu_ColumnAfter: "Colonne après",
        insertMenu_Sheet: "Feuille...",
        insertMenu_Image: "Image...",
        insertMenu_DuplicateSheet: "Dupliquer la feuille",
        insertMenu_Function: "Fonction",
        insertMenu_FunctionSum: "SOMME",
        insertMenu_FunctionAverage: "MOYENNE",
        insertMenu_FunctionCount: "NB",
        insertMenu_FunctionMax: "MAX",
        insertMenu_FunctionMin: "MIN",
        insertMenu_FunctionMore: "Autres fonctions...",
        insertMenu_NameRange: "Plage nommée",
        insertMenu_NameRangeNew: "Nouvelle plage...",
        insertMenu_NameRangeManage: "Gérer les plages...",
        insertMenu_Chart: "Graphique...",

        contextMenu_insertCellRight: "Insérer des cellules et décaler vers la droite",
        contextMenu_insertCellDown: "Insérer des cellules et décaler vers le bas",
        contextMenu_InsertRowAbove: "Insérer une ligne au-dessus",
        contextMenu_InsertRowBelow: "Insérer une ligne au-dessous",
        contextMenu_InsertColumnBefore: "Insérer une colonne avant",
        contextMenu_InsertColumnAfter: "Insérer une colonne après",
        contextMenu_DownloadImage: "Télécharger en tant qu'image",

        formatMenu: "Format",
        formatMenu_Columns: "Colonnes",
        formatMenu_DefaultFormatting: "Mise en forme par défaut",
        formatMenu_Template: "Styles...",
        contextMenu_Template: "Styles de tableau...",
        formatMenu_LineSpacing: "Interligne",
        formatMenu_LineSpacing1: "1",
        formatMenu_LineSpacing12: "1,2",
        formatMenu_LineSpacing15: "1,5",
        formatMenu_LineSpacing2: "2",
        formatMenu_LineSpacing25: "2,5",
        formatMenu_LineSpacing3: "3",
        formatMenu_TextProperties: "Propriétés du texte",
        formatMenu_PageBreakBefore: "Saut de page avant",
        formatMenu_KeepLines: "Paragraphes solidaires",
        formatMenu_WidowControl: "Contrôle des veuves/orphelines",
        formatMenu_Pagination: "Propriétés de paragraphe",
        formatMenu_Bold: "Gras",
        formatMenu_Italic: "Italique",
        formatMenu_Underline: "Souligné",
        formatMenu_Strikethrough: "Barré",
        formatMenu_IncreaseSize: "Augmenter la taille de la police",
        formatMenu_DecreaseSize: "Diminuer la taille de la police",
        formatMenu_ImageProperties: "Propriétés de l'image...",
        formatMenu_ChartProperties: "Propriétés du graphique...",
        formatMenu_EditChart: "Editer un graphique",
        formatMenu_InsertChart: "Insérer un graphique",
        formatMenu_Properties: "Propriétés...",
        formatMenu_Heading: "Titre",
        formatMenu_Normal: "Normal",
        formatMenu_Title: "Titre",
        formatMenu_Subtitle: "Sous-titre",
        formatMenu_Heading1: "Titre 1",
        formatMenu_Heading2: "Titre 2",
        formatMenu_Heading3: "Titre 3",
        formatMenu_Heading4: "Titre 4",
        formatMenu_Heading5: "Titre 5",
        formatMenu_Heading6: "Titre 6",
        formatMenu_Heading7: "Titre 7",
        formatMenu_Heading8: "Titre 8",
        formatMenu_Heading9: "Titre 9",
        formatMenu_BulletedList: "Liste à puces",
        formatMenu_NumberedList: "Liste numérotée",
        formatMenu_OutLine: "Liste multi-niveaux",
        formatMenu_Superscript: "Exposant",
        formatMenu_Subscript: "Indice",
        formatMenu_Align: "Aligner",
        formatMenu_Left: "Gauche",
        formatMenu_Right: "Droite",
        formatMenu_Center: "Centrer",
        formatMenu_Justify: "Justifier",
        formatMenu_Text_Direction: "Orientation du texte",
        formatMenu_Ltr: "De gauche à droite",
        formatMenu_Rtl: "De droite à gauche",
        formatMenu_LineSpacing: "Interligne",
        formatMenu_LineSpacing1: "1",
        formatMenu_LineSpacing115: "1,15",
        formatMenu_LineSpacing15: "1,5",
        formatMenu_LineSpacing2: "2",
        formatMenu_LineSpacing25: "2,5",
        formatMenu_LineSpacing3: "3",
        formatMenu_Top: "Haut",
        formatMenu_Bottom: "Bas",
        formatMenu_Middle: "Milieu",
        formatMenu_Direction: "Orientation du texte",
        formatMenu_Rtl: "De droite à gauche",
        formatMenu_Ltr: "De gauche à droite",
        formatMenu_Auto: "Contextuel",
        formatMenu_SheetDirection: "Orientation de la feuille",
        formatMenu_SheetRtl: "De droite à gauche",
        formatMenu_SheetLtr: "De gauche à droite",
        formatMenu_Indent: "Augmenter le retrait",
        formatMenu_DecreaseIndent: "Réduire le retrait",
        formatMenu_ClearFormat: "Effacer la mise en forme",
        formatMenu_RowHeight: "Hauteur de ligne",
        formatMenu_ColumnWidth: "Largeur de colonne",
        formatMenu_ShowRow: "Afficher la ligne",
        formatMenu_HideRow: "Masquer la ligne",
        formatMenu_ShowColumn: "Afficher la colonne",
        formatMenu_HideColumn: "Masquer la colonne",
        formatMenu_WrapText: "Adapter le texte",
        formatMenu_Number: "Nombre",
        formatMenu_FontArial: "Arial",
        formatMenu_FontComicSansMS: "Comic Sans MS",
        formatMenu_FontCourierNew: "Courier New",
        formatMenu_FontGeorgia: "Georgia",
        formatMenu_FontLucidaSansUnicode: "Lucida Sans Unicode",
        formatMenu_FontTahoma: "Tahoma",
        formatMenu_FontTimesNewRoman: "Times New Roman",
        formatMenu_FontTrebuchetMS: "Trebuchet MS",
        formatMenu_FontVerdana: "Verdana",
        formatMenu_FontName: "Police",

        layoutMenu: "Disposition",
        layoutMenu_SlideLayout: "Mise en page de diapositive...",
        layoutMenu_SlideDesign: "Style maître...",
        layoutMenu_DefaultFormatting: "Mise en forme par défaut",
        layoutMenu_Textprop_Bold: "Gras",
        layoutMenu_Textprop_Italic: "Italique",
        layoutMenu_Textprop_Underline: "Souligné",
        layoutMenu_Textprop_Strikethrough: "Barré",
        layoutMenu_TextProp: "Propriétés du texte",
        LayoutMenu_RowHeight: "Hauteur de ligne...",
        LayoutMenu_ColumnWidth: "Largeur de colonne...",
        LayoutMenu_ShowRow: "Afficher la ligne",
        LayoutMenu_HideRow: "Masquer la ligne",
        LayoutMenu_RenameSheet: "Renommer la feuille...",
        LayoutMenu_MoveSheet: "Déplacer la feuille",

        tableMenu: "Tableau",
        tableMenu_Create: "Créer...",
        tableMenu_CreateFromTemplate: "Créer à partir d'un modèle",
        tableMenu_Delete: "Supprimer",
        tableMenu_SetTableColor: "Cellule de couleur",
        tableMenu_CreateTable: "Créer un tableau",
        tableMenu_Cell: "Cellule",
        tableMenu_CellMergeCells: "Fusionner les cellules",
        tableMenu_CellAlignLeft: "Aligner à gauche",
        tableMenu_CellAlignCenter: "Centrer",
        tableMenu_CellAlignRight: "Aligner à droite",
        tableMenu_CellClearContents: "Effacer le contenu",
        tableMenu_CellProperties: "Propriétés de la cellule...",
        tableMenu_Row: "Ligne",
        tableMenu_InsertRowAbove: "Insérer une ligne au-dessus",
        tableMenu_InsertRowBelow: "Insérer une ligne au-dessous",
        tableMenu_MoveRowAbove: "Déplacer la ligne vers le haut",
        tableMenu_MoveRowBelow: "Déplacer la ligne vers le bas",
        tableMenu_RowInsertRow: "Insérer une ligne...",
        tableMenu_RowInsertRowAbove: "Insérer une ligne au-dessus",
        tableMenu_RowInsertRowBelow: "Insérer une ligne au-dessous",
        tableMenu_RowMoveRowAbove: "Déplacer la ligne au-dessus",
        tableMenu_RowMoveRowBelow: "Déplacer la ligne au-dessous",
        tableMenu_RowDelete: "Supprimer",
        tableMenu_RowRepeat: "Répéter la ligne d'en-tête",
        tableMenu_InsertColumnBefore: "Insérer une colonne avant",
        tableMenu_InsertColumnAfter: "Insérer une colonne après",
        tableMenu_MoveColumnBefore: "Déplacer la colonne vers la gauche",
        tableMenu_MoveColumnAfter: "Déplacer la colonne vers la droite",
        tableMenu_ResizeColumn: "Redimensionner la colonne",
        tableMenu_ResizeColumns: "Redimensionner les colonnes",
        tableMenu_MarkasCategory: "Marquer comme catégorie",
        tableMenu_ColumnInsertColumn: "Insérer une colonne...",
        tableMenu_ColumnAddColumnBefore: "Insérer une colonne avant",
        tableMenu_ColumnAddColumnAfter: "Insérer une colonne après",
        tableMenu_ColumnMoveColumnAfter: "Déplacer la colonne après",
        tableMenu_ColumnMoveColumnBefore: "Déplacer la colonne avant",
        tableMenu_ColumnDelete: "Supprimer",
        tableMenu_ColumnSortAscending: "Tri croissant",
        tableMenu_ColumnSortDescending: "Tri décroissant",
        tableMenu_Column: "Colonne",
        tableMenu_Style: "Style",
        tableMenu_TableProperties: "Propriétés du tableau...",

        teamMenu: "Equipe",
        teamMenu_AddComment: "Ajouter un commentaire",
        teamMenu_AssignCells: "Affecter des cellules",
        teamMenu_AssignSection: "Affecter une section",
        teamMenu_EditAssignment: "Editer l'affectation",
        teamMenu_MarkSectionComplete: "Marquer la section comme terminée",
        teamMenu_MarkAssignmentComplete: "Marquer l'affectation comme terminée",
        teamMenu_WorkPrivatelyOnSection: "Travailler en privé sur la section",
        teamMenu_CancelPrivateWork: "Annuler les modifications privées",
        teamMenu_ApproveSection: "Approuver la section",
        teamMenu_ApproveAssignment: "Approuver l'affectation",
        teamMenu_ReturnSectionForRework: "Retourner la section pour transformation",
        teamMenu_ReturnAssignmentForRework: "Retourner l'affectation pour transformation",
        teamMenu_RemoveSectionAssignment: "Retirer l'affectation de la section",
        teamMenu_RemoveCellAssignment: "Retirer l'affectation de la cellule",
        teamMenu_RemoveCompletedAssignments: "Retirer les affectations terminées",
        teamMenu_AboutThisSection: "A propos de cette section",
        teamMenu_AboutAssignment: "A propos de cette affectation",

        presentationMenu: "Présentation",
        presentationMenu_SlideShow: "Lancer le diaporama",
        presentationMenu_SlideShowWithCoview: "Lancer un diaporama partagé",
        presentationMenu_SlideTransitions: "Appliquer une transition entre les diapositives...",
        presentationMenu_SlideShowFromCurrent: "Lancer depuis la diapositive actuelle",
        presentationMenu_EmptyCoviewInvites: "Aucun diaporama partagé actif",
        presentationMenu_CoviewInvites: "Diaporama partagé actif",

        dataMenu: "Données",
        dataMenu_Sort: "Trier...",
        dataMenu_SortAsc: "Tri croissant",
        dataMenu_SortDesc: "Tri décroissant",
        dataMenu_ACL: "Zones protégées",
        dataMenu_ACL_DELETE: "Supprimer tous les droits",
        dataMenu_Validity: "Validation des données",
        dataMenu_InstantFilter: "Filtre instantané",
        dataMenu_Validation: "Validation...",

        toolsMenu: "Outils",
        toolsMenu_AutoComplete: "Remplir automatiquement les entrées de cellule",
        toolsMenu_SelectDictionary: "Dictionnaires de vérification orthographique",
        toolsMenu_Dictionary_ca_CT: "Catalan",
        toolsMenu_Dictionary_cs_CZ: "Tchèque (République tchécoslovaque)",
        toolsMenu_Dictionary_da_DK: "Danois (Danemark)",
        toolsMenu_Dictionary_nl_NL: "Néerlandais (Pays-Bas)",
        toolsMenu_Dictionary_en_AU: "Anglais (Australie)",
        toolsMenu_Dictionary_en_GB: "Anglais (Grande-Bretagne)",
        toolsMenu_Dictionary_en_US: "Anglais (Etats-Unis)",
        toolsMenu_Dictionary_fi_FI: "Finnois (Finlande)",
        toolsMenu_Dictionary_fr_FR: "Français (France)",
        toolsMenu_Dictionary_fr_CA: "Français (Canada)",
        toolsMenu_Dictionary_de_DE: "Allemand (Allemagne)",
        toolsMenu_Dictionary_de_CH: "Allemand (Suisse)",
        toolsMenu_Dictionary_el_GR: "Grec (Grèce)",
        toolsMenu_Dictionary_it_IT: "Italien (Italie)",
        toolsMenu_Dictionary_pl_PL: "Polonais (Pologne)",
        toolsMenu_Dictionary_pt_BR: "Portugais (Brésil)",
        toolsMenu_Dictionary_pt_PT: "Portugais (Portugal)",
        toolsMenu_Dictionary_ru_RU: "Russe (Russie)",
        toolsMenu_Dictionary_es_ES: "Espagnol (Espagne)",
        toolsMenu_Dictionary_sv_SE: "Suédois (Suède)",
        toolsMenu_Dictionary_nb_NO: "Norvégien (Bokml)",
        toolsMenu_Dictionary_nn_NO: "Norvégien (Nynorsk)",
        toolsMenu_Dictionary_he_IL: "Hébreu (Israël)",
        toolsMenu_SpellCheck: "Lancer la vérification orthographique manuelle...",
        toolsMenu_Preferences: "Préférences",
        toolsMenu_Task: "Tâche",
        toolsMenu_Task_Assigntask: "Affecter une tâche",
        teamMenu_AssignSlide: "Affecter la diapositive",
        teamMenu_AssignSlides: "Affecter les diapositives",
        teamMenu_EditSlide: "Editer l'affectation de la diapositive",
        teamMenu_ReopenSlideAssignment: "Rouvrir l'affectation de la diapositive",
        teamMenu_ReopenSlideAssignments: "Rouvrir les affectations de la diapositive",
        teamMenu_ReassignSlide: "Réaffecter la diapositive",
        teamMenu_ReassignSlides: "Réaffecter les diapositives",
        teamMenu_MarkSlidesComplete: "Marquer la diapositive comme terminée",
        teamMenu_MarkSlidesCompletes: "Marquer les diapositives comme terminées",
        teamMenu_ApproveSlide: "Approuver la diapositive",
        teamMenu_ApproveSlides: "Approuver les diapositives",
        teamMenu_ReturnForRework: "Retourner la diapositive pour transformation",
        teamMenu_ReturnForReworks: "Retourner les diapositives pour transformation",
        teamMenu_RemoveAssignment: "Retirer l'affectation de la diapositive",
        teamMenu_AboutThisSlide: "A propos de cette diapositive",

        addOnsMenu: "Modules complémentaires",

        helpMenu: "Aide",
        helpMenu_About: "A propos",
        helpMenu_Overview: "Contenu de l'aide",
        helpMenu_NewFeatures: "Nouveautés",
        helpMenu_Tour: "Visite guidée",

        accel_fileMenu_Save: "Ctrl+S",
        accel_fileMenu_Save_Mac: "\u2318S",
        accel_fileMenu_Print: "Ctrl+P",
        accel_fileMenu_Print_Mac: "\u2318P",
        accel_editMenu_SelectAll: "Ctrl+A",
        accel_editMenu_SelectAll_Mac: "\u2318A",
        accel_editMenu_Undo: "Ctrl+Z",
        accel_editMenu_Undo_Mac: "\u2318Z",
        accel_editMenu_Redo: "Ctrl+Y",
        accel_editMenu_Redo_Mac: "\u2318Y",
        accel_editMenu_Cut: "Ctrl+X",
        accel_editMenu_Cut_Mac: "\u2318X",
        accel_editMenu_Copy: "Ctrl+C",
        accel_editMenu_Copy_Mac: "\u2318C",
        accel_editMenu_Paste: "Ctrl+V",
        accel_editMenu_Paste_Mac: "\u2318V",
        accel_editMenu_Find: "Ctrl+F",
        accel_editMenu_Find_Mac: "\u2318F",
        accel_insertMenu_Link: "Ctrl+K",
        accel_insertMenu_Link_Mac: "\u2318K",
        accel_insertMenu_Header: "Ctrl+Maj+H",
        accel_insertMenu_Header_Mac: "\u21e7\u2318H",
        accel_insertMenu_Footer: "Ctrl+Maj+F",
        accel_insertMenu_Footer_Mac: "\u21e7\u2318F",
        accel_formatMenu_Textprop_Bold: "Ctrl+B",
        accel_formatMenu_Textprop_Bold_Mac: "\u2318B",
        accel_formatMenu_Textprop_Italic: "Ctrl+I",
        accel_formatMenu_Textprop_Italic_Mac: "\u2318I",
        accel_formatMenu_Textprop_FormatPainter: "Ctrl+Maj+C, Ctrl+Maj+V",
        accel_formatMenu_Textprop_FormatPainter_Mac: "\u21e7\u2318C, \u21e7\u2318V",
        accel_formatMenu_Textprop_Underline: "Ctrl+U",
        accel_formatMenu_Textprop_Underline_Mac: "\u2318U",
        accel_formatMenu_Headingprop_P: "Ctrl+Maj+0",
        accel_formatMenu_Headingprop_H1: "Ctrl+Maj+1",
        accel_formatMenu_Headingprop_H2: "Ctrl+Maj+2",
        accel_formatMenu_Headingprop_H3: "Ctrl+Maj+3",
        accel_formatMenu_Headingprop_H4: "Ctrl+Maj+4",
        accel_formatMenu_Headingprop_H5: "Ctrl+Maj+5",
        accel_formatMenu_Headingprop_H6: "Ctrl+Maj+6",
        accel_formatMenu_Superscript: "Ctrl+.",
        accel_formatMenu_Superscript_Mac: "\u2318.",
        accel_formatMenu_Subscript: "Ctrl+,",
        accel_formatMenu_Subscript_Mac: "\u2318,",
        accel_formatMenu_Left: "Ctrl+Maj+L",
        accel_formatMenu_Left_Mac: "\u21e7\u2318L",
        accel_formatMenu_Right: "Ctrl+Maj+R",
        accel_formatMenu_Right_Mac: "\u21e7\u2318R",
        accel_formatMenu_Center: "Ctrl+Maj+E",
        accel_formatMenu_Center_Mac: "\u21e7\u2318E",
        accel_formatMenu_Justify: "Ctrl+Maj+J",
        accel_formatMenu_Justify_Mac: "\u21e7\u2318J",
        accel_formatMenu_Indent: "Ctrl+M",
        accel_formatMenu_Indent_Mac: "\u2318M",
        accel_formatMenu_DecreaseIndent: "Ctrl+Maj+M",
        accel_formatMenu_DecreaseIndent_Mac: "\u21e7\u2318M",
        accel_teamMenu_AddComment: "Maj+F2",

        ctxMenuSmartTable: 'Tableau',
        ctxMenuTableProperties: "Propriétés du tableau",
        ctxMenuDeleteST: 'Supprimer',
        ctxMenuDeleteSTTable: 'Supprimer le tableau',
        ctxMenuChgSTStyle: 'Changer de style',
        ctxMenuShowCaption: 'Afficher la légende',
        ctxMenuHideCaption: 'Masquer la légende',
        ctxMenuResizeST: 'Redimensionner',
        ctxMenuResizeColumnsST: 'Redimensionner les colonnes',
        ctxMenuSTRow: 'Ligne',
        ctxMenuAddSTRowAbv: 'Insérer une ligne au-dessus',
        ctxMenuAddSTRowBlw: 'Insérer une ligne au-dessous',
        ctxMenuMoveSTRowUp: 'Déplacer la ligne au-dessus',
        ctxMenuMoveSTRowDown: 'Déplacer la ligne au-dessous',
        ctxMenuDelSTRow: 'Supprimer',
        ctxMenuRepeatRow: 'Répéter la ligne d\'en-tête',
        ctxMenuSTCol: 'Colonne',
        ctxMenuAddSTColBfr: 'Insérer une colonne avant',
        ctxMenuAddSTColAft: 'Insérer une colonne après',
        ctxMenuMoveSTColBefore: 'Déplacer la colonne avant',
        ctxMenuMoveSTColAfter: 'Déplacer la colonne après',
        ctxMenuDelSTCol: 'Supprimer',
        ctxMenuSortSTColAsc: 'Tri croissant',
        ctxMenuSortSTColDesc: 'Tri décroissant',
        ctxMenuShowAllFacets: 'Afficher les catégories',
        ctxMenuHideAllFacets: 'Masquer les catégories',
        ctxMenuSTCell: 'Cellule',
        ctxMenuMergeCells: 'Fusionner les cellules',
        ctxMenuMergeDown: 'Fusionner avec la cellule au-dessous',
        ctxMenuVerSplit: 'Fractionner verticalement',
        ctxMenuHorSplit: 'Fractionner horizontalement',
        ctxMenuSplitCells: 'Fractionner les cellules...',
        splitCells: 'Fractionner la cellule',
        ctxMenuAlignTextLeft: 'Aligner à gauche',
        ctxMenuAlignTextCenter: 'Centrer',
        ctxMenuAlignTextRight: 'Aligner à droite',
        ctxMenuClearSTCellContent: 'Effacer le contenu',
        ctxMenuMakeHeaderRow: 'Utiliser la ligne sélectionnée comme en-tête',
        ctxMenuMakeNonHeaderRow: 'Supprimer le style de titre',
        ctxMenuMakeHeaderCol: 'Utiliser la colonne sélectionnée comme en-tête',
        ctxMenuMakeNonHeaderCol: 'Supprimer le style de titre',
        SHEET_CONTEXT_Hide: "Masquer", // hide row, column or sheet
        SHEET_CONTEXT_Show: "Afficher", // show row, column
        SHEET_CONTEXT_MoveSheet: "Déplacer...", // move sheet
        SHEET_CONTEXT_InsertSheet: "Insérer...", // insert sheet
        SHEET_CONTEXT_DeleteSheet: "Supprimer...", // delete sheet	
        SHEET_CONTEXT_DuplicateSheet: "Dupliquer...", // duplicate sheet
        SHEET_CONTEXT_RenameSheet: "Renommer...", // rename sheet
	
        ctxMenu_Image_WrapText: "Adapter le texte",
        ctxMenu_Image_WrapText_Inline: "Aligné sur le texte",
        ctxMenu_Image_WrapText_Square: "Carré",
        ctxMenu_Image_WrapText_TopBottom: "Haut et bas",
        ctxMenu_Image_WrapText_Behind: "Derrière le texte",
        ctxMenu_Image_WrapText_InFront: "Devant le texte",
        ctxMenu_Image_WrapText_Other: "Adapter encore le texte",
        ctxMenu_Image_WrapText_BothSides: "Des deux cotés",
        ctxMenu_Image_WrapText_LeftOnly: "Gauche uniquement",
        ctxMenu_Image_WrapText_RightOnly: "Droite uniquement",
        ctxMenu_Image_WrapText_LargestOnly: "Le plus grand uniquement",

        ctxMenu_Shape_AddText: "Ajouter du texte",

        ctxMenu_Range_ACL: "Protéger la plage",
        ctxMenu_Sheet_ACL: "Protéger la feuille",

        ctxMenu_HeaderFooter: "En-tête / Pied de page",
        ctxMenu_HeaderFooter_DiffFirst: "Première page uniquement",
        ctxMenu_HeaderFooter_DiffOddEven: "Pages paires et impaires différentes",
        ctxMenu_HeaderFooter_LinkToPre: "Lien à précédent",

        ctxMenu_copy: "Copier",
        ctxMenu_paste: "Coller",
        ctxMenu_delete: "Supprimer",
        ctxMenu_cut: "Couper",
        ctxMenu_select: "Sélectionner",
        ctxMenu_properties: "Propriétés",
        ctxMenu_bringToFront: "Au premier plan",
        ctxMenu_sendToBack: "A l'arrière-plan",
        ctxMenu_arrange: "Disposer",
        ctxMenu_sendBackward: "Vers l'arrière",
        ctxMenu_sendForward: "Vers l'avant",
        ctxMenu_fontStyle: "Style de police",
        ctxMenu_selectStyle: "Sélectionner le style",
        ctxMenu_fontSize: "Taille de la police",
        ctxMenu_fontFamily: "Famille de police",
        ctxMenu_bold: "Gras",
        ctxMenu_italic: "Italique",
        ctxMenu_u: "Souligné",
        ctxMenu_strike: "Barré",
        ctxMenu_super: "Exposant",
        ctxMenu_sub: "Indice",
        ctxMenu_color: "Couleur",
        ctxMenu_bgcolor: "Couleur d'arrière-plan",
        ctxMenu_highcolor: "Couleur de mise en évidence",
        ctxMenu_restart: "Redémarrer la liste",
        ctxMenu_continue: "Continuer la liste",
        ctxMenu_separate: "Séparer la liste",
        ctxMenu_join: "Joindre à la liste précédente",
        ctxMenu_setNumberVal: "Définir la valeur de numérotation...",
        webClipboardInfoTitle: "Presse-papiers",
        webClipboardInfoOKBtn: "OK",
        webClipboardInfoCutMsg: "Les paramètres de sécurité de votre navigateur empêchent la copie automatique. Utilisez la combinaison de touches Ctrl+X de votre clavier.",
        webClipboardInfoCopyMsg: "Les paramètres de sécurité de votre navigateur empêchent la copie automatique. Utilisez la combinaison de touches Ctrl+C de votre clavier.",
        webClipboardInfoPasteMsg: "Les paramètres de sécurité de votre navigateur empêchent cet éditeur d'accéder aux données du presse-papiers. Utilisez la combinaison de touches Ctrl+V de votre clavier.",

        clearTrackChangeConfirmMsg: "Tous les codes de couleur qui marquent les modifications apportées à ce document seront retirés définitivement. Voulez-vous poursuivre ?"
});

