({	
	createTaskSummary: "${0} 已建立作業。",
	completeTaskSummary: "${0} 已將作業標示為完成。",
	editTaskSummary5: "${0} 已編輯作業的 ${1}、${2}、${3}、${4} 及 ${5}。",
	editTaskSummary4: "${0} 已編輯作業的 ${1}、${2}、${3} 及 ${4}。",
	editTaskSummary3: "${0} 已編輯作業的 ${1}、${2} 及 ${3}。",
	editTaskSummary2: "${0} 已編輯作業的 ${1} 及 ${2}。",
	editTaskSummary1: "${0} 已編輯作業的 ${1}。",
	editTaskSummary0: "${0} 已編輯作業。",
	removeTaskSummary: "${0} 已移除作業。",
	reopenTaskSummary: "${0} 已重新開啟作業。",
	reassignTaskSummary: "${0} 已將 ${1} 從 ${2} 重新指派給 ${3}。",
	reassignTaskSummary2: "${0} 已將被指派者從 ${1} 重新指派給 ${2}，將檢閱人員從 ${3} 重新指派給 ${4}。",
	workPrivateSummary: "${0} 已開始私下處理此作業。",
	approveTaskSummary: "${0} 已核准此作業。",
	rejectTaskSummary: "${0} 已拒絕此作業。",
	rejectTaskSummary2: "${0} 將這項作業退回 ${1} 重做。",
	submitTaskSummary: "${0} 已將私人工作提交回文件。",
	cancelPrivateSummary: "${0} 已取消私人工作。",
	updatedFieldsDesc: "${0}: ${1} -> ${2}",
	fieldAssignee: "被指派者",
	fieldDuedate: "到期日",
	fieldDescription: "說明",
	fieldReviewer: "檢閱人員",
	fieldTitle: "標題",
	emptyFieldValue: "[未指派]",
	errorAddMember:"沒有活動伺服器的存取權，無法新增被指派者或檢閱人員。請稍後重試。",
	errorCreateActivity:"沒有活動伺服器的存取權，無法建立活動。請稍後重試。",
	errorLoadActivity:"沒有活動伺服器的存取權，無法載入指派。請稍後重試。",
	errorCreateAssignment: "沒有活動伺服器的存取權，無法建立指派。請稍後重試。",
	errorDeleteAssignment: "沒有活動伺服器的存取權，無法刪除指派。請稍後重試。",
	errorupdateAssignment: "沒有活動伺服器的存取權，無法更新指派。請稍後重試。",
	errorSubmitAssignment: "您不能執行這個動作。請查看您是否有許可權執行這個動作。",	
	errorAddMember2:"沒有伺服器的存取權，無法新增被指派者或檢閱人員。請稍後重試。",
	errorCreateActivity2:"沒有伺服器的存取權，無法建立活動。請稍後重試。",
	errorLoadActivity2:"沒有伺服器的存取權，無法載入指派。請稍後重試。",
	errorCreateAssignment2: "沒有伺服器的存取權，無法建立指派。請稍後重試。",
	errorDeleteAssignment2: "沒有伺服器的存取權，無法刪除指派。請稍後重試。",
	errorupdateAssignment2: "沒有伺服器的存取權，無法更新指派。請稍後重試。"	
})
