({	
	createTaskSummary: "${0} on luonut tehtävän.",
	completeTaskSummary: "${0} on merkinnyt tehtävän valmiiksi.",
	editTaskSummary5: "${0} on muokannut seuraavia tehtävän tietoja: ${1}, ${2}, ${3}, ${4} ja ${5}.",
	editTaskSummary4: "${0} on muokannut seuraavia tehtävän tietoja: ${1}, ${2}, ${3} ja ${4}.",
	editTaskSummary3: "${0} on muokannut seuraavia tehtävän tietoja: ${1}, ${2} ja ${3}.",
	editTaskSummary2: "${0} on muokannut seuraavia tehtävän tietoja: ${1} ja ${2}.",
	editTaskSummary1: "${0} on muokannut seuraavia tehtävän tietoja: ${1}.",
	editTaskSummary0: "${0} on muokannut tehtävää.",
	removeTaskSummary: "${0} on poistanut tehtävän.",
	reopenTaskSummary: "${0} on avannut tehtävän uudelleen.",
	reassignTaskSummary: "${0} osoitti tehtävän ${1} uudelleen käyttäjältä ${2} käyttäjälle ${3}.",
	reassignTaskSummary2: "${0} määritti toimeksiannon saajan ${1} tilalle toimeksiannon saajan ${2} ja tarkistajan ${3} tilalle tarkistajan ${4}.",
	workPrivateSummary: "${0} on aloittanut tehtävän yksityisen käsittelyn.",
	approveTaskSummary: "${0} on hyväksynyt tehtävän.",
	rejectTaskSummary: "${0} on hylännyt tehtävän.",
	rejectTaskSummary2: "${0} on palauttanut tämän tehtävän tekijälle ${1} tehtäväksi uudelleen.",
	submitTaskSummary: "${0} on lähettänyt yksityisessä käsittelyssä tehdyt muutokset takaisin asiakirjaan.",
	cancelPrivateSummary: "${0} on peruuttanut yksityisen käsittelyn.",
	updatedFieldsDesc: "${0}: ${1} -> ${2}",
	fieldAssignee: "asianosainen",
	fieldDuedate: "määräpäivä",
	fieldDescription: "kuvaus",
	fieldReviewer: "tarkistaja",
	fieldTitle: "otsikko",
	emptyFieldValue: "[Ei osoitettu]",
	errorAddMember:"Aktiviteettipalvelinta ei voi käyttää toimeksiannon saajien tai tarkistajien lisäykseen. Yritä myöhemmin uudelleen.",
	errorCreateActivity:"Aktiviteettipalvelinta ei voi käyttää aktiviteetin luontiin. Yritä myöhemmin uudelleen.",
	errorLoadActivity:"Aktiviteettipalvelinta ei voi käyttää toimeksiantojen lataukseen. Yritä myöhemmin uudelleen.",
	errorCreateAssignment: "Aktiviteettipalvelinta ei voi käyttää toimeksiannon luontiin. Yritä myöhemmin uudelleen.",
	errorDeleteAssignment: "Aktiviteettipalvelinta ei voi käyttää toimeksiantojen poistoon. Yritä myöhemmin uudelleen.",
	errorupdateAssignment: "Aktiviteettipalvelinta ei voi käyttää toimeksiantojen päivitykseen. Yritä myöhemmin uudelleen.",
	errorSubmitAssignment: "Toiminnon toteutus ei onnistu. Tarkista, onko sinulla siihen oikeuksia.",	
	errorAddMember2:"Palvelinta ei voi käyttää toimeksiannon saajien tai tarkistajien lisäykseen. Yritä myöhemmin uudelleen.",
	errorCreateActivity2:"Palvelinta ei voi käyttää aktiviteetin luontiin. Yritä myöhemmin uudelleen.",
	errorLoadActivity2:"Palvelinta ei voi käyttää toimeksiantojen lataukseen. Yritä myöhemmin uudelleen.",
	errorCreateAssignment2: "Palvelinta ei voi käyttää toimeksiannon luontiin. Yritä myöhemmin uudelleen.",
	errorDeleteAssignment2: "Palvelinta ei voi käyttää toimeksiantojen poistoon. Yritä myöhemmin uudelleen.",
	errorupdateAssignment2: "Palvelinta ei voi käyttää toimeksiantojen päivitykseen. Yritä myöhemmin uudelleen."	
})
