/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2014. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
	service_unavailable_title: "Usluga nije dostupna.",
	service_unavailable_content: "${productName} usluga nije dostupna. Vaš zahtjev ne može trenutno da se obradi. Pokušajte kasnije ili kontaktirajte vašeg sistem administratora.",
	access_denied_title: "Pristup zabranjen.",
	viewaccess_denied_content: "Nemate dozvolu za gledanje ove datoteke. Datoteka mora biti javna ili mora da se dijeli s vama.",
	editaccess_denied_content: "Niste ovlašteni za korištenje proizvoda ${productName} ili nemate dozvolu za uređivanje ove datoteke. Datoteka mora biti podijeljena s vama, a vi imati pravo uređivanja. Datoteku je možda zaključao drugi korisnik koji je uređuje.",
	doc_notfound_title: "Dokument nije pronađen.",
	doc_notfound_content: "Dokument kojem ste htjeli da pristupite je izbrisan ili premješten. Provjerite ispravnost linka.",
	repository_out_of_space_title: "Nema dovoljno prostora",
	repository_out_of_space_content: "Ne može se objaviti ${0} jer ste dosegli kvotu prostora za pohranu datoteka. Smanjite kvotu prenošenjem nekih datoteka u smeće i zatim ih izbrišite.",
	fileconnect_denied_title: "Veza je odbijena.",
	fileconnect_denied_content: "${productName} se ne može povezati sa repozitorijem datoteka. Pokušajte kasnije ili kontaktirajte vašeg sistem administratora.",
	convservice_unavailable_title: "Usluga konverzije nije dostupna.",
	convservice_unavailable_content: "${productName} usluga konverzije nije dostupna. Vaš zahtjev ne može trenutno da se obradi. Pokušajte kasnije ili kontaktirajte vašeg sistem administratora.",
	doc_toolarge_title: "Datoteka je prevelika.",
	doc_toolarge_content: "Dokument kojem želite pristupiti je prevelik.",
	doc_toolarge_content2: "Datoteci se ne može pristupiti. Mogući razlozi su:",
	doc_toolarge_content3: "Datoteci se ne može pristupiti, jer je datoteka veća od ${0} KB. Ako datoteka sadrži sliku visoke rezolucije, možete je zamijeniti sa slikom niže rezolucije da smanjite veličinu datoteke.",
	doc_toolarge_content_mobile: "Datoteka se ne može otvoriti. Veličina datoteke na prijienosnim uređajima ne može biti veća od ${0} KB.",
	sheet_toolarge_content: "Veličina proračunske tabele je veća od ${0} KB.",
	sheet_toolarge_content2: "Proračunska tabela sadrži više od ${0} redova na jednom listu.",
	sheet_toolarge_content5: "Proračunska tabela sadrži više od ${0} kolona na jednom listu.",
	sheet_toolarge_content3: "Proračunska tabela sadrži više od ${0} ćelija.",
	sheet_toolarge_content4: "Proračunska tabela sadrži više od ${0} formula.",
	text_toolarge_content: "Veličina dokumenta je veća od ${0} KB.",
	text_toolarge_content2:"Dokument sadrži više od ${0} strana.",
	text_toolarge_content3:"Veličina teksta u dokumentu je veća od ${0} KB.",
	pres_toolarge_content: "Prezentaciji se ne može pristupiti, jer je veličina prezentacije veća od ${0} KB. Ako prezentacija sadrži sliku visoke rezolucije, možete je zamijeniti slikom manje rezolucije da smanjite veličinu prezentacije.",
	pres_toolarge_content2: "Prezentaciji se ne može pristupiti jer sadrži više od ${0} stranica.",
	pres_toolarge_content3: "Prezentaciji se ne može pristupiti jer sadrži više od ${0} objekata.",
	pres_toolarge_content2_mobile: "Prezentacija se ne može otvoriti jer sadrži više od ${0} strana na prijenosnom uređaju.",
	pres_toolarge_content3_mobile: "Prezentacija se ne može otvoriti jer sadrži više od ${0} objekata na mobilnom uređaju.",
	sheet_view_toolarge_content1_mobile: "Proračunska tabela se ne može pregledati jer sadrži više od ${0} redova na prijenosnom uređaju.",
	sheet_view_toolarge_content2_mobile: "Proračunska tabela se ne može pegledati jer sadrži više od ${0} kolona na prijenosnom uređaju.",
	sheet_view_toolarge_content3_mobile: "Proračunska tabela se ne može pregledati jer sadrži više od ${0} redova i ${1} kolona na prijenosnom uređaju.",
	conversion_timeout_title: "Konverzija dokumenta je prekoračila vrijeme.",
	conversion_timeout_content: "Trenutno, predugo traje konverzija dokumenta. Pokušajte ponovno kasnije.",
	invalid_docformat_title: "Dokument se ne može otvoriti",
	invalid_docformat_content: "Ekstenzija dokumenta je važeća, ali sadržaj se ne može čitati jer je pokvaren ili šifrovan.",
	template_extension_conent_mismatch: "Ekstenzija izvorne datoteke pogrešno je označava kao uzorak. Datoteka je zapravo u formatu .${0}. Upotrijebite važeći uzorak ili spremite ovu datoteku s drugačijim nazivom, koristeći .${0} kao ekstenziju.",
	invalid_docformat_title2: "Datoteka se ne može importovati u ${productName}.",
	invalid_docformat_content2: "U ovoj datoteci nalazi se nešto što ${productName} trenutno ne podržava. Ova datoteka ne može da se importira.",
	invalid_doctype_title: "Tip dokumenta nije podržan.",
	invalid_doctype_content: "${productName} trenutno ne podržava ovaj tip dokumenta.",
	unsupported_browser_title: "Vaš pretraživač ne podržava sve funkcije",
	malformed_request_title: "Zahtjev je pogrešno formiran.",
	malformed_request_content: "Osigurajte da su URL i parametri ispravni.",
	storageserver_error_title: "Server za pohranu podataka nije raspoloživ.",
	storageserver_error_content: "Server je trenutno nedostupan. Vaš zahtjev ne može trenutno da se obradi. Pokušajte kasnije ili kontaktirajte vašeg sistem administratora.",
	document_already_opened_title: "Dokument je već otvoren",
	document_already_opened_content:"Ovaj dokument je već otvoren u vašem pretraživaču.",
	toomany_documents_opened_inone_browser_title: "Dokument se ne može otvoriti",
	toomany_documents_opened_inone_browser_content:"Samo pet ${productName} datoteka može biti otvoremeno istovremeno. Zatvorite druge dokumente i pokušajte ponovo otvoriti ovaj dokument.",
	document_max_session_exceeded_title:"Usluga nije dostupna.",
	document_max_session_exceeded_content:"Previše korisnika uređuje dokumente na serveru, ne može se nastaviti s vašim zahtjevom. Pokušajte ponovno kasnije.",
	kickout_user_content: "Ovaj dokument već je otvoren u drugom prozoru na vašem računaru. Vratite se na drugi prozor, ako želite da  nastavite s uređivanjem dokumenta.",
	return_to_files: "Vratite se u Datoteke",
	return_to_library: "Povratak u Biblioteku",
	return_to_icn: "Povratak u Content Navigator",
	document_already_open: "Dokument je već otvoren",
	cannotedit_noentitled_title: "Ne možete zajednički uređivati ovu datoteku",
	cannotedit_noentitled_content1: "Sljedeći korisnici sada uređuju datoteku:",
	cannotedit_noentitled_content2: "Niste ovlašteni uređivati ovu datoteku dok je drugi uređuju. Pokušajte uređivanje ove datoteke kasnije.",
	cannotedit_noentitled_content3: "Sljedeći korisnik trenutno uređuje datoteku:",
	cannotedit_noentitled_content4: "Ne možete se pridružiti ovoj sesiji za uređivanje, jer korisnik koji uređuje nije ovlašten za zajedničko uređivanje. Pokušajte uređivanje ove datoteke kasnije.",
	toomany_coeditors_title: "Previše korisnika",
	toomany_coeditors_content: "Previše korisnika trenutno uređuje ovaj dokument, samo {0} korisnika može da radi u isto vrijeme  na dokumentu.",
	encrypted_pptdoc_title:"Šifrovani dokument nije podržan.",
	encrypted_pptdoc_content:"Datoteka je zaštićena lozinkom. Da biste otvorili datoteku u ${productName}, prvo morate dešifrovati datoteku.",
	server_busy_title:"Server je zauzet",
	server_busy_content:"Pričekajte malo i pokušajte ponovo kasnije.",
	document_encrypt_title:"Šifrovani dokument nije podržan",
	document_encrypt_content:"Ova datoteka je šifrovana u repozitoriju datoteka. ${productName}  ne može je direktno uređivati iz sigurnosnih razloga.",
	edit_locked_file: "Ne možete da uređivati ovu datoteku jer ju je zaključao drugi korisnik koji je uređuje.",
	publish_locked_file: "Ne možete objaviti ovu datoteku kao novu verziju jer je zaključana, ali je sadržaj automatski spremljen kao skica.",
	join_locked_file_session: "Ne možete se pridružiti sesiji zajedničkog uređivanja jer su drugi zaključali datoteku.",
	no_need_to_convert_title:"Nije potrebna konverzija",
	no_need_to_convert_content:"Format datoteke koju želite konvertirati je upravo onakav kakav želite. Molim preuzmite je direktno.",
	warning_icon: "Ikona upozorenja",
	//html viewer error message
	incorrect_web_address_title:"Pogrešna web adresa.",
	incorrect_web_address_content:"Web adresa nije ispravna.  Unesite web adresu i pokušajte ponovo.",
	unexpecified_conversion_error_title:"Greška nije određena.",
	unexpecified_conversion_error_content:"Server je vratio grešku koja nije određena.",
	encrypted_conversion_error_title:"Šifrovani dokument nije podržan.",
	encrypted_conversion_error_content:"Datoteka je zaštićena lozinkom. Da biste mogli pregledati datoteku u pregledniku, prvo treba da je dešifrujete.",
	service_busy_title:"Neuspješno otvaranje dokumenta",
	service_busy_content:"Datoteka koju želite pregledati se ne može otvoriti. Server je možda zauzet ili nije dostupan. Pokušajte kasnije ili kontaktirajte administratora.",
	empty_doc_title: "Dokument je prazan.",
	empty_doc_content: "Provjerite nalazi li se u dokumentu sadržaj i pokušajte ponovo.",
	corrupted_doc_title: "Datoteka se ne može otvoriti.",
	corrupted_doc_content: "Datoteka sadrži nepodržani sadržaj, na primjer makronaredbe, pa se ne može pregledati u ovoj aplikaciji.",
	unexpected_code_title: "${productName} server vraća neočekivani kod.",
	unexpected_code_content: "${productName} server vraća neočekivani kod."
})

