({
	ORIENTATION_LABEL: "Orientare",
	PORTRAIT: "Portret",
	LANDSCAPE: "Peisaj",
	HEADER: "Antet",
	FOOTER: "Subsol",
	MARGINS_LABEL: "Margini",
	TOP: "Sus:",
	BOTTOM: "Jos:",
	LEFT: "Stânga:",
	RIGHT: "Dreapta:",
	PAPER_FORMAT_LABEL: "Formatul hârtiei",
	PAPER_SIZE_LABEL: "Dimensiunea hârtiei:",
	HEIGHT: "Înălţime:",
	WIDTH: "Lăţime:",
	HEIGHT_DESC:"Înălţime hârtie, în centimetri",
	HEIGHT_DESC2:"Înălţime hârtie, în inch",
	WIDTH_DESC:"Lăţime hârtie, în centimetri",
	WIDTH_DESC2:"Lăţime hârtie, în inch",
	BOTTOM_DESC:"Marginea de jos, în centimetri",
	BOTTOM_DESC2:"Marginea de jos, în inch",
	TOP_DESC:"Marginea de sus, în centimetri",
	TOP_DESC2:"Marginea de sus, în inch",
	LEFT_DESC:"Marginea din stânga, în centimetri",
	LEFT_DESC2:"Marginea din stânga, în inch",
	RIGHT_DESC:"Marginea din dreapta, în centimetri",
	RIGHT_DESC2:"Marginea din dreapta, în inch",
	CM_LABEL: "cm",
	LETTER: "Scrisoare",
	LEGAL: "Legal",
	TABLOID: "Tabloid",
	USER: "Utilizator",
	SIZE1: "Env. #6 3/4",
	SIZE2: "Env. Monarch",
	SIZE3: "Env. #9",
	SIZE4: "Env. #10",
	SIZE5: "Env. #11",
	SIZE6: "Env. #12",
	SIZE7: "16 kai",
	SIZE8: "32 kai",
	SIZE9: "32 kai large",
	INVALID_MSG: "Intrarea este invalidă şi a fost rectificată automat. Încercaţi altă valoare dacă vreţi un rezultat diferit."
})
	

