({
	labelPrintConfig: "En iyi yazdırma sonuçlarını almak için, tarayıcınızın sayfa ayarlarını aşağıdaki yapılandırmayı kullanacak şekilde ayarlayın:",
	labelConfigPageSize: "Sayfa boyutu: ${0}",
	labelConfigOrientation: "Yön: ${0}",
	labelConfigHeader: "Üstbilgi: boş",
	labelConfigFooter: "Altbilgi: boş",
	labelConfigMargins: "Kenar boşlukları: ",
	labelConfigMarginTop: "Üst: ${0}${1}",
	labelConfigMarginBottom: "Alt: ${0}${1}",
	labelConfigMarginLeft: "Sol: ${0}${1}",
	labelConfigMarginRight: "Sağ: ${0}${1}",
	labelPrintContinue: "Tarayıcı ayarlarını belirledikten sonra, dosyanızı yazdırmaya devam etmek için Tamam düğmesini tıklatın. ",
	labelMm: "milimetre",
	labelInch: "inç",
	labelPortrait: "Dikey",
	labelPageA4: "A4",
	labelLetter: "Mektup",
	labelLandscape: "Yatat",
	titlePrintConfig: "Yazdırma Ayarları",
	titlePrepare: "Yazdırmaya Hazırlanıyor",
	msgPrepare: "Dosya yazdırılmak üzere hazırlanıyor. Hazırlık uzun sürebilir.",
	errPrepare: "Veriler hazırlanırken bir hata oluştu. \nYeniden denemek ister misiniz?",
	titleErr: "Hata",
	btnRetry: "Yeniden dene"
})
