/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
    Arrow01_Gray: "Strelica 01 siva",
    Arrow02_Gray: "Strelica 02 siva",
    Arrow03_Red: "Strelica 03 crvena",
    Arrow04_Blue: "Strelica 04 plava",
    Arrow05_Blue: "Strelica 05 plava",
    Arrow06_Yellow: "Strelica 06 žuta",
    Arrow07_Red: "Strelica 07 crvena",
    Arrow08_Gray: "Strelica 08 siva",
    Arrow09_Orange: "Strelica 09 narančasta",
    Arrow10_Blue: "Strelica 10 plava",
    Arrow11_Blue: "Strelica 11 plava",
    Arrow12_Green: "Strelica 12 zelena",
    Arrow13_Blue: "Strelica 13 plava",
    Arrow14_Green: "Strelica 14 zelena",
    Arrow15_Orange: "Strelica 15 narančasta",
    Arrow16_Gray: "Strelica 16 siva",
    CircleArrow01_Green: "Kružna strelica 01 zelena",
    CircleArrow02_Multi: "Kružna strelica 02 višestruka",
    CircleArrow03_Multi: "Kružna strelica 03 višestruka",
    CircleArrow04_Multi: "Kružna strelica 04 višestruka",
    CircleArrow05_Multi: "Kružna strelica 05 višestruka",
    CircleArrow06_Multi: "Kružna strelica 06 višestruka",
    CircleArrow07_Blue: "Kružna strelica 07 plava",
    CircleArrow08_Green: "Kružna strelica 08 zelena",
    CircleArrow09_Multi: "Kružna strelica 09 višestruka",
    CurvedArrow01_Gray: "Zakrivljena strelica 01 siva",
    CurvedArrow02_Blue: "Zakrivljena strelica 02 plava",
    CurvedArrow03_Blue: "Zakrivljena strelica 03 plava",
    CurvedArrow04_Orange: "Zakrivljena strelica 04 narančasta",
    CurvedArrow05_Red: "Zakrivljena strelica 05 crvena",
    CurvedArrow06_Blue: "Zakrivljena strelica 06 plava",
    CurvedArrow07_Purple: "Zakrivljena strelica 07 purpurna",
    CurvedArrow08_Green: "Zakrivljena strelica 08 zelena",
    CurvedArrow09_Gray: "Zakrivljena strelica 09 siva",
    CurvedArrow10_Blue: "Zakrivljena strelica 10 plava",
    CurvedArrow11_Orange: "Zakrivljena strelica 11 narančasta",
    CurvedArrow12_Blue: "Zakrivljena strelica 12 plava",
    CurvedArrow13_Green: "Zakrivljena strelica 13 zelena",
    CurvedArrow14_Brown: "Zakrivljena strelica 14 smeđa",
    CurvedArrow15_Blue: "Zakrivljena strelica 15 plava",
    CurvedArrow16_Gray: "Zakrivljena strelica 16 siva",
    CurvedArrow17_Gray: "Zakrivljena strelica 17 siva",
    CurvedArrow18_Gray: "Zakrivljena strelica 18 siva",
    CurvedArrow19_Gray: "Zakrivljena strelica 19 siva",
    CurvedArrow20_Gray: "Zakrivljena strelica 20 siva",
    TrendArrow01_Red: "Trend strelica 01 crvena",
    TrendArrow02_Green: "Trend strelica 02 zelena",
    TrendArrow03_Orange: "Trend strelica 03 narančasta",
    TrendArrow04_Red: "Trend strelica 04 crvena",
    TrendArrow05_Orange: "Trend strelica 05 narančasta",
    TrendArrow06_Blue: "Trend strelica 06 plava",
    TrendArrow07_Orange: "Trend strelica 07 narančasta",
    TrendArrow08_Yellow: "Trend strelica 08 žuta",
    TrendArrow09_Blue: "Trend strelica 09 plava",
    TrendArrow10_Blue: "Trend strelica 10 plava",
    TrendArrow11_Blue: "Trend strelica 11 plava",
    TrendArrow12_Blue: "Trend strelica 12 plava",
    TrendArrow13_Red: "Trend strelica 13 crvena",
    TrendArrow14_Multi: "Trend strelica 14 višestruka",
    TrendArrow15_Blue: "Trend strelica 15 plava",
    Bullet01_Circle_DarkRed: "Oznaka 01 krug tamnocrveni",
    Bullet02_Circle_Blue: "Oznaka 02 krug plavi",
    Bullet03_Circle_Green: "Oznaka 03 krug zeleni",
    Bullet04_Square_Black: "Oznaka 04 kvadrat crni",
    Bullet05_Square_Orange: "Oznaka 05 kvadrat narančasti",
    Bullet06_Square_Purple: "Oznaka 06 kvadrat purpurni",
    Bullet07_Diamond_Blue: "Oznaka 07 dijamant plavi",
    Bullet08_Diamond_LightBlue: "Oznaka 08 dijamant svijetloplavi",
    Bullet09_Diamond_Red: "Oznaka 09 dijamant crvena",
    Bullet10_Star_Yellow: "Oznaka 10 zvijezda žuta",
    Bullet11_Star_Blue: "Oznaka 11 zvijezda plava",
    Bullet12_Triangle_Blue: "Oznaka 12 trokut plavi",
    Bullet13_Triangle_DarkGreen: "Oznaka 13 trokut tamnozeleni",
    Bullet14_Arrow_Red: "Oznaka 14 strelica crvena",
    Bullet15_Arrow_Blue: "Oznaka 15 strelica plava",
    Bullet16_Box_Blue: "Oznaka 16 okvir plavi",
    Bullet17_Box_Red: "Oznaka 17 okvir crveni",
    Bullet18_Asterisk_LightBlue: "Oznaka 18 zvjezdica svijetloplava",
    Bullet19_Leaves_Red: "Oznaka 19 ostavlja crveno",
    Bullet20_Target_Blue: "Oznaka 20 ciljno plava",
    Bullet21_Arrow_Blue: "Oznaka 21 strelica plava",
    Bullet22_Arrow_DarkBlue: "Oznaka 22 strelica tamnoplava",
    Bullet23_Arrow_Brown: "Oznaka 23 strelica smeđa",
    Bullet24_Flag_Red: "Oznaka 24 zastava crvena",
    Bullet25_Flag_Green: "Oznaka 25 zastava zelena",
    Bullet26_X_Red: "Oznaka 26 X crveni",
    Bullet27_X_Black: "Oznaka 27 X crni",
    Bullet28_Checkmark_Green: "Oznaka 28 kvačica zelena",
    Bullet29_Checkmark_Blue: "Oznaka 29 kvačica plava",
    Bullet30_Square_DarkRed: "Oznaka 30 kvadrat tamnocrveni",
    camera: "Kamera",
    computer1: "Računalo 1",
    computer2: "Računalo 2",
    computer3: "Računalo 3",
    Computer_Cloud: "Oblak računalo",
    Computer_Desktop: "Desktop računalo",
    Computer_Laptop_Black: "Laptop računalo crno",
    Computer_Laptop_Silver: "Laptop računalo srebreno",
    Database: "Baza podataka",
    evelope: "Koverta",
    newspapers: "Novine",
    openevelope: "Otvorena koverta",
    Server: "Poslužitelj",
    speaker: "Zvučnik",
    WirelessAccessPoint: "Bežična pristupna točka",
    Cycle01_Transparent: "Ciklus 01 proziran",
    Cycle02_Transparent_Blue: "Ciklus 02 prozirno plavi",
    Cycle03_Blue: "Ciklus 03 plavi",
    Cycle04_Blue: "Ciklus 04 plavi",
    Cycle05: "Ciklus 05",
    Cycle06: "Ciklus 06",
    Cycle07: "Ciklus 07",
    Cycle08_Blue: "Ciklus 08 plavi",
    Cycle09_Orange: "Ciklus 09 narančasti",
    Donut01_LightBlue: "Uštipak 01 svijetloplavi",
    Donut02_Blue: "Uštipak 02 plavi",
    Donut03_Blue: "Uštipak 03 plavi",
    Donut04_DarkBlue: "Uštipak 04 tamnoplavi",
    Donut05_DarkBlue: "Uštipak 05 tamnoplavi",
    Donut06_Blue: "Uštipak 06 plavi",
    Donut07_Blue: "Uštipak 07 plavi",
    Graph: "Graf",
    People01_Blue: "Ljudi 01 plavi",
    People02: "Ljudi 02",
    Pillars01_Orange: "Stup 01 narančasti",
    Pillars02_LightBlue: "Stup 02 svijetloplavi",
    Process01_Blue: "Proces 01 plavi",
    Process02_Blue: "Proces 02 plavi",
    Process03_Blue: "Proces 03 plavi",
    Process04_GoUp_Blue: "Proces 04 prema gore plavi",
    Process05_GoUp_Red: "Proces 05 prema gore crveni",
    Process06_GoUp_Yellow: "Proces 06 prema gore žuti",
    Process07_Blue: "Proces 07 plavi",
    Pyramid01: "Piramida 01",
    Pyramid02_Blue: "Piramida 02 plava",
    Pyramid03: "Piramida 03",
    Radial01_Green: "Radijalno 01 zeleno",
    Radial02_Green: "Radijalno 02 zeleno",
    Radial03_Sphere: "Radijalno 03 sferno",
    Radial04_Sphere_Red: "Radijalno 04 sferno crveno",
    Radial05_Sphere_Blue: "Radijalno 05 sferno plavo",
    Radial06_Arrows_DarkBlue: "Radijalno 06 strelice tamnoplave",
    Radial07_Arrows_DarkBlue: "Radijalno 07 strelice tamnoplave",
    Section_Circle: "Dio krug",
    Section_Cubes01: "Dio kocke 01",
    Section_Cubes02_Blue: "Dio kocke 02 plavi",
    Section_Cubes03_Orange: "Dio kocke 03 narančasti",
    Section_Cubes04: "Dio kocke 04",
    Section_Cubes05: "Dio kocke 05",
    Section_Cuboids01_Blue: "Dio kuboidi 01 plavo",
    Section_Cuboids02_Blue: "Dio kuboidi 02 plavo",
    Section_Cuboids03: "Dio kuboidi 03",
    Section_Gears01: "Dio zupčanici 01",
    Section_Gears02: "Dio zupčanici 02",
    Section_Gears03: "Dio zupčanici 03",
    Section_Hexagon04_Orange: "Dio heksagon 04 narančasti",
    Section_Hexagons01: "Dio heksagoni 01",
    Section_Hexagons02_Blue: "Dio heksagoni 02 plavi",
    Section_Hexagons03_Blue: "Dio heksagoni 03 plavi",
    Section_Leaves01_LightBlue: "Dio lišće 01 svijetloplavo",
    Section_Leaves02_Green: "Dio lišće 02 zeleno",
    Section_Pasters01: "Dio pasteri 01",
    Section_Pasters02_Blue: "Dio pasteri 02 plavi",
    Section_Puzzle01: "Dio puzzle 01",
    Section_Puzzle02: "Dio puzzle 02",
    Section_Puzzle03: "Dio puzzle 03",
    Section_Rectangles: "Dio pravokutnici",
    Section_Squares: "Dio kvadrati",
    Section_Triangle: "Dio trokuti",
    Target: "Cilj",
    Venn01: "Venn 01",
    Venn02: "Venn 02",
    Venn03: "Venn 03",
    Venn04: "Venn 04",
    Venn05: "Venn 05",
    Venn06_Blue: "Venn 06 plavo",
    Venn07_Blue: "Venn 07 plavo",
    Venn08: "Venn 08",
    Blackboard: "Tabla",
    Books: "Knjige",
    Books1: "Knjige 1",
    books2: "Knjige 2",
    Chalk: "Kreda",
    clipboard: "memorija za isječke",
    clock: "sat",
    Globe: "Globus",
    Glue: "Ljepilo",
    GraduationCap: "Diplomska kapa",
    magnifyingglass: "povećalo",
    Microscope: "Mikroskop",
    Notebook: "Notebook",
    notepad1: "Notepad 1",
    notepad2: "Notepad 2",
    notepad3: "Notepad 3",
    PaperClip_Blue: "Spajalica plava",
    PaperClip_Red: "Spajalica crvena",
    Pencil: "Olovka",
    Ruler: "Ravnalo",
    TestTubes: "Epruvete",
    thumbtack: "Pribadača",
    clouds: "Oblaci",
    DrippingFaucet: "Kaplja iz slavine",
    Earth: "Zemlja",
    EndangeredAnimals1: "Ugrožene životinje 1",
    EndangeredAnimals2: "Ugrožene životinje 2",
    GreenCar: "Zeleni auto",
    GreenFactory: "Zelena tvornica",
    GreenHouse: "Zelena kuća",
    Leaf1: "List 1",
    Leaf2: "List 2",
    lightbulb: "Žarulja",
    LightBulb_Flourescent_Off: "Fluorescentna žarulja ugašena",
    LightBulb_Flourescent_On: "Fluorescentna žarulja upaljena",
    LightBulb_Standard_Off1: "Žarulja standardna ugašena 1",
    LightBulb_Standard_Off2: "Žarulja standardna ugašena 2",
    LightBulb_Standard_On: "Žarulja standardna upaljena",
    lightningcloud: "Svjetleći oblak",
    Pollution_Car: "Auto koji zagađuje",
    Pollution_Factory: "Tvornica koja zagađuje",
    Raindrop: "Kap kiše",
    RecycleBin: "Košara za otpad",
    RecycleSymbol: "Simbol recikliranja",
    RenewableEnergySymbol: "Obnovljiva energija simbol",
    RenewableEnergy_Solar: "Obnovljiva energija sunce",
    RenewableEnergy_Water: "Obnovljiva energija voda",
    RenewableEnergy_Wind: "Obnovljiva energija vjetar",
    sun: "Sunce",
    Sun1: "Sunce 1",
    Sun2: "Sunce 2",
    sundandcloud: "Sunce i oblak",
    world: "Svijet",
    Agreement: "Sporazum",
    ATM01: "ATM 01",
    ATM02: "ATM 02",
    Balance_Balanced1: "Ravnoteža uravnoteženo 1",
    Balance_Balanced2: "Ravnoteža uravnoteženo 2",
    Balance_Unbalanced1: "Ravnoteža neuravnoteženo 1",
    Balance_Unbalanced2: "Ravnoteža neuravnoteženo 2",
    Calculator: "Kalkulator",
    Chart_Decrease1: "Grafikon pada 1",
    Chart_Decrease2: "Grafikon pada 2",
    Chart_Increase1: "Grafikon rasta 1",
    Chart_Increase2: "Grafikon rasta 2",
    Chart_Plateau: "Grafikon plato",
    Check: "Provjera",
    Contract: "Ugovor",
    CreditCard_Black: "Kreditna kartica crna",
    CreditCard_Cut: "Kreditna kartica prerezana",
    CreditCard_Gold: "Kreditna kartica zlatna",
    Currency_Dollar: "Valuta dolar",
    Currency_Dollars: "Valuta dolari",
    Currency_Stack: "Valuta hrpa",
    Currency_StackCoins: "Valuta hrpa kovanice",
    GoldBar: "Zlatna poluga",
    GoldBar_Stack: "Zlatna poluga hrpa",
    MoneyBag01: "Vreća novca 01",
    MoneyBag02: "Vreća novca 02",
    PercentSign: "Postotak znak",
    PiggyBank01_Broken: "Banka prase 01 razbijena",
    PiggyBank02_Broken: "Banka prase 02 razbijena",
    PiggyBank_Coins: "Banka prase kovanice",
    PiggyBank_Currency: "Banka prase valuta",
    Portfolio: "Portfolio",
    PriceTag: "Etiketa s cijenom",
    Safe_Closed: "Sef zatvoren",
    Safe_Empty: "Sef prazan",
    Safe_Full: "Sef pun",
    Seal_Gold: "Pečat zlatan",
    Seal_Red: "Pečat crven",
    Seal_Silver: "Pečat srebren",
    Wallet_Empty: "Novčanik prazan",
    Wallet_Full1: "Novčanik pun 1",
    Wallet_Full2: "Novčanik pun 2",
    BusinessPerson_Female6: "Poslovna osoba žena 6",
    BusinessPerson_Male3: "Poslovna osoba muškarac 3",
    Computer_User_Female1: "Korisnik računala žena1",
    ConstructionWorker2: "Građevinski radnik 2",
    Presenter_Female1: "Predstavljač žena 1",
    Component_Circle01_Transparent_DarkBlue: "Komponentni krug 01 prozirno tamnoplavo",
    Component_Circle02_Transparent_Bule: "Komponentni krug 02 prozirno plavo",
    Component_Circle03_Transparent_Green: "Komponentni krug 03 prozirno zeleno",
    Component_Circle04_Transparent_Orange: "Komponentni krug 04 prozirno narančasto",
    Component_Circle05_Transparent_Red: "Komponentni krug 05 prozirno crveno",
    Component_Cube01_DarkBlue: "Komponentna kocka 01 tamnoplava",
    Component_Cube02_LightBlue: "Komponentna kocka 02 svijetloplava",
    Component_Cube03_Green: "Komponentna kocka 03 zelena",
    Component_Cube04_Orange: "Komponentna kocka 04 narančasta",
    Component_Cube05_DarkRed: "Komponentna kocka 05 tamnocrvena",
    Component_Cuboid01_DarkBlue: "Komponentni kuboid 01 tamnoplavi",
    Component_Cuboid02_Blue: "Komponentni kuboid 02 plavi",
    Component_Cuboid03_Green: "Komponentni kuboid 03 zeleni",
    Component_Cuboid04_Orange: "Komponentni kuboid 04 narančasti",
    Component_Cuboid05_Red: "Komponentni kuboid 05 crveni",
    Component_Gear01_DarkBlue: "Komponentni zupčanik 01 tamnoplavi",
    Component_Gear02_LightBlue: "Komponentni zupčanik 02 svijetloplavi",
    Component_Gear03_Green: "Komponentni zupčanik 03 zeleni",
    Component_Gear04_DarkRed: "Komponentni zupčanik 04 tamnocrveni",
    Component_Gear05_Orange: "Komponentni zupčanik 05 narančasti",
    Component_Person01_DarkBlue: "Komponentna osoba 01 tamnoplava",
    Component_Person02_Blue: "Komponentna osoba 02 plava",
    Component_Person03_Green: "Komponentna osoba 03 zelena",
    Component_Person04_DarkRed: "Komponentna osoba 04 tamnocrvena",
    Component_Person05_Orange: "Komponentna osoba 05 narančasta",
    Component_PuzzlePiece01_DarkBlue: "Komponentni puzzle komad 01 tamnoplavi",
    Component_PuzzlePiece02_Blue: "Komponentni puzzle komad 02 plavi",
    Component_PuzzlePiece03_Green: "Komponentni puzzle komad 03 zeleni",
    Component_PuzzlePiece04_Red: "Komponentni puzzle komad 04 crveni",
    Component_PuzzlePiece05_Orange: "Komponentni puzzle komad 05 narančasti",
    Component_Sphere01_DarkBlue: "Komponentna sfera 01 tamnoplava",
    Component_Sphere02_LightBlue: "Komponentna sfera 02 svijetloplava",
    Component_Sphere03_Green: "Komponentna sfera 03 zelena",
    Component_Sphere04_DarkRed: "Komponentna sfera 04 tamnocrvena",
    Component_Sphere05_Orange: "Komponentna sfera 05 narančasta",
    Book: "Knjiga",
    Box01: "Okvir 01",
    Box02: "Okvir 02",
    Bulb01_Yellow: "Žarulja 01 žuta",
    Bulb02_Yellow: "Žarulja 02 žuta",
    Calendar: "Kalendar",
    Chart: "Grafikon",
    Clipboard: "Memorija za isječke",
    Clock: "Sat",
    Compass: "Kompas",
    Flag01_Red: "Zastava 01 crvena",
    Flag02_Green: "Zastava 02 zelena",
    Flag03_Blue: "Zastava 03 plava",
    Gift: "Poklon",
    House: "Kuća",
    Icon_Computer01_White: "Ikona računalo 01 bijela",
    Icon_Computer02_Black: "Ikona računalo 02 crna",
    Icon_Disk01_Blue: "Ikona disk 01 plava",
    Icon_Disk02_Green: "Ikona disk 02 zelena",
    Icon_Document01_Grey: "Ikona dokument 01 siva",
    Icon_Document02_Grey: "Ikona dokument 02 siva",
    Icon_Document03_Blue: "Ikona dokument 03 plava",
    Icon_Document04_Blue: "Ikona dokument 04 plava",
    Icon_Envelope01_Blue: "Ikona koverta 01 plava",
    Icon_Envelope02_Yellow: "Ikona koverta 02 žuta",
    Icon_Envelope03_Open_Yellow: "Ikona koverta 03 otvoreno žuta",
    Icon_Envelope04_Open_Yellow: "Ikona koverta 04 otvoreno žuta",
    Icon_Folder01_Yellow: "Ikona folder 01 žuta",
    Icon_Folder02_Yellow: "Ikona folder 02 žuta",
    Icon_Folder03_Open_Yellow: "Ikona folder 03 otvoreno žuta",
    Icon_Folder04_Open_Yellow: "Ikona folder 04 otvoreno žuta",
    Icon_Gear01_Grey: "Ikona zupčanik 01 siva",
    Icon_Gear02_Blue: "Ikona zupčanik 02 plava",
    Icon_Network01_Blue: "Ikona mreža 01 plava",
    Icon_Network02: "Ikona mreža 02",
    Icon_Pencil01: "Ikona olovka 01",
    Icon_Pencil02: "Ikona olovka 02",
    Icon_Printer01_White: "Ikona pisač 01 bijela",
    Icon_Printer02_Black: "Ikona pisač 02 crna",
    Key01: "Ključ 01",
    Key02: "Ključ 02",
    Lock01_Yellow: "Brava 01 žuta",
    Lock02_Yellow: "Brava 02 žuta",
    Lock03_Blue: "Brava 03 plava",
    Lock04_Blue: "Brava 04 plava",
    Magnet: "Magnet",
    MagnifyingGlass: "Povećalo",
    Medal: "Medalja",
    Notebook: "Notebook",
    Phone: "Telefon",
    PieChart: "Tortni grafikon",
    Pin: "Igla",
    PuzzlePiece: "Puzzle komad",
    PuzzlePieces: "Puzzle komadi",
    Roadblock: "Prepreka na putu",
    Scissors: "Škare",
    Shield01: "Štit 01",
    Shield02_Orange: "Štit 02 narančast",
    Shield03_Blue: "Štit 03 plavi",
    Sign_Ban01: "Znak zabrane 01",
    Sign_Ban02: "Znak zabrane 02",
    Sign_CheckBox01: "Znak kontrolna kućica 01",
    Sign_CheckBox02_Unchecked: "Znak kontrolna kućica 02 neoznačen",
    Sign_Checkmark01_Green: "Znak kvačica 01 zeleni",
    Sign_Checkmark02_Green: "Znak kvačica 02 zeleni",
    Sign_DoNotEnter: "Znak ne ulazi",
    Sign_Error01: "Znak greška 01",
    Sign_Error02: "Znak greška 02",
    Sign_ExclamationPoint01_Red: "Znak uskličnik 01 crveni",
    Sign_ExclamationPoint02_Orange: "Znak uskličnik 02 narančasti",
    Sign_Help01_Green: "Znak pomoć 01 zeleni",
    Sign_Help02_Blue: "Znak pomoć 02 plavi",
    Sign_Information: "Znak informacije",
    Sign_Null: "Znak null",
    Sign_QuestionMark01_Blue: "Znak upitnik 01 plavi",
    Sign_QuestionMark02_Red: "Znak upitnik 02 crveni",
    Sign_RadioButton01: "Znak radio gumb 01",
    Sign_RadioButton02_Unchecked: "Znak radio gumb 02 neoznačen",
    Sign_Warning01_Red: "Znak upozorenje 01 crveni",
    Sign_Warning02_Orange: "Znak upozorenje 02 narančasti",
    Sign_X01_Red: "Znak X 01 crveni",
    Sign_X02_Red: "Znak X 02 crveni",
    Star_Yellow: "Zvijezda žuta",
    Wrench: "Ključ",
    Airplane_Blue: "Avion plavi",
    Bicycle_Blue: "Bicikl plavi",
    Bus: "Autobus",
    Canoe_Blue: "Kanu plavi",
    Car_Red: "Auto crveni",
    Helicopter_Blue: "Helikopter plavi",
    Motorcycle_Red: "Motocikl crveni",
    Pedestrian_Blue: "Pješak plavi",
    PersonalTransporter_Green: "Osobni transporter zeleni",
    Sailboat_Red: "Jedrenjak crveni",
    Scooter_Orange: "Skuter narančasti",
    Train_Red: "Vlak crveni",
    Truck_Blue: "Kamion plavi",
    
    aria_category_selector: "Opcije kategorije slika",
    filterImageGallery: "Filter galerije slika"

})
