({
	labelNormal: "垂直ビュー",
	labelPlay: "スライド・ショーの再生",
	labelZoomIn: "拡大",
	labelZoomOut: "縮小",
	labelFitWidth: "幅に合わせる",
	labelReset: "リセット",
	lablePageUp: "前のページ",
	lablePageDown: "次のページ",
	labelPrint: "印刷",
	labelBuild: "${productName} ${0}",
	labelVersion: "${productName} ${0} ${1}",
	msgLoading: "文書がロードされるまでお待ちください。",
	msgConversionFail: "変換に失敗しました",
	labelReload: "再読み込み",
	labelHelpContent:"ヘルプ目次",
	labelAbout:"詳細情報",
	labelProject:"${productName}",
	labelEdit: "編集",
	labelHelp: "ヘルプ",
	labelCancel: "キャンセル",
	labelImageTypeIcon: "文書",
	errPrintBeforeLoading: "印刷するには、ブラウザーのメニューは使用できません。「印刷」ツールバーをクリックして文書を印刷します。コンテンツが完全に読み込まれていないため、現在印刷できません。",
	errPrintFromBrowserMenu: "文書を印刷するには、ブラウザーの「印刷」メニューではなく、ツールバーの「印刷」ボタンをクリックします。",
	errPrintConversionFail: "コンテンツを正常に変換できなかったため、印刷できませんでした。",
	successMsg:"成功",
	warningMsg:"警告",
	errorMsg:"エラー",
	backtofiles:"ファイルに戻る",
	openLatestFile: "最新のファイルを開く",
	updatePresentation:"プレゼンテーションは更新されました。すべてのテキストとイメージを表示するには、${0}。",
	updateNow: "今すぐ開く",
	fileUpdated: "プレゼンテーションが更新されました",
	fileUpdatedContent1: "プレゼンテーションが更新されました。 印刷する前に最新のファイルを開いてください。",
	fileUpdatedContent2: "プレゼンテーションが更新されました。 スライド・ショーを実行する前に最新のファイルを開いてください。",
	htmlviewerlimitation: "このプレゼンテーションには、表示できないアニメーションが含まれています",
	labelStopReview: "レビューの停止",
	labelRejct: "拒否",
	labelApprove: "承認",
	labelItemNotFountTitle: "アクションを完了できません。",
	labelItemNotFountMsg: "別のコミュニティー・メンバーが既にこの文書でアクションを実行中です。 詳細は、文書を閉じて、ライブラリーにある「ファイルの詳細」ページに移動してください。"
})

