/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
    Arrow01_Gray: "Pil 01 Grå",
    Arrow02_Gray: "Pil 02 Grå",
    Arrow03_Red: "Pil 03 Rød",
    Arrow04_Blue: "Pil 04 Blå",
    Arrow05_Blue: "Pil 05 Blå",
    Arrow06_Yellow: "Pil 06 Gul",
    Arrow07_Red: "Pil 07 Rød",
    Arrow08_Gray: "Pil 08 Grå",
    Arrow09_Orange: "Pil 09 Oransje",
    Arrow10_Blue: "Pil 10 Blå",
    Arrow11_Blue: "Pil 11 Blå",
    Arrow12_Green: "Pil 12 Grønn",
    Arrow13_Blue: "Pil 13 Blå",
    Arrow14_Green: "Pil 14 Grønn",
    Arrow15_Orange: "Pil 15 Oransje",
    Arrow16_Gray: "Pil 16 Grå",
    CircleArrow01_Green: "Sirkelpil 01 Grønn",
    CircleArrow02_Multi: "Sirkelpil 02 Multi",
    CircleArrow03_Multi: "Sirkelpil 03 Multi",
    CircleArrow04_Multi: "Sirkelpil 04 Multi",
    CircleArrow05_Multi: "Sirkelpil 05 Multi",
    CircleArrow06_Multi: "Sirkelpil 06 Multi",
    CircleArrow07_Blue: "Sirkelpil 07 Blå",
    CircleArrow08_Green: "Sirkelpil 08 Grønn",
    CircleArrow09_Multi: "Sirkelpil 09 Multi",
    CurvedArrow01_Gray: "Buet pil 01 Grå",
    CurvedArrow02_Blue: "Buet pil 02 Blå",
    CurvedArrow03_Blue: "Buet pil 03 Blå",
    CurvedArrow04_Orange: "Buet pil 04 Oransje",
    CurvedArrow05_Red: "Buet pil 05 Rød",
    CurvedArrow06_Blue: "Buet pil 06 Blå",
    CurvedArrow07_Purple: "Buet pil 07 Purpur",
    CurvedArrow08_Green: "Buet pil 08 Grønn",
    CurvedArrow09_Gray: "Buet pil 09 Grå",
    CurvedArrow10_Blue: "Buet pil 10 Blå",
    CurvedArrow11_Orange: "Buet pil 11 Oransje",
    CurvedArrow12_Blue: "Buet pil 12 Blå",
    CurvedArrow13_Green: "Buet pil 13 Grønn",
    CurvedArrow14_Brown: "Buet pil 14 Brun",
    CurvedArrow15_Blue: "Buet pil 15 Blå",
    CurvedArrow16_Gray: "Buet pil 16 Grå",
    CurvedArrow17_Gray: "Buet pil 17 Grå",
    CurvedArrow18_Gray: "Buet pil 18 Grå",
    CurvedArrow19_Gray: "Buet pil 19 Grå",
    CurvedArrow20_Gray: "Buet pil 20 Grå",
    TrendArrow01_Red: "Trendpil 01 Rød",
    TrendArrow02_Green: "Trendpil 02 Grønn",
    TrendArrow03_Orange: "Trendpil 03 Oransje",
    TrendArrow04_Red: "Trendpil 04 Rød",
    TrendArrow05_Orange: "Trendpil 05 Oransje",
    TrendArrow06_Blue: "Trendpil 06 Blå",
    TrendArrow07_Orange: "Trendpil 07 Oransje",
    TrendArrow08_Yellow: "Trendpil 08 Gul",
    TrendArrow09_Blue: "Trendpil 09 Blå",
    TrendArrow10_Blue: "Trendpil 10 Blå",
    TrendArrow11_Blue: "Trendpil 11 Blå",
    TrendArrow12_Blue: "Trendpil 12 Blå",
    TrendArrow13_Red: "Trendpil 13 Rød",
    TrendArrow14_Multi: "Trendpil 14 Multi",
    TrendArrow15_Blue: "Trendpil 15 Blå",
    Bullet01_Circle_DarkRed: "Punkt 01 Sirkel Mørk rød",
    Bullet02_Circle_Blue: "Punkt 02 Sirkel Blå",
    Bullet03_Circle_Green: "Punkt 03 Sirkel Grønn",
    Bullet04_Square_Black: "Punkt 04 Firkant Svart",
    Bullet05_Square_Orange: "Punkt 05 Firkant Oransje",
    Bullet06_Square_Purple: "Punkt 06 Firkant Purpur",
    Bullet07_Diamond_Blue: "Punkt 07 Diamant Blå",
    Bullet08_Diamond_LightBlue: "Punkt 08 Diamant Lys blå",
    Bullet09_Diamond_Red: "Punkt 09 Diamant Rød",
    Bullet10_Star_Yellow: "Punkt 10 Stjerne Gul",
    Bullet11_Star_Blue: "Punkt 11 Stjerne Blå",
    Bullet12_Triangle_Blue: "Punkt 12 Trekant Blå",
    Bullet13_Triangle_DarkGreen: "Punkt 13 Trekant Mørk grønn",
    Bullet14_Arrow_Red: "Punkt 14 Pil Rød",
    Bullet15_Arrow_Blue: "Punkt 15 Pil Blå",
    Bullet16_Box_Blue: "Punkt 16 Boks Blå",
    Bullet17_Box_Red: "Punkt 17 Boks Rød",
    Bullet18_Asterisk_LightBlue: "Punkt 18 Asterisk Lys blå",
    Bullet19_Leaves_Red: "Punkt 19 Løv Rød",
    Bullet20_Target_Blue: "Punkt 20 Mål Blå",
    Bullet21_Arrow_Blue: "Punkt 21 Pil Blå",
    Bullet22_Arrow_DarkBlue: "Punkt 22 Pil Mørk blå",
    Bullet23_Arrow_Brown: "Punkt 23 Pil Brun",
    Bullet24_Flag_Red: "Punkt 24 Flagg Rød",
    Bullet25_Flag_Green: "Punkt 25 Flagg Grønn",
    Bullet26_X_Red: "Punkt 26 X Rød",
    Bullet27_X_Black: "Punkt 27 X Svart",
    Bullet28_Checkmark_Green: "Punkt 28 Hake Grønn",
    Bullet29_Checkmark_Blue: "Punkt 29 Hake Blå",
    Bullet30_Square_DarkRed: "Punkt 30 Firkant Mørk rød",
    camera: "Kamera",
    computer1: "Datamaskin 1",
    computer2: "Datamaskin 2",
    computer3: "Datamaskin 3",
    Computer_Cloud: "Datamaskinsky",
    Computer_Desktop: "Datamaskin stasjonær",
    Computer_Laptop_Black: "Datamaskin Bærbar Svart",
    Computer_Laptop_Silver: "Datamaskin Bærbar Sølv",
    Database: "Database",
    evelope: "Konvolutt",
    newspapers: "Aviser",
    openevelope: "Åpen konvolutt",
    Server: "Server",
    speaker: "Høyttaler",
    WirelessAccessPoint: "Trådløst tilgangspunkt",
    Cycle01_Transparent: "Syklus 01 Gjennomsiktig",
    Cycle02_Transparent_Blue: "Syklus 02 Gjennomsiktig Blå",
    Cycle03_Blue: "Syklus 03 Blå",
    Cycle04_Blue: "Syklus 04 Blå",
    Cycle05: "Syklus 05",
    Cycle06: "Syklus 06",
    Cycle07: "Syklus 07",
    Cycle08_Blue: "Syklus 08 Blå",
    Cycle09_Orange: "Syklus 09 Oransje",
    Donut01_LightBlue: "Smultring 01 Lys blå",
    Donut02_Blue: "Smultring 02 Blå",
    Donut03_Blue: "Smultring 03 Blå",
    Donut04_DarkBlue: "Smultring 04 Mørk blå",
    Donut05_DarkBlue: "Smultring 05 Mørk blå",
    Donut06_Blue: "Smultring 06 Blå",
    Donut07_Blue: "Smultring 07 Blå",
    Graph: "Diagram",
    People01_Blue: "Personer 01 Blå",
    People02: "Personer 02",
    Pillars01_Orange: "Pilarer 01 Oransje",
    Pillars02_LightBlue: "Pilarer 02 Lys blå",
    Process01_Blue: "Prosess 01 Blå",
    Process02_Blue: "Prosess 02 Blå",
    Process03_Blue: "Prosess 03 Blå",
    Process04_GoUp_Blue: "Prosess 04 Gå opp Blå",
    Process05_GoUp_Red: "Prosess 05 Gå opp Rød",
    Process06_GoUp_Yellow: "Prosess 06 Gå opp Gul",
    Process07_Blue: "Prosess 07 Blå",
    Pyramid01: "Pyramide 01",
    Pyramid02_Blue: "Pyramide 02 Blå",
    Pyramid03: "Pyramide 03",
    Radial01_Green: "Radial 01 Grønn",
    Radial02_Green: "Radial 02 Grønn",
    Radial03_Sphere: "Radial 03 Kule",
    Radial04_Sphere_Red: "Radial 04 Kule Rød",
    Radial05_Sphere_Blue: "Radial 05 Kule Blå",
    Radial06_Arrows_DarkBlue: "Radial 06 Piler Mørk blå",
    Radial07_Arrows_DarkBlue: "Radial 07 Piler Mørk blå",
    Section_Circle: "Seksjon Sirkel",
    Section_Cubes01: "Seksjon Kuber 01",
    Section_Cubes02_Blue: "Seksjon Kuber 02 Blå",
    Section_Cubes03_Orange: "Seksjon Kuber 03 Oransje",
    Section_Cubes04: "Seksjon Kuber 04",
    Section_Cubes05: "Seksjon Kuber 05",
    Section_Cuboids01_Blue: "Seksjon Rette prismer 01 Blå",
    Section_Cuboids02_Blue: "Seksjon Rette prismer 02 Blå",
    Section_Cuboids03: "Seksjon Rette prismer 03",
    Section_Gears01: "Seksjon Tannhjul 01",
    Section_Gears02: "Seksjon Tannhjul 02",
    Section_Gears03: "Seksjon Tannhjul 03",
    Section_Hexagon04_Orange: "Seksjon Sekskant 04 Oransje",
    Section_Hexagons01: "Seksjon Sekskanter 01",
    Section_Hexagons02_Blue: "Seksjon Sekskanter 02 Blå",
    Section_Hexagons03_Blue: "Seksjon Sekskanter 03 Blå",
    Section_Leaves01_LightBlue: "Seksjon Løv 01 Lys blå",
    Section_Leaves02_Green: "Seksjon Løv 02 Grønn",
    Section_Pasters01: "Seksjon Klistrelapper 01",
    Section_Pasters02_Blue: "Seksjon Klistrelapper 02 Blå",
    Section_Puzzle01: "Seksjon Puslespill 01",
    Section_Puzzle02: "Seksjon Puslespill 02",
    Section_Puzzle03: "Seksjon Puslespill 03",
    Section_Rectangles: "Seksjon Rektangler",
    Section_Squares: "Seksjon Kvadrater",
    Section_Triangle: "Seksjon Triangel",
    Target: "Mål",
    Venn01: "Venn 01",
    Venn02: "Venn 02",
    Venn03: "Venn 03",
    Venn04: "Venn 04",
    Venn05: "Venn 05",
    Venn06_Blue: "Venn 06 Blå",
    Venn07_Blue: "Venn 07 Blå",
    Venn08: "Venn 08",
    Blackboard: "Tavle",
    Books: "Bøker",
    Books1: "Bøker 1",
    books2: "Bøker 2",
    Chalk: "Kritt",
    clipboard: "utklippstavle",
    clock: "klokke",
    Globe: "Klode",
    Glue: "Lim",
    GraduationCap: "Studentlue",
    magnifyingglass: "lupe",
    Microscope: "Mikroskop",
    Notebook: "Notisbok",
    notepad1: "Notisblokk 1",
    notepad2: "Notisblokk 2",
    notepad3: "Notisblokk 3",
    PaperClip_Blue: "Binders Blå",
    PaperClip_Red: "Binders Rød",
    Pencil: "Blyant",
    Ruler: "Linjal",
    TestTubes: "Prøverør",
    thumbtack: "Tegnestift",
    clouds: "Skyer",
    DrippingFaucet: "Dryppende kran",
    Earth: "Jord",
    EndangeredAnimals1: "Utrydningstruede dyr 1",
    EndangeredAnimals2: "Utrydningstruede dyr 2",
    GreenCar: "Grønn bil",
    GreenFactory: "Grønn fabrikk",
    GreenHouse: "Grønt hus",
    Leaf1: "Blad 1",
    Leaf2: "Blad 2",
    lightbulb: "Lyspære",
    LightBulb_Flourescent_Off: "Lyspære Fluorescerende Av",
    LightBulb_Flourescent_On: "Lyspære Fluorescerende På",
    LightBulb_Standard_Off1: "Lyspære Standard Av 1",
    LightBulb_Standard_Off2: "Lyspære Standard Av 2",
    LightBulb_Standard_On: "Lyspære Standard På",
    lightningcloud: "Sky med lyn",
    Pollution_Car: "Forurensningsbil",
    Pollution_Factory: "Forurensningsfabrikk",
    Raindrop: "Regndråpe",
    RecycleBin: "Papirkurv",
    RecycleSymbol: "Resirkuleringssymbol",
    RenewableEnergySymbol: "Fornybar energi Symbol",
    RenewableEnergy_Solar: "Fornybar energi Sol",
    RenewableEnergy_Water: "Fornybar energi Vann",
    RenewableEnergy_Wind: "Fornybar energi Vind",
    sun: "Sol",
    Sun1: "Sol 1",
    Sun2: "Sol 2",
    sundandcloud: "Sol og sky",
    world: "Verden",
    Agreement: "Avtale",
    ATM01: "ATM 01",
    ATM02: "ATM 02",
    Balance_Balanced1: "Vekt Balansert 1",
    Balance_Balanced2: "Vekt Balansert 2",
    Balance_Unbalanced1: "Vekt Ubalansert 1",
    Balance_Unbalanced2: "Vekt Ubalansert 2",
    Calculator: "Kalkulator",
    Chart_Decrease1: "Diagram Reduser 1",
    Chart_Decrease2: "Diagram Reduser 2",
    Chart_Increase1: "Diagram Øk 1",
    Chart_Increase2: "Diagram Øk 2",
    Chart_Plateau: "Diagramplatå",
    Check: "Kontroller",
    Contract: "Trekk sammen",
    CreditCard_Black: "Kredittkort Svart",
    CreditCard_Cut: "Kredittkort Kutt",
    CreditCard_Gold: "Kredittkort Gull",
    Currency_Dollar: "Valuta Dollar",
    Currency_Dollars: "Valuta Dollars",
    Currency_Stack: "Valutastabel",
    Currency_StackCoins: "Valutastabel Mynter",
    GoldBar: "Gullbarre",
    GoldBar_Stack: "Gullbarrestabel",
    MoneyBag01: "Pengesekk 01",
    MoneyBag02: "Pengesekk 02",
    PercentSign: "Prosenttegn",
    PiggyBank01_Broken: "Sparebøsse 01 Ødelagt",
    PiggyBank02_Broken: "Sparebøsse 02 Ødelagt",
    PiggyBank_Coins: "Sparebøsse Mynter",
    PiggyBank_Currency: "Sparebøsse Valuta",
    Portfolio: "Portefølje",
    PriceTag: "Prislapp",
    Safe_Closed: "Safe Lukket",
    Safe_Empty: "Safe Tom",
    Safe_Full: "Safe Full",
    Seal_Gold: "Segl Gull",
    Seal_Red: "Segl Rød",
    Seal_Silver: "Segl Sølv",
    Wallet_Empty: "Lommebok Tom",
    Wallet_Full1: "Lommebok Full 1",
    Wallet_Full2: "Lommebok Full 2",
    BusinessPerson_Female6: "Forretningsperson Kvinne 6",
    BusinessPerson_Male3: "Forretningsperson Mann 3",
    Computer_User_Female1: "Datamaskinbruker Kvinne 1",
    ConstructionWorker2: "Bygningsarbeider 2",
    Presenter_Female1: "Presentatør Kvinne 1",
    Component_Circle01_Transparent_DarkBlue: "Komponent Sirkel 01 Gjennomsiktig Mørk blå",
    Component_Circle02_Transparent_Bule: "Komponent Sirkel 02 Gjennomsiktig Blå",
    Component_Circle03_Transparent_Green: "Komponent Sirkel 03 Gjennomsiktig Grønn",
    Component_Circle04_Transparent_Orange: "Komponent Sirkel 04 Gjennomsiktig Oransje",
    Component_Circle05_Transparent_Red: "Komponent Sirkel 05 Gjennomsiktig Rød",
    Component_Cube01_DarkBlue: "Komponent Kube 01 Mørk blå",
    Component_Cube02_LightBlue: "Komponent Kube 02 Lys blå",
    Component_Cube03_Green: "Komponent Kube 03 Grønn",
    Component_Cube04_Orange: "Komponent Kube 04 Oransje",
    Component_Cube05_DarkRed: "Komponent Kube 05 Mørk rød",
    Component_Cuboid01_DarkBlue: "Komponent Rett prisme 01 Mørk blå",
    Component_Cuboid02_Blue: "Komponent Rett prisme 02 Blå",
    Component_Cuboid03_Green: "Komponent Rett prisme 03 Grønn",
    Component_Cuboid04_Orange: "Komponent Rett prisme 04 Oransje",
    Component_Cuboid05_Red: "Komponent Rett prisme 05 Rød",
    Component_Gear01_DarkBlue: "Komponent Tannhjul 01 Mørk blå",
    Component_Gear02_LightBlue: "Komponent Tannhjul 02 Lys blå",
    Component_Gear03_Green: "Komponent Tannhjul 03 Grønn",
    Component_Gear04_DarkRed: "Komponent Tannhjul 04 Mørk rød",
    Component_Gear05_Orange: "Komponent Tannhjul 05 Oransje",
    Component_Person01_DarkBlue: "Komponent Person 01 Mørk blå",
    Component_Person02_Blue: "Komponent Person 02 Blå",
    Component_Person03_Green: "Komponent Person 03 Grønn",
    Component_Person04_DarkRed: "Komponent Person 04 Mørk rød",
    Component_Person05_Orange: "Komponent Person 05 Oransje",
    Component_PuzzlePiece01_DarkBlue: "Komponent Puslespillbrikke 01 Mørk blå",
    Component_PuzzlePiece02_Blue: "Komponent Puslespillbrikke 02 Blå",
    Component_PuzzlePiece03_Green: "Komponent Puslespillbrikke 03 Grønn",
    Component_PuzzlePiece04_Red: "Komponent Puslespillbrikke 04 Rød",
    Component_PuzzlePiece05_Orange: "Komponent Puslespillbrikke 05 Oransje",
    Component_Sphere01_DarkBlue: "Komponent Kule 01 Mørk blå",
    Component_Sphere02_LightBlue: "Komponent Kule 02 Lys blå",
    Component_Sphere03_Green: "Komponent Kule 03 Grønn",
    Component_Sphere04_DarkRed: "Komponent Kule 04 Mørk rød",
    Component_Sphere05_Orange: "Komponent Kule 05 Oransje",
    Book: "Bok",
    Box01: "Boks 01",
    Box02: "Boks 02",
    Bulb01_Yellow: "Lyspære 01 Gul",
    Bulb02_Yellow: "Lyspære 02 Gul",
    Calendar: "Kalender",
    Chart: "Diagram",
    Clipboard: "Utklippstavle",
    Clock: "Klokke",
    Compass: "Kompass",
    Flag01_Red: "Flagg 01 Rød",
    Flag02_Green: "Flagg 02 Grønn",
    Flag03_Blue: "Flagg 03 Blå",
    Gift: "Gave",
    House: "Hus",
    Icon_Computer01_White: "Ikon Datamaskin 01 Hvit",
    Icon_Computer02_Black: "Ikon Datamaskin 02 Svart",
    Icon_Disk01_Blue: "Ikon Disk 01 Blå",
    Icon_Disk02_Green: "Ikon Disk 02 Grønn",
    Icon_Document01_Grey: "Ikon Dokument 01 Grå",
    Icon_Document02_Grey: "Ikon Dokument 02 Grå",
    Icon_Document03_Blue: "Ikon Dokument 03 Blå",
    Icon_Document04_Blue: "Ikon Dokument 04 Blå",
    Icon_Envelope01_Blue: "Ikon Konvolutt 01 Blå",
    Icon_Envelope02_Yellow: "Ikon Konvolutt 02 Gul",
    Icon_Envelope03_Open_Yellow: "Ikon Konvolutt 03 Åpen Gul",
    Icon_Envelope04_Open_Yellow: "Ikon Konvolutt 04 Åpen Gul",
    Icon_Folder01_Yellow: "Ikon Mappe 01 Gul",
    Icon_Folder02_Yellow: "Ikon Mappe 02 Gul",
    Icon_Folder03_Open_Yellow: "Ikon Mappe 03 Åpen Gul",
    Icon_Folder04_Open_Yellow: "Ikon Mappe 04 Åpen Gul",
    Icon_Gear01_Grey: "Ikon Tannhjul 01 Grå",
    Icon_Gear02_Blue: "Ikon Tannhjul 02 Blå",
    Icon_Network01_Blue: "Ikon Nettverk 01 Blå",
    Icon_Network02: "Ikon Nettverk 02",
    Icon_Pencil01: "Ikon Blyant 01",
    Icon_Pencil02: "Ikon Blyant 02",
    Icon_Printer01_White: "Ikon Skriver 01 Hvit",
    Icon_Printer02_Black: "Ikon Skriver 02 Svart",
    Key01: "Nøkkel 01",
    Key02: "Nøkkel 02",
    Lock01_Yellow: "Lås 01 Gul",
    Lock02_Yellow: "Lås 02 Gul",
    Lock03_Blue: "Lås 03 Blå",
    Lock04_Blue: "Lås 04 Blå",
    Magnet: "Magnet",
    MagnifyingGlass: "Lupe",
    Medal: "Medalje",
    Notebook: "Notisbok",
    Phone: "Telefon",
    PieChart: "Sektordiagram",
    Pin: "Nål",
    PuzzlePiece: "Puslespillbrikke",
    PuzzlePieces: "Puslespillbrikker",
    Roadblock: "Veisperring",
    Scissors: "Saks",
    Shield01: "Skjold 01",
    Shield02_Orange: "Skjold 02 Oransje",
    Shield03_Blue: "Skjold 03 Blå",
    Sign_Ban01: "Symbol Forbudt 01",
    Sign_Ban02: "Symbol Forbudt 02",
    Sign_CheckBox01: "Symbol Avmerkingsboks 01",
    Sign_CheckBox02_Unchecked: "Symbol Avmerkingsboks 02 Ikke valgt",
    Sign_Checkmark01_Green: "Symbol Hake 01 Grønn",
    Sign_Checkmark02_Green: "Symbol Hake 02 Grønn",
    Sign_DoNotEnter: "Symbol Adgang forbudt",
    Sign_Error01: "Symbol Feil 01",
    Sign_Error02: "Symbol Feil 02",
    Sign_ExclamationPoint01_Red: "Symbol Utropstegn 01 Rød",
    Sign_ExclamationPoint02_Orange: "Symbol Utropstegn 02 Oransje",
    Sign_Help01_Green: "Symbol Hjelp 01 Grønn",
    Sign_Help02_Blue: "Symbol Hjelp 02 Blå",
    Sign_Information: "Symbol Informasjon",
    Sign_Null: "Symbol Null",
    Sign_QuestionMark01_Blue: "Symbol Spørsmålstegn 01 Blå",
    Sign_QuestionMark02_Red: "Symbol Spørsmålstegn 02 Rød",
    Sign_RadioButton01: "Symbol Valgknapp 01",
    Sign_RadioButton02_Unchecked: "Symbol Valgknapp 02 Ikke valgt",
    Sign_Warning01_Red: "Symbol Advarsel 01 Rød",
    Sign_Warning02_Orange: "Symbol Advarsel 02 Oransje",
    Sign_X01_Red: "Symbol X 01 Rød",
    Sign_X02_Red: "Symbol X 02 Rød",
    Star_Yellow: "Stjerne Gul",
    Wrench: "Skrunøkkel",
    Airplane_Blue: "Fly Blå",
    Bicycle_Blue: "Sykkel Blå",
    Bus: "Buss",
    Canoe_Blue: "Kano Blå",
    Car_Red: "Bil Rød",
    Helicopter_Blue: "Helikopter Blå",
    Motorcycle_Red: "Motorsykkel Rød",
    Pedestrian_Blue: "Fotgjenger Blå",
    PersonalTransporter_Green: "Personlig transportmiddel Grønt",
    Sailboat_Red: "Seilbåt Rød",
    Scooter_Orange: "Scooter Oransje",
    Train_Red: "Tog Rødt",
    Truck_Blue: "Lastebil Blå",
    
    aria_category_selector: "Bildekategorialternativer",
    filterImageGallery: "Filtrer bildegalleri"

})
