({
	ORIENTATION_LABEL: "Orientação",
	PORTRAIT: "Vertical",
	LANDSCAPE: "Horizontal",
	PAGE_LABEL: "Ordem das páginas",
	PAGE_TYPE1: "De cima para baixo, depois à direita",
	PAGE_TYPE2: "Da esquerda para a direita, depois para baixo",
	DISPLAY_OPTION_LABEL: "Opções de apresentação",
	HEADER: "Cabeçalho",
	FOOTER: "Rodapé",
	GRIDLINE: "Linhas da grelha",
	MARGINS_LABEL: "Margens",
	TOP: "Superior:",
	BOTTOM: "Inferior:",
	LEFT: "Esquerda:",
	RIGHT: "Direita:",
	PAPER_FORMAT_LABEL: "Formato do papel",
	PAPER_SIZE_LABEL: "Tamanho do papel:",
	HEIGHT: "Altura:",
	WIDTH: "Largura:",
	
	TOOLTIP1:"Imprime o número máximo de linhas permitido num papel, avançando até já não existirem mais colunas na folha e, em seguida, avança para baixo e para a esquerda para imprimir o próximo grupo de linhas.",
	TOOLTIP2:"Imprime o número máximo de colunas permitido num papel, avançando para baixo até já não existirem mais linhas na folha e, em seguida, avança para cima e para a direita para imprimir o próximo grupo de colunas.",
	CM_LABEL: "cm",
	LETTER: "Carta",
	LEGAL: "Legal",
	TABLOID: "Tablóide",
	USER: "Utilizador",
	SIZE1: "Env. #6 3/4",
	SIZE2: "Env. Monarch",
	SIZE3: "Env. #9",
	SIZE4: "Env. #10",
	SIZE5: "Env. #11",
	SIZE6: "Env. #12",
	SIZE7: "16 kai",
	SIZE8: "32 kai",
	SIZE9: "32 kai de compr"
})
	
