({
	LOCALE_DESC: "Seleccione a configuração regional para formatar números, moedas, datas e horas.",
	INPUT_INVALID_LOCALENAME: "Nome da configuração regional não válido",
	INPUT_EMPTY_LOCALENAME: "Seleccione uma configuração regional.",
	
	Spain_Catalan: "Espanha (Catalão)",
	Denmark: "Dinamarca",
	Germany: "Alemanha",
	Greek: "Grécia",
	United_States: "Estados Unidos",
	United_Kingdom: "Reino Unido",
	Spain: "Espanha",
	Finland: "Finlândia",
	France: "França",
	Italy: "Itália",
	Japan: "Japão",
	Korean: "Coreia do Sul",
	Norway: "Noruega",
	Netherlands: "Países Baixos",
	Poland: "Polónia",
	Brazil: "Brasil",
	Portugal: "Portugal",
	Russia: "Rússia",
	Sweden: "Suécia",
	Thailand: "Tailândia",
	Turkey: "Turquia",
	China: "China",
	Taiwan_China: "Taiwan (China)",
	Israel: "Israel"
})

