/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2014. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
	service_unavailable_title: "Hizmet sağlanamıyor.",
	service_unavailable_content: "${productName} hizmeti kullanılamıyor. İsteğiniz şu an için işlenemiyor. Daha sonra yeniden deneyin ya da sistem yöneticinize başvurun.",
	access_denied_title: "Erişim reddedildi.",
	viewaccess_denied_content: "Bu dosyayı görüntüleme izniniz yok. Dosyanın genel kullanıma açılması ya da sizinle paylaşılması gerekiyor.",
	editaccess_denied_content: "${productName} ürününü kullanma yetkiniz yok ya da bu dosyayı düzenleme izniniz yok. Dosyanın sizinle paylaşılması ve erişim düzeyinizin düzenleyici olarak ayarlanması gerekiyor. Dosya başka bir düzenleyici tarafından kilitlenmiş de olabilir.",
	doc_notfound_title: "Belge bulunamadı.",
	doc_notfound_content: "Erişmek istediğiniz belge silinmiş ya da taşınmış. Bağlantının doğru olup olmadığını kontrol edin.",
	repository_out_of_space_title: "Yeterli Alan Yok",
	repository_out_of_space_content: "Dosya boyutu kotasına ulaştığınızdan ${0} yayınlanamıyor. Diğer dosyaları çöp kutusuna taşıyıp silerek kotanızı azaltın.",
	fileconnect_denied_title: "Bağlantı reddedildi.",
	fileconnect_denied_content: "${productName}, dosya havuzuyla bağlantı kuramıyor. Daha sonra yeniden deneyin ya da sistem yöneticinize başvurun.",
	unscanned_document_title: "Virüsc taraması tamamlanıyor",
	unscanned_document_content: "Connections'a yüklenen dosyalar otomatik olarak taranır. Taraması tamamlanır tamamlanmaz bu dosyayı düzenleyebilirsiniz.",
	malicious_document_title: "Zararlı dosya",
	malicious_document_content: "Tarama sırasında Connections bir virüs saptadığından bu dosyayı düzenleyemezsiniz.",	
	convservice_unavailable_title: "Dönüştürme hizmeti kullanılamıyor.",
	convservice_unavailable_content: "${productName} dönüştürme hizmeti kullanılamıyor. İsteğiniz şu an için işlenemiyor. Daha sonra yeniden deneyin ya da sistem yöneticinize başvurun.",
	doc_toolarge_title: "Dosya çok büyük",
	doc_toolarge_content: "Erişmek istediğiniz belge çok büyük.",
	doc_toolarge_content2: "Dosyaya erişilemiyor. Olası nedenler arasında şunlar yer alır:",
	doc_toolarge_content3: "Dosyasının boyutu ${0} KB'den büyük olduğundan dosya görüntülenemiyor. Düzenlemek için dosyayı karşıdan yükleyebilirsiniz. Dosyada yüksek çözünürlüklü resimler varsa, dosya boyutunu küçültmek için bunları düşük çözünürlüklü resimlerle değiştirebilirsiniz.",
	doc_toolarge_content4: "Dosya burada görüntülemek için fazla büyük, ancak yine de başlık çubuğundaki karşıdan yükle düğmesini tıklatarak dosyayı açabilirsiniz.",
	doc_toolarge_content_mobile: "Dosyaya açılamıyor. Bir mobil aygıtta dosya boyutu ${0} KB'den büyük olamaz.",
	sheet_toolarge_content: "Elektronik sayfanın boyutu ${0} KB'den büyük.",
	sheet_toolarge_content2: "Elektronik sayfa, bir sayfada ${0} satırdan fazla satır içeriyor.",
	sheet_toolarge_content5: "Elektronik sayfa, bir sayfada ${0} sütundan fazla sütun içeriyor.",
	sheet_toolarge_content3: "Elektronik sayfa ${0} hücreden daha fazla hücre içeriyor.",
	sheet_toolarge_content4: "Elektronik sayfa ${0} formülden daha fazla formül içeriyor.",
	text_toolarge_content: "Belgenin boyutu ${0} KB'den büyük.",
	text_toolarge_content2:"Belge ${0} sayfadan fazla sayfa içeriyor.",
	text_toolarge_content3:"Belgenin metin boyutu ${0} KB'den büyük.",
	pres_toolarge_content: "Sunumun boyutu ${0} KB'den büyük olduğundan sunuma erişilemiyor. Sunumda yüksek çözünürlüklü resimler varsa, sunum boyutunu küçültmek için bunları düşük çözünürlüklü resimlerle değiştirebilirsiniz.",
	pres_toolarge_content2: "Sunum ${0} sayfadan daha fazla sayfa içerdiğinden sunuma erişilemiyor.",
	pres_toolarge_content3: "Sunum ${0} nesneden daha fazla nesne içerdiğinden sunuma erişilemiyor.",
	pres_toolarge_content2_mobile: "Bir mobil aygıtta ${0} sayfadan fazla sayfa içerdiğinden sunum açılamıyor.",
	pres_toolarge_content3_mobile: "Bir mobil aygıtta ${0} nesneden fazla nesneden içerdiğinden sunum açılamıyor.",
	sheet_view_toolarge_content1_mobile: "Bir mobil aygıtta ${0} satırdan fazla satır içerdiğinden elektronik sayfa görüntülenemiyor.",
	sheet_view_toolarge_content2_mobile: "Bir mobil aygıtta ${0} sütundan fazla sütun içerdiğinden elektronik sayfa görüntülenemiyor.",
	sheet_view_toolarge_content3_mobile: "Bir mobil aygıtta ${0} satırdan fazla satır ve ${1} sütundan fazla sütun içerdiğinden elektronik sayfa görüntülenemiyor.",
	conversion_timeout_title: "Belge dönüştürme işlemi zaman aşımına uğradı.",
	conversion_timeout_content: "Şu anda belgenin dönüştürülmesi çok uzun sürecek. Daha sonra yeniden deneyin.",
	invalid_docformat_title: "Belge açılamıyor",
	invalid_docformat_content: "Belgenin uzantısı geçerli, ancak belgenin içeriği bozuk ya da şifreli olduğundan okunamıyor.",
	template_extension_conent_mismatch: "Kaynak dosyasının uzantısı dosyayı şablon olarak tanımlıyor. Dosya aslında .${0} biçimindedir. Geçerli bir şablonla başlayın ya da uzantı olarak .${0} kullanarak dosyayı farklı bir adla kaydedin.",
	invalid_docformat_title2: "Dosya ${productName} içine alınamıyor.",
	invalid_docformat_content2: "Bu dosya, ${productName} ürününün şu anda destekleyemediği bir öğe içeriyor. Bu dosya alınamıyor.",
	invalid_doctype_title: "Bu belge tipi desteklenmiyor.",
	invalid_doctype_content: "Bu belge tipi ${productName} tarafından şu anda desteklenmiyor.",
	unsupported_browser_title: "Tarayıcınız tüm özellikleri desteklemiyor",
	malformed_request_title: "İstek hatalı oluşturulmuş.",
	malformed_request_content: "URL ve parametrelerin doğru olduğundan emin olun.",
	storageserver_error_title: "Depolama sunucusu kullanılamıyor.",
	storageserver_error_content: "Sunucu şu anda kullanılamıyor. İsteğiniz şu an için işlenemiyor. Daha sonra yeniden deneyin ya da sistem yöneticinize başvurun.",
	document_already_opened_title: "Belge zaten açıldı",
	document_already_opened_content:"Bu belge tarayıcınız tarafından zaten açıldı.",
	toomany_documents_opened_inone_browser_title: "Belge açılamadı.",
	toomany_documents_opened_inone_browser_content:"Bir kerede yalnızca beş ${productName} dosyası açılabilir. Diğer belgeleri kapatın ve bu belgeyi yeniden açmayı deneyin.",
	document_max_session_exceeded_title:"Hizmet sağlanamıyor.",
	document_max_session_exceeded_content:"Sunucuda belgeleri düzenleyen çok fazla kullanıcı var, istek işlenemiyor. Daha sonra yeniden deneyin.",
	kickout_user_content: "Bu belge, bilgisayarınızda başka bir pencerede zaten açık. Belgeyi düzenlemeye devam etmek istiyorsanız diğer pencereye dönün.",
	return_to_files: "Dosyalara Geri Dön",
	return_to_library: "Kitaplığa Geri Dön",
	return_to_icn: "Content Navigator'a Geri Dön",
	document_already_open: "Belge zaten açık",
	cannotedit_noentitled_title: "Bu dosyayı birlikte düzenleyemezsiniz",
	cannotedit_noentitled_content1: "Aşağıdaki kullanıcılar şu anda dosyayı düzenliyor:",
	cannotedit_noentitled_content2: "Başkaları düzenlerken bu dosyayı düzenleme yetkiniz yok. Bu dosyayı düzenlemeyi daha sonra deneyin.",
	cannotedit_noentitled_content3: "Aşağıdaki kullanıcı şu anda dosyayı düzenliyor:",
	cannotedit_noentitled_content4: "Dosyayı düzenleyen kişinin birlikte düzenleme yetkisi olmadığından düzenleme oturumuna katılamazsınız. Bu dosyayı daha sonra düzenlemeyi deneyin.",
	toomany_coeditors_title: "Çok fazla kullanıcı",
	toomany_coeditors_content: "Şu anda bu belgeyi çok fazla kullanıcı düzenliyor, bu belge üzerinde aynı anda yalnızca {0} kullanıcı çalışabilir.",
	encrypted_pptdoc_title:"Şifreli dosya",
	encrypted_pptdoc_content:"Dosya parola korumalı. Önce şifresi çözümlenmezse ${productName} içinde düzenlenemez.",
	server_busy_title:"Sunucu çok meşgul",
	server_busy_content:"Bir süre bekleyin ve daha sonra yeniden deneyin.",
	document_encrypt_title:"Şifrelenmiş belge desteklenmiyor",
	document_encrypt_content:"Bu dosya, dosya havuzunda şifrelidir. Güvenlik nedeniyle ${productName} bunu doğrudan düzenleyemez.",
	edit_locked_file: "Diğer düzenleyiciler tarafından kilitlendiğinden dosyayı düzenleyemezsiniz.",
	publish_locked_file: "Kilitli olduğundan bu dosyayı yeni bir sürüm olarak yayınlayamazsınız; ancak içeriğiniz taslağa otomatik olarak kaydedilir.",
	join_locked_file_session: "Bu dosya başkaları tarafından kilitlendiğinden yardımcı düzenleme oturumuna katılamazsınız.",
	no_need_to_convert_title:"Dönüştürme gerekli değil.",
	no_need_to_convert_content:"Dönüştürmek istediğiniz dosya biçimi zaten dosya biçimiyle aynı. Lütfen doğrudan karşıdan yükleyin.",
	warning_icon: "Uyarı simgesi",
	//html viewer error message
	incorrect_web_address_title:"Hatalı web adresi.",
	incorrect_web_address_content:"Web adresi hatalı.  Web adresini girin ve yeniden deneyin.",
	unexpecified_conversion_error_title:"Hata belirtilmemiş.",
	unexpecified_conversion_error_content:"Sunucu belirtilmemiş bir hata döndürdü.",
	encrypted_conversion_error_title:"Şifreli belge desteklenmiyor.",
	encrypted_conversion_error_content:"Dosya parola korumalı. Dosyayı görüntüleyicide görüntülemek için önce dosyanın şifrelendiğinden emin olun.",
	service_busy_title:"Belge açılamadı",
	service_busy_content:"Görüntülemek istediğiniz dosya açılamadı. Sunucu meşgul ya da kullanılamıyor. Daha sonra yeniden deneyin ya da sistem yöneticinize başvurun.",
	empty_doc_title: "Belge boş.",
	empty_doc_content: "Belgenin içeriğe sahip olduğundan emin olun ve sonra yeniden deneyin.",
	corrupted_doc_title: "Dosyaya açılamıyor.",
	corrupted_doc_content: "Dosyada desteklenmeyen içerik, örneğin makrolar var, bu nedenle dosya bu uygulamada görüntülenemiyor.",
	draft_storage_error_title: "Belge açılamıyor.",
	draft_storage_error_content: "İçerik bozuk olduğundan yüklenemiyor. Destek için sistem yöneticinizle iletişim kurun.",
	unexpected_code_title: "${productName} sunucucu beklenmeyen bir kod döndürdü.",
	unexpected_code_content: "${productName} sunucucu beklenmeyen bir kod döndürdü.",
	request_time_out_title: "Belgeyi yükleme işlemi zaman aşımına uğradı.",
	request_time_out_content: "Bu belgenin yüklenmesi çok uzun sürüyor. Lütfen daha sonra yeniden deneyin.",
	problem_id_msg_title: "Bu sorunu sistem yöneticisine bildirin. ",
	problem_id_msg_show: "Ayrıntıları görmek için tıklatın",
	problem_id_msg_hide: "Gizlemek için tıklatın"
})

