({
		SAVE: "Salva",
		UNDO:"Annulla",
		REDO:"Ripristina",
		INSERTROW:"Inserisci riga",
		DELETEROW:"Elimina riga",
		INSERTCOLUMN:"Inserisci colonna",
		DELETECOLUMN:"Elimina colonna",
		FONTSIZE:"Dimensione font",
		FONTCOLOR:"Colore font",
		BOLD:"Grassetto",
		ITALIC:"Corsivo",
		UNDERLINE:"Sottolineato",
		STRIKETHROUGH:"Barrato",
		CURRENCYTIP:"Formatta come valuta",
		PERCENTLABEL:"%",
		PERCENTTIP:"Formatta come percentuale",
		NUMBERFORMAT:"Formato numerico",
		ALIGNLEFT:"Allinea a sinistra",
		ALIGNCENTER:"Centra",
		ALIGNRIGHT:"Allinea a destra",
		SETCELLBORDER:"Imposta bordo cella",
		BACKGROUNDCOLOR:"Colore sfondo",
		TASK:"Assegna sezione",
		COMMENTS:"Aggiungi commento",
		SUBMIT:"Invia",
		MERGECELL: "Unisci/Dividi celle",
		QUICKFORMULA: "Formula rapida",
		WRAPTEXT: "Manda a capo testo",
		EIGHT:"8 pt",
		NINE:"9 pt",
		TEN:"10 pt",
		ELEVEN:"11 pt",
		TWELVE:"12 pt",
		FOURTEEN:"14 pt",
		SIXTEEN:"16 pt",
		EIGHTEEN:"18 pt",
		TWENTY:"20 pt",
		TWENTYTWO:"22 pt",
		TWENTYFOUR:"24 pt",
		NUMBER:"Numero",
		CURRENCY:"Valuta",
		PERCENT:"Percentuale",
		DATE:"Data",
		TIME:"Ora",
		DATETIME: "Data/ora",
		MORECURRENCY:"Altre valute",
		MOREDATE:"Altri formati",
		
		
		CAD: "dollaro canadese",
		USD: "dollaro",
		EUR: "euro",
		CHF: "franco svizzero",
		HKD: "dollaro di Hong Kong",
		DKK: "corona",
		LTL: "lita",
		PHP: "peso",
		BRL: "real",
		RUR: "rublo",
		GBP: "sterlina",
		NLG: "fiorino olandese", // Netherlands
		TWD: "nuovo dollaro taiwanese",
		THB: "baht", // Thailand
		ITL: "lira turca", // Turkey
		BGL: "lev", // Uzbekistan
		VND: "dong", // Vietnam
		KRW: "won",	// Korean 
		CNY: "yuan", // RMB
		JPY: "yen" // Japan Yen
})
