({
	labelNormal: "Vista normal",
	labelPlay: "Reprodueix la visualització de diapositives",
	labelZoomIn: "Apropa",
	labelZoomOut: "Allunya",
	labelFitWidth: "Ajusta a l\'amplada",
	labelReset: "Restableix",
	lablePageUp: "Pàgina anterior",
	lablePageDown: "Pàgina següent",
	labelPrint: "Imprimeix",
	labelBuild: "${productName} ${0}",
	labelVersion: "${productName} ${0} ${1}",
	msgLoading: "Espereu mentre es carrega el vostre document.",
	msgConversionFail: "La conversió ha fallat",
	labelReload: "Torna a carregar",
	labelHelpContent:"Contingut de l\'ajuda",
	labelAbout:"Quant a",
	labelProject:"${productName}",
	labelEdit: "Edita",
	labelHelp: "Ajuda",
	labelCancel: "Cancel·la",
	labelImageTypeIcon: "Document",
	errPrintBeforeLoading: "Per imprimir, no podeu utilitzar el menú del navegador. Feu clic al botó Imprimeix de la barra d\'eines per imprimir el document. No podeu imprimir ara, perquè el contingut no s\'ha carregat completament.",
	errPrintFromBrowserMenu: "Per imprimir el document, feu clic al botó Imprimeix de la barra d\'eines en comptes del menú d\'impressió del navegador.",
	errPrintConversionFail: "No podeu imprimir perquè el contingut no s\'ha convertit correctament.",
	successMsg:"Correcte",
	warningMsg:"Advertiment",
	errorMsg:"Error",
	backtofiles:"Torneu a Fitxers",
	openLatestFile: "Obre el fitxer més recent",
	updatePresentation:"La presentació s'ha actualitzat. ${0} per visualitzar tot el text i les imatges.",
	updateNow: "Obre ara",
	fileUpdated: "La presentació s'ha actualitzat.",
	fileUpdatedContent1: "La presentació s'ha actualitzat. Obriu el fitxer més recent abans d'imprimir.",
	fileUpdatedContent2: "La presentació s'ha actualitzat. Obriu el fitxer més recent abans de reproduir la presentació de diapositives.",
	htmlviewerlimitation: "Aquesta presentació conté animació que no es pot visualitzar",
	labelStopReview: "Atura la revisió",
	labelRejct: "Rebutja",
	labelApprove: "Aprova",
	labelItemNotFountTitle: "No es pot completar l'acció.",
	labelItemNotFountMsg: "Un altre membre de la comunitat ja ha actuat en aquest document. Per obtenir més informació, tanqueu el document i aneu a la pàgina Detalls del fitxer de la biblioteca. "
})

