({
	stViewClient:"Mostrar el cliente de Sametime",
	stChatList:"Pulse para abrir el cliente web de Sametime en una ventana nueva.",
	stWebClient:"HCL Sametime ",
	stStatusMeeting:"En una reunión",
	stStatusAvailable:"Estoy disponible",
	stViewBd:"Mostrar lista de amigos de Sametime",
	stErrorSTServer:"Error al conectar con Sametime",
	stStatusAway:"Estoy ausente",
	stLConnLogIn:"Inicie sesión en HCL Connections para ver el estado en Sametime",
	stActionBar:"Barra de acciones de Sametime",
	stStatusBusy:"Estoy ocupado",
	stLogin:"Iniciar sesión en Sametime",
	stUserOffline:"Estoy desconectado",
	stStartChat:"Pulse aquí para iniciar una conversación",
	stLogout:"Cerrar la sesión de Sametime",
	stDisconnect:"Desconectar de Sametime",
	stViewSTActions:"Pulse para ver las acciones de Sametime",
	stError:"Se ha producido un error. El servicio Sametime no está disponible.",
	stUnableToConnect:"La conexión a Sametime no está disponible. ",
	stConnect:"Conectar a Sametime",
	stNoStatuAvailable:"No hay estado de Sametime disponible",
	stStatusdnt:"No molestar",
	stLoadingSTStatus:"Cargando estado de Sametime...",
	stShareAs:"Compartir documento...",
	stShareDlgTitle:"Compartir documento mediante Sametime...",
	stShareDlgMsgTemplate:"¿Desea compartir '${file_name}' con ${contact_name} como Editor o Lector?",
	stShareEditor:"Editor",
	stShareReader:"Lector",
	stShareSuccessTemplate:"${contact_name}, deseo compartir el documento '${file_name}' con usted:\n<a href=\"${document_link}\">${document_link}</a>"
})
