({	
	dlgTaskCreateTitle: "Přiřadit sekci",  
	dlgTaskDeleteTitle: "Odebrat sekci", 
	dlgTaskEditTitle: "Upravit přiřazení",
	dlgTaskRewordTitle: "Opravit přiřazení",
	dlgTaskHistoryTitle: "O této sekci",
	dlgTaskReopenTitle: "Znovu otevřít přiřazení",
	dlgTaskReassignTitle: "Znovu přiřadit sekci",
	dlgTaskDeleteBtn: "Odstranit",
	creatingTaskAsTODO: "Probíhá ukládání úkolu, který vám byl přiřazen, jako položky úkolu v aplikaci Aktivity",
	creatingTaskAsTODO2: "Probíhá ukládání přiřazeného úkolu",
	creatingTaskAsTODO3: "Probíhá ukládání přiřazených úkolů",
	updatingTask: "Probíhá aktualizace úkolu, který vám byl přiřazen, v aplikaci Aktivity",
	updatingTask2: "Probíhá aktualizace přiřazeného úkolu",
	updatingTask3: "Probíhá aktualizace přiřazených úkolů",
	restoringTask: "Počkejte, dokud nebude přiřazený úkol obnoven v seznamu aktivity.",
	creatingFragment: "Probíhá vytváření soukromého dokumentu pro tuto sekci",
	updatingMaster: "Probíhá zpracování. Je aktualizována sekce v hlavním dokumentu.",
	cannotAccessActivity: "Chyba! Není dostupný server aktivit pro záznam přiřazení. Zkuste to později.",
	cannotAccessActivity2: "Chyba! Není dostupný server pro záznam přiřazení. Zkuste to později.",
	cannotAccessActivityContent: "Není dostupný server aktivit pro záznam přiřazení. Zkuste to později.",
	cannotRecordAssignment: "Není dostupný server aktivit pro záznam přiřazení. Zkuste to později.",
	notMemberofActivity: "V aktivitě nelze zaznamenat vaše přiřazení. Zkontrolujte, zda jste byli do aktivity přidáni, a zopakujte operaci. ",
	cannotLoadActivity: "Pro načtení přiřazení není k dispozici přístup k serveru aktivit. Zkuste to později.",
	cannotLoadActivity2: "Pro načtení přiřazení není k dispozici přístup k serveru. Zkuste to později.",
	cannotLoadAssignment: "Pro načtení tohoto přiřazení není k dispozici přístup k serveru aktivit. Zkuste to později.",
	cannotSupportSocialEdit: "Nemáte oprávnění pro společné úpravy nebo přiřazování sekcí. ",
	cannotDeleteDraft: "Koncept nyní nelze odstranit. Odstraňte soubor později ručně. ",
	taskAlreadyRemoved: "Úloha v tomto dokumentu byla odebrána nebo nemáte povolení k její úpravě.",
	taskAlreadyCompleted: "Úloha je dokončena nebo zrušena.",
	taskAlreadyReassigned: "Úloha byla přeřazena. ",
	assignmentAlreadyExist: "Vybraná oblast již byla přiřazena. ",
	notAllowedEditMaster: "Hlavní dokument nemůžete upravovat. Zkontrolujte, zda k tomu máte oprávnění.",
	notAllowedEditPaticipant: "Pověřená osoba nebo kontrolor nejsou definováni nebo nemají přístup pro úpravy. Zajistěte udělení potřebného přístupu pověřené osobě nebo kontrolorovi. ",
	notValidAssignment: "Přiřazení je neplatné. Je možné, že došlo k poškození některých jeho vlastností na serveru aktivit. Můžete je odebrat klepnutím na volbu Akce > Odebrat přiřazení. ",
	disableBlockerMsg: "Máte aktivováno blokování automaticky otvíraných oken, které brání správnému zobrazení stránky. Povolte zobrazování automaticky otvíraných oken pro web *cn.ibm.com. ",
	writeDesc: "Zápis ${0}: ${1}",
	reviewDesc: "Kontrola ${0}: ${1}",
	reworkDesc: "Přepracování ${0}: ${1}",
	writeCompleteDesc: "Sekci ${0} napsal uživatel ${1}",
	reviewCompleteDesc: "Sekci ${0} zkontroloval uživatel ${1}",
	workingPrivateDesc: "Soukromá práce uživatele ${1} na dokumentu ${0}",
	actions: "Akce",	
	onlyAssignerDeleteTask: "Toto přiřazení nemůžete odstranit, protože nebylo označeno jako dokončené. Odstranit je může jen uživatel, který je vytvořil. ",
	actionBtnEdit: "Upravit přiřazení",
	actionBtnRemove: "Odebrat přiřazení",
	actionBtnAbout: "O této sekci",
	actionBtnMarkComplete: "Označit jako dokončené",
	actionBtnWorkPrivately: "Pracovat soukromě",
	actionBtnApprove: "Schválit tuto sekci",
	actionBtnGotoPrivate: "Přejít k soukromému dokumentu",
	actionBtnCancelPrivate: "Zrušit soukromou práci",
	actionBtnRework: "Je požadováno přepracování",
	actionBtnReopen: "Znovu otevřít přiřazení",
	actionBtnReassign: "Znovu přiřadit sekci",
	creating: "Vytváření...",
	deleting: "Odstraňování...",
	updating: "Aktualizace...",
	loading: "Načítání...",
	restoring: "Obnovení...",
	lockCoeditingTask:"Na stejném přiřazeném úkolu pracuje jiný editor. Zkuste to později."
})
