({
	question:"Frage",
	issue:"Problem",
	toDo:"Unerledigte Aufgabe",
	comment:"Kommentare",
	done:"Fertig ",
	jan:"Januar",
	feb:"Februar",
	mar:"März",
	apr:"April",
	may:"Mai",
	june:"Juni",
	july:"Juli",
	aug:"August",
	sept:"September",
	oct:"Oktober",
	nov:"November",
	dec:"Dezember",
	pm:"12 bis 24 Uhr",
	am:"0 bis 12 Uhr",
	assignTo:"Zuordnen zu: "
})
