/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
    Arrow01_Gray: "Pfeil 01 Grau",
    Arrow02_Gray: "Pfeil 02 Grau",
    Arrow03_Red: "Pfeil 03 Rot",
    Arrow04_Blue: "Pfeil 04 Blau",
    Arrow05_Blue: "Pfeil 05 Blue",
    Arrow06_Yellow: "Pfeil 06 Gelb",
    Arrow07_Red: "Pfeil 07 Rot",
    Arrow08_Gray: "Pfeil 08 Grau",
    Arrow09_Orange: "Pfeil 09 Orange",
    Arrow10_Blue: "Pfeil 10 Blau",
    Arrow11_Blue: "Pfeil 11 Blau",
    Arrow12_Green: "Pfeil 12 Grün",
    Arrow13_Blue: "Pfeil 13 Blau",
    Arrow14_Green: "Pfeil 14 Grün",
    Arrow15_Orange: "Pfeil 15 Orange",
    Arrow16_Gray: "Pfeil 16 Grau",
    CircleArrow01_Green: "Kreisförmiger Pfeil 01 Grün",
    CircleArrow02_Multi: "Kreisförmiger Pfeil 02 Multi",
    CircleArrow03_Multi: "Kreisförmiger Pfeil 03 Multi",
    CircleArrow04_Multi: "Kreisförmiger Pfeil 04 Multi",
    CircleArrow05_Multi: "Kreisförmiger Pfeil 05 Multi",
    CircleArrow06_Multi: "Kreisförmiger Pfeil 06 Multi",
    CircleArrow07_Blue: "Kreisförmiger Pfeil 07 Blau",
    CircleArrow08_Green: "Kreisförmiger Pfeil 08 Grün",
    CircleArrow09_Multi: "Kreisförmiger Pfeil 09 Multi",
    CurvedArrow01_Gray: "Gebogener Pfeil 01 Grau",
    CurvedArrow02_Blue: "Gebogener Pfeil 02 Blau",
    CurvedArrow03_Blue: "Gebogener Pfeil 03 Blau",
    CurvedArrow04_Orange: "Gebogener Pfeil 04 Orange",
    CurvedArrow05_Red: "Gebogener Pfeil 05 Rot",
    CurvedArrow06_Blue: "Gebogener Pfeil 06 Blau",
    CurvedArrow07_Purple: "Gebogener Pfeil 07 Lila",
    CurvedArrow08_Green: "Gebogener Pfeil 08 Grün",
    CurvedArrow09_Gray: "Gebogener Pfeil 09 Grau",
    CurvedArrow10_Blue: "Gebogener Pfeil 10 Blau",
    CurvedArrow11_Orange: "Gebogener Pfeil 11 Orange",
    CurvedArrow12_Blue: "Gebogener Pfeil 12 Blau",
    CurvedArrow13_Green: "Gebogener Pfeil 13 Grün",
    CurvedArrow14_Brown: "Gebogener Pfeil 14 Braun",
    CurvedArrow15_Blue: "Gebogener Pfeil 15 Blau",
    CurvedArrow16_Gray: "Gebogener Pfeil 16 Grau",
    CurvedArrow17_Gray: "Gebogener Pfeil 17 Grau",
    CurvedArrow18_Gray: "Gebogener Pfeil 18 Grau",
    CurvedArrow19_Gray: "Gebogener Pfeil 19 Grau",
    CurvedArrow20_Gray: "Gebogener Pfeil 20 Grau",
    TrendArrow01_Red: "Trendpfeil 01 Rot",
    TrendArrow02_Green: "Trendpfeil 02 Grün",
    TrendArrow03_Orange: "Trendpfeil 03 Orange",
    TrendArrow04_Red: "Trendpfeil 04 Rot",
    TrendArrow05_Orange: "Trendpfeil 05 Orange",
    TrendArrow06_Blue: "Trendpfeil 06 Blau",
    TrendArrow07_Orange: "Trendpfeil 07 Orange",
    TrendArrow08_Yellow: "Trendpfeil 08 Gelb",
    TrendArrow09_Blue: "Trendpfeil 09 Blau",
    TrendArrow10_Blue: "Trendpfeil 10 Blau",
    TrendArrow11_Blue: "Trendpfeil 11 Blau",
    TrendArrow12_Blue: "Trendpfeil 12 Blau",
    TrendArrow13_Red: "Trendpfeil 13 Rot",
    TrendArrow14_Multi: "Trendpfeil 14 Multi",
    TrendArrow15_Blue: "Trendpfeil 15 Blau",
    Bullet01_Circle_DarkRed: "Aufzählungszeichen 01 Kreis Dunkelrot",
    Bullet02_Circle_Blue: "Aufzählungszeichen 02 Kreis Blau",
    Bullet03_Circle_Green: "Aufzählungszeichen 03 Kreis Grün",
    Bullet04_Square_Black: "Aufzählungszeichen 04 Quadrat Schwarz",
    Bullet05_Square_Orange: "Aufzählungszeichen 05 Quadrat Orange",
    Bullet06_Square_Purple: "Aufzählungszeichen 06 Quadrat Purpurrot",
    Bullet07_Diamond_Blue: "Aufzählungszeichen 07 Diamant Blau",
    Bullet08_Diamond_LightBlue: "Aufzählungszeichen 08 Diamant Hellblau",
    Bullet09_Diamond_Red: "Aufzählungszeichen 09 Diamant Rot",
    Bullet10_Star_Yellow: "Aufzählungszeichen 10 Stern Gelb",
    Bullet11_Star_Blue: "Aufzählungszeichen 11 Stern Blau",
    Bullet12_Triangle_Blue: "Aufzählungszeichen 12 Dreieck Blau",
    Bullet13_Triangle_DarkGreen: "Aufzählungszeichen 13 Dreieck Dunkelgrün",
    Bullet14_Arrow_Red: "Aufzählungszeichen 14 Pfeil Rot",
    Bullet15_Arrow_Blue: "Aufzählungszeichen 15 Pfeil Blau",
    Bullet16_Box_Blue: "Aufzählungszeichen 16 Rechteck Blau",
    Bullet17_Box_Red: "Aufzählungszeichen 17 Rechteck Rot",
    Bullet18_Asterisk_LightBlue: "Aufzählungszeichen 18 Sternchen Hellblau",
    Bullet19_Leaves_Red: "Aufzählungszeichen 19 Blatt Rot",
    Bullet20_Target_Blue: "Aufzählungszeichen 20 Zielscheibe Blau",
    Bullet21_Arrow_Blue: "Aufzählungszeichen 21 Pfeil Blau",
    Bullet22_Arrow_DarkBlue: "Aufzählungszeichen 22 Pfeil Dunkelblau",
    Bullet23_Arrow_Brown: "Aufzählungszeichen 23 Pfeil Braun",
    Bullet24_Flag_Red: "Aufzählungszeichen 24 Flagge Rot",
    Bullet25_Flag_Green: "Aufzählungszeichen 25 Flagge Grün",
    Bullet26_X_Red: "Aufzählungszeichen 26 X Rot",
    Bullet27_X_Black: "Aufzählungszeichen 27 X Schwarz",
    Bullet28_Checkmark_Green: "Aufzählungszeichen 28 Häkchen Grün",
    Bullet29_Checkmark_Blue: "Aufzählungszeichen 29 Häkchen Blau",
    Bullet30_Square_DarkRed: "Aufzählungszeichen 30 Quadrat Dunkelrot",
    camera: "Kamera",
    computer1: "Computer 1",
    computer2: "Computer 2",
    computer3: "Computer 3",
    Computer_Cloud: "Computer-Wolke",
    Computer_Desktop: "Computer-Desktop",
    Computer_Laptop_Black: "Computer-Laptop Schwarz",
    Computer_Laptop_Silver: "Computer-Laptop Silber",
    Database: "Datenbank",
    evelope: "Umschlag",
    newspapers: "Zeitungen",
    openevelope: "Geöffneter Umschlag",
    Server: "Server",
    speaker: "Lautsprecher",
    WirelessAccessPoint: "WLAN-Hotspot",
    Cycle01_Transparent: "Kreislauf 01 Transparent",
    Cycle02_Transparent_Blue: "Kreislauf 02 Transparent Blau",
    Cycle03_Blue: "Kreislauf 03 Blau",
    Cycle04_Blue: "Kreislauf 04 Blau",
    Cycle05: "Kreislauf 05",
    Cycle06: "Kreislauf 06",
    Cycle07: "Kreislauf 07",
    Cycle08_Blue: "Kreislauf 08 Blau",
    Cycle09_Orange: "Kreislauf 09 Orange",
    Donut01_LightBlue: "Donut 01 Hellblau",
    Donut02_Blue: "Donut 02 Blau",
    Donut03_Blue: "Donut 03 Blau",
    Donut04_DarkBlue: "Donut 04 Dunkelblau",
    Donut05_DarkBlue: "Donut 05 Dunkelblau",
    Donut06_Blue: "Donut 06 Blau",
    Donut07_Blue: "Donut 07 Blau",
    Graph: "Grafik",
    People01_Blue: "Menschen 01 Blau",
    People02: "Menschen 02",
    Pillars01_Orange: "Säulen 01 Orange",
    Pillars02_LightBlue: "Säulen 02 Hellblau",
    Process01_Blue: "Vorgang 01 Blau",
    Process02_Blue: "Vorgang 02 Blau",
    Process03_Blue: "Vorgang 03 Blau",
    Process04_GoUp_Blue: "Vorgang 04 Ansteigend Blau",
    Process05_GoUp_Red: "Vorgang 05 Ansteigend Rot",
    Process06_GoUp_Yellow: "Vorgang 06 Ansteigend Gelb",
    Process07_Blue: "Vorgang 07 Blau",
    Pyramid01: "Pyramide 01",
    Pyramid02_Blue: "Pyramide 02 Blue",
    Pyramid03: "Pyramide 03",
    Radial01_Green: "Radial 01 Grün",
    Radial02_Green: "Radial 02 Grün",
    Radial03_Sphere: "Radial 03 Kugel",
    Radial04_Sphere_Red: "Radial 04 Kugel Rot",
    Radial05_Sphere_Blue: "Radial 05 Kugel Blau",
    Radial06_Arrows_DarkBlue: "Radial 06 Pfeile Dunkelblau",
    Radial07_Arrows_DarkBlue: "Radial 07 Pfeile Dunkelblau",
    Section_Circle: "Abschnitt Kreis",
    Section_Cubes01: "Abschnitt Würfel 01",
    Section_Cubes02_Blue: "Abschnitt Würfel 02 Blau",
    Section_Cubes03_Orange: "Abschnitt Würfel 03 Orange",
    Section_Cubes04: "Abschnitt Würfel 04",
    Section_Cubes05: "Abschnitt Würfel 05",
    Section_Cuboids01_Blue: "Abschnitt Quader 01 Blau",
    Section_Cuboids02_Blue: "Abschnitt Quader 02 Blau",
    Section_Cuboids03: "Abschnitt Quader 03",
    Section_Gears01: "Abschnitt Zahnrad 01",
    Section_Gears02: "Abschnitt Zahnrad 02",
    Section_Gears03: "Abschnitt Zahnrad 03",
    Section_Hexagon04_Orange: "Abschnitt Sechseck 04 Orange",
    Section_Hexagons01: "Abschnitt Sechsecke 01",
    Section_Hexagons02_Blue: "Abschnitt Sechsecke 02 Blau",
    Section_Hexagons03_Blue: "Abschnitt Sechsecke 03 Blau",
    Section_Leaves01_LightBlue: "Abschnitt Blätter 01 Hellblau",
    Section_Leaves02_Green: "Abschnitt Blätter 02 Grün",
    Section_Pasters01: "Abschnitt Abroller 01",
    Section_Pasters02_Blue: "Abschnitt Abroller 02 Blau",
    Section_Puzzle01: "Abschnitt Puzzle 01",
    Section_Puzzle02: "Abschnitt Puzzle 02",
    Section_Puzzle03: "Abschnitt Puzzle 03",
    Section_Rectangles: "Abschnitt Rechtecke",
    Section_Squares: "Abschnitt Quadrate",
    Section_Triangle: "Abschnitt Dreieck",
    Target: "Zielscheibe",
    Venn01: "Venn 01",
    Venn02: "Venn 02",
    Venn03: "Venn 03",
    Venn04: "Venn 04",
    Venn05: "Venn 05",
    Venn06_Blue: "Venn 06 Blau",
    Venn07_Blue: "Venn 07 Blau",
    Venn08: "Venn 08",
    Blackboard: "Tafel",
    Books: "Bücher",
    Books1: "Bücher 1",
    books2: "Bücher 2",
    Chalk: "Kreide",
    clipboard: "Klemmbrett",
    clock: "Uhr",
    Globe: "Globus",
    Glue: "Klebstoff",
    GraduationCap: "Doktorhut",
    magnifyingglass: "Lupe",
    Microscope: "Mikroskop",
    Notebook: "Notizbuch",
    notepad1: "Notizblock 1",
    notepad2: "Notizblock 2",
    notepad3: "Notizblock 3",
    PaperClip_Blue: "Büroklammer Blau",
    PaperClip_Red: "Büroklammer Rot",
    Pencil: "Bleistift",
    Ruler: "Lineal",
    TestTubes: "Reagenzgläser",
    thumbtack: "Reißzwecke",
    clouds: "Wolken",
    DrippingFaucet: "Tropfender Wasserhahn",
    Earth: "Erde",
    EndangeredAnimals1: "Bedrohte Tiere 1",
    EndangeredAnimals2: "Bedrohte Tiere 2",
    GreenCar: "Umweltauto",
    GreenFactory: "Umweltgerechte Fabrik",
    GreenHouse: "Umweltgerechtes Wohnen",
    Leaf1: "Blatt 1",
    Leaf2: "Blatt 2",
    lightbulb: "Glühbirne",
    LightBulb_Flourescent_Off: "Glühbirne fluoreszierend Aus",
    LightBulb_Flourescent_On: "Glühbirne fluoreszierend An",
    LightBulb_Standard_Off1: "Glühbirne Standard Aus 1",
    LightBulb_Standard_Off2: "Glühbirne Standard Aus 2",
    LightBulb_Standard_On: "Glühbirne Standard An",
    lightningcloud: "Gewitterwolke",
    Pollution_Car: "Umweltverschmutzung Auto",
    Pollution_Factory: "Umweltverschmutzung Fabrik",
    Raindrop: "Regentropfen",
    RecycleBin: "Papierkorb",
    RecycleSymbol: "Recyclingsymbol",
    RenewableEnergySymbol: "Erneuerbare Energien-Symbol",
    RenewableEnergy_Solar: "Erneuerbare Energien Sonne",
    RenewableEnergy_Water: "Erneuerbare Energien Wasser",
    RenewableEnergy_Wind: "Erneuerbare Energien Wind",
    sun: "Sonne",
    Sun1: "Sonne 1",
    Sun2: "Sonne 2",
    sundandcloud: "Sonne und Wolke",
    world: "Welt",
    Agreement: "Vertrag",
    ATM01: "Geldautomat 01",
    ATM02: "Geldautomat 02",
    Balance_Balanced1: "Bilanz Ausgeglichen 1",
    Balance_Balanced2: "Bilanz Ausgeglichen 2",
    Balance_Unbalanced1: "Bilanz Nicht Ausgeglichen 1",
    Balance_Unbalanced2: "Bilanz Nicht Ausgeglichen 2",
    Calculator: "Taschenrechner",
    Chart_Decrease1: "Diagramm Absteigend 1",
    Chart_Decrease2: "Diagramm Absteigend 2",
    Chart_Increase1: "Diagramm Ansteigend 1",
    Chart_Increase2: "Diagramm Ansteigend 2",
    Chart_Plateau: "Diagramm Stagnierend",
    Check: "Scheck",
    Contract: "Vertrag",
    CreditCard_Black: "Kreditkarte Schwarz",
    CreditCard_Cut: "Kreditkarte Prozente",
    CreditCard_Gold: "Kreditkarte Gold",
    Currency_Dollar: "Währung Dollar",
    Currency_Dollars: "Währung Dollars",
    Currency_Stack: "Währung Stapel",
    Currency_StackCoins: "Währung Stapel Münzen",
    GoldBar: "Goldbarren",
    GoldBar_Stack: "Goldbarren Stapel",
    MoneyBag01: "Geldbeutel 01",
    MoneyBag02: "Geldbeutel 02",
    PercentSign: "Prozentzeichen",
    PiggyBank01_Broken: "Sparschwein 01 Zerbrochen",
    PiggyBank02_Broken: "Sparschwein 02 Zerbrochen",
    PiggyBank_Coins: "Sparschwein Münzen",
    PiggyBank_Currency: "Sparschwein Währung",
    Portfolio: "Portfolio",
    PriceTag: "Preiszettel",
    Safe_Closed: "Safe Geschlossen",
    Safe_Empty: "Safe Leer",
    Safe_Full: "Safe Voll",
    Seal_Gold: "Siegel Gold",
    Seal_Red: "Siegel Rot",
    Seal_Silver: "Siegel Silber",
    Wallet_Empty: "Geldbörse Leer",
    Wallet_Full1: "Geldbörse Voll 1",
    Wallet_Full2: "Geldbörse Voll 2",
    BusinessPerson_Female6: "Geschäftsperson Weiblich 6",
    BusinessPerson_Male3: "Geschäftsperson Männlich 3",
    Computer_User_Female1: "Computerbenutzer Weiblich 1",
    ConstructionWorker2: "Bauarbeiter 2",
    Presenter_Female1: "Moderatorin 1",
    Component_Circle01_Transparent_DarkBlue: "Gegliederter Kreis 01 Transparent Dunkelblau",
    Component_Circle02_Transparent_Bule: "Gegliederter Kreis 02 Transparent Blau",
    Component_Circle03_Transparent_Green: "Gegliederter Kreis 03 Transparent Grün",
    Component_Circle04_Transparent_Orange: "Gegliederter Kreis 04 Transparent Orange",
    Component_Circle05_Transparent_Red: "Gegliederter Kreis 05 Transparent Rot",
    Component_Cube01_DarkBlue: "Gegliederter Würfel 01 Dunkelblau",
    Component_Cube02_LightBlue: "Gegliederter Würfel 02 Hellblau",
    Component_Cube03_Green: "Gegliederter Würfel 03 Grün",
    Component_Cube04_Orange: "Gegliederter Würfel 04 Orange",
    Component_Cube05_DarkRed: "Gegliederter Würfel 05 Dunkelrot",
    Component_Cuboid01_DarkBlue: "Gegliederter Quader 01 Dunkelblau",
    Component_Cuboid02_Blue: "Gegliederter Quader 02 Blau",
    Component_Cuboid03_Green: "Gegliederter Quader 03 Grün",
    Component_Cuboid04_Orange: "Gegliederter Quader 04 Orange",
    Component_Cuboid05_Red: "Gegliederter Quader 05 Rot",
    Component_Gear01_DarkBlue: "Gegliedertes Zahnrad 01 Dunkelblau",
    Component_Gear02_LightBlue: "Gegliedertes Zahnrad 02 Hellblau",
    Component_Gear03_Green: "Gegliedertes Zahnrad 03 Grün",
    Component_Gear04_DarkRed: "Gegliedertes Zahnrad 04 Dunkelrot",
    Component_Gear05_Orange: "Gegliedertes Zahnrad 05 Orange",
    Component_Person01_DarkBlue: "Gegliederter Mensch 01 Dunkelblau",
    Component_Person02_Blue: "Gegliederter Mensch 02 Blau",
    Component_Person03_Green: "Gegliederter Mensch 03 Grün",
    Component_Person04_DarkRed: "Gegliederter Mensch 04 Dunkelrot",
    Component_Person05_Orange: "Gegliederter Mensch 05 Orange",
    Component_PuzzlePiece01_DarkBlue: "Gegliedertes Puzzlestück 01 Dunkelblau",
    Component_PuzzlePiece02_Blue: "Gegliedertes Puzzlestück 02 Blau",
    Component_PuzzlePiece03_Green: "Gegliedertes Puzzlestück 03 Grün",
    Component_PuzzlePiece04_Red: "Gegliedertes Puzzlestück 04 Rot",
    Component_PuzzlePiece05_Orange: "Gegliedertes Puzzlestück 05 Orange",
    Component_Sphere01_DarkBlue: "Gegliederte Kugel 01 Dunkelblau",
    Component_Sphere02_LightBlue: "Gegliederte Kugel 02 Hellblau",
    Component_Sphere03_Green: "Gegliederte Kugel 03 Grün",
    Component_Sphere04_DarkRed: "Gegliederte Kugel 04 Dunkelrot",
    Component_Sphere05_Orange: "Gegliederte Kugel 05 Orange",
    Book: "Buch",
    Box01: "Box 01",
    Box02: "Box 02",
    Bulb01_Yellow: "Knolle 01 Gelb",
    Bulb02_Yellow: "Knolle 02 Gelb",
    Calendar: "Kalender",
    Chart: "Diagramm",
    Clipboard: "Klemmbrett",
    Clock: "Uhr",
    Compass: "Kompass",
    Flag01_Red: "Flagge 01 Rot",
    Flag02_Green: "Flagge 02 Grün",
    Flag03_Blue: "Flagge 03 Blau",
    Gift: "Geschenk",
    House: "Haus",
    Icon_Computer01_White: "Symbol Computer 01 Weiß",
    Icon_Computer02_Black: "Symbol Computer 02 Schwarz",
    Icon_Disk01_Blue: "Symbol Disk 01 Blau",
    Icon_Disk02_Green: "Symbol Disk 02 Grün",
    Icon_Document01_Grey: "Symbol Dokument 01 Grau",
    Icon_Document02_Grey: "Symbol Dokument 02 Grau",
    Icon_Document03_Blue: "Symbol Dokument 03 Blau",
    Icon_Document04_Blue: "Symbol Dokument 04 Blau",
    Icon_Envelope01_Blue: "Symbol Umschlag 01 Blau",
    Icon_Envelope02_Yellow: "Symbol Umschlag 02 Gelb",
    Icon_Envelope03_Open_Yellow: "Symbol Umschlag geöffnet 03 Gelb",
    Icon_Envelope04_Open_Yellow: "Symbol Umschlag geöffnet 04 Gelb",
    Icon_Folder01_Yellow: "Symbol Ordner 01 Gelb",
    Icon_Folder02_Yellow: "Symbol Ordner 02 Gelb",
    Icon_Folder03_Open_Yellow: "Symbol Ordner geöffnet 03 Gelb",
    Icon_Folder04_Open_Yellow: "Symbol Ordner geöffnet 04 Gelb",
    Icon_Gear01_Grey: "Symbol Zahnrad 01 Grau",
    Icon_Gear02_Blue: "Symbol Zahnrad 02 Blau",
    Icon_Network01_Blue: "Symbol Netzwerk 01 Blau",
    Icon_Network02: "Symbol Netzwerk 02",
    Icon_Pencil01: "Symbol Bleistift 01",
    Icon_Pencil02: "Symbol Bleistift 02",
    Icon_Printer01_White: "Symbol Drucker 01 Weiß",
    Icon_Printer02_Black: "Symbol Drucker 02 Schwarz",
    Key01: "Schlüssel 01",
    Key02: "Schlüssel 02",
    Lock01_Yellow: "Schloss 01 Gelb",
    Lock02_Yellow: "Schloss 02 Gelb",
    Lock03_Blue: "Schloss 03 Blau",
    Lock04_Blue: "Schloss 04 Blau",
    Magnet: "Magnet",
    MagnifyingGlass: "Lupe",
    Medal: "Medaille",
    Notebook: "Notizbuch",
    Phone: "Telefon",
    PieChart: "Kreisdiagramm",
    Pin: "Reißzwecke",
    PuzzlePiece: "Puzzlestück",
    PuzzlePieces: "Puzzlestücke",
    Roadblock: "Straßensperre",
    Scissors: "Schere",
    Shield01: "Schutzschild 01",
    Shield02_Orange: "Schutzschild 02 Orange",
    Shield03_Blue: "Schutzschild 03 Blau",
    Sign_Ban01: "Schild Verbot 01",
    Sign_Ban02: "Schild Verbot 02",
    Sign_CheckBox01: "Schild Kontrollkästchen 01",
    Sign_CheckBox02_Unchecked: "Schild Kontrollkästchen 02 Leer",
    Sign_Checkmark01_Green: "Schild Häkchen 01 Grün",
    Sign_Checkmark02_Green: "Schild Häkchen 02 Grün",
    Sign_DoNotEnter: "Schild Nicht Betreten",
    Sign_Error01: "Schild Fehler 01",
    Sign_Error02: "Schild Fehler 02",
    Sign_ExclamationPoint01_Red: "Schild Ausrufezeichen 01 Rot",
    Sign_ExclamationPoint02_Orange: "Schild Ausrufezeichen 02 Orange",
    Sign_Help01_Green: "Schild Hilfe 01 Grün",
    Sign_Help02_Blue: "Schild Hilfe 02 Blau",
    Sign_Information: "Schild Information",
    Sign_Null: "Schild Null",
    Sign_QuestionMark01_Blue: "Schild Fragezeichen 01 Blau",
    Sign_QuestionMark02_Red: "Schild Fragezeichen 02 Rot",
    Sign_RadioButton01: "Schild Optionsfeld 01",
    Sign_RadioButton02_Unchecked: "Schild Optionsfeld 02 Nicht Gedrückt",
    Sign_Warning01_Red: "Schild Warnung 01 Rot",
    Sign_Warning02_Orange: "Schild Warnung 02 Orange",
    Sign_X01_Red: "Schild X 01 Rot",
    Sign_X02_Red: "Schild X 02 Rot",
    Star_Yellow: "Stern Gelb",
    Wrench: "Schraubenschlüssel",
    Airplane_Blue: "Flugzeug Blau",
    Bicycle_Blue: "Fahrrad Blau",
    Bus: "Bus",
    Canoe_Blue: "Kanu Blau",
    Car_Red: "Auto Rot",
    Helicopter_Blue: "Helikopter Blau",
    Motorcycle_Red: "Motorrad Rot",
    Pedestrian_Blue: "Fußgänger Blau",
    PersonalTransporter_Green: "Minibus Grün",
    Sailboat_Red: "Segelboot Rot",
    Scooter_Orange: "Roller Orange",
    Train_Red: "Eisenbahn Rot",
    Truck_Blue: "LKW Blau",
    
    aria_category_selector: "Bildkategorieoptionen",
    filterImageGallery: "Bildergalerie filtern"

})
