/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */


define({
        saveTip: "Speichern",
        undoTip: "Rückgängig machen",
        redoTip: "Wiederholen",
        formatPainterTip: "Formatierung kopieren",
        showSorterTip: "Foliensortierung anzeigen",
        hideSorterTip: "Foliensortierung ausblenden",
        webClipboardTip: "Webbasierte Zwischenablage",
        spellCheckTip: "Manuelle Rechtschreibprüfung ausführen",
        createSectionTip: "Abschnitt zuweisen",
        createCellsTip: "Zellen zuweisen",
        createSlideTip: "Folien zuweisen",
        submitTip: "Zuweisung versenden",
        addCommentTip: "Kommentar hinzufügen",
        removeFormatTip: "Formatierung löschen",
        sortAscTip: "Aufsteigend sortieren",
        sortDescTip: "Absteigend sortieren",
        instantFilterTip: "AutoFilter",
        insertChartTip: "Diagramm einfügen",
        startAutofillTip: "Automatische Füllung",
        dataValidationTip: "Datenvalidierung",

        selectFontTip: "Schriftart wählen",
        selectFontSizeTip: "Schriftgrad wählen",
        selectFontNameTip: "Schriftartnamen wählen",
        FontName: "Schriftartname",
        FontSize: "Schriftgrad",
        increaseFontSizeTip: "Schriftgröße erhöhen",
        decreaseFontSizeTip: "Schriftgröße verkleinern",
        boldTip: "Fett",
        italicTip: "Kursiv",
        underlineTip: "Unterstrichen",
        strikeThroughTip: "Durchgestrichen",
        setFontColorTip: "Schriftfarbe festlegen",
        setShadingColorTip: "Schattierungsfarbe festlegen",
        setBackgroundFill: "Hintergrundfüllbereich festlegen",
        setBgColorTip: "Hintergrundfarbe festlegen",
        setBorderTip: "Rahmenart und Farbe festlegen",
        setBorderColorTip: "Rahmenfarbe festlegen",
        setHighlightColor: "Markierungsfarbe festlegen",
        formatPainter: "Formatierung kopieren",
        //	clearFormat:"Remove Formatting",
        zoom: "Zoom",
        selectStyleTip: "Darstellung festlegen",
        styles: "Formatvorlage",
        formatAsCurrencyTip: "Als Währung formatieren",
        formatAsPercentTip: "Als Prozent formatieren",
        decreaseDecimalTip: "Dezimalstellen verringern",
        increaseDecimalTip: "Dezimalstellen erhöhen",
        formatNumberTip: "Zahlenformat",

        numberedListTip: "Nummerierung hinzufügen oder Nummerierungsstil ändern",
        bulletedListTip: "Aufzählungszeichen hinzufügen oder den Stil der Aufzählungszeichen ändern",
        multilevelListTip: "Mehrstufige Liste hinzufügen oder ändern",
        indentTip: "Einzug vergrößern",
        decreaseIndentTip: "Einzug verkleinern",
        alignTip: "Ausrichten",
        leftAlignTip: "Linksbündig",
        centerTip: "Zentriert",
        rightAlignTip: "Rechtsbündig",
        justifyTip: "Blocksatz",
        bottomBorderTip: "Rahmen unten",
        borderTypes: "Rahmentypen",
        borderTip: "Rahmenart festlegen",
        topAlignTip: "Oben ausrichten",
        middleAlignTip: "Mitte ausrichten",
        bottomAlignTip: "Unten ausrichten",
        lineSpacingTip: "Zeilenabstand",
        mergeSplitCellTip: "Zellen verbinden oder teilen",
        wrapNoWrapTip: "Umbruch aktivieren/inaktivieren",
        ltrDirectionTip: "Ersetzen durch Textausrichtung Links nach Rechts",
        rtlDirectionTip: "Ersetzen durch Textausrichtung Rechts nach Links",
        autoDirectionTip: "Textausrichtung ändern",
        toggleSheetDirectionTip: "Blattrichtung ändern",
        setSheetDirectionLTR: "Links nach Rechts",
        setSheetDirectionRTL: "Rechts nach Links",

        addTableTip: "Tabelle hinzufügen",
        insertOrMoveRowTip: "Zeile einfügen oder verschieben",
        insertOrMoveColTip: "Spalte einfügen oder verschieben",
        insertOrDeleteRowTip: "Zeile einfügen oder löschen",
        insertOrDeleteColTip: "Spalte einfügen oder löschen",
        insertFunctionTip: "Funktion einfügen",
        insertImage: "Bild einfügen",
        resizeCol: "Spaltengröße ändern",
        resizeCols: "Größe der Spalten ändern",
        addLink: "Link hinzufügen oder bearbeiten",
        tableStyle: "Tabellendarstellung",

        selectBorder_BottomBorder: "Untere Umrandung",
        selectBorder_TopBorder: "Obere Umrandung",
        selectBorder_LeftBorder: "Linker Rahmen",
        selectBorder_RightBorder: "Rechter Rahmen",
        selectBorder_NoBorder: "Keine Linien",
        selectBorder_AllBorders: "Rahmen gesamt",

        insertOrMoveRow_InsertAbove: "Zeile oberhalb einfügen",
        insertOrMoveRow_InsertBelow: "Zeile unterhalb einfügen",
        insertOrMoveRow_MoveUp: "Zeile nach oben verschieben",
        insertOrMoveRow_MoveDown: "Zeile nach unten verschieben",
        insertOrMoveCol_InsertLeft: "Spalte davor einfügen",
        insertOrMoveCol_InsertRight: "Spalte danach einfügen",
        insertOrMoveCol_InsertBefore: "Spalte davor einfügen",
        insertOrMoveCol_InsertAfter: "Spalte danach einfügen",
        insertOrMoveCol_MoveLeft: "Spalte nach links verschieben",
        insertOrMoveCol_MoveRight: "Spalte nach rechts verschieben",

        insertOrDelete_Delete: "Löschen",

        combineButtonReadTip: "Drücken Sie die Abwärtspfeiltaste, um das Menü zu aktivieren, und navigieren Sie dann mit den Pfeiltasten.",

        lineSpacing_1: "1",
        lineSpacing_12: "1,2",
        lineSpacing_15: "1,5",
        lineSpacing_2: "2",
        lineSpacing_25: "2,5",
        lineSpacing_3: "3",

        percent: "%",
        font_arial: "Arial",

        fontSize: "${0}pt",

        slides: "Eine Folie pro Seite",
        slidesWithNotes: "Folien mit Notizen",
        preparingSlides: "Ihre Folien werden für den Druck vorbereitet...",
        printLayoutOptionLabel: "Drucklayout-Optionen",

        targetRemovedWhenDialogOpen: "Die Aktion kann nicht beendet werden, da das Ziel von einem anderen Editor entfernt wurde.",

        NUMBER: "Zahl",
        CURRENCY: "Währung",
        PERCENT: "Prozent",
        DATE: "Datum",
        TIME: "Uhrzeit",
        DATETIME: "DateTime (Datum und Zeit)",
        MORECURRENCY: "Weitere Währungen nach Geldeinheit",
        MORECURRENCYCODE: "Weitere Währungen nach Währungsbezeichnung",
        MOREDATE: "Weitere Uhrzeit- und Datumsformate",
        TEXT: "Text",
	
        // currency, by currency code
        // NOTE: MUST keep it in order
        CURRENCY_CODE: {
            AED: "Vereinigte Arabische Emirate (Dirham)",
            ARS: "Argentinien (Pesos)",
            AUD: "Australien (Dollar)",
            BGN: "Bulgarien (Leva)",
            BOB: "Bolivien (Bolivianos)",
            BRL: "Brasilien (Real)",
            CAD: "Kanada (Dollar)",
            CHF: "Schweiz (Franken)",
            CLP: "Chile (Pesos)",
            CNY: "China (Yuan Renminbi)",
            COP: "Kolumbien (Pesos)",
            CRC: "Costa Rica (Colon)",
            CZK: "Tschechische Republik (Kronen)",
            DKK: "Dänemark (Kronen)",
            DOP: "Dominikanische Republik (Pesos)",
            EGP: "Ägypten (Pfund)",
            EUR: "Österreich, Belgien, Finnland, Frankreich,  ..., Slowenien, Spanien (Euro)",
            GBP: "England, Vereinigtes Königreich (Pfund Sterling)",
            HKD: "Hongkong (Dollar)",
            HRK: "Kroatien (Kuna)",
            HUF: "Ungarn (Forint)",
            IDR: "Indonesien (Rupiah)",
            ILS: "Israel (New Shekel)",
            INR: "Indien (Rupiah)",
            JPY: "Japan (Yen)",
            KRW: "Korea, Süd (Won)",
            KZT: "Kasachstan (Tenges)",
            MAD: "Marokko (Dirham)",
            MXN: "Mexiko (Pesos)",
            MYR: "Malaysia (Ringgit)",
            NOK: "Norwegen (Krone)",
            NZD: "Neuseeland (Dollar)",
            PAB: "Panama (Balboa)",
            PEN: "Peru (Sol)",
            PHP: "Philippinen (Pesos)",
            PKR: "Pakistan (Rupie)",
            PLN: "Polen (Zloty)",
            PYG: "Paraguay (Guarani)",
            RON: "Rumänien (Neue Lei)",
            RSD: "Serbisch (Kyrillisch), Serbisch (Lateinisch)",
            RUB: "Russland (Rubel)",
            SAR: "Saudi-Arabien (Riyal)",
            SEK: "Schweden (Kronen)",
            SGD: "Singapur (Dollar)",
            SVC: "El Salvador (Colon)",
            THB: "Thailand (Baht)",
            TRY: "Türkei (Lira)",
            TWD: "Taiwan (Dollar)",
            USD: "Ecuador, Puerto Rico, Vereinigte Staaten von Amerika (US-Dollar)",
            UYU: "Uruguay (Pesos)",
            VEF: "Venezuela (Bolivar Fuerte)",
            VND: "Vietnam (Dong)",
            ZAR: "Südafrika (Rand)"
        },
        // for border toolbar
        allBorders: "Alle Rahmen",
        innerBorders: "Innere Rahmen",
        horizontalBorders: "Horizontale Rahmen",
        verticalBorders: "Vertikale Rahmen",
        outerBorders: "Äußere Rahmen",
        borderColor: "Rahmenfarbe",
        leftBorder: "Linker Rahmen",
        topBorder: "Oberer Rahmen",
        rightBorder: "Rechter Rahmen",
        bottomBorder: "Unterer Rahmen",
        clearBorders: "Kein Rahmen",
        BorderStyle_ThinSolid: "Schmal ausgefüllt",
        BorderStyle_ThinDotted: "Schmal gepunktet",
        BorderStyle_ThinDashed: "Schmal gestrichelt",
        BorderStyle_ThickSolid: "Dick ausgefüllt",
        BorderStyle_ThickDotted: "Dick gepunktet",
        BorderStyle_ThickDashed: "Dick gestrichelt"
})

