﻿/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        fileMenu: "Bestand",
        fileMenu_New: "Nieuw",
        fileMenu_NewDocument: "Document",
        fileMenu_NewFromTemplate: "Met sjabloon",
        fileMenu_NewDocumentfromTemplate: "Document op basis van sjabloon",
        fileMenu_NewPresentation: "Presentatie",
        fileMenu_NewPresentationfromTemplate: "Presentatie op basis van sjabloon",
        fileMenu_NewSpreadsheet: "Spreadsheet",
        fileMenu_NewSpreadsheetFromTemplate: "Spreadsheet op basis van sjabloon",
        fileMenu_Open: "Openen",
        fileMenu_Import: "Importeren...",
        //	fileMenu_Close: "Close",
        fileMenu_Discard: "Terug naar laatste versie",
        fileMenu_ClearTrackChange: "Wijzigingsmarkeringen verwijderen",
        fileMenu_SpreadsheetSettings: "Locale voor document instellen...",
        filemenu_revisionhistory: "Revisies",
        fileMenu_Save: "Opslaan",
        fileMenu_SaveAs: "Kopiëren...",
        fileMenu_AutoPublish: "Automatisch publiceren",
        fileMenu_AutoCheckIn: "Automatisch inchecken",
        fileMenu_PublishVersion: "Nu publiceren",
        fileMenu_AutoPublish2: "Automatisch opslaan in repository",
        //	fileMenu_AutoPublish_Tips: "Makes your changes available to readers at the end of each editing session.",
        fileMenu_PublishVersion2: "Nu opslaan in repository",
        fileMenu_AutoPublish3: "Automatisch opslaan in ${0}",
        fileMenu_PublishVersion3: "Nu opslaan in ${0}",      
        fileMenu_SubmitForReview: "Verzenden voor evaluatie...",
        fileMenu_CheckinVersion: "Inchecken...",
        fileMenu_Unlock: "Ontgrendelen",
        //	fileMenu_SaveAsDraft: "as Draft",
        //	fileMenu_SaveInMyDocs: "in My Documents",
        //	fileMenu_SaveToSymphony: "to Lotus Symphany",
        fileMenu_DownloadAs: "Downloaden als",
        fileMenu_PDF: "PDF",
        fileMenu_ODF: "ODF",
        fileMenu_DOC: "Microsoft Word 97- 2007 (*.doc)",
        fileMenu_ODS: "ODS",
        fileMenu_XLS: "Microsoft Excel 97-2007 (*.xls) ",
        fileMenu_ShareWith: "Delen...",
        fileMenu_ExportAsPDF: "PDF",
        fileMenu_ExportAsODF: "ODF",
        fileMenu_ExportAsPPT: "Microsoft Powerpoint 97- 2007 (*.ppt)",
        //	fileMenu_WebPreview: "Web Preview",
        fileMenu_PrintToPDF: "Afdrukken naar PDF...",
        fileMenu_ViewFileDetails: "Bestandsgegevens bekijken...",
        fileMenu_RecentFile: "Recente bestanden",
        fileMenu_Open: "Openen",
        fileMenu_Download: "Downloaden",
        fileMenu_Print: "Afdrukken",
        fileMenu_Export: "Exporteren",
        fileMenu_ExportToCSV: "CSV",
        fileMenu_ExportToPDF: "PDF (.pdf)",
        fileMenu_ExportToMarkdown: "Markdown (.md)",
        fileMenu_ExportToMS: "Microsoft Office-indeling (.${FILEEXTENSION})",
        fileMenu_ExportToODF: "Open Document-indeling (.${FILEEXTENSION})",
        fileMenu_PgSetup: "Pagina-indeling...",

        editMenu: "Bewerken",
        editMenu_Undo: "Ongedaan maken",
        editMenu_Redo: "Opnieuw uitvoeren",
        editMenu_Cut: "Knippen",
        editMenu_Copy: "Kopiëren",
        editMenu_Paste: "Plakken",
        editMenu_DeleteSlide: "Dia wissen",
        editMenu_SelectAll: "Alles selecteren",
        editMenu_Find: "Zoeken...",
        editMenu_Replace: "Vervangen...",
        editMenu_FindReplace: "Zoeken en vervangen...",
        editMenu_EditLink: "Link toevoegen of bewerken",
        editMenu_DeleteSheet: "Werkblad wissen...",
        editMenu_RenameSheet: "Naam werkblad wijzigen...",
        editMenu_HideSheet: "Werkblad verbergen",
        editMenu_MoveSheet: "Werkblad verplaatsen...",
        editMenu_DeleteRow: "Rij wissen",
        editMenu_DeleteColumn: "Kolom wissen",
        editMenu_DeleteCellLeft: "Cellen wissen en naar links verschuiven",
        editMenu_DeleteCellUp: "Cellen wissen en omhoog verschuiven",
        editMenu_ClearCell: "Inhoud wissen",

        viewMenu: "Beeld",
        viewMenu_Master: "Master",
        viewMenu_Notifications: "Meldingen",
        viewMenu_SlideSorter: "Diasorteerder",
        viewMenu_SpeakerNotes: "Sprekersnotities",
        viewMenu_Toolbar_Basic: "Eenvoudig",
        viewMenu_Toolbar_Advanced: "Geavanceerd",
        viewMenu_Toolbar_None: "Geen",
        viewMenu_Toolbar: "Werkbalk",
        viewMenu_Statusbar: "Statusbalk",
        viewMenu_Navigator: "Navigator...",
        //viewMenu_Sidebar: "Sidebar",
        viewMenu_ShowHideIndicators: "Indicators voor gelijktijdige bewerking afbeelden",
        viewMenu_Assignment: "Toewijzingsindicators",
        viewMenu_Bookmark: "Bladwijzers",
        viewMenu_Coediting: "Markeringen voor gelijktijdige bewerking",
        viewMenu_Rulers: "Linialen",
        viewMenu_WebLayout: "Web-layout",
        viewMenu_AutomaticSpellCheck: "Spellingcontrole terwijl u typt",
        viewMenu_Formulabar: "Formulebalk",
        viewMenu_moveRight: "Enter verplaatst cursor naar rechts",
        viewMenu_showFullString: "Inhoud in cellen verlengen",
        viewMenu_Doc: "Document bekijken",
        viewMenu_Templates: "Sjablonen",
        viewMenu_GridLines: "Rasterlijnen verbergen",
        viewMenu_UnsupportWarning: "Berichten over niet-ondersteunde functies afbeelden",
        viewMenu_HiddenSheets: "Verborgen werkbladen",
        viewMenu_FreezeRows: "Rijen fixeren",
        viewMenu_FreezeColumns: "Kolommen fixeren",
        viewMenu_NoFrozenRows: "Geen rijen gefixeerd",
        viewmenu_NoFrozenColumns: "Geen kolommen gefixeerd",
        viewMenu_FreezeXRows: "${0} rijen fixeren",
        viewMenu_FreezeOneRow: "${0} rij fizeren",
        viewMenu_FreezeXColumns: "${0} kolommen fixeren",
        viewMenu_FreezeOneColumn: "${0} kolom fixeren",
        viewMenu_CarriageReturn: "Opmaakmarkeringen",
        viewMenu_Navigation: "Navigatievenster",
        viewMenu_ACL: "Bewerkbare gebieden",
        viewMenu_GridOnOff: "Rasterlijnen",
        viewMenu_ObserverMode: 'Observatiemodus',

        createMenu: "Invoegen",
        createMenu_NewSlide: "Nieuwe dia",
        createMenu_DuplicateSlide: "Dia kopiëren",
        createMenu_ImageFromFile: "Afbeelding...",
        createMenu_TextBox: "Tekstvak",
        createMenu_Shape: "Vorm",
        createMenu_break: "Afbreken",
        createMenu_RowAbove: "Rij boven",
        createMenu_RowBelow: "Rij onder",
        createMenu_ColumnRight: "Kolom rechts",
        createMenu_ColumnLeft: "Kolom links",
        createMenu_Sheet: "Werkblad...",
        createMenu_Image: "Afbeelding...",
        createMenu_Comments: "Commentaar...",
        createMenu_WebLink: "Weblink...",
        createMenu_SpecialCharacter: "Speciaal teken...",
        createMenu_Function: "Functie...",
        createMenu_Fromtemplate: "Maken op basis van sjabloon",

        insertMenu: "Invoegen",
        insertMenu_break: "Paginaeinde",
        insertMenu_sectionbreak: "Sectiescheiding",
        insertMenu_Bookmark: "Bladwijzer...",
        insertMenu_WebLink: "Link...",
        insertMenu_SpecialCharacter: "Speciaal teken...",
        insertMenu_HorizontalLine: "Horizontale lijn",
        insertMenu_Header: "Titel",
        insertMenu_Footer: "Voettekst",
        insertMenu_TableOfContents: "Inhoudsopgave",

        insertMenu_HeaderFooter: "Koptekst/voettekst",
        insertMenu_HF_Edit: "Bewerken",
        insertMenu_HF_Hide: "Verbergen",
        insertMenu_Endnotes: "Eindnoten",
        insertMenu_RowAbove: "Rij boven",
        insertMenu_PageNumber: "Paginanummer",
        insertMenu_PageNumberTop: "Bovenaan pagina",
        insertMenu_PageNumberBottom: "Onderaan pagina",
        insertMenu_PageNumberCurr: "Huidige positie",
        insertMenu_TotalPageNumber: "Pagina 1 van N",
        insertMenu_Date: "Datum...",
        insertMenu_Time: "Tijd...",
        insertMenu_Fields: "Velden",
        //    insertMenu_Comment: "Comment",
        insertMenu_CellRight: "Cellen en naar rechts verschuiven",
        insertMenu_CellDown: "Cellen en omlaag verschuiven",
        insertMenu_RowBelow: "Rij onder",
        insertMenu_ColumnBefore: "Kolom voor",
        insertMenu_ColumnAfter: "Kolom achter",
        insertMenu_Sheet: "Werkblad...",
        insertMenu_Image: "Afbeelding...",
        insertMenu_DuplicateSheet: "Werkblad kopiëren",
        insertMenu_Function: "Functie",
        insertMenu_FunctionSum: "SUM",
        insertMenu_FunctionAverage: "AVERAGE",
        insertMenu_FunctionCount: "COUNT",
        insertMenu_FunctionMax: "MAX",
        insertMenu_FunctionMin: "MIN",
        insertMenu_FunctionMore: "Meer functies...",
        insertMenu_NameRange: "Benoemd bereik",
        insertMenu_NameRangeNew: "Nieuw bereik...",
        insertMenu_NameRangeManage: "Bereiken beheren...",
        insertMenu_Chart: "Diagram...",

        contextMenu_insertCellRight: "Cellen invoegen en naar rechts verschuiven",
        contextMenu_insertCellDown: "Cellen invoegen en omlaag verschuiven",
        contextMenu_InsertRowAbove: "Rij invoegen boven",
        contextMenu_InsertRowBelow: "Rij invoegen onder",
        contextMenu_InsertColumnBefore: "Kolom invoegen voor",
        contextMenu_InsertColumnAfter: "Kolom invoegen na",
        contextMenu_DownloadImage: "Downloaden als afbeelding",

        formatMenu: "Opmaak",
        formatMenu_Columns: "Kolommen",
        formatMenu_DefaultFormatting: "Standaardopmaak",
        formatMenu_Template: "Stijlen...",
        contextMenu_Template: "Tabelstijlen...",
        formatMenu_LineSpacing: "Regelafstand",
        formatMenu_LineSpacing1: "1",
        formatMenu_LineSpacing12: "1,2",
        formatMenu_LineSpacing15: "1,5",
        formatMenu_LineSpacing2: "2",
        formatMenu_LineSpacing25: "2,5",
        formatMenu_LineSpacing3: "3",
        formatMenu_TextProperties: "Teksteigenschappen",
        formatMenu_PageBreakBefore: "Paginaeinde boven invoegen",
        formatMenu_KeepLines: "Regels bijeenhouden",
        formatMenu_WidowControl: "Zwevende regels voorkomen",
        formatMenu_Pagination: "Alinea-eigenschappen",
        formatMenu_Bold: "Vet",
        formatMenu_Italic: "Cursief",
        formatMenu_Underline: "Onderstrepen",
        formatMenu_Strikethrough: "Doorhalen",
        formatMenu_IncreaseSize: "Grotere letters",
        formatMenu_DecreaseSize: "Kleinere letters",
        formatMenu_ImageProperties: "Eigenschappen afbeelding...",
        formatMenu_ChartProperties: "Eigenschappen diagram...",
        formatMenu_EditChart: "Diagram bewerken",
        formatMenu_InsertChart: "Diagram invoegen",
        formatMenu_Properties: "Eigenschappen...",
        formatMenu_Heading: "Kop",
        formatMenu_Normal: "Normaal",
        formatMenu_Title: "Titel",
        formatMenu_Subtitle: "Subtitel",
        formatMenu_Heading1: "Kop 1",
        formatMenu_Heading2: "Kop 2",
        formatMenu_Heading3: "Kop 3",
        formatMenu_Heading4: "Kop 4",
        formatMenu_Heading5: "Kop 5",
        formatMenu_Heading6: "Kop 6",
        formatMenu_Heading7: "Kop 7",
        formatMenu_Heading8: "Kop 8",
        formatMenu_Heading9: "Kop 9",
        formatMenu_BulletedList: "Lijst met opsommingstekens",
        formatMenu_NumberedList: "Genummerde lijst",
        formatMenu_OutLine: "Meervoudige lijst",
        formatMenu_Superscript: "Superscript",
        formatMenu_Subscript: "Subscript",
        formatMenu_Align: "Uitlijnen",
        formatMenu_Left: "Links",
        formatMenu_Right: "Rechts",
        formatMenu_Center: "Centreren",
        formatMenu_Justify: "Uitvullen",
        formatMenu_Text_Direction: "Tekstrichting",
        formatMenu_Ltr: "Links naar rechts",
        formatMenu_Rtl: "Rechts naar links",
        formatMenu_LineSpacing: "Regelafstand",
        formatMenu_LineSpacing1: "1,0",
        formatMenu_LineSpacing115: "1,15",
        formatMenu_LineSpacing15: "1,5",
        formatMenu_LineSpacing2: "2,0",
        formatMenu_LineSpacing25: "2,5",
        formatMenu_LineSpacing3: "3,0",
        formatMenu_Top: "Boven",
        formatMenu_Bottom: "Onder",
        formatMenu_Middle: "Midden",
        formatMenu_Direction: "Tekstrichting",
        formatMenu_Rtl: "Rechts naar links",
        formatMenu_Ltr: "Links naar rechts",
        formatMenu_Auto: "Contextueel",
        formatMenu_SheetDirection: "Bladrichting",
        formatMenu_SheetRtl: "Rechts naar links",
        formatMenu_SheetLtr: "Links naar rechts",
        formatMenu_Indent: "Inspringing vergroten",
        formatMenu_DecreaseIndent: "Inspringing verkleinen",
        formatMenu_ClearFormat: "Opmaak verwijderen",
        formatMenu_RowHeight: "Rijhoogte",
        formatMenu_ColumnWidth: "Kolombreedte",
        formatMenu_ShowRow: "Rij afbeelden",
        formatMenu_HideRow: "Rij verbergen",
        formatMenu_ShowColumn: "Kolom afbeelden",
        formatMenu_HideColumn: "Kolom verbergen",
        formatMenu_WrapText: "Tekstterugloop",
        formatMenu_Number: "Getal",
        formatMenu_FontArial: "Arial",
        formatMenu_FontComicSansMS: "Comic Sans MS",
        formatMenu_FontCourierNew: "Courier New",
        formatMenu_FontGeorgia: "Georgia",
        formatMenu_FontLucidaSansUnicode: "Lucida Sans Unicode",
        formatMenu_FontTahoma: "Tahoma",
        formatMenu_FontTimesNewRoman: "Times New Roman",
        formatMenu_FontTrebuchetMS: "Trebuchet MS",
        formatMenu_FontVerdana: "Verdana",
        formatMenu_FontName: "Lettertype",

        layoutMenu: "Layout",
        layoutMenu_SlideLayout: "Dia-layout...",
        layoutMenu_SlideDesign: "Masterstijl...",
        layoutMenu_DefaultFormatting: "Standaardopmaak",
        layoutMenu_Textprop_Bold: "Vet",
        layoutMenu_Textprop_Italic: "Cursief",
        layoutMenu_Textprop_Underline: "Onderstrepen",
        layoutMenu_Textprop_Strikethrough: "Doorhalen",
        layoutMenu_TextProp: "Teksteigenschappen",
        LayoutMenu_RowHeight: "Rijhoogte...",
        LayoutMenu_ColumnWidth: "Kolombreedte...",
        LayoutMenu_ShowRow: "Rij afbeelden",
        LayoutMenu_HideRow: "Rij verbergen",
        LayoutMenu_RenameSheet: "Naam werkblad wijzigen...",
        LayoutMenu_MoveSheet: "Werkblad verplaatsen",

        tableMenu: "Tabel",
        tableMenu_Create: "Maken...",
        tableMenu_CreateFromTemplate: "Maken op basis van sjabloon",
        tableMenu_Delete: "Wissen",
        tableMenu_SetTableColor: "Celkleur",
        tableMenu_CreateTable: "Tabel maken",
        tableMenu_Cell: "Cel",
        tableMenu_CellMergeCells: "Cellen samenvoegen",
        tableMenu_CellAlignLeft: "Links uitlijnen",
        tableMenu_CellAlignCenter: "Centreren",
        tableMenu_CellAlignRight: "Rechts uitlijnen",
        tableMenu_CellClearContents: "Inhoud wissen",
        tableMenu_CellProperties: "Celeigenschappen...",
        tableMenu_Row: "Rij",
        tableMenu_InsertRowAbove: "Rij invoegen boven",
        tableMenu_InsertRowBelow: "Rij invoegen onder",
        tableMenu_MoveRowAbove: "Rij omhoog",
        tableMenu_MoveRowBelow: "Rij omlaag",
        tableMenu_RowInsertRow: "Rij invoegen...",
        tableMenu_RowInsertRowAbove: "Rij invoegen boven",
        tableMenu_RowInsertRowBelow: "Rij invoegen onder",
        tableMenu_RowMoveRowAbove: "Rij omhoog",
        tableMenu_RowMoveRowBelow: "Rij omlaag",
        tableMenu_RowDelete: "Wissen",
        tableMenu_RowRepeat: "Koprij herhalen",
        tableMenu_InsertColumnBefore: "Kolom invoegen voor",
        tableMenu_InsertColumnAfter: "Kolom invoegen na",
        tableMenu_MoveColumnBefore: "Kolom naar links",
        tableMenu_MoveColumnAfter: "Kolom naar rechts",
        tableMenu_ResizeColumn: "Kolombreedte wijzigen",
        tableMenu_ResizeColumns: "Kolommenbreedtes wijzigen",
        tableMenu_MarkasCategory: "Markeren als categorie",
        tableMenu_ColumnInsertColumn: "Kolom invoegen...",
        tableMenu_ColumnAddColumnBefore: "Kolom invoegen voor",
        tableMenu_ColumnAddColumnAfter: "Kolom invoegen na",
        tableMenu_ColumnMoveColumnAfter: "Kolom naar rechts",
        tableMenu_ColumnMoveColumnBefore: "Kolom naar links",
        tableMenu_ColumnDelete: "Wissen",
        tableMenu_ColumnSortAscending: "Oplopend sorteren",
        tableMenu_ColumnSortDescending: "Aflopend sorteren",
        tableMenu_Column: "Kolom",
        tableMenu_Style: "Stijl",
        tableMenu_TableProperties: "Tabeleigenschappen...",

        teamMenu: "Team",
        teamMenu_AddComment: "Commentaar toevoegen",
        teamMenu_AssignCells: "Cellen toewijzen",
        teamMenu_AssignSection: "Sectie toewijzen",
        teamMenu_EditAssignment: "Toewijzing bewerken",
        teamMenu_MarkSectionComplete: "Sectie markeren als Voltooid",
        teamMenu_MarkAssignmentComplete: "Toewijzing markeren als Voltooid",
        teamMenu_WorkPrivatelyOnSection: "Alleen aan sectie werken",
        teamMenu_CancelPrivateWork: "Alleen werken annuleren",
        teamMenu_ApproveSection: "Sectie goedkeuren",
        teamMenu_ApproveAssignment: "Toewijzing goedkeuren",
        teamMenu_ReturnSectionForRework: "Sectie retourneren voor revisie",
        teamMenu_ReturnAssignmentForRework: "Toewijzing retourneren voor revisie",
        teamMenu_RemoveSectionAssignment: "Sectietoewijzing verwijderen",
        teamMenu_RemoveCellAssignment: "Celtoewijzing verwijderen",
        teamMenu_RemoveCompletedAssignments: "Voltooide toewijzingen verwijderen",
        teamMenu_AboutThisSection: "Informatie over deze sectie",
        teamMenu_AboutAssignment: "Informatie over deze toewijzing",

        presentationMenu: "Presentatie",
        presentationMenu_SlideShow: "Diapresentatie afspelen",
        presentationMenu_SlideShowWithCoview: "Gedeelde diapresentatie afspelen",
        presentationMenu_SlideTransitions: "Diaovergang toepassen...",
        presentationMenu_SlideShowFromCurrent: "Afspelen vanaf huidige dia",
        presentationMenu_EmptyCoviewInvites: "Geen actieve gedeelde diapresentatie",
        presentationMenu_CoviewInvites: "Actieve gedeelde diapresentatie",

        dataMenu: "Gegevens",
        dataMenu_Sort: "Sorteren...",
        dataMenu_SortAsc: "Oplopend sorteren",
        dataMenu_SortDesc: "Aflopend sorteren",
        dataMenu_ACL: "Beschermde gebieden",
        dataMenu_ACL_DELETE: "Alle machtigingen wissen",
        dataMenu_Validity: "Geldigheid",
        dataMenu_InstantFilter: "Instantfilter",
        dataMenu_Validation: "Validatie...",

        toolsMenu: "Extra",
        toolsMenu_AutoComplete: "Celinhoud automatisch aanvullen",
        toolsMenu_SelectDictionary: "Woordenboeken voor spellingcontrole",
        toolsMenu_Dictionary_ca_CT: "Catalaans",
        toolsMenu_Dictionary_cs_CZ: "Tsjechisch (Tsjechië)",
        toolsMenu_Dictionary_da_DK: "Deens (Denemarken)",
        toolsMenu_Dictionary_nl_NL: "Nederlands (Nederland)",
        toolsMenu_Dictionary_en_AU: "Engels (Australië)",
        toolsMenu_Dictionary_en_GB: "Engels (Groot-Brittannië)",
        toolsMenu_Dictionary_en_US: "Engels (Verenigde Staten)",
        toolsMenu_Dictionary_fi_FI: "Fins (Finland)",
        toolsMenu_Dictionary_fr_FR: "Frans (Frankrijk)",
        toolsMenu_Dictionary_fr_CA: "Frans (Canada)",
        toolsMenu_Dictionary_de_DE: "Duits (Duitsland)",
        toolsMenu_Dictionary_de_CH: "Duits (Zwitserland)",
        toolsMenu_Dictionary_el_GR: "Grieks (Griekenland)",
        toolsMenu_Dictionary_it_IT: "Italiaans (Italië)",
        toolsMenu_Dictionary_pl_PL: "Pools (Polen)",
        toolsMenu_Dictionary_pt_BR: "Portugees (Brazilië)",
        toolsMenu_Dictionary_pt_PT: "Portugees (Portugal)",
        toolsMenu_Dictionary_ru_RU: "Russisch (Rusland)",
        toolsMenu_Dictionary_es_ES: "Spaans (Spanje)",
        toolsMenu_Dictionary_sv_SE: "Zweeds (Zweden)",
        toolsMenu_Dictionary_nb_NO: "Noors (Bokmål)",
        toolsMenu_Dictionary_nn_NO: "Noors (Nynorsk)",
        toolsMenu_Dictionary_he_IL: "Hebreeuws (Israël)",
        toolsMenu_SpellCheck: "Handmatige spellingcontrole uitvoeren...",
        toolsMenu_Preferences: "Voorkeuren",
        toolsMenu_Task: "Taak",
        toolsMenu_Task_Assigntask: "Taak toewijzen",
        teamMenu_AssignSlide: "Dia toewijzen",
        teamMenu_AssignSlides: "Dia's toewijzen",
        teamMenu_EditSlide: "Diatoewijzing bewerken",
        teamMenu_ReopenSlideAssignment: "Diatoewijzing opnieuw openen",
        teamMenu_ReopenSlideAssignments: "Diatoewijzingen opnieuw openen",
        teamMenu_ReassignSlide: "Dia opnieuw toewijzen",
        teamMenu_ReassignSlides: "Dia\'s opnieuw toewijzen",
        teamMenu_MarkSlidesComplete: "Dia markeren als Voltooid",
        teamMenu_MarkSlidesCompletes: "Dia\'s markeren als Voltooid",
        teamMenu_ApproveSlide: "Dia goedkeuren",
        teamMenu_ApproveSlides: "Dia\'s goedkeuren",
        teamMenu_ReturnForRework: "Dia retourneren voor revisie",
        teamMenu_ReturnForReworks: "Dia\'s retourneren voor revisie",
        teamMenu_RemoveAssignment: "Diatoewijzing verwijderen",
        teamMenu_AboutThisSlide: "Informatie over deze dia",

        addOnsMenu: "Addons",

        helpMenu: "Help",
        helpMenu_About: "Info",
        helpMenu_Overview: "Inhoudsopgave Help",
        helpMenu_NewFeatures: "Nieuwe functies",
        helpMenu_Tour: "Rondleiding",

        accel_fileMenu_Save: "Ctrl+S",
        accel_fileMenu_Save_Mac: "\u2318S",
        accel_fileMenu_Print: "Ctrl+P",
        accel_fileMenu_Print_Mac: "\u2318P",
        accel_editMenu_SelectAll: "Ctrl+A",
        accel_editMenu_SelectAll_Mac: "\u2318A",
        accel_editMenu_Undo: "Ctrl+Z",
        accel_editMenu_Undo_Mac: "\u2318Z",
        accel_editMenu_Redo: "Ctrl+Y",
        accel_editMenu_Redo_Mac: "\u2318Y",
        accel_editMenu_Cut: "Ctrl+X",
        accel_editMenu_Cut_Mac: "\u2318X",
        accel_editMenu_Copy: "Ctrl+C",
        accel_editMenu_Copy_Mac: "\u2318C",
        accel_editMenu_Paste: "Ctrl+V",
        accel_editMenu_Paste_Mac: "\u2318V",
        accel_editMenu_Find: "Ctrl+F",
        accel_editMenu_Find_Mac: "\u2318F",
        accel_insertMenu_Link: "Ctrl+K",
        accel_insertMenu_Link_Mac: "\u2318K",
        accel_insertMenu_Header: "Ctrl+Shift+H",
        accel_insertMenu_Header_Mac: "\u21e7\u2318H",
        accel_insertMenu_Footer: "Ctrl+Shift+F",
        accel_insertMenu_Footer_Mac: "\u21e7\u2318F",
        accel_formatMenu_Textprop_Bold: "Ctrl+B",
        accel_formatMenu_Textprop_Bold_Mac: "\u2318B",
        accel_formatMenu_Textprop_Italic: "Ctrl+I",
        accel_formatMenu_Textprop_Italic_Mac: "\u2318I",
        accel_formatMenu_Textprop_FormatPainter: "Ctrl+Shift+C, Ctrl+Shift+V",
        accel_formatMenu_Textprop_FormatPainter_Mac: "\u21e7\u2318C, \u21e7\u2318V",
        accel_formatMenu_Textprop_Underline: "Ctrl+U",
        accel_formatMenu_Textprop_Underline_Mac: "\u2318U",
        accel_formatMenu_Headingprop_P: "Ctrl+Shift+0",
        accel_formatMenu_Headingprop_H1: "Ctrl+Shift+1",
        accel_formatMenu_Headingprop_H2: "Ctrl+Shift+2",
        accel_formatMenu_Headingprop_H3: "Ctrl+Shift+3",
        accel_formatMenu_Headingprop_H4: "Ctrl+Shift+4",
        accel_formatMenu_Headingprop_H5: "Ctrl+Shift+5",
        accel_formatMenu_Headingprop_H6: "Ctrl+Shift+6",
        accel_formatMenu_Superscript: "Ctrl+.",
        accel_formatMenu_Superscript_Mac: "\u2318.",
        accel_formatMenu_Subscript: "Ctrl+,",
        accel_formatMenu_Subscript_Mac: "\u2318,",
        accel_formatMenu_Left: "Ctrl+Shift+L",
        accel_formatMenu_Left_Mac: "\u21e7\u2318L",
        accel_formatMenu_Right: "Ctrl+Shift+R",
        accel_formatMenu_Right_Mac: "\u21e7\u2318R",
        accel_formatMenu_Center: "Ctrl+Shift+E",
        accel_formatMenu_Center_Mac: "\u21e7\u2318E",
        accel_formatMenu_Justify: "Ctrl+Shift+J",
        accel_formatMenu_Justify_Mac: "\u21e7\u2318J",
        accel_formatMenu_Indent: "Ctrl+M",
        accel_formatMenu_Indent_Mac: "\u2318M",
        accel_formatMenu_DecreaseIndent: "Ctrl+Shift+M",
        accel_formatMenu_DecreaseIndent_Mac: "\u21e7\u2318M",
        accel_teamMenu_AddComment: "Shift+F2",

        ctxMenuSmartTable: 'Tabel',
        ctxMenuTableProperties: "Tabeleigenschappen",
        ctxMenuDeleteST: 'Wissen',
        ctxMenuDeleteSTTable: 'Tabel wissen',
        ctxMenuChgSTStyle: 'Stijl wijzigen',
        ctxMenuShowCaption: 'Bijschrift afbeelden',
        ctxMenuHideCaption: 'Bijschrift verbergen',
        ctxMenuResizeST: 'Formaat wijzigen',
        ctxMenuResizeColumnsST: 'Kolommenbreedtes wijzigen',
        ctxMenuSTRow: 'Rij',
        ctxMenuAddSTRowAbv: 'Rij invoegen boven',
        ctxMenuAddSTRowBlw: 'Rij invoegen onder',
        ctxMenuMoveSTRowUp: 'Rij omhoog',
        ctxMenuMoveSTRowDown: 'Rij omlaag',
        ctxMenuDelSTRow: 'Wissen',
        ctxMenuRepeatRow: 'Koprij herhalen',
        ctxMenuSTCol: 'Kolom',
        ctxMenuAddSTColBfr: 'Kolom invoegen voor',
        ctxMenuAddSTColAft: 'Kolom invoegen na',
        ctxMenuMoveSTColBefore: 'Kolom naar links',
        ctxMenuMoveSTColAfter: 'Kolom naar rechts',
        ctxMenuDelSTCol: 'Wissen',
        ctxMenuSortSTColAsc: 'Oplopend sorteren',
        ctxMenuSortSTColDesc: 'Aflopend sorteren',
        ctxMenuShowAllFacets: 'Categorieën afbeelden',
        ctxMenuHideAllFacets: 'Categorieën verbergen',
        ctxMenuSTCell: 'Cel',
        ctxMenuMergeCells: 'Cellen samenvoegen',
        ctxMenuMergeDown: 'Samenvoegen met onderliggende cel',
        ctxMenuVerSplit: 'Verticaal splitsen',
        ctxMenuHorSplit: 'Horizontaal splitsen',
        ctxMenuSplitCells: 'Cellen splitsen...',
        splitCells: 'Cel splitsen',
        ctxMenuAlignTextLeft: 'Links uitlijnen',
        ctxMenuAlignTextCenter: 'Centreren',
        ctxMenuAlignTextRight: 'Rechts uitlijnen',
        ctxMenuClearSTCellContent: 'Inhoud wissen',
        ctxMenuMakeHeaderRow: 'Geselecteerde rij als koptekst gebruiken',
        ctxMenuMakeNonHeaderRow: 'Stijl koptekst verwijderen',
        ctxMenuMakeHeaderCol: 'Geselecteerde kolom als koptekst gebruiken',
        ctxMenuMakeNonHeaderCol: 'Stijl koptekst verwijderen',
        SHEET_CONTEXT_Hide: "Verbergen", // hide row, column or sheet
        SHEET_CONTEXT_Show: "Afbeelden", // show row, column
        SHEET_CONTEXT_MoveSheet: "Verplaatsen...", // move sheet
        SHEET_CONTEXT_InsertSheet: "Invoegen...", // insert sheet
        SHEET_CONTEXT_DeleteSheet: "Wissen...", // delete sheet	
        SHEET_CONTEXT_DuplicateSheet: "Dupliceren...", // duplicate sheet
        SHEET_CONTEXT_RenameSheet: "Naam wijzigen...", // rename sheet
	
        ctxMenu_Image_WrapText: "Tekstterugloop",
        ctxMenu_Image_WrapText_Inline: "Uitgelijnd met tekst",
        ctxMenu_Image_WrapText_Square: "Vierkant",
        ctxMenu_Image_WrapText_TopBottom: "Bovenaan en onderaan",
        ctxMenu_Image_WrapText_Behind: "Achter tekst",
        ctxMenu_Image_WrapText_InFront: "Voor tekst",
        ctxMenu_Image_WrapText_Other: "Meer tekstterugloop",
        ctxMenu_Image_WrapText_BothSides: "Beide zijden",
        ctxMenu_Image_WrapText_LeftOnly: "Alleen links",
        ctxMenu_Image_WrapText_RightOnly: "Alleen rechts",
        ctxMenu_Image_WrapText_LargestOnly: "Alleen grootste",

        ctxMenu_Shape_AddText: "Tekst toevoegen",

        ctxMenu_Range_ACL: "Bereik beschermen",
        ctxMenu_Sheet_ACL: "Werkblad beschermen",

        ctxMenu_HeaderFooter: "Koptekst / Voettekst",
        ctxMenu_HeaderFooter_DiffFirst: "Alleen eerste pagina",
        ctxMenu_HeaderFooter_DiffOddEven: "Even en oneven pagina's verschillend",
        ctxMenu_HeaderFooter_LinkToPre: "Link naar vorige",

        ctxMenu_copy: "Kopiëren",
        ctxMenu_paste: "Plakken",
        ctxMenu_delete: "Wissen",
        ctxMenu_cut: "Knippen",
        ctxMenu_select: "Selecteren",
        ctxMenu_properties: "Eigenschappen",
        ctxMenu_bringToFront: "Op voorgrond",
        ctxMenu_sendToBack: "Naar achtergrond",
        ctxMenu_arrange: "Positie",
        ctxMenu_sendBackward: "Naar achteren",
        ctxMenu_sendForward: "Naar voren",
        ctxMenu_fontStyle: "Letterstijl",
        ctxMenu_selectStyle: "Stijl selecteren",
        ctxMenu_fontSize: "Lettergrootte",
        ctxMenu_fontFamily: "Letterfamilie",
        ctxMenu_bold: "Vet",
        ctxMenu_italic: "Cursief",
        ctxMenu_u: "Onderstrepen",
        ctxMenu_strike: "Doorhalen",
        ctxMenu_super: "Superscript",
        ctxMenu_sub: "Subscript",
        ctxMenu_color: "Kleur",
        ctxMenu_bgcolor: "Achtergrondkleur",
        ctxMenu_highcolor: "Markeringskleur",
        ctxMenu_restart: "Lijst opnieuw starten",
        ctxMenu_continue: "Lijst voortzetten",
        ctxMenu_separate: "Afzonderlijke lijst",
        ctxMenu_join: "Samenvoegen met eerdere lijst",
        ctxMenu_setNumberVal: "Nummering instellen...",
        webClipboardInfoTitle: "Klembord",
        webClipboardInfoOKBtn: "OK",
        webClipboardInfoCutMsg: "De beveiligingsinstellingen van uw browser verhinderen automatisch kopiëren. Gebruik in plaats daarvan de toetsencombinatie Ctrl+X.",
        webClipboardInfoCopyMsg: "De beveiligingsinstellingen van uw browser verhinderen automatisch kopiëren. Gebruik in plaats daarvan de toetsencombinatie Ctrl+C.",
        webClipboardInfoPasteMsg: "De beveiligingsinstellingen van uw browser verhinderen dat deze editor toegang heeft tot uw klembordgegevens. Gebruik in plaats daarvan de toetsencombinatie Ctrl+V.",

        clearTrackChangeConfirmMsg: "Alle kleurcodes voor de wijzigingen in dit document worden permanent verwijderd. Wilt u doorgaan?"
});

