/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */


define({
        saveTip: "Opslaan",
        undoTip: "Ongedaan maken",
        redoTip: "Opnieuw uitvoeren",
        formatPainterTip: "Opmaak overnemen",
        showSorterTip: "Diasorteerder afbeelden",
        hideSorterTip: "Diasorteerder verbergen",
        webClipboardTip: "Webklembord",
        spellCheckTip: "Handmatige spellingcontrole uitvoeren",
        createSectionTip: "Sectie toewijzen",
        createCellsTip: "Cellen toewijzen",
        createSlideTip: "Dia's toewijzen",
        submitTip: "Toewijzing verzenden",
        addCommentTip: "Commentaar toevoegen",
        removeFormatTip: "Opmaak verwijderen",
        sortAscTip: "Oplopend sorteren",
        sortDescTip: "Aflopend sorteren",
        instantFilterTip: "Instantfilter",
        insertChartTip: "Diagram invoegen",
        startAutofillTip: "Automatisch vullen",
        dataValidationTip: "Gegevensvalidatie",

        selectFontTip: "Lettertype kiezen",
        selectFontSizeTip: "Lettergrootte selecteren",
        selectFontNameTip: "Lettertype selecteren",
        FontName: "Lettertype",
        FontSize: "Lettergrootte",
        increaseFontSizeTip: "Grotere letters",
        decreaseFontSizeTip: "Kleinere letters",
        boldTip: "Vet",
        italicTip: "Cursief",
        underlineTip: "Onderstrepen",
        strikeThroughTip: "Doorhalen",
        setFontColorTip: "Letterkleur instellen",
        setShadingColorTip: "Schaduwkleur instellen",
        setBackgroundFill: "Achtergrond instellen",
        setBgColorTip: "Achtergrondkleur instellen",
        setBorderTip: "Randstijl en -kleur instellen",
        setBorderColorTip: "Randkleur instellen",
        setHighlightColor: "Markeringskleur instellen",
        formatPainter: "Opmaak overnemen",
        //	clearFormat:"Remove Formatting",
        zoom: "In-/uitzoomen",
        selectStyleTip: "Stijl selecteren",
        styles: "Stijl",
        formatAsCurrencyTip: "Notatie als valuta",
        formatAsPercentTip: "Notatie als percentage",
        decreaseDecimalTip: "Minder decimalen",
        increaseDecimalTip: "Meer decimalen",
        formatNumberTip: "Getalnotatie",

        numberedListTip: "Nummering toevoegen of nummeringsstijl wijzigen",
        bulletedListTip: "Opsommingstekens toevoegen of opsommingstekenstijl wijzigen",
        multilevelListTip: "Lijst met niveaus toevoegen of wijzigen",
        indentTip: "Inspringing vergroten",
        decreaseIndentTip: "Inspringing verkleinen",
        alignTip: "Uitlijnen",
        leftAlignTip: "Links uitlijnen",
        centerTip: "Centreren",
        rightAlignTip: "Rechts uitlijnen",
        justifyTip: "Uitvullen",
        bottomBorderTip: "Onderrand",
        borderTypes: "Randtypen",
        borderTip: "Randstijl instellen",
        topAlignTip: "Boven uitlijnen",
        middleAlignTip: "Midden uitlijnen",
        bottomAlignTip: "Onder uitlijnen",
        lineSpacingTip: "Regelafstand",
        mergeSplitCellTip: "Cellen samenvoegen of splitsen",
        wrapNoWrapTip: "Tekstterugloop aan/uit",
        ltrDirectionTip: "Wijzigen in Links naar rechts",
        rtlDirectionTip: "Wijzigen in Rechts naar links",
        autoDirectionTip: "Tekstrichting wijzigen",
        toggleSheetDirectionTip: "Bladrichting wijzigen",
        setSheetDirectionLTR: "Links naar rechts",
        setSheetDirectionRTL: "Rechts naar links",

        addTableTip: "Tabel toevoegen",
        insertOrMoveRowTip: "Rij invoegen of verplaatsen",
        insertOrMoveColTip: "Kolom invoegen of verplaatsen",
        insertOrDeleteRowTip: "Rij invoegen of wissen",
        insertOrDeleteColTip: "Kolom invoegen of wissen",
        insertFunctionTip: "Functie invoegen",
        insertImage: "Afbeelding invoegen",
        resizeCol: "Kolombreedte wijzigen",
        resizeCols: "Kolommenbreedtes wijzigen",
        addLink: "Link toevoegen of bewerken",
        tableStyle: "Tabelstijlen",

        selectBorder_BottomBorder: "Onderrand",
        selectBorder_TopBorder: "Bovenrand",
        selectBorder_LeftBorder: "Linkerrand",
        selectBorder_RightBorder: "Rechterrand",
        selectBorder_NoBorder: "Geen lijnen",
        selectBorder_AllBorders: "Alle randen",

        insertOrMoveRow_InsertAbove: "Rij invoegen boven",
        insertOrMoveRow_InsertBelow: "Rij invoegen onder",
        insertOrMoveRow_MoveUp: "Rij omhoog",
        insertOrMoveRow_MoveDown: "Rij omlaag",
        insertOrMoveCol_InsertLeft: "Kolom invoegen voor",
        insertOrMoveCol_InsertRight: "Kolom invoegen na",
        insertOrMoveCol_InsertBefore: "Kolom invoegen voor",
        insertOrMoveCol_InsertAfter: "Kolom invoegen na",
        insertOrMoveCol_MoveLeft: "Kolom naar links",
        insertOrMoveCol_MoveRight: "Kolom naar rechts",

        insertOrDelete_Delete: "Wissen",

        combineButtonReadTip: "Druk op de pijl omlaag om het menu te activeren, en gebruik de cursortoetsen voor de navigatie.",

        lineSpacing_1: "1",
        lineSpacing_12: "1,2",
        lineSpacing_15: "1,5",
        lineSpacing_2: "2",
        lineSpacing_25: "2,5",
        lineSpacing_3: "3",

        percent: "%",
        font_arial: "Arial",

        fontSize: "${0}pt",

        slides: "Een dia per pagina",
        slidesWithNotes: "Dia's met notities",
        preparingSlides: "De afdruk van uw dia's wordt voorbereid...",
        printLayoutOptionLabel: "Opties voor afdruklayout",

        targetRemovedWhenDialogOpen: "Deze actie kan niet worden voltooid want het doeldocument is verwijderd door een andere editor.",

        NUMBER: "Getal",
        CURRENCY: "Valuta",
        PERCENT: "Percentage",
        DATE: "Datum",
        TIME: "Tijd",
        DATETIME: "DatumTijd",
        MORECURRENCY: "Meer valuta op munt",
        MORECURRENCYCODE: "Meer valuta op code",
        MOREDATE: "Meer tijd- en datumnotaties",
        TEXT: "Tekst",
	
        // currency, by currency code
        // NOTE: MUST keep it in order
        CURRENCY_CODE: {
            AED: "Verenigde Arabische Emiraten (Dirham)",
            ARS: "Argentinië (Peso)",
            AUD: "Australië (Dollar)",
            BGN: "Bulgarije (Leva)",
            BOB: "Bolivia (Boliviano)",
            BRL: "Brazilië (Real)",
            CAD: "Canada (Dollar)",
            CHF: "Zwitserland (Frank)",
            CLP: "Chili (Peso)",
            CNY: "China (Yuan Renminbi)",
            COP: "Colombia (Peso)",
            CRC: "Costa Rica (Colon)",
            CZK: "Tsjechië (Koruny)",
            DKK: "Denemarken (Kroon)",
            DOP: "Dominicaanse Republiek (Peso)",
            EGP: "Egypte (Pond)",
            EUR: "Nederland en andere eurolanden (Euro)",
            GBP: "Engeland, Verenigd Koninkrijk (Pond)",
            HKD: "Hongkong (Dollar)",
            HRK: "Kroatië (Kuna)",
            HUF: "Hongarije (Forint)",
            IDR: "Indonesië (Rupiah)",
            ILS: "Israël (Nieuwe shekel)",
            INR: "India (Roepie)",
            JPY: "Japan (Yen)",
            KRW: "Zuid-Korea, (Won)",
            KZT: "Kazachstan (Tenges)",
            MAD: "Marokko (dirham)",
            MXN: "Mexico (Peso)",
            MYR: "Maleisië (Ringgit)",
            NOK: "Noorwegen (Kroon)",
            NZD: "Nieuw-Zeeland (Dollar)",
            PAB: "Panama (Balboa)",
            PEN: "Peru (Nuevo Sol)",
            PHP: "Filipijnen (Peso)",
            PKR: "Pakistan (Roepie)",
            PLN: "Polen (Zloty)",
            PYG: "Paraguay (Guarani)",
            RON: "Roemenië (Nieuwe lei)",
            RSD: "Servië (Cyrillisch), Servië (Latijns)",
            RUB: "Rusland (Roebel)",
            SAR: "Saudi-Arabië (Riyal)",
            SEK: "Zweden (Kroon)",
            SGD: "Singapore (Dollar)",
            SVC: "El Salvador (Colon)",
            THB: "Thailand (Baht)",
            TRY: "Turkije (Lira)",
            TWD: "Taiwan (Nieuwe dollar)",
            USD: "Ecuador, Puerto Rico, Verenigde Staten (U.S. dollar)",
            UYU: "Uruguay (Peso)",
            VEF: "Venezuela (Bolivar)",
            VND: "Vietnam (Dong)",
            ZAR: "Zuid-Afrika (Rand)"
        },
        // for border toolbar
        allBorders: "Alle randen",
        innerBorders: "Interne randen",
        horizontalBorders: "Horizontale randen",
        verticalBorders: "Verticale randen",
        outerBorders: "Externe randen",
        borderColor: "Randkleur",
        leftBorder: "Linkerrand",
        topBorder: "Bovenrand",
        rightBorder: "Rechterrand",
        bottomBorder: "Onderrand",
        clearBorders: "Geen randen",
        BorderStyle_ThinSolid: "Dun ononderbroken",
        BorderStyle_ThinDotted: "Dun gestippeld",
        BorderStyle_ThinDashed: "Dun onderbroken",
        BorderStyle_ThickSolid: "Dik ononderbroken",
        BorderStyle_ThickDotted: "Dik gestippeld",
        BorderStyle_ThickDashed: "Dik onderbroken"
})

