({
		SAVE: "Guardar",
		UNDO:"Anular",
		REDO:"Refazer",
		INSERTROW:"Inserir linha",
		DELETEROW:"Eliminar linha",
		INSERTCOLUMN:"Inserir coluna",
		DELETECOLUMN:"Eliminar coluna",
		FONTSIZE:"Tamanho do tipo de letra",
		FONTCOLOR:"Cor do tipo de letra",
		BOLD:"Negrito",
		ITALIC:"Itálico",
		UNDERLINE:"Sublinhado",
		STRIKETHROUGH:"Rasurado",
		CURRENCYTIP:"Formatar como moeda",
		PERCENTLABEL:"%",
		PERCENTTIP:"Formatar como percentagem",
		NUMBERFORMAT:"Formato numérico",
		ALIGNLEFT:"Alinhar à esquerda",
		ALIGNCENTER:"Alinhar ao centro",
		ALIGNRIGHT:"Alinhar à direita",
		SETCELLBORDER:"Definir contorno da célula",
		BACKGROUNDCOLOR:"Cor de segundo plano",
		TASK:"Atribuir secção",
		COMMENTS:"Adicionar comentário",
		SUBMIT:"Submeter",
		MERGECELL: "Unir ou dividir células",
		QUICKFORMULA: "Fórmula rápida",
		WRAPTEXT: "Translinear texto",
		EIGHT:"8pt",
		NINE:"9pt",
		TEN:"10pt",
		ELEVEN:"11pt",
		TWELVE:"12pt",
		FOURTEEN:"14pt",
		SIXTEEN:"16pt",
		EIGHTEEN:"18pt",
		TWENTY:"20pt",
		TWENTYTWO:"22pt",
		TWENTYFOUR:"24pt",
		NUMBER:"Número",
		CURRENCY:"Moeda",
		PERCENT:"Percentagem",
		DATE:"Data",
		TIME:"Hora",
		DATETIME: "Data/Hora",
		MORECURRENCY:"Mais moedas",
		MOREDATE:"Mais formatos",
		
		
		CAD: "dólar canadiano",
		USD: "dólar",
		EUR: "euro",
		CHF: "franco suíço",
		HKD: "dólar de Hong Kong",
		DKK: "coroa",
		LTL: "lita",
		PHP: "peso",
		BRL: "real",
		RUR: "rublo",
		GBP: "libra",
		NLG: "florim", // Netherlands
		TWD: "novo dólar de Taiwan",
		THB: "baht", // Thailand
		ITL: "lira", // Turkey
		BGL: "lev", // Uzbekistan
		VND: "dong", // Vietnam
		KRW: "won",	// Korean 
		CNY: "yuan", // RMB
		JPY: "iene" // Japan Yen
})
