({
	ORIENTATION_LABEL: "Retning",
	PORTRAIT: "Stående",
	LANDSCAPE: "Liggende",
	HEADER: "Overskrift",
	FOOTER: "Bundtekst",
	MARGINS_LABEL: "Margener",
	TOP: "Top:",
	BOTTOM: "Bund:",
	LEFT: "Venstre:",
	RIGHT: "Højre:",
	PAPER_FORMAT_LABEL: "Papirformat",
	PAPER_SIZE_LABEL: "Papirstørrelse:",
	HEIGHT: "Højde:",
	WIDTH: "Bredde:",
	HEIGHT_DESC:"Papirhøjde, i centimeter",
	HEIGHT_DESC2:"Papirhøjde, i tommer",
	WIDTH_DESC:"Papirbredde, i centimeter",
	WIDTH_DESC2:"Papirbredde, i tommer",
	BOTTOM_DESC:"Bundmargen, i centimeter",
	BOTTOM_DESC2:"Bundmargen, i tommer",
	TOP_DESC:"Topmargen, i centimeter",
	TOP_DESC2:"Topmargen, i tommer",
	LEFT_DESC:"Venstre margen, i centimeter",
	LEFT_DESC2:"Venstre margen, i tommer",
	RIGHT_DESC:"Højre margen, i centimeter",
	RIGHT_DESC2:"Højre margen, i tommer",
	CM_LABEL: "cm",
	LETTER: "Brev",
	LEGAL: "Legal",
	TABLOID: "Tabloid",
	USER: "Bruger",
	SIZE1: "Kuv. #6 3/4",
	SIZE2: "Kuv. Monarch",
	SIZE3: "Kuv. #9",
	SIZE4: "Kuv. #10",
	SIZE5: "Kuv. #11",
	SIZE6: "Kuv. #12",
	SIZE7: "16 kai",
	SIZE8: "32 kai",
	SIZE9: "32 kai stor",
	INVALID_MSG: "Inputtet er ugyldigt, og er automatisk blevet rettet. Prøv en anden værdi, hvis du vil have et andet resultat."
})
	

