({
	COLUMN: "Stapel",
	CLUSTERED_COLUMN: "Klustrad stapel",
	STACKED_COLUMN: "Staplad stapel",
	BAR:"Liggande stapel",
	CLUSTERED_BAR:"Klustrad liggande stapel",
	STACKED_BAR: "Staplad liggande stapel",
	PIE:"Cirkel",
	SLICE: "Sektor ",
	AREA: "Yta",
	STACKED_AREA: "Staplad yta",
	LINE: "Linje",
	STACKED_LINE: "Staplad linje",
	MAKER_LINE: "Linje med markeringar ",
	STACKED_MARKER_LINE: "Staplad linje med markeringar",
	SCATTER: "Punkt",
	SCATTER_MARKER_ONLY: "Punkter med markeringar",
	SCATTER_MARKER_LINE_S: "Punkter med jämna linjer och markeringar",
	SCATTER_LINE_S: "Punkter med jämna linjer", 
	SCATTER_MARKER_LINE_X: "Punkter med raka linjer och markeringar",
	SCATTER_LINE_X: "Punkter med raka linjer",
	ERROR_INVALID_RANGE:"Ogiltigt dataintervall",
	TOO_MANY_POINTS: "Det går inte att skapa ett diagram som har fler än ${0} datapunkter",
	CHART_TYPES:"Diagramtyper",
	DATA:"Data",
	DATA_RANGE:"Dataintervall",
	IN_ROWS:"Dataserier i rader",
	IN_COLUMNS:"Dataserier i kolumner",
	AUTO:"Automatiskt"
})
