({
	alt			: "Alternativ text:",
	width		: "Bredd:",
	height		: "Höjd:",
	cmUnit   : " cm",
	ptUnit 	 : "pt",
	inchUnit : "tum",
	inUnit   : "in",
	mmUnit 	 : "mm",
	
	inputWarning: "Skriv ett positivt tal med standardenheten. ",
	
	properties: "Egenskaper",
	data: "Data",
	chart: "Diagram",
	axis: "Axel",
	series: "Serie",
	font: "Teckensnitt",
	title: "Rubrik",
	legend: "Teckenförklaring",
	placement: "Placering",
	background: "Bakgrund",
	plotarea: "Rityta",
	line : "Linje",
	fill: "Fyllning",
	border : "Kantlinje",
	labelfont: "Etikett",
	scale: "Skala ",
	minimum: "Minimum",
	maximum: "Maximum",
	majorunit: "Enhet för huvudskala",
	minorunit: "Enhet för delskala",
	smooth: "Jämn",
	marker: "Markeringar",
	markerfill: "Markering",
	enterTitle: "Skriv rubriken här",
	inputNumberWarning: "Skriv ett tal. ",
	inputPosNumberWarning: "Skriv ett positivt tal. ",
	maxMinWarning: "Maximalt värde måste vara högre än minimalt värde",
	selectFontName: "Välj teckensnitt",
	selectFontSize: "Välj teckenstorlek",
	setBold: "Halvfet",
	setItalic: "Kursiv",
	setFontColor: "Välj teckenfärg",
	setLegendPos: "Välj teckenförklaringsplacering",
	setBackColor: "Välj diagrambakgrundsfärg",
	setBorderWidth: "Välj kantlinjebredd",
	setBorderColor: "Välj kantlinjefärg",
	setPlotAreaColor: "Välj ritytefärg",
	selectAxis: "Välj axel ",
	setLineWidth: "Välj linjebredd",
	setLineColor: "Välj linjefärg",
	selectSeries: "Välj serie",
	setFillColor: "Välj fyllningsfärg",
	setMarker: "Välj markeringar",
	setSmooth: "Välj jämn linje",
	chartTitle: "Diagramrubrik",
	axisTitle: "Axelrubrik",
	
	ERR1: "En matris måste omges av klammerparenteser.",
	ERR3: "Strängobjekten måste omges av citattecken.",
	ERR4: "Ange endast ett intervall.",
	ERR5: "Ogiltigt intervall ",
	ERR6: "Alla intervall måste finnas på samma ark.",
	ERR7: "Alla intervall måste gälla en enskild rad eller kolumn.",
	ERR9: "Du måste ange ett serievärde.",
	
	n	: "Ingen",
	l	: "Vänster",
	r	: "Höger",
	t	: "Överkant",
	b   : "Nederkant",
	
	dataSeries:"Dataserier ",
	label:"Serienamn",
	xVal:"X-värden",
	yVal:"Y-värden",
	val:"Serievärden",
	cat:"Kategori ",
		
	ltr: "Vänster till höger ",
	rtl: "Höger till vänster ",
	auto: "Kontext",
	bidi_dir: "Riktning",
	bidi_text_dir: "Textriktning"
})
