({	
	dlgTaskCreateTitle: "הקצאת חלק",  
	dlgTaskDeleteTitle: "סילוק חלק", 
	dlgTaskEditTitle: "עריכת הקצאה",
	dlgTaskRewordTitle: "הקצאת עיבוד מחדש",
	dlgTaskHistoryTitle: "אודות חלק זה",
	dlgTaskReopenTitle: "פתיחה מחדש של הקצאה",
	dlgTaskReassignTitle: "הקצאה מחדש של חלק",
	dlgTaskDeleteBtn: "מחיקה",
	creatingTaskAsTODO: "ההקצאה שלכם נשמרת כמטלה ביישום הפעילויות",
	creatingTaskAsTODO2: "ההקצאה נשמרת כעת",
	creatingTaskAsTODO3: "ההקצאות נשמרות כעת",
	updatingTask: "ההקצאות שלכם מעודכנות כעת ביישום הפעילויות",
	updatingTask2: "ההקצאה מעודכנת כעת",
	updatingTask3: "ההקצאות מעודכנות כעת",
	restoringTask: "המתינו עד שההקצאה שלכם תשוחזר בפעילות.",
	creatingFragment: "מסמך פרטי נוצר עבור חלק זה",
	updatingMaster: "עיבוד בביצוע... החלק מעודכן במסמך הראשי",
	cannotAccessActivity: "שגיאה! אין גישה לשרת הפעילויות לרישום הקצאות. נסו שוב מאוחר יותר.‏",
	cannotAccessActivity2: "שגיאה! אין גישה לשרת לרישום הקצאות. נסו שוב מאוחר יותר.‏",
	cannotAccessActivityContent: "אין גישה לשרת הפעילויות לרישום הקצאות. נסו שוב מאוחר יותר.‏",
	cannotRecordAssignment: "אין גישה לשרת הפעילויות לרישום הקצאות. נסו שוב מאוחר יותר.‏",
	notMemberofActivity: "לא ניתן לרשום את ההקצאה שלכם בפעילות. ודאו שנוספתם לפעילות ונסו שוב.",
	cannotLoadActivity: "אין גישה לשרת הפעילויות לטעינת הקצאות. נסו שוב מאוחר יותר.‏",
	cannotLoadActivity2: "אין גישה לשרת לטעינת הקצאות. נסו שוב מאוחר יותר.‏",
	cannotLoadAssignment: "אין גישה לשרת הפעילויות לטעינת ההקצאה. נסו שוב מאוחר יותר.‏",
	cannotSupportSocialEdit: "אינכם זכאים לעריכה משותפת או להקצאת חלקים.",
	cannotDeleteDraft: "לא ניתן למחוק את הטיוטה כרגע. מחקו את הקובץ ידנית מאוחר יותר.",
	taskAlreadyRemoved: "המשימה של מסמך זה סולקה, או שאין לכם הרשאה לערוך את המשימה.",
	taskAlreadyCompleted: "המשימה הושלמה או בוטלה.",
	taskAlreadyReassigned: "המשימה הוקצתה מחדש.",
	assignmentAlreadyExist: "האזור שנבחר כבר הוקצה בעבר.",
	notAllowedEditMaster: "אינכם יכולים לערוך את המסמך הראשי. בדקו אם יש לכם הרשאה מתאימה.",
	notAllowedEditPaticipant: "מקבל ההקצאה או הסוקר אינו מוגדר או שאין לא גישת עריכה. ודאו שלמקבל ההקצאה או הסוקר יש גישה מתאימה. ",
	notValidAssignment: "ההקצאה אינה חוקית, יתכן שחלק מתכונות ההקצאה בשרת הפעילויות פגומות. תוכלו לסלק את ההקצאה בלחיצה על 'פעולות > סילוק הקצאה' ",
	disableBlockerMsg: "בדפדפן שלכם מופעל חוסם חלונות המונע הצגה נכונה של הדף. התירו הצגת חלונות צצים עבור אתר ‎*cn.ibm.com.‏ ",
	writeDesc: "כתיבת ${0}: ${1}",
	reviewDesc: "סקירת ${0}: ${1}",
	reworkDesc: "עיבוד חוזר של${0}: ${1}",
	writeCompleteDesc: "החלק ${0} נכתב על ידי ${1}",
	reviewCompleteDesc: "החלק ${0} נסקר על ידי ${1}",
	workingPrivateDesc: "עבודה פרטית על ${0} על ידי ${1}",
	actions: "פעולות",	
	onlyAssignerDeleteTask: "אינכם יכולים למחוק הקצאה זו שלא סומנה בסימון 'הושלם'. רק האדם שהקצה אותה יכול למחוק אותה. ",
	actionBtnEdit: "עריכת הקצאה",
	actionBtnRemove: "סילוק הקצאה",
	actionBtnAbout: "אודות חלק זה",
	actionBtnMarkComplete: "סימון 'הושלם'‏",
	actionBtnWorkPrivately: "עבודה פרטית",
	actionBtnApprove: "אישור חלק זה",
	actionBtnGotoPrivate: "מעבר למסמך פרטי",
	actionBtnCancelPrivate: "ביטול עבודה פרטית",
	actionBtnRework: "דרוש עיבוד חוזר",
	actionBtnReopen: "פתיחה מחדש של הקצאה",
	actionBtnReassign: "הקצאה מחדש של חלק",
	creating: "יצירה...‏",
	deleting: "מחיקה...‏",
	updating: "עדכון...‏",
	loading: "טעינה...‏",
	restoring: "שחזור...‏",
	lockCoeditingTask:"עורך אחר עובד על אותה הקצאה. נסו שוב מאוחר יותר.‏"
})
