({
	ORIENTATION_LABEL: "Suunta",
	PORTRAIT: "Pystytaso",
	LANDSCAPE: "Vaakataso",
	HEADER: "Ylätunniste",
	FOOTER: "Alatunniste",
	MARGINS_LABEL: "Reunukset",
	TOP: "Yläreuna:",
	BOTTOM: "Alareuna:",
	LEFT: "Vasen:",
	RIGHT: "Oikea:",
	PAPER_FORMAT_LABEL: "Paperikoko",
	PAPER_SIZE_LABEL: "Paperikoko:",
	HEIGHT: "Korkeus:",
	WIDTH: "Leveys:",
	HEIGHT_DESC:"Paperin korkeus senttimetreinä",
	HEIGHT_DESC2:"Paperin korkeus tuumina",
	WIDTH_DESC:"Paperin leveys senttimetreinä",
	WIDTH_DESC2:"Paperin leveys tuumina",
	BOTTOM_DESC:"Alareunus senttimetreinä",
	BOTTOM_DESC2:"Alareunus tuumina",
	TOP_DESC:"Yläreunus senttimetreinä",
	TOP_DESC2:"Yläreunus tuumina",
	LEFT_DESC:"Vasen reunus senttimetreinä",
	LEFT_DESC2:"Vasen reunus tuumina",
	RIGHT_DESC:"Oikea reunus senttimetreinä",
	RIGHT_DESC2:"Oikea reunus tuumina",
	CM_LABEL: " cm",
	LETTER: "Letter",
	LEGAL: "Legal",
	TABLOID: "Tabloidi",
	USER: "Mukautettu",
	SIZE1: "Kirjek. #6 3/4",
	SIZE2: "Kirjek. Monarch",
	SIZE3: "Kirjek. #9",
	SIZE4: "Kirjek. #10",
	SIZE5: "Kirjek. #11",
	SIZE6: "Kirjek. #12",
	SIZE7: "16 kai",
	SIZE8: "32 kai",
	SIZE9: "32 kai suuri",
	INVALID_MSG: "Syöte on virheellinen, ja se on korjattu automaattisesti. Kokeile toista arvoa, jos haluat toisen tuloksen."
})
	
