﻿/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        fileMenu: "Fitxategia",
        fileMenu_New: "Berria",
        fileMenu_NewDocument: "Dokumentua",
        fileMenu_NewFromTemplate: "Txantiloitik",
        fileMenu_NewDocumentfromTemplate: "Dokumentua txantiloitik",
        fileMenu_NewPresentation: "Aurkezpena",
        fileMenu_NewPresentationfromTemplate: "Aurkezpena txantiloitik",
        fileMenu_NewSpreadsheet: "Kalkulu-orria",
        fileMenu_NewSpreadsheetFromTemplate: "Kalkulu-orria txantiloitik",
        fileMenu_Open: "Ireki",
        fileMenu_Import: "Inportatu...",
        //	fileMenu_Close: "Close",
        fileMenu_Discard: "Leheneratu azken bertsiora",
        fileMenu_ClearTrackChange: "Kendu aldaketa-markak",
        fileMenu_SpreadsheetSettings: "Ezarri dokumentuaren eskualdeko ezarpenak...",
        filemenu_revisionhistory: "Berrikuspenak",
        fileMenu_Save: "Gorde",
        fileMenu_SaveAs: "Kopiatu...",
        fileMenu_AutoPublish: "Argitaratu automatikoki",
        fileMenu_AutoCheckIn: "Babestu automatikoki",
        fileMenu_PublishVersion: "Argitaratu orain",
        fileMenu_AutoPublish2: "Automatikoki gorde biltegian",
        //	fileMenu_AutoPublish_Tips: "Makes your changes available to readers at the end of each editing session.",
        fileMenu_PublishVersion2: "Gorde biltegian orain",
        fileMenu_AutoPublish3: "Gorde hemen: ${0}",
        fileMenu_PublishVersion3: "Gorde hemen orain: ${0}",      
        fileMenu_SubmitForReview: "Bidali berrikusteko...",
        fileMenu_CheckinVersion: "Babestu...",
        fileMenu_Unlock: "Desblokeatu",
        //	fileMenu_SaveAsDraft: "as Draft",
        //	fileMenu_SaveInMyDocs: "in My Documents",
        //	fileMenu_SaveToSymphony: "to Lotus Symphany",
        fileMenu_DownloadAs: "Deskargatu honela",
        fileMenu_PDF: "PDF",
        fileMenu_ODF: "ODF",
        fileMenu_DOC: "Microsoft Word 97- 2007 (*.doc)",
        fileMenu_ODS: "ODS",
        fileMenu_XLS: "Microsoft Excel 97-2007 (*.xls) ",
        fileMenu_ShareWith: "Partekatu...",
        fileMenu_ExportAsPDF: "PDF",
        fileMenu_ExportAsODF: "ODF",
        fileMenu_ExportAsPPT: "Microsoft Powerpoint 97- 2007 (*.ppt)",
        //	fileMenu_WebPreview: "Web Preview",
        fileMenu_PrintToPDF: "Inprimatu PDF formatuan...",
        fileMenu_ViewFileDetails: "Ikusi fitxategiaren xehetasunak...",
        fileMenu_RecentFile: "Azken fitxategiak",
        fileMenu_Open: "Ireki",
        fileMenu_Download: "Deskargatu",
        fileMenu_Print: "Inprimatu",
        fileMenu_Export: "Esportatu",
        fileMenu_ExportToCSV: "CSV",
        fileMenu_ExportToPDF: "PDF (.pdf)",
        fileMenu_ExportToMarkdown: "Markdown (.md)",
        fileMenu_ExportToMS: "Microsoft Office format (.${FILEEXTENSION})",
        fileMenu_ExportToODF: "Open Document format (.${FILEEXTENSION})",
        fileMenu_PgSetup: "Orriaren konfigurazioa...",

        editMenu: "Editatu",
        editMenu_Undo: "Desegin",
        editMenu_Redo: "Berregin",
        editMenu_Cut: "Ebaki",
        editMenu_Copy: "Kopiatu",
        editMenu_Paste: "Itsatsi",
        editMenu_DeleteSlide: "Ezabatu diapositiba",
        editMenu_SelectAll: "Hautatu guztiak",
        editMenu_Find: "Aurkitu...",
        editMenu_Replace: "Ordeztu...",
        editMenu_FindReplace: "Aurkitu eta ordeztu...",
        editMenu_EditLink: "Gehitu edo editatu esteka",
        editMenu_DeleteSheet: "Ezabatu orria...",
        editMenu_RenameSheet: "Eman beste izen bat orriari...",
        editMenu_HideSheet: "Ezkutatu orria",
        editMenu_MoveSheet: "Mugitu orria...",
        editMenu_DeleteRow: "Ezabatu errenkada",
        editMenu_DeleteColumn: "Ezabatu zutabea",
        editMenu_DeleteCellLeft: "Ezabatu gelaxkak eta lerratu ezkerrera",
        editMenu_DeleteCellUp: "Ezabatu gelaxkak eta lerratu gora",
        editMenu_ClearCell: "Ezabatu edukia",

        viewMenu: "Ikusi",
        viewMenu_Master: "Nagusia",
        viewMenu_Notifications: "Jakinarazpenak",
        viewMenu_SlideSorter: "Diapositiba-sailkatzailea",
        viewMenu_SpeakerNotes: "Aurkezlearen oharrak",
        viewMenu_Toolbar_Basic: "Oinarrizkoa",
        viewMenu_Toolbar_Advanced: "Aurreratua",
        viewMenu_Toolbar_None: "Bat ere ez",
        viewMenu_Toolbar: "Tresna-barra",
        viewMenu_Statusbar: "Egoera-barra",
        viewMenu_Navigator: "Nabigatzailea...",
        //viewMenu_Sidebar: "Sidebar",
        viewMenu_ShowHideIndicators: "Erakutsi lankidetza-edizioaren adierazleak",
        viewMenu_Assignment: "Esleipenaren adierazleak",
        viewMenu_Bookmark: "Laster-markak",
        viewMenu_Coediting: "Lankidetza-edizioan nabarmenduak",
        viewMenu_Rulers: "Erregelak",
        viewMenu_WebLayout: "Web-diseinua",
        viewMenu_AutomaticSpellCheck: "Egiaztatu ortografia idatzi ahala",
        viewMenu_Formulabar: "Formula-barra",
        viewMenu_moveRight: "Sartu teklak kurtsorea mugitzen du eskuinetara",
        viewMenu_showFullString: "Hedatu gelaxken edukia",
        viewMenu_Doc: "Ikusi dokumentua",
        viewMenu_Templates: "Txantiloiak",
        viewMenu_GridLines: "Ezkutatu saretak",
        viewMenu_UnsupportWarning: "Erakutsi onartzen ez diren eginbideen mezuak",
        viewMenu_HiddenSheets: "Orri ezkutuak",
        viewMenu_FreezeRows: "Izoztu errenkadak",
        viewMenu_FreezeColumns: "Izoztu zutabeak",
        viewMenu_NoFrozenRows: "Errenkada izozturik ez",
        viewmenu_NoFrozenColumns: "Zutabe izozturik ez",
        viewMenu_FreezeXRows: "Izoztu ${0} errenkada",
        viewMenu_FreezeOneRow: "Izoztu errenkada ${0}",
        viewMenu_FreezeXColumns: "Izoztu ${0} zutabe",
        viewMenu_FreezeOneColumn: "Izoztu zutabe ${0}",
        viewMenu_CarriageReturn: "Formatu-markak",
        viewMenu_Navigation: "Nabigazio panela",
        viewMenu_ACL: "Area editagarriak",
        viewMenu_GridOnOff: "Sareta-lerroak",
        viewMenu_ObserverMode: 'Behatzaile-modua',

        createMenu: "Txertatu",
        createMenu_NewSlide: "Diapositiba berria",
        createMenu_DuplicateSlide: "Bikoiztu diapositiba",
        createMenu_ImageFromFile: "Irudia...",
        createMenu_TextBox: "Testu-koadroa",
        createMenu_Shape: "Forma",
        createMenu_break: "Jauzia",
        createMenu_RowAbove: "Errenkada gainean",
        createMenu_RowBelow: "Errenkada behean",
        createMenu_ColumnRight: "Zutabea eskuinean",
        createMenu_ColumnLeft: "Zutabea ezkerrean",
        createMenu_Sheet: "Orria...",
        createMenu_Image: "Irudia...",
        createMenu_Comments: "Iruzkina...",
        createMenu_WebLink: "Web-esteka...",
        createMenu_SpecialCharacter: "Karaktere berezia...",
        createMenu_Function: "Funtzioa...",
        createMenu_Fromtemplate: "Sortu txantiloitik",

        insertMenu: "Txertatu",
        insertMenu_break: "Orri-jauzia",
        insertMenu_sectionbreak: "Sekzio-jauzia",
        insertMenu_Bookmark: "Laster-marka...",
        insertMenu_WebLink: "Esteka...",
        insertMenu_SpecialCharacter: "Karaktere berezia...",
        insertMenu_HorizontalLine: "Lerro horizontala",
        insertMenu_Header: "Goiburua",
        insertMenu_Footer: "Orri-oina",
        insertMenu_TableOfContents: "Eduki-taula",

        insertMenu_HeaderFooter: "Goiburua/Orri-oina",
        insertMenu_HF_Edit: "Editatu",
        insertMenu_HF_Hide: "Ezkutatu",
        insertMenu_Endnotes: "Amaiera-oharrak",
        insertMenu_RowAbove: "Errenkada gainean",
        insertMenu_PageNumber: "Orriaren zenbakia",
        insertMenu_PageNumberTop: "Orriaren goiko partea",
        insertMenu_PageNumberBottom: "Orriaren beheko partea",
        insertMenu_PageNumberCurr: "Uneko posizioan",
        insertMenu_TotalPageNumber: "Orria 1/Z",
        insertMenu_Date: "Data...",
        insertMenu_Time: "Ordua...",
        insertMenu_Fields: "Eremuak",
        //    insertMenu_Comment: "Comment",
        insertMenu_CellRight: "Gelaxkak eta lerratu ezkerrera",
        insertMenu_CellDown: "Gelaxkak eta lerratu behera",
        insertMenu_RowBelow: "Errenkada behean",
        insertMenu_ColumnBefore: "Zutabea ezkerrean",
        insertMenu_ColumnAfter: "Zutabea eskuinean",
        insertMenu_Sheet: "Orria...",
        insertMenu_Image: "Irudia...",
        insertMenu_DuplicateSheet: "Bikoiztu orria",
        insertMenu_Function: "Funtzioa",
        insertMenu_FunctionSum: "BATU",
        insertMenu_FunctionAverage: "BATEZBESTEKOA",
        insertMenu_FunctionCount: "ZENBATU",
        insertMenu_FunctionMax: "MAX",
        insertMenu_FunctionMin: "MIN",
        insertMenu_FunctionMore: "Funtzio gehiago...",
        insertMenu_NameRange: "Izendatutako barrutia",
        insertMenu_NameRangeNew: "Barruti berria...",
        insertMenu_NameRangeManage: "Kudeatu barrutiak...",
        insertMenu_Chart: "Diagrama...",

        contextMenu_insertCellRight: "Txertatu gelaxkak eta lerratu ezkerrera",
        contextMenu_insertCellDown: "Txertatu gelaxkak eta lerratu behera",
        contextMenu_InsertRowAbove: "Txertatu errenkada goian",
        contextMenu_InsertRowBelow: "Txertatu errenkada behean",
        contextMenu_InsertColumnBefore: "Txertatu zutabea aurrean",
        contextMenu_InsertColumnAfter: "Txertatu zutabea atzean",
        contextMenu_DownloadImage: "Deskargatu irudi gisa",

        formatMenu: "Formatua",
        formatMenu_Columns: "Zutabeak",
        formatMenu_DefaultFormatting: "Formatu lehenetsia",
        formatMenu_Template: "Estiloak...",
        contextMenu_Template: "Taula-estiloak...",
        formatMenu_LineSpacing: "Lerroartea",
        formatMenu_LineSpacing1: "1",
        formatMenu_LineSpacing12: "1,2",
        formatMenu_LineSpacing15: "1,5",
        formatMenu_LineSpacing2: "2",
        formatMenu_LineSpacing25: "2,5",
        formatMenu_LineSpacing3: "3",
        formatMenu_TextProperties: "Testuaren propietateak",
        formatMenu_PageBreakBefore: "Orri-jauzia lehenago",
        formatMenu_KeepLines: "Mantendu lerroak elkarrekin",
        formatMenu_WidowControl: "Kontrolatu lerro solteak",
        formatMenu_Pagination: "Paragrafo-propietateak",
        formatMenu_Bold: "Lodia",
        formatMenu_Italic: "Etzana",
        formatMenu_Underline: "Azpimarratu",
        formatMenu_Strikethrough: "Marratu",
        formatMenu_IncreaseSize: "Handitu letraren tamaina",
        formatMenu_DecreaseSize: "Txikiagotu letraren tamaina",
        formatMenu_ImageProperties: "Irudiaren propietateak...",
        formatMenu_ChartProperties: "Diagramaren propietateak...",
        formatMenu_EditChart: "Editatu diagrama",
        formatMenu_InsertChart: "Txertatu diagrama",
        formatMenu_Properties: "Propietateak...",
        formatMenu_Heading: "Izenburua",
        formatMenu_Normal: "Arrunta",
        formatMenu_Title: "Titulua",
        formatMenu_Subtitle: "Azpititulua",
        formatMenu_Heading1: "Izenburua 1",
        formatMenu_Heading2: "Izenburua 2",
        formatMenu_Heading3: "Izenburua 3",
        formatMenu_Heading4: "Izenburua 4",
        formatMenu_Heading5: "Izenburua 5",
        formatMenu_Heading6: "Izenburua 6",
        formatMenu_Heading7: "Izenburua 7",
        formatMenu_Heading8: "Izenburua 8",
        formatMenu_Heading9: "Izenburua 9",
        formatMenu_BulletedList: "Buletdun zerrenda",
        formatMenu_NumberedList: "Zerrenda zenbakiduna",
        formatMenu_OutLine: "Maila anitzeko zerrenda",
        formatMenu_Superscript: "Goi-indizea",
        formatMenu_Subscript: "Azpiindizea",
        formatMenu_Align: "Lerrokatzea",
        formatMenu_Left: "Ezkerrean",
        formatMenu_Right: "Eskuinean",
        formatMenu_Center: "Orriaren erdian",
        formatMenu_Justify: "Justifikazioa",
        formatMenu_Text_Direction: "Testuaren norabidea",
        formatMenu_Ltr: "Ezkerretik eskuinera",
        formatMenu_Rtl: "Eskuinetik ezkerrera",
        formatMenu_LineSpacing: "Lerroartea",
        formatMenu_LineSpacing1: "1,0",
        formatMenu_LineSpacing115: "1,15",
        formatMenu_LineSpacing15: "1,5",
        formatMenu_LineSpacing2: "2,0",
        formatMenu_LineSpacing25: "2,5",
        formatMenu_LineSpacing3: "3,0",
        formatMenu_Top: "Goian",
        formatMenu_Bottom: "Behean",
        formatMenu_Middle: "Lerroaren erdian",
        formatMenu_Direction: "Testuaren norabidea",
        formatMenu_Rtl: "Eskuinetik ezkerrera",
        formatMenu_Ltr: "Ezkerretik eskuinera",
        formatMenu_Auto: "Testuinguruaren araberakoak",
        formatMenu_SheetDirection: "Orriaren norabidea",
        formatMenu_SheetRtl: "Eskuinetik ezkerrera",
        formatMenu_SheetLtr: "Ezkerretik eskuinera",
        formatMenu_Indent: "Handitu koska",
        formatMenu_DecreaseIndent: "Txikiagotu koska",
        formatMenu_ClearFormat: "Garbitu formatua",
        formatMenu_RowHeight: "Errenkadaren altuera",
        formatMenu_ColumnWidth: "Zutabearen zabalera",
        formatMenu_ShowRow: "Erakutsi errenkada",
        formatMenu_HideRow: "Ezkutatu errenkada",
        formatMenu_ShowColumn: "Erakutsi zutabea",
        formatMenu_HideColumn: "Ezkutatu zutabea",
        formatMenu_WrapText: "Moldatu testua",
        formatMenu_Number: "Zenbakia",
        formatMenu_FontArial: "Arial",
        formatMenu_FontComicSansMS: "Comic Sans MS",
        formatMenu_FontCourierNew: "Courier New",
        formatMenu_FontGeorgia: "Georgia",
        formatMenu_FontLucidaSansUnicode: "Lucida Sans Unicode",
        formatMenu_FontTahoma: "Tahoma",
        formatMenu_FontTimesNewRoman: "Times New Roman",
        formatMenu_FontTrebuchetMS: "Trebuchet MS",
        formatMenu_FontVerdana: "Verdana",
        formatMenu_FontName: "Letra-tipoa",

        layoutMenu: "Diseinua",
        layoutMenu_SlideLayout: "Diapositiba-diseinua...",
        layoutMenu_SlideDesign: "Estilo nagusia...",
        layoutMenu_DefaultFormatting: "Formatu lehenetsia",
        layoutMenu_Textprop_Bold: "Lodia",
        layoutMenu_Textprop_Italic: "Etzana",
        layoutMenu_Textprop_Underline: "Azpimarratu",
        layoutMenu_Textprop_Strikethrough: "Marratu",
        layoutMenu_TextProp: "Testuaren propietateak",
        LayoutMenu_RowHeight: "Errenkadaren altuera...",
        LayoutMenu_ColumnWidth: "Errenkadaren zabalera...",
        LayoutMenu_ShowRow: "Erakutsi errenkada",
        LayoutMenu_HideRow: "Ezkutatu errenkada",
        LayoutMenu_RenameSheet: "Eman beste izen bat orriari...",
        LayoutMenu_MoveSheet: "Mugitu orria",

        tableMenu: "Taula",
        tableMenu_Create: "Sortu...",
        tableMenu_CreateFromTemplate: "Sortu txantiloitik",
        tableMenu_Delete: "Ezabatu",
        tableMenu_SetTableColor: "Koloratu gelaxka",
        tableMenu_CreateTable: "Sortu taula",
        tableMenu_Cell: "Gelaxka",
        tableMenu_CellMergeCells: "Konbinatu gelaxkak",
        tableMenu_CellAlignLeft: "Lerrokatu ezkerrean",
        tableMenu_CellAlignCenter: "Lerrokatu erdian",
        tableMenu_CellAlignRight: "Lerrokatu eskuinean",
        tableMenu_CellClearContents: "Garbitu edukia",
        tableMenu_CellProperties: "Gelaxkaren propietateak...",
        tableMenu_Row: "Errenkada",
        tableMenu_InsertRowAbove: "Txertatu errenkada goian",
        tableMenu_InsertRowBelow: "Txertatu errenkada behean",
        tableMenu_MoveRowAbove: "Mugitu errenkada gorantz",
        tableMenu_MoveRowBelow: "Mugitu errenkada beherantz",
        tableMenu_RowInsertRow: "Txertatu errenkada...",
        tableMenu_RowInsertRowAbove: "Txertatu errenkada goian",
        tableMenu_RowInsertRowBelow: "Txertatu errenkada behean",
        tableMenu_RowMoveRowAbove: "Mugitu errenkada gorantz",
        tableMenu_RowMoveRowBelow: "Mugitu errenkada beherantz",
        tableMenu_RowDelete: "Ezabatu",
        tableMenu_RowRepeat: "Errepikatu goiburuko errenkada",
        tableMenu_InsertColumnBefore: "Txertatu zutabea aurrean",
        tableMenu_InsertColumnAfter: "Txertatu zutabea atzean",
        tableMenu_MoveColumnBefore: "Mugitu zutabea ezkerretara",
        tableMenu_MoveColumnAfter: "Mugitu zutabea eskuinetara",
        tableMenu_ResizeColumn: "Aldatu zutabearen tamaina",
        tableMenu_ResizeColumns: "Aldatu zutabeen tamaina",
        tableMenu_MarkasCategory: "Markatu kategoria gisa",
        tableMenu_ColumnInsertColumn: "Txertatu zutabea...",
        tableMenu_ColumnAddColumnBefore: "Txertatu zutabea aurrean",
        tableMenu_ColumnAddColumnAfter: "Txertatu zutabea atzean",
        tableMenu_ColumnMoveColumnAfter: "Mugitu zutabea eskuinetara",
        tableMenu_ColumnMoveColumnBefore: "Mugitu zutabea ezkerretara",
        tableMenu_ColumnDelete: "Ezabatu",
        tableMenu_ColumnSortAscending: "Ordenatu gorantz",
        tableMenu_ColumnSortDescending: "Ordenatu beherantz",
        tableMenu_Column: "Zutabea",
        tableMenu_Style: "Estiloa",
        tableMenu_TableProperties: "Taularen propietateak...",

        teamMenu: "Taldea",
        teamMenu_AddComment: "Gehitu iruzkina",
        teamMenu_AssignCells: "Esleitu gelaxkak",
        teamMenu_AssignSection: "Esleitu sekzio bat",
        teamMenu_EditAssignment: "Editatu esleipena",
        teamMenu_MarkSectionComplete: "Markatu sekzioa osatuta gisa",
        teamMenu_MarkAssignmentComplete: "Markatu esleipena osatuta gisa",
        teamMenu_WorkPrivatelyOnSection: "Jardun sekzioan pribatuan",
        teamMenu_CancelPrivateWork: "Utzi lan pribatua bertan behera",
        teamMenu_ApproveSection: "Onartu sekzioa",
        teamMenu_ApproveAssignment: "Onartu esleipena",
        teamMenu_ReturnSectionForRework: "Itzuli sekzioa egokitzeko",
        teamMenu_ReturnAssignmentForRework: "Itzuli esleipena egokitzeko",
        teamMenu_RemoveSectionAssignment: "Kendu sekzioaren esleipena",
        teamMenu_RemoveCellAssignment: "Kendu gelaxkaren esleipena",
        teamMenu_RemoveCompletedAssignments: "Kendu osatutako esleipenak",
        teamMenu_AboutThisSection: "Sekzio honi buruz",
        teamMenu_AboutAssignment: "Esleipen honi buruz",

        presentationMenu: "Aurkezpena",
        presentationMenu_SlideShow: "Erreproduzitu diaporama",
        presentationMenu_SlideShowWithCoview: "Erreproduzitu diaporama partekatua",
        presentationMenu_SlideTransitions: "Ezarri diapositiba-trantsizioa...",
        presentationMenu_SlideShowFromCurrent: "Erreproduzitu uneko diapositibatik",
        presentationMenu_EmptyCoviewInvites: "Ez dago diaporama partekatu aktiborik",
        presentationMenu_CoviewInvites: "Diaporama partekatu aktiboa",

        dataMenu: "Datuak",
        dataMenu_Sort: "Ordenatu...",
        dataMenu_SortAsc: "Ordenatu gorantz",
        dataMenu_SortDesc: "Ordenatu beherantz",
        dataMenu_ACL: "Area babestuak",
        dataMenu_ACL_DELETE: "Ezabatu baimen guztiak",
        dataMenu_Validity: "Baliotasuna",
        dataMenu_InstantFilter: "Istanteko iragazkia",
        dataMenu_Validation: "Balidazioa...",

        toolsMenu: "Tresnak",
        toolsMenu_AutoComplete: "Gelaxka-sarreren osatze automatikoa",
        toolsMenu_SelectDictionary: "Ortografia egiaztatzeko hiztegiak",
        toolsMenu_Dictionary_ca_CT: "Katalana",
        toolsMenu_Dictionary_cs_CZ: "Txekiera (Txekiar Errepublika)",
        toolsMenu_Dictionary_da_DK: "Daniera (Danimarka)",
        toolsMenu_Dictionary_nl_NL: "Nederlandera (Holanda)",
        toolsMenu_Dictionary_en_AU: "Ingelesa (Australia)",
        toolsMenu_Dictionary_en_GB: "Ingelesa (Britainia Handia)",
        toolsMenu_Dictionary_en_US: "Ingelesa (Estatu Batuak)",
        toolsMenu_Dictionary_fi_FI: "Finlandiera (Finlandia)",
        toolsMenu_Dictionary_fr_FR: "Frantsesa (Frantzia)",
        toolsMenu_Dictionary_fr_CA: "Frantsesa (Kanada)",
        toolsMenu_Dictionary_de_DE: "Alemana (Alemania)",
        toolsMenu_Dictionary_de_CH: "Alemana (Suitza)",
        toolsMenu_Dictionary_el_GR: "Greziera (Grezia)",
        toolsMenu_Dictionary_it_IT: "Italiera (Italia)",
        toolsMenu_Dictionary_pl_PL: "Poloniera (Polonia)",
        toolsMenu_Dictionary_pt_BR: "Portugalera (Brasil)",
        toolsMenu_Dictionary_pt_PT: "Portugalera (Portugal)",
        toolsMenu_Dictionary_ru_RU: "Errusiera (Errusia)",
        toolsMenu_Dictionary_es_ES: "Gaztelania (Espainia)",
        toolsMenu_Dictionary_sv_SE: "Suediera (Suedia)",
        toolsMenu_Dictionary_nb_NO: "Norvegiera (Bokmåla)",
        toolsMenu_Dictionary_nn_NO: "Norvegiera (Nynorsk)",
        toolsMenu_Dictionary_he_IL: "Hebreera (Israel)",
        toolsMenu_SpellCheck: "Hasieratu eskuzko ortografia-egiaztapena...",
        toolsMenu_Preferences: "Hobespenak",
        toolsMenu_Task: "Ataza",
        toolsMenu_Task_Assigntask: "Esleitu ataza bat",
        teamMenu_AssignSlide: "Esleitu diapositiba",
        teamMenu_AssignSlides: "Esleitu diapositibak",
        teamMenu_EditSlide: "Editatu diapositiba-esleipena",
        teamMenu_ReopenSlideAssignment: "Ireki diapositiba-esleipena berriro",
        teamMenu_ReopenSlideAssignments: "Ireki diapositiba-esleipenak berriro",
        teamMenu_ReassignSlide: "Esleitu diapositiba berriro",
        teamMenu_ReassignSlides: "Esleitu diapositibak berriro",
        teamMenu_MarkSlidesComplete: "Markatu diapositiba osatuta gisa",
        teamMenu_MarkSlidesCompletes: "Markatu diapositibak osatuta gisa",
        teamMenu_ApproveSlide: "Onartu diapositiba",
        teamMenu_ApproveSlides: "Onartu diapositibak",
        teamMenu_ReturnForRework: "Itzuli diapositiba egokitzeko",
        teamMenu_ReturnForReworks: "Itzuli diapositibak egokitzeko",
        teamMenu_RemoveAssignment: "Kendu diapositiba-esleipena",
        teamMenu_AboutThisSlide: "Diapositiba honi buruz",

        addOnsMenu: "Gehigarriak",

        helpMenu: "Laguntza",
        helpMenu_About: "Honi buruz",
        helpMenu_Overview: "Laguntza-edukia",
        helpMenu_NewFeatures: "Berriak",
        helpMenu_Tour: "Aurkezpen gidatua",

        accel_fileMenu_Save: "Ctrl+S",
        accel_fileMenu_Save_Mac: "\u2318S",
        accel_fileMenu_Print: "Ctrl+P",
        accel_fileMenu_Print_Mac: "\u2318P",
        accel_editMenu_SelectAll: "Ctrl+A",
        accel_editMenu_SelectAll_Mac: "\u2318A",
        accel_editMenu_Undo: "Ctrl+Z",
        accel_editMenu_Undo_Mac: "\u2318Z",
        accel_editMenu_Redo: "Ctrl+Y",
        accel_editMenu_Redo_Mac: "\u2318Y",
        accel_editMenu_Cut: "Ctrl+X",
        accel_editMenu_Cut_Mac: "\u2318X",
        accel_editMenu_Copy: "Ctrl+C",
        accel_editMenu_Copy_Mac: "\u2318C",
        accel_editMenu_Paste: "Ctrl+V",
        accel_editMenu_Paste_Mac: "\u2318V",
        accel_editMenu_Find: "Ctrl+F",
        accel_editMenu_Find_Mac: "\u2318F",
        accel_insertMenu_Link: "Ctrl+K",
        accel_insertMenu_Link_Mac: "\u2318K",
        accel_insertMenu_Header: "CTRL+SHIFT+H",
        accel_insertMenu_Header_Mac: "\u21e7\u2318H",
        accel_insertMenu_Footer: "CTRL+SHIFT+F",
        accel_insertMenu_Footer_Mac: "\u21e7\u2318F",
        accel_formatMenu_Textprop_Bold: "Ctrl+B",
        accel_formatMenu_Textprop_Bold_Mac: "\u2318B",
        accel_formatMenu_Textprop_Italic: "Ctrl+I",
        accel_formatMenu_Textprop_Italic_Mac: "\u2318I",
        accel_formatMenu_Textprop_FormatPainter: "Ctrl+SHIFT+C, Ctrl+SHIFT+V",
        accel_formatMenu_Textprop_FormatPainter_Mac: "\u21e7\u2318C, \u21e7\u2318V",
        accel_formatMenu_Textprop_Underline: "Ctrl+U",
        accel_formatMenu_Textprop_Underline_Mac: "\u2318U",
        accel_formatMenu_Headingprop_P: "CTRL+SHIFT+0",
        accel_formatMenu_Headingprop_H1: "CTRL+SHIFT+1",
        accel_formatMenu_Headingprop_H2: "CTRL+SHIFT+2",
        accel_formatMenu_Headingprop_H3: "CTRL+SHIFT+3",
        accel_formatMenu_Headingprop_H4: "CTRL+SHIFT+4",
        accel_formatMenu_Headingprop_H5: "CTRL+SHIFT+5",
        accel_formatMenu_Headingprop_H6: "CTRL+SHIFT+6",
        accel_formatMenu_Superscript: "Ctrl+.",
        accel_formatMenu_Superscript_Mac: "\u2318.",
        accel_formatMenu_Subscript: "Ctrl+,",
        accel_formatMenu_Subscript_Mac: "\u2318,",
        accel_formatMenu_Left: "CTRL+SHIFT+L",
        accel_formatMenu_Left_Mac: "\u21e7\u2318L",
        accel_formatMenu_Right: "CTRL+SHIFT+R",
        accel_formatMenu_Right_Mac: "\u21e7\u2318R",
        accel_formatMenu_Center: "CTRL+SHIFT+E",
        accel_formatMenu_Center_Mac: "\u21e7\u2318E",
        accel_formatMenu_Justify: "CTRL+SHIFT+J",
        accel_formatMenu_Justify_Mac: "\u21e7\u2318J",
        accel_formatMenu_Indent: "CTRL+M",
        accel_formatMenu_Indent_Mac: "\u2318M",
        accel_formatMenu_DecreaseIndent: "CTRL+SHIFT+M",
        accel_formatMenu_DecreaseIndent_Mac: "\u21e7\u2318M",
        accel_teamMenu_AddComment: "SHIFT+F2",

        ctxMenuSmartTable: 'Taula',
        ctxMenuTableProperties: "Taularen propietateak",
        ctxMenuDeleteST: 'Ezabatu',
        ctxMenuDeleteSTTable: 'Ezabatu taula',
        ctxMenuChgSTStyle: 'Aldatu estiloa',
        ctxMenuShowCaption: 'Erakutsi epigrafea',
        ctxMenuHideCaption: 'Ezkutatu epigrafea',
        ctxMenuResizeST: 'Aldatu tamaina',
        ctxMenuResizeColumnsST: 'Aldatu zutabeen tamaina',
        ctxMenuSTRow: 'Errenkada',
        ctxMenuAddSTRowAbv: 'Txertatu errenkada goian',
        ctxMenuAddSTRowBlw: 'Txertatu errenkada behean',
        ctxMenuMoveSTRowUp: 'Mugitu errenkada gorantz',
        ctxMenuMoveSTRowDown: 'Mugitu errenkada beherantz',
        ctxMenuDelSTRow: 'Ezabatu',
        ctxMenuRepeatRow: 'Errepikatu goiburuko errenkada',
        ctxMenuSTCol: 'Zutabea',
        ctxMenuAddSTColBfr: 'Txertatu zutabea aurrean',
        ctxMenuAddSTColAft: 'Txertatu zutabea atzean',
        ctxMenuMoveSTColBefore: 'Mugitu zutabea ezkerretara',
        ctxMenuMoveSTColAfter: 'Mugitu zutabea eskuinetara',
        ctxMenuDelSTCol: 'Ezabatu',
        ctxMenuSortSTColAsc: 'Ordenatu gorantz',
        ctxMenuSortSTColDesc: 'Ordenatu beherantz',
        ctxMenuShowAllFacets: 'Erakutsi kategoriak',
        ctxMenuHideAllFacets: 'Ezkutatu kategoriak',
        ctxMenuSTCell: 'Gelaxka',
        ctxMenuMergeCells: 'Konbinatu gelaxkak',
        ctxMenuMergeDown: 'Konbinatu behean dagoen gelaxkarekin',
        ctxMenuVerSplit: 'Zatitu bertikalean',
        ctxMenuHorSplit: 'Zaitu horizontalean',
        ctxMenuSplitCells: 'Zatitu gelaxkak...',
        splitCells: 'Zatitu gelaxka',
        ctxMenuAlignTextLeft: 'Lerrokatu ezkerrean',
        ctxMenuAlignTextCenter: 'Lerrokatu erdian',
        ctxMenuAlignTextRight: 'Lerrokatu eskuinean',
        ctxMenuClearSTCellContent: 'Garbitu edukia',
        ctxMenuMakeHeaderRow: 'Erabili hautatutako errenkada goiburu gisa',
        ctxMenuMakeNonHeaderRow: 'Kendu goiburuaren estiloa',
        ctxMenuMakeHeaderCol: 'Erabili hautatutako zutabea goiburu gisa',
        ctxMenuMakeNonHeaderCol: 'Kendu goiburuaren estiloa',
        SHEET_CONTEXT_Hide: "Ezkutatu", // hide row, column or sheet
        SHEET_CONTEXT_Show: "Erakutsi", // show row, column
        SHEET_CONTEXT_MoveSheet: "Mugitu...", // move sheet
        SHEET_CONTEXT_InsertSheet: "Txertatu...", // insert sheet
        SHEET_CONTEXT_DeleteSheet: "Ezabatu...", // delete sheet	
        SHEET_CONTEXT_DuplicateSheet: "Bikoiztu...", // duplicate sheet
        SHEET_CONTEXT_RenameSheet: "Eman beste izen bat...", // rename sheet
	
        ctxMenu_Image_WrapText: "Moldatu testua",
        ctxMenu_Image_WrapText_Inline: "Lerrokatuta testuarekin",
        ctxMenu_Image_WrapText_Square: "Karratua",
        ctxMenu_Image_WrapText_TopBottom: "Goian eta behean",
        ctxMenu_Image_WrapText_Behind: "Testuaren atzean",
        ctxMenu_Image_WrapText_InFront: "Testuaren aurrean",
        ctxMenu_Image_WrapText_Other: "Aukera gehiago",
        ctxMenu_Image_WrapText_BothSides: "Bi aldeetatik",
        ctxMenu_Image_WrapText_LeftOnly: "Ezkerrean bakarrik",
        ctxMenu_Image_WrapText_RightOnly: "Eskuinean bakarrik",
        ctxMenu_Image_WrapText_LargestOnly: "Luzeena bakarrik",

        ctxMenu_Shape_AddText: "Gehitu testua",

        ctxMenu_Range_ACL: "Babestu barrutia",
        ctxMenu_Sheet_ACL: "Babestu orria",

        ctxMenu_HeaderFooter: "Goiburua / Orri-oina",
        ctxMenu_HeaderFooter_DiffFirst: "Lehenengo orria bakarrik",
        ctxMenu_HeaderFooter_DiffOddEven: "Bereizi orri bakoitiak eta bikoitiak",
        ctxMenu_HeaderFooter_LinkToPre: "Estekatu aurrekora",

        ctxMenu_copy: "Kopiatu",
        ctxMenu_paste: "Itsatsi",
        ctxMenu_delete: "Ezabatu",
        ctxMenu_cut: "Ebaki",
        ctxMenu_select: "Hautatu",
        ctxMenu_properties: "Propietateak",
        ctxMenu_bringToFront: "Ekarri aurrera",
        ctxMenu_sendToBack: "Eraman atzera",
        ctxMenu_arrange: "Antolatu",
        ctxMenu_sendBackward: "Eraman atzerago",
        ctxMenu_sendForward: "Eraman aurrerago",
        ctxMenu_fontStyle: "Letra-estiloa",
        ctxMenu_selectStyle: "Hautatu estiloa",
        ctxMenu_fontSize: "Letra-tamaina",
        ctxMenu_fontFamily: "Letra-tipoaren familia",
        ctxMenu_bold: "Lodia",
        ctxMenu_italic: "Etzana",
        ctxMenu_u: "Azpimarratu",
        ctxMenu_strike: "Marratu",
        ctxMenu_super: "Goi-indizea",
        ctxMenu_sub: "Azpiindizea",
        ctxMenu_color: "Kolorea",
        ctxMenu_bgcolor: "Atzeko planoaren kolorea",
        ctxMenu_highcolor: "Nabarmentze-kolorea",
        ctxMenu_restart: "Hasi zerrenda berriro",
        ctxMenu_continue: "Jarraitu zerrenda",
        ctxMenu_separate: "Banandu zerrenda",
        ctxMenu_join: "Lotu aurreko zerrendari",
        ctxMenu_setNumberVal: "Ezarri numerazio-balioa...",
        webClipboardInfoTitle: "Arbela",
        webClipboardInfoOKBtn: "Ados",
        webClipboardInfoCutMsg: "Arakatzailearen segurtasun-ezarpenek kopiatze automatikoa saihesten dute. Horren ordez, erabili Ctrl+X teklatuan.",
        webClipboardInfoCopyMsg: "Arakatzailearen segurtasun-ezarpenek kopiatze automatikoa saihesten dute. Horren ordez, erabili Ctrl+C teklatuan.",
        webClipboardInfoPasteMsg: "Arakatzailearen segurtasun-ezarpenek editore honek arbelaren datuak atzitzea saihesten dute. Horren ordez, erabili Ctrl+V teklatuan.",

        clearTrackChangeConfirmMsg: "Dokumentu honetan egindako aldaketak nabarmentzen dituen kolore kodea kenduko da betiko. Jarraitu nahi duzu?"
});

