({
	labelPrintConfig: "Ak chcete získať najlepšie výsledky pri tlači, nastavte stranu v prehliadači na túto konfiguráciu:",
	labelConfigPageSize: "Veľkosť strany: ${0}",
	labelConfigOrientation: "Orientácia: ${0}",
	labelConfigHeader: "Hlavička: prázdna",
	labelConfigFooter: "Päta: prázdna",
	labelConfigMargins: "Okraje: ",
	labelConfigMarginTop: "Vrch: ${0}${1}",
	labelConfigMarginBottom: "Spodok: ${0}${1}",
	labelConfigMarginLeft: "Vľavo: ${0}${1}",
	labelConfigMarginRight: "Vpravo: ${0}${1}",
	labelPrintContinue: "Po nastavení prehliadača kliknite na tlačidlo OK a pokračujte v tlači súboru.",
	labelMm: "milimetre",
	labelInch: "palce",
	labelPortrait: "Portrét",
	labelPageA4: "A4",
	labelLetter: "Letter",
	labelLandscape: "Krajinka",
	titlePrintConfig: "Nastavenia tlače",
	titlePrepare: "Príprava na tlač",
	msgPrepare: "Súbor sa pripravuje na tlač. Príprava môže chvíľu trvať.",
	errPrepare: "Nastala chyba počas pripravovania údajov.\nChcete to skúsiť znova?",
	titleErr: "Chyba",
	btnRetry: "Zopakovať"
})
