/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2014. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
	service_unavailable_title: "Zerbitzua ez dago erabilgarri.",
	service_unavailable_content: "${productName} zerbitzua ez dago erabilgarri. Momentu honetan ezin da zure eskaera prozesatu. Saiatu berriro beranduago edo jarri kontaktuan zure administratzailearekin.",
	access_denied_title: "Atzipena ukatu da.",
	viewaccess_denied_content: "Ez daukazu fitxategi hau ikusteko baimenik. Fitxategia publikoa izan behar da edo zurekin partekatua.",
	editaccess_denied_content: "Ez duzu ${productName} erabiltzeko edo fitxategi hau editatzeko baimenik. Fitxategia zurekin partekatu behar dute eta atzitzeko maila Editorea izan behar da. Bestela, baliteke beste editore batek fitxategia blokeatu izana.",
	doc_notfound_title: "Ez da dokumentua aurkitu.",
	doc_notfound_content: "Atzitu nahi duzun dokumentua ezabatu edo mugitu dute. Egiaztatu esteka zuzena den.",
	repository_out_of_space_title: "Ez dago nahikoa leku",
	repository_out_of_space_content: "Ezin da ${0} argitaratu fitxategien tamainaren kuota gainditu duzulako. Murriztu erabilitako lekua beste fitxategiak zaborrontzira mugituz eta ezabatuz.",
	fileconnect_denied_title: "Konexioa ukatu da.",
	fileconnect_denied_content: "${productName} ezin da fitxategiaren biltegiarekin konektatu. Saiatu berriro beranduago edo jarri kontaktuan zure administratzailearekin.",
	unscanned_document_title: "Birusak bilatzeko azterketa burutu da",
	unscanned_document_content: "Connections-en kargatutako fitxategiak automatikoki aztertzen dira. Eskaneatzen amaitu bezain laster edita dezakezu fitxategi hau.",
	malicious_document_title: "Fitxategi gaiztoa",
	malicious_document_content: "Ezin duzu fitxategi hau editatu Connections-ek birus bat aurkitu duelako eskaneatzean.",	
	convservice_unavailable_title: "Bihurketa zerbitzua ez dago eskuragarri.",
	convservice_unavailable_content: "${productName} produktuaren bihurketa-zerbitzua ez dago erabilgarri. Momentu honetan ezin da zure eskaera prozesatu. Saiatu berriro beranduago edo jarri kontaktuan zure administratzailearekin.",
	doc_toolarge_title: "Fitxategia handiegia da.",
	doc_toolarge_content: "Atzitu nahi duzun dokumentua handiegia da.",
	doc_toolarge_content2: "Ezin da fitxategia atzitu. Hona hemen arrazoi posible batzuk:",
	doc_toolarge_content3: "Fitxategia ezin da bistaratu bere tamaina ${0} KB baino handiagoa delako. Editatzeko, fitxategia deskarga dezakezu. Fitxategiak bereizmen handiko irudi batzuk baditu, irudiak ordezkatu ahal dituzu bereizmen txikiko beste irudi batzuekin fitxategiaren tamaina gutxitzeko.",
	doc_toolarge_content4: "Fitxategia handiegia da hemen bistaratzeko. Irekitzeko, izenburuaren barrako deskarga-botoian klik egin dezakezu.",
	doc_toolarge_content_mobile: "Ezin da fitxategia ireki. Gailu mugikorretan, fitxategiak ezin du ${0} KB baino gehiago pisatu.",
	sheet_toolarge_content: "Kalkulu-orriaren tamaina ${0} KB baino handiagoa da.",
	sheet_toolarge_content2: "Kalkulu-orriak ${0} errenkada baino gehiago ditu orri batean.",
	sheet_toolarge_content5: "Kalkulu-orriak ${0} zutabe baino gehiago ditu orri batean.",
	sheet_toolarge_content3: "Kalkulu-orriak ${0} gelaxka baino gehiago ditu.",
	sheet_toolarge_content4: "Kalkulu-orriak ${0} formula baino gehiago ditu.",
	text_toolarge_content: "Dokumentuaren tamaina ${0} KB baino handiagoa da.",
	text_toolarge_content2:"Dokumentuak ${0} orrialde baino gehiago ditu.",
	text_toolarge_content3:"Dokumentuaren testuaren tamaina ${0} KB baino handiagoa da.",
	pres_toolarge_content: "Aurkezpenak ${0} KB baino gehiago pisatzen du eta ezin da atzitu. Aurkezpenak bereizmen handiko irudirik badu, bereizmen gutxiko-irudiekin ordezkatu dezakezu aurkezpenaren tamaina gutxitzeko.",
	pres_toolarge_content2: "Aurkezpenak ${0} orri baino gehiago ditu eta ezin da atzitu.",
	pres_toolarge_content3: "Aurkezpenak ${0} objektu baino gehiago ditu eta ezin da atzitu.",
	pres_toolarge_content2_mobile: "Aurkezpenak ${0} orri baino gehiago ditu gailu mugikorretan eta ezin da ireki.",
	pres_toolarge_content3_mobile: "Aurkezpenak ${0} objektu baino gehiago ditu gailu mugikor batean eta ezin da atzitu.",
	sheet_view_toolarge_content1_mobile: "Kalkulu-orriak ${0} errenkada baino gehiago ditu gailu mugikorretan eta ezin da ikusi.",
	sheet_view_toolarge_content2_mobile: "Kalkulu-orriak ${0} zutabe baino gehiago ditu gailu mugikorretan eta ezin da ikusi.",
	sheet_view_toolarge_content3_mobile: "Kalkulu-orriak ${0} errenkada eta ${1} zutabe baino gehiago ditu gailu mugikorretan eta ezin da ikusi.",
	conversion_timeout_title: "Dokumentuaren bihurketa iraungi da.",
	conversion_timeout_content: "Une honetan, denbora gehiegi behar da dokumentua bihurtzeko. Saiatu berriro beranduago.",
	invalid_docformat_title: "Ezin da dokumentua ireki",
	invalid_docformat_content: "Dokumentuaren luzapena baliozkoa da, baina edukia hondatuta edo enkriptatuta dago eta ezin da irakurri.",
	template_extension_conent_mismatch: "Iturburuaren fitxategi-luzapenak oker identifikatu du fitxategia txantiloi gisa. Fitxategiaren formatu zuzena .${0} da. Hasi txantiloi baliozko batekin edo gorde fitxategia beste izen bat eta .${0} luzapena erabiliz.",
	invalid_docformat_title2: "Ezin da fitxategia inportatu ${productName} produktura.",
	invalid_docformat_content2: "Fitxategi honek ${productName} produktuak une honetan onartzen ez duen ezaugarriren bat dauka. Fitxategi hau ezin da inportatu.",
	invalid_doctype_title: "Dokumentu-mota ez da onartzen.",
	invalid_doctype_content: "${productName} produktuak ez du une honetan dokumentu mota onartzen.",
	unsupported_browser_title: "Arakatzaileak ez ditu eginbide guztiak onartzen",
	malformed_request_title: "Eskaera ez dago ondo osatuta.",
	malformed_request_content: "Ziurtatu URLa eta parametroak zuzenak direla.",
	storageserver_error_title: "Biltegiratze-zerbitzaria ez dago eskuragarri.",
	storageserver_error_content: "Momentu honetan zerbitzaria ez dago eskuragarri. Momentu honetan ezin da zure eskaera prozesatu. Saiatu berriro beranduago edo jarri kontaktuan zure administratzailearekin.",
	document_already_opened_title: "Dokumentua irekita dago",
	document_already_opened_content:"Arakatzaileak dokumentu hau ireki du dagoeneko.",
	toomany_documents_opened_inone_browser_title: "Ezin da dokumentua ireki",
	toomany_documents_opened_inone_browser_content:"Bost ${productName} fitxategi bakarrik ireki ditzakezu aldi berean. Itxi beste dokumentu batzuk eta saiatu dokumentu hau berriro irekitzen.",
	document_max_session_exceeded_title:"Zerbitzua ez dago erabilgarri.",
	document_max_session_exceeded_content:"Erabiltzaile gehiegi dago dokumentuak zerbitzarian editatzen eta ezin da eskaera prozesatu. Saiatu berriro beranduago.",
	kickout_user_content: "Dokumentua irekita dago beste leiho batean. Dokumentua editatzen jarraitu nahi izanez gero, itzuli beste leihora.",
	return_to_files: "Itzuli hona: Fitxategiak",
	return_to_library: "Itzuli hona: Liburutegia",
	return_to_icn: "Itzuli hona: Eduki-nabigatzailea",
	document_already_open: "Dokumentua ireki da dagoeneko",
	cannotedit_noentitled_title: "Fitxategi hau ezin da elkarlanean editatu",
	cannotedit_noentitled_content1: "Erabiltzaile hauek fitxategia editatzen ari dira une honetan:",
	cannotedit_noentitled_content2: "Ez duzu fitxategi hau editatzeko baimena beste batzuk editatzen ari diren bitartean. Saiatu fitxategi hau geroago editatzen.",
	cannotedit_noentitled_content3: "Erabiltzaile hau fitxategia editatzen ari da une honetan:",
	cannotedit_noentitled_content4: "Fitxategia editatzen ari den editoreak ezin du elkarlanean editatu, eta ezin zara edizio-saio honetan sartu. Saiatu fitxategi hau geroago editatzen.",
	toomany_coeditors_title: "Erabiltzaile gehiegi",
	toomany_coeditors_content: "Erabiltzaile gehiegi dago dokumentu hau une honetan editatzen. {0} erabiltzailek bakarrik lan egin dezakete dokumentuarekin aldi berean.",
	encrypted_pptdoc_title:"Fitxategi enkriptatua",
	encrypted_pptdoc_content:"Fitxategi hau pasahitzez babestuta dago. Ezin da editatu ${productName}(e)n aldez aurretik desenkriptatzen ez bada.",
	server_busy_title:"Zerbitzaria okupatuta dago",
	server_busy_content:"Itxaron pixka bat eta saiatu berriro.",
	document_encrypt_title:"Ez da dokumentu enkriptatua onartzen",
	document_encrypt_content:"Fitxategi hau enkriptatuta dago fitxategi-biltegian. Segurtasuna mantentzeko, ${productName}(e)k ezin izan du zuzenean editatu.",
	edit_locked_file: "Ezin duzu fitxategi hau editatu beste editoreek blokeatu dutelako.",
	publish_locked_file: "Fitxategi hau blokeatuta dago eta ezin duzu argitaratu bertsio berri bat gisa. Halere, edukia automatikoki gordeko da zirriborroan.",
	join_locked_file_session: "Beste batzuek fitxategi hau blokeatu dute eta ezin duzu edizio-saioarekin bat egin.",
	no_need_to_convert_title:"Bihurketa ez da beharrezkoa",
	no_need_to_convert_content:"Bihurtu nahi duzun fitxategi-formatua nahi duzuna da dagoeneko. Deskargatu zuzenean.",
	warning_icon: "Abisu-ikonoa",
	//html viewer error message
	incorrect_web_address_title:"Web-helbide okerra.",
	incorrect_web_address_content:"Web-helbidea ez da zuzena.  Sartu web-helbidea eta saiatu berriro.",
	unexpecified_conversion_error_title:"Errorea ez da zehaztu.",
	unexpecified_conversion_error_content:"Zerbitzariak errore zehaztugabe batekin erantzun du.",
	encrypted_conversion_error_title:"Dokumentu enkriptatua ez da onartzen.",
	encrypted_conversion_error_content:"Fitxategia pasahitz baten bidez babestuta dago. Fitxategia ikustailean ikusteko, egiaztatu lehenago fitxategia desenkriptatuta dagoela.",
	service_busy_title:"Dokumentua ezin izan da ireki",
	service_busy_content:"Ikusi nahi duzun fitxategia ezin izan da ireki. Baliteke zerbitzaria lanpetuta egotea edo ezin eskuratzea. Saiatu berriro beranduago edo jarri kontaktuan zure administratzailearekin.",
	empty_doc_title: "Dokumentua hutsik dago.",
	empty_doc_content: "Ziurtatu dokumentuak edukia daukala eta saiatu berriro.",
	corrupted_doc_title: "Ezin da fitxategia ireki.",
	corrupted_doc_content: "Dokumentuak onartu gabeko edukia dauka (adibidez, makroak) eta horregatik ezin da aplikazio honetan ikusi.",
	draft_storage_error_title: "Ezin da dokumentua ireki.",
	draft_storage_error_content: "Edukia hondatuta dago eta ezin da kargatu. Laguntza behar baduzu, jarri harremanetan zure administratzailearekin.",
	unexpected_code_title: "${productName} produktuaren zerbitzariak ustekabeko kodea ematen du.",
	unexpected_code_content: "${productName} produktuaren zerbitzariak ustekabeko kodea ematen du.",
	request_time_out_title: "Dokumentua kargatzeko denbora iraungi egin da.",
	request_time_out_content: "Dokumentu honen karga luze jotzen ari da. Saiatu berriro geroago.",
	problem_id_msg_title: "Eman arazo honen berri administratzaileari ",
	problem_id_msg_show: "Sakatu xehetasunak ikusteko",
	problem_id_msg_hide: "Sakatu ezkutatzeko"
})

