/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2014. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        spreadsheetTemplates: "Kalkulu-orrien txantiloiak",
        documentTemplates: "Dokumentu-txantiloiak",
        titleShareDocument: "Partekatu dokumentua",
        offline: "Lineaz kanpo",
        versionPublishing: "Argitaratu bertsioa.",
        versionPublishFailed: "Bertsioa ez da argitaratu. Baliteke fitxategia handiegia izatea edo zerbitzariak denbora-muga gainditu izatea. Saiatu berriro edo utzi eta eskatu administratzaileari zerbitzari-egunkaria aztertzeko arazoa aurkitzeko.",
        versionCheckinFailed: "Bertsioa ez da babestu. Baliteke fitxategia handiegia izatea edo zerbitzariak denbora-muga gainditu izatea. Saiatu berriro edo utzi eta eskatu administratzaileari zerbitzari-egunkaria aztertzeko arazoa aurkitzeko.",
        versionSavedFailed: "Gordetze prozesua ez da osatu. Saiatu gordetzen berriro geroago.",
        publishFileSizeExceedMsg: "Fitxategiak biltegiaren administratzaileak ezarritako gehienezko tamaina gainditzen du eta ezin da argitaratu. Ezabatu elementu batzuk fitxategia txikiagoa izan dadin edo jarri harremanetan administratzailearekin tamaina-muga handitzeko.",
        checkinFileSizeExceedMsg: "Fitxategiak biltegiaren administratzaileak ezarritako gehienezko tamaina gainditzen du eta ezin da babestu. Ezabatu elementu batzuk fitxategia txikiagoa izan dadin edo jarri harremanetan administratzailearekin tamaina-muga handitzeko.",
        versionpublished: "Bertsio hau ${0}(e)k argitaratu du (${1}).",
        versionPublishing2: "Bertsioa gordetzen.",
        versionPublishFailed2: "Bertsioa ez da gorde. Baliteke fitxategia handiegia izatea edo zerbitzariak denbora-muga gainditu izatea. Saiatu berriro edo utzi eta eskatu administratzaileari zerbitzari-egunkaria aztertzeko arazoa aurkitzeko.",      
        publishFileSizeExceedMsg2: "Fitxategia ezin da gorde, biltegiko administratzaileak ezarritako gehieneko tamaina gainditzen duelako. Ezabatu elementu batzuk fitxategia txikiagoa izan dadin edo jarri harremanetan administratzailearekin tamaina-muga handitzeko.",
        versionpublished2: "Bertsio hau ${0}(e)k gorde du (${1}).",
        chekinCloseDocsMsg: "${productName} itxi dezakezu orain.",
        draftSavingAs: "Fitxategia kopiatzen...",
        draftSavedAs: "Kopia berria gorde da ${0} gisa.",
        synchronizing: "Itxaron zerbitzariarekiko sinkronizatze-prozesua amaitu arte.",
        synchronizeError: "Ezin da zerbitzariarekiko sinkronizatze-prozesua osatu.",
        joinwithoutentitle: "Erabiltzaileak: ${0}(e)k dokumentua editatu nahi du, baina ez duzu lankidetza-edizioan aritzeko baimenik eta ezin da edizio-saioan sartu.",
        joinwithoutentitle2: "Erabiltzaileak: ${0}(e)k dokumentua editatu nahi du, baina ez duzu lankidetza-edizioan aritzeko baimenik eta ezin da edizio-saioan sartu.",
        backtoFiles: "Ireki Nire fitxategiak",
        backtoCommFiles: "Ireki Komunitatearen fitxategiak",
        backtoLibrary: "Ireki Liburutegia",
        backtoICN: "Ireki Content Navigator",
        backtoRepository: "Ireki fitxategien zerrenda",
        createNewSpred: "Sortu kalkulu-orri bat",
        createNewDoc: "Sortu dokumentu bat",
        createNewDocFromTemp: "Sortu dokumentu bat txantiloi batetik",
        shareDoc: "Partekatu dokumentu bat",
        exportPdf: "Orriaren konfigurazioa",
        insertDate: "Data-hautaketa",
        insertTime: "Ordu-hautaketa",
        connect: "Konektatu",
        theDoc: "dokumentua",
        save: "Gorde aldaketak",
        saveBeforeReviewMsg: "Hainbat aldaketa ez dira gorde. Gorde aldaketak eta bidali berriro berrikusteko.",
        submitReviewWidgetsFaiure: "Aplikazioa ez da ondo hasieratu. Bidali berriro berrikusteko geroago.",
        widgetsFaiure: "Aplikazioa ez da ondo hasieratu.",
        slideSorter: "Diapositibak",
        commentsBar: "Iruzkinak",
        draftBadge: "ZIRRIBORROA",
        share: "Partekatu",
        comment: "Iruzkina",
        showSidebar: "Erakutsi alboko barra",
        publishVersion: "Argitaratu",
        checkInVersion: "Babestu",
        saveVersion: "Gorde",
        saved: "Aldaketa guztiak gorde dira",
        saving: "Gordetzen",
        submitFragment: "Bidali",
        aria_inMainMenu: "Menu nagusian zaude",
        aria_inSlideSorter: "Diapositiba-sailkatzearen ikuspegian zaude",
        aria_inSlideEditor: "Diapositiba-editorearen ikuspegian zaude",
        createNewPres: "Sortu aurkezpen bat",
        createNewAppFromTemp: "Sortu dokumentu bat txantiloi batetik",
        textdoc: "testua",
        sheetdoc: "kalkulu-orria",
        presdoc: "aurkezpena",
        saveAsTextErrMsg: "Ezin da testu-dokumentu berria gorde.",
        saveAsPresErrMsg: "Ezin da aurkezpen-dokumentu berria gorde.",
        saveAsSheetErrMsg: "Ezin da kalkulu-orriaren dokumentu berria gorde.",
        saveAsTextErrMsg1: "Ez dago dokumentua gordetzeko nahikoa leku.",
        saveAsPresErrMsg1: "Ez dago aurkezpena gordetzeko nahikoa leku.",
        saveAsSheetErrMsg1: "Ez dago kalkulu-orria gordetzeko nahikoa leku.",
        newDocTextErrMsg: "Ezin da testu-dokumentu berri bat sortu.",
        newDocSheetErrMsg: "Ezin da kalkulu-orriaren dokumentu berri bat sortu.",
        newDocPresErrMsg: "Ezin da aurkezpen-dokumentu berri bat sortu.",
        newDocTextErrMsg2: "Ezin da testu-dokumentu berri bat sortu txantiloitik.",
        newDocSheetErrMsg2: "Ezin da kalkulu-orriaren dokumentu berri bat sortu txantiloitik.",
        newDocPresErrMsg2: "Ezin da aurkezpen-dokumentu berri bat sortu txantiloitik.",
        newDocTextErrMsg3: "Ez dago dokumentu bat sortzeko nahikoa leku.",
        newDocSheetErrMsg3: "Ez dago kalkulu-orri bat sortzeko nahikoa leku.",
        newDocPresErrMsg3: "Ez dago aurkezpen bat sortzeko nahikoa leku.",
        newDocTextErrMsg4: "Badago izenburu hori duen dokumentu bat. Eman beste izenburu bat dokumentu berriari.",
        newDocSheetErrMsg4: "Badago izenburu hori duen kalkulu-orri bat. Eman beste izenburu bat kalkulu-orri berriari.",
        newDocPresErrMsg4: "Badago izenburu hori duen aurkezpen bat. Eman beste izen bat aurkezpen berriari.",        
        aclWarningTitle: "Ezin da bertsio berria editatu",
        aclWarningMsg: "Fitxategiaren jabeak fitxategi honen hainbat area babestu ditu eta hobe da linean editatzen baduzu. Jarri harremanetan fitxategiaren jabearekin (${0}) bertsio berri bat halabeharrez kargatu behar duzula uste baduzu.",
        aclWarningMsgForOwner: "Fitxategi honek hainbat babestutako area ditu. Beraz, ezin izango duzu kargatu duzun bertsio berria linean editatu.  Fitxategi honen babestutako area guztiak ezabatu behar dituzu; gero, kargatutako bertsio berria ireki eta editatu ahal izango duzu.",
        st0: "1.orria",
        st1: "2.orria",
        st2: "3.orria",
        FootnoteMsg: "Orria",
        conflictMsg: "Gatazka sortu da beste editore batzuk aldatzen ari direnarekin.  Zure aldaketa deuseztatu da.",
        undoRedoConflictMsg: "Gatazka sortu da editatzen ari zarenarekin eta beste bat elkarlanean editatzen ari denarekin artean eta desegiteko eta berregiteko eragiketak bertan behera utzi dira",
        bigFileErrMsg: "Dokumentuaren tamaina handiegia da. Freskatu arakatzailea eduki osoa osorik dagoen ikusteko",
        noPermissionMsg: "Ez duzu fitxategi hau editatzeko baimenik. Jarri harremanetan fitxategiaren jabearekin editatzeko baimena lortzeko eta saiatu berriro.",
        networkIssueMsg: "Arazo bat dago sarean.",
        networkIssueTitle: "Arazoren bat dago sarean",
        networkIssueContent: "Arazo bat dago sarean. Freskatu orria eta saiatu berriz konektatzen.",
        lockEditorMsg: "Ezin da dokumentua editatu zerbitzariarekiko konexioa izan arte.",
        offlineReasonMsg: "Saioa iraungi da.",
        offlineReasonForServerUnacceptedMsg: "Ezin da ekintza batzuk prozesatu. Docs guneko zerbitzariak minutu bateko ekintzak baztertuko ditu.",
        offlineReasonForServerDraftFormatChange: "Zerbitzariaren eguneratzea dela eta, dokumentuaren formatua zaharkituta dago.",
        reloadExplanationMsg: "Hasi saioa berriro lan egiten jarraitzeko.",
        reloadBtnLabel: "Kargatu berriro",
        reconnectingMsg: "Itxaron zerbitzariarekiko konexioa ezarri arte.",
        loadMsg: "Itxaron dokumentua kargatu arte.",
        loadingDocumentMsg: "Itxaron dokumentua zerbitzaritik kargatu arte.",
        reLoadingDocumentMsg: "Itxaron dokumentua zerbitzaritik berriro kargatu arte.",
        unsupportMsg: "Onartuta ez dagoen eginbide bat aurkitu da. Ikusi xehetasun gehiago.",
        browserWorkingMsg: "Lanean...",
        fileDeepDetectTitle: "Fitxategiaren formatua eta fitxategiaren luzapena ez datoz bat",
        fileDeepDetectMsg: "Fitxategiaren formatua eta fitxategiaren luzapenak adierazten duen formatua ez dira berdinak. Sakatu Jarraitu fitxategia formatu honekin editatzeko.",
        fileDeepDetectOkLabel: "Jarraitu",
        tipInfo: "Aholkua: ${0}",
        selectTextInfo: "Hautatu testua estiloa ezartzeko.",
        removeRecentFile: "Ireki nahi duzun fitxategia ezabatu dute. Fitxategiaren izena kendu nahi duzu Azken fitxategiak zerrendatik?",
        altLotusIcon: "",
        altErrorMsgIcon: "Errore-mezua",
        altWarningMsgIcon: "Abisu-mezua",
        altSuccessMsgIcon: "Arrakasta-mezua",
        sidebarLandmarkDesc: "alboko barra",
        footerTitle: "orri-oina",
        mainDesc: "eduki-area",
        editLockedDocumentWarning: "Fitxategi hau blokeatu duzu beste batzuk fitxategia editatzen ari ziren bitartean. Egin elkarlana beraiekin aldaketak batera egiteko edo eskatu iezaiezu edizio-prozesua bukatzeko editatzeko baimena zuk bakarrik izateko.",
        observerMode: "Behatzaile moduan zaude",
        editorMode: "Editore moduan zaude",
        maxEditorLimitReached: "Dokumentua saio honetarako gehienezko editore-kopurura heldu da (${0}). Editore bat dokumentutik irtetean edo behatzaile modura pasatzean, editore modura pasa zaitezke.",
        maxEditorLimitReachedTitle: "Gehienezko editore-kopurura heldu da",
        uploadNewVersionOpenConfirm: "${0}(e)k bertsio berri bat kargatu du (${2} - ${1}). Bertsio berria ireki nahi duzu?", //${0} name, ${1} time, ${2} date
        uploadNewVersionPublishConfirm: "${0}(e)k bertsio berri bat kargatu du (${2} - ${1}).", //${0} name, ${1} time, ${2} date
        you: "Zu(k)",
        today: "gaur",
        yesterday: "atzo",
        slideShowInviteMsg: "${0} erabiltzaileak diaporama partekatu bat hasieratu du. Bat egin nahi duzu?",
        slideShowInviteTitle: "Diaporama partekatuaren gonbidapena",
        slideShowInviteTitle1: "Diaporama partekatuaren gonbidapen kolektiboa",
        slideShowCoviewSelectUsersTitle: "Diaporama partekatua",
        slideShowCoviewSelectUsersTitle1: "Diaporama kolektiboa",
        slideShowCoviewStmt: "Partekatu aurkezpenaren uneko egoera diaporama partekatu batean.",
        slideShowCoviewStmt1: "Partekatu aurkezpenaren uneko egoera diaporama kolektibo batean.",
        slideShowCoviewOptionOne: "Gonbidatu editore guztiak diaporamara.",
        slideShowCoviewOptionOne1: "Gonbidatu editore eta behatzaile guztiak diaporamara.",
        slideShowCoviewOptionTwo: "Gonbidatu bakarrik editore hauek diaporamara.",
        slideShowCoviewOptionTwo1: "Gonbidatu bakarrik editore eta behatzaile hauek diaporamara.",
        slideShowCoviewSlidesOf: "Diapositiba ${0} / ${1}",  //as in Slide 1 of 4
        slideShowCoviewViewers: "${0} ikusle",
        slideShowCoviewDialogInput: "Idatzi izena iragazteko",
        slideShowCoviewAddTitle: "Gehitu diaporama partekatura",
        slideShowCoviewAddTitle1: "Gehitu diaporama kolektibora",
        slideShowCoviewMessage: "Hautatu erabiltzaile gehiago diaporama partekatu honetara gonbidatzeko.",
        slideShowCoviewMessage1: "Hautatu erabiltzaile gehiago diaporama kolektibo honetara gonbidatzeko.",
        slideShowCoviewEnded: "Diaporama partekatua amaitu da",
        slideShowCoviewEndMessage: "Atzitu nahi duzun diaporama jada ez dago erabilgarri.",
        slideShowCoviewEndMessage2: "${0} erabiltzaileak diaporama partekatua amaitu du.",
        slideShowWarning: "Uneko diaporama itxi behar duzu beste bat abiarazi baino lehen.",
        slideShowHoverMsg: "Egin klik diaporama nor ikusten ari den jakiteko.",
        slideShowHoverMsgAdd: "Egin klik ikusle gehiago gonbidatzeko.",
        csvEmpty: "Orriak ez dauka daturik eta ezin da .csv fitxategi gisa esportatu.",
        edit: "Editatu",
        printToPDF: "Deskargatu PDF gisa",
        print: "Inprimatu",
        view: "Ikusi",
        openLatestFile: "Ireki azken fitxategia",
        updateDocument: "Dokumentua eguneratu da.${0}.",
        updateSpreadsheet: "Kalkulu-orria eguneratu da.${0}",
        updatePresentation: "Aurkezpena eguneratu egin da.${0}.",
        labelCancel: "Utzi",
        msgConversionFail: "Bihurketak huts egin du",
        updateNow: "Ireki orain",
        fileUpdated: "Dokumentua eguneratu da",
        fileUpdatedContent1: "Dokumentua eguneratu da. Ireki azken fitxategia inprimatu baino lehen.",
        htmlviewerlimitation1: "Kalkulu-orri honek bistaratu ezin den taula dinamikoa dauka",
        htmlviewerlimitation2: "Kalkulu-orri honek bistaratu ezin den baldintzapeko formatua dauka",
        htmlviewerlimitation3: "Kalkulu-orri honek bistaratu ezin den taula dinamikoa eta baldintzapeko formatua dauka",
        close: "Itxi",
        closeDocs: "Itxi ${productName}",
        endSessionDlgTitle: "Edizio-saioa amaitu da",
        endSessionDlgNotice: "${0}(e)k fitxategia babestu du eta edizio-saioa amaitu da.",
        labelStopReview: "Gelditu berrikuspena",
        labelRejct: "Baztertu",
        labelApprove: "Onartu",
        errorMsg: "Errorea",
        labelItemNotFountTitle: "Ezin da ekintza osatu.",
        labelItemNotFountMsg: "Beste erabiltzaile bat hasi da dokumentu hau kudeatzen. Informazio gehiago nahi izanez gero, itxi dokumentua eta joan zaitez fitxategi-xehetasunen orrira liburutegian.",
        viewProtectedAreas: "Kalkulu-orri honek hainbat babestutako area ditu. Linean bakarrik ikusi edota editatu behar duzu.",
        macroTitle: "Fitxategiak makro bat du", 
        macroDesc: "Fitxategi hau editatzen bada, agian makroa apurtuko da. Makroa duen barrutia edo orria editatzea galarazteko jendeari, erabili Datuak > Babestutako areak.",
        problem_id_msg_title: "Eman arazo honen berri administratzaileari ",
        problem_id_msg_show: "Sakatu xehetasunak ikusteko",
    	problem_id_msg_hide: "Sakatu ezkutatzeko",
    	uploadNewVersionWarningTitle: "Ezin da bertsio berria editatu",
        changeHistoryWarningMsg: "Fitxategiaren jabeak Aldaketen Kontrola aktibatu du, eta, beraz, hobe da online editatzea. Jarri harremanetan fitxategiaren jabearekin (${0}) bertsio berri bat halabeharrez kargatu behar duzula uste baduzu.",
        changeHistoryWarningMsgForOwner: "Fitxategi honek Aldaketa Historia dauka. Beraz, ezin izango duzu kargatu duzun bertsio berria linean editatu.  Fitxategi honen Aldaketa Historia ezabatu eta Aldaketen Kontrola desaktibatu behar duzu; gero, kargatutako bertsio berria ireki eta editatu ahal izango duzu..",
        viewChangeHistory: "Dokumentu honek aldaketa-historia dauka. Linean bakarrik ikusi edota editatu behar duzu.",
    	contentCorruptErrMsg: "Edukia hondatuta dago eta ezin da kargatu. Laguntza behar baduzu, jarri harremanetan zure administratzailearekin."
});

