({	
	createTaskSummary: "${0} opprettet oppgaven.",
	completeTaskSummary: "${0} merket oppgaven som fullført.",
	editTaskSummary5: "${0} redigerte oppgavens ${1}, ${2}, ${3}, ${4} og ${5}.",
	editTaskSummary4: "${0} redigerte oppgavens ${1}, ${2}, ${3} og ${4}.",
	editTaskSummary3: "${0} redigerte oppgavens ${1}, ${2} og ${3}.",
	editTaskSummary2: "${0} redigerte oppgavens ${1} og ${2}.",
	editTaskSummary1: "${0} redigerte oppgavens ${1}.",
	editTaskSummary0: "${0} redigerte oppgaven.",
	removeTaskSummary: "${0} fjernet oppgaven.",
	reopenTaskSummary: "${0} gjenåpnet oppgaven.",
	reassignTaskSummary: "${0} tildelte ${1} på nytt fra ${2} til ${3}.",
	reassignTaskSummary2: "${0} endret tildelt person fra ${1} til ${2} og korrekturleseren fra ${3} til ${4}.",
	workPrivateSummary: "${0} begynte å arbeide privat på denne oppgaven.",
	approveTaskSummary: "${0} godkjente denne oppgaven.",
	rejectTaskSummary: "${0} forkastet denne oppgaven.",
	rejectTaskSummary2: "${0} returnerte denne oppgaven til ${1} for omarbeiding.",
	submitTaskSummary: "${0} sendte privat arbeid tilbake til dokumentet.",
	cancelPrivateSummary: "${0} avbrøt det private arbeidet.",
	updatedFieldsDesc: "${0}: ${1} -> ${2}",
	fieldAssignee: "tildelt person",
	fieldDuedate: "frist",
	fieldDescription: "beskrivelse",
	fieldReviewer: "korrekturleser",
	fieldTitle: "tittel",
	emptyFieldValue: "[Ikke tildelt]",
	errorAddMember:"Det er ikke tilgang til aktivitetsserveren for å legge til tildelte personer eller korrekturlesere. Prøv igjen senere.",
	errorCreateActivity:"Det er ikke tilgang til aktivitetsserveren for å opprette aktiviteten. Prøv igjen senere.",
	errorLoadActivity:"Det er ikke tilgang til aktivitetsserveren for å laste inn tildelinger. Prøv igjen senere.",
	errorCreateAssignment: "Det er ikke tilgang til aktivitetsserveren for å opprette tildelingen. Prøv igjen senere.",
	errorDeleteAssignment: "Det er ikke tilgang til aktivitetsserveren for å slette tildelinger. Prøv igjen senere.",
	errorupdateAssignment: "Det er ikke tilgang til aktivitetsserveren for å oppdatere tildelinger. Prøv igjen senere.",
	errorSubmitAssignment: "Du kan ikke utføre denne handlingen. Kontroller om du har tillatelse til å utføre den.",	
	errorAddMember2:"Det er ikke tilgang til serveren for å legge til tildelte personer eller korrekturlesere. Prøv igjen senere.",
	errorCreateActivity2:"Det er ikke tilgang til serveren for å opprette aktiviteten. Prøv igjen senere.",
	errorLoadActivity2:"Det er ikke tilgang til serveren for å laste inn tildelinger. Prøv igjen senere.",
	errorCreateAssignment2: "Det er ikke tilgang til serveren for å opprette tildelingen. Prøv igjen senere.",
	errorDeleteAssignment2: "Det er ikke tilgang til serveren for å slette tildelinger. Prøv igjen senere.",
	errorupdateAssignment2: "Det er ikke tilgang til serveren for å oppdatere tildelinger. Prøv igjen senere."	
})
