({
		SAVE: "Αποθήκευση",
		UNDO:"Αναίρεση",
		REDO:"Ακύρωση αναίρεσης",
		INSERTROW:"Εισαγωγή γραμμής",
		DELETEROW:"Διαγραφή γραμμής",
		INSERTCOLUMN:"Εισαγωγή στήλης",
		DELETECOLUMN:"Διαγραφή στήλης",
		FONTSIZE:"Μέγεθος γραμματοσειράς",
		FONTCOLOR:"Χρώμα γραμματοσειράς",
		BOLD:"Έντονη γραφή",
		ITALIC:"Πλάγια γραφή",
		UNDERLINE:"Υπογράμμιση",
		STRIKETHROUGH:"Διαγράμμιση",
		CURRENCYTIP:"Μορφή νομισματικής μονάδας",
		PERCENTLABEL:"%",
		PERCENTTIP:"Μορφή ποσοστού",
		NUMBERFORMAT:"Μορφή αριθμητικών δεδομένων",
		ALIGNLEFT:"Στοίχιση αριστερά",
		ALIGNCENTER:"Στοίχιση στο κέντρο",
		ALIGNRIGHT:"Στοίχιση δεξιά",
		SETCELLBORDER:"Ορισμός περιγράμματος κελιών",
		BACKGROUNDCOLOR:"Χρώμα φόντου",
		TASK:"Ανάθεση ενότητας",
		COMMENTS:"Προσθήκη σχολίου",
		SUBMIT:"Υποβολή",
		MERGECELL: "Συγχώνευση ή διαχωρισμός κελιών",
		QUICKFORMULA: "Γρήγορος υπολογισμός",
		WRAPTEXT: "Αναδίπλωση κειμένου",
		EIGHT:"8 pt",
		NINE:"9 pt",
		TEN:"10 pt",
		ELEVEN:"11 pt",
		TWELVE:"12 pt",
		FOURTEEN:"14 pt",
		SIXTEEN:"16 pt",
		EIGHTEEN:"18 pt",
		TWENTY:"20 pt",
		TWENTYTWO:"22 pt",
		TWENTYFOUR:"24 pt",
		NUMBER:"Αριθμός",
		CURRENCY:"Νόμισμα",
		PERCENT:"Ποσοστό",
		DATE:"Ημερομηνία",
		TIME:"Ώρα",
		DATETIME: "Ημερομηνία/Ώρα",
		MORECURRENCY:"Περισσότερα νομίσματα",
		MOREDATE:"Περισσότερες μορφές",
		
		
		CAD: "Δολάριο Καναδά",
		USD: "Δολάριο",
		EUR: "Ευρώ",
		CHF: "Ελβετικό φράγκο",
		HKD: "Δολάριο Χονγκ Κονγκ",
		DKK: "Κορόνα",
		LTL: "Λίτας",
		PHP: "Πέσο",
		BRL: "Ρεάλ",
		RUR: "Ρούβλι",
		GBP: "Λίρα",
		NLG: "Φιορίνι", // Netherlands
		TWD: "Νέο δολάριο Ταϊβάν",
		THB: "Μπατ", // Thailand
		ITL: "Τουρκική λίρα", // Turkey
		BGL: "Λεβ", // Uzbekistan
		VND: "Ντονγκ", // Vietnam
		KRW: "Ουόν",	// Korean 
		CNY: "Γουάν", // RMB
		JPY: "Γιεν" // Japan Yen
})
