({
	service_unavailable_title: "Der Service ist nicht verfügbar.",
	service_unavailable_content: "Der Service ${productName} ist nicht verfügbar, und Ihre Anfrage kann zurzeit nicht bearbeitet werden. Versuchen Sie es später noch einmal oder wenden Sie sich an Ihren Systemadministrator, um sicherzustellen, dass der ${productName}-Service online ist.",
	access_denied_title: "Zugriff wird verweigert.",
	viewaccess_denied_content: "Sie sind nicht berechtigt, diese Datei anzuzeigen. Die Datei muss öffentlich oder für Sie freigegeben sein.",
	editaccess_denied_content: "Sie sind nicht berechtigt, diese Datei zu bearbeiten. Diese Datei muss für Sie freigegeben sein oder Sie müssen über einen Editorzugriff für diese Datei verfügen.",
	doc_notfound_title: "Der ${productName}-Service kann die Datei nicht finden.",
	doc_notfound_content: "Wenden Sie sich an den Systemadministrator um sicherzustellen, dass der ${productName}-Service ordnungsgemäß eingerichtet ist.",
	fullviewer_notsupport_title: "Dokument nicht gefunden",
	fullviewer_notsupport_content: "Eine neue Dateianzeigefunktion speichert das Dokument unter einer abweichenden URL. Zum Anzeigen des Dokuments suchen Sie die Datei in der Anwendung und klicken Sie auf die Schaltfläche \"Vorschau\".",
	fileconnect_denied_title: "Die Verbindung wurde verweigert.",
	fileconnect_denied_content: "${productName} kann keine Verbindung mit dem Dateirepository herstellen. Versuchen Sie es später noch einmal oder wenden Sie sich an Ihren Systemadministrator.",
	convservice_unavailable_title: "Konvertierungsservice ist nicht verfügbar.",
	convservice_unavailable_content: "Ihre Anfrage kann derzeit nicht bearbeitet werden. Versuchen Sie es später noch einmal oder wenden Sie sich an Ihren Systemadministrator, um sicherzustellen, dass der Konvertierungsservice online ist.",
	doc_toolarge_title: "Die Datei ist zu groß.",
	doc_toolarge_content: "Das Dokument, auf das Sie zugreifen möchten, ist zu groß.",
	doc_toolarge_content2: "Auf die Datei kann aus folgendem Grund nicht zugegriffen werden:",
	doc_toolarge_content3: "Die Datei kann nicht angezeigt werden, da die Größe der Datei ${0} KB überschreitet. Sie können die Datei zum Anzeigen herunterladen. Falls die Datei hoch auflösende Bilder enthält, können Sie diese durch Bilder mit geringer Auflösung ersetzen, um die Größe der Datei zu reduzieren.",
	doc_toolarge_content4: "Die Datei kann nicht angezeigt werden, da die Größe der Datei ${0} ${1} KB überschreitet.",
	doc_toolarge_content5: "Die Datei ist zu groß, um hier angezeigt zu werden. Sie können Sie aber öffnen, indem Sie auf die Schaltfläche zum Herunterladen in der Titelleiste klicken. ",
	edit_locked_file: "Sie können diese Datei nicht bearbeiten, da sie momentan von anderen Benutzern bearbeitet wird.",
	sheet_toolarge_content: "Das Arbeitsblatt ist größer als ${0} KB.",
	sheet_toolarge_content2: "Das Arbeitsblatt enthält mehr als ${0} Zeilen pro Blatt.",
	sheet_toolarge_content5: "Das Arbeitsblatt enthält mehr als ${0} Spalten pro Blatt.",
	sheet_toolarge_content3: "Das Arbeitsblatt enthält mehr als ${0} Zellen.",
	sheet_toolarge_content4: "Das Arbeitsblatt enthält mehr als ${0} Formeln.",
	text_toolarge_content: "Das Dokument ist größer als ${0} KB.",
	text_toolarge_content2:"Das Dokument enthält mehr als ${0} Seiten.",
	text_toolarge_content3:"Der Text des Dokuments ist größer als ${0} KB.",
	pres_toolarge_content: "Die Präsentation ist größer als ${0} KB.",
	pres_toolarge_content2: "Die Präsentation enthält mehr als ${0} Seiten.",
	pres_toolarge_content3: "Die Präsentation enthält mehr als ${0} Grafiken.",
	pdf_toolarge_content: "Die Größe der PDF-Datei überschreitet ${0} KB.",
	conversion_timeout_title: "Das zulässige Zeitlimit für die Dokumentkonvertierung wurde überschritten.",
	conversion_timeout_content: "Zu diesem Zeitpunkt dauert die Konvertierung des Dokuments zu lang. Versuchen Sie es später erneut.",
	invalid_docformat_title: "Der Dokumentinhalt ist nicht gültig.",
	invalid_docformat_content: "Die Dokumenterweiterung ist gültig, aber der Zugriff auf den Inhalt ist nicht möglich. Vergewissern Sie sich, dass die Datei nicht beschädigt ist. ",
	invalid_doctype_title: "Der Dokumenttyp wird nicht unterstützt.",
	invalid_doctype_content: "Der Dokumenttyp wird derzeit nicht von ${productName} unterstützt.",
	malformed_request_title: "URL oder Parameter sind falsch.",
	malformed_request_content: "Vergewissern Sie sich, dass die URL und die Parameter richtig sind.",
	storageserver_error_title: "Der Speicherserver ist nicht verfügbar.",
	storageserver_error_content: "Der Server ist zurzeit nicht verfügbar. Ihre Anfrage kann derzeit nicht bearbeitet werden. Versuchen Sie es später noch einmal oder wenden Sie sich an Ihren Systemadministrator, um sicherzustellen, dass der Speicherservice online ist.",
	incorrect_web_address_title:"Falsche Webadresse.",
	incorrect_web_address_content:"Die Webadresse ist falsch.  Geben Sie die Webadresse ein und versuchen Sie es erneut.",
	unexpecified_conversion_error_title:"Unbekannter Fehler.",
	unexpecified_conversion_error_content:"Der Server hat eine unbekannte Fehlermeldung zurückgegeben.",
	encrypted_conversion_error_title:"Mit CryptoAPI RC4 verschlüsselte Dokumente werden nicht unterstützt.",
	encrypted_conversion_error_content:"Die Datei ist kennwortgeschützt. Um die Datei in ${productName} anzeigen zu können, müssen Sie sie zunächst entschlüsseln.",
	document_encrypt_title:"Das Dokument ist verschlüsselt.",
	document_encrypt_content:"Sie können die Datei nicht online anzeigen, da Sie beim Hochladen in Files verschlüsselt wurde.",
	service_busy_title:"Das Dokument konnte nicht geöffnet werden",
	service_busy_content:"Die Datei, die Sie anzeigen möchten, konnte nicht geöffnet werden. Der Server ist entweder ausgelastet oder nicht verfügbar. Versuchen Sie es später noch einmal oder wenden Sie sich an Ihren Administrator.",
	empty_doc_title: "Das Dokument ist leer.",
	empty_doc_content: "Stellen Sie sicher, dass das Dokument Inhalte enthält, und versuchen  Sie es erneut.",
	corrupted_doc_title: "Die Datei kann nicht geöffnet werden.",
	corrupted_doc_content: "Die Datei enthält nicht unterstützte Inhalte, z. B. Makros, und kann deswegen in dieser Anwendung nicht angezeigt werden.",
	draft_storage_error_title: "Das Dokument kann nicht geöffnet werden.",
	draft_storage_error_content: "Der Inhalt kann nicht geladen werden, da er beschädigt ist. Wenden Sie sich an Ihren Administrator, um Unterstützung zu erhalten.",
	unexpected_code_title: "Das Dokument kann nicht angezeigt werden.",
	unexpected_code_content: "Der ${docsProductName}-Server ist möglicherweise nicht verfügbar. Versuchen Sie es später erneut.",
	unpublished_document_title: "Datei kann nicht angezeigt werden",
	unpublished_document_content: "Es ist keine veröffentlichte Version dieser Datei zur Ansicht vorhanden. Der Dateieigner muss eine Version der Datei veröffentlichen, bevor sie angezeigt werden kann.",
	unscanned_document_title: "Virenprüfung wird abgeschlossen",
	unscanned_document_content: "In Connections hochgeladene Dateien werden automatisch gescannt. Sie können diese Datei anzeigen, wenn die Virenprüfung abgeschlossen ist.",
	malicious_document_title: "Schädliche Datei",
	malicious_document_content: "Sie können diese Datei nicht anzeigen, da Connections bei der Prüfung einen Virus erkannt hat.",
	repository_out_of_space_title: "Nicht genügend Speicherplatz",
	repository_out_of_space_content: "${0} kann nicht veröffentlicht werden, weil Ihr Dateigrößenkontingent erreicht ist. Verkleinern Sie Ihr Kontingent, indem Sie andere Dateien in den Papierkorb verschieben und dann löschen.",
	pdf_error_title:"Die Datei kann nicht geöffnet werden.",
	pdf_error_content:"Die PDF-Datei ist möglicherweise beschädigt.",
	problem_id_msg_title: "Melden Sie dieses Problem Ihrem Administrator. ",
	problem_id_msg_show: "Klicken, um Details anzuzeigen",
	problem_id_msg_hide: "Klicken, um auszublenden"
})
