({
		SAVE: "Zapisz",
		UNDO:"Cofnij",
		REDO:"Ponów",
		INSERTROW:"Wstaw wiersz",
		DELETEROW:"Usuń wiersz",
		INSERTCOLUMN:"Wstaw kolumnę",
		DELETECOLUMN:"Usuń kolumnę",
		FONTSIZE:"Wielkość czcionki",
		FONTCOLOR:"Kolor czcionki",
		BOLD:"Pogrubienie",
		ITALIC:"Kursywa",
		UNDERLINE:"Podkreślenie",
		STRIKETHROUGH:"Przekreślenie",
		CURRENCYTIP:"Formatuj jako walutę",
		PERCENTLABEL:"%",
		PERCENTTIP:"Formatuj jako wartość procentową",
		NUMBERFORMAT:"Format liczb",
		ALIGNLEFT:"Wyrównaj do lewej",
		ALIGNCENTER:"Wyśrodkuj",
		ALIGNRIGHT:"Wyrównaj do prawej",
		SETCELLBORDER:"Ustaw krawędzie komórki",
		BACKGROUNDCOLOR:"Kolor tła",
		TASK:"Przypisz sekcję",
		COMMENTS:"Dodaj komentarz",
		SUBMIT:"Wyślij",
		MERGECELL: "Scal lub podziel komórki",
		QUICKFORMULA: "Szybka formuła",
		WRAPTEXT: "Zawiń tekst",
		EIGHT:"8 pkt",
		NINE:"9 pkt",
		TEN:"10 pkt",
		ELEVEN:"11 pkt",
		TWELVE:"12 pkt",
		FOURTEEN:"14 pkt",
		SIXTEEN:"16 pkt",
		EIGHTEEN:"18 pkt",
		TWENTY:"20 pkt",
		TWENTYTWO:"22 pkt",
		TWENTYFOUR:"24 pkt",
		NUMBER:"Liczba",
		CURRENCY:"Waluta",
		PERCENT:"Wartość procentowa",
		DATE:"Data",
		TIME:"Godzina",
		DATETIME: "Data i godzina",
		MORECURRENCY:"Więcej walut",
		MOREDATE:"Więcej formatów",
		
		
		CAD: "dolar kanadyjski",
		USD: "dolar",
		EUR: "euro",
		CHF: "frank szwajcarski",
		HKD: "dolar hongkoński",
		DKK: "korona",
		LTL: "lit",
		PHP: "peso",
		BRL: "real",
		RUR: "rubel",
		GBP: "funt",
		NLG: "gulden", // Netherlands
		TWD: "nowy dolar tajwański",
		THB: "baht", // Thailand
		ITL: "lira", // Turkey
		BGL: "lew", // Uzbekistan
		VND: "dong", // Vietnam
		KRW: "won",	// Korean 
		CNY: "juan", // RMB
		JPY: "jen" // Japan Yen
})
