({
	labelPrintConfig: "Za najbolje rezultate ispisivanja, upotrijebite sljedeću konfiguraciju postava stranice u pretražitelju:",
	labelConfigPageSize: "Veličina stranice: ${0}",
	labelConfigOrientation: "Orijentacija: ${0}",
	labelConfigHeader: "Zaglavlje: prazno",
	labelConfigFooter: "Donje zaglavlje: prazno",
	labelConfigMargins: "Margine: ",
	labelConfigMarginTop: "Vrh: ${0}${1}",
	labelConfigMarginBottom: "Dno: ${0}${1}",
	labelConfigMarginLeft: "Lijevo: ${0}${1}",
	labelConfigMarginRight: "Desno: ${0}${1}",
	labelPrintContinue: "Nakon postavljanja postavki pretražitelja, kliknite na OK za nastavak ispisivanja datoteke.",
	labelMm: "milimetri",
	labelInch: "inči",
	labelPortrait: "Portret",
	labelPageA4: "A4",
	labelLetter: "Pismo",
	labelLandscape: "Pejzaž",
	titlePrintConfig: "Postavke ispisa",
	titlePrepare: "Priprema za ispis",
	msgPrepare: "Datoteka se priprema za ispis. Priprema može dugo trajati.",
	errPrepare: "Pojavila se greška tijekom pripreme podataka.\nŽelite li pokušati ponovno?",
	titleErr: "Greška",
	btnRetry: "Pokušaj ponovno"
})
