({	
	viewExpandedBtn: "Prikaži manje odgovora",
	viewCollapsedBtn: "Prikaži još ${0} odgovor(a)",
	placeholderMsg: "Ovde unesite poruku",
	sure: "Želite li zaista da izbrišete ovaj komentar?",
	exceed: "Komentar je predugačak.\n Komentar koji ste uneli premašuje maksimalnu dozvoljenu dužinu.\n Skratite ga tako da ne sadrži više od ${0} znak(ov)a i kliknite na Dodaj.",
	remainLabelHint:"Komentar je dostigao ograničenje od 500 znakova.",
	tipsCommentField: "Unesite komentar za sve uređivače ili za jednog uređivača",
	tipsRespondField: "Unesite odgovor za sve uređivače ili za jednog uređivača",	
	resolveBtn: "Reši",	
	replyBtn: "Odgovori",
	saveBtn: "Postavi",
	deleteBtn: "Izbriši",
	cancelBtn: "Otkaži",
	reopenBtn: "Otvori ponovo",
	todayAt: "Danas u ${time}",
	yesterdayAt: "Juče u ${time}",
	dateAt: "${date} u ${time}",
	mentions: "Izaberite korisnika koga ćete pomenuti",
	noMentions: "Dodirnite prazan prostor da biste dovršili unos",
	nocomments: "Nema komentara u dokumentu „${0}“.",
	
	newComments:"Novi komentari",
	mentiontomesomebody:"Neko",
	mentiontome:"${0} vas je pomenuo/la u komentaru",
	
	newcommentsnumber:"Broj nepročitanih komentara",
	jawsnewcommentsnumber: "Broj nepročitanih komentara je ",
	jawsnactivecommentsnumber: "Broj aktivnih komentara je ",
	
	activenum:"Broj aktivnih komentara",
	filterDesc:"Filtriraj komentare",
	menuallcomments:"Svi komentari",
	menutome: "Za mene",
	menubyme: "Od mene",
	menuactive: "Aktivni",
	menuresolved: "Rešeni",
	searchDesc: "Pretraži komentare",
	search: "Pretraži",
	closeDesc: "Zatvori pretragu",
	clear: "Obriši",
	warnEnterKeywords: "Unesite termine za pretragu",
	nocommentstome: "Trenutno nema komentara niti odgovora koji me pominju u dokumentu „${0}“.",
	nocommentsbyme: "Trenutno nema komentara niti odgovora koje sam napisao/la u dokumentu „${0}“.",
	nocommentsar: "Trenutno nema komentara u kategoriji „${0}“ u dokumentu „${1}“.",
	nosearchedcomments: "Trenutno nema komentara niti odgovora koji sadrže „${0}“ u kategoriji „${1}“ u dokumentu „${2}“.",
	
	prevBtn: "Prethodno",
	nextBtn: "Sledeće",
	mentionHint:"Prikazuje se ${0} do ${1} podudaranja od ukupno ${2}",
		
	resolveFlag: "Rešeni komentari",
	jawsCommentHint: "${authorname} je objavio/la komentar ${timestamp}",
	jawsReplyHint: "${authorname} je objavio/la odgovor ${timestamp}",
	jawsContentHint: "Sadržaj je ${content}",
	jawsCommentStatusHint: "Status je ${status}",
	jawsCommentKeyHint: "Možete da pritisnete taster Enter ili razmaknicu da biste otvorili dokument i pogledali kompletnu nit komentara, kao i da biste rešili komentare, odgovorili na njih ili ih izbrisali.",
	jawsMentionHint: "Docs vidžet za pominjanje. Možete da pritisnete taster sa strelicom nagore ili strelicom nadole da biste izabrali korisnika koga želite da pomenete",
	jawsMentionSelected: "Pritisnite taster Enter ili razmaknicu da biste pomenuli nekoga",
	commentDeletedMsg: "Aktuelni komentar je izbrisao drugi uređivač.",
	commentResolvedMsg: "Aktuelni komentar je rešen.",
	warningCommentMsg: "Komentari uneti u Docs za ${0} datoteke podržani su samo onlajn. Veze do komentara će biti uklonjene ako se otpremi nova verzija za uređivanje.",
	orphanCommentTip: "Veza sa komentarima je uklonjena iz ove otpremljene verzije.",
	warningCommentName: "Upozorenje"
})

