﻿﻿/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        fileMenu: "Ficheiro",
        fileMenu_New: "Novo",
        fileMenu_NewDocument: "Documento",
        fileMenu_NewFromTemplate: "A partir do modelo",
        fileMenu_NewDocumentfromTemplate: "Documento a partir do modelo",
        fileMenu_NewPresentation: "Apresentação",
        fileMenu_NewPresentationfromTemplate: "Apresentação a partir do modelo",
        fileMenu_NewSpreadsheet: "Folha de cálculo",
        fileMenu_NewSpreadsheetFromTemplate: "Folha de cálculo a partir do modelo",
        fileMenu_Open: "Abrir",
        fileMenu_Import: "Importar...",
        //	fileMenu_Close: "Close",
        fileMenu_Discard: "Reverter para a última versão",
        fileMenu_ClearTrackChange: "Remover marcações de alteração",
        fileMenu_SpreadsheetSettings: "Definir configuração regional do documento...",
        filemenu_revisionhistory: "Revisões",
        fileMenu_Save: "Guardar",
        fileMenu_SaveAs: "Copiar...",
        fileMenu_AutoPublish: "Publicar automaticamente",
        fileMenu_AutoCheckIn: "Dar entrada automaticamente",
        fileMenu_PublishVersion: "Publicar agora",
        fileMenu_AutoPublish2: "Guardar automaticamente para o repositório",
        //	fileMenu_AutoPublish_Tips: "Makes your changes available to readers at the end of each editing session.",
        fileMenu_PublishVersion2: "Guardar para o repositório agora",
        fileMenu_AutoPublish3: "Guardar automaticamente para ${0}",
        fileMenu_PublishVersion3: "Guardar para ${0} agora",      
        fileMenu_SubmitForReview: "Submeter para revisão...",
        fileMenu_CheckinVersion: "Dar entrada...",
        fileMenu_Unlock: "Desbloquear",
        //	fileMenu_SaveAsDraft: "as Draft",
        //	fileMenu_SaveInMyDocs: "in My Documents",
        //	fileMenu_SaveToSymphony: "to Lotus Symphany",
        fileMenu_DownloadAs: "Descarregar como",
        fileMenu_PDF: "PDF",
        fileMenu_ODF: "ODF",
        fileMenu_DOC: "Microsoft Word 97- 2007 (*.doc)",
        fileMenu_ODS: "ODS",
        fileMenu_XLS: "Microsoft Excel 97-2007 (*.xls) ",
        fileMenu_ShareWith: "Partilhar...",
        fileMenu_ExportAsPDF: "PDF",
        fileMenu_ExportAsODF: "ODF",
        fileMenu_ExportAsPPT: "Microsoft Powerpoint 97- 2007 (*.ppt)",
        //	fileMenu_WebPreview: "Web Preview",
        fileMenu_PrintToPDF: "Imprimir como PDF...",
        fileMenu_ViewFileDetails: "Ver detalhes do ficheiro...",
        fileMenu_RecentFile: "Ficheiros recentes",
        fileMenu_Open: "Abrir",
        fileMenu_Download: "Descarregar",
        fileMenu_Print: "Imprimir",
        fileMenu_Export: "Exportar",
        fileMenu_ExportToCSV: "CSV",
        fileMenu_ExportToPDF: "PDF (.pdf)",
        fileMenu_ExportToMarkdown: "Markdown(.md)",
        fileMenu_ExportToMS: "Formato Microsoft Office (.${FILEEXTENSION})",
        fileMenu_ExportToODF: "Formato Open Document (.${FILEEXTENSION})",
        fileMenu_PgSetup: "Configuração da Página...",

        editMenu: "Editar",
        editMenu_Undo: "Anular",
        editMenu_Redo: "Refazer",
        editMenu_Cut: "Cortar",
        editMenu_Copy: "Copiar",
        editMenu_Paste: "Colar",
        editMenu_DeleteSlide: "Eliminar diapositivo",
        editMenu_SelectAll: "Seleccionar tudo",
        editMenu_Find: "Localizar...",
        editMenu_Replace: "Substituir...",
        editMenu_FindReplace: "Localizar e substituir...",
        editMenu_EditLink: "Adicionar ou editar ligação",
        editMenu_DeleteSheet: "Eliminar folha...",
        editMenu_RenameSheet: "Mudar o nome da folha...",
        editMenu_HideSheet: "Ocultar folha",
        editMenu_MoveSheet: "Mover folha...",
        editMenu_DeleteRow: "Eliminar linha",
        editMenu_DeleteColumn: "Eliminar coluna",
        editMenu_DeleteCellLeft: "Eliminar células e deslocar para a esquerda",
        editMenu_DeleteCellUp: "Eliminar células e deslocar para cima",
        editMenu_ClearCell: "Eliminar conteúdo",

        viewMenu: "Ver",
        viewMenu_Master: "Modelo global",
        viewMenu_Notifications: "Notificações",
        viewMenu_SlideSorter: "Ordenador de diapositivos",
        viewMenu_SpeakerNotes: "Notas do orador",
        viewMenu_Toolbar_Basic: "Básica",
        viewMenu_Toolbar_Advanced: "Avançada",
        viewMenu_Toolbar_None: "Nenhuma",
        viewMenu_Toolbar: "Barra de ferramentas",
        viewMenu_Statusbar: "Barra de estado",
        viewMenu_Navigator: "Navegador...",
        //viewMenu_Sidebar: "Sidebar",
        viewMenu_ShowHideIndicators: "Mostrar indicadores de co-edição",
        viewMenu_Assignment: "Indicadores de atribuição",
        viewMenu_Bookmark: "Marcadores",
        viewMenu_Coediting: "Realces de co-edição",
        viewMenu_Rulers: "Réguas",
        viewMenu_WebLayout: "Esquema da Web",
        viewMenu_AutomaticSpellCheck: "Verificar ortografia ao escrever",
        viewMenu_Formulabar: "Barra de fórmulas",
        viewMenu_moveRight: "Enter move cursor para a direita",
        viewMenu_showFullString: "Expandir conteúdo nas células",
        viewMenu_Doc: "Ver documento",
        viewMenu_Templates: "Modelos",
        viewMenu_GridLines: "Ocultar linhas da grelha",
        viewMenu_UnsupportWarning: "Mostrar mensagens de funções não suportadas",
        viewMenu_HiddenSheets: "Folhas ocultas",
        viewMenu_FreezeRows: "Fixar linhas",
        viewMenu_FreezeColumns: "Fixar colunas",
        viewMenu_NoFrozenRows: "Nenhuma linha fixa",
        viewmenu_NoFrozenColumns: "Nenhuma coluna fixa",
        viewMenu_FreezeXRows: "Fixar ${0} linhas",
        viewMenu_FreezeOneRow: "Fixar ${0} linha",
        viewMenu_FreezeXColumns: "Fixar ${0} colunas",
        viewMenu_FreezeOneColumn: "Fixar ${0} coluna",
        viewMenu_CarriageReturn: "Marcas de formatação",
        viewMenu_Navigation: "Área de navegação",
        viewMenu_ACL: "Áreas editáveis",
        viewMenu_GridOnOff: "Linhas de grelha",
        viewMenu_ObserverMode: 'Modo de observador',

        createMenu: "Inserir",
        createMenu_NewSlide: "Novo diapositivo",
        createMenu_DuplicateSlide: "Duplicar diapositivo",
        createMenu_ImageFromFile: "Imagem...",
        createMenu_TextBox: "Caixa de texto",
        createMenu_Shape: "Forma",
        createMenu_break: "Quebra",
        createMenu_RowAbove: "Linha acima",
        createMenu_RowBelow: "Linha abaixo",
        createMenu_ColumnRight: "Coluna à direita",
        createMenu_ColumnLeft: "Coluna à esquerda",
        createMenu_Sheet: "Folha...",
        createMenu_Image: "Imagem...",
        createMenu_Comments: "Comentário...",
        createMenu_WebLink: "Ligação da Web...",
        createMenu_SpecialCharacter: "Carácter especial...",
        createMenu_Function: "Função...",
        createMenu_Fromtemplate: "Criar a partir do modelo",

        insertMenu: "Inserir",
        insertMenu_break: "Quebra de página",
        insertMenu_sectionbreak: "Quebra de secção",
        insertMenu_Bookmark: "Marcador...",
        insertMenu_WebLink: "Ligação...",
        insertMenu_SpecialCharacter: "Carácter especial...",
        insertMenu_HorizontalLine: "Linha horizontal",
        insertMenu_Header: "Cabeçalho",
        insertMenu_Footer: "Rodapé",
        insertMenu_TableOfContents: "Índice",

        insertMenu_HeaderFooter: "Cabeçalho/rodapé",
        insertMenu_HF_Edit: "Editar",
        insertMenu_HF_Hide: "Ocultar",
        insertMenu_Endnotes: "Notas finais",
        insertMenu_RowAbove: "Linha acima",
        insertMenu_PageNumber: "Número de página",
        insertMenu_PageNumberTop: "Início da página",
        insertMenu_PageNumberBottom: "Fim de página",
        insertMenu_PageNumberCurr: "Posição actual",
        insertMenu_TotalPageNumber: "Página 1 de N",
        insertMenu_Date: "Data...",
        insertMenu_Time: "Hora...",
        insertMenu_Fields: "Campos",
        //    insertMenu_Comment: "Comment",
        insertMenu_CellRight: "Células e deslocar para a direita",
        insertMenu_CellDown: "Células e deslocar para baixo",
        insertMenu_RowBelow: "Linha abaixo",
        insertMenu_ColumnBefore: "Coluna antes",
        insertMenu_ColumnAfter: "Coluna depois",
        insertMenu_Sheet: "Folha...",
        insertMenu_Image: "Imagem...",
        insertMenu_DuplicateSheet: "Duplicar folha",
        insertMenu_Function: "Função",
        insertMenu_FunctionSum: "SOMA",
        insertMenu_FunctionAverage: "MÉDIA",
        insertMenu_FunctionCount: "CONTAR",
        insertMenu_FunctionMax: "MÁX",
        insertMenu_FunctionMin: "MÍN",
        insertMenu_FunctionMore: "Mais funções...",
        insertMenu_NameRange: "Intervalo especificado",
        insertMenu_NameRangeNew: "Novo intervalo...",
        insertMenu_NameRangeManage: "Gerir intervalos...",
        insertMenu_Chart: "Gráfico...",

        contextMenu_insertCellRight: "Inserir células e deslocar para a direita",
        contextMenu_insertCellDown: "Inserir células e deslocar para baixo",
        contextMenu_InsertRowAbove: "Inserir linha acima",
        contextMenu_InsertRowBelow: "Inserir linha abaixo",
        contextMenu_InsertColumnBefore: "Inserir coluna antes",
        contextMenu_InsertColumnAfter: "Inserir coluna depois",
        contextMenu_DownloadImage: "Descarregar como Imagem",

        formatMenu: "Formatar",
        formatMenu_Columns: "Colunas",
        formatMenu_DefaultFormatting: "Formatação predefinida",
        formatMenu_Template: "Estilos...",
        contextMenu_Template: "Estilos de tabela...",
        formatMenu_LineSpacing: "Espaçamento de linhas",
        formatMenu_LineSpacing1: "1",
        formatMenu_LineSpacing12: "1,2",
        formatMenu_LineSpacing15: "1,5",
        formatMenu_LineSpacing2: "2",
        formatMenu_LineSpacing25: "2,5",
        formatMenu_LineSpacing3: "3",
        formatMenu_TextProperties: "Propriedades do texto",
        formatMenu_PageBreakBefore: "Quebra de página antes",
        formatMenu_KeepLines: "Manter linhas juntas",
        formatMenu_WidowControl: "Controlo de linhas isoladas",
        formatMenu_Pagination: "Propriedades de parágrafo",
        formatMenu_Bold: "Negrito",
        formatMenu_Italic: "Itálico",
        formatMenu_Underline: "Sublinhado",
        formatMenu_Strikethrough: "Rasurado",
        formatMenu_IncreaseSize: "Aumentar tamanho do tipo de letra",
        formatMenu_DecreaseSize: "Diminuir tamanho do tipo de letra",
        formatMenu_ImageProperties: "Propriedades da imagem...",
        formatMenu_ChartProperties: "Propriedades do gráfico...",
        formatMenu_EditChart: "Editar gráfico",
        formatMenu_InsertChart: "Inserir gráfico",
        formatMenu_Properties: "Propriedades...",
        formatMenu_Heading: "Título",
        formatMenu_Normal: "Normal",
        formatMenu_Title: "Título",
        formatMenu_Subtitle: "Subtítulo",
        formatMenu_Heading1: "Título 1",
        formatMenu_Heading2: "Título 2",
        formatMenu_Heading3: "Título 3",
        formatMenu_Heading4: "Título 4",
        formatMenu_Heading5: "Título 5",
        formatMenu_Heading6: "Título 6",
        formatMenu_Heading7: "Título 7",
        formatMenu_Heading8: "Título 8",
        formatMenu_Heading9: "Título 9",
        formatMenu_BulletedList: "Lista marcada",
        formatMenu_NumberedList: "Lista numerada",
        formatMenu_OutLine: "Lista multinível",
        formatMenu_Superscript: "Superior à linha",
        formatMenu_Subscript: "Inferior à linha",
        formatMenu_Align: "Alinhar",
        formatMenu_Left: "Esquerda",
        formatMenu_Right: "Direita",
        formatMenu_Center: "Centro",
        formatMenu_Justify: "Justificar",
        formatMenu_Text_Direction: "Direcção do texto",
        formatMenu_Ltr: "Esquerda para a direita",
        formatMenu_Rtl: "Direita para a esquerda",
        formatMenu_LineSpacing: "Espaçamento de linhas",
        formatMenu_LineSpacing1: "1",
        formatMenu_LineSpacing115: "1,15",
        formatMenu_LineSpacing15: "1,5",
        formatMenu_LineSpacing2: "2",
        formatMenu_LineSpacing25: "2,5",
        formatMenu_LineSpacing3: "3.0",
        formatMenu_Top: "Superior",
        formatMenu_Bottom: "Inferior",
        formatMenu_Middle: "Centro",
        formatMenu_Direction: "Direcção do texto",
        formatMenu_Rtl: "Direita para a esquerda",
        formatMenu_Ltr: "Esquerda para a direita",
        formatMenu_Auto: "Contextual",
        formatMenu_SheetDirection: "Direcção da folha",
        formatMenu_SheetRtl: "Direita para a esquerda",
        formatMenu_SheetLtr: "Esquerda para a direita",
        formatMenu_Indent: "Aumentar indentação",
        formatMenu_DecreaseIndent: "Diminuir indentação",
        formatMenu_ClearFormat: "Limpar formatação",
        formatMenu_RowHeight: "Altura da linha",
        formatMenu_ColumnWidth: "Largura da coluna",
        formatMenu_ShowRow: "Mostrar linha",
        formatMenu_HideRow: "Ocultar linha",
        formatMenu_ShowColumn: "Mostrar coluna",
        formatMenu_HideColumn: "Ocultar coluna",
        formatMenu_WrapText: "Translinear texto",
        formatMenu_Number: "Número",
        formatMenu_FontArial: "Arial",
        formatMenu_FontComicSansMS: "Comic Sans MS",
        formatMenu_FontCourierNew: "Courier New",
        formatMenu_FontGeorgia: "Georgia",
        formatMenu_FontLucidaSansUnicode: "Lucida Sans Unicode",
        formatMenu_FontTahoma: "Tahoma",
        formatMenu_FontTimesNewRoman: "Times New Roman",
        formatMenu_FontTrebuchetMS: "Trebuchet MS",
        formatMenu_FontVerdana: "Verdana",
        formatMenu_FontName: "Tipo de letra",

        layoutMenu: "Esquema",
        layoutMenu_SlideLayout: "Esquema de diapositivo...",
        layoutMenu_SlideDesign: "Estilo de modelo global...",
        layoutMenu_DefaultFormatting: "Formatação predefinida",
        layoutMenu_Textprop_Bold: "Negrito",
        layoutMenu_Textprop_Italic: "Itálico",
        layoutMenu_Textprop_Underline: "Sublinhado",
        layoutMenu_Textprop_Strikethrough: "Rasurado",
        layoutMenu_TextProp: "Propriedades do texto",
        LayoutMenu_RowHeight: "Altura da linha...",
        LayoutMenu_ColumnWidth: "Largura da coluna...",
        LayoutMenu_ShowRow: "Mostrar linha",
        LayoutMenu_HideRow: "Ocultar linha",
        LayoutMenu_RenameSheet: "Mudar o nome da folha...",
        LayoutMenu_MoveSheet: "Mover folha",

        tableMenu: "Tabela",
        tableMenu_Create: "Criar...",
        tableMenu_CreateFromTemplate: "Criar a partir do modelo",
        tableMenu_Delete: "Eliminar",
        tableMenu_SetTableColor: "Colorir célula",
        tableMenu_CreateTable: "Criar tabela",
        tableMenu_Cell: "Célula",
        tableMenu_CellMergeCells: "Unir células",
        tableMenu_CellAlignLeft: "Alinhar à esquerda",
        tableMenu_CellAlignCenter: "Alinhar ao centro",
        tableMenu_CellAlignRight: "Alinhar à direita",
        tableMenu_CellClearContents: "Limpar conteúdo",
        tableMenu_CellProperties: "Propriedades da célula...",
        tableMenu_Row: "Linha",
        tableMenu_InsertRowAbove: "Inserir linha acima",
        tableMenu_InsertRowBelow: "Inserir linha abaixo",
        tableMenu_MoveRowAbove: "Mover linha para cima",
        tableMenu_MoveRowBelow: "Mover linha para baixo",
        tableMenu_RowInsertRow: "Inserir linha...",
        tableMenu_RowInsertRowAbove: "Inserir linha acima",
        tableMenu_RowInsertRowBelow: "Inserir linha abaixo",
        tableMenu_RowMoveRowAbove: "Mover linha acima",
        tableMenu_RowMoveRowBelow: "Mover linha abaixo",
        tableMenu_RowDelete: "Eliminar",
        tableMenu_RowRepeat: "Repetir linha do cabeçalho",
        tableMenu_InsertColumnBefore: "Inserir coluna antes",
        tableMenu_InsertColumnAfter: "Inserir coluna depois",
        tableMenu_MoveColumnBefore: "Mover coluna para a esquerda",
        tableMenu_MoveColumnAfter: "Mover coluna para a direita",
        tableMenu_ResizeColumn: "Redimensionar coluna",
        tableMenu_ResizeColumns: "Redimensionar colunas",
        tableMenu_MarkasCategory: "Marcar como categoria",
        tableMenu_ColumnInsertColumn: "Inserir coluna...",
        tableMenu_ColumnAddColumnBefore: "Inserir coluna antes",
        tableMenu_ColumnAddColumnAfter: "Inserir coluna depois",
        tableMenu_ColumnMoveColumnAfter: "Mover coluna depois",
        tableMenu_ColumnMoveColumnBefore: "Mover coluna antes",
        tableMenu_ColumnDelete: "Eliminar",
        tableMenu_ColumnSortAscending: "Ordenar de forma ascendente",
        tableMenu_ColumnSortDescending: "Ordenar de forma descendente",
        tableMenu_Column: "Coluna",
        tableMenu_Style: "Estilo",
        tableMenu_TableProperties: "Propriedades da tabela...",

        teamMenu: "Equipa",
        teamMenu_AddComment: "Adicionar comentário",
        teamMenu_AssignCells: "Atribuir células",
        teamMenu_AssignSection: "Atribuir uma secção",
        teamMenu_EditAssignment: "Editar atribuição",
        teamMenu_MarkSectionComplete: "Marcar secção como concluída",
        teamMenu_MarkAssignmentComplete: "Marcar atribuição como concluída",
        teamMenu_WorkPrivatelyOnSection: "Trabalhar em privado na secção",
        teamMenu_CancelPrivateWork: "Cancelar trabalho privado",
        teamMenu_ApproveSection: "Aprovar secção",
        teamMenu_ApproveAssignment: "Aprovar atribuição",
        teamMenu_ReturnSectionForRework: "Devolver secção para reformulação",
        teamMenu_ReturnAssignmentForRework: "Devolver atribuição para reformulação",
        teamMenu_RemoveSectionAssignment: "Remover atribuição da secção",
        teamMenu_RemoveCellAssignment: "Remover atribuição da célula",
        teamMenu_RemoveCompletedAssignments: "Remover atribuições concluídas",
        teamMenu_AboutThisSection: "Acerca desta secção",
        teamMenu_AboutAssignment: "Acerca desta atribuição",

        presentationMenu: "Apresentação",
        presentationMenu_SlideShow: "Reproduzir apresentação de diapositivos",
        presentationMenu_SlideShowWithCoview: "Reproduzir apresentação de diapositivos partilhada",
        presentationMenu_SlideTransitions: "Aplicar transição de diapositivos...",
        presentationMenu_SlideShowFromCurrent: "Reproduzir a partir do diapositivo actual",
        presentationMenu_EmptyCoviewInvites: "Nenhuma apresentação de diapositivos partilhada activa",
        presentationMenu_CoviewInvites: "Apresentação de diapositivos partilhada activa",

        dataMenu: "Dados",
        dataMenu_Sort: "Ordenar...",
        dataMenu_SortAsc: "Ordenar de forma ascendente",
        dataMenu_SortDesc: "Ordenar de forma descendente",
        dataMenu_ACL: "Áreas protegidas",
        dataMenu_ACL_DELETE: "Eliminar todas as permissões",
        dataMenu_Validity: "Validade",
        dataMenu_InstantFilter: "Filtro instantâneo",
        dataMenu_Validation: "Validação...",

        toolsMenu: "Ferramentas",
        toolsMenu_AutoComplete: "Conclusão automática de entradas de células",
        toolsMenu_SelectDictionary: "Dicionários de verificação ortográfica",
        toolsMenu_Dictionary_ca_CT: "Catalão",
        toolsMenu_Dictionary_cs_CZ: "Checo (República Checa)",
        toolsMenu_Dictionary_da_DK: "Dinamarquês (Dinamarca)",
        toolsMenu_Dictionary_nl_NL: "Neerlandês (Países Baixos)",
        toolsMenu_Dictionary_en_AU: "Inglês (Austrália)",
        toolsMenu_Dictionary_en_GB: "Inglês (Grã-Bretanha)",
        toolsMenu_Dictionary_en_US: "Inglês (Estados Unidos)",
        toolsMenu_Dictionary_fi_FI: "Finlandês (Finlândia)",
        toolsMenu_Dictionary_fr_FR: "Francês (França)",
        toolsMenu_Dictionary_fr_CA: "Francês (Canadá)",
        toolsMenu_Dictionary_de_DE: "Alemão (Alemanha)",
        toolsMenu_Dictionary_de_CH: "Alemão (Suíça)",
        toolsMenu_Dictionary_el_GR: "Grego (Grécia)",
        toolsMenu_Dictionary_it_IT: "Italiano (Itália)",
        toolsMenu_Dictionary_pl_PL: "Polaco (Polónia)",
        toolsMenu_Dictionary_pt_BR: "Português (Brasil)",
        toolsMenu_Dictionary_pt_PT: "Português (Portugal)",
        toolsMenu_Dictionary_ru_RU: "Russo (Rússia)",
        toolsMenu_Dictionary_es_ES: "Espanhol (Espanha)",
        toolsMenu_Dictionary_sv_SE: "Sueco (Suécia)",
        toolsMenu_Dictionary_nb_NO: "Norueguês (Bokml)",
        toolsMenu_Dictionary_nn_NO: "Norueguês (Nynorsk)",
        toolsMenu_Dictionary_he_IL: "Hebraico (Israel)",
        toolsMenu_SpellCheck: "Executar verificação ortográfica manual...",
        toolsMenu_Preferences: "Preferências",
        toolsMenu_Task: "Tarefa",
        toolsMenu_Task_Assigntask: "Atribuir uma tarefa",
        teamMenu_AssignSlide: "Atribuir diapositivo",
        teamMenu_AssignSlides: "Atribuir diapositivos",
        teamMenu_EditSlide: "Editar atribuição de diapositivos",
        teamMenu_ReopenSlideAssignment: "Reabrir atribuição de diapositivos",
        teamMenu_ReopenSlideAssignments: "Reabrir atribuições de diapositivos",
        teamMenu_ReassignSlide: "Reatribuir diapositivo",
        teamMenu_ReassignSlides: "Reatribuir diapositivos",
        teamMenu_MarkSlidesComplete: "Marcar diapositivo como concluído",
        teamMenu_MarkSlidesCompletes: "Marcar diapositivos como concluídos",
        teamMenu_ApproveSlide: "Aprovar diapositivo",
        teamMenu_ApproveSlides: "Aprovar diapositivos",
        teamMenu_ReturnForRework: "Devolver diapositivo para reformulação",
        teamMenu_ReturnForReworks: "Devolver diapositivos para reformulação",
        teamMenu_RemoveAssignment: "Remover atribuição de diapositivos",
        teamMenu_AboutThisSlide: "Acerca deste diapositivo",

        addOnsMenu: "Suplementos",

        helpMenu: "Ajuda",
        helpMenu_About: "Acerca de",
        helpMenu_Overview: "Conteúdo da ajuda",
        helpMenu_NewFeatures: "O que há de novo",
        helpMenu_Tour: "Visita guiada",

        accel_fileMenu_Save: "Ctrl+G",
        accel_fileMenu_Save_Mac: "\u2318S",
        accel_fileMenu_Print: "Ctrl+P",
        accel_fileMenu_Print_Mac: "\u2318P",
        accel_editMenu_SelectAll: "Ctrl+T",
        accel_editMenu_SelectAll_Mac: "\u2318A",
        accel_editMenu_Undo: "Ctrl+Z",
        accel_editMenu_Undo_Mac: "\u2318Z",
        accel_editMenu_Redo: "Ctrl+R",
        accel_editMenu_Redo_Mac: "\u2318Y",
        accel_editMenu_Cut: "Ctrl+X",
        accel_editMenu_Cut_Mac: "\u2318X",
        accel_editMenu_Copy: "Ctrl+C",
        accel_editMenu_Copy_Mac: "\u2318C",
        accel_editMenu_Paste: "Ctrl+V",
        accel_editMenu_Paste_Mac: "\u2318V",
        accel_editMenu_Find: "Ctrl+L",
        accel_editMenu_Find_Mac: "\u2318F",
        accel_insertMenu_Link: "Ctrl+K",
        accel_insertMenu_Link_Mac: "\u2318K",
        accel_insertMenu_Header: "CTRL+SHIFT+H",
        accel_insertMenu_Header_Mac: "\u21e7\u2318H",
        accel_insertMenu_Footer: "CTRL+SHIFT+F",
        accel_insertMenu_Footer_Mac: "\u21e7\u2318F",
        accel_formatMenu_Textprop_Bold: "Ctrl+N",
        accel_formatMenu_Textprop_Bold_Mac: "\u2318B",
        accel_formatMenu_Textprop_Italic: "Ctrl+I",
        accel_formatMenu_Textprop_Italic_Mac: "\u2318I",
        accel_formatMenu_Textprop_FormatPainter: "Ctrl+SHIFT+C, Ctrl+SHIFT+V",
        accel_formatMenu_Textprop_FormatPainter_Mac: "\u21e7\u2318C, \u21e7\u2318V",
        accel_formatMenu_Textprop_Underline: "Ctrl+S",
        accel_formatMenu_Textprop_Underline_Mac: "\u2318U",
        accel_formatMenu_Headingprop_P: "CTRL+SHIFT+0",
        accel_formatMenu_Headingprop_H1: "CTRL+SHIFT+1",
        accel_formatMenu_Headingprop_H2: "CTRL+SHIFT+2",
        accel_formatMenu_Headingprop_H3: "CTRL+SHIFT+3",
        accel_formatMenu_Headingprop_H4: "CTRL+SHIFT+4",
        accel_formatMenu_Headingprop_H5: "CTRL+SHIFT+5",
        accel_formatMenu_Headingprop_H6: "CTRL+SHIFT+6",
        accel_formatMenu_Superscript: "Ctrl+.",
        accel_formatMenu_Superscript_Mac: "\u2318.",
        accel_formatMenu_Subscript: "Ctrl+,",
        accel_formatMenu_Subscript_Mac: "\u2318,",
        accel_formatMenu_Left: "CTRL+SHIFT+E",
        accel_formatMenu_Left_Mac: "\u21e7\u2318L",
        accel_formatMenu_Right: "CTRL+SHIFT+D",
        accel_formatMenu_Right_Mac: "\u21e7\u2318R",
        accel_formatMenu_Center: "CTRL+SHIFT+C",
        accel_formatMenu_Center_Mac: "\u21e7\u2318E",
        accel_formatMenu_Justify: "CTRL+SHIFT+J",
        accel_formatMenu_Justify_Mac: "\u21e7\u2318J",
        accel_formatMenu_Indent: "CTRL+M",
        accel_formatMenu_Indent_Mac: "\u2318M",
        accel_formatMenu_DecreaseIndent: "CTRL+SHIFT+M",
        accel_formatMenu_DecreaseIndent_Mac: "\u21e7\u2318M",
        accel_teamMenu_AddComment: "SHIFT+F2",

        ctxMenuSmartTable: 'Tabela',
        ctxMenuTableProperties: "Propriedades da tabela",
        ctxMenuDeleteST: 'Eliminar',
        ctxMenuDeleteSTTable: 'Eliminar tabela',
        ctxMenuChgSTStyle: 'Alterar estilo',
        ctxMenuShowCaption: 'Mostrar legenda',
        ctxMenuHideCaption: 'Ocultar legenda',
        ctxMenuResizeST: 'Redimensionar',
        ctxMenuResizeColumnsST: 'Redimensionar colunas',
        ctxMenuSTRow: 'Linha',
        ctxMenuAddSTRowAbv: 'Inserir linha acima',
        ctxMenuAddSTRowBlw: 'Inserir linha abaixo',
        ctxMenuMoveSTRowUp: 'Mover linha acima',
        ctxMenuMoveSTRowDown: 'Mover linha abaixo',
        ctxMenuDelSTRow: 'Eliminar',
        ctxMenuRepeatRow: 'Repetir linha do cabeçalho',
        ctxMenuSTCol: 'Coluna',
        ctxMenuAddSTColBfr: 'Inserir coluna antes',
        ctxMenuAddSTColAft: 'Inserir coluna depois',
        ctxMenuMoveSTColBefore: 'Mover coluna antes',
        ctxMenuMoveSTColAfter: 'Mover coluna depois',
        ctxMenuDelSTCol: 'Eliminar',
        ctxMenuSortSTColAsc: 'Ordenar de forma ascendente',
        ctxMenuSortSTColDesc: 'Ordenar de forma descendente',
        ctxMenuShowAllFacets: 'Mostrar categorias',
        ctxMenuHideAllFacets: 'Ocultar categorias',
        ctxMenuSTCell: 'Célula',
        ctxMenuMergeCells: 'Unir células',
        ctxMenuMergeDown: 'Unir com a célula abaixo',
        ctxMenuVerSplit: 'Dividir na vertical',
        ctxMenuHorSplit: 'Dividir na horizontal',
        ctxMenuSplitCells: 'Dividir células...',
        splitCells: 'Dividir célula',
        ctxMenuAlignTextLeft: 'Alinhar à esquerda',
        ctxMenuAlignTextCenter: 'Alinhar ao centro',
        ctxMenuAlignTextRight: 'Alinhar à direita',
        ctxMenuClearSTCellContent: 'Limpar conteúdo',
        ctxMenuMakeHeaderRow: 'Utilizar linha seleccionada como cabeçalho',
        ctxMenuMakeNonHeaderRow: 'Remover estilo do título',
        ctxMenuMakeHeaderCol: 'Utilizar coluna seleccionada como cabeçalho',
        ctxMenuMakeNonHeaderCol: 'Remover estilo do título',
        SHEET_CONTEXT_Hide: "Ocultar", // hide row, column or sheet
        SHEET_CONTEXT_Show: "Mostrar", // show row, column
        SHEET_CONTEXT_MoveSheet: "Mover...", // move sheet
        SHEET_CONTEXT_InsertSheet: "Inserir...", // insert sheet
        SHEET_CONTEXT_DeleteSheet: "Eliminar...", // delete sheet	
        SHEET_CONTEXT_DuplicateSheet: "Duplicar...", // duplicate sheet
        SHEET_CONTEXT_RenameSheet: "Mudar o nome...", // rename sheet
	
        ctxMenu_Image_WrapText: "Translinear texto",
        ctxMenu_Image_WrapText_Inline: "Em linha com o texto",
        ctxMenu_Image_WrapText_Square: "Quadrado",
        ctxMenu_Image_WrapText_TopBottom: "Superior ou inferior",
        ctxMenu_Image_WrapText_Behind: "Atrás do texto",
        ctxMenu_Image_WrapText_InFront: "À frente do texto",
        ctxMenu_Image_WrapText_Other: "Mais texto de translineação",
        ctxMenu_Image_WrapText_BothSides: "Ambos os lados",
        ctxMenu_Image_WrapText_LeftOnly: "Apenas esquerda",
        ctxMenu_Image_WrapText_RightOnly: "Apenas direita",
        ctxMenu_Image_WrapText_LargestOnly: "Apenas maior",

        ctxMenu_Shape_AddText: "Adicionar texto",

        ctxMenu_Range_ACL: "Proteger intervalo",
        ctxMenu_Sheet_ACL: "Proteger folha",

        ctxMenu_HeaderFooter: "Cabeçalho / rodapé",
        ctxMenu_HeaderFooter_DiffFirst: "Apenas primeira página",
        ctxMenu_HeaderFooter_DiffOddEven: "Páginas ímpares e pares diferentes",
        ctxMenu_HeaderFooter_LinkToPre: "Ligação para anterior",

        ctxMenu_copy: "Copiar",
        ctxMenu_paste: "Colar",
        ctxMenu_delete: "Eliminar",
        ctxMenu_cut: "Cortar",
        ctxMenu_select: "Seleccionar",
        ctxMenu_properties: "Propriedades",
        ctxMenu_bringToFront: "Colocar em primeiro plano",
        ctxMenu_sendToBack: "Colocar em segundo plano",
        ctxMenu_arrange: "Posicionar",
        ctxMenu_sendBackward: "Retroceder um nível",
        ctxMenu_sendForward: "Avançar um nível",
        ctxMenu_fontStyle: "Estilo de tipo de letra",
        ctxMenu_selectStyle: "Seleccionar estilo",
        ctxMenu_fontSize: "Tamanho do tipo de letra",
        ctxMenu_fontFamily: "Família do tipo de letra",
        ctxMenu_bold: "Negrito",
        ctxMenu_italic: "Itálico",
        ctxMenu_u: "Sublinhado",
        ctxMenu_strike: "Rasurado",
        ctxMenu_super: "Superior à linha",
        ctxMenu_sub: "Inferior à linha",
        ctxMenu_color: "Cor",
        ctxMenu_bgcolor: "Cor de segundo plano",
        ctxMenu_highcolor: "Cor de realce",
        ctxMenu_restart: "Recomeçar lista",
        ctxMenu_continue: "Continuar lista",
        ctxMenu_separate: "Separar lista",
        ctxMenu_join: "Adicionar à Lista anterior",
        ctxMenu_setNumberVal: "Definir valor de numeração...",
        webClipboardInfoTitle: "Área de transferência",
        webClipboardInfoOKBtn: "OK",
        webClipboardInfoCutMsg: "As definições de segurança do navegador impedem a cópia automática. Em alternativa, utilize Ctrl+X no teclado.",
        webClipboardInfoCopyMsg: "As definições de segurança do navegador impedem a cópia automática. Em alternativa, utilize Ctrl+C no teclado.",
        webClipboardInfoPasteMsg: "As definições de segurança do navegador impedem que este editor aceda aos dados da área de transferência. Em alternativa, utilize Ctrl+V no teclado.",

        clearTrackChangeConfirmMsg: "A codificação de cores que assinala alterações neste documento será removida permanentemente. Pretende continuar?"
});
