/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
	fileMenu: "Ficheiro",
	fileMenu_New: "Novo(a)",
	fileMenu_NewDocument: "Documento",
	fileMenu_NewDocumentfromTemplate: "Documento a partir do modelo",
	fileMenu_NewPresentation: "Apresentação",
	fileMenu_NewPresentationfromTemplate: "Apresentação a partir do modelo",
	fileMenu_NewSpreadsheet: "Folha de cálculo",
	fileMenu_Open: "Abrir",
//	fileMenu_Close: "Close",
	fileMenu_Discard: "Rejeitar",
	fileMenu_Save: "Guardar",
//	fileMenu_SaveAs: "Save As...",
//	fileMenu_SaveAsDraft: "as Draft",
//	fileMenu_SaveInMyDocs: "in My Documents",
//	fileMenu_SaveToSymphony: "to Lotus Symphany",
	fileMenu_ShareWith: "Partilhar com...	",
	fileMenu_ExportAsPDF: "Exportar como PDF",
	fileMenu_WebPreview: "Pré-visualização da Web",
	fileMenu_PrintPreview: "Pré-visualizar impressão",
	fileMenu_RecentFile: "Ficheiros recentes",
	fileMenu_Print: "Imprimir...",
	editMenu: "Editar",
	editMenu_Undo: "Anular",
	editMenu_Redo: "Refazer",
	editMenu_Cut: "Cortar",
	editMenu_Copy: "Copiar",
	editMenu_Paste: "Colar",
	editMenu_DeleteSlide:"Eliminar diapositivo",
	editMenu_SelectAll: "Seleccionar tudo",
	editMenu_Find: "Localizar...",
	editMenu_Replace: "Substituir...",
	editMenu_DeleteSheet: "Eliminar folha",
	editMenu_DuplicateSheet: "Duplicar folha",
	editMenu_DeleteRow: "Eliminar linha",
	editMenu_DeleteColumn: "Eliminar coluna",
	editMenu_ClearCell: "Limpar célula",
	viewMenu: "Ver",
	viewMenu_Master: "Modelo global",
	viewMenu_Notifications: "Notificações",
	viewMenu_ShowHideIndicators: "Mostrar/Ocultar indicadores de co-edição",
	viewMenu_SlideSorter: "Mostrar ordenador de diapositivos",
	viewMenu_SpeakerNotes: "Mostrar notas do orador",
	viewMenu_NextSlide: "Diapositivo seguinte",
	viewMenu_PrevSlide: "Diapositivo anterior",
	createMenu: "Criar",
	createMenu_NewSlide: "Novo diapositivo",
	createMenu_DuplicateSlide: "Duplicar diapositivo",
	createMenu_ImageFromFile: "Gráfico a partir do ficheiro",
	createMenu_TextBox: "Caixa de texto",
	createMenu_Task: "Tarefa",
    formatMenu_Text_Direction: "Direcção do texto",
    formatMenu_Ltr: "Esquerda para a direita",
    formatMenu_Rtl: "Direita para a esquerda",  	
    formatMenu_Horizontal_Align: "Alinhamento horizontal",
    formatMenu_Vertical_Align: "Alinhamento vertical",
    formatMenu_Align_Top: "Superior",
    formatMenu_Align_Middle: "Centro",
    formatMenu_Align_Bottom: "Inferior",
	layoutMenu: "Esquema",
	layoutMenu_SlideLayout: "Esquema de diapositivo",
	layoutMenu_SlideDesign: "Estilos de modelo global",
	tableMenu: "Tabela",
	tableMenu_CreateTable: "Criar tabela",
	tableMenu_Cell: "Célula",
	tableMenu_CellAlignLeft: "Alinhar texto à esquerda",
	tableMenu_CellAlignCenter: "Alinhar texto ao centro",
	tableMenu_CellAlignRight: "Alinhar texto à direita",
	tableMenu_CellClearContents: "Limpar conteúdo",
	tableMenu_Row: "Linha",
	tableMenu_RowAddRowAbove: "Adicionar linha acima",
	tableMenu_RowAddRowBelow: "Adicionar linha abaixo",
	tableMenu_RowMoveRowAbove: "Mover linha acima",
	tableMenu_RowMoveRowBelow: "Mover linha abaixo",
	tableMenu_RowDelete: "Eliminar",
	tableMenu_ColumnAddColumnBefore: "Adicionar coluna antes",
	tableMenu_ColumnAddColumnAfter: "Adicionar coluna depois",
	tableMenu_ColumnMoveColumnAfter: "Mover coluna depois",
	tableMenu_ColumnMoveColumnBefore: "Mover coluna antes",
	tableMenu_ColumnDelete: "Eliminar",
	tableMenu_ColumnSortAscending: "Ordenar de forma ascendente",
	tableMenu_ColumnSortDescending: "Ordenar de forma descendente",
	tableMenu_Column: "Coluna",
	tableMenu_Delete: "Eliminar",
	presentationMenu: "Apresentação",
	presentationMenu_SlideShow: "Reproduzir apresentação de diapositivos",
	presentationMenu_SlideShowFromCurrent: "Reproduzir a partir do diapositivo actual",
	toolsMenu: "Ferramentas",
	toolsMenu_Task: "Tarefa",
	helpMenu: "Ajuda",
	helpMenu_Overview: "Conteúdo da ajuda"
})

