({
	service_unavailable_title: "الخدمة غير متاحة.",
	service_unavailable_content: "خدمة ${productName} غير متاحة والطلب الخاص بك لا يمكن معالجته فى هذا الوقت. حاول مجددا فى وقت لاحق أو اتصل بموجه النظام الخاص بك للتأكد من أن خدمة ${productName} متصلة.",
	access_denied_title: "تم رفض التوصل.",
	viewaccess_denied_content: "لا يتوافر لديك تصريح لمشاهدة هذا الملف. يمكن تعميم الملف أو يجب مشاركته معك.",
	editaccess_denied_content: "لا يتوافر لديك تصريح لتحرير هذا الملف. يمكن مشاركة الملف معك أو يجب أن يكون لديك امكانية التوصل المحرر الى الملف.",
	doc_notfound_title: "خدمة ${productName} لا يمكنها ايجاد الملف.",
	doc_notfound_content: "اتصل بموجه النظام الخاص بك للتأكد من أن خدمة ${productName} قد تم اعدادها بالشكل الصحيح.",
	fullviewer_notsupport_title: "لم يتم ايجاد الوثيقة",
	fullviewer_notsupport_content: "يقوم برنامج مشاهدة جديدة للملف بتخزين الوثيقة بعنوان url مختلف. لمشاهدة الوثيقة، قم بايجاد الملف في التطبيق الخاص بك واضغط مفتاح المعاينة.",
	fileconnect_denied_title: "تم رفض الاتصال.",
	fileconnect_denied_content: "لا يمكن الى ${productName} الاتصال بمستودع تخزين الملف. حاول مرة أخرى لاحقا أو اتصل بموجه النظام الخاص بك.",
	convservice_unavailable_title: "خدمة التحويل غير متاحة.",
	convservice_unavailable_content: "لا يمكن تشغيل الطلب الخاص بك فى هذا الوقت. حاول مرة أخرى لاحقا أو اتصل بموجه النظام الخاص بك للتأكد من أن اتصال خدمة التحويل.",
	doc_toolarge_title: "الملف كبير جدا.",
	doc_toolarge_content: "الوثيقة التى تريد التوصل لها كبيرة للغاية.",
	doc_toolarge_content2: "لا يمكن التوصل الى الملف، بسبب:",
	doc_toolarge_content3: "لا يمكن عرض الملف، لأن حجم الملف أكبر من ${0} كيلوبايت. يمكنك تنزيل الملف لمشاهدته. اذا كان الملف يحتوي على صور ذات درجة وضوح عالية، فانه يمكنك استبداله بواحد ذو درجة وضوح أقل لتقليل حجم الملف.",
	doc_toolarge_content4: "لا يمكن عرض الملف، لأن حجم الملف ${0} أكبر من ${1} كيلوبايت.",
	doc_toolarge_content5: "الملف كبير جدا بحيث يصعب مشاهدته هنا، ولكن مازال يمكنك فتحه بالضغط فوق مفتاح التحميل بخط العنوان.",
	edit_locked_file: "لا يمكنك تحرير هذا الملف لأنه تم اقفاله من قبل محررين آخرين.",
	sheet_toolarge_content: "حجم الجدول الحسابي أكبر من ${0} كيلوبايت.",
	sheet_toolarge_content2: "يحتوي الجدول الحسابي على أكثر من ${0} صف/صفوف بجدول واحد.",
	sheet_toolarge_content5: "يحتوي الجدول الحسابي على أكثر من ${0} عمود/أعمدة بجدول واحد.",
	sheet_toolarge_content3: "يحتوي الجدول الحسابي على أكثر من ${0} خانة/خانات.",
	sheet_toolarge_content4: "يحتوي الجدول الحسابي على أكثر من ${0} معادلة/معادلات.",
	text_toolarge_content: "حجم الوثيقة أكبر من ${0} كيلوبايت.",
	text_toolarge_content2:"تحتوي الوثيقة على أكثر من ${0} صفحة/صفحات.",
	text_toolarge_content3:"حجم النص بالوثيقة أكبر من ${0} كيلوبايت.",
	pres_toolarge_content: "حجم العرض التقديمي أكبر من ${0} كيلوبايت.",
	pres_toolarge_content2: "يحتوي العرض التقديمي على أكثر من ${0} صفحة/صفحات.",
	pres_toolarge_content3: "يحتوي العرض التقديمي على أكثر من ${0} رسم بياني/رسوم بيانية.",
	pdf_toolarge_content: "حجم pdf أكبر من ${0} كيلوبايت.",
	conversion_timeout_title: "انتهى وقت تحويل الوثيقة.",
	conversion_timeout_content: "فى هذا الوقت، تستغرق الوثيقة وقتا طويلا للتحويل. أعد المحاولة فيما بعد.",
	invalid_docformat_title: "محتويات الوثيقة غير صحيحة.",
	invalid_docformat_content: "لاحقة الملف للوثيقة لها نسق صحيح، ولكن لا يمكن التوصل الى محتويات الملف.  تأكد من أن الملف غير تالف. ",
	invalid_doctype_title: "لا يتم دعم نوع الوثيقة.",
	invalid_doctype_content: "لا يتم دعم نوع الوثيقة فى الوقت الحالى بواسطة ${productName}.",
	malformed_request_title: "عنوان URL أو المعاملات غير صحيحة.",
	malformed_request_content: "تأكد أن عنوان URL والمعاملات صحيحة.",
	storageserver_error_title: "وحدة خدمة التخزين غير متاحة.",
	storageserver_error_content: "وحدة الخدمة غير متاحة حاليا. لا يمكن تشغيل الطلب الخاص بك فى هذا الوقت. حاول مرة أخرى لاحقا أو اتصل بموجه النظام الخاص بك للتأكد من أن اتصال خدمة التخزين.",
	incorrect_web_address_title:"عنوان الانترنت غير صحيح.",
	incorrect_web_address_content:"عنوان الانترنت غير صحيح.  أدخل عنوان الانترنت وأعد المحاولة.",
	unexpecified_conversion_error_title:"الخطأ غير محدد.",
	unexpecified_conversion_error_content:"أرجعت وحدة الخدمة خطأ غير محدد.",
	encrypted_conversion_error_title:"لا يتم دعم وثائق CryptoAPI RC4 المشفرة. ",
	encrypted_conversion_error_content:"الملف تحت حماية كلمة سرية. لمشاهدة الملف فى ${productName}، تأكد أولا أن الملف مشفر.",
	document_encrypt_title:"تم تشفير الوثيقة.",
	document_encrypt_content:"لا يمكنك مشاهدة الملف على الانترنت حيث أنه قد تم تشفيره عند تحميله الى الملفات.",
	service_busy_title:"فشل فتح الوثيقة",
	service_busy_content:"تعذر فتح الملف الذى تريد مشاهدته. ربما تكون وحدة الخدمة مشغولة أو غير متاحة. حاول مرة أخرى لاحقا أو اتصل بموجه النظام الخاص بك.",
	empty_doc_title: "الوثيقة خالية.",
	empty_doc_content: "تأكد أن الوثيقة تحتوى على المحتويات ثم أعد المحاولة.",
	corrupted_doc_title: "لا يمكن فتح الملفات.",
	corrupted_doc_content: "الملف يحتوى على محتويات لا يتم دعمها، على سبيل المثال الأوامر المركبة، وبالتالى لا يمكن مشاهدتها فى هذا التطبيق.",
	draft_storage_error_title: "لا يمكن فتح الوثيقة. ",
	draft_storage_error_content: "لا يمكن تحميل المحتوى بسبب تلفه. اتصل بمسؤول النظام للحصول على الدعم. ",
	unexpected_code_title: "لا يمكن مشاهدة الوثيقة.",
	unexpected_code_content: "وحدة خدمة ${docsProductName} قد تكون متوقفة. أعد المحاولة فيما بعد.",
	unpublished_document_title: "لا يمكن مشاهدة الملف",
	unpublished_document_content: "لا توجد نسخة منشورة من هذا الملف متاحة للمشاهدة.  يجب على مالك الملف نشر نسخة من الملف قبل أن يمكن مشاهدته.",
	unscanned_document_title: "اتمام فحص الفيروسات",
	unscanned_document_content: "يتم اجراء مسح ضوئي آليا للملفات التي تم تحميلها الى Connections. يمكنك مشاهدة هذا الملف بمجرد اتمام عملية المسح الضوئي.",
	malicious_document_title: "ملف ضار",
	malicious_document_content: "لا يمكنك مشاهدة هذا الملف لأن Connections اكتشف فيروس أثناء اجراء مسح ضوئي له.",		
	repository_out_of_space_title: "لا توجد مساحة كافية",
	repository_out_of_space_content: "لا يمكن نشر ${0} لأنك قد وصلت الى الحصة النسبية الخاصة بك لحجم الملف. قم بتخفيض الحصة النسبية الخاصة بك بنقل ملفات أخرى الى المحذوفات ثم حذفها.",
	pdf_error_title:"لا يمكن فتح الملفات.",
	pdf_error_content:"ملف PDF قد يكون تالف.",
	problem_id_msg_title: "ابلغ هذه المشكلة الى موجه النظام الخاص بك. ",
	problem_id_msg_show: "اضغط لعرض التفاصيل",
	problem_id_msg_hide: "اضغط للاخفاء"
})

