define({      
//begin v1.x content
	"clearFilterDialogTitle": "Filter wissen",
	"filterDefDialogTitle": "Filter",
	"defaultRuleTitle": "Regel",
	"ruleTitleTemplate": "Regel ${ruleNumber}",
	"noFilterApplied": "Geen filter gebruikt.",
	"defineFilter": "Filter definiëren",
	"conditionEqual": "gelijk",
	"conditionNotEqual": "niet gelijk",
	"conditionLess": "is kleiner dan",
	"conditionLessEqual": "kleiner dan of gelijk aan",
	"conditionGreater": "is groter dan",
	"conditionGreaterEqual": "groter dan of gelijk aan",
	"conditionContain": "bevat",
	"conditionIs": "is",
	"conditionStartWith": "start met",
	"conditionEndWith": "eindigt met",
	"conditionNotContain": "bevat niet",
	"conditionIsNot": "is niet",
	"conditionNotStartWith": "start niet met",
	"conditionNotEndWith": "eindigt niet met",
	"conditionBefore": "voor",
	"conditionAfter": "achter",
	"conditionRange": "bereik",
	"conditionIsEmpty": "is leeg",
	"all": "alle",
	"any": "een",
	"relationAll": "alle regels",
	"waiRelAll": "Alle volgende regels toepassen:",
	"relationAny": "een regel",
	"waiRelAny": "Een van de volgende regels toepassen:",
	"relationMsgFront": "Toepassen",
	"relationMsgTail": "",
	"and": "en",
	"or": "of",
	"addRuleButton": "Regel toevoegen",
	"waiAddRuleButton": "Nieuwe regel toevoegen",
	"removeRuleButton": "Regel verwijderen",
	"waiRemoveRuleButtonTemplate": "Regel ${0} verwijderen",
	"addRuleButton": "Filterregel toevoegen",
	"cancelButton": "Annuleren",
	"waiCancelButton": "Dit venster annuleren",
	"clearButton": "Wissen",
	"waiClearButton": "Het filter wissen",
	"filterButton": "Filter",
	"waiFilterButton": "Filter aanbieden",
	"columnSelectLabel": "Kolom:",
	"waiColumnSelectTemplate": "Kolom voor regel ${0}",
	"conditionSelectLabel": "Voorwaarde:",
	"waiConditionSelectTemplate": "Voorwaarde voor regel ${0}",
	"valueBoxLabel": "Waarde:",
	"waiValueBoxTemplate": "Waarde voor filter voor regel ${0} opgeven",
	"rangeTo": "tot",
	"rangeTemplate": "van ${0} tot ${1}",
	"statusTipHeaderColumn": "Kolom",
	"statusTipHeaderCondition": "Regels",
	"statusTipTitle": "Filterbalk",
	"statusTipMsg": "Klik op de filterbalk om waarden in ${0} te filteren.",
	"anycolumn": "een kolom",
	"statusTipTitleNoFilter": "Filterbalk",
	"statusTipTitleHasFilter": "Filter",
	"statusTipRelPre": "Toepassen",
	"statusTipRelPost": "regels",
	"statusTipHeaderAll": "Alle regels toepassen",
	"statusTipHeaderAny": "Een of meer regels toepassen",
	"defaultItemsName": "items",
	"filterBarMsgHasFilterTemplate": "${0} van ${1} ${2} afgebeeld.",
	"filterBarMsgNoFilterTemplate": "Geen filter toegepast",
	"filterBarDefButton": "Filter definiëren",
	"waiFilterBarDefButton": "Tabel filteren",
	"a11yFilterBarDefButton": "Filteren...",
	"filterBarClearButton": "Filter wissen",
	"waiFilterBarClearButton": "Het filter wissen",
	"closeFilterBarBtn": "Filterbalk sluiten",
	"clearFilterMsg": "Hiermee verwijdert u het filter en beeldt u alle beschikbare records af.",
	"anyColumnOption": "Een kolom",
	"trueLabel": "Waar",
	"falseLabel": "Onwaar",
	"radioTrueLabel": "Waarde waar",
	"radioFalseLabel": "Waarde onwaar",
	"beginTimeRangeLabel": "Startwaarde tijdbereik",
	"endTimeRangeLabel": "Eindwaarde tijdbereik",
	"beginDateRangeLabel": "Startwaarde datumbereik",
	"endDateRangeLabel": "Eindwaarde datumbereik",
	"startsWithExpr": "${0}*"
//end v1.x content
});

