({
	delete_general: "Избриши",
	order: "Редослед",
	align_text: "Порамни текст",
	align_slide: "Порамни во слајд",
	align_objects: "Порамни избрани предмети",
	zoom: "Зумирај",
	zoom_fit: "Прилагоди во прозорец",
	insert_link: "Вметни врска",
	add_link: "Додај врска",
	open_link: "Отвори врска",
	edit_link: "Уреди врска",
	remove_link: "Отстрани врска",
	insert_link_menu: "Врска",
	invalid_url: "URL-врската не може да се отвори. Проверете дали URL-врската е точна или проверете ја поставката за блокирање појавувачки прозорци на прегледувачот.",
	dnd_canceled_on_slide_event: "Слајдот не може да се премести бидејќи друг уредник неодамна ја изменил презентацијата. Обидете се повторно подоцна.",
	rotate: "Ротирај",
	flipX: "Преврти хоризонтално",
	flipY: "Преврти вертикално",
	rotate_right: "Ротирај за 90&#x00B0 во насока на часовникот",
	rotate_left: "Ротирај за 90&#x00B0 во насока обратна од часовникот",
	color_set_fill: "Постави боја на полнеж",
	color_nofill: "Нема полнеж",
	color_nobackground: "Нема заднина",
	color_auto: "Автоматски",
	color_default: "Стандардно",
	color_transparent: "Проѕирно",
	
	objects_distribute: "Дистрибуирај",
	objects_distribute_v: "Вертикално",
	objects_distribute_h: "Хоризонтално",
	
	link_subject: "Предмет :",
	link_text: "Текст за прикажување :",
	link_mailto: "Отвори е-пошта",
	link_goto: "Отвори врска",
	link_done: "Готово",
	link_remove: "Отстрани",
	link_website: "Веб-локација",
	link_email: "Е-пошта",
	link_slide: "Слајд",
	link_slide_placeholder: "Изберете или внесете број",
	link_slide_placeholder_deleted: "Поврзаниот слајд се избриша",
	link_slide_next: "Нареден слајд",
	link_slide_prev: "Претходен слајд",
	link_slide_first: "Прв слајд",
	link_slide_last: "Последен слајд",
	link_slide_number: "Слајд ${0}",
	link_not_support: "Неподржан тип на врска",
	link_acc_input: "Влезна адреса на врска",
	link_acc_mail_input: "Влезна адреса на е-пошта",
	

	// Jaws Support
	acc_blank: "празно",// when selection is nothing but space char and empty paragraph
	acc_selected: " избрано",
	acc_showed: " покажано",
	acc_inTable: " во табела ред ${0} колона ${1} ",
	acc_titleSelected: "избран наслов",
	acc_subtitleSelected: "избран поднаслов",
	acc_outlineSelected: "избрана контура",
	acc_notesSelected: "избрани белешки на говорник",
	acc_imageSelected: "избрана графика",
	acc_shapeSelected: "избран облик",
	acc_rotated: " ротирано ${0} степени",
	acc_tableSelected: "избрана табела",
	acc_textboxSelected: "избрано текстуално поле",
	acc_enterEdit: " притиснете Enter за да уредите",
	acc_locked_by: " што го заклучил корисникот ${0}",
	acc_slide_used_by: " што го користи корисникот ${0}",
	ACC_TABLE_TABLESIZE: "Избравте ${0} редови, ${1} колони",
	ACC_TABLE_MAXSIZE: " Максималната поддржана големина на табела е 8*8",
	ACC_EditorMode: "режим на уредување уредник",
	ACC_EndEditorMode: "крај на режим на уредување уредник",
	ACC_Table_new_row: "Се додаде нов ред",
	ACC_Table_new_column: "Се додаде нова колона",
	Acc_column: "колона ${0}",
	acc_slide: "слајд ${0}",
	acc_editor: "Уредил ${0}",
	Plain: "Обичен текст",
	BlueStyle: "Син стил",
	RedTint: "Црвен тон на боја",
	BlueHeader: "Црно заглавие",
	DarkGrayHF: "Темно сино заглавие/подножје",
	LightGrayRows: "Светло сиви редови",
	DarkGrayRows: "Темно сиви редови",
	BlueTint: "Син тон на боја",
	RedHeader: "Црвено заглавие",
	GreenHF: "Зелено заглавие/подножје",
	PlainRows: "Обични редови",
	GrayTint: "Сив тон на боја",
	GreenTint: "Зелен тон на боја",
	GreenHeader: "Зелено заглавие",
	RedHF: "Црвено заглавие/подножје",
	GreenStyle: "Зелен стил",
	PurpleTint: "Пурпурен тон на боја",
	BlackHeader: "Црно заглавие",
	PurpleHeader: "Пурпурно заглавие",
	LightBlueHF: "Светло сино заглавие/подножје",
	
    formatMenu_LineSpacing: "Проред на ред",
	linespaceboxTitle:"Прилагоди проред",
	linespacelineTitle:"Ред:",
	linespacenoticeContent :"Проред на ред",
    formatMenu_LineSpacing_Customize: "Прилагоди...",
    formatMenu_LineSpacing_CustomValue:"Прилагоди: ${0}",
    lineSpaceWarning:"Внесете број од 0 до 10",
    
    set_transparency_menu: "Непроѕирност на слика",
    opacity_percent_value: "${0}%",
    opacity_title: "Непроѕирност",
    
    increaseLineWidthTip: "Зголеми дебелина на линија",
	decreaseLineWidthTip : "Намали дебелина на линија",
    setBorderStyleTip:"Постави стил на линија",
    line_width_title: "Дебелина на линија",
    line_end_title: "Крајни точки на линија",
    line_dash_title: "Шема на редови",
    line_dash_type1: "Непроѕирно",
    line_dash_type2: "Квадратни точки",
    line_dash_type3: "Црти",
    line_dash_type4: "Кружни точки",
    line_dash_type5: "Црти и точки",
    line_dash_type6: "Долги црти",
    line_endpoints_type1: "Нема",
    line_endpoints_type2: "Едноставна стрелка надесно",
	line_endpoints_type3: "Едноставна стрелка налево",
	line_endpoints_type4: "Едноставна двојна стрелка",
	line_endpoints_type5: "Исполнета стрелка надесно",
	line_endpoints_type6: "Исполнета стрелка налево",
    line_endpoints_type7: "Исполнета двојна стрелка",
    line_endpoints_type8: "Исполнети круг и стрелка",
	line_endpoints_type9: "Исполнети ромб и стрелка",
	line_endpoints_type10: "Исполнети ромбови",
    line_endpoints_type11: "Исполнети кругови"
})

