({
	alt			: "alt 텍스트:",
	width		: "너비:",
	height		: "높이:",
	cmUnit   : "cm",
	ptUnit 	 : "pt",
	inchUnit : "인치",
	inUnit   : "in",
	mmUnit 	 : "mm",
	
	inputWarning: "기본 단위의 양수를 입력하십시오. ",
	
	properties: "특성",
	data: "데이터",
	chart: "차트",
	axis: "축",
	series: "시리즈",
	font: "글꼴",
	title: "제목",
	legend: "범례",
	placement: "배치",
	background: "배경",
	plotarea: "도표 영역",
	line : "선형",
	fill: "채우기",
	border : "테두리",
	labelfont: "레이블",
	scale: "배율",
	minimum: "최소",
	maximum: "최대",
	majorunit: "주 단위",
	minorunit: "부 단위",
	smooth: "곡선",
	marker: "마커",
	markerfill: "마커",
	enterTitle: "여기에 제목 입력",
	inputNumberWarning: "숫자를 입력하십시오.",
	inputPosNumberWarning: "양수를 입력하십시오.",
	maxMinWarning: "최대값은 최소값보다 커야 합니다.",
	selectFontName: "글꼴 이름 선택",
	selectFontSize: "글꼴 크기 선택",
	setBold: "굵은체",
	setItalic: "기울임꼴",
	setFontColor: "글꼴 색상 설정",
	setLegendPos: "범례 배치 설정",
	setBackColor: "차트 배경색 설정",
	setBorderWidth: "테두리 너비 설정",
	setBorderColor: "테두리 색상 설정",
	setPlotAreaColor: "도표 영역 색상 설정",
	selectAxis: "축 선택",
	setLineWidth: "선 너비 설정",
	setLineColor: "선 색상 설정",
	selectSeries: "시리즈 선택",
	setFillColor: "채우기 색상 설정",
	setMarker: "마커 설정",
	setSmooth: "곡선 설정",
	chartTitle: "차트 제목",
	axisTitle: "축 제목",
	
	ERR1: "배열은 중괄호로 묶어야 합니다.",
	ERR3: "문자열 항목은 큰따옴표로 묶어야 합니다.",
	ERR4: "한 범위만 입력해야 합니다.",
	ERR5: "범위가 있어야 합니다.",
	ERR6: "모든 범위는 동일한 용지에 있어야 합니다.",
	ERR7: "모든 범위는 단일 행 또는 열이어야 합니다.",
	ERR9: "시리즈 값이 필요합니다.",
	
	n	: "없음",
	l	: "왼쪽",
	r	: "오른쪽",
	t	: "맨 위",
	b   : "아래",
	
	dataSeries:"데이터 시리즈",
	label:"시리즈 이름",
	xVal:"시리즈 X 값",
	yVal:"시리즈 Y 값",
	val:"시리즈 값",
	cat:"카테고리",
		
	ltr: "왼쪽에서 오른쪽",
	rtl: "오른쪽에서 왼쪽",
	auto: "컨텍스트",
	bidi_dir: "방향",
	bidi_text_dir: "텍스트 방향"
})
