({
	service_unavailable_title: "Zerbitzua ez dago eskuragarri.",
	service_unavailable_content: "${productName} zerbitzua ez dago eskuragarri eta zure eskaera ezin da orain prozesatu. Saiatu berriro beranduago edo galdetu zure sistemaren administratzaileari ${productName} zerbitzua linean dagoela ziurtatzeko.",
	access_denied_title: "Atzipena ukatu da.",
	viewaccess_denied_content: "Ez daukazu fitxategi hau ikusteko baimenik. Fitxategia publikoa izan behar da edo zurekin partekatua.",
	editaccess_denied_content: "Ez daukazu fitxategi hau editatzeko baimenik. Fitxategia zurekin partekatua izan behar da edo editore bezala atzitzeko baimena izan behar duzu.",
	doc_notfound_title: "${productName} zerbitzuak ezin du fitxategia aurkitu.",
	doc_notfound_content: "Jarri kontaktuan zure administratzailearekin ${productName} zerbitzua ondo konfiguratuta dagoela ziurtatzeko.",
	fullviewer_notsupport_title: "Dokumentua ez da aurkitu.",
	fullviewer_notsupport_content: "Dokumentuaren ikustaile berri batek dokumentua url ezberdin batean gordetzen du. Dokumentua ikusteko, aurkitu fitxategia zure aplikazioan eta egin klik Aurrebista botoian.",
	fileconnect_denied_title: "Konexioa ukatu da.",
	fileconnect_denied_content: "${productName} ezin da fitxategiaren biltegiarekin konektatu. Saiatu berriro beranduago edo jarri kontaktuan zure administratzailearekin.",
	convservice_unavailable_title: "Bihurketa zerbitzua ez dago eskuragarri.",
	convservice_unavailable_content: "Momentu honetan ezin da zure eskaera prozesatu. Saiatu berriro beranduago edo galdetu zure sistemaren administratzaileari bihurketa zerbitzua linean dagoela ziurtatzeko.",
	doc_toolarge_title: "Fitxategia handiegia da.",
	doc_toolarge_content: "Atzitu nahi duzun dokumentua handiegia da.",
	doc_toolarge_content2: "Ezin da fitxategia atzitu. Arrazoia:",
	doc_toolarge_content3: "Fitxategia ezin da bistaratu bere tamaina ${0} KB baino handiagoa delako. Fitxategia deskargatu ahal duzu ikusteko. Fitxategiak bereizmen handiko irudi batzuk baditu, irudiak ordezkatu ahal dituzu bereizmen txikiko beste irudi batzuekin fitxategiaren tamaina gutxitzeko.",
	doc_toolarge_content4: "Fitxategia ezin da bistaratu; ${0} fitxategiaren tamaina ${1} KB baino handiagoa da.",
	doc_toolarge_content5: "Fitxategia handiegia da hemen bistaratzeko. Irekitzeko, izenburuaren barrako deskarga-botoian klik egin dezakezu.",
	edit_locked_file: "Ezin duzu fitxategi hau editatu beste editoreek blokeatu dutelako.",
	sheet_toolarge_content: "Kalkulu-orriaren tamaina ${0} KB baino handiagoa da.",
	sheet_toolarge_content2: "Kalkulu-orriak ${0} errenkada baino gehiago ditu orri batean.",
	sheet_toolarge_content5: "Kalkulu-orriak ${0} zutabe baino gehiago ditu orri batean.",
	sheet_toolarge_content3: "Kalkulu-orriak ${0} gelaxka baino gehiago ditu.",
	sheet_toolarge_content4: "Kalkulu-orriak ${0} formula baino gehiago ditu.",
	text_toolarge_content: "Dokumentuaren tamaina ${0} KB baino handiagoa da.",
	text_toolarge_content2:"Dokumentuak ${0} orrialde baino gehiago ditu.",
	text_toolarge_content3:"Dokumentuaren testuaren tamaina ${0} KB baino handiagoa da.",
	pres_toolarge_content: "Aurkezpenaren tamaina ${0} KB baino handiagoa da.",
	pres_toolarge_content2: "Aurkezpenak ${0} orrialde baino gehiago ditu.",
	pres_toolarge_content3: "Aurkezpenak ${0} grafiko baino gehiago ditu.",
	pdf_toolarge_content: "Pdf fitxategiak ${0} KB baino gehiago ditu.",
	conversion_timeout_title: "Dokumentuaren bihurketa iraungi da.",
	conversion_timeout_content: "Momentu honetan, dokumentua bihurtzeko denbora gehiegi behar da. Saiatu berriro beranduago.",
	invalid_docformat_title: "Dokumentuaren edukia ez da baliozkoa.",
	invalid_docformat_content: "Dokumentuaren luzapenak baliozko formatua dauka, baina fitxategiaren edukia ezin da atzitu.  Ziurtatu fitxategia hondatuta ez dagoela. ",
	invalid_doctype_title: "Dokumentu-mota ez da onartzen.",
	invalid_doctype_content: "Momentu honetan ${productName}(e)k ez du dokumentu mota hau onartzen.",
	malformed_request_title: "URLa edo parametroak okerrak dira.",
	malformed_request_content: "Ziurtatu URLa eta parametroak zuzenak direla.",
	storageserver_error_title: "Biltegiratze-zerbitzaria ez dago eskuragarri.",
	storageserver_error_content: "Momentu honetan zerbitzaria ez dago eskuragarri. Momentu honetan ezin da zure eskaera prozesatu. Saiatu berriro beranduago edo galdetu zure sistemaren administratzaileari biltegiratze-zerbitzua linean dagoela ziurtatzeko.",
	incorrect_web_address_title:"Web-helbide okerra.",
	incorrect_web_address_content:"Web-helbidea ez da zuzena.  Sartu web-helbidea eta saiatu berriro.",
	unexpecified_conversion_error_title:"Errorea ez da zehaztu.",
	unexpecified_conversion_error_content:"Zerbitzariak errore zehaztugabe batekin erantzun du.",
	encrypted_conversion_error_title:"CryptoAPI RC4 dokumentu enkriptatuak ez dira onartzen.",
	encrypted_conversion_error_content:"Fitxategia pasahitz baten bidez babestuta dago. ${productName}(e)n fitxategia ikusteko, ziurtatu fitxategia desenkriptatuta dagoela.",
	document_encrypt_title:"Dokumentua enkriptatuta dago.",
	document_encrypt_content:"Ezin duzu fitxategia linean ikusi Fitxategietara kargatu zenean enkriptatuta zegoelako.",
	service_busy_title:"Dokumentua ezin izan da ireki",
	service_busy_content:"Ikusi nahi duzun fitxategia ezin izan da ireki. Baliteke zerbitzaria lanpetuta egotea edo ezin eskuratzea. Saiatu berriro beranduago edo jarri kontaktuan zure administratzailearekin.",
	empty_doc_title: "Dokumentua hutsik dago.",
	empty_doc_content: "Ziurtatu dokumentuak edukia daukala eta saiatu berriro.",
	corrupted_doc_title: "Ezin da fitxategia ireki.",
	corrupted_doc_content: "Dokumentuak onartu gabeko edukia dauka (adibidez, makroak) eta horregatik ezin da aplikazio honetan ikusi.",
	draft_storage_error_title: "Ezin da dokumentua ireki.",
	draft_storage_error_content: "Edukia hondatuta dago eta ezin da kargatu. Laguntza behar baduzu, jarri harremanetan zure  administratzailearekin.",
	unexpected_code_title: "Ezin da dokumentua ikusi.",
	unexpected_code_content: "Baliteke ${docsProductName} zerbitzaria ez ibiltzea. Saiatu berriro beranduago.",
	unpublished_document_title: "Ezin da fitxategia ikusi",
	unpublished_document_content: "Ez dago fitxategi honen bertsio argitaraturik eskuragarri.  Fitxategiaren jabeak fitxategiaren bertsio bat argitaratu behar du besteek ikusi ahal izateko.",
	unscanned_document_title: "Birusak bilatzeko azterketa burutu da",
	unscanned_document_content: "Connections-en kargatutako fitxategiak automatikoki aztertzen dira. Azterketa burutu bezain laster ikusiko duzu fitxategia.",
	malicious_document_title: "Fitxategi gaiztoa",
	malicious_document_content: "Ezin duzu fitxategi hau ikusi Connections-ek bertan birus bat aurkitu duelako.",		
	repository_out_of_space_title: "Ez dago nahikoa leku",
	repository_out_of_space_content: "Ezin da ${0} argitaratu fitxategien tamainaren kuota gainditu duzulako. Murriztu erabilitako lekua beste fitxategiak zaborrontzira mugituz eta ezabatuz.",
	pdf_error_title:"Ezin da fitxategia ireki.",
	pdf_error_content:"Baliteke PDF fitxategia hondatuta egotea.",
	problem_id_msg_title: "Jakinarazi arazoa administratzaileari. ",
	problem_id_msg_show: "Sakatu xehetasunak ikusteko",
	problem_id_msg_hide: "Sakatu ezkutatzeko"
})

