/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2014. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
	service_unavailable_title: "Service is niet beschikbaar.",
	service_unavailable_content: "De service ${productName} is niet beschikbaar. Uw opdracht kan op dit moment niet worden verwerkt. Probeer het later opnieuw of neem contact op met de systeembeheerder.",
	access_denied_title: "Toegang geweigerd",
	viewaccess_denied_content: "U bent niet gemachtigd om dit bestand te bekijken. Het bestand moet openbaar worden gemaakt of met u worden gedeeld.",
	editaccess_denied_content: "U bent niet gemachtigd voor ${productName} of u kunt dit bestand niet bewerken. Het bestand moet met u zijn gedeeld en uw toegangsniveau moet dat van Editor zijn. Het kan ook zijn dat het bestand door een andere editor is vergrendeld.",
	doc_notfound_title: "Het document is niet gevonden.",
	doc_notfound_content: "Het document dat u zoekt is gewist of verplaatst. Controleer of de link correct is.",
	repository_out_of_space_title: "Onvoldoende ruimte",
	repository_out_of_space_content: "${0} kan niet worden gepubliceerd, want uw bestandsquota zijn bereikt. Maak ruimte door andere bestanden naar de prullenbak te verplaatsen en deze te verwijderden.",
	fileconnect_denied_title: "De verbinding wordt geweigerd.",
	fileconnect_denied_content: "${productName} kan geen verbinding maken met de bestandsrepository. Probeer het later opnieuw of neem contact op met de systeembeheerder.",
	unscanned_document_title: "Virusscan wordt voltooid",
	unscanned_document_content: "Er wordt automatisch een virusscan uitgevoerd op bestanden die worden geüpload naar Connections. Wanneer de virusscan is voltooid, kunt u dit bestand bewerken.",
	malicious_document_title: "Kwaadaardig bestand",
	malicious_document_content: "U kunt dit bestand niet bewerken, omdat Connections bij het scannen een virus heeft gevonden.",	
	convservice_unavailable_title: "Conversieservice is niet beschikbaar.",
	convservice_unavailable_content: "Conversieservice voor ${productName} is niet beschikbaar. Uw opdracht kan op dit moment niet worden verwerkt. Probeer het later opnieuw of neem contact op met de systeembeheerder.",
	doc_toolarge_title: "Het bestand is te groot.",
	doc_toolarge_content: "Het document dat u zoekt is te groot.",
	doc_toolarge_content2: "Het bestand kan niet worden geopend. Mogelijke redenen zijn:",
	doc_toolarge_content3: "Het bestand kan niet worden weergegeven, want het is groter dan ${0} kB. U kunt het bestand wel downloaden en bewerken. Als het bestand afbeeldingen met hoge resolutie bevat, kunt u deze vervangen door het bestand afbeeldingen met lage resolutie om het bestand kleiner te maken.",
	doc_toolarge_content4: "Het bestand is te groot om hier te bekijken, maar u kunt het nog wel openen door op de knop voor downloaden op de titelbalk te klikken.",
	doc_toolarge_content_mobile: "Het bestand kan niet worden geopend. Het bestand kan op een mobiel apparaat niet groter zijn dan ${0} kB.",
	sheet_toolarge_content: "De spreadsheet is groter dan ${0} kB.",
	sheet_toolarge_content2: "De spreadsheet bevat meer dan ${0} rijen op één werkblad.",
	sheet_toolarge_content5: "De spreadsheet bevat meer dan ${0} kolommen op één werkblad.",
	sheet_toolarge_content3: "De spreadsheet bevat meer dan ${0} cellen.",
	sheet_toolarge_content4: "De spreadsheet bevat meer dan ${0} formules.",
	text_toolarge_content: "Het document is groter dan ${0} kB.",
	text_toolarge_content2:"Het document bevat meer dan ${0} pagina's.",
	text_toolarge_content3:"De tekstgrootte van het document is groter dan ${0} kB.",
	pres_toolarge_content: "De presentatie kan niet worden geopend, want het bestand is groter dan ${0} kB. Als de presentatie afbeeldingen met hoge resolutie bevat, kunt u deze vervangen door afbeeldingen met een lagere resolutie om het bestand kleiner te maken.",
	pres_toolarge_content2: "De presentatie kan niet worden geopend, want deze bevat meer dan ${0} pagina's.",
	pres_toolarge_content3: "De presentatie kan niet worden geopend, want deze bevat meer dan ${0} objecten.",
	pres_toolarge_content2_mobile: "De presentatie bestaat uit meer dan ${0} pagina's en kan op een mobiel apparaat niet worden geopend.",
	pres_toolarge_content3_mobile: "De presentatie bevat meer dan ${0} objecten en kan op een mobiel apparaat niet worden geopend.",
	sheet_view_toolarge_content1_mobile: "De spreadsheet bevat meer dan ${0} rijen en kan op een mobiel apparaat niet worden bekeken.",
	sheet_view_toolarge_content2_mobile: "De spreadsheet bevat meer dan ${0} kolommen en kan op een mobiel apparaat niet worden bekeken.",
	sheet_view_toolarge_content3_mobile: "De spreadsheet bevat meer dan ${0} rijen en ${1} kolommen en kan op een mobiel apparaat niet worden bekeken.",
	conversion_timeout_title: "Er is een timeout op getreden voor de documentconversie.",
	conversion_timeout_content: "Op dit moment duurt het te lang om het document te converteren. Probeer het later opnieuw.",
	invalid_docformat_title: "Het document kan niet worden geopend.",
	invalid_docformat_content: "De extensie van het document is geldig, maar de inhoud kan niet worden gelezen, want het bestand is beschadigd of versleuteld.",
	template_extension_conent_mismatch: "De extensie van het bronbestand geeft ten onrechte aan dat het een sjabloon is. Het bestand heeft in werkelijkheid een .${0}-indeling. Start met een geldig sjabloon of sla dit bestand op met een andere naam met .${0} als extensie.",
	invalid_docformat_title2: "Het bestand kan niet worden geïmporteerd in ${productName}.",
	invalid_docformat_content2: "Het bestand bevat iets wat ${productName} op dit moment nog niet ondersteunt. Dit bestand kan niet worden geïmporteerd.",
	invalid_doctype_title: "Het documenttype wordt niet ondersteund.",
	invalid_doctype_content: "Het documenttype wordt momenteel niet ondersteund door ${productName}.",
	unsupported_browser_title: "Niet alle functies worden door uw browser ondersteund",
	malformed_request_title: "De notatie van de opdracht is onjuist.",
	malformed_request_content: "Controleer de waarden van de URL en de parameters.",
	storageserver_error_title: "De opslagserver is niet beschikbaar.",
	storageserver_error_content: "De server is nu niet beschikbaar. Uw opdracht kan op dit moment niet worden verwerkt. Probeer het later opnieuw of neem contact op met de systeembeheerder.",
	document_already_opened_title: "Document is al geopend",
	document_already_opened_content:"Dit document is al geopend in uw browser.",
	toomany_documents_opened_inone_browser_title: "Het document kan niet worden geopend.",
	toomany_documents_opened_inone_browser_content:"Er kunnen niet meer dan vijf ${productName}-bestanden tegelijk worden geopend. Sluit andere documenten en probeer dit document opnieuw te openen.",
	document_max_session_exceeded_title:"Service is niet beschikbaar.",
	document_max_session_exceeded_content:"Er zijn te veel gebruikers op de server bezig met het bewerken van documenten. Uw verzoek kan niet worden verwerkt. Probeer het later opnieuw.",
	kickout_user_content: "Dit document is al geopend in een ander venster op uw computer. Ga naar dat andere venster als u het document verder wilt bewerken.",
	return_to_files: "Terug naar Bestanden",
	return_to_library: "Terug naar Bibliotheek",
	return_to_icn: "Terug naar Content Navigator",
	document_already_open: "Document is al open",
	cannotedit_noentitled_title: "Gelijktijdige bewerking van dit bestand is niet mogelijk",
	cannotedit_noentitled_content1: "De volgende gebruikers bewerken op dit moment het bestand:",
	cannotedit_noentitled_content2: "U bent niet gemachtigd om dit bestand te bewerken terwijl andere gebruikers dat ook doen. Probeer het op een ander moment opnieuw.",
	cannotedit_noentitled_content3: "De volgende gebruiker bewerkt op dit moment het bestand:",
	cannotedit_noentitled_content4: "U kunt niet deelnemen aan deze bewerkingssessie, want de gebruiker die het bestand geopend heeft, is niet gemachtigd voor gelijktijdige bewerking. Probeer het op een ander moment opnieuw.",
	toomany_coeditors_title: "Te veel gebruikers",
	toomany_coeditors_content: "Er zijn op dit moment te veel gebruikers bezig met het bewerken van dit document. Er kunnen slechts {0} gebruikers tegelijk aan dit document werken.",
	encrypted_pptdoc_title:"Versleuteld bestand",
	encrypted_pptdoc_content:"Dit bestand is beveiligd met een wachtwoord. Het moet eerst worden gedecodeerd voordat het kan worden gewijzigd in ${productName}.",
	server_busy_title:"De server is bezig",
	server_busy_content:"Wacht even en probeer het dan opnieuw.",
	document_encrypt_title:"Het versleutelde document kan niet worden verwerkt.",
	document_encrypt_content:"Dit bestand in de bestandsrepository is versleuteld. Om veiligheidsredenen kan ${productName} het niet rechtstreeks bewerken.",
	edit_locked_file: "Het bestand kan niet worden bewerkt, want het is vergrendeld door andere editors.",
	publish_locked_file: "U kunt dit bestand niet publiceren als nieuwe versie, want het is vergrendeld. De inhoud wordt echter automatisch opgeslagen in de conceptversie.",
	join_locked_file_session: "U kunt dit bestand niet gelijktijdig met andere gebruikers bewerken, want het is een of meer van hen vergrendeld.",
	no_need_to_convert_title:"Conversie is niet nodig",
	no_need_to_convert_content:"Het bestand heeft al de gewenste indeling. U kunt het direct downloaden.",
	warning_icon: "Waarschuwing",
	//html viewer error message
	incorrect_web_address_title:"Onjuist webadres.",
	incorrect_web_address_content:"Het webadres is onjuist.  Geef het goede adres op en probeer het opnieuw.",
	unexpecified_conversion_error_title:"De fout is onbekend.",
	unexpecified_conversion_error_content:"De server heeft een onbekende fout geretourneerd.",
	encrypted_conversion_error_title:"Het versleutelde document kan niet worden verwerkt.",
	encrypted_conversion_error_content:"Het bestand is met een wachtwoord beveiligd. Als u het bestand in de viewer wilt bekijken, moet u het eerst worden gedecodeerd.",
	service_busy_title:"Het document kan niet worden geopend.",
	service_busy_content:"Het bestand dat u wilt bekijken, kan niet worden geopend. Mogelijk is de server bezig of niet beschikbaar. Probeer het later opnieuw of neem contact op met de beheerder.",
	empty_doc_title: "Het document is leeg.",
	empty_doc_content: "Zorg dat het document content bevat en probeer het opnieuw.",
	corrupted_doc_title: "Het bestand kan niet worden geopend.",
	corrupted_doc_content: "Het bestand bevat niet-ondersteunde content, zoals macro's, en kan daarom niet in deze toepassing worden bekeken.",
	draft_storage_error_title: "Document kan niet worden geopend.",
	draft_storage_error_content: "Content kan niet worden geladen omdat deze beschadigd is. Neem voor ondersteuning contact op met de beheerder.",
	unexpected_code_title: "${productName}-server retourneert onvoorziene code.",
	unexpected_code_content: "${productName}-server retourneert onvoorziene code.",
	request_time_out_title: "Timeout bij laden van document.",
	request_time_out_content: "Het laden van dit document kost te veel tijd. Probeer het later nog eens.",
	problem_id_msg_title: "Meld het probleem aan de beheerder. ",
	problem_id_msg_show: "Klik om details af te beelden",
	problem_id_msg_hide: "Klik om te verbergen"
})

