/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
	fileMenu: "Файл",
	fileMenu_New: "Создать",
	fileMenu_NewDocument: "Документ",
	fileMenu_NewDocumentfromTemplate: "Документ с помощью шаблона",
	fileMenu_NewPresentation: "Презентация",
	fileMenu_NewPresentationfromTemplate: "Презентация с помощью шаблона",
	fileMenu_NewSpreadsheet: "Электронная таблица",
	fileMenu_Open: "Открыть",
//	fileMenu_Close: "Close",
	fileMenu_Discard: "Аннулировать",
	fileMenu_Save: "Сохранить",
//	fileMenu_SaveAs: "Save As...",
//	fileMenu_SaveAsDraft: "as Draft",
//	fileMenu_SaveInMyDocs: "in My Documents",
//	fileMenu_SaveToSymphony: "to Lotus Symphany",
	fileMenu_ShareWith: "Использовать совместно с...	",
	fileMenu_ExportAsPDF: "Экспортировать как PDF",
	fileMenu_WebPreview: "Просмотр в веб-среде",
	fileMenu_PrintPreview: "Просмотр",
	fileMenu_RecentFile: "Недавние файлы",
	fileMenu_Print: "Печать...",
	editMenu: "Правка",
	editMenu_Undo: "Отменить",
	editMenu_Redo: "Повторить",
	editMenu_Cut: "Вырезать",
	editMenu_Copy: "Копировать",
	editMenu_Paste: "Вставить",
	editMenu_DeleteSlide:"Удалить слайд",
	editMenu_SelectAll: "Выделить все",
	editMenu_Find: "Найти...",
	editMenu_Replace: "Заменить...",
	editMenu_DeleteSheet: "Удалить лист",
	editMenu_DuplicateSheet: "Скопировать лист",
	editMenu_DeleteRow: "Удалить строку",
	editMenu_DeleteColumn: "Удалить столбец",
	editMenu_ClearCell: "Очистить ячейку",
	viewMenu: "Вид",
	viewMenu_Master: "Шаблон",
	viewMenu_Notifications: "Уведомления",
	viewMenu_ShowHideIndicators: "Показать/скрыть индикаторы одновременного редактирования",
	viewMenu_SlideSorter: "Показать сортировщик слайдов",
	viewMenu_SpeakerNotes: "Показать озвучиваемый текст",
	viewMenu_NextSlide: "Следующий слайд",
	viewMenu_PrevSlide: "Предыдущий слайд",
	createMenu: "Создать",
	createMenu_NewSlide: "Создать слайд",
	createMenu_DuplicateSlide: "Скопировать слайд",
	createMenu_ImageFromFile: "Рисунок из файла",
	createMenu_TextBox: "Текстовое поле",
	createMenu_Task: "Задача",
    formatMenu_Text_Direction: "Направление текста",
    formatMenu_Ltr: "Слева направо",
    formatMenu_Rtl: "Справа налево",  	
    formatMenu_Horizontal_Align: "По горизонтали",
    formatMenu_Vertical_Align: "По вертикали",
    formatMenu_Align_Top: "По верхнему краю",
    formatMenu_Align_Middle: "По центру",
    formatMenu_Align_Bottom: "По нижнему краю",
	layoutMenu: "Макет",
	layoutMenu_SlideLayout: "Макет слайда",
	layoutMenu_SlideDesign: "Главный стиль",
	tableMenu: "Таблица",
	tableMenu_CreateTable: "Создать таблицу",
	tableMenu_Cell: "Ячейка",
	tableMenu_CellAlignLeft: "Выровнять текст по левому краю",
	tableMenu_CellAlignCenter: "Выровнять текст по центру",
	tableMenu_CellAlignRight: "Выровнять текст по правому краю",
	tableMenu_CellClearContents: "Удалить содержимое",
	tableMenu_Row: "Строка",
	tableMenu_RowAddRowAbove: "Добавить строку сверху",
	tableMenu_RowAddRowBelow: "Добавить строку снизу",
	tableMenu_RowMoveRowAbove: "Переместить строку вверх",
	tableMenu_RowMoveRowBelow: "Переместить строку вниз",
	tableMenu_RowDelete: "Удалить",
	tableMenu_ColumnAddColumnBefore: "Добавить столбец перед",
	tableMenu_ColumnAddColumnAfter: "Добавить столбец после",
	tableMenu_ColumnMoveColumnAfter: "Переместить столбец после",
	tableMenu_ColumnMoveColumnBefore: "Переместить столбец перед",
	tableMenu_ColumnDelete: "Удалить",
	tableMenu_ColumnSortAscending: "Сортировать по возрастанию",
	tableMenu_ColumnSortDescending: "Сортировать по убыванию",
	tableMenu_Column: "Столбец",
	tableMenu_Delete: "Удалить",
	presentationMenu: "Презентация",
	presentationMenu_SlideShow: "Показать демонстрацию",
	presentationMenu_SlideShowFromCurrent: "Показать с текущего слайда",
	toolsMenu: "Сервис",
	toolsMenu_Task: "Задача",
	helpMenu: "Справка",
	helpMenu_Overview: "Содержание справки"
})

