/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */


define({
        saveTip: "Сохранить",
        undoTip: "Отменить",
        redoTip: "Повторить",
        formatPainterTip: "Функция Копировать форматирование",
        showSorterTip: "Показать сортировщик слайдов",
        hideSorterTip: "Скрыть сортировщик слайдов",
        webClipboardTip: "Веб-буфер обмена",
        spellCheckTip: "Проверить орфографию вручную",
        createSectionTip: "Присвоить раздел",
        createCellsTip: "Присвоить ячейки",
        createSlideTip: "Присвоить слайды",
        submitTip: "Передать присвоение",
        addCommentTip: "Добавить комментарий",
        removeFormatTip: "Удалить форматирование",
        sortAscTip: "Сортировать по возрастанию",
        sortDescTip: "Сортировать по убыванию",
        instantFilterTip: "Автофильтр",
        insertChartTip: "Вставить диаграмму",
        startAutofillTip: "Автозаполнение",
        dataValidationTip: "Проверка данных",

        selectFontTip: "Выбрать шрифт",
        selectFontSizeTip: "Выбрать размер шрифта",
        selectFontNameTip: "Выбрать шрифт",
        FontName: "Шрифт",
        FontSize: "Размер шрифта",
        increaseFontSizeTip: "Увеличить размер шрифта",
        decreaseFontSizeTip: "Уменьшить размер шрифта",
        boldTip: "Полужирный",
        italicTip: "Курсив",
        underlineTip: "Подчеркивание",
        strikeThroughTip: "Зачеркивание",
        setFontColorTip: "Задать цвет шрифта",
        setShadingColorTip: "Задать цвет затенения",
        setBackgroundFill: "Задать заполнение фона",
        setBgColorTip: "Задать цвет фона",
        setBorderTip: "Задать стиль и цвет границ",
        setBorderColorTip: "Задать цвет границ",
        setHighlightColor: "Задать цвет выделения",
        formatPainter: "Функция Копировать форматирование",
        //	clearFormat:"Remove Formatting",
        zoom: "Масштаб",
        selectStyleTip: "Выбрать стиль",
        styles: "Стиль",
        formatAsCurrencyTip: "Отформатировать как денежную единицу",
        formatAsPercentTip: "Отформатировать как процентное отношение",
        decreaseDecimalTip: "Сократить дробную часть",
        increaseDecimalTip: "Увеличить дробную часть",
        formatNumberTip: "Числовой формат",

        numberedListTip: "Добавить нумерацию или изменить стиль нумерации",
        bulletedListTip: "Добавить маркировку или изменить стиль списков",
        multilevelListTip: "Добавить или изменить многоуровневый список",
        indentTip: "Увеличить отступ",
        decreaseIndentTip: "Уменьшить отступ",
        alignTip: "Выровнять",
        leftAlignTip: "Выровнять по левому краю",
        centerTip: "Выровнять по центру",
        rightAlignTip: "Выровнять по правому краю",
        justifyTip: "По обоим краям",
        bottomBorderTip: "Нижняя граница",
        borderTypes: "Типы границ",
        borderTip: "Задать стиль границы",
        topAlignTip: "Выровнять по верхнему краю",
        middleAlignTip: "Выровнять по середине",
        bottomAlignTip: "Выровнять по нижнему краю",
        lineSpacingTip: "Междустрочный интервал",
        mergeSplitCellTip: "Объединить или разбить ячейки",
        wrapNoWrapTip: "Вкл./выкл. перенос",
        ltrDirectionTip: "Задать направление текста Слева-направо",
        rtlDirectionTip: "Задать направление текста Справа-налево",
        autoDirectionTip: "Изменить направление текста",
        toggleSheetDirectionTip: "Изменить направление текста на листе",
        setSheetDirectionLTR: "Слева направо",
        setSheetDirectionRTL: "Справа налево",

        addTableTip: "Добавить таблицу",
        insertOrMoveRowTip: "Вставить или переместить строку",
        insertOrMoveColTip: "Вставить или переместить столбец",
        insertOrDeleteRowTip: "Вставить или удалить строку",
        insertOrDeleteColTip: "Вставить или удалить столбец",
        insertFunctionTip: "Вставить функцию",
        insertImage: "Вставить изображение",
        resizeCol: "Изменить ширину столбца",
        resizeCols: "Изменить ширину столбцов",
        addLink: "Добавить или изменить ссылку",
        tableStyle: "Стили таблицы",

        selectBorder_BottomBorder: "Нижняя граница",
        selectBorder_TopBorder: "Верхняя граница",
        selectBorder_LeftBorder: "Левая граница",
        selectBorder_RightBorder: "Правая граница",
        selectBorder_NoBorder: "Без линий",
        selectBorder_AllBorders: "Все границы",

        insertOrMoveRow_InsertAbove: "Вставить строку перед",
        insertOrMoveRow_InsertBelow: "Вставить строку после",
        insertOrMoveRow_MoveUp: "Переместить строку выше",
        insertOrMoveRow_MoveDown: "Переместить строку ниже",
        insertOrMoveCol_InsertLeft: "Вставить столбец перед",
        insertOrMoveCol_InsertRight: "Вставить столбец после",
        insertOrMoveCol_InsertBefore: "Вставить столбец перед",
        insertOrMoveCol_InsertAfter: "Вставить столбец после",
        insertOrMoveCol_MoveLeft: "Переместить столбец влево",
        insertOrMoveCol_MoveRight: "Переместить столбец вправо",

        insertOrDelete_Delete: "Удалить",

        combineButtonReadTip: "Нажмите клавишу Стрелка вниз для активации меню, затем воспользуйтесь стрелками для навигации",

        lineSpacing_1: "1",
        lineSpacing_12: "1,2",
        lineSpacing_15: "1,5",
        lineSpacing_2: "2",
        lineSpacing_25: "2,5",
        lineSpacing_3: "3",

        percent: "%",
        font_arial: "Arial",

        fontSize: "${0} п.",

        slides: "Один слайд на странице",
        slidesWithNotes: "Слайды с примечаниями",
        preparingSlides: "Подготовка слайдов к печати...",
        printLayoutOptionLabel: "Опции печати макета",

        targetRemovedWhenDialogOpen: "Выполнить это действие невозможно, поскольку целевой объект был удален другим соредактором.",

        NUMBER: "Число",
        CURRENCY: "Денежная единица",
        PERCENT: "Проценты",
        DATE: "Дата",
        TIME: "Время",
        DATETIME: "Дата и время",
        MORECURRENCY: "Другие денежные единицы по обозначению валюты",
        MORECURRENCYCODE: "Другие денежные единицы по коду валюты",
        MOREDATE: "Дополнительные форматы даты и времени",
        TEXT: "Текст",
	
        // currency, by currency code
        // NOTE: MUST keep it in order
        CURRENCY_CODE: {
            AED: "ОАЭ (дирхам)",
            ARS: "Аргентина (песо)",
            AUD: "Австралия (доллар)",
            BGN: "Болгария (лев)",
            BOB: "Боливия (боливиано)",
            BRL: "Бразилия (реал)",
            CAD: "Канада (доллар)",
            CHF: "Швейцария (франк)",
            CLP: "Чили (песо)",
            CNY: "Китай (юань женьминьби)",
            COP: "Колумбия (песо)",
            CRC: "Коста-Рика (колон)",
            CZK: "Чешская Республика (крона)",
            DKK: "Дания (крона)",
            DOP: "Доминиканская Республика (песо)",
            EGP: "Египет (фунт)",
            EUR: "Австрия, Бельгия, Финляндия, Франция,  ..., Словения, Испания (евро)",
            GBP: "Англия, Соединенное Королевство (фунт)",
            HKD: "Гонконг (доллар)",
            HRK: "Хорватия (куна)",
            HUF: "Венгрия (форинт)",
            IDR: "Индонезия (рупия)",
            ILS: "Израиль (новый шекель)",
            INR: "Индия (рупия)",
            JPY: "Япония (йена)",
            KRW: "Корея, Южная (вона)",
            KZT: "Казахстан (тенге)",
            MAD: "Марокко (дирхам)",
            MXN: "Мексика (песо)",
            MYR: "Малайзия (ринггит)",
            NOK: "Норвегия (крона)",
            NZD: "Новая Зеландия (доллар)",
            PAB: "Панама (бальбоа)",
            PEN: "Перу (новый соль)",
            PHP: "Филиппины (песо)",
            PKR: "Пакистан (рупия)",
            PLN: "Польша (злотый)",
            PYG: "Парагвай (гуарани)",
            RON: "Румыния (новый лей)",
            RSD: "Сербский (кириллица), Сербский (латиница)",
            RUB: "Россия (рубль)",
            SAR: "Саудовская Аравия (риял)",
            SEK: "Швеция (крона)",
            SGD: "Сингапур (доллар)",
            SVC: "Сальвадор (колон)",
            THB: "Таиланд (бат)",
            TRY: "Турция (лира)",
            TWD: "Тайвань (новый доллар)",
            USD: "Эквадор, Пуэрто-Рико, Соединенные Штаты Америки (доллар США)",
            UYU: "Уругвай (песо)",
            VEF: "Венесуэла (боливар фуэрте)",
            VND: "Вьетнам (донг)",
            ZAR: "Южная Африка (ранд)"
        },
        // for border toolbar
        allBorders: "Все границы",
        innerBorders: "Внутренние границы",
        horizontalBorders: "Горизонтальные границы",
        verticalBorders: "Вертикальные границы",
        outerBorders: "Внешние границы",
        borderColor: "Цвет границы",
        leftBorder: "Левая граница",
        topBorder: "Верхняя граница",
        rightBorder: "Правая граница",
        bottomBorder: "Нижняя граница",
        clearBorders: "Без границ",
        BorderStyle_ThinSolid: "Тонкая сплошная линия",
        BorderStyle_ThinDotted: "Тонкая точечная линия",
        BorderStyle_ThinDashed: "Тонкая пунктирная линия",
        BorderStyle_ThickSolid: "Толстая сплошная линия",
        BorderStyle_ThickDotted: "Толстая точечная линия",
        BorderStyle_ThickDashed: "Толстая пунктирная линия"
})

