({
	labelPrintConfig: "Per ottenere i migliori risultati di stampa, configurare la pagina delle impostazioni del proprio browser nel modo seguente:",
	labelConfigPageSize: "Dimensioni pagina: ${0}",
	labelConfigOrientation: "Orientamento: ${0}",
	labelConfigHeader: "Intestazione: vuota",
	labelConfigFooter: "Piè di pagina: vuoto",
	labelConfigMargins: "Margini: ",
	labelConfigMarginTop: "Superiore: ${0}${1}",
	labelConfigMarginBottom: "Inferiore: ${0}${1}",
	labelConfigMarginLeft: "Sinistra: ${0}${1}",
	labelConfigMarginRight: "Destra: ${0}${1}",
	labelPrintContinue: "Una volta configurate le impostazioni del browser, fare clic su OK per continuare a stampare il file.",
	labelMm: "millimetri",
	labelInch: "pollici",
	labelPortrait: "Verticale",
	labelPageA4: "A4",
	labelLetter: "Letter",
	labelLandscape: "Orizzontale",
	titlePrintConfig: "Impostazioni di stampa",
	titlePrepare: "Preparazione per la stampa",
	msgPrepare: "Preparazione del file per la stampa in corso. La preparazione potrebbe richiedere molto tempo.",
	errPrepare: "Si è verificato un errore durante la preparazione dei dati.\nRiprovare?",
	titleErr: "Errore",
	btnRetry: "Riprova"
})
