({
	labelNormal: "Нормален приказ",
	labelPlay: "Пушти приказ на слајд",
	labelZoomIn: "Зумирај",
	labelZoomOut: "Одзумирај",
	labelFitWidth: "Прилагоди на ширина",
	labelReset: "Ресетирај",
	lablePageUp: "Претходна страница",
	lablePageDown: "Следна страница",
	labelPrint: "Печати",
	labelBuild: "${productName} ${0}",
	labelVersion: "${productName} ${0} ${1}",
	msgLoading: "Почекајте додека документот се вчитува.",
	msgConversionFail: "Претворањето не успеа",
	labelReload: "Вчитај повторно",
	labelHelpContent:"Содржина на Помош",
	labelAbout:"За",
	labelProject:"${productName}",
	labelEdit: "Уреди",
	labelHelp: "Помош",
	labelCancel: "Откажи",
	labelImageTypeIcon: "Документ",
	errPrintBeforeLoading: "Не можете да го користите менито во прегледувачот за да печатите. За печатење на документот, кликнете на копчето Печати на алатникот. Не можете да печатите сега бидејќи содржината не е целосно вчитана.",
	errPrintFromBrowserMenu: "За печатење на документот, кликнете на копчето Печати на алатникот, наместо на менито Печати во прегледувачот.",
	errPrintConversionFail: "Не можете да печатите бидејќи содржината не успеа успешно да се претвори.",
	successMsg:"Успех",
	warningMsg:"Предупредување",
	errorMsg:"Грешка",
	backtofiles:"Назад кон Датотеки",
	openLatestFile: "Отворете ја последната датотека",
	updatePresentation:"Презентацијата е ажурирана.${0} за да ги видите целиот текст и сликите",
	updateNow: "Отвори сега",
	fileUpdated: "Презентацијата е ажурирана",
	fileUpdatedContent1: "Презентацијата е ажурирана. Отворете ја последната датотека пред да печатите.",
	fileUpdatedContent2: "Презентацијата е ажурирана. Отворете ја последната датотека пред да го пуштите приказот на слајд.",
	htmlviewerlimitation: "Оваа презентација содржи анимација којашто не може да се прикаже",
	labelStopReview: "Запри Преглед",
	labelRejct: "Отфрли",
	labelApprove: "Одобри",
	labelItemNotFountTitle: "Дејството не може да се заврши.",
	labelItemNotFountMsg: "Друг член на заедницата веќе презел дејство врз документот. За повеќе информации, затворете го документот и одете на страницата Детали за датотека во вашата библиотека."
})

