({
	stViewClient:"顯示 Sametime 用戶端",
	stChatList:"按一下可在新視窗中開啟 Sametime Web 用戶端。",
	stWebClient:"HCL Sametime",
	stStatusMeeting:"開會中",
	stStatusAvailable:"有空",
	stViewBd:"顯示 Sametime 好友清單",
	stErrorSTServer:"連線到 Sametime 時發生錯誤",
	stStatusAway:"離開座位",
	stLConnLogIn:"登入 HCL Connections，以檢視 Sametime 狀態",
	stActionBar:"Sametime 動作列",
	stStatusBusy:"忙碌",
	stLogin:"登入 Sametime",
	stUserOffline:"離線",
	stStartChat:"按一下這裡可開始會談",
	stLogout:"登出 Sametime",
	stDisconnect:"中斷 Sametime 連線",
	stViewSTActions:"按一下可檢視 Sametime 動作",
	stError:"發生錯誤。Sametime 服務無法使用。",
	stUnableToConnect:"無法連線到 Sametime。",
	stConnect:"連線到 Sametime",
	stNoStatuAvailable:"沒有 Sametime 狀態可供顯示",
	stStatusdnt:"勿打擾",
	stLoadingSTStatus:"正在載入 Sametime 狀態...",
	stShareAs:"共用文件...",
	stShareDlgTitle:"透過 Sametime 共用文件...",
	stShareDlgMsgTemplate:"要以「編輯者」或「讀者」的身分，與 ${contact_name} 共用 ${file_name} 嗎？",
	stShareEditor:"編輯者",
	stShareReader:"讀者",
	stShareSuccessTemplate:"${contact_name} 您好：我想要與您一起共用 '${file_name}'：\n<a href=\"${document_link}\">${document_link}</a>"
})
