({	
	createTaskSummary: "${0} görevi oluşturdu.",
	completeTaskSummary: "${0} görevi tamamlandı olarak işaretledi.",
	editTaskSummary5: "${0} görevin ${1}, ${2}, ${3}, ${4} ve ${5} alanlarını düzenledi.",
	editTaskSummary4: "${0} görevin ${1}, ${2}, ${3} ve ${4} alanlarını düzenledi.",
	editTaskSummary3: "${0} görevin ${1}, ${2} ve ${3} alanlarını düzenledi.",
	editTaskSummary2: "${0} görevin ${1} ve ${2} alanlarını düzenledi.",
	editTaskSummary1: "${0} görevin ${1} alanını düzenledi.",
	editTaskSummary0: "${0} görevi düzenledi.",
	removeTaskSummary: "${0} görevi kaldırdı.",
	reopenTaskSummary: "${0} görevi yeniden açtı.",
	reassignTaskSummary: "${0}, ${1} görevini ${2} adlı kişiden ${3} adlı kişiye yeniden atadı.",
	reassignTaskSummary2: "${0}, atananı ${1} adlı kişiden ${2} adlı kişiye ve inceleyeni ${3} adlı kişiden ${4} adlı kişiye değiştirdi.",
	workPrivateSummary: "${0} bu görev üzerinde özel olarak çalışmaya başladı.",
	approveTaskSummary: "${0} bu görevi onayladı.",
	rejectTaskSummary: "${0} bu görevi reddetti.",
	rejectTaskSummary2: "${0}, bu görevi yeniden çalışma için ${1} adlı kişiye geri gönderdi.",
	submitTaskSummary: "${0}, özel çalışmayı belgeye geri gönderdi.",
	cancelPrivateSummary: "${0} özel çalışmayı iptal etti.",
	updatedFieldsDesc: "${0}: ${1} -> ${2}",
	fieldAssignee: "atanan",
	fieldDuedate: "son tarih",
	fieldDescription: "açıklama",
	fieldReviewer: "inceleyen",
	fieldTitle: "başlık",
	emptyFieldValue: "[Atanmamış]",
	errorAddMember:"Atanan ya da gözden geçirecek kişileri eklemek için etkinlik sunucusuna erişilemiyor. Daha sonra yeniden deneyin.",
	errorCreateActivity:"Etkinliği oluşturmak için etkinlik sunucusuna erişilemiyor. Daha sonra yeniden deneyin.",
	errorLoadActivity:"Atamaları yüklemek için etkinlik sunucusuna erişilemiyor. Daha sonra yeniden deneyin.",
	errorCreateAssignment: "Atamaları oluşturmak için etkinlik sunucusuna erişilemiyor. Daha sonra yeniden deneyin.",
	errorDeleteAssignment: "Atamaları silmek için etkinlik sunucusuna erişilemiyor. Daha sonra yeniden deneyin.",
	errorupdateAssignment: "Atamaları güncelleştirmek için etkinlik sunucusuna erişilemiyor. Daha sonra yeniden deneyin.",
	errorSubmitAssignment: "Bu işlemi gerçekleştiremezsiniz. Buna izniniz olup olmadığını görmek için denetleyin.",	
	errorAddMember2:"Atanan ya da gözden geçirecek kişileri eklemek için sunucuya erişilemiyor. Daha sonra yeniden deneyin.",
	errorCreateActivity2:"Etkinliği oluşturmak için sunucuya erişilemiyor. Daha sonra yeniden deneyin.",
	errorLoadActivity2:"Atamaları yüklemek için sunucuya erişilemiyor. Daha sonra yeniden deneyin.",
	errorCreateAssignment2: "Atamayı oluşturmak için sunucuya erişilemiyor. Daha sonra yeniden deneyin.",
	errorDeleteAssignment2: "Atamaları silmek için sunucuya erişilemiyor. Daha sonra yeniden deneyin.",
	errorupdateAssignment2: "Atamaları güncelleştirmek için sunucuya erişilemiyor. Daha sonra yeniden deneyin."	
})
