({
	ORIENTATION_LABEL: "Ausrichtung",
	PORTRAIT: "Hochformat",
	LANDSCAPE: "Querformat",
	PAGE_LABEL: "Seitenreihenfolge",
	PAGE_TYPE1: "Von oben nach unten, dann nach links",
	PAGE_TYPE2: "Von links nach rechts, dann nach unten",
	DISPLAY_OPTION_LABEL: "Anzeigeoptionen",
	HEADER: "Kopfzeile",
	FOOTER: "Fußzeile",
	GRIDLINE: "Rasterlinien",
	MARGINS_LABEL: "Randeinstellungen",
	TOP: "Oben:",
	BOTTOM: "Unten:",
	LEFT: "Links:",
	RIGHT: "Rechts:",
	PAPER_FORMAT_LABEL: "Papierformat",
	PAPER_SIZE_LABEL: "Papierformat:",
	HEIGHT: "Höhe:",
	WIDTH: "Breite:",
	
	TOOLTIP1:"Druckt so viele Zeilen, wie die Seite lang ist und bewegt sich so lange hin und her, bis keine Spalten mehr auf dem Blatt sind und anschließend nach unten und links, um die nächste Gruppe von Zeilen zu drucken.",
	TOOLTIP2:"Druckt so viele Spalten, wie das Blatt breit ist und bewegt sich nach unten, bis keine Zeilen mehr auf dem Blatt sind. Anschließend bewegt es sich nach oben und nach rechts, um die nächste Gruppe von Spalten zu drucken.",
	CM_LABEL: "cm",
	LETTER: "Letter",
	LEGAL: "Brief",
	TABLOID: "Tabloid",
	USER: "Benutzer(spezifisch)",
	SIZE1: "Umschlag #6 3/4",
	SIZE2: "Umschlag Monarch",
	SIZE3: "Umschlag #9",
	SIZE4: "Umschlag #10",
	SIZE5: "Umschlag #11",
	SIZE6: "Umschlag #12",
	SIZE7: "16 Kai",
	SIZE8: "32 Kai",
	SIZE9: "32 Kai groß"
})
	
