({
	stViewClient:"Sametime-Client anzeigen",
	stChatList:"Klicken Sie hier, um den Sametime-Web-Client in einem neuen Fenster zu öffnen.",
	stWebClient:"HCL Sametime ",
	stStatusMeeting:"In einer Besprechung",
	stStatusAvailable:"Ich bin verfügbar",
	stViewBd:"Sametime-Buddy-Liste anzeigen",
	stErrorSTServer:"Fehler beim Herstellen der Verbindung zu Sametime",
	stStatusAway:"Ich bin abwesend",
	stLConnLogIn:"Bei HCL Connections anmelden, um den Sametime-Status anzuzeigen",
	stActionBar:"Sametime-Aktionsleiste",
	stStatusBusy:"Ich bin gerade beschäftigt",
	stLogin:"Bei Sametime anmelden",
	stUserOffline:"Ich bin offline",
	stStartChat:"Klicken Sie hier, um einen Chat zu starten",
	stLogout:"Von Sametime abmelden",
	stDisconnect:"Verbindung zu Sametime trennen",
	stViewSTActions:"Klicken Sie hier, um Sametime-Aktionen anzuzeigen",
	stError:"Ein Fehler ist aufgetreten. Der Sametime-Service ist nicht verfügbar.",
	stUnableToConnect:"Die Verbindung zu Sametime ist nicht verfügbar. ",
	stConnect:"Verbindung zu Sametime herstellen",
	stNoStatuAvailable:"Kein Sametime-Status verfügbar",
	stStatusdnt:"Bitte nicht stören",
	stLoadingSTStatus:"Sametime-Status wird geladen...",
	stShareAs:"Dokument freigeben...",
	stShareDlgTitle:"Dokument über Sametime freigeben...",
	stShareDlgMsgTemplate:"Möchten Sie die Datei \"${file_name}\" für \"${contact_name}\" als Bearbeiter oder Leser freigeben?",
	stShareEditor:"Bearbeitende Person",
	stShareReader:"Leser",
	stShareSuccessTemplate:"${contact_name}, ich möchte das Dokument \"${file_name}\" für Sie freigeben:\n<a href=\"${document_link}\">${document_link}</a>"
})
