({
	ORIENTATION_LABEL: "Usmerjenost",
	PORTRAIT: "Pokončno",
	LANDSCAPE: "Ležeče",
	PAGE_LABEL: "Vrstni red strani",
	PAGE_TYPE1: "Od vrha proti dnu, nato desno",
	PAGE_TYPE2: "Od leve proti desni, nato navzdol",
	DISPLAY_OPTION_LABEL: "Možnosti prikaza",
	HEADER: "Glava",
	FOOTER: "Noga",
	GRIDLINE: "Mrežne črte ",
	TAGGED_PDF: "Označen PDF",
	MARGINS_LABEL: "Robovi",
	TOP: "Zgornji:",
	TOP_DESC:"Zgornji rob, v centimetrih",
	TOP_DESC2:"Zgornji rob, v palcih",
	BOTTOM: "Spodnji:",
	BOTTOM_DESC:"Spodnji rob, v centimetrih",
	BOTTOM_DESC2:"Spodnji rob, v palcih",	
	LEFT: "Levi:",
	LEFT_DESC:"Levi rob, v centimetrih",
	LEFT_DESC2:"Levi rob, v palcih",	
	RIGHT: "Desni:",
	RIGHT_DESC:"Desni rob, v centimetrih",
	RIGHT_DESC2:"Desni rob, v palcih",	
	PAPER_FORMAT_LABEL: "Oblika papirja",
	PAPER_SIZE_LABEL: "Velikost papirja:",
	HEIGHT: "Višina:",
	HEIGHT_DESC:"Višina papirja, v centimetrih",
	HEIGHT_DESC2:"Višina papirja, v palcih",		
	WIDTH: "Širina:",
	WIDTH_DESC:"Širina papirja, v centimetrih",
	WIDTH_DESC2:"Širina papirja, v palcih",
	
	INVALID_MSG: "Vnos je neveljaven in je bil samodejno popravljen. Če želite drugačen rezultat, poskusite vnesti drugo vrednost.",
	
	TOOLTIP1:"Natisne toliko vrstic, kot jih je mogoče natisniti na dolžino papirja, pri čemer se pomika počez, dokler na listu ni več stolpcev, nato se pomakne navzdol in v levo, da natisne naslednjo skupino vrstic.",
	TOOLTIP2:"Natisne toliko stolpcev, kot jih je mogoče natisniti na širino papirja, pri čemer se pomika navzdol, dokler na listu ni več vrstic, nato se pomakne navzgor in v desno, da natisne naslednjo skupino stolpcev.",
	CM_LABEL: "cm",
	LETTER: "Letter",
	LEGAL: "Legal",
	TABLOID: "Tabloid",
	USER: "Uporabnik",
	SIZE1: "Env. #6 3/4",
	SIZE2: "Env. Monarch",
	SIZE3: "Env. #9",
	SIZE4: "Env. #10",
	SIZE5: "Env. #11",
	SIZE6: "Env. #12",
	SIZE7: "16 kai",
	SIZE8: "32 kai",
	SIZE9: "32 kai large"
})
	
