({
	delete_general: "Hapus",
	order: "Urutan",
	align_text: "Sejajarkan Teks",
	align_slide: "Sejajarkan dalam Slide",
	align_objects: "Sejajarkan Objek yang Dipilih",
	zoom: "Zoom",
	zoom_fit: "Sesuaikan dengan Jendela",
	insert_link: "Masukkan Tautan",
	add_link: "Tambah Tautan",
	open_link: "Buka Tautan",
	edit_link: "Edit Tautan",
	remove_link: "Hapus Tautan",
	insert_link_menu: "Tautan",
	invalid_url: "Tidak dapat membuka URL. Periksa apakah URL sudah benar atau pengaturan block pop-up windows browser.",
	dnd_canceled_on_slide_event: "Slide tidak dapat dipindahkan karena editor lain sedang mengubah presentasi. Coba lagi nanti.",
	rotate: "Putar",
	flipX: "Balik secara Horizontal",
	flipY: "Balik secara Vertikal",
	rotate_right: "Putar 90&#x00B0 Searah Jarum Jam",
	rotate_left: "Putar 90&#x00B0 Berlawanan Arah Jarum Jam",
	color_set_fill: "Atur Warna Isian",
	color_nofill: "Tanpa Warna",
	color_nobackground: "Tanpa Latar Belakang",
	color_auto: "Otomatis",
	color_default: "Default",
	color_transparent: "Transparan",
	
	objects_distribute: "Distribusikan",
	objects_distribute_v: "Secara Vertikal",
	objects_distribute_h: "Secara Horizontal",
	
	link_subject: "Subjek :",
	link_text: "Teks yang akan ditampilkan :",
	link_mailto: "Buka Email",
	link_goto: "Buka Tautan",
	link_done: "Selesai",
	link_remove: "Hapus",
	link_website: "Situs web",
	link_email: "Email",
	link_slide: "Slide",
	link_slide_placeholder: "Pilih untuk memasukkan bilangan",
	link_slide_placeholder_deleted: "Slide yang Ditautkan Telah Dihapus",
	link_slide_next: "Slide Berikutnya",
	link_slide_prev: "Slide Sebelumnya",
	link_slide_first: "Slide Pertama",
	link_slide_last: "Slide Terakhir",
	link_slide_number: "Slide ${0}",
	link_not_support: "Tipe tautan tidak didukung",
	link_acc_input: "Masukkan alamat tautan",
	link_acc_mail_input: "Masukkan alamat email",
	

	// Jaws Support
	acc_blank: "kosong",// when selection is nothing but space char and empty paragraph
	acc_selected: " dipilih",
	acc_showed: " ditampilkan",
	acc_inTable: " dalam tabel baris ${0} kolom ${1} ",
	acc_titleSelected: "judul dipilih",
	acc_subtitleSelected: "subjudul dipilih",
	acc_outlineSelected: "outline dipilih",
	acc_notesSelected: "catatan berbicara dipilih",
	acc_imageSelected: "grafik dipilih",
	acc_shapeSelected: "bentuk dipilih",
	acc_rotated: " diputar ${0} derajat",
	acc_tableSelected: "tabel dipilih",
	acc_textboxSelected: "kotak teks yang dipilih",
	acc_enterEdit: " tekan untuk mengedit",
	acc_locked_by: " yang dikunci oleh pengguna ${0}",
	acc_slide_used_by: " yang digunakan oleh pengguna ${0}",
	ACC_TABLE_TABLESIZE: "Anda telah memilih ${0} baris, ${1} kolom",
	ACC_TABLE_MAXSIZE: " Ukuran tabel maksimum yang didukung adalah 8*8",
	ACC_EditorMode: "mode edit editor",
	ACC_EndEditorMode: "mode edit editor akhir",
	ACC_Table_new_row: "Sebuah baris baru ditambahkan",
	ACC_Table_new_column: "Sebuah kolom baru ditambahkan",
	Acc_column: "kolom ${0}",
	acc_slide: "slide ${0}",
	acc_editor: "Edit dengan ${0}",
	Plain: "Biasa",
	BlueStyle: "Gaya biru",
	RedTint: "Tint merah",
	BlueHeader: "Header biru",
	DarkGrayHF: "Header/footer abu-abu tua",
	LightGrayRows: "Baris abu-abu muda",
	DarkGrayRows: "Baris abu-abu tua",
	BlueTint: "Tint biru",
	RedHeader: "Header merah",
	GreenHF: "Header/footer hijau",
	PlainRows: "Baris biasa",
	GrayTint: "Tint abu-abu",
	GreenTint: "Tint hijau",
	GreenHeader: "Header hijau",
	RedHF: "Header/footer merah",
	GreenStyle: "Gaya hijau",
	PurpleTint: "Tint ungu",
	BlackHeader: "Header hitam",
	PurpleHeader: "Header ungu",
	LightBlueHF: "Header/footer biru muda",
	
    formatMenu_LineSpacing: "Spasi Baris",
	linespaceboxTitle:"Spasi Kustom",
	linespacelineTitle:"Baris:",
	linespacenoticeContent :"Spasi Baris",
    formatMenu_LineSpacing_Customize: "Kustom...",
    formatMenu_LineSpacing_CustomValue:"Kustom: ${0}",
    lineSpaceWarning:"Masukkan bilangan dari 0 sampai 10",
    
    set_transparency_menu: "Opasitas Gambar",
    opacity_percent_value: "${0}%",
    opacity_title: "Opasitas",
    
    increaseLineWidthTip: "Tambah Ketebalan Garis",
	decreaseLineWidthTip : "Kurangi Ketebalan Garis",
    setBorderStyleTip:"Atur Gaya Garis",
    line_width_title: "Tebal garis",
    line_end_title: "Titik akhir garis",
    line_dash_title: "Pola garis",
    line_dash_type1: "Padat",
    line_dash_type2: "Titik kotak",
    line_dash_type3: "Garis pisah",
    line_dash_type4: "Titik bulat",
    line_dash_type5: "Garis pisah dan titik",
    line_dash_type6: "Garis pisah panjang",
    line_endpoints_type1: "None",
    line_endpoints_type2: "Tanda panah kanan sederhana",
	line_endpoints_type3: "Tanda panah kiri sederhana",
	line_endpoints_type4: "Tanda panah ganda sederhana",
	line_endpoints_type5: "Tanda panah kanan berwarna",
	line_endpoints_type6: "Tanda panah kiri berwarna",
    line_endpoints_type7: "Tanda panah ganda berwarna",
    line_endpoints_type8: "Lingkaran dan tanda panah berwarna",
	line_endpoints_type9: "Berlian dan tanda panah berwarna",
	line_endpoints_type10: "Berlian berwarna",
    line_endpoints_type11: "Lingkaran berwarna"
})

