/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2014. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
	service_unavailable_title: "Usługa jest niedostępna.",
	service_unavailable_content: "Usługa programu ${productName} jest niedostępna. W tym momencie nie można przetworzyć żądania. Spróbuj ponownie później lub skontaktuj się z administratorem systemu.",
	access_denied_title: "Odmowa dostępu.",
	viewaccess_denied_content: "Nie masz uprawnień do wyświetlania tego pliku. Plik musi być publiczny lub udostępniony do współużytkowania.",
	editaccess_denied_content: "Nie masz uprawnień do używania programu ${productName} lub nie masz uprawnień do edytowania tego pliku. Plik musi być udostępniony do współużytkowania i musisz mieć dostęp do pliku z uprawnieniami edytującego. Plik może być również zablokowany przez innego edytującego.",
	doc_notfound_title: "Nie znaleziono dokumentu.",
	doc_notfound_content: "Dokument, do którego chcesz uzyskać dostęp, został usunięty lub przeniesiony. Sprawdź, czy odsyłacz jest poprawny.",
	repository_out_of_space_title: "Brak miejsca",
	repository_out_of_space_content: "Nie można opublikować pliku ${0}, ponieważ został osiągnięty limit wielkości plików. Zwiększ ilość wolnego miejsca, przenosząc pliki do kosza i usuwając je.",
	fileconnect_denied_title: "Odmówiono nawiązania połączenia.",
	fileconnect_denied_content: "Program ${productName} nie może nawiązać połączenia z repozytorium plików. Spróbuj ponownie później lub skontaktuj się z administratorem systemu.",
	unscanned_document_title: "Kończenie skanowania antywirusowego",
	unscanned_document_content: "Pliki przesyłane do programu Connections są automatycznie skanowane. Ten plik będzie można edytować, gdy zakończy się jego skanowanie.",
	malicious_document_title: "Szkodliwy plik",
	malicious_document_content: "Nie można edytować tego pliku, ponieważ podczas jego skanowania program Connections wykrył w nim wirusa.",	
	convservice_unavailable_title: "Usługa konwersji jest niedostępna.",
	convservice_unavailable_content: "Usługa konwersji programu ${productName} jest niedostępna. W tym momencie nie można przetworzyć żądania. Spróbuj ponownie później lub skontaktuj się z administratorem systemu.",
	doc_toolarge_title: "Plik jest zbyt duży.",
	doc_toolarge_content: "Dokument, do którego chcesz uzyskać dostęp, jest zbyt duży.",
	doc_toolarge_content2: "Nie można uzyskać dostępu do pliku. Możliwe przyczyny:",
	doc_toolarge_content3: "Nie można wyświetlić pliku, ponieważ jego wielkość przekracza ${0} kB. Można pobrać plik w celu jego edycji. Jeśli plik zawiera obrazy w wysokiej rozdzielczości, można zastąpić je obrazami w małej rozdzielczości w celu zmniejszenia wielkości pliku.",
	doc_toolarge_content4: "Plik jest zbyt duży, aby można było go tutaj wyświetlić, ale nadal można go otworzyć, klikając przycisk pobierania na pasku tytułu.",
	doc_toolarge_content_mobile: "Nie można otworzyć pliku. Plik nie możne być większy niż ${0} kB na urządzeniu mobilnym.",
	sheet_toolarge_content: "Wielkość arkusza kalkulacyjnego przekracza ${0} kB.",
	sheet_toolarge_content2: "W arkuszu kalkulacyjnym liczba wierszy w jednym arkuszu jest większa niż ${0}.",
	sheet_toolarge_content5: "W arkuszu kalkulacyjnym liczba kolumn w jednym arkuszu jest większa niż ${0}.",
	sheet_toolarge_content3: "Liczba komórek zawartych w arkuszu kalkulacyjnym jest większa niż ${0}.",
	sheet_toolarge_content4: "Liczba formuł zawartych w arkuszu kalkulacyjnym jest większa niż ${0}.",
	text_toolarge_content: "Wielkość dokumentu przekracza ${0} kB.",
	text_toolarge_content2:"Liczba stron w dokumentu jest większa niż ${0}.",
	text_toolarge_content3:"Wielkość tekstu w dokumencie przekracza ${0} kB.",
	pres_toolarge_content: "Nie można uzyskać dostępu do prezentacji, ponieważ jej wielkość przekracza ${0} kB. Jeśli prezentacja zawiera obrazy o wysokiej rozdzielczości, można zastąpić je obrazami o niskiej rozdzielczości, aby zmniejszyć wielkość prezentacji.",
	pres_toolarge_content2: "Nie można uzyskać dostępu do prezentacji, ponieważ liczba stron w prezentacji jest większa niż ${0}.",
	pres_toolarge_content3: "Nie można uzyskać dostępu do prezentacji, ponieważ liczba obiektów w prezentacji jest większa niż ${0}.",
	pres_toolarge_content2_mobile: "Nie można otworzyć prezentacji, ponieważ na urządzeniu mobilnym liczba stron w prezentacji jest większa niż ${0}.",
	pres_toolarge_content3_mobile: "Nie można otworzyć prezentacji, ponieważ na urządzeniu mobilnym liczba obiektów w prezentacji jest większa niż ${0}.",
	sheet_view_toolarge_content1_mobile: "Nie można wyświetlić arkusza kalkulacyjnego, ponieważ na urządzeniu mobilnym liczba wierszy w arkuszu kalkulacyjnym jest większa niż ${0}.",
	sheet_view_toolarge_content2_mobile: "Nie można wyświetlić arkusza kalkulacyjnego, ponieważ na urządzeniu mobilnym liczba kolumn w arkuszu kalkulacyjnym jest większa niż ${0}.",
	sheet_view_toolarge_content3_mobile: "Nie można wyświetlić arkusza kalkulacyjnego, ponieważ na urządzeniu mobilnym liczba wierszy i kolumn w arkuszu kalkulacyjnym jest większa niż odpowiednio ${0} i ${1}.",
	conversion_timeout_title: "Limit czasu konwersji dokumentu został przekroczony.",
	conversion_timeout_content: "Tym razem konwersja dokumentu trwała zbyt długo. Spróbuj ponownie później.",
	invalid_docformat_title: "Nie można otworzyć dokumentu",
	invalid_docformat_content: "Rozszerzenie dokumentu jest poprawne, ale nie można odczytać treści, ponieważ jest uszkodzona lub zaszyfrowana.",
	template_extension_conent_mismatch: "Rozszerzenie nazwy pliku źródłowego niepoprawnie identyfikuje go jako szablon. Plik jest aktualnie w formacie .${0}. Rozpocznij pracę z użyciem poprawnego szablonu lub zapisz ten plik pod inną nazwą i użyj rozszerzenia .${0}.",
	invalid_docformat_title2: "Nie można zaimportować pliku do programu ${productName}.",
	invalid_docformat_content2: "W tym pliku znajduje się coś, co nie jest obsługiwane przez program ${productName}. Nie można zaimportować tego pliku",
	invalid_doctype_title: "Typ dokumentu nie jest obsługiwany.",
	invalid_doctype_content: "Typ dokumentu nie jest aktualnie obsługiwany przez program ${productName}.",
	unsupported_browser_title: "Przeglądarka nie obsługuje wszystkich składników.",
	malformed_request_title: "Żądanie jest zniekształcone.",
	malformed_request_content: "Upewnij się, że adres URL i parametry są poprawne.",
	storageserver_error_title: "Serwer pamięci masowej jest niedostępny.",
	storageserver_error_content: "Serwer jest obecnie niedostępny. W tym momencie nie można przetworzyć żądania. Spróbuj ponownie później lub skontaktuj się z administratorem systemu.",
	document_already_opened_title: "Dokument jest już otwarty.",
	document_already_opened_content:"Ten dokument jest już otwarty w przeglądarce.",
	toomany_documents_opened_inone_browser_title: "Nie można otworzyć dokumentu.",
	toomany_documents_opened_inone_browser_content:"Jednocześnie można otworzyć tylko pięć plików programu ${productName}. Zamknij inne dokumenty i spróbuj ponownie otworzyć ten dokument.",
	document_max_session_exceeded_title:"Usługa jest niedostępna.",
	document_max_session_exceeded_content:"Zbyt wielu użytkowników edytuje dokumenty na serwerze. Nie można przetworzyć żądania. Spróbuj ponownie później.",
	kickout_user_content: "Ten dokument jest już otwarty w innym oknie na tym komputerze. Aby kontynuować jego edytowanie, wróć do innego okna.",
	return_to_files: "Wróć do komponentu Pliki",
	return_to_library: "Wróć do biblioteki",
	return_to_icn: "Wróć do nawigatora treści",
	document_already_open: "Dokument jest już otwarty",
	cannotedit_noentitled_title: "Nie można współedytować tego pliku",
	cannotedit_noentitled_content1: "Następujący użytkownicy edytują teraz ten plik:",
	cannotedit_noentitled_content2: "Nie masz autoryzacji do edycji tego pliku, gdy jest on edytowany przez inne osoby. Spróbuj edytować go później.",
	cannotedit_noentitled_content3: "Następujący użytkownik edytuje teraz ten plik:",
	cannotedit_noentitled_content4: "Nie możesz dołączyć do tej sesji edycji, ponieważ użytkownik edytujący plik nie jest uprawniony do współedytowania. Spróbuj ponownie edytować ten plik później.",
	toomany_coeditors_title: "Zbyt wielu użytkowników",
	toomany_coeditors_content: "Aktualnie zbyt wielu użytkowników edytuje ten dokument. Jednocześnie z dokumentem może pracować następująca liczba użytkowników: {0}.",
	encrypted_pptdoc_title:"Zaszyfrowany plik",
	encrypted_pptdoc_content:"Plik jest chroniony hasłem. Jeśli chcesz przeprowadzić edycję tego pliku w programie ${productName}, zdeszyfruj go najpierw.",
	server_busy_title:"Serwer jest zajęty",
	server_busy_content:"Zaczekaj jakiś czas i spróbuj ponownie później.",
	document_encrypt_title:"Zaszyfrowany dokument nie jest obsługiwany",
	document_encrypt_content:"Ten plik został zaszyfrowany w repozytorium plików. Ze względów bezpieczeństwa program ${productName} nie może go edytować bezpośrednio.",
	edit_locked_file: "Nie możesz edytować tego pliku, ponieważ jest on zablokowany przez innych edytujących.",
	publish_locked_file: "Nie możesz opublikować tego pliku jako nowej wersji, ponieważ jest on zablokowany. Jednak treść użytkownika jest automatycznie zapisywana w wersji roboczej.",
	join_locked_file_session: "Nie możesz dołączyć do sesji współedytowania, ponieważ ten plik jest zablokowany przez innych użytkowników.",
	no_need_to_convert_title:"Konwersja nie jest potrzebna",
	no_need_to_convert_content:"Plik jest już w formacie, który wybrano jako docelowy format konwersji. Pobierz plik bezpośrednio.",
	warning_icon: "Ikona ostrzeżenia",
	//html viewer error message
	incorrect_web_address_title:"Niepoprawny adres WWW.",
	incorrect_web_address_content:"Adres WWW jest niepoprawny.  Wprowadź adres WWW i spróbuj ponownie.",
	unexpecified_conversion_error_title:"Błąd nie jest określony.",
	unexpecified_conversion_error_content:"Serwer zwrócił nieokreślony błąd.",
	encrypted_conversion_error_title:"Zaszyfrowany dokument nie jest obsługiwany.",
	encrypted_conversion_error_content:"Plik jest chroniony hasłem. Aby wyświetlić go w przeglądarce, należy go wcześniej zdeszyfrować.",
	service_busy_title:"Otwieranie dokumentu nie powiodło się",
	service_busy_content:"Nie można otworzyć pliku, który ma zostać wyświetlony. Serwer może być zajęty lub niedostępny. Spróbuj ponownie później lub skontaktuj się z administratorem.",
	empty_doc_title: "Dokument jest pusty.",
	empty_doc_content: "Wybierz dokument zawierający treść i spróbuj ponownie.",
	corrupted_doc_title: "Nie można otworzyć pliku.",
	corrupted_doc_content: "Plik zawiera nieobsługiwaną zawartość (np. makra) i dlatego nie można go wyświetlić w tej aplikacji.",
	draft_storage_error_title: "Nie można otworzyć dokumentu.",
	draft_storage_error_content: "Nie można załadować treści, ponieważ jest ona uszkodzona. Skontaktuj się z administratorem, aby uzyskać wsparcie.",
	unexpected_code_title: "Serwer ${productName} zwrócił nieoczekiwany kod.",
	unexpected_code_content: "Serwer ${productName} zwrócił nieoczekiwany kod.",
	request_time_out_title: "Przekroczono limit czasu ładowania dokumentu.",
	request_time_out_content: "Ładowanie dokumentu trwa zbyt długo. Spróbuj ponownie później.",
	problem_id_msg_title: "Zgłoś ten problem administratorowi. ",
	problem_id_msg_show: "Kliknij, aby wyświetlić szczegóły",
	problem_id_msg_hide: "Kliknij, aby ukryć"
})

