/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2014. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        spreadsheetTemplates: "Szablony arkuszy kalkulacyjnych",
        documentTemplates: "Szablony dokumentów",
        titleShareDocument: "Współużytkowanie dokumentu",
        offline: "Niepołączony",
        versionPublishing: "Trwa publikowanie wersji.",
        versionPublishFailed: "Wersja nie została opublikowana. Być może plik jest zbyt duży lub serwer przekroczył limit czasu. Spróbuj ponownie lub anuluj i poproś administratora o sprawdzenie dziennika serwera w celu zidentyfikowania problemu.",
        versionCheckinFailed: "Wersja nie została wprowadzona do biblioteki. Być może plik jest zbyt duży lub serwer przekroczył limit czasu. Spróbuj ponownie lub anuluj i poproś administratora o sprawdzenie dziennika serwera w celu zidentyfikowania problemu.",
        versionSavedFailed: "Zapis nie doszedł do skutku. Spróbuj zapisać później.",
        publishFileSizeExceedMsg: "Nie można opublikować pliku, ponieważ jego wielkość przekracza maksymalną dozwoloną wielkość ustawioną przez administratora repozytorium. Usuń część treści, aby plik był mniejszy, lub skontaktuj się z administratorem w celu zmiany ograniczenia wielkości.",
        checkinFileSizeExceedMsg: "Nie można wprowadzić pliku do biblioteki, ponieważ jego wielkość przekracza maksymalną wielkość ustawioną przez administratora repozytorium. Usuń część treści, aby plik był mniejszy, lub skontaktuj się z administratorem w celu zmiany ograniczenia wielkości.",
        versionpublished: "Wersja została opublikowana przez użytkownika ${0} o ${1}.",
        versionPublishing2: "Zapisywanie wersji.",
        versionPublishFailed2: "Nie zapisano wersji. Być może plik jest zbyt duży lub serwer przekroczył limit czasu. Spróbuj ponownie lub anuluj i poproś administratora o sprawdzenie dziennika serwera w celu zidentyfikowania problemu.",      
        publishFileSizeExceedMsg2: "Nie można zapisać pliku, ponieważ jego wielkość przekracza maksymalną dozwoloną wielkość ustawioną przez administratora repozytorium. Usuń część treści, aby plik był mniejszy, lub skontaktuj się z administratorem w celu zmiany ograniczenia wielkości.",
        versionpublished2: "Wersja została zapisana przez użytkownika ${0} o ${1}.",
        chekinCloseDocsMsg: "Produkt ${productName} można teraz zamknąć.",
        draftSavingAs: "Kopiowanie pliku...",
        draftSavedAs: "Nowa kopia została zapisana jako ${0}.",
        synchronizing: "Poczekaj, aż zostanie zakończona operacja synchronizacji z serwerem.",
        synchronizeError: "Nie można zakończyć operacji synchronizacji z serwerem.",
        joinwithoutentitle: "Następujący użytkownicy: ${0} chcą edytować dokument, ale nie mogą dołączyć do sesji edycji, ponieważ bieżący użytkownik nie jest uprawniony do współedytowania.",
        joinwithoutentitle2: "Następujący użytkownicy: ${0} chcą edytować dokument, ale nie mogą dołączyć do sesji edycji, ponieważ nie są uprawnieni do współedytowania.",
        backtoFiles: "Otwórz komponent Moje pliki",
        backtoCommFiles: "Otwórz pliki społeczności",
        backtoLibrary: "Otwórz bibliotekę",
        backtoICN: "Otwórz nawigator treści",
        backtoRepository: "Otwórz listę plików",
        createNewSpred: "Utwórz arkusz kalkulacyjny",
        createNewDoc: "Utwórz dokument",
        createNewDocFromTemp: "Utwórz dokument na podstawie szablonu",
        shareDoc: "Udostępnianie dokumentu do współużytkowania",
        exportPdf: "Ustawienia strony",
        insertDate: "Wybór daty",
        insertTime: "Wybór godziny",
        connect: "Połącz",
        theDoc: "dokument",
        save: "Zapisz zmiany",
        saveBeforeReviewMsg: "Istnieją niezapisane zmiany. Zapisz zmiany i ponownie wyślij do przeglądu.",
        submitReviewWidgetsFaiure: "Ta aplikacja nie została poprawnie zainicjowana. Wyślij ponownie do przeglądu później.",
        widgetsFaiure: "Ta aplikacja nie została poprawnie zainicjowana.",
        slideSorter: "Slajdy",
        commentsBar: "Komentarze",
        draftBadge: "WERSJA ROBOCZA",
        share: "Współużytkuj",
        comment: "Komentarz",
        showSidebar: "Pokaż pasek boczny",
        publishVersion: "Publikuj",
        checkInVersion: "Wprowadź do biblioteki",
        saveVersion: "Zapisz",
        saved: "Zapisano wszystkie zmiany",
        saving: "Zapisywanie",
        submitFragment: "Wyślij",
        aria_inMainMenu: "Znajdujesz się w menu głównym",
        aria_inSlideSorter: "Znajdujesz się w widoku modułu sortowania slajdów",
        aria_inSlideEditor: "Znajdujesz się w widoku edytora slajdów",
        createNewPres: "Utwórz prezentację",
        createNewAppFromTemp: "Utwórz dokument na podstawie szablonu",
        textdoc: "tekst",
        sheetdoc: "arkusz kalkulacyjny",
        presdoc: "prezentacja",
        saveAsTextErrMsg: "Nie można zapisać nowego dokumentu tekstowego.",
        saveAsPresErrMsg: "Nie można zapisać nowego dokumentu prezentacji.",
        saveAsSheetErrMsg: "Nie można zapisać nowego dokumentu arkusza kalkulacyjnego.",
        saveAsTextErrMsg1: "Za mało miejsca do zapisania dokumentu.",
        saveAsPresErrMsg1: "Za mało miejsca do zapisania prezentacji.",
        saveAsSheetErrMsg1: "Za mało miejsca do zapisania arkusza kalkulacyjnego.",
        newDocTextErrMsg: "Nie można utworzyć nowego dokumentu tekstowego.",
        newDocSheetErrMsg: "Nie można utworzyć nowego dokumentu arkusza kalkulacyjnego.",
        newDocPresErrMsg: "Nie można utworzyć nowego dokumentu prezentacji.",
        newDocTextErrMsg2: "Nie można utworzyć nowego dokumentu tekstowego z szablonu.",
        newDocSheetErrMsg2: "Nie można utworzyć nowego dokumentu arkusza kalkulacyjnego z szablonu.",
        newDocPresErrMsg2: "Nie można utworzyć nowego dokumentu prezentacji z szablonu.",
        newDocTextErrMsg3: "Za mało miejsca do utworzenia dokumentu.",
        newDocSheetErrMsg3: "Za mało miejsca do utworzenia arkusza kalkulacyjnego.",
        newDocPresErrMsg3: "Za mało miejsca do utworzenia prezentacji.",
        newDocTextErrMsg4: "Już istnieje dokument o tym tytule. Podaj inny tytuł nowego dokumentu.",
        newDocSheetErrMsg4: "Już istnieje arkusz kalkulacyjny o tym tytule. Podaj inny tytuł nowego arkusza kalkulacyjnego.",
        newDocPresErrMsg4: "Już istnieje prezentacja o tym tytule. Podaj inny tytuł nowej prezentacji.",        
        aclWarningTitle: "Nie można edytować nowej wersji",
        aclWarningMsg: "Właściciel pliku skonfigurował chronione obszary w tym pliku, najlepiej zatem edytować go tylko w sieci. Skontaktuj się z właścicielem pliku (${0}), jeśli naprawdę chcesz przesłać nową wersję.",
        aclWarningMsgForOwner: "W tym pliku istnieją chronione obszary. Nie będzie można edytować przesłanej nowej wersji w trybie z połączeniem.  Należy usunąć wszystkie chronione obszary w tym pliku, aby można było otwierać i edytować przesłaną nową wersję.",
        st0: "Arkusz1",
        st1: "Arkusz2",
        st2: "Arkusz3",
        FootnoteMsg: "Strona",
        conflictMsg: "Występuje konflikt z elementami zmienianymi przez innych edytujących.  Wprowadzona zmiana zostanie unieważniona.",
        undoRedoConflictMsg: "Operacje cofania i ponawiania zostały zawieszone ze względu na konflikt między tym, co edytujesz, i tym, nad czym pracuje inna osoba w trybie współedytowania.",
        bigFileErrMsg: "Dokument jest zbyt duży. Odśwież przeglądarkę, aby sprawdzić, czy treść jest nienaruszona.",
        noPermissionMsg: "Nie masz uprawnień do edytowania tego pliku. Skontaktuj się z właścicielem pliku, aby uzyskać uprawnienia do edycji, i spróbuj ponownie.",
        networkIssueMsg: "Występuje problem związany z siecią.",
        networkIssueTitle: "Problem związany z siecią",
        networkIssueContent: "Występuje problem związany z siecią. Odśwież stronę i spróbuj ponownie nawiązać połączenie.",
        lockEditorMsg: "Dokumentu nie można edytować do czasu uzyskania połączenia z serwerem.",
        offlineReasonMsg: "Przekroczono limit czasu sesji.",
        offlineReasonForServerUnacceptedMsg: "Nie można przetworzyć niektórych działań. W ciągu 1 minuty działania zostaną odrzucone przez serwer Docs.",
        offlineReasonForServerDraftFormatChange: "Format dokumentu jest nieaktualny z powodu aktualizacji serwera.",
        reloadExplanationMsg: "Zaloguj się ponownie, aby kontynuować pracę.",
        reloadBtnLabel: "Przeładuj",
        reconnectingMsg: "Poczekaj na nawiązanie połączenia z serwerem.",
        loadMsg: "Poczekaj na załadowanie dokumentu.",
        loadingDocumentMsg: "Poczekaj na załadowanie dokumentu z serwera.",
        reLoadingDocumentMsg: "Poczekaj na ponowne załadowanie dokumentu z serwera.",
        unsupportMsg: "Wykryto nieobsługiwaną opcję. Przeczytaj więcej szczegółowych informacji na ten temat.",
        browserWorkingMsg: "Przetwarzanie...",
        fileDeepDetectTitle: "Format pliku i rozszerzenie nazwy pliku nie są zgodne",
        fileDeepDetectMsg: "Format pliku nie jest tym samym formatem, co format wskazany przez rozszerzenie pliku. Kliknij przycisk Kontynuuj, aby edytować plik w tym formacie.",
        fileDeepDetectOkLabel: "Kontynuuj",
        tipInfo: "Wskazówka: ${0}",
        selectTextInfo: "Wybierz tekst, do którego ma być zastosowany styl.",
        removeRecentFile: "Plik, który chcesz otworzyć, został usunięty. Czy usunąć nazwę tego pliku z listy ostatnio otwieranych plików?",
        altLotusIcon: "",
        altErrorMsgIcon: "Komunikat o błędzie",
        altWarningMsgIcon: "Komunikat ostrzegawczy",
        altSuccessMsgIcon: "Komunikat o powodzeniu",
        sidebarLandmarkDesc: "pasek boczny",
        footerTitle: "stopka",
        mainDesc: "obszar strony",
        editLockedDocumentWarning: "Zablokowano plik, gdy inni użytkownicy go edytowali. Skontaktuj się z tymi użytkownikami, aby skoordynować zmiany, lub poproś ich o zakończenie edytowania, aby uzyskać wyłączny dostęp z uprawnieniami do edycji.",
        observerMode: "Jesteś w trybie obserwatora",
        editorMode: "Jesteś w trybie edytującego",
        maxEditorLimitReached: "Osiągnięto maksymalną liczbę edytujących dokument (${0}) dla tej sesji. Gdy edytujący opuści dokument lub przełączy się do trybu obserwatora, możesz przełączyć się do trybu edytującego.",
        maxEditorLimitReachedTitle: "Osiągnięto maksymalną liczbę edytujących",
        uploadNewVersionOpenConfirm: "Użytkownik ${0} przesłał nową wersję ${2} o ${1}. Czy chcesz otworzyć nową wersję?", //${0} name, ${1} time, ${2} date
        uploadNewVersionPublishConfirm: "Użytkownik ${0} przesłał nową wersję ${2} o ${1}. ", //${0} name, ${1} time, ${2} date
        you: "Ty",
        today: "dzisiaj",
        yesterday: "wczoraj",
        slideShowInviteMsg: "Użytkownik ${0} zainicjował współużytkowany pokaz slajdów. Czy chcesz dołączyć?",
        slideShowInviteTitle: "Zaproszenie do współużytkowanego pokazu slajdów",
        slideShowInviteTitle1: "Zaproszenie do wspólnego pokazu slajdów",
        slideShowCoviewSelectUsersTitle: "Współużytkowany pokaz slajdów",
        slideShowCoviewSelectUsersTitle1: "Wspólny pokaz slajdów",
        slideShowCoviewStmt: "Udostępnij do współużytkowania prezentację w obecnym stanie we współużytkowanym pokazie slajdów.",
        slideShowCoviewStmt1: "Udostępnij do współużytkowania prezentację w obecnym stanie we wspólnym pokazie slajdów.",
        slideShowCoviewOptionOne: "Zaproś wszystkich edytujących, aby dołączyli do pokazu slajdów.",
        slideShowCoviewOptionOne1: "Zaproś wszystkich edytujących i obserwatorów, aby dołączyli do pokazu slajdów.",
        slideShowCoviewOptionTwo: "Zaproś tylko następujących edytujących, aby dołączyli do pokazu slajdów.",
        slideShowCoviewOptionTwo1: "Zaproś tylko następujących edytujących i obserwatorów, aby dołączyli do pokazu slajdów.",
        slideShowCoviewSlidesOf: "Slajd ${0} z ${1}",  //as in Slide 1 of 4
        slideShowCoviewViewers: "${0} - osoby przeglądające",
        slideShowCoviewDialogInput: "Wpisz tekst, aby filtrować nazwę",
        slideShowCoviewAddTitle: "Dodaj do współużytkowanego pokazu slajdów",
        slideShowCoviewAddTitle1: "Dodaj do wspólnego pokazu slajdów",
        slideShowCoviewMessage: "Wybierz dodatkowych użytkowników, aby ich zaprosić do tego współużytkowanego pokazu slajdów.",
        slideShowCoviewMessage1: "Wybierz dodatkowych użytkowników, aby ich zaprosić do tego wspólnego pokazu slajdów.",
        slideShowCoviewEnded: "Zakończono współużytkowany pokaz slajdów",
        slideShowCoviewEndMessage: "Współużytkowany pokaz slajdów, do którego próbujesz dołączyć, jest już niedostępny.",
        slideShowCoviewEndMessage2: "Użytkownik ${0} zakończył współużytkowany pokaz slajdów.",
        slideShowWarning: "Musisz zamknąć bieżący pokaz slajdów przed rozpoczęciem nowego.",
        slideShowHoverMsg: "Kliknij, aby zobaczyć, kto jeszcze ogląda pokaz slajdów.",
        slideShowHoverMsgAdd: "Kliknij, aby zaprosić kolejne osoby przeglądające.",
        csvEmpty: "Nie można wyeksportować arkusza jako pliku CSV, ponieważ nie zawiera on żadnych danych.",
        edit: "Edytuj",
        printToPDF: "Pobierz jako plik PDF",
        print: "Drukuj",
        view: "Wyświetl",
        openLatestFile: "Otwórz najnowszy plik",
        updateDocument: "Dokument został zaktualizowany. ${0}.",
        updateSpreadsheet: "Arkusz kalkulacyjny został zaktualizowany. ${0}.",
        updatePresentation: "Prezentacja została zaktualizowana.${0}.",
        labelCancel: "Anuluj",
        msgConversionFail: "Konwersja nie powiodła się",
        updateNow: "Otwórz teraz",
        fileUpdated: "Zaktualizowano dokument",
        fileUpdatedContent1: "Dokument został zaktualizowany. Zanim go wydrukujesz, otwórz najnowszy plik.",
        htmlviewerlimitation1: "Ten arkusz zawiera tabelę przestawną, której nie można wyświetlić",
        htmlviewerlimitation2: "Ten arkusz zawiera formatowanie warunkowe, którego nie można wyświetlić",
        htmlviewerlimitation3: "Ten arkusz zawiera tabelę przestawną i formatowanie warunkowe, których nie można wyświetlić",
        close: "Zamknij",
        closeDocs: "Zamknij produkt ${productName}",
        endSessionDlgTitle: "Sesja edycji została zakończona",
        endSessionDlgNotice: "Sesja edycji została zakończona, ponieważ użytkownik ${0} wprowadził plik do biblioteki.",
        labelStopReview: "Przerwij przegląd",
        labelRejct: "Odrzuć",
        labelApprove: "Zatwierdź",
        errorMsg: "Błąd",
        labelItemNotFountTitle: "Nie można wykonać działania.",
        labelItemNotFountMsg: "Inny członek społeczności już podjął działanie w odniesieniu do tego dokumentu. Aby uzyskać więcej informacji na ten temat, zamknij dokument i przejdź do strony Szczegóły pliku w swojej bibliotece.",
        viewProtectedAreas: "Ten arkusz kalkulacyjny zawiera chronione obszary. Należy go wyświetlać i edytować tylko w sieci.",
        macroTitle: "Plik zawiera makro", 
        macroDesc: "Edytowanie tego pliku może uszkodzić makro. Aby uniemożliwić użytkownikom edycję zakresu lub arkusza zawierającego makro, użyj opcji Dane > Obszary chronione.",
        problem_id_msg_title: "Zgłoś ten problem administratorowi. ",
        problem_id_msg_show: "Kliknij, aby wyświetlić szczegóły",
    	problem_id_msg_hide: "Kliknij, aby ukryć",
    	uploadNewVersionWarningTitle: "Nie można edytować nowej wersji",
        changeHistoryWarningMsg: "Właściciel pliku włączył śledzenie zmian w tym pliku, więc najlepiej edytować go w sieci. Skontaktuj się z właścicielem pliku (${0}), jeśli naprawdę chcesz przesłać nową wersję.",
        changeHistoryWarningMsgForOwner: "Ten plik zawiera historię zmian. Nie będzie można edytować przesłanej nowej wersji w trybie z połączeniem.  Należy wyczyścić historię zmian i wyłączyć śledzenie zmian w tym pliku, aby można było otwierać i edytować przesłaną nową wersję.",
        viewChangeHistory: "Ten dokument zawiera historię zmian. Należy go wyświetlać i edytować tylko w sieci.",
    	contentCorruptErrMsg: "Nie można załadować treści, ponieważ jest ona uszkodzona. Skontaktuj się z administratorem, aby uzyskać wsparcie."
});

