/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_concord_viewer_services_fileUtil_FileLocker */

#ifndef _Included_com_ibm_concord_viewer_services_fileUtil_WinFileLocker
#define _Included_com_ibm_concord_viewer_services_fileUtil_WinFileLocker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_concord_viewer_services_fileUtil_WinFileLocker
 * Method:    lock
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_concord_viewer_services_fileUtil_WinFileLocker_lock
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ibm_concord_viewer_services_fileUtil_WinFileLocker
 * Method:    unlock
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_concord_viewer_services_fileUtil_WinFileLocker_unlock
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
