({
	service_unavailable_title: "De service is niet beschikbaar.",
	service_unavailable_content: "De service ${productName} is niet beschikbaar en uw opdracht kan op dit moment niet worden verwerkt. Probeer het later opnieuw, of vraag uw systeembeheerder om te controleren of de service ${productName} online is.",
	access_denied_title: "De toegang is geweigerd.",
	viewaccess_denied_content: "U bent niet gemachtigd om dit bestand te bekijken. Het bestand moet openbaar worden gemaakt of met u worden gedeeld.",
	editaccess_denied_content: "U bent niet gemachtigd om dit bestand te bewerken. Het bestand moet met u worden gedeeld of u moet beschikken over editortoegang tot dit bestand.",
	doc_notfound_title: "De service ${productName} kan het bestand niet vinden.",
	doc_notfound_content: "Informeer bij uw systeembeheerder of de service ${productName} juist is geconfigureerd.",
	fullviewer_notsupport_title: "Document is niet gevonden",
	fullviewer_notsupport_content: "Een nieuwe bestandsviewer slaat het document op onder een andere URL. Als u het document wilt bekijken, kunt u het opzoeken in uw toepassing en op de knop Preview klikken.",
	fileconnect_denied_title: "De verbinding is geweigerd.",
	fileconnect_denied_content: "${productName} kan geen verbinding maken met de bestandsrepository. Probeer het later opnieuw of neem contact op met de systeembeheerder.",
	convservice_unavailable_title: "De conversieservice is niet beschikbaar.",
	convservice_unavailable_content: "Uw opdracht kan op dit moment niet worden verwerkt. Probeer het later opnieuw, of vraag uw systeembeheerder om te controleren of de conversieservice online is.",
	doc_toolarge_title: "Het bestand is te groot.",
	doc_toolarge_content: "Het document dat u zoekt is te groot.",
	doc_toolarge_content2: "Het bestand kan niet worden geopend, want",
	doc_toolarge_content3: "Het bestand kan niet worden weergegeven, want het is groter dan ${0} kB. U kunt het bestand wel downloaden en dan bekijken. Als het bestand afbeeldingen met hoge resolutie bevat, kunt u deze vervangen door afbeeldingen met een lagere resolutie om het bestand minder groot te maken.",
	doc_toolarge_content4: "Het bestand ${0} kan niet worden weergegeven, want het is groter dan ${1} kB.",
	doc_toolarge_content5: "Het bestand is te groot om hier te bekijken, maar u kunt het nog wel openen door op de knop voor downloaden op de titelbalk te klikken.",
	edit_locked_file: "Het bestand kan niet worden bewerkt, want het is vergrendeld door andere editors.",
	sheet_toolarge_content: "De spreadsheet is groter dan ${0} kB.",
	sheet_toolarge_content2: "De spreadsheet bevat meer dan ${0} rijen op een enkel werkblad.",
	sheet_toolarge_content5: "De spreadsheet bevat meer dan ${0} kolommen op een enkel werkblad.",
	sheet_toolarge_content3: "De spreadsheet bevat meer dan ${0} cellen.",
	sheet_toolarge_content4: "De spreadsheet bevat meer dan ${0} formules.",
	text_toolarge_content: "Het document is groter dan ${0} kB.",
	text_toolarge_content2:"Het document bevat meer dan ${0} pagina's.",
	text_toolarge_content3:"De tekst van het document is groter dan ${0} kB.",
	pres_toolarge_content: "De presentatie is groter dan ${0} kB.",
	pres_toolarge_content2: "De presentatie bevat meer dan ${0} pagina's.",
	pres_toolarge_content3: "De presentatie bevat meer dan ${0} afbeeldingen.",
	pdf_toolarge_content: "Het pdf-bestand is groter dan ${0} kB.",
	conversion_timeout_title: "Er is een timeout op getreden voor de documentconversie.",
	conversion_timeout_content: "De conversie van het document duurt te lang voor dit moment. Probeer het later opnieuw.",
	invalid_docformat_title: "De inhoud van het document is ongeldig.",
	invalid_docformat_content: "De bestandsextensie van het document is geldig, maar de inhoud kan niet worden gelezen.  Controleer of het bestand beschadigd is. ",
	invalid_doctype_title: "Het documenttype wordt niet ondersteund.",
	invalid_doctype_content: "Het documenttype wordt op dit moment niet ondersteund door ${productName}.",
	malformed_request_title: "De URL of de parameters zijn onjuist.",
	malformed_request_content: "Controleer de waarden van de URL en de parameters.",
	storageserver_error_title: "De opslagserver is niet beschikbaar.",
	storageserver_error_content: "De server is nu niet beschikbaar. Uw opdracht kan op dit moment niet worden verwerkt. Probeer het later opnieuw, of vraag uw systeembeheerder om te controleren of de opslagservice online is.",
	incorrect_web_address_title:"Onjuist webadres.",
	incorrect_web_address_content:"Het webadres is onjuist.  Geef het goede adres op en probeer het opnieuw.",
	unexpecified_conversion_error_title:"De fout is onbekend.",
	unexpecified_conversion_error_content:"De server heeft een onbekende fout geretourneerd.",
	encrypted_conversion_error_title:"Documenten die zijn versleuteld met CryptoAPI RC4 worden niet ondersteund.",
	encrypted_conversion_error_content:"Het bestand is met een wachtwoord beveiligd. Als u het bestand in ${productName} wilt bekijken, moet het eerst worden gedecodeerd.",
	document_encrypt_title:"Het document is versleuteld.",
	document_encrypt_content:"U kunt het bestand niet bekijken, want het was versleuteld toen het is geüpload naar Bestanden.",
	service_busy_title:"Het document kan niet worden geopend.",
	service_busy_content:"Het bestand dat u wilt bekijken, kan niet worden geopend. Mogelijk is de server bezig of niet beschikbaar. Probeer het later opnieuw of neem contact op met de beheerder.",
	empty_doc_title: "Het document is leeg.",
	empty_doc_content: "Zorg dat het document content bevat en probeer het opnieuw.",
	corrupted_doc_title: "Het bestand kan niet worden geopend.",
	corrupted_doc_content: "Het bestand bevat niet-ondersteunde content, zoals macro's, en kan daarom niet in deze toepassing worden bekeken.",
	draft_storage_error_title: "Document kan niet worden geopend.",
	draft_storage_error_content: "Content kan niet worden geladen omdat deze beschadigd is. Neem voor ondersteuning contact op met de beheerder.",
	unexpected_code_title: "Document kan niet worden bekeken",
	unexpected_code_content: "De ${docsProductName}-server is mogelijk down. Probeer het later opnieuw.",
	unpublished_document_title: "Bestand kan niet worden bekeken",
	unpublished_document_content: "Er is geen gepubliceerde versie van dit bestand beschikbaar.  U kunt een bestand pas bekijken nadat de eigenaar een versie heeft gepubliceerd.",
	unscanned_document_title: "Virusscan wordt voltooid",
	unscanned_document_content: "Er wordt automatisch een virusscan uitgevoerd op bestanden die worden geüpload naar Connections. Wanneer de virusscan is voltooid, kunt u dit bestand bekijken.",
	malicious_document_title: "Kwaadaardig bestand",
	malicious_document_content: "U kunt dit bestand niet bekijken, omdat Connections bij het scannen een virus heeft gevonden.",		
	repository_out_of_space_title: "Onvoldoende ruimte",
	repository_out_of_space_content: "${0} kan niet worden gepubliceerd, want uw bestandsquota zijn bereikt. Verklein de gebruikte ruimte door andere bestanden naar de prullenbak te verplaatsen en dan te wissen.",
	pdf_error_title:"Het bestand kan niet worden geopend.",
	pdf_error_content:"Mogelijk is het PDF-bestand beschadigd.",
	problem_id_msg_title: "Meld het probleem aan de beheerder. ",
	problem_id_msg_show: "Klik om details af te beelden",
	problem_id_msg_hide: "Klik om te verbergen"
})

