({
	stViewClient:"Sametime İstemcisini Göster",
	stChatList:"Yeni bir pencerede Sametime Web istemcisini açmak için tıklatın.",
	stWebClient:"HCL Sametime ",
	stStatusMeeting:"Toplantıda",
	stStatusAvailable:"Uygun",
	stViewBd:"Sametime Arkadaş Listesini Göster",
	stErrorSTServer:"Sametime'a bağlanırken hata oluştu",
	stStatusAway:"Dışarıda",
	stLConnLogIn:"Sametime durumunu görüntülemek için HCL Connections oturumu açın",
	stActionBar:"Sametime İşlem Çubuğu",
	stStatusBusy:"Meşgul",
	stLogin:"Sametime oturumu aç",
	stUserOffline:"Çevrimdışı",
	stStartChat:"Sohbet başlatmak için burayı tıklatın",
	stLogout:"Sametime oturumunu kapat",
	stDisconnect:"Sametime'dan çık",
	stViewSTActions:"Sametime işlemlerini görüntülemek için tıklatın",
	stError:"Hata oluştu. Sametime hizmeti kullanılamıyor.",
	stUnableToConnect:"Sametime bağlantısı kullanılamıyor.",
	stConnect:"Sametime'a bağlan",
	stNoStatuAvailable:"Sametime durumu yok",
	stStatusdnt:"Rahatsız Etmeyin",
	stLoadingSTStatus:"Sametime durumu yükleniyor...",
	stShareAs:"Belge Paylaş...",
	stShareDlgTitle:"Sametime ile Belge Paylaş...",
	stShareDlgMsgTemplate:"Düzenleyici ya da Okur olarak ${contact_name} ile ${file_name} dosyasını paylaşmak istiyor musunuz?",
	stShareEditor:"Düzenleyici",
	stShareReader:"Okur",
	stShareSuccessTemplate:"${contact_name}, '${file_name}' adlı dosyayı sizinle paylaşmak istiyorum:\n<a href=\"${document_link}\">${document_link}</a>"
})
