({
	labelNormal: "Tampilan Normal",
	labelPlay: "Putar Slide Show",
	labelZoomIn: "Perbesar",
	labelZoomOut: "Perkecil",
	labelFitWidth: "Sesuaikan dengan Lebar",
	labelReset: "Atur ulang",
	lablePageUp: "Halaman Sebelumnya",
	lablePageDown: "Halaman Berikutnya",
	labelPrint: "Cetak",
	labelBuild: "${productName} ${0}",
	labelVersion: "${productName} ${0} ${1}",
	msgLoading: "Tunggulah dokumen Anda dimuat.",
	msgConversionFail: "Konversi Gagal",
	labelReload: "Muat Ulang",
	labelHelpContent:"Konten Bantuan",
	labelAbout:"Tentang",
	labelProject:"${productName}",
	labelEdit: "Edit",
	labelHelp: "Bantuan",
	labelCancel: "Batal",
	labelImageTypeIcon: "Dokumen",
	errPrintBeforeLoading: "Untuk mencetak, Anda tidak dapat menggunakan menu di browser. Klik tombol toolbar Cetak untuk mencetak dokumen. Anda tidak dapat mencetak sekarang, karena konten belum selesai dimuat.",
	errPrintFromBrowserMenu: "Untuk mencetak dokumen, klik tombol Cetak pada toolbar, bukan menu cetak di browser.",
	errPrintConversionFail: "Anda tidak dapat mencetak karena konten gagal dikonversi.",
	successMsg:"Berhasil",
	warningMsg:"Peringatan",
	errorMsg:"Kesalahan",
	backtofiles:"Kembali ke File",
	openLatestFile: "Buka file terbaru",
	updatePresentation:"Presentasi diperbarui.${0} untuk melihat semua teks dan gambar",
	updateNow: "Buka Sekarang",
	fileUpdated: "Presentasi diperbarui",
	fileUpdatedContent1: "Presentasi diperbarui. Buka file terbaru sebelum Anda mencetak.",
	fileUpdatedContent2: "Presentasi diperbarui. Buka file terbaru sebelum Anda memutar slide show.",
	htmlviewerlimitation: "Presentasi ini berisi animasi yang tidak dapat ditampilkan",
	labelStopReview: "Hentikan Peninjauan",
	labelRejct: "Tolak",
	labelApprove: "Terima",
	labelItemNotFountTitle: "Tidak dapat menyelesaikan tindakan.",
	labelItemNotFountMsg: "Salah satu anggota komunitas telah melakukan tindakan pada dokumen ini. Untuk informasi lebih lanjut, tutup dokumen dan pergi ke halaman Rincian File di pustaka Anda."
})

