({
	COLUMN: "Pylväskaavio",
	CLUSTERED_COLUMN: "Ryvästetyt pylväät",
	STACKED_COLUMN: "Pinotut pylväät",
	BAR:"Palkkikaavio",
	CLUSTERED_BAR:"Ryvästetyt palkit",
	STACKED_BAR: "Pinotut palkit",
	PIE:"Ympyräkaavio",
	SLICE: "Sektori",
	AREA: "Aluekaavio",
	STACKED_AREA: "Pinotut alueet",
	LINE: "Viivakaavio",
	STACKED_LINE: "Pinotut viivat",
	MAKER_LINE: "Merkitty viiva",
	STACKED_MARKER_LINE: "Pinotut merkityt viivat",
	SCATTER: "Pistekaavio",
	SCATTER_MARKER_ONLY: "Vain merkityt pisteet",
	SCATTER_MARKER_LINE_S: "Merkityt pisteet ja pyöristetyt viivat",
	SCATTER_LINE_S: "Pisteet ja pyöristetyt viivat", 
	SCATTER_MARKER_LINE_X: "Merkityt pisteet ja suorat viivat",
	SCATTER_LINE_X: "Pisteet ja suorat viivat",
	ERROR_INVALID_RANGE:"Virheellinen tietoalue",
	TOO_MANY_POINTS: "Sellaisen kaavion luonti ei onnistu, jossa on enemmän kuin ${0} tietopistettä",
	CHART_TYPES:"Kaaviolajit",
	DATA:"Tiedot",
	DATA_RANGE:"Tietoalue",
	IN_ROWS:"Arvosarjat riveissä",
	IN_COLUMNS:"Arvosarjat sarakkeissa",
	AUTO:"Automaattinen"
})
