({
	alt			: "Vaihtoehtoinen teksti:",
	width		: "Leveys:",
	height		: "Korkeus:",
	cmUnit   : " cm",
	ptUnit 	 : " pt",
	inchUnit : "tuuma",
	inUnit   : "in",
	mmUnit 	 : " mm",
	
	inputWarning: "Anna oletusyksikön mukainen positiivinen luku. ",
	
	properties: "Ominaisuudet",
	data: "Tiedot",
	chart: "Kaavio",
	axis: "Akseli",
	series: "Sarja",
	font: "Fontti",
	title: "Otsikko",
	legend: "Nimiö",
	placement: "Sijoittelu",
	background: "Tausta",
	plotarea: "Kaavioalue",
	line : "Viivakaavio",
	fill: "Täyttö",
	border : "Reuna",
	labelfont: "Nimiö",
	scale: "Skaala",
	minimum: "Pienin mahdollinen",
	maximum: "Suurin mahdollinen",
	majorunit: "Pääyksikkö",
	minorunit: "Aliyksikkö",
	smooth: "Tasoita",
	marker: "Merkit",
	markerfill: "Merkki",
	enterTitle: "Kirjoita otsikko tähän",
	inputNumberWarning: "Anna luku.",
	inputPosNumberWarning: "Anna positiivinen luku.",
	maxMinWarning: "Enimmäisarvon täytyy olla suurempi kuin vähimmäisarvon",
	selectFontName: "Valitse fontin nimi",
	selectFontSize: "Valitse fonttikoko",
	setBold: "Lihavointi",
	setItalic: "Kursivointi",
	setFontColor: "Määritä fontin väri",
	setLegendPos: "Aseta selitteen sijainti",
	setBackColor: "Aseta taustan väri",
	setBorderWidth: "Aseta reunan leveys",
	setBorderColor: "Aseta reunan väri",
	setPlotAreaColor: "Aseta piirtoalueen väri",
	selectAxis: "Valitse akseli",
	setLineWidth: "Aseta viivan leveys",
	setLineColor: "Aseta viivan väri",
	selectSeries: "Valitse sarja",
	setFillColor: "Aseta täytön väri",
	setMarker: "Aseta merkit",
	setSmooth: "Aseta tasoitettu viiva",
	chartTitle: "Kaavion otsikko",
	axisTitle: "Akselin otsikko",
	
	ERR1: "Matriisin täytyy olla aaltosulkeissa.",
	ERR3: "Komentosarjan kohteiden täytyy olla lainausmerkeissä.",
	ERR4: "Anna vain yksi alue.",
	ERR5: "Alue on annettava.",
	ERR6: "Kaikkien alueiden täytyy olla samassa laskentataulukossa.",
	ERR7: "Kaikkien alueiden täytyy olla yksittäisiä rivejä tai sarakkeita.",
	ERR9: "Sarjan arvo on pakollinen.",
	
	n	: "Ei mitään",
	l	: "Vasemmalle",
	r	: "Oikealle",
	t	: "Yläreuna",
	b   : "Alareuna",
	
	dataSeries:"Arvosarja",
	label:"Sarjan nimi",
	xVal:"Sarjan X-arvot",
	yVal:"Sarjan Y-arvot",
	val:"Sarjan arvot",
	cat:"Luokka",
		
	ltr: "Vasemmalta oikealle",
	rtl: "Oikealta vasemmalle",
	auto: "Kontekstin mukainen",
	bidi_dir: "Suunta",
	bidi_text_dir: "Tekstin suunta"
})
