({
	labelPrintConfig: "Chcete-li dosáhnout nejlepších možných výsledků tisku, nastavte vzhled stránky prohlížeče následujícím způsobem: ",
	labelConfigPageSize: "Velikost stránky: ${0}",
	labelConfigOrientation: "Orientace: ${0}",
	labelConfigHeader: "Záhlaví: prázdné",
	labelConfigFooter: "Zápatí: prázdné",
	labelConfigMargins: "Okraje: ",
	labelConfigMarginTop: "Nahoře: ${0} ${1}",
	labelConfigMarginBottom: "Dole: ${0} ${1}",
	labelConfigMarginLeft: "Vlevo: ${0} ${1}",
	labelConfigMarginRight: "Vpravo: ${0} ${1}",
	labelPrintContinue: "Po nastavení prohlížeče pokračujte v tisku souboru klepnutím na tlačítko OK. ",
	labelMm: "mm",
	labelInch: "in",
	labelPortrait: "Na výšku",
	labelPageA4: "A4",
	labelLetter: "Letter",
	labelLandscape: "Na šířku",
	titlePrintConfig: "Nastavení tisku",
	titlePrepare: "Příprava na tisk",
	msgPrepare: "Probíhá příprava souboru na tisk. Příprava může trvat delší dobu. ",
	errPrepare: "Během přípravy dat došlo k chybě. \nChcete pokus zopakovat? ",
	titleErr: "Chyba",
	btnRetry: "Opakovat"
})
