-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- IBM Docs Source Materials                                         
--                                                                   
-- (c) Copyright IBM Corporation 2012. All Rights Reserved.          
--                                                                   
-- U.S. Government Users Restricted Rights: Use, duplication or      
-- disclosure restricted by GSA ADP Schedule Contract with IBM Corp. 
--                                                                   
-- ***************************************************************** 


CREATE DATABASE CONCORD USING CODESET UTF-8 TERRITORY US@
	CONNECT TO CONCORD@
	CREATE SCHEMA CONCORDDB@
	CONNECT RESET@



CONNECT TO CONCORD@
CREATE BUFFERPOOL "CONCORDBUFFER"  SIZE 250 PAGESIZE 32768@
CONNECT RESET@

CONNECT TO CONCORD@
CREATE  LARGE  TABLESPACE "CONCORDNAMESPACE" PAGESIZE 32 K  MANAGED BY AUTOMATIC STORAGE EXTENTSIZE 16 OVERHEAD 10.5 PREFETCHSIZE 16 TRANSFERRATE 0.14 BUFFERPOOL  CONCORDBUFFER @
CONNECT RESET@

------------------------------------
-- TABLESPACES --
------------------------------------
CONNECT TO CONCORD@
CREATE LARGE TABLESPACE "SYSTOOLSPACE" IN DATABASE PARTITION GROUP IBMCATGROUP 
	 PAGESIZE 4096 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 32 M 
	 MAXSIZE NONE 
	 EXTENTSIZE 4
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL IBMDEFAULTBP
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON@


CREATE USER TEMPORARY TABLESPACE "SYSTOOLSTMPSPACE" IN DATABASE PARTITION GROUP IBMCATGROUP 
	 PAGESIZE 4096 MANAGED BY AUTOMATIC STORAGE 
	 EXTENTSIZE 4
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL IBMDEFAULTBP
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY OFF@


-- 

ALTER TABLESPACE SYSCATSPACE
      PREFETCHSIZE AUTOMATIC
      OVERHEAD 7.500000
      NO FILE SYSTEM CACHING 
      AUTORESIZE YES 
      TRANSFERRATE 0.060000@


ALTER TABLESPACE TEMPSPACE1
      PREFETCHSIZE AUTOMATIC
      OVERHEAD 7.500000
      FILE SYSTEM CACHING 
      TRANSFERRATE 0.060000@


ALTER TABLESPACE USERSPACE1
      PREFETCHSIZE AUTOMATIC
      OVERHEAD 7.500000
      NO FILE SYSTEM CACHING 
      AUTORESIZE YES 
      TRANSFERRATE 0.060000@


-- userpreference			
CREATE TABLE "CONCORDDB"."USERPREFERENCE"  (
		  "ID" VARCHAR(2048) NOT NULL , 
		  "ORGID" VARCHAR(256),
		  "PREFERENCE" BLOB(4096) LOGGED NOT COMPACT ,
		  PRIMARY KEY("ID"))   
		 IN "CONCORDNAMESPACE" @

CREATE TABLE "CONCORDDB"."DOCEDITORS" (
	"REPOID" VARCHAR(2048) NOT NULL,
	"DOCID" VARCHAR(2048) NOT NULL,
	"USERID" VARCHAR(2048) NOT NULL,
	"ORGID" VARCHAR(2048) NOT NULL,
	"DISPLAYNAME" VARCHAR(2048),
	"COLOR" VARCHAR(64)
) IN "CONCORDNAMESPACE" @

CREATE TABLE "CONCORDDB"."DOC_ACTIVITY" (
	"REPO_ID" VARCHAR(256) NOT NULL,
	"URI" VARCHAR(256) NOT NULL,
	"ACTIVITY_ID" VARCHAR(256) NOT NULL,
	"ORGID" VARCHAR(256) NOT NULL,
	"CREATEDBY" VARCHAR(256) NOT NULL,
	"CREATIONDATE" TIMESTAMP,
	PRIMARY KEY("REPO_ID", "URI"))
	IN "CONCORDNAMESPACE" @

--repo_id(string) uri(string) org_id (string), user_id (string) activity_id(string) creationdate (string)
CREATE TABLE "CONCORDDB"."DOC_REFERENCE" (
	"PARENT_REPO" VARCHAR(256) NOT NULL,
	"PARENT_URI" VARCHAR(256) NOT NULL,
	"CHILD_REPO" VARCHAR(256) NOT NULL,
	"CHILD_URI" VARCHAR(256) NOT NULL,
	"ORGID" VARCHAR(256),
	"CREATEDBY" VARCHAR(256),
	"CREATIONDATE" TIMESTAMP,
	PRIMARY KEY("PARENT_REPO", "PARENT_URI", "CHILD_REPO", "CHILD_URI"))
	IN "CONCORDNAMESPACE" @
--parent_repo (string) parent_uri (string) child_repo (string) child_uri (string) org_id(string) user_id (string) creationdate (timestamp)
-- clipboard			
CREATE TABLE "CONCORDDB"."CLIPBOARD"  (
		  "ID" VARCHAR(2048) NOT NULL , 
		  "USERID" VARCHAR (2048)  NOT NULL ,
		  "ORGID" VARCHAR(256),
		  "USEREMAIL" VARCHAR (1024) ,
		  "TAG" VARCHAR (1024) ,
		  "PROVIDERS" VARCHAR (2048) ,
		  "CLIPDATA" VARCHAR (20480) ,
		  "LASTMODIFICATIONDATE" TIMESTAMP ,
		  PRIMARY KEY("ID"))   
		 IN "CONCORDNAMESPACE" @
			

COMMIT WORK@

CONNECT RESET@

TERMINATE@

@
