-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- IBM Docs Source Materials                                         
--                                                                   
-- (c) Copyright IBM Corporation 2016. All Rights Reserved.          
--                                                                   
-- U.S. Government Users Restricted Rights: Use, duplication or      
-- disclosure restricted by GSA ADP Schedule Contract with IBM Corp. 
--                                                                   
-- ***************************************************************** 

CONNECT TO CONCORD@

CREATE TABLE "CONCORDDB"."DOCUMENTMETA"
(
	"REPOID" VARCHAR(256) NOT NULL,
	"DOCID" VARCHAR(256) NOT NULL,
	"ORGID" VARCHAR(128) NOT NULL,
	"SYNCSTATE" INTEGER NOT NULL,
	"LAST_VISIT" TIMESTAMP NOT NULL,
	"LAST_MODIFIED" TIMESTAMP NOT NULL,
	"LAST_MODIFIER_ID" VARCHAR(256) NOT NULL,
	"CREATED" TIMESTAMP NOT NULL,
	"BASE_VERSION" VARCHAR(16) NOT NULL,
	"MIME" VARCHAR(128) NOT NULL,
	"TITLE" VARCHAR(256) NOT NULL,
	"EXT" VARCHAR(32) NOT NULL,
	"FORMAT_VER" VARCHAR(16),
	"REMOTE_LAST_MODIFIED" TIMESTAMP NOT NULL,
	"BASE_CONTENT_HASH" VARCHAR(1024) NOT NULL,
	
	PRIMARY KEY("REPOID", "DOCID")
)	IN "CONCORDNAMESPACE"@

CREATE INDEX "CONCORDDB"."DOCUMENTMETA_LASTVISIT_INDEX" ON "CONCORDDB"."DOCUMENTMETA" ("LAST_VISIT") @
CREATE INDEX "CONCORDDB"."DOCUMENTMETA_MIME_FORMAT_VER_INDEX" ON "CONCORDDB"."DOCUMENTMETA" ("MIME", "FORMAT_VER") CLUSTER @

CREATE TABLE "CONCORDDB"."SNAPSHOTMETA"
(
	"REPOID" VARCHAR(256) NOT NULL,
	"DOCID" VARCHAR(256) NOT NULL,
	"ORGID" VARCHAR(128) NOT NULL,
	"LAST_VISIT" TIMESTAMP NOT NULL,
	"CREATED" TIMESTAMP NOT NULL,
	"MIME" VARCHAR(128) NOT NULL,
	"FORMAT_VER" VARCHAR(16),
	"REMOTE_LAST_MODIFIED" TIMESTAMP NOT NULL,
	
	PRIMARY KEY("REPOID", "DOCID")
)	IN "CONCORDNAMESPACE"@

CREATE INDEX "CONCORDDB"."SNAPSHOTMETA_LASTVISIT_INDEX" ON "CONCORDDB"."SNAPSHOTMETA" ("LAST_VISIT") @
CREATE INDEX "CONCORDDB"."SNAPSHOTMETA_MIME_FORMAT_VER_INDEX" ON "CONCORDDB"."SNAPSHOTMETA" ("MIME", "FORMAT_VER") CLUSTER @

CREATE TABLE "CONCORDDB"."UPLOADMETA"
(
	"REPOID" VARCHAR(256) NOT NULL,
	"DOCID" VARCHAR(256) NOT NULL,
	"ORGID" VARCHAR(128) NOT NULL,
	"CREATED" TIMESTAMP NOT NULL,
	"MIME" VARCHAR(128) NOT NULL,
	"FORMAT_VER" VARCHAR(16),
	
	PRIMARY KEY("REPOID", "DOCID")
)	IN "CONCORDNAMESPACE"@

CREATE INDEX "CONCORDDB"."UPLOADMETA_LASTVISIT_INDEX" ON "CONCORDDB"."UPLOADMETA" ("CREATED") @
CREATE INDEX "CONCORDDB"."UPLOADMETA_MIME_FORMAT_VER_INDEX" ON "CONCORDDB"."UPLOADMETA" ("MIME", "FORMAT_VER") CLUSTER @


ALTER TABLE CONCORDDB.SUBSCRIBER DROP PRIMARY KEY @
ALTER TABLE CONCORDDB.SUBSCRIBER ADD CONSTRAINT SUBSCRIBER_PK PRIMARY KEY ( ID, TYPE, CUSTOMER_ID) @
ALTER TABLE "CONCORDDB"."SUBSCRIBER" ADD COLUMN "VISITOR" SMALLINT @
REORG TABLE "CONCORDDB"."SUBSCRIBER" @

COMMIT WORK@
CONNECT RESET@
