({	
	viewExpandedBtn: "Weniger Antworten anzeigen",
	viewCollapsedBtn: "${0} weitere Antworten anzeigen",
	placeholderMsg: "Geben Sie hier Ihre Nachricht ein",
	sure: "Möchten Sie diesen Kommentar wirklich löschen?",
	exceed: "Der Kommentar ist zu lang.\n Der eingefügte Kommentar überschreitet die maximale Länge.\n Verkürzen Sie ihn auf nicht mehr als ${0} Zeichen und klicken Sie auf Hinzufügen.",
	remainLabelHint:"Ihr Kommentar hat die maximal zulässige Länge von 500 Zeichen erreicht.",
	tipsCommentField: "Geben Sie einen Kommentar für alle Editoren oder für einen Editor ein.",
	tipsRespondField: "Geben Sie eine Antwort für alle Editoren oder für einen Editor ein.",	
	resolveBtn: "Erledigen",	
	replyBtn: "Antworten",
	saveBtn: "Veröffentlichen",
	deleteBtn: "Löschen",
	cancelBtn: "Abbrechen",
	reopenBtn: "Erneut öffnen",
	todayAt: "Heute um ${time}",
	yesterdayAt: "Gestern um ${time}",
	dateAt: "${date} um ${time}",
	mentions: "Wählen Sie einen zu erwähnenden Benutzer aus",
	noMentions: "Leerzeichen antippen, um die Eingabe zu beenden",
	nocomments: "Das Dokument \"${0}\" enthält keine Kommentare.",
	
	newComments:"Neue Kommentare",
	mentiontomesomebody:"Unbekannt",
	mentiontome:"${0} hat Sie in einem Kommentar erwähnt",
	
	newcommentsnumber:"Die Anzahl der ungelesenen Kommentare",
	jawsnewcommentsnumber: "Die Anzahl der ungelesenen Kommentare ist ",
	jawsnactivecommentsnumber: "Die Anzahl der aktiven Kommentare ist ",
	
	activenum:"Die Anzahl der aktiven Kommentare",
	filterDesc:"Kommentare filtern",
	menuallcomments:"Alle Kommentare",
	menutome: "An mich",
	menubyme: "Von mir",
	menuactive: "Aktiv",
	menuresolved: "Erledigt",
	searchDesc: "Kommentare suchen",
	search: "Suchen",
	closeDesc: "Suche schließen",
	clear: "Löschen",
	warnEnterKeywords: "Geben Sie einen Suchbegriff ein.",
	nocommentstome: "Im Dokument \"${0}\" sind momentan keine Kommentare oder Antworten enthalten, die mich erwähnen",
	nocommentsbyme: "Im Dokument \"${0}\" sind momentan keine Kommentare oder Antworten von mir enthalten",
	nocommentsar: "Derzeit sind keine Kommentare der Kategorie \"${0}\" im Dokument \"${1}\" enthalten.",
	nosearchedcomments: "Derzeit sind keine Kommentare oder Antworten mit \"${0}\" in der Kategorie \"${1}\" im Dokument \"${2}\" enthalten.",
	
	prevBtn: "Zurück",
	nextBtn: "Weiter",
	mentionHint:"Zeigt ${0} bis ${1} Übereinstimmungen von insgesamt ${2} an",
		
	resolveFlag: "Aufgelöste Kommentare",
	jawsCommentHint: "${authorname} hat einen Kommentar veröffentlicht ${timestamp}",
	jawsReplyHint: "${authorname} hat eine Antwort veröffentlicht ${timestamp}",
	jawsContentHint: "Der Inhalt lautet ${content}",
	jawsCommentStatusHint: "Der Status ist ${status}",
	jawsCommentKeyHint: "Sie können zum Zurückkehren zum Dokument die Eingabetaste oder die Leertaste drücken, um den vollständigen Kommentarthread anzuzeigen und Kommentare zu lösen, beantworten oder zu löschen.",
	jawsMentionHint: "Das Erwähnungs-Widget in Docs. Sie können den Aufwärts- oder Abwärtspfeil verwenden, um einen zu erwähnenden Benutzer auszuwählen",
	jawsMentionSelected: "Drücken Sie zum Erwähnen die Eingabe- oder die Leertaste",
	commentDeletedMsg: "Der aktuelle Kommentar wurde von einem anderen Benutzer gelöscht.",
	commentResolvedMsg: "Der aktuelle Kommentar wurde gelöst.",
	warningCommentMsg: "Kommentare innerhalb von Docs für ${0}-Dateien werden nur online unterstützt. Die Verlinkung 'Kommentare' wird entfernt, wenn eine neue Version zur Bearbeitung hochgeladen wird.",
	orphanCommentTip: "Die Kommentarverlinkung wurde in dieser hochgeladenen Version entfernt.",
	warningCommentName: "Warnung"
})

