({
	stViewClient:"Sametime-ügyfél megjelenítése",
	stChatList:"Kattintson ide a Sametime webes ügyfél megnyitásához új ablakban.",
	stWebClient:"HCL Sametime ",
	stStatusMeeting:"Találkozón vagyok",
	stStatusAvailable:"Elérhető vagyok",
	stViewBd:"Sametime partnerlista megjelenítése",
	stErrorSTServer:"Hiba történt a csatlakozáskor a Sametime alkalmazáshoz",
	stStatusAway:"Távol vagyok",
	stLConnLogIn:"Jelentkezzen be az HCL Connections alkalmazásba a Sametime állapot megtekintéséhez",
	stActionBar:"Sametime műveletsáv",
	stStatusBusy:"Elfoglalt vagyok",
	stLogin:"Bejelentkezés a Sametime alkalmazásba",
	stUserOffline:"Offline vagyok",
	stStartChat:"Kattintson ide csevegés indításához",
	stLogout:"Kijelentkezés a Sametime alkalmazásból",
	stDisconnect:"A Sametime kapcsolat bontása",
	stViewSTActions:"Kattintson ide a Sametime műveletek megtekintéséhez",
	stError:"Hiba történt. A Sametime szolgáltatás nem elérhető.",
	stUnableToConnect:"A csatlakozás a Sametime alkalmazáshoz nem elérhető. ",
	stConnect:"Csatlakozás a Sametime alkalmazáshoz",
	stNoStatuAvailable:"Nem áll rendelkezésre Sametime állapot",
	stStatusdnt:"Ne zavarjanak",
	stLoadingSTStatus:"Sametime állapot betöltése...",
	stShareAs:"Dokumentum megosztása...",
	stShareDlgTitle:"Dokumentum megosztása a Sametime szolgáltatáson keresztül...",
	stShareDlgMsgTemplate:"Szerkesztőként vagy olvasóként kívánja megosztani a '${file_name}' fájlt a(z) ${contact_name} nevű felhasználóval?",
	stShareEditor:"Szerkesztő",
	stShareReader:"Olvasó",
	stShareSuccessTemplate:"${contact_name}, szeretném megosztani a(z) '${file_name}' nevű dokumentumot:\n<a href=\"${document_link}\">${document_link}</a>"
})
