/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
	fileMenu: "Датотека",
	fileMenu_New: "Ново",
	fileMenu_NewDocument: "Документ",
	fileMenu_NewDocumentfromTemplate: "Документ од шаблон",
	fileMenu_NewPresentation: "Презентација",
	fileMenu_NewPresentationfromTemplate: "Презентација од шаблон",
	fileMenu_NewSpreadsheet: "Пресметковен лист",
	fileMenu_Open: "Отвори",
//	fileMenu_Close: "Close",
	fileMenu_Discard: "Отфрли",
	fileMenu_Save: "Зачувај",
//	fileMenu_SaveAs: "Save As...",
//	fileMenu_SaveAsDraft: "as Draft",
//	fileMenu_SaveInMyDocs: "in My Documents",
//	fileMenu_SaveToSymphony: "to Lotus Symphany",
	fileMenu_ShareWith: "Сподели со...	",
	fileMenu_ExportAsPDF: "Извези како PDF",
	fileMenu_WebPreview: "Преглед на веб",
	fileMenu_PrintPreview: "Преглед пред печатење",
	fileMenu_RecentFile: "Најнови датотеки",
	fileMenu_Print: "Печати...",
	editMenu: "Уреди",
	editMenu_Undo: "Врати",
	editMenu_Redo: "Повтори",
	editMenu_Cut: "Отсечи",
	editMenu_Copy: "Копирај",
	editMenu_Paste: "Залепи",
	editMenu_DeleteSlide:"Избриши слајд",
	editMenu_SelectAll: "Избери ги сите",
	editMenu_Find: "Најди...",
	editMenu_Replace: "Замени...",
	editMenu_DeleteSheet: "Избриши лист",
	editMenu_DuplicateSheet: "Дуплирај лист",
	editMenu_DeleteRow: "Избриши ред",
	editMenu_DeleteColumn: "Избриши колона",
	editMenu_ClearCell: "Исчисти ќелија",
	viewMenu: "Прикажи",
	viewMenu_Master: "Главен",
	viewMenu_Notifications: "Известувања",
	viewMenu_ShowHideIndicators: "Прикажи/сокриј показатели на заедничко уредување",
	viewMenu_SlideSorter: "Прикажи сортирање слајдови",
	viewMenu_SpeakerNotes: "Прикажи белешки на говорникот",
	viewMenu_NextSlide: "Нареден слајд",
	viewMenu_PrevSlide: "Претходен слајд",
	createMenu: "Создај",
	createMenu_NewSlide: "Нов слајд",
	createMenu_DuplicateSlide: "Дуплирај слајд",
	createMenu_ImageFromFile: "Графика од датотека",
	createMenu_TextBox: "Текстуално поле",
	createMenu_Task: "Задача",
    formatMenu_Text_Direction: "Насока на текст",
    formatMenu_Ltr: "Од лево надесно",
    formatMenu_Rtl: "Од десно налево",  	
    formatMenu_Horizontal_Align: "Порамни хоризонтално",
    formatMenu_Vertical_Align: "Порамни вертикално",
    formatMenu_Align_Top: "Врв",
    formatMenu_Align_Middle: "Средина",
    formatMenu_Align_Bottom: "Дно",
	layoutMenu: "Распоред",
	layoutMenu_SlideLayout: "Распоред на слајдови",
	layoutMenu_SlideDesign: "Главни слајдови",
	tableMenu: "Табела",
	tableMenu_CreateTable: "Создај табела",
	tableMenu_Cell: "Ќелија",
	tableMenu_CellAlignLeft: "Порамни текст налево",
	tableMenu_CellAlignCenter: "Порамни текст централно",
	tableMenu_CellAlignRight: "Порамни текст надесно",
	tableMenu_CellClearContents: "Исчисти содржина",
	tableMenu_Row: "Ред",
	tableMenu_RowAddRowAbove: "Додај ред над",
	tableMenu_RowAddRowBelow: "Додај ред под",
	tableMenu_RowMoveRowAbove: "Премести ред над",
	tableMenu_RowMoveRowBelow: "Премести ред под",
	tableMenu_RowDelete: "Избриши",
	tableMenu_ColumnAddColumnBefore: "Додај колона пред",
	tableMenu_ColumnAddColumnAfter: "Додај колона после",
	tableMenu_ColumnMoveColumnAfter: "Премести колона после",
	tableMenu_ColumnMoveColumnBefore: "Премести колона пред",
	tableMenu_ColumnDelete: "Избриши",
	tableMenu_ColumnSortAscending: "Сортирај по нагорен редослед",
	tableMenu_ColumnSortDescending: "Сортирај по надолен редослед",
	tableMenu_Column: "Колона",
	tableMenu_Delete: "Избриши",
	presentationMenu: "Презентација",
	presentationMenu_SlideShow: "Пушти приказ на слајд",
	presentationMenu_SlideShowFromCurrent: "Пушти од тековен слајд",
	toolsMenu: "Алатки",
	toolsMenu_Task: "Задача",
	helpMenu: "Помош",
	helpMenu_Overview: "Содржина на Помош"
})

