({
	ORIENTATION_LABEL: "Yönlendirme",
	PORTRAIT: "Dikey",
	LANDSCAPE: "Yatay",
	PAGE_LABEL: "Sayfa düzeni",
	PAGE_TYPE1: "Yukarıdan aşağı, sonra sağa",
	PAGE_TYPE2: "Soldan sağa, sonra aşağı",
	DISPLAY_OPTION_LABEL: "Görüntü seçenekleri",
	HEADER: "Üstbilgi",
	FOOTER: "Altbilgi",
	GRIDLINE: "Kılavuz çizgiler",
	TAGGED_PDF: "Etiketlenmiş PDF",
	MARGINS_LABEL: "Kenar boşlukları",
	TOP: "Üst:",
	TOP_DESC:"Üst kenar boşluğu (santimetre)",
	TOP_DESC2:"Üst kenar boşluğu (inç)",
	BOTTOM: "Alt:",
	BOTTOM_DESC:"Alt kenar boşluğu (santimetre)",
	BOTTOM_DESC2:"Alt kenar boşluğu (inç)",	
	LEFT: "Sol:",
	LEFT_DESC:"Sol kenar boşluğu (santimetre)",
	LEFT_DESC2:"Sol kenar boşluğu (inç)",	
	RIGHT: "Sağ:",
	RIGHT_DESC:"Sağ kenar boşluğu (santimetre)",
	RIGHT_DESC2:"Sağ kenar boşluğu (inç)",	
	PAPER_FORMAT_LABEL: "Kağıt biçimi",
	PAPER_SIZE_LABEL: "Kağıt boyutu:",
	HEIGHT: "Yükseklik:",
	HEIGHT_DESC:"Kağıt yüksekliği (santimetre)",
	HEIGHT_DESC2:"Kağıt yüksekliği (inç)",		
	WIDTH: "Genişlik:",
	WIDTH_DESC:"Kağıt genişliği (santimetre)",
	WIDTH_DESC2:"Kağıt genişliği (inç)",
	
	INVALID_MSG: "Giriş geçersiz ve otomatik olarak düzeltildi. Farklı bir sonuç istiyorsanız başka bir değer deneyin.",
	
	TOOLTIP1:"Kağıdın uzunluğu kadar satır yazdırır, sayfada başka sütun kalmayıncaya kadar çapraz olarak hareket eder, daha sonra bir sonraki satır grubunu yazdırmak üzere aşağıya ve sola doğru hareket eder.",
	TOOLTIP2:"Kağıdın genişliği kadar sütun yazdırır, sayfada başka satır kalmayıncaya kadar aşağıya doğru hareket eder, daha sonra bir sonraki sütun grubunu yazdırmak üzere yukarıya ve sağa doğru hareket eder.",
	CM_LABEL: "cm",
	LETTER: "Mektup",
	LEGAL: "Yasal",
	TABLOID: "Tabloid",
	USER: "Kullanıcı",
	SIZE1: "Zarf. No.6 3/4",
	SIZE2: "Zarf. Monarch",
	SIZE3: "Zarf. No.9",
	SIZE4: "Zarf. No.10",
	SIZE5: "Zarf. No.11",
	SIZE6: "Zarf. No.12",
	SIZE7: "16 kai",
	SIZE8: "32 kai",
	SIZE9: "32 kai genişliğinde"
})
	
