({
	delete_general: "Ştergere",
	order: "Ordine",
	align_text: "Aliniere text",
	align_slide: "Aliniere în diapozitiv",
	align_objects: "Aliniere obiecte selectate",
	zoom: "Panoramare",
	zoom_fit: "Potrivire în fereastră",
	insert_link: "Inserare legătură",
	add_link: "Adăugare legătură",
	open_link: "Deschidere legătură",
	edit_link: "Editare legătură",
	remove_link: "Înlăturare legătură",
	insert_link_menu: "Legătură",
	invalid_url: "Nu s-a putut deschide URL-ul. Verificaţi dacă URL-ul este corect sau verificaţi setarea de blocare ferestre pop-up a browser-ului. ",
	dnd_canceled_on_slide_event: "Diapozitivul nu poate fi mutat deoarece un alt editor a modificat recent prezentarea. Încercaţi din nou mai târziu.",
	rotate: "Rotire",
	flipX: "Inversare orizontală",
	flipY: "Inversare verticală",
	rotate_right: "Rotire în sensul acelor de ceas 90&#x00B0",
	rotate_left: "Rotire în sensul invers acelor de ceas 90&#x00B0",
	color_set_fill: "Setare culoare de umplere",
	color_nofill: "Nicio umplere",
	color_nobackground: "Fără fundal",
	color_auto: "Automată",
	color_default: "Implicită",
	color_transparent: "Transparentă",
	
	objects_distribute: "Distribuire",
	objects_distribute_v: "Verticală",
	objects_distribute_h: "Orizontală",
	
	link_subject: "Subiect :",
	link_text: "Text e afişat:",
	link_mailto: "Deschidere e-mail",
	link_goto: "Deschidere legătură",
	link_done: "Gata",
	link_remove: "Înlăturare",
	link_website: "Site web",
	link_email: "E-mail",
	link_slide: "Cadru",
	link_slide_placeholder: "Selectaţi sau introduceţi un număr",
	link_slide_placeholder_deleted: "Diapozitiv legat şters",
	link_slide_next: "Cadru următor",
	link_slide_prev: "Cadru anterior",
	link_slide_first: "Primul diapozitiv",
	link_slide_last: "Ultimul diapozitiv",
	link_slide_number: "Diapozitivul ${0}",
	link_not_support: "Tip de legătură nesuportat",
	link_acc_input: "Adresă legătură de intrare",
	link_acc_mail_input: "Adresă poştă de intrare",
	

	// Jaws Support
	acc_blank: "blanc",// when selection is nothing but space char and empty paragraph
	acc_selected: " selectat",
	acc_showed: " arătat",
	acc_inTable: " în tabel rândul ${0} coloana ${1} ",
	acc_titleSelected: "titlu selectat",
	acc_subtitleSelected: "subtitlu selectat",
	acc_outlineSelected: "contur selectat",
	acc_notesSelected: "note de vorbire selectate",
	acc_imageSelected: "grafică selectată",
	acc_shapeSelected: "formă selectată",
	acc_rotated: " rotit ${0} grade",
	acc_tableSelected: "tabel selectat",
	acc_textboxSelected: "casetă de text selectată",
	acc_enterEdit: " apăsaţi enter pentru editare",
	acc_locked_by: " care este blocat de utilizatorul ${0}",
	acc_slide_used_by: " care este folosit de utilizatorul ${0}",
	ACC_TABLE_TABLESIZE: "Aţi selectat ${0} rânduri, ${1} coloane",
	ACC_TABLE_MAXSIZE: " Dimensiunea maximă a tabelului suportată este de 8*8",
	ACC_EditorMode: "mod de editare editor",
	ACC_EndEditorMode: "oprire mod de editare editor",
	ACC_Table_new_row: "Este adăugat un rând nou",
	ACC_Table_new_column: "Este adăugată o coloană nouă",
	Acc_column: "coloana  ${0}",
	acc_slide: "diapozitiv ${0}",
	acc_editor: "Editare de ${0}",
	Plain: "Simplu",
	BlueStyle: "Stil albastru",
	RedTint: "Tentă roşie",
	BlueHeader: "Antet albastru",
	DarkGrayHF: "Antet/Subsol gri închis",
	LightGrayRows: "Rânduri gri deschis",
	DarkGrayRows: "Rânduri gri închis",
	BlueTint: "Tentă albastră",
	RedHeader: "Antet roşu",
	GreenHF: "Antet/subsol verde",
	PlainRows: "Rânduri simple",
	GrayTint: "Tentă gri",
	GreenTint: "Tentă verde",
	GreenHeader: "Antet verde",
	RedHF: "Antet/Subsol roşu",
	GreenStyle: "Stil verde",
	PurpleTint: "Tentă mov",
	BlackHeader: "Antet negru",
	PurpleHeader: "Antet mov",
	LightBlueHF: "Antet/Subsol albastru deschis",
	
    formatMenu_LineSpacing: "Spaţiere linie",
	linespaceboxTitle:"Spaţiere personalizată",
	linespacelineTitle:"Linie:",
	linespacenoticeContent :"Spaţiere linie",
    formatMenu_LineSpacing_Customize: "Personalizare...",
    formatMenu_LineSpacing_CustomValue:"Personalizare: ${0}",
    lineSpaceWarning:"Introduceţi un număr de la 0 la 10",
    
    set_transparency_menu: "Opacitate imagine",
    opacity_percent_value: "${0}%",
    opacity_title: "Opacitate",
    
    increaseLineWidthTip: "Creşteţi grosimea liniei",
	decreaseLineWidthTip : "Descreşteţi grosimea liniei",
    setBorderStyleTip:"Setaţi stilul liniei",
    line_width_title: "Grosime linie",
    line_end_title: "Puncte finale linie",
    line_dash_title: "Model linie",
    line_dash_type1: "Solidă",
    line_dash_type2: "Puncte pătrate",
    line_dash_type3: "Liniuţe",
    line_dash_type4: "Puncte rotunde",
    line_dash_type5: "Liniuţe şi puncte",
    line_dash_type6: "Liniuţe lungi",
    line_endpoints_type1: "Fără",
    line_endpoints_type2: "Săgeată dreapta simplă",
	line_endpoints_type3: "Săgeată stânga simplă",
	line_endpoints_type4: "Săgeată dublă simplă",
	line_endpoints_type5: "Săgeată dreapta umplută",
	line_endpoints_type6: "Săgeată stânga umplută",
    line_endpoints_type7: "Săgeată dublă umplută",
    line_endpoints_type8: "Cerc umplut şi săgeată",
	line_endpoints_type9: "Romb umplut şi săgeată",
	line_endpoints_type10: "Romburi umplute",
    line_endpoints_type11: "Cercuri umplute"
})

