({
	service_unavailable_title: "Služba není k dispozici.",
	service_unavailable_content: "Služba produktu ${productName} není k dispozici a požadavek nyní nelze zpracovat. Zkuste operaci zopakovat později nebo se obraťte na administrátora systému a ověřte, že je služba produktu ${productName} online.",
	access_denied_title: "Přístup je odepřen.",
	viewaccess_denied_content: "K zobrazení tohoto souboru nemáte oprávnění. Soubor musí být nejprve zveřejněn nebo s vámi musí být sdílen.",
	editaccess_denied_content: "K úpravám tohoto souboru nemáte oprávnění. Soubor s vámi musí být sdílen nebo musíte mít pro tento soubor přístup editora.",
	doc_notfound_title: "Služba produktu ${productName} nemůže soubor nalézt.",
	doc_notfound_content: "Zeptejte se administrátora, zda je služba produktu ${productName} správně nastavena.",
	fullviewer_notsupport_title: "Dokument nebyl nalezen",
	fullviewer_notsupport_content: "Nový prohlížeč souborů ukládá dokumenty na jinou adresu URL. Chcete-lil si dokument prohlédnout, soubor vyhledejte v aplikaci a klepněte na tlačítko Náhled.",
	fileconnect_denied_title: "Připojení bylo odepřeno.",
	fileconnect_denied_content: "Produkt ${productName} se nemůže připojit k úložišti souborů. Zkuste to později nebo se obraťte na administrátora systému.",
	convservice_unavailable_title: "Převodní služba není dostupná.",
	convservice_unavailable_content: "Požadavek nelze nyní zpracovat. Zkuste operaci zopakovat později nebo se obraťte na administrátora systému a ověřte, že je převodní služba online.",
	doc_toolarge_title: "Soubor je příliš velký.",
	doc_toolarge_content: "Dokument, k němuž chcete získat přístup, je příliš velký.",
	doc_toolarge_content2: "K souboru nelze přistupovat, protože",
	doc_toolarge_content3: "Soubor nelze zobrazit, protože je větší než ${0} kB. Soubor si můžete stáhnout, a pak zobrazit. Pokud soubor obsahuje obrázky s vysokým rozlišením, můžete je nahradit obrázky s nízkým rozlišením, aby se velikost souboru zmenšila.",
	doc_toolarge_content4: "Soubor nelze zobrazit, protože velikost souboru ${0} překračuje ${1} KB.",
	doc_toolarge_content5: "Soubor je příliš veliký na to, abyste si jej mohli zde prohlédnout. Ale můžete jej otevřít klepnutím na tlačítko sloužící ke stažení, které je uvedené v pruhu titulku.",
	edit_locked_file: "Tento soubor nemůžete upravovat, protože je uzamknut jinými editory.",
	sheet_toolarge_content: "Velikost tabulky překračuje ${0} kB.",
	sheet_toolarge_content2: "Tabulka obsahuje více než ${0} řádků na jednom listu.",
	sheet_toolarge_content5: "Tabulka obsahuje více než ${0} sloupců na jednom listu.",
	sheet_toolarge_content3: "Tabulka obsahuje více než ${0} buněk.",
	sheet_toolarge_content4: "Tabulka obsahuje více než ${0} vzorců.",
	text_toolarge_content: "Velikost dokumentu překračuje ${0} kB.",
	text_toolarge_content2:"Dokument obsahuje více než ${0} stránek.",
	text_toolarge_content3:"Velikost textu v dokumentu překračuje ${0} kB.",
	pres_toolarge_content: "Velikost prezentace překračuje ${0} kB.",
	pres_toolarge_content2: "Prezentace obsahuje více než ${0} stránek.",
	pres_toolarge_content3: "Prezentace obsahuje více než ${0} obrázků.",
	pdf_toolarge_content: "Velikost souboru pdf překračuje ${0} kB.",
	conversion_timeout_title: "Vypršel časový limit pro převod dokumentu.",
	conversion_timeout_content: "Převod dokumentu nyní trvá příliš dlouho. Zkuste to později.",
	invalid_docformat_title: "Obsah dokumentu je neplatný.",
	invalid_docformat_content: "Přípona souboru dokumentu odpovídá platnému formátu, obsah souboru však není přístupný. Ověřte, že soubor není poškozen. ",
	invalid_doctype_title: "Tento typ dokumentu není podporován.",
	invalid_doctype_content: "Typ dokumentu aktuálně není podporován produktem ${productName}.",
	malformed_request_title: "Adresa URL nebo parametry jsou nesprávné.",
	malformed_request_content: "Ověřte správnost adresy URL a parametrů.",
	storageserver_error_title: "Server úložišť není k dispozici.",
	storageserver_error_content: "Server není aktuálně k dispozici. Požadavek nelze nyní zpracovat. Zkuste operaci zopakovat později nebo se obraťte na administrátora systému a ověřte, že je služba úložiště online.",
	incorrect_web_address_title:"Nesprávná webová adresa.",
	incorrect_web_address_content:"Webová adresa je nesprávná. Zadejte webovou adresu a zkuste operaci zopakovat.",
	unexpecified_conversion_error_title:"Chyba není určena.",
	unexpecified_conversion_error_content:"Server vrátil neurčenou chybu.",
	encrypted_conversion_error_title:"Šifrované dokumenty typu CryptoAPI RC4 nejsou podporovány.",
	encrypted_conversion_error_content:"Soubor je chráněn heslem. Chcete-li soubor zobrazit v produktu ${productName}, zajistěte nejprve jeho dešifrování.",
	document_encrypt_title:"Dokument je šifrován.",
	document_encrypt_content:"Soubor nelze zobrazit online, protože byl při odesílání do služby Soubory šifrován.",
	service_busy_title:"Dokument se nepodařilo otevřít.",
	service_busy_content:"Soubor, který chcete zobrazit, se nepodařilo otevřít. Je možné, že server je zaneprázdněn nebo není k dispozici. Zkuste operaci zopakovat později nebo se obraťte na administrátora.",
	empty_doc_title: "Dokument je prázdný.",
	empty_doc_content: "Ověřte, že dokument má obsah, a poté zkuste operaci zopakovat.",
	corrupted_doc_title: "Soubor nelze otevřít.",
	corrupted_doc_content: "Soubor obsahuje nepodporovaný obsah, například makra, a proto jej v této aplikaci nelze zobrazit.",
	draft_storage_error_title: "Dokument nelze otevřít.",
	draft_storage_error_content: "Obsah nelze načíst, protože je poškozen. Obraťte se na administrátora se žádostí o podporu.",
	unexpected_code_title: "Dokument nelze zobrazit.",
	unexpected_code_content: "Server ${docsProductName} je pravděpodobně nedostupný. Zkuste to později.",
	unpublished_document_title: "Soubor nelze zobrazit",
	unpublished_document_content: "Pro zobrazení není k dispozici publikovaná verze tohoto souboru. Vlastník souboru musí publikovat verzi souboru, aby bylo možné zobrazit jej.",
	unscanned_document_title: "Dokončování skenování virů",
	unscanned_document_content: "Soubory odeslané do produktu Connections se skenují automaticky. Jakmile se skenování dokončí, budete si moci soubor prohlédnout.",
	malicious_document_title: "Škodlivý soubor",
	malicious_document_content: "Soubor si nemůžete prohlédnout, protože produkt Connections během skenování zjistil virus.",		
	repository_out_of_space_title: "Nedostatek místa",
	repository_out_of_space_content: "Soubor ${0} nelze publikovat, protože jste vyčerpali přidělenou kvótu pro velikost souborů. Uvolněte kvótu přesunutím jiných souborů do koše a následným odstraněním.",
	pdf_error_title:"Soubor nelze otevřít.",
	pdf_error_content:"Soubor PDF může být poškozen.",
	problem_id_msg_title: "Nahlaste problém administrátorovi. ",
	problem_id_msg_show: "Klepnutím zobrazíte podrobnosti",
	problem_id_msg_hide: "Klepnutím je skryjete"
})

