({
	labelNormal: "Normální zobrazení",
	labelPlay: "Přehrát prezentaci",
	labelZoomIn: "Přiblížit",
	labelZoomOut: "Oddálit",
	labelFitWidth: "Přizpůsobit šířce",
	labelReset: "Resetovat",
	lablePageUp: "Předchozí stránka",
	lablePageDown: "Další stránka",
	labelPrint: "Tisk",
	labelBuild: "${productName} ${0}",
	labelVersion: "${productName} ${0} ${1}",
	msgLoading: "Čekejte, prosím, dokud se dokument nenačte.",
	msgConversionFail: "Převod se nezdařil.",
	labelReload: "Znovu načíst",
	labelHelpContent:"Obsah nápovědy",
	labelAbout:"O produktu",
	labelProject:"${productName}",
	labelEdit: "Upravit",
	labelHelp: "Nápověda",
	labelCancel: "Storno",
	labelImageTypeIcon: "Dokument",
	errPrintBeforeLoading: "Chcete-li tisknout, nelze použít nabídku v prohlížeči. Chcete-li dokument vytisknout, klepněte na tlačítko Tisk na panelu nástrojů. Nyní tisknout nelze, protože obsah není zcela načten.",
	errPrintFromBrowserMenu: "Chcete-li dokument vytisknout, klepněte na tlačítko Tisk na panelu nástrojů namísto nabídky tisku v prohlížeči.",
	errPrintConversionFail: "Nelze tisknout, protože se nepodařilo převést obsah.",
	successMsg:"Úspěch",
	warningMsg:"Varování",
	errorMsg:"Chyba",
	backtofiles:"Zpět ke službě Soubory",
	openLatestFile: "Otevřete poslední soubor",
	updatePresentation:"Prezentace byla aktualizována. ${0}, chcete-li zobrazit veškerý text a obrázky.",
	updateNow: "Otevřít nyní",
	fileUpdated: "Prezentace byla aktualizována.",
	fileUpdatedContent1: "Prezentace byla aktualizována. Před tiskem otevřete poslední soubor.",
	fileUpdatedContent2: "Prezentace byla aktualizována. Před přehráním prezentace otevřete poslední soubor.",
	htmlviewerlimitation: "Tato prezentace obsahuje animaci, kterou nelze zobrazit.",
	labelStopReview: "Zastavit revizi",
	labelRejct: "Odmítnout",
	labelApprove: "Schválit",
	labelItemNotFountTitle: "Akci nelze dokončit.",
	labelItemNotFountMsg: "Na tomto dokumentu již provádí akci jiný člen komunity. Chcete-li získat další informace, zavřete dokument a ve vaší knihovně jděte na stránku Podrobnosti o souboru."
})

