/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
    Arrow01_Gray: "Šipka 01 - šedá",
    Arrow02_Gray: "Šipka 02 - šedá",
    Arrow03_Red: "Šipka 03 - červená",
    Arrow04_Blue: "Šipka 04 - modrá",
    Arrow05_Blue: "Šipka 05 - modrá",
    Arrow06_Yellow: "Šipka 06 - žlutá",
    Arrow07_Red: "Šipka 07 - červená",
    Arrow08_Gray: "Šipka 08 - šedá",
    Arrow09_Orange: "Šipka 09 - oranžová",
    Arrow10_Blue: "Šipka 10 - modrá",
    Arrow11_Blue: "Šipka 11 - modrá",
    Arrow12_Green: "Šipka 12 - zelená",
    Arrow13_Blue: "Šipka 13 - modrá",
    Arrow14_Green: "Šipka 14 - zelená",
    Arrow15_Orange: "Šipka 15 - oranžová",
    Arrow16_Gray: "Šipka 16 - šedá",
    CircleArrow01_Green: "Kruhová šipka 01 - zelená",
    CircleArrow02_Multi: "Kruhová šipka 02 - více",
    CircleArrow03_Multi: "Kruhová šipka 03 - více",
    CircleArrow04_Multi: "Kruhová šipka 04 - více",
    CircleArrow05_Multi: "Kruhová šipka 05 - více",
    CircleArrow06_Multi: "Kruhová šipka 06 - více",
    CircleArrow07_Blue: "Kruhová šipka 07 - modrá",
    CircleArrow08_Green: "Kruhová šipka 08 - zelená",
    CircleArrow09_Multi: "Kruhová šipka 09 - více",
    CurvedArrow01_Gray: "Zakřivená šipka 01 - šedá",
    CurvedArrow02_Blue: "Zakřivená šipka 02 - modrá",
    CurvedArrow03_Blue: "Zakřivená šipka 03 - modrá",
    CurvedArrow04_Orange: "Zakřivená šipka 04 - oranžová",
    CurvedArrow05_Red: "Zakřivená šipka 05 - červená",
    CurvedArrow06_Blue: "Zakřivená šipka 06 - modrá",
    CurvedArrow07_Purple: "Zakřivená šipka 07 - nachová",
    CurvedArrow08_Green: "Zakřivená šipka 08 - zelená",
    CurvedArrow09_Gray: "Zakřivená šipka 09 - šedá",
    CurvedArrow10_Blue: "Zakřivená šipka 10 - modrá",
    CurvedArrow11_Orange: "Zakřivená šipka 11 - oranžová",
    CurvedArrow12_Blue: "Zakřivená šipka 12 - modrá",
    CurvedArrow13_Green: "Zakřivená šipka 13 - zelená",
    CurvedArrow14_Brown: "Zakřivená šipka 14 - hnědá",
    CurvedArrow15_Blue: "Zakřivená šipka 15 - modrá",
    CurvedArrow16_Gray: "Zakřivená šipka 16 - šedá",
    CurvedArrow17_Gray: "Zakřivená šipka 17 - šedá",
    CurvedArrow18_Gray: "Zakřivená šipka 18 - šedá",
    CurvedArrow19_Gray: "Zakřivená šipka 19 - šedá",
    CurvedArrow20_Gray: "Zakřivená šipka 20 - šedá",
    TrendArrow01_Red: "Šipka trendu 01 - červená",
    TrendArrow02_Green: "Šipka trendu 02 - zelená",
    TrendArrow03_Orange: "Šipka trendu 03 - oranžová",
    TrendArrow04_Red: "Šipka trendu 04 - červená",
    TrendArrow05_Orange: "Šipka trendu 05 - oranžová",
    TrendArrow06_Blue: "Šipka trendu 06 - modrá",
    TrendArrow07_Orange: "Šipka trendu 07 - oranžová",
    TrendArrow08_Yellow: "Šipka trendu 08 - žlutá",
    TrendArrow09_Blue: "Šipka trendu 09 - modrá",
    TrendArrow10_Blue: "Šipka trendu 10 - modrá",
    TrendArrow11_Blue: "Šipka trendu 11 - modrá",
    TrendArrow12_Blue: "Šipka trendu 12 - modrá",
    TrendArrow13_Red: "Šipka trendu 13 - červená",
    TrendArrow14_Multi: "Šipka trendu 14 - více",
    TrendArrow15_Blue: "Šipka trendu 15 - modrá",
    Bullet01_Circle_DarkRed: "Odrážka 01 kruh - tmavě červená",
    Bullet02_Circle_Blue: "Odrážka 02 kruh - modrá",
    Bullet03_Circle_Green: "Odrážka 03 kruh - zelená",
    Bullet04_Square_Black: "Odrážka 04 čtverec - černá",
    Bullet05_Square_Orange: "Odrážka 05 čtverec - oranžová",
    Bullet06_Square_Purple: "Odrážka 06 čtverec - nachová",
    Bullet07_Diamond_Blue: "Odrážka 07 kosočtverec - modrá",
    Bullet08_Diamond_LightBlue: "Odrážka 08 kosočtverec - světle modrá",
    Bullet09_Diamond_Red: "Odrážka 09 kosočtverec - červená",
    Bullet10_Star_Yellow: "Odrážka 10 hvězda - žlutá",
    Bullet11_Star_Blue: "Odrážka 11 hvězda - modrá",
    Bullet12_Triangle_Blue: "Odrážka 12 trojúhelník - modrá",
    Bullet13_Triangle_DarkGreen: "Odrážka 13 trojúhelník - tmavě zelená",
    Bullet14_Arrow_Red: "Odrážka 14 šipka - červená",
    Bullet15_Arrow_Blue: "Odrážka 15 šipka - modrá",
    Bullet16_Box_Blue: "Odrážka 16 krychle - modrá",
    Bullet17_Box_Red: "Odrážka 17 krychle - červená",
    Bullet18_Asterisk_LightBlue: "Odrážka 18 hvězdička - světle modrá",
    Bullet19_Leaves_Red: "Odrážka 19 listí - červená",
    Bullet20_Target_Blue: "Odrážka 20 terč - modrá",
    Bullet21_Arrow_Blue: "Odrážka 21 šipka - modrá",
    Bullet22_Arrow_DarkBlue: "Odrážka 22 šipka - tmavě modrá",
    Bullet23_Arrow_Brown: "Odrážka 23 šipka - hnědá",
    Bullet24_Flag_Red: "Odrážka 24 praporek - červená",
    Bullet25_Flag_Green: "Odrážka 25 praporek - zelená",
    Bullet26_X_Red: "Odrážka 26 X - červená",
    Bullet27_X_Black: "Odrážka 27 X - černá",
    Bullet28_Checkmark_Green: "Odrážka 28 zaškrtnutí - zelená",
    Bullet29_Checkmark_Blue: "Odrážka 29 zaškrtnutí - modrá",
    Bullet30_Square_DarkRed: "Odrážka 30 čtverec - tmavě červená",
    camera: "Fotoaparát",
    computer1: "Počítač 1",
    computer2: "Počítač 2",
    computer3: "Počítač 3",
    Computer_Cloud: "Počítač - shluk",
    Computer_Desktop: "Stolní počítač",
    Computer_Laptop_Black: "Laptop - černá",
    Computer_Laptop_Silver: "Laptop - stříbrná",
    Database: "Databáze",
    evelope: "Obálka",
    newspapers: "Noviny",
    openevelope: "Otevřená obálka",
    Server: "Server",
    speaker: "Reproduktor",
    WirelessAccessPoint: "Bezdrátový přístupový bod",
    Cycle01_Transparent: "Cyklus 01 - průhledné",
    Cycle02_Transparent_Blue: "Cyklus 02 - průhledné, modrá",
    Cycle03_Blue: "Cyklus 03 - modrá",
    Cycle04_Blue: "Cyklus 04 - modrá",
    Cycle05: "Cyklus 05",
    Cycle06: "Cyklus 06",
    Cycle07: "Cyklus 07",
    Cycle08_Blue: "Cyklus 08 - modrá",
    Cycle09_Orange: "Cyklus 09 - oranžová",
    Donut01_LightBlue: "Prstenec 01 - světle modrá",
    Donut02_Blue: "Prstenec 02 - modrá",
    Donut03_Blue: "Prstenec 03 - modrá",
    Donut04_DarkBlue: "Prstenec 04 - tmavě modrá",
    Donut05_DarkBlue: "Prstenec 05 - tmavě modrá",
    Donut06_Blue: "Prstenec 06 - modrá",
    Donut07_Blue: "Prstenec 07 - modrá",
    Graph: "Graf",
    People01_Blue: "Lidé 01 - modrá",
    People02: "Lidé 02",
    Pillars01_Orange: "Pilíře 01 - oranžová",
    Pillars02_LightBlue: "Pilíře 02 - světle modrá",
    Process01_Blue: "Proces 01 - modrá",
    Process02_Blue: "Proces 02 - modrá",
    Process03_Blue: "Proces 03 - modrá",
    Process04_GoUp_Blue: "Proces 04 – směr vzhůru, modrá",
    Process05_GoUp_Red: "Proces 05 – směr vzhůru, červená",
    Process06_GoUp_Yellow: "Proces 06 – směr vzhůru, žlutá",
    Process07_Blue: "Proces 07 - modrá",
    Pyramid01: "Pyramida 01",
    Pyramid02_Blue: "Pyramida 02 - modrá",
    Pyramid03: "Pyramida 03",
    Radial01_Green: "Radiála 01 – zelená",
    Radial02_Green: "Radiála 02 - zelená",
    Radial03_Sphere: "Radiála 03 – koule",
    Radial04_Sphere_Red: "Radiála 04 - koule, červená",
    Radial05_Sphere_Blue: "Radiála 05 – koule, modrá",
    Radial06_Arrows_DarkBlue: "Radiála 06 - šipky, tmavě modrá",
    Radial07_Arrows_DarkBlue: "Radiála 07 - šipky, tmavě modrá",
    Section_Circle: "Díly – kruh",
    Section_Cubes01: "Díly – krychle 01",
    Section_Cubes02_Blue: "Díly – krychle 02 – modrá",
    Section_Cubes03_Orange: "Díly – krychle 03 – oranžová",
    Section_Cubes04: "Díly – krychle 04",
    Section_Cubes05: "Díly – krychle 05",
    Section_Cuboids01_Blue: "Díly – kvádry 01 – modrá",
    Section_Cuboids02_Blue: "Díly – kvádry 02 – modrá",
    Section_Cuboids03: "Díly – kvádry 03",
    Section_Gears01: "Díly – ozubená kola 01",
    Section_Gears02: "Díly – ozubená kola 02",
    Section_Gears03: "Díly – ozubená kola 03",
    Section_Hexagon04_Orange: "Díly – šestiúhelníky 04 – oranžová",
    Section_Hexagons01: "Díly – šestiúhelníky 01",
    Section_Hexagons02_Blue: "Díly – šestiúhelníky 02 – modrá",
    Section_Hexagons03_Blue: "Díly – šestiúhelníky 03 – modrá",
    Section_Leaves01_LightBlue: "Díly – listy 01 – světle modrá",
    Section_Leaves02_Green: "Díly – listy 02 – zelená",
    Section_Pasters01: "Díly – nálepky 01",
    Section_Pasters02_Blue: "Díly – nálepky 02 – modrá",
    Section_Puzzle01: "Díly – puzzle 01",
    Section_Puzzle02: "Díly – puzzle 02",
    Section_Puzzle03: "Díly – puzzle 03",
    Section_Rectangles: "Díly – obdélníky",
    Section_Squares: "Díly – čtverce",
    Section_Triangle: "Díly – trojúhelník",
    Target: "Cíl",
    Venn01: "Vennův diagram 01",
    Venn02: "Vennův diagram 02",
    Venn03: "Vennův diagram 03",
    Venn04: "Vennův diagram 04",
    Venn05: "Vennův diagram 05",
    Venn06_Blue: "Vennův diagram 06 - modrá",
    Venn07_Blue: "Vennův diagram 07 - modrá",
    Venn08: "Vennův diagram 08",
    Blackboard: "Tabule",
    Books: "Knihy",
    Books1: "Knihy 1",
    books2: "Knihy 2",
    Chalk: "Křída",
    clipboard: "Psací podložka",
    clock: "Hodiny",
    Globe: "Glóbus",
    Glue: "Lepidlo",
    GraduationCap: "Baret na promoci",
    magnifyingglass: "Lupa",
    Microscope: "Mikroskop",
    Notebook: "Zápisník",
    notepad1: "Zápisník 1",
    notepad2: "Zápisník 2",
    notepad3: "Zápisník 3",
    PaperClip_Blue: "Sponka - modrá",
    PaperClip_Red: "Sponka - červená",
    Pencil: "Tužka",
    Ruler: "Pravítko",
    TestTubes: "Zkumavky",
    thumbtack: "Připínáček",
    clouds: "Mraky",
    DrippingFaucet: "Kapající kohoutek",
    Earth: "Země",
    EndangeredAnimals1: "Ohrožená zvířata 1",
    EndangeredAnimals2: "Ohrožená zvířata 2",
    GreenCar: "Zelené auto",
    GreenFactory: "Zelená továrna",
    GreenHouse: "Zelený dům",
    Leaf1: "List 1",
    Leaf2: "List 2",
    lightbulb: "Žárovka",
    LightBulb_Flourescent_Off: "Zhasnutá zářivka",
    LightBulb_Flourescent_On: "Rozsvícená zářivka",
    LightBulb_Standard_Off1: "Zhasnutá žárovka 1",
    LightBulb_Standard_Off2: "Zhasnutá žárovka 2",
    LightBulb_Standard_On: "Rozsvícená žárovka",
    lightningcloud: "Bouřkový mrak",
    Pollution_Car: "Kouřící auto",
    Pollution_Factory: "Kouřící továrna",
    Raindrop: "Kapka deště",
    RecycleBin: "Odpadkový koš",
    RecycleSymbol: "Symbol recyklace",
    RenewableEnergySymbol: "Symbol obnovitelné energie",
    RenewableEnergy_Solar: "Solární obnovitelná energie",
    RenewableEnergy_Water: "Vodní obnovitelná energie",
    RenewableEnergy_Wind: "Větrná obnovitelná energie",
    sun: "Slunce",
    Sun1: "Slunce 1",
    Sun2: "Slunce 2",
    sundandcloud: "Slunce a mrak",
    world: "Svět",
    Agreement: "Dohoda",
    ATM01: "Bankomat 01",
    ATM02: "Bankomat 02",
    Balance_Balanced1: "Váhy vyvážené 1",
    Balance_Balanced2: "Váhy vyvážené 2",
    Balance_Unbalanced1: "Váhy vychýlené 1",
    Balance_Unbalanced2: "Váhy vychýlené 2",
    Calculator: "Kalkulačka",
    Chart_Decrease1: "Graf - pokles 1",
    Chart_Decrease2: "Graf - pokles 2",
    Chart_Increase1: "Graf - nárůst 1",
    Chart_Increase2: "Graf - nárůst 2",
    Chart_Plateau: "Graf - konstanta",
    Check: "Šek",
    Contract: "Smlouva",
    CreditCard_Black: "Kreditní karta - černá",
    CreditCard_Cut: "Kreditní karta - přestřižená",
    CreditCard_Gold: "Kreditní karta - zlatá",
    Currency_Dollar: "Měna - dolar",
    Currency_Dollars: "Měna - dolary",
    Currency_Stack: "Měna – balíček",
    Currency_StackCoins: "Měna – sloupec mincí",
    GoldBar: "Zlatá cihla",
    GoldBar_Stack: "Zlatá cihla - stoh",
    MoneyBag01: "Měšec 01",
    MoneyBag02: "Měšec 02",
    PercentSign: "Procenta",
    PiggyBank01_Broken: "Prasátko 01 - rozbité",
    PiggyBank02_Broken: "Prasátko 02 - rozbité",
    PiggyBank_Coins: "Prasátko - mince",
    PiggyBank_Currency: "Prasátko - měna",
    Portfolio: "Portfolio",
    PriceTag: "Cenová visačka",
    Safe_Closed: "Zavřený sejf",
    Safe_Empty: "Prázdný sejf",
    Safe_Full: "Plný sejf",
    Seal_Gold: "Pečeť - zlatá",
    Seal_Red: "Pečeť - červená",
    Seal_Silver: "Pečeť - stříbrná",
    Wallet_Empty: "Peněženka - prázdná",
    Wallet_Full1: "Peněženka - plná 1",
    Wallet_Full2: "Peněženka - plná 2",
    BusinessPerson_Female6: "Obchodník - žena 6",
    BusinessPerson_Male3: "Obchodník - muž 3",
    Computer_User_Female1: "Uživatel počítače - žena 1",
    ConstructionWorker2: "Dělník 2",
    Presenter_Female1: "Přednášející - žena 1",
    Component_Circle01_Transparent_DarkBlue: "Komponenta kruh 01 – průhledná tmavě modrá",
    Component_Circle02_Transparent_Bule: "Komponenta kruh 02 – průhledná modrá",
    Component_Circle03_Transparent_Green: "Komponenta kruh 03 – průhledná zelená",
    Component_Circle04_Transparent_Orange: "Komponenta kruh 04 – průhledná oranžová",
    Component_Circle05_Transparent_Red: "Komponenta kruh 05 – průhledná červená",
    Component_Cube01_DarkBlue: "Komponenta krychle 01 – tmavě modrá",
    Component_Cube02_LightBlue: "Komponenta krychle 02 – světle modrá",
    Component_Cube03_Green: "Komponenta krychle 03 – zelená",
    Component_Cube04_Orange: "Komponenta krychle 04 – oranžová",
    Component_Cube05_DarkRed: "Komponenta krychle 05 – tmavě červená",
    Component_Cuboid01_DarkBlue: "Komponenta kvádr 01 – tmavě modrá",
    Component_Cuboid02_Blue: "Komponenta kvádr 02 – modrá",
    Component_Cuboid03_Green: "Komponenta kvádr 03 – zelená",
    Component_Cuboid04_Orange: "Komponenta kvádr 04 – oranžová",
    Component_Cuboid05_Red: "Komponenta kvádr 05 – červená",
    Component_Gear01_DarkBlue: "Komponenta ozubené kolo 01 – tmavě modrá",
    Component_Gear02_LightBlue: "Komponenta ozubené kolo 02 – světle modrá",
    Component_Gear03_Green: "Komponenta ozubené kolo 03 – zelená",
    Component_Gear04_DarkRed: "Komponenta ozubené kolo 04 – tmavě červená",
    Component_Gear05_Orange: "Komponenta ozubené kolo 05 – oranžová",
    Component_Person01_DarkBlue: "Komponenta postava 01 – tmavě modrá",
    Component_Person02_Blue: "Komponenta postava 02 – modrá",
    Component_Person03_Green: "Komponenta postava 03 – zelená",
    Component_Person04_DarkRed: "Komponenta postava 04 – tmavě červená",
    Component_Person05_Orange: "Komponenta postava 05 – oranžová",
    Component_PuzzlePiece01_DarkBlue: "Komponenta dílek puzzle 01 – tmavě modrá",
    Component_PuzzlePiece02_Blue: "Komponenta dílek puzzle 02 – modrá",
    Component_PuzzlePiece03_Green: "Komponenta dílek puzzle 03 – zelená",
    Component_PuzzlePiece04_Red: "Komponenta dílek puzzle 04 – červená",
    Component_PuzzlePiece05_Orange: "Komponenta dílek puzzle 05 – oranžová",
    Component_Sphere01_DarkBlue: "Komponenta koule 01 – tmavě modrá",
    Component_Sphere02_LightBlue: "Komponenta koule 02 – světle modrá",
    Component_Sphere03_Green: "Komponenta koule 03 – zelená",
    Component_Sphere04_DarkRed: "Komponenta koule 04 – tmavě červená",
    Component_Sphere05_Orange: "Komponenta koule 05 – oranžová",
    Book: "Kniha",
    Box01: "Krabice 01",
    Box02: "Krabice 02",
    Bulb01_Yellow: "Žárovka 01 – žlutá",
    Bulb02_Yellow: "Žárovka 02 – žlutá",
    Calendar: "Kalendář",
    Chart: "Graf",
    Clipboard: "Psací podložka",
    Clock: "Hodiny",
    Compass: "Kompas",
    Flag01_Red: "Praporek 01 - červená",
    Flag02_Green: "Praporek 02 - zelená",
    Flag03_Blue: "Praporek 03 - modrá",
    Gift: "Dárek",
    House: "Dům",
    Icon_Computer01_White: "Ikona počítač 01 – bílá",
    Icon_Computer02_Black: "Ikona počítač 02 – černá",
    Icon_Disk01_Blue: "Ikona disketa 01 – modrá",
    Icon_Disk02_Green: "Ikona disketa 02 – zelená",
    Icon_Document01_Grey: "Ikona dokument 01 – šedá",
    Icon_Document02_Grey: "Ikona dokument 02 – šedá",
    Icon_Document03_Blue: "Ikona dokument 03 – modrá",
    Icon_Document04_Blue: "Ikona dokument 04 – modrá",
    Icon_Envelope01_Blue: "Ikona obálka 01 – modrá",
    Icon_Envelope02_Yellow: "Ikona obálka 02 – žlutá",
    Icon_Envelope03_Open_Yellow: "Ikona obálka 03 – otevřená žlutá",
    Icon_Envelope04_Open_Yellow: "Ikona obálka 04 – otevřená žlutá",
    Icon_Folder01_Yellow: "Ikona složka 01 - žlutá",
    Icon_Folder02_Yellow: "Ikona složka 02 – žlutá",
    Icon_Folder03_Open_Yellow: "Ikona složka 03 – otevřená žlutá",
    Icon_Folder04_Open_Yellow: "Ikona složka 04 – otevřená žlutá",
    Icon_Gear01_Grey: "Ikona ozubené kolo 01 – šedá",
    Icon_Gear02_Blue: "Ikona ozubené kolo 02 – modrá",
    Icon_Network01_Blue: "Ikona síť 01 – modrá",
    Icon_Network02: "Ikona síť 02",
    Icon_Pencil01: "Ikona tužka 01",
    Icon_Pencil02: "Ikona tužka 02",
    Icon_Printer01_White: "Ikona tiskárna 01 – bílá",
    Icon_Printer02_Black: "Ikona tiskárna 02 – černá",
    Key01: "Klíč 01",
    Key02: "Klíč 02",
    Lock01_Yellow: "Zámek 01 - žlutá",
    Lock02_Yellow: "Zámek 02 - žlutá",
    Lock03_Blue: "Zámek 03 - modrá",
    Lock04_Blue: "Zámek 04 - modrá",
    Magnet: "Magnet",
    MagnifyingGlass: "Lupa",
    Medal: "Medaile",
    Notebook: "Zápisník",
    Phone: "Telefon",
    PieChart: "Výsečový graf",
    Pin: "Připínáček",
    PuzzlePiece: "Dílek puzzle",
    PuzzlePieces: "Dílky puzzle",
    Roadblock: "Zátaras",
    Scissors: "Nůžky",
    Shield01: "Štít 01",
    Shield02_Orange: "Štít 02 – oranžová",
    Shield03_Blue: "Štít 03 - modrá",
    Sign_Ban01: "Štítek zákaz 01",
    Sign_Ban02: "Štítek zákaz 02",
    Sign_CheckBox01: "Štítek zaškrtávací políčko 01",
    Sign_CheckBox02_Unchecked: "Štítek zaškrtávací políčko 02 - nezaškrtnuté",
    Sign_Checkmark01_Green: "Štítek zaškrtnutí 01 – zelená",
    Sign_Checkmark02_Green: "Štítek zaškrtnutí 02 – zelená",
    Sign_DoNotEnter: "Štítek nevstupovat",
    Sign_Error01: "Štítek chyba 01",
    Sign_Error02: "Štítek chyba 02",
    Sign_ExclamationPoint01_Red: "Štítek vykřičník 01 – červená",
    Sign_ExclamationPoint02_Orange: "Štítek vykřičník 02 – oranžová",
    Sign_Help01_Green: "Štítek nápověda 01 – zelená",
    Sign_Help02_Blue: "Štítek nápověda 02 – modrá",
    Sign_Information: "Štítek informace",
    Sign_Null: "Štítek nedefinováno",
    Sign_QuestionMark01_Blue: "Štítek otazník 01 – modrá",
    Sign_QuestionMark02_Red: "Štítek otazník 02 – červená",
    Sign_RadioButton01: "Štítek přepínač 01",
    Sign_RadioButton02_Unchecked: "Štítek přepínač 02 - vypnutý",
    Sign_Warning01_Red: "Štítek varování 01 – červená",
    Sign_Warning02_Orange: "Štítek varování 02 – oranžová",
    Sign_X01_Red: "Štítek X 01 – červená",
    Sign_X02_Red: "Štítek X 02 – červená",
    Star_Yellow: "Hvězda - žlutá",
    Wrench: "Nástroje",
    Airplane_Blue: "Letadlo - modrá",
    Bicycle_Blue: "Kolo - modrá",
    Bus: "Autobus",
    Canoe_Blue: "Kanoe - modrá",
    Car_Red: "Auto - červená",
    Helicopter_Blue: "Vrtulník - modrá",
    Motorcycle_Red: "Motorka - červená",
    Pedestrian_Blue: "Chodec - modrá",
    PersonalTransporter_Green: "Osobní vozítko – zelená",
    Sailboat_Red: "Plachetnice – červená",
    Scooter_Orange: "Skútr - oranžová",
    Train_Red: "Vlak - červená",
    Truck_Blue: "Nákladní auto - modrá",
    
    aria_category_selector: "Volby kategorií obrázků",
    filterImageGallery: "Filtrovat galerii obrázků"

})
