({
	service_unavailable_title: "Servicen er ikke tilgængelig.",
	service_unavailable_content: "${productName} er ikke tilgængelig, og din forespørgsel kan ikke behandles i øjeblikket. Prøv igen senere, eller kontakt systemadministratoren for at kontrollere, at ${productName}-service er online.",
	access_denied_title: "Adgang nægtet.",
	viewaccess_denied_content: "Du har ikke tilladelse til at få vist denne fil. Filen skal være offentlig, eller den skal være delt med dig.",
	editaccess_denied_content: "Du har ikke tilladelse til at redigere denne fil. Filen skal være delt med dig, eller du skal have redigeringsadgang til filen.",
	doc_notfound_title: "${productName} kan ikke finde filen",
	doc_notfound_content: "Kontakt administratoren for at undersøge, om ${productName} er konfigureret korrekt.",
	fullviewer_notsupport_title: "Dokumentet er ikke fundet",
	fullviewer_notsupport_content: "En ny filfremviser gemmer dokumentet på en anden URL-adresse. Hvis du vil have vist dokumentet, skal du finde filen i applikationen og klikke på knappen til forhåndsvisning.",
	fileconnect_denied_title: "Forbindelsen er blevet afvist.",
	fileconnect_denied_content: "${productName} kan ikke oprette forbindelse til fillageret. Prøv igen senere, eller kontakt systemadministratoren.",
	convservice_unavailable_title: "Konverteringsservicen er ikke tilgængelig.",
	convservice_unavailable_content: "Din forespørgsel kan ikke behandles i øjeblikket. Prøv igen senere, eller kontakt systemadministratoren for at kontrollere, at konverteringsservicen er online.",
	doc_toolarge_title: "Filen er for stor.",
	doc_toolarge_content: "Det dokument, du vil anvende, er for stort.",
	doc_toolarge_content2: "Filen kan ikke åbnes, fordi:",
	doc_toolarge_content3: "Filen kan ikke vises, fordi filen er større end ${0} KB. Du skal downloade filen for at få den vist. Hvis filen indeholder billeder i høj opløsning, kan du erstatte dem med billeder i lav opløsning for at reducere filstørrelsen.",
	doc_toolarge_content4: "Filen kan ikke vises, fordi filen ${0} er større end ${1} KB.",
	doc_toolarge_content5: "Filen er for stor til at blive vist her, men du kan stadig åbne den ved at klikke på downloadknappen på titellinjen.",
	edit_locked_file: "Du kan ikke redigere denne fil, fordi den er låst af andre redaktører.",
	sheet_toolarge_content: "Regnearket er større end ${0} KB.",
	sheet_toolarge_content2: "Regnearket indeholder flere end ${0} rækker i ét ark.",
	sheet_toolarge_content5: "Regnearket indeholder flere end ${0} kolonner i ét ark.",
	sheet_toolarge_content3: "Regnearket indeholder flere end ${0} celler.",
	sheet_toolarge_content4: "Regnearket indeholder flere end ${0} formler.",
	text_toolarge_content: "Dokumentet er større end ${0} KB.",
	text_toolarge_content2:"Dokumentet indeholder flere end ${0} sider.",
	text_toolarge_content3:"Dokumentets tekst er større end ${0} KB.",
	pres_toolarge_content: "Præsentationen er større end ${0} KB.",
	pres_toolarge_content2: "Præsentationen indeholder flere end ${0} sider.",
	pres_toolarge_content3: "Præsentationen indeholder mere end ${0} grafik.",
	pdf_toolarge_content: "PDF-filen er større end ${0} KB.",
	conversion_timeout_title: "Tidsfristen for dokumentkonvertering er overskredet.",
	conversion_timeout_content: "Det tager i øjeblikket for lang tid tid at konvertere dokumentet. Prøv igen senere.",
	invalid_docformat_title: "Dokumentindholdet er ugyldigt.",
	invalid_docformat_content: "Dokumentfiltypen er et gyldigt format, men du kan ikke få adgang til indholdet af filen.  Kontrollér, at filen ikke er ødelagt. ",
	invalid_doctype_title: "Dokumenttype understøttes ikke.",
	invalid_doctype_content: "Dokumenttypen understøttes ikke aktuelt af ${productName}.",
	malformed_request_title: "URL'en eller parametrene er forkerte.",
	malformed_request_content: "Kontrollér, om URL'en og parametrene er korrekte.",
	storageserver_error_title: "Lagringsserveren er ikke tilgængelig.",
	storageserver_error_content: "Der er aktuelt ikke adgang til serveren. Din forespørgsel kan ikke behandles i øjeblikket. Prøv igen senere, eller kontakt systemadministratoren for at kontrollere, at lagerserveren er online.",
	incorrect_web_address_title:"Forkert webadresse.",
	incorrect_web_address_content:"Webadressen er ikke korrekt.  Indtast webadressen, og prøv igen.",
	unexpecified_conversion_error_title:"Fejlen er ikke specificeret.",
	unexpecified_conversion_error_content:"Serveren har returneret en ikke-specificeret fejl.",
	encrypted_conversion_error_title:"CryptoAPI RC4-krypterede dokumenter understøttes ikke.",
	encrypted_conversion_error_content:"Filen er beskyttet med kodeord. For at få vist filen i ${productName} skal den være dekrypteret.",
	document_encrypt_title:"Dokumentet er krypteret.",
	document_encrypt_content:"Du kan ikke få vist filen online, fordi den blev krypteret i forbindelse med upload til Filer.",
	service_busy_title:"Dokumentet kunne ikke åbnes",
	service_busy_content:"Den fil, du vil have vist, kunne ikke åbnes. Serveren er optaget eller ikke tilgængelig. Prøv igen senere, eller kontakt systemadministratoren.",
	empty_doc_title: "Dokumentet er tomt.",
	empty_doc_content: "Undersøg, om dokumentet indeholder noget, og prøv derefter igen.",
	corrupted_doc_title: "Filen kan ikke åbnes.",
	corrupted_doc_content: "Filen indeholder ikke-understøttet indhold, f.eks. makroer, og den kan derfor ikke vises i denne applikation.",
	draft_storage_error_title: "Dokumentet kan ikke åbnes.",
	draft_storage_error_content: "Kan ikke indlæse indholdet, fordi det er ødelagt. Kontakt administratoren for at få hjælp.",
	unexpected_code_title: "Dokumentet kan ikke vises.",
	unexpected_code_content: "${docsProductName}-serveren er muligvis inaktiv. Prøv igen senere.",
	unpublished_document_title: "Filen kan ikke fremvises",
	unpublished_document_content: "Der er ingen publiceret version af denne fil, der kan fremvises.  Filejeren skal publicere en version af filen, før den kan fremvises.",
	unscanned_document_title: "Virusscan udført",
	unscanned_document_content: "Filer, der uploades til Connections, bliver automatisk scannet. Du kan få vist filen, når scanningen er udført.",
	malicious_document_title: "Skadelig fil",
	malicious_document_content: "Du kan ikke få vist denne fil, fordi Connections har fundet en virus under scanningen.",		
	repository_out_of_space_title: "Ikke nok plads",
	repository_out_of_space_content: "Kan ikke publicere ${0}, fordi du har nået kvoten for filstørrelse. Reducér kvoten ved at flytte andre filer til papirkurven, og slet dem derefter.",
	pdf_error_title:"Filen kan ikke åbnes.",
	pdf_error_content:"PDF-filen er muligvis ødelagt.",
	problem_id_msg_title: "Rapportér dette problem til administratoren. ",
	problem_id_msg_show: "Klik for at få vist detaljer",
	problem_id_msg_hide: "Klik for at skjule"
})

