({
	labelNormal: "Normal visning",
	labelPlay: "Afspil diasshow",
	labelZoomIn: "Zoom ind",
	labelZoomOut: "Zoom ud",
	labelFitWidth: "Tilpas til bredde",
	labelReset: "Nulstil",
	lablePageUp: "Forrige side",
	lablePageDown: "Næste side",
	labelPrint: "Udskriv",
	labelBuild: "${productName} ${0}",
	labelVersion: "${productName} ${0} ${1}",
	msgLoading: "Vent, mens dokumentet indlæses.",
	msgConversionFail: "Konvertering ikke udført",
	labelReload: "Indlæs igen",
	labelHelpContent:"Indhold af hjælp",
	labelAbout:"Om",
	labelProject:"${productName}",
	labelEdit: "Redigér",
	labelHelp: "Hjælp",
	labelCancel: "Annullér",
	labelImageTypeIcon: "Dokument",
	errPrintBeforeLoading: "Du kan ikke udskrive via menuen i browseren. Klik på udskrivningsknappen på værktøjslinjen for at udskrive dokumentet.  Du kan ikke udskrive nu, for indholdet er ikke færdigindlæst.",
	errPrintFromBrowserMenu: "Du udskriver dokumentet ved at klikke på udskrivningsknappen på værktøjslinjen, du skal ikke bruge udskrivningsmenuen i browseren.",
	errPrintConversionFail: "Du kan ikke udskrive, fordi indholdet ikke er blevet konverteret.",
	successMsg:"Udført",
	warningMsg:"Advarsel",
	errorMsg:"Fejl",
	backtofiles:"Tilbage til Filer",
	openLatestFile: "Åbn den seneste fil",
	updatePresentation:"Præsentationen er opdateret. ${0} for at få vist al tekst og alle billeder",
	updateNow: "Åbn nu",
	fileUpdated: "Præsentationen er opdateret",
	fileUpdatedContent1: "Præsentationen er opdateret. Åbn den seneste fil, før du udskriver.",
	fileUpdatedContent2: "Præsentationen er opdateret. Åbn den seneste fil, før du afspiller diasshowet.",
	htmlviewerlimitation: "Præsentationen indeholder animation, der ikke kan vises.",
	labelStopReview: "Stop gennemsyn",
	labelRejct: "Afvis",
	labelApprove: "Godkend",
	labelItemNotFountTitle: "Kan ikke fuldføre handlingen.",
	labelItemNotFountMsg: "Et andet medlem af fællesskabet behandler allerede dette dokument. Hvis du vil have flere oplysninger, skal du lukke dokumentet og vælge at få vist filoplysninger i dit bibliotek."
})

