/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2014. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        spreadsheetTemplates: "Modèles de feuille de calcul",
        documentTemplates: "Modèles de document",
        titleShareDocument: "Partager le document",
        offline: "Hors ligne",
        versionPublishing: "Publication de la version.",
        versionPublishFailed: "La version n'a pas été publiée. Il se peut que le fichier soit trop gros ou que le serveur fasse l'objet d'un dépassement de délai. Recommencez ou annulez et demandez à votre administrateur de consulter le journal serveur afin d'identifier le problème.",
        versionCheckinFailed: "La version n'a pas été restituée. Il se peut que le fichier soit trop gros ou que le serveur fasse l'objet d'un dépassement de délai. Recommencez ou annulez et demandez à votre administrateur de consulter le journal serveur afin d'identifier le problème.",
        versionSavedFailed: "L'enregistrement ne s'est pas terminé. Réessayez d'enregistrer plus tard.",
        publishFileSizeExceedMsg: "Impossible de publier le fichier car sa taille dépasse la limite définie par votre administrateur de référentiel. Supprimez du contenu pour réduire la taille du fichier ou contactez votre administrateur pour qu'il augmente la limite de taille.",
        checkinFileSizeExceedMsg: "Impossible de restituer le fichier car sa taille dépasse la limite définie par votre administrateur de référentiel. Supprimez du contenu pour réduire la taille du fichier ou contactez votre administrateur pour qu'il augmente la limite de taille.",
        versionpublished: "Version publiée par ${0} à ${1}.",
        versionPublishing2: "Enregistrement de la version.",
        versionPublishFailed2: "La version n'a pas été enregistrée. Il se peut que le fichier soit trop gros ou que le serveur fasse l'objet d'un dépassement de délai. Recommencez ou annulez et demandez à votre administrateur de consulter le journal serveur afin d'identifier le problème.",      
        publishFileSizeExceedMsg2: "Impossible d'enregistrer le fichier car sa taille dépasse la limite définie par votre administrateur de référentiel. Supprimez du contenu pour réduire la taille du fichier ou contactez votre administrateur pour qu'il augmente la limite de taille.",
        versionpublished2: "Version enregistrée par ${0} à ${1}.",
        chekinCloseDocsMsg: "Vous pouvez maintenant fermer ${productName}.",
        draftSavingAs: "Copie du fichier en cours...",
        draftSavedAs: "La nouvelle copie est enregistrée en tant que ${0}.",
        synchronizing: "Patientez pendant l'exécution de l'opération de synchronisation avec le serveur.",
        synchronizeError: "L'opération de synchronisation avec le serveur ne peut aboutir.",
        joinwithoutentitle: "Utilisateurs : ${0} veulent éditer le document mais ne peuvent rejoindre cette session d'édition, car vous n'avez pas le droit de co-éditer.",
        joinwithoutentitle2: "Utilisateurs : ${0} veulent éditer le document mais ne peuvent rejoindre cette session d'édition, car ils n'ont pas le droit de co-éditer.",
        backtoFiles: "Ouvrir Mes fichiers",
        backtoCommFiles: "Ouvrir des fichiers de communauté",
        backtoLibrary: "Ouvrir une bibliothèque",
        backtoICN: "Ouvrir Content Navigator",
        backtoRepository: "Ouvrir une liste de fichiers",
        createNewSpred: "Créer une feuille de calcul",
        createNewDoc: "Créer un document",
        createNewDocFromTemp: "Créer un document à partir d'un modèle",
        shareDoc: "Partager un document",
        exportPdf: "Mise en page",
        insertDate: "Sélection de la date",
        insertTime: "Sélection de l'heure",
        connect: "Connecter",
        theDoc: "le document",
        save: "Enregistrer les modifications",
        saveBeforeReviewMsg: "Il y a des modifications non enregistrées. Enregistrez vos modifications, puis soumettez à nouveau pour vérification.",
        submitReviewWidgetsFaiure: "L'application ne s'est pas initialisée correctement. Réessayez plus tard de soumettre pour vérification.",
        widgetsFaiure: "L'application ne s'est pas initialisée correctement.",
        slideSorter: "Diapositives",
        commentsBar: "Commentaires",
        draftBadge: "BROUILLON",
        share: "Partager",
        comment: "Commentaire",
        showSidebar: "Afficher la barre latérale",
        publishVersion: "Publier",
        checkInVersion: "Restituer",
        saveVersion: "Enregistrer",
        saved: "Toutes les modifications sont enregistrées",
        saving: "Enregistrement en cours",
        submitFragment: "Soumettre",
        aria_inMainMenu: "Vous êtes maintenant dans le menu principal",
        aria_inSlideSorter: "Vous êtes maintenant dans la vue sélecteur de diapositive",
        aria_inSlideEditor: "Vous êtes maintenant dans la vue éditeur de diapositive",
        createNewPres: "Créer une présentation",
        createNewAppFromTemp: "Créer un document à partir d'un modèle",
        textdoc: "texte",
        sheetdoc: "feuille de calcul",
        presdoc: "présentation",
        saveAsTextErrMsg: "Le nouveau document de texte ne peut être enregistré.",
        saveAsPresErrMsg: "Le nouveau document de présentation ne peut être enregistré.",
        saveAsSheetErrMsg: "Le nouveau document de feuille de calcul ne peut être enregistré.",
        saveAsTextErrMsg1: "L'espace disponible ne permet pas d'enregistrer le document.",
        saveAsPresErrMsg1: "L'espace disponible ne permet pas d'enregistrer la présentation.",
        saveAsSheetErrMsg1: "L'espace disponible ne permet pas d'enregistrer la feuille de calcul.",
        newDocTextErrMsg: "Impossible de créer un nouveau document de texte.",
        newDocSheetErrMsg: "Impossible de créer un nouveau document de feuille de calcul.",
        newDocPresErrMsg: "Impossible de créer un nouveau document de présentation.",
        newDocTextErrMsg2: "Impossible de créer un nouveau document de texte depuis le modèle.",
        newDocSheetErrMsg2: "Impossible de créer un nouveau document de feuille de calcul depuis le modèle.",
        newDocPresErrMsg2: "Impossible de créer un nouveau document de présentation depuis le modèle.",
        newDocTextErrMsg3: "L'espace disponible ne permet pas de créer un document.",
        newDocSheetErrMsg3: "L'espace disponible ne permet pas de créer une feuille de calcul.",
        newDocPresErrMsg3: "L'espace disponible ne permet pas de créer une présentation.",
        newDocTextErrMsg4: "Il existe déjà un document portant ce titre. Indiquez un titre différent pour le nouveau document.",
        newDocSheetErrMsg4: "Il existe déjà une feuille de calcul portant ce titre. Indiquez un titre différent pour la nouvelle feuille de calcul.",
        newDocPresErrMsg4: "Il existe déjà une présentation portant ce titre. Indiquez un titre différent pour la nouvelle présentation.",        
        aclWarningTitle: "Impossible d'éditer la nouvelle version",
        aclWarningMsg: "Le propriétaire du fichier ayant défini des zones protégées dans ce fichier, il est préférable de l'éditer en ligne. Contactez le propriétaire du fichier (${0}) si vous pensez que vous avez réellement besoin d'envoyer une nouvelle version par téléchargement.",
        aclWarningMsgForOwner: "Il y a des zones protégées dans ce fichier. Vous pourrez éditer la nouvelle version envoyée par téléchargement en ligne.  Vous devez retirer toutes les zones protégées dans ce fichier et vous pourrez ensuite ouvrir et éditer la nouvelle version envoyée par téléchargement.",
        st0: "Feuille1",
        st1: "Feuille2",
        st2: "Feuille3",
        FootnoteMsg: "Page",
        conflictMsg: "Il existe un conflit avec des modifications effectuées par d'autres éditeurs.  Votre modification a été annulée.",
        undoRedoConflictMsg: "Les opérations d'annulation et de rétablissement ont été suspendues du fait de l'existence d'un conflit entre ce que vous éditez et ce qu'un autre co-éditeur est en train de faire",
        bigFileErrMsg: "La taille du document est trop importante. Actualisez le navigateur pour voir si tout le contenu est intact",
        noPermissionMsg: "Vous ne disposez pas des droits nécessaires pour éditer ce fichier. Contactez le propriétaire du fichier pour obtenir des droits d'édition et réessayez.",
        networkIssueMsg: "Il y a un problème réseau.",
        networkIssueTitle: "Problème réseau",
        networkIssueContent: "Il y a un problème réseau. Actualisez la page et réessayez de vous connecter.",
        lockEditorMsg: "Le document ne peut pas être édité tant qu'il n'y a pas de connexion au serveur.",
        offlineReasonMsg: "Votre session a expiré.",
        offlineReasonForServerUnacceptedMsg: "Certaines de vos actions ne peuvent pas être traitées. Les actions seront supprimées par le serveur Docs au cours de la prochaine minute.",
        offlineReasonForServerDraftFormatChange: "Le format de votre document est obsolète en raison d'une mise à niveau du serveur.",
        reloadExplanationMsg: "Reconnectez-vous pour continuer à travailler.",
        reloadBtnLabel: "Recharger",
        reconnectingMsg: "Patientez pendant l'établissement de la connexion au serveur.",
        loadMsg: "Patientez pendant le chargement du document.",
        loadingDocumentMsg: "Patientez pendant le chargement du document depuis le serveur.",
        reLoadingDocumentMsg: "Patientez pendant le rechargement du document depuis le serveur.",
        unsupportMsg: "Une fonction non prise en charge a été détectée. Consultez les détails.",
        browserWorkingMsg: "Traitement en cours...",
        fileDeepDetectTitle: "Le format et l'extension du fichier ne correspondent pas",
        fileDeepDetectMsg: "Le format du fichier n'est pas celui indiqué par son extension. Cliquez sur Continuer pour éditer le fichier dans ce format.",
        fileDeepDetectOkLabel: "Continuer",
        tipInfo: "Astuce : ${0}",
        selectTextInfo: "Sélectionnez le texte sur lequel appliquer le style.",
        removeRecentFile: "Le fichier que vous voulez ouvrir a été supprimé. Voulez-vous retirer son nom de la liste Fichiers récents ?",
        altLotusIcon: "",
        altErrorMsgIcon: "Message d'erreur",
        altWarningMsgIcon: "Message d'avertissement",
        altSuccessMsgIcon: "Message de succès",
        sidebarLandmarkDesc: "barre latérale",
        footerTitle: "pied de page",
        mainDesc: "zone de contenu",
        editLockedDocumentWarning: "Vous avez verrouillé ce fichier alors que d'autres personnes l'éditaient. Consultez ces personnes pour coordonner les modifications ou demandez-leur de terminer l'édition pour que vous puissiez être le seul à avoir accès en édition.",
        observerMode: "Vous êtes maintenant en mode Observateur",
        editorMode: "Vous êtes maintenant en mode Editeur",
        maxEditorLimitReached: "Le nombre maximum d'éditeurs (${0}) du document a été atteint pour cette session. Vous pourrez basculer en mode Editeur lorsqu'un éditeur quittera le document ou basculera en mode Observateur.",
        maxEditorLimitReachedTitle: "Nombre maximum d'éditeurs atteint",
        uploadNewVersionOpenConfirm: "${0} a envoyé par téléchargement une nouvelle version à ${1} ${2}. Voulez-vous ouvrir la nouvelle version ?", //${0} name, ${1} time, ${2} date
        uploadNewVersionPublishConfirm: "${0} a envoyé par téléchargement une nouvelle version à ${1} ${2}.", //${0} name, ${1} time, ${2} date
        you: "Vous",
        today: "aujourd'hui",
        yesterday: "hier",
        slideShowInviteMsg: "L'utilisateur ${0} a lancé un diaporama partagé. Voulez-vous vous y joindre ?",
        slideShowInviteTitle: "Invitation à un diaporama partagé",
        slideShowInviteTitle1: "Invitation à un diaporama collectif",
        slideShowCoviewSelectUsersTitle: "Diaporama partagé",
        slideShowCoviewSelectUsersTitle1: "Diaporama collectif",
        slideShowCoviewStmt: "Partager l'état en cours de la présentation dans un diaporama partagé.",
        slideShowCoviewStmt1: "Partager l'état en cours de la présentation dans un diaporama collectif.",
        slideShowCoviewOptionOne: "Inviter tous les éditeurs à rejoindre le diaporama.",
        slideShowCoviewOptionOne1: "Inviter tous les éditeurs et observateurs à rejoindre le diaporama.",
        slideShowCoviewOptionTwo: "Inviter uniquement les éditeurs suivants à rejoindre le diaporama.",
        slideShowCoviewOptionTwo1: "Inviter uniquement les éditeurs et observateurs suivants à rejoindre le diaporama.",
        slideShowCoviewSlidesOf: "Diapositive ${0} sur ${1}",  //as in Slide 1 of 4
        slideShowCoviewViewers: "${0} visualiseurs",
        slideShowCoviewDialogInput: "Tapez pour filtrer par nom",
        slideShowCoviewAddTitle: "Ajouter au diaporama partagé",
        slideShowCoviewAddTitle1: "Ajouter au diaporama collectif",
        slideShowCoviewMessage: "Sélectionnez d'autres utilisateurs à inviter à ce diaporama partagé.",
        slideShowCoviewMessage1: "Sélectionnez d'autres utilisateurs à inviter à ce diaporama collectif.",
        slideShowCoviewEnded: "Diaporama partagé terminé",
        slideShowCoviewEndMessage: "Le diaporama partagé que vous tentez de rejoindre n'est plus disponible.",
        slideShowCoviewEndMessage2: "L'utilisateur ${0} a mis fin au diaporama partagé.",
        slideShowWarning: "Vous devez fermer le diaporama en cours avant d'en démarrer un nouveau.",
        slideShowHoverMsg: "Cliquez pour voir qui d'autre consulte le diaporama.",
        slideShowHoverMsgAdd: "Cliquez pour inviter d'autres visualiseurs.",
        csvEmpty: "Exportation en tant que fichier .csv impossible car la feuille ne contient pas de données.",
        edit: "Editer",
        printToPDF: "Télécharger au format PDF",
        print: "Imprimer",
        view: "Vue",
        openLatestFile: "Ouvrir le fichier le plus récent",
        updateDocument: "Le document a été mis à jour.${0}.",
        updateSpreadsheet: "La feuille de calcul a été mise à jour.${0}",
        updatePresentation: "La présentation a été mise à jour.${0}.",
        labelCancel: "Annuler",
        msgConversionFail: "Echec de la conversion",
        updateNow: "Ouvrir maintenant",
        fileUpdated: "Le document a été mis à jour",
        fileUpdatedContent1: "Le document a été mis à jour. Ouvrez le fichier le plus récent avant d'imprimer.",
        htmlviewerlimitation1: "Cette feuille de calcul contient un tableau croisé dynamique qui ne peut pas être affiché",
        htmlviewerlimitation2: "Cette feuille de calcul contient de la mise en forme conditionnelle qui ne peut pas être affichée",
        htmlviewerlimitation3: "Cette feuille de calcul contient un tableau croisé dynamique et de la mise en forme conditionnelle qui ne peuvent pas être affichés",
        close: "Fermer",
        closeDocs: "Fermer ${productName}",
        endSessionDlgTitle: "La session d'édition est terminée",
        endSessionDlgNotice: "Votre session d'édition s'est terminée car ${0} a restitué le fichier.",
        labelStopReview: "Arrêter la révision",
        labelRejct: "Rejeter",
        labelApprove: "Valider",
        errorMsg: "Erreur",
        labelItemNotFountTitle: "Impossible d'effectuer l'action.",
        labelItemNotFountMsg: "Un autre membre de communauté a déjà effectué l'action sur ce document. Pour plus d'informations, fermez le document et accédez à la page des détails du fichier dans votre bibliothèque.",
        viewProtectedAreas: "Cette feuille de calcul contient des zones protégées. Vous devez l'afficher ou l'éditer en ligne uniquement.",
        macroTitle: "Le fichier contient une macro", 
        macroDesc: "L'édition de ce fichier pourrait casser la macro. Pour éviter que des personnes éditent la plage ou la feuille contenant la macro, utilisez Données > Zones protégées.",
        problem_id_msg_title: "Signalez ce problème à votre administrateur. ",
        problem_id_msg_show: "Cliquez pour afficher des détails",
    	problem_id_msg_hide: "Cliquez pour masquer",
    	uploadNewVersionWarningTitle: "Impossible d'éditer la nouvelle version",
        changeHistoryWarningMsg: "Le propriétaire du fichier ayant le suivi des modifications dans ce fichier, il est préférable de l'éditer en ligne. Contactez le propriétaire du fichier (${0}) si vous pensez que vous avez réellement besoin d'envoyer une nouvelle version par téléchargement.",
        changeHistoryWarningMsgForOwner: "Il existe un historique des modifications dans ce fichier. Vous pourrez éditer la nouvelle version envoyée par téléchargement en ligne.  Vous devez effacer l'historique des modifications et désactiver le suivi des modifications dans ce fichier pour pouvoir ouvrir et éditer la nouvelle version envoyée par téléchargement.",
        viewChangeHistory: "Ce document contient un historique des modifications. Vous devez l'afficher ou l'éditer en ligne uniquement.",
    	contentCorruptErrMsg: "Impossible de charger le contenu car il est endommagé. Contactez votre administrateur pour obtenir de l'aide."
});

