/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
    Arrow01_Gray: "Strelica 01 siva",
    Arrow02_Gray: "Strelica 02 siva",
    Arrow03_Red: "Strelica 03 crvena",
    Arrow04_Blue: "Strelica 04 plava",
    Arrow05_Blue: "Strelica 05 plava",
    Arrow06_Yellow: "Strelica 06 žuta",
    Arrow07_Red: "Strelica 07 crvena",
    Arrow08_Gray: "Strelica 08 siva",
    Arrow09_Orange: "Strelica 09 narandžasta",
    Arrow10_Blue: "Strelica 10 plava",
    Arrow11_Blue: "Strelica 11 plava",
    Arrow12_Green: "Strelica 12 zelena",
    Arrow13_Blue: "Strelica 13 plava",
    Arrow14_Green: "Strelica 14 zelena",
    Arrow15_Orange: "Strelica 15 narandžasta",
    Arrow16_Gray: "Strelica 16 siva",
    CircleArrow01_Green: "Kružna strelica 01 zelena",
    CircleArrow02_Multi: "Kružna strelica 02 višebojna",
    CircleArrow03_Multi: "Kružna strelica 03 višebojna",
    CircleArrow04_Multi: "Kružna strelica 04 višebojna",
    CircleArrow05_Multi: "Kružna strelica 05 višebojna",
    CircleArrow06_Multi: "Kružna strelica 06 višebojna",
    CircleArrow07_Blue: "Kružna strelica 07 plava",
    CircleArrow08_Green: "Kružna strelica 08 zelena",
    CircleArrow09_Multi: "Kružna strelica 09 višebojna",
    CurvedArrow01_Gray: "Zakrivljena strelica 01 siva",
    CurvedArrow02_Blue: "Zakrivljena strelica 02 plava",
    CurvedArrow03_Blue: "Zakrivljena strelica 03 plava",
    CurvedArrow04_Orange: "Zakrivljena strelica 04 narandžasta",
    CurvedArrow05_Red: "Zakrivljena strelica 05 crvena",
    CurvedArrow06_Blue: "Zakrivljena strelica 06 plava",
    CurvedArrow07_Purple: "Zakrivljena strelica 07 ljubičasta",
    CurvedArrow08_Green: "Zakrivljena strelica 08 zelena",
    CurvedArrow09_Gray: "Zakrivljena strelica 09 siva",
    CurvedArrow10_Blue: "Zakrivljena strelica 10 plava",
    CurvedArrow11_Orange: "Zakrivljena strelica 11 narandžasta",
    CurvedArrow12_Blue: "Zakrivljena strelica 12 plava",
    CurvedArrow13_Green: "Zakrivljena strelica 13 zelena",
    CurvedArrow14_Brown: "Zakrivljena strelica 14 braon",
    CurvedArrow15_Blue: "Zakrivljena strelica 15 plava",
    CurvedArrow16_Gray: "Zakrivljena strelica 16 siva",
    CurvedArrow17_Gray: "Zakrivljena strelica 17 siva",
    CurvedArrow18_Gray: "Zakrivljena strelica 18 siva",
    CurvedArrow19_Gray: "Zakrivljena strelica 19 siva",
    CurvedArrow20_Gray: "Zakrivljena strelica 20 siva",
    TrendArrow01_Red: "Strelica trenda 01 crvena",
    TrendArrow02_Green: "Strelica trenda 02 zelena",
    TrendArrow03_Orange: "Strelica trenda 03 narandžasta",
    TrendArrow04_Red: "Strelica trenda 04 crvena",
    TrendArrow05_Orange: "Strelica trenda 05 narandžasta",
    TrendArrow06_Blue: "Strelica trenda 06 plava",
    TrendArrow07_Orange: "Strelica trenda 07 narandžasta",
    TrendArrow08_Yellow: "Strelica trenda 08 žuta",
    TrendArrow09_Blue: "Strelica trenda 09 plava",
    TrendArrow10_Blue: "Strelica trenda 10 plava",
    TrendArrow11_Blue: "Strelica trenda 11 plava",
    TrendArrow12_Blue: "Strelica trenda 12 plava",
    TrendArrow13_Red: "Strelica trenda 13 crvena",
    TrendArrow14_Multi: "Strelica trenda 14 višebojna",
    TrendArrow15_Blue: "Strelica trenda 15 plava",
    Bullet01_Circle_DarkRed: "Znak za nabrajanje 01 kružni tamnocrveni",
    Bullet02_Circle_Blue: "Znak za nabrajanje 02 kružni plavi",
    Bullet03_Circle_Green: "Znak za nabrajanje 03 kružni zeleni",
    Bullet04_Square_Black: "Znak za nabrajanje 04 četvrtasti crni",
    Bullet05_Square_Orange: "Znak za nabrajanje 05 četvrtasti narandžasti",
    Bullet06_Square_Purple: "Znak za nabrajanje 06 četvrtasti ljubičasti",
    Bullet07_Diamond_Blue: "Znak za nabrajanje 07 romboidni plavi",
    Bullet08_Diamond_LightBlue: "Znak za nabrajanje 08 romboidni svetloplavi",
    Bullet09_Diamond_Red: "Znak za nabrajanje 09 romboidni crveni",
    Bullet10_Star_Yellow: "Znak za nabrajanje 10 zvezda žuti",
    Bullet11_Star_Blue: "Znak za nabrajanje 11 zvezda plavi",
    Bullet12_Triangle_Blue: "Znak za nabrajanje 12 trougao plavi",
    Bullet13_Triangle_DarkGreen: "Znak za nabrajanje 13 trougao tamnozeleni",
    Bullet14_Arrow_Red: "Znak za nabrajanje 14 strelica crvena",
    Bullet15_Arrow_Blue: "Znak za nabrajanje 15 strelica plava",
    Bullet16_Box_Blue: "Znak za nabrajanje 16 kutija plavi",
    Bullet17_Box_Red: "Znak za nabrajanje 17 kutija crveni",
    Bullet18_Asterisk_LightBlue: "Znak za nabrajanje 18 zvezdica svetloplavi",
    Bullet19_Leaves_Red: "Znak za nabrajanje 19 lišće crveni",
    Bullet20_Target_Blue: "Znak za nabrajanje 20 meta plavi",
    Bullet21_Arrow_Blue: "Znak za nabrajanje 21 strelica plavi",
    Bullet22_Arrow_DarkBlue: "Znak za nabrajanje 22 strelica tamnoplavi",
    Bullet23_Arrow_Brown: "Znak za nabrajanje 23 strelica braon",
    Bullet24_Flag_Red: "Znak za nabrajanje 24 zastavica crveni",
    Bullet25_Flag_Green: "Znak za nabrajanje 25 zastavica zeleni",
    Bullet26_X_Red: "Znak za nabrajanje 26 X crveni",
    Bullet27_X_Black: "Znak za nabrajanje 27 X crni",
    Bullet28_Checkmark_Green: "Znak za nabrajanje 28 potvrdni znak zeleni",
    Bullet29_Checkmark_Blue: "Znak za nabrajanje 29 potvrdni znak plavi",
    Bullet30_Square_DarkRed: "Znak za nabrajanje 30 kvadrat tamnocrveni",
    camera: "Kamera",
    computer1: "Računar 1",
    computer2: "Računar 2",
    computer3: "Računar 3",
    Computer_Cloud: "Računarski oblak",
    Computer_Desktop: "Desktop računar",
    Computer_Laptop_Black: "Crni laptop računar",
    Computer_Laptop_Silver: "Sivi laptop računar",
    Database: "Baza podataka",
    evelope: "Koverta",
    newspapers: "Novine",
    openevelope: "Otvorena koverta",
    Server: "Server",
    speaker: "Zvučnik",
    WirelessAccessPoint: "Bežična pristupna tačka",
    Cycle01_Transparent: "Ciklus 01 providan",
    Cycle02_Transparent_Blue: "Ciklus 02 providan plav",
    Cycle03_Blue: "Ciklus 03 plav",
    Cycle04_Blue: "Ciklus 04 plav",
    Cycle05: "Ciklus 05",
    Cycle06: "Ciklus 06",
    Cycle07: "Ciklus 07",
    Cycle08_Blue: "Ciklus 08 plav",
    Cycle09_Orange: "Ciklus 09 narandžast",
    Donut01_LightBlue: "Prsten 01 svetloplavi",
    Donut02_Blue: "Prsten 02 plavi",
    Donut03_Blue: "Prsten 03 plavi",
    Donut04_DarkBlue: "Prsten 04 tamnoplavi",
    Donut05_DarkBlue: "Prsten 05 tamnoplavi",
    Donut06_Blue: "Prsten 06 plavi",
    Donut07_Blue: "Prsten 07 plavi",
    Graph: "Grafikon",
    People01_Blue: "Ljudi 01 plavo",
    People02: "Ljudi 02",
    Pillars01_Orange: "Stubovi 01 narandžasti",
    Pillars02_LightBlue: "Stubovi 02 svetloplavi",
    Process01_Blue: "Proces 01 plavi",
    Process02_Blue: "Proces 02 plavi",
    Process03_Blue: "Proces 03 plavi",
    Process04_GoUp_Blue: "Proces 04 nagore plavo",
    Process05_GoUp_Red: "Proces 05 nagore crveno",
    Process06_GoUp_Yellow: "Proces 06 nagore žuto",
    Process07_Blue: "Proces 07 plavi",
    Pyramid01: "Piramida 01",
    Pyramid02_Blue: "Piramida 02 plava",
    Pyramid03: "Piramida 03",
    Radial01_Green: "Radijalno 01 zeleno",
    Radial02_Green: "Radijalno 02 zeleno",
    Radial03_Sphere: "Radijalno 03 sfera",
    Radial04_Sphere_Red: "Radijalno 04 sfera crveno",
    Radial05_Sphere_Blue: "Radijalno 05 sfera plavo",
    Radial06_Arrows_DarkBlue: "Radijalno 06 strelice tamnoplavo",
    Radial07_Arrows_DarkBlue: "Radijalno 07 strelice tamnoplavo",
    Section_Circle: "Odeljak strelice",
    Section_Cubes01: "Odeljak kocke 01",
    Section_Cubes02_Blue: "Odeljak kocke 02 plavo",
    Section_Cubes03_Orange: "Odeljak kocke 03 narandžasto",
    Section_Cubes04: "Odeljak kocke 04",
    Section_Cubes05: "Odeljak kocke 05",
    Section_Cuboids01_Blue: "Odeljak kvadri 01 plavo",
    Section_Cuboids02_Blue: "Odeljak kvadri 02 plavo",
    Section_Cuboids03: "Odeljak kvadri 03",
    Section_Gears01: "Odeljak zupčanici 01",
    Section_Gears02: "Odeljak zupčanici 02",
    Section_Gears03: "Odeljak zupčanici 03",
    Section_Hexagon04_Orange: "Odeljak šestougaonik 04 narandžasti",
    Section_Hexagons01: "Odeljak šestougaonici 01",
    Section_Hexagons02_Blue: "Odeljak šestougaonici 02 plavi",
    Section_Hexagons03_Blue: "Odeljak šestougaonici 03 plavi",
    Section_Leaves01_LightBlue: "Odeljak listovi 01 svetloplavi",
    Section_Leaves02_Green: "Odeljak listovi 02 zeleni",
    Section_Pasters01: "Odeljak nalepnice 01",
    Section_Pasters02_Blue: "Odeljak nalepnice 02 plavo",
    Section_Puzzle01: "Odeljak slagalica 01",
    Section_Puzzle02: "Odeljak slagalica 02",
    Section_Puzzle03: "Odeljak slagalica 03",
    Section_Rectangles: "Odeljak pravougaonici",
    Section_Squares: "Odeljak kvadrati",
    Section_Triangle: "Odeljak truogao",
    Target: "Meta",
    Venn01: "Venov dijagram 01",
    Venn02: "Venov dijagram 02",
    Venn03: "Venov dijagram 03",
    Venn04: "Venov dijagram 04",
    Venn05: "Venov dijagram 05",
    Venn06_Blue: "Venov dijagram 06 plavi",
    Venn07_Blue: "Venov dijagram 07 plavi",
    Venn08: "Venov dijagram 08",
    Blackboard: "Tabla",
    Books: "Knjige",
    Books1: "Knjige 1",
    books2: "Knjige 2",
    Chalk: "Kreda",
    clipboard: "klipbord",
    clock: "sat",
    Globe: "Globus",
    Glue: "Lepak",
    GraduationCap: "Akademska kapa",
    magnifyingglass: "lupa",
    Microscope: "Mikroskop",
    Notebook: "Sveska",
    notepad1: "Sveska 1",
    notepad2: "Sveska 2",
    notepad3: "Sveska 3",
    PaperClip_Blue: "Spajalica plava",
    PaperClip_Red: "Spajalica crvena",
    Pencil: "Olovka",
    Ruler: "Lenjir",
    TestTubes: "Epruvete",
    thumbtack: "Čioda",
    clouds: "Oblaci",
    DrippingFaucet: "Slavina koja kaplje",
    Earth: "Zemlja",
    EndangeredAnimals1: "Ugrožene životinje 1",
    EndangeredAnimals2: "Ugrožene životinje 2",
    GreenCar: "Zeleni automobil",
    GreenFactory: "Zelena fabrika",
    GreenHouse: "Zelena kuća",
    Leaf1: "List 1",
    Leaf2: "List 2",
    lightbulb: "Sijalica",
    LightBulb_Flourescent_Off: "Isključena fluorescentna sijalica",
    LightBulb_Flourescent_On: "Uključena fluorescentna sijalica",
    LightBulb_Standard_Off1: "Isključena standardna sijalica 1",
    LightBulb_Standard_Off2: "Isključena standardna sijalica 2",
    LightBulb_Standard_On: "Uključena standardna sijalica",
    lightningcloud: "Oblak sa munjama",
    Pollution_Car: "Automobil-zagađivač",
    Pollution_Factory: "Fabrika-zagađivač",
    Raindrop: "Kap kiše",
    RecycleBin: "Korpa za otpatke",
    RecycleSymbol: "Simbol za recikliranje",
    RenewableEnergySymbol: "Simbol obnovljive energije",
    RenewableEnergy_Solar: "Solarna obnovljiva energija",
    RenewableEnergy_Water: "Obnovljiva energija vode",
    RenewableEnergy_Wind: "Obnovljiva energija vetra",
    sun: "Sunce",
    Sun1: "Sunce 1",
    Sun2: "Sunce 2",
    sundandcloud: "Sunce i oblak",
    world: "Svet",
    Agreement: "Dogovor",
    ATM01: "Bankomat 01",
    ATM02: "Bankomat 02",
    Balance_Balanced1: "Ravnoteža - balansirano 1",
    Balance_Balanced2: "Ravnoteža - balansirano 2",
    Balance_Unbalanced1: "Ravnoteža - nebalansirano 1",
    Balance_Unbalanced2: "Ravnoteža - nebalansirano 2",
    Calculator: "Kalkulator",
    Chart_Decrease1: "Smanjenje na grafikonu 1",
    Chart_Decrease2: "Smanjenje na grafikonu 2",
    Chart_Increase1: "Povećanje na grafikonu 1",
    Chart_Increase2: "Povećanje na grafikonu 2",
    Chart_Plateau: "Nepromenljiva vrednost na grafikonu",
    Check: "Ček",
    Contract: "Ugovor",
    CreditCard_Black: "Crna kreditna kartica",
    CreditCard_Cut: "Deo kreditne kartice",
    CreditCard_Gold: "Zlatna kreditna kartica",
    Currency_Dollar: "Valuta - dolar",
    Currency_Dollars: "Valuta - dolari",
    Currency_Stack: "Valuta - svežanj",
    Currency_StackCoins: "Valuta - novčići",
    GoldBar: "Zlatna poluga",
    GoldBar_Stack: "Naslagane zlatne poluge",
    MoneyBag01: "Vreća sa novcem 01",
    MoneyBag02: "Vreća sa novcem 02",
    PercentSign: "Znak za procenat",
    PiggyBank01_Broken: "Kasica-prasica 01 polomljena",
    PiggyBank02_Broken: "Kasica-prasica 02 polomljena",
    PiggyBank_Coins: "Novčići iz kasice-prasice",
    PiggyBank_Currency: "Kasica-prasica - valuta",
    Portfolio: "Portfolio",
    PriceTag: "Oznaka sa cenom",
    Safe_Closed: "Zatvoren sef",
    Safe_Empty: "Prazan sef",
    Safe_Full: "Pun sef",
    Seal_Gold: "Zlatni pečat",
    Seal_Red: "Crveni pečat",
    Seal_Silver: "Srebrni pečat",
    Wallet_Empty: "Prazan novčanik",
    Wallet_Full1: "Pun novčanik 1",
    Wallet_Full2: "Pun novčanik 2",
    BusinessPerson_Female6: "Poslovna žena 6",
    BusinessPerson_Male3: "Poslovni čovek 3",
    Computer_User_Female1: "Korisnik računara - ženski 1",
    ConstructionWorker2: "Građevinski radnik 2",
    Presenter_Female1: "Spikerka 1",
    Component_Circle01_Transparent_DarkBlue: "Komponenta krug 01 providna tamnoplava",
    Component_Circle02_Transparent_Bule: "Komponenta krug 02 providna plava",
    Component_Circle03_Transparent_Green: "Komponenta krug 03 providna zelena",
    Component_Circle04_Transparent_Orange: "Komponenta krug 04 providna narandžasta",
    Component_Circle05_Transparent_Red: "Komponenta krug 05 providna crvena",
    Component_Cube01_DarkBlue: "Komponenta kocka 01 tamnoplava",
    Component_Cube02_LightBlue: "Komponenta kocka 02 svetloplava",
    Component_Cube03_Green: "Komponenta kocka 03 zelena",
    Component_Cube04_Orange: "Komponenta kocka 04 narandžasta",
    Component_Cube05_DarkRed: "Komponenta kocka 05 tamnocrvena",
    Component_Cuboid01_DarkBlue: "Komponenta kvadar 01 tamnoplava",
    Component_Cuboid02_Blue: "Komponenta kvadar 02 plava",
    Component_Cuboid03_Green: "Komponenta kvadar 03 zelena",
    Component_Cuboid04_Orange: "Komponenta kvadar 04 narandžasta",
    Component_Cuboid05_Red: "Komponenta kvadar 05 crvena",
    Component_Gear01_DarkBlue: "Komponenta zupčanik 01 tamnoplava",
    Component_Gear02_LightBlue: "Komponenta zupčanik 02 svetloplava",
    Component_Gear03_Green: "Komponenta zupčanik 03 zelena",
    Component_Gear04_DarkRed: "Komponenta zupčanik 04 tamnocrvena",
    Component_Gear05_Orange: "Komponenta zupčanik 05 narandžasta",
    Component_Person01_DarkBlue: "Komponenta osoba 01 tamnoplava",
    Component_Person02_Blue: "Komponenta osoba 02 plava",
    Component_Person03_Green: "Komponenta osoba 03 zelena",
    Component_Person04_DarkRed: "Komponenta osoba 04 tamnocrvena",
    Component_Person05_Orange: "Komponenta osoba 05 narandžasta",
    Component_PuzzlePiece01_DarkBlue: "Komponenta deo slagalice 01 tamnoplava",
    Component_PuzzlePiece02_Blue: "Komponenta deo slagalice 02 plava",
    Component_PuzzlePiece03_Green: "Komponenta deo slagalice 03 zelena",
    Component_PuzzlePiece04_Red: "Komponenta deo slagalice 04 crvena",
    Component_PuzzlePiece05_Orange: "Komponenta deo slagalice 05 narandžasta",
    Component_Sphere01_DarkBlue: "Komponenta sfera 01 tamnoplava",
    Component_Sphere02_LightBlue: "Komponenta sfera 02 svetloplava",
    Component_Sphere03_Green: "Komponenta sfera 03 zelena",
    Component_Sphere04_DarkRed: "Komponenta sfera 04 tamnocrvena",
    Component_Sphere05_Orange: "Komponenta sfera 05 narandžasta",
    Book: "Knjiga",
    Box01: "Kutija 01",
    Box02: "Kutija 02",
    Bulb01_Yellow: "Sijalica 01 žuta",
    Bulb02_Yellow: "Sijalica 02 žuta",
    Calendar: "Kalendar",
    Chart: "Grafikon",
    Clipboard: "Tablica za pisanje",
    Clock: "Sat",
    Compass: "Kompas",
    Flag01_Red: "Zastavica 01 crvena",
    Flag02_Green: "Zastavica 02 zelena",
    Flag03_Blue: "Zastavica 03 plava",
    Gift: "Poklon",
    House: "Kuća",
    Icon_Computer01_White: "Ikona računara 01 bela",
    Icon_Computer02_Black: "Ikona računara 02 crna",
    Icon_Disk01_Blue: "Ikona diskete 01 plava",
    Icon_Disk02_Green: "Ikona diskete 02 zelena",
    Icon_Document01_Grey: "Ikona dokumenta 01 siva",
    Icon_Document02_Grey: "Ikona dokumenta 02 siva",
    Icon_Document03_Blue: "Ikona dokumenta 03 plava",
    Icon_Document04_Blue: "Ikona dokumenta 04 plava",
    Icon_Envelope01_Blue: "Ikona koverte 01 plava",
    Icon_Envelope02_Yellow: "Ikona koverte 02 žuta",
    Icon_Envelope03_Open_Yellow: "Ikona koverte 03 otvorena žuta",
    Icon_Envelope04_Open_Yellow: "Ikona koverte 04 otvorena žuta",
    Icon_Folder01_Yellow: "Ikona fascikle 01 žuta",
    Icon_Folder02_Yellow: "Ikona fascikle 02 žuta",
    Icon_Folder03_Open_Yellow: "Ikona fascikle 03 otvorena žuta",
    Icon_Folder04_Open_Yellow: "Ikona fascikle 04 otvorena žuta",
    Icon_Gear01_Grey: "Ikona zupčanika 01 siva",
    Icon_Gear02_Blue: "Ikona zupčanika 02 plava",
    Icon_Network01_Blue: "Ikona mreže 01 plava",
    Icon_Network02: "Ikona mreže 02",
    Icon_Pencil01: "Ikona olovke 01",
    Icon_Pencil02: "Ikona olovke 02",
    Icon_Printer01_White: "Ikona štampača 01 bela",
    Icon_Printer02_Black: "Ikona štampača 02 crna",
    Key01: "Ključ 01",
    Key02: "Ključ 02",
    Lock01_Yellow: "Brava 01 žuta",
    Lock02_Yellow: "Brava 02 žuta",
    Lock03_Blue: "Brava 03 plava",
    Lock04_Blue: "Brava 04 plava",
    Magnet: "Magnet",
    MagnifyingGlass: "Lupa",
    Medal: "Medalja",
    Notebook: "Sveska",
    Phone: "Telefon",
    PieChart: "Kružni grafikon",
    Pin: "Čioda",
    PuzzlePiece: "Deo slagalice",
    PuzzlePieces: "Delovi slagalice",
    Roadblock: "Blokada puta",
    Scissors: "Makaze",
    Shield01: "Štit 01",
    Shield02_Orange: "Štit 02 narandžasti",
    Shield03_Blue: "Štit 03 plavi",
    Sign_Ban01: "Znak za zabranu 01",
    Sign_Ban02: "Znak za zabranu 02",
    Sign_CheckBox01: "Znak polja za potvrdu 01",
    Sign_CheckBox02_Unchecked: "Znak polja za potvrdu 02 neobeležen",
    Sign_Checkmark01_Green: "Potvrdni znak 01 zeleni",
    Sign_Checkmark02_Green: "Potvrdni znak 02 zeleni",
    Sign_DoNotEnter: "Znak za zabranjen ulaz",
    Sign_Error01: "Znak za grešku 01",
    Sign_Error02: "Znak za grešku 02",
    Sign_ExclamationPoint01_Red: "Znak sa uzvičnikom 01 crveni",
    Sign_ExclamationPoint02_Orange: "Znak sa uzvičnikom 02 narandžasti",
    Sign_Help01_Green: "Znak za pomoć 01 zeleni",
    Sign_Help02_Blue: "Znak za pomoć 02 plavi",
    Sign_Information: "Znak za informacije",
    Sign_Null: "Znak sa nulom",
    Sign_QuestionMark01_Blue: "Znak sa upitnikom 01 plavi",
    Sign_QuestionMark02_Red: "Znak sa upitnikom 02 crveni",
    Sign_RadioButton01: "Znak za radio dugme 01",
    Sign_RadioButton02_Unchecked: "Znak za radio dugme 02 neobeležen",
    Sign_Warning01_Red: "Znak za upozorenje 01 crveni",
    Sign_Warning02_Orange: "Znak za upozorenje 02 narandžasti",
    Sign_X01_Red: "Znak X 01 crveni",
    Sign_X02_Red: "Znak X 02 crveni",
    Star_Yellow: "Žuta zvezda",
    Wrench: "Odvijač",
    Airplane_Blue: "Plavi avion",
    Bicycle_Blue: "Plavi bicikl",
    Bus: "Autobus",
    Canoe_Blue: "Plavi kanu",
    Car_Red: "Crveni automobil",
    Helicopter_Blue: "Plavi helikopter",
    Motorcycle_Red: "Crveni motocikl",
    Pedestrian_Blue: "Plavi pešak",
    PersonalTransporter_Green: "Zeleni lični transporter",
    Sailboat_Red: "Crveni čamac",
    Scooter_Orange: "Narandžasti skuter",
    Train_Red: "Crveni voz",
    Truck_Blue: "Plavi kamion",
    
    aria_category_selector: "Opcije za kategoriju slike",
    filterImageGallery: "Filtriraj galeriju slika"

})

