/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
	fileMenu: "Datoteka",
	fileMenu_New: "Novo",
	fileMenu_NewDocument: "Dokument",
	fileMenu_NewDocumentfromTemplate: "Dokument od predloška",
	fileMenu_NewPresentation: "Prezentacija",
	fileMenu_NewPresentationfromTemplate: "Prezentacija od predloška",
	fileMenu_NewSpreadsheet: "Unakrsna tabela",
	fileMenu_Open: "Otvori",
//	fileMenu_Close: "Close",
	fileMenu_Discard: "Odbaci",
	fileMenu_Save: "Sačuvaj",
//	fileMenu_SaveAs: "Save As...",
//	fileMenu_SaveAsDraft: "as Draft",
//	fileMenu_SaveInMyDocs: "in My Documents",
//	fileMenu_SaveToSymphony: "to Lotus Symphany",
	fileMenu_ShareWith: "Deli sa...	",
	fileMenu_ExportAsPDF: "Izvezi kao PDF",
	fileMenu_WebPreview: "Pregled na vebu",
	fileMenu_PrintPreview: "Pregled za štampanje",
	fileMenu_RecentFile: "Nedavne datoteke",
	fileMenu_Print: "Odštampaj... ",
	editMenu: "Uredi",
	editMenu_Undo: "Opozovi",
	editMenu_Redo: "Ponovi",
	editMenu_Cut: "Iseci",
	editMenu_Copy: "Kopiraj",
	editMenu_Paste: "Nalepi",
	editMenu_DeleteSlide:"Izbriši slajd",
	editMenu_SelectAll: "Izaberi sve",
	editMenu_Find: "Pronađi...",
	editMenu_Replace: "Zameni...",
	editMenu_DeleteSheet: "Izbriši list",
	editMenu_DuplicateSheet: "Dupliraj list",
	editMenu_DeleteRow: "Izbriši red",
	editMenu_DeleteColumn: "Izbriši kolonu",
	editMenu_ClearCell: "Izbriši ćeliju",
	viewMenu: "Prikaz",
	viewMenu_Master: "Glavno",
	viewMenu_Notifications: "Obaveštenja",
	viewMenu_ShowHideIndicators: "Prikaži/sakrij indikatore zajedničkog uređivanja",
	viewMenu_SlideSorter: "Prikaži sortiranje slajdova",
	viewMenu_SpeakerNotes: "Prikaži beleške govornika",
	viewMenu_NextSlide: "Sledeći slajd",
	viewMenu_PrevSlide: "Prethodni slajd",
	createMenu: "Kreiranje",
	createMenu_NewSlide: "Novi slajd",
	createMenu_DuplicateSlide: "Dupliraj slajd",
	createMenu_ImageFromFile: "Grafika od datoteke",
	createMenu_TextBox: "Okvir za tekst",
	createMenu_Task: "Zadatak",
    formatMenu_Text_Direction: "Smer teksta",
    formatMenu_Ltr: "Sleva nadesno",
    formatMenu_Rtl: "Zdesna nalevo",  	
    formatMenu_Horizontal_Align: "Horizontalno poravnanje",
    formatMenu_Vertical_Align: "Vertikalno poravnanje",
    formatMenu_Align_Top: "Gore",
    formatMenu_Align_Middle: "Sredina",
    formatMenu_Align_Bottom: "Dole",
	layoutMenu: "Raspored",
	layoutMenu_SlideLayout: "Izgled slajda",
	layoutMenu_SlideDesign: "Glavni stilovi",
	tableMenu: "Tabela",
	tableMenu_CreateTable: "Kreiraj tabelu",
	tableMenu_Cell: "Ćelija",
	tableMenu_CellAlignLeft: "Poravnaj tekst levo",
	tableMenu_CellAlignCenter: "Poravnaj tekst po centru",
	tableMenu_CellAlignRight: "Poravnaj tekst desno",
	tableMenu_CellClearContents: "Izbriši sadržaj",
	tableMenu_Row: "Red",
	tableMenu_RowAddRowAbove: "Dodaj red iznad",
	tableMenu_RowAddRowBelow: "Dodaj red ispod",
	tableMenu_RowMoveRowAbove: "Premesti red iznad",
	tableMenu_RowMoveRowBelow: "Premesti red ispod",
	tableMenu_RowDelete: "Brisanje",
	tableMenu_ColumnAddColumnBefore: "Dodaj kolonu ispred",
	tableMenu_ColumnAddColumnAfter: "Dodaj kolonu posle",
	tableMenu_ColumnMoveColumnAfter: "Premesti kolonu posle",
	tableMenu_ColumnMoveColumnBefore: "Premesti kolonu pre",
	tableMenu_ColumnDelete: "Brisanje",
	tableMenu_ColumnSortAscending: "Sortiraj po rastućem redosledu",
	tableMenu_ColumnSortDescending: "Sortiraj po opadajućem redosledu",
	tableMenu_Column: "Kolona",
	tableMenu_Delete: "Brisanje",
	presentationMenu: "Prezentacija",
	presentationMenu_SlideShow: "Pusti projekciju slajdova",
	presentationMenu_SlideShowFromCurrent: "Pusti od aktuelnog slajda",
	toolsMenu: "Alatke",
	toolsMenu_Task: "Zadatak",
	helpMenu: "Pomoć",
	helpMenu_Overview: "Sadržaj pomoći"
})

