/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2014. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
    root: ({
        spreadsheetTemplates: "Spreadsheet Templates",
        documentTemplates: "Document Templates",
        titleShareDocument: "Share Document",
        offline: "Offline",
        versionPublishing: "Publishing the version.",
        versionPublishFailed: "The version was not published. The file might be too large, or the server might have timed out. Try again, or cancel and ask your administrator to check the server log to identify the problem.",
        versionCheckinFailed: "The version was not checked in. The file might be too large, or the server might have timed out. Try again, or cancel and ask your administrator to check the server log to identify the problem.",
        versionSavedFailed: "Save did not complete. Try to Save again later.",
        publishFileSizeExceedMsg: "Cannot publish the file because it exceeds the maximum size set by your repository administrator. Delete some content to make the file smaller, or contact your administrator to increase the size limitation.",
        checkinFileSizeExceedMsg: "Cannot check in the file because it exceeds the maximum size set by your repository administrator. Delete some content to make the file smaller, or contact your administrator to increase the size limitation.",
        versionpublished: "Version published by ${0} at ${1}.",
        versionPublishing2: "Saving the version.",
        versionPublishFailed2: "The version was not saved. The file might be too large, or the server might have timed out. Try again, or cancel and ask your administrator to check the server log to identify the problem.",      
        publishFileSizeExceedMsg2: "Cannot save the file because it exceeds the maximum size set by your repository administrator. Delete some content to make the file smaller, or contact your administrator to increase the size limitation.",
        versionpublished2: "Version saved by ${0} at ${1}.",
        chekinCloseDocsMsg: "You can close ${productName} now.",
        draftSavingAs: "Copying file...",
        draftSavedAs: "The new copy is saved as ${0}.",
        synchronizing: "Wait while the synchronization operation with the server completes.",
        synchronizeError: "The synchronization operation with the server cannot complete.",
        joinwithoutentitle: "Users: ${0} want to edit the document, but cannot join the editing session because you are not entitled for co-editing.",
        joinwithoutentitle2: "Users: ${0} want to edit the document but cannot join the editing session, because they are not entitled for co-editing.",
        backtoFiles: "Open My Files",
        backtoCommFiles: "Open Community Files",
        backtoLibrary: "Open Library",
        backtoICN: "Open Content Navigator",
        backtoRepository: "Open Files List",
        createNewSpred: "Create a Spreadsheet",
        createNewDoc: "Create a Document",
        createNewDocFromTemp: "Create a Document from a Template",
        shareDoc: "Share a document",
        exportPdf: "Page Setup",
        insertDate: "Date Selection",
        insertTime: "Time Selection",
        connect: "Connect",
        theDoc: "the document",
        save: "Save Changes",
        saveBeforeReviewMsg: "You have unsaved changes. Save your changes and then Submit for Review again.",
        submitReviewWidgetsFaiure: "The application did not initialize correctly. Submit for Review again later.",
        widgetsFaiure: "The application did not initialize correctly.",
        slideSorter: "Slides",
        commentsBar: "Comments",
        draftBadge: "DRAFT",
        share: "Share",
        comment: "Comment",
        showSidebar: "Show Sidebar",
        publishVersion: "Publish",
        checkInVersion: "Check In",
        saveVersion: "Save",
        saved: "All changes saved",
        saving: "Saving",
        submitFragment: "Submit",
        aria_inMainMenu: "You are now in the main menu",
        aria_inSlideSorter: "You are now in the slide sorter view",
        aria_inSlideEditor: "You are now in the slide editor view",
        createNewPres: "Create a Presentation",
        createNewAppFromTemp: "Create a document from a template",
        textdoc: "text",
        sheetdoc: "spreadsheet",
        presdoc: "presentation",
        saveAsTextErrMsg: "The new text document cannot be saved.",
        saveAsPresErrMsg: "The new presentation document cannot be saved.",
        saveAsSheetErrMsg: "The new spreadsheet document cannot be saved.",
        saveAsTextErrMsg1: "There is not enough space to save the document.",
        saveAsPresErrMsg1: "There is not enough space to save the presentation.",
        saveAsSheetErrMsg1: "There is not enough space to save the spreadsheet.",
        newDocTextErrMsg: "A new text document cannot be created.",
        newDocSheetErrMsg: "A new spreadsheet document cannot be created.",
        newDocPresErrMsg: "A new presentation document cannot be created.",
        newDocTextErrMsg2: "A new text document cannot be created from the template.",
        newDocSheetErrMsg2: "A new spreadsheet document cannot be created from the template.",
        newDocPresErrMsg2: "A new presentation document cannot be created from the template.",
        newDocTextErrMsg3: "There is not enough space to create a document.",
        newDocSheetErrMsg3: "There is not enough space to create a spreadsheet.",
        newDocPresErrMsg3: "There is not enough space to create a presentation.",
        newDocTextErrMsg4: "There is already a document with that title. Provide a different title for the new document.",
        newDocSheetErrMsg4: "There is already a spreadsheet with that title. Provide a different title for the new spreadsheet.",
        newDocPresErrMsg4: "There is already a presentation with that title. Provide a different title for the new presentation.",        
        aclWarningTitle: "Cannot edit the new version",
        aclWarningMsg: "Because the file owner set protected areas in this file, it is best to edit it online. Contact the file owner (${0}) if you think that you really need to upload a new version.",
        aclWarningMsgForOwner: "There are protected areas in this file. So you will not be able to edit the uploaded new version online.  You must remove all protected areas in this file and then you can open and edit the uploaded new version.",
        st0: "Sheet1",
        st1: "Sheet2",
        st2: "Sheet3",
        FootnoteMsg: "Page",
        conflictMsg: "There is a conflict with what other editors are changing.  Your change is rescinded.",
        undoRedoConflictMsg: "The undo and redo operations have been suspended because of a conflict between what you are editing and what another person who is co-editing is working on",
        bigFileErrMsg: "The size of the document is too large. Refresh the browser to see if all of the content is intact",
        noPermissionMsg: "You do not have permission to edit this file. Contact the owner of the file to obtain edit permission and try again.",
        networkIssueMsg: "There is a network problem.",
        networkIssueTitle: "Network Problem",
        networkIssueContent: "There is a network problem. Refresh the page and try to get connected again.",
        lockEditorMsg: "The document cannot be edited until there is a connection with the server.",
        offlineReasonMsg: "Your session has timed out.",
        offlineReasonForServerUnacceptedMsg: "Unable to process some of your actions. Actions within 1 minute will be discarded by Docs server.",
        offlineReasonForServerDraftFormatChange: "The format of your document is out of date due to server upgrade.",
        reloadExplanationMsg: "Log in again to continue working.",
        reloadBtnLabel: "Reload",
        reconnectingMsg: "Wait while the connection is established with the server.",
        loadMsg: "Wait while the document is loading.",
        loadingDocumentMsg: "Wait while the document is loading from the server.",
        reLoadingDocumentMsg: "Wait while the document is reloading from the server.",
        unsupportMsg: "An unsupported feature is detected. See more details.",
        browserWorkingMsg: "Working...",
        fileDeepDetectTitle: "The file format and file extension do not match",
        fileDeepDetectMsg: "The file format is not the same format that is indicated by the file extension. Click Continue to edit the file in this format.",
        fileDeepDetectOkLabel: "Continue",
        tipInfo: "Tip: ${0}",
        selectTextInfo: "Select text to apply style.",
        removeRecentFile: "The file that you want to open was deleted. Do you want to remove the file name from the Recent Files list?",
        altLotusIcon: "",
        altErrorMsgIcon: "Error Message",
        altWarningMsgIcon: "Warning Message",
        altSuccessMsgIcon: "Success Message",
        sidebarLandmarkDesc: "sidebar",
        footerTitle: "footer",
        mainDesc: "content area",
        editLockedDocumentWarning: "You locked this file while others were editing it. Please work with them to coordinate changes or ask them to finish editing so you can have exclusive edit access.",
        observerMode: "You are now in Observer mode",
        editorMode: "You are now in editor mode",
        maxEditorLimitReached: "The document has reached the maximum number of editors of ${0} for this session. You can switch to editor mode when an editor leaves the document or switches to observer mode.",
        maxEditorLimitReachedTitle: "Maximum Number of Editors Reached",
        uploadNewVersionOpenConfirm: "${0} uploaded a new version at ${1} ${2}. Do you want open the new version?", //${0} name, ${1} time, ${2} date
        uploadNewVersionPublishConfirm: "${0} uploaded a new version at ${1} ${2}.", //${0} name, ${1} time, ${2} date
        you: "You",
        today: "today",
        yesterday: "yesterday",
        slideShowInviteMsg: "User ${0} has initiated a shared slide show. Do you wish to join?",
        slideShowInviteTitle: "Shared Slide Show Invitation",
        slideShowInviteTitle1: "Collective Slide Show Invitation",
        slideShowCoviewSelectUsersTitle: "Shared Slide Show",
        slideShowCoviewSelectUsersTitle1: "Collective Slide Show",
        slideShowCoviewStmt: "Share the current state of the presentation in a shared slide show.",
        slideShowCoviewStmt1: "Share the current state of the presentation in a collectiove slide show.",
        slideShowCoviewOptionOne: "Invite all editors to join the slide show.",
        slideShowCoviewOptionOne1: "Invite all editors and observers to join the slide show.",
        slideShowCoviewOptionTwo: "Invite only the following editors to join the slide show.",
        slideShowCoviewOptionTwo1: "Invite only the following editors and observers to join the slide show.",
        slideShowCoviewSlidesOf: "Slide ${0} of ${1}",  //as in Slide 1 of 4
        slideShowCoviewViewers: "${0} Viewers",
        slideShowCoviewDialogInput: "Type to filter name",
        slideShowCoviewAddTitle: "Add to Shared Slide Show",
        slideShowCoviewAddTitle1: "Add to Collective Slide Show",
        slideShowCoviewMessage: "Select additional users to invite to this shared slide show.",
        slideShowCoviewMessage1: "Select additional users to invite to this collective slide show.",
        slideShowCoviewEnded: "Shared Slide Show Ended",
        slideShowCoviewEndMessage: "The shared slide show you are trying to join is no longer available.",
        slideShowCoviewEndMessage2: "User ${0} has ended the shared slide show.",
        slideShowWarning: "You must close the current slide show before starting a new one.",
        slideShowHoverMsg: "Click to see who else is viewing the slide show.",
        slideShowHoverMsgAdd: "Click to invite more viewers.",
        csvEmpty: "Cannot export as .csv file because the sheet contains no data.",
        edit: "Edit",
        printToPDF: "Download as PDF",
        print: "Print",
        view: "View",
        openLatestFile: "Open the latest file",
        updateDocument: "The document was updated.${0}.",
        updateSpreadsheet: "The spreadsheet was updated.${0}",
        updatePresentation: "The presentation was updated.${0}.",
        labelCancel: "Cancel",
        msgConversionFail: "Conversion Failed",
        updateNow: "Open Now",
        fileUpdated: "The document updated",
        fileUpdatedContent1: "The document was updated. Open the latest file before you print.",
        htmlviewerlimitation1: "This spreadsheet contains pivot table that cannot be displayed",
        htmlviewerlimitation2: "This spreadsheet contains conditional formatting that cannot be displayed",
        htmlviewerlimitation3: "This spreadsheet contains pivot table and conditional formatting that cannot be displayed",
        close: "Close",
        closeDocs: "Close ${productName}",
        endSessionDlgTitle: "Editing session has ended",
        endSessionDlgNotice: "Your editing session has ended because ${0} has checked in the file.",
        labelStopReview: "Stop Review",
        labelRejct: "Reject",
        labelApprove: "Approve",
        errorMsg: "Error",
        labelItemNotFountTitle: "Cannot complete action.",
        labelItemNotFountMsg: "Another community member has already taken action on this document. For more information, close the document and go to the File Details page in your library.",
        viewProtectedAreas: "This spreadsheet contains protected areas. You should view or edit it online only.",
        macroTitle: "File contains a macro", 
        macroDesc: "Editing this file might break the macro. To prevent people from editing the range or sheet containing the macro, use Data > Protected Areas.",
        problem_id_msg_title: "Report this problem to your administrator. ",
        problem_id_msg_show: "Click to show details",
    	problem_id_msg_hide: "Click to hide",
    	uploadNewVersionWarningTitle: "Cannot edit the new version",
        changeHistoryWarningMsg: "Because the file owner has enabled Track Change in this file, it is best to edit it online. Contact the file owner (${0}) if you think that you really need to upload a new version.",
        changeHistoryWarningMsgForOwner: "There has Change History in this file. So you will not be able to edit the uploaded new version online.  You must clear Change History and disable Track Change in this file and then you can open and edit the uploaded new version.",
        viewChangeHistory: "This document contains change history. You should view or edit it online only.",
    	contentCorruptErrMsg: "Unable to load the content because it is corrupted. Contact your administrator for support."
    })
});
