/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2014. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
	service_unavailable_title: "الخدمة غير متاحة.",
	service_unavailable_content: "خدمة ${productName} غير متاحة. لا يمكن تشغيل الطلب الخاص بك فى هذا الوقت. حاول مرة أخرى لاحقا أو اتصل بموجه النظام الخاص بك.",
	access_denied_title: "تم رفض التوصل.",
	viewaccess_denied_content: "لا يتوافر لديك تصريح لمشاهدة هذا الملف. يمكن تعميم الملف أو يجب مشاركته معك.",
	editaccess_denied_content: "ليس لديك استحقاق استخدام ${productName} أو لا يوجد لديك التصريح لتحرير هذا الملف. يجب مشاركة الملف معك ويتم تحديد مستوى التوصل الى محرر. ربما أيضا يكون الملف مقفل بواسطة محرر أخر.",
	doc_notfound_title: "لم يتم ايجاد الوثيقة.",
	doc_notfound_content: "تم ازالة أو حذف الوثيقة التى تريد التوصل لها. تأكد من صحة الوصلة.",
	repository_out_of_space_title: "لا توجد مساحة كافية",
	repository_out_of_space_content: "لا يمكن نشر ${0} لأنك قد وصلت الى الحصة النسبية الخاصة بك لحجم الملف. قم بتخفيض الحصة النسبية الخاصة بك بنقل ملفات أخرى الى المحذوفات ثم حذفها.",
	fileconnect_denied_title: "تم رفض الاتصال.",
	fileconnect_denied_content: "لا يمكن الى ${productName} الاتصال بمستودع تخزين الملف. حاول مرة أخرى لاحقا أو اتصل بموجه النظام الخاص بك.",
	unscanned_document_title: "اتمام فحص الفيروسات",
	unscanned_document_content: "يتم اجراء مسح ضوئي آليا للملفات التي تم تحميلها الى Connections. يمكنك تحرير هذا الملف بمجرد اتمام عملية المسح الضوئي.",
	malicious_document_title: "ملف ضار",
	malicious_document_content: "لا يمكنك تحرير هذا الملف بسبب قيام Connections باكتشاف فيروس أثناء اجراء مسح ضوئي له.",	
	convservice_unavailable_title: "خدمة التحويل غير متاحة.",
	convservice_unavailable_content: "خدمة تحويل ${productName} غير متاحة. لا يمكن تشغيل الطلب الخاص بك فى هذا الوقت. حاول مرة أخرى لاحقا أو اتصل بموجه النظام الخاص بك.",
	doc_toolarge_title: "الملف كبير جدا.",
	doc_toolarge_content: "الوثيقة التى تريد التوصل لها كبيرة للغاية.",
	doc_toolarge_content2: "لا يمكن التوصل الى الملف. تتضمن الأسباب الممكنة:",
	doc_toolarge_content3: "لا يمكن عرض الملف، لأن حجم الملف أكبر من ${0} كيلوبايت. يمكنك تحميل الملف للتحرير. اذا كان الملف يحتوي على صور ذات درجة وضوح عالية، فانه يمكنك استبداله بواحد ذو درجة وضوح أقل لتقليل حجم الملف.",
	doc_toolarge_content4: "الملف كبير جدا بحيث يصعب مشاهدته هنا، ولكن مازال يمكنك فتحه بالضغط فوق مفتاح التحميل بخط العنوان.",
	doc_toolarge_content_mobile: "لا يمكن فتح الملفات. حجم الملف لا يمكن أن يكون أكبر من ${0} KB على جهاز التليفون المحمول.",
	sheet_toolarge_content: "حجم الجدول الحسابي أكبر من ${0} كيلوبايت.",
	sheet_toolarge_content2: "يحتوي الجدول الحسابي على أكثر من ${0} صف/صفوف بجدول واحد.",
	sheet_toolarge_content5: "يحتوي الجدول الحسابي على أكثر من ${0} عمود/أعمدة بجدول واحد.",
	sheet_toolarge_content3: "يحتوي الجدول الحسابي على أكثر من ${0} خانة/خانات.",
	sheet_toolarge_content4: "يحتوي الجدول الحسابي على أكثر من ${0} معادلة/معادلات.",
	text_toolarge_content: "حجم الوثيقة أكبر من ${0} كيلوبايت.",
	text_toolarge_content2:"تحتوي الوثيقة على أكثر من ${0} صفحة/صفحات.",
	text_toolarge_content3:"حجم النص بالوثيقة أكبر من ${0} كيلوبايت.",
	pres_toolarge_content: "لا يمكن التوصل الى العرض التقديمي، لأن حجم العرض التقديمي أكبر من ${0} كيلوبايت. اذا كان العرض التقديمي يحتوي على صور ذات درجة وضوح عالية، فانه يمكنك استبدالها بواحدة ذات درجة وضوح أقل لتقليل حجم العرض التقديمي.",
	pres_toolarge_content2: "لا يمكن التوصل الى العرض التقديمي، لأن العرض التقديمي يحتوي على أكثر من ${0} صفحات.",
	pres_toolarge_content3: "لا يمكن التوصل الى العرض التقديمي، لأن العرض التقديمي يحتوي على أكثر من ${0} عنصر.",
	pres_toolarge_content2_mobile: "لا يمكن فتح العرض التقديمي، لأنه يحتوى على أكثر من ${0} صفحة (صفحات) على جهاز متنقل.",
	pres_toolarge_content3_mobile: "لا يمكن فتح العرض التقديمي، لأنه يحتوي على أكثر من ${0} عنصر على الجهاز المتنقل.",
	sheet_view_toolarge_content1_mobile: "لا يمكن مشاهدة الجداول الحسابية، لأنها تحتوى على أكثر من ${0} صف (صفوف) على جهاز متنقل.",
	sheet_view_toolarge_content2_mobile: "لا يمكن مشاهدة الجداول الحسابية، لأنها تحتوى على أكثر من ${0} عمود (أعمدة) على جهاز متنقل.",
	sheet_view_toolarge_content3_mobile: "لا يمكن مشاهدة الجداول الحسابية، لأنها تحتوى على أكثر من ${0} صف (صفوف) و ${1} عمود (أعمدة) على جهاز متنقل.",
	conversion_timeout_title: "انتهى وقت تحويل الوثيقة.",
	conversion_timeout_content: "فى هذا الوقت، تستغرق الوثيقة مدة طويلة للتحويل. أعد المحاولة فيما بعد.",
	invalid_docformat_title: "لا يمكن فتح الوثيقة",
	invalid_docformat_content: "لاحقة الوثيقة صحيحة، ولكن لا يمكن قراءة المحتويات، اما لأنها تالفة أو مشفرة.",
	template_extension_conent_mismatch: "تقوم لاحقة ملف المصدر بتعريفه بطريقة غير صحيحة كقالب. الملف بنسق ‏‎.${0}‎‏ بالفعل. قم بالبدء بقالب صحيح أو حفظ هذا الملف باسم مختلف، باستخدام ‏‎.${0}‎‏ كلاحقة له.",
	invalid_docformat_title2: "لا يمكن استقبال الملف داخل ${productName}.",
	invalid_docformat_content2: "هناك شيء ما فى هذا الملف لا يدعمه ${productName} فى الوقت الحالى. لا يمكن استقبال هذا الملف.",
	invalid_doctype_title: "لا يتم دعم نوع الوثيقة.",
	invalid_doctype_content: "لا يتم دعم نوع الوثيقة بواسطة ${productName} حاليا.",
	unsupported_browser_title: "برنامج الاستعراض الخاص بك لا يدعم كل الخصائص",
	malformed_request_title: "الطلب تالف.",
	malformed_request_content: "تأكد أن عنوان URL والمعاملات صحيحة.",
	storageserver_error_title: "وحدة خدمة التخزين غير متاحة.",
	storageserver_error_content: "وحدة الخدمة غير متاحة حاليا. لا يمكن تشغيل الطلب الخاص بك فى هذا الوقت. حاول مرة أخرى لاحقا أو اتصل بموجه النظام الخاص بك.",
	document_already_opened_title: "الوثيقة مفتوحة بالفعل",
	document_already_opened_content:"تم فتح هذه الوثيقة بالفعل بواسطة برنامج الاستعراض الخاص بك.",
	toomany_documents_opened_inone_browser_title: "لا يمكن فتح الوثيقة",
	toomany_documents_opened_inone_browser_content:"يمكن فتح خمس ملفات ${productName} فى نفس الوقت. قم باغلاق الوثائق الأخرى وأعد محاولة فتح هذه الوثيقة مرة أخرى.",
	document_max_session_exceeded_title:"الخدمة غير متاحة.",
	document_max_session_exceeded_content:"هناك عدد كبير من المستخدمين يقومون بتحرير الوثائق على وحدة الخدمة، لا يمكن الاستمرار فى الطلب الخاص بك. أعد المحاولة فيما بعد.",
	kickout_user_content: "هذه الوثيقة مفتوحة بالفعل فى نافذة أخرى على الحاسب الآلى الخاص بك. ارجع الى النافذة الأخرى اذا كنت تريد الاستمرار فى تحرير الوثيقة.",
	return_to_files: "العودة الى الملفات",
	return_to_library: "العودة الى المكتبة",
	return_to_icn: "العودة الى Content Navigator",
	document_already_open: "الوثيقة مفتوحة بالفعل",
	cannotedit_noentitled_title: "لا يمكن المشاركة فى تحرير هذا الملف",
	cannotedit_noentitled_content1: "ما يلى من مستخدمين يقومون بتحرير الملف الآن:",
	cannotedit_noentitled_content2: "غير مصرح لك بتحرير هذا الملف بينما يقوم الآخرين بتحريره. حاول تحرير هذا الملف لاحقا.",
	cannotedit_noentitled_content3: "المستخدم التالى يقوم بتحرير الملف الآن:",
	cannotedit_noentitled_content4: "لا يمكنك الانضمام الى جلسة التحرير هذه، لأن المستخدم الذى يقوم بتحريره ليس مؤهلا للتحرير المشترك. حاول تحرير هذا الملف لاحقا.",
	toomany_coeditors_title: "كثير جدا من المستخدمين",
	toomany_coeditors_content: "يقوم عدة مستخدمين بتحرير هذه الوثيقة حاليا، يستطيع {0} مستخدم/مستخدمين فقط العمل بالوثيقة في نفس الوقت.",
	encrypted_pptdoc_title:"ملف مشفر ",
	encrypted_pptdoc_content:"هذا الملف تحت حماية كلمة سرية. لا يمكن تحريره في ${productName} ما لم يتم فك تشفيره أولا. ",
	server_busy_title:"وحدة الخدمة مشغولة",
	server_busy_content:"انتظر فترة من الوقت وأعد المحاولة لاحقا.",
	document_encrypt_title:"لا يتم دعم الوثيقة المشفرة",
	document_encrypt_content:"تم تشفير هذا الملف فى مستودع تخزين الملف. لاعتبارات خاصة بالسرية، تعذر على ${productName} تحريره بشكل مباشر.",
	edit_locked_file: "لا يمكنك تحرير هذا الملف لأنه تم اقفاله من قبل محررين آخرين.",
	publish_locked_file: "لا يمكنك نشر هذا الملف كنسخة جديدة لأنه مقفل، ومع ذلك، يتم حفظ المحتويات الخاصة بك آليا فى المسودة.",
	join_locked_file_session: "لا يمكنك الانضمام فى جلسة التحرير المشتركة لأن هذا الملف تم اقفاله من قبل آخرين.",
	no_need_to_convert_title:"لا حاجة الى التحويل",
	no_need_to_convert_content:"نسق الملف الذى تريد تحويله هو تماما ما تريد. يرجى تحميله مباشرة.",
	warning_icon: "شارة التحذير",
	//html viewer error message
	incorrect_web_address_title:"عنوان الانترنت غير صحيح.",
	incorrect_web_address_content:"عنوان الانترنت غير صحيح.  أدخل عنوان الانترنت وأعد المحاولة.",
	unexpecified_conversion_error_title:"الخطأ غير محدد.",
	unexpecified_conversion_error_content:"أرجعت وحدة الخدمة خطأ غير محدد.",
	encrypted_conversion_error_title:"لا يتم دعم الوثيقة المشفرة.",
	encrypted_conversion_error_content:"الملف تحت حماية كلمة سرية. لمشاهدة الملف فى برنامج المشاهدة،أولا تأكد أن الملف قد تم فك تشفيره.",
	service_busy_title:"فشل فتح الوثيقة",
	service_busy_content:"تعذر فتح الملف الذى تريد مشاهدته. ربما تكون وحدة الخدمة مشغولة أو غير متاحة. حاول مرة أخرى لاحقا أو اتصل بموجه النظام الخاص بك.",
	empty_doc_title: "الوثيقة خالية.",
	empty_doc_content: "تأكد أن الوثيقة تحتوى على المحتويات ثم أعد المحاولة.",
	corrupted_doc_title: "لا يمكن فتح الملفات.",
	corrupted_doc_content: "الملف يحتوى على محتويات لا يتم دعمها، على سبيل المثال الأوامر المركبة، وبالتالى لا يمكن مشاهدتها فى هذا التطبيق.",
	draft_storage_error_title: "لا يمكن فتح الوثيقة.",
	draft_storage_error_content: "لا يمكن تحميل المحتوى بسبب تلفه. اتصل بمسؤول النظام للحصول على الدعم.",
	unexpected_code_title: "وحدة خدمة ${productName} تقوم بارجاع كود غير متوقع.",
	unexpected_code_content: "وحدة خدمة ${productName} تقوم بارجاع كود غير متوقع.",
	request_time_out_title: "تحميل وثيقة انتهاء الوقت.",
	request_time_out_content: "يستغرق الأمر الكثير من الوقت لتحميل هذه الوثيقة. برجاء اعادة المحاولة لاحقا.",
	problem_id_msg_title: "ابلغ هذه المشكلة الى موجه النظام الخاص بك. ",
	problem_id_msg_show: "اضغط لعرض التفاصيل",
	problem_id_msg_hide: "اضغط للاخفاء"
})

