({
	delete_general: "Vymazať",
	order: "Poradie",
	align_text: "Zarovnať text",
	align_slide: "Zarovnať v snímke",
	align_objects: "Zarovnať vybraté objekty",
	zoom: "Priblíženie",
	zoom_fit: "Prispôsobiť oknu",
	insert_link: "Vložiť odkaz",
	add_link: "Pridať odkaz",
	open_link: "Otvoriť odkaz",
	edit_link: "Upraviť odkaz",
	remove_link: "Odstrániť odkaz",
	insert_link_menu: "Odkaz",
	invalid_url: "Nemožno otvoriť adresu URL. Skontrolujte správnosť adresy URL alebo nastavenia blokovania kontextových okien v prehliadači.",
	dnd_canceled_on_slide_event: "Snímku nemožno presunúť, pretože iný editor upravil prezentáciu. Skúste to znova neskôr.",
	rotate: "Otočiť",
	flipX: "Prevrátiť horizontálne",
	flipY: "Prevrátiť vertikálne",
	rotate_right: "Otočiť v smere pohybu hodinových ručičiek o 90&#x00B0",
	rotate_left: "Otočiť proti smeru pohybu hodinových ručičiek o 90&#x00B0",
	color_set_fill: "Nastaviť farbu výplne",
	color_nofill: "Žiadna výplň",
	color_nobackground: "Žiadne pozadie",
	color_auto: "Automaticky",
	color_default: "Štandardný",
	color_transparent: "Priesvitná",
	
	objects_distribute: "Distribuovať",
	objects_distribute_v: "Vertikálne",
	objects_distribute_h: "Horizontálne",
	
	link_subject: "Predmet:",
	link_text: "Text na zobrazenie:",
	link_mailto: "Otvoriť e-mail",
	link_goto: "Otvoriť odkaz",
	link_done: "Hotovo",
	link_remove: "Odstrániť",
	link_website: "Webová lokalita",
	link_email: "E-mail",
	link_slide: "Snímka",
	link_slide_placeholder: "Vyberte alebo zadajte číslo",
	link_slide_placeholder_deleted: "Prepojená snímka bola vymazaná",
	link_slide_next: "Ďalšia snímka",
	link_slide_prev: "Predošlá snímka",
	link_slide_first: "Prvá snímka",
	link_slide_last: "Posledná snímka",
	link_slide_number: "Snímka ${0}",
	link_not_support: "Nepodporovaný typ odkazu",
	link_acc_input: "Zadajte adresu odkazu",
	link_acc_mail_input: "Zadajte poštovú adresu",
	

	// Jaws Support
	acc_blank: "prázdne",// when selection is nothing but space char and empty paragraph
	acc_selected: " vybraté",
	acc_showed: " zobrazené",
	acc_inTable: " v riadku ${0}, stĺpci ${1} tabuľky ",
	acc_titleSelected: "vybratý nadpis",
	acc_subtitleSelected: "vybratý podnadpis",
	acc_outlineSelected: "vybratý obrys",
	acc_notesSelected: "vybraté poznámky rečníka",
	acc_imageSelected: "vybratá grafika",
	acc_shapeSelected: "vybratý tvar",
	acc_rotated: " otočené o ${0} stupňov",
	acc_tableSelected: "vybratá tabuľka",
	acc_textboxSelected: "vybraté textové pole",
	acc_enterEdit: " ak chcete upraviť, stlačte kláves Enter",
	acc_locked_by: " ktoré je zamknuté používateľom ${0}",
	acc_slide_used_by: " ktoré je používané používateľom ${0}",
	ACC_TABLE_TABLESIZE: "Vybrali ste ${0} riadkov a ${1} stĺpcov",
	ACC_TABLE_MAXSIZE: " Podporovaná maximálna veľkosť tabuľky je 8x8",
	ACC_EditorMode: "režim úpravy editora",
	ACC_EndEditorMode: "ukončiť režim úpravy editora",
	ACC_Table_new_row: "Bol pridaný nový riadok",
	ACC_Table_new_column: "Bol pridaný nový stĺpec",
	Acc_column: "stĺpec ${0}",
	acc_slide: "snímka ${0}",
	acc_editor: "Upravil ${0}",
	Plain: "Prostý",
	BlueStyle: "Modrý štýl",
	RedTint: "Červený odtieň",
	BlueHeader: "Modrá hlavička",
	DarkGrayHF: "Tmavosivá hlavička/päta",
	LightGrayRows: "Svetlosivé riadky",
	DarkGrayRows: "Tmavosivé riadky",
	BlueTint: "Modrý odtieň",
	RedHeader: "Červená hlavička",
	GreenHF: "Zelená hlavička/päta",
	PlainRows: "Prosté riadky",
	GrayTint: "Sivý odtieň",
	GreenTint: "Zelený odtieň",
	GreenHeader: "Zelená hlavička",
	RedHF: "Červená hlavička/päta",
	GreenStyle: "Zelený štýl",
	PurpleTint: "Purpurový odtieň",
	BlackHeader: "Čierna hlavička",
	PurpleHeader: "Purpurová hlavička",
	LightBlueHF: "Svetlomodrá hlavička/päta",
	
    formatMenu_LineSpacing: "Riadkovanie",
	linespaceboxTitle:"Vlastné riadkovanie",
	linespacelineTitle:"Riadok:",
	linespacenoticeContent :"Riadkovanie",
    formatMenu_LineSpacing_Customize: "Vlastné...",
    formatMenu_LineSpacing_CustomValue:"Vlastné: ${0}",
    lineSpaceWarning:"Zadajte číslo od 0 do 10",
    
    set_transparency_menu: "Opacita obrázka",
    opacity_percent_value: "${0}%",
    opacity_title: "Opacita",
    
    increaseLineWidthTip: "Zväčšiť hrúbku čiary",
	decreaseLineWidthTip : "Zmenšiť hrúbku čiary",
    setBorderStyleTip:"Nastaviť štýl čiary",
    line_width_title: "Hrúbka čiary",
    line_end_title: "Koncové body čiary",
    line_dash_title: "Vzor čiary",
    line_dash_type1: "Súvislá",
    line_dash_type2: "Hranaté body",
    line_dash_type3: "Pomlčky",
    line_dash_type4: "Okrúhle body",
    line_dash_type5: "Pomlčky a body",
    line_dash_type6: "Dlhé pomlčky",
    line_endpoints_type1: "Žiadny",
    line_endpoints_type2: "Jednoduchá šípka doprava",
	line_endpoints_type3: "Jednoduchá šípka doľava",
	line_endpoints_type4: "Jednoduchá dvojitá šípka",
	line_endpoints_type5: "Vyplnená šípka doprava",
	line_endpoints_type6: "Vyplnená šípka doľava",
    line_endpoints_type7: "Vyplnená dvojitá šípka",
    line_endpoints_type8: "Vyplnený kruh a šípka",
	line_endpoints_type9: "Vyplnený diamant a šípka",
	line_endpoints_type10: "Vyplnené diamanty",
    line_endpoints_type11: "Vyplnené kruhy"
})

