/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2014. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        spreadsheetTemplates: "Regnearksskabeloner",
        documentTemplates: "Dokumentskabeloner",
        titleShareDocument: "Del dokument",
        offline: "Offline",
        versionPublishing: "Publicerer versionen.",
        versionPublishFailed: "Versionen blev ikke publiceret. Filen er muligvis for stor, eller der er udløbet en tidsfrist på serveren. Prøv igen, eller annullér, og bed administratoren om at kontrollere serverloggen for at identificere problemet.",
        versionCheckinFailed: "Versionen blev ikke tjekket ind. Filen er muligvis for stor, eller der er udløbet en tidsfrist på serveren. Prøv igen, eller annullér, og bed administratoren om at kontrollere serverloggen for at identificere problemet.",
        versionSavedFailed: "Gemning blev ikke udført. Prøv igen senere.",
        publishFileSizeExceedMsg: "Kan ikke publicere filen, fordi den er større end den maksimale størrelse, der er angivet af lageradministratoren. Slet indhold for at gøre filen mindre, eller kontakt administratoren for at få øget størrelsesgrænsen.",
        checkinFileSizeExceedMsg: "Kan ikke tjekke filen ind, fordi den er større end den maksimale størrelse, der er angivet af lageradministratoren. Slet indhold for at gøre filen mindre, eller kontakt administratoren for at få øget størrelsesgrænsen.",
        versionpublished: "Version publiceret af ${0} ${1}.",
        versionPublishing2: "Gemmer versionen.",
        versionPublishFailed2: "Versionen blev ikke gemt. Filen er muligvis for stor, eller der er udløbet en tidsfrist på serveren. Prøv igen, eller annullér, og bed administratoren om at kontrollere serverloggen for at identificere problemet.",      
        publishFileSizeExceedMsg2: "Kan ikke gemme filen, fordi den er større end den maksimale størrelse, der er angivet af lageradministratoren. Slet indhold for at gøre filen mindre, eller kontakt administratoren for at få øget størrelsesgrænsen.",
        versionpublished2: "Version gemt af ${0} ${1}.",
        chekinCloseDocsMsg: "Du kan lukke ${productName} nu.",
        draftSavingAs: "Kopierer fil...",
        draftSavedAs: "Den nye kopi er gemt som ${0}.",
        synchronizing: "Vent, mens synkroniseringsfunktionen på serveren udføres.",
        synchronizeError: "Synkroniseringsfunktionen på serveren kan ikke udføres.",
        joinwithoutentitle: "Brugerne: ${0} vil redigere dokumentet, men kan ikke deltage i redigeringssessionen, fordi du ikke er berettiget til samredigering.",
        joinwithoutentitle2: "Brugerne: ${0} vil redigere dokumentet, men kan ikke deltage i redigeringssessionen, fordi de ikke er berettiget til samredigering.",
        backtoFiles: "Åbn Mine filer",
        backtoCommFiles: "Åbn Fællesskabsfiler",
        backtoLibrary: "Åbn Bibliotek",
        backtoICN: "Åbn Indholdsnavigator",
        backtoRepository: "Åbn Filliste",
        createNewSpred: "Opret et regneark",
        createNewDoc: "Opret et dokument",
        createNewDocFromTemp: "Opret et dokument fra en skabelon",
        shareDoc: "Del et dokument",
        exportPdf: "Sideopsætning",
        insertDate: "Datovalg",
        insertTime: "Klokkeslætsvalg",
        connect: "Tilslut",
        theDoc: "dokumentet",
        save: "Gem ændringer",
        saveBeforeReviewMsg: "Der er ændringer, der ikke er gemt. Gem dine ændringer, og afsend til gennemsyn igen.",
        submitReviewWidgetsFaiure: "Applikationen startede ikke korrekt. Send til gennemsyn igen senere.",
        widgetsFaiure: "Applikationen startede ikke korrekt.",
        slideSorter: "Dias",
        commentsBar: "Kommentarer",
        draftBadge: "KLADDE",
        share: "Del",
        comment: "Kommentar",
        showSidebar: "Vis sidelinje",
        publishVersion: "Publicér",
        checkInVersion: "Tjek ind",
        saveVersion: "Gem",
        saved: "Alle ændringer gemt",
        saving: "Gemmer",
        submitFragment: "Afsend",
        aria_inMainMenu: "Du er nu på hovedmenuen",
        aria_inSlideSorter: "Du er nu i diassorteringsoversigten",
        aria_inSlideEditor: "Du er nu i diaseditoroversigten",
        createNewPres: "Opret en præsentation",
        createNewAppFromTemp: "Opret et dokument fra en skabelon",
        textdoc: "tekst",
        sheetdoc: "regneark",
        presdoc: "præsentation",
        saveAsTextErrMsg: "Det nye tekstdokument kan ikke gemmes.",
        saveAsPresErrMsg: "Det nye præsentationsdokument kan ikke gemmes.",
        saveAsSheetErrMsg: "Det nye regnearksdokument kan ikke gemmes.",
        saveAsTextErrMsg1: "Der er ikke nok plads til at gemme dokumentet.",
        saveAsPresErrMsg1: "Der er ikke nok plads til at gemme præsentationen.",
        saveAsSheetErrMsg1: "Der er ikke nok plads til at gemme regnearket.",
        newDocTextErrMsg: "Et nyt tekstdokument kan ikke oprettes.",
        newDocSheetErrMsg: "Et nyt regnearksdokument kan ikke oprettes.",
        newDocPresErrMsg: "Et nyt præsentationsdokument kan ikke oprettes.",
        newDocTextErrMsg2: "Et nyt tekstdokument kan ikke oprettes på basis af skabelonen.",
        newDocSheetErrMsg2: "Et nyt regnearksdokument kan ikke oprettes på basis af skabelonen.",
        newDocPresErrMsg2: "Et nyt præsentationsdokument kan ikke oprettes på basis af skabelonen.",
        newDocTextErrMsg3: "Der er ikke nok plads til at oprette et dokument.",
        newDocSheetErrMsg3: "Der er ikke nok plads til at oprette et regneark.",
        newDocPresErrMsg3: "Der er ikke nok plads til at oprette en præsentation.",
        newDocTextErrMsg4: "Der findes allerede et dokument med dette navn. Angiv et andet navn til dette nye dokument.",
        newDocSheetErrMsg4: "Der findes allerede et regneark med dette navn. Angiv et andet navn til dette nye regneark.",
        newDocPresErrMsg4: "Der findes allerede en præsentation med dette navn. Angiv et andet navn til denne nye præsentation.",        
        aclWarningTitle: "Kan ikke redigere den nye version",
        aclWarningMsg: "Da filejeren har angivet beskyttede områder i denne fil, er det bedst at redigere den online. Kontakt filerejeren (${0}), hvis du mener, at der skal uploades en ny version.",
        aclWarningMsgForOwner: "Der er beskyttede områder i denne fil. Du kan ikke redigere den uploadede nye version online.  Du skal fjerne alle beskyttede områder i denne fil, og du kan derefter åbne og redigere den uploadede nye version.",
        st0: "Ark1",
        st1: "Ark2",
        st2: "Ark3",
        FootnoteMsg: "Side",
        conflictMsg: "Der er en konflikt med hensyn til, hvad andre redaktører ændrer.  Din ændring er annulleret.",
        undoRedoConflictMsg: "Fortryd- og Annullér Fortryd-funktionerne er midlertidigt standset pga. en konflikt mellem det, du redigerer, og det, som en anden person, der samredigerer, arbejder på.",
        bigFileErrMsg: "Dokumentet er for stort. Opfrisk browseren for at se, om alt indhold er intakt.",
        noPermissionMsg: "Du har ikke tilladelse til at redigere denne fil. Kontakt ejeren af filen for at få redigeringstilladelsen, og prøv igen.",
        networkIssueMsg: "Der er et netværksproblem.",
        networkIssueTitle: "Netværksproblem",
        networkIssueContent: "Der er et netværksproblem. Opfrisk siden, og prøv at oprette forbindelse igen.",
        lockEditorMsg: "Dokumentet kan ikke redigeres, før der er en forbindelse til serveren.",
        offlineReasonMsg: "Tidsfristen er udløbet for din session.",
        offlineReasonForServerUnacceptedMsg: "Kan ikke behandle nogle af dine handlinger. Handlinger vil inden for et 1 minut blive slettet af Docs-serveren.",
        offlineReasonForServerDraftFormatChange: "Dokumentformatet er forældet i forhold til serveropgraderingen.",
        reloadExplanationMsg: "Log på igen for at fortsætte arbejdet.",
        reloadBtnLabel: "Indlæs igen",
        reconnectingMsg: "Vent, mens der oprettes forbindelse til serveren.",
        loadMsg: "Vent, mens dokumentet indlæses.",
        loadingDocumentMsg: "Vent, mens dokumentet indlæses fra serveren.",
        reLoadingDocumentMsg: "Vent, mens dokumentet indlæses igen fra serveren.",
        unsupportMsg: "Der er registreret en ikke-understøttet funktion. Der er flere oplysninger.",
        browserWorkingMsg: "Arbejder...",
        fileDeepDetectTitle: "Filformatet og -typen passer ikke sammen",
        fileDeepDetectMsg: "Filformatet er ikke samme format, som er angivet via filtypen. Klik på Fortsæt for at redigere filen i dette format.",
        fileDeepDetectOkLabel: "Fortsæt",
        tipInfo: "Tip: ${0}",
        selectTextInfo: "Vælg tekst for at anvende typografi.",
        removeRecentFile: "Den fil, du vil åbne, er blevet slette. Vil du fjerne filnavnet fra listen over seneste filer?",
        altLotusIcon: "",
        altErrorMsgIcon: "Fejlmeddelelse",
        altWarningMsgIcon: "Advarselsmeddelelse",
        altSuccessMsgIcon: "Succesmeddelelse",
        sidebarLandmarkDesc: "sidelinje",
        footerTitle: "bundtekst",
        mainDesc: "indholdsområde",
        editLockedDocumentWarning: "Du har låst denne fil, mens andre redigerede den. Koordinér arbejdet med ændringer, eller bed de andre brugere om at afslutte redigeringen, så kun du har redigeringsadgang.",
        observerMode: "Du er nu i observationstilstand",
        editorMode: "Du er nu i redigeringstilstand",
        maxEditorLimitReached: "Dokumentet har nået til det maksimale antal redaktører af ${0} for denne session. Du kan skifte til redigeringstilstand, når en redaktør forlader dokumentet eller skifter til observationstilstand.",
        maxEditorLimitReachedTitle: "Det maksimale antal redaktører er nået",
        uploadNewVersionOpenConfirm: "${0} uploadede en ny version ${1} ${2}. Vil du åbne den nye version?", //${0} name, ${1} time, ${2} date
        uploadNewVersionPublishConfirm: "${0} uploadede en ny version ${1} ${2}.", //${0} name, ${1} time, ${2} date
        you: "Du",
        today: "i dag",
        yesterday: "i går",
        slideShowInviteMsg: "Brugeren ${0} har startet et delt diasshow. Vil du deltage?",
        slideShowInviteTitle: "Invitation til delt diasshow",
        slideShowInviteTitle1: "Invitation til kollektivt diasshow",
        slideShowCoviewSelectUsersTitle: "Delt diasshow",
        slideShowCoviewSelectUsersTitle1: "Kollektivt diasshow",
        slideShowCoviewStmt: "Del den aktuelle tilstand af præsentationen i et delt diasshow.",
        slideShowCoviewStmt1: "Del den aktuelle tilstand af præsentationen i et kollektivt diasshow.",
        slideShowCoviewOptionOne: "Invitér alle redaktører til at deltage i diasshowet.",
        slideShowCoviewOptionOne1: "Invitér alle redaktører og observatører til at deltage i diasshowet.",
        slideShowCoviewOptionTwo: "Invitér kun følgende redaktører til at deltage i diasshowet.",
        slideShowCoviewOptionTwo1: "Invitér kun følgende redaktører og observatører til at deltage i diasshowet.",
        slideShowCoviewSlidesOf: "Dias ${0} af ${1}",  //as in Slide 1 of 4
        slideShowCoviewViewers: "${0} seere",
        slideShowCoviewDialogInput: "Skriv for at filtrere navn",
        slideShowCoviewAddTitle: "Tilføj til delt diasshow",
        slideShowCoviewAddTitle1: "Tilføj til kollektivt diasshow",
        slideShowCoviewMessage: "Vælg yderligere brugere, der skal inviteres til dette delte diasshow.",
        slideShowCoviewMessage1: "Vælg yderligere brugere, der skal inviteres til dette kollektive diasshow.",
        slideShowCoviewEnded: "Delt diasshow er afsluttet",
        slideShowCoviewEndMessage: "Det delte diasshow, du forsøger at deltage i, er ikke længere tilgængeligt.",
        slideShowCoviewEndMessage2: "Brugeren ${0} har afsluttet det delte diasshow.",
        slideShowWarning: "Du skal lukke det aktuelle diasshow, før du starter et nyt.",
        slideShowHoverMsg: "Klik for at se, hvem der ellers ser dette diasshow.",
        slideShowHoverMsgAdd: "Klik for at invitere flere seere.",
        csvEmpty: "Kan ikke eksportere som .csv-fil, fordi arket ikke indeholder data.",
        edit: "Redigér",
        printToPDF: "Download som PDF",
        print: "Udskriv",
        view: "Vis",
        openLatestFile: "Åbn den seneste fil",
        updateDocument: "Dokumentet er opdateret.${0}.",
        updateSpreadsheet: "Regnearket er opdateret.${0}",
        updatePresentation: "Præsentationen er opdateret.${0}.",
        labelCancel: "Annullér",
        msgConversionFail: "Konvertering ikke udført",
        updateNow: "Åbn nu",
        fileUpdated: "Dokumentet er opdateret",
        fileUpdatedContent1: "Dokumentet er opdateret. Åbn den seneste fil, før du udskriver.",
        htmlviewerlimitation1: "Regnearket indeholder en pivottabel, der ikke kan vises.",
        htmlviewerlimitation2: "Regnearket indeholder betinget formatering, der ikke kan vises.",
        htmlviewerlimitation3: "Regnearket indeholder en pivottabel og betinget formatering, der ikke kan vises.",
        close: "Luk",
        closeDocs: "Luk ${productName}",
        endSessionDlgTitle: "Redigeringssessionen er afsluttet",
        endSessionDlgNotice: "Din redigeringssession er afsluttet, fordi ${0} har tjekket filen ind.",
        labelStopReview: "Stop gennemsyn",
        labelRejct: "Afvis",
        labelApprove: "Godkend",
        errorMsg: "Fejl",
        labelItemNotFountTitle: "Funktionen kunne ikke udføres.",
        labelItemNotFountMsg: "Et andet fællesskabsmedlem arbejder allerede med dette dokument. Hvis du vil have flere oplysninger, skal du lukke dokumentet og gå til siden Fildetaljer i dit bibliotek.",
        viewProtectedAreas: "Dette regneark indeholder beskyttede områder. Du bør kun få vist eller redigere det online.",
        macroTitle: "Filen indeholder en makro", 
        macroDesc: "Hvis filen redigeres, kan makroen blive ødelagt. Hvis du vil forhindre brugere i at redigere området eller arket med makroen, skal du bruge Data > Beskyttede områder.",
        problem_id_msg_title: "Rapportér dette problem til administratoren. ",
        problem_id_msg_show: "Klik for at få vist detaljer",
    	problem_id_msg_hide: "Klik for at skjule",
    	uploadNewVersionWarningTitle: "Kan ikke redigere den nye version",
        changeHistoryWarningMsg: "Da filejeren har aktiveret Spor ændring i denne fil, er det bedst at redigere den online. Kontakt filerejeren (${0}), hvis du mener, at der skal uploades en ny version.",
        changeHistoryWarningMsgForOwner: "Der er ændringshistorik i denne fil. Du kan ikke redigere den uploadede nye version online.  Du skal rydde ændringshistorikken og deaktivere Spor ændring i denne fil. Derefter kan du åbne og redigere den uploadede nye version.",
        viewChangeHistory: "Dette dokument indeholder ændringshistorik. Du bør kun få vist eller redigere det online.",
    	contentCorruptErrMsg: "Kan ikke indlæse indholdet, fordi det er ødelagt. Kontakt administratoren for at få hjælp."
});

