({
	COLUMN: "עמודה",
	CLUSTERED_COLUMN: "עמודות באשכול",
	STACKED_COLUMN: "עמודות מוערמות",
	BAR:"עמודים",
	CLUSTERED_BAR:"עמודים באשכול",
	STACKED_BAR: "עמודים מוערמים",
	PIE:"פלחים",
	SLICE: "פלח",
	AREA: "שטחים",
	STACKED_AREA: "שטחים מוערמים",
	LINE: "קווים",
	STACKED_LINE: "קווים מוערמים",
	MAKER_LINE: "קו עם סימונים",
	STACKED_MARKER_LINE: "קווים מוערמים עם סימונים",
	SCATTER: "פיזור",
	SCATTER_MARKER_ONLY: "פיזור עם סימונים בלבד",
	SCATTER_MARKER_LINE_S: "פיזור עם קווים חלקים וסימונים",
	SCATTER_LINE_S: "פיזור עם קווים חלקים", 
	SCATTER_MARKER_LINE_X: "פיזור עם קווים ישרים וסימונים",
	SCATTER_LINE_X: "פיזור עם קווים חלקים",
	ERROR_INVALID_RANGE:"טווח נתונים לא חוקי",
	TOO_MANY_POINTS: "לא ניתן ליצור תרשים הכולל מעל ${0} נקודות נתונים",
	CHART_TYPES:"סוגי תרשים",
	DATA:"נתונים",
	DATA_RANGE:"טווח נתונים",
	IN_ROWS:"סדרת נתונים בשורות",
	IN_COLUMNS:"סדרת נתונים בעמודות",
	AUTO:"אוטומטי"
})
