define({      
//begin v1.x content
	"clearFilterDialogTitle": "Limpar Filtro",
	"filterDefDialogTitle": "Filtrar",
	"defaultRuleTitle": "Regra",
	"ruleTitleTemplate": "Regra ${ruleNumber}",
	"noFilterApplied": "Nenhum filtro aplicado.",
	"defineFilter": "Definir filtro",
	"conditionEqual": "igual",
	"conditionNotEqual": "diferente",
	"conditionLess": "é menor que",
	"conditionLessEqual": "menor ou igual",
	"conditionGreater": "é maior que",
	"conditionGreaterEqual": "maior ou igual",
	"conditionContain": "contém",
	"conditionIs": "é",
	"conditionStartWith": "começa com",
	"conditionEndWith": "termina com",
	"conditionNotContain": "não contém",
	"conditionIsNot": "não é",
	"conditionNotStartWith": "não começa com",
	"conditionNotEndWith": "não termina com",
	"conditionBefore": "antes",
	"conditionAfter": "depois",
	"conditionRange": "intervalo",
	"conditionIsEmpty": "está vazio",
	"all": "todos",
	"any": "qualquer",
	"relationAll": "todas as regras",
	"waiRelAll": "Corresponde a todas as seguintes regras:",
	"relationAny": "qualquer regra",
	"waiRelAny": "Corresponde a quaisquer das seguintes regras:",
	"relationMsgFront": "Corresponder",
	"relationMsgTail": "",
	"and": "e",
	"or": "ou",
	"addRuleButton": "Incluir Regra",
	"waiAddRuleButton": "Incluir uma nova regra",
	"removeRuleButton": "Remover Regra",
	"waiRemoveRuleButtonTemplate": "Remover regra ${0}",
	"addRuleButton": "Incluir Regra de Filtro",
	"cancelButton": "Cancelar",
	"waiCancelButton": "Cancelar esse diálogo",
	"clearButton": "Limpar",
	"waiClearButton": "Limpar o filtro",
	"filterButton": "Filtrar",
	"waiFilterButton": "Enviar o filtro",
	"columnSelectLabel": "Coluna:",
	"waiColumnSelectTemplate": "Coluna para a regra ${0}",
	"conditionSelectLabel": "Condição:",
	"waiConditionSelectTemplate": "Condição para a regra ${0}",
	"valueBoxLabel": "Valor:",
	"waiValueBoxTemplate": "Insira o valor para filtrar a regra ${0}",
	"rangeTo": "até",
	"rangeTemplate": "de ${0} até ${1}",
	"statusTipHeaderColumn": "Coluna",
	"statusTipHeaderCondition": "Regras",
	"statusTipTitle": "Barra de Filtros",
	"statusTipMsg": "Clique na barra de filtros aqui para filtrar os valores em ${0}.",
	"anycolumn": "qualquer coluna",
	"statusTipTitleNoFilter": "Barra de Filtros",
	"statusTipTitleHasFilter": "Filtrar",
	"statusTipRelPre": "Corresponder",
	"statusTipRelPost": "regras.",
	"statusTipHeaderAll": "Corresponder todas as regras.",
	"statusTipHeaderAny": "Corresponder quaisquer regras.",
	"defaultItemsName": "itens",
	"filterBarMsgHasFilterTemplate": "${0} de ${1} ${2} mostradas.",
	"filterBarMsgNoFilterTemplate": "Nenhum filtro aplicado",
	"filterBarDefButton": "Definir filtro",
	"waiFilterBarDefButton": "Filtrar a tabela",
	"a11yFilterBarDefButton": "Filtrar...",
	"filterBarClearButton": "Limpar filtro",
	"waiFilterBarClearButton": "Limpar o filtro",
	"closeFilterBarBtn": "Fechar a barra de filtros",
	"clearFilterMsg": "Isso removerá o filtro e mostrará todos os registros disponíveis.",
	"anyColumnOption": "Qualquer Coluna",
	"trueLabel": "Verdadeiro",
	"falseLabel": "Falso",
	"radioTrueLabel": "Valor Verdadeiro",
	"radioFalseLabel": "Valor Falso",
	"beginTimeRangeLabel": "Valor de Início do Intervalo de Tempo",
	"endTimeRangeLabel": "Valor de Término do Intervalo de Tempo",
	"beginDateRangeLabel": "Valor de Início do Intervalo de Data",
	"endDateRangeLabel": "Valor de Término do Intervalo de Data",
	"startsWithExpr": "${0}*"
//end v1.x content
});

