({	
	createTaskSummary: "${0} a créé la tâche.",
	completeTaskSummary: "${0} a marqué la tâche comme terminée.",
	editTaskSummary5: "${0} a édité les tâches ${1}, ${2}, ${3} ${4} et ${5}.",
	editTaskSummary4: "${0} a édité les zones ${1}, ${2}, ${3} et ${4} de la tâche.",
	editTaskSummary3: "${0} a édité les zones ${1}, ${2} et ${3} de la tâche.",
	editTaskSummary2: "${0} a édité les zones ${1} et ${2} de la tâche.",
	editTaskSummary1: "${0} a édité la zone ${1} de la tâche.",
	editTaskSummary0: "${0} a édité la tâche.",
	removeTaskSummary: "${0} a supprimé la tâche.",
	reopenTaskSummary: "${0} a réouvert la tâche.",
	reassignTaskSummary: "${0} a réaffecté ${1} de ${2} à ${3}.",
	reassignTaskSummary2: "${0} a réaffecté le destinataire de l'affectation de ${1} à ${2}, et le réviseur, de ${3} à ${4}.",
	workPrivateSummary: "${0} a commencé à travailler en privé sur cette tâche.",
	approveTaskSummary: "${0} a approuvé cette tâche.",
	rejectTaskSummary: "${0} a rejeté cette tâche.",
	rejectTaskSummary2: "${0} a renvoyé cette tâche à ${1} pour réécriture.",
	submitTaskSummary: "${0} a soumis des modifications privées en retour dans le document.",
	cancelPrivateSummary: "${0} a annulé le travail privé.",
	updatedFieldsDesc: "${0}: ${1} -> ${2}",
	fieldAssignee: "destinataire",
	fieldDuedate: "date d'échéance",
	fieldDescription: "description",
	fieldReviewer: "réviseur",
	fieldTitle: "titre",
	emptyFieldValue: "[Non affecté]",
	errorAddMember:"L'accès actuel au serveur d'activité ne permet pas d'ajouter des destinataires d'affectation ou des réviseurs. Réessayez plus tard.",
	errorCreateActivity:"L'accès actuel au serveur d'activité ne permet pas de créer l'activité. Réessayez plus tard.",
	errorLoadActivity:"L'accès actuel au serveur d'activité ne permet pas de charger des affectations. Réessayez plus tard.",
	errorCreateAssignment: "L'accès actuel au serveur d'activité ne permet pas de créer l'affectation. Réessayez plus tard.",
	errorDeleteAssignment: "L'accès actuel au serveur d'activité ne permet pas de supprimer des affectations. Réessayez plus tard.",
	errorupdateAssignment: "L'accès actuel au serveur d'activité ne permet pas de mettre à jour des affectations. Réessayez plus tard.",
	errorSubmitAssignment: "Vous ne pouvez pas effectuer cette action .Vérifiez si vous disposez des droits nécessaires.",	
	errorAddMember2:"L'accès actuel au serveur ne permet pas d'ajouter des destinataires d'affectation ou des réviseurs. Réessayez plus tard.",
	errorCreateActivity2:"L'accès actuel au serveur ne permet pas de créer l'activité. Réessayez plus tard.",
	errorLoadActivity2:"L'accès actuel au serveur ne permet pas de charger des affectations. Réessayez plus tard.",
	errorCreateAssignment2: "L'accès actuel au serveur ne permet pas de créer l'affectation. Réessayez plus tard.",
	errorDeleteAssignment2: "L'accès actuel au serveur ne permet pas de supprimer des affectations. Réessayez plus tard.",
	errorupdateAssignment2: "L'accès actuel au serveur ne permet pas de mettre à jour des affectations. Réessayez plus tard."	
})
