({
	stViewClient:"Tampilkan Klien Sametime",
	stChatList:"Klik untuk membuka klien Web Sametime di dalam jendela baru.",
	stWebClient:"HCL Sametime ",
	stStatusMeeting:"Sedang Rapat",
	stStatusAvailable:"Saya Ada",
	stViewBd:"Tampilkan Daftar Sametime Buddy",
	stErrorSTServer:"Kesalahan menyambungkan ke Sametime",
	stStatusAway:"Saya sedang Pergi",
	stLConnLogIn:"Masuk ke HCL Connections untuk melihat status Sametime",
	stActionBar:"Bilah Tindakan Sametime",
	stStatusBusy:"Saya sedang Sibuk",
	stLogin:"Login ke Sametime",
	stUserOffline:"Saya sedang offline",
	stStartChat:"Klik di sini untuk memulai percakapan",
	stLogout:"Logout dari Sametime",
	stDisconnect:"Putuskan sambungan dari Sametime",
	stViewSTActions:"Klik untuk melihat tindakan Sametime",
	stError:"Terjadi kesalahan. Layanan Sametime tidak tersedia.",
	stUnableToConnect:"Sambungan ke Sametime tidak tersedia. ",
	stConnect:"Sambungkan ke Sametime",
	stNoStatuAvailable:"Tidak ada status Sametime yang tersedia",
	stStatusdnt:"Jangan Mengganggu",
	stLoadingSTStatus:"Memuat status Sametime...",
	stShareAs:"Membagikan Dokumen...",
	stShareDlgTitle:"Bagikan Dokumen melalui Sametime...",
	stShareDlgMsgTemplate:"Apakah Anda ingin 'membagikan ${file_name}' dengan ${contact_name} sebagai Penyunting atau Pembaca?",
	stShareEditor:"Penyunting",
	stShareReader:"Pembaca",
	stShareSuccessTemplate:"${contact_name}, Saya ingin membagikan dokumen '${file_name}' dengan Anda:\n<a href=\"${document_link}\">${document_link}</a>"
})
