({	
	dlgTaskCreateTitle: "Tildel en sektion",  
	dlgTaskDeleteTitle: "Fjern en sektion", 
	dlgTaskEditTitle: "Redigér tildeling",
	dlgTaskRewordTitle: "Omarbejd tildeling",
	dlgTaskHistoryTitle: "Om denne sektion",
	dlgTaskReopenTitle: "Åbn tildeling igen",
	dlgTaskReassignTitle: "Tildel sektion igen",
	dlgTaskDeleteBtn: "Slet",
	creatingTaskAsTODO: "Din tildeling gemmes som en opgave i applikationen Aktiviteter.",
	creatingTaskAsTODO2: "Tildelingen er gemt",
	creatingTaskAsTODO3: "Tildelingerne er gemt",
	updatingTask: "Din tildeling opdateres i programmet Aktiviteter",
	updatingTask2: "Tildelingen opdateres",
	updatingTask3: "Tildelingerne opdateres",
	restoringTask: "Vent, mens din tildeling gendannes i aktiviteten.",
	creatingFragment: "Et privat dokument oprettes til denne sektion",
	updatingMaster: "Behandler... Sektionen opdateres i det primære dokument",
	cannotAccessActivity: "Fejl. Der er ingen adgang til aktivitetsserveren, så tildelingerne kan registreres. Prøv igen senere.",
	cannotAccessActivity2: "Fejl. Der er ingen adgang til serveren, så tildelingerne kan registreres. Prøv igen senere.",
	cannotAccessActivityContent: "Der er ingen adgang til aktivitetsserveren, så tildelingerne kan registreres. Prøv igen senere.",
	cannotRecordAssignment: "Der er ingen adgang til aktivitetsserveren, så tildelingerne kan registreres. Prøv igen senere.",
	notMemberofActivity: "Aktiviteten kan ikke registrere din tildeling. Kontrollér, at du er tilføjet til aktiviteten, og prøv igen.",
	cannotLoadActivity: "Der er ingen adgang til aktivitetsserveren, så tildelingerne kan indlæses. Prøv igen senere.",
	cannotLoadActivity2: "Der er ingen adgang til serveren, så tildelingerne kan indlæses. Prøv igen senere.",
	cannotLoadAssignment: "Der er ingen adgang til aktivitetsserveren, så tildelingerne kan indlæses. Prøv igen senere.",
	cannotSupportSocialEdit: "Du er ikke berettiget til at samredigere eller tildele sektioner.",
	cannotDeleteDraft: "Kladden kan ikke slettes på nuværende tidspunkt. Slet filen senere manuelt.",
	taskAlreadyRemoved: "Opgaven til dette dokument er fjernet, eller også har du ikke tilladelse til at redigere opgaven.",
	taskAlreadyCompleted: "Opgaven er færdig eller annulleret.",
	taskAlreadyReassigned: "Opgaven er tildelt igen.",
	assignmentAlreadyExist: "Det valgte område er tidligere tildelt.",
	notAllowedEditMaster: "Du kan ikke redigere det primære dokument. Kontrollér, om du har tilladelse til at gøre det.",
	notAllowedEditPaticipant: "Den tildelte eller korrekturlæseren er ikke defineret eller har ikke redigeringsadgang. Kontrollér, at den tildelte eller korrekturlæseren har den korrekte adgang.",
	notValidAssignment: "Tildelingen er ugyldig, nogle af tildelingsegenskaberne på aktivitetsserveren er eventuelt ødelagt. Du kan fjerne tildelingen ved at klikke på Handlinger > Fjern tildeling",
	disableBlockerMsg: "Du har en pop op-blokeringsfunktion aktiveret, der forhindrer siden i at blive vist korrekt.  Tillad pop op-vinduer at blive vist i forbindelse med *cn.ibm.com-webstedet.",
	writeDesc: "Skriv ${0}: ${1}",
	reviewDesc: "Gennemse ${0}: ${1}",
	reworkDesc: "Gennemgå ${0}: ${1}",
	writeCompleteDesc: "Sektion ${0} skrevet af ${1}",
	reviewCompleteDesc: "Sektion ${0} gennemset af ${1}",
	workingPrivateDesc: "Arbejder privat på ${0} af ${1}",
	actions: "Handlinger",	
	onlyAssignerDeleteTask: "Du kan ikke slette denne tildeling, som ikke er markeret som udført. Kun den person, der tildelte den, kan slette den.",
	actionBtnEdit: "Redigér tildeling",
	actionBtnRemove: "Fjern tildeling",
	actionBtnAbout: "Om denne sektion",
	actionBtnMarkComplete: "Markér som udført",
	actionBtnWorkPrivately: "Arbejd privat",
	actionBtnApprove: "Godkend denne sektion",
	actionBtnGotoPrivate: "Gå til Privat dokument",
	actionBtnCancelPrivate: "Annullér privat arbejde",
	actionBtnRework: "Omarbejde er påkrævet",
	actionBtnReopen: "Åbn tildeling igen",
	actionBtnReassign: "Tildel sektion igen",
	creating: "Opretter...",
	deleting: "Sletter...",
	updating: "Opdaterer...",
	loading: "Indlæser...",
	restoring: "Gendanner...",
	lockCoeditingTask:"En anden editor arbejder på den samme tildeling. Prøv igen senere."
})
