({
	delete_general: "Wissen",
	order: "Volgorde",
	align_text: "Tekst uitlijnen",
	align_slide: "Uitlijnen in dia",
	align_objects: "Geselecteerde objecten uitlijnen",
	zoom: "In-/uitzoomen",
	zoom_fit: "Hele pagina",
	insert_link: "Link invoegen",
	add_link: "Link toevoegen",
	open_link: "Link openen",
	edit_link: "Link bewerken",
	remove_link: "Link verwijderen",
	insert_link_menu: "Link",
	invalid_url: "De URL kan niet worden geopend. Controleer of de URL juist is en of in de browser popup-blokkering is ingesteld.",
	dnd_canceled_on_slide_event: "De dia kan niet worden verplaatst, want een andere editor heeft de presentatie recent gewijzigd. Probeer het later nog eens.",
	rotate: "Draaien",
	flipX: "Horizontaal spiegelen",
	flipY: "Verticaal spiegelen",
	rotate_right: "Met de klok mee draaien 90&#x00B0",
	rotate_left: "Tegen de klok in draaien 90&#x00B0",
	color_set_fill: "Vulkleur instellen",
	color_nofill: "Geen vulling",
	color_nobackground: "Geen achtergrond",
	color_auto: "Auto",
	color_default: "Standaard",
	color_transparent: "Transparant",
	
	objects_distribute: "Distribueren",
	objects_distribute_v: "Verticaal",
	objects_distribute_h: "Horizontaal",
	
	link_subject: "Onderwerp:",
	link_text: "Af te beelden tekst :",
	link_mailto: "E-mail openen",
	link_goto: "Link openen",
	link_done: "Gereed",
	link_remove: "Verwijderen",
	link_website: "Website",
	link_email: "E-mail",
	link_slide: "Dia",
	link_slide_placeholder: "Selecteer een getal of voer het in",
	link_slide_placeholder_deleted: "Gekoppelde dia is gewist",
	link_slide_next: "Volgende dia",
	link_slide_prev: "Vorige dia",
	link_slide_first: "Eerste dia",
	link_slide_last: "Laatste dia",
	link_slide_number: "Dia ${0}",
	link_not_support: "Niet-ondersteund linktype",
	link_acc_input: "Invoer linkadres",
	link_acc_mail_input: "Invoer mailadres",
	

	// Jaws Support
	acc_blank: "blanco",// when selection is nothing but space char and empty paragraph
	acc_selected: " geselecteerd",
	acc_showed: " afgebeeld",
	acc_inTable: " in tabel, rij ${0} kolom ${1} ",
	acc_titleSelected: "titel geselecteerd",
	acc_subtitleSelected: "subtitel geselecteerd",
	acc_outlineSelected: "kader geselecteerd",
	acc_notesSelected: "speakersnotities geselecteerd",
	acc_imageSelected: "afbeelding geselecteerd",
	acc_shapeSelected: "vorm geselecteerd",
	acc_rotated: " ${0} graden geroteerd",
	acc_tableSelected: "tabel geselecteerd",
	acc_textboxSelected: "tekstvak geselecteerd",
	acc_enterEdit: " druk op enter om te bewerken",
	acc_locked_by: " die is vergrendeld door gebruiker ${0}",
	acc_slide_used_by: " die wordt gebruikt door gebruiker ${0}",
	ACC_TABLE_TABLESIZE: "U hebt ${0} rijen en ${1} kolommen geselecteerd.",
	ACC_TABLE_MAXSIZE: " De maximale tabelgrootte 8*8",
	ACC_EditorMode: "bewerkingsmodus voor editor",
	ACC_EndEditorMode: "bewerkingsmodis voor editor beëindigen",
	ACC_Table_new_row: "Er is een nieuwe rij toegevoegd",
	ACC_Table_new_column: "Er is een nieuwe kolom toegevoegd",
	Acc_column: "kolom ${0}",
	acc_slide: "dia ${0}",
	acc_editor: "Bewerken door ${0}",
	Plain: "Standaard",
	BlueStyle: "Blauwe stijl",
	RedTint: "Rode tint",
	BlueHeader: "Blauwe koptekst",
	DarkGrayHF: "Donkergrijze koptekst/voettekst",
	LightGrayRows: "Lichtgrijze rijen",
	DarkGrayRows: "Donkergrijze rijen",
	BlueTint: "Blauwe tint",
	RedHeader: "Rode koptekst",
	GreenHF: "Groene koptekst/voettekst",
	PlainRows: "Losse rijen",
	GrayTint: "Grijze tint",
	GreenTint: "Groene tint",
	GreenHeader: "Groene koptekst",
	RedHF: "Rode koptekst/voettekst",
	GreenStyle: "Groene stijl",
	PurpleTint: "Paarse tint",
	BlackHeader: "Zwarte koptekst",
	PurpleHeader: "Paarse koptekst",
	LightBlueHF: "Lichtblauwe koptekst/voettekst",
	
    formatMenu_LineSpacing: "Regelafstand",
	linespaceboxTitle:"Aangepaste regelafstand",
	linespacelineTitle:"Regel:",
	linespacenoticeContent :"Regelafstand",
    formatMenu_LineSpacing_Customize: "Aangepast...",
    formatMenu_LineSpacing_CustomValue:"Aangepast: ${0}",
    lineSpaceWarning:"Voer een getal tussen 0 en 10 in",
    
    set_transparency_menu: "Ondoorzichtigheid van afbeelding",
    opacity_percent_value: "${0}%",
    opacity_title: "Ondoorzichtigheid",
    
    increaseLineWidthTip: "Lijndikte verhogen",
	decreaseLineWidthTip : "Lijndikte verlagen",
    setBorderStyleTip:"Lijnstijl instellen",
    line_width_title: "Lijndikte",
    line_end_title: "Lijneindpunten",
    line_dash_title: "Lijnenpatroon",
    line_dash_type1: "Ononderbroken",
    line_dash_type2: "Vierkante stippen",
    line_dash_type3: "Streepjes",
    line_dash_type4: "Ronde stippen",
    line_dash_type5: "Streepjes en stippen",
    line_dash_type6: "Lange streepjes",
    line_endpoints_type1: "Geen",
    line_endpoints_type2: "Enkele pijl naar rechts",
	line_endpoints_type3: "Enkele pijl naar links",
	line_endpoints_type4: "Enkele tabpijl",
	line_endpoints_type5: "Opgevulde pijl naar rechts",
	line_endpoints_type6: "Opgevulde pijl naar links",
    line_endpoints_type7: "Opgevulde tabpijl",
    line_endpoints_type8: "Opgevulde cirkel en pijl",
	line_endpoints_type9: "Opgevulde ruit en pijl",
	line_endpoints_type10: "Opgevulde ruitjes",
    line_endpoints_type11: "Opgevulde cirkels"
})

