({
	stViewClient:"Pokaži Sametime klijent",
	stChatList:"Kliknite za otvaranje Sametime web klijenta u novom prozoru",
	stWebClient:"HCL Sametime ",
	stStatusMeeting:"Na sastanku",
	stStatusAvailable:"Dostupan sam",
	stViewBd:"Pokaži listu Sametime prijatelja",
	stErrorSTServer:"Greška povezivanja sa Sametimeom",
	stStatusAway:"Odsutan sam",
	stLConnLogIn:"Prijavite se na HCL Connections za pregled Sametime statusa",
	stActionBar:"Sametime traka akcija",
	stStatusBusy:"Zauzet sam",
	stLogin:"Prijavite se na Sametime",
	stUserOffline:"Nisam u mreži",
	stStartChat:"Kliknite ovdje za pokretanje razgovora",
	stLogout:"Odjava iz Sametimea",
	stDisconnect:"Prekid veze sa Sametimeom",
	stViewSTActions:"Kliknite za pregled Sametime akcija",
	stError:"Pojavila se greška. Usluga Sametime nije dostupna.",
	stUnableToConnect:"Veza sa Sametimeom nije dostupna. ",
	stConnect:"Povezivanje sa Sametimeom",
	stNoStatuAvailable:"Sametime status nije dostupan",
	stStatusdnt:"Ne ometaj",
	stLoadingSTStatus:"Učitavanje Sametime statusa...",
	stShareAs:"Dijeli dokument...",
	stShareDlgTitle:"Dijeljenje dokumenta putem Sametimea...",
	stShareDlgMsgTemplate:"Želite li 'podijeliti ${file_name}' s ${contact_name} kao urednik ili čitač?",
	stShareEditor:"Urednik",
	stShareReader:"Čitač",
	stShareSuccessTemplate:"${contact_name}, želim podijeliti dokument '${file_name}' s tobom:\n<a href=\"${document_link}\">${document_link}</a>"
})

