/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
    Arrow01_Gray: "Seta 01 Cinza",
    Arrow02_Gray: "Seta 02 Cinza",
    Arrow03_Red: "Seta 03 Vermelha",
    Arrow04_Blue: "Seta 04 Azul",
    Arrow05_Blue: "Seta 05 Azul",
    Arrow06_Yellow: "Seta 06 Amarela",
    Arrow07_Red: "Seta 07 Vermelha",
    Arrow08_Gray: "Seta 08 Cinza",
    Arrow09_Orange: "Seta 09 Laranja",
    Arrow10_Blue: "Seta 10 Azul",
    Arrow11_Blue: "Seta 11 Azul",
    Arrow12_Green: "Seta 12 Verde",
    Arrow13_Blue: "Seta 13 Azul",
    Arrow14_Green: "Seta 14 Verde",
    Arrow15_Orange: "Seta 15 Laranja",
    Arrow16_Gray: "Seta 16 Cinza",
    CircleArrow01_Green: "Seta Circular 01 Verde",
    CircleArrow02_Multi: "Seta Circular 02 Multi",
    CircleArrow03_Multi: "Seta Circular 03 Multi",
    CircleArrow04_Multi: "Seta Circular 04 Multi",
    CircleArrow05_Multi: "Seta Circular 05 Multi",
    CircleArrow06_Multi: "Seta Circular 06 Multi",
    CircleArrow07_Blue: "Seta Circular 07 Azul",
    CircleArrow08_Green: "Seta Circular 08 Verde",
    CircleArrow09_Multi: "Seta Circular 09 Multi",
    CurvedArrow01_Gray: "Seta Curvada 01 Cinza",
    CurvedArrow02_Blue: "Seta Curvada 02 Azul",
    CurvedArrow03_Blue: "Seta Curvada 03 Azul",
    CurvedArrow04_Orange: "Seta Curvada 04 Laranja",
    CurvedArrow05_Red: "Seta Curvada 05 Vermelha",
    CurvedArrow06_Blue: "Seta Curvada 06 Azul",
    CurvedArrow07_Purple: "Seta Curvada 07 Púrpura",
    CurvedArrow08_Green: "Seta Curvada 08 Verde",
    CurvedArrow09_Gray: "Seta Curvada 09 Cinza",
    CurvedArrow10_Blue: "Seta Curvada 10 Azul",
    CurvedArrow11_Orange: "Seta Curvada 11 Laranja",
    CurvedArrow12_Blue: "Seta Curvada 12 Azul",
    CurvedArrow13_Green: "Seta Curvada 13 Verde",
    CurvedArrow14_Brown: "Seta Curvada 14 Marrom",
    CurvedArrow15_Blue: "Seta Curvada 15 Azul",
    CurvedArrow16_Gray: "Seta Curvada 16 Cinza",
    CurvedArrow17_Gray: "Seta Curvada 17 Cinza",
    CurvedArrow18_Gray: "Seta Curvada 18 Cinza",
    CurvedArrow19_Gray: "Seta Curvada 19 Cinza",
    CurvedArrow20_Gray: "Seta Curvada 20 Cinza",
    TrendArrow01_Red: "Seta de Tendência 01 Vermelha",
    TrendArrow02_Green: "Seta de Tendência 02 Verde",
    TrendArrow03_Orange: "Seta de Tendência 03 Laranja",
    TrendArrow04_Red: "Seta de Tendência 04 Vermelha",
    TrendArrow05_Orange: "Seta de Tendência 05 Laranja",
    TrendArrow06_Blue: "Seta de Tendência 06 Azul",
    TrendArrow07_Orange: "Seta de Tendência 07 Laranja",
    TrendArrow08_Yellow: "Seta de Tendência 08 Amarela",
    TrendArrow09_Blue: "Seta de Tendência 09 Azul",
    TrendArrow10_Blue: "Seta de Tendência 10 Azul",
    TrendArrow11_Blue: "Seta de Tendência 11 Azul",
    TrendArrow12_Blue: "Seta de Tendência 12 Azul",
    TrendArrow13_Red: "Seta de Tendência 13 Vermelha",
    TrendArrow14_Multi: "Seta de Tendência 14 Multi",
    TrendArrow15_Blue: "Seta de Tendência 15 Azul",
    Bullet01_Circle_DarkRed: "Marcador de Círculo 01 Vermelho Escuro",
    Bullet02_Circle_Blue: "Marcador de Círculo 02 Azul",
    Bullet03_Circle_Green: "Marcador de Círculo 03 Verde",
    Bullet04_Square_Black: "Marcador de Quadrado 04 Preto",
    Bullet05_Square_Orange: "Marcador de Quadrado 05 Laranja",
    Bullet06_Square_Purple: "Marcador de Quadrado 06 Púrpura",
    Bullet07_Diamond_Blue: "Marcador de Losango 07 Azul",
    Bullet08_Diamond_LightBlue: "Marcador de Losango 08 Azul Claro",
    Bullet09_Diamond_Red: "Marcador de Losango 09 Vermelho",
    Bullet10_Star_Yellow: "Marcador de Estrela 10 Amarelo",
    Bullet11_Star_Blue: "Marcador de Estrela 11 Azul",
    Bullet12_Triangle_Blue: "Marcador de Triângulo 12 Azul",
    Bullet13_Triangle_DarkGreen: "Marcador de Triângulo 13 Verde Escuro",
    Bullet14_Arrow_Red: "Marcador de Seta 14 Vermelho",
    Bullet15_Arrow_Blue: "Marcador de Seta 15 Azul",
    Bullet16_Box_Blue: "Marcador de Caixa 16 Azul",
    Bullet17_Box_Red: "Marcador de Caixa 17 Vermelho",
    Bullet18_Asterisk_LightBlue: "Marcador de Asterisco 18 Azul Claro",
    Bullet19_Leaves_Red: "Marcador de Folhas 19 Vermelho",
    Bullet20_Target_Blue: "Marcador de Alvo 20 Azul",
    Bullet21_Arrow_Blue: "Marcador de Seta 21 Azul",
    Bullet22_Arrow_DarkBlue: "Marcador de Seta 22 Azul Escuro",
    Bullet23_Arrow_Brown: "Marcador de Seta 23 Marrom",
    Bullet24_Flag_Red: "Marcador de Sinalizador 24 Vermelho",
    Bullet25_Flag_Green: "Marcador de Sinalizador 25 Verde",
    Bullet26_X_Red: "Marcador de X 26 Vermelho",
    Bullet27_X_Black: "Marcador de X 27 Preto",
    Bullet28_Checkmark_Green: "Marcador de Marca de Seleção 28 Verde",
    Bullet29_Checkmark_Blue: "Marcador de Marca de Seleção 29 Azul",
    Bullet30_Square_DarkRed: "Marcador de Quadrado 30 Vermelho Escuro",
    camera: "Câmera",
    computer1: "Computador 1",
    computer2: "Computador 2",
    computer3: "Computador 3",
    Computer_Cloud: "Nuvem de Computador",
    Computer_Desktop: "Área de trabalho do Computador",
    Computer_Laptop_Black: "Laptop Preto",
    Computer_Laptop_Silver: "Laptop Prata",
    Database: "Banco de Dados",
    evelope: "Envelope",
    newspapers: "Jornais",
    openevelope: "Abrir Envelope",
    Server: "Servidor",
    speaker: "Alto-falante",
    WirelessAccessPoint: "Ponto de Acesso Wireless",
    Cycle01_Transparent: "Ciclo 01 Transparente",
    Cycle02_Transparent_Blue: "Ciclo 02 Transparente Azul",
    Cycle03_Blue: "Ciclo 03 Azul",
    Cycle04_Blue: "Ciclo 04 Azul",
    Cycle05: "Ciclo 05",
    Cycle06: "Ciclo 06",
    Cycle07: "Ciclo 07",
    Cycle08_Blue: "Ciclo 08 Azul",
    Cycle09_Orange: "Ciclo 09 Laranja",
    Donut01_LightBlue: "Donut 01 Azul Claro",
    Donut02_Blue: "Donut 02 Azul",
    Donut03_Blue: "Donut 03 Azul",
    Donut04_DarkBlue: "Donut 04 Azul Escuro",
    Donut05_DarkBlue: "Donut 05 Azul Escuro",
    Donut06_Blue: "Donut 06 Azul",
    Donut07_Blue: "Donut 07 Azul",
    Graph: "Gráfico",
    People01_Blue: "Pessoas 01 Azuis",
    People02: "Pessoas 02",
    Pillars01_Orange: "Pilares 01 Laranjas",
    Pillars02_LightBlue: "Pilares 02 Azul-claros",
    Process01_Blue: "Processo 01 Azul",
    Process02_Blue: "Processo 02 Azul",
    Process03_Blue: "Processo 03 Azul",
    Process04_GoUp_Blue: "Processo Ir para Cima 04 Azul",
    Process05_GoUp_Red: "Processo Ir para Cima 05 Vermelho",
    Process06_GoUp_Yellow: "Processo Ir para Cima 06 Amarelo",
    Process07_Blue: "Processo 07 Azul",
    Pyramid01: "Pirâmide 01",
    Pyramid02_Blue: "Pirâmide 02 Azul",
    Pyramid03: "Pirâmide 03",
    Radial01_Green: "Radial 01 Verde",
    Radial02_Green: "Radial 02 Verde",
    Radial03_Sphere: "Radial de Esfera 03",
    Radial04_Sphere_Red: "Radial de Esfera 04 Vermelha",
    Radial05_Sphere_Blue: "Radial de Esfera 05 Azul",
    Radial06_Arrows_DarkBlue: "Radial de Setas 06 Azul Escuro",
    Radial07_Arrows_DarkBlue: "Radial de Setas 07 Azul Escuro",
    Section_Circle: "Seção Círculo",
    Section_Cubes01: "Seção Cubos 01",
    Section_Cubes02_Blue: "Seção Cubos 02 Azuis",
    Section_Cubes03_Orange: "Seção Cubos 03 Laranjas",
    Section_Cubes04: "Seção Cubos 04",
    Section_Cubes05: "Seção Cubos 05",
    Section_Cuboids01_Blue: "Seção Cuboides 01 Azuis",
    Section_Cuboids02_Blue: "Seção Cuboides 02 Azuis",
    Section_Cuboids03: "Seção Cuboides 03",
    Section_Gears01: "Seção Mecanismos 01",
    Section_Gears02: "Seção Mecanismos 02",
    Section_Gears03: "Seção Mecanismos 03",
    Section_Hexagon04_Orange: "Seção Hexágono 04 Laranja",
    Section_Hexagons01: "Seção Hexágonos 01",
    Section_Hexagons02_Blue: "Seção Hexágonos 02 Azuis",
    Section_Hexagons03_Blue: "Seção Hexágonos 03 Azuis",
    Section_Leaves01_LightBlue: "Seção Folhas 01 Azul-claras",
    Section_Leaves02_Green: "Seção Folhas 02 Verdes",
    Section_Pasters01: "Seção Fitas Adesivas 01",
    Section_Pasters02_Blue: "Seção Fitas Adesivas 02 Azuis",
    Section_Puzzle01: "Seção Quebra-cabeça 01",
    Section_Puzzle02: "Seção Quebra-cabeça 02",
    Section_Puzzle03: "Seção Quebra-cabeça 03",
    Section_Rectangles: "Seção Retângulos",
    Section_Squares: "Seção Quadrados",
    Section_Triangle: "Seção Triângulo",
    Target: "Destino",
    Venn01: "Venn 01",
    Venn02: "Venn 02",
    Venn03: "Venn 03",
    Venn04: "Venn 04",
    Venn05: "Venn 05",
    Venn06_Blue: "Venn 06 Azul",
    Venn07_Blue: "Venn 07 Azul",
    Venn08: "Venn 08",
    Blackboard: "Lousa",
    Books: "Livros",
    Books1: "Livros 1",
    books2: "Livros 2",
    Chalk: "Giz",
    clipboard: "Área de transferência",
    clock: "clock",
    Globe: "Globo",
    Glue: "Cola",
    GraduationCap: "Chapéu de Formatura",
    magnifyingglass: "lupa",
    Microscope: "Microscópio",
    Notebook: "Bloco de notas",
    notepad1: "Notepad 1",
    notepad2: "Notepad 2",
    notepad3: "Notepad 3",
    PaperClip_Blue: "Clipe de Papel Azul",
    PaperClip_Red: "Clipe de Papel Vermelho",
    Pencil: "Lápis",
    Ruler: "Régua",
    TestTubes: "Tubos de Teste",
    thumbtack: "Tachinha",
    clouds: "Nuvens",
    DrippingFaucet: "Torneira pingando",
    Earth: "Terra",
    EndangeredAnimals1: "Animais Ameaçados 1",
    EndangeredAnimals2: "Animais Ameaçados 2",
    GreenCar: "Carro Verde",
    GreenFactory: "Fábrica Verde",
    GreenHouse: "Casa Verde",
    Leaf1: "Folha 1",
    Leaf2: "Folha 2",
    lightbulb: "Lâmpada",
    LightBulb_Flourescent_Off: "Lâmpada Fluorescente Apagada",
    LightBulb_Flourescent_On: "Lâmpada Fluorescente Acesa",
    LightBulb_Standard_Off1: "Lâmpada Padrão Apagada 1",
    LightBulb_Standard_Off2: "Lâmpada Padrão Apagada 2",
    LightBulb_Standard_On: "Lâmpada Padrão Acesa",
    lightningcloud: "Nuvem com Raio",
    Pollution_Car: "Carro Poluente",
    Pollution_Factory: "Fábrica Poluente",
    Raindrop: "Gota",
    RecycleBin: "Compartimento de Reciclagem",
    RecycleSymbol: "Símbolo da Reciclagem",
    RenewableEnergySymbol: "Símbolo da Energia Renovável",
    RenewableEnergy_Solar: "Energia Solar Renovável",
    RenewableEnergy_Water: "Energia Renovável da Água",
    RenewableEnergy_Wind: "Energia Renovável do Vento",
    sun: "Sol",
    Sun1: "Sol 1",
    Sun2: "Sol 2",
    sundandcloud: "Sol e Nuvem",
    world: "Mundo",
    Agreement: "Acordo",
    ATM01: "Caixa Eletrônico 01",
    ATM02: "Caixa Eletrônico 02",
    Balance_Balanced1: "Saldo Balanceado 1",
    Balance_Balanced2: "Saldo Balanceado 2",
    Balance_Unbalanced1: "Saldo Não Balanceado 1",
    Balance_Unbalanced2: "Saldo Não Balanceado 2",
    Calculator: "Calculadora",
    Chart_Decrease1: "Gráfico Decrescente 1",
    Chart_Decrease2: "Gráfico Decrescente 2",
    Chart_Increase1: "Gráfico Crescente 1",
    Chart_Increase2: "Gráfico Crescente 2",
    Chart_Plateau: "Gráfico Estático",
    Check: "Visto",
    Contract: "Contrato",
    CreditCard_Black: "Cartão de Crédito Preto",
    CreditCard_Cut: "Corte de Cartão de Crédito",
    CreditCard_Gold: "Cartão de Crédito Dourado",
    Currency_Dollar: "Dólar",
    Currency_Dollars: "Dólares",
    Currency_Stack: "Pilha de Dinheiro",
    Currency_StackCoins: "Pilha de Moedas",
    GoldBar: "Barra de Ouro",
    GoldBar_Stack: "Pilha de Barras de Ouro",
    MoneyBag01: "Saco de Dinheiro 01",
    MoneyBag02: "Saco de Dinheiro 02",
    PercentSign: "Sinal de Percentual",
    PiggyBank01_Broken: "Cofrinho 01 Quebrado",
    PiggyBank02_Broken: "Cofrinho 02 Quebrado",
    PiggyBank_Coins: "Moedas do Cofrinho",
    PiggyBank_Currency: "Dinheiro do Cofrinho",
    Portfolio: "Portfólio",
    PriceTag: "Etiqueta de Preço",
    Safe_Closed: "Cofre Fechado",
    Safe_Empty: "Cofre Vazio",
    Safe_Full: "Cofre Cheio",
    Seal_Gold: "Selo Dourado",
    Seal_Red: "Selo Vermelho",
    Seal_Silver: "Selo Prata",
    Wallet_Empty: "Carteira Vazia",
    Wallet_Full1: "Carteira Cheia 1",
    Wallet_Full2: "Carteira Cheia 2",
    BusinessPerson_Female6: "Mulher de Negócios 6",
    BusinessPerson_Male3: "Homem de Negócios 3",
    Computer_User_Female1: "Usuária de Computador 1",
    ConstructionWorker2: "Operário 2",
    Presenter_Female1: "Apresentadora 1",
    Component_Circle01_Transparent_DarkBlue: "Componente Círculo 01 Azul Escuro Transparente",
    Component_Circle02_Transparent_Bule: "Componente Círculo 02 Azul Transparente",
    Component_Circle03_Transparent_Green: "Componente Círculo 03 Verde Transparente",
    Component_Circle04_Transparent_Orange: "Componente Círculo 04 Laranja Transparente",
    Component_Circle05_Transparent_Red: "Componente Círculo 05 Vermelho Transparente",
    Component_Cube01_DarkBlue: "Componente Cubo 01 Azul Escuro",
    Component_Cube02_LightBlue: "Componente Cubo 02 Azul Claro",
    Component_Cube03_Green: "Componente Cubo 03 Verde",
    Component_Cube04_Orange: "Componente Cubo 04 Laranja",
    Component_Cube05_DarkRed: "Componente Cubo 05 Vermelho Escuro",
    Component_Cuboid01_DarkBlue: "Componente Cuboide 01 Azul Escuro",
    Component_Cuboid02_Blue: "Componente Cuboide 02 Azul",
    Component_Cuboid03_Green: "Componente Cuboide 03 Verde",
    Component_Cuboid04_Orange: "Componente Cuboide 04 Laranja",
    Component_Cuboid05_Red: "Componente Cuboide 05 Vermelho",
    Component_Gear01_DarkBlue: "Componente Mecanismo 01 Azul Escuro",
    Component_Gear02_LightBlue: "Componente Mecanismo 02 Azul Claro",
    Component_Gear03_Green: "Componente Mecanismo 03 Verde",
    Component_Gear04_DarkRed: "Componente Mecanismo 04 Vermelho Escuro",
    Component_Gear05_Orange: "Componente Mecanismo 05 Laranja",
    Component_Person01_DarkBlue: "Componente Pessoa 01 Azul Escuro",
    Component_Person02_Blue: "Componente Pessoa 02 Azul",
    Component_Person03_Green: "Componente Pessoa 03 Verde",
    Component_Person04_DarkRed: "Componente Pessoa 04 Vermelho Escuro",
    Component_Person05_Orange: "Componente Pessoa 05 Laranja",
    Component_PuzzlePiece01_DarkBlue: "Componente Peça de Quebra-cabeça 01 Azul-escura",
    Component_PuzzlePiece02_Blue: "Componente Peça de Quebra-cabeça 02 Azul",
    Component_PuzzlePiece03_Green: "Componente Peça de Quebra-cabeça 03 Verde",
    Component_PuzzlePiece04_Red: "Componente Peça de Quebra-cabeça 04 Vermelha",
    Component_PuzzlePiece05_Orange: "Componente Peça de Quebra-cabeça 05 Laranja",
    Component_Sphere01_DarkBlue: "Componente Esfera 01 Azul-escura",
    Component_Sphere02_LightBlue: "Componente Esfera 02 Azul-clara",
    Component_Sphere03_Green: "Componente Esfera 03 Verde",
    Component_Sphere04_DarkRed: "Componente Esfera 04 Vermelho-escura",
    Component_Sphere05_Orange: "Componente Esfera 05 Laranja",
    Book: "Livro",
    Box01: "Caixa 01",
    Box02: "Caixa 02",
    Bulb01_Yellow: "Bulbo 01 Amarelo",
    Bulb02_Yellow: "Bulbo 02 Amarelo",
    Calendar: "Agenda",
    Chart: "Gráfico",
    Clipboard: "Área de Transferência",
    Clock: "Clock",
    Compass: "Compasso",
    Flag01_Red: "Sinalizador Flag 01 Vermelho",
    Flag02_Green: "Sinalizador 02 Verde",
    Flag03_Blue: "Sinalizador 03 Azul",
    Gift: "Presente",
    House: "Casa",
    Icon_Computer01_White: "Ícone de Computador 01 Branco",
    Icon_Computer02_Black: "Ícone de Computador 02 Preto",
    Icon_Disk01_Blue: "Ícone de Disco 01 Azul",
    Icon_Disk02_Green: "Ícone de Disco 02 Verde",
    Icon_Document01_Grey: "Ícone de Documento 01 Cinza",
    Icon_Document02_Grey: "Ícone de Documento 02 Cinza",
    Icon_Document03_Blue: "Ícone de Documento 03 Azul",
    Icon_Document04_Blue: "Ícone de Documento 04 Azul",
    Icon_Envelope01_Blue: "Ícone de Envelope 01 Azul",
    Icon_Envelope02_Yellow: "Ícone de Envelope 02 Amarelo",
    Icon_Envelope03_Open_Yellow: "Ícone de Envelope Aberto 03 Amarelo",
    Icon_Envelope04_Open_Yellow: "Ícone de Envelope Aberto 04 Amarelo",
    Icon_Folder01_Yellow: "Ícone de Pasta 01 Amarela",
    Icon_Folder02_Yellow: "Ícone de Pasta 02 Amarela",
    Icon_Folder03_Open_Yellow: "Ícone de Pasta Aberta 03 Amarela",
    Icon_Folder04_Open_Yellow: "Ícone de Pasta Aberta 04 Amarela",
    Icon_Gear01_Grey: "Ícone de Mecanismo 01 Cinza",
    Icon_Gear02_Blue: "Ícone de Mecanismo 02 Azul",
    Icon_Network01_Blue: "Ícone de Rede 01 Azul",
    Icon_Network02: "Ícone de Rede 02",
    Icon_Pencil01: "Ícone de Lápis 01",
    Icon_Pencil02: "Ícone de Lápis 02",
    Icon_Printer01_White: "Ícone de Impressora 01 Branco",
    Icon_Printer02_Black: "Ícone de Impressora 02 Preto",
    Key01: "Chave 01",
    Key02: "Chave 02",
    Lock01_Yellow: "Trava 01 Amarela",
    Lock02_Yellow: "Trava 02 Amarela",
    Lock03_Blue: "Trava 03 Azul",
    Lock04_Blue: "Trava 04 Azul",
    Magnet: "Ímã",
    MagnifyingGlass: "Lupa",
    Medal: "Medalha",
    Notebook: "Bloco de notas",
    Phone: "Telefone",
    PieChart: "Gráfico de Setores Circulares",
    Pin: "Pino",
    PuzzlePiece: "Peça de quebra-cabeça",
    PuzzlePieces: "Peças de quebra-cabeça",
    Roadblock: "Obstáculo",
    Scissors: "Tesoura",
    Shield01: "Blindagem 01",
    Shield02_Orange: "Blindagem 02 Laranja",
    Shield03_Blue: "Blindagem 03 Azul",
    Sign_Ban01: "Sinal de Interdição 01",
    Sign_Ban02: "Sinal de Interdição 02",
    Sign_CheckBox01: "Sinal de Caixa de Seleção 01",
    Sign_CheckBox02_Unchecked: "Sinal de Caixa de Seleção 02 Não Marcado",
    Sign_Checkmark01_Green: "Sinal de Marca de Seleção 01 Verde",
    Sign_Checkmark02_Green: "Sinal de Marca de Seleção 02 Verde",
    Sign_DoNotEnter: "Sinal de Não Entre",
    Sign_Error01: "Sinal de Erro 01",
    Sign_Error02: "Sinal de Erro 02",
    Sign_ExclamationPoint01_Red: "Sinal de Ponto de Exclamação 01 Vermelho",
    Sign_ExclamationPoint02_Orange: "Sinal de Ponto de Exclamação 02 Laranja",
    Sign_Help01_Green: "Sinal de Ajuda 01 Verde",
    Sign_Help02_Blue: "Sinal de Ajuda 02 Azul",
    Sign_Information: "Sinal de Informações",
    Sign_Null: "Sinal de Nulo",
    Sign_QuestionMark01_Blue: "Sinal de Ponto de Interrogação 01 Azul",
    Sign_QuestionMark02_Red: "Sinal de Ponto de Interrogação 02 Vermelho",
    Sign_RadioButton01: "Sinal de Botão de Opções 01",
    Sign_RadioButton02_Unchecked: "Sinal de Botão de Opções 02 Não Marcado",
    Sign_Warning01_Red: "Sinal de Aviso 01 Vermelho",
    Sign_Warning02_Orange: "Sinal de Aviso 02 Laranja",
    Sign_X01_Red: "Sinal X 01 Vermelho",
    Sign_X02_Red: "Sinal X 02 Vermelho",
    Star_Yellow: "Estrela Amarela",
    Wrench: "Chave Inglesa",
    Airplane_Blue: "Avião Azul",
    Bicycle_Blue: "Bicicleta Azul",
    Bus: "Ônibus",
    Canoe_Blue: "Canoa Azul",
    Car_Red: "Carro Vermelho",
    Helicopter_Blue: "Helicóptero Azul",
    Motorcycle_Red: "Motocicleta Vermelha",
    Pedestrian_Blue: "Pedestre Azul",
    PersonalTransporter_Green: "Veículo Pessoal Verde",
    Sailboat_Red: "Veleiro Vermelho",
    Scooter_Orange: "Patinete Laranja",
    Train_Red: "Trem Vermelho",
    Truck_Blue: "Caminhão Azul",
    
    aria_category_selector: "Opções de Categoria da Imagem",
    filterImageGallery: "Filtrar galeria de imagens"

})
