﻿﻿/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        fileMenu: "Arquivo",
        fileMenu_New: "Novo",
        fileMenu_NewDocument: "Documento",
        fileMenu_NewFromTemplate: "Do Modelo",
        fileMenu_NewDocumentfromTemplate: "Documento do Modelo",
        fileMenu_NewPresentation: "Apresentação",
        fileMenu_NewPresentationfromTemplate: "Apresentação do Modelo",
        fileMenu_NewSpreadsheet: "Planilha",
        fileMenu_NewSpreadsheetFromTemplate: "Planilha do Modelo",
        fileMenu_Open: "Abrir",
        fileMenu_Import: "Importar...",
        //	fileMenu_Close: "Close",
        fileMenu_Discard: "Reverter para a Última Versão",
        fileMenu_ClearTrackChange: "Remover Marcas de Mudanças",
        fileMenu_SpreadsheetSettings: "Configurar Código de Idioma do Documento...",
        filemenu_revisionhistory: "Revisões",
        fileMenu_Save: "Salvar",
        fileMenu_SaveAs: "Copiar...",
        fileMenu_AutoPublish: "Publicar automaticamente",
        fileMenu_AutoCheckIn: "Efetuar o registro de entrada automaticamente",
        fileMenu_PublishVersion: "Publicar agora",
        fileMenu_AutoPublish2: "Salvamento Automático para o Repositório",
        //	fileMenu_AutoPublish_Tips: "Makes your changes available to readers at the end of each editing session.",
        fileMenu_PublishVersion2: "Salvar no Repositório Agora",
        fileMenu_AutoPublish3: "Auto salvar para ${0}",
        fileMenu_PublishVersion3: "Salvar em ${0} Agora",      
        fileMenu_SubmitForReview: "Enviar Para Revisão...",
        fileMenu_CheckinVersion: "Efetuar o Registro de Entrada...",
        fileMenu_Unlock: "Desbloquear",
        //	fileMenu_SaveAsDraft: "as Draft",
        //	fileMenu_SaveInMyDocs: "in My Documents",
        //	fileMenu_SaveToSymphony: "to Lotus Symphany",
        fileMenu_DownloadAs: "Fazer download como",
        fileMenu_PDF: "PDF",
        fileMenu_ODF: "ODF",
        fileMenu_DOC: "Microsoft Word 97- 2007 (*.doc)",
        fileMenu_ODS: "ODS",
        fileMenu_XLS: "Microsoft Excel 97-2007 (*.xls) ",
        fileMenu_ShareWith: "Compartilhar...",
        fileMenu_ExportAsPDF: "PDF",
        fileMenu_ExportAsODF: "ODF",
        fileMenu_ExportAsPPT: "Microsoft Powerpoint 97- 2007 (*.ppt)",
        //	fileMenu_WebPreview: "Web Preview",
        fileMenu_PrintToPDF: "Imprimir em PDF...",
        fileMenu_ViewFileDetails: "Visualizar Detalhes do Arquivo...",
        fileMenu_RecentFile: "Arquivos Recentes",
        fileMenu_Open: "Abrir",
        fileMenu_Download: "Fazer download",
        fileMenu_Print: "Imprimir",
        fileMenu_Export: "Exportar",
        fileMenu_ExportToCSV: "CSV",
        fileMenu_ExportToPDF: "PDF (.pdf)",
        fileMenu_ExportToMarkdown: "Markdown (.md)",
        fileMenu_ExportToMS: "Formato Microsoft Office (.${FILEEXTENSION})",
        fileMenu_ExportToODF: "Formato Open Document (.${FILEEXTENSION})",
        fileMenu_PgSetup: "Configuração da página...",

        editMenu: "Editar",
        editMenu_Undo: "Desfazer",
        editMenu_Redo: "Refazer",
        editMenu_Cut: "Recortar",
        editMenu_Copy: "Copiar",
        editMenu_Paste: "Colar",
        editMenu_DeleteSlide: "Excluir Slide",
        editMenu_SelectAll: "Selecionar Tudo",
        editMenu_Find: "Localizar...",
        editMenu_Replace: "Substituir...",
        editMenu_FindReplace: "Localizar e Substituir...",
        editMenu_EditLink: "Incluir ou Editar Link",
        editMenu_DeleteSheet: "Excluir Planilha...",
        editMenu_RenameSheet: "Renomear Folha...",
        editMenu_HideSheet: "Ocultar Planilha",
        editMenu_MoveSheet: "Mover Planilha...",
        editMenu_DeleteRow: "Excluir Linha",
        editMenu_DeleteColumn: "Excluir Coluna",
        editMenu_DeleteCellLeft: "Excluir Células e Deslocar à Esquerda",
        editMenu_DeleteCellUp: "Excluir Células e Deslocar para Cima",
        editMenu_ClearCell: "Excluir Conteúdo",

        viewMenu: "Visualizar",
        viewMenu_Master: "Principal",
        viewMenu_Notifications: "Notificações",
        viewMenu_SlideSorter: "Classificador de Slide",
        viewMenu_SpeakerNotes: "Notas do Locutor",
        viewMenu_Toolbar_Basic: "Básico",
        viewMenu_Toolbar_Advanced: "Avançado",
        viewMenu_Toolbar_None: "Nenhum",
        viewMenu_Toolbar: "Barra de Ferramentas",
        viewMenu_Statusbar: "Statusbar",
        viewMenu_Navigator: "Navegador...",
        //viewMenu_Sidebar: "Sidebar",
        viewMenu_ShowHideIndicators: "Mostrar Favoritos de Co-edição",
        viewMenu_Assignment: "Favoritos de Designação",
        viewMenu_Bookmark: "Favoritos",
        viewMenu_Coediting: "Coeditando os Destaques",
        viewMenu_Rulers: "Réguas",
        viewMenu_WebLayout: "Layout da Web",
        viewMenu_AutomaticSpellCheck: "Faça a verificação ortográfica à medida que você digita",
        viewMenu_Formulabar: "Barra da Fórmula",
        viewMenu_moveRight: "Inserir Movimentações do Cursor à Direita",
        viewMenu_showFullString: "Estender Conteúdo nas Células",
        viewMenu_Doc: "Visualizar Documento",
        viewMenu_Templates: "Modelos",
        viewMenu_GridLines: "Ocultar Linhas de Grade",
        viewMenu_UnsupportWarning: "Mostrar Mensagens de Recurso Não Suportadas",
        viewMenu_HiddenSheets: "Planilhas Ocultas",
        viewMenu_FreezeRows: "Congelar Linhas",
        viewMenu_FreezeColumns: "Congelar Colunas",
        viewMenu_NoFrozenRows: "Sem Linhas Congeladas",
        viewmenu_NoFrozenColumns: "Sem Colunas Congeladas",
        viewMenu_FreezeXRows: "Congelar ${0} Linhas",
        viewMenu_FreezeOneRow: "Congelar ${0} Linha",
        viewMenu_FreezeXColumns: "Congelar ${0} Colunas",
        viewMenu_FreezeOneColumn: "Congelar ${0} Coluna",
        viewMenu_CarriageReturn: "Formatando marcas",
        viewMenu_Navigation: "Área de janela de navegação",
        viewMenu_ACL: "Áreas editáveis",
        viewMenu_GridOnOff: "Linhas de Grade",
        viewMenu_ObserverMode: 'Modo de Observador',

        createMenu: "Inserir",
        createMenu_NewSlide: "Novo Slide",
        createMenu_DuplicateSlide: "Duplicar Slide",
        createMenu_ImageFromFile: "Imagem...",
        createMenu_TextBox: "Caixa de Texto",
        createMenu_Shape: "Forma",
        createMenu_break: "Quebra",
        createMenu_RowAbove: "Linha Acima",
        createMenu_RowBelow: "Linha Abaixo",
        createMenu_ColumnRight: "Coluna Direita",
        createMenu_ColumnLeft: "Coluna Esquerda",
        createMenu_Sheet: "Planilha...",
        createMenu_Image: "Imagem...",
        createMenu_Comments: "Comentário...",
        createMenu_WebLink: "Link da Web...",
        createMenu_SpecialCharacter: "Caractere Especial...",
        createMenu_Function: "Função...",
        createMenu_Fromtemplate: "Criar a Partir do Modelo",

        insertMenu: "Inserir",
        insertMenu_break: "Quebra de Página",
        insertMenu_sectionbreak: "Quebra de Seção",
        insertMenu_Bookmark: "Favorito...",
        insertMenu_WebLink: "Link...",
        insertMenu_SpecialCharacter: "Caractere Especial...",
        insertMenu_HorizontalLine: "Linha Horizontal",
        insertMenu_Header: "Cabeçalho",
        insertMenu_Footer: "Rodapé",
        insertMenu_TableOfContents: "Índice",

        insertMenu_HeaderFooter: "Cabeçalho/Rodapé",
        insertMenu_HF_Edit: "Editar",
        insertMenu_HF_Hide: "Ocultar",
        insertMenu_Endnotes: "Notas finais",
        insertMenu_RowAbove: "Linha Acima",
        insertMenu_PageNumber: "Número da Página",
        insertMenu_PageNumberTop: "Parte Superior da Página",
        insertMenu_PageNumberBottom: "Parte Inferior da Página",
        insertMenu_PageNumberCurr: "Posição Atual",
        insertMenu_TotalPageNumber: "Página 1 de N",
        insertMenu_Date: "Data...",
        insertMenu_Time: "Hora...",
        insertMenu_Fields: "Campos",
        //    insertMenu_Comment: "Comment",
        insertMenu_CellRight: "Células e Deslocar para a Direita",
        insertMenu_CellDown: "Células e Deslocar para Baixo",
        insertMenu_RowBelow: "Linha Abaixo",
        insertMenu_ColumnBefore: "Coluna Anterior",
        insertMenu_ColumnAfter: "Coluna Posterior",
        insertMenu_Sheet: "Planilha...",
        insertMenu_Image: "Imagem...",
        insertMenu_DuplicateSheet: "Duplicar Planilha",
        insertMenu_Function: "Função",
        insertMenu_FunctionSum: "SOMA",
        insertMenu_FunctionAverage: "MÉDIA",
        insertMenu_FunctionCount: "CONTAGEM",
        insertMenu_FunctionMax: "MAX",
        insertMenu_FunctionMin: "MIN",
        insertMenu_FunctionMore: "Mais Funções...",
        insertMenu_NameRange: "Intervalo Nomeado",
        insertMenu_NameRangeNew: "Novo Intervalo...",
        insertMenu_NameRangeManage: "Gerenciar Intervalos...",
        insertMenu_Chart: "Gráfico...",

        contextMenu_insertCellRight: "Inserir Células e Deslocar para a Direita",
        contextMenu_insertCellDown: "Inserir Células e Deslocar para Baixo",
        contextMenu_InsertRowAbove: "Inserir Linha Acima",
        contextMenu_InsertRowBelow: "Inserir Linha Abaixo",
        contextMenu_InsertColumnBefore: "Inserir Coluna Antes",
        contextMenu_InsertColumnAfter: "Inserir Coluna Depois",
        contextMenu_DownloadImage: "Fazer Download como Imagem",

        formatMenu: "Formatar",
        formatMenu_Columns: "Colunas",
        formatMenu_DefaultFormatting: "Formatação Padrão",
        formatMenu_Template: "Estilos...",
        contextMenu_Template: "Estilos de Tabela...",
        formatMenu_LineSpacing: "Espaçamento entre Linhas",
        formatMenu_LineSpacing1: "1",
        formatMenu_LineSpacing12: "1.2",
        formatMenu_LineSpacing15: "1.5",
        formatMenu_LineSpacing2: "2",
        formatMenu_LineSpacing25: "2.5",
        formatMenu_LineSpacing3: "3",
        formatMenu_TextProperties: "Propriedades de Texto",
        formatMenu_PageBreakBefore: "Quebrar página antes",
        formatMenu_KeepLines: "Manter linhas juntas",
        formatMenu_WidowControl: "Controle Viúvo/Órfão",
        formatMenu_Pagination: "Propriedades do parágrafo",
        formatMenu_Bold: "Negrito",
        formatMenu_Italic: "Itálico",
        formatMenu_Underline: "Sublinhado",
        formatMenu_Strikethrough: "Tachado",
        formatMenu_IncreaseSize: "Aumentar Tamanho da Fonte",
        formatMenu_DecreaseSize: "Diminuir Tamanho da Fonte",
        formatMenu_ImageProperties: "Propriedades da Imagem...",
        formatMenu_ChartProperties: "Propriedades do Gráfico...",
        formatMenu_EditChart: "Editar Gráfico",
        formatMenu_InsertChart: "Inserir Gráfico",
        formatMenu_Properties: "Propriedades...",
        formatMenu_Heading: "Título",
        formatMenu_Normal: "Normal",
        formatMenu_Title: "Título",
        formatMenu_Subtitle: "Subtítulo",
        formatMenu_Heading1: "Título 1",
        formatMenu_Heading2: "Título 2",
        formatMenu_Heading3: "Título 3",
        formatMenu_Heading4: "Título 4",
        formatMenu_Heading5: "Título 5",
        formatMenu_Heading6: "Título 6",
        formatMenu_Heading7: "Título 7",
        formatMenu_Heading8: "Título 8",
        formatMenu_Heading9: "Título 9",
        formatMenu_BulletedList: "Lista com Marcadores",
        formatMenu_NumberedList: "Lista Numerada",
        formatMenu_OutLine: "Lista em Vários Níveis",
        formatMenu_Superscript: "Sobrescrito",
        formatMenu_Subscript: "Subscrito",
        formatMenu_Align: "Alinhar",
        formatMenu_Left: "Esquerda",
        formatMenu_Right: "Direita",
        formatMenu_Center: "Centro",
        formatMenu_Justify: "Justificar",
        formatMenu_Text_Direction: "Direção do Texto",
        formatMenu_Ltr: "Esquerda para a Direita",
        formatMenu_Rtl: "Direita para a Esquerda",
        formatMenu_LineSpacing: "Espaçamento entre Linhas",
        formatMenu_LineSpacing1: "1.0",
        formatMenu_LineSpacing115: "1.15",
        formatMenu_LineSpacing15: "1.5",
        formatMenu_LineSpacing2: "2.0",
        formatMenu_LineSpacing25: "2.5",
        formatMenu_LineSpacing3: "3.0",
        formatMenu_Top: "Início da Página",
        formatMenu_Bottom: "Parte Inferior",
        formatMenu_Middle: "Meio",
        formatMenu_Direction: "Direção do Texto",
        formatMenu_Rtl: "Direita para a Esquerda",
        formatMenu_Ltr: "Esquerda para a Direita",
        formatMenu_Auto: "Contextual",
        formatMenu_SheetDirection: "Direção da Planilha",
        formatMenu_SheetRtl: "Direita para a Esquerda",
        formatMenu_SheetLtr: "Esquerda para a Direita",
        formatMenu_Indent: "Aumentar Indentação",
        formatMenu_DecreaseIndent: "Diminuir Indentação",
        formatMenu_ClearFormat: "Limpar formatação",
        formatMenu_RowHeight: "Altura de Linha",
        formatMenu_ColumnWidth: "Largura da Coluna",
        formatMenu_ShowRow: "Mostrar Linha",
        formatMenu_HideRow: "Ocultar Linha",
        formatMenu_ShowColumn: "Mostrar Coluna",
        formatMenu_HideColumn: "Ocultar Coluna",
        formatMenu_WrapText: "Quebrar Texto",
        formatMenu_Number: "Número",
        formatMenu_FontArial: "Arial",
        formatMenu_FontComicSansMS: "Comic Sans MS",
        formatMenu_FontCourierNew: "Courier New",
        formatMenu_FontGeorgia: "Georgia",
        formatMenu_FontLucidaSansUnicode: "Lucida Sans Unicode",
        formatMenu_FontTahoma: "Tahoma",
        formatMenu_FontTimesNewRoman: "Times New Roman",
        formatMenu_FontTrebuchetMS: "Trebuchet MS",
        formatMenu_FontVerdana: "Verdana",
        formatMenu_FontName: "Fonte",

        layoutMenu: "Layout",
        layoutMenu_SlideLayout: "Layout do Slide...",
        layoutMenu_SlideDesign: "Estilo Principal...",
        layoutMenu_DefaultFormatting: "Formatação Padrão",
        layoutMenu_Textprop_Bold: "Negrito",
        layoutMenu_Textprop_Italic: "Itálico",
        layoutMenu_Textprop_Underline: "Sublinhado",
        layoutMenu_Textprop_Strikethrough: "Tachado",
        layoutMenu_TextProp: "Propriedades de Texto",
        LayoutMenu_RowHeight: "Altura da Linha...",
        LayoutMenu_ColumnWidth: "Largura da Coluna...",
        LayoutMenu_ShowRow: "Mostrar Linha",
        LayoutMenu_HideRow: "Ocultar Linha",
        LayoutMenu_RenameSheet: "Renomear Folha...",
        LayoutMenu_MoveSheet: "Mover Planilha",

        tableMenu: "Tabela",
        tableMenu_Create: "Criar...",
        tableMenu_CreateFromTemplate: "Criar a Partir do Modelo",
        tableMenu_Delete: "Excluir",
        tableMenu_SetTableColor: "Colorir Célula",
        tableMenu_CreateTable: "Criar Tabela",
        tableMenu_Cell: "Célula",
        tableMenu_CellMergeCells: "Mesclar Células",
        tableMenu_CellAlignLeft: "Alinhar à Esquerda",
        tableMenu_CellAlignCenter: "Alinhar ao Centro",
        tableMenu_CellAlignRight: "Alinhar à Direita",
        tableMenu_CellClearContents: "Limpar Conteúdo",
        tableMenu_CellProperties: "Propriedades da Célula...",
        tableMenu_Row: "Linha",
        tableMenu_InsertRowAbove: "Inserir Linha Acima",
        tableMenu_InsertRowBelow: "Inserir Linha Abaixo",
        tableMenu_MoveRowAbove: "Mover Linha para Cima",
        tableMenu_MoveRowBelow: "Mover Linha para Baixo",
        tableMenu_RowInsertRow: "Inserir Linha...",
        tableMenu_RowInsertRowAbove: "Inserir Linha Acima",
        tableMenu_RowInsertRowBelow: "Inserir Linha Abaixo",
        tableMenu_RowMoveRowAbove: "Mover Linha para Cima",
        tableMenu_RowMoveRowBelow: "Mover Linha para Baixo",
        tableMenu_RowDelete: "Excluir",
        tableMenu_RowRepeat: "Repetir linha do cabeçalho",
        tableMenu_InsertColumnBefore: "Inserir Coluna Antes",
        tableMenu_InsertColumnAfter: "Inserir Coluna Depois",
        tableMenu_MoveColumnBefore: "Mover Coluna para a Esquerda",
        tableMenu_MoveColumnAfter: "Mover Coluna para a Direita",
        tableMenu_ResizeColumn: "Redimensionar Coluna",
        tableMenu_ResizeColumns: "Redimensionar Colunas",
        tableMenu_MarkasCategory: "Marcar como Categoria",
        tableMenu_ColumnInsertColumn: "Inserir Coluna...",
        tableMenu_ColumnAddColumnBefore: "Inserir Coluna Antes",
        tableMenu_ColumnAddColumnAfter: "Inserir Coluna Depois",
        tableMenu_ColumnMoveColumnAfter: "Mover Coluna Depois",
        tableMenu_ColumnMoveColumnBefore: "Mover Coluna Antes",
        tableMenu_ColumnDelete: "Excluir",
        tableMenu_ColumnSortAscending: "Classificar em Ordem Crescente",
        tableMenu_ColumnSortDescending: "Classificar em Ordem Decrescente",
        tableMenu_Column: "Coluna",
        tableMenu_Style: "Estilo",
        tableMenu_TableProperties: "Propriedades da Tabela...",

        teamMenu: "Equipe",
        teamMenu_AddComment: "Incluir Comentário",
        teamMenu_AssignCells: "Designar Células",
        teamMenu_AssignSection: "Designar uma Seção",
        teamMenu_EditAssignment: "Editar Designação",
        teamMenu_MarkSectionComplete: "Marcar Seção Concluída",
        teamMenu_MarkAssignmentComplete: "Marcar Designação Concluída",
        teamMenu_WorkPrivatelyOnSection: "Trabalhar de Forma Privada na Seção",
        teamMenu_CancelPrivateWork: "Cancelar o Trabalho Privado",
        teamMenu_ApproveSection: "Aprovar Seção",
        teamMenu_ApproveAssignment: "Aprovar Designação",
        teamMenu_ReturnSectionForRework: "Retornar Seção para Retrabalho",
        teamMenu_ReturnAssignmentForRework: "Retornar Designação para Retrabalho",
        teamMenu_RemoveSectionAssignment: "Remover Designação de Seção",
        teamMenu_RemoveCellAssignment: "Remover Designação de Célula",
        teamMenu_RemoveCompletedAssignments: "Remover Designações Concluídas",
        teamMenu_AboutThisSection: "Sobre esta Seção",
        teamMenu_AboutAssignment: "Sobre esta Designação",

        presentationMenu: "Apresentação",
        presentationMenu_SlideShow: "Reproduzir Slide",
        presentationMenu_SlideShowWithCoview: "Reproduzir Apresentação de Slides Compartilhada",
        presentationMenu_SlideTransitions: "Aplicar Transição de Slide...",
        presentationMenu_SlideShowFromCurrent: "Reproduzir a Partir do Slide Atual",
        presentationMenu_EmptyCoviewInvites: "Nenhuma Apresentação de Slides Compartilhada Ativa",
        presentationMenu_CoviewInvites: "Apresentação de Slides Compartilhada Ativa",

        dataMenu: "Dados",
        dataMenu_Sort: "Classificar...",
        dataMenu_SortAsc: "Classificar em Ordem Crescente",
        dataMenu_SortDesc: "Classificar em Ordem Decrescente",
        dataMenu_ACL: "Áreas protegidas",
        dataMenu_ACL_DELETE: "Excluir todas as permissões",
        dataMenu_Validity: "Validade",
        dataMenu_InstantFilter: "Filtro Instantâneo",
        dataMenu_Validation: "Validação...",

        toolsMenu: "Ferramentas",
        toolsMenu_AutoComplete: "Entradas de Célula de Conclusão Automática",
        toolsMenu_SelectDictionary: "Dicionários de Verificação Ortográfica",
        toolsMenu_Dictionary_ca_CT: "Catalão",
        toolsMenu_Dictionary_cs_CZ: "Tcheco (Tchecoslováquia)",
        toolsMenu_Dictionary_da_DK: "Dinamarquês (Dinamarca)",
        toolsMenu_Dictionary_nl_NL: "Holandês (Holanda)",
        toolsMenu_Dictionary_en_AU: "Inglês (Austrália)",
        toolsMenu_Dictionary_en_GB: "Inglês (Grã-Bretanha)",
        toolsMenu_Dictionary_en_US: "Inglês (Estados Unidos)",
        toolsMenu_Dictionary_fi_FI: "Finlandês (Finlândia)",
        toolsMenu_Dictionary_fr_FR: "Francês (França)",
        toolsMenu_Dictionary_fr_CA: "Francês (Canadá)",
        toolsMenu_Dictionary_de_DE: "Alemão (Alemanha)",
        toolsMenu_Dictionary_de_CH: "Alemão (Suíça)",
        toolsMenu_Dictionary_el_GR: "Grego (Grécia)",
        toolsMenu_Dictionary_it_IT: "Italiano (Itália)",
        toolsMenu_Dictionary_pl_PL: "Polonês (Polônia)",
        toolsMenu_Dictionary_pt_BR: "Português (Brasil)",
        toolsMenu_Dictionary_pt_PT: "Português (Portugal)",
        toolsMenu_Dictionary_ru_RU: "Russo (Rússia)",
        toolsMenu_Dictionary_es_ES: "Espanhol (Espanha)",
        toolsMenu_Dictionary_sv_SE: "Sueco (Suécia)",
        toolsMenu_Dictionary_nb_NO: "Norueguês (Bokml)",
        toolsMenu_Dictionary_nn_NO: "Norueguês (Nynorsk)",
        toolsMenu_Dictionary_he_IL: "Hebraico (Israel)",
        toolsMenu_SpellCheck: "Executar Verificação Ortográfica Manual...",
        toolsMenu_Preferences: "Preferências",
        toolsMenu_Task: "Tarefa",
        toolsMenu_Task_Assigntask: "Designar uma Tarefa",
        teamMenu_AssignSlide: "Designar Slide",
        teamMenu_AssignSlides: "Designar Slides",
        teamMenu_EditSlide: "Editar Designação de Slide",
        teamMenu_ReopenSlideAssignment: "Reabrir Designação de Slide",
        teamMenu_ReopenSlideAssignments: "Reabrir Designações de Slide",
        teamMenu_ReassignSlide: "Redesignar Slide",
        teamMenu_ReassignSlides: "Redesignar Slides",
        teamMenu_MarkSlidesComplete: "Marcar Slide como Concluído",
        teamMenu_MarkSlidesCompletes: "Marcar Slides como Concluídos",
        teamMenu_ApproveSlide: "Aprovar Slide",
        teamMenu_ApproveSlides: "Aprovar Slides",
        teamMenu_ReturnForRework: "Retornar Slide para Retrabalho",
        teamMenu_ReturnForReworks: "Retornar Slides para Retrabalho",
        teamMenu_RemoveAssignment: "Remover Designação de Slide",
        teamMenu_AboutThisSlide: "Sobre este Slide",

        addOnsMenu: "Complementos",

        helpMenu: "Ajuda",
        helpMenu_About: "Sobre",
        helpMenu_Overview: "Conteúdo da Ajuda",
        helpMenu_NewFeatures: "O que há de Novo",
        helpMenu_Tour: "Tour Guiado",

        accel_fileMenu_Save: "Ctrl+S",
        accel_fileMenu_Save_Mac: "\u2318S",
        accel_fileMenu_Print: "Ctrl+P",
        accel_fileMenu_Print_Mac: "\u2318P",
        accel_editMenu_SelectAll: "Ctrl+A",
        accel_editMenu_SelectAll_Mac: "\u2318A",
        accel_editMenu_Undo: "Ctrl+Z",
        accel_editMenu_Undo_Mac: "\u2318Z",
        accel_editMenu_Redo: "Ctrl+Y",
        accel_editMenu_Redo_Mac: "\u2318Y",
        accel_editMenu_Cut: "Ctrl+X",
        accel_editMenu_Cut_Mac: "\u2318X",
        accel_editMenu_Copy: "Ctrl+C",
        accel_editMenu_Copy_Mac: "\u2318C",
        accel_editMenu_Paste: "Ctrl+V",
        accel_editMenu_Paste_Mac: "\u2318V",
        accel_editMenu_Find: "Ctrl+F",
        accel_editMenu_Find_Mac: "\u2318F",
        accel_insertMenu_Link: "Ctrl+K",
        accel_insertMenu_Link_Mac: "\u2318K",
        accel_insertMenu_Header: "CTRL+SHIFT+H",
        accel_insertMenu_Header_Mac: "\u21e7\u2318H",
        accel_insertMenu_Footer: "CTRL+SHIFT+F",
        accel_insertMenu_Footer_Mac: "\u21e7\u2318F",
        accel_formatMenu_Textprop_Bold: "Ctrl+B",
        accel_formatMenu_Textprop_Bold_Mac: "\u2318B",
        accel_formatMenu_Textprop_Italic: "Ctrl+I",
        accel_formatMenu_Textprop_Italic_Mac: "\u2318I",
        accel_formatMenu_Textprop_FormatPainter: "Ctrl+SHIFT+C, Ctrl+SHIFT+V",
        accel_formatMenu_Textprop_FormatPainter_Mac: "\u21e7\u2318C, \u21e7\u2318V",
        accel_formatMenu_Textprop_Underline: "Ctrl+U",
        accel_formatMenu_Textprop_Underline_Mac: "\u2318U",
        accel_formatMenu_Headingprop_P: "CTRL+SHIFT+0",
        accel_formatMenu_Headingprop_H1: "CTRL+SHIFT+1",
        accel_formatMenu_Headingprop_H2: "CTRL+SHIFT+2",
        accel_formatMenu_Headingprop_H3: "CTRL+SHIFT+3",
        accel_formatMenu_Headingprop_H4: "CTRL+SHIFT+4",
        accel_formatMenu_Headingprop_H5: "CTRL+SHIFT+5",
        accel_formatMenu_Headingprop_H6: "CTRL+SHIFT+6",
        accel_formatMenu_Superscript: "Ctrl+.",
        accel_formatMenu_Superscript_Mac: "\u2318.",
        accel_formatMenu_Subscript: "Ctrl+,",
        accel_formatMenu_Subscript_Mac: "\u2318,",
        accel_formatMenu_Left: "CTRL+SHIFT+L",
        accel_formatMenu_Left_Mac: "\u21e7\u2318L",
        accel_formatMenu_Right: "CTRL+SHIFT+R",
        accel_formatMenu_Right_Mac: "\u21e7\u2318R",
        accel_formatMenu_Center: "CTRL+SHIFT+E",
        accel_formatMenu_Center_Mac: "\u21e7\u2318E",
        accel_formatMenu_Justify: "CTRL+SHIFT+J",
        accel_formatMenu_Justify_Mac: "\u21e7\u2318J",
        accel_formatMenu_Indent: "CTRL+M",
        accel_formatMenu_Indent_Mac: "\u2318M",
        accel_formatMenu_DecreaseIndent: "CTRL+SHIFT+M",
        accel_formatMenu_DecreaseIndent_Mac: "\u21e7\u2318M",
        accel_teamMenu_AddComment: "SHIFT+F2",

        ctxMenuSmartTable: 'Tabela',
        ctxMenuTableProperties: "Propriedades da Tabela",
        ctxMenuDeleteST: 'Excluir',
        ctxMenuDeleteSTTable: 'Excluir Tabela',
        ctxMenuChgSTStyle: 'Alterar Estilo',
        ctxMenuShowCaption: 'Mostrar Legenda',
        ctxMenuHideCaption: 'Ocultar Legenda',
        ctxMenuResizeST: 'Redimensionar',
        ctxMenuResizeColumnsST: 'Redimensionar Colunas',
        ctxMenuSTRow: 'Linha',
        ctxMenuAddSTRowAbv: 'Inserir Linha Acima',
        ctxMenuAddSTRowBlw: 'Inserir Linha Abaixo',
        ctxMenuMoveSTRowUp: 'Mover Linha para Cima',
        ctxMenuMoveSTRowDown: 'Mover Linha para Baixo',
        ctxMenuDelSTRow: 'Excluir',
        ctxMenuRepeatRow: 'Repetir linha do cabeçalho',
        ctxMenuSTCol: 'Coluna',
        ctxMenuAddSTColBfr: 'Inserir Coluna Antes',
        ctxMenuAddSTColAft: 'Inserir Coluna Depois',
        ctxMenuMoveSTColBefore: 'Mover Coluna Antes',
        ctxMenuMoveSTColAfter: 'Mover Coluna Depois',
        ctxMenuDelSTCol: 'Excluir',
        ctxMenuSortSTColAsc: 'Classificar em Ordem Crescente',
        ctxMenuSortSTColDesc: 'Classificar em Ordem Decrescente',
        ctxMenuShowAllFacets: 'Mostrar Categorias',
        ctxMenuHideAllFacets: 'Ocultar Categorias',
        ctxMenuSTCell: 'Célula',
        ctxMenuMergeCells: 'Mesclar Células',
        ctxMenuMergeDown: 'Mesclar com a Célula Abaixo',
        ctxMenuVerSplit: 'Dividir Verticalmente',
        ctxMenuHorSplit: 'Dividir Horizontalmente',
        ctxMenuSplitCells: 'Dividir Células...',
        splitCells: 'Célula dividida',
        ctxMenuAlignTextLeft: 'Alinhar à Esquerda',
        ctxMenuAlignTextCenter: 'Alinhar ao Centro',
        ctxMenuAlignTextRight: 'Alinhar à Direita',
        ctxMenuClearSTCellContent: 'Limpar Conteúdo',
        ctxMenuMakeHeaderRow: 'Usar Linha Selecionada como Cabeçalho',
        ctxMenuMakeNonHeaderRow: 'Remover Estilo de Título',
        ctxMenuMakeHeaderCol: 'Usar Coluna Selecionada como Cabeçalho',
        ctxMenuMakeNonHeaderCol: 'Remover Estilo de Título',
        SHEET_CONTEXT_Hide: "Ocultar", // hide row, column or sheet
        SHEET_CONTEXT_Show: "Mostrar", // show row, column
        SHEET_CONTEXT_MoveSheet: "Mover...", // move sheet
        SHEET_CONTEXT_InsertSheet: "Inserir...", // insert sheet
        SHEET_CONTEXT_DeleteSheet: "Excluir...", // delete sheet	
        SHEET_CONTEXT_DuplicateSheet: "Duplicar...", // duplicate sheet
        SHEET_CONTEXT_RenameSheet: "Renomear...", // rename sheet
	
        ctxMenu_Image_WrapText: "Quebrar Texto",
        ctxMenu_Image_WrapText_Inline: "Na Linha com Texto",
        ctxMenu_Image_WrapText_Square: "Quadrado",
        ctxMenu_Image_WrapText_TopBottom: "Partes Superior e Inferior",
        ctxMenu_Image_WrapText_Behind: "Atrás do Texto",
        ctxMenu_Image_WrapText_InFront: "Na Frente do Texto",
        ctxMenu_Image_WrapText_Other: "Mais Texto Entre Aspas",
        ctxMenu_Image_WrapText_BothSides: "Ambos os Lados",
        ctxMenu_Image_WrapText_LeftOnly: "Esquerda Somente",
        ctxMenu_Image_WrapText_RightOnly: "Direita Somente",
        ctxMenu_Image_WrapText_LargestOnly: "Somente o Maior",

        ctxMenu_Shape_AddText: "Incluir texto",

        ctxMenu_Range_ACL: "Proteger faixa",
        ctxMenu_Sheet_ACL: "Proteger planilha",

        ctxMenu_HeaderFooter: "Cabeçalho / Rodapé",
        ctxMenu_HeaderFooter_DiffFirst: "Somente a Primeira Página",
        ctxMenu_HeaderFooter_DiffOddEven: "Diferenciar Páginas Ímpares e Pares",
        ctxMenu_HeaderFooter_LinkToPre: "Link para o Anterior",

        ctxMenu_copy: "Copiar",
        ctxMenu_paste: "Colar",
        ctxMenu_delete: "Excluir",
        ctxMenu_cut: "Recortar",
        ctxMenu_select: "Selecionar",
        ctxMenu_properties: "Propriedades",
        ctxMenu_bringToFront: "Trazer para Frente",
        ctxMenu_sendToBack: "Voltar",
        ctxMenu_arrange: "Organizar",
        ctxMenu_sendBackward: "Voltar",
        ctxMenu_sendForward: "Avançar",
        ctxMenu_fontStyle: "Estilo de Fonte",
        ctxMenu_selectStyle: "Selecionar Estilo",
        ctxMenu_fontSize: "Tamanho da Fonte",
        ctxMenu_fontFamily: "Família de origem",
        ctxMenu_bold: "Negrito",
        ctxMenu_italic: "Itálico",
        ctxMenu_u: "Sublinhado",
        ctxMenu_strike: "Tachado",
        ctxMenu_super: "Sobrescrito",
        ctxMenu_sub: "Subscrito",
        ctxMenu_color: "Cor",
        ctxMenu_bgcolor: "Cor do Plano de Fundo",
        ctxMenu_highcolor: "Cor de Destaque",
        ctxMenu_restart: "Reiniciar Lista",
        ctxMenu_continue: "Continuar Lista",
        ctxMenu_separate: "Separar Lista",
        ctxMenu_join: "Participar da Lista Anterior",
        ctxMenu_setNumberVal: "Configurar valor da numeração...",
        webClipboardInfoTitle: "Área de Transferência",
        webClipboardInfoOKBtn: "OK",
        webClipboardInfoCutMsg: "Suas configurações de segurança do navegador impedem a cópia automática. Em vez disso, use Ctrl+X em seu teclado.",
        webClipboardInfoCopyMsg: "Suas configurações de segurança do navegador impedem a cópia automática. Em vez disso, use Ctrl+C em seu teclado.",
        webClipboardInfoPasteMsg: "As configurações de segurança de seu navegador impedem que este editor acesse os dados da área de transferência. Em vez disso, use Ctrl+V em seu teclado.",

        clearTrackChangeConfirmMsg: "Toda codificação de cor que marca mudanças neste documento será removida permanentemente. Deseja continuar?"
});

