/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
	fileMenu: "Arquivo",
	fileMenu_New: "Novo",
	fileMenu_NewDocument: "Documento",
	fileMenu_NewDocumentfromTemplate: "Documento do Modelo",
	fileMenu_NewPresentation: "Apresentação",
	fileMenu_NewPresentationfromTemplate: "Apresentação do Modelo",
	fileMenu_NewSpreadsheet: "Planilha",
	fileMenu_Open: "Abrir",
//	fileMenu_Close: "Close",
	fileMenu_Discard: "Descartar",
	fileMenu_Save: "Salvar",
//	fileMenu_SaveAs: "Save As...",
//	fileMenu_SaveAsDraft: "as Draft",
//	fileMenu_SaveInMyDocs: "in My Documents",
//	fileMenu_SaveToSymphony: "to Lotus Symphany",
	fileMenu_ShareWith: "Compartilhar com...	",
	fileMenu_ExportAsPDF: "Exportar como PDF",
	fileMenu_WebPreview: "Visualização da Web",
	fileMenu_PrintPreview: "Visualização de Impressão",
	fileMenu_RecentFile: "Arquivos Recentes",
	fileMenu_Print: "Imprimir...",
	editMenu: "Editar",
	editMenu_Undo: "Desfazer",
	editMenu_Redo: "Refazer",
	editMenu_Cut: "Recortar",
	editMenu_Copy: "Copiar",
	editMenu_Paste: "Colar",
	editMenu_DeleteSlide:"Excluir Slide",
	editMenu_SelectAll: "Selecionar Tudo",
	editMenu_Find: "Localizar...",
	editMenu_Replace: "Substituir...",
	editMenu_DeleteSheet: "Excluir Planilha",
	editMenu_DuplicateSheet: "Duplicar Planilha",
	editMenu_DeleteRow: "Excluir Linha",
	editMenu_DeleteColumn: "Excluir Coluna",
	editMenu_ClearCell: "Limpar Célula",
	viewMenu: "Visualizar",
	viewMenu_Master: "Principal",
	viewMenu_Notifications: "Notificações",
	viewMenu_ShowHideIndicators: "Mostrar/Ocultar Indicadores de Co-edição",
	viewMenu_SlideSorter: "Exibir Classificador de Slide",
	viewMenu_SpeakerNotes: "Mostrar Notas de Alto-falante",
	viewMenu_NextSlide: "Próximo Slide",
	viewMenu_PrevSlide: "Slide Anterior",
	createMenu: "Criar",
	createMenu_NewSlide: "Novo Slide",
	createMenu_DuplicateSlide: "Duplicar Slide",
	createMenu_ImageFromFile: "Gráfico do Arquivo",
	createMenu_TextBox: "Caixa de Texto",
	createMenu_Task: "Tarefa",
    formatMenu_Text_Direction: "Direção do Texto",
    formatMenu_Ltr: "Esquerda para a Direita",
    formatMenu_Rtl: "Direita para a Esquerda",  	
    formatMenu_Horizontal_Align: "Alinhamento Horizontal",
    formatMenu_Vertical_Align: "Alinhamento Vertical",
    formatMenu_Align_Top: "Início da Página",
    formatMenu_Align_Middle: "Meio",
    formatMenu_Align_Bottom: "Parte Inferior",
	layoutMenu: "Layout",
	layoutMenu_SlideLayout: "Layout do Slide",
	layoutMenu_SlideDesign: "Estilos Principais",
	tableMenu: "Tabela",
	tableMenu_CreateTable: "Criar Tabela",
	tableMenu_Cell: "Célula",
	tableMenu_CellAlignLeft: "Alinhar Texto à Esquerda",
	tableMenu_CellAlignCenter: "Alinhar Texto ao Centro",
	tableMenu_CellAlignRight: "Alinhar Texto à Direita",
	tableMenu_CellClearContents: "Limpar Conteúdo",
	tableMenu_Row: "Linha",
	tableMenu_RowAddRowAbove: "Incluir Linha Acima",
	tableMenu_RowAddRowBelow: "Incluir Linha Abaixo",
	tableMenu_RowMoveRowAbove: "Mover Linha para Cima",
	tableMenu_RowMoveRowBelow: "Mover Linha para Baixo",
	tableMenu_RowDelete: "Excluir",
	tableMenu_ColumnAddColumnBefore: "Incluir Coluna Antes",
	tableMenu_ColumnAddColumnAfter: "Incluir Coluna Depois",
	tableMenu_ColumnMoveColumnAfter: "Mover Coluna Depois",
	tableMenu_ColumnMoveColumnBefore: "Mover Coluna Antes",
	tableMenu_ColumnDelete: "Excluir",
	tableMenu_ColumnSortAscending: "Classificar em Ordem Crescente",
	tableMenu_ColumnSortDescending: "Classificar em Ordem Decrescente",
	tableMenu_Column: "Coluna",
	tableMenu_Delete: "Excluir",
	presentationMenu: "Apresentação",
	presentationMenu_SlideShow: "Reproduzir Slide",
	presentationMenu_SlideShowFromCurrent: "Reproduzir a Partir do Slide Atual",
	toolsMenu: "Ferramentas",
	toolsMenu_Task: "Tarefa",
	helpMenu: "Ajuda",
	helpMenu_Overview: "Conteúdo da Ajuda"
})

