define({      
//begin v1.x content
	"clearFilterDialogTitle": "Esborra filtre",
	"filterDefDialogTitle": "Filtre",
	"defaultRuleTitle": "Regla",
	"ruleTitleTemplate": "Regla ${ruleNumber}",
	"noFilterApplied": "No s\'ha aplicat cap filtre.",
	"defineFilter": "Definició de filtre",
	"conditionEqual": "igual a",
	"conditionNotEqual": "no és igual a",
	"conditionLess": "és menor que",
	"conditionLessEqual": "menor que o igual a",
	"conditionGreater": "major que",
	"conditionGreaterEqual": "major que o igual a",
	"conditionContain": "conté",
	"conditionIs": "és",
	"conditionStartWith": "comença per",
	"conditionEndWith": "acaba en",
	"conditionNotContain": "no conté",
	"conditionIsNot": "no és",
	"conditionNotStartWith": "no comença per",
	"conditionNotEndWith": "no acaba en",
	"conditionBefore": "abans",
	"conditionAfter": "després",
	"conditionRange": "rang",
	"conditionIsEmpty": "està buit",
	"all": "totes",
	"any": "qualsevol",
	"relationAll": "totes les regles",
	"waiRelAll": "Coincideix amb totes les regles següents:",
	"relationAny": "qualsevol regla",
	"waiRelAny": "Coincideix amb qualsevol de les regles següents:",
	"relationMsgFront": "Coincideix amb",
	"relationMsgTail": "",
	"and": "i",
	"or": "o",
	"addRuleButton": "Afegeix regla",
	"waiAddRuleButton": "Afegeix una regla nova",
	"removeRuleButton": "Elimina regla",
	"waiRemoveRuleButtonTemplate": "Elimina la regla ${0}",
	"addRuleButton": "Afegeix regla de filtre",
	"cancelButton": "Cancel·la",
	"waiCancelButton": "Cancel·la aquest diàleg",
	"clearButton": "Esborra",
	"waiClearButton": "Esborra el filtre",
	"filterButton": "Filtre",
	"waiFilterButton": "Envia el filtre",
	"columnSelectLabel": "Columna:",
	"waiColumnSelectTemplate": "Columna per a la regla ${0}",
	"conditionSelectLabel": "Condició:",
	"waiConditionSelectTemplate": "Condició per a la regla ${0}",
	"valueBoxLabel": "Valor:",
	"waiValueBoxTemplate": "Introduïu el valor per filtrar per la regla ${0}",
	"rangeTo": "a",
	"rangeTemplate": "de ${0} a ${1}",
	"statusTipHeaderColumn": "Columna",
	"statusTipHeaderCondition": "Regles",
	"statusTipTitle": "Barra de filtre",
	"statusTipMsg": "Premeu la barra de filtre aquí per filtrar pels valors de ${0}.",
	"anycolumn": "qualsevol columna",
	"statusTipTitleNoFilter": "Barra de filtre",
	"statusTipTitleHasFilter": "Filtre",
	"statusTipRelPre": "Coincideix amb",
	"statusTipRelPost": "regles.",
	"statusTipHeaderAll": "Coincideix amb totes les regles.",
	"statusTipHeaderAny": "Coincideix amb qualsevol regla.",
	"defaultItemsName": "elements",
	"filterBarMsgHasFilterTemplate": "${0} de ${1} ${2} mostrats.",
	"filterBarMsgNoFilterTemplate": "No s\'ha aplicat cap filtre",
	"filterBarDefButton": "Definició de filtre",
	"waiFilterBarDefButton": "Filtra la taula",
	"a11yFilterBarDefButton": "Filtre...",
	"filterBarClearButton": "Esborra filtre",
	"waiFilterBarClearButton": "Esborra el filtre",
	"closeFilterBarBtn": "Tanca la barra de filtre",
	"clearFilterMsg": "S\'eliminarà el filtre i es mostrarà tots els registres disponibles.",
	"anyColumnOption": "Qualsevol columna",
	"trueLabel": "Cert",
	"falseLabel": "Fals",
	"radioTrueLabel": "Valor cert",
	"radioFalseLabel": "Valor fals",
	"beginTimeRangeLabel": "Inici de valor de rang temporal",
	"endTimeRangeLabel": "Final de valor de rang temporal",
	"beginDateRangeLabel": "Inici de valor de rang de data",
	"endDateRangeLabel": "Final de valor de rang de data",
	"startsWithExpr": "${0}*"
//end v1.x content
});

