﻿/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        fileMenu: "Fájl",
        fileMenu_New: "Új",
        fileMenu_NewDocument: "Dokumentum",
        fileMenu_NewFromTemplate: "Sablonból",
        fileMenu_NewDocumentfromTemplate: "Dokumentum sablonból",
        fileMenu_NewPresentation: "Bemutató",
        fileMenu_NewPresentationfromTemplate: "Bemutató sablonból",
        fileMenu_NewSpreadsheet: "Táblázat",
        fileMenu_NewSpreadsheetFromTemplate: "Táblázat sablonból",
        fileMenu_Open: "Megnyitás",
        fileMenu_Import: "Importálás...",
        //	fileMenu_Close: "Close",
        fileMenu_Discard: "Visszatérés a legutolsó változathoz",
        fileMenu_ClearTrackChange: "A módosításjelek eltávolítása",
        fileMenu_SpreadsheetSettings: "A dokumentum területi beállításainak megadása...",
        filemenu_revisionhistory: "Módosítások",
        fileMenu_Save: "Mentés",
        fileMenu_SaveAs: "Másolás...",
        fileMenu_AutoPublish: "Automatikus közzététel",
        fileMenu_AutoCheckIn: "Automatikus beadás",
        fileMenu_PublishVersion: "Közzététel most",
        fileMenu_AutoPublish2: "Automatikus mentés a tárba",
        //	fileMenu_AutoPublish_Tips: "Makes your changes available to readers at the end of each editing session.",
        fileMenu_PublishVersion2: "Tárba mentés most",
        fileMenu_AutoPublish3: "Automatikus mentés a következőbe: ${0}",
        fileMenu_PublishVersion3: "Mentés most a következőbe: ${0}",      
        fileMenu_SubmitForReview: "Beküldés áttekintésre...",
        fileMenu_CheckinVersion: "Leadás...",
        fileMenu_Unlock: "Zárolás feloldása",
        //	fileMenu_SaveAsDraft: "as Draft",
        //	fileMenu_SaveInMyDocs: "in My Documents",
        //	fileMenu_SaveToSymphony: "to Lotus Symphany",
        fileMenu_DownloadAs: "Letöltési formátum:",
        fileMenu_PDF: "PDF",
        fileMenu_ODF: "ODF",
        fileMenu_DOC: "Microsoft Word 97-2007 (*.doc)",
        fileMenu_ODS: "ODS",
        fileMenu_XLS: "Microsoft Excel 97-2007 (*.xls) ",
        fileMenu_ShareWith: "Megosztás...",
        fileMenu_ExportAsPDF: "PDF",
        fileMenu_ExportAsODF: "ODF",
        fileMenu_ExportAsPPT: "Microsoft Powerpoint 97-2007 (*.ppt)",
        //	fileMenu_WebPreview: "Web Preview",
        fileMenu_PrintToPDF: "Nyomtatás PDF formátumba...",
        fileMenu_ViewFileDetails: "Fájl részletek megtekintése...",
        fileMenu_RecentFile: "Legutóbbi fájlok",
        fileMenu_Open: "Megnyitás",
        fileMenu_Download: "Letöltés",
        fileMenu_Print: "Nyomtatás",
        fileMenu_Export: "Exportálás",
        fileMenu_ExportToCSV: "CSV",
        fileMenu_ExportToPDF: "PDF (.pdf)",
        fileMenu_ExportToMarkdown: "Markdown (.md)",
        fileMenu_ExportToMS: "Microsoft Office-formátum (.${FILEEXTENSION})",
        fileMenu_ExportToODF: "Open Document-formátum (.${FILEEXTENSION})",
        fileMenu_PgSetup: "Oldalbeállítás...",

        editMenu: "Szerkesztés",
        editMenu_Undo: "Visszavonás",
        editMenu_Redo: "Újra",
        editMenu_Cut: "Kivágás",
        editMenu_Copy: "Másolás",
        editMenu_Paste: "Beillesztés",
        editMenu_DeleteSlide: "Dia törlése",
        editMenu_SelectAll: "Mindet kijelöli",
        editMenu_Find: "Keresés...",
        editMenu_Replace: "Csere...",
        editMenu_FindReplace: "Keresés és csere...",
        editMenu_EditLink: "Hivatkozás hozzáadása vagy szerkesztése",
        editMenu_DeleteSheet: "Munkalap törlése...",
        editMenu_RenameSheet: "Munkalap átnevezése...",
        editMenu_HideSheet: "Munkalap elrejtése",
        editMenu_MoveSheet: "Munkalap áthelyezése...",
        editMenu_DeleteRow: "Sor törlése",
        editMenu_DeleteColumn: "Oszlop törlése",
        editMenu_DeleteCellLeft: "Cellák törlése és eltolás balra",
        editMenu_DeleteCellUp: "Cellák törlése és eltolás felfelé",
        editMenu_ClearCell: "Tartalom törlése",

        viewMenu: "Nézet",
        viewMenu_Master: "Elsődleges",
        viewMenu_Notifications: "Értesítések",
        viewMenu_SlideSorter: "Diarendező",
        viewMenu_SpeakerNotes: "Előadói jegyzetek",
        viewMenu_Toolbar_Basic: "Alapszintű",
        viewMenu_Toolbar_Advanced: "Speciális",
        viewMenu_Toolbar_None: "Nincs",
        viewMenu_Toolbar: "Eszközsáv",
        viewMenu_Statusbar: "Állapotsor",
        viewMenu_Navigator: "Navigátor...",
        //viewMenu_Sidebar: "Sidebar",
        viewMenu_ShowHideIndicators: "A közös szerkesztés jelzéseinek megjelenítése",
        viewMenu_Assignment: "Hozzárendelés-jelző",
        viewMenu_Bookmark: "Könyvjelzők",
        viewMenu_Coediting: "A közös szerkesztés kiemelései",
        viewMenu_Rulers: "Vonalzók",
        viewMenu_WebLayout: "Webes elrendezés",
        viewMenu_AutomaticSpellCheck: "Helyesírás-ellenőrzés beíráskor",
        viewMenu_Formulabar: "Képletsáv",
        viewMenu_moveRight: "Az Enter billentyű jobbra viszi a kurzort",
        viewMenu_showFullString: "A cellákban lévő tartalom kibővítése",
        viewMenu_Doc: "Dokumentum megtekintése",
        viewMenu_Templates: "Sablonok",
        viewMenu_GridLines: "Rácsvonalak elrejtése",
        viewMenu_UnsupportWarning: "A Nem támogatott szolgáltatás üzenetek megjelenítése",
        viewMenu_HiddenSheets: "Rejtett munkalapok",
        viewMenu_FreezeRows: "Sorok befagyasztása",
        viewMenu_FreezeColumns: "Oszlopok befagyasztása",
        viewMenu_NoFrozenRows: "Nincsenek befagyasztott sorok",
        viewmenu_NoFrozenColumns: "Nincsenek befagyasztott oszlopok",
        viewMenu_FreezeXRows: "${0} sor befagyasztása",
        viewMenu_FreezeOneRow: "${0} sor befagyasztása",
        viewMenu_FreezeXColumns: "${0} oszlop befagyasztása",
        viewMenu_FreezeOneColumn: "${0} oszlop befagyasztása",
        viewMenu_CarriageReturn: "Formázási jelek",
        viewMenu_Navigation: "Navigációs panel",
        viewMenu_ACL: "Szerkeszthető területek",
        viewMenu_GridOnOff: "Rácsvonalak",
        viewMenu_ObserverMode: 'Megfigyelő üzemmód',

        createMenu: "Beszúrás",
        createMenu_NewSlide: "Új dia",
        createMenu_DuplicateSlide: "Dia többszörözése",
        createMenu_ImageFromFile: "Kép...",
        createMenu_TextBox: "Szövegmező",
        createMenu_Shape: "Alakzat",
        createMenu_break: "Törés",
        createMenu_RowAbove: "Sor fölé",
        createMenu_RowBelow: "Sor alulra",
        createMenu_ColumnRight: "Oszlop jobbra",
        createMenu_ColumnLeft: "Oszlop balra",
        createMenu_Sheet: "Munkalap...",
        createMenu_Image: "Kép...",
        createMenu_Comments: "Megjegyzés...",
        createMenu_WebLink: "Webes hivatkozás...",
        createMenu_SpecialCharacter: "Különleges karakter...",
        createMenu_Function: "Függvény...",
        createMenu_Fromtemplate: "Létrehozás sablonból",

        insertMenu: "Beszúrás",
        insertMenu_break: "Oldaltörés",
        insertMenu_sectionbreak: "Szakasztörés",
        insertMenu_Bookmark: "Könyvjelző...",
        insertMenu_WebLink: "Link...",
        insertMenu_SpecialCharacter: "Különleges karakter...",
        insertMenu_HorizontalLine: "Vízszintes vonal",
        insertMenu_Header: "Fejléc",
        insertMenu_Footer: "Lábléc",
        insertMenu_TableOfContents: "Tartalomjegyzék",

        insertMenu_HeaderFooter: "Fejléc/lábléc",
        insertMenu_HF_Edit: "Szerkesztés",
        insertMenu_HF_Hide: "Elrejtés",
        insertMenu_Endnotes: "Végjegyzetek",
        insertMenu_RowAbove: "Sor fölé",
        insertMenu_PageNumber: "Oldalszám",
        insertMenu_PageNumberTop: "Oldal teteje",
        insertMenu_PageNumberBottom: "Oldal alja",
        insertMenu_PageNumberCurr: "Jelenlegi helyzet",
        insertMenu_TotalPageNumber: "1. oldal, összesen: N",
        insertMenu_Date: "Dátum...",
        insertMenu_Time: "Időpont...",
        insertMenu_Fields: "Mezők",
        //    insertMenu_Comment: "Comment",
        insertMenu_CellRight: "Cellák és eltolás jobbra",
        insertMenu_CellDown: "Cellák és eltolás lefelé",
        insertMenu_RowBelow: "Sor alulra",
        insertMenu_ColumnBefore: "Oszlop elé",
        insertMenu_ColumnAfter: "Oszlop mögé",
        insertMenu_Sheet: "Munkalap...",
        insertMenu_Image: "Kép...",
        insertMenu_DuplicateSheet: "Munkalap többszörözése",
        insertMenu_Function: "Függvény",
        insertMenu_FunctionSum: "SZUM",
        insertMenu_FunctionAverage: "ÁTLAG",
        insertMenu_FunctionCount: "DARAB",
        insertMenu_FunctionMax: "MAX",
        insertMenu_FunctionMin: "MIN",
        insertMenu_FunctionMore: "További függvények...",
        insertMenu_NameRange: "Elnevezett tartomány",
        insertMenu_NameRangeNew: "Új tartomány...",
        insertMenu_NameRangeManage: "Tartományok kezelése...",
        insertMenu_Chart: "Diagram...",

        contextMenu_insertCellRight: "Cellák beszúrása és eltolás jobbra",
        contextMenu_insertCellDown: "Cellák beszúrása és eltolás lefelé",
        contextMenu_InsertRowAbove: "Sor beszúrása e fölé",
        contextMenu_InsertRowBelow: "Sor beszúrása ez alá",
        contextMenu_InsertColumnBefore: "Oszlop beszúrása ez elé",
        contextMenu_InsertColumnAfter: "Oszlop beszúrása ez után",
        contextMenu_DownloadImage: "Letöltés képként",

        formatMenu: "Formázás",
        formatMenu_Columns: "Oszlopok",
        formatMenu_DefaultFormatting: "Alapértelmezett formázás",
        formatMenu_Template: "Stílusok...",
        contextMenu_Template: "Táblázatstílusok...",
        formatMenu_LineSpacing: "Sortávolság",
        formatMenu_LineSpacing1: "1",
        formatMenu_LineSpacing12: "1,2",
        formatMenu_LineSpacing15: "1,5",
        formatMenu_LineSpacing2: "2",
        formatMenu_LineSpacing25: "2,5",
        formatMenu_LineSpacing3: "3",
        formatMenu_TextProperties: "Szöveg tulajdonságai",
        formatMenu_PageBreakBefore: "Oldaltörés előtte",
        formatMenu_KeepLines: "Egy oldalra",
        formatMenu_WidowControl: "Fattyú- és árvasorok",
        formatMenu_Pagination: "Bekezdés tulajdonságai",
        formatMenu_Bold: "Félkövér",
        formatMenu_Italic: "Dőlt",
        formatMenu_Underline: "Aláhúzott",
        formatMenu_Strikethrough: "Áthúzott",
        formatMenu_IncreaseSize: "Betűméret növelése",
        formatMenu_DecreaseSize: "Betűméret csökkentése",
        formatMenu_ImageProperties: "Kép tulajdonságai...",
        formatMenu_ChartProperties: "Diagramtulajdonságok...",
        formatMenu_EditChart: "Diagram szerkesztése",
        formatMenu_InsertChart: "Diagram beszúrása",
        formatMenu_Properties: "Tulajdonságok...",
        formatMenu_Heading: "Címsor",
        formatMenu_Normal: "Normál",
        formatMenu_Title: "Cím",
        formatMenu_Subtitle: "Alcím",
        formatMenu_Heading1: "1. címsor",
        formatMenu_Heading2: "2. címsor",
        formatMenu_Heading3: "3. címsor",
        formatMenu_Heading4: "4. címsor",
        formatMenu_Heading5: "5. címsor",
        formatMenu_Heading6: "6. címsor",
        formatMenu_Heading7: "7. címsor",
        formatMenu_Heading8: "8. címsor",
        formatMenu_Heading9: "9. címsor",
        formatMenu_BulletedList: "Felsorolásjeles lista",
        formatMenu_NumberedList: "Számozott lista",
        formatMenu_OutLine: "Többszintű lista",
        formatMenu_Superscript: "Felső index",
        formatMenu_Subscript: "Alsó index",
        formatMenu_Align: "Igazítás",
        formatMenu_Left: "Balra",
        formatMenu_Right: "Jobbra",
        formatMenu_Center: "Középre",
        formatMenu_Justify: "Sorkizárt",
        formatMenu_Text_Direction: "Írásirány",
        formatMenu_Ltr: "Balról jobbra",
        formatMenu_Rtl: "Jobbról balra",
        formatMenu_LineSpacing: "Sortávolság",
        formatMenu_LineSpacing1: "1,0",
        formatMenu_LineSpacing115: "1,15",
        formatMenu_LineSpacing15: "1,5",
        formatMenu_LineSpacing2: "2,0",
        formatMenu_LineSpacing25: "2,5",
        formatMenu_LineSpacing3: "3,0",
        formatMenu_Top: "Felülre",
        formatMenu_Bottom: "Alulra",
        formatMenu_Middle: "Középre",
        formatMenu_Direction: "Írásirány",
        formatMenu_Rtl: "Jobbról balra",
        formatMenu_Ltr: "Balról jobbra",
        formatMenu_Auto: "Környezetfüggő",
        formatMenu_SheetDirection: "Munkalap írásiránya",
        formatMenu_SheetRtl: "Jobbról balra",
        formatMenu_SheetLtr: "Balról jobbra",
        formatMenu_Indent: "Behúzás növelése",
        formatMenu_DecreaseIndent: "Behúzás csökkentése",
        formatMenu_ClearFormat: "Formázás törlése",
        formatMenu_RowHeight: "Sormagasság",
        formatMenu_ColumnWidth: "Oszlopszélesség",
        formatMenu_ShowRow: "Sor megjelenítése",
        formatMenu_HideRow: "Sor elrejtése",
        formatMenu_ShowColumn: "Oszlop megjelenítése",
        formatMenu_HideColumn: "Oszlop elrejtése",
        formatMenu_WrapText: "Szöveg tördelése",
        formatMenu_Number: "Szám",
        formatMenu_FontArial: "Arial",
        formatMenu_FontComicSansMS: "Comic Sans MS",
        formatMenu_FontCourierNew: "Courier New",
        formatMenu_FontGeorgia: "Georgia",
        formatMenu_FontLucidaSansUnicode: "Lucida Sans Unicode",
        formatMenu_FontTahoma: "Tahoma",
        formatMenu_FontTimesNewRoman: "Times New Roman",
        formatMenu_FontTrebuchetMS: "Trebuchet MS",
        formatMenu_FontVerdana: "Verdana",
        formatMenu_FontName: "Betűtípus",

        layoutMenu: "Elrendezés",
        layoutMenu_SlideLayout: "Dia elrendezése...",
        layoutMenu_SlideDesign: "Stílusminta...",
        layoutMenu_DefaultFormatting: "Alapértelmezett formázás",
        layoutMenu_Textprop_Bold: "Félkövér",
        layoutMenu_Textprop_Italic: "Dőlt",
        layoutMenu_Textprop_Underline: "Aláhúzott",
        layoutMenu_Textprop_Strikethrough: "Áthúzott",
        layoutMenu_TextProp: "Szöveg tulajdonságai",
        LayoutMenu_RowHeight: "Sormagasság...",
        LayoutMenu_ColumnWidth: "Oszlopszélesség...",
        LayoutMenu_ShowRow: "Sor megjelenítése",
        LayoutMenu_HideRow: "Sor elrejtése",
        LayoutMenu_RenameSheet: "Munkalap átnevezése...",
        LayoutMenu_MoveSheet: "Munkalap áthelyezése",

        tableMenu: "Táblázat",
        tableMenu_Create: "Létrehozás...",
        tableMenu_CreateFromTemplate: "Létrehozás sablonból",
        tableMenu_Delete: "Törlés",
        tableMenu_SetTableColor: "Cellaszín",
        tableMenu_CreateTable: "Táblázat létrehozása",
        tableMenu_Cell: "Cella",
        tableMenu_CellMergeCells: "Cellák egyesítése",
        tableMenu_CellAlignLeft: "Balra igazítás",
        tableMenu_CellAlignCenter: "Középre igazítás",
        tableMenu_CellAlignRight: "Jobbra igazítás",
        tableMenu_CellClearContents: "Tartalom törlése",
        tableMenu_CellProperties: "Cella tulajdonságai...",
        tableMenu_Row: "Sor",
        tableMenu_InsertRowAbove: "Sor beszúrása e fölé",
        tableMenu_InsertRowBelow: "Sor beszúrása ez alá",
        tableMenu_MoveRowAbove: "Sor mozgatása felfelé",
        tableMenu_MoveRowBelow: "Sor mozgatása lefelé",
        tableMenu_RowInsertRow: "Sor beszúrása...",
        tableMenu_RowInsertRowAbove: "Sor beszúrása e fölé",
        tableMenu_RowInsertRowBelow: "Sor beszúrása ez alá",
        tableMenu_RowMoveRowAbove: "Sor e fölé vitele",
        tableMenu_RowMoveRowBelow: "Sor ez alá vitele",
        tableMenu_RowDelete: "Törlés",
        tableMenu_RowRepeat: "Fejlécsor ismétlése",
        tableMenu_InsertColumnBefore: "Oszlop beszúrása ez elé",
        tableMenu_InsertColumnAfter: "Oszlop beszúrása ez után",
        tableMenu_MoveColumnBefore: "Oszlop mozgatása balra",
        tableMenu_MoveColumnAfter: "Oszlop mozgatása jobbra",
        tableMenu_ResizeColumn: "Oszlop átméretezése",
        tableMenu_ResizeColumns: "Oszlopok átméretezése",
        tableMenu_MarkasCategory: "Megjelölés kategóriaként",
        tableMenu_ColumnInsertColumn: "Oszlop beszúrása...",
        tableMenu_ColumnAddColumnBefore: "Oszlop beszúrása ez elé",
        tableMenu_ColumnAddColumnAfter: "Oszlop beszúrása ez után",
        tableMenu_ColumnMoveColumnAfter: "Az oszlop e mögé vitele",
        tableMenu_ColumnMoveColumnBefore: "Az oszlop ez elé vitele",
        tableMenu_ColumnDelete: "Törlés",
        tableMenu_ColumnSortAscending: "Rendezés növekvő sorrendbe",
        tableMenu_ColumnSortDescending: "Rendezés csökkenő sorrendbe",
        tableMenu_Column: "Oszlop",
        tableMenu_Style: "Stílus",
        tableMenu_TableProperties: "Táblázat tulajdonságai...",

        teamMenu: "Csoport",
        teamMenu_AddComment: "Megjegyzés hozzáadása",
        teamMenu_AssignCells: "Cellák hozzárendelése",
        teamMenu_AssignSection: "Szakasz hozzárendelése",
        teamMenu_EditAssignment: "A hozzárendelés módosítása",
        teamMenu_MarkSectionComplete: "A szakasz késznek jelölése",
        teamMenu_MarkAssignmentComplete: "A hozzárendelés késznek jelölése",
        teamMenu_WorkPrivatelyOnSection: "Önálló munka a szakaszon",
        teamMenu_CancelPrivateWork: "Az önálló munka megszakítása",
        teamMenu_ApproveSection: "A szakasz jóváhagyása",
        teamMenu_ApproveAssignment: "A hozzárendelés jóváhagyása",
        teamMenu_ReturnSectionForRework: "A szakasz visszaadása átdolgozásra",
        teamMenu_ReturnAssignmentForRework: "A hozzárendelés visszaadása átdolgozásra",
        teamMenu_RemoveSectionAssignment: "A szakasz-hozzárendelés eltávolítása",
        teamMenu_RemoveCellAssignment: "A cella-hozzárendelés eltávolítása",
        teamMenu_RemoveCompletedAssignments: "A kész hozzárendelések eltávolítása",
        teamMenu_AboutThisSection: "A rész bemutatása",
        teamMenu_AboutAssignment: "A hozzárendelés ismertetése",

        presentationMenu: "Bemutató",
        presentationMenu_SlideShow: "Diavetítés lejátszása",
        presentationMenu_SlideShowWithCoview: "Megosztott diavetítés lejátszása",
        presentationMenu_SlideTransitions: "Diaátmenet alkalmazása...",
        presentationMenu_SlideShowFromCurrent: "Lejátszás a jelenlegi diáról",
        presentationMenu_EmptyCoviewInvites: "Nincs aktív megosztott diavetítés",
        presentationMenu_CoviewInvites: "Aktív megosztott diavetítés",

        dataMenu: "Adatok",
        dataMenu_Sort: "Rendezés...",
        dataMenu_SortAsc: "Rendezés növekvő sorrendbe",
        dataMenu_SortDesc: "Rendezés csökkenő sorrendbe",
        dataMenu_ACL: "Védett területek",
        dataMenu_ACL_DELETE: "Összes jogosultság törlése",
        dataMenu_Validity: "Érvényesség",
        dataMenu_InstantFilter: "Azonnali szűrő",
        dataMenu_Validation: "Érvényesítés...",

        toolsMenu: "Eszközök",
        toolsMenu_AutoComplete: "A cellabejegyzések automatikus kiegészítése",
        toolsMenu_SelectDictionary: "Helyesírási szótárak",
        toolsMenu_Dictionary_ca_CT: "Katalán",
        toolsMenu_Dictionary_cs_CZ: "Cseh (cseh)",
        toolsMenu_Dictionary_da_DK: "Dán (dániai)",
        toolsMenu_Dictionary_nl_NL: "Holland (hollandiai)",
        toolsMenu_Dictionary_en_AU: "Angol (ausztrál)",
        toolsMenu_Dictionary_en_GB: "Angol (nagy-britanniai)",
        toolsMenu_Dictionary_en_US: "Angol (amerikai egyesült államokbeli)",
        toolsMenu_Dictionary_fi_FI: "Finn (finnországi)",
        toolsMenu_Dictionary_fr_FR: "Francia (franciaországi)",
        toolsMenu_Dictionary_fr_CA: "Francia (kanadai)",
        toolsMenu_Dictionary_de_DE: "Német (németországi)",
        toolsMenu_Dictionary_de_CH: "Német (svájci)",
        toolsMenu_Dictionary_el_GR: "Görög (görögországi)",
        toolsMenu_Dictionary_it_IT: "Olasz (olaszországi)",
        toolsMenu_Dictionary_pl_PL: "Lengyel (lengyelországi)",
        toolsMenu_Dictionary_pt_BR: "Portugál (brazil)",
        toolsMenu_Dictionary_pt_PT: "Portugál (portugáliai)",
        toolsMenu_Dictionary_ru_RU: "Orosz (oroszországi)",
        toolsMenu_Dictionary_es_ES: "Spanyol (spanyolországi)",
        toolsMenu_Dictionary_sv_SE: "Svéd (svédországi)",
        toolsMenu_Dictionary_nb_NO: "Norvég (bokmal)",
        toolsMenu_Dictionary_nn_NO: "Norvég (nynorsk)",
        toolsMenu_Dictionary_he_IL: "Héber (izraeli)",
        toolsMenu_SpellCheck: "Helyesírás-ellenőrzés kézi futtatása...",
        toolsMenu_Preferences: "Beállítások",
        toolsMenu_Task: "Feladat",
        toolsMenu_Task_Assigntask: "Feladat hozzárendelése",
        teamMenu_AssignSlide: "Dia hozzárendelése",
        teamMenu_AssignSlides: "Diák hozzárendelése",
        teamMenu_EditSlide: "A dia-hozzárendelés módosítása",
        teamMenu_ReopenSlideAssignment: "A dia-hozzárendelés újramegnyitása",
        teamMenu_ReopenSlideAssignments: "A dia-hozzárendelések újramegnyitása",
        teamMenu_ReassignSlide: "A dia hozzárendelésének megváltoztatása",
        teamMenu_ReassignSlides: "A diák hozzárendelésének megváltoztatása",
        teamMenu_MarkSlidesComplete: "A dia késznek jelölése",
        teamMenu_MarkSlidesCompletes: "A diák késznek jelölése",
        teamMenu_ApproveSlide: "Dia jóváhagyása",
        teamMenu_ApproveSlides: "Diák jóváhagyása",
        teamMenu_ReturnForRework: "A dia visszaadása átdolgozásra",
        teamMenu_ReturnForReworks: "A diák visszaadása átdolgozásra",
        teamMenu_RemoveAssignment: "A dia-hozzárendelés eltávolítása",
        teamMenu_AboutThisSlide: "A dia ismertetése",

        addOnsMenu: "Bővítmények",

        helpMenu: "Súgó",
        helpMenu_About: "Névjegy",
        helpMenu_Overview: "A súgó tartalomjegyzéke",
        helpMenu_NewFeatures: "Újdonságok",
        helpMenu_Tour: "Bemutató",

        accel_fileMenu_Save: "Ctrl+S",
        accel_fileMenu_Save_Mac: "\u2318S",
        accel_fileMenu_Print: "Ctrl+P",
        accel_fileMenu_Print_Mac: "\u2318P",
        accel_editMenu_SelectAll: "Ctrl+A",
        accel_editMenu_SelectAll_Mac: "\u2318A",
        accel_editMenu_Undo: "Ctrl+Z",
        accel_editMenu_Undo_Mac: "\u2318Z",
        accel_editMenu_Redo: "Ctrl+Y",
        accel_editMenu_Redo_Mac: "\u2318Y",
        accel_editMenu_Cut: "Ctrl+X",
        accel_editMenu_Cut_Mac: "\u2318X",
        accel_editMenu_Copy: "Ctrl+C",
        accel_editMenu_Copy_Mac: "\u2318C",
        accel_editMenu_Paste: "Ctrl+V",
        accel_editMenu_Paste_Mac: "\u2318V",
        accel_editMenu_Find: "Ctrl+F",
        accel_editMenu_Find_Mac: "\u2318F",
        accel_insertMenu_Link: "Ctrl+K",
        accel_insertMenu_Link_Mac: "\u2318K",
        accel_insertMenu_Header: "CTRL+SHIFT+H",
        accel_insertMenu_Header_Mac: "\u21e7\u2318H",
        accel_insertMenu_Footer: "CTRL+SHIFT+F",
        accel_insertMenu_Footer_Mac: "\u21e7\u2318F",
        accel_formatMenu_Textprop_Bold: "Ctrl+B",
        accel_formatMenu_Textprop_Bold_Mac: "\u2318B",
        accel_formatMenu_Textprop_Italic: "Ctrl+I",
        accel_formatMenu_Textprop_Italic_Mac: "\u2318I",
        accel_formatMenu_Textprop_FormatPainter: "Ctrl+SHIFT+C, Ctrl+SHIFT+V",
        accel_formatMenu_Textprop_FormatPainter_Mac: "\u21e7\u2318C, \u21e7\u2318V",
        accel_formatMenu_Textprop_Underline: "Ctrl+U",
        accel_formatMenu_Textprop_Underline_Mac: "\u2318U",
        accel_formatMenu_Headingprop_P: "CTRL+SHIFT+0",
        accel_formatMenu_Headingprop_H1: "CTRL+SHIFT+1",
        accel_formatMenu_Headingprop_H2: "CTRL+SHIFT+2",
        accel_formatMenu_Headingprop_H3: "CTRL+SHIFT+3",
        accel_formatMenu_Headingprop_H4: "CTRL+SHIFT+4",
        accel_formatMenu_Headingprop_H5: "CTRL+SHIFT+5",
        accel_formatMenu_Headingprop_H6: "CTRL+SHIFT+6",
        accel_formatMenu_Superscript: "Ctrl+.",
        accel_formatMenu_Superscript_Mac: "\u2318.",
        accel_formatMenu_Subscript: "Ctrl+,",
        accel_formatMenu_Subscript_Mac: "\u2318,",
        accel_formatMenu_Left: "CTRL+SHIFT+L",
        accel_formatMenu_Left_Mac: "\u21e7\u2318L",
        accel_formatMenu_Right: "CTRL+SHIFT+R",
        accel_formatMenu_Right_Mac: "\u21e7\u2318R",
        accel_formatMenu_Center: "CTRL+SHIFT+E",
        accel_formatMenu_Center_Mac: "\u21e7\u2318E",
        accel_formatMenu_Justify: "CTRL+SHIFT+J",
        accel_formatMenu_Justify_Mac: "\u21e7\u2318J",
        accel_formatMenu_Indent: "CTRL+M",
        accel_formatMenu_Indent_Mac: "\u2318M",
        accel_formatMenu_DecreaseIndent: "CTRL+SHIFT+M",
        accel_formatMenu_DecreaseIndent_Mac: "\u21e7\u2318M",
        accel_teamMenu_AddComment: "SHIFT+F2",

        ctxMenuSmartTable: 'Táblázat',
        ctxMenuTableProperties: "Táblázat tulajdonságai",
        ctxMenuDeleteST: 'Törlés',
        ctxMenuDeleteSTTable: 'Táblázat törlése',
        ctxMenuChgSTStyle: 'Stílus módosítása',
        ctxMenuShowCaption: 'Felirat megjelenítése',
        ctxMenuHideCaption: 'Felirat elrejtése',
        ctxMenuResizeST: 'Átméretezés',
        ctxMenuResizeColumnsST: 'Oszlopok átméretezése',
        ctxMenuSTRow: 'Sor',
        ctxMenuAddSTRowAbv: 'Sor beszúrása e fölé',
        ctxMenuAddSTRowBlw: 'Sor beszúrása ez alá',
        ctxMenuMoveSTRowUp: 'Sor e fölé vitele',
        ctxMenuMoveSTRowDown: 'Sor ez alá vitele',
        ctxMenuDelSTRow: 'Törlés',
        ctxMenuRepeatRow: 'Fejlécsor ismétlése',
        ctxMenuSTCol: 'Oszlop',
        ctxMenuAddSTColBfr: 'Oszlop beszúrása ez elé',
        ctxMenuAddSTColAft: 'Oszlop beszúrása ez után',
        ctxMenuMoveSTColBefore: 'Az oszlop ez elé vitele',
        ctxMenuMoveSTColAfter: 'Az oszlop e mögé vitele',
        ctxMenuDelSTCol: 'Törlés',
        ctxMenuSortSTColAsc: 'Rendezés növekvő sorrendbe',
        ctxMenuSortSTColDesc: 'Rendezés csökkenő sorrendbe',
        ctxMenuShowAllFacets: 'Kategóriák megjelenítése',
        ctxMenuHideAllFacets: 'Kategóriák elrejtése',
        ctxMenuSTCell: 'Cella',
        ctxMenuMergeCells: 'Cellák egyesítése',
        ctxMenuMergeDown: 'Egyesítés az alatta lévő cellával',
        ctxMenuVerSplit: 'Felosztás függőlegesen',
        ctxMenuHorSplit: 'Felosztás vízszintesen',
        ctxMenuSplitCells: 'Cellák felosztása...',
        splitCells: 'Cella felosztása',
        ctxMenuAlignTextLeft: 'Balra igazítás',
        ctxMenuAlignTextCenter: 'Középre igazítás',
        ctxMenuAlignTextRight: 'Jobbra igazítás',
        ctxMenuClearSTCellContent: 'Tartalom törlése',
        ctxMenuMakeHeaderRow: 'A kijelölt sor használata fejlécként',
        ctxMenuMakeNonHeaderRow: 'Címsorstílus eltávolítása',
        ctxMenuMakeHeaderCol: 'A kijelölt oszlop használata fejlécként',
        ctxMenuMakeNonHeaderCol: 'Címsorstílus eltávolítása',
        SHEET_CONTEXT_Hide: "Elrejtés", // hide row, column or sheet
        SHEET_CONTEXT_Show: "Megjelenítés", // show row, column
        SHEET_CONTEXT_MoveSheet: "Áthelyezés...", // move sheet
        SHEET_CONTEXT_InsertSheet: "Beszúrás...", // insert sheet
        SHEET_CONTEXT_DeleteSheet: "Törlés...", // delete sheet	
        SHEET_CONTEXT_DuplicateSheet: "Többszörözés...", // duplicate sheet
        SHEET_CONTEXT_RenameSheet: "Átnevezés...", // rename sheet
	
        ctxMenu_Image_WrapText: "Szöveg tördelése",
        ctxMenu_Image_WrapText_Inline: "A szöveggel egy sorba",
        ctxMenu_Image_WrapText_Square: "Négyzet",
        ctxMenu_Image_WrapText_TopBottom: "Felül és alul",
        ctxMenu_Image_WrapText_Behind: "A szöveg mögé",
        ctxMenu_Image_WrapText_InFront: "A szöveg elé",
        ctxMenu_Image_WrapText_Other: "További szövegtördelés",
        ctxMenu_Image_WrapText_BothSides: "Mindkét oldalra",
        ctxMenu_Image_WrapText_LeftOnly: "Csak a bal oldal",
        ctxMenu_Image_WrapText_RightOnly: "Csak a jobb oldal",
        ctxMenu_Image_WrapText_LargestOnly: "Ahol több a hely",

        ctxMenu_Shape_AddText: "Szöveg hozzáadása",

        ctxMenu_Range_ACL: "Tartomány védelme",
        ctxMenu_Sheet_ACL: "Munkalap védelme",

        ctxMenu_HeaderFooter: "Fejléc / Lábléc",
        ctxMenu_HeaderFooter_DiffFirst: "Csak az első oldalon",
        ctxMenu_HeaderFooter_DiffOddEven: "Páros és páratlan oldal eltérő",
        ctxMenu_HeaderFooter_LinkToPre: "Összekapcsolás az előzővel",

        ctxMenu_copy: "Másolás",
        ctxMenu_paste: "Beillesztés",
        ctxMenu_delete: "Törlés",
        ctxMenu_cut: "Kivágás",
        ctxMenu_select: "Kijelölés",
        ctxMenu_properties: "Tulajdonságok",
        ctxMenu_bringToFront: "Előrehozás",
        ctxMenu_sendToBack: "Hátraküldés",
        ctxMenu_arrange: "Elrendezés",
        ctxMenu_sendBackward: "Hátrébb küldés",
        ctxMenu_sendForward: "Előrébb hozás",
        ctxMenu_fontStyle: "Betűtípus stílusa",
        ctxMenu_selectStyle: "Stílus kiválasztása",
        ctxMenu_fontSize: "Betűméret",
        ctxMenu_fontFamily: "Betűtípuscsalád",
        ctxMenu_bold: "Félkövér",
        ctxMenu_italic: "Dőlt",
        ctxMenu_u: "Aláhúzott",
        ctxMenu_strike: "Áthúzott",
        ctxMenu_super: "Felső index",
        ctxMenu_sub: "Alsó index",
        ctxMenu_color: "Szín",
        ctxMenu_bgcolor: "Háttérszín",
        ctxMenu_highcolor: "Kiemelő szín",
        ctxMenu_restart: "A lista újrakezdése",
        ctxMenu_continue: "A lista folytatása",
        ctxMenu_separate: "Külön lista",
        ctxMenu_join: "Egyesítés az előző listával",
        ctxMenu_setNumberVal: "Számozási érték beállítása...",
        webClipboardInfoTitle: "Vágólap",
        webClipboardInfoOKBtn: "OK",
        webClipboardInfoCutMsg: "A böngésző biztonsági beállításai nem engedik az automatikus másolást. Használja helyette a Ctrl+X billentyűkombinációt.",
        webClipboardInfoCopyMsg: "A böngésző biztonsági beállításai nem engedik az automatikus másolást. Használja helyette a Ctrl+C billentyűkombinációt.",
        webClipboardInfoPasteMsg: "A böngésző biztonsági beállításai nem engedik, hogy a szerkesztőprogram hozzáférjen a vágólapon lévő adatokhoz. Használja helyette a Ctrl+V billentyűkombinációt.",

        clearTrackChangeConfirmMsg: "A dokumentum változtatásait jelölő összes színkód végleg el lesz távolítva. Folytatja?"
});

