/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */


define({
        saveTip: "Mentés",
        undoTip: "Visszavonás",
        redoTip: "Újra",
        formatPainterTip: "Formázás másolása",
        showSorterTip: "Diarendező megjelenítése",
        hideSorterTip: "Diarendező elrejtése",
        webClipboardTip: "Webes vágólap",
        spellCheckTip: "Helyesírás-ellenőrzés kézi futtatása",
        createSectionTip: "Szakasz hozzárendelése",
        createCellsTip: "Cellák hozzárendelése",
        createSlideTip: "Diák hozzárendelése",
        submitTip: "Hozzárendelések elküldése",
        addCommentTip: "Megjegyzés hozzáadása",
        removeFormatTip: "Formázás eltávolítása",
        sortAscTip: "Rendezés növekvő sorrendbe",
        sortDescTip: "Rendezés csökkenő sorrendbe",
        instantFilterTip: "Azonnali szűrő",
        insertChartTip: "Diagram beszúrása",
        startAutofillTip: "Automatikus kitöltés",
        dataValidationTip: "Adatérvényesítés",

        selectFontTip: "Betűtípus kiválasztása",
        selectFontSizeTip: "Betűméret kiválasztása",
        selectFontNameTip: "Betűtípus kiválasztása",
        FontName: "Betűtípus neve",
        FontSize: "Betűméret",
        increaseFontSizeTip: "Betűméret növelése",
        decreaseFontSizeTip: "Betűméret csökkentése",
        boldTip: "Félkövér",
        italicTip: "Dőlt",
        underlineTip: "Aláhúzott",
        strikeThroughTip: "Áthúzott",
        setFontColorTip: "Betűszín beállítása",
        setShadingColorTip: "Árnyékszín beállítása",
        setBackgroundFill: "Háttér kitöltésének beállítása",
        setBgColorTip: "Háttérszín beállítása",
        setBorderTip: "A szegély stílusának és színének megadása",
        setBorderColorTip: "Szegélyszín megadása",
        setHighlightColor: "Kiemelési szín megadása",
        formatPainter: "Formázás másolása",
        //	clearFormat:"Remove Formatting",
        zoom: "Nagyítás",
        selectStyleTip: "Stílus kiválasztása",
        styles: "Stílus",
        formatAsCurrencyTip: "Formázás pénznemként",
        formatAsPercentTip: "Formázás százalékként",
        decreaseDecimalTip: "Tizedeshelyek számának csökkentése",
        increaseDecimalTip: "Tizedeshelyek számának növelése",
        formatNumberTip: "Szám formázása",

        numberedListTip: "Számozás hozzáadása vagy a számozás stílusának megváltoztatása",
        bulletedListTip: "Felsorolásjelek hozzáadása vagy a felsorolásjelek stílusának megváltoztatása",
        multilevelListTip: "Többszintes lista hozzáadása vagy megváltoztatása",
        indentTip: "Behúzás növelése",
        decreaseIndentTip: "Behúzás csökkentése",
        alignTip: "Igazítás",
        leftAlignTip: "Balra igazítás",
        centerTip: "Középre igazítás",
        rightAlignTip: "Jobbra igazítás",
        justifyTip: "Sorkizárt",
        bottomBorderTip: "Alsó szegély",
        borderTypes: "Szegélytípusok",
        borderTip: "Szegélystílus megadása",
        topAlignTip: "Felülre igazítás",
        middleAlignTip: "Középre igazítás",
        bottomAlignTip: "Alulra igazítás",
        lineSpacingTip: "Sortávolság",
        mergeSplitCellTip: "Cellák összevonása vagy felosztása",
        wrapNoWrapTip: "Szövegtördelés be- vagy kikapcsolása",
        ltrDirectionTip: "Váltás balról jobbra haladó írásra",
        rtlDirectionTip: "Váltás jobbról balra haladó írásra",
        autoDirectionTip: "Írásirány módosítása",
        toggleSheetDirectionTip: "Munkalap írásirányának módosítása",
        setSheetDirectionLTR: "Balról jobbra",
        setSheetDirectionRTL: "Jobbról balra",

        addTableTip: "Tábla hozzáadása",
        insertOrMoveRowTip: "Sor beszúrása vagy áthelyezése",
        insertOrMoveColTip: "Oszlop beszúrása vagy áthelyezése",
        insertOrDeleteRowTip: "Sor beszúrása vagy törlése",
        insertOrDeleteColTip: "Oszlop beszúrása vagy törlése",
        insertFunctionTip: "Függvény beszúrása",
        insertImage: "Kép beszúrása",
        resizeCol: "Oszlop átméretezése",
        resizeCols: "Oszlopok átméretezése",
        addLink: "Hivatkozás hozzáadása vagy szerkesztése",
        tableStyle: "Táblázatstílusok",

        selectBorder_BottomBorder: "Alsó szegély",
        selectBorder_TopBorder: "Felső szegély",
        selectBorder_LeftBorder: "Bal oldali szegély",
        selectBorder_RightBorder: "Jobb oldali szegély",
        selectBorder_NoBorder: "Nincsenek vonalak",
        selectBorder_AllBorders: "Minden szegély",

        insertOrMoveRow_InsertAbove: "Sor beszúrása e fölé",
        insertOrMoveRow_InsertBelow: "Sor beszúrása ez alá",
        insertOrMoveRow_MoveUp: "Sor mozgatása felfelé",
        insertOrMoveRow_MoveDown: "Sor mozgatása lefelé",
        insertOrMoveCol_InsertLeft: "Oszlop beszúrása ez elé",
        insertOrMoveCol_InsertRight: "Oszlop beszúrása ez után",
        insertOrMoveCol_InsertBefore: "Oszlop beszúrása ez elé",
        insertOrMoveCol_InsertAfter: "Oszlop beszúrása ez után",
        insertOrMoveCol_MoveLeft: "Oszlop mozgatása balra",
        insertOrMoveCol_MoveRight: "Oszlop mozgatása jobbra",

        insertOrDelete_Delete: "Törlés",

        combineButtonReadTip: "A menü aktiválásához nyomja le a lefelé nyíl billentyűt. Ezután a nyílbillentyűkkel tud a menüben mozogni.",

        lineSpacing_1: "1",
        lineSpacing_12: "1,2",
        lineSpacing_15: "1,5",
        lineSpacing_2: "2",
        lineSpacing_25: "2,5",
        lineSpacing_3: "3",

        percent: "%",
        font_arial: "Arial",

        fontSize: "${0} pt",

        slides: "Oldalanként egy dia",
        slidesWithNotes: "Diák megjegyzésekkel",
        preparingSlides: "A diák előkészítése nyomtatásra...",
        printLayoutOptionLabel: "Nyomtatási elrendezési beállítások",

        targetRemovedWhenDialogOpen: "A műveletet nem lehet végrehajtani, mert a célt egy másik közös szerkesztő eltávolította.",

        NUMBER: "Szám",
        CURRENCY: "Pénznem",
        PERCENT: "Százalék",
        DATE: "Dátum",
        TIME: "Idő",
        DATETIME: "Dátum és idő",
        MORECURRENCY: "További pénznemek pénzegységenként",
        MORECURRENCYCODE: "További pénznemek pénznemkódonként",
        MOREDATE: "További idő- és dátumformátumok",
        TEXT: "Szöveg",
	
        // currency, by currency code
        // NOTE: MUST keep it in order
        CURRENCY_CODE: {
            AED: "Egyesült Arab Emírségek (dirham)",
            ARS: "Argentína (peso)",
            AUD: "Ausztrália (dollár)",
            BGN: "Bulgária (leva)",
            BOB: "Bolívia (boliviano)",
            BRL: "Brazília (real)",
            CAD: "Kanada (dollár)",
            CHF: "Svájc (frank)",
            CLP: "Chile (peso)",
            CNY: "Kína (renminbi jüan)",
            COP: "Kolumbia (peso)",
            CRC: "Costa Rica (colón)",
            CZK: "Csehország (korona)",
            DKK: "Dánia (korona)",
            DOP: "Dominikai Köztársaság (peso)",
            EGP: "Egyiptom (font)",
            EUR: "Ausztria, Belgium, Finnország, Franciaország,  ..., Szlovénia, Spanyolország (euró)",
            GBP: "Anglia, Egyesült Királyság (font)",
            HKD: "Hongkong (dollár)",
            HRK: "Horvátország (kuna)",
            HUF: "Magyarország (forint)",
            IDR: "Indonézia (rúpia)",
            ILS: "Izrael (új sékel)",
            INR: "India (rúpia)",
            JPY: "Japán (jen)",
            KRW: "Dél-Korea (won)",
            KZT: "Kazahsztán (tenge)",
            MAD: "Marokkó (dirham)",
            MXN: "Mexikó (peso)",
            MYR: "Malajzia (ringgit)",
            NOK: "Norvégia (korona)",
            NZD: "Új-Zéland (dollár)",
            PAB: "Panama (balboa)",
            PEN: "Peru (új sol)",
            PHP: "Fülöp-szigetek (peso)",
            PKR: "Pakisztán (rúpia)",
            PLN: "Lengyelország (zloty)",
            PYG: "Paraguay (guarani)",
            RON: "Románia (új lej)",
            RSD: "szerb (cirill), szerb (latin)",
            RUB: "Oroszország (rubel)",
            SAR: "Szaúd-Arábia (riál)",
            SEK: "Svédország (korona)",
            SGD: "Szingapúr (dollár)",
            SVC: "El Salvador (colón)",
            THB: "Thaiföld (baht)",
            TRY: "Törökország (líra)",
            TWD: "Tajvan (új dollár)",
            USD: "Ecuador, Puerto Rico, Amerikai Egyesült Államok (amerikai dollár)",
            UYU: "Uruguay (peso)",
            VEF: "Venezuela (erős bolívar)",
            VND: "Vietnam (dong)",
            ZAR: "Dél-Afrikai Köztársaság (rand)"
        },
        // for border toolbar
        allBorders: "Minden szegély",
        innerBorders: "Belső szegélyek",
        horizontalBorders: "Vízszintes szegélyek",
        verticalBorders: "Függőleges szegélyek",
        outerBorders: "Külső szegélyek",
        borderColor: "Szegélyszín",
        leftBorder: "Bal oldali szegély",
        topBorder: "Felső szegély",
        rightBorder: "Jobb oldali szegély",
        bottomBorder: "Alsó szegély",
        clearBorders: "Nincs szegély",
        BorderStyle_ThinSolid: "Vékony folytonos vonal",
        BorderStyle_ThinDotted: "Vékony pontvonal",
        BorderStyle_ThinDashed: "Vékony szaggatott vonal",
        BorderStyle_ThickSolid: "Vastag folytonos vonal",
        BorderStyle_ThickDotted: "Vastag pontvonal",
        BorderStyle_ThickDashed: "Vastag szaggatott vonal"
})

