({
	delete_general: "Eliminar",
	order: "Ordenar",
	align_text: "Alinhar texto",
	align_slide: "Alinhar no diapositivo",
	align_objects: "Alinhar objectos seleccionados",
	zoom: "Zoom",
	zoom_fit: "Ajustar à janela",
	insert_link: "Inserir ligação",
	add_link: "Adicionar ligação",
	open_link: "Abrir ligação",
	edit_link: "Editar ligação",
	remove_link: "Remover ligação",
	insert_link_menu: "Ligação",
	invalid_url: "Não é possível abrir o URL. Verifique se o URL está correcto ou verifique a definição de bloqueio de janelas emergentes do navegador.",
	dnd_canceled_on_slide_event: "O diapositivo não pode ser movido porque a apresentação foi modificada recentemente por outro editor. Tente novamente mais tarde.",
	rotate: "Rodar",
	flipX: "Inverter horizontalmente",
	flipY: "Inverter verticalmente",
	rotate_right: "Rodar no sentido dos ponteiros do relógio 90&#x00B0",
	rotate_left: "Rodar no sentido contrário aos ponteiros do relógio 90&#x00B0",
	color_set_fill: "Definir cor de preenchimento",
	color_nofill: "Sem preenchimento",
	color_nobackground: "Sem segundo plano",
	color_auto: "Automático",
	color_default: "Predefinição",
	color_transparent: "Transparente",
	
	objects_distribute: "Distribuir",
	objects_distribute_v: "Verticalmente",
	objects_distribute_h: "Horizontalmente",
	
	link_subject: "Assunto:",
	link_text: "Texto a apresentar:",
	link_mailto: "Abrir correio electrónico",
	link_goto: "Abrir ligação",
	link_done: "Concluído",
	link_remove: "Remover",
	link_website: "Sítio da Web",
	link_email: "Correio electrónico",
	link_slide: "Diapositivo",
	link_slide_placeholder: "Seleccionar ou escrever número",
	link_slide_placeholder_deleted: "O diapositivo ligado foi eliminado",
	link_slide_next: "Diapositivo seguinte",
	link_slide_prev: "Diapositivo anterior",
	link_slide_first: "Primeiro diapositivo",
	link_slide_last: "Último diapositivo",
	link_slide_number: "Diapositivo ${0}",
	link_not_support: "Tipo de ligação não suportado",
	link_acc_input: "Endereço de ligação de entrada",
	link_acc_mail_input: "Endereço de correio de entrada",
	

	// Jaws Support
	acc_blank: "em branco",// when selection is nothing but space char and empty paragraph
	acc_selected: " seleccionado",
	acc_showed: " apresentado",
	acc_inTable: " na tabela, linha ${0}, coluna ${1} ",
	acc_titleSelected: "título seleccionado",
	acc_subtitleSelected: "subtítulo seleccionado",
	acc_outlineSelected: "destaque seleccionado",
	acc_notesSelected: "notas do orador seleccionadas",
	acc_imageSelected: "imagem seleccionada",
	acc_shapeSelected: "forma seleccionada",
	acc_rotated: " rodado ${0} graus",
	acc_tableSelected: "tabela seleccionada",
	acc_textboxSelected: "caixa de texto seleccionada",
	acc_enterEdit: " prima Enter para editar",
	acc_locked_by: " o qual está bloqueado pelo utilizador ${0}",
	acc_slide_used_by: " o qual é utilizado pelo utilizador ${0}",
	ACC_TABLE_TABLESIZE: "Seleccionou ${0} linhas, ${1} colunas",
	ACC_TABLE_MAXSIZE: " A dimensão máxima de tabela suportada é de 8*8",
	ACC_EditorMode: "modo de edição de editor",
	ACC_EndEditorMode: "terminar modo de edição do editor",
	ACC_Table_new_row: "Foi adicionada uma nova linha",
	ACC_Table_new_column: "É adicionada uma nova coluna",
	Acc_column: "coluna  ${0}",
	acc_slide: "diapositivo ${0}",
	acc_editor: "Editado por ${0}",
	Plain: "Simples",
	BlueStyle: "Estilo azul",
	RedTint: "Tonalidade vermelha",
	BlueHeader: "Cabeçalho azul",
	DarkGrayHF: "Cabeçalho/rodapé cinzento escuro",
	LightGrayRows: "Linhas cinzentas claras",
	DarkGrayRows: "Linhas cinzentas escuras",
	BlueTint: "Tonalidade azul",
	RedHeader: "Cabeçalho vermelho",
	GreenHF: "Cabeçalho/rodapé verde",
	PlainRows: "Linhas sem cor",
	GrayTint: "Tonalidade cinzenta",
	GreenTint: "Tonalidade verde",
	GreenHeader: "Cabeçalho verde",
	RedHF: "Cabeçalho/rodapé vermelho",
	GreenStyle: "Estilo verde",
	PurpleTint: "Tonalidade roxa",
	BlackHeader: "Cabeçalho preto",
	PurpleHeader: "Cabeçalho roxo",
	LightBlueHF: "Cabeçalho/rodapé azul claro",
	
    formatMenu_LineSpacing: "Espaçamento de linhas",
	linespaceboxTitle:"Espaçamento personalizado",
	linespacelineTitle:"Linha:",
	linespacenoticeContent :"Espaçamento de linhas",
    formatMenu_LineSpacing_Customize: "Personalizar...",
    formatMenu_LineSpacing_CustomValue:"Personalização: ${0}",
    lineSpaceWarning:"Escreva um número entre 0 e 10",
    
    set_transparency_menu: "Opacidade da imagem",
    opacity_percent_value: "${0}%",
    opacity_title: "Opacidade",
    
    increaseLineWidthTip: "Aumentar espessura da linha",
	decreaseLineWidthTip : "Diminuir espessura da linha",
    setBorderStyleTip:"Definir estilo da linha",
    line_width_title: "Espessura da linha",
    line_end_title: "Extremidades da linha",
    line_dash_title: "Padrão da linha",
    line_dash_type1: "Sólido",
    line_dash_type2: "Pontos quadrados",
    line_dash_type3: "Traços",
    line_dash_type4: "Pontos redondos",
    line_dash_type5: "Traços e pontos",
    line_dash_type6: "Travessões",
    line_endpoints_type1: "Nenhuma",
    line_endpoints_type2: "Seta para a direita simples",
	line_endpoints_type3: "Seta para a esquerda simples",
	line_endpoints_type4: "Seta dupla simples",
	line_endpoints_type5: "Seta para a direita preenchida",
	line_endpoints_type6: "Seta para a esquerda preenchida",
    line_endpoints_type7: "Seta dupla preenchida",
    line_endpoints_type8: "Círculo e seta preenchidos",
	line_endpoints_type9: "Diamante e seta preenchidos",
	line_endpoints_type10: "Diamantes preenchidos",
    line_endpoints_type11: "Círculos preenchidos"
})

