/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2014. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        spreadsheetTemplates: "Regnearkmaler",
        documentTemplates: "Dokumentmaler",
        titleShareDocument: "Del dokument",
        offline: "Frakoblet",
        versionPublishing: "Publiserer versjonen.",
        versionPublishFailed: "Versjonen ble ikke publisert. Filen er kanskje for stor, eller det oppstod et tidsavbrudd på serveren. Prøv igjen eller avbryt og be administratoren om å kontrollere serverloggen for å identifisere problemet.",
        versionCheckinFailed: "Versjonen ble ikke sjekket inn. Filen er kanskje for stor, eller det oppstod et tidsavbrudd på serveren. Prøv igjen eller avbryt og be administratoren om å kontrollere serverloggen for å identifisere problemet.",
        versionSavedFailed: "Lagringen ble ikke fullført. Prøv å lagre igjen senere.",
        publishFileSizeExceedMsg: "Kan ikke publisere filen fordi den er over maksimumsstørrelsen som er definert datalageradministratoren. Slett noe av innholdet for å gjøre filen mindre, eller be administratoren om å heve størrelsesgrensen.",
        checkinFileSizeExceedMsg: "Kan ikke sjekke inn filen fordi den er over maksimumsstørrelsen som er definert datalageradministratoren. Slett noe av innholdet for å gjøre filen mindre, eller be administratoren om å heve størrelsesgrensen.",
        versionpublished: "Versjon publisert av ${0} klokken ${1}.",
        versionPublishing2: "Lagrer versjonen.",
        versionPublishFailed2: "Versjonen ble ikke lagret. Filen er kanskje for stor, eller det oppstod et tidsavbrudd på serveren. Prøv igjen eller avbryt og be administratoren om å kontrollere serverloggen for å identifisere problemet.",      
        publishFileSizeExceedMsg2: "Kan ikke lagre filen fordi den er over maksimumsstørrelsen som er definert datalageradministratoren. Slett noe av innholdet for å gjøre filen mindre, eller be administratoren om å heve størrelsesgrensen.",
        versionpublished2: "Versjon lagret av ${0} klokken ${1}.",
        chekinCloseDocsMsg: "Du kan lukke ${productName} nå.",
        draftSavingAs: "Kopierer fil...",
        draftSavedAs: "Den nye kopien er lagret som ${0}.",
        synchronizing: "Vent mens synkroniseringsoperasjonen med serveren blir fullført.",
        synchronizeError: "Synkroniseringsoperasjonen med serveren kan ikke fullføres.",
        joinwithoutentitle: "Brukere: ${0} vil redigere dokumentet, men kan ikke delta i redigeringssesjonen fordi du ikke er autorisert for fellesredigering.",
        joinwithoutentitle2: "Brukere: ${0} vil redigere dokumentet, men kan ikke delta i redigeringssesjonen fordi vedkommende ikke er autorisert for fellesredigering.",
        backtoFiles: "Åpne Mine filer",
        backtoCommFiles: "Åpne Fellesskapsfiler",
        backtoLibrary: "Åpne Bibliotek",
        backtoICN: "Åpne Content Navigator",
        backtoRepository: "Åpne Filliste",
        createNewSpred: "Opprett et regneark",
        createNewDoc: "Opprett et dokument",
        createNewDocFromTemp: "Opprett et dokument fra en mal",
        shareDoc: "Del et dokument",
        exportPdf: "Sideoppsett",
        insertDate: "Datovalg",
        insertTime: "Klokkeslettvalg",
        connect: "Koble til",
        theDoc: "dokumentet",
        save: "Lagre endringer",
        saveBeforeReviewMsg: "Du har endringer som ikke er lagret. Lagre endringene og send deretter til korrektur på nytt.",
        submitReviewWidgetsFaiure: "Applikasjonen ble ikke initialisert på riktig måte. Send til korrektur igjen senere.",
        widgetsFaiure: "Applikasjonen ble ikke initialisert på riktig måte.",
        slideSorter: "Lysbilder",
        commentsBar: "Kommentarer",
        draftBadge: "UTKAST",
        share: "Deling",
        comment: "Kommentar",
        showSidebar: "Vis sidelinjen",
        publishVersion: "Publiser",
        checkInVersion: "Sjekk inn",
        saveVersion: "Lagre",
        saved: "Alle endringer er lagret",
        saving: "Lagrer",
        submitFragment: "Send",
        aria_inMainMenu: "Du er nå på hovedmenyen",
        aria_inSlideSorter: "Du er nå i lysbildesorterervisningen",
        aria_inSlideEditor: "Du er nå i lysbilderedigerervisningen",
        createNewPres: "Opprett en presentasjon",
        createNewAppFromTemp: "Opprett et dokument fra en mal",
        textdoc: "tekst",
        sheetdoc: "regneark",
        presdoc: "presentasjons",
        saveAsTextErrMsg: "Det nye tekstdokumentet kan ikke lagres.",
        saveAsPresErrMsg: "Det nye presentasjonsdokumentet kan ikke lagres.",
        saveAsSheetErrMsg: "Det nye regnearkdokumentet kan ikke lagres.",
        saveAsTextErrMsg1: "Det er ikke nok plass til å lagre dokumentet.",
        saveAsPresErrMsg1: "Det er ikke nok plass til å lagre presentasjonen.",
        saveAsSheetErrMsg1: "Det er ikke nok plass til å lagre regnearket.",
        newDocTextErrMsg: "Ikke mulig å opprette et nytt tekstdokument.",
        newDocSheetErrMsg: "Ikke mulig å opprette et nytt regnearkdokument.",
        newDocPresErrMsg: "Ikke mulig å opprette et nytt presentasjonsdokument.",
        newDocTextErrMsg2: "Ikke mulig å opprette et nytt tekstdokument fra malen.",
        newDocSheetErrMsg2: "Ikke mulig å opprette et nytt regnearkdokument fra malen.",
        newDocPresErrMsg2: "Ikke mulig å opprette et nytt presentasjonsdokument fra malen.",
        newDocTextErrMsg3: "Det er ikke nok plass til å opprette et dokument.",
        newDocSheetErrMsg3: "Det er ikke nok plass til å opprette et regneark.",
        newDocPresErrMsg3: "Det er ikke nok plass til å opprette en presentasjon.",
        newDocTextErrMsg4: "Det finnes allerede et dokument med den tittelen. Angi en annen tittel for det nye dokumentet.",
        newDocSheetErrMsg4: "Det finnes allerede et regneark med den tittelen. Angi en annen tittel for det nye regnearket.",
        newDocPresErrMsg4: "Det finnes allerede en presentasjon med den tittelen. Angi en annen tittel for den nye presentasjonen.",        
        aclWarningTitle: "Kan ikke redigere den nye versjonen",
        aclWarningMsg: "Siden fileieren har angitt beskyttede områder i denne filen, er det best å redigere den online. Kontakt fileieren (${0}) hvis du mener at du likevel har behov for å laste opp en ny versjon.",
        aclWarningMsgForOwner: "Det er beskyttede områder i denne filen. Du vil derfor ikke kunne redigere den opplastede nye versjonen online. Du må fjerne alle beskyttede områder i denne filen før du kan åpne og redigere den opplastede nye versjonen.",
        st0: "Ark1",
        st1: "Ark2",
        st2: "Ark3",
        FootnoteMsg: "Side",
        conflictMsg: "Det er en konflikt med det andre redigerere endrer. Endringen din blir opphevet.",
        undoRedoConflictMsg: "Angre- og omgjøringsoperasjonene er satt ut av funksjon på grunn av en konflikt mellom det du redigerer, og det en annen medredigerer arbeider med",
        bigFileErrMsg: "Størrelsen på dokumentet er for stor. Oppdater nettleseren for å se om alt innholdet er intakt",
        noPermissionMsg: "Du har ikke tillatelse til å redigere denne filen. Kontakt eieren av filen for å få redigeringstillatelse, og prøv igjen.",
        networkIssueMsg: "Det har oppstått et nettverksproblem.",
        networkIssueTitle: "Nettverksproblem",
        networkIssueContent: "Det har oppstått et nettverksproblem. Oppdater siden og prøv å koble deg til igjen.",
        lockEditorMsg: "Dokumentet kan ikke redigeres før det er en tilkobling til serveren.",
        offlineReasonMsg: "Sesjonen din ble tidsavbrutt.",
        offlineReasonForServerUnacceptedMsg: "Kan ikke behandlet enkelte av handlingene dine. Handlinger innen 1 minutt vil bli fjernet av Docs-serveren.",
        offlineReasonForServerDraftFormatChange: "Formatet på dokumentet er foreldet på grunn av en serveroppgradering.",
        reloadExplanationMsg: "Logg deg på igjen for å fortsette arbeidet.",
        reloadBtnLabel: "Last inn på nytt",
        reconnectingMsg: "Vent mens tilkoblingen til serveren blir opprettet.",
        loadMsg: "Vent mens dokumentet blir lastet inn.",
        loadingDocumentMsg: "Vent mens dokumentet blir lastet inn fra serveren.",
        reLoadingDocumentMsg: "Vent mens dokumentet blir lastet inn på nytt fra serveren.",
        unsupportMsg: "Det ble oppdaget en funksjon som ikke støttes. Les mer om dette.",
        browserWorkingMsg: "Arbeider...",
        fileDeepDetectTitle: "Filformatet og filtypen stemmer ikke overens",
        fileDeepDetectMsg: "Filformatet er ikke det samme formatet som er angitt av filtypen. Klikk på Fortsett for å redigere filen i dette formatet.",
        fileDeepDetectOkLabel: "Fortsett",
        tipInfo: "Tips: ${0}",
        selectTextInfo: "Velg tekst for å ta i bruk stil.",
        removeRecentFile: "Filen du vil åpne, er slettet. Vil du fjerne filnavnet fra listen Nylig brukte filer?",
        altLotusIcon: "",
        altErrorMsgIcon: "Feilmelding",
        altWarningMsgIcon: "Varselmelding",
        altSuccessMsgIcon: " Vellykket-melding",
        sidebarLandmarkDesc: "sidelinje",
        footerTitle: "bunntekst",
        mainDesc: "innholdsområde",
        editLockedDocumentWarning: "Du låste denne filen mens andre redigerte den. Samarbeid med dem for å koordinere endringene eller be dem om å fullføre redigeringen slik at du kan få eksklusiv redigeringstilgang.",
        observerMode: "Du er nå i observatørmodus",
        editorMode: "Du er nå i redigeringsmodus",
        maxEditorLimitReached: "Dokumentet har nådd det maksimale antall redigerere, ${0}, for denne sesjonen. Du kan bytte til redigeringsmodus når en redigerer forlater dokumentet eller bytter til observatørmodus.",
        maxEditorLimitReachedTitle: "Det maksimale antall redigerere er nådd",
        uploadNewVersionOpenConfirm: "${0} lastet opp en ny versjon klokken ${1} ${2}. Vil du åpne den nye versjonen?", //${0} name, ${1} time, ${2} date
        uploadNewVersionPublishConfirm: "${0} lastet opp en ny versjon klokken ${1} ${2}.", //${0} name, ${1} time, ${2} date
        you: "Du",
        today: "i dag",
        yesterday: "i går",
        slideShowInviteMsg: "Bruker ${0} har startet en delt lysbildefremvisning. Vil du delta?",
        slideShowInviteTitle: "Invitasjon til delt lysbildefremvisning",
        slideShowInviteTitle1: "Invitasjon til felles lysbildefremvisning",
        slideShowCoviewSelectUsersTitle: "Delt lysbildefremvisning",
        slideShowCoviewSelectUsersTitle1: "Felles lysbildefremvisning",
        slideShowCoviewStmt: "Del den gjeldende tilstanden for en presentasjon i en delt lysbildefremvisning.",
        slideShowCoviewStmt1: "Del den gjeldende tilstanden for en presentasjon i en felles lysbildefremvisning.",
        slideShowCoviewOptionOne: "Inviter alle redigerere til å delta i lysbildefremvisningen.",
        slideShowCoviewOptionOne1: "Inviter alle redigerere og observatører til å delta i lysbildefremvisningen.",
        slideShowCoviewOptionTwo: "Inviter bare følgende redigerere til å delta i lysbildefremvisningen.",
        slideShowCoviewOptionTwo1: "Inviter bare følgende redigerere og observatører til å delta i lysbildefremvisningen.",
        slideShowCoviewSlidesOf: "Lysbilde ${0} av ${1}",  //as in Slide 1 of 4
        slideShowCoviewViewers: "${0} seere",
        slideShowCoviewDialogInput: "Skriv for å filtrere navn",
        slideShowCoviewAddTitle: "Legg til i delt lysbildefremvisning",
        slideShowCoviewAddTitle1: "Legg til i felles lysbildefremvisning",
        slideShowCoviewMessage: "Velg ekstra brukere som skal inviteres til denne delte lysbildefremvisningen.",
        slideShowCoviewMessage1: "Velg ekstra brukere som skal inviteres til denne felles lysbildefremvisningen.",
        slideShowCoviewEnded: "Delt lysbildefremvisning avsluttet",
        slideShowCoviewEndMessage: "Den delte lysbildefremvisningen du forsøkte å delta i, er ikke lenger tilgjengelig.",
        slideShowCoviewEndMessage2: "Bruker ${0} har avsluttet den delte lysbildefremvisningen.",
        slideShowWarning: "Du må lukke den gjeldende lysbildefremvisningen før du starter en ny.",
        slideShowHoverMsg: "Klikk på for å se hvilke andre som ser på lysbildefremvisningen.",
        slideShowHoverMsgAdd: "Klikk for å invitere flere seere.",
        csvEmpty: "Kan ikke eksportere som csv-fil fordi arket ikke inneholder data.",
        edit: "Rediger",
        printToPDF: "Last ned som PDF",
        print: "Skriv ut",
        view: "Vis",
        openLatestFile: "Åpne den nyeste filen",
        updateDocument: "Dokumentet ble oppdatert.${0}.",
        updateSpreadsheet: "Regnearket ble oppdatert.${0}",
        updatePresentation: "Presentasjonen ble oppdatert.${0}.",
        labelCancel: "Avbryt",
        msgConversionFail: "Konvertering mislyktes",
        updateNow: "Åpne nå",
        fileUpdated: "Dokumentet ble oppdatert",
        fileUpdatedContent1: "Dokumentet ble oppdatert. Åpne den nyeste filen før du skriver ut.",
        htmlviewerlimitation1: "Dette regnearket inneholder en pivottabell som ikke kan vises",
        htmlviewerlimitation2: "Dette regnearket inneholder betinget formatering som ikke kan vises",
        htmlviewerlimitation3: "Dette regnearket inneholder en pivottabell og betinget formatering som ikke kan vises",
        close: "Lukk",
        closeDocs: "Lukk ${productName}",
        endSessionDlgTitle: "Redigeringssesjonen er avsluttet",
        endSessionDlgNotice: "Redigeringssesjonen din er avsluttet fordi ${0} har sjekket inn filen.",
        labelStopReview: "Stopp korrektur",
        labelRejct: "Forkast",
        labelApprove: "Godkjenn",
        errorMsg: "Feil",
        labelItemNotFountTitle: "Kan ikke fullføre handlingen.",
        labelItemNotFountMsg: "Et annet fellesskapsmedlem har allerede utført en handling på dette dokumentet. Hvis du vil ha mer informasjon, må du lukke dokumentet og gå til siden Fildetaljer i biblioteket.",
        viewProtectedAreas: "Dette regnearket inneholder beskyttede områder. Du bør vise eller redigere det bare online.",
        macroTitle: "Filen inneholder en makro", 
        macroDesc: "Hvis denne filen redigeres, kan makroen bli ødelagt. For å hindre at noen redigerer området eller arket som inneholder makroen, kan du bruke Data > Beskyttede områder.",
        problem_id_msg_title: "Rapporter dette problemet til administratoren. ",
        problem_id_msg_show: "Klikk for å vise detaljer",
    	problem_id_msg_hide: "Klikk for å skjule",
    	uploadNewVersionWarningTitle: "Kan ikke redigere den nye versjonen",
        changeHistoryWarningMsg: "Siden fileieren har aktivert Spor endringer i denne filen, er det best å redigere den online. Kontakt fileieren (${0}) hvis du mener at du likevel har behov for å laste opp en ny versjon.",
        changeHistoryWarningMsgForOwner: "Det er en endringshistorikk i denne filen. Du vil derfor ikke kunne redigere den opplastede nye versjonen online. Du må tømme endringshistorikken og deaktivere Spor endringer i denne filen før du kan åpne og redigere den opplastede nye versjonen.",
        viewChangeHistory: "Dette dokumentet inneholder endringshistorikk. Du bør vise eller redigere det bare online.",
    	contentCorruptErrMsg: "Kan ikke laste inn innholdet fordi det er ødelagt. Kontakt administratoren for å få hjelp."
});

