({
	ORIENTATION_LABEL: "Orientação",
	PORTRAIT: "Vertical",
	LANDSCAPE: "Horizontal",
	PAGE_LABEL: "Ordem das páginas",
	PAGE_TYPE1: "De cima para baixo, depois à direita",
	PAGE_TYPE2: "Da esquerda para a direita, depois para baixo",
	DISPLAY_OPTION_LABEL: "Opções de apresentação",
	HEADER: "Cabeçalho",
	FOOTER: "Rodapé",
	GRIDLINE: "Linhas da grelha",
	TAGGED_PDF: "PDF com etiquetas",
	MARGINS_LABEL: "Margens",
	TOP: "Superior:",
	TOP_DESC:"Margem superior, em centímetros",
	TOP_DESC2:"Margem superior, em polegadas",
	BOTTOM: "Inferior:",
	BOTTOM_DESC:"Margem inferior, em centímetros",
	BOTTOM_DESC2:"Margem inferior, em polegadas",	
	LEFT: "Esquerda:",
	LEFT_DESC:"Margem esquerda, em centímetros",
	LEFT_DESC2:"Margem esquerda, em polegadas",	
	RIGHT: "Direita:",
	RIGHT_DESC:"Margem direita, em centímetros",
	RIGHT_DESC2:"Margem direita, em polegadas",	
	PAPER_FORMAT_LABEL: "Formato do papel",
	PAPER_SIZE_LABEL: "Tamanho do papel:",
	HEIGHT: "Altura:",
	HEIGHT_DESC:"Altura do papel, em centímetros",
	HEIGHT_DESC2:"Altura do papel, em polegadas",		
	WIDTH: "Largura:",
	WIDTH_DESC:"Largura do papel, em centímetros",
	WIDTH_DESC2:"Largura do papel, em polegadas",
	
	INVALID_MSG: "A entrada de dados não é válida e foi rectificada automaticamente. Experimente outro valor, caso pretenda um resultado diferente.",
	
	TOOLTIP1:"Imprime o número máximo de linhas permitido num papel, avançando até já não existirem mais colunas na folha e, em seguida, avança para baixo e para a esquerda para imprimir o próximo grupo de linhas.",
	TOOLTIP2:"Imprime o número máximo de colunas permitido num papel, avançando para baixo até já não existirem mais linhas na folha e, em seguida, avança para cima e para a direita para imprimir o próximo grupo de colunas.",
	CM_LABEL: "cm",
	LETTER: "Carta",
	LEGAL: "Legal",
	TABLOID: "Tablóide",
	USER: "Utilizador",
	SIZE1: "Env. #6 3/4",
	SIZE2: "Env. Monarch",
	SIZE3: "Env. #9",
	SIZE4: "Env. #10",
	SIZE5: "Env. #11",
	SIZE6: "Env. #12",
	SIZE7: "16 kai",
	SIZE8: "32 kai",
	SIZE9: "32 kai de compr"
})
	
