({	
	dlgTaskCreateTitle: "Assign a Section",  
	dlgTaskDeleteTitle: "Remove a Section", 
	dlgTaskEditTitle: "Edit Assignment",
	dlgTaskRewordTitle: "Rework Assignment",
	dlgTaskHistoryTitle: "About this Section",
	dlgTaskReopenTitle: "Reopen Assignment",
	dlgTaskReassignTitle: "Reassign Section",
	dlgTaskDeleteBtn: "Delete",
	creatingTaskAsTODO: "Your assignment is being saved as a to-do item in the Activities application",
	creatingTaskAsTODO2: "The assignment is being saved",
	creatingTaskAsTODO3: "The assignments are being saved",
	updatingTask: "Your assignment is being updated in the Activities application",
	updatingTask2: "The assignment is being updated",
	updatingTask3: "The assignments are being updated",
	restoringTask: "Wait while your assignment is restored in the activity.",
	creatingFragment: "A private document is being created for this section",
	updatingMaster: "Processing... The section is being updated in the main document",
	cannotAccessActivity: "Error! There is no access to the activity server to record assignments. Try again later.",
	cannotAccessActivity2: "Error! There is no access to the server to record assignments. Try again later.",
	cannotAccessActivityContent: "There is no access to the activity server to record assignments. Try again later.",
	cannotRecordAssignment: "There is no access to the activity server to record assignments. Try again later.",
	notMemberofActivity: "The activity cannot record your assignment. Check to make sure that you are added to the activity and try again.",
	cannotLoadActivity: "There is no access to the activity server to load assignments. Try again later.",
	cannotLoadActivity2: "There is no access to the server to load assignments. Try again later.",
	cannotLoadAssignment: "There is no access to the activity server to load this assignment. Try again later.",
	cannotSupportSocialEdit: "You are not entitled for co-editing or assigning sections.",
	cannotDeleteDraft: "The draft cannot be deleted at this time. Delete the file later manually.",
	taskAlreadyRemoved: "The task of this document has been removed, or you are not allowed to edit the task.",
	taskAlreadyCompleted: "The task is complete or cancelled.",
	taskAlreadyReassigned: "The task has been reassigned.",
	assignmentAlreadyExist: "The selected area has been previously assigned.",
	notAllowedEditMaster: "You cannot edit the main document. Check to see if you have permission to do it.",
	notAllowedEditPaticipant: "The assignee or reviewer is not defined or does not have edit access. Make sure that the assignee or reviewer has the correct access.",
	notValidAssignment: "The assignment is invalid, some of the assignment properties on the activity server might be corrupted. You can remove it by clicking Actions > Remove Assignment",
	disableBlockerMsg: "You have a pop-up blocker enabled that prevents the page from displaying correctly.  Allow pop-ups to display for the *cn.ibm.com website.",
	writeDesc: "Write ${0}: ${1}",
	reviewDesc: "Review ${0}: ${1}",
	reworkDesc: "Rework ${0}: ${1}",
	writeCompleteDesc: "Section ${0} written by ${1}",
	reviewCompleteDesc: "Section ${0} reviewed by ${1}",
	workingPrivateDesc: "Working privately on ${0} by ${1}",
	actions: "Actions",	
	onlyAssignerDeleteTask: "You cannot delete this assignment that has not been marked as complete. Only the person who assigned it can delete it.",
	actionBtnEdit: "Edit Assignment",
	actionBtnRemove: "Remove Assignment",
	actionBtnAbout: "About This Section",
	actionBtnMarkComplete: "Mark Complete",
	actionBtnWorkPrivately: "Work Privately",
	actionBtnApprove: "Approve This Section",
	actionBtnGotoPrivate: "Go to Private Document",
	actionBtnCancelPrivate: "Cancel Private Work",
	actionBtnRework: "Rework Required",
	actionBtnReopen: "Reopen Assignment",
	actionBtnReassign: "Reassign Section",
	creating: "Creating...",
	deleting: "Deleting...",
	updating: "Updating...",
	loading: "Loading...",
	restoring: "Restoring...",
	lockCoeditingTask:"Another editor is working on the same assignment. Try again later."
})