/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
    Arrow01_Gray: "חץ 01 אפור",
    Arrow02_Gray: "חץ 02 אפור",
    Arrow03_Red: "חץ 03 אדום",
    Arrow04_Blue: "חץ 04 כחול",
    Arrow05_Blue: "חץ 05 כחול",
    Arrow06_Yellow: "חץ 06 צהוב",
    Arrow07_Red: "חץ אדום 07",
    Arrow08_Gray: "חץ 08 אפור",
    Arrow09_Orange: "חץ 09 כתום",
    Arrow10_Blue: "חץ 10 כחול",
    Arrow11_Blue: "חץ 11 כחול",
    Arrow12_Green: "חץ 12 ירוק",
    Arrow13_Blue: "חץ 13 כחול",
    Arrow14_Green: "חץ 14 ירוק",
    Arrow15_Orange: "חץ 15 כתום",
    Arrow16_Gray: "חץ 16 אפור",
    CircleArrow01_Green: "חץ עיגול 10 ירוק",
    CircleArrow02_Multi: "חץ עיגול 20 צבעוני",
    CircleArrow03_Multi: "חץ עיגול 30 צבעוני",
    CircleArrow04_Multi: "חץ עיגול 40 צבעוני",
    CircleArrow05_Multi: "חץ עיגול 50 צבעוני",
    CircleArrow06_Multi: "חץ עיגול 60 צבעוני",
    CircleArrow07_Blue: "חץ עיגול 07 כחול",
    CircleArrow08_Green: "חץ עיגול 08 ירוק",
    CircleArrow09_Multi: "חץ עיגול 09 צבעוני",
    CurvedArrow01_Gray: "חץ מעוקל 01 אפור",
    CurvedArrow02_Blue: "חץ מעוקל 02 כחול",
    CurvedArrow03_Blue: "חץ מעוקל 03 כחול",
    CurvedArrow04_Orange: "חץ מעוקל 04 כתום",
    CurvedArrow05_Red: "חץ מעוקל 05 אדום",
    CurvedArrow06_Blue: "חץ מעוקל 06 כחול",
    CurvedArrow07_Purple: "חץ מעוקל 07 סגול",
    CurvedArrow08_Green: "חץ מעוקל 08 ירוק",
    CurvedArrow09_Gray: "חץ מעוקל 09 אפור",
    CurvedArrow10_Blue: "חץ מעוקל 10 כחול",
    CurvedArrow11_Orange: "חץ מעוקל 11 כתום",
    CurvedArrow12_Blue: "חץ מעוקל 12 כחול",
    CurvedArrow13_Green: "חץ מעוקל 13 ירוק",
    CurvedArrow14_Brown: "חץ מעוקל 14 חום",
    CurvedArrow15_Blue: "חץ מעוקל 15 כחול",
    CurvedArrow16_Gray: "חץ מעוקל 16 אפור",
    CurvedArrow17_Gray: "חץ מעוקל 17 אפור",
    CurvedArrow18_Gray: "חץ מעוקל 18 אפור",
    CurvedArrow19_Gray: "חץ מעוקל 19 אפור",
    CurvedArrow20_Gray: "חץ מעוקל 20 אפור",
    TrendArrow01_Red: "חץ מגמה 01 אדום",
    TrendArrow02_Green: "חץ מגמה 02 ירוק",
    TrendArrow03_Orange: "חץ מגמה 03 כתום",
    TrendArrow04_Red: "חץ מגמה 04 אדום",
    TrendArrow05_Orange: "חץ מגמה 05 כתום",
    TrendArrow06_Blue: "חץ מגמה 06 כחול",
    TrendArrow07_Orange: "חץ מגמה 07 כתום",
    TrendArrow08_Yellow: "חץ מגמה 08 צהוב",
    TrendArrow09_Blue: "חץ מגמה 09 כחול",
    TrendArrow10_Blue: "חץ מעוקל 10 כחול",
    TrendArrow11_Blue: "חץ מגמה 11 כחול",
    TrendArrow12_Blue: "חץ מגמה 12 כחול",
    TrendArrow13_Red: "חץ מגמה 13 אדום",
    TrendArrow14_Multi: "חץ מעוקל 14 צבעוני",
    TrendArrow15_Blue: "חץ מגמה 15 כחול",
    Bullet01_Circle_DarkRed: "תבליט 01 עיגול אדום כהה",
    Bullet02_Circle_Blue: "תבליט 02 עיגול כחול",
    Bullet03_Circle_Green: "תבליט 03 עיגול ירוק",
    Bullet04_Square_Black: "תבליט 04 ריבוע שחור",
    Bullet05_Square_Orange: "תבליט 05 ריבוע כתום",
    Bullet06_Square_Purple: "תבליט 06 ריבוע סגול",
    Bullet07_Diamond_Blue: "תבליט 07 מעוין כחול",
    Bullet08_Diamond_LightBlue: "תבליט 08 מעוין כחול בהיר",
    Bullet09_Diamond_Red: "תבליט 09 מעוין אדום",
    Bullet10_Star_Yellow: "תבליט 10 כוכב צהוב",
    Bullet11_Star_Blue: "תבליט 11 כוכב כחול",
    Bullet12_Triangle_Blue: "תבליט 12 משולש כחול",
    Bullet13_Triangle_DarkGreen: "תבליט 13 משולש ירוק כהה",
    Bullet14_Arrow_Red: "תבליט 14 חץ אדום",
    Bullet15_Arrow_Blue: "תבליט 15 חץ כחול",
    Bullet16_Box_Blue: "תבליט 16 תיבה כחולה",
    Bullet17_Box_Red: "תבליט 17 תיבה אדומה",
    Bullet18_Asterisk_LightBlue: "תבליט 18 כוכבית כחולה בהירה",
    Bullet19_Leaves_Red: "תבליט 19 עלים אדומים",
    Bullet20_Target_Blue: "תבליט 20 כחול מטרה",
    Bullet21_Arrow_Blue: "תבליט 21 חץ כחול",
    Bullet22_Arrow_DarkBlue: "תבליט 22 חץ כחול כהה",
    Bullet23_Arrow_Brown: "תבליט 23 חץ חום",
    Bullet24_Flag_Red: "תבליט 24 דגל אדום",
    Bullet25_Flag_Green: "תבליט 25 דגל ירוק",
    Bullet26_X_Red: "תבליט 26 X אדום",
    Bullet27_X_Black: "תבליט 27 X שחור",
    Bullet28_Checkmark_Green: "תבליט 28 V ירוק",
    Bullet29_Checkmark_Blue: "תבליטי 29 V כחול",
    Bullet30_Square_DarkRed: "תבליט 30 ריבוע אדום כהה",
    camera: "מצלמה",
    computer1: "מחשב 1",
    computer2: "מחשב 2",
    computer3: "3 מחשב",
    Computer_Cloud: "מחשב ענן",
    Computer_Desktop: "מחשב שולחני",
    Computer_Laptop_Black: "מחשב נייד שחור",
    Computer_Laptop_Silver: "מחשב נייד כסף",
    Database: "מסד נתונים",
    evelope: "מעטפה",
    newspapers: "עיתונים",
    openevelope: "מעטפה פתוחה",
    Server: "שרת",
    speaker: "רמקול",
    WirelessAccessPoint: "נקודת גישה אלחוטית",
    Cycle01_Transparent: "מחזור 01 שקוף",
    Cycle02_Transparent_Blue: "מחזור 02 כחול שקוף",
    Cycle03_Blue: "מחזור 03 כחול",
    Cycle04_Blue: "מחזור 04 כחול",
    Cycle05: "מחזור 05",
    Cycle06: "מחזור 06",
    Cycle07: "מחזור 07",
    Cycle08_Blue: "מחזור 08 כחול",
    Cycle09_Orange: "מחזור 09 כתום",
    Donut01_LightBlue: "טורוס 01 כחול בהיר",
    Donut02_Blue: "טורוס 02 כחול",
    Donut03_Blue: "טורוס 03 כחול",
    Donut04_DarkBlue: "טורוס 04 כחול כהה",
    Donut05_DarkBlue: "טורוס 05 כחול כהה",
    Donut06_Blue: "טורוס 06 כחול",
    Donut07_Blue: "טורוס 07 כחול",
    Graph: "גרף",
    People01_Blue: "אנשים 01 כחול",
    People02: "אנשים 02",
    Pillars01_Orange: "עמודים 01 כתום",
    Pillars02_LightBlue: "עמודים 02 כחול בהיר",
    Process01_Blue: "תהליך 01 כחול",
    Process02_Blue: "תהליך 02 כחול",
    Process03_Blue: "תהליך 03 כחול",
    Process04_GoUp_Blue: "תהליך 04 למעלה כחול",
    Process05_GoUp_Red: "תהליך 05 למעלה אדום",
    Process06_GoUp_Yellow: "תהליך 06 למעלה צהוב",
    Process07_Blue: "תהליך 07 כחול",
    Pyramid01: "פירמידה 01",
    Pyramid02_Blue: "פירמידה 02 כחול",
    Pyramid03: "פירמידה 03",
    Radial01_Green: "מעגלי 01 ירוק",
    Radial02_Green: "מעגלי 02 ירוק",
    Radial03_Sphere: "מעגלי 03 כדור",
    Radial04_Sphere_Red: "מעגלי 04 כדור אדום",
    Radial05_Sphere_Blue: "מעגלי 05 כדור כחול",
    Radial06_Arrows_DarkBlue: "מעגלי 06 חיצים כחול כהה",
    Radial07_Arrows_DarkBlue: "מעגלי 07 חיצים כחול כהה",
    Section_Circle: "חלק מעגל  ",
    Section_Cubes01: "חלק קוביות 01",
    Section_Cubes02_Blue: "חלק קוביות 02 כחול",
    Section_Cubes03_Orange: "חלק קוביות 03 כתום ",
    Section_Cubes04: "חלק קוביות 04",
    Section_Cubes05: "חלק קוביות 05",
    Section_Cuboids01_Blue: "חלק קוביות 01 כחול",
    Section_Cuboids02_Blue: "חלק קוביות 02 כחול",
    Section_Cuboids03: "חלק קוביות 03 ",
    Section_Gears01: "חלק גלגלי שיניים 01",
    Section_Gears02: "חלק גלגלי שיניים 02",
    Section_Gears03: "חלק גלגלי שיניים 03",
    Section_Hexagon04_Orange: "חלק משושה 04 כתום ",
    Section_Hexagons01: "חלק משושים 01",
    Section_Hexagons02_Blue: "חלק משושים 02 כחול",
    Section_Hexagons03_Blue: "חלק משושים 03 כחול",
    Section_Leaves01_LightBlue: "חלק עלים 01 כחול בהיר",
    Section_Leaves02_Green: "חלק עלים 02 ירוק",
    Section_Pasters01: "חלק מדבקות 01",
    Section_Pasters02_Blue: "חלק מדבקות 02 כחול",
    Section_Puzzle01: "חלק פאזל 01",
    Section_Puzzle02: "חלק פאזל 02",
    Section_Puzzle03: "חלק פאזל 03",
    Section_Rectangles: "חלק מלבנים",
    Section_Squares: "חלק ריבועים",
    Section_Triangle: "חלק משולש",
    Target: "מטרה",
    Venn01: "תרשים ון 01",
    Venn02: "תרשים ון 02",
    Venn03: "תרשים ון 03",
    Venn04: "תרשים ון 04",
    Venn05: "תרשים ון 05",
    Venn06_Blue: "תרשים ון 06 כחול",
    Venn07_Blue: "תרשים ון 07 כחול",
    Venn08: "תרשים ון 08",
    Blackboard: "לוח",
    Books: "ספרים",
    Books1: "ספרים 1",
    books2: "ספרים 2",
    Chalk: "גיר",
    clipboard: "לוח גזירים",
    clock: "שעון",
    Globe: "גלובוס",
    Glue: "דבק",
    GraduationCap: "מצנפת סיום ליומדים",
    magnifyingglass: "זכוכית מגדלת",
    Microscope: "מיקרוסקופ",
    Notebook: "פנקס רשימות",
    notepad1: "פנקס רשימות 1",
    notepad2: "פנקס רשימות 2",
    notepad3: "פנקס רשימות 3",
    PaperClip_Blue: "מהדק נייר כחול",
    PaperClip_Red: "מהדק נייר אדום",
    Pencil: "עיפרון",
    Ruler: "סרגל",
    TestTubes: "מבחנות",
    thumbtack: "נעץ",
    clouds: "עננים",
    DrippingFaucet: "ברז דולף",
    Earth: "כדור הארץ",
    EndangeredAnimals1: "חיות בסכנת הכחדה 1",
    EndangeredAnimals2: "חיות בסכנת הכחדה 2",
    GreenCar: "מכונית ירוקה",
    GreenFactory: "מפעל ירוק",
    GreenHouse: "בית ירוק",
    Leaf1: "עלה 1",
    Leaf2: "עלה 2",
    lightbulb: "נורה",
    LightBulb_Flourescent_Off: "נורת פלואורסצנט כבויה",
    LightBulb_Flourescent_On: "נורת פלואורסצנט דולקת",
    LightBulb_Standard_Off1: "נורה רגילה כבויה 1",
    LightBulb_Standard_Off2: "נורה רגילה כבויה 2",
    LightBulb_Standard_On: "נורה רגילה דולקת",
    lightningcloud: "ענן עם ברק",
    Pollution_Car: "זיהום מכונית",
    Pollution_Factory: "זיהום מפעל",
    Raindrop: "טיפת גשם",
    RecycleBin: "סל מחזור",
    RecycleSymbol: "סמל מיחזור",
    RenewableEnergySymbol: "סמל אנרגיה מתחדשת",
    RenewableEnergy_Solar: "אנרגיה מתחדשת סולרית",
    RenewableEnergy_Water: "אנרגיה מתחדשת מים",
    RenewableEnergy_Wind: "אנרגיה מתחדשת רוח",
    sun: "שמש",
    Sun1: "שמש 1",
    Sun2: "שמש 2",
    sundandcloud: "שמש וענן",
    world: "עולם",
    Agreement: "הסכם",
    ATM01: "כספומט 01",
    ATM02: "כספומט 02",
    Balance_Balanced1: "יתרה מאוזן 1",
    Balance_Balanced2: "יתרה מאוזן 2",
    Balance_Unbalanced1: "יתרה לא מאוזן 1",
    Balance_Unbalanced2: "יתרה לא מאוזן 2",
    Calculator: "מחשבון",
    Chart_Decrease1: "תרשים הקטנה 1",
    Chart_Decrease2: "תרשים הקטנה 2",
    Chart_Increase1: "תרשים הגדלה 1",
    Chart_Increase2: "תרשים הגדלה 2",
    Chart_Plateau: "תרשים מישור ",
    Check: "בדיקה",
    Contract: "כיווץ",
    CreditCard_Black: "כרטיס אשראי שחור",
    CreditCard_Cut: "כרטיס אשראי גזזר",
    CreditCard_Gold: "כרטיס אשראי זהב",
    Currency_Dollar: "מטבע דולר ",
    Currency_Dollars: "מטבע דולרים ",
    Currency_Stack: "מטבע ערימה ",
    Currency_StackCoins: "מטבע ערימת מטבעות ",
    GoldBar: "מטיל זהב",
    GoldBar_Stack: "ערימת מטילי זהב",
    MoneyBag01: "שק כסף 01",
    MoneyBag02: "שק כסף 02",
    PercentSign: "סימן אחוז",
    PiggyBank01_Broken: "קופת חסכון 01 שבור",
    PiggyBank02_Broken: "קופת חסכון 02 שבור",
    PiggyBank_Coins: "קופת חסכון מטבעות ",
    PiggyBank_Currency: "קופת חסכון מטבע",
    Portfolio: "תיק",
    PriceTag: "תג מחיר",
    Safe_Closed: "כספת סגורה ",
    Safe_Empty: "כספת ריקה ",
    Safe_Full: "כספת מלאה ",
    Seal_Gold: "חותם זהב ",
    Seal_Red: "חותם אדום ",
    Seal_Silver: "חותם כסף ",
    Wallet_Empty: "ארנק ריק",
    Wallet_Full1: "ארנק מלא 1",
    Wallet_Full2: "ארנק מלא 2",
    BusinessPerson_Female6: "אשת עסקים 6 ",
    BusinessPerson_Male3: "איש עסקים 3",
    Computer_User_Female1: "משתמשת מחשב 1 ",
    ConstructionWorker2: "פועל בניין 2",
    Presenter_Female1: "מציגה 1 ",
    Component_Circle01_Transparent_DarkBlue: "רכיב מעגל 01 כחול כהה שקוף ",
    Component_Circle02_Transparent_Bule: "רכיב מעגל 02 כחול כהה שקוף",
    Component_Circle03_Transparent_Green: "רכיב מעגל 03 ירוק שקוף",
    Component_Circle04_Transparent_Orange: "רכיב מעגל 04 כתום שקוף",
    Component_Circle05_Transparent_Red: "רכיב מעגל 05 אדום שקוף",
    Component_Cube01_DarkBlue: "רכיב קוביה 01 כחול כהה ",
    Component_Cube02_LightBlue: "רכיב קוביה 02 כחול בהיר ",
    Component_Cube03_Green: "רכיב קוביה 03 ירוק ",
    Component_Cube04_Orange: "רכיב קוביה 04 כתום ",
    Component_Cube05_DarkRed: "חלק קוביה 05 אדום כהה",
    Component_Cuboid01_DarkBlue: "רכיב קוביה 01 כחול כהה",
    Component_Cuboid02_Blue: "רכיב קוביה 02 כחול ",
    Component_Cuboid03_Green: "רכיב קוביה 03 ירוק",
    Component_Cuboid04_Orange: "רכיב קוביה 04 כתום",
    Component_Cuboid05_Red: "רכיב קוביה 05 אדום ",
    Component_Gear01_DarkBlue: "רכיב גלגל שיניים 01 כחול כהה",
    Component_Gear02_LightBlue: "רכיב גלגל שיניים 02 כחול בהיר",
    Component_Gear03_Green: "רכיב גלגל שיניים 03 ירוק ",
    Component_Gear04_DarkRed: "רכיב גלגל שיניים 04 אדום כהה",
    Component_Gear05_Orange: "רכיב גלגל שיניים 05 כתום ",
    Component_Person01_DarkBlue: "רכיב אדם 01 כחול כהה",
    Component_Person02_Blue: "רכיב אדם 02 כחול",
    Component_Person03_Green: "רכיב אדם 03 ירוק",
    Component_Person04_DarkRed: "רכיב אדם 04 אדום כהה",
    Component_Person05_Orange: "רכיב אדם 05 כתום",
    Component_PuzzlePiece01_DarkBlue: "רכיב חלק פאזל 01 כחול כהה",
    Component_PuzzlePiece02_Blue: "רכיב חלק פאזל 02 כחול ",
    Component_PuzzlePiece03_Green: "רכיב חלק פאזל 03 ירוק",
    Component_PuzzlePiece04_Red: "רכיב חלק פאזל 04 אדום",
    Component_PuzzlePiece05_Orange: "רכיב חלק פאזל 05 כתום ",
    Component_Sphere01_DarkBlue: "רכיב כדור 01 כחול כהה",
    Component_Sphere02_LightBlue: "רכיב כדור 02 כחול בהיר",
    Component_Sphere03_Green: "רכיב כדור 03 ירוק",
    Component_Sphere04_DarkRed: "רכיב כדור 04 אדום כהה",
    Component_Sphere05_Orange: "רכיב כדור 05 כתום",
    Book: "ספר",
    Box01: "תיבה 01",
    Box02: "תיבה 02",
    Bulb01_Yellow: "נורה 01 צהוב",
    Bulb02_Yellow: "נורה 02 צהוב",
    Calendar: "יומן",
    Chart: "תרשים",
    Clipboard: "לוח גזירים",
    Clock: "שעון",
    Compass: "מצפן ",
    Flag01_Red: "דגל 01 אדום",
    Flag02_Green: "דגל 02 ירוק",
    Flag03_Blue: "דגל 03 כחול",
    Gift: "מתנה",
    House: "בית",
    Icon_Computer01_White: "איקון מחשב 01 לבן",
    Icon_Computer02_Black: "איקון מחשב 02 לבן",
    Icon_Disk01_Blue: "איקון דיסק 01 כחול",
    Icon_Disk02_Green: "איקון דיסק 02 ירוק",
    Icon_Document01_Grey: "איקון מסמך 01 אפור ",
    Icon_Document02_Grey: "איקון מסמך 02 אפור",
    Icon_Document03_Blue: "איקון מסמך 03 כחול",
    Icon_Document04_Blue: "איקון מסמך 04 כחול",
    Icon_Envelope01_Blue: "איקון מעטפה 01 כחול",
    Icon_Envelope02_Yellow: "איקון מעטפה 02 צהוב",
    Icon_Envelope03_Open_Yellow: "איקון 03 מעטפה פתוחה צהוב",
    Icon_Envelope04_Open_Yellow: "איקון 04 מעטפה פתוחה צהוב",
    Icon_Folder01_Yellow: "איקון תיקיה 01 צהוב",
    Icon_Folder02_Yellow: "איקון תיקיה 02 צהוב",
    Icon_Folder03_Open_Yellow: "איקון תיקיה פתוחה 03 צהוב",
    Icon_Folder04_Open_Yellow: "איקון תיקיה פתוחה 04 צהוב",
    Icon_Gear01_Grey: "איקון גלגל שיניים 01 אפור",
    Icon_Gear02_Blue: "איקון גלגל שיניים 02 כחול ",
    Icon_Network01_Blue: "איקון רשת 01 כחול",
    Icon_Network02: "איקון רשת 02 ",
    Icon_Pencil01: "איקון עפרון 01",
    Icon_Pencil02: "איקון עפרון 02",
    Icon_Printer01_White: "איקון מדפסת 01 לבן",
    Icon_Printer02_Black: "איקון מדפסת 02 שחור",
    Key01: "מפתח 01",
    Key02: "מפתח 02",
    Lock01_Yellow: "מנעול 01 צהוב",
    Lock02_Yellow: "מנעול 02 צהוב",
    Lock03_Blue: "מנעול 03 כחול ",
    Lock04_Blue: "מנעול 04 כחול",
    Magnet: "מגנט ",
    MagnifyingGlass: "זכוכית מגדלת",
    Medal: "מדליה ",
    Notebook: "פנקס רשימות",
    Phone: "טלפון",
    PieChart: "תרשים פלחים",
    Pin: "נעץ ",
    PuzzlePiece: "חלק פאזל ",
    PuzzlePieces: "חלקי פאזל ",
    Roadblock: "מחסום דרכים",
    Scissors: "מספריים ",
    Shield01: "מגן 01",
    Shield02_Orange: "מגן 02 כתום  ",
    Shield03_Blue: "מגן 03 כחול",
    Sign_Ban01: "סימן אסור 01",
    Sign_Ban02: "סימן אסור 02",
    Sign_CheckBox01: "סימן תיבת סימון 01",
    Sign_CheckBox02_Unchecked: "סימן תיבת סימון 02 לא מסומנת  ",
    Sign_Checkmark01_Green: "סימן תו סימןן 10 ירוק",
    Sign_Checkmark02_Green: "סימן תו סימון 10 ירוק",
    Sign_DoNotEnter: "סימן אין כניסה  ",
    Sign_Error01: "סימן שגיאה 01",
    Sign_Error02: "סימן שגיאה 02",
    Sign_ExclamationPoint01_Red: "סימן קריאה אדום 01",
    Sign_ExclamationPoint02_Orange: "סימן קריאה 02 כתום ",
    Sign_Help01_Green: "סימן עזרה 10 ירוק",
    Sign_Help02_Blue: "סימן עזרה 02 כחול",
    Sign_Information: "סימון מידע ",
    Sign_Null: "סימן Null",
    Sign_QuestionMark01_Blue: "סימן שאלה 01 כחול",
    Sign_QuestionMark02_Red: "סימן שאלה 02 אדום",
    Sign_RadioButton01: "סימן לחצן רדיו 01",
    Sign_RadioButton02_Unchecked: "סימן לחצן רדיו 02 לא מסומן  ",
    Sign_Warning01_Red: "סימן אזהרה 01 אדום",
    Sign_Warning02_Orange: "סימן אזהרה 02 כתום ",
    Sign_X01_Red: "סימן X 01 אדום",
    Sign_X02_Red: "סימן X 02 אדום",
    Star_Yellow: "כוכב צהוב",
    Wrench: "מפתח ברגים",
    Airplane_Blue: "מטוס כחול",
    Bicycle_Blue: "אופניים כחול",
    Bus: "אוטובוס",
    Canoe_Blue: "קנו כחול  ",
    Car_Red: "מכונית אדום",
    Helicopter_Blue: "מסוק כחול",
    Motorcycle_Red: "אופנוע אדום",
    Pedestrian_Blue: "הולך רגל כחול",
    PersonalTransporter_Green: "רכב אישי ירוק ",
    Sailboat_Red: "סירת מפרש אדום",
    Scooter_Orange: "קטנוע כתום ",
    Train_Red: "רכבת אדום",
    Truck_Blue: "משאית כחול",
    
    aria_category_selector: "אפשרויות קטגוריית תמונה",
    filterImageGallery: "סינון גלריית תמונות"

})
