﻿/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        fileMenu: "קובץ",
        fileMenu_New: "חדש",
        fileMenu_NewDocument: "מסמך",
        fileMenu_NewFromTemplate: "מתוך תבנית",
        fileMenu_NewDocumentfromTemplate: "מסמך מתבנית",
        fileMenu_NewPresentation: "מצגת",
        fileMenu_NewPresentationfromTemplate: "מצגת מתבנית",
        fileMenu_NewSpreadsheet: "גליון אלקטרוני",
        fileMenu_NewSpreadsheetFromTemplate: "גיליון אלקטרוני מתבנית",
        fileMenu_Open: "פתיחה",
        fileMenu_Import: "יבוא...‏",
        //	fileMenu_Close: "Close",
        fileMenu_Discard: "החזרה לגרסה האחרונה",
        fileMenu_ClearTrackChange: "סילוק סימוני שינויים",
        fileMenu_SpreadsheetSettings: "הגדרת אזור מסמך...",
        filemenu_revisionhistory: "גרסאות",
        fileMenu_Save: "שמירה",
        fileMenu_SaveAs: "העתקה...‏",
        fileMenu_AutoPublish: "פרסום אוטומטי",
        fileMenu_AutoCheckIn: "הפקדה אוטומטית ",
        fileMenu_PublishVersion: "פרסום עכשיו",
        fileMenu_AutoPublish2: "שמירה אוטומטית במאגר",
        //	fileMenu_AutoPublish_Tips: "Makes your changes available to readers at the end of each editing session.",
        fileMenu_PublishVersion2: "שמירה במאגר עכשיו",
        fileMenu_AutoPublish3: "שמירה אוטומטית אל ${0}",
        fileMenu_PublishVersion3: "שמירה אל ${0} עכשיו",      
        fileMenu_SubmitForReview: "הגשה לסקירה...",
        fileMenu_CheckinVersion: "הפקדה...‏",
        fileMenu_Unlock: "שחרור נעילה",
        //	fileMenu_SaveAsDraft: "as Draft",
        //	fileMenu_SaveInMyDocs: "in My Documents",
        //	fileMenu_SaveToSymphony: "to Lotus Symphany",
        fileMenu_DownloadAs: "הורדה בתור",
        fileMenu_PDF: "PDF",
        fileMenu_ODF: "ODF",
        fileMenu_DOC: "Microsoft Word 97-2007 (‎*.doc)",
        fileMenu_ODS: "ODS",
        fileMenu_XLS: "Microsoft Excel 97-2007 (‎*.xls) ",
        fileMenu_ShareWith: "שיתוף...‏",
        fileMenu_ExportAsPDF: "PDF",
        fileMenu_ExportAsODF: "ODF",
        fileMenu_ExportAsPPT: "Microsoft Powerpoint 97-2007 (‎*.ppt)",
        //	fileMenu_WebPreview: "Web Preview",
        fileMenu_PrintToPDF: "הדפסה ל-PDF...",
        fileMenu_ViewFileDetails: "הצגת פרטי קובץ...",
        fileMenu_RecentFile: "קבצים אחרונים",
        fileMenu_Open: "פתיחה",
        fileMenu_Download: "הורדה",
        fileMenu_Print: "הדפסה",
        fileMenu_Export: "יצוא",
        fileMenu_ExportToCSV: "CSV",
        fileMenu_ExportToPDF: "PDF (‎.pdf)‎",
        fileMenu_ExportToMarkdown: "Markdown(‎.md)‎",
        fileMenu_ExportToMS: "Microsoft Office format (‎.${FILEEXTENSION})‎",
        fileMenu_ExportToODF: "Open Document format (‎.${FILEEXTENSION})‎",
        fileMenu_PgSetup: "הגדרות עמודים...‏",

        editMenu: "עריכה",
        editMenu_Undo: "ביטול פעולה",
        editMenu_Redo: "שחזור פעולה",
        editMenu_Cut: "גזירה",
        editMenu_Copy: "העתקה",
        editMenu_Paste: "הדבקה",
        editMenu_DeleteSlide: "מחיקת שקופית",
        editMenu_SelectAll: "בחירת הכל",
        editMenu_Find: "חיפוש...",
        editMenu_Replace: "החלפה...",
        editMenu_FindReplace: "חיפוש והחלפה...‏",
        editMenu_EditLink: "הוספה או עריכת קישור",
        editMenu_DeleteSheet: "מחיקת גליון...‏",
        editMenu_RenameSheet: "שינוי שם גליון...‏",
        editMenu_HideSheet: "הסתרת גליון",
        editMenu_MoveSheet: "העברת גליון...",
        editMenu_DeleteRow: "מחיקת שורה",
        editMenu_DeleteColumn: "מחיקת עמודה",
        editMenu_DeleteCellLeft: "מחיקת תאים והזזה שמאלה",
        editMenu_DeleteCellUp: "מחיקת תאים והזזה למעלה",
        editMenu_ClearCell: "מחיקת תוכן",

        viewMenu: "הצגה",
        viewMenu_Master: "תבנית",
        viewMenu_Notifications: "דיווחים",
        viewMenu_SlideSorter: "בורר שקופיות",
        viewMenu_SpeakerNotes: "הערות הדובר",
        viewMenu_Toolbar_Basic: "בסיסי",
        viewMenu_Toolbar_Advanced: "מתקדם",
        viewMenu_Toolbar_None: "ללא",
        viewMenu_Toolbar: "סרגל כלים",
        viewMenu_Statusbar: "סרגל מצב",
        viewMenu_Navigator: "נווט...‏",
        //viewMenu_Sidebar: "Sidebar",
        viewMenu_ShowHideIndicators: "הצגת מחווני עריכה משותפת",
        viewMenu_Assignment: "מחווני הקצאה",
        viewMenu_Bookmark: "סימניות",
        viewMenu_Coediting: "הבלטות עריכה משותפת",
        viewMenu_Rulers: "סרגלים",
        viewMenu_WebLayout: "מתכונת רשת",
        viewMenu_AutomaticSpellCheck: "בדיקת איות בזמן ההקלדה",
        viewMenu_Formulabar: "סרגל נוסחאות",
        viewMenu_moveRight: "Enter מעביר את הסמן לימין",
        viewMenu_showFullString: "הרחבת תוכן בתאים",
        viewMenu_Doc: "הצגת מסמך",
        viewMenu_Templates: "תבניות",
        viewMenu_GridLines: "הסתרת קווי סריג",
        viewMenu_UnsupportWarning: "הצגת הודעות על מאפיינים לא נתמכים",
        viewMenu_HiddenSheets: "גליונות מוסתרים",
        viewMenu_FreezeRows: "הקפאת שורות",
        viewMenu_FreezeColumns: "הקפאת עמודות",
        viewMenu_NoFrozenRows: "אין שורות קפואות",
        viewmenu_NoFrozenColumns: "אין עמודות קפואות",
        viewMenu_FreezeXRows: "הקפאת ${0} שורות",
        viewMenu_FreezeOneRow: "הקפאת ${0} שורה",
        viewMenu_FreezeXColumns: "הקפאת ${0} עמודות",
        viewMenu_FreezeOneColumn: "הקפאת ${0} עמודה",
        viewMenu_CarriageReturn: "סימוני עיצוב",
        viewMenu_Navigation: "חלונית ניווט",
        viewMenu_ACL: "אזורים ניתנים לעריכה",
        viewMenu_GridOnOff: "קווי סריג",
        viewMenu_ObserverMode: 'מצב צופה',

        createMenu: "הוספה",
        createMenu_NewSlide: "שקופית חדשה",
        createMenu_DuplicateSlide: "שכפול שקופית",
        createMenu_ImageFromFile: "תמונה...",
        createMenu_TextBox: "תיבת תמליל",
        createMenu_Shape: "צורה",
        createMenu_break: "מעבר",
        createMenu_RowAbove: "שורה מעל",
        createMenu_RowBelow: "שורה מתחת",
        createMenu_ColumnRight: "עמודה מימין",
        createMenu_ColumnLeft: "עמודה משמאל",
        createMenu_Sheet: "גליון...‏",
        createMenu_Image: "תמונה...",
        createMenu_Comments: "הערה...",
        createMenu_WebLink: "קישור רשת...‏",
        createMenu_SpecialCharacter: "תו מיוחד...‏",
        createMenu_Function: "פונקציה...",
        createMenu_Fromtemplate: "יצירה מתבנית",

        insertMenu: "הוספה",
        insertMenu_break: "מעבר עמוד",
        insertMenu_sectionbreak: "מעבר חלק",
        insertMenu_Bookmark: "סימניה...‏",
        insertMenu_WebLink: "קישור...",
        insertMenu_SpecialCharacter: "תו מיוחד...‏",
        insertMenu_HorizontalLine: "קו אופקי",
        insertMenu_Header: "כותרת עליונה",
        insertMenu_Footer: "כותרת תחתונה",
        insertMenu_TableOfContents: "תוכן עניינים",

        insertMenu_HeaderFooter: "כותרת עליונה/תחתונה",
        insertMenu_HF_Edit: "עריכה",
        insertMenu_HF_Hide: "הסתרה",
        insertMenu_Endnotes: "הערות סיום",
        insertMenu_RowAbove: "שורה מעל",
        insertMenu_PageNumber: "מספר עמוד",
        insertMenu_PageNumberTop: "ראש העמוד",
        insertMenu_PageNumberBottom: "תחתית העמוד",
        insertMenu_PageNumberCurr: "מיקום נוכחי",
        insertMenu_TotalPageNumber: "עמוד 1 מתוך N",
        insertMenu_Date: "תאריך...‏",
        insertMenu_Time: "שעה...‏",
        insertMenu_Fields: "שדות",
        //    insertMenu_Comment: "Comment",
        insertMenu_CellRight: "תאים והזזה ימינה",
        insertMenu_CellDown: "תאים והזזה למטה",
        insertMenu_RowBelow: "שורה מתחת",
        insertMenu_ColumnBefore: "עמודה לפני",
        insertMenu_ColumnAfter: "עמודה אחרי",
        insertMenu_Sheet: "גליון...‏",
        insertMenu_Image: "תמונה...",
        insertMenu_DuplicateSheet: "שכפול גליון",
        insertMenu_Function: "פונקציה",
        insertMenu_FunctionSum: "SUM",
        insertMenu_FunctionAverage: "AVERAGE",
        insertMenu_FunctionCount: "COUNT",
        insertMenu_FunctionMax: "MAX",
        insertMenu_FunctionMin: "MIN",
        insertMenu_FunctionMore: "פונקציות נוספות...",
        insertMenu_NameRange: "טווח מוגדר",
        insertMenu_NameRangeNew: "טווח חדש...",
        insertMenu_NameRangeManage: "ניהול טווחים...",
        insertMenu_Chart: "תרשים...",

        contextMenu_insertCellRight: "הוספת תאים והזזה ימינה",
        contextMenu_insertCellDown: "הוספת תאים והזזה למטה",
        contextMenu_InsertRowAbove: "הוספת שורה מעל",
        contextMenu_InsertRowBelow: "הוספת שורה מתחת",
        contextMenu_InsertColumnBefore: "הוספת עמודה לפני",
        contextMenu_InsertColumnAfter: "הוספת עמודה אחרי",
        contextMenu_DownloadImage: "הורדה כתמונה",

        formatMenu: "עיצוב",
        formatMenu_Columns: "עמודות",
        formatMenu_DefaultFormatting: "עיצוב מחדלי",
        formatMenu_Template: "סגנונות...‏",
        contextMenu_Template: "סגנונות טבלה...‏",
        formatMenu_LineSpacing: "ריווח שורות",
        formatMenu_LineSpacing1: "1",
        formatMenu_LineSpacing12: "1.2",
        formatMenu_LineSpacing15: "1.5",
        formatMenu_LineSpacing2: "2",
        formatMenu_LineSpacing25: "2.5",
        formatMenu_LineSpacing3: "3",
        formatMenu_TextProperties: "תכונות תמליל",
        formatMenu_PageBreakBefore: "מעבר עמוד לפני",
        formatMenu_KeepLines: "השארת שורות ביחד",
        formatMenu_WidowControl: "בקרת אלמנות/יתומים",
        formatMenu_Pagination: "תכונות פיסקה",
        formatMenu_Bold: "מודגש",
        formatMenu_Italic: "נטוי",
        formatMenu_Underline: "קו תחתי",
        formatMenu_Strikethrough: "קו חוצה",
        formatMenu_IncreaseSize: "הגדלת גופן",
        formatMenu_DecreaseSize: "הקטנת גופן",
        formatMenu_ImageProperties: "תכונות תמונה...‏",
        formatMenu_ChartProperties: "תכונות תרשים...",
        formatMenu_EditChart: "עריכת תרשים",
        formatMenu_InsertChart: "הוספת תרשים",
        formatMenu_Properties: "תכונות...‏",
        formatMenu_Heading: "כותרת",
        formatMenu_Normal: "רגיל",
        formatMenu_Title: "כותרת",
        formatMenu_Subtitle: "תת-כותרת",
        formatMenu_Heading1: "כותרת 1",
        formatMenu_Heading2: "כותרת 2",
        formatMenu_Heading3: "כותרת 3",
        formatMenu_Heading4: "כותרת 4",
        formatMenu_Heading5: "כותרת 5",
        formatMenu_Heading6: "כותרת 6",
        formatMenu_Heading7: "כותרת 7",
        formatMenu_Heading8: "כותרת 8",
        formatMenu_Heading9: "כותרת 9",
        formatMenu_BulletedList: "רשימה עם תבליטים",
        formatMenu_NumberedList: "רשימה ממוספרת",
        formatMenu_OutLine: "רשימה רבת-רמות",
        formatMenu_Superscript: "כתב עילי",
        formatMenu_Subscript: "כתב תחתי",
        formatMenu_Align: "יישור",
        formatMenu_Left: "שמאל",
        formatMenu_Right: "ימין",
        formatMenu_Center: "מרכז",
        formatMenu_Justify: "יישור דו-צדדי",
        formatMenu_Text_Direction: "כיוון תמליל",
        formatMenu_Ltr: "משמאל לימין",
        formatMenu_Rtl: "מימין לשמאל",
        formatMenu_LineSpacing: "ריווח שורות",
        formatMenu_LineSpacing1: "1.0",
        formatMenu_LineSpacing115: "1.15",
        formatMenu_LineSpacing15: "1.5",
        formatMenu_LineSpacing2: "2.0",
        formatMenu_LineSpacing25: "2.5",
        formatMenu_LineSpacing3: "3.0",
        formatMenu_Top: "ראש",
        formatMenu_Bottom: "תחתית",
        formatMenu_Middle: "אמצע",
        formatMenu_Direction: "כיוון תמליל",
        formatMenu_Rtl: "מימין לשמאל",
        formatMenu_Ltr: "משמאל לימין",
        formatMenu_Auto: "תלוי-הקשר",
        formatMenu_SheetDirection: "כיוון גליון",
        formatMenu_SheetRtl: "מימין לשמאל",
        formatMenu_SheetLtr: "משמאל לימין",
        formatMenu_Indent: "הגדלת כניסה",
        formatMenu_DecreaseIndent: "הקטנת כניסה",
        formatMenu_ClearFormat: "ניקוי עיצוב",
        formatMenu_RowHeight: "גובה שורה",
        formatMenu_ColumnWidth: "רוחב עמודה",
        formatMenu_ShowRow: "הצגת שורה",
        formatMenu_HideRow: "הסתרת שורה",
        formatMenu_ShowColumn: "הצגת עמודה",
        formatMenu_HideColumn: "הסתרת עמודה",
        formatMenu_WrapText: "גלישת תמליל",
        formatMenu_Number: "מספר",
        formatMenu_FontArial: "Arial",
        formatMenu_FontComicSansMS: "Comic Sans MS",
        formatMenu_FontCourierNew: "Courier New",
        formatMenu_FontGeorgia: "Georgia",
        formatMenu_FontLucidaSansUnicode: "Lucida Sans Unicode",
        formatMenu_FontTahoma: "Tahoma",
        formatMenu_FontTimesNewRoman: "Times New Roman",
        formatMenu_FontTrebuchetMS: "Trebuchet MS",
        formatMenu_FontVerdana: "Verdana",
        formatMenu_FontName: "גופן",

        layoutMenu: "מתכונת",
        layoutMenu_SlideLayout: "מתכונת שקופית...‏",
        layoutMenu_SlideDesign: "סגנון אב...‏",
        layoutMenu_DefaultFormatting: "עיצוב מחדלי",
        layoutMenu_Textprop_Bold: "מודגש",
        layoutMenu_Textprop_Italic: "נטוי",
        layoutMenu_Textprop_Underline: "קו תחתי",
        layoutMenu_Textprop_Strikethrough: "קו חוצה",
        layoutMenu_TextProp: "תכונות תמליל",
        LayoutMenu_RowHeight: "גובה שורה...‏",
        LayoutMenu_ColumnWidth: "רוחב עמודה...‏",
        LayoutMenu_ShowRow: "הצגת שורה",
        LayoutMenu_HideRow: "הסתרת שורה",
        LayoutMenu_RenameSheet: "שינוי שם גליון...‏",
        LayoutMenu_MoveSheet: "העברת גליון",

        tableMenu: "טבלה",
        tableMenu_Create: "יצירה...‏",
        tableMenu_CreateFromTemplate: "יצירה מתבנית",
        tableMenu_Delete: "מחיקה",
        tableMenu_SetTableColor: "צבע תא",
        tableMenu_CreateTable: "יצירת טבלה",
        tableMenu_Cell: "תא",
        tableMenu_CellMergeCells: "מיזוג תאים",
        tableMenu_CellAlignLeft: "יישור לשמאל",
        tableMenu_CellAlignCenter: "יישור למרכז",
        tableMenu_CellAlignRight: "יישור לימין",
        tableMenu_CellClearContents: "ניקוי תוכן",
        tableMenu_CellProperties: "תכונות תא...",
        tableMenu_Row: "שורה",
        tableMenu_InsertRowAbove: "הוספת שורה מעל",
        tableMenu_InsertRowBelow: "הוספת שורה מתחת",
        tableMenu_MoveRowAbove: "העברת שורה למעלה",
        tableMenu_MoveRowBelow: "העברת שורה למטה",
        tableMenu_RowInsertRow: "הוספת שורה...",
        tableMenu_RowInsertRowAbove: "הוספת שורה מעל",
        tableMenu_RowInsertRowBelow: "הוספת שורה מתחת",
        tableMenu_RowMoveRowAbove: "העברת שורה מעל",
        tableMenu_RowMoveRowBelow: "העברת שורה מתחת",
        tableMenu_RowDelete: "מחיקה",
        tableMenu_RowRepeat: "חזרה על שורת הכותרת",
        tableMenu_InsertColumnBefore: "הוספת עמודה לפני",
        tableMenu_InsertColumnAfter: "הוספת עמודה אחרי",
        tableMenu_MoveColumnBefore: "העברת עמודה שמאלה",
        tableMenu_MoveColumnAfter: "העברת עמודה ימינה",
        tableMenu_ResizeColumn: "שינוי גודל עמודה",
        tableMenu_ResizeColumns: "שינוי גודל עמודות",
        tableMenu_MarkasCategory: "סימון כקטגוריה",
        tableMenu_ColumnInsertColumn: "הוספת עמודה...",
        tableMenu_ColumnAddColumnBefore: "הוספת עמודה לפני",
        tableMenu_ColumnAddColumnAfter: "הוספת עמודה אחרי",
        tableMenu_ColumnMoveColumnAfter: "העברת עמודה אחרי",
        tableMenu_ColumnMoveColumnBefore: "העברת עמודה לפני",
        tableMenu_ColumnDelete: "מחיקה",
        tableMenu_ColumnSortAscending: "מיון עולה",
        tableMenu_ColumnSortDescending: "מיון יורד",
        tableMenu_Column: "עמודה",
        tableMenu_Style: "סגנון",
        tableMenu_TableProperties: "תכונות טבלה...‏",

        teamMenu: "צוות",
        teamMenu_AddComment: "הוספת הערה",
        teamMenu_AssignCells: "הקצאת תאים",
        teamMenu_AssignSection: "הקצאת חלק",
        teamMenu_EditAssignment: "עריכת הקצאה",
        teamMenu_MarkSectionComplete: "סימון 'הושלם' לבחירה",
        teamMenu_MarkAssignmentComplete: "סימון 'הושלם' להקצאה",
        teamMenu_WorkPrivatelyOnSection: "עבודה פרטית על חלק",
        teamMenu_CancelPrivateWork: "ביטול עבודה פרטית",
        teamMenu_ApproveSection: "אישור חלק",
        teamMenu_ApproveAssignment: "אישור הקצאה",
        teamMenu_ReturnSectionForRework: "החזרת חלק לעיבוד חוזר",
        teamMenu_ReturnAssignmentForRework: "החזרת הקצאה לעיבוד חוזר",
        teamMenu_RemoveSectionAssignment: "סילוק הקצאת חלק",
        teamMenu_RemoveCellAssignment: "סילוק הקצאת תא",
        teamMenu_RemoveCompletedAssignments: "סילוק הקצאות שהושלמו",
        teamMenu_AboutThisSection: "אודות חלק זה",
        teamMenu_AboutAssignment: "אודות הקצאה זו",

        presentationMenu: "מצגת",
        presentationMenu_SlideShow: "הרצת מצגת שקופיות",
        presentationMenu_SlideShowWithCoview: "הרצת מצגת שקופיות משותפת",
        presentationMenu_SlideTransitions: "החלת מעבר שקופיות...‏",
        presentationMenu_SlideShowFromCurrent: "הרצה מהשקופית הנוכחית",
        presentationMenu_EmptyCoviewInvites: "אין מצגת שקופיות משותפת פעילה",
        presentationMenu_CoviewInvites: "מצגת שקופיות משותפת פעילה",

        dataMenu: "נתונים",
        dataMenu_Sort: "מיון...‏",
        dataMenu_SortAsc: "מיון עולה",
        dataMenu_SortDesc: "מיון יורד",
        dataMenu_ACL: "אזורים מוגנים",
        dataMenu_ACL_DELETE: "מחיקת כל ההרשאות",
        dataMenu_Validity: "תוקף",
        dataMenu_InstantFilter: "מסנן מידי",
        dataMenu_Validation: "אימות...",

        toolsMenu: "כלים",
        toolsMenu_AutoComplete: "השלמה אוטומטית של ערכי תאים",
        toolsMenu_SelectDictionary: "מילוני בדיקת איות",
        toolsMenu_Dictionary_ca_CT: "קטלאנית",
        toolsMenu_Dictionary_cs_CZ: "צ'כית (צ'כיה)",
        toolsMenu_Dictionary_da_DK: "דנית (דנמרק)",
        toolsMenu_Dictionary_nl_NL: "הולנדית (הולנד)",
        toolsMenu_Dictionary_en_AU: "אנגלית (אוסטרליה)",
        toolsMenu_Dictionary_en_GB: "אנגלית (בריטניה)",
        toolsMenu_Dictionary_en_US: "אנגלית (ארצות הברית)",
        toolsMenu_Dictionary_fi_FI: "פינית (פינלנד)",
        toolsMenu_Dictionary_fr_FR: "צרפתית (צרפת)",
        toolsMenu_Dictionary_fr_CA: "צרפתית (קנדה)",
        toolsMenu_Dictionary_de_DE: "גרמנית (גרמניה)",
        toolsMenu_Dictionary_de_CH: "גרמנית (שוויץ)",
        toolsMenu_Dictionary_el_GR: "יוונית (יוון)",
        toolsMenu_Dictionary_it_IT: "איטלקית (איטליה)",
        toolsMenu_Dictionary_pl_PL: "פולנית (פולין)",
        toolsMenu_Dictionary_pt_BR: "פורטוגזית (ברזיל)",
        toolsMenu_Dictionary_pt_PT: "פורטוגזית (פורטוגל)",
        toolsMenu_Dictionary_ru_RU: "רוסית (רוסיה)",
        toolsMenu_Dictionary_es_ES: "ספרדית (ספרד)",
        toolsMenu_Dictionary_sv_SE: "שוודית (שוודיה)",
        toolsMenu_Dictionary_nb_NO: "נורווגית (Bokml)",
        toolsMenu_Dictionary_nn_NO: "נורווגית (Nynorsk)",
        toolsMenu_Dictionary_he_IL: "עברית (ישראל)",
        toolsMenu_SpellCheck: "הרצת בדיקת איות ידנית...",
        toolsMenu_Preferences: "העדפות",
        toolsMenu_Task: "משימה",
        toolsMenu_Task_Assigntask: "הקצאת משימה",
        teamMenu_AssignSlide: "הקצאת שקופית",
        teamMenu_AssignSlides: "הקצאת שקופיות",
        teamMenu_EditSlide: "עריכת הקצאת שקופית",
        teamMenu_ReopenSlideAssignment: "פתיחה מחדש של הקצאת שקופית",
        teamMenu_ReopenSlideAssignments: "פתיחה מחדש של הקצאות שקופיות",
        teamMenu_ReassignSlide: "הקצאה מחדש של שקופית",
        teamMenu_ReassignSlides: "הקצאה מחדש של שקופיות",
        teamMenu_MarkSlidesComplete: "סימון 'הושלם' לשקופית",
        teamMenu_MarkSlidesCompletes: "סימון 'הושלם' לשקופיות",
        teamMenu_ApproveSlide: "אישור שקופית",
        teamMenu_ApproveSlides: "אישור שקופיות",
        teamMenu_ReturnForRework: "החזרת שקופית לעיבוד חוזר",
        teamMenu_ReturnForReworks: "החזרת שקופיות לעיבוד חוזר",
        teamMenu_RemoveAssignment: "סילוק הקצאת שקופית",
        teamMenu_AboutThisSlide: "אודות שקופית זו",

        addOnsMenu: "תוספים",

        helpMenu: "עזרה",
        helpMenu_About: "אודות",
        helpMenu_Overview: "תוכן עזרה",
        helpMenu_NewFeatures: "מה חדש",
        helpMenu_Tour: "סיור מודרך",

        accel_fileMenu_Save: "Ctrl+S",
        accel_fileMenu_Save_Mac: "\u2318S",
        accel_fileMenu_Print: "Ctrl+P",
        accel_fileMenu_Print_Mac: "\u2318P",
        accel_editMenu_SelectAll: "Ctrl+A",
        accel_editMenu_SelectAll_Mac: "\u2318A",
        accel_editMenu_Undo: "Ctrl+Z",
        accel_editMenu_Undo_Mac: "\u2318Z",
        accel_editMenu_Redo: "Ctrl+Y",
        accel_editMenu_Redo_Mac: "\u2318Y",
        accel_editMenu_Cut: "Ctrl+X",
        accel_editMenu_Cut_Mac: "\u2318X",
        accel_editMenu_Copy: "Ctrl+C",
        accel_editMenu_Copy_Mac: "\u2318C",
        accel_editMenu_Paste: "Ctrl+V",
        accel_editMenu_Paste_Mac: "\u2318V",
        accel_editMenu_Find: "Ctrl+F",
        accel_editMenu_Find_Mac: "\u2318F",
        accel_insertMenu_Link: "Ctrl+K",
        accel_insertMenu_Link_Mac: "\u2318K",
        accel_insertMenu_Header: "CTRL+SHIFT+H",
        accel_insertMenu_Header_Mac: "\u21e7\u2318H",
        accel_insertMenu_Footer: "CTRL+SHIFT+F",
        accel_insertMenu_Footer_Mac: "\u21e7\u2318F",
        accel_formatMenu_Textprop_Bold: "Ctrl+B",
        accel_formatMenu_Textprop_Bold_Mac: "\u2318B",
        accel_formatMenu_Textprop_Italic: "Ctrl+I",
        accel_formatMenu_Textprop_Italic_Mac: "\u2318I",
        accel_formatMenu_Textprop_FormatPainter: "Ctrl+SHIFT+C,‏ Ctrl+SHIFT+V",
        accel_formatMenu_Textprop_FormatPainter_Mac: "\u21e7\u2318C,‏ \u21e7\u2318V",
        accel_formatMenu_Textprop_Underline: "Ctrl+U",
        accel_formatMenu_Textprop_Underline_Mac: "\u2318U",
        accel_formatMenu_Headingprop_P: "CTRL+SHIFT+0",
        accel_formatMenu_Headingprop_H1: "CTRL+SHIFT+1",
        accel_formatMenu_Headingprop_H2: "CTRL+SHIFT+2",
        accel_formatMenu_Headingprop_H3: "CTRL+SHIFT+3",
        accel_formatMenu_Headingprop_H4: "CTRL+SHIFT+4",
        accel_formatMenu_Headingprop_H5: "CTRL+SHIFT+5",
        accel_formatMenu_Headingprop_H6: "CTRL+SHIFT+6",
        accel_formatMenu_Superscript: "Ctrl+.",
        accel_formatMenu_Superscript_Mac: "\u2318.",
        accel_formatMenu_Subscript: "Ctrl+,",
        accel_formatMenu_Subscript_Mac: "\u2318,",
        accel_formatMenu_Left: "CTRL+SHIFT+L",
        accel_formatMenu_Left_Mac: "\u21e7\u2318L",
        accel_formatMenu_Right: "CTRL+SHIFT+R",
        accel_formatMenu_Right_Mac: "\u21e7\u2318R",
        accel_formatMenu_Center: "CTRL+SHIFT+E",
        accel_formatMenu_Center_Mac: "\u21e7\u2318E",
        accel_formatMenu_Justify: "CTRL+SHIFT+J",
        accel_formatMenu_Justify_Mac: "\u21e7\u2318J",
        accel_formatMenu_Indent: "CTRL+M",
        accel_formatMenu_Indent_Mac: "\u2318M",
        accel_formatMenu_DecreaseIndent: "CTRL+SHIFT+M",
        accel_formatMenu_DecreaseIndent_Mac: "\u21e7\u2318M",
        accel_teamMenu_AddComment: "SHIFT+F2",

        ctxMenuSmartTable: 'טבלה',
        ctxMenuTableProperties: "תכונות טבלה",
        ctxMenuDeleteST: 'מחיקה',
        ctxMenuDeleteSTTable: 'מחיקת טבלה',
        ctxMenuChgSTStyle: 'שינוי סגנון',
        ctxMenuShowCaption: 'הצגת מיקרא',
        ctxMenuHideCaption: 'הסתרת מיקרא',
        ctxMenuResizeST: 'שינוי גודל',
        ctxMenuResizeColumnsST: 'שינוי גודל עמודות',
        ctxMenuSTRow: 'שורה',
        ctxMenuAddSTRowAbv: 'הוספת שורה מעל',
        ctxMenuAddSTRowBlw: 'הוספת שורה מתחת',
        ctxMenuMoveSTRowUp: 'העברת שורה מעל',
        ctxMenuMoveSTRowDown: 'העברת שורה מתחת',
        ctxMenuDelSTRow: 'מחיקה',
        ctxMenuRepeatRow: 'חזרה על שורת הכותרת',
        ctxMenuSTCol: 'עמודה',
        ctxMenuAddSTColBfr: 'הוספת עמודה לפני',
        ctxMenuAddSTColAft: 'הוספת עמודה אחרי',
        ctxMenuMoveSTColBefore: 'העברת עמודה לפני',
        ctxMenuMoveSTColAfter: 'העברת עמודה אחרי',
        ctxMenuDelSTCol: 'מחיקה',
        ctxMenuSortSTColAsc: 'מיון עולה',
        ctxMenuSortSTColDesc: 'מיון יורד',
        ctxMenuShowAllFacets: 'הצגת קטגוריות',
        ctxMenuHideAllFacets: 'הסתרת קטגוריות',
        ctxMenuSTCell: 'תא',
        ctxMenuMergeCells: 'מיזוג תאים',
        ctxMenuMergeDown: 'מיזוג עם התא שמתחת',
        ctxMenuVerSplit: 'פיצול אנכי',
        ctxMenuHorSplit: 'פיצול אופקי',
        ctxMenuSplitCells: 'פיצול תאים...‏',
        splitCells: 'פיצול תא',
        ctxMenuAlignTextLeft: 'יישור לשמאל',
        ctxMenuAlignTextCenter: 'יישור למרכז',
        ctxMenuAlignTextRight: 'יישור לימין',
        ctxMenuClearSTCellContent: 'ניקוי תוכן',
        ctxMenuMakeHeaderRow: 'שימוש בשורה שנבחרה ככותרת עליונה',
        ctxMenuMakeNonHeaderRow: 'סילוק סגנון כותרת עליונה',
        ctxMenuMakeHeaderCol: 'שימוש בעמודה שנבחרה ככותרת עליונה',
        ctxMenuMakeNonHeaderCol: 'סילוק סגנון כותרת עליונה',
        SHEET_CONTEXT_Hide: "הסתרה", // hide row, column or sheet
        SHEET_CONTEXT_Show: "הצגה", // show row, column
        SHEET_CONTEXT_MoveSheet: "העברה...", // move sheet
        SHEET_CONTEXT_InsertSheet: "הוספה...‏", // insert sheet
        SHEET_CONTEXT_DeleteSheet: "מחיקה...‏", // delete sheet	
        SHEET_CONTEXT_DuplicateSheet: "שכפול...‏", // duplicate sheet
        SHEET_CONTEXT_RenameSheet: "שינוי שם...‏", // rename sheet
	
        ctxMenu_Image_WrapText: "גלישת תמליל",
        ctxMenu_Image_WrapText_Inline: "בשורה עם התמליל",
        ctxMenu_Image_WrapText_Square: "ריבוע",
        ctxMenu_Image_WrapText_TopBottom: "ראש ותחתית",
        ctxMenu_Image_WrapText_Behind: "מאחורי התמליל",
        ctxMenu_Image_WrapText_InFront: "לפני התמליל",
        ctxMenu_Image_WrapText_Other: "עוד גלישה תמליל",
        ctxMenu_Image_WrapText_BothSides: "שני הצדדים",
        ctxMenu_Image_WrapText_LeftOnly: "שמאל בלבד",
        ctxMenu_Image_WrapText_RightOnly: "ימין בלבד",
        ctxMenu_Image_WrapText_LargestOnly: "הגדול ביותר בלבד",

        ctxMenu_Shape_AddText: "הוספת תמליל",

        ctxMenu_Range_ACL: "הגנה על טווח",
        ctxMenu_Sheet_ACL: "הגנה על גליון",

        ctxMenu_HeaderFooter: "כותרת עליונה / תחתונה",
        ctxMenu_HeaderFooter_DiffFirst: "עמוד ראשון בלבד",
        ctxMenu_HeaderFooter_DiffOddEven: "עמודים זוגיים ואי-זוגיים שונים",
        ctxMenu_HeaderFooter_LinkToPre: "קישור לקודם",

        ctxMenu_copy: "העתקה",
        ctxMenu_paste: "הדבקה",
        ctxMenu_delete: "מחיקה",
        ctxMenu_cut: "גזירה",
        ctxMenu_select: "בחירה",
        ctxMenu_properties: "תכונות",
        ctxMenu_bringToFront: "הבאה לחזית",
        ctxMenu_sendToBack: "העברה אחורה",
        ctxMenu_arrange: "סידור",
        ctxMenu_sendBackward: "העברה לרקע",
        ctxMenu_sendForward: "משלוח קדימה",
        ctxMenu_fontStyle: "סגנון גופן",
        ctxMenu_selectStyle: "בחירת סגנון",
        ctxMenu_fontSize: "גודל גופן",
        ctxMenu_fontFamily: "משפחת גופנים",
        ctxMenu_bold: "מודגש",
        ctxMenu_italic: "נטוי",
        ctxMenu_u: "קו תחתי",
        ctxMenu_strike: "קו חוצה",
        ctxMenu_super: "כתב עילי",
        ctxMenu_sub: "כתב תחתי",
        ctxMenu_color: "צבע",
        ctxMenu_bgcolor: "צבע רקע",
        ctxMenu_highcolor: "צבע הבלטה",
        ctxMenu_restart: "התחלת רשימה מחדש",
        ctxMenu_continue: "המשך רשימה",
        ctxMenu_separate: "רשימה נפרדת",
        ctxMenu_join: "צירוף לרשימה הקודמת",
        ctxMenu_setNumberVal: "הגדרת ערך מספור...‏",
        webClipboardInfoTitle: "לוח גזירים",
        webClipboardInfoOKBtn: "אישור",
        webClipboardInfoCutMsg: "הגדרות האבטחה של הדפדפן שלכם מונעות העתקה אוטומטית. השתמשו בשילוב המקשים Ctrl+X במקלדת במקום זאת.",
        webClipboardInfoCopyMsg: "הגדרות האבטחה של הדפדפן שלכם מונעות העתקה אוטומטית. השתמשו בשילוב המקשים Ctrl+C במקלדת במקום זאת.",
        webClipboardInfoPasteMsg: "הגדרות האבטחה של הדפדפן שלכם מונעות מהעורך לגשת לנתונים בלוח הגזירים. השתמשו בשילוב המקשים Ctrl+V במקלדת במקום זאת.",

        clearTrackChangeConfirmMsg: "כל קודי הצבע המסמנים שינויים במסמך זה יסולקו לצמיתות. האם ברצונכם להמשיך?‏"
});

