/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
	fileMenu: "קובץ",
	fileMenu_New: "חדש",
	fileMenu_NewDocument: "מסמך",
	fileMenu_NewDocumentfromTemplate: "מסמך מתבנית",
	fileMenu_NewPresentation: "מצגת",
	fileMenu_NewPresentationfromTemplate: "מצגת מתבנית",
	fileMenu_NewSpreadsheet: "גליון אלקטרוני",
	fileMenu_Open: "פתוח",
//	fileMenu_Close: "Close",
	fileMenu_Discard: "זניחה",
	fileMenu_Save: "שמירה",
//	fileMenu_SaveAs: "Save As...",
//	fileMenu_SaveAsDraft: "as Draft",
//	fileMenu_SaveInMyDocs: "in My Documents",
//	fileMenu_SaveToSymphony: "to Lotus Symphany",
	fileMenu_ShareWith: "שיתוף עם...	",
	fileMenu_ExportAsPDF: "יצוא כ-PDF",
	fileMenu_WebPreview: "תצוגה מקדימה ברשת",
	fileMenu_PrintPreview: "הצגה לפני הדפסה",
	fileMenu_RecentFile: "קבצים אחרונים",
	fileMenu_Print: "הדפסה...‏",
	editMenu: "עריכה",
	editMenu_Undo: "ביטול פעולה",
	editMenu_Redo: "שחזור פעולה",
	editMenu_Cut: "גזירה",
	editMenu_Copy: "העתקה",
	editMenu_Paste: "הדבקה",
	editMenu_DeleteSlide:"מחיקת שקופית",
	editMenu_SelectAll: "בחירת הכל",
	editMenu_Find: "חיפוש...",
	editMenu_Replace: "החלפה...",
	editMenu_DeleteSheet: "מחיקת גליון",
	editMenu_DuplicateSheet: "שכפול גליון",
	editMenu_DeleteRow: "מחיקת שורה",
	editMenu_DeleteColumn: "מחיקת עמודה",
	editMenu_ClearCell: "ניקוי תא",
	viewMenu: "תצוגה",
	viewMenu_Master: "תבנית",
	viewMenu_Notifications: "דיווחים",
	viewMenu_ShowHideIndicators: "הצגה/הסתרה של מחווני עריכה משותפת",
	viewMenu_SlideSorter: "הצגת בורר השקופיות",
	viewMenu_SpeakerNotes: "הצגת הערות הדובר",
	viewMenu_NextSlide: "השקופית הבאה",
	viewMenu_PrevSlide: "השקופית הקודמת",
	createMenu: "יצירה",
	createMenu_NewSlide: "שקופית חדשה",
	createMenu_DuplicateSlide: "שכפול שקופית",
	createMenu_ImageFromFile: "גרפיקה מקובץ",
	createMenu_TextBox: "תיבת תמליל",
	createMenu_Task: "משימה",
    formatMenu_Text_Direction: "כיוון תמליל",
    formatMenu_Ltr: "משמאל לימין",
    formatMenu_Rtl: "מימין לשמאל",  	
    formatMenu_Horizontal_Align: "יישור אופקי",
    formatMenu_Vertical_Align: "יישור אנכי",
    formatMenu_Align_Top: "ראש",
    formatMenu_Align_Middle: "אמצע",
    formatMenu_Align_Bottom: "תחתית",
	layoutMenu: "מתכונת",
	layoutMenu_SlideLayout: "מתכונות שקופית",
	layoutMenu_SlideDesign: "סגנונות אב",
	tableMenu: "טבלה",
	tableMenu_CreateTable: "יצירת טבלה",
	tableMenu_Cell: "תא",
	tableMenu_CellAlignLeft: "יישור תמליל לשמאל",
	tableMenu_CellAlignCenter: "יישור תמליל למרכז",
	tableMenu_CellAlignRight: "יישור תמליל לימין",
	tableMenu_CellClearContents: "ניקוי תוכן",
	tableMenu_Row: "שורה",
	tableMenu_RowAddRowAbove: "הוספת שורה למעלה",
	tableMenu_RowAddRowBelow: "הוספת שורה מתחת",
	tableMenu_RowMoveRowAbove: "העברת שורה מעל",
	tableMenu_RowMoveRowBelow: "העברת שורה מתחת",
	tableMenu_RowDelete: "מחיקה",
	tableMenu_ColumnAddColumnBefore: "הוספת עמודה לפני",
	tableMenu_ColumnAddColumnAfter: "הוספת שורה אחרי",
	tableMenu_ColumnMoveColumnAfter: "העברת עמודה אחרי",
	tableMenu_ColumnMoveColumnBefore: "העברת עמודה לפני",
	tableMenu_ColumnDelete: "מחיקה",
	tableMenu_ColumnSortAscending: "מיון עולה",
	tableMenu_ColumnSortDescending: "מיון יורד",
	tableMenu_Column: "עמודה",
	tableMenu_Delete: "מחיקה",
	presentationMenu: "מצגת",
	presentationMenu_SlideShow: "הרצת מצגת שקופיות",
	presentationMenu_SlideShowFromCurrent: "הרצה מהשקופית הנוכחית",
	toolsMenu: "כלים",
	toolsMenu_Task: "משימה",
	helpMenu: "עזרה",
	helpMenu_Overview: "תוכן עזרה"
})

