/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
	fileMenu: "Datoteka",
	fileMenu_New: "Novo",
	fileMenu_NewDocument: "Dokument",
	fileMenu_NewFromTemplate: "Iz uzorka",
	fileMenu_NewDocumentfromTemplate: "Dokument iz uzorka",
	fileMenu_NewPresentation: "Prezentacija",
	fileMenu_NewPresentationfromTemplate: "Prezentacija iz uzorka",
	fileMenu_NewSpreadsheet: "Proračunska tabela",
	fileMenu_NewSpreadsheetFromTemplate: "Proračunska tabela iz uzorka",
	fileMenu_Open: "Otvori",
	fileMenu_Import: "Import...",
//	fileMenu_Close: "Close",
	fileMenu_Discard: "Vrati na zadnju verziju",
	fileMenu_ClearTrackChange: "Ukloni oznake promjene",
	fileMenu_SpreadsheetSettings: "Postavljanje lokalizacije dokumenta...",
	filemenu_revisionhistory: "Revizije",
	fileMenu_Save: "Spremi",
	fileMenu_SaveAs: "Kopiraj...",
	fileMenu_AutoPublish: "Automatski objavi",
//	fileMenu_AutoPublish_Tips: "Makes your changes available to readers at the end of each editing session.",
	fileMenu_PublishVersion: "Objavi sada",
	fileMenu_SubmitForReview: "Predaj na pregled...",
	fileMenu_CheckinVersion: "Prijavi...",
	fileMenu_Unlock: "Otključaj",
//	fileMenu_SaveAsDraft: "as Draft",
//	fileMenu_SaveInMyDocs: "in My Documents",
//	fileMenu_SaveToSymphony: "to Lotus Symphany",
	fileMenu_DownloadAs: "Preuzmi kao",
	fileMenu_PDF: "PDF",
	fileMenu_ODF: "ODF",
	fileMenu_DOC: "Microsoft Word 97- 2007 (*.doc)",
	fileMenu_ODS: "ODS",
	fileMenu_XLS: "Microsoft Excel 97-2007 (*.xls) ",
	fileMenu_ShareWith: "Dijeljenje...	",
	fileMenu_ExportAsPDF: "PDF",
	fileMenu_ExportAsODF: "ODF",
	fileMenu_ExportAsPPT: "Microsoft Powerpoint 97- 2007 (*.ppt)",
//	fileMenu_WebPreview: "Web Preview",
	fileMenu_PrintToPDF: "Printanje kao PDF...",
	fileMenu_ViewFileDetails: "Gledanje detalja datoteke...",
	fileMenu_RecentFile: "Nedavne datoteke",
	fileMenu_Open: "Otvori",
	fileMenu_Download: "Preuzmi",
	fileMenu_Print: "Ispiši",
	fileMenu_Export: "Eksport",
	fileMenu_ExportToCSV: "CSV",
	fileMenu_ExportToPDF: "PDF (.pdf)",
	fileMenu_ExportToMS: "Microsoft Office format (.${FILEEXTENSION})",
	fileMenu_ExportToODF: "Open Document format (.${FILEEXTENSION})",
	fileMenu_PgSetup: "Podešavanje stranice...",
	
	editMenu: "Uredi",
	editMenu_Undo: "Poništi",
	editMenu_Redo: "Ponovo napravi",
	editMenu_Cut: "Izreži",
	editMenu_Copy: "Kopiraj",
	editMenu_Paste: "Zalijepi",
	editMenu_DeleteSlide:"Izbriši slajd",
	editMenu_SelectAll: "Izaberi sve",
	editMenu_Find: "Nalaženje...",
	editMenu_Replace: "Zamjena...",
	editMenu_FindReplace: "Nalaženje i zamjena...",
	editMenu_EditLink: "Dodaj ili uredi link",
	editMenu_DeleteSheet: "Brisanje lista...",
	editMenu_RenameSheet: "Preimenovanje lista...",
	editMenu_HideSheet: "Sakrij list",
	editMenu_MoveSheet: "Prenošenje lista...",
	editMenu_DeleteRow: "Izbriši red",
	editMenu_DeleteColumn: "Izbriši kolonu",
	editMenu_ClearCell: "Izbriši sadržaj",
	
	viewMenu: "Pogled",
	viewMenu_Master: "Glavni",
	viewMenu_Notifications: "Obavještenja",
	viewMenu_SlideSorter: "Sortiranje slajdova",
	viewMenu_SpeakerNotes: "Napomene za govornika",
	viewMenu_Toolbar_Basic: "Osnovno",
	viewMenu_Toolbar_Advanced: "Napredno",
	viewMenu_Toolbar_None: "Ništa",
	viewMenu_Toolbar: "Traka s alatima",
	viewMenu_Statusbar:	"Statusna traka",
	viewMenu_Navigator: "Navigator...",
	//viewMenu_Sidebar: "Sidebar",
	viewMenu_ShowHideIndicators: "Pokaži indikatore zajedničkog uređivanja",	
	viewMenu_Assignment: "Indikatori zaduženja",
	viewMenu_Bookmark: "Bukmarci",
	viewMenu_Coediting: "Istaknuto u zajedničkom uređivanju",
	viewMenu_Rulers: "Linijari",
	viewMenu_WebLayout: "Izgled Weba",
	viewMenu_AutomaticSpellCheck: "Provjera pravopisa u toku pisanja",
	viewMenu_Formulabar: "Traka s formulama",
	viewMenu_moveRight: "Unos pomiče kursor u desno",
	viewMenu_showFullString: "Proširi sadržaj u ćelijama",
	viewMenu_Doc: "Pregled dokumenta",
	viewMenu_Templates: "Uzorci",
	viewMenu_GridLines: "Sakrij linije mreže",
	viewMenu_UnsupportWarning: "Pokaži poruke o nepodržanim mogućnostima",
	viewMenu_HiddenSheets:"Skriveni listovi",
	viewMenu_FreezeRows:"Zamrzni redove",
	viewMenu_FreezeColumns:"Zamrzni kolone",
	viewMenu_NoFrozenRows:"Bez zamrznutih redova",
	viewmenu_NoFrozenColumns:"Bez zamrznutih kolona",
	viewMenu_FreezeXRows:"Zamrzni ${0} redova",
	viewMenu_FreezeOneRow:"Zamrzni ${0} red",
	viewMenu_FreezeXColumns:"Zamrzni ${0} kolona",
	viewMenu_FreezeOneColumn:"Zamrzni ${0} kolonu",
	viewMenu_CarriageReturn:"Oznake formatiranja",
	
	viewMenu_ObserverMode: 'Način posmatranja',
	createMenu: "Ubaci",
	createMenu_NewSlide: "Novi slajd",
	createMenu_DuplicateSlide: "Duplikat slajda",
	createMenu_ImageFromFile: "Slika...",
	createMenu_TextBox: "Tekstualni okvir",
	createMenu_Shape: "Oblik",
	createMenu_break: "Prekid",
    createMenu_RowAbove: "Red iznad",
    createMenu_RowBelow: "Red ispod",
    createMenu_ColumnRight: "Kolona desno",
    createMenu_ColumnLeft: "Kolona lijevo",
    createMenu_Sheet: "List...",
    createMenu_Image: "Slika...",
    createMenu_Comments: "Komentar...",
    createMenu_WebLink: "Web link...",
    createMenu_SpecialCharacter: "Specijalni karakter...",
    createMenu_Function: "Funkcija...",
    createMenu_Fromtemplate: "Kreiraj iz uzorka",
    
    insertMenu: "Ubaci",
    insertMenu_break: "Prijelom stranice",
	insertMenu_sectionbreak: "Prijelom sekcije",
	insertMenu_Bookmark: "Bukmark...",
    insertMenu_WebLink: "Link...",
    insertMenu_SpecialCharacter: "Specijalni karakter...",
    insertMenu_HorizontalLine: "Horizontalna linija",
    insertMenu_Header: "Zaglavlje",
    insertMenu_Footer: "Podnožje",
 	insertMenu_TableOfContents: "Tabela sadržaja",
     
    insertMenu_HeaderFooter: "Zaglavlje/podnožje",
    insertMenu_HF_Edit: "Uredi",
    insertMenu_HF_Hide: "Sakrij",
    insertMenu_Endnotes: "Završne napomene",
    insertMenu_RowAbove: "Red iznad",
    insertMenu_PageNumber: "Broj stranice",
    insertMenu_PageNumberTop: "Vrh stranice",
    insertMenu_PageNumberBottom: "Dno stranice",
    insertMenu_PageNumberCurr: "Trenutni položaj",    
    insertMenu_TotalPageNumber: "Stranica 1 od N",
    insertMenu_Date: "Datum...",
    insertMenu_Time: "Vrijeme...",
    insertMenu_Fields: "Polja",
//    insertMenu_Comment: "Comment",
    insertMenu_RowBelow: "Red ispod",
    insertMenu_ColumnBefore: "Kolona ispred",
    insertMenu_ColumnAfter: "Kolona iza",
    insertMenu_Sheet: "List...",
    insertMenu_Image: "Slika...",
    insertMenu_DuplicateSheet: "Dupliciraj list",
    insertMenu_Function: "Funkcija",
    insertMenu_FunctionSum: "SUM",
    insertMenu_FunctionAverage: "AVERAGE",
    insertMenu_FunctionCount: "COUNT",
    insertMenu_FunctionMax: "MAX",
    insertMenu_FunctionMin: "MIN",
    insertMenu_FunctionMore: "Više funkcija...",    
    insertMenu_NameRange:"Imenovani raspon",  
    insertMenu_NameRangeNew:"Novi raspon...",
    insertMenu_NameRangeManage:"Uređivanje raspona...",
    insertMenu_Chart: "Grafikon...",
    
    contextMenu_InsertRowAbove: "Ubaci red iznad",
    contextMenu_InsertRowBelow: "Ubaci red ispod",
    contextMenu_InsertColumnBefore: "Ubaci kolonu  ispred",
    contextMenu_InsertColumnAfter: "Ubaci kolonu iza",
    contextMenu_DownloadImage: "Preuzmi kao sliku",
    
    formatMenu: "Format",
	formatMenu_DefaultFormatting: "Default formatiranje",    
    formatMenu_Template: "Stilovi...",
    contextMenu_Template: "Stilovi tabele...",
    formatMenu_LineSpacing: "Prored",
    formatMenu_LineSpacing1: "1",
    formatMenu_LineSpacing12: "1.2",
    formatMenu_LineSpacing15: "1.5",
    formatMenu_LineSpacing2: "2",
    formatMenu_LineSpacing25: "2.5",
    formatMenu_LineSpacing3: "3",
    formatMenu_TextProperties: "Osobine teksta",
    formatMenu_PageBreakBefore: "Prekid stranice ispred",
    formatMenu_KeepLines: "Zadrži linije zajedno",
    formatMenu_WidowControl: "Udovica/Siroče",
    formatMenu_Pagination: "Osobine paragrafa",
    formatMenu_Bold: "Podebljano",
    formatMenu_Italic: "Kurziv",
    formatMenu_Underline: "Podcrtano",
    formatMenu_Strikethrough: "Precrtano",
    formatMenu_IncreaseSize: "Povećaj veličinu fonta",
    formatMenu_DecreaseSize: "Smanji veličinu fonta",
    formatMenu_ImageProperties: "Osobine slike...",
    formatMenu_ChartProperties: "Osobine grafikona...",
    formatMenu_EditChart: "Uredi grafikon",
    formatMenu_InsertChart: "Ubaci grafikon",
    formatMenu_Properties: "Osobine...",
    formatMenu_Heading: "Naslov",
    formatMenu_Normal: "Normalno",
    formatMenu_Title : "Naslov",
    formatMenu_Subtitle: "Podnaslov",
    formatMenu_Heading1: "Naslov 1",
    formatMenu_Heading2: "Naslov 2",
    formatMenu_Heading3: "Naslov 3",
    formatMenu_Heading4: "Naslov 4",
    formatMenu_Heading5: "Naslov 5",
    formatMenu_Heading6: "Naslov 6",
    formatMenu_Heading7 : "Zaglavlje 7",
    formatMenu_Heading8 : "Zaglavlje 8",
    formatMenu_Heading9 : "Zaglavlje 9",
    formatMenu_BulletedList: "Lista s oznakama",
    formatMenu_NumberedList: "Lista s brojevima",
    formatMenu_OutLine:"Lista s više razina",
    formatMenu_Superscript: "Superskript",
    formatMenu_Subscript: "Indeks",
    formatMenu_Align: "Poravnaj",
    formatMenu_Left: "Lijevo",
    formatMenu_Right: "Desno",
    formatMenu_Center: "Centar",
    formatMenu_Justify: "Poravnaj",
    formatMenu_Text_Direction: "Smjer teksta",
    formatMenu_Ltr: "Slijeva nadesno",
    formatMenu_Rtl: "S desna na lijevo",
    formatMenu_LineSpacing:"Prored",
    formatMenu_LineSpacing1:"1.0",
    formatMenu_LineSpacing115:"1.15",
    formatMenu_LineSpacing15:"1.5",
    formatMenu_LineSpacing2:"2.0",
    formatMenu_LineSpacing25:"2.5",
    formatMenu_LineSpacing3:"3.0",
    formatMenu_Top: "Vrh",
    formatMenu_Bottom: "Dno",
    formatMenu_Middle: "Sredina",
    formatMenu_Direction: "Smjer teksta",
    formatMenu_Rtl: "S desna na lijevo",
    formatMenu_Ltr: "Slijeva nadesno",
    formatMenu_Auto: "Kontekstualno",
    formatMenu_SheetDirection: "Smjer radnog lista",
    formatMenu_SheetRtl: "S desna na lijevo",
    formatMenu_SheetLtr: "Slijeva nadesno",
    formatMenu_Indent: "Povećaj uvlačenje",
    formatMenu_DecreaseIndent: "Smanji uvlačenje",
    formatMenu_ClearFormat:"Očisti formatiranje",
    formatMenu_RowHeight: "Visina reda",
    formatMenu_ColumnWidth: "Širina kolone",
    formatMenu_ShowRow: "Pokaži red",
    formatMenu_HideRow: "Sakrij red",
    formatMenu_ShowColumn: "Pokaži kolonu",
    formatMenu_HideColumn: "Sakrij kolonu",
    formatMenu_WrapText: "Prelomi tekst",
    formatMenu_Number: "Broj",
    formatMenu_FontArial: "Arial",
    formatMenu_FontComicSansMS: "Comic Sans MS",
    formatMenu_FontCourierNew: "Courier New",
    formatMenu_FontGeorgia: "Georgia",
    formatMenu_FontLucidaSansUnicode: "Lucida Sans Unicode",
    formatMenu_FontTahoma: "Tahoma",
    formatMenu_FontTimesNewRoman: "Times New Roman",
    formatMenu_FontTrebuchetMS: "Trebuchet MS",
    formatMenu_FontVerdana: "Verdana",
    formatMenu_FontName: "Font",
    
	layoutMenu: "Izgled",
	layoutMenu_SlideLayout: "Izgled slajda...",
	layoutMenu_SlideDesign: "Glavni slajd...",
	layoutMenu_DefaultFormatting: "Default formatiranje",
	layoutMenu_Textprop_Bold: "Podebljano",
	layoutMenu_Textprop_Italic: "Kurziv",
	layoutMenu_Textprop_Underline: "Podcrtano",
	layoutMenu_Textprop_Strikethrough: "Precrtano",
	layoutMenu_TextProp: "Osobine teksta",
    LayoutMenu_RowHeight: "Visina reda...",
    LayoutMenu_ColumnWidth: "Širina kolone...",
    LayoutMenu_ShowRow: "Pokaži red",
    LayoutMenu_HideRow: "Sakrij red",
    LayoutMenu_RenameSheet: "Preimenovanje lista...",
    LayoutMenu_MoveSheet: "Premjesti list",
    
	tableMenu: "Tabela",
	tableMenu_Create: "Kreiranje...",
	tableMenu_CreateFromTemplate: "Kreiraj iz uzorka",
	tableMenu_Delete: "Izbriši",
	tableMenu_SetTableColor:"Boja ćelije",
	tableMenu_CreateTable: "Kreiraj tabelu",
	tableMenu_Cell: "Ćelija",
	tableMenu_CellMergeCells: "Spoji ćelije",
	tableMenu_CellAlignLeft: "Poravnaj lijevo",
	tableMenu_CellAlignCenter: "Poravnaj centralno",
	tableMenu_CellAlignRight: "Poravnaj desno",
	tableMenu_CellClearContents: "Očisti sadržaj",
	tableMenu_CellProperties: "Osobine ćelije...",
	tableMenu_Row: "Red",
	tableMenu_InsertRowAbove: "Ubaci red iznad",
	tableMenu_InsertRowBelow: "Ubaci red ispod",
	tableMenu_MoveRowAbove: "Premjesti red gore",
	tableMenu_MoveRowBelow: "Premjesti red dolje",
	tableMenu_RowInsertRow: "Umetanje reda...",
	tableMenu_RowInsertRowAbove: "Ubaci red iznad",
	tableMenu_RowInsertRowBelow: "Ubaci red ispod",
	tableMenu_RowMoveRowAbove: "Premjesti red iznad",
	tableMenu_RowMoveRowBelow: "Premjesti red ispod",
	tableMenu_RowDelete: "Izbriši",
	tableMenu_RowRepeat: "Ponovi red zaglavlja",
	tableMenu_InsertColumnBefore: "Ubaci kolonu  ispred",
	tableMenu_InsertColumnAfter: "Ubaci kolonu iza",
	tableMenu_MoveColumnBefore: "Premjesti kolonu lijevo",
	tableMenu_MoveColumnAfter: "Premjesti kolonu desno",
	tableMenu_ResizeColumn: "Promijeni veličinu kolone",
	tableMenu_ResizeColumns: "Promijeni veličinu kolona",
	tableMenu_MarkasCategory: "Označi kao kategoriju",
	tableMenu_ColumnInsertColumn: "Umetanje kolone...",
	tableMenu_ColumnAddColumnBefore: "Ubaci kolonu  ispred",
	tableMenu_ColumnAddColumnAfter: "Ubaci kolonu iza",
	tableMenu_ColumnMoveColumnAfter: "Premjesti kolonu iza",
	tableMenu_ColumnMoveColumnBefore: "Premjesti kolonu ispred",
	tableMenu_ColumnDelete: "Izbriši",
	tableMenu_ColumnSortAscending: "Sortiraj uzlazno",
	tableMenu_ColumnSortDescending: "Sortiraj silazno",
	tableMenu_Column: "Kolona",
	tableMenu_Style: "Stil",
	tableMenu_TableProperties: "Osobine tabele...",
	
	teamMenu: "Tim",
	teamMenu_AddComment: "Dodaj komentar",
	teamMenu_AssignCells: "Dodijeli ćelije",
	teamMenu_AssignSection: "Dodijeli sekciju",
	teamMenu_EditAssignment: "Uređenje zaduženja",
	teamMenu_MarkSectionComplete: "Označi sekciju dovršenim",
	teamMenu_MarkAssignmentComplete: "Označi zaduženje dovršenom",
	teamMenu_WorkPrivatelyOnSection: "Rad privatno na odjeljku",
	teamMenu_CancelPrivateWork: "Otkaži privatan rad",
	teamMenu_ApproveSection: "Odobri sekciju",
	teamMenu_ApproveAssignment: "Odobri zaduženje",
	teamMenu_ReturnSectionForRework: "Vrati sekciju na preradu",
	teamMenu_ReturnAssignmentForRework: "Vrati zaduženje na preradu",
	teamMenu_RemoveSectionAssignment: "Ukloni zaduženje sekcije",
	teamMenu_RemoveCellAssignment: "Ukloni zaduženje ćelije",
	teamMenu_RemoveCompletedAssignments: "Ukloni dovršena zaduženja",
	teamMenu_AboutThisSection: "O ovom odjeljku",
	teamMenu_AboutAssignment: "O ovoj dodjeli",
	
	presentationMenu: "Prezentacija",
	presentationMenu_SlideShow: "Pokreni prikazivanje slajdova",
	presentationMenu_SlideShowWithCoview: "Pokreni prikazivanje dijeljenih slajdova",
	presentationMenu_SlideTransitions: "Primjeni prelaz između slajdova...",
	presentationMenu_SlideShowFromCurrent: "Prikaži od trenutnog slajda",
	presentationMenu_EmptyCoviewInvites: "Nema aktivnog dijeljenog prikazivanja slajdova",
	presentationMenu_CoviewInvites: "Aktivno dijeljeno prikazivanje slajdova",
	
	dataMenu: "Podaci",
	dataMenu_Sort: "Sort...",
	dataMenu_SortAsc: "Sortiraj uzlazno",
	dataMenu_SortDesc: "Sortiraj silazno",	
	dataMenu_ACL: "Dozvola",
	dataMenu_ACL_DELETE: "Obriši sve dozvole",
	dataMenu_Validity: "Vaslidnost",
	dataMenu_InstantFilter: "Instant filter",
	dataMenu_Validation: "Validacija...",
	
	toolsMenu: "Alati",
	toolsMenu_AutoComplete: "Automatsko dovršavanje unosa u ćelije",
	toolsMenu_SelectDictionary: "Rječnici provjere pravopisa",
	toolsMenu_Dictionary_ca_CT: "Katalonski",
	toolsMenu_Dictionary_cs_CZ: "Češki (Češka)",
	toolsMenu_Dictionary_da_DK: "Danski (Danska)",
	toolsMenu_Dictionary_nl_NL: "Holandski (Holandija)",
	toolsMenu_Dictionary_en_AU: "Engleski (Australija)",
	toolsMenu_Dictionary_en_GB: "Engleski (Velika Britanija)",
	toolsMenu_Dictionary_en_US: "Engleski (Sjedinjene Države)",
	toolsMenu_Dictionary_fi_FI: "Finski (Finska)",
	toolsMenu_Dictionary_fr_FR: "Francuski (Francuska)",
	toolsMenu_Dictionary_fr_CA: "Francuski (Kanada)",
	toolsMenu_Dictionary_de_DE: "Njemački (Njemačka)",
	toolsMenu_Dictionary_de_CH: "Njemački (Švajcarska)",
	toolsMenu_Dictionary_el_GR: "Grčki (Grčka)",
	toolsMenu_Dictionary_it_IT: "Talijanski (Italija)",
	toolsMenu_Dictionary_pl_PL: "Poljski (Poljska)",
	toolsMenu_Dictionary_pt_BR: "Portugalski (Brazil)",
	toolsMenu_Dictionary_pt_PT: "Portugalski (Portugal)",
	toolsMenu_Dictionary_ru_RU: "Ruski (Rusija)",
	toolsMenu_Dictionary_es_ES: "Španski (Španija)",
	toolsMenu_Dictionary_sv_SE: "Švedski (Švedska)",
	toolsMenu_Dictionary_nb_NO: "Norveški (Bukmol)",
	toolsMenu_Dictionary_nn_NO: "Norveški (Novonorveški)",	
	toolsMenu_Dictionary_he_IL: "Hebrejski (Izrael)",	
	toolsMenu_SpellCheck: "Izvođenje manuelne provjere pravopisa...",
	toolsMenu_Preferences: "Preference",
	toolsMenu_Task: "Zadatak",
	toolsMenu_Task_Assigntask: "Zaduženje zadatka",
	teamMenu_AssignSlide: "Zaduženje slajda",
	teamMenu_AssignSlides: "Zaduženje slajdova",
	teamMenu_EditSlide: "Uređivanje zaduženja slajda",
	teamMenu_ReopenSlideAssignment: "Ponovo otvaranje zaduženja slajda",	
	teamMenu_ReopenSlideAssignments: "Ponovo otvaranje zaduženja slajdova",	
	teamMenu_ReassignSlide: "Ponova dodjela slajda",
	teamMenu_ReassignSlides: "Ponova dodjela slajdova",	
	teamMenu_MarkSlidesComplete: "Označavanje slajda dovršenim",
	teamMenu_MarkSlidesCompletes: "Označavanje slajdova dovršenim",
	teamMenu_ApproveSlide: "Odobravanje slajda",
	teamMenu_ApproveSlides: "Odobravanje slajdova",
	teamMenu_ReturnForRework: "Vraćanje slajda na preradu",
	teamMenu_ReturnForReworks: "Vraćanje slajdova na preradu",
	teamMenu_RemoveAssignment: "Uklanjanje zaduženja slajda",
	teamMenu_AboutThisSlide: "O ovom slajdu",
	
	helpMenu: "Pomoć",
	helpMenu_About: "O proizvodu",
	helpMenu_Overview: "Sadržaji pomoći",
	helpMenu_NewFeatures: "Šta je novo",
	helpMenu_Tour: "Vođeno razgledavanje",
	
	accel_fileMenu_Save: "Ctrl+S",
	accel_fileMenu_Save_Mac:"\u2318S",
	accel_fileMenu_Print: "Ctrl+P",	
	accel_fileMenu_Print_Mac: "\u2318P",
	accel_editMenu_SelectAll: "Ctrl+A",
	accel_editMenu_SelectAll_Mac:"\u2318A",
	accel_editMenu_Undo: "Ctrl+Z",
	accel_editMenu_Undo_Mac: "\u2318Z",
	accel_editMenu_Redo: "Ctrl+Y",
	accel_editMenu_Redo_Mac: "\u2318Y",
	accel_editMenu_Cut: "Ctrl+X",
	accel_editMenu_Cut_Mac: "\u2318X",
	accel_editMenu_Copy: "Ctrl+C",
	accel_editMenu_Copy_Mac: "\u2318C",
	accel_editMenu_Paste: "Ctrl+V",
	accel_editMenu_Paste_Mac: "\u2318V",
	accel_editMenu_Find: "Ctrl+F",
	accel_editMenu_Find_Mac: "\u2318F",
	accel_insertMenu_Link: "Ctrl+K",
	accel_insertMenu_Link_Mac: "\u2318K",
	accel_insertMenu_Header: "CTRL+SHIFT+H",
	accel_insertMenu_Header_Mac: "\u21e7\u2318H",
	accel_insertMenu_Footer: "CTRL+SHIFT+F",
	accel_insertMenu_Footer_Mac: "\u21e7\u2318F",
	accel_formatMenu_Textprop_Bold: "Ctrl+B",
	accel_formatMenu_Textprop_Bold_Mac: "\u2318B",
	accel_formatMenu_Textprop_Italic: "Ctrl+I",
	accel_formatMenu_Textprop_Italic_Mac: "\u2318I",
	accel_formatMenu_Textprop_FormatPainter:"Ctrl+SHIFT+C, Ctrl+SHIFT+V",
	accel_formatMenu_Textprop_FormatPainter_Mac: "\u21e7\u2318C, \u21e7\u2318V",
	accel_formatMenu_Textprop_Underline: "Ctrl+U",
	accel_formatMenu_Textprop_Underline_Mac: "\u2318U",
	accel_formatMenu_Headingprop_P:  "CTRL+SHIFT+0",
	accel_formatMenu_Headingprop_H1: "CTRL+SHIFT+1",
	accel_formatMenu_Headingprop_H2: "CTRL+SHIFT+2",
	accel_formatMenu_Headingprop_H3: "CTRL+SHIFT+3",
	accel_formatMenu_Headingprop_H4: "CTRL+SHIFT+4",
	accel_formatMenu_Headingprop_H5: "CTRL+SHIFT+5",
	accel_formatMenu_Headingprop_H6: "CTRL+SHIFT+6",
	accel_formatMenu_Superscript: "Ctrl+.",
	accel_formatMenu_Superscript_Mac: "\u2318.",
	accel_formatMenu_Subscript: "Ctrl+,",
	accel_formatMenu_Subscript_Mac: "\u2318,",
	accel_formatMenu_Left: "CTRL+SHIFT+L",
	accel_formatMenu_Left_Mac: "\u21e7\u2318L",
	accel_formatMenu_Right: "CTRL+SHIFT+R",
	accel_formatMenu_Right_Mac: "\u21e7\u2318R",
	accel_formatMenu_Center: "CTRL+SHIFT+E",
	accel_formatMenu_Center_Mac: "\u21e7\u2318E",
	accel_formatMenu_Justify: "CTRL+SHIFT+J",
	accel_formatMenu_Justify_Mac: "\u21e7\u2318J",
	accel_formatMenu_Indent: "CTRL+M",
	accel_formatMenu_Indent_Mac: "\u2318M",
	accel_formatMenu_DecreaseIndent: "CTRL+SHIFT+M",
	accel_formatMenu_DecreaseIndent_Mac: "\u21e7\u2318M",
	accel_teamMenu_AddComment: "SHIFT+F2",
	
	ctxMenuSmartTable: 'Tabela',
	ctxMenuTableProperties: "Osobine tabele",
	ctxMenuDeleteST: 'Izbriši',
	ctxMenuDeleteSTTable: 'Izbriši tabelu',
	ctxMenuChgSTStyle: 'Promijeni stil',
	ctxMenuShowCaption: 'Pokaži naslov',
	ctxMenuHideCaption: 'Sakrij naslov',
	ctxMenuResizeST: 'Promijeni veličinu',
	ctxMenuResizeColumnsST: 'Promijeni veličinu kolona',
	ctxMenuSTRow: 'Red',
	ctxMenuAddSTRowAbv: 'Ubaci red iznad',
	ctxMenuAddSTRowBlw: 'Ubaci red ispod',
	ctxMenuMoveSTRowUp: 'Premjesti red iznad',
	ctxMenuMoveSTRowDown: 'Premjesti red ispod',
	ctxMenuDelSTRow: 'Izbriši',
	ctxMenuRepeatRow: 'Ponovi red zaglavlja',
	ctxMenuSTCol: 'Kolona',
	ctxMenuAddSTColBfr: 'Ubaci kolonu  ispred',
	ctxMenuAddSTColAft: 'Ubaci kolonu iza',  
	ctxMenuMoveSTColBefore: 'Premjesti kolonu ispred',
	ctxMenuMoveSTColAfter: 'Premjesti kolonu iza',
	ctxMenuDelSTCol: 'Izbriši',
	ctxMenuSortSTColAsc: 'Sortiraj uzlazno',
	ctxMenuSortSTColDesc: 'Sortiraj silazno',
	ctxMenuShowAllFacets: 'Pokaži kategorije',
	ctxMenuHideAllFacets: 'Sakrij kategorije',
	ctxMenuSTCell: 'Ćelija',
	ctxMenuMergeCells: 'Spoji ćelije',
	ctxMenuMergeDown: 'Spoji s ćelijom ispod',
	ctxMenuVerSplit: 'Razdijeli vertikalno',
	ctxMenuHorSplit: 'Razdijeli horizontalno',
	ctxMenuSplitCells: 'Podijeli ćelije...',
	splitCells: 'Podijeli ćeliju',
	ctxMenuAlignTextLeft: 'Poravnaj lijevo',
	ctxMenuAlignTextCenter: 'Poravnaj centralno',
	ctxMenuAlignTextRight: 'Poravnaj desno',
	ctxMenuClearSTCellContent: 'Očisti sadržaj',
	ctxMenuMakeHeaderRow: 'Koristi izabrani red kao naslov',
	ctxMenuMakeNonHeaderRow: 'Ukloni stil naslova',
	ctxMenuMakeHeaderCol: 'Koristi izabranu kolonu kao naslov',
	ctxMenuMakeNonHeaderCol: 'Ukloni stil naslova',
	SHEET_CONTEXT_Hide: "Sakrij", // hide row, column or sheet
	SHEET_CONTEXT_Show: "Pokazivanje", // show row, column
	SHEET_CONTEXT_MoveSheet: "Premjesti...", // move sheet
	SHEET_CONTEXT_InsertSheet: "Ubaci...", // insert sheet
	SHEET_CONTEXT_DeleteSheet: "Izbriši...", // delete sheet	
	SHEET_CONTEXT_DuplicateSheet: "Dupliciraj...", // duplicate sheet
	SHEET_CONTEXT_RenameSheet: "Preimenuj...", // rename sheet
	
	ctxMenu_Image_WrapText:	"Prelomi tekst",
	ctxMenu_Image_WrapText_Inline: "U liniji s tekstom",
	ctxMenu_Image_WrapText_Square: "Kvadrat",
	ctxMenu_Image_WrapText_TopBottom: "Vrh i dno",
	ctxMenu_Image_WrapText_Behind: "Iza teksta",
	ctxMenu_Image_WrapText_InFront: "Ispred teksta",
	ctxMenu_Image_WrapText_Other: "Više preloma teksta",
	ctxMenu_Image_WrapText_BothSides: "Obostrano",
	ctxMenu_Image_WrapText_LeftOnly: "Samo lijevo",
	ctxMenu_Image_WrapText_RightOnly: "Samo desno",
	ctxMenu_Image_WrapText_LargestOnly: "Samo najveće",

	ctxMenu_Shape_AddText: "Dodaj tekst",
	
	ctxMenu_HeaderFooter: "Zaglavlje / podnožje",
	ctxMenu_HeaderFooter_DiffFirst: "Samo prva strana",
	ctxMenu_HeaderFooter_DiffOddEven: "Različite parne i neparne stranice",
	ctxMenu_HeaderFooter_LinkToPre: "Poveži s prethodnom",
	
	ctxMenu_copy: 		"Kopiraj",
	ctxMenu_paste: 		"Zalijepi",
	ctxMenu_delete: 	"Izbriši",
	ctxMenu_cut:		"Izreži",
	ctxMenu_properties:	"Osobine",
	ctxMenu_bringToFront: "Postavi ispred",
	ctxMenu_sendToBack: "Pošalji iza",
	ctxMenu_arrange: "Razmjesti",
	ctxMenu_sendBackward: "Pošalji nazad",
	ctxMenu_sendForward: "Pošalji naprijed",
	ctxMenu_fontStyle:	"Stil fonta",
	ctxMenu_selectStyle:	"Izaberi stil",
	ctxMenu_fontSize:	"Veličina fonta",
	ctxMenu_fontFamily:	"Porodica fonta",
	ctxMenu_bold:		"Podebljano",
	ctxMenu_italic:		"Kurziv",
	ctxMenu_u:			"Podcrtano",
	ctxMenu_strike:		"Precrtano",
	ctxMenu_super:		"Superskript",
	ctxMenu_sub:		"Indeks",
	ctxMenu_color:		"Boja",
	ctxMenu_bgcolor:	"Boja pozadine",
	ctxMenu_highcolor:	"Boja za isticanje",
	ctxMenu_restart:	"Ponovo pokreni listu",
	ctxMenu_continue:	"Nastavi listu",
	ctxMenu_separate:	"Odvoji listu",
	ctxMenu_join:		"Pridruži prethodnoj listi",
	ctxMenu_setNumberVal:"Postavi vrijednost numerisanja...",
	webClipboardInfoTitle: "Memorija za isječke",
	webClipboardInfoOKBtn: "OK",
	webClipboardInfoCutMsg: "Sigurnosne postavke vašeg pretraživača sprečavaju automatsko kopiranje. Umjesto toga koristite Ctrl+X na tastaturi.",
	webClipboardInfoCopyMsg: "Sigurnosne postavke vašeg pretraživača sprečavaju automatsko kopiranje. Umjesto toga koristite Ctrl+C na tastaturi.",
	webClipboardInfoPasteMsg: "Sigurnosne postavke vašeg pretraživača sprečavaju editor u pristupu do podataka u memoriji za isječke. Umjesto toga koristite Ctrl+V na tastaturi.",
	
	clearTrackChangeConfirmMsg: "Sve boje koje označavaju promjene u dokumentu, bit će trajno uklonjene. Da li želite nastaviti?"
})



