/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
	fileMenu: "Datoteka",
	fileMenu_New: "Novo",
	fileMenu_NewDocument: "Dokument",
	fileMenu_NewDocumentfromTemplate: "Dokument iz uzorka",
	fileMenu_NewPresentation: "Prezentacija",
	fileMenu_NewPresentationfromTemplate: "Prezentacija iz uzorka",
	fileMenu_NewSpreadsheet: "Proračunska tabela",
	fileMenu_Open: "Otvori",
//	fileMenu_Close: "Close",
	fileMenu_Discard: "Odbaci",
	fileMenu_Save: "Spremi",
//	fileMenu_SaveAs: "Save As...",
//	fileMenu_SaveAsDraft: "as Draft",
//	fileMenu_SaveInMyDocs: "in My Documents",
//	fileMenu_SaveToSymphony: "to Lotus Symphany",
	fileMenu_ShareWith: "Podijeli s...	",
	fileMenu_ExportAsPDF: "Eksportuj kao PDF",
	fileMenu_WebPreview: "Web pregled",
	fileMenu_PrintPreview: "Pregled ispisa",
	fileMenu_RecentFile: "Nedavne datoteke",
	fileMenu_Print: "Printanje...",
	editMenu: "Uredi",
	editMenu_Undo: "Poništi",
	editMenu_Redo: "Ponovo napravi",
	editMenu_Cut: "Izreži",
	editMenu_Copy: "Kopiraj",
	editMenu_Paste: "Zalijepi",
	editMenu_DeleteSlide:"Izbriši slajd",
	editMenu_SelectAll: "Izaberi sve",
	editMenu_Find: "Nalaženje...",
	editMenu_Replace: "Zamjena...",
	editMenu_DeleteSheet: "Izbriši list",
	editMenu_DuplicateSheet: "Dupliciraj list",
	editMenu_DeleteRow: "Izbriši red",
	editMenu_DeleteColumn: "Izbriši kolonu",
	editMenu_ClearCell: "Očisti ćeliju",
	viewMenu: "Pogled",
	viewMenu_Master: "Glavni",
	viewMenu_Notifications: "Obavještenja",
	viewMenu_ShowHideIndicators: "Pokaži/sakrij indikatore zajedničkog uređivanja",
	viewMenu_SlideSorter: "Pokaži sortiranje slajdova",
	viewMenu_SpeakerNotes: "Pokaži napomene za govornika",
	viewMenu_NextSlide: "Sljedeći slajd",
	viewMenu_PrevSlide: "Prethodni slajd",
	createMenu: "Kreiraj",
	createMenu_NewSlide: "Novi slajd",
	createMenu_DuplicateSlide: "Dupliciraj slajd",
	createMenu_ImageFromFile: "Grafika iz datoteke",
	createMenu_TextBox: "Tekstualni okvir",
	createMenu_Task: "Zadatak",
    formatMenu_Text_Direction: "Smjer teksta",
    formatMenu_Ltr: "S lijeva na desno",
    formatMenu_Rtl: "S desna na lijevo",  	
    formatMenu_Horizontal_Align: "Horizontalno poravnanje",
    formatMenu_Vertical_Align: "Vertikalno poravnanje",
    formatMenu_Align_Top: "Vrh",
    formatMenu_Align_Middle: "Sredina",
    formatMenu_Align_Bottom: "Dno",
	layoutMenu: "Izgled",
	layoutMenu_SlideLayout: "Izgled slajda",
	layoutMenu_SlideDesign: "Glavni stilovi",
	tableMenu: "Tabela",
	tableMenu_CreateTable: "Kreiraj tabelu",
	tableMenu_Cell: "Ćelija",
	tableMenu_CellAlignLeft: "Poravnaj tekst lijevo",
	tableMenu_CellAlignCenter: "Poravnaj tekst centralno",
	tableMenu_CellAlignRight: "Poravnaj tekst desno",
	tableMenu_CellClearContents: "Očisti sadržaj",
	tableMenu_Row: "Red",
	tableMenu_RowAddRowAbove: "Dodaj red iznad",
	tableMenu_RowAddRowBelow: "Dodaj red ispod",
	tableMenu_RowMoveRowAbove: "Premjesti red iznad",
	tableMenu_RowMoveRowBelow: "Premjesti red ispod",
	tableMenu_RowDelete: "Izbriši",
	tableMenu_ColumnAddColumnBefore: "Dodaj kolonu ispred",
	tableMenu_ColumnAddColumnAfter: "Dodaj kolonu iza",
	tableMenu_ColumnMoveColumnAfter: "Premjesti kolonu iza",
	tableMenu_ColumnMoveColumnBefore: "Premjesti kolonu ispred",
	tableMenu_ColumnDelete: "Izbriši",
	tableMenu_ColumnSortAscending: "Sortiraj uzlazno",
	tableMenu_ColumnSortDescending: "Sortiraj silazno",
	tableMenu_Column: "Kolona",
	tableMenu_Delete: "Izbriši",
	presentationMenu: "Prezentacija",
	presentationMenu_SlideShow: "Pokreni prikazivanje slajdova",
	presentationMenu_SlideShowFromCurrent: "Prikaži od trenutnog slajda",
	toolsMenu: "Alati",
	toolsMenu_Task: "Zadatak",
	helpMenu: "Pomoć",
	helpMenu_Overview: "Sadržaji pomoći"
})

