/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
	saveTip : "Spremi",
	undoTip : "Poništi",
	redoTip : "Ponovo napravi",
	webClipboardTip : "Web memorija za isječke",
	spellCheckTip : "Izvedi manuelnu provjeru pravopisa",
	createSectionTip : "Dodijeli sekciju",
	createCellsTip : "Dodijeli ćelije",
	createSlideTip : "Zaduženje slajdova",
	submitTip: "Pošalji zaduženje",
	addCommentTip : "Dodaj komentar",
	removeFormatTip: "Ukloni formatiranje",
	sortAscTip: "Sortiraj uzlazno",
	sortDescTip: "Sortiraj silazno",
	instantFilterTip: "Instant filter",
	insertChartTip:"Ubaci grafikon",
	startAutofillTip:"Samoispunjavanje",
	dataValidationTip:"Provjera podataka",
	
	selectFontTip : "Izaberi font",
	selectFontSizeTip : "Izaberi veličinu fonta",
	selectFontNameTip: "Izaberi ime fonta",
	FontName : "Ime fonta",
	FontSize : "Veličina fonta",
	increaseFontSizeTip : "Povećaj veličinu fonta",
	decreaseFontSizeTip : "Smanji veličinu fonta",
	boldTip : "Podebljano",
	italicTip : "Kurziv",
	underlineTip : "Podcrtano",
	strikeThroughTip : "Precrtano",
	setFontColorTip : "Postavi boju fonta",
	setShadingColorTip : "Postavi boju sjenčanja",
	setBackgroundFill: "Postavi boju unutrašnjosti",
	setBgColorTip: "Postavi boju pozadine",
	setBorderTip: "Postavi stil i boju ivice",
	setBorderColorTip: "Postavi boju ivice",
	setHighlightColor : "Postavi boju isticanja",
	formatPainter:"Kopirajte formatiranje",
//	clearFormat:"Remove Formatting",
	zoom: "Zumiranje",
	selectStyleTip : "Izaberi stil",
	styles : "Stil",
	formatAsCurrencyTip: "Formatiraj kao valutu",
	formatAsPercentTip: "Formatiraj kao postotak",
	decreaseDecimalTip: "Smanji broj decimalnih mjesta",
	increaseDecimalTip: "Povećaj broj decimalnih mjesta",	
	formatNumberTip: "Formatiraj broj",
	
	numberedListTip : "Dodaj numerisanje ili promijeni stil numerisanja",
	bulletedListTip : "Dodaj oznake ili promijeni stil oznaka",
	multilevelListTip : "Dodaj ili promijeni listu s više razina",
	indentTip : "Povećaj uvlačenje",
	decreaseIndentTip : "Smanji uvlačenje",
	alignTip: "Poravnaj",
	leftAlignTip : "Poravnaj lijevo",
	centerTip : "Poravnaj centralno",
	rightAlignTip : "Poravnaj desno",
	justifyTip : "Poravnaj",
	bottomBorderTip : "Obrub na dnu",
	borderTypes : "Tipovi obruba",
	borderTip : "Postavi stil obruba",
	topAlignTip : "Poravnaj vrh",
	middleAlignTip : "Poravnaj sredinu",
	bottomAlignTip : "Poravnaj dno",
	lineSpacingTip : "Prored",
	mergeSplitCellTip: "Spoji ili razdijeli ćelije",
	wrapNoWrapTip: "Uključi ili isključi preklapanje",
	ltrDirectionTip : "Promijeni na tekst slijeva nadesno",
	rtlDirectionTip : "Promijeni na tekst zdesna nalijevo",
	autoDirectionTip : "Promijeni smjer teksta",
	toggleSheetDirectionTip : "Promijeni smjer radnog lista",
	setSheetDirectionLTR : "Slijeva nadesno",
	setSheetDirectionRTL : "Zdesna nalijevo",
	
	addTableTip : "Dodaj tabelu",
	insertOrMoveRowTip : "Ubaci ili premjesti red",
	insertOrMoveColTip : "Ubaci ili premjesti kolonu",
	insertOrDeleteRowTip : "Ubaci ili izbriši red",
	insertOrDeleteColTip : "Ubaci ili izbriši kolonu",
	insertFunctionTip: "Ubaci funkciju",
	insertImage : "Ubaci sliku",
	resizeCol : "Promijeni veličinu kolone",
	resizeCols : "Promijeni veličinu kolone",
	addLink : "Dodaj ili uredi link",
	tableStyle: "Stilovi tabele",
	
	selectBorder_BottomBorder : "Donji obrub",
	selectBorder_TopBorder : "Gornji obrub",
	selectBorder_LeftBorder : "Lijevi obrub",
	selectBorder_RightBorder : "Desni obrub",
	selectBorder_NoBorder : "Bez linija",
	selectBorder_AllBorders : "Svi obrubi",
	
	insertOrMoveRow_InsertAbove : "Ubaci red iznad",
	insertOrMoveRow_InsertBelow : "Ubaci red ispod",
	insertOrMoveRow_MoveUp : "Premjesti red gore",
	insertOrMoveRow_MoveDown : "Premjesti red dolje",
	insertOrMoveCol_InsertLeft : "Ubaci kolonu ispred",
	insertOrMoveCol_InsertRight : "Ubaci kolonu iza",
	insertOrMoveCol_InsertBefore : "Ubaci kolonu ispred",
	insertOrMoveCol_InsertAfter : "Ubaci kolonu iza",
	insertOrMoveCol_MoveLeft : "Premjesti kolonu lijevo",
	insertOrMoveCol_MoveRight : "Premjesti kolonu desno",

	insertOrDelete_Delete : "Izbriši",
	
	combineButtonReadTip : "Pritisni tipku Strelica dole za aktiviranje menija, a zatim se pomičite pomoću tipki sa strelicama",
	
	lineSpacing_1 : "1",
	lineSpacing_12 : "1.2",
	lineSpacing_15 : "1.5",
	lineSpacing_2 : "2",
	lineSpacing_25 : "2.5",
	lineSpacing_3 : "3",
	
	percent: "%",
	font_arial: "Arial",
	
	fontSize: "${0}pt",

	slides:"Jedan slajd po strani",
	slidesWithNotes:"Slajdovi s napomenama",
	preparingSlides:"Priprema slajdova za ispis...",
	printLayoutOptionLabel:"Opcije izgleda ispisa",
	
	targetRemovedWhenDialogOpen : "Ova akcija ne može biti dovršena jer je cilj uklonio drugi co-editor.",
	
	NUMBER:"Broj",
	CURRENCY:"Valuta",
	PERCENT:"Postotak",
	DATE:"Datum",
	TIME:"Vrijeme",
	DATETIME: "Datum i vrijeme",
	MORECURRENCY:"Više valuta po novčanoj jedinici",
	MORECURRENCYCODE:"Više valuta po šifri valute",
	MOREDATE:"Više formata vremena i datuma",
	TEXT: "Tekst",
	
	// currency, by currency code
	// NOTE: MUST keep it in order
	CURRENCY_CODE: {
		ARS: "Argentina (Pezo)",
		AUD: "Australija (Dolar)",
		BGN: "Bugarska (Leva)",
		BOB: "Bolivija (Bolivijano)",
		BRL: "Brazil (Real)",
		CAD: "Kanada (Dolar)",
		CHF: "Švajcarska (Franak)",
		CLP: "Čile (Pezo)",
		CNY: "Kina (Juan)",
		COP: "Kolumbija (Pezo)",
		CRC: "Kostarika (Kolon)",
		CZK: "Češka (Kruna)",
		DKK: "Danska (Kruna)",
		DOP: "Dominikanska Republika (Pezo)",
		EGP: "Egipat (Funta)",
		EUR: "Austrija, Belgija, Finska, Francuska,  ..., Slovenija, Španjolska (Euro)",
		GBP: "Engleska, Ujedinjeno Kraljevstvo (Funta)",
		HKD: "Hong Kong (Dolar)",
		HRK: "Hrvatska (Kuna)",
		HUF: "Mađarska (Forinta)",
		IDR: "Indonezija (Rupija)",
		ILS: "Izrael (Novi šekel)",
		INR: "Indija (Rupija)",
		JPY: "Japan (Jen)",
		KRW: "Koreja, južna (Von)",
		KZT: "Kazakstan (Tenges)",
		MAD: "Maroko (Dirham)",
		MXN: "Meksiko (Pezo)",
		MYR: "Malezija (Ringit)",
		NOK: "Norveška (Kruna)",
		NZD: "Novi Zeland (Dolar)",
		PAB: "Panama (Balboa)",
		PEN: "Peru (Novi sol)",
		PHP: "Filipini (Pezo)",
		PKR: "Pakistan (Rupija)",
		PLN: "Poljska (Zloti)",
		PYG: "Paragvaj (Gvarani)",
		RON: "Romunija (Novi leu)",
		RUB: "Rusija (Rubalj)",
		SAR: "Saudijska Arabija (Rijal)",
		SEK: "Švedska (Kruna)",
		SGD: "Singapur (Dolar)",
		SVC: "El Salvador (Kolon)",
		THB: "Tajland (Baht)",
		TRY: "Turska (Lira)",
		TWD: "Tajvan (Novi dolar)",
		USD: "Ekvador, Portoriko, SAD (dolar)",
		UYU: "Urugvaj (Pezo)",
		VEF: "Venezuela (Bolivar)",
		VND: "Vijetnam (Dong)",
		ZAR: "Južna Afrika (Rand)"
	},
	// for border toolbar
	allBorders:"Svi ivice",
	innerBorders: "Unutrašnji ivice",
	horizontalBorders: "Horizontalni ivice",
	verticalBorders: "Vertikalni ivice",
	outerBorders: "Vanjski ivice",
	borderColor: "Boja ivice",
	leftBorder: "Lijevi obrub",
	topBorder: "Gornji rub",
	rightBorder: "Desni obrub",
	bottomBorder: "Donji rub",
	clearBorders: "Bez rubova",	
	BorderStyle_ThinSolid: "Tanko puno",
	BorderStyle_ThinDotted: "Tanko tačkasto",
	BorderStyle_ThinDashed: "Tanko isprekidano",
	BorderStyle_ThickSolid: "Debelo puno",
	BorderStyle_ThickDotted: "Debelo tačkasto",
	BorderStyle_ThickDashed: "Debelo isprekidano"
})



