({
	labelPrintConfig: "לתוצאות הדפסה מיטביות, השתמשו בערכים אלה להגדרת העמודים של הדפדפן: ",
	labelConfigPageSize: "גודל עמוד: ${0}",
	labelConfigOrientation: "כיווניות: ${0}",
	labelConfigHeader: "כותרת עליונה: ריק",
	labelConfigFooter: "כותרת תחתונה: ריק",
	labelConfigMargins: "שוליים: ",
	labelConfigMarginTop: "ראש: ${0}${1}",
	labelConfigMarginBottom: "תחתית: ${0}${1}",
	labelConfigMarginLeft: "ימין: ${0}${1}",
	labelConfigMarginRight: "שמאל: ${0}${1}",
	labelPrintContinue: "לאחר שתקבעו את הגדרות הדפדפן, לחצו על 'אישור' כדי להמשיך בהדפסה הקובץ שלכם.",
	labelMm: "מילימטרים",
	labelInch: "אינצ'ים",
	labelPortrait: "אנכית",
	labelPageA4: "A4",
	labelLetter: "Letter",
	labelLandscape: "אופקית",
	titlePrintConfig: "הגדרות הדפסה",
	titlePrepare: "הכנה להדפסה",
	msgPrepare: "הכנת הקובץ להדפסה מתבצעת כעת. ההכנה עשויה להימשך זמן רב.",
	errPrepare: "אירעה שגיאה בהכנת הנתונים.\nהאם ברצונכם לנסות שוב?",
	titleErr: "שגיאה",
	btnRetry: "נסיון חוזר"
})
