({	
	createTaskSummary: "${0} ha creato l\'attività.",
	completeTaskSummary: "${0} ha contrassegnato l'attività come completa.",
	editTaskSummary5: "${0} ha modificato le attività ${1}, ${2}, ${3}, ${4} e ${5}.",
	editTaskSummary4: "${0} ha modificato le attività ${1}, ${2}, ${3} e ${4}.",
	editTaskSummary3: "${0} ha modificato le attività ${1}, ${2} e ${3}.",
	editTaskSummary2: "${0} ha modificato le attività ${1} e ${2}.",
	editTaskSummary1: "${0} ha modificato l\'attività ${1}.",
	editTaskSummary0: "${0} ha modificato l\'attività.",
	removeTaskSummary: "${0} ha rimosso l\'attività.",
	reopenTaskSummary: "${0} ha riaperto l'attività.",
	reassignTaskSummary: "${0} ha riassegnato ${1} da ${2} a ${3}.",
	reassignTaskSummary2: "${0} ha riassegnato l'assegnatario da ${1} a ${2} e il revisore da ${3} a ${4}.",
	workPrivateSummary: "${0} ha cominciato a lavorare in privato a questa attività.",
	approveTaskSummary: "${0} ha approvato questa attività.",
	rejectTaskSummary: "${0} ha rifiutato questa attività.",
	rejectTaskSummary2: "${0} ha restituito questa attività a ${1} per la rielaborazione.",
	submitTaskSummary: "${0} ha reinviato il lavoro privato al documento.",
	cancelPrivateSummary: "${0} ha annullato il lavoro privato.",
	updatedFieldsDesc: "${0}: ${1} -> ${2}",
	fieldAssignee: "assegnatario",
	fieldDuedate: "data di scadenza",
	fieldDescription: "descrizione",
	fieldReviewer: "revisore",
	fieldTitle: "titolo",
	emptyFieldValue: "[Non assegnato]",
	errorAddMember:"Non c'è accesso al server delle attività per aggiungere assegnatari o revisori. Riprovare in seguito.",
	errorCreateActivity:"Non c'è accesso al server delle attività per creare l'attività. Riprovare in seguito.",
	errorLoadActivity:"Non c\'è accesso al server delle attività per caricare le assegnazioni. Riprovare in seguito.",
	errorCreateAssignment: "Non c'è accesso al server delle attività per creare l'assegnazione. Riprovare in seguito.",
	errorDeleteAssignment: "Non c'è accesso al server delle attività per eliminare le assegnazioni. Riprovare in seguito.",
	errorupdateAssignment: "Non c'è accesso al server delle attività per aggiornare le assegnazioni. Riprovare in seguito.",
	errorSubmitAssignment: "Impossibile eseguire questa azione. Verificare se si dispone dell'autorizzazione per eseguire questa operazione.",	
	errorAddMember2:"Non c'è accesso al server per aggiungere assegnatari o revisori. Riprovare in seguito.",
	errorCreateActivity2:"Non c'è accesso al server per creare l'attività. Riprovare in seguito.",
	errorLoadActivity2:"Non c'è accesso al server per caricare le assegnazioni. Riprovare in seguito.",
	errorCreateAssignment2: "Non c'è accesso al server per creare l'assegnazione. Riprovare in seguito.",
	errorDeleteAssignment2: "Non c'è accesso al server per eliminare le assegnazioni. Riprovare in seguito.",
	errorupdateAssignment2: "Non c'è accesso al server per aggiornare le assegnazioni. Riprovare in seguito."	
})
