/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2014. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
	service_unavailable_title: "השירות אינו זמין.",
	service_unavailable_content: "שירות ${productName} אינו זמין. לא ניתן לעבד את בקשתכם כרגע. נסו שוב מאוחר יותר או פנו למנהלן המערכת.",
	access_denied_title: "הגישה נחסמה.",
	viewaccess_denied_content: "אין לכם הרשאה להציג קובץ זה.‏ הקובץ חייב להיות ציבורי או משותף אתכם.",
	editaccess_denied_content: "אינכם זכאים להשתמש ב-${productName} או שאין לכם הרשאה לערוך קובץ זה. הקובץ חייב להיות משותף אתכם ורמת הגישה שלכם חייבת להיות מוגדרת בתור 'עורך'. יתכן גם שהקובץ ננעל על ידי עורך אחר.",
	doc_notfound_title: "המסמך לא נמצא.‏",
	doc_notfound_content: "המסמך שברצונכם לגשת אליו נמחק או הועבר. ודאו שהקישור נכון.",
	repository_out_of_space_title: "אין מספיק מקום",
	repository_out_of_space_content: "לא ניתן לפרסם את ${0} מפני שהגעתם למכסת גודל הקבצים שלכם. העבירו קבצים לסל המיחזור ואז מחקו אותם כדי להקטין את המיכסה שלכם.",
	fileconnect_denied_title: "החיבור נדחה.",
	fileconnect_denied_content: "${productName} אינו מצליח להתחבר אל מאגר הקבצים. נסו שוב מאוחר יותר או פנו למנהלן המערכת.",
	unscanned_document_title: "סריקת הווירוסים מסתיימת",
	unscanned_document_content: "קבצים הנטענים אל Connections נסרקים אוטומטית. תוכלו לערוך קובץ זה ברגע שהסריקה תסתיים. ",
	malicious_document_title: "קובץ מזיק ",
	malicious_document_content: "אינכם יכולים לערוך קובץ זה כי Connections גילה וירוס בזמן סריקת הקובץ. ",	
	convservice_unavailable_title: "שירות ההמרה אינו זמין.",
	convservice_unavailable_content: "שירות ההמרה של ${productName} אינו זמין. לא ניתן לעבד את בקשתכם כרגע. נסו שוב מאוחר יותר או פנו למנהלן המערכת.",
	doc_toolarge_title: "הקובץ גדול מדי.",
	doc_toolarge_content: "המסמך שברצונכם לגשת אליו גדול מדי.",
	doc_toolarge_content2: "לא ניתן לגשת אל הקובץ. סיבות אפשריות הן:",
	doc_toolarge_content3: "לא ניתן להציג את הקובץ מפני שגודל הקובץ גדול מ-${0} KB.‏ תוכלו להוריד את הקובץ כדי לערוך אותו. אם הקובץ מכיל תמונות ברזולוציה גבוהה, תוכלו להחליף אותן בתמונות ברזולוציה נמוכה כדי להקטין את גודל הקובץ.",
	doc_toolarge_content4: "הקובץ גדול מדי להצגה כאן, אך תוכלו לפתוח אותו בלחיצה על לחצן ההורדה בפס הכותרת. ",
	doc_toolarge_content_mobile: "לא ניתן לפתוח את הקובץ. גודל הקובץ אינו יכול לעלות על ${0} קילובתים בהתקן נייד.",
	sheet_toolarge_content: "גודל הגליון האלקטרוני גדול מ-${0} קילובתים.",
	sheet_toolarge_content2: "הגליון האלקטרוני מכיל יותר מ-${0} שורות בגליון אחד.",
	sheet_toolarge_content5: "הגליון האלקטרוני מכיל יותר מ-${0} עמודות בגליון אחד.",
	sheet_toolarge_content3: "הגליון האלקטרוני מכיל יותר מ-${0} תאים.",
	sheet_toolarge_content4: "הגליון האלקטרוני מכיל יותר מ-${0} נוסחאות.",
	text_toolarge_content: "גודל המסמך עולה על ${0} קילובתים.",
	text_toolarge_content2:"המסמך מכיל יותר מ-0${0} עמודים.",
	text_toolarge_content3:"גודל התמליל של המסמך עולה על ${0} קילובתים.",
	pres_toolarge_content: "לא ניתן לגשת אל המצגת, מפני שגודל המצגת עולה על ${0} KB.‏ אם יש במצגת תמונות ברזולוציה גבוהה, תוכלו להחליף אותן בתמונות ברזולוציה נמוכה כדי להקטין את גודל המצגת.",
	pres_toolarge_content2: "לא ניתן לגשת למצגת, מפני שהיא מכילה יותר מ-${0} עמודים.",
	pres_toolarge_content3: "לא ניתן לגשת למצגת, מפני שהיא מכילה יותר מ-${0} אובייקטים.",
	pres_toolarge_content2_mobile: "לא ניתן לפתוח את המצגת, מפני שהמצגת מכילה יותר מ-${0} עמודים בהתקן נייד.",
	pres_toolarge_content3_mobile: "לא ניתן לפתוח את המצגת, מפני שהיא מכילה יותר מ-${0} אובייקטים בהתקן נייד.",
	sheet_view_toolarge_content1_mobile: "לא ניתן להציג את הגליון האלקטרוני, מפני שהוא מכיל יותר מ-${0} שורות בהתקן נייד.",
	sheet_view_toolarge_content2_mobile: "לא ניתן להציג את הגליון האלקטרוני, מפני שהוא מכיל יותר מ-${0} עמודות בהתקן נייד.",
	sheet_view_toolarge_content3_mobile: "לא ניתן להציג את הגליון האלקטרוני, מפני שהוא מכיל יותר מ-${0} שורות ו-${1} עמודות בהתקן נייד.",
	conversion_timeout_title: "המרת המסמך חרגה ממגבלת הזמן.",
	conversion_timeout_content: "בשלב זה, המרת המסמך נמשכת זמן רב מדי. נסו שוב מאוחר יותר.‏",
	invalid_docformat_title: "לא ניתן לפתוח המסמך",
	invalid_docformat_content: "סיומת המסמך חוקית, אך לא ניתן לקרוא את התוכן, מפני שהוא פגום או מוצפן.",
	template_extension_conent_mismatch: "הסיומת של קובץ המקור מזהה אותו באופן שגוי כתבנית. בפועל הקובץ הוא במבנה ‎.${0}.‏ התחילו עם תבנית חוקית, או שמרו קובץ זה בשם שונה הכולל ${0} כסיומת.",
	invalid_docformat_title2: "לא ניתן ליבא את הקובץ לתוך ${productName}.",
	invalid_docformat_content2: "יש בקובץ מאפיין ש-${productName} אינו תומך בו כרגע. לא ניתן ליבא קובץ זה.",
	invalid_doctype_title: "סוג המסמך אינו נתמך.",
	invalid_doctype_content: "סוג המסמך אינו נתמך על ידי ${productName} כרגע.",
	unsupported_browser_title: "הדפדפן שלכם אינו תומך בכל המאפיינים",
	malformed_request_title: "הבקשה אינה במבנה תקין.",
	malformed_request_content: "ודאו שה-URL והפרמטרים נכונים.",
	storageserver_error_title: "שרת האחסון אינו זמין.",
	storageserver_error_content: "השרת אינו זמין כרגע. לא ניתן לעבד את בקשתכם כרגע. נסו שוב מאוחר יותר או פנו למנהלן המערכת.",
	document_already_opened_title: "המסמך כבר פתוח",
	document_already_opened_content:"מסמך זה כבר נפתח בדפדפן שלכם.",
	toomany_documents_opened_inone_browser_title: "לא ניתן לפתוח את המסמך",
	toomany_documents_opened_inone_browser_content:"אפשר לפתוח רק חמישה קובצי ${productName} בבת אחת. סגרו מסמכים אחרים ונסו לפתוח את המסמך שוב.",
	document_max_session_exceeded_title:"השירות אינו זמין.",
	document_max_session_exceeded_content:"יותר מדי משתמשים עורכים מסמכים בשרת, לא ניתן להמשיך עם הבקשה שלכם. נסו שוב מאוחר יותר.‏",
	kickout_user_content: "מסמך זה כבר פתוח בחלון אחר במחשב שלכם. חזרו אל החלון האחר אם ברצונכם להמשיך לערוך את המסמך.",
	return_to_files: "בחזרה ליישום הקבצים",
	return_to_library: "חזרה לספריה",
	return_to_icn: "חזרה אל Content Navigator",
	document_already_open: "המסמך כבר פתוח",
	cannotedit_noentitled_title: "קובץ זה אינו מאפשר עריכה משותפת",
	cannotedit_noentitled_content1: "המשתמשים שלהלן עורכים את הקובץ עכשיו:",
	cannotedit_noentitled_content2: "אינכם מורשים לערוך קובץ זה בזמן שאחרים עורכים אותו. נסו לערוך את הקובץ מאוחר יותר.",
	cannotedit_noentitled_content3: "המשתמשי שלהלן עורך את הקובץ עכשיו:",
	cannotedit_noentitled_content4: "אינכם יכולים להצטרף למהלך עריכה זה, מפני שהמשתמש העורך אינו זכאי לעריכה משותפת. נסו לערוך את הקובץ מאוחר יותר.",
	toomany_coeditors_title: "יותר מדי משתמשים",
	toomany_coeditors_content: "יותר מדי משתמשים עורכים כרגע מסמך זה, רק {0} משתמשים יכולים לעבוד על מסמך זה באותו הזמן.",
	encrypted_pptdoc_title:"קובץ מוצפן",
	encrypted_pptdoc_content:"קובץ זה מוגן בסיסמה. ניתן לערוך אותו בתוך ${productName} רק אם פוענח קודם לכן. ",
	server_busy_title:"השרת עמוס",
	server_busy_content:"המתינו זמן מה ונסו שוב מאוחר יותר.",
	document_encrypt_title:"המסמך המוצפן אינו נתמך",
	document_encrypt_content:"הקובץ מוצפן במאגר הקבצים. משיקולי אבטחה, ${productName} אינו יכול לערוך אותו ישירות.",
	edit_locked_file: "אינכם יכולים לערוך את הקובץ מפני שהוא ננעל על ידי עורכים אחרים.",
	publish_locked_file: "אינכם יכולים לפרסם קובץ זה כגרסה חדשה מפני שהוא נעול. עם זאת, התוכן שלכם נשמר אוטומטית בטיוטה.",
	join_locked_file_session: "אינכם יכולים להצטרף לעריכה המשותפת  של קובץ זה מפני שהוא ננעל על ידי אחרים.",
	no_need_to_convert_title:"אין צורך בהמרה",
	no_need_to_convert_content:"הקובץ שברצונכם להמיר כבר במבנה המבוקש. נא להוריד אותו ישירות.",
	warning_icon: "איקון אזהרה",
	//html viewer error message
	incorrect_web_address_title:"כתובת רשת שגויה.",
	incorrect_web_address_content:"כתובת הרשת שגויה.  ציינו את כתובת הרשת ונסו שוב.",
	unexpecified_conversion_error_title:"השגיאה אינה ספציפית.",
	unexpecified_conversion_error_content:"השרת החזיר שגיאה לא ספציפית.",
	encrypted_conversion_error_title:"המסמך המוצפן אינו נתמך.",
	encrypted_conversion_error_content:"הקובץ מוגן בסיסמה. כדי להציג את הקובץ במציג, ודאו תחילה שהקובץ פוענח.",
	service_busy_title:"כשל בפתיחת המסמך",
	service_busy_content:"לא ניתן לפתוח את הקובץ שברצונכם להציג. יתכן שהשרת עמוס או לא זמין. נסו שוב מאוחר יותר או פנו אל המנהלן.",
	empty_doc_title: "המסמך ריק.",
	empty_doc_content: "ודאו שהמסמך מכיל תוכן, ונסו שוב.",
	corrupted_doc_title: "לא ניתן לפתוח את הקובץ.",
	corrupted_doc_content: "הקובץ מכיל תוכן לא נתמך, לדוגמה הגדרות מאקרו, ולכן לא ניתן להציג אותו ביישום זה.",
	draft_storage_error_title: "לא ניתן לפתוח המסמך.",
	draft_storage_error_content: "לא ניתן לטעון את התוכן מפני שהוא פגום. פנו אל מנהלן כדי לקבל תמיכה.",
	unexpected_code_title: "שרת ${productName} החזיר קוד לא צפוי.",
	unexpected_code_content: "שרת ${productName} החזיר קוד לא צפוי.",
	request_time_out_title: "טעינת המסמך חרגה ממגבלת הזמן.",
	request_time_out_content: "טעינת מסמך זה אורכת זמן רב מדי. נא לנסות שוב מאוחר יותר.",
	problem_id_msg_title: "דווחו על בעיה זו למנהלן. ",
	problem_id_msg_show: "לחצו כדי להציג פרטים ",
	problem_id_msg_hide: "לחצו כדי להסתיר "
})

