/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2014. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        spreadsheetTemplates: "תבניות גליון אלקטרוני",
        documentTemplates: "תבניות מסמך",
        titleShareDocument: "שיתוף מסמך",
        offline: "עבודה לא מקוונת",
        versionPublishing: "הגרסה מפורסמת כעת.",
        versionPublishFailed: "הגרסה לא פורסמה. יתכן שהקובץ גדול מדי, או יתכן שהשרת חרג ממגבלת הזמן. נסו שוב, או בטלו ובקשו מהמנהלן לבדוק את יומן השרת כדי לזהות את הבעיה.",
        versionCheckinFailed: "הגרסה לא הופקדה. יתכן שהקובץ גדול מדי, או יתכן שהשרת חרג ממגבלת הזמן. נסו שוב, או בטלו ובקשו מהמנהלן לבדוק את יומן השרת כדי לזהות את הבעיה.",
        versionSavedFailed: "השמירה לא הושלמה. נסו לשמור שוב מאוחר יותר.‏",
        publishFileSizeExceedMsg: "לא ניתן לפרסם את הקובץ מפני שהוא חורג מהגודל המרבי שהגדיר מנהלן המאגר. מחקו חלק מהתוכן כדי להקטין את הקובץ, או פנו למנהלן כדי להגדיל את מגבלת הגודל.",
        checkinFileSizeExceedMsg: "לא ניתן להפקיד את הקובץ מפני שהוא חורג מהגודל המרבי שהגדיר מנהלן המאגר. מחקו חלק מהתוכן כדי להקטין את הקובץ, או פנו למנהלן כדי להגדיל את מגבלת הגודל.",
        versionpublished: "הגרסה פורסמה על ידי ${0} בשעה ${1}",
        versionPublishing2: "הגרסה נשמרתת כעת.",
        versionPublishFailed2: "הגרסה לא נשמרה. יתכן שהקובץ גדול מדי, או יתכן שהשרת חרג ממגבלת הזמן. נסו שוב, או בטלו ובקשו מהמנהלן לבדוק את יומן השרת כדי לזהות את הבעיה.",      
        publishFileSizeExceedMsg2: "לא ניתן לשמור את הקובץ מפני שהוא חורג מהגודל המרבי שהגדיר מנהלן המאגר. מחקו חלק מהתוכן כדי להקטין את הקובץ, או פנו למנהלן כדי להגדיל את מגבלת הגודל.",
        versionpublished2: "הגרסה נשמרה על ידי ${0} בשעה ${1}",
        chekinCloseDocsMsg: "אתם יכולים לסגור את ${productName} כעת.",
        draftSavingAs: "העתקת קבצים...‏",
        draftSavedAs: "העותק החדש נשמר בשם ${0}.",
        synchronizing: "המתינו עד שפעולת הסינכרון עם השרת תושלם.",
        synchronizeError: "לא ניתן להשלים את פעולת הסינכרון עם השרת.",
        joinwithoutentitle: "משתמשים: ${0} רוצים לערוך את המסמך, אך אינם יכולים להצטרף למהלך העריכה מפני שאינכם זכאים לעריכה משותפת.",
        joinwithoutentitle2: "משתמשים: ${0} רוצים לערוך את המסמך, אך אינם יכולים להצטרף למהלך העריכה מפני שאינם זכאים לעריכה משותפת.",
        backtoFiles: "פתיחת 'הקבצים שלי'",
        backtoCommFiles: "פתיחת 'קובצי קהילה'",
        backtoLibrary: "פתיחת ספריה",
        backtoICN: "פתיחת נווט התוכן",
        backtoRepository: "פתיחת רשימת קבצים",
        createNewSpred: "יצירת גליון אלקטרוני",
        createNewDoc: "יצירת מסמך",
        createNewDocFromTemp: "יצירת מסמך מתבנית",
        shareDoc: "שיתוף מסמך",
        exportPdf: "הגדרות עמוד",
        insertDate: "בחירת תאריך",
        insertTime: "בחירת שעה",
        connect: "חיבור",
        theDoc: "המסמך",
        save: "שמירת שינויים",
        saveBeforeReviewMsg: "יש לכם שינויים שלא נשמרו. שמרו את השינויים ואז הגישו לסקירה שוב.",
        submitReviewWidgetsFaiure: "היישום לא אותחל באופן תקין. הגישו לסקירה שוב מאוחר יותר.",
        widgetsFaiure: "היישום לא אותחל באופן תקין.",
        slideSorter: "שקופיות",
        commentsBar: "הערות",
        draftBadge: "טיוטה",
        share: "שיתוף",
        comment: "הערה",
        showSidebar: "הצגת סרגל הצד",
        publishVersion: "פרסום",
        checkInVersion: "הפקדה",
        saveVersion: "שמירה",
        saved: "כל השינויים נשמרו",
        saving: "שמירה",
        submitFragment: "הגשה",
        aria_inMainMenu: "אתם נמצאים כעת בתפריט הראשי",
        aria_inSlideSorter: "אתם נמצאים כעת בתצוגת מאגר השקופיות",
        aria_inSlideEditor: "אתם נמצאים כעת בתצוגת עורך השקופיות",
        createNewPres: "יצירת מצגת",
        createNewAppFromTemp: "יצירת מסמך מתבנית",
        textdoc: "תמליל",
        sheetdoc: "גליון אלקטרוני",
        presdoc: "מצגת",
        saveAsTextErrMsg: "לא ניתן לשמור את מסמך התמליל החדש.",
        saveAsPresErrMsg: "לא ניתן לשמור את מסמך המצגת החדש.",
        saveAsSheetErrMsg: "לא ניתן לשמור את מסמך הגליון האלקטרוני החדש.",
        saveAsTextErrMsg1: "אין מספיק מקום לשמירת המסמך.",
        saveAsPresErrMsg1: "אין מספיק מקום לשמירת המצגת.",
        saveAsSheetErrMsg1: "אין מספיק מקום לשמירת הגליון האלקטרוני.",
        newDocTextErrMsg: "לא ניתן ליצור מסמך תמליל חדש.",
        newDocSheetErrMsg: "לא ניתן ליצור מסמך גליון אלקטרוני חדש.",
        newDocPresErrMsg: "לא ניתן ליצור מסמך מצגת חדש.",
        newDocTextErrMsg2: "לא ניתן ליצור מסמך תמליל חדש מהתבנית.",
        newDocSheetErrMsg2: "לא ניתן ליצור מסמך גליון אלקטרוני חדש מהתבנית.",
        newDocPresErrMsg2: "לא ניתן ליצור מסמך מצגת חדש מהתבנית.",
        newDocTextErrMsg3: "אין מספיק מקום ליצירת מסמך.",
        newDocSheetErrMsg3: "אין מספיק מקום ליצירת גליון אלקטרוני.",
        newDocPresErrMsg3: "אין מספיק מקום ליצירת מצגת.",
        newDocTextErrMsg4: "כבר יש מסמך עם כותרת זו. ציינו כותרת שונה עבור המסמך החדש.",
        newDocSheetErrMsg4: "כבר יש גליון אלקטרוני עם כותרת זו. ציינו כותרת שונה עבור הגליון האלקטרוני החדש.",
        newDocPresErrMsg4: "כבר יש מצגת עם כותרת זו. ציינו כותרת שונה עבור המצגת החדשה.",        
        aclWarningTitle: "לא ניתן לערוך את הגרסה החדשה",
        aclWarningMsg: "מאחר שהבעלים של הקובץ הגדיר אזורים מוגנים בקובץ זה, מומלץ לערוך אותו במצב מקוון. פנו אל הבעלים של הקובץ (${0}) אם אתם בטוחים שיש צורך לטעון גרסה חדשה.",
        aclWarningMsgForOwner: "יש אזורים מוגנים בקובץ זה. לכן לא תוכלו לערוך את הגרסה החדשה שנטענה באופן מקוון.  עליכם לסלק את כל האזורים המוגנים בקובץ, ואז תוכלו לפתוח ולערוך את הגרסה החדשה שנטענה.",
        st0: "גליון1",
        st1: "גליון2",
        st2: "גליון3",
        FootnoteMsg: "עמוד",
        conflictMsg: "יש סתירה עם שינויים של עורכים אחרים.  השינוי שלכם נזנח.",
        undoRedoConflictMsg: "ביטול פעולות ושחזור פעולות הושבתו בגלל סתירה בין מה שאתם עורכים לבין מה שהעורכים השותפים עורכים",
        bigFileErrMsg: "המסמך גדול מדי. רעננו את הדפדפן כדי לראות אם את כל התוכן שלם",
        noPermissionMsg: "אין לכם הרשאה לערוך קובץ זה. פנו לבעלים של הקובץ כדי לקבל הרשאת עריכה ונסו שוב.",
        networkIssueMsg: "יש בעיה ברשת.",
        networkIssueTitle: "בעיית רשת",
        networkIssueContent: "יש בעיה ברשת. רעננו את הדף ונסו להתחבר שוב.",
        lockEditorMsg: "לא ניתן לערוך את המסמך עד שיהיה חיבור עם השרת.",
        offlineReasonMsg: "מהלך העבודה שלכם חרג ממגבלת הזמן שלו.‏",
        offlineReasonForServerUnacceptedMsg: "לא ניתן לעבד חלק מהפעולות שלכם. פעולות בטווח של 1 דקה ייזנחו על ידי שרת Docs.‏",
        offlineReasonForServerDraftFormatChange: "מבנה המסמך שלכם אינו עדכני בעקבות שדרוג של השרת.",
        reloadExplanationMsg: "התחברו שוב כדי להמשיך לעבוד.",
        reloadBtnLabel: "טעינה מחדש",
        reconnectingMsg: "המתינו עד שיוקם חיבור עם השרת. ‏",
        loadMsg: "המתינו עד שהקובץ ייטען.",
        loadingDocumentMsg: "המתינו עד שהקובץ ייטען מהשרת.",
        reLoadingDocumentMsg: "המתינו עד שהקובץ ייטען מחדש מהשרת.",
        unsupportMsg: "התגלה מאפיין לא נתמך. ראו פרטים נוספים.",
        browserWorkingMsg: "בביצוע...",
        fileDeepDetectTitle: "מבנה הקובץ וסיומת הקובץ אינם תואמים",
        fileDeepDetectMsg: "מבנה הקובץ אינו המבנה המצוין על ידי סיומת הקובץ. לחצו על 'המשך' כדי לערוך את הקובץ במבנה זה.",
        fileDeepDetectOkLabel: "המשך",
        tipInfo: "עצה: ${0}",
        selectTextInfo: "בחרו תמליל להחלת סגנון.",
        removeRecentFile: "הקובץ שברצונכם לפתוח נמחק. האם ברצונכם לסלק את שם הקובץ מרשימת הקבצים האחרונים?",
        altLotusIcon: "",
        altErrorMsgIcon: "הודעת שגיאה",
        altWarningMsgIcon: "הודעת אזהרה",
        altSuccessMsgIcon: "הודעת הצלחה",
        sidebarLandmarkDesc: "סרגל צד",
        footerTitle: "כותרת תחתונה",
        mainDesc: "אזור תוכן",
        editLockedDocumentWarning: "נעלתם קובץ זה בזמן שאחרים ערכו אותו. תאמו את השינויים עם העורכים האחרים או בקשו מהם לסיים את העריכה כדי שתהיה לכם גישת עריכה בלעדית.",
        observerMode: "אתם נמצאים כעת במצב 'צופה'",
        editorMode: "אתם נמצאים כעת במצב 'עורך'",
        maxEditorLimitReached: "המסמך הגיע למספר העורכים המרבי ${0} עבור מהלך עבודה זה. תוכלו לעבור למצב עריכה כשעורך אחר יעזוב את המסמך או יעבור למצב צפייה.",
        maxEditorLimitReachedTitle: "המסמך הגיע למספר העורכים המרבי",
        uploadNewVersionOpenConfirm: "${0} טען גרסה חדשה ב-${1} ${2}. האם ברצונכם לפתוח את הגרסה החדשה?‏", //${0} name, ${1} time, ${2} date
        uploadNewVersionPublishConfirm: "${0} טען גרסה חדשה ב-${1} ${2}.", //${0} name, ${1} time, ${2} date
        you: "אתם",
        today: "היום",
        yesterday: "אתמול",
        slideShowInviteMsg: "המשתמש ${0} התחיל מצגת שקופיות משותפת. האם ברצונכם להצטרף?‏",
        slideShowInviteTitle: "הזמנה למצגת שקופיות משותפת",
        slideShowInviteTitle1: "הזמנה למצגת שקופיות קולקטיבית",
        slideShowCoviewSelectUsersTitle: "מצגת שקופיות משותפת",
        slideShowCoviewSelectUsersTitle1: "מצגת שקופיות קולקטיבית",
        slideShowCoviewStmt: "שיתוף המצב הנוכחי של המצגת במצגת שקופיות משותפת.",
        slideShowCoviewStmt1: "שיתוף המצב הנוכחי של המצגת במצגת שקופיות קולקטיבית.",
        slideShowCoviewOptionOne: "הזמנת כל העורכים להצטרף למצגת השקופיות.",
        slideShowCoviewOptionOne1: "הזמנת כל העורכים והצופים להצטרף למצגת השקופיות.",
        slideShowCoviewOptionTwo: "הזמנת העורכים שלהלן בלבד להצטרף למצגת השקופיות.",
        slideShowCoviewOptionTwo1: "הזמנת העורכים והצופים שלהלן בלבד להצטרף למצגת השקופיות.",
        slideShowCoviewSlidesOf: "שקופית ${0} מתוך ${1}",  //as in Slide 1 of 4
        slideShowCoviewViewers: "${0} צופים",
        slideShowCoviewDialogInput: "הקלידו כדי לסנן את שם",
        slideShowCoviewAddTitle: "הוספה למצגת שקופיות משותפת",
        slideShowCoviewAddTitle1: "הוספה למצגת שקופיות קולקטיבית",
        slideShowCoviewMessage: "בחרו אנשים נוספים שיוזמנו למצגת שקופיות משותפת זו.",
        slideShowCoviewMessage1: "בחרו אנשים נוספים שיוזמנו למצגת שקופיות קולקטיבית זו.",
        slideShowCoviewEnded: "מצגת השקופיות המשותפת הסתיימה",
        slideShowCoviewEndMessage: "מצגת השקופיות המשותפת שאתם מנסים להצטרף אליה כבר אינה זמינה.",
        slideShowCoviewEndMessage2: "המשתמש ${0} סיים את מצגת השקופיות המשותפת.",
        slideShowWarning: "עליכם לסגור את מצג השקופיות הנוכחית לפני שתתחילו מצגת חדשה.",
        slideShowHoverMsg: "לחצו כדי לראות מי עוד צופה במצגת השקופיות.",
        slideShowHoverMsgAdd: "לחצו כדי להזמין עוד צופים.",
        csvEmpty: "לא ניתן לייצא בתור ‎.csv מפני שהגליון אינו מכיל נתונים.",
        edit: "עריכה",
        printToPDF: "הורדה כקובץ PDF",
        print: "הדפסה",
        view: "הצגה",
        openLatestFile: "פתיחת הקובץ העדכני",
        updateDocument: "המסמך עודכן. ${0}.",
        updateSpreadsheet: "הגליון האלקטרוני עודכן.${0}",
        updatePresentation: "המצגת עודכנה. ${0}.",
        labelCancel: "ביטול",
        msgConversionFail: "ההמרה נכשלה",
        updateNow: "פתיחה עכשיו",
        fileUpdated: "המסמך עודכן.",
        fileUpdatedContent1: "המסמך עודכן. פתחו את הקובץ העדכני לפי שתדפיסו.",
        htmlviewerlimitation1: "גליון אלקטרוני זה כולל טבלת צירים שלא ניתן להציג אותה",
        htmlviewerlimitation2: "גליון אלקטרוני זה כולל עיצוב מותנה שלא ניתן להציג אותו",
        htmlviewerlimitation3: "גליון אלקטרוני זה כולל טבלת צירים ועיצוב מותנה שלא ניתן להציג",
        close: "סגירה",
        closeDocs: "סגרו את ${productName}",
        endSessionDlgTitle: "מהלך העריכה הסתיים",
        endSessionDlgNotice: "מהלך העריכה שלכם הסתיים כי ${0} הפקיד את הקובץ.",
        labelStopReview: "הפסקת הסקירה",
        labelRejct: "פסילה",
        labelApprove: "אישור",
        errorMsg: "שגיאה",
        labelItemNotFountTitle: "לא ניתן להשלים את הפעולה.",
        labelItemNotFountMsg: "חבר קהילה אחר כבר ביצע פעולה על מסמך זה. כדי לקבל מידע נוסף, סגרו את המסמך וגשו אל הדף 'פרטי קובץ' בספריה שלכם.",
        viewProtectedAreas: "גליון אלקטרוני זה כולל אזורים מוגנים. יש להציג או לערוך אותו במצב מקוון בלבד.",
        macroTitle: "הקובץ מכיל מאקרו", 
        macroDesc: "עריכת הקובץ עלולה לקלקל את המאקרו. כדי למנוע מאנשים לערוך את הטווח או הגליון המכילים את המאקרו, בחרו 'נתונים > אזורים מוגנים'.",
        problem_id_msg_title: "דווחו על בעיה זו למנהלן. ",
        problem_id_msg_show: "לחצו כדי להציג פרטים ",
    	problem_id_msg_hide: "לחצו כדי להסתיר ",
    	uploadNewVersionWarningTitle: "לא ניתן לערוך את הגרסה החדשה",
        changeHistoryWarningMsg: "מאחר שהבעלים של הקובץ הפעיל מעקב שינויים בקובץ זה, מומלץ לערוך אותו במצב מקוון. פנו אל הבעלים של הקובץ (${0}) אם אתם בטוחים שיש צורך לטעון גרסה חדשה.",
        changeHistoryWarningMsgForOwner: "יש היסטוריית שינויים בקובץ זה. לכן לא תוכלו לערוך את הגרסה החדשה שנטענה באופן מקוון.  עליכם לנקות את היסטוריית השינויים ולהשבית מעקב שינויים בקובץ זה, ואז תוכלו לפתוח ולערוך את הגרסה החדשה שנטענה.",
        viewChangeHistory: "המסמך מכיל היסטוריית שינויים. יש להציג או לערוך אותו במצב מקוון בלבד.",
    	contentCorruptErrMsg: "לא ניתן לטעון את התוכן מפני שהוא פגום. פנו אל מנהלן כדי לקבל תמיכה."
});

