({	
	viewExpandedBtn: "Vizualizare mai puţine replici",
	viewCollapsedBtn: "Vizualizare încă ${0} replici",
	placeholderMsg: "Tastaţi-vă mesajul aici",
	sure: "Sunteţi sigur că vreţi să ştergeţi acest comentariu?",
	exceed: "Comentariul este prea lung.\n Comentariul pe care l-aţi introdus depăşeşte lungimea permisă maximă.\n Reduceţi-o la nu mai mult de ${0} caractere şi faceţi clic pe Adăugare.",
	remainLabelHint:"Comentariul dumneavoastră a ajuns la limita de 500 de caractere.",
	tipsCommentField: "Tastaţi un comentariu către toţi editorii sau către un editor",
	tipsRespondField: "Tastaţi un răspuns către toţi editorii sau către un editor",	
	resolveBtn: "Rezolvare",	
	replyBtn: "Replicare",
	saveBtn: "Postare",
	deleteBtn: "Ştergere",
	cancelBtn: "Anulare",
	reopenBtn: "Redeschidere",
	todayAt: "Astăzi la ${time}",
	yesterdayAt: "Ieri la ${time}",
	dateAt: "${date} la ${time}",
	mentions: "Selectaţi un utilizator pentru menţionare",
	noMentions: "Atingeţi blancul pentru a finaliza intrarea",
	nocomments: "Nu există comentarii în documentul '${0}'.",
	
	newComments:"Comentarii noi",
	mentiontomesomebody:"Cineva",
	mentiontome:"${0} v-a menţionat într-un comentariu",
	
	newcommentsnumber:"Numărul de comentarii necitite",
	jawsnewcommentsnumber: "Numărul de comentarii necitite este ",
	jawsnactivecommentsnumber: "Numărul de comentarii active este ",
	
	activenum:"Numărul de comentarii active",
	filterDesc:"Filtrare comentarii",
	menuallcomments:"Toate comentariile",
	menutome: "@eu",
	menubyme: "De mine",
	menuactive: "Active",
	menuresolved: "Rezolvate",
	searchDesc: "Căutare comentarii",
	search: "Căutare",
	closeDesc: "Închidere căutare",
	clear: "Curăţare",
	warnEnterKeywords: "Introduceţi termeni de căutare",
	nocommentstome: "Momentan, nu există comentarii sau răspunsuri care mă menţionează în documentul '${0}'.",
	nocommentsbyme: "Momentan, nu există comentarii sau răspunsuri făcute de mine în documentul '${0}'.",
	nocommentsar: "Momentan, nu există comentarii sub categoria '${0}' în documentul '${1}'.",
	nosearchedcomments: "Momentan, nu există comentarii sau răspunsuri care conţin '${0}' sub categoria '${1}' în documentul '${2}'.",
	
	prevBtn: "Anterior",
	nextBtn: "Următor",
	mentionHint:"Afişare de la ${0} la ${1} potriviri din totalul de ${2}",
		
	resolveFlag: "Comentarii rezolvate",
	jawsCommentHint: "${authorname} a postat comentariul ${timestamp}",
	jawsReplyHint: "${authorname} a postat răspunsul ${timestamp}",
	jawsContentHint: "Conţinutul este ${content}",
	jawsCommentStatusHint: "Starea este ${status}",
	jawsCommentKeyHint: "Puteţi apăsa Enter sau Space Bar pentru a vă deplasa la document pentru a vizualiza firul complet de comentarii şi a rezolva, a răspunde sau a şterge comentarii.",
	jawsMentionHint: "Widget de menţionare documente. Puteţi apăsa Săgeată în sus sau Săgeată în jos pentru a selecta un utilizator pentru a fi menţionat",
	jawsMentionSelected: "Apăsaţi Enter sau Space Bar pentru a menţiona",
	commentDeletedMsg: "Comentariul curent a fost şters de alt editor.",
	commentResolvedMsg: "Comentariul curent a fost rezolvat.",
	warningCommentMsg: "Comentariile făcute în Docs pentru fişiere ${0} sunt suportate doar online. Legarea la comentarii va fi înlăturată dacă este încărcată o nouă versiune pentru editare.",
	orphanCommentTip: "Legarea la comentarii a fost înlăturată în această versiune încărcată.",
	warningCommentName: "Avertisment"
})

