({
	ORIENTATION_LABEL: "Orientazioa",
	PORTRAIT: "Bertikala",
	LANDSCAPE: "Horizontala",
	PAGE_LABEL: "Orriaren ordena",
	PAGE_TYPE1: "Goitik behera, eta eskuina",
	PAGE_TYPE2: "Ezkerretik eskuinera, eta behera",
	DISPLAY_OPTION_LABEL: "Bistaratze-aukerak",
	HEADER: "Goiburua",
	FOOTER: "Orri-oina",
	GRIDLINE: "Sareta-marrak",
	TAGGED_PDF: "Etiketadun PDF",
	MARGINS_LABEL: "Marjinak",
	TOP: "Goikoa:",
	TOP_DESC:"Goiko marjina, zentimetrotan",
	TOP_DESC2:"Goiko marjina, hazbetetan",
	BOTTOM: "Behekoa:",
	BOTTOM_DESC:"Beheko marjina, zentimetrotan",
	BOTTOM_DESC2:"Beheko marjina, hazbetetan",	
	LEFT: "Ezkerrekoa:",
	LEFT_DESC:"Ezkerreko marjina, zentimetrotan",
	LEFT_DESC2:"Ezkerreko marjina, hazbetetan",	
	RIGHT: "Eskuinekoa:",
	RIGHT_DESC:"Eskuineko marjina, zentimetrotan",
	RIGHT_DESC2:"Eskuineko marjina, hazbetetan",	
	PAPER_FORMAT_LABEL: "Paperaren formatua",
	PAPER_SIZE_LABEL: "Paperaren tamaina:",
	HEIGHT: "Altuera:",
	HEIGHT_DESC:"Paperaren altuera, zentimetrotan",
	HEIGHT_DESC2:"Paperaren altuera, hazbetetan",		
	WIDTH: "Zabalera:",
	WIDTH_DESC:"Paperaren zabalera, zentimetrotan",
	WIDTH_DESC2:"Paperaren zabalera, hazbetetan",
	
	INVALID_MSG: "Sarrerak ez du balio eta automatikoki zuzendu da. Idatzi beste balio bat beste emaitza bat lortzeko.",
	
	TOOLTIP1:"Paperaren luzerak hartzen dituen beste errenkada inprimatzen du, orrian zutaberik ez dagoen arte mugituz, gero behera eta ezkerrera mugitzen da hurrengo errenkada-multzoa inprimatzeko.",
	TOOLTIP2:"Paperaren zabalerak hartzen dituen beste zutabe inprimatzen du, orrian errenkadarik ez dagoen arte mugituz, gero gora eta eskuinera mugitzen da hurrengo zutabe-multzoa inprimatzeko.",
	CM_LABEL: "cm",
	LETTER: "Gutuna",
	LEGAL: "Legala",
	TABLOID: "Tabloidea",
	USER: "Erabiltzailea",
	SIZE1: "Env. #6 3/4",
	SIZE2: "Env. Monarch",
	SIZE3: "Env. #9",
	SIZE4: "Env. #10",
	SIZE5: "Env. #11",
	SIZE6: "Env. #12",
	SIZE7: "16 kai",
	SIZE8: "32 kai",
	SIZE9: "32 kai handi"
})
	

