({	
	createTaskSummary: "${0} membuat tugas.",
	completeTaskSummary: "${0} menandai tugas sebagai selesai.",
	editTaskSummary5: "${0} mengedit ${1}, ${2}, ${3}, ${4} dan ${5} tugas.",
	editTaskSummary4: "${0} mengedit ${1}, ${2}, ${3} dan ${4} tugas.",
	editTaskSummary3: "${0} mengedit ${1}, ${2} dan ${3} tugas.",
	editTaskSummary2: "${0} mengedit ${1} dan ${2} tugas.",
	editTaskSummary1: "${0} mengedit ${1} tugas.",
	editTaskSummary0: "${0} mengedit tugas.",
	removeTaskSummary: "${0} menghapus.",
	reopenTaskSummary: "${0} membuka tugas kembali.",
	reassignTaskSummary: "${0} menugaskan ${1} kembali dari ${2} ke ${3}.",
	reassignTaskSummary2: "${0} menugaskan kembali orang yang ditugaskan dari ${1} ke ${2}, dan peninjau dari ${3} ke ${4}.",
	workPrivateSummary: "${0} mulai bekerja secara pribadi pada tugas ini.",
	approveTaskSummary: "${0} menyetujui.",
	rejectTaskSummary: "${0} menolak tugas ini.",
	rejectTaskSummary2: "${0} mengembalikan tugas ini ke ${1} untuk dikerjakan kembali.",
	submitTaskSummary: "${0} mengajukan pekerjaan pribadi kembali ke dokumen.",
	cancelPrivateSummary: "${0} membatalkan pekerjaan pribadi.",
	updatedFieldsDesc: "${0}: ${1} -> ${2}",
	fieldAssignee: "penerima tugas",
	fieldDuedate: "batas tanggal",
	fieldDescription: "deskripsi",
	fieldReviewer: "peninjau",
	fieldTitle: "judul",
	emptyFieldValue: "[Belum Ditugaskan]",
	errorAddMember:"Tidak ada akses ke server aktivitas untuk menambah penerima tugas atau peninjau. Coba lagi nanti.",
	errorCreateActivity:"Tidak ada akses ke server aktivitas untuk membuat aktivitas. Coba lagi nanti.",
	errorLoadActivity:"Tidak ada akses ke server aktivitas untuk memuat penugasan. Coba lagi nanti.",
	errorCreateAssignment: "Tidak ada akses ke server aktivitas untuk membuat penugasan. Coba lagi nanti.",
	errorDeleteAssignment: "Tidak ada akses ke server aktivitas untuk menghapus penugasan. Coba lagi nanti.",
	errorupdateAssignment: "Tidak ada akses ke server aktivitas untuk memperbarui penugasan. Coba lagi nanti.",
	errorSubmitAssignment: "Anda tidak dapat menampilkan tindakan ini. Periksa untuk melihat jika Anda memiliki izin untuk melakukannya.",	
	errorAddMember2:"Tidak ada akses ke server untuk menambahkan penerima tugas atau peninjau. Coba lagi nanti.",
	errorCreateActivity2:"Tidak ada akses ke server untuk membuat aktivitas. Coba lagi nanti.",
	errorLoadActivity2:"Tidak ada akses ke server untuk memuat penugasan. Coba lagi nanti.",
	errorCreateAssignment2: "Tidak ada akses ke server untuk membuat penugasan. Coba lagi nanti.",
	errorDeleteAssignment2: "Tidak ada akses ke server untuk menghapus penugasan. Coba lagi nanti.",
	errorupdateAssignment2: "Tidak ada akses ke server untuk memperbarui penugasan. Coba lagi nanti."	
})
