({
	alt			: "Texto alternativo",
	width		: "Anchura:",
	height		: "Altura:",
	cmUnit   : "cm",
	ptUnit 	 : "pt",
	inchUnit : "pulgada",
	inUnit   : "in",
	mmUnit 	 : "mm",
	
	inputWarning: "Especifique un número positivo con la unidad predeterminada. ",
	
	properties: "Propiedades",
	data: "Datos",
	chart: "Gráfico",
	axis: "Eje",
	series: "Series",
	font: "Font",
	title: "Título",
	legend: "Leyenda",
	placement: "Colocación",
	background: "Fondo",
	plotarea: "Área de trazo",
	line : "Línea",
	fill: "Relleno",
	border : "Borde",
	labelfont: "Etiqueta",
	scale: "Escala",
	minimum: "Mínimo",
	maximum: "Máximo",
	majorunit: "Unidad mayor",
	minorunit: "Unidad menor",
	smooth: "Fino",
	marker: "Marcadores",
	markerfill: "Marcador",
	enterTitle: "Especifique el título aquí",
	inputNumberWarning: "Especifique un número.",
	inputPosNumberWarning: "Especifique un número positivo.",
	maxMinWarning: "El valor máximo debe ser superior al valor mínimo",
	selectFontName: "Seleccionar nombre de font",
	selectFontSize: "Seleccionar tamaño de font",
	setBold: "Negrita",
	setItalic: "Cursiva",
	setFontColor: "Establecer color de fuente",
	setLegendPos: "Establecer colocación de la leyenda",
	setBackColor: "Establecer color de fondo del gráfico",
	setBorderWidth: "Establecer anchura de borde",
	setBorderColor: "Establecer color de borde",
	setPlotAreaColor: "Establecer color de área de trazo",
	selectAxis: "Seleccionar un eje",
	setLineWidth: "Establecer anchura de línea",
	setLineColor: "Establecer color de línea",
	selectSeries: "Seleccione una serie",
	setFillColor: "Establecer color de relleno",
	setMarker: "Establecer marcadores",
	setSmooth: "Establecer línea suave",
	chartTitle: "Título de gráfico",
	axisTitle: "Título de eje",
	
	ERR1: "Una matriz debe estar delimitada por llaves.",
	ERR3: "Los elementos de serie deben estar entre comillas.",
	ERR4: "Especifique sólo un rango.",
	ERR5: "El rango debe existir.",
	ERR6: "Todos los rangos deben estar en la misma hoja.",
	ERR7: "Todos los rangos deben ser para una sola fila o columna.",
	ERR9: "Es necesario especificar un valor de serie.",
	
	n	: "Ninguna",
	l	: "Izquierda",
	r	: "Derecha",
	t	: "Arriba",
	b   : "Abajo",
	
	dataSeries:"Serie de datos",
	label:"Nombre de serie",
	xVal:"Valores X de serie",
	yVal:"Valores Y de serie",
	val:"Valores de serie",
	cat:"Categoría",
		
	ltr: "De izquierda a derecha",
	rtl: "De derecha a izquierda",
	auto: "Contextual",
	bidi_dir: "Dirección",
	bidi_text_dir: "Dirección del texto"
})
