/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */


define({
        saveTip: "‏حفظ‏",
        undoTip: "تراجع",
        redoTip: "‏اعادة‏",
        formatPainterTip: "نسخ التنسيق",
        showSorterTip: "عرض فارز الشرائح",
        hideSorterTip: "اخفاء فارز الشرائح ",
        webClipboardTip: "مسودة الانترنت",
        spellCheckTip: "تشغيل فحص الهجاء اليدوي",
        createSectionTip: "تخصيص قسم",
        createCellsTip: "تخصيص الخانات",
        createSlideTip: "تخصيص الشرائح",
        submitTip: "احالة التخصيص",
        addCommentTip: "اضافة تعقيب",
        removeFormatTip: "ازالة التنسيق",
        sortAscTip: "‏فرز تصاعدي‏",
        sortDescTip: "‏فرز تنازلي‏",
        instantFilterTip: "ترشيح البيانات الفوري",
        insertChartTip: "ادراج مخطط بياني",
        startAutofillTip: "ملء آلي",
        dataValidationTip: "التحقق من صلاحية البيانات",

        selectFontTip: "تحديد طاقم الطباعة",
        selectFontSizeTip: "تحديد حجم الخط",
        selectFontNameTip: "تحديد اسم طاقم الطباعة",
        FontName: "اسم طاقم الطباعة",
        FontSize: "حجم طاقم الطباعة",
        increaseFontSizeTip: "تكبير حجم الخط",
        decreaseFontSizeTip: "تصغير حجم الخط",
        boldTip: "عريض",
        italicTip: "مائل",
        underlineTip: "تسطير",
        strikeThroughTip: "يتوسطه خط",
        setFontColorTip: "تحديد لون طاقم الطباعة",
        setShadingColorTip: "تحديد لون التظليل",
        setBackgroundFill: "تحديد ملء الخلفية",
        setBgColorTip: "تحديد لون الخلفية",
        setBorderTip: "تحديد لون ونمط الحدود",
        setBorderColorTip: "تحديد لون الحدود",
        setHighlightColor: "تحديد لون الاظهار",
        formatPainter: "نسخ التنسيق",
        //	clearFormat:"Remove Formatting",
        zoom: "تكبير/تصغير",
        selectStyleTip: "تحديد الأسلوب",
        styles: "الأسلوب",
        formatAsCurrencyTip: "التنسيق كعملة",
        formatAsPercentTip: "التنسيق كنسبة مئوية",
        decreaseDecimalTip: "تقليل الأماكن العشرية",
        increaseDecimalTip: "زيادة الأماكن العشرية",
        formatNumberTip: "تنسيق العدد",

        numberedListTip: "اضافة ترقيم أو تغيير أسلوب الترقيم",
        bulletedListTip: "اضافة تعداد نقطي أو تغيير أسلوب التعداد النقطة",
        multilevelListTip: "اضافة أو تغيير كشف متعدد المستويات",
        indentTip: "زيادة الازاحة للداخل",
        decreaseIndentTip: "تقليل الازاحة للداخل",
        alignTip: "محاذاة",
        leftAlignTip: "محاذاة الى اليسار",
        centerTip: "محاذاة في الوسط",
        rightAlignTip: "محاذاة الى اليمين",
        justifyTip: "ضبط",
        bottomBorderTip: "المساحة السفلية للحدود",
        borderTypes: "أنواع الحدود",
        borderTip: "تحديد شكل الحدود",
        topAlignTip: "محاذاة بأعلى",
        middleAlignTip: "محاذاة بالوسط",
        bottomAlignTip: "محاذاة لأسفل",
        lineSpacingTip: "تباعد الأسطر",
        mergeSplitCellTip: "دمج أو تقسيم الخانات",
        wrapNoWrapTip: "تشغيل أو تعطيل الالتفاف",
        ltrDirectionTip: "التغيير الى نص من اليسار الى اليمين",
        rtlDirectionTip: "التغيير الى نص من اليمين الى اليسار",
        autoDirectionTip: "تغيير اتجاه النص",
        toggleSheetDirectionTip: "تغيير اتجاه الجدول",
        setSheetDirectionLTR: "يسار الى يمين",
        setSheetDirectionRTL: "يمين الى يسار",

        addTableTip: "اضافة جدول",
        insertOrMoveRowTip: "ادراج أو نقل صف",
        insertOrMoveColTip: "ادراج أو نقل عمود",
        insertOrDeleteRowTip: "ادراج أو حذف صف",
        insertOrDeleteColTip: "ادراج أو حذف عمود",
        insertFunctionTip: "ادراج وظيفة",
        insertImage: "ادراج صورة",
        resizeCol: "تغيير حجم العمود",
        resizeCols: "تغيير حجم الأعمدة",
        addLink: "اضافة أو تحرير وصلة",
        tableStyle: "أنماط الجدول",

        selectBorder_BottomBorder: "الحدود السفلية",
        selectBorder_TopBorder: "الحدود العليا",
        selectBorder_LeftBorder: "حدود اليسار",
        selectBorder_RightBorder: "حدود اليمين",
        selectBorder_NoBorder: "بدون أسطر",
        selectBorder_AllBorders: "كل الحدود",

        insertOrMoveRow_InsertAbove: "ادراج صف لأعلى",
        insertOrMoveRow_InsertBelow: "ادراج صف لأسفل",
        insertOrMoveRow_MoveUp: "نقل الصف لأعلى",
        insertOrMoveRow_MoveDown: "نقل الصف لأسفل",
        insertOrMoveCol_InsertLeft: "ادراج عمود قبل",
        insertOrMoveCol_InsertRight: "ادراج عمود بعد",
        insertOrMoveCol_InsertBefore: "ادراج عمود قبل",
        insertOrMoveCol_InsertAfter: "ادراج عمود بعد",
        insertOrMoveCol_MoveLeft: "نقل العمود الى اليسار",
        insertOrMoveCol_MoveRight: "نقل العمود الى اليمين",

        insertOrDelete_Delete: "حذف",

        combineButtonReadTip: "اضغط على مفتاح السهم لأسفل لتفعيل القائمة، ثم تجول بمفاتيح الاسهم",

        lineSpacing_1: "1",
        lineSpacing_12: "1.2",
        lineSpacing_15: "1.5",
        lineSpacing_2: "2",
        lineSpacing_25: "2.5",
        lineSpacing_3: "3",

        percent: "%",
        font_arial: "Arial",

        fontSize: "${0}pt",

        slides: "شريحة واحدة لكل صفحة",
        slidesWithNotes: "الشرائح مع ملاحظات",
        preparingSlides: "تحضير الشرائح الخاصة بك للطباعة...",
        printLayoutOptionLabel: "طباعة اختيارات الشكل العام",

        targetRemovedWhenDialogOpen: "لا يمكن اتمام هذا الاختيار حيث تم ازالة الهدف بواسطة محرر مشترك أخر.",

        NUMBER: "رقم",
        CURRENCY: "العملة",
        PERCENT: "نسبة",
        DATE: "التاريخ",
        TIME: "وقت",
        DATETIME: "تاريخ/وقت",
        MORECURRENCY: "مزيد من العملات بالوحدة النقدية",
        MORECURRENCYCODE: "مزيد من العملات بكود العملة",
        MOREDATE: "مزيد من تنسيقات التاريخ والوقت",
        TEXT: "نص",
	
        // currency, by currency code
        // NOTE: MUST keep it in order
        CURRENCY_CODE: {
            AED: "الامارات العربية المتحدة (الدرهم)",
            ARS: "الأرجنتين (بيزو)",
            AUD: "أستراليا (دولار)",
            BGN: "بلغاريا (ليفا)",
            BOB: "بوليفيا (بوليفيانوس)",
            BRL: "البرازيل (الريال)",
            CAD: "كندا (دولار)",
            CHF: "سويسرا (فرنك)",
            CLP: "تشيلي (بيزو)",
            CNY: "الصين (يوان صيني)",
            COP: "كولومبيا (بيزو)",
            CRC: "كوستاريكا (كولون)",
            CZK: "جمهورية التشيك (كرونة)",
            DKK: "الدنمارك (كرونة)",
            DOP: "جمهورية الدومنيكان (بيزو)",
            EGP: "مصر (الجنيه)",
            EUR: "النمسا، بلجيكا، فنلندا، فرنسا، ...، سلوفينية، اسبانيا (اليورو)",
            GBP: "انجلترا، المملكة المتحدة (جنيه)",
            HKD: "هونج كونج (دولار)",
            HRK: "كرواتيا (كونا)",
            HUF: "المجر (فورينت)",
            IDR: "اندونيسيا (روبية)",
            ILS: "اسرائيل (شيكل جديد)",
            INR: "الهند (روبية)",
            JPY: "اليابان (الين)",
            KRW: "كوريا الجنوبية (وون)",
            KZT: "كازخستان (Tenges)",
            MAD: "المغرب (الدرهم)",
            MXN: "المكسيك (بيزو)",
            MYR: "ماليزيا (رنقت)",
            NOK: "النرويج (كرون)",
            NZD: "نيوزيلندا (دولار)",
            PAB: "بنما (بالبوا)",
            PEN: "بيرو (سول الجديد)",
            PHP: "الفلبين (بيزو)",
            PKR: "باكستان (روبية)",
            PLN: "بولندا (زلوتى)",
            PYG: "باراغواي (جواراني)",
            RON: "رومانيا (لى جديد)",
            RSD: "الصربية (السيريلية)، الصربية (اللاتينية)",
            RUB: "روسيا (روبل)",
            SAR: "المملكة العربية السعودية (بالريال)",
            SEK: "السويد (كرونا)",
            SGD: "سنغافورة (دولار)",
            SVC: "السلفادور (كولون)",
            THB: "تايلاند (باهت)",
            TRY: "تركيا (ليرة)",
            TWD: "تايوان (دولار جديد)",
            USD: "الاكوادور، بورتوريكو، الولايات المتحدة الأمريكية (بالدولار الأمريكي)",
            UYU: "أوروجواي (بيزو)",
            VEF: "فنزويلا (بوليفار فويرتس)",
            VND: "فيتنام (دونج)",
            ZAR: "جنوب أفريقيا (راند)"
        },
        // for border toolbar
        allBorders: "كل الحدود",
        innerBorders: "حدود داخلية",
        horizontalBorders: "حدود أفقية",
        verticalBorders: "حدود رأسية",
        outerBorders: "حدود خارجية",
        borderColor: "لون الحدود",
        leftBorder: "حدود اليسار",
        topBorder: "الحدود العلوية",
        rightBorder: "حدود اليمين",
        bottomBorder: "الحدود السفلية",
        clearBorders: "بلا حدود",
        BorderStyle_ThinSolid: "رفيع مصمت",
        BorderStyle_ThinDotted: "رفيع منقط",
        BorderStyle_ThinDashed: "رفيع متقطع",
        BorderStyle_ThickSolid: "سميك مصمت",
        BorderStyle_ThickDotted: "سميك منقط",
        BorderStyle_ThickDashed: "سميك متقطع"
})

