define({      
//begin v1.x content
	"clearFilterDialogTitle": "Garbitu iragazkia",
	"filterDefDialogTitle": "Iragazkia",
	"defaultRuleTitle": "Araua",
	"ruleTitleTemplate": "${ruleNumber} araua",
	"noFilterApplied": "Ez da iragazkirik erabili.",
	"defineFilter": "Definitu iragazkia",
	"conditionEqual": "honen berdina:",
	"conditionNotEqual": "ez da honen berdina:",
	"conditionLess": "hau baino txikiagoa:",
	"conditionLessEqual": "hau baino txikiagoa edo berdina:",
	"conditionGreater": "hau baino handiagoa:",
	"conditionGreaterEqual": "hau baino handiagoa edo berdina:",
	"conditionContain": "hau dauka:",
	"conditionIs": "hau da:",
	"conditionStartWith": "honekin hasten da:",
	"conditionEndWith": "honekin bukatzen da:",
	"conditionNotContain": "hau ez dauka:",
	"conditionIsNot": "hau ez da:",
	"conditionNotStartWith": "ez da honekin hasten:",
	"conditionNotEndWith": "ez da honekin bukatzen:",
	"conditionBefore": "hau baino lehenago:",
	"conditionAfter": "hau baino atzerago:",
	"conditionRange": "tartea",
	"conditionIsEmpty": "hutsik dago",
	"all": "denak",
	"any": "edozein",
	"relationAll": "arau guztiak",
	"waiRelAll": "Ondorengo arau guztiak bete:",
	"relationAny": "edozein arau",
	"waiRelAny": "Ondorengo edozein arau bete:",
	"relationMsgFront": "Bete",
	"relationMsgTail": "",
	"and": "eta",
	"or": "edo",
	"addRuleButton": "Gehitu araua",
	"waiAddRuleButton": "Gehitu arau berria",
	"removeRuleButton": "Dendu araua",
	"waiRemoveRuleButtonTemplate": "Kendu ${0} araua",
	"addRuleButton": "Gehitu iragazkiaren araua",
	"cancelButton": "Utzi",
	"waiCancelButton": "Utzi elkarrizketa koadro hau",
	"clearButton": "Garbitu",
	"waiClearButton": "Garbitu iragazkia",
	"filterButton": "Iragazkia",
	"waiFilterButton": "Bidali iragazkia",
	"columnSelectLabel": "Zutabea:",
	"waiColumnSelectTemplate": "${0} arauaren zutabea",
	"conditionSelectLabel": "Baldintza:",
	"waiConditionSelectTemplate": "${0} arauaren baldintza",
	"valueBoxLabel": "Balioa:",
	"waiValueBoxTemplate": "Sartu ${0} arauaren bidez iragazteko balioa",
	"rangeTo": "honetara:",
	"rangeTemplate": "honetatik: ${0} honetara: ${1}",
	"statusTipHeaderColumn": "Zutabea",
	"statusTipHeaderCondition": "Arauak",
	"statusTipTitle": "Iragazkiaren barra",
	"statusTipMsg": "Egin klik hemen, iragazkiaren barran, honen balioak iragazteko: ${0}",
	"anycolumn": "edozein zutabe",
	"statusTipTitleNoFilter": "Iragazkiaren barra",
	"statusTipTitleHasFilter": "Iragazkia",
	"statusTipRelPre": "Bete",
	"statusTipRelPost": "araua.",
	"statusTipHeaderAll": "Bete arau guztiak.",
	"statusTipHeaderAny": "Bete edozein arau.",
	"defaultItemsName": "elementuak",
	"filterBarMsgHasFilterTemplate": "${1} ${2}(e)tik ${0} erakusten dira.",
	"filterBarMsgNoFilterTemplate": "Ez da iragazkirik erabili.",
	"filterBarDefButton": "Definitu iragazkia",
	"waiFilterBarDefButton": "Iragazi taula",
	"a11yFilterBarDefButton": "Iragazi...",
	"filterBarClearButton": "Garbitu iragazkia",
	"waiFilterBarClearButton": "Garbitu iragazkia",
	"closeFilterBarBtn": "Itxi iragazkiaren barra",
	"clearFilterMsg": "Honek iragazkia kenduko du eta erregistro eskuragarri guztiak erakutsiko ditu.",
	"anyColumnOption": "Edozein zutabe",
	"trueLabel": "Zuzena",
	"falseLabel": "Okerra",
	"radioTrueLabel": "Balio zuzena",
	"radioFalseLabel": "Balio okerra",
	"beginTimeRangeLabel": "Denbora tartearen balioaren hasiera",
	"endTimeRangeLabel": "Denbora tartearen balioaren bukaera",
	"beginDateRangeLabel": "Data tartearen balioaren hasiera",
	"endDateRangeLabel": "Data tartearen balioaren bukaera",
	"startsWithExpr": "${0}*"
//end v1.x content
});

