({
	ORIENTATION_LABEL: "方向",
	PORTRAIT: "直印",
	LANDSCAPE: "橫印",
	HEADER: "頁首",
	FOOTER: "頁尾",
	MARGINS_LABEL: "邊距",
	TOP: "上：",
	BOTTOM: "下：",
	LEFT: "左：",
	RIGHT: "右：",
	PAPER_FORMAT_LABEL: "紙張格式",
	PAPER_SIZE_LABEL: "紙張大小：",
	HEIGHT: "高度：",
	WIDTH: "寬度：",
	HEIGHT_DESC:"紙張高度（以公分為單位）",
	HEIGHT_DESC2:"紙張高度（以英寸為單位）",
	WIDTH_DESC:"紙張寬度（以公分為單位）",
	WIDTH_DESC2:"紙張寬度（以英寸為單位）",
	BOTTOM_DESC:"下邊距（以公分為單位）",
	BOTTOM_DESC2:"下邊距（以英寸為單位）",
	TOP_DESC:"上邊距（以公分為單位）",
	TOP_DESC2:"上邊距（以英寸為單位）",
	LEFT_DESC:"左邊距（以公分為單位）",
	LEFT_DESC2:"左邊距（以英寸為單位）",
	RIGHT_DESC:"右邊距（以公分為單位）",
	RIGHT_DESC2:"右邊距（以英寸為單位）",
	CM_LABEL: "公分",
	LETTER: "信紙",
	LEGAL: "法規紙",
	TABLOID: "小報",
	USER: "使用者",
	SIZE1: "Env. #6 3/4",
	SIZE2: "Env. Monarch",
	SIZE3: "Env. #9",
	SIZE4: "Env. #10",
	SIZE5: "Env. #11",
	SIZE6: "Env. #12",
	SIZE7: "16 開",
	SIZE8: "32 開",
	SIZE9: "32 大開",
	INVALID_MSG: "輸入無效，已自動更正。若要有不同的結果，請嘗試輸入其他值。"
})
	

