({
	ORIENTATION_LABEL: "Orientação",
	PORTRAIT: "Vertical",
	LANDSCAPE: "Horizontal",
	HEADER: "Cabeçalho",
	FOOTER: "Rodapé",
	MARGINS_LABEL: "Margens",
	TOP: "Superior:",
	BOTTOM: "Inferior:",
	LEFT: "Esquerda:",
	RIGHT: "Direita:",
	PAPER_FORMAT_LABEL: "Formato do papel",
	PAPER_SIZE_LABEL: "Tamanho do papel:",
	HEIGHT: "Altura:",
	WIDTH: "Largura:",
	HEIGHT_DESC:"Altura do papel, em centímetros",
	HEIGHT_DESC2:"Altura do papel, em polegadas",
	WIDTH_DESC:"Largura do papel, em centímetros",
	WIDTH_DESC2:"Largura do papel, em polegadas",
	BOTTOM_DESC:"Margem inferior, em centímetros",
	BOTTOM_DESC2:"Margem inferior, em polegadas",
	TOP_DESC:"Margem superior, em centímetros",
	TOP_DESC2:"Margem superior, em polegadas",
	LEFT_DESC:"Margem esquerda, em centímetros",
	LEFT_DESC2:"Margem esquerda, em polegadas",
	RIGHT_DESC:"Margem direita, em centímetros",
	RIGHT_DESC2:"Margem direita, em polegadas",
	CM_LABEL: "cm",
	LETTER: "Carta",
	LEGAL: "Legal",
	TABLOID: "Tablóide",
	USER: "Utilizador",
	SIZE1: "Env. #6 3/4",
	SIZE2: "Env. Monarch",
	SIZE3: "Env. #9",
	SIZE4: "Env. #10",
	SIZE5: "Env. #11",
	SIZE6: "Env. #12",
	SIZE7: "16 kai",
	SIZE8: "32 kai",
	SIZE9: "32 kai grande",
	INVALID_MSG: "A entrada de dados não é válida e foi rectificada automaticamente. Experimente outro valor, caso pretende um resultado diferente."
})
	

