/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */


define({
        saveTip: "Записване",
        undoTip: "Отказ",
        redoTip: "Връщане",
        formatPainterTip: "Копиране на форматиране",
        showSorterTip: "Показване на подреждане на слайдове",
        hideSorterTip: "Скриване на Сортиране на слайдове",
        webClipboardTip: "Уеб буферна памет",
        spellCheckTip: "Стартиране на ръчна проверка на правописа",
        createSectionTip: "Добавяне на раздел",
        createCellsTip: "Задаване на клетки",
        createSlideTip: "Задаване на слайдове",
        submitTip: "Подаване на задание",
        addCommentTip: "Добавяне на коментар",
        removeFormatTip: "Премахване на форматиране",
        sortAscTip: "Възходящо сортиране",
        sortDescTip: "Низходящо сортиране",
        instantFilterTip: "Мигновен филтър",
        insertChartTip: "Вмъкване на диаграма",
        startAutofillTip: "Автоматично попълване",
        dataValidationTip: "Валидиране на данни",

        selectFontTip: "Избиране на шрифт",
        selectFontSizeTip: "Избиране на размер на шрифт",
        selectFontNameTip: "Избиране на име на шрифт",
        FontName: "Име на шрифт",
        FontSize: "Размер на шрифт",
        increaseFontSizeTip: "Увеличаване на шрифт",
        decreaseFontSizeTip: "Намаляване на шрифт",
        boldTip: "Получер",
        italicTip: "Курсив",
        underlineTip: "Подчертаване",
        strikeThroughTip: "Зачеркване",
        setFontColorTip: "Задаване на цвят на шрифт",
        setShadingColorTip: "Задаване на цвят за оцветяване",
        setBackgroundFill: "Задаване на фоново запълване",
        setBgColorTip: "Задаване на цвят на фон",
        setBorderTip: "Задаване на стил и цвят на граница",
        setBorderColorTip: "Задаване на цвят на граница",
        setHighlightColor: "Задаване на цвят за осветяване",
        formatPainter: "Копиране на форматиране",
        //	clearFormat:"Remove Formatting",
        zoom: "Мащабиране",
        selectStyleTip: "Избор на стил",
        styles: "Стил",
        formatAsCurrencyTip: "Форматиране като валута",
        formatAsPercentTip: "Форматиране като процент",
        decreaseDecimalTip: "Намаляване на десетичните позиции",
        increaseDecimalTip: "Увеличаване на десетичните позиции",
        formatNumberTip: "Форматиране на число",

        numberedListTip: "Добавяне на номериране или промяна на стил на номериране",
        bulletedListTip: "Добавяне на водещи символи или промяна на стил на водещ символ",
        multilevelListTip: "Добавяне или промяна на списък с много нива",
        indentTip: "Увеличи отстъп",
        decreaseIndentTip: "Намали отстъп",
        alignTip: "Подравняване",
        leftAlignTip: "Подравняване наляво",
        centerTip: "Подравняване в център",
        rightAlignTip: "Подравняване надясно",
        justifyTip: "Двустранно",
        bottomBorderTip: "Долна част на границата",
        borderTypes: "Типове граници",
        borderTip: "Задаване на стил за границата",
        topAlignTip: "Подравняване отгоре",
        middleAlignTip: "Подравняване по средата",
        bottomAlignTip: "Подравняване в долна част",
        lineSpacingTip: "Редова разредка",
        mergeSplitCellTip: "Обединяване или разделяне на клетки",
        wrapNoWrapTip: "Пренасяне на нов ред включено или изключено",
        ltrDirectionTip: "Промяна до текст от ляво надясно",
        rtlDirectionTip: "Промяна до текст от дясно наляво",
        autoDirectionTip: "Промяна на посока на текст",
        toggleSheetDirectionTip: "Промяна на посока на лист",
        setSheetDirectionLTR: "От ляво надясно",
        setSheetDirectionRTL: "От дясно наляво",

        addTableTip: "Добавяне на таблица",
        insertOrMoveRowTip: "Вмъкване или преместване на ред",
        insertOrMoveColTip: "Вмъкване или преместване на колона",
        insertOrDeleteRowTip: "Вмъкване или изтриване на ред",
        insertOrDeleteColTip: "Вмъкване или изтриване на колона",
        insertFunctionTip: "Вмъкване на функция",
        insertImage: "Вмъкване на изображение",
        resizeCol: "Преоразмеряване на колона",
        resizeCols: "Преоразмеряване на колони",
        addLink: "Добавяне или редактиране на връзка",
        tableStyle: "Стилове на таблица",

        selectBorder_BottomBorder: "Долна граница",
        selectBorder_TopBorder: "Горна граница",
        selectBorder_LeftBorder: "Лява граница",
        selectBorder_RightBorder: "Дясна граница",
        selectBorder_NoBorder: "Без линии",
        selectBorder_AllBorders: "Всички граници",

        insertOrMoveRow_InsertAbove: "Вмъкване на ред отгоре",
        insertOrMoveRow_InsertBelow: "Вмъкване на ред отдолу",
        insertOrMoveRow_MoveUp: "Преместване на ред нагоре",
        insertOrMoveRow_MoveDown: "Преместване на ред надолу",
        insertOrMoveCol_InsertLeft: "Вмъкване на колона преди",
        insertOrMoveCol_InsertRight: "Вмъкване на колона след",
        insertOrMoveCol_InsertBefore: "Вмъкване на колона преди",
        insertOrMoveCol_InsertAfter: "Вмъкване на колона след",
        insertOrMoveCol_MoveLeft: "Преместване на колона наляво",
        insertOrMoveCol_MoveRight: "Преместване на колона надясно",

        insertOrDelete_Delete: "Изтриване",

        combineButtonReadTip: "Натиснете клавиш Стрелка надолу, за да активирате менюто, след което навигирайте със стрелките",

        lineSpacing_1: "1",
        lineSpacing_12: "1.2",
        lineSpacing_15: "1.5",
        lineSpacing_2: "2",
        lineSpacing_25: "2.5",
        lineSpacing_3: "3",

        percent: "%",
        font_arial: "Arial",

        fontSize: "${0}pt",

        slides: "Един слайд на страница",
        slidesWithNotes: "Слайдове с бележки",
        preparingSlides: "Подготвяне на Вашите слайдове за отпечатване...",
        printLayoutOptionLabel: "Опции на оформление за печат",

        targetRemovedWhenDialogOpen: "Това действие не може да се завърши, защото приемникът е премахнат от друг съвместен редактор.",

        NUMBER: "Номер",
        CURRENCY: "Валута",
        PERCENT: "Процент",
        DATE: "Дата",
        TIME: "Час",
        DATETIME: "ДатаЧас",
        MORECURRENCY: "Още валути по парична единица",
        MORECURRENCYCODE: "Още валути по валутен код",
        MOREDATE: "Още формати за време и дата",
        TEXT: "Текст",
	
        // currency, by currency code
        // NOTE: MUST keep it in order
        CURRENCY_CODE: {
            AED: "Обединените арабски емирства (дирхам)",
            ARS: "Аржентина (песо)",
            AUD: "Австралия (долари)",
            BGN: "България (лева)",
            BOB: "Боливия (боливиано)",
            BRL: "Бразилия (реал)",
            CAD: "Канада (долари)",
            CHF: "Швейцария (франк)",
            CLP: "Чили (песо)",
            CNY: "Китай (юан)",
            COP: "Колумбия (песо)",
            CRC: "Коста Рика (колон)",
            CZK: "Чешка Република (крона)",
            DKK: "Дания (крона)",
            DOP: "Доминиканска Република (песо)",
            EGP: "Египет (лира)",
            EUR: "Австрия, Белгия, Финландия, Франция,  ..., Словения, Испания (евро)",
            GBP: "Англия, Обединено кралство (паунд)",
            HKD: "Хонконг (долари)",
            HRK: "Хърватия (куна)",
            HUF: "Унгария (флоринт)",
            IDR: "Индонезия (рупия)",
            ILS: "Израел (нов шекел)",
            INR: "Индия (рупия)",
            JPY: "Япония (йена)",
            KRW: "Южна Корея (вон)",
            KZT: "Казахстан (тенге)",
            MAD: "Мароко (дирхам)",
            MXN: "Мексико (песо)",
            MYR: "Малайзия (рингит)",
            NOK: "Норвегия (крона)",
            NZD: "Нова Зеландия (долари)",
            PAB: "Панама (балбоа)",
            PEN: "Перу (нов сол)",
            PHP: "Филипини (песо)",
            PKR: "Пакистан (рупия)",
            PLN: "Полша (злота)",
            PYG: "Парагвай (гуарани)",
            RON: "Румъния (нова лея)",
            RSD: "Сръбски (кирилица), Сръбски (латински)",
            RUB: "Руска Федерация (рубла)",
            SAR: "Саудитска Арабия (риал)",
            SEK: "Швеция (крона)",
            SGD: "Сингапур (долари)",
            SVC: "Ел Салвадор (колон)",
            THB: "Тайланд (бат)",
            TRY: "Турция (лира)",
            TWD: "Тайван (нов долар)",
            USD: "Еквадор, Пуерто Рико, САЩ (щатски долар)",
            UYU: "Уругвай (песо)",
            VEF: "Венецуела (боливар)",
            VND: "Виетнам (донг)",
            ZAR: "Южна Африка (ранд)"
        },
        // for border toolbar
        allBorders: "Всички граници",
        innerBorders: "Вътрешни граници",
        horizontalBorders: "Хоризонтални граници",
        verticalBorders: "Вертикални граници",
        outerBorders: "Външни граници",
        borderColor: "Цвят на граница",
        leftBorder: "Лява граница",
        topBorder: "Горна граница",
        rightBorder: "Дясна граница",
        bottomBorder: "Долна граница",
        clearBorders: "Без граници",
        BorderStyle_ThinSolid: "Тънка плътна",
        BorderStyle_ThinDotted: "Тънка пунктирана",
        BorderStyle_ThinDashed: "Тънка прекъсната",
        BorderStyle_ThickSolid: "Дебела плътна",
        BorderStyle_ThickDotted: "Дебела пунктирана",
        BorderStyle_ThickDashed: "Дебела прекъсната"
})

