/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

({
    Arrow01_Gray: "Panah 01 Abu-abu",
    Arrow02_Gray: "Panah 02 Abu-abu",
    Arrow03_Red: "Panah 03 Merah",
    Arrow04_Blue: "Panah 04 Biru",
    Arrow05_Blue: "Panah 05 Biru",
    Arrow06_Yellow: "Panah 06 Kuning",
    Arrow07_Red: "Panah 07 Merah",
    Arrow08_Gray: "Panah 08 Abu-abu",
    Arrow09_Orange: "Panah 09 Oranye",
    Arrow10_Blue: "Panah 10 Biru",
    Arrow11_Blue: "Panah 11 Biru",
    Arrow12_Green: "Panah 12 Hijau",
    Arrow13_Blue: "Panah 13 Biru",
    Arrow14_Green: "Panah 14 Hijau",
    Arrow15_Orange: "Panah 15 Oranye",
    Arrow16_Gray: "Panah 16 Abu-abu",
    CircleArrow01_Green: "Panah Lingkaran 01 Hijau",
    CircleArrow02_Multi: "Panah Lingkaran 02 Multi",
    CircleArrow03_Multi: "Panah Lingkaran 03 Multi",
    CircleArrow04_Multi: "Panah Lingkaran 04 Multi",
    CircleArrow05_Multi: "Panah Lingkaran 05 Multi",
    CircleArrow06_Multi: "Panah Lingkaran 06 Multi",
    CircleArrow07_Blue: "Panah Linkaran 07 Biru",
    CircleArrow08_Green: "Panah Lingkaran 08 Hijau",
    CircleArrow09_Multi: "Panah Lingkaran 09 Multi",
    CurvedArrow01_Gray: "Panah Kurva 01 Abu-abu",
    CurvedArrow02_Blue: "Panah Kurva 02 Biru",
    CurvedArrow03_Blue: "Panah Kurva 03 Biru",
    CurvedArrow04_Orange: "Panah Kurva 04 Oranye",
    CurvedArrow05_Red: "Panah Kurva 05 Merah",
    CurvedArrow06_Blue: "Panah Kurva 06 Biru",
    CurvedArrow07_Purple: "Panah Kurva 07 Ungu",
    CurvedArrow08_Green: "Panah Kurva 08 Hijau",
    CurvedArrow09_Gray: "Panah Kurva 09 Abu-abu",
    CurvedArrow10_Blue: "Panah Kurva 10 Biru",
    CurvedArrow11_Orange: "Panah Kurva 11 Oranye",
    CurvedArrow12_Blue: "Panah Kurva 12 Biru",
    CurvedArrow13_Green: "Panah Kurva 13 Hijau",
    CurvedArrow14_Brown: "Panah Kurva 14 Coklat",
    CurvedArrow15_Blue: "Panah Kurva 15 Biru",
    CurvedArrow16_Gray: "Panah Kurva 16 Abu-abu",
    CurvedArrow17_Gray: "Panah Kurva 17 Abu-abu",
    CurvedArrow18_Gray: "Panah Kurva 18 Abu-abu",
    CurvedArrow19_Gray: "Panah Kurva 19 Abu-abu",
    CurvedArrow20_Gray: "Panah Kurva 20 Abu-abu",
    TrendArrow01_Red: "Panah Trend 01 Merah",
    TrendArrow02_Green: "Panah Trend 02 Hijau",
    TrendArrow03_Orange: "Panah Trend 03 Oranye",
    TrendArrow04_Red: "Panah Trend 04 Merah",
    TrendArrow05_Orange: "Panah Trend 05 Oranye",
    TrendArrow06_Blue: "Panah Trend 06 Biru",
    TrendArrow07_Orange: "Panah Trend 07 Oranye",
    TrendArrow08_Yellow: "Panah Trend 08 Kuning",
    TrendArrow09_Blue: "Panah Trend 09 Biru",
    TrendArrow10_Blue: "Panah Trend 10 Biru",
    TrendArrow11_Blue: "Panah Trend 11 Biru",
    TrendArrow12_Blue: "Panah Trend 12 Biru",
    TrendArrow13_Red: "Panah Trend 13 Merah",
    TrendArrow14_Multi: "Panah Trend 14 Multi",
    TrendArrow15_Blue: "Panah Trend 15 Biru",
    Bullet01_Circle_DarkRed: "Poin 01 Lingkaran Merah Tua",
    Bullet02_Circle_Blue: "Poin 02 Lingkaran Biru",
    Bullet03_Circle_Green: "Poin 03 Lingkaran Hijau",
    Bullet04_Square_Black: "Poin 04 Persegi Hitam",
    Bullet05_Square_Orange: "Poin 05 Persegi Oranye",
    Bullet06_Square_Purple: "Poin 06 Persegi Ungu",
    Bullet07_Diamond_Blue: "Poin 07 Wajik Biru",
    Bullet08_Diamond_LightBlue: "Poin 08 Wajik Biru Muda",
    Bullet09_Diamond_Red: "Poin 09 Wajib Merah",
    Bullet10_Star_Yellow: "Poin 10 Bintang Kuning",
    Bullet11_Star_Blue: "Poin 11 Bintang Biru",
    Bullet12_Triangle_Blue: "Poin 12 Segitiga Biru",
    Bullet13_Triangle_DarkGreen: "Poin 13 Segitiga Hijau Tua",
    Bullet14_Arrow_Red: "Poin 14 Panah Merah",
    Bullet15_Arrow_Blue: "Poin 15 Panah Biru",
    Bullet16_Box_Blue: "Poin 16 Kotak Biru",
    Bullet17_Box_Red: "Poin 17 Kotak Merah",
    Bullet18_Asterisk_LightBlue: "Poin 18 Asterik Biru Muda",
    Bullet19_Leaves_Red: "Poin 19 Daun Merah",
    Bullet20_Target_Blue: "Poin 20 Sasaran Biru",
    Bullet21_Arrow_Blue: "Poin 21 Panah Biru",
    Bullet22_Arrow_DarkBlue: "Poin 22 Panah Biru Tua",
    Bullet23_Arrow_Brown: "Poin 23 Panah Coklat",
    Bullet24_Flag_Red: "Poin 24 Bendera Merah",
    Bullet25_Flag_Green: "Poin 25 Bendera Hijau",
    Bullet26_X_Red: "Poin 26 X Merah",
    Bullet27_X_Black: "Poin 27 X Hitam",
    Bullet28_Checkmark_Green: "Poin 28 Tanda Centang Hijau",
    Bullet29_Checkmark_Blue: "Poin 29 Tanda Centang Biru",
    Bullet30_Square_DarkRed: "Poin 30 Persegi Merah Tua",
    camera: "Kamera",
    computer1: "Komputer 1",
    computer2: "Komputer 2",
    computer3: "Komputer 3",
    Computer_Cloud: "Komputer Awan",
    Computer_Desktop: "Komputer Desktop",
    Computer_Laptop_Black: "Komputer Laptop Hitam",
    Computer_Laptop_Silver: "Komputer Laptop Perak",
    Database: "Basis Data",
    evelope: "Amplop",
    newspapers: "Koran",
    openevelope: "Amplop Terbuka",
    Server: "Server",
    speaker: "Speaker",
    WirelessAccessPoint: "Titik Akses Nirkabel",
    Cycle01_Transparent: "Lingkaran 01 Transparan",
    Cycle02_Transparent_Blue: "Lingkaran 02 Transparan Biru",
    Cycle03_Blue: "Lingkaran 03 Biru",
    Cycle04_Blue: "Lingkaran 04 Biru",
    Cycle05: "Lingkaran 05",
    Cycle06: "Lingkaran 06",
    Cycle07: "Lingkaran 07",
    Cycle08_Blue: "Lingkaran 08 Biru",
    Cycle09_Orange: "Lingkaran 09 Oranye",
    Donut01_LightBlue: "Donat 01 Biru Muda",
    Donut02_Blue: "Donat 02 Biru",
    Donut03_Blue: "Donat 03 Biru",
    Donut04_DarkBlue: "Donat 04 Biru Tua",
    Donut05_DarkBlue: "Donat 05 Biru Tua",
    Donut06_Blue: "Donat 06 Biru",
    Donut07_Blue: "Donat 07 Biru",
    Graph: "Grafik",
    People01_Blue: "Orang 01 Biru",
    People02: "Orang 02",
    Pillars01_Orange: "Pilar 01 Oranye",
    Pillars02_LightBlue: "Pilar 02 Biru Muda",
    Process01_Blue: "Proses 01 Biru",
    Process02_Blue: "Proses 02 Biru",
    Process03_Blue: "Proses 03 Biru",
    Process04_GoUp_Blue: "Proses 04 Naik Biru",
    Process05_GoUp_Red: "Proses 05 Naik Merah",
    Process06_GoUp_Yellow: "Proses 06 Naik Kuning",
    Process07_Blue: "Proses 07 Biru",
    Pyramid01: "Piramida 01",
    Pyramid02_Blue: "Piramida 02 Biru",
    Pyramid03: "Piramida 03",
    Radial01_Green: "Radial 01 Hijau",
    Radial02_Green: "Radial 02 Hijau",
    Radial03_Sphere: "Radial 03 Bola",
    Radial04_Sphere_Red: "Radial 04 Bola Merah",
    Radial05_Sphere_Blue: "Radial 05 Bola Biru",
    Radial06_Arrows_DarkBlue: "Radial 06 Panah Biru Tua",
    Radial07_Arrows_DarkBlue: "Radial 07 Panah Biru Tua",
    Section_Circle: "Lingkaran Bagian",
    Section_Cubes01: "Kubus Bagian 01",
    Section_Cubes02_Blue: "Kubus Bagian 02 Biru",
    Section_Cubes03_Orange: "Kubus Bagian 03 Oranye",
    Section_Cubes04: "Kubus Bagian 04",
    Section_Cubes05: "Kubus Bagian 05",
    Section_Cuboids01_Blue: "Balok Bagian 01 Biru",
    Section_Cuboids02_Blue: "Balok Bagian 02 Biru",
    Section_Cuboids03: "Balok Bagian 03",
    Section_Gears01: "Bagian Roga Gigi 01",
    Section_Gears02: "Bagian Roga Gigi 02",
    Section_Gears03: "Bagian Roga Gigi 03",
    Section_Hexagon04_Orange: "Segi Enam Bagian 04 Oranye",
    Section_Hexagons01: "Segi Enam Bagian 01",
    Section_Hexagons02_Blue: "Segi Enam Bagian 02 Biru",
    Section_Hexagons03_Blue: "Segi Enam Bagian 03 Biru",
    Section_Leaves01_LightBlue: "Daun Bagian 01 Biru Muda",
    Section_Leaves02_Green: "Bagian Daun 02 Hijau",
    Section_Pasters01: "Paster Bagian 01",
    Section_Pasters02_Blue: "Paster Bagian 02 Biru",
    Section_Puzzle01: "Puzzle Bagian 01",
    Section_Puzzle02: "Puzzle Bagian 02",
    Section_Puzzle03: "Puzzle Bagian 03",
    Section_Rectangles: "Persegi Panjang Bagian",
    Section_Squares: "Bagian Persegi",
    Section_Triangle: "Bagian Segitiga",
    Target: "Target",
    Venn01: "Venn 01",
    Venn02: "Venn 02",
    Venn03: "Venn 03",
    Venn04: "Venn 04",
    Venn05: "Venn 05",
    Venn06_Blue: "Venn 06 Biru",
    Venn07_Blue: "Venn 07 Biru",
    Venn08: "Venn 08",
    Blackboard: "Papan Tulis",
    Books: "Buku",
    Books1: "Buku 1",
    books2: "Buku 2",
    Chalk: "Kapur",
    clipboard: "clipboard",
    clock: "jam",
    Globe: "Globe",
    Glue: "Lem",
    GraduationCap: "Topi Wisuda",
    magnifyingglass: "Kaca Pembesar",
    Microscope: "Mikroskop",
    Notebook: "Notebook",
    notepad1: "Notepad 1",
    notepad2: "Notepad 2",
    notepad3: "Notepad 3",
    PaperClip_Blue: "Klip Kertas Biru",
    PaperClip_Red: "Klip Kertas Merah",
    Pencil: "Pensil",
    Ruler: "Penggaris",
    TestTubes: "Tabung Reaksi",
    thumbtack: "Paku Payung",
    clouds: "Awan",
    DrippingFaucet: "Keran Air",
    Earth: "Bumi",
    EndangeredAnimals1: "Binatang Langka 1",
    EndangeredAnimals2: "Hewan Langka 2",
    GreenCar: "Mobil Hijau",
    GreenFactory: "Pabrik Hijau",
    GreenHouse: "Rumah Hijau",
    Leaf1: "Daun 1",
    Leaf2: "Daun 2",
    lightbulb: "Bola Lampu",
    LightBulb_Flourescent_Off: "Bola Lampu Neon Mati",
    LightBulb_Flourescent_On: "Bola Lampu Neon Hidup",
    LightBulb_Standard_Off1: "Bola Lampu Standar Mati 1",
    LightBulb_Standard_Off2: "Bola Lampu Standar Mati 2",
    LightBulb_Standard_On: "Bola Lampu Standar Hidup",
    lightningcloud: "Awan Petir",
    Pollution_Car: "Mobil Berpolusi",
    Pollution_Factory: "Pabrik Berpolusi",
    Raindrop: "Tetes Hujan",
    RecycleBin: "Keranjang Sampah",
    RecycleSymbol: "Simbol Daur Ulang",
    RenewableEnergySymbol: "Simbol Energi Terbarukan",
    RenewableEnergy_Solar: "Energi Matahari",
    RenewableEnergy_Water: "Energi Air",
    RenewableEnergy_Wind: "Energi Angin",
    sun: "Matahari",
    Sun1: "Matahari 1",
    Sun2: "Matahari 2",
    sundandcloud: "Matahari dan Awan",
    world: "Dunia",
    Agreement: "Perjanjian",
    ATM01: "ATM 01",
    ATM02: "ATM 02",
    Balance_Balanced1: "Timbangan Seimbang 1",
    Balance_Balanced2: "Timbangan Seimbang 2",
    Balance_Unbalanced1: "Timbangan Tidak Seimbang 1",
    Balance_Unbalanced2: "Timbangan Tidak Seimbang 2",
    Calculator: "Kalkulator",
    Chart_Decrease1: "Grafik Menurun 1",
    Chart_Decrease2: "Grafik Menurun 2",
    Chart_Increase1: "Grafik Menaik 1",
    Chart_Increase2: "Grafik Menaik 2",
    Chart_Plateau: "Grafik Plato",
    Check: "Cek",
    Contract: "Kontrak",
    CreditCard_Black: "Kartu Kredit Hitam",
    CreditCard_Cut: "Kartu Kredit Terpotong",
    CreditCard_Gold: "Kartu Kredit Emas",
    Currency_Dollar: "Mata Uang Dolar",
    Currency_Dollars: "Mata Uang Dolar",
    Currency_Stack: "Tumpukan Uang",
    Currency_StackCoins: "Tumpukan Uang Koin",
    GoldBar: "Batang Emas",
    GoldBar_Stack: "Tumpukan Batang Emas",
    MoneyBag01: "Kantong Uang 01",
    MoneyBag02: "Kantong Uang 02",
    PercentSign: "Tanda Persen",
    PiggyBank01_Broken: "Celengan 01 Pecah",
    PiggyBank02_Broken: "Celengan 02 Pecah",
    PiggyBank_Coins: "Celengan Koin",
    PiggyBank_Currency: "Mata Uang Celengan",
    Portfolio: "Portofolio",
    PriceTag: "Label Harga",
    Safe_Closed: "Brangkas Tertutup",
    Safe_Empty: "Brangkas Kosong",
    Safe_Full: "Brangkas Penuh",
    Seal_Gold: "Segel Emas",
    Seal_Red: "Segel Merah",
    Seal_Silver: "Segel Perak",
    Wallet_Empty: "Dompet Kosong",
    Wallet_Full1: "Dompet Penuh 1",
    Wallet_Full2: "Dompet Penuh 2",
    BusinessPerson_Female6: "Pelaku Bisnis Wanita 6",
    BusinessPerson_Male3: "Pelaku Bisnis Pria 3",
    Computer_User_Female1: "Pengguna Komputer Wanita 1",
    ConstructionWorker2: "Pekerja Konstruksi 2",
    Presenter_Female1: "Penyaji Wanita 1",
    Component_Circle01_Transparent_DarkBlue: "Lingkaran Komponen 01 Transparan Biru Tua",
    Component_Circle02_Transparent_Bule: "Lingkaran Komponen 02 Transparan Biru Tua",
    Component_Circle03_Transparent_Green: "Lingkaran Komponen 03 Transparan Hijau",
    Component_Circle04_Transparent_Orange: "Lingkaran Komponen 04 Transparan Oranye",
    Component_Circle05_Transparent_Red: "Lingkaran Komponen 05 Transparan Merah",
    Component_Cube01_DarkBlue: "Kubus Komponen 01 Biru Tua",
    Component_Cube02_LightBlue: "Kubus Komponen 02 Biru Muda",
    Component_Cube03_Green: "Kubus Komponen 03 Hijau",
    Component_Cube04_Orange: "Kubus Komponen 04 Oranye",
    Component_Cube05_DarkRed: "Kubus Komponen 05 Merah Tua",
    Component_Cuboid01_DarkBlue: "Balok Komponen 01 Biru Tua",
    Component_Cuboid02_Blue: "Balok Komponen 02 Biru",
    Component_Cuboid03_Green: "Balok Komponen 03 Hijau",
    Component_Cuboid04_Orange: "Balok Komponen 04 Oranye",
    Component_Cuboid05_Red: "Balok Komponen 05 Merah",
    Component_Gear01_DarkBlue: "Roda Gigi Komponen 01 Biru Tua",
    Component_Gear02_LightBlue: "Komponen Roda Gigi 02 Biru Muda",
    Component_Gear03_Green: "Roda Gigi Komponen 03 Hijau",
    Component_Gear04_DarkRed: "Roda Gigi Komponen 04 Merah Tua",
    Component_Gear05_Orange: "Roda Gigi Komponen 05 Oranye",
    Component_Person01_DarkBlue: "Komponen Orang 01 Biru Tua",
    Component_Person02_Blue: "Komponen Orang 02 Biru",
    Component_Person03_Green: "Komponen Orang 03 Hijau",
    Component_Person04_DarkRed: "Komponen Orang 04 Merah Tua",
    Component_Person05_Orange: "Komponen Orang 05 Oranye",
    Component_PuzzlePiece01_DarkBlue: "Komponen Kepingan Puzzle 01 Biru Tua",
    Component_PuzzlePiece02_Blue: "Komponen Kepingan Puzzle 02 Biru",
    Component_PuzzlePiece03_Green: "Komponen Kepingan Puzzle 03 Hijau",
    Component_PuzzlePiece04_Red: "Komponen Kepingan Puzzle 04 Merah",
    Component_PuzzlePiece05_Orange: "Komponen Kepingan Puzzle 05 Oranye",
    Component_Sphere01_DarkBlue: "Komponen Bola 01 Biru Tua",
    Component_Sphere02_LightBlue: "Komponen Bola 02 Biru Muda",
    Component_Sphere03_Green: "Komponen Bola 03 Hijau",
    Component_Sphere04_DarkRed: "Komponen Bola 04 Merah Tua",
    Component_Sphere05_Orange: "Komponen Bola 05 Oranye",
    Book: "Buku",
    Box01: "Kotak 01",
    Box02: "Kotak 02",
    Bulb01_Yellow: "Bola Lampu 01 Kuning",
    Bulb02_Yellow: "Bola Lampu 02 Kuning",
    Calendar: "Kalendar",
    Chart: "Grafik",
    Clipboard: "Clipboard",
    Clock: "Jam",
    Compass: "Kompas",
    Flag01_Red: "Bendera 01 Merah",
    Flag02_Green: "Bendera 02 Hijau",
    Flag03_Blue: "Bendera 03 Biru",
    Gift: "Kado",
    House: "Rumah",
    Icon_Computer01_White: "Ikon Komputer 01 Putih",
    Icon_Computer02_Black: "Ikon Komputer 02 Hitam",
    Icon_Disk01_Blue: "Ikon Disk 01 Biru",
    Icon_Disk02_Green: "Ikon Disk 02 Hijau",
    Icon_Document01_Grey: "Ikon Dokumen 01 Abu-abu",
    Icon_Document02_Grey: "Ikon Dokumen 02 Abu-abu",
    Icon_Document03_Blue: "Ikon Dokumen 03 Biru",
    Icon_Document04_Blue: "Ikon Dokumen 04 Biru",
    Icon_Envelope01_Blue: "Ikon Amplop 01 Biru",
    Icon_Envelope02_Yellow: "Ikon Amplop 02 Kuning",
    Icon_Envelope03_Open_Yellow: "Ikon Amplop 03 Terbuka Kuning",
    Icon_Envelope04_Open_Yellow: "Ikon Amplop 04 Terbuka Kuning",
    Icon_Folder01_Yellow: "Ikon Folder 01 Kuning",
    Icon_Folder02_Yellow: "Ikon Folder 02 Kuning",
    Icon_Folder03_Open_Yellow: "Ikon Folder 03 Terbuka Kuning",
    Icon_Folder04_Open_Yellow: "Ikon Folder 04 Terbuka Kuning",
    Icon_Gear01_Grey: "Ikon Roda Gigi 01 Abu-abu",
    Icon_Gear02_Blue: "Ikon Roda Gigi 02 Biru",
    Icon_Network01_Blue: "Ikon Jaringan 01 Biru",
    Icon_Network02: "Ikon Jaringan 02",
    Icon_Pencil01: "Ikon Pensil 01",
    Icon_Pencil02: "Ikon Pensil 02",
    Icon_Printer01_White: "Ikon Printer 01 Putih",
    Icon_Printer02_Black: "Ikon Printer 02 Hitam",
    Key01: "Kunci 01",
    Key02: "Kunci 02",
    Lock01_Yellow: "Gembok 01 Kuning",
    Lock02_Yellow: "Gembok 02 Kuning",
    Lock03_Blue: "Gembok 03 Biru",
    Lock04_Blue: "Gembok 04 Biru",
    Magnet: "Magnet",
    MagnifyingGlass: "Kaca Pembesar",
    Medal: "Medali",
    Notebook: "Notebook",
    Phone: "Telepon",
    PieChart: "Grafik Pai",
    Pin: "Pin",
    PuzzlePiece: "Kepingan Puzzle",
    PuzzlePieces: "Keping-kepingan Puzzle",
    Roadblock: "Penghalang",
    Scissors: "Gunting",
    Shield01: "Perisai 01",
    Shield02_Orange: "Perisai 02 Oranye",
    Shield03_Blue: "Perisai 03 Biru",
    Sign_Ban01: "Tanda Larangan 01",
    Sign_Ban02: "Tanda Larangan 02",
    Sign_CheckBox01: "Tanda Kotak Centang 01",
    Sign_CheckBox02_Unchecked: "Tanda Kotak Centang 02 Tidak Dicentang",
    Sign_Checkmark01_Green: "Tanda Tanda Centang 01 Hijau",
    Sign_Checkmark02_Green: "Tanda Tanda Centang 02 Hijau",
    Sign_DoNotEnter: "Tanda Dilarang Masuk",
    Sign_Error01: "Tanda Kesalahan 01",
    Sign_Error02: "Tanda Kesalahan 02",
    Sign_ExclamationPoint01_Red: "Tanda Tanda Seru 01 Merah",
    Sign_ExclamationPoint02_Orange: "Tanda Tanda Seru 02 Oranye",
    Sign_Help01_Green: "Tanda Bantuan 01 Hijau",
    Sign_Help02_Blue: "Tanda Bantuan 02 Biru",
    Sign_Information: "Tanda Informasi",
    Sign_Null: "Tanda Kosong",
    Sign_QuestionMark01_Blue: "Tanda Tanda Tanya 01 Biru",
    Sign_QuestionMark02_Red: "Tanda Tanda Tanya 02 Merah",
    Sign_RadioButton01: "Tanda Tombol Radio 01",
    Sign_RadioButton02_Unchecked: "Tanda Tombol Radio 02 Tidak Dicentang",
    Sign_Warning01_Red: "Tanda Peringatan 01 Merah",
    Sign_Warning02_Orange: "Tanda Peringatan 02 Oranye",
    Sign_X01_Red: "Tanda X 01 Merah",
    Sign_X02_Red: "Tanda X 02 Merah",
    Star_Yellow: "Bintang Kuning",
    Wrench: "Kunci Inggris",
    Airplane_Blue: "Pesawat Biru",
    Bicycle_Blue: "Sepeda Biru",
    Bus: "Bus",
    Canoe_Blue: "Kano Biru",
    Car_Red: "Mobil Merah",
    Helicopter_Blue: "Helikopter Biru",
    Motorcycle_Red: "Sepeda Motor Merah",
    Pedestrian_Blue: "Pejalan Kaki Biru",
    PersonalTransporter_Green: "Alat Angkut Pribadi Hijau",
    Sailboat_Red: "Perahu Layar Merah",
    Scooter_Orange: "Skuter Oranye",
    Train_Red: "Kereta Merah",
    Truck_Blue: "Truk Biru",
    
    aria_category_selector: "Opsi Kategori Gambar",
    filterImageGallery: "Penyaring Galeri Gambar"

})
