﻿/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* IBM Docs Source Materials                                         */
/*                                                                   */
/* (c) Copyright IBM Corporation 2012. All Rights Reserved.          */
/*                                                                   */
/* U.S. Government Users Restricted Rights: Use, duplication or      */
/* disclosure restricted by GSA ADP Schedule Contract with IBM Corp. */
/*                                                                   */
/* ***************************************************************** */

define({
        fileMenu: "File",
        fileMenu_New: "Baru",
        fileMenu_NewDocument: "Dokumen",
        fileMenu_NewFromTemplate: "Dari Templat",
        fileMenu_NewDocumentfromTemplate: "Dokumen dari Templat",
        fileMenu_NewPresentation: "Presentasi",
        fileMenu_NewPresentationfromTemplate: "Presentasi dari Templat",
        fileMenu_NewSpreadsheet: "Spreadsheet",
        fileMenu_NewSpreadsheetFromTemplate: "Spreadsheet dari Templat",
        fileMenu_Open: "Buka",
        fileMenu_Import: "Impor...",
        //	fileMenu_Close: "Close",
        fileMenu_Discard: "Kembalikan ke Versi Terakhir",
        fileMenu_ClearTrackChange: "Hapus Tanda Perubahan",
        fileMenu_SpreadsheetSettings: "Atur Lokal Dokumen...",
        filemenu_revisionhistory: "Revisi",
        fileMenu_Save: "Simpan",
        fileMenu_SaveAs: "Salin...",
        fileMenu_AutoPublish: "Terbitkan secara Otomatis",
        fileMenu_AutoCheckIn: "Check in secara Otomatis",
        fileMenu_PublishVersion: "Terbitkan Sekarang",
        fileMenu_AutoPublish2: "Simpan Otomatis ke Repositori",
        //	fileMenu_AutoPublish_Tips: "Makes your changes available to readers at the end of each editing session.",
        fileMenu_PublishVersion2: "Simpan ke Repositori Sekarang",
        fileMenu_AutoPublish3: "Simpan Otomatis ke ${0}",
        fileMenu_PublishVersion3: "Simpan ke ${0} Sekarang",      
        fileMenu_SubmitForReview: "Kirim untuk Peninjauan...",
        fileMenu_CheckinVersion: "Check In...",
        fileMenu_Unlock: "Buka Kunci",
        //	fileMenu_SaveAsDraft: "as Draft",
        //	fileMenu_SaveInMyDocs: "in My Documents",
        //	fileMenu_SaveToSymphony: "to Lotus Symphany",
        fileMenu_DownloadAs: "Unduh sebagai",
        fileMenu_PDF: "PDF",
        fileMenu_ODF: "ODF",
        fileMenu_DOC: "Microsoft Word 97- 2007 (*.doc)",
        fileMenu_ODS: "ODS",
        fileMenu_XLS: "Microsoft Excel 97-2007 (*.xls) ",
        fileMenu_ShareWith: "Bagikan...",
        fileMenu_ExportAsPDF: "PDF",
        fileMenu_ExportAsODF: "ODF",
        fileMenu_ExportAsPPT: "Microsoft Powerpoint 97- 2007 (*.ppt)",
        //	fileMenu_WebPreview: "Web Preview",
        fileMenu_PrintToPDF: "Cetak ke PDF...",
        fileMenu_ViewFileDetails: "Tampilkan Rincian File...",
        fileMenu_RecentFile: "File Terbaru",
        fileMenu_Open: "Buka",
        fileMenu_Download: "Unduh",
        fileMenu_Print: "Cetak",
        fileMenu_Export: "Ekspor",
        fileMenu_ExportToCSV: "CSV",
        fileMenu_ExportToPDF: "PDF (.pdf)",
        fileMenu_ExportToMarkdown: "Markdown(.md)",
        fileMenu_ExportToMS: "Format Microsoft Office (.${FILEEXTENSION})",
        fileMenu_ExportToODF: "Format Open Document (.${FILEEXTENSION})",
        fileMenu_PgSetup: "Pengaturan Halaman...",

        editMenu: "Edit",
        editMenu_Undo: "Batal",
        editMenu_Redo: "Ulangi",
        editMenu_Cut: "Potong",
        editMenu_Copy: "Salin",
        editMenu_Paste: "Tempel",
        editMenu_DeleteSlide: "Hapus Slide",
        editMenu_SelectAll: "Pilih Semua",
        editMenu_Find: "Temukan...",
        editMenu_Replace: "Ganti...",
        editMenu_FindReplace: "Temukan dan Ganti...",
        editMenu_EditLink: "Tambah atau Edit Tautan",
        editMenu_DeleteSheet: "Hapus Lembar...",
        editMenu_RenameSheet: "Ganti Nama Lembar...",
        editMenu_HideSheet: "Sembunyikan Lembar",
        editMenu_MoveSheet: "Pindahkan Lembar...",
        editMenu_DeleteRow: "Hapus Baris",
        editMenu_DeleteColumn: "Hapus Kolom",
        editMenu_DeleteCellLeft: "Hapus Sel dan Geser Kiri",
        editMenu_DeleteCellUp: "Hapus Sel dan Geser Atas",
        editMenu_ClearCell: "Hapus Konten",

        viewMenu: "Tampilan",
        viewMenu_Master: "Master",
        viewMenu_Notifications: "Pemberitahuan",
        viewMenu_SlideSorter: "Penyortir Slide",
        viewMenu_SpeakerNotes: "Catatan Pembicara",
        viewMenu_Toolbar_Basic: "Dasar",
        viewMenu_Toolbar_Advanced: "Lanjutan",
        viewMenu_Toolbar_None: "None",
        viewMenu_Toolbar: "Toolbar",
        viewMenu_Statusbar: "Barstatus",
        viewMenu_Navigator: "Navigator...",
        //viewMenu_Sidebar: "Sidebar",
        viewMenu_ShowHideIndicators: "Tunjukkan Indikator Pengeditan Bersama",
        viewMenu_Assignment: "Indikator Penugasan",
        viewMenu_Bookmark: "Markah",
        viewMenu_Coediting: "Sorotan Pengeditan Bersama",
        viewMenu_Rulers: "Penggaris",
        viewMenu_WebLayout: "Tata Letak Web",
        viewMenu_AutomaticSpellCheck: "Pemeriksaan Ejaan saat Anda Mengetik",
        viewMenu_Formulabar: "Bar Formula",
        viewMenu_moveRight: "Masukkan Pindahkan Kursor ke Kanan",
        viewMenu_showFullString: "Perluas Konten dalam Sel",
        viewMenu_Doc: "Tampilkan Dokumen",
        viewMenu_Templates: "Templat",
        viewMenu_GridLines: "Sembunyikan Garis Kisi",
        viewMenu_UnsupportWarning: "Tampilkan Pesan Fitur yang Tidak Didukung",
        viewMenu_HiddenSheets: "Lembar Tersembunyi",
        viewMenu_FreezeRows: "Baris Beku",
        viewMenu_FreezeColumns: "Kolom Beku",
        viewMenu_NoFrozenRows: "Tidak Ada Baris yang Beku",
        viewmenu_NoFrozenColumns: "Tidak Ada Kolom yang Beku",
        viewMenu_FreezeXRows: "Bekukan ${0} Baris",
        viewMenu_FreezeOneRow: "Bekukan ${0} Baris",
        viewMenu_FreezeXColumns: "Bekukan ${0} Kolom",
        viewMenu_FreezeOneColumn: "Bekukan ${0} Kolom",
        viewMenu_CarriageReturn: "Tanda Format",
        viewMenu_Navigation: "Panel Navigasi",
        viewMenu_ACL: "Area yang Dapat Diedit",
        viewMenu_GridOnOff: "Garis Kisi",
        viewMenu_ObserverMode: 'Mode Pengamat',

        createMenu: "Sisipkan",
        createMenu_NewSlide: "Slide Baru",
        createMenu_DuplicateSlide: "Gandakan Slide",
        createMenu_ImageFromFile: "Gambar...",
        createMenu_TextBox: "Kotak Teks",
        createMenu_Shape: "Bentuk",
        createMenu_break: "Pemisah",
        createMenu_RowAbove: "Baris Di Atas",
        createMenu_RowBelow: "Baris Di Bawah",
        createMenu_ColumnRight: "Kolom Di Kanan",
        createMenu_ColumnLeft: "Kolom di Kiri",
        createMenu_Sheet: "Lembar...",
        createMenu_Image: "Gambar...",
        createMenu_Comments: "Komentar...",
        createMenu_WebLink: "Tautan Web...",
        createMenu_SpecialCharacter: "Karakter Khusus...",
        createMenu_Function: "Fungsi...",
        createMenu_Fromtemplate: "Buat Dari Template",

        insertMenu: "Sisipkan",
        insertMenu_break: "Pemisah Halaman",
        insertMenu_sectionbreak: "Pemisah Bagian",
        insertMenu_Bookmark: "Beri markah...",
        insertMenu_WebLink: "Tautan...",
        insertMenu_SpecialCharacter: "Karakter Khusus...",
        insertMenu_HorizontalLine: "Garis Horizontal",
        insertMenu_Header: "Header",
        insertMenu_Footer: "Footer",
        insertMenu_TableOfContents: "Daftar Isi",

        insertMenu_HeaderFooter: "Header/Footer",
        insertMenu_HF_Edit: "Edit",
        insertMenu_HF_Hide: "Sembunyikan",
        insertMenu_Endnotes: "Catatan Akhir",
        insertMenu_RowAbove: "Baris Di Atas",
        insertMenu_PageNumber: "Nomor Halaman",
        insertMenu_PageNumberTop: "Bagian Atas Halaman",
        insertMenu_PageNumberBottom: "Bagian Bawah Halaman",
        insertMenu_PageNumberCurr: "Posisi Saat Ini",
        insertMenu_TotalPageNumber: "Halaman 1 dari N",
        insertMenu_Date: "Tanggal...",
        insertMenu_Time: "Waktu...",
        insertMenu_Fields: "Bidang",
        //    insertMenu_Comment: "Comment",
        insertMenu_CellRight: "Sel dan Geser Kanan",
        insertMenu_CellDown: "Sel dan Geser Bawah",
        insertMenu_RowBelow: "Baris Di Bawah",
        insertMenu_ColumnBefore: "Kolom Sebelumnya",
        insertMenu_ColumnAfter: "Kolom Setelahnya",
        insertMenu_Sheet: "Lembar...",
        insertMenu_Image: "Gambar...",
        insertMenu_DuplicateSheet: "Cadangkan Lembar",
        insertMenu_Function: "Fungsi",
        insertMenu_FunctionSum: "SUM",
        insertMenu_FunctionAverage: "AVERAGE",
        insertMenu_FunctionCount: "COUNT",
        insertMenu_FunctionMax: "MAX",
        insertMenu_FunctionMin: "MIN",
        insertMenu_FunctionMore: "Lebih Banyak Fungsi...",
        insertMenu_NameRange: "Rentang yang Ditentukan",
        insertMenu_NameRangeNew: "Rentang Baru...",
        insertMenu_NameRangeManage: "Kelola Rentang...",
        insertMenu_Chart: "Grafik...",

        contextMenu_insertCellRight: "Masukkan Sel dan Geser Kanan",
        contextMenu_insertCellDown: "Masukkan Sel dan Geser Bawah",
        contextMenu_InsertRowAbove: "Sisipkan Baris Di Atas",
        contextMenu_InsertRowBelow: "Sisipkan Baris Di Bawah",
        contextMenu_InsertColumnBefore: "Sisipkan Kolom Sebelumnya",
        contextMenu_InsertColumnAfter: "Sisipkan Kolom Setelahnya",
        contextMenu_DownloadImage: "Unduh sebagai Gambar",

        formatMenu: "Format",
        formatMenu_Columns: "Kolom",
        formatMenu_DefaultFormatting: "Format Default",
        formatMenu_Template: "Gaya...",
        contextMenu_Template: "Gaya Tabel...",
        formatMenu_LineSpacing: "Spasi Baris",
        formatMenu_LineSpacing1: "1",
        formatMenu_LineSpacing12: "1,2",
        formatMenu_LineSpacing15: "1,5",
        formatMenu_LineSpacing2: "2",
        formatMenu_LineSpacing25: "2,5",
        formatMenu_LineSpacing3: "3",
        formatMenu_TextProperties: "Properti Teks",
        formatMenu_PageBreakBefore: "Pemisah Halaman Sebelum",
        formatMenu_KeepLines: "Pertahankan Baris Bersama",
        formatMenu_WidowControl: "Kontrol Widow/Orphan",
        formatMenu_Pagination: "Properti Paragraf",
        formatMenu_Bold: "Tebal",
        formatMenu_Italic: "Miring",
        formatMenu_Underline: "Garis Bawah",
        formatMenu_Strikethrough: "Coretan",
        formatMenu_IncreaseSize: "Perbesar Ukuran Font",
        formatMenu_DecreaseSize: "Perkecil Ukuran Font",
        formatMenu_ImageProperties: "Properti Gambar...",
        formatMenu_ChartProperties: "Properti Grafik...",
        formatMenu_EditChart: "Edit Grafik",
        formatMenu_InsertChart: "Sisipkan Grafik",
        formatMenu_Properties: "Properti...",
        formatMenu_Heading: "Judul",
        formatMenu_Normal: "Normal",
        formatMenu_Title: "Judul",
        formatMenu_Subtitle: "Subjudul",
        formatMenu_Heading1: "Judul 1",
        formatMenu_Heading2: "Judul 2",
        formatMenu_Heading3: "Judul 3",
        formatMenu_Heading4: "Judul 4",
        formatMenu_Heading5: "Judul 5",
        formatMenu_Heading6: "Judul 6",
        formatMenu_Heading7: "Judul 7",
        formatMenu_Heading8: "Judul 8",
        formatMenu_Heading9: "Judul 9",
        formatMenu_BulletedList: "Daftar Berpoin",
        formatMenu_NumberedList: "Daftar Bernomor",
        formatMenu_OutLine: "Daftar Multilevel",
        formatMenu_Superscript: "Superskrip",
        formatMenu_Subscript: "Subskrip",
        formatMenu_Align: "Ratakan",
        formatMenu_Left: "Kiri",
        formatMenu_Right: "Kanan",
        formatMenu_Center: "Tengah",
        formatMenu_Justify: "Rata Kanan Kiri",
        formatMenu_Text_Direction: "Arah Teks",
        formatMenu_Ltr: "Kiri ke Kanan",
        formatMenu_Rtl: "Kanan ke Kiri",
        formatMenu_LineSpacing: "Spasi Baris",
        formatMenu_LineSpacing1: "1,0",
        formatMenu_LineSpacing115: "1,15",
        formatMenu_LineSpacing15: "1,5",
        formatMenu_LineSpacing2: "2,0",
        formatMenu_LineSpacing25: "2,5",
        formatMenu_LineSpacing3: "3,0",
        formatMenu_Top: "Atas",
        formatMenu_Bottom: "Bawah",
        formatMenu_Middle: "Tengah",
        formatMenu_Direction: "Arah Teks",
        formatMenu_Rtl: "Kanan ke Kiri",
        formatMenu_Ltr: "Kiri ke Kanan",
        formatMenu_Auto: "Kontekstual",
        formatMenu_SheetDirection: "Arah Lembar",
        formatMenu_SheetRtl: "Kanan ke Kiri",
        formatMenu_SheetLtr: "Kiri ke Kanan",
        formatMenu_Indent: "Tambah Inden",
        formatMenu_DecreaseIndent: "Kurangi Inden",
        formatMenu_ClearFormat: "Hapus pemformatan",
        formatMenu_RowHeight: "Tinggi Baris",
        formatMenu_ColumnWidth: "Lebar Kolom",
        formatMenu_ShowRow: "Tunjukkan Baris",
        formatMenu_HideRow: "Sembunyikan Baris",
        formatMenu_ShowColumn: "Tunjukkan Kolom",
        formatMenu_HideColumn: "Sembunyikan Kolom",
        formatMenu_WrapText: "Bungkus Teks",
        formatMenu_Number: "Nomor",
        formatMenu_FontArial: "Arial",
        formatMenu_FontComicSansMS: "Comic Sans MS",
        formatMenu_FontCourierNew: "Courier New",
        formatMenu_FontGeorgia: "Georgia",
        formatMenu_FontLucidaSansUnicode: "Lucida Sans Unicode",
        formatMenu_FontTahoma: "Tahoma",
        formatMenu_FontTimesNewRoman: "Times New Roman",
        formatMenu_FontTrebuchetMS: "Trebuchet MS",
        formatMenu_FontVerdana: "Verdana",
        formatMenu_FontName: "Font",

        layoutMenu: "Tata Letak",
        layoutMenu_SlideLayout: "Tata Letak Slide...",
        layoutMenu_SlideDesign: "Gaya Master...",
        layoutMenu_DefaultFormatting: "Format Default",
        layoutMenu_Textprop_Bold: "Tebal",
        layoutMenu_Textprop_Italic: "Miring",
        layoutMenu_Textprop_Underline: "Garis Bawah",
        layoutMenu_Textprop_Strikethrough: "Coretan",
        layoutMenu_TextProp: "Properti Teks",
        LayoutMenu_RowHeight: "Tinggi Baris...",
        LayoutMenu_ColumnWidth: "Lebar Kolom...",
        LayoutMenu_ShowRow: "Tunjukkan Baris",
        LayoutMenu_HideRow: "Sembunyikan Baris",
        LayoutMenu_RenameSheet: "Ganti Nama Lembar...",
        LayoutMenu_MoveSheet: "Pindahkan Lembar",

        tableMenu: "Tabel",
        tableMenu_Create: "Buat...",
        tableMenu_CreateFromTemplate: "Buat Dari Template",
        tableMenu_Delete: "Hapus",
        tableMenu_SetTableColor: "Beri Warna Sel",
        tableMenu_CreateTable: "Buat Tabel",
        tableMenu_Cell: "Sel",
        tableMenu_CellMergeCells: "Gabungkan Sel",
        tableMenu_CellAlignLeft: "Rata Kiri",
        tableMenu_CellAlignCenter: "Rata Tengah",
        tableMenu_CellAlignRight: "Rata Kanan",
        tableMenu_CellClearContents: "Hapus Konten",
        tableMenu_CellProperties: "Properti Sel...",
        tableMenu_Row: "Baris",
        tableMenu_InsertRowAbove: "Sisipkan Baris Di Atas",
        tableMenu_InsertRowBelow: "Sisipkan Baris Di Bawah",
        tableMenu_MoveRowAbove: "Pindahkan Baris ke Atas",
        tableMenu_MoveRowBelow: "Pindahkan Baris ke Bawah",
        tableMenu_RowInsertRow: "Sisipkan Baris...",
        tableMenu_RowInsertRowAbove: "Sisipkan Baris Di Atas",
        tableMenu_RowInsertRowBelow: "Sisipkan Baris Di Bawah",
        tableMenu_RowMoveRowAbove: "Pindahkan Baris Ke Atas",
        tableMenu_RowMoveRowBelow: "Pindahkan Baris Ke Bawah",
        tableMenu_RowDelete: "Hapus",
        tableMenu_RowRepeat: "Ulangi Baris Header",
        tableMenu_InsertColumnBefore: "Sisipkan Kolom Sebelumnya",
        tableMenu_InsertColumnAfter: "Sisipkan Kolom Setelahnya",
        tableMenu_MoveColumnBefore: "Pindahkan Kolom ke Kiri",
        tableMenu_MoveColumnAfter: "Pindahkan Kolom ke Kanan",
        tableMenu_ResizeColumn: "Ubah Ukuran Kolom",
        tableMenu_ResizeColumns: "Ubah Ukuran Kolom",
        tableMenu_MarkasCategory: "Tandai sebagai Kategori",
        tableMenu_ColumnInsertColumn: "Sisipkan Kolom...",
        tableMenu_ColumnAddColumnBefore: "Sisipkan Kolom Sebelumnya",
        tableMenu_ColumnAddColumnAfter: "Sisipkan Kolom Setelahnya",
        tableMenu_ColumnMoveColumnAfter: "Pindahkan Kolom Setelahnya",
        tableMenu_ColumnMoveColumnBefore: "Pindahkan Kolom Sebelumnya",
        tableMenu_ColumnDelete: "Hapus",
        tableMenu_ColumnSortAscending: "Urutkan Naik",
        tableMenu_ColumnSortDescending: "Urutkan Turun",
        tableMenu_Column: "Kolom",
        tableMenu_Style: "Gaya",
        tableMenu_TableProperties: "Properti Tabel...",

        teamMenu: "Tim",
        teamMenu_AddComment: "Tambah Komentar",
        teamMenu_AssignCells: "Tetapkan Sel",
        teamMenu_AssignSection: "Tetapkan Bagian",
        teamMenu_EditAssignment: "Edit Penugasan",
        teamMenu_MarkSectionComplete: "Tandai Bagian Selesai",
        teamMenu_MarkAssignmentComplete: "Tandai Penugasan Selesai",
        teamMenu_WorkPrivatelyOnSection: "Bekerja Secara Privat pada Bagian",
        teamMenu_CancelPrivateWork: "Batalkan Pekerjaan Pribadi",
        teamMenu_ApproveSection: "Setujui Bagian",
        teamMenu_ApproveAssignment: "Setujui Penugasan",
        teamMenu_ReturnSectionForRework: "Kembali Ke Bagian untuk Bekerja Kembali",
        teamMenu_ReturnAssignmentForRework: "Kembali ke Penugasan untuk Bekerja Kembali",
        teamMenu_RemoveSectionAssignment: "Hapus Penugasan Bagian",
        teamMenu_RemoveCellAssignment: "Hapus Penugasan Sel",
        teamMenu_RemoveCompletedAssignments: "Hapus Penugasan yang Telah Diselesaikan",
        teamMenu_AboutThisSection: "Tentang Bagian Ini",
        teamMenu_AboutAssignment: "Tentang Penugasan Ini",

        presentationMenu: "Presentasi",
        presentationMenu_SlideShow: "Mulai Slide Show",
        presentationMenu_SlideShowWithCoview: "Mulai Slide Show yang Dibagi",
        presentationMenu_SlideTransitions: "Terapkan Transisi Slide...",
        presentationMenu_SlideShowFromCurrent: "Mulai dari Slide Saat Ini",
        presentationMenu_EmptyCoviewInvites: "Tidak Ada Peragaan Slide yang Dibagi yang Aktif",
        presentationMenu_CoviewInvites: "Peragaan Slide yang Dibagi yang Aktif",

        dataMenu: "Data",
        dataMenu_Sort: "Urutkan...",
        dataMenu_SortAsc: "Urutkan Naik",
        dataMenu_SortDesc: "Urutkan Turun",
        dataMenu_ACL: "Area yang Dilindungi",
        dataMenu_ACL_DELETE: "Hapus Semua Izin",
        dataMenu_Validity: "Validitas",
        dataMenu_InstantFilter: "Filter Instan",
        dataMenu_Validation: "Validasi...",

        toolsMenu: "Peralatan",
        toolsMenu_AutoComplete: "Entri Sel Otomatis Lengkap",
        toolsMenu_SelectDictionary: "Kamus Pemeriksa Ejaan",
        toolsMenu_Dictionary_ca_CT: "Katala",
        toolsMenu_Dictionary_cs_CZ: "Ceko (Ceko)",
        toolsMenu_Dictionary_da_DK: "Denmark (Denmark)",
        toolsMenu_Dictionary_nl_NL: "Belanda (Belanda)",
        toolsMenu_Dictionary_en_AU: "Inggris (Australia)",
        toolsMenu_Dictionary_en_GB: "Inggris (Inggris Raya)",
        toolsMenu_Dictionary_en_US: "Inggris (Amerika Serikat)",
        toolsMenu_Dictionary_fi_FI: "Finlandia (Finlandia)",
        toolsMenu_Dictionary_fr_FR: "Perancis (Prancis)",
        toolsMenu_Dictionary_fr_CA: "Perancis (Kanada)",
        toolsMenu_Dictionary_de_DE: "Jerman (Jerman)",
        toolsMenu_Dictionary_de_CH: "Jerman (Swiss)",
        toolsMenu_Dictionary_el_GR: "Yunani (Yunani)",
        toolsMenu_Dictionary_it_IT: "Italia (Italia)",
        toolsMenu_Dictionary_pl_PL: "Polandia (Polandia)",
        toolsMenu_Dictionary_pt_BR: "Portugis (Brasil)",
        toolsMenu_Dictionary_pt_PT: "Portugis (Portugis)",
        toolsMenu_Dictionary_ru_RU: "Rusia (Rusia)",
        toolsMenu_Dictionary_es_ES: "Spanyol (Spanyol)",
        toolsMenu_Dictionary_sv_SE: "Swedia (Swedia)",
        toolsMenu_Dictionary_nb_NO: "Norwegia (Bokmål)",
        toolsMenu_Dictionary_nn_NO: "Norwegia (Norwegia Baru)",
        toolsMenu_Dictionary_he_IL: "Ibrani (Israel)",
        toolsMenu_SpellCheck: "Jalankan Ejaan Manual...",
        toolsMenu_Preferences: "Preferensi",
        toolsMenu_Task: "Tugas",
        toolsMenu_Task_Assigntask: "Tetapkan Tugas",
        teamMenu_AssignSlide: "Tetapkan Slide",
        teamMenu_AssignSlides: "Tetapkan Slide",
        teamMenu_EditSlide: "Edit Penugasan Slide",
        teamMenu_ReopenSlideAssignment: "Buka Kembali Penugasan Slide",
        teamMenu_ReopenSlideAssignments: "Buka Kembali Penugasan Slide",
        teamMenu_ReassignSlide: "Tetapkan Kembali Slide",
        teamMenu_ReassignSlides: "Tetapkan Kembali Slide",
        teamMenu_MarkSlidesComplete: "Tandai Slide Selesai",
        teamMenu_MarkSlidesCompletes: "Tandai Slide Selesai",
        teamMenu_ApproveSlide: "Setujui Slide",
        teamMenu_ApproveSlides: "Setujui Slide",
        teamMenu_ReturnForRework: "Kembali ke Slide untuk Bekerja Kembali",
        teamMenu_ReturnForReworks: "Kembali ke Slide untuk Bekerja Kembali",
        teamMenu_RemoveAssignment: "Hapus Penugasan Slide",
        teamMenu_AboutThisSlide: "Tentang Slide Ini",

        addOnsMenu: "Add-on",

        helpMenu: "Bantuan",
        helpMenu_About: "Tentang",
        helpMenu_Overview: "Konten Bantuan",
        helpMenu_NewFeatures: "yang Baru",
        helpMenu_Tour: "Tur Berpemandu",

        accel_fileMenu_Save: "Ctrl+S",
        accel_fileMenu_Save_Mac: "\u2318S",
        accel_fileMenu_Print: "Ctrl+P",
        accel_fileMenu_Print_Mac: "\u2318P",
        accel_editMenu_SelectAll: "Ctrl+A",
        accel_editMenu_SelectAll_Mac: "\u2318A",
        accel_editMenu_Undo: "Ctrl+Z",
        accel_editMenu_Undo_Mac: "\u2318Z",
        accel_editMenu_Redo: "Ctrl+Y",
        accel_editMenu_Redo_Mac: "\u2318Y",
        accel_editMenu_Cut: "Ctrl+X",
        accel_editMenu_Cut_Mac: "\u2318X",
        accel_editMenu_Copy: "Ctrl+C",
        accel_editMenu_Copy_Mac: "\u2318C",
        accel_editMenu_Paste: "Ctrl+V",
        accel_editMenu_Paste_Mac: "\u2318V",
        accel_editMenu_Find: "Ctrl+F",
        accel_editMenu_Find_Mac: "\u2318F",
        accel_insertMenu_Link: "Ctrl+K",
        accel_insertMenu_Link_Mac: "\u2318K",
        accel_insertMenu_Header: "CTRL+SHIFT+H",
        accel_insertMenu_Header_Mac: "\u21e7\u2318H",
        accel_insertMenu_Footer: "CTRL+SHIFT+F",
        accel_insertMenu_Footer_Mac: "\u21e7\u2318F",
        accel_formatMenu_Textprop_Bold: "Ctrl+B",
        accel_formatMenu_Textprop_Bold_Mac: "\u2318B",
        accel_formatMenu_Textprop_Italic: "Ctrl+I",
        accel_formatMenu_Textprop_Italic_Mac: "\u2318I",
        accel_formatMenu_Textprop_FormatPainter: "Ctrl+SHIFT+C, Ctrl+SHIFT+V",
        accel_formatMenu_Textprop_FormatPainter_Mac: "\u21e7\u2318C, \u21e7\u2318V",
        accel_formatMenu_Textprop_Underline: "Ctrl+U",
        accel_formatMenu_Textprop_Underline_Mac: "\u2318U",
        accel_formatMenu_Headingprop_P: "CTRL+SHIFT+0",
        accel_formatMenu_Headingprop_H1: "CTRL+SHIFT+1",
        accel_formatMenu_Headingprop_H2: "CTRL+SHIFT+2",
        accel_formatMenu_Headingprop_H3: "CTRL+SHIFT+3",
        accel_formatMenu_Headingprop_H4: "CTRL+SHIFT+4",
        accel_formatMenu_Headingprop_H5: "CTRL+SHIFT+5",
        accel_formatMenu_Headingprop_H6: "CTRL+SHIFT+6",
        accel_formatMenu_Superscript: "Ctrl+.",
        accel_formatMenu_Superscript_Mac: "\u2318.",
        accel_formatMenu_Subscript: "Ctrl+,",
        accel_formatMenu_Subscript_Mac: "\u2318,",
        accel_formatMenu_Left: "CTRL+SHIFT+L",
        accel_formatMenu_Left_Mac: "\u21e7\u2318L",
        accel_formatMenu_Right: "CTRL+SHIFT+R",
        accel_formatMenu_Right_Mac: "\u21e7\u2318R",
        accel_formatMenu_Center: "CTRL+SHIFT+E",
        accel_formatMenu_Center_Mac: "\u21e7\u2318E",
        accel_formatMenu_Justify: "CTRL+SHIFT+J",
        accel_formatMenu_Justify_Mac: "\u21e7\u2318J",
        accel_formatMenu_Indent: "CTRL+M",
        accel_formatMenu_Indent_Mac: "\u2318M",
        accel_formatMenu_DecreaseIndent: "CTRL+SHIFT+M",
        accel_formatMenu_DecreaseIndent_Mac: "\u21e7\u2318M",
        accel_teamMenu_AddComment: "SHIFT+F2",

        ctxMenuSmartTable: 'Tabel',
        ctxMenuTableProperties: "Properti Tabel",
        ctxMenuDeleteST: 'Hapus',
        ctxMenuDeleteSTTable: 'Hapus Tabel',
        ctxMenuChgSTStyle: 'Ganti Gaya',
        ctxMenuShowCaption: 'Tampilkan Keterangan',
        ctxMenuHideCaption: 'Sembunyikan Keterangan',
        ctxMenuResizeST: 'Ubah Ukuran',
        ctxMenuResizeColumnsST: 'Ubah Ukuran Kolom',
        ctxMenuSTRow: 'Baris',
        ctxMenuAddSTRowAbv: 'Sisipkan Baris Di Atas',
        ctxMenuAddSTRowBlw: 'Sisipkan Baris Di Bawah',
        ctxMenuMoveSTRowUp: 'Pindahkan Baris Ke Atas',
        ctxMenuMoveSTRowDown: 'Pindahkan Baris Ke Bawah',
        ctxMenuDelSTRow: 'Hapus',
        ctxMenuRepeatRow: 'Ulangi Baris Header',
        ctxMenuSTCol: 'Kolom',
        ctxMenuAddSTColBfr: 'Sisipkan Kolom Sebelumnya',
        ctxMenuAddSTColAft: 'Sisipkan Kolom Setelahnya',
        ctxMenuMoveSTColBefore: 'Pindahkan Kolom Sebelumnya',
        ctxMenuMoveSTColAfter: 'Pindahkan Kolom Setelahnya',
        ctxMenuDelSTCol: 'Hapus',
        ctxMenuSortSTColAsc: 'Urutkan Naik',
        ctxMenuSortSTColDesc: 'Urutkan Turun',
        ctxMenuShowAllFacets: 'Tampilkan Kategori',
        ctxMenuHideAllFacets: 'Sembunyikan Kategori',
        ctxMenuSTCell: 'Sel',
        ctxMenuMergeCells: 'Gabungkan Sel',
        ctxMenuMergeDown: 'Gabungkan dengan Sel Di Bawah',
        ctxMenuVerSplit: 'Pisahkan Secara Vertikal',
        ctxMenuHorSplit: 'Pisahkan Secara Horizontal',
        ctxMenuSplitCells: 'Pisahkan Sel...',
        splitCells: 'Pisahkan Sel',
        ctxMenuAlignTextLeft: 'Rata Kiri',
        ctxMenuAlignTextCenter: 'Rata Tengah',
        ctxMenuAlignTextRight: 'Rata Kanan',
        ctxMenuClearSTCellContent: 'Hapus Konten',
        ctxMenuMakeHeaderRow: 'Gunakan Baris yang Dipilih sebagai Header',
        ctxMenuMakeNonHeaderRow: 'Hapus Gaya Header',
        ctxMenuMakeHeaderCol: 'Gunakan Kolom yang Dipilih sebagai Header',
        ctxMenuMakeNonHeaderCol: 'Hapus Gaya Header',
        SHEET_CONTEXT_Hide: "Sembunyikan", // hide row, column or sheet
        SHEET_CONTEXT_Show: "Tunjukkan", // show row, column
        SHEET_CONTEXT_MoveSheet: "Pindahkan...", // move sheet
        SHEET_CONTEXT_InsertSheet: "Sisipkan...", // insert sheet
        SHEET_CONTEXT_DeleteSheet: "Hapus...", // delete sheet	
        SHEET_CONTEXT_DuplicateSheet: "Gandakan...", // duplicate sheet
        SHEET_CONTEXT_RenameSheet: "Ganti Nama..", // rename sheet
	
        ctxMenu_Image_WrapText: "Bungkus Teks",
        ctxMenu_Image_WrapText_Inline: "Di dalam Baris Teks",
        ctxMenu_Image_WrapText_Square: "Persegi",
        ctxMenu_Image_WrapText_TopBottom: "Atas dan Bawah",
        ctxMenu_Image_WrapText_Behind: "Di belakang Teks",
        ctxMenu_Image_WrapText_InFront: "Di depan Teks",
        ctxMenu_Image_WrapText_Other: "Bungkus Teks Lebih Banyak",
        ctxMenu_Image_WrapText_BothSides: "Kedua Sisi",
        ctxMenu_Image_WrapText_LeftOnly: "Hanya Sisi Kiri",
        ctxMenu_Image_WrapText_RightOnly: "Hanya Sisi Kanan",
        ctxMenu_Image_WrapText_LargestOnly: "Hanya yang Paling Besar",

        ctxMenu_Shape_AddText: "Tambah Teks",

        ctxMenu_Range_ACL: "Lindungi Rentang",
        ctxMenu_Sheet_ACL: "Lindungi Lembar",

        ctxMenu_HeaderFooter: "Header / Footer",
        ctxMenu_HeaderFooter_DiffFirst: "Hanya Halaman Pertama",
        ctxMenu_HeaderFooter_DiffOddEven: "Berbeda untuk Halaman Ganjil dan Genap",
        ctxMenu_HeaderFooter_LinkToPre: "Tautkan ke Sebelumnya",

        ctxMenu_copy: "Salin",
        ctxMenu_paste: "Tempel",
        ctxMenu_delete: "Hapus",
        ctxMenu_cut: "Potong",
        ctxMenu_select: "Pilih",
        ctxMenu_properties: "Properti",
        ctxMenu_bringToFront: "Bawa ke Depan",
        ctxMenu_sendToBack: "Kirim ke Belakang",
        ctxMenu_arrange: "Susun",
        ctxMenu_sendBackward: "Kirim Mundur",
        ctxMenu_sendForward: "Kirim Maju",
        ctxMenu_fontStyle: "Gaya Font",
        ctxMenu_selectStyle: "Pilih Gaya",
        ctxMenu_fontSize: "Ukuran Font",
        ctxMenu_fontFamily: "Keluarga Font",
        ctxMenu_bold: "Tebal",
        ctxMenu_italic: "Miring",
        ctxMenu_u: "Garis Bawah",
        ctxMenu_strike: "Coretan",
        ctxMenu_super: "Superskrip",
        ctxMenu_sub: "Subskrip",
        ctxMenu_color: "Warna",
        ctxMenu_bgcolor: "Warna Latar Belakang",
        ctxMenu_highcolor: "Warna Sorotan",
        ctxMenu_restart: "Mulai Ulang Daftar",
        ctxMenu_continue: "Lanjutkan Daftar",
        ctxMenu_separate: "Pisah Daftar",
        ctxMenu_join: "Gabungkan ke Daftar Sebelumnya",
        ctxMenu_setNumberVal: "Atur Nilai Penomoran...",
        webClipboardInfoTitle: "Clipboard",
        webClipboardInfoOKBtn: "OK",
        webClipboardInfoCutMsg: "Pengaturan keamanan pada browser Anda mencegah penyalinan otomatis. Sebagai gantinya, gunakan Ctrl+X pada keyboard Anda.",
        webClipboardInfoCopyMsg: "Pengaturan keamanan pada browser Anda mencegah penyalinan otomatis. Sebagai gantinya, gunakan Ctrl+C pada keyboard Anda.",
        webClipboardInfoPasteMsg: "Pengaturan keamanan pada browser Anda mencegah editor ini mengakses data clipboard Anda. Sebagai gantinya, gunakan Ctrl+V pada keyboard Anda.",

        clearTrackChangeConfirmMsg: "Semua pengodean warna yang menandai perubahan-perubahan dalam dokumen ini akan dihapus secara permanen. Apakah Anda ingin melanjutkan?"
});

