({
	delete_general: "Odstranit",
	order: "Pořadí",
	align_text: "Zarovnat text",
	align_slide: "Zarovnat v rámci snímku",
	align_objects: "Zarovnat vybrané objekty",
	zoom: "Přiblížit/oddálit",
	zoom_fit: "Přizpůsobit oknu",
	insert_link: "Vložit odkaz",
	add_link: "Přidat odkaz",
	open_link: "Otevřít odkaz",
	edit_link: "Upravit odkaz",
	remove_link: "Odebrat odkaz",
	insert_link_menu: "Odkaz",
	invalid_url: "Adresu URL nelze otevřít. Ověřte správnost adresy URL a zkontrolujte, zda v nastaveních prohlížeče není blokováno otevírání rozevíracích oken. ",
	dnd_canceled_on_slide_event: "Snímek nelze přesunout, protože prezentaci nedávno upravil jiný editor. Zkuste to později.",
	rotate: "Otočit",
	flipX: "Překlopit vodorovně",
	flipY: "Překlopit svisle",
	rotate_right: "Otočit ve směru hodinových ručiček o 90&#x00B0",
	rotate_left: "Otočit proti směru hodinových ručiček o 90&#x00B0",
	color_set_fill: "Nastavit barvu výplně",
	color_nofill: "Bez výplně",
	color_nobackground: "Žádné pozadí",
	color_auto: "Automaticky",
	color_default: "Výchozí",
	color_transparent: "Průhledné",
	
	objects_distribute: "Rozdělit",
	objects_distribute_v: "Svisle",
	objects_distribute_h: "Vodorovně",
	
	link_subject: "Předmět:",
	link_text: "Text pro zobrazení:",
	link_mailto: "Otevřít e-mail",
	link_goto: "Otevřít odkaz",
	link_done: "Hotovo",
	link_remove: "Odebrat",
	link_website: "Web",
	link_email: "E-mail",
	link_slide: "Snímek",
	link_slide_placeholder: "Vyberte nebo zadejte číslo.",
	link_slide_placeholder_deleted: "Propojený snímek byl odstraněn",
	link_slide_next: "Následující snímek",
	link_slide_prev: "Předchozí snímek",
	link_slide_first: "První snímek",
	link_slide_last: "Poslední snímek",
	link_slide_number: "Snímek ${0}",
	link_not_support: "Nepodporovaný typ odkazu",
	link_acc_input: "Vstupní adresa odkazu",
	link_acc_mail_input: "Vstupní poštovní adresa",
	

	// Jaws Support
	acc_blank: "prázdné",// when selection is nothing but space char and empty paragraph
	acc_selected: " vybrané",
	acc_showed: " zobrazené",
	acc_inTable: " v tabulce na řádku ${0} ve sloupci ${1} ",
	acc_titleSelected: "byl vybrán nadpis",
	acc_subtitleSelected: "byl vybrán podnadpis",
	acc_outlineSelected: "byla vybrána osnova",
	acc_notesSelected: "byly vybrány poznámky přednášejícího",
	acc_imageSelected: "vybraná grafika",
	acc_shapeSelected: "vybraný tvar",
	acc_rotated: " otočeno o ${0} stupňů",
	acc_tableSelected: "byla vybrána tabulka",
	acc_textboxSelected: "vybrané textové pole",
	acc_enterEdit: " klávesou Enter zahájíte úpravy",
	acc_locked_by: " tato položka je uzamknuta uživatelem ${0}",
	acc_slide_used_by: " tato položka je používána uživatelem ${0}",
	ACC_TABLE_TABLESIZE: "Vybrali jste ${0} řádků, ${1} sloupců",
	ACC_TABLE_MAXSIZE: " Maximální podporovaná velikost tabulky je 8*8.",
	ACC_EditorMode: "režim úprav editoru",
	ACC_EndEditorMode: "ukončení režimu úprav editoru",
	ACC_Table_new_row: "Byl přidán nový řádek",
	ACC_Table_new_column: "Byl přidán nový sloupec",
	Acc_column: "sloupec  ${0}",
	acc_slide: "snímek ${0}",
	acc_editor: "Upravil: ${0}",
	Plain: "Prostý styl",
	BlueStyle: "Modrý styl",
	RedTint: "Červený odstín",
	BlueHeader: "Modré záhlaví",
	DarkGrayHF: "Tmavě šedé záhlaví/zápatí",
	LightGrayRows: "Světle šedé řádky",
	DarkGrayRows: "Tmavě šedé řádky",
	BlueTint: "Modrý odstín",
	RedHeader: "Červené záhlaví",
	GreenHF: "Zelené záhlaví/zápatí",
	PlainRows: "Prosté řádky",
	GrayTint: "Šedý odstín",
	GreenTint: "Zelený odstín",
	GreenHeader: "Zelené záhlaví",
	RedHF: "Červené záhlaví/zápatí",
	GreenStyle: "Zelený styl",
	PurpleTint: "Nachový odstín",
	BlackHeader: "Černé záhlaví",
	PurpleHeader: "Nachové záhlaví",
	LightBlueHF: "Světle modré záhlaví/zápatí",
	
    formatMenu_LineSpacing: "Řádkování",
	linespaceboxTitle:"Vlastní mezery",
	linespacelineTitle:"Řádek:",
	linespacenoticeContent :"Řádkování",
    formatMenu_LineSpacing_Customize: "Vlastní...",
    formatMenu_LineSpacing_CustomValue:"Vlastní: ${0}",
    lineSpaceWarning:"Zadejte číslo v rozmezí 0 až 10.",
    
    set_transparency_menu: "Neprůhlednost obrázku",
    opacity_percent_value: "${0}%",
    opacity_title: "Neprůhlednost",
    
    increaseLineWidthTip: "Zvýšit tloušťku čáry",
	decreaseLineWidthTip : "Snížit tloušťku čáry",
    setBorderStyleTip:"Nastavit styl čáry",
    line_width_title: "Tloušťka čáry",
    line_end_title: "Koncové body čáry",
    line_dash_title: "Vzorek čáry",
    line_dash_type1: "Plná",
    line_dash_type2: "Čtverečky",
    line_dash_type3: "Čárky",
    line_dash_type4: "Tečky",
    line_dash_type5: "Čárky a tečky",
    line_dash_type6: "Dlouhé čárky",
    line_endpoints_type1: "Žádná položka",
    line_endpoints_type2: "Jednoduchá šipka doprava",
	line_endpoints_type3: "Jednoduchá šipka doleva",
	line_endpoints_type4: "Jednoduchá dvojitá šipka",
	line_endpoints_type5: "Šipka doprava s výplní",
	line_endpoints_type6: "Šipka doleva s výplní",
    line_endpoints_type7: "Dvojitá šipka s výplní",
    line_endpoints_type8: "Kroužek a šipka s výplní",
	line_endpoints_type9: "Kosočtverec a šipka s výplní",
	line_endpoints_type10: "Vyplněné kosočtverce",
    line_endpoints_type11: "Vyplněné kroužky"
})

